### ISSUE TITLE
Add new format struct stuff to --list=format-[all-]details/methods

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1004]
- [x] Add plaintext_min_length output
- [x] For salt_compare I guess the output should be something like yes/no
- [x] Ensure we list FMT_MAIN_VERSION in --list=build-info

**Comment by magnumripper** [comment]
https://github.com/magnumripper/JohnTheRipper/issues/996#issuecomment-68641578:
> Do we put the output of the min. length next to the max length output in llist=format-(all-)details, or do we put it close to the end, to reduce the risk of breaking some scripts users might have created?

Good question. I have no indications anyone uses --list in a way that would break - but I still think we should add it to the end.

**Comment by frank-dittrich** [comment]
Before or after the (possibly truncated) ciphertext example?
Both could break existing scripts.
But I think most people who are interested in test hashes would use --list=format-tests instead of --list=format-(all-)details.

**Comment by magnumripper** [comment]
The test vectors need to stay last row/column forever considering the potential length of a ciphertext.

**Comment by magnumripper** [comment]
Hmm it would really look nicer to put it before max length... I think I might actually go with that. Hey, do we have any --list command that shows you FMT_MAIN_VERSION? We should!

**Comment by frank-dittrich** [comment]
--list=build-info should show the format version.

**Comment by magnumripper** [comment]
I'll fix it if it doesn't.

**Comment by magnumripper** [comment]
I decided to play nice and add min-len as second last column.
