### ISSUE TITLE
Should -list=build info show asan support / memdbg /DEBUG

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1005]
I htink it would be a good idea if --list=build-info would print an information if asan and/or memdbg  (and may be DEBUG) are enabled, but not if they are disabled (don't give users the idea their build is missing something...)

Of course, only for autoconf builds, not for legacy builds.

**Comment by magnumripper** [comment]
debug and memdbg are listed already. Is there a macro for knowing about ASAN?

**Comment by kholia** [comment]
@magnumripper ``misc.h`` has something like,

```
#if /* is ASAN enabled? */ \
    __has_feature(address_sanitizer) /* Clang */ || \
    defined(__SANITIZE_ADDRESS__)  /* GCC 4.8.x */
  #define ATTRIBUTE_NO_ADDRESS_SAFETY_ANALYSIS \
        __attribute__((no_address_safety_analysis)) \
        __attribute__((noinline))
#else
  #define ATTRIBUTE_NO_ADDRESS_SAFETY_ANALYSIS
#endif
```

Hopefully this will help.

**Comment by jfoug** [comment]
1aba8f5
