### ISSUE TITLE
Implement PRINCE mode

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1011]
Atom released princeprocessor under a MIT license so we can base a mode on his code if we want to.

https://github.com/jsteube/princeprocessor

**Comment by magnumripper** [comment]
What would be *really* cool though, is implementing it on GPU. I assume Atom will do so (if at all applicable). Just load stuff to GPU memory once, and after that almost no PCI transfers.

**Comment by magnumripper** [comment]
http://www.openwall.com/lists/john-dev/2015/01/09/1

**Comment by magnumripper** [comment]
This is easy. 1st version working soon.

**Comment by magnumripper** [comment]
To do:
- [ ] Fix external mode filter
- [ ] Fix session save/restore
- [ ] Fix ETA/Progress
- [ ] Fix node/fork/MPI support

**Comment by frank-dittrich** [comment]
> Rough 1st version committed.

Where is that commit?

**Comment by magnumripper** [comment]
I dropped the topic branch now and pushed to main branch. This code is so separated it won't do any harm to anything else.

**Comment by magnumripper** [comment]
Session resume implemented, but may need tweaks.

**Comment by magnumripper** [comment]
I think this is pretty usable now. For specific bugs found, please open new issues.
