### ISSUE TITLE
Should we really always report DONE?

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1015]
Before 855c636 we had this (in PRINCE mode) when everything was cracked after processing 4.47% of the keyspace;

```
Loaded 5000000 password hashes with no different salts (NT [MD4 128/128 X2 SSE2-16])
Press 'q' or Ctrl-C to abort, almost any other key for status
5000000g 0:00:00:11 4.47% (ETA: 14:28:34) 440528g/s 440528p/s 440528c/s 1136GC/s 0511581..1811581
Session completed
```

After 855c636 we do like all other modes:

```
Loaded 5000000 password hashes with no different salts (NT [MD4 128/128 X2 SSE2-16])
Press 'q' or Ctrl-C to abort, almost any other key for status
5000000g 0:00:00:11 DONE (2015-01-11 14:26) 434027g/s 434027p/s 434027c/s 1136GC/s 0511581..1811581
Session completed
```

But is this really a good idea? We lose the information about how much of the keyspace was actually searched.

**Comment by magnumripper** [comment]
Core John reports it like this. It does not have ETA/Progress.
```
5000000g 0:00:00:49 100725g/s 3042Kp/s 3042Kc/s 3360GC/s 73673837..121224145566
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

In Jumbo we probably still want to mute the ETA so it would look something like this:
```
Loaded 5000000 password hashes with no different salts (NT [MD4 128/128 X2 SSE2-16])
Press 'q' or Ctrl-C to abort, almost any other key for status
5000000g 0:00:00:11 4.47% (2015-01-11 14:26) 440528g/s 440528p/s 440528c/s 1136GC/s 0511581..1811581
Session completed
```
Just like when printing DONE, the time in parens is "now" and not the original ETA.

**Comment by jfoug** [comment]
Would it make sense to output a statistical update in the complete line?  Normally we have an ETA format. Would it not make sense to simply leave that line alone (the last update listed), and simply output a complete new line. There is no ETA (we are done). BUT there may be things in there we want to list, such as "4.7% of keyspace checked".  That IS good information, to know.  It is just as valuable as being told that 100% of the keyspace was completed, anf 38.4% of the passwords were cracked.  Same type info, listing what was used/done during the test.

**Comment by magnumripper** [comment]
This issue is too old to bother with. I'm not sure it's an issue anymore and if it is, someone can open a new one.
