### ISSUE TITLE
Add CRAM-MD5 support to existing HMAC-MD5 format

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1018]
Hashcat has them as
```
$cram_md5$PG5vLXJlcGx5QGhhc2hjYXQubmV0Pg==$dXNlciA0NGVhZmQyMmZlNzY2NzBmNmIyODc5MDgxYTdmNWY3MQ==
```

- [x] Add a prepare() that converts the above (trivial, described in doc/CRAM-MD5.txt) to our canonical HMAC-MD5 format.
- [x] Add the above as a test vector. Plaintext is supposedly "hashcat".
- [x] Update doc/CRAM-MD5.txt

**Comment by magnumripper** [comment]
@jfoug that was easy, using your Base64 helpers!

**Comment by kholia** [comment]
Awesome :+1: 

Pasting the whole email in ``doc/CRAM-MD5.txt`` was bothering me for a while.
