### ISSUE TITLE
PRINCE bash completion for wordlist filename fails.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1020]
See also #543.

We now have
```
--prince[=FILE]           PRINCE mode, read words from FILE
--prince-elem-cnt-min=N   PRINCE, minimum number of elements per chain
--prince-elem-cnt-max=N   PRINCE, maximum number of elements per chain
--prince-wl-dist-len      PRINCE, calculate length distribution from wordlist
```
All of them works as expected with bash completion, except one case: Wordlist filename, eg. 
`--prince=[TAB][TAB]` or `--prince=rockyou[TAB][TAB]`.

**Comment by frank-dittrich** [comment]
No, this didn't help.

The reason is one we already know.
There are multiple options begining with `--prince`.

I have to think about how to resolve this.

**Comment by frank-dittrich** [comment]
Renaming `--prince=` into some other name starting with `--prince-` would resolve this issue.

**Comment by magnumripper** [comment]
I really don't want to rename the options. They are very logical and fully supported by John. I'm sure there's an easy fix... once found. I'll look into it later.

**Comment by frank-dittrich** [comment]
Then we need to enhance the general logic. If options exist that start with the exact name, then assume that this option is meant if the name is still ambiguous.
We could also prefer ambiouous core options / optons listed on the usage screen over hidden options.
We just need to update the documentation as well.

BTW, --prince plus --prince-something is not *fully* supported:
```
(bleeding-jumbo)run $ ./john --princ=password.lst --stdout
Unknown option: "--princ=password.lst"
(bleeding-jumbo)run $ ./john --prin=password.lst --stdout
Unknown option: "--prin=password.lst"
(bleeding-jumbo)run $ ./john --pri=password.lst --stdout 
Unknown option: "--pri=password.lst"
```

**Comment by magnumripper** [comment]
> BTW, --prince plus --prince-something is not fully supported:

Yes it is fully supported. Your examples are ambigous, so it fails. Just like
```
$ ../run/john -in=utf8
Unknown option: "-in=utf8"
```
That is the exact same behavior.

**Comment by magnumripper** [comment]
I fixed it with a prince-specific hack, but it should be totally doable to make it generic.
