### ISSUE TITLE
"keepass" format is totally broken due to "inlining" stuff

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1023]
Are these "inlining" limits recent? They totally break the "keepass" format and I am not interested in working around them.

Feel feel to grab this ticket.

**Comment by magnumripper** [comment]
I did not get what you meant - but now I realize it's about the inlined data in the non-hash? Just over-ride it with `keepass2john -i 195000`. How do they break the format?

**Comment by kholia** [comment]
```
$ ../run/keepass2john -i 195000 example.kdb
../run/keepass2john error: threshold 195000, can't be larger than 98048

# example.kdb is 88204 bytes in size
```

**Comment by kholia** [comment]
I have pushed commit 8d9a5651b4fa25c81b3890d6cc87606fd71b3b29 which tells the user, why the hash was rejected.

**Comment by magnumripper** [comment]
Good. I'm closing this and opening one for the actual issue.
