### ISSUE TITLE
Keepass format is supposed to handle non-inlined data, but does not

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1026]
See #1023.

**Comment by magnumripper** [comment]
keepass2john now defaults to max inline threshold (98048 bytes for a LINE_BUFFER_SIZE of 0x30000, see 05628387) but once someone has a safe larger than that, we *need* inlining. We can't just bump LINE_BUFFER_SIZE to silly figures.

**Comment by kholia** [comment]
Data is now always inlined. See commit 0ed240a2bedd75aa161ef9065e2766a389b2f0a4.
