### ISSUE TITLE
gcc false warning in pp.c

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1029]
Using gcc 4.9.2
```
In file included from pp.c:64:0:
pp.c: In function 'do_prince_crack':
pp.c:1256:33: warning: array subscript is above array bounds [-Warray-bounds]
       mpz_init_set_si (pw_ks_pos[pw_len], 0);
                                 ^
mpz_int128.h:51:28: note: in definition of macro 'mpz_init_set'
 #define mpz_init_set(x, y) x = y
                            ^
pp.c:1256:7: note: in expansion of macro 'mpz_init_set_si'
       mpz_init_set_si (pw_ks_pos[pw_len], 0);
       ^
```
This only happens with -O2 and only when not using GMP for PRINCE. This is 100% a red herring. Maybe this is the same compiler bug that produces the false DES warning we saw for years (#276):
```
DES_std.c: In function 'DES_std_set_key':
DES_std.c:639:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;
                 ^
```

**Comment by magnumripper** [comment]
Wow, this actually turned out to be a real bug (although not normally triggered). And it's fixed now.

**Comment by jfoug** [comment]
What was the fix?  I see no commit

**Comment by magnumripper** [comment]
It came and went a couple of time until I realized it. Finally settled in c4db2e81, it was the definitions of pw_ks_pos and pw_ks_cnt. Only a problem if you tried an output length beyond 32, which was never properly supported anyway so is now disallowed...
