### ISSUE TITLE
Audit salted hashes not dupe salt removing.  (started with lastpass, and cracked[] hashes)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1031]
I have moved this to the top post. It is a list of hashes that salt dupe is not working. It MAY be that some of these simply do not have dupe salts (many encryption based quasi-hashes will not). But others have busted salt dupe remove logic. I will put them all here, with checkboxes, when I find them (using the tester script in one of the lower posts).

- [ ] o5logon probably can not be salt duped
- [ ] o5logon:   Loaded 15 password hashes with 15 different salts (o5logon, Oracle O5LOGON protocol [SHA1 AES 32/64 AES-NI])
- [ ] truecrype can not salt dupe
- [ ] tc_ripemd160: Loaded 15 password hashes with 15 different salts (tc_ripemd160, TrueCrypt RIPEMD160 AES256_XTS [32/64])
- [ ] tc_sha512: Loaded 15 password hashes with 15 different salts (tc_sha512, TrueCrypt SHA512 AES256_XTS [128/128 SSE4.1 2x])
- [ ] tc_whirlpool: Loaded 15 password hashes with 15 different salts (tc_whirlpool, TrueCrypt WHIRLPOOL AES256_XTS [64/64])
- [ ] zip:  (still to test. Not sure how to get same salts).
- [ ] Pretty sure rar was 'right', and is not removing dupes.
- [ ] rar:        Loaded 15 password hashes with 15 different salts (rar, RAR3 [SHA1 AES 32/64])
- [ ] keychain Loaded 15 password hashes with 15 different salts (keychain, Mac OS X Keychain [PBKDF2-SHA1 3DES 8x SSE2])  (I think no salt dupes.  Looks like decryption only)
- [ ] krb5pa_md5

This is a complete set, from pass_gen.pl as it stands. This is ALL of them, with exception of dynamic, which should properly reduce salts.

I believe that all of these can not do dupe salt removal.  Most need encryption or some other thing done, that keeps salts random.

This one does not show up in the salt find logic. BUT it failes.  Found with TS.  the lp format (lastpass) works fine.  LP-sniffed, not so much.  It is due to design.

The salt contains the encrypted_user name.  That should NOT be there. This should be a normal 'binary' type, and not a cracked[] array type. If it was binary, we could remove that encr user name from the salt array, and then properly only have the salt (which is the user name in clear text).

We need to look at other cracked[] method formats, and make sure that they are NOT hiding this type latent bug. It suck, because things work, so auto type testing appears to not spot it. It is found by having multiple inputs that 'should' have same salt, BUT the format does not see them.  On the run I was working on for the TS, I should have had 1500 hashes with 10 salts (150 passwords for each salt). What I got was 1500 hashes 1500 salts.

**Comment by jfoug** [comment]
I am going to check in the TS and we can see this, prior to getting this format fix. I am off to a gun show, so will not be able to get to the format for half a day or so.

This shows the current 'broken' format.
```
$ ../run/john lastpass_tst.in -w=pw.dic
Warning: check for duplicates partially bypassed to speedup loading
Loaded 1500 password hashes with 1500 different salts (LastPass, sniffed sessions [PBKDF2-SHA256 AES 128/128 XOP 4x])
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
Skipping and*    (u0-lp_sniffed)
password__3      (u148-lp_sniffed)
good to KN0W__2  (u147-lp_sniffed)
characters__2    (u146-lp_sniffed)
bartlby__2       (u145-lp_sniffed)
develsdue__2     (u144-lp_sniffed)
fukOFF__2        (u143-lp_sniffed)
DOGBERT__2       (u142-lp_sniffed)
IwasJu$there__2  (u141-lp_sniffed)
enterNow__2      (u140-lp_sniffed)
hhello__2        (u139-lp_sniffed)
outleft__2       (u138-lp_sniffed)
```

**Comment by jfoug** [comment]
Ok, i now have this:

```
$ ../run/john lastpass_tst.in -w=pw.dic
Loaded 1500 password hashes with 10 different salts (LastPass, sniffed sessions [PBKDF2-SHA256 AES 128/128 XOP 4x])
Remaining 1366 password hashes with 10 different salts
Warning: no OpenMP support for this hash type
Press 'q' or Ctrl-C to abort, almost any other key for status
Skipping and*    (u0-lp_sniffed)
Bert$ErnIE       (u1-lp_sniffed)
Skipping and*    (u0-lp_sniffed)
Bert$ErnIE       (u1-lp_sniffed)
```

BUT I get self test failure if built with OMP, so I can not check it in. I am not sure why.

I had to change the decrypt of the 'encrypted' data into an encrypt of the salt (user name).  The binary is simply the first 16 bytes of the encrypted data stored on the hash line.  Then I encrypt the user name and let john do the comparisons.

I just have to get OMP working.  Right now, I undef _OPENMP and have removed FMT_OMP from flags, and it runs just fine (both SIMD and nonSIMD). But I get this failure if I run OMP:

```
$ ../run/john -test=5 -form=lastpass
Will run 4 OpenMP threads
Benchmarking: LastPass, sniffed sessions [PBKDF2-SHA256 AES 128/128 XOP 4x]... (4xOMP) FAILED (get_hash[0](4))
```

**Comment by kholia** [comment]
@jfoug You can always push work-in-progress code to a different branch (in case you haven't done so already). This way, other folks can lend a hand :-)

**Comment by jfoug** [comment]
The problem was simple and stupid (almost always was).  I copy 16 bytes of crypt from a large enough out buffer (32 bytes), to the crypt_out item inside a loop. Well, I was doing ```memcpy(crypt_key[i], out, 16);``` when I should have been doing ```memcpy(crypt_key[index+i], out, 16);```   So when building under OMP mode, and we had OMP_SCALE of 64, all items would be going into the first set of crypt_key values (1 or 4, depending upon SIMD).  Dumb error, but sort of hard for me to spot.

**Comment by jfoug** [comment]
I am leaving this issue open.  There may be other formats that have this same problem.

The easiest way to spot, is to generate a file with pass_gen.pl, setting a known 'fixed' salt, and 10 passwords. Then run the file.  If more than 1 salt is observed, then start to research.  It could be that there really were more than 1 salt created in the input file (i.e. pass_gen can't do dupe salts, OR there are more items that make up the complex salt).  The other issue is the design of the format may be wrong, like this one was.  These are not the easiest to spot, but we do need to spot them.

I think there was another one I recently did on my JTRTS work, that may have a similar problem.  It was one where there were 3 or 4 formats almost the same, but one of them got slow.  I will have to dig back in recent work, and see if it is something similar.

**Comment by jfoug** [comment]
I wonder if this could also be some sign where we have many-salts test speed being slower than 1 salt.  That may be another symptom, I have to look at that.  I think we have a few formats like that.

**Comment by jfoug** [comment]
I got office_2007 changed.  I still need to figure out how to do office_2010 and 2013. Right now, the CPU format is a hybrid binary/cracked.  Only the 2007 uses binary.

This changes the TS input.  I generated the files incorrectly (what are in the TS now).  But I do have new ones, that are 10 salts of 150 passwords.  With the changes to O2007, it cracks the 1500 in 6s.  Before it was 7:05  (425s).

Now, I am not 100% sure this is going to make that much difference in working with ITW hashes, since these are a generated IV. But it does make building input files for the TS to be much nicer, to get these slow formats to use fewer salts and run in an acceptable manner.

**Comment by jfoug** [comment]
Ok, I am now working with a tiny script, that should ferret out these things pretty quickly.  I found what I think is a problem already, and likely it goes back to core (md5crypt).

The script simply makes an input file of the right format, using an input dictionary of garbage lines, and it makes it with 3 fixed salts.  The code in the script must be tweaked properly to give the right size salt prior to executing it. Then the script makes a 3 salt file, with 15 lines, and runs jtr.  It only captures the 'Loaded' line, which lists the # of hashes, and # of salts.  I set a max run time of 1s, so it exists instantly.   Seems to work.  I am just walking down pass_gen.pl, looking at formats now,  I also put a comment into the script once I run it, so that I know a salted format has passed (or failed).

Here is the trivial script.  I am running it in test directory.

```
#!/bin/sh

# BUSTED!!!!
# md5crypt: Loaded 15 password hashes with 15 different salts (md5crypt, crypt(3) $1$ [MD5 128/128 XOP 8x])

./run/pass_gen.pl -salt xxxxxxxx -count 5 $1 < rnd.dic > tst.in 2>/dev/null
./run/pass_gen.pl -salt yyyyxxxx -count 5 $1 < rnd.dic >> tst.in 2>/dev/null
./run/pass_gen.pl -salt zzzzxxxx -count 5 $1 < rnd.dic >> tst.in 2>/dev/null
if [ x$2 != x ] ; then ../run/john -form=$2 -w=rnd.dic tst.in --max-run-time=1 2> /dev/null | grep Loaded ;
else ../run/john -form=$1 -w=rnd.dic tst.in --max-run-time=1 2> /dev/null | grep Loaded
fi

# descrypt:  Loaded 15 password hashes with 3 different salts (descrypt, traditional crypt(3) [DES 128/128 XOP-16])
# bigcrypt:  Loaded 30 password hashes with 18 different salts (descrypt, traditional crypt(3) [DES 128/128 XOP-16])
# bsdicrypt: Loaded 15 password hashes with 3 different salts (bsdicrypt, BSDI crypt(3) [DES 128/128 XOP-16])

```

**Comment by jfoug** [comment]
Here is the hashes with properly working salt-dupe (as found by the script above).  I will continue to update this post.

```
# descrypt:      Loaded 15 password hashes with 3 different salts (descrypt, traditional crypt(3) [DES 128/128 XOP-16])
# bsdicrypt:     Loaded 15 password hashes with 3 different salts (bsdicrypt, BSDI crypt(3) [DES 128/128 XOP-16])
# bcrypt:        Loaded 15 password hashes with 3 different salts (bcrypt [Blowfish 32/64 X3])
# bcryptx:       Loaded 15 password hashes with 3 different salts (bcrypt [Blowfish 32/64 X3])
# cisco8:        Loaded 15 password hashes with 3 different salts (PBKDF2-HMAC-SHA256 [PBKDF2-SHA256 128/128 XOP 4x])
# dragonfly3-32: Loaded 15 password hashes with 3 different salts (dragonfly3-32, DragonFly BSD $3$ w/ bug, 32-bit [SHA256 32/64 OpenSSL])
# dragonfly4-32: Loaded 15 password hashes with 3 different salts (dragonfly4-32, DragonFly BSD $4$ w/ bugs, 32-bit [SHA512 64/64 OpenSSL])
# dragonfly4-64: Loaded 15 password hashes with 3 different salts (dragonfly4-64, DragonFly BSD $4$ w/ bugs, 64-bit [SHA512 64/64 OpenSSL])
# dragonfly3-64: Loaded 15 password hashes with 3 different salts (dragonfly3-64, DragonFly BSD $3$ w/ bug, 64-bit [SHA256 32/64 OpenSSL])
# mscash:        Loaded 15 password hashes with 3 different salts (mscash, MS Cache Hash (DCC) [MD4 32/64])
# krb5-18:       Loaded 15 password hashes with 3 different salts (krb5-18, Kerberos 5 db etype 18 aes256-cts-hmac-sha1-96 [128/128 XOP 8x])
# lp:            Loaded 15 password hashes with 3 different salts (lp, LastPass offline [PBKDF2-SHA256 128/128 XOP 4x])
# lastpass:      Loaded 15 password hashes with 3 different salts (LastPass, sniffed sessions [PBKDF2-SHA256 AES 128/128 XOP 4x])
# odf:           Loaded 15 password hashes with 3 different salts (ODF [SHA1 BF / SHA256 AES 8x SSE2])
# odf-1:         Loaded 15 password hashes with 3 different salts (ODF [SHA1 BF / SHA256 AES 8x SSE2])
# office2007:    Loaded 15 password hashes with 3 different salts (Office, 2007/2010 (SHA-1) / 2013 (SHA-512), with AES [32/64 OpenSSL])
# mongodb:       Loaded 15 password hashes with 3 different salts (MongoDB, system / network [MD5 32/64])
# mysqlna:       Loaded 15 password hashes with 3 different salts (mysqlna, MySQL Network Authentication [SHA1 32/64])
# postgres:      Loaded 15 password hashes with 3 different salts (postgres, PostgreSQL C/R [MD5 32/64])
# postgres:(usr) Loaded 15 password hashes with 3 different salts (postgres, PostgreSQL C/R [MD5 32/64])
# siemens-s7:    Loaded 15 password hashes with 3 different salts (Siemens-S7 [HMAC-SHA1 32/64])
# ssha512:       Loaded 15 password hashes with 3 different salts (SSHA512, LDAP [32/64 OpenSSL])
# tcp-md5:       Loaded 15 password hashes with 3 different salts (tcp-md5, TCP MD5 Signatures, BGP [MD5 32/64])
# known_hosts:   Loaded 15 password hashes with 3 different salts (known_hosts, HashKnownHosts HMAC-SHA1 [SHA1 32/64])
# rsvp:          Loaded 15 password hashes with 3 different salts (rsvp, HMAC-MD5 / HMAC-SHA1, RSVP, IS-IS [MD5 32/64])
# saph:          Loaded 15 password hashes with 3 different salts (saph, SAP CODVN H (PWDSALTEDHASH) [SHA-1/256/384/512])
# bb-es10:       Loaded 15 password hashes with 3 different salts (blackberry-es10 [101x SHA-512])
# citrix-ns10:   Loaded 15 password hashes with 3 different salts (Citrix_NS10, Netscaler 10 [SHA1 128/128 AVX 8x])
# chap:          Loaded 15 password hashes with 3 different salts (chap, iSCSI CHAP authentication [MD5 32/64])
# fortigate:     Loaded 15 password hashes with 3 different salts (Fortigate, FortiOS [SHA1 128/128 AVX 8x])

```

**Comment by magnumripper** [comment]
What exactly did you test? RAR has a salt (an actual salt) as **part** of what WE consider a salt in the format (which is really not a salt but a non-hash). There's no other way to do it afaik, it's just like WPAPSK (we could sort salts just like WPAPSK but there's no much point in doing so).

So it does not detect a dupe actual salt but it does detect a dupe non-hash. Or isn't it?

**Comment by jfoug** [comment]
The rar 'logic' I have in pass_gen does not use any rar logic. It uses the actual 'encryption' logic, without care or concern for the data.  We use rar2john to pull certain things from the file, and then perform certain hash work on them.  What I have done is to reverse that logic, and make code that produces 'valid' data (as far as john is concerned) rar data, which can be processed properly by john.

It may be that rar is correct.  It may be that there is someting in the salt that should not be there (thus there never will be a constant salt). It is hard to say. What I did over teh last couple hours was to use a script that I did some simple edits on, and running it against pass_gen., then against john.  

The list at the top of this issue is just that, a place to start looking.  MOST of the hashes can not be dupe salted any way. They are decryption of data, so that encrypted data IS within the salt, and there is no way to use any salt combining logic at all.  It may end up that rar fits that type hash in the end.  I was very hopeful that we could find dupe salts, where same salt with different passwords could be put to work.   But the 'ease' of getting that done, and the usefulness of it (is it just theoretical that there are dupes, and ITW we would never see them).  Those we can simply ignore, once analyzed and determined.

But things like wpapsk, that is NOT theoretical.  If the SSID is the salt, and we can reduce them based on that, then we should.

**Comment by magnumripper** [comment]
Here's a simple test (unless I'm confused... I'm very tired): Any format in your list that has a BINARY_SIZE of 0 is a "non-hash". So they simply can't have dupe salts (except dupe complete ciphertexts, which we of course should ensure are detected as dupes but that's not the scope of this if I read you right) and should probably be checked or deleteted from the list.

**Comment by jfoug** [comment]
That logic is not right. You  have to look at the format. 

I just did SKEY. It had 0 byte length. The binary was simply put into the salt, vs being a proper binary.


That is also what most of the 'cracked[]' model hashes do. They put the binary into the salt. SOME of them actually are valid doing this.  Something where you get an encrypted blob, some salt stuff, etc, and decrypt the buffer, and compare to something, well, there is NO way to dupe salt remove that.  BUT if the format was simply built using the 'do not create a binary' model of format, but it really is something that should be a binary() type format, then the testing done is finding them.

NOTE, just because the hash is for some object, does NOT mean that there is no salt-dupe removal possible.  I was able to dupe-salt office-2007.  However, I think it is not possible for 2010 or 2013.

Of the hashes in the first post of this thread, there will likely only be a handful that really 'do' have ability to dupe-salt.     One really nice thing, EVEN if the dupe salt is only in theory, is that we can make really fast jtr-ts input files, that are just as valid as one with 1000's of unique salts.  But that can ONLY be done if the format can do dupe removal, AND has properly been coded to do just that  (i.e. the salt is ONLY the salt)

**Comment by magnumripper** [comment]
> I got office_2007 changed. I still need to figure out how to do office_2010 and 2013. Right now, the CPU format is a hybrid binary/cracked. Only the 2007 uses binary.

The above is about TS, right?

> I was able to dupe-salt office-2007. However, I think it is not possible for 2010 or 2013.

Is this committed? Where?

**Comment by jfoug** [comment]
It is not yet committed.

I think the only thing it will help, is the TS. I doubt this would happen ITW, but who knows how 'correct' the salt logic is for MS.

**Comment by jfoug** [comment]
Closing.  I believe that the other hashes not properly salt-dupe removing are all formats which can not be salt duped.
