### ISSUE TITLE
1.8.0-jumbo-1 self-test failures with mips64

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1032]
From Solar:
```
Benchmarking: scrypt (16384, 8, 1) [Salsa20/8 32/64]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: dynamic_17 [phpass ($P$ or $H$) 32/64 48x2  (MD5_body)]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: cloudkeychain, 1Password Cloud Keychain [PBKDF2-SHA512 32/64]... (2xOMP) FAILED (cmp_all(1))

Benchmarking: django-scrypt [Salsa20/8 32/64]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: EFS [PBKDF2-SHA1-efs-variant 3DES 32/64]... (2xOMP) FAILED (cmp_all(1))

Benchmarking: HMAC-SHA384 [password is key, SHA384 64/64 OpenSSL]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: HMAC-SHA512 [password is key, SHA512 64/64 OpenSSL]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: krb5-18, Kerberos 5 db etype 18 aes256-cts-hmac-sha1-96 [64/64]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: mschapv2-naive, MSCHAPv2 C/R [MD4 DES DES 64/64 naive]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: krb5pa-md5, Kerberos 5 AS-REQ Pre-Auth etype 23 [32/64]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: netlmv2, LMv2 C/R [MD4 HMAC-MD5 32/64]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: netntlmv2, NTLMv2 C/R [MD4 HMAC-MD5 32/64]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: netntlm-naive, NTLMv1 C/R [MD4 DES (ESS MD5) DES 64/64 naive]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: po, Post.Office [MD5 32/64]... FAILED (get_hash[0](0))

Benchmarking: Sybase-PROP [salted FEAL-8 32/64]... (2xOMP) FAILED (get_hash[0](0))

Benchmarking: tc_aes_xts, TrueCrypt (RIPEMD160/SHA512/WHIRLPOOL) AES256_XTS [64/64]... (2xOMP) FAILED (cmp_all(1))

Benchmarking: tc_ripemd160, TrueCrypt RIPEMD160 AES256_XTS [32/64]... (2xOMP) FAILED (cmp_all(1))

Benchmarking: tc_sha512, TrueCrypt SHA512 AES256_XTS [64/64]... (2xOMP) FAILED (cmp_all(1))

Benchmarking: tc_whirlpool, TrueCrypt WHIRLPOOL AES256_XTS [64/64]... (2xOMP) FAILED (cmp_all(1))

19 out of 377 tests have FAILED
```
OMP or not makes no difference.

Note that some of these *might* have been fixed already, since Jumbo-1.

**Comment by jfoug** [comment]
Every single one of those formats are ones I have worked on since J1.  Until he pulls current code, I am not going to look at any of these. Yes, there certainly may be some BE problems that are being triggered by his 64 bit BE system.  But since ALL of these have recently been worked on, we should wait to see if a current build fixes this.

**Comment by magnumripper** [comment]
I think I have a ppc64 virtual machine somewhere, I'll see if I can test current bleeding a little.

**Comment by jfoug** [comment]
I am working on getting a build done now (on Solar's machine).  I did find one bug already (compiler warnings told me where to look. I will audit the warnings when things are done, and start looking at -test=0, -test=1 and jtrts.   But wow, this box is like watching grass grow.  For a 64 bit box, it must have been build by daisychaining 8 Comodor VIC 20's together.  But I do think it is finally getting close (I am down to putty2john.o), so I think its finally through all the main source files

**Comment by jfoug** [comment]
These were the only warnings (the dynamic is already fixed)

```
gcc -DAC_BUILT  -c -g -O2 -I/usr/local/include -DARCH_LITTLE_ENDIAN=0   -Wall -Wdeclaration-after-statement -fomit-frame-pointer -Wno-deprecated-declarations -Wno-format-extra-args -D__BSD_VISIBLE -DMEMDBG_ON   -fopenmp  -D_THREAD_SAFE -pthread  -funroll-loops dynamic_fmt.c -o dynamic_fmt.o
dynamic_fmt.c:2562: warning: braces around scalar initializer
dynamic_fmt.c:2562: warning: (near initialization for 'fmt_Dynamic.params.flags')
dynamic_fmt.c:2562: warning: initialization makes integer from pointer without a cast
dynamic_fmt.c:2565: warning: missing braces around initializer
dynamic_fmt.c:2565: warning: (near initialization for 'fmt_Dynamic.params.tunable_cost_name')
dynamic_fmt.c:2565: warning: initialization from incompatible pointer type

gcc -DAC_BUILT  -c -g -O2 -I/usr/local/include -DARCH_LITTLE_ENDIAN=0   -Wall -Wdeclaration-after-statement -fomit-frame-pointer -Wno-deprecated-declarations -Wno-format-extra-args -D__BSD_VISIBLE -DMEMDBG_ON   -fopenmp  -D_THREAD_SAFE -pthread  -funroll-loops ike_fmt_plug.c -o ike_fmt_plug.o
ike-crack.h: In function 'crypt_all':
ike-crack.h:505: warning: passing argument 1 of 'hmac_md5' discards qualifiers from pointer target type
ike-crack.h:523: warning: passing argument 1 of 'hmac_md5' discards qualifiers from pointer target type
ike-crack.h:536: warning: passing argument 1 of 'hmac_md5' discards qualifiers from pointer target type

gcc -DAC_BUILT  -c -g -O2 -I/usr/local/include -DARCH_LITTLE_ENDIAN=0   -Wall -Wdeclaration-after-statement -fomit-frame-pointer -Wno-deprecated-declarations -Wno-format-extra-args -D__BSD_VISIBLE -DMEMDBG_ON   -fopenmp  -D_THREAD_SAFE -pthread  -funroll-loops sha1crypt_common_plug.c -o sha1crypt_common_plug.o
sha1crypt_common_plug.c: In function 'sha1crypt_common_get_binary':
sha1crypt_common_plug.c:91: warning: implicit declaration of function 'JOHNSWAP'
```

**Comment by jfoug** [comment]
NOTE, I am seeing the exact same errors as reported by Solar.  I am using current bleeding jumbo.  I see the same, also adding LUKS to the list, so there are 20 of them to start looking at.  At least I will not have to endure the make statement again.  That was painful.

**Comment by jfoug** [comment]
here was the bug for hmac-sha384/512.  Using ARCH_WORD is not valid. The wrong byte is compared.  If you use default_binary_hash_0, (or 1, 2, etc), it typecasts to a ARCH_WORD_32.

Now if we need to use ARCH_WORD, then we will have to typecast within the get_hash_0...6 functions.

https://github.com/magnumripper/JohnTheRipper/commit/e56c83420bbbc6f0e94b7ff1af14eca9c72b1853

**Comment by jfoug** [comment]
- [ ]  scrypt (16384, 8, 1) [Salsa20/8 32/64]... (2xOMP) FAILED (get_hash[0](0))
- [ ] dynamic_17 [phpass ($P$ or $H$) 32/64 48x2  (MD5_body)]... (2xOMP) FAILED (get_hash[0](0))
- [ ] cloudkeychain, 1Password Cloud Keychain [PBKDF2-SHA512 32/64]... (2xOMP) FAILED (cmp_all(1))
- [ ] django-scrypt [Salsa20/8 32/64]... (2xOMP) FAILED (get_hash[0](0))
- [ ] EFS [PBKDF2-SHA1-efs-variant 3DES 32/64]... (2xOMP) FAILED (cmp_all(1))
- [x] HMAC-SHA384 [password is key, SHA384 64/64 OpenSSL]... (2xOMP) FAILED (get_hash[0](0))
- [x] HMAC-SHA512 [password is key, SHA512 64/64 OpenSSL]... (2xOMP) FAILED (get_hash[0](0))
krb5-18, Kerberos 5 db etype 18 aes256-cts-hmac-sha1-96 [64/64]... (2xOMP) FAILED (get_hash[0](0))
- [ ] mschapv2-naive, MSCHAPv2 C/R [MD4 DES DES 64/64 naive]... (2xOMP) FAILED (get_hash[0](0))
- [ ] krb5pa-md5, Kerberos 5 AS-REQ Pre-Auth etype 23 [32/64]... (2xOMP) FAILED (get_hash[0](0))
- [ ] netlmv2, LMv2 C/R [MD4 HMAC-MD5 32/64]... (2xOMP) FAILED (get_hash[0](0))
- [ ] netntlmv2, NTLMv2 C/R [MD4 HMAC-MD5 32/64]... (2xOMP) FAILED (get_hash[0](0))
- [ ] netntlm-naive, NTLMv1 C/R [MD4 DES (ESS MD5) DES 64/64 naive]... (2xOMP) FAILED (get_hash[0](0))
- [ ] po, Post.Office [MD5 32/64]... FAILED (get_hash[0](0))
- [ ] Sybase-PROP [salted FEAL-8 32/64]... (2xOMP) FAILED (get_hash[0](0))
- [ ] tc_aes_xts, TrueCrypt (RIPEMD160/SHA512/WHIRLPOOL) AES256_XTS [64/64]... (2xOMP) FAILED (cmp_all(1))
- [ ] tc_ripemd160, TrueCrypt RIPEMD160 AES256_XTS [32/64]... (2xOMP) FAILED (cmp_all(1))
- [ ] tc_sha512, TrueCrypt SHA512 AES256_XTS [64/64]... (2xOMP) FAILED (cmp_all(1))
- [ ] tc_whirlpool, TrueCrypt WHIRLPOOL AES256_XTS [64/64]... (2xOMP) FAILED (cmp_all(1))

**Comment by magnumripper** [comment]
> At least I will not have to endure the make statement again. That was painful.

The newly added dependencies in Makefile pay off good now!

**Comment by jfoug** [comment]
> The newly added dependencies in Makefile pay off good now!

Do they ever.  You now pretty much know that required rebuild happens properly, without having to make clean & make    Some of the things being changes are on headers.  That used to be one of those unknowns that you simply were better off cleaning down and doing a full rebuild.  SOOO much nicer to only have 3 or 4 .o filed compile, and get a good result in the end!

**Comment by jfoug** [comment]
I started to look at mschapv2-naive (and netntlmv2)   They use the getbits from the DES_b code. It uses ARCH_WORD   So I switched from using fmt_default_binary_hash_0, ..._6 to my own binary_hash_0...6 which use ARCH_WORD* to deref the binary. That did not fix it. I think I need to leave them the way they are (using the custom binary_hah_0), and then find somewhere in code that needs a JOHNSWAP.

We might have to add custom binary_hash_0 for all DES formats. But when I look at DES_FMT.c, it also has binary_hash_0 function, BUT that function is just fmt_default_binary_hash_0 so I am not sure what to think here.

**Comment by jfoug** [comment]
```
$ grep E_md4hash *.c
krb5pa-md5_fmt_plug.c:                  len = E_md4hash((unsigned char *) saved_plain[i], saved_len[i], K);
MSCHAPv2_bs_fmt_plug.c:                 len = E_md4hash((uchar *) saved_plain[i], saved_len[i],
NETLMv2_fmt_plug.c:                     len = E_md4hash(saved_plain[i], saved_len[i], ntlm);
NETNTLM_bs_fmt_plug.c:                  len = E_md4hash((uchar *) saved_plain[i], saved_len[i],
NETNTLMv2_fmt_plug.c:                   len = E_md4hash(saved_plain[i], saved_len[i], ntlm);
opencl_krb5pa-md5_fmt_plug.c:                   E_md4hash((unsigned char*)password,
unicode.c:int E_md4hash(const UTF8 *passwd, unsigned int len, unsigned char *p16)
```

Every one of these are in this list of failures. @magnumripper can you look at this function as run against BE64 ?   It looks like the len>27 part is working (the MAXLENGTHAAAAAAAAAAA works), but the other part does not give proper results.

**Comment by jfoug** [comment]
Getting closer.  Down to 7 of them (and scrypt variants are probably both fixed when one gets fixed.

**Comment by jfoug** [comment]
The scrypt issue has been found. IT was a F'n ugly sob.  It looks like it has to do with compiler/optimizer bug, possibly dealing with data cache reading/writing.   I can fix it with a single 'volatile' variable addition within the salsa20_8() within crptyo_scrypt-nosse.c file, BUT performance greatly suffers on other platforms.  There has to be a better way, possibly by re-ordering instructions or something.

**Comment by magnumripper** [comment]
If the root problem is aliasing violation I'd expect to see compiler warnings but I never saw that for scrypt.

**Comment by jfoug** [comment]
It was hidden by conversion to void *

**Comment by jfoug** [comment]
Found the feal8 bug. That was the last one.  Pretty easy to spot, once I finally figured it out. The feal code was using unsigned long, and it was fine for LE or BE if long is 32 bits.  But once long became 64 bits, then 0 was always being used (uninitialized bits).

**Comment by jfoug** [comment]
Once again, I think we are golden on BE hardware.  This was a very good test.  There were some 64 bit only issues shown by this, along with numerous BE failures on formats which I have recently updated, and a couple that showed up due to allow_unaligned issues.

**Comment by magnumripper** [comment]
> The feal code was using unsigned long, and it was fine for LE or BE if long is 32 bits

Duh. Who use long for 32-bit in the 21th century?! I regularly check all our code base for use of long and replace them with int or (infrequently) uint64_t. We shouldn't use "long" anywhere except for things like ftell() which returns long.
