### ISSUE TITLE
solaris compiler crash in mpz_int128.h

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1033]
gmake[1]: Entering directory `/export/home/jim.fougeron/john/bleed/src'
gcc -DAC_BUILT  -c -g -O2 -I/usr/local/include -DARCH_LITTLE_ENDIAN=0   -Wall -Wdeclaration-after-statement -fomit-frame-pointer -Wno-deprecated-declarations -Wno-format-extra-args -D__EXTENSIONS__ -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -I/usr/sfw/include     -D_REENTRANT -pthreads  -funroll-loops -DJTR_MODE -Wno-declaration-after-statement -std=c99 -c pp.c
mpz_int128.h: In function `_int128tostr':
mpz_int128.h:127: internal compiler error: Segmentation Fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <URL:http://gcc.gnu.org/bugs.html> for instructions.
gmake[1]: *** [pp.o] Error 1
gmake[1]: Leaving directory `/export/home/jim.fougeron/john/bleed/src'
gmake: *** [default] Error 2

**Comment by jfoug** [comment]
For now, I am hand editing my autoconfig.h file, to strip out this code from being built at all.  But it is something that must be looked at, if it is going to be kept.

**Comment by magnumripper** [comment]
Maybe it tries to optimize away the recursive code :-P

**Comment by magnumripper** [comment]
What version of gcc is this?

**Comment by magnumripper** [comment]
And what's the output of `grep 128 autoconfig.h`?

**Comment by magnumripper** [comment]
> Maybe it tries to optimize away or inline the recursive code :-P

Seriously, I see now I declared that function as "inline" which does not make sense since it does recurse. Try dropping that and see what happens!

**Comment by jfoug** [comment]
gcc --version shows   gcc (GCC) 3.4.6  (yes I know it is ancient).

The 128 only is set for  HAVE___INT128_T   So I have __int128_t on this system.

I will try (later) with removing the inline.  I am somewhat heads down in the truecrypt code.

**Comment by jfoug** [comment]
Without the inline, it still cores.  I bet if this was in a .c file (properly), it would work just fine.

I am going back to autoconfig.h commenting out the __int128_t type.

**Comment by magnumripper** [comment]
> I bet if this was in a .c file (properly), it would work just fine.

That's nonsense: After the PP the compiler would not know the difference.

**Comment by magnumripper** [comment]
We actually don't need/use any return code. What if you apply this?
```
diff --git a/src/mpz_int128.h b/src/mpz_int128.h
index bc54438..5187500 100755
--- a/src/mpz_int128.h
+++ b/src/mpz_int128.h
@@ -112,11 +112,10 @@ static inline int _mpz_fdiv_q_ui(mpz_t *q, mpz_t n, mpz_t d)
 			_int128tostr(op, base, ptr); \
 	} while (0)
 
-static inline int _int128tostr(uint128_t op, int base, char *ptr)
+static void _int128tostr(uint128_t op, int base, char *ptr)
 {
-	char *orig = ptr;
 	if (op == 0)
-		return 0;
+		return;
 
 	if (base != 10) {
 		fprintf(stderr, "%s(): base %d not implemented\n",
@@ -127,7 +126,6 @@ static inline int _int128tostr(uint128_t op, int base, char *ptr)
 	ptr += _int128tostr(op / base, base, ptr);
 	*ptr++ = op % base + '0';
 	*ptr = 0;
-	return ptr - orig;
 }
 
 #define mpz_set_str(rop, str, base) _mpz_set_str(&rop, str, base)
```

**Comment by magnumripper** [comment]
No, scrap that. We do need that returncode internally :doh:

**Comment by magnumripper** [comment]
I bet using `-O1` or `-O0` would work around it, just like that other problem we had on Sparc w/ gcc 3... was it unrar.c?

**Comment by magnumripper** [comment]
OK, that wasn't an ICE but anyway: fba70c6

**Comment by jfoug** [comment]
I tried with as minimal compile line as possible (after splitting just that function into it's own .c file, for good measure).  It still cores.

gcc -O0 mpz_int128.c
mpz_int128.c: In function `_int128tostr':
mpz_int128.c:55: internal compiler error: Segmentation Fault
Please submit a full bug report,
with preprocessed source if appropriate.


Note, that ONLY used -O0, nothing else, and it still barfs.

**Comment by jfoug** [comment]
Ok, here is a MUCH faster version (I did 2 versions, one is a tiny bit faster, one is 4x or so faster). They do not use recursion.  However, I had to add strrev() since linux does not have it, and we will have to add that to the configure and jumbo.c

```C
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <time.h>

#define uint128_t __uint128_t

// in JtR we will have to have HAVE_STRREV or something.
#ifndef _MSC_VER
/* inplace strrev */
char *strrev(char *str) {
	char *p1, *p2;
	if (!str || !str[0])
		return str;
	for (p1 = str, p2 = str + strlen(str) - 1; p2 > p1; ++p1, --p2) {
		*p1 ^= *p2; *p2 ^= *p1; *p1 ^= *p2;
	}
	return str;
}
#endif

int ___int128tostr(uint128_t op, int base, char *ptr) {
	char *p = ptr;
	if (!op) 
		return 0;
	do {
		uint32_t t = op % 1000000000;
		op /= 1000000000;
		while (t) {
			*p++ = (char)(t % base) + '0';
			t /= base;
		}
	} while (op);
	*p = 0;
	strrev(ptr);
	return p-ptr;
}
int __int128tostr(uint128_t op, int base, char *ptr) {
	char *p = ptr;
	if (!op) 
		return 0;
	while (op) {
		*p++ = (char)(op % base) + '0';
		op /= base;
	}
	*p = 0;
	strrev(ptr);
	return p-ptr;
}
int _int128tostr(uint128_t op, int base, char *ptr) {
	char *orig = ptr;
	char buf[40];
	if (op == 0)
		return 0;
	ptr += _int128tostr(op / base, base, ptr);
	*ptr++ = (char)(op % base) + '0';
	*ptr = 0;
	return ptr - orig;
}

int main() {
	char buf[45], buf2[45], buf3[45];
	int i, x, y, z;
	clock_t t1, t2, t3, t4;
	uint128_t v = 2194751296777771151ULL;
	v *= v;

	t1=clock();
	for (i = 0; i < 1000000; ++i) {
		x =  _int128tostr(v, 10, buf);
	}
	t2=clock();
	for (i = 0; i < 1000000; ++i) {
		y =  __int128tostr(v, 10, buf2);
	}
	t3=clock();
	for (i = 0; i < 1000000; ++i) {
		z =  ___int128tostr(v, 10, buf3);
	}
	t4=clock();
	printf("%s\n%s\n%s\nx=%d y=%d y=%d\n", buf, buf2, buf3, x, y, z);
	printf ("t1=%u  t2=%u t3=%u\n", t2-t1, t3-t2, t4-t3);
}
```

Here were the results (not how much faster the ___int128.. is  The speed is due to 'most' math being done in native uint32.  NOTE, we could change that to be uint64 on 64 bit machines, and get even more performance, due to reducing the number off uint128_t mod/divides.

```
$ g++ -O2 ../test.cpp

$ ./a.exe
4816933254707708099902251355327864801
4816933254707708099902251355327864801
4816933254707708099902251355327864801
x=37 y=37 y=37 2337280
t1=3062  t2=2969 t3=672
```

Here is the number shown in bc:

```
$ bc
bc 1.06.95
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006 Free Software Foundation, Inc.
This is free software with ABSOLUTELY NO WARRANTY.
For details type `warranty'.
2194751296777771151*2194751296777771151
4816933254707708099902251355327864801
```

**Comment by jfoug** [comment]
I just tested using uint64 (and ARCH_BITS=64 define), and it was not faster. It was 15-20% slower than the usage of 32 bit for the inner math:

```
$ g++ -O2 ../test.cpp -DARCH_BITS=64

$ ./a
4816933254707708099902251355327864801
4816933254707708099902251355327864801
4816933254707708099902251355327864801
x=37 y=37 y=37 2337280
t1=3109  t2=3000 t3=719

$ ./a
4816933254707708099902251355327864801
4816933254707708099902251355327864801
4816933254707708099902251355327864801
x=37 y=37 y=37 2337280
t1=3015  t2=2985 t3=734
```

With these changes:

```C
int ___int128tostr(uint128_t op, int base, char *ptr) {
	char *p = ptr;
	if (!op) 
		return 0;
	do {
+ #if ARCH_BITS==64
+ 		uint64_t t = op % 10000000000000000000ULL;
+ 		op /= 10000000000000000000ULL;
+ #else
		uint32_t t = op % 1000000000;
		op /= 1000000000;
+ #endif
		while (t) {
			*p++ = (char)(t % base) + '0';
			t /= base;
		}
	} while (op);
```

**Comment by jfoug** [comment]
Now after changing int128tostr to be non recursive, it compiles that part, but still cores :(

```
SET_BITS=64   -I/usr/sfw/include     -D_REENTRANT -pthreads  -funroll-loops -DJTR_MODE -Wno-declaration-after-statement -std=c99 -c pp.c
pp.c: In function `set_chain_ks_poses':
pp.c:572: internal compiler error: Segmentation Fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <URL:http://gcc.gnu.org/bugs.html> for instructions.
```

**Comment by magnumripper** [comment]
Too bad :(  I tried googling for known problems with gcc 3.4 but did not find anything like this. Maybe this is actually a problem with int128's, I thought it really looked like being caused by recursion.

**Comment by jfoug** [comment]
I think it likely is the int128's also.  They are defined, but probably do not get a huge amount of regression testing.

**Comment by jfoug** [comment]
But the change to the int128tostr should be kept. It is 4x faster doing it the 32 bit way, and has no recursion.

**Comment by jfoug** [comment]
This likely has to do with 32 bit solaris and gcc of that version.  It likely has to do with the compiler having to do all the math up front (since there is no native 64 bit stuff, and if the complexity gets too large, the compiler runs out of symbol space.

**Comment by jfoug** [comment]
I bet it is fully unsupported even though it is currently is 'listed' as being supported. It is like VC.  __int128 gets a 'unsupported in this arch' if I build with it.  Sparc, probably the same thing.

I think we should look at the configure script, and possibly look at the probes.  I bet the probe code is nothing more than:

```C
#include <stdio.h>
__int128_t check;
void main() {
  return 0;
}
```

If that is the case, then sparc32 is happy to build it. BUT it can not use the value.  We might need special probes built for this.

**Comment by jfoug** [comment]
Ok, here is the code for check_type:

```C
int
main ()
{
if (sizeof (__int128_t))
	 return 0;
  ;
  return 0;
}
```

This does not appear adequate to test for these.  the gcc for sparc gives us the type, but if you use it (i have tried a simple n/q)  it crashes the compiler.  So we need a better way to test for these being acceptable.

**Comment by magnumripper** [comment]
I thought this was Sparc64. I'd rather stay out of native tests but we should only do the current test for int128 on 64-bit builds!

**Comment by magnumripper** [comment]
I belive later gcc will not show int128 support on 32-bit, only 64-bit. This is the problem.

**Comment by jfoug** [comment]
cygwin32 does not show support for int128 stuff.  But yes, this is gcc-32 (but on a 64 bit sparc).

You do not want to put in correct native probing for this issue?  Even if we only do the test on 64 bit systems, is that valid enough?

**Comment by magnumripper** [comment]
> You do not want to put in correct native probing for this issue?

I just can't see any situation a native test would add any information. We should keep the tests we had, but onyl run them if we're on 64-bit.

**Comment by magnumripper** [comment]
d876a0d should disable the format on sparc32.
