### ISSUE TITLE
Three format fails after merging GPU mask branch

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1036]
```
Testing: bfegg, Eggdrop [Blowfish 32/64]... (4xOMP) FAILED (get_key(1))
Testing: HMAC-SHA1 [password is key, SHA1 128/128 XOP 8x]... (4xOMP) FAILED (get_key(3))
Testing: mysql, MySQL pre-4.1 [32/64]... (4xOMP) FAILED (get_key(4))
```
This may or may not be problems in the formats. It's more likely these are "self test technical" issues that need to be worked around, either in formats.c or in these formats.

**Comment by Sayantan2048** [comment]
Yes, I saw that too. Looking into it right now.

**Comment by Sayantan2048** [comment]
Quick fix:
change line 539 in format.c to the following:
```
for (i = match - 1; i >= 0; i--)
```

**Comment by Sayantan2048** [comment]
However, it looks like the these format generate same hashes for multiple passwords. Otherwise, there shouldn't have been any problem.

**Comment by magnumripper** [comment]
Hmm or maybe they just have dupe test vectors?

**Comment by magnumripper** [comment]
Hm, no.
```
$ ../run/john -form:bfegg --list=format-tests 
bfegg	0	+9F93o1OxwgK1	123456
bfegg	1	+C/.8o.Wuph9.	qwerty
bfegg	2	+EEHgy/MBLDd0	walkman
bfegg	3	+vPBrs07OTXE/	tesztuser
bfegg	4	+zIvO/1nDsd9.	654321
```

**Comment by magnumripper** [comment]
Are we always setting all keys in the batch? If not, you might see leftovers from a previous crypt.

**Comment by Sayantan2048** [comment]
Yes, right. But then, shouldn't the format cleanse its buffer such that cmp_one() and cmp_exact() does not return false positives?

Anyway, the latest commit emulates the self-test exactly as we did before for older formats and externally, they shouldn't notice any difference.

**Comment by magnumripper** [comment]
> shouldn't the format cleanse its buffer such that cmp_one() and cmp_exact() does not return false positives?

In real runs, we always fill *n* keys and then call `crypt_all(n)` so buffer cleaning would just harm performance. We should try to have the self-test work like IRL (perhaps fill keys with dummy strings that are not included in any actual test vector).
