### ISSUE TITLE
Add int128 support for 32-bit builds using 64-bit lo/hi structs

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1040]
This is trivial and very similar to math.h's 64-bit functions that use 32-bit lo/hi structs. We should add it to mpz_int128.h with #ifdef's so it's used instead of int128 when needed. This could also be contributed to [upstream PRINCE](https://github.com/jsteube/princeprocessor).

**Comment by magnumripper** [comment]
One thing I'm not sure of: How would you do a (fast) modulo operation using 64x64? I think that's the only detail I'm not sure how to accomplish.

**Comment by magnumripper** [comment]
@Sayantan2048 from recent john-dev messages it seems you might be able to fill in the function above? That would make me complete the rest of this task.

**Comment by Sayantan2048** [comment]
On Wednesday, March 11, 2015, magnum <notifications@github.com> wrote:

> @Sayantan2048 <https://github.com/Sayantan2048> from recent john-dev
> messages it seems you might be able to fill in the function above? That
> would make me complete the rest of this task.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magnumripper/JohnTheRipper/issues/1040#issuecomment-78158940>
> .
>

I can make a (128 bit modulo 31bit) operation much faster using 64 bit
hi/lo structs but generic (128 bit modulo 128 bit) won't be any faster or
Infact might be slower than native 128 bit modulo divisions.

**Comment by magnumripper** [comment]
> I can make a (128 bit modulo 31bit) operation much faster using 64 bit hi/lo structs

This is exactly what I need. This is for systems lacking native int128.

**Comment by Sayantan2048** [comment]
```
typedef struct {
	uint64_t LO64;
	uint64_t HI64;
} uint128_t;

shift64 = ((1ULL << 63) % N) * 2; // must be executed and  passed to  modulo128_32b() when N is changed.

/* Assuming N <= 0x7fffffff */ 
inline unsigned int modulo128_32b(uint128_t a, unsigned int N, uint64_t shift64)
{
	uint64_t p;
	p = (a.HI64 % N) * shift64;
	p += (a.LO64 % N);
	p %= N;
	return (unsigned int)p;
}
```

**Comment by magnumripper** [comment]
This is no longer very appealing - 32-bit systems are not very common.
