### ISSUE TITLE
Add support for cracking password-protected installer(s) generated by Inno Setup

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1042]
http://www.jrsoftware.org/ishelp/topic_setup_encryption.htm

**Comment by magnumripper** [comment]
Lol, so it's a single SHA1 of an 8-byte random salt + password. Should be pretty fast!

**Comment by magnumripper** [comment]
So do we have a known plain to match?

**Comment by jfoug** [comment]
Should this be a thin dyna hash ?

**Comment by jfoug** [comment]
I bet not. Likely we will have to compute 160 bit key then decrypt something with it, looking for plaintext matches, so just because key is trivial does not mean dynamic will be helpful.

**Comment by magnumripper** [comment]
As I read it, we actually have a hash to compare against (and so the password is not much of a protection). So it could be a single limb of SHA1 and we're done.

**Comment by kholia** [comment]
@jfoug @magnumripper 

How do I do a hex dump of something like ARRAY(0x37f9608) in Perl?

**Comment by kholia** [comment]
One limb of SHA1 should be enough (TM), I think.

**Comment by jfoug** [comment]
unpack("H*", $array);   ?

or possibly    foreach my $s (@array) { print $s; }

I am not really sure what you mean by ARRAY(0x37f9608)

**Comment by kholia** [comment]
``p $setup0->{Header}->{PasswordSalt}; # Data::Printer`` gives me,

```

\ [
    [0] 70,
    [1] 50,
    [2] 67,
    [3] 217,
    [4] 42,
    [5] 188,
    [6] 20,
    [7] 204
]
```

**Comment by jfoug** [comment]
I think this is what you want (I think it will give you the hex string).

unpack ("H*", $setup0->{Header}->{PasswordSalt});

unpack (and pack) are your friends :)

**Comment by kholia** [comment]
``unpack ("H*", $setup0->{Header}->{PasswordSalt});`` gives me ``41525241592830783361393633613829`` which decodes to ``ARRAY(0x3a963a8)``.

WOW! ;)

**Comment by kholia** [comment]
https://github.com/kholia/inno2john/blob/tweaks-v1/Setup/Inno.pm#L142

**Comment by magnumripper** [comment]
LOL, perl is a footgun

**Comment by kholia** [comment]
I have spent more than 30 minutes and still can't figure this out.

Sorry but Perl is one of the worst thing I have ever seen.

**Comment by jfoug** [comment]
Ok, try this:

my $val = join ( '' , $setup0->{Header}->{PasswordSalt});
print unpack ("H*", $val);

See what that gives you.  NOTE the first param in the join it 2 single quotes with nothing between them.

**Comment by magnumripper** [comment]
I think there's something like Data::Dumper or what it's called, that is everything you'll ever need

**Comment by jfoug** [comment]
```Perl
#!/usr/bin/perl

my @ar = (chr(70),chr(50),chr(67),chr(217),chr(42),chr(188),chr(20),chr(204));
my $str = join ('', @ar);
print unpack("H*", $str);
```
$ perl xx.pl
463243d92abc14cc

**Comment by kholia** [comment]
The ``join`` stuff gives me ``41525241592830783339326338633029`` ;(

**Comment by kholia** [comment]
You can try the actual code yourself by running ``./extract.pl samples/Output/setup.exe``.

**Comment by jfoug** [comment]
When I did a git of kholia/inno2john, the 'sample' directory was not there.  Is that a separate repo?

**Comment by kholia** [comment]
The algorithm is ``hashlib.sha1("PasswordCheckHash" + salt + password).hexdigest()``.

**Comment by jfoug** [comment]
```Perl
		# working method #1
		for (my $i = 0; $i < 8; $i++) {
			print unpack("H*", chr($setup0->{Header}->{PasswordSalt}[$i]));
		}
		print ("\n");

		# working method #2
		my @ar = (chr($setup0->{Header}->{PasswordSalt}[0]), chr($setup0->{Header}->{PasswordSalt}[1]),
		          chr($setup0->{Header}->{PasswordSalt}[2]), chr($setup0->{Header}->{PasswordSalt}[3]),
		          chr($setup0->{Header}->{PasswordSalt}[4]), chr($setup0->{Header}->{PasswordSalt}[5]),
		          chr($setup0->{Header}->{PasswordSalt}[6]), chr($setup0->{Header}->{PasswordSalt}[7]));
		$val = join ('' , @ar);
		print unpack ("H*", $val)."\n";

```

**Comment by jfoug** [comment]
So is this the 'algorithm' ?

```Perl
my $digest = Digest::SHA1("PasswordCheckHash" . salt . password);
```

**Comment by kholia** [comment]
@jfoug yes, that is the algorithm.

**Comment by kholia** [comment]
@jfoug thanks. I have now modified the code to output `dynamic_25`` hashes.

```
$ extract.pl samples/Output.old/setup.exe      
...
$dynamic_25$6d29001f8a5062d7b6f5b32b30a8cf64da6567e0$HEX$50617373776f7264436865636b48617368463243d92abc14cc
```

However, these hashes don't load up. Any hints?

**Comment by kholia** [comment]
The following works though,

```
# Inno Setup, Digest::SHA1("PasswordCheckHash" . salt . password)
[List.Generic:dynamic_1505]
Expression=sha1($s.$p) (long hex salts)
Flag=MGF_INPUT_20_BYTE
Flag=MGF_SALTED
Flag=MGF_FLAT_BUFFERS
Func=DynamicFunc__clean_input
Func=DynamicFunc__append_salt
Func=DynamicFunc__append_keys
Func=DynamicFunc__SHA1_crypt_input1_to_output1_FINAL
Test=$dynamic_1505$6d29001f8a5062d7b6f5b32b30a8cf64da6567e0$HEX$50617373776f7264436865636b48617368463243d92abc14cc:openwall
```

**Comment by kholia** [comment]
@jfoug should I commit this or do we have a better approach?

**Comment by kholia** [comment]
Done in commit 2f67e599fc0279dbc2166add29aa726de60691ac.

**Comment by kholia** [comment]
``inno2john.pl`` will stay as an external project (for a log while).

See https://github.com/kholia/inno2john for more details.

**Comment by jfoug** [comment]
Lets please use 25. I will fix it. The salt was too short.  This is flat buffers, it should not be limited to a 24 byte salt.

**Comment by kholia** [comment]
@jfoug cool, I will roll back my changes once your fix is in.

**Comment by jfoug** [comment]
Try now, after 857819f

**Comment by kholia** [comment]
@jfoug thanks, all set now :+1:
