### ISSUE TITLE
agile-keychain.  Why is this 'not exact'

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1048]
as far as I see, it looks like we decrypt a 16 byte buffer, looking for padding. The padding should be the full 16 bytes. It is the block after the IV, so probably is full padding.  If that is the case, then we have 16 full 16 byte value, which is more than enough.

Also, if we 'know' this is will be a 0x10.....0x10 buffer, then we can remove the decryption, and instead encrypt, which allows us to do salt dupe removal. But I do not know this format well enough to know if that fixed 0x10 0x10 bytes is the proper padded value.

@kholia some help here would be nice.

**Comment by magnumripper** [comment]
```C
static int akcdecrypt(unsigned char *derived_key, unsigned char *data)
{
	unsigned char out[CTLEN];
	int pad, n, i, key_size;
	AES_KEY akey;
	unsigned char iv[16];
	memcpy(iv, data + CTLEN - 32, 16);

	if(AES_set_decrypt_key(derived_key, 128, &akey) < 0) {
		fprintf(stderr, "AES_set_decrypt_key failed in crypt!\n");
	}
	AES_cbc_encrypt(data + CTLEN - 16, out + CTLEN - 16, 16, &akey, iv, AES_DECRYPT);

	// now check padding
	pad = out[CTLEN - 1];
	if(pad < 1 || pad > 16) /* AES block size is 128 bits = 16 bytes */
		// "Bad padding byte. You probably have a wrong password"
		return -1;
	n = CTLEN - pad;
	key_size = n / 8;
	if(key_size != 128 && key_size != 192 && key_size != 256)
		// "invalid key size"
		return -1;
	for(i = n; i < CTLEN; i++)
		if(out[i] != pad)
			// "Bad padding. You probably have a wrong password"
			return -1;
	return 0;
}
```
I haven't really groked the code, but it looks to me random data (ie. incorrect key) would lead to a "padding" of `01` once in 256 guesses, or `0202` once in 65536 guesses and so on. But we definitely don't have THAT many false positives so somehow these must be filtered out by the above. I really don't understand that key size test.

Also, why isn't it just `unsigned char out[16];` when that is all we use?

**Comment by magnumripper** [comment]
> Also, why isn't it just `unsigned char out[16];` when that is all we use?

Not to mention the CTLEN sized buffer in the salt. Are we not only using 16 of the 1040 bytes of ciphertext?

**Comment by magnumripper** [comment]
```C
static struct custom_salt {
	unsigned int nkeys;
	unsigned int iterations[2];
	unsigned int saltlen[2];
	unsigned char salt[2][SALTLEN];
	unsigned int ctlen[2];
	unsigned char ct[2][CTLEN];
} *cur_salt;
```
...and why is everything `[2]` when we're only using the `[0]`?!

**Comment by jfoug** [comment]
The buffer that is decoded is a 16 byte buffer located AFTER the IV item. So likely it is siply 16 bytes of 0x10   In the sample that is what it is.  I have made a pass_gen, and I simply encode a 16 byte buffer of 0x10's and that is it.

**Comment by jfoug** [comment]
There are 2 keys,  But the format does not use them.   I also read the link and it mentions 2 keys. I am not sure why.  I did not write the thing.

**Comment by jfoug** [comment]
Kinda waiting for @kholia to chime in.  He is the obscure format guru.

**Comment by jfoug** [comment]
I think it is simply a zero byte buffer that gets encrypted, with a specific padding scheme (AES ???) and that is why this type padding is done.

However, why we accept 1 to 15, I do not know. Possibly it is not always 16 bytes of padding.

**Comment by frank-dittrich** [comment]
You mean the guru of unnecessarily obscure formats?

**Comment by jfoug** [comment]
lol

**Comment by magnumripper** [comment]
The scheme is PKCS#7/RFC3369.
https://bitbucket.org/gwik/agilekeychain/src/f4339daef15a36f9d03c0d29d5dfc3d5804834b3/RFC3369.py?at=default
http://www.di-mgt.com.au/cryptopad.html#aeslargerblocksize

**Comment by magnumripper** [comment]
Looks to me most of the format is hardcoded for 128-bit although some code seem to try supporting 192 and 256-bit AES too... We need test vectors (real ones, not pass_gen.pl) for all sizes.

**Comment by kholia** [comment]
Hi!

I lost internet access at home yesterday. I will try to answer these
questions later today :)

Dhiru
>
>

-- 
Dhiru

**Comment by magnumripper** [comment]
This is in our samples collection
```
$ unzip -l openwall.agilekeychain.zip 
Archive:  openwall.agilekeychain.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  07-20-12 11:33   openwall.agilekeychain/
   317261  03-31-12 16:36   openwall.agilekeychain/1Password.html
    15086  03-31-12 16:36   openwall.agilekeychain/AgileKeychain.ico
        0  07-20-12 11:33   openwall.agilekeychain/config/
      513  03-31-12 16:36   openwall.agilekeychain/config/domains
        1  03-31-12 16:36   openwall.agilekeychain/config/use-thumbnails
        4  03-31-12 16:36   openwall.agilekeychain/config/version
        0  07-20-12 11:33   openwall.agilekeychain/data/
        0  07-20-12 11:33   openwall.agilekeychain/data/default/
     6585  07-21-12 11:22   openwall.agilekeychain/data/default/.1password.keys
        0  07-21-12 11:22   openwall.agilekeychain/data/default/.ws.agile.1Password.write
     6585  07-21-12 11:22   openwall.agilekeychain/data/default/1password.keys
        2  03-31-12 16:36   openwall.agilekeychain/data/default/contents.js
     5964  07-21-12 11:22   openwall.agilekeychain/data/default/encryptionKeys.js
      224  03-31-12 16:36   openwall.agilekeychain/desktop.ini
 --------                   -------
   352225                   15 files
```
But I can't find a suitable agile2john program?

**Comment by magnumripper** [comment]
OK it's 1password2john.py. That is confusing. We should rename the format or the tool.

**Comment by kholia** [comment]
I am taking a look now. In the meanwhile, here is an useful link,

https://learn2.agilebits.com/1Password4/Security/keychain-design.html

**Comment by kholia** [comment]
Here is another sample,

https://github.com/gwik/agilekeychain/tree/master/test_data

**Comment by kholia** [comment]
> ...and why is everything [2] when we're only using the [0]?!

Initially, the plan was to decrypt more data, in order to reduce the false positives. However, the addition of the "key size check", later on, helped in reducing the false positives.

So, the "extra space" was never used :-)

**Comment by loverszhaokai** [comment]
Does the number of key is exactly **two** ?

**Comment by kholia** [comment]
@loverszhaokai 

I don't remember, and I will be "offline" for next 6 weeks or so.

I recommend you to re-trace my steps (think about how I wrote the format, which projects did I use code from, and so on).

**Comment by loverszhaokai** [comment]
@kholia  OK, I will try to make it clear.

**Comment by loverszhaokai** [comment]
@kholia  I try to use **1password4** on Windows 7, create Logins/Wallets/Accounts. And the encryptionKeys.js remains has two child in **"list"**. So I think there should be exactly two keys.

**Comment by kholia** [comment]
Quick notes,

1. I am OK with keeping `FMT_NOT_EXACT`, if we suspect that our verification checks are not very strong.

2. There doesn't seem to be a way to use AES-192 or AES-256. The official app. has moved to a newer hash format now.
