### ISSUE TITLE
blockchain update python to handle v2 hashes

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1050]
Here is an example:

```
{"pbkdf2_iterations":5000,"version":2,"payload":"mk1RV9SWljay/gc493o3b+2i+5eXOMXPDnEvXUovABYIgkqGXSUEG8heCtNZhZmfz659IY6xCacDeB9X57WgPCn/37dW7I7jjtiUGwVpIs3RdMjon+tA4aDhdmeShF9XmSrp12Z+/0Gl5VgPPyibBQ12zA8EnL0wxnXvw6VTwPGfMMuVicfDdz3Qld6SqZGWN4lAg1H1Q8HcMHdR5feBwnjadycANeN0PfAatOQRVbZDfZx+ZDiKKPgzGspIIua4nN1fRQYbmXaCGNhTo1dbvQKVZIJryxiNVURCc82liNTlk/xdKWlnE9dHz8gwKj6cnbsbs3VMLgDyi2nY+usuRcBAhTWcaptr/s/QpqjyetZHtr/UmPIiSowEQvf+cwZWJjrChpkjspatmVXbrVFbT4itM2Gb2swzrn8Uxl/OAp4PnkqcQUcW2aI+Q2GqJkSTu2/Jp/2oJZmwIyF0ufySoccXyizG3ri9aq83Brlf39xYIxbLPScReNr+OmcEqRjge+BXvvZ2uxRIQMfyZnbxg/J0T8L+IsnD/rdGG0ODmBwAtv/0A/71ePblRk3C0Ly3uNDcLnrdUCs0yP6fm2OO6+ft4l41Gxfqi4wfUhO2l4DAun7z1XNMBjXp0u5JUkkU8EfUVTYYC+JedhDbgJ22lM7rFqO/2KvVqwzaRBUgNAg4dpj+cHVoVm9/VnFkcHCRqAasLRG5ud0MPJkf8Df0Vw=="}
```

Pasword is   Openwall1234#

**Comment by kholia** [comment]
This ticket is up for grabs now.

**Comment by ljx34** [comment]
Ok, so..

"Please upload a sample wallet file which exhibits the problem clearly. Also, describe the exact steps you took earlier. Thanks!"

Here is the wallet file:

http://clicknupload.com/rm2n0wowmo8n

Password is: johntheripper!

Exact steps I have tried are.. running blockchain2john.py on it with both --json option on and off, taking the $blockchain+data part and saving it to a file, then running that with johntheripper with a dictionary containing johntheripper! password in it.

**Comment by kholia** [comment]
@ljx34 thanks for your help in fixing this problem! :+1: 

@jfoug great work in handling v2 hashes in the actual format :+1:

**Comment by ljx34** [comment]
Man, kholia... thank you so much for your help, I really really really appretiate the work you are doing.

**Comment by larrylballes** [comment]
pbkdf2_iterations":5000,"version":2,"payload
