### ISSUE TITLE
Python helpers overhaul

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1057]
Quoting @psypanda in https://github.com/magnumripper/JohnTheRipper/pull/1056#issuecomment-74917401
> Please also note that some python scripts still use the [deprecated optparse ](https://docs.python.org/2/library/optparse.html) for parsing command line options. It might be a good idea to move from optparse to [argparse](https://docs.python.org/2.7/library/argparse.html) in the near future.
Here is a list of .py files that still got optparse code in them:
* aix2john.py
* bitcoin2john.py
* blockchain2john.py
* efs2john.py
* openssl2john.py

**Comment by kholia** [comment]
@magnumripper Solar cares about supporting super old Python versions. So, we need to do something clever here, I think.

**Comment by magnumripper** [comment]
I guess we'll just do the try-catch dance, or is it harder this time? Or we could throw python to h3ll and use something that doesn't change the rules as you are typing.

**Comment by psypanda** [comment]
Well supporting v2.6+ and v3.0+ makes sense for me, but why such old versions as v2.2 *(release December 2001)*?

**Comment by magnumripper** [comment]
Let's concentrate on 3.x while trying to keep compatibility with last 2.7. On the other hand, there's no need to drop *existing* try/catch kludges for older versions.

**Comment by magnumripper** [comment]
> we need to do something clever here

You can't do anything clever with a language this stupid.

**Comment by kholia** [comment]
I made a mistake when I said "v2.2". Supporting Python >=2.4 should be good enough (TM).

I also agree with magnum's suggestions. Patches are welcome ;)

**Comment by campeador** [comment]
Hello, how can i push this files with modifications ?

**Comment by magnumripper** [comment]
We do Fork & Pull: https://help.github.com/articles/using-pull-requests/

Thanks in advance!

**Comment by magnumripper** [comment]
Reviewing last couple of comments I guess this is fixed.
