### ISSUE TITLE
DEScrypt-opencl LWS/GWS problems

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1058]
Requesting LWS/GWS via environment is broken now.

Works fine without:
```
$ ../run/john -test -form:descrypt-opencl -dev=2
Device 2: GeForce GT 650M
Local worksize (LWS) 64, Global worksize (GWS) 16384
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... DONE
Many salts:	2520K c/s real, 37449K c/s virtual
Only one salt:	2595K c/s real, 26214K c/s virtual
```

Requesting the very same(!) values:
```
$ LWS=64 GWS=16384 ../run/john -test -form:descrypt-opencl -dev=2
Device 2: GeForce GT 650M
Local worksize (LWS) 64, Global worksize (GWS) 16384
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
(...)
Get key error! 16383 0
Get key error! 16383 0
Get key error! 16383 0
Get key error! 16383 0
Get key error! 16383 0
Get key error! 16383 0
DONE
Many salts:	2299K c/s real, 37449K c/s virtual
Only one salt:	2621K c/s real, 26214K c/s virtual
```

Same or worse (segfault) for --test=0
```
$ ../run/john -test=0 -form:descrypt-opencl -dev=2
Device 2: GeForce GT 650M
Local worksize (LWS) 7, Global worksize (GWS) 49
Testing: descrypt-opencl, traditional crypt(3) [DES OpenCL]... Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
Get key error! 1 0
(...)
Get key error! 48 0
Get key error! 48 0
Get key error! 48 0
Get key error! 48 0
Get key error! 48 0
Get key error! 48 0
Abort trap: 6
```

**Comment by Sayantan2048** [comment]
fixed in 65fd39cee838613946d77ce6704bd3d8c6799722

**Comment by magnumripper** [comment]
It's fixed for most devices but once again you ignore device limits:
```
$ ../run/john -test -form:descrypt-opencl -dev=0
Device 0: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
Salt compiled from Source:1
OpenCL error (CL_INVALID_WORK_GROUP_SIZE) in file (opencl_DES_bs_h_plug.c) at line (474) - (Enque Kernel Failed)
```
This is (only) when using HARDCODE_SALT and problem is only seen with my CPU device. Obviously I do not care about using that very device, but this inidcates a problem we might get with other devices (not likely with that silly limit of 1 but it could be 32, or some other value) - so it must be fixed. Thing is, if you query for that device's max usable LWS it will anwer 1024. But when you *query for a particular kernel* the figure can and will sometimes be lower. We have been here before. You need to query each kernel involved and use the lowest figure.

**Comment by Sayantan2048** [comment]
The problem is the actual kernels are built after a call to crypt_all(). Maybe I should build a dummy kernel and query it in  init().

**Comment by Sayantan2048** [comment]
Please test 597f323e06e4f10b20431d5f5751f338bd74505f. Otherwise we'd have to force LWS for specific devices.

**Comment by magnumripper** [comment]
It works fine!
