### ISSUE TITLE
pkzip optimizations

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1061]
I stumbled upon this old document: http://www.woodmann.com/fravia/mike_zipattacks.htm

@jfoug is there anything important in there we do not already know/use? I think some of it is more about actual cracking (as opposed to brute-forcing candidates) so might not be applicable to JtR.

**Comment by jfoug** [comment]
This is nothing more than app notes about the 'known' plaintext attack against the weak encryption.  pkcrack uses this.  All you need is 13 'known' bytes to break it.  If you get more known bytes, it is faster.  This does not 'guess' the input password (but you can get many known good working passwords). It gets the 'actual' internal key state used in the cryptor.   This is not really what JtR does at all, and is not an optimization for pkzip cracking.
