### ISSUE TITLE
HMAC-SHA384 intermittent failures

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1063]
We still have some OpenMP problem with HMAC-SHA384. Running one thread seems to always be OK (even with OMP build) but two or more threads will fail more often than not. They fail in different places and with different test vectors.

Easily reproducible with `--stress-test=0` instead of `--test`

**Comment by magnumripper** [comment]
I had a good look at this but can't find the problem.

**Comment by jfoug** [comment]
I looked also, but saw nothing.  I am jam packed for the next 3days or so, trying to get my house on the market. Once that is done, I will be on this one. Likely there is some buffer that is short, but I looked and can not find it.   Let me do a quick compare against sha512 and see if something sticks out that I missed. All 4 of them (224/256/384/512) are done same way.  There are some differences between 32 and 64 bit types, but all in all they are the same.  comparing the 2 64 bit version might show the problem.

**Comment by jfoug** [comment]
Could there be any way new_keys could be set to 0 before all threads have run through the key loop ???

**Comment by jfoug** [comment]
I have found problems. BUT not the OMP issue.  One huge problem, BUT it is in code that is not run, since our PLAIN length is < 128, is that we use SHA512 for SIMD. That code was not changed.  I also moved the read/write of the global 'new_keys' out of the OMP code, and use a local variable that knew what new_keys was set to.  That did not help either.

I can not see any difference other than the end of 64 byte cleaning (where we re-pad 48 bytes) between sha512 and sha384 that have any significance.  The same type re-pad code is in sha224 and it works solid.  I have to give up for now, and get back on working on the house.  I will check in the few changes I have done.

**Comment by magnumripper** [comment]
> Could there be any way new_keys could be set to 0 before all threads have run through the key loop ???

There is an implied barrier at the end of the parallel block. I'd prefer you wouldn't commit random changes like that when they don't fix anything, they just add confusion.

I too compared it to hmac-sha512 and saw no differences (I did not spot that bug in set_key(), I'm glad you found it even though it's academic as of now). I presume there is another subtle problem with eg. PAD_SIZE vs. BINARY_SIZE... but I can't find it.

**Comment by magnumripper** [comment]
Hmm if I comment out the OpenMP pragma but otherwise build using OpenMP (serializing the OMP_SCALE), it keeps failing. So it's not about threads - some buffer is wrong size.

**Comment by magnumripper** [comment]
> Hmm if I comment out the OpenMP pragma but otherwise build using OpenMP (serializing the OMP_SCALE), it keeps failing. So it's not about threads - some buffer is wrong size.

Scrap that! I screwed up. Running like that does NOT show the problem.

**Comment by magnumripper** [comment]
Nailed it, indeed it was a BINARY_SIZE that should be PAD_SIZE in a bunch of places.

**Comment by magnumripper** [comment]
I did the same change to all HMAC formats which lead to segfault (caught by Travis) in MD5 so I fixed it and SHA1 in d1808c1. But I'm confused now. Was this an actual bug in eg. HMAC-MD5 that has been uncaught by self-tests and the Test Suite for years? I can't believe that. Are the MD5 and SHA1 interfaces different, so we could actually use smaller size there? I'm too dizzy right now from staring at all those different size macros. Anyway I believe the issues are really fixed now but the remaining possible issue is we might use more memory than needed for MD5 and possibly SHA1.

**Comment by magnumripper** [comment]
Here's the net changes for SHA384 over the last three commits
```diff
diff --git a/src/hmacSHA384_fmt_plug.c b/src/hmacSHA384_fmt_plug.c
index df1caa3..e468fe5 100644
--- a/src/hmacSHA384_fmt_plug.c
+++ b/src/hmacSHA384_fmt_plug.c
@@ -26,7 +26,7 @@ john_register_one(&fmt_hmacSHA384);
 #ifdef _OPENMP
 #include <omp.h>
 #ifdef MMX_COEF_SHA512
-#define OMP_SCALE               1024 // scaled on scaled core i7-quad HT
+#define OMP_SCALE               1024 // scaled on core i7-quad HT
 #else
 #define OMP_SCALE               512 // scaled K8-dual HT
 #endif
@@ -45,6 +45,7 @@ john_register_one(&fmt_hmacSHA384);
 
 #define PAD_SIZE			128
 #define BINARY_SIZE			(384/8)
+#define BINARY_SIZE_512			(512/8)
 #define BINARY_ALIGN			8
 
 #ifndef MMX_COEF_SHA512
@@ -115,8 +116,8 @@ static void init(struct fmt_main *self)
 	crypt_key = mem_calloc_tiny(bufsize, MEM_ALIGN_SIMD);
 	ipad = mem_calloc_tiny(bufsize, MEM_ALIGN_SIMD);
 	opad = mem_calloc_tiny(bufsize, MEM_ALIGN_SIMD);
-	prep_ipad = mem_calloc_tiny(sizeof(*prep_ipad) * self->params.max_keys_per_crypt * PAD_SIZE, MEM_ALIGN_SIMD);
-	prep_opad = mem_calloc_tiny(sizeof(*prep_opad) * self->params.max_keys_per_crypt * PAD_SIZE, MEM_ALIGN_SIMD);
+	prep_ipad = mem_calloc_tiny(sizeof(*prep_ipad) * self->params.max_keys_per_crypt * BINARY_SIZE_512, MEM_ALIGN_SIMD);
+	prep_opad = mem_calloc_tiny(sizeof(*prep_opad) * self->params.max_keys_per_crypt * BINARY_SIZE_512, MEM_ALIGN_SIMD);
 	for (i = 0; i < self->params.max_keys_per_crypt; ++i) {
 		crypt_key[GETPOS(BINARY_SIZE, i)] = 0x80;
 		((ARCH_WORD_64*)crypt_key)[15 * MMX_COEF_SHA512 + (i & (MMX_COEF_SHA512-1)) + (i >> (MMX_COEF_SHA512>>1)) * SHA512_BUF_SIZ * MMX_COEF_SHA512] = (BINARY_SIZE + PAD_SIZE) << 3;
@@ -187,6 +188,7 @@ static void set_key(char *key, int index)
 	memcpy(saved_plain[index], key, len);
 	saved_plain[index][len] = 0;
 
+#if PAD_SIZE < PLAINTEXT_LENGTH
 	if (len > PAD_SIZE) {
 		unsigned char k0[BINARY_SIZE];
 		SHA512_CTX ctx;
@@ -205,6 +207,7 @@ static void set_key(char *key, int index)
 		}
 	}
 	else
+#endif
 	while(((temp = JOHNSWAP64(*keyp++)) & 0xff00000000000000)) {
 		if (!(temp & 0x00ff000000000000) || !(temp & 0x0000ff0000000000))
 		{
@@ -251,6 +254,7 @@ static void set_key(char *key, int index)
 	memset(ipad[index], 0x36, PAD_SIZE);
 	memset(opad[index], 0x5C, PAD_SIZE);
 
+#if PAD_SIZE < PLAINTEXT_LENGTH
 	if (len > PAD_SIZE) {
 		SHA512_CTX ctx;
 		unsigned char k0[BINARY_SIZE];
@@ -268,6 +272,7 @@ static void set_key(char *key, int index)
 		}
 	}
 	else
+#endif
 	for(i=0;i<len;i++)
 	{
 		ipad[index][i] ^= key[i];
@@ -330,7 +335,6 @@ static int crypt_all(int *pcount, struct db_salt *salt)
 {
 	int count = *pcount;
 	int index = 0;
-	int local_new_keys = new_keys;
 #if defined(_OPENMP) || MAX_KEYS_PER_CRYPT > 1
 	int inc = 1;
 #endif
@@ -348,17 +352,17 @@ static int crypt_all(int *pcount, struct db_salt *salt)
 	{
 #ifdef MMX_COEF_SHA512
 		ARCH_WORD_64 *pclear;
-		if (local_new_keys) {
+		if (new_keys) {
 			SSESHA512body(&ipad[index * SHA512_BUF_SIZ * 8],
-			            (ARCH_WORD_64*)&prep_ipad[index * BINARY_SIZE],
+			            (ARCH_WORD_64*)&prep_ipad[index * BINARY_SIZE_512],
 			            NULL, SSEi_MIXED_IN|SSEi_CRYPT_SHA384);
 			SSESHA512body(&opad[index * SHA512_BUF_SIZ * 8],
-			            (ARCH_WORD_64*)&prep_opad[index * BINARY_SIZE],
+			            (ARCH_WORD_64*)&prep_opad[index * BINARY_SIZE_512],
 			            NULL, SSEi_MIXED_IN|SSEi_CRYPT_SHA384);
 		}
 		SSESHA512body(cur_salt,
 		            (ARCH_WORD_64*)&crypt_key[index * SHA512_BUF_SIZ * 8],
-		            (ARCH_WORD_64*)&prep_ipad[index * BINARY_SIZE],
+		            (ARCH_WORD_64*)&prep_ipad[index * BINARY_SIZE_512],
 		            SSEi_MIXED_IN|SSEi_RELOAD|SSEi_OUTPUT_AS_INP_FMT);
 		// NOTE, SSESHA384 will output 64 bytes. We need the first 48 (plus the 0x80 padding).
 		// so we are forced to 'clean' this crap up, before using the crypt as the input.
@@ -368,7 +372,7 @@ static int crypt_all(int *pcount, struct db_salt *salt)
 		pclear[14] = pclear[15] = 0;
 		SSESHA512body(&crypt_key[index * SHA512_BUF_SIZ * 8],
 		            (ARCH_WORD_64*)&crypt_key[index * SHA512_BUF_SIZ * 8],
-		            (ARCH_WORD_64*)&prep_opad[index * BINARY_SIZE],
+		            (ARCH_WORD_64*)&prep_opad[index * BINARY_SIZE_512],
 		            SSEi_MIXED_IN|SSEi_RELOAD|SSEi_OUTPUT_AS_INP_FMT);
 #else
 		SHA512_CTX ctx;
@@ -462,7 +466,6 @@ static int get_hash_5(int index) { return crypt_key[index][0] & 0xffffff; }
 static int get_hash_6(int index) { return crypt_key[index][0] & 0x7ffffff; }
 #endif
 
-
 struct fmt_main fmt_hmacSHA384 = {
 	{
 		FORMAT_LABEL,
```
We just needed to use BINARY_SIZE_512 for SHA384 ipad/opad just like we need to use BINARY_SIZE_256 in the SHA224 format.

**Comment by magnumripper** [comment]
Oh, and both Travis and TS are happy now. I always have a hard time with HMAC. They are conceptually simple but always makes me fuk up when trying to optimize. OpenCL is hard, SIMD is harder.
