### ISSUE TITLE
bash completion bug

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1066]
When I start my bash shell, I get this:

```
bash: /JtR/bleed/run/john.bash_completion: line 565: syntax error near unexpected token `('
bash: /JtR/bleed/run/john.bash_completion: line 565: `		--show=?([Ll]|[Ll][Ee]|[Ll][Ee][Ff]|[Ll][Ee][Ff][Tt]))'
```

ubuntu-64 in a VM.  To install jtr bash completion, I simply added ```  . /JtR/bleed/run/john.bash_completion```  to my ~/.bashrc file

**Comment by frank-dittrich** [comment]
What does ` shopt -p extglob` print on your ubuntu system?
On my fedora 20 system I get
```
(bleeding-jumbo)run $ shopt -p extglob
shopt -s extglob
```

If you get ` shopt -u extglob` instead, you need to enable extended pattern matching features by running `shopt -s extglob` before you source  john.bash_completion.

**Comment by frank-dittrich** [comment]
See also section "Prerequisites" of doc/README.bash-completion:
```
        Prerequisites

The bash completion for john requires bash version >= 4,
and extended pattern matching features enabled.
If the command
        shopt -p extglob
prints
        shopt -s extglob
then the extended pattern matching features are enabled.
If this command
prints
        shopt -u extglob
then they are disabled.
```

**Comment by frank-dittrich** [comment]
May be I should add a comment similar to the one in john.bash_completion's lines 12-20 closer to the source code lines which cause the problems when extended pattern matching is disabled, i.e., line 565.

**Comment by jfoug** [comment]
Extended patterns are turned on, AND I am running 4.3.11(1) bash (with the recent patches).

```
$ shopt -p extglob
shopt -s extglob
```

**Comment by frank-dittrich** [comment]
The only explanation is that `shopt -s extglob` is processed after you sourced john.bash_completion.
Can you put the line
```
shopt -p extglob
```
immediately before
```
. /your_path/john.bash_completion
```
into your ~/.bashrc file?

I have

```
shopt -u extglob
shopt -p extglob
. /home/fd/git/JtR/run/john.bash_completion
```
in my ~/.bashrc now, and I get

```
[fd@f20xs ~]$ bash
shopt -u extglob
bash: /home/fd/git/JtR/run/john.bash_completion: line 565: syntax error near unexpected token `('
bash: /home/fd/git/JtR/run/john.bash_completion: line 565: `		--show=?([Ll]|[Ll][Ee]|[Ll][Ee][Ff]|[Ll][Ee][Ff][Tt]))'
```
when I start a new shell or xterm.

**Comment by frank-dittrich** [comment]
I just tested this with ubuntu 14.10.

Adding
```
. /home/fd/git/JtR/run/john.bash_completion
```
at the end of my /home/fd/.bashrc file works for me.
After opening a new terminal, bash completion just works for john.

**Comment by magnumripper** [comment]
I get a very similar error on Super. It has bash 4.1.2

**Comment by magnumripper** [comment]
I tried enbling extglob on Super and then source JtR bash completion.
```
$ ../run/john --t<TAB>bash: _get_comp_words_by_ref: command not found
```

**Comment by frank-dittrich** [comment]
looks like bash completion is not installed on super.
Neither /etc/bash_completion nor /usr/share/bash-completion/bash_completion exist.

**Comment by frank-dittrich** [comment]
On well it should work.

**Comment by jfoug** [comment]
I put the load line at the bottom of the .bashrc and it is working fine.    Gonna mark this as PEBCAK and close it.
