### ISSUE TITLE
xsha512 TS error 

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1068]
```
(master)test $ ./jtrts.pl -v -type xsha512 --stoponerror
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp_memdbg-ex_asan [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.
--pot=NAME option is valid
--encoding=NAME option is valid
all.chr (../run/all.chr) not found
alnum.chr found, inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8 added as a capability
Types to filter on:
xsha512
Capabilities in this build of john:
jumbo core inc local_pot_valid encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8

form=XSHA512                      guesses: 1496 -show=1496 0:00:00:07 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
Exiting on error. The .pot file ./tst.pot contains the found data
The command used to run this test was:

../run/john -ses=./tst  -pot=./tst.pot XSHA512_tst.in --wordlist=pw.dic -form=xsha512
```

Error occurs even for OMP_NUM_THREADS=1.

**Comment by jfoug** [comment]
It is missing these lines:

```
u7-XSHA512:$LION$745047650e9404e797d113ad3fa48760e5e869ab635506902870062f6b3b641aa9fcf1e2da9fa4615c5f4a5b25e878d66846d1bd3105b29555a35d6d8b2befb0424c4dcb:7:0: ::
u6-XSHA512:385134620c94659833f1ca01c754b7107b939553affb73fa7ac5baa55cf5fa56fca681a66a5a523c159c95fb954e2467f6892e11edeb32a9f337ad035c5f78172ef3290f:6:0:::
u8-XSHA512:4d427948417495c64b4833a44bc59dba227c710729767ffb9ef4c7f4b19303f1ccb7be92c13245682b0f13953f655f8d497eeae28c6eef63c1afc5e3ec8e9bc589af283b:8:0:1::
u16-XSHA512:66593248cb82266da947f143563ddaf9b5875c3122254a465c9fe65e8d2fd9fdbe1fb82f18fd640e8261c4d39e766975bb8c29821b8db638d8173b50539cb2185b8d0536:16:0:▒::
```

So it is missing a space, a null password, a '1' and a single upper bit set byte.  All are 0 to 1 byte long.

That gives something to look against.

**Comment by jfoug** [comment]
This also only affects SIMD.  I undef'd mmx_coef, and a non-SIMD build (after having to make a patch to source) works fine (all 1500).

**Comment by magnumripper** [comment]
Due to how set_key() is coded we should definitely add permanent test vectors for 0-5 characters.

**Comment by magnumripper** [comment]
I think the below fixes bugs, but not the bug we're seeing
```patch
diff --git a/src/XSHA512_fmt_plug.c b/src/XSHA512_fmt_plug.c
index cee3d72..9eb2272 100644
--- a/src/XSHA512_fmt_plug.c
+++ b/src/XSHA512_fmt_plug.c
@@ -261,7 +263,7 @@ static void set_key(char *key, int index)
        if (key[2] == 0) {wucp[GETPOS(6, index)] = 0x80; wucp[GETPOS(7, index)] = 0; goto key_cleaning; }
        wucp[GETPOS(6, index)] = key[2];
        ++len;
-       if (key[2] == 0) {wucp[GETPOS(7, index)] = 0x80;}
+       if (key[3] == 0) {wucp[GETPOS(7, index)] = 0x80; goto key_cleaning; }
        wucp[GETPOS(7, index)] = key[3];
        ++len;
 
```

**Comment by magnumripper** [comment]
> Due to how set_key() is coded we should definitely add permanent test vectors for 0-5 characters.

To be safe I think we really need test vectors for all length between 0 and at least 13.

**Comment by jfoug** [comment]
I have a better fix.  I start the buffers out 'right', and inc the pointer prior to going into the 'main' loop.  Before I started buffer 1 MMX_COEF past start, so the problem was key cleaning did not clean the 2nd element, IF the pw was under 5 bytes long.

**Comment by jfoug** [comment]
But what you found was a bug also (for a 3 byte password).

**Comment by jfoug** [comment]
The prob lem started here:


	ARCH_WORD_64 *keybuffer = &((ARCH_WORD_64 *)saved_key)[(index&(MMX_COEF_SHA512-1)) + (index>>(MMX_COEF_SHA512>>1))*SHA512_BUF_SIZ*MMX_COEF_SHA512 + MMX_COEF_SHA512];

I changed to 	

ARCH_WORD_64 *keybuffer = &((ARCH_WORD_64 *)saved_key)[(index&(MMX_COEF_SHA512-1)) + (index>>(MMX_COEF_SHA512>>1))*SHA512_BUF_SIZ*MMX_COEF_SHA512];

**Comment by magnumripper** [comment]
I reckoned you were working on it, so I exercised by just looking at the code :-)  But I could not spot the cleaning problem, it looked right to me.

**Comment by jfoug** [comment]
Me to when I wrote it, BUT it was not.  We had no test case under 4, so the bug was not exercised.

**Comment by magnumripper** [comment]
Hm but TS still fails here?

**Comment by magnumripper** [comment]
Ah you only committed that other thing yet

**Comment by jfoug** [comment]
0177995 is the fix.
