### ISSUE TITLE
sha256crypt/sha512crypt format: not handling shorter salts (GPU only)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1077]
```
(bleeding-jumbo)run $ ./john --test=0 --format=sha256crypt
Will run 8 OpenMP threads
Testing: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 128/128 SSE4.1 4x]... (8xOMP) FAILED (cmp_all(142))
```

But test suite works with --skip-self-test:

```
(master)test $ ./jtrts.pl -type sha256crypt -v -stoponerror -passthru="--skip-self-test"
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp_dbg [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.
--pot=NAME option is valid
--encoding=NAME option is valid
all.chr (../run/all.chr) not found
alnum.chr found, inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8 added as a capability
Types to filter on:
sha256crypt
Capabilities in this build of john:
jumbo core inc local_pot_valid encode_valid utf8 cp1252 cp1251 koi8r cp437 cp737 cp850 cp858 cp866 iso8859-1 iso8859-15 inc_alnum_ee8763c850dee8e4b88ef547a8ed39b8

form=sha256crypt                  guesses: 1500 0:00:00:03 DONE  [PASSED]
.pot CHK:sha256crypt              guesses: 1500 0:00:00:02 DONE  [PASSED] (1500 val-pwd)

form=sha256crypt-new              guesses: 1500 0:00:00:05 DONE  [PASSED]
.pot CHK:sha256crypt-new          guesses: 1500 0:00:00:01 DONE  [PASSED] (1500 val-pwd)

All tests passed without error.  Performed 2 tests.  Time used was 18 seconds
```

A non-debug build works without problems

**Comment by jfoug** [comment]
What exactly get this:

1.8.0.2-jumbo-1-bleeding_omp_dbg

(the _dbg)   can you try without that and list good or bad success?

**Comment by frank-dittrich** [comment]
On 03/07/2015 11:43 PM, JimF wrote:
> What exactly get this:
> 
> 1.8.0.2-jumbo-1-bleeding_omp_dbg


If I understand your question correctly, it is:

$ make -s distclean ; ./configure && make -s -j 16 debug

> 
> (the _dbg) can you try without that and list good or bad success?

A non-debug build works without problems.

**Comment by magnumripper** [comment]
I bet ASAN together with the debug target will expose the bug immediately.

**Comment by frank-dittrich** [comment]
> I bet ASAN together with the debug target will expose the bug immediately.

No, it doesn't.

```
(bleeding-jumbo)run $ ./john --test=0 --format=sha256crypt
Will run 8 OpenMP threads
Testing: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 128/128 SSE4.1 4x]... (8xOMP) FAILED (cmp_all(142))

(bleeding-jumbo)run $ ./john --list=build-info 
Version: 1.8.0.2-jumbo-1-bleeding_omp_dbg_asan
Build: linux-gnu 64-bit AVX-autoconf
Arch: 64-bit LE
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
File locking: fcntl()
Compiler version: 4.8.3 20140911 (Red Hat 4.8.3-7)
gcc version: 4.8.3
OpenSSL library version: 01000105f
OpenSSL 1.0.1e-fips 11 Feb 2013
GMP library version: 5.1.2
Regex library version: 1.2	(loaded: 1.2.3)
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

Built with these debugging options
	'#define DEBUG' set
	ASan (Address Sanitizer debugging)

```

**Comment by jfoug** [comment]
There is ```#ifdef DEBUG ``` within the 'common' code that wraps some longer tests. I bet one of those is the problem (possibly MAX length or something).  If that is the case, I should be able to find this is a second.

**Comment by jfoug** [comment]
The problem is the short salts.

ITW, will there ever be short salts???  Or are these just fabrications that do not happen??

**Comment by frank-dittrich** [comment]
http://www.akkadia.org/drepper/SHA-crypt.txt

The description doesn't mention salt length (or I just didn't search correctly.
But the sample code has
```
/* Maximum salt string length.  */
#define SALT_LEN_MAX 16
```

So, we have to assume salt length can vary.

**Comment by jfoug** [comment]
d979508 'fixes' this for SIMD.

NOTE, I think it is also broken on cuda/opencl.  It 'can' be easily worked around, by simply forcing invalid for non 16 byte salts.

The fix in SIMD was sort of easy, since I do a sorting algorithm. I simply made a larger table, one for each salt length.  Then the proper length passwords all get placed together, so they use the same number of limbs for each step.   I have no idea how this was done on cuda/opencl, but my initial testing on opencl appears to show it is a problem.

**Comment by jfoug** [comment]
I am leaving open, until we figure it out for the GPU formats.

**Comment by jfoug** [comment]
This also is an issue for cryptsha512 then.

**Comment by jfoug** [comment]
I agree that by reading http://www.akkadia.org/drepper/SHA-crypt.txt it does sound like this is NOT fixed at 16 bytes, but limited to a max of 16 bytes.  The CPU an SIMD should be working, now, however.

**Comment by frank-dittrich** [comment]
Ulrich Drepper put another gem into the sample implementation:

```
salt_len = MIN (strcspn (salt, "$"), SALT_LEN_MAX);
```
So, do we we also need to support this crap? I hope not.
At least, fedora 20 doesn't accept the password
```
U*U*U*U*
````
after changing the hash from
```
$5$LKO/Ute40T3FNF95$U0prpBQd4PloSGU0pnpM4z9wKn4vZ1.jsrzQfPqxph9
```
to
```
$5$LKO/Ute40T3FNF95678$U0prpBQd4PloSGU0pnpM4z9wKn4vZ1.jsrzQfPqxph9
```

But if some system follows that reference implementation, we would reject hashes as invalid that other systems / applications accept as valid.

This java implementation truncates the salt at the max. salt length:

ftp://ftp.arlut.utexas.edu/pub/java_hashes/Sha256Crypt.java

**Comment by frank-dittrich** [comment]
Google finds several instances of
```
salt_len = MIN (strcspn (salt, "$"), SALT_LEN_MAX);
```
But as long as none of these systems/applications really generate salts longer than 16 bytes, it probably doesn't matter.

**Comment by jfoug** [comment]
> Ulrich Drepper put another gem into the sample implementation:

I find this in the doc page, so the doc implementation are at odds:

```
The input string used for the salt parameter of the crypt function can
potentially be much longer.  But since the salt string is truncated to
at most 16 characters the size of the output string is limited.
```

**Comment by jfoug** [comment]
Our current valid will not allow longer than 16.  We 'could' remove that, and then within the salt() function, simply grab up to first 16 bytes, and (possibly) modify binary to handle a longer salt.  Not really that big of a deal, IF it is something that could be seen ITW.

**Comment by jfoug** [comment]
Updated test suite for all pw len up to 35 for all salt lengths (1 to 16)

https://github.com/magnumripper/jtrTestSuite/commit/262a026344b511cc9dba4c0e8c16d4341a718638

NOTE, I did not add lines for cuda or opencl, yet. NOTE, I do not think they will find 1600. I would have to figure out how many they 'should' find.

**Comment by jfoug** [comment]
SHA512crypt handled SIMD in 561f95b . I am going to check to make 'sure' non-SIMD is actually fine (it should be, since this bug is cause by having to group for vectorizations)

**Comment by jfoug** [comment]
This issue is now 'closed' for CPU/SIMD.  @magnumripper can you test this on opencl/cuda?   I think the TS has the right expected PW count for each of them.

**Comment by jfoug** [comment]
NOTE, we are not handling the longer than 16 byte salts at this time (if such things actually exist). In that case, we would have to truncate properly within salt, change valid to handle it, and also change pass_gen.pl to handle it, if a salt was given longer than 16 bytes.  I personally do  not think this is worth the time.

**Comment by magnumripper** [comment]
> we are not handling the longer than 16 byte salts

Unless someone starts using that, we shouldn't. And why would anyone? 16 bytes is plenty.

**Comment by jfoug** [comment]
It is not that it would be 'used'. The spec says 16 bytes max. It is that the example code published (and @frank-dittrich search of the web seems to say it is in code), 'allows' a longer salt to be in the hash string.  BUT only the first 16 bytes are used.

Right now, valid will fail, and I am 99% sure that all salts would have to account for this. binary already would handle it just fine.

**Comment by magnumripper** [comment]
I see. But still: Until we see this being an actual problems IRL, let's ignore it.

**Comment by jfoug** [comment]
I do not think there are salts < 16 bytes (IRL), other than the phony ones provided by KoreLogic. But now the code handles them.  It does not cause any slowdown, and 'is' in the writeup of the spec.   Handing a 200 byte salt would be zero impact also.  Valid would have to be ok, salt() only runs at startup.  The 'used' salt would only be 16 bytes.  There is no 'loss', other than time to write it.  And we have probably spend more time here chatting about it that than it would have taken to code it, lol.  Handling shorter salts actually took coding and research to get it right. Not hard, just took a couple hours of time.

**Comment by frank-dittrich** [comment]
I don't know whether some system generates such hashes with shorter salts, but fedora 20 at least accepts those hashes, i.e. --format=crypt cracks them, and if I manually put such a hash into /etc/shadow, I can login.

**Comment by magnumripper** [comment]
> Handing a 200 byte salt would be zero impact also. Valid would have to be ok, salt() only runs at startup. The 'used' salt would only be 16 bytes. There is no 'loss', other than time to write it.

OK maybe we should do this. It doesn't sound very error-prone.

**Comment by magnumripper** [comment]
```
$ ./jtrts.pl -type -stoponerror sha256crypt-opencl
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [darwin14.1.0 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sha256crypt-opencl           guesses: 1500 0:00:00:31 DONE  [PASSED]
.pot CHK:sha256crypt-opencl       guesses: 1500 0:00:00:31 DONE  [PASSED] (1500 val-pwd)

form=sha256crypt-opencl-new       guesses: 1070 -show=1070 0:00:00:41 DONE : Expected count(s) (1030)  [!!!FAILED1!!!]
.pot CHK:sha256crypt-opencl-new   guesses: 1070 0:00:00:11 DONE  [PASSED] (1070 val-pwd)

form=sha256crypt-opencl-xsalt     guesses: 1290 -show=1290 0:00:00:41 DONE : Expected count(s) (1296)  [!!!FAILED1!!!]
.pot CHK:sha256crypt-opencl-xsalt guesses: 1287 -show=1287 0:00:00:17 DONE : Expected count(s) (1296)  [!!!FAILED4!!!]  (1287 val-pwd  0 inval-pwd)

Some tests had Errors. Performed 3 tests.  2 errors  1 errors reprocessing the .POT files
Time used was 202 seconds
```

**Comment by jfoug** [comment]
To me, that sounds like it is missing them. It will not miss a 'huge' number, but it will miss some.  It has to be a specific length salt/password combo that would get stuck into the wrong 'group'. I would have certainly expected more than 6 to have been missed, but I think this shows openCL is not properly dealing with shorter salts.

The one guessing too many, could be a mistake on my part, trying to compute how many passwords would be guessed.  I have a perl script that helps, but if I compute things wrong, then I would be off.  Since it is even 10, and since the pot reload also found same count, I think it could be that I mis computed how many 24 byte passwords are in there.

The 'xsalt' one to me screams it is not handling short salts correctly, espcially since the .pot rerun missed more.

**Comment by claudioandre** [comment]
Anything special about your build (OSX only)? I'm getting the 1296 result here. 

```
$ ./jtrts.pl -type -stoponerror sha256crypt-opencl
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit SSE2-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sha256crypt-opencl           guesses: 1500 0:00:00:35 DONE  [PASSED]
.pot CHK:sha256crypt-opencl       guesses: 1500 -show=1500 0:00:00:33 DONE : Expected count(s) (1389)(1500)  [!!!FAILED4!!!]  (1500 val-pwd  1 inval-pwd)

form=sha256crypt-opencl-new       guesses: 1070 -show=1070 0:00:00:48 DONE : Expected count(s) (1030)  [!!!FAILED1!!!]
.pot CHK:sha256crypt-opencl-new   guesses: 1070 -show=1070 0:00:00:12 DONE : Expected count(s) (1030)  [!!!FAILED4!!!]  (1070 val-pwd  1 inval-pwd)

form=sha256crypt-opencl-xsalt     guesses: 1296 0:00:00:41 DONE  [PASSED]
.pot CHK:sha256crypt-opencl-xsalt guesses: 1296 -show=1296 0:00:00:19 DONE : Expected count(s) (1296)  [!!!FAILED4!!!]  (1296 val-pwd  1 inval-pwd)

Some tests had Errors. Performed 3 tests.  1 errors  3 errors reprocessing the .POT files
Time used was 223 seconds
```

**Comment by claudioandre** [comment]
The invalid password message below means what? I mean, I'm not sure I found what is causing it.

```
d_show_line2 = 
1500 password hashes cracked, 0 left
1 invalid passwords
1500 valid passwords
```

**Comment by jfoug** [comment]
Usually nothing. The new code reads stdout data looking for proper cracked passwords. That logic Rorschach problems but it still needs work.

**Comment by claudioandre** [comment]
Jim, In order to check the 1070 versus 1030 (guesses), I tried to change the the CPU format and limit it to plaintext 24

```
../run/john sha256crypt_new_tst.in --wordlist=pw-new.dic -form=sha256crypt
../run/john sha256crypt_new_tst.in --show -form=sha256crypt
1070 password hashes cracked, 430 left
---
rm pot file
---
../run/john sha256crypt_new_tst.in --wordlist=pw-new.dic -form=sha256crypt-opencl
../run/john sha256crypt_new_tst.in --wordlist=pw-new.dic -form=sha256crypt-opencl
1070 password hashes cracked, 430 left
```

Is there a script that produces the 1030?

**Comment by claudioandre** [comment]
Super shows the error. I will investigate
```
./jtrts.pl sha256crypt-opencl
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sha256crypt-opencl           guesses: 1500 0:00:00:42 DONE  [PASSED]
.pot CHK:sha256crypt-opencl       guesses: 1500 -show=1500 0:00:00:42 DONE : Expected count(s) (1389)(1500)  [!!!FAILED4!!!]  (1500 val-pwd  1 inval-pwd)

form=sha256crypt-opencl-new       guesses: 1057 -show=1057 0:00:00:52 DONE : Expected count(s) (1030)  [!!!FAILED1!!!]
.pot CHK:sha256crypt-opencl-new   guesses: 1049 -show=1049 0:00:00:14 DONE : Expected count(s) (1030)  [!!!FAILED4!!!]  (1049 val-pwd  1 inval-pwd)

form=sha256crypt-opencl-xsalt     guesses: 1287 -show=1287 0:00:00:42 DONE : Expected count(s) (1296)  [!!!FAILED1!!!]
.pot CHK:sha256crypt-opencl-xsalt guesses: 1275 -show=1275 0:00:00:19 DONE : Expected count(s) (1296)  [!!!FAILED4!!!]  (1275 val-pwd  1 inval-pwd)

Some tests had Errors. Performed 3 tests.  2 errors  3 errors reprocessing the .POT files
Time used was 263 seconds

```

**Comment by jfoug** [comment]
It looks like 1070 is correct.  I mis computed the count for len==24.  I have  a script that I tell it how large the password length was for the 'computation', what length I am interested in, and the count.  Many slower formats DO NOT have 1500, but might have 150, 20, 30, 50, etc, with same salt.

So if the width computed was 35, I am interested in len 24 and I did 150, then I would give those to my command line script, and it would tell me this:

```
$ ./count_finder.pl 35 24 150
Found 150 of length 35  (required 586 total lines to do)
Found 107 of length 24
```

This tells me that we need to put at least 586 (600 is better) count to reduce the pw-new.dic down to pw-600.dic, so when there are missing data it stops as quickly as possible.  It also says that there were only 107 passwords of length 24, which verifies that 1070 is correct, since it is 10 salts of 150 passwords in the input file.  The input file was created length 35 max (for CPU format).

I will change this in the TS now, that even the script is telling me I put the wrong amount in there.

**Comment by claudioandre** [comment]
>Ulrich Drepper put another gem into the sample implementation:

JFYI: this is already committed in JtR.
```
len = (len > SALT_LENGTH ? SALT_LENGTH : len);
```

**Comment by jfoug** [comment]
Look at the crypt-all in cpu.  I 'group' passwords.  They are grouped so that ALL work being done requires exactly the same number of SHA256 limbs at each step of the process for ALL passwords. I had to make an array off array of 'break' points.

**Comment by jfoug** [comment]
```
for (pos = ciphertext; *pos && *pos != '$'; pos++);
if (!*pos || pos < ciphertext || pos > &ciphertext[SALT_LENGTH]) return 0;
```

This is in valid in sha256crypt-common.c (used by all formats).  The ``` pos > &ciphertext[SALT_LENGTH])  ``` will cause ALL hashes with salt > 16 to fail valid().  Thus even though you have that code at a later point, you will never see a salt length > SALT_LENGTH.

**Comment by jfoug** [comment]
> Super shows the error. I will investigate

The 'error' should only be happening on the '--xsalt' input file. That it is happening on the normal pw-new.dic input file (which ONLY has 16 byte salts), tells me that there may be some other issue that overall is a problem (password length related likely).

**Comment by magnumripper** [comment]
For me, it passes TS (with 1070 and 1296) when using the CPU device or the nvidia GT650M. Using the Intel HD4000 (which was what I used earlier) it fails last test:
```
form=sha256crypt-opencl-xsalt     guesses: 1290 -show=1290 0:00:00:35 DONE : Expected count(s) (1296)  [!!!FAILED1!!!]
.pot CHK:sha256crypt-opencl-xsalt guesses: 1287 -show=1287 0:00:00:16 DONE : Expected count(s) (1296)  [!!!FAILED4!!!]  (1287 val-pwd  0 inval-pwd)
```

**Comment by magnumripper** [comment]
CUDA is fine but awfully slow and only support up to length 15 (is that a relevant limit?)
```
$ ./jtrts.pl sha256crypt-cuda
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [darwin14.1.0 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sha256crypt-cuda             guesses: 1389 0:00:01:36 DONE  [PASSED]
.pot CHK:sha256crypt-cuda         guesses: 1389 0:00:01:44 DONE  [PASSED] (1389 val-pwd)

form=sha256crypt-cuda             guesses:  630 0:00:00:19 DONE  [PASSED]
.pot CHK:sha256crypt-cuda         guesses:  630 0:00:00:21 DONE  [PASSED] (630 val-pwd)

form=sha256crypt-cuda-xsalt       guesses:  864 0:00:00:25 DONE  [PASSED]
.pot CHK:sha256crypt-cuda-xsalt   guesses:  864 0:00:00:29 DONE  [PASSED] (864 val-pwd)

All tests passed without error.  Performed 3 tests.  Time used was 346 seconds
```

**Comment by magnumripper** [comment]
BTW the CUDA test is missing the `-new` tag in the middle test.

**Comment by magnumripper** [comment]
I tried bumping CUDA to length 24 and that sort of works, but some bug shows up: It finds 1050 in the -new test and 1280 in the -xsalt one. That does not match a length limit:
```
$ LC_ALL=C ./pw_len_finder.sh sha256crypt_new_tst.in 
num	len	sum
(...)
60	15	630
70	16	700
90	17	790
70	18	860
50	19	910
40	20	950
40	21	990
20	22	1010
20	23	1030
40	24	1070
30	25	1100
(...)
```

**Comment by magnumripper** [comment]
Bumping CUDA to 23 for now in 63a84004. Maybe it should do 24 but has a bug somewhere. Anyway 23 does work fine.

**Comment by jfoug** [comment]
23 bytes IS one of the cut-offs.  24 bytes is a whole different set of single step lengths for 2 of the steps.  24 bytes IS the first byte in a higher level for both sha256 and sha512, so this actually makes sense.

**Comment by magnumripper** [comment]
But it does crack some 24-byte ones...

**Comment by jfoug** [comment]
I do not know the code, so really can not comment.  All I know is that when I went to vectorize them it was VERY important to group them properly.  The GPU stuff may or may not have these constraints to work with.

**Comment by jfoug** [comment]
Have we ever validated (yes or no), that shorter salts are a problem within the GPU code?   To find out, we probably will need to run outside of the TS, so that we can really see what is happening.

**Comment by magnumripper** [comment]
I think they never had that problem. Is that not what the -xsalt tests check?

**Comment by jfoug** [comment]
That is exactly what that test does

**Comment by magnumripper** [comment]
OpenCL and CUDA pass all tests now.

**Comment by frank-dittrich** [comment]
Let the jtrts GPU tests run in a `--random --seed=$i` loop for a while...

**Comment by claudioandre** [comment]
> For me, it passes TS (with 1500/1070/1296) when using the CPU device or the nvidia GT650M. Using the Intel HD4000 (which was what I used earlier) it fails last test:

So, it is failing only on some AMD boards (anyone disagrees?). **That said, I will check for any AMD "optimization" inside OpenCL and report later.**

Below, NVIDIA's GPU on super works as expected. 
```
./jtrts.pl sha256crypt-opencl --passthru="-dev=5"
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sha256crypt-opencl           guesses: 1500 0:00:00:24 DONE  [PASSED]
.pot CHK:sha256crypt-opencl       guesses: 1500 0:00:00:24 DONE  [PASSED] (1500 val-pwd)

form=sha256crypt-opencl-new       guesses: 1070 0:00:00:30 DONE  [PASSED]
.pot CHK:sha256crypt-opencl-new   guesses: 1070 0:00:00:08 DONE  [PASSED] (1070 val-pwd)

form=sha256crypt-opencl-xsalt     guesses: 1296 0:00:00:26 DONE  [PASSED]
.pot CHK:sha256crypt-opencl-xsalt guesses: 1296 0:00:00:11 DONE  [PASSED] (1296 val-pwd)

All tests passed without error.  Performed 3 tests.  Time used was 160 seconds
```

**Comment by claudioandre** [comment]
> I do not know the code, so really can not comment. All I know is that when I went to vectorize them it was VERY important to group them properly. The GPU stuff may or may not have these constraints to work with.

It makes sense to group in sha256crypt-gpu. But, I am not sure if it helps a lot in a real run since only divergent "threads" have to stop execution in a mixed list. 

- And it will happen (could happen) inside a CU even for a sorted candidates list.
- Or I should set max_key_per_crypt to a big number (much bigger than GWS) and make a few calls to  the OpenCL code inside each crypt_all() in a way to "group" and avoid any "divergent thread".

Opinions?

**Comment by claudioandre** [comment]
@magnumripper I don't trust super (and bull could be in use). So, if you found anything in sha512, please, let me know.

Thanks

**Comment by magnumripper** [comment]
>> Using the Intel HD4000 (which was what I used earlier) it fails last test:

> So, it is failing only on some AMD boards (anyone disagrees?).

Not sure how you meant that, but Intel HD4000 is not an AMD board.

**Comment by magnumripper** [comment]
> @magnumripper I don't trust super (and bull could be in use)

How about well? Is it too slow?

**Comment by magnumripper** [comment]
> - Or I should set max_key_per_crypt to a big number (much bigger than GWS) and make a few calls to  the OpenCL code inside each crypt_all() in a way to "group" and avoid any "divergent thread".

That's how I have pictured what needs to be done. Otherwise it will be cheaper to just live with the diverging threads.

**Comment by claudioandre** [comment]
> Not sure how you meant that, but Intel HD4000 is not an AMD board.

My fault, I saw the HD and presumed it was AMD.

**Comment by claudioandre** [comment]
For the records: to run without errors on super (not sure how well it will behave on Intel). 
- It means "skip optimizations". I've failed to nail the problem to a better solution (yet, I hope).

```
_TYPE=0 ./jtrts.pl sha256crypt-opencl
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.4-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=sha256crypt-opencl           guesses: 1500 0:00:00:48 DONE  [PASSED]
.pot CHK:sha256crypt-opencl       guesses: 1500 -show=1500 0:00:00:47 DONE : Expected count(s) (1389)(1500)  [!!!FAILED4!!!]  (1500 val-pwd  2 inval-pwd)

form=sha256crypt-opencl-new       guesses: 1070 0:00:00:59 DONE  [PASSED]
.pot CHK:sha256crypt-opencl-new   guesses: 1070 -show=1070 0:00:00:15 DONE : Expected count(s) (1070)  [!!!FAILED4!!!]  (1070 val-pwd  2 inval-pwd)

form=sha256crypt-opencl-xsalt     guesses: 1296 0:00:00:48 DONE  [PASSED]
.pot CHK:sha256crypt-opencl-xsalt guesses: 1296 -show=1296 0:00:00:22 DONE : Expected count(s) (1296)  [!!!FAILED4!!!]  (1296 val-pwd  2 inval-pwd)

Some tests had Errors. Performed 3 tests.  3 errors reprocessing the .POT files
Time used was 288 seconds
```

**Comment by claudioandre** [comment]
> How about well? Is it too slow? 

BTW: I can't see a ./configure warning as discussed some time ago in JtR lists.

```
make[1]: Leaving directory `/space/home/claudio/bleeding/src/escrypt'
/tmp/cccvyNSE.s: Assembler messages:
/tmp/cccvyNSE.s:434: Error: no such instruction: `vfmadd312sd .LC5(%rip),%xmm0,%xmm2'
make[1]: *** [formats.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```

**Comment by magnumripper** [comment]
A workaround for the "no such instruction" is `./configure --disable-native-tests`

**Comment by claudioandre** [comment]
Please, consider applying https://gist.github.com/claudioandre/d382ebf003f1cef2dd0a

The PLAINTEXT_LENGTH is 23

```
$ LC_ALL=C ./pw_len_finder.sh sha512crypt_Xsalts_new_tst.in
num	len	sum
[...]
64	19	1136
32	20	1168
16	24	1184
```

**Comment by magnumripper** [comment]
> Please, consider applying https://gist.github.com/claudioandre/d382ebf003f1cef2dd0a

Done
