### ISSUE TITLE
legacy build fails

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1079]
```
(bleeding-jumbo)src $ make -s distclean ; make -s clean ; make -s -f Makefile.legacy linux-x86-64-native
In file included from sph_haval.h:65:0,
                 from dynamic_big_crypt.c:34:
sph_types.h:50:24: fatal error: autoconfig.h: No such file or directory
 #include "autoconfig.h"
                        ^
compilation terminated.
In file included from sph_tiger.h:48:0,
                 from tiger_plug.c:36:
sph_types.h:50:24: fatal error: autoconfig.h: No such file or directory
 #include "autoconfig.h"
                        ^
compilation terminated.
make[1]: *** [dynamic_big_crypt.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [tiger_plug.o] Error 1
make: *** [linux-x86-64-native] Error 2
```

**Comment by kholia** [comment]
I am heavily in favor of dropping the legacy build system. It's a waste of time.

**Comment by frank-dittrich** [comment]
I don't disagree.
While this bug looks like it is easy to fix, new bugs will creep in because nobody tests legacy builds anymore.
I just noticed the problem because I wanted to verify whether a problem in an autoconf debug build would occur on a legacy debug build as well.

**Comment by kholia** [comment]
Done in commit d9e2daacd64663145dd850944ecb96ad260397c5.

@magnumripper hopefully, this is a sane decision.

**Comment by magnumripper** [comment]
I was a minute away from stopping you. Revert, and let's think this over. I'd like it to be kept at least in unused/ for now. Or kept as-is but documented as not supported.

**Comment by kholia** [comment]
It is reverted now. I am all ears :-)

**Comment by magnumripper** [comment]
For a starter, we have to change doc/INSTALL and perhaps some more files first.

**Comment by kholia** [comment]
@magnumripper @frank-dittrich OK, I am working towards this now.

I will move the file to ``unused`` and will fix / remove all references to it. Sounds good?

**Comment by frank-dittrich** [comment]
Good idea. Move it to unused, or just make legacy builds fail with a comment that legacy builds are currently not supported.
When we are about to release the next jumbo, just check how much trouble it would be to fix the issues that come up

**Comment by magnumripper** [comment]
I'm on the road today, will try to come up with some sane idea. One problem is merging core changes. That is already a problem, since core's file is called Makefile and our version of it is generated.

Yes, keeping it and ensuring it works for releases is definitely an option.

**Comment by frank-dittrich** [comment]
Make sure to check
```
git grep Makefile.legacy
```
and
```
git grep "legacy build"
```
output.

**Comment by magnumripper** [comment]
From now on, legacy builds are not supported. They may work from time to time (and I endorse anyone to "fix" them as problems are seen), but they are not supported for end users. See #1084.
