### ISSUE TITLE
Bug in Siemens-s7 format

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1089]
I have put the issue to john-dev list to ensure it is a bug.

According to the valid() function, the hash below can also pass the valid check.

"$siemens-s7$1$599fe00cdb61f76cc6e949162f22c95943468acb$0"
                                                                                                          ^
So, there is a bug in get_binary().

line 120:  static void *get_binary(char *ciphertext)
line 121:  {
line 122:     static union {
line 123:        unsigned char c[BINARY_SIZE];
line 124:        ARCH_WORD dummy;
line 125:    } buf;
line 126:    unsigned char *out = buf.c;
line 127:    char *p;
line 128:    int i;
line 129:    p = strrchr(ciphertext, '#39;) + 1;
line 130:    for (i = 0; i < BINARY_SIZE; i++) {
line 131:        out[i] = 
line 132:                  (atoi16[ARCH_INDEX(*p)] << 4)  |
line 133:                  atoi16[ARCH_INDEX(p[1])];
line 134:        p += 2;
line 135:    }
line 136: 
line 137:    return out;
line 138: }

In line 129, p points to "0", and BINARY_SIZE is 20. But in line 132 and 133 it tries 
to visit *p and p[1], also p += 2, thus it will visit the unknown ares!

**Comment by magnumripper** [comment]
Why did you close this issue without a comment? And why did you open another very similar issue instead?

**Comment by loverszhaokai** [comment]
Sorry, I made a mistake in describe the problem. So I closed the old issue and recreate a new issue. 
And I find I should have edit the old issue. Sorry.

**Comment by magnumripper** [comment]
OK that's fine. Next time you edit it instead. Please also make use of [markdown](https://guides.github.com/features/mastering-markdown/) when applicable. I hope you follow our issues and discussions, we make heavy use of markdown (especially Syntax highlighting)

**Comment by loverszhaokai** [comment]
OK, I will try to **use the markdown**.

**Comment by magnumripper** [comment]
:+1:
