### ISSUE TITLE
Some refactoring before AVX2 and AVX-512

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1099]
@jfoug 

Would it not make sense to drop MMX_COEF_SHA256 and just use MMX_COEF instead? I see no reason to use another one - in both cases it's about how many uint32's you process with a SIMD instruction.

Also, I think MMX_COEF_SHA512 should better be called MMX_COEF_64. Because it's not really about SHA512, it's about uint64.

Taking it a step further we could consider refactoring them to SIMD_COEF_32 and SIMD_COEF_64. MMX is so 1996...

**Comment by magnumripper** [comment]
On the other hand, we'll probably want to use SHA256_SSE_PARA and SHA512_SSE_PARA for future interleaving, as these are actually tied to the respective function. They too could be refactored (eg. MD4_SSE_PARA -> MD4_SIMD_PARA) if we wanted to.

**Comment by jfoug** [comment]
The reason that MMX_COEF and MMX_COEF_SHA256 were split was to preserve MMX ability for the md5/md4/sha1 functions. If we were drop MMX building for those, and only allow SSE and above, then yes, they 'could' be merged into a single SIMD_COEF_32  and another SIMD_COEF_64.  But IIRC, you spent a little time actually validating that an MMX build was still able to be done using the autoconf suite.  Now again, we 'could' drop it.  But should we? 

At some time, yes, we probably should.  Is that time now?

**Comment by jfoug** [comment]
How about:

MMX_COEF (if we drop true mmx compatibility, then we could drop this)
SIMD_COEF_32    (should mirror MMX_COEF)
SIMD_COEF_64
SIMD_PARA_MD[45]
SIMD_PARA_SHA[1][256][512] 

I would rather have same front prefix for all of the para, and append the function type to that, vs other direction, but that certainly is not something that has to be.

These are all define enums, but I do agree, getting them more consistent does make things a bit easier.  I did a count of MMX_COEF and there were about 2400 lines or so in all source/header files, and a little over 300 SSE_PARA lines.

**Comment by jfoug** [comment]
I took it on, and did the SHA2 functions, since they are cut and dry only SSE2+ code.  I changed them to SIMD_COEF_[32][64] and SIMD_PARA_SHA[256][512]

f2da5cf

**Comment by jfoug** [comment]
So now, for this type cleanup, we have MD5/MD4/SHA1 COEF and PARA left to do.

**Comment by jfoug** [comment]
With change to bfb3f52  there now are no MMX_COEF_* strings left in source.

**Comment by magnumripper** [comment]
> The reason that MMX_COEF and MMX_COEF_SHA256 were split was to preserve MMX ability for the md5/md4/sha1 functions. If we were drop MMX building for those, and only allow SSE and above, then yes, they 'could' be merged into a single SIMD_COEF_32 and another SIMD_COEF_64. But IIRC, you spent a little time actually validating that an MMX build was still able to be done using the autoconf suite. Now again, we 'could' drop it. But should we?

At some time, yes, we probably should. Is that time now?

We already dropped that support long ago as far as I can remember. What we do have is MMX support for *core* stuff, and for Alain's NT format but that's it. And neither of them use MMX_COEF iirc.

**Comment by magnumripper** [comment]
> SIMD_PARA_MD[45]
> SIMD_PARA_SHA[1][256][512]

Why reverse them? The current ones are eg. SHA1_SSE_PARA so it seems logical to me to use SHA1_SIMD_PARA. Not that it matters.

**Comment by jfoug** [comment]
I thought it would be better to have all of these be

SIMD_WHAT_TYPE

So there is SIMD_PARA and SIMD_COEF (for listing how many and how they interleave), and then the types are types,   MD5/MD4/.....SHA512 etc.

That was the only reason why.

**Comment by jfoug** [comment]
> We already dropped that support long ago as far as I can remember. 

I am pretty sure that intrinsics 'can' do MMX.  I may be wrong on that. If so, then lets simply drop MMX_COEF, and rename it to SIMD_COEF_32

**Comment by magnumripper** [comment]
> I am pretty sure that intrinsics 'can' do MMX.

You mean we could theoretically make sse-intrinsics.c produce MMX code if applicable? This has crossed my mind too but making that work is probably not worth it.

Anyway, the current code paths for MMX-only (if we have any legacy code still in there) is either
```
#if defined(MMX_COEF) && !defined(MD5_SSE_PARA)
    (code for MMX-only)
#endif
```
or
```
#if defined(MMX_COEF) && MMX_COEF == 2
    (code for MMX-only)
#endif
```
so there is no need at all to separate MMX_COEF and SIMD_COEF_32. Although we don't have to rush it either.

**Comment by magnumripper** [comment]
I have a patch ready for dropping MMX_COEF for good. Seems to be problem free. I'm just not sure if I want to commit it.

**Comment by magnumripper** [comment]
I can't seem to build 32-bit MMX even with current tree
```
Undefined symbols for architecture i386:
  "_else384224_Init", referenced from:
      _DynamicFunc__SHA384_crypt_input1_append_input2 in dynamic_big_crypt.o
      _DynamicFunc__SHA512_crypt_input1_append_input2 in dynamic_big_crypt.o
      _DynamicFunc__SHA384_crypt_input2_append_input1 in dynamic_big_crypt.o
      _DynamicFunc__SHA512_crypt_input2_append_input1 in dynamic_big_crypt.o
      _DynamicFunc__SHA384_crypt_input1_overwrite_input1 in dynamic_big_crypt.o
      _DynamicFunc__SHA512_crypt_input1_overwrite_input1 in dynamic_big_crypt.o
      _DynamicFunc__SHA384_crypt_input1_overwrite_input2 in dynamic_big_crypt.o
      ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../run/john] Error 1
make: *** [default] Error 2
```
This did work some time ago.

**Comment by jfoug** [comment]
I would not know why not.  If we are not going to support MMX, then lets dump it totally, switch to useing SIMD_COEF_32, and remove all of the MMX_* stuff.

There is quite a bit of code in places I can clean up.  I have lots of this kind of stuff:

(x<<(MMX_COEF>>1))  (or things similar.  That could easily be changed to (x<<2)  or x*4  The only reason for a lot of these type things (even things like (MMX_COEF-1) vs 3 for an 'and') could easily be removed.  dyna has a ton of that.   It is all right, and works for MMX_COEF==4 or MMX_COEF==2 but if MMX_COEF (SIMD_COEF_32) will always be 4, then it is time to dump it.

**Comment by jfoug** [comment]
Yup, those would all need SIMD stuff.  Without them, there will be calls used (which 'could' be commented out) in the fmt which have not functions because in the _bigcrypt.c they are not available.

So mmx alone has been down at least 8 months.

**Comment by magnumripper** [comment]
No no no, we'll soon have SIMD_COEF_32 == 8 for AVX2 or 16 for AVX-512, that is the whole point of this operation

**Comment by magnumripper** [comment]
> So mmx alone has been down at least 8 months.

Sigh. We are supposed to build MMX properly. It's just that we'll not **use** MMX instructions (nor any other SIMD instructions) for anything but core formats (and possibly NT).

**Comment by jfoug** [comment]
Ok, I see.  BUT I have to make 100% sure the logic holds for 4 and 8, like it did for 2 and 4.

if we need to * by MMX coef, frequently it is    (x<<(COEF>>1))  So for 2 that was <<=1  for 4 that is <<=2 and for 8 it will be <<=4.   NOPE, that fails.

So that logic has to be redone anyway.   BUT I can easily do the same logic for 4 and 8 (as long as I do not have to worry about 2).

**Comment by magnumripper** [comment]
> if we need to * by MMX coef, frequently it is (x<<(COEF>>1)) So for 2 that was <<=1 for 4 that is <<=2 and for 8 it will be <<=4. NOPE, that fails.

This is exactly what I want to address, without rushing it. So things like that are "ready" when some GSoC intern starts to add cool stuff to sse-instrinsics.c.

**Comment by magnumripper** [comment]
On October 9 2014, I could build MMX. Things have fallen apart since.

**Comment by jfoug** [comment]
Those type items are the biggest _problem_ we have with multiple possible values for MMX_COEF (now SIMD_COEF_32).   There are only 2 or 3 of these patterns.   If we have only 2 values, that are base-2 apart from each other, it's easy.  If we have 3   (2,4,8), then it is harder to do.

**Comment by jfoug** [comment]
It is in the last couple days, when I added SHA2-64 code SIMD to dyna.  I probably could figure out what went wrong there.

**Comment by magnumripper** [comment]
In order not to make things like GETPOS slower, we could simply define a shift macro in arch.h
eg.
```
#if __AVX2__
#define SIMD_COEF_32 8
#define SIMD_SHIFT 3
...
```

**Comment by jfoug** [comment]
Oh shit, I just reread what you wrote.  So now, we will have this:

SIMD_COEF_32 be any of 4, 8, 16.  I already will have to address this.   

we 'could' do this easily with *=    The division (mod) is easy. It is always &=(COEF-1), since all coef's are base-2

**Comment by jfoug** [comment]
> define a shift macro in arch.h

Probably the best way.

**Comment by magnumripper** [comment]
Let's not rush this, we still have plenty of time to think!

**Comment by jfoug** [comment]
I am now seeing why this WAS such a good idea to do now.  Try to get it all down and 'normalized', before we get slammed with multiple possible COEF's.

**Comment by magnumripper** [comment]
Yes, I was afraid it would get out of hands if we just left this mess to someone not used to it, LOL!

**Comment by jfoug** [comment]
I will get mmx working.   It will have NO mmx from intrinsics. It will be all oSSL, with the exceptions of things like x86.S (or whatever use MMX).  All of the md5/sha-X used outside of core will be oSSL.

**Comment by jfoug** [comment]
Oh, it probably will be a mess, but very good to get it as smooth as we can NOW.

**Comment by jfoug** [comment]
We probably 'should' use some MMX value in the core stuff.  Then make ALL non-core stuff SIMD, so that it separates itself from that old mmx compatibility.

**Comment by magnumripper** [comment]
> We probably 'should' use some MMX value in the core stuff. Then make ALL non-core stuff SIMD, so that it separates itself from that old mmx compatibility.

I think that is pretty much the situation already. DES never used any of our MMX_COEF or PARA stuff. And core MD5crypt does not use SIMD at all - that is a Jumbo-only enhancement.

**Comment by jfoug** [comment]
Then we simply stop mentioning MMX, switch to SIMD, and list that SSE is the first version of SIMD that we support.  Then find all the 'multiple' coef issues (most were found in the MMX/SSE2 days, we just have to update them), and I 'think' that we are golden.

One other issue, is MEM_ALIGN_SIMD going to be valid???  We may have to adjust that also.

**Comment by jfoug** [comment]
Could you check in your MMX_COEF to SIMD_COEF_32 changes, and then I will get on trying to 'normalize' properly the mults and mods (shift/and)  For SHA1, there still are mults, since we have 5 items, and there are possible mults for some others.  But mostly I use shift/and where I can, and those obviously will require changing for COEF > 4

**Comment by magnumripper** [comment]
Done in 97af1ec

**Comment by magnumripper** [comment]
Note, an MMX-only build does not define SIMD_COEF (MMX_COEF) at all in arch.h so I'm not sure what triggers the problem in Dynamic now? Maybe this is a problem with any non-SIMD build?

**Comment by jfoug** [comment]
What problem are you getting,  I get this:

```
-ldl  -lbz2 aes/aes.a -o ../run/john
Undefined                       first referenced
 symbol                             in file
else384224_Init                     dynamic_big_crypt.o
ld: fatal: symbol referencing errors. No output written to ../run/john
collect2: ld returned 1 exit status
```

There also was a 'not pre-defined' warning upon compile.  I have no idea what this var is.  Looks like something for sha384 during init.

**Comment by jfoug** [comment]
> I'm not sure what triggers the problem in Dynamic now? Maybe this is a problem with any non-SIMD build?

Try after 9fd743e

**Comment by magnumripper** [comment]
64-bit "any" build does not work (`CC="gcc -mno-mmx" --disable-native-tests`)
```
Undefined symbols for architecture x86_64:
  "_SSESHA1body", referenced from:
      _DoSHA1_crypt_f_sse in dynamic_big_crypt.o
      _DoSHA1_crypt_sse in dynamic_big_crypt.o
      _crypt_all._omp_fn.0 in XSHA_fmt_plug.o
      _crypt_all._omp_fn.0 in agilekeychain_fmt_plug.o
      _crypt_all._omp_fn.0 in aix_ssha_fmt_plug.o
      _hash_plugin_check_hash in androidfde_fmt_plug.o
      _crypt_all._omp_fn.0 in blockchain_fmt_plug.o
      ...
  "_SSESHA256body", referenced from:
      _DoSHA256_crypt_f_sse in dynamic_big_crypt.o
      _DoSHA256_crypt_sse in dynamic_big_crypt.o
      _crypt_all._omp_fn.0 in SybaseASE_fmt_plug.o
      _crypt_all._omp_fn.0 in aix_ssha_fmt_plug.o
      _crypt_all._omp_fn.0 in cryptsha256_fmt_plug.o
      _pbkdf2_sha256_sse.constprop.2 in django_fmt_plug.o
      _crypt_all._omp_fn.0 in hmacSHA224_fmt_plug.o
      ...
  "_SSESHA512body", referenced from:
      _DoSHA512_crypt_f_sse in dynamic_big_crypt.o
      _DoSHA512_crypt_sse in dynamic_big_crypt.o
      _crypt_all._omp_fn.0 in XSHA512_fmt_plug.o
      _pbkdf2_sha512_sse.constprop.2 in aix_ssha_fmt_plug.o
      _crypt_all._omp_fn.0 in bitcoin_fmt_plug.o
      _crypt_all._omp_fn.0 in blackberry_ES10_fmt_plug.o
      _pbkdf2_sha512_sse.constprop.3 in cloudkeychain_fmt_plug.o
      ...
  "_SSEmd4body", referenced from:
      _DynamicFunc__crypt_md4_in1_to_out2 in dynamic_fmt.o
      _DynamicFunc__crypt_md4 in dynamic_fmt.o
      _DynamicFunc__crypt_md4_in2_to_out1 in dynamic_fmt.o
      _DynamicFunc__crypt2_md4 in dynamic_fmt.o
      _DoMD4_crypt_f_sse in dynamic_big_crypt.o
      _DoMD4_crypt_sse in dynamic_big_crypt.o
      _crypt_all in nt2_fmt_plug.o
      ...
  "_SSEmd5body", referenced from:
      _DynamicFunc__crypt_md5_to_input_raw_Overwrite_NoLen in dynamic_fmt.o
      _DynamicFunc__crypt_md5_to_input_raw_Overwrite_NoLen_but_setlen_in_SSE in dynamic_fmt.o
      _DynamicFunc__crypt_md5_to_input_raw in dynamic_fmt.o
      _DynamicFunc__crypt_md5_in1_to_out2 in dynamic_fmt.o
      _DynamicFunc__crypt_md5 in dynamic_fmt.o
      _DynamicFunc__crypt_md5_in2_to_out1 in dynamic_fmt.o
      _DynamicFunc__crypt2_md5 in dynamic_fmt.o
      ...
  "_md5cryptsse", referenced from:
      _crypt_all._omp_fn.0 in MD5_fmt.o
  "_nt_crypt_all_8859_1_x86_64", referenced from:
      _fmt_NT_init in NT_fmt_plug.o
  "_nt_crypt_all_x86_64", referenced from:
      _fmt_NT_init in NT_fmt_plug.o
      _fmt_NT in NT_fmt_plug.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [../run/john] Error 1
make: *** [default] Error 2
```

**Comment by magnumripper** [comment]
32-bit "any" build works (`CC="gcc -m32 -mno-mmx" --disable-native-tests`)

**Comment by magnumripper** [comment]
32-bit MMX does not work, it seems it tries to build x86-64.o? (`CC="gcc -m32 -mmmx -mno-sse2"`)

**Comment by magnumripper** [comment]
32-bit MMX works fine with `CC="gcc -m32 -mmmx -mno-sse2" --disable-native-tests --host=i686-mac-darwin`

**Comment by jfoug** [comment]
> 64-bit "any" build does not work ``` (CC="gcc -mno-mmx" --disable-native-tests)```

Trying to build under cygwin was a little more difficult.  Here is my config line:

``` CC="gcc -mno-mmx -march=x86-64 -mno-sse" --disable-native-tests)```

After that (without the no-sse I get ALL kinds of compile errors, when windows.h is inluced, since __SSE2__=1 is defined).  But I get these problems:

```
 memdbg.o  -g  -L/usr/local/lib -lkernel32   -lssl -lcrypto  -fopenmp -lgmp       -lm -lz -ldl -lcrypt  -lbz2 aes/aes.a -o ../run/john
john.o:john.c:(.rdata$.refptr.fmt_sha1_ng[.refptr.fmt_sha1_ng]+0x0): undefined reference to `fmt_sha1_ng'
john.o:john.c:(.rdata$.refptr.fmt_rawSHA512_ng[.refptr.fmt_rawSHA512_ng]+0x0): undefined reference to `fmt_rawSHA512_ng'
john.o:john.c:(.rdata$.refptr.fmt_rawSHA256_ng[.refptr.fmt_rawSHA256_ng]+0x0): undefined reference to `fmt_rawSHA256_ng'
john.o:john.c:(.rdata$.refptr.fmt_rawSHA1_LI[.refptr.fmt_rawSHA1_LI]+0x0): undefined reference to `fmt_rawSHA1_LI'
collect2: error: ld returned 1 exit status
Makefile:1092: recipe for target '../run/john.exe' failed
make[1]: *** [../run/john.exe] Error 1
make[1]: Leaving directory '/cygdrive/c/phpbb/johnripper/bleed-64/src'
Makefile:180: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by jfoug** [comment]
Ok ,after a re ./configure with that ,it worked fine. I had 'patched' Makefile with "-march=x86-64 -mno-sse -m64", but the fmt_*.h files had those other objects in there.  After a rerun of ./configure with right params, it built a 64-any just fine on cygwin.

So for me, getting an 'any' worked with this:

```
./configure CC="gcc -mno-mmx -mno-sse -m64 -march=x86-64" --disable-native-tests
```

**Comment by jfoug** [comment]
$ ./configure CC="gcc -mno-mmx -mno-sse -m32 -march=i686" --disable-native-tests --disable-opencl
checking build system type... __x86_64-unknown-cygwin__
checking host system type... x86_64-unknown-cygwin
checking whether to compile using MPI... no
checking for gcc... gcc -mno-mmx -mno-sse -m32 -march=i686
checking whether the C compiler works... no
configure: error: in `/c/phpbb/johnripper/bleed-64/src':
configure: error: C compiler cannot create executables
See `config.log' for more details

Even with -m32 and -march=i686  I still host and build system of x86_64, so I do not know how you are doing 32 bit (unless it is a 32 bit linux)

**Comment by magnumripper** [comment]
Use eg. `-host=i686-pc-cygwin` for telling configure about your intentions. We could add some more logic but we need to be careful.

Also, doesn't -march=i686 override -mno-mmx? Perhaps it doesn't but I'd put them in this order to be sure: `-march=i686 -m32 -mno-mmx -mno-sse` (the -m32 may be redundant)

**Comment by jfoug** [comment]
On my cygw64, I can not use --host=i686-pc-cygwin  It simply will not build a exe file. But i do have cygwin32 installedd, and I am testing with that.

**Comment by magnumripper** [comment]
> On my cygw64, I can not use --host=i686-pc-cygwin It simply will not build a exe file

That is strange, I wonder why

**Comment by jfoug** [comment]
I thought I had multilib, but I may still be lacking a lot to do cross compiles.

NOTE, I get problems with XSHA and XSHA512. They bitch about the count var, since we switched it to a const int (for no real reason).

**Comment by magnumripper** [comment]
```
$ make -s distclean && ./configure CC="gcc -m32 -mmmx -mno-sse2"--host=i686-mac-darwin  --disable-native-tests --disable-openmp-for-fast-formats --disable-cuda --disable-opencl && make -sj8
checking build system type... x86_64-apple-darwin14.1.0
checking host system type... i686-mac-darwin
```

**Comment by magnumripper** [comment]
Yeah that const patch probably has some regressions. BTW there's a LOT of function prototypes that should use const and that would make more good, but I'd rather have it in core before Jumbo.

**Comment by magnumripper** [comment]
I see no problem with count being const in those formats... What does it say?

**Comment by jfoug** [comment]
```
XSHA_fmt_plug.c: In function ‘crypt_all’:
XSHA_fmt_plug.c:356:57: error: ‘count’ is predetermined ‘shared’ for ‘shared’
 #pragma omp parallel for default(none) private(i) shared(ctx_salt, count, saved_key, saved_key_length, crypt_out)
                                                         ^
Makefile:1324: recipe for target 'XSHA_fmt_plug.o' failed
```

**Comment by jfoug** [comment]
function proto's and const make a WHOLE lot more sense, than a const used like the count const.  The count const 'might' have a tiny impact on code emitted.  const on many of our prototypes will have drastic impact on code emitted.  Const on some of our char * provide a world of safety also.  The problem is you get into a const avalanche.  Since solar never designed properly for constness (and probably some VERY old compilers would have had problems), it is a very long row to hoe to get it all put in properly.

**Comment by jfoug** [comment]
The 32 biit no-sse worked fine, and built an 'any.  I am trying now with -mmmx and without the -march=i686  and see if I can get a 32 bit MMX build.  If I can do that, I will try a 64 bit MMX, but I think that is a unicorn, and no reason to support that (it may not build anyway).

**Comment by jfoug** [comment]
This worked just fine (32 bit cygwin)

```./configure CC="gcc -mmmx -mno-sse -m32" --disable-native-tests --disable-opencl```

Got MMX on some core items, but not on any of the sse-intrisic things, and I think we agreed that it was going to be that way.

I also did this on 64 bit (have not built yet, just configured)

```./configure CC="gcc -mmmx -mno-sse -m64" --disable-native-tests --disable-opencl```

Configure output looks good, and lists x86_64 MMX, 64-bit LE.  I will see how the build goes.

**Comment by jfoug** [comment]
MMX for 64 bit was not happy on build:

```
$ make -sj8
mssql12_fmt_plug.c:184:13: warning: ‘clear_keys’ defined but not used [-Wunused-function]
 static void clear_keys()
             ^
In file included from sse-intrinsics.c:45:0:
/usr/lib/gcc/x86_64-pc-cygwin/4.8.3/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"
 # error "SSE2 instruction set not enabled"
   ^
sse-intrinsics.c:1624:20: error: unknown type name ‘__m128i’
 void SSESHA256body(__m128i *data, ARCH_WORD_32 *out, ARCH_WORD_32 *reload_state, unsigned SSEi_flags)
                    ^
Makefile:1324: recipe for target 'sse-intrinsics.o' failed
make[1]: *** [sse-intrinsics.o] Error 1
make[1]: *** Waiting for unfinished jobs....
pp.c: In function ‘do_prince_crack’:
pp.c:1431:22: warning: implicit declaration of function ‘fileno’ [-Wimplicit-function-declaration]
                      fileno(read_fp), 0);
                      ^
/usr/bin/ar: creating aes.a
Makefile:180: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by magnumripper** [comment]
> I will try a 64 bit MMX, but I think that is a unicorn, and no reason to support that (it may not build anyway).

No there's no reason to, and core core probably doesn't support that. What would be nice to accomplish though, is 64-bit "any" build. It used to work at some point. There's no reason at all to "support" that either *for end users*, but it's a valuable target for debugging generic 64-bit builds.

I guess we can build it if hacking or replacing the arch.h between "./configure" and "make"

**Comment by magnumripper** [comment]
> What would be nice to accomplish though, is 64-bit "any" build on an x86_64.

Actually from the current problems I get, I strongly suspect a build like that will work just fine on Linux (and that might be were I tried it in the past) while OSX seem to have system headers that really expects SSE2 to be there. So maybe we're fine and I'll just forget about 64-any on OSX.

**Comment by magnumripper** [comment]
OTOH I could probably hack up some arch.h that allows build non-MMX non-SSE while not actually using -mno-sse2, which is likely what a core "make generic" ends up like.

**Comment by jfoug** [comment]
Add -no-sse to your config gcc command, and I bet it will work for you. I got x86-64-any to build easily.  Read above posts (about 10 up or so).  It was done on cygwin.  I will try on my ubuntu, but I bet it is easy.

**Comment by jfoug** [comment]
```
$ ./configure CC="gcc -mno-mmx -mno-sse2" --disable-native-tests

$ make -s clean & make -sj8
/usr/bin/ar: creating aes.a
Make process completed.
[1]+  Done                    make clean



```

Then -test=0 worked with all passing. (and oSSL for algo).   Seems a 64 bit 'any' build to me.  You simply have to force OFF having __SSE2__ defined. If not, then it IS building a SIMD build, no matter what.

**Comment by magnumripper** [comment]
> Add -mno-sse to your config gcc command, and I bet it will work for you.

Nope, I get this
```
$ make -s distclean && ./configure CC="gcc -mno-mmx -mno-sse -mno-sse2" --disable-native-tests --disable-openmp-for-fast-formats && make -sj8
(...)
timer.c: In function 'sTimer_GetSecs':
timer.c:105:1: error: SSE register return with SSE disabled
 {
 ^
make[1]: *** [timer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```
My gcc is assuming it can use the FPU for math operations on x86-64 (despite -mno-sse etc). This can supposedly be fixed by adding `-msoft-float` to CFLAGS (and `-lsoft-fp` to LDFLAGS) but I get the same error with those switches.

**Comment by jfoug** [comment]
timer.c is ancillary code I wrote, that might be able to be done in other ways (but the double return of seconds IS the easiest). Isn't there float code in other parts of JtR ?

**Comment by magnumripper** [comment]
Sure, timer.c is probably just the first one it hits. Anyway this is more a problem with OSX than anything else, so lets ignore it for now.

**Comment by magnumripper** [comment]
What if we set up buffers for AVX2, and then run SSE2 (or AVX/XOP) twice (offset) on them? As far as I can imagine, that would work just fine (and would be somewhat similar to SIMD_PARA).

In fact, will the buffers differ at all from SSE2 w/ PARA 2, if you consider the intrinsics function being a black box? Do they need to? I'm just thinking out loud.

**Comment by magnumripper** [comment]
> Do they need to? I'm just thinking out loud.

I think they really need to be different. For a while I thought we could layout the buffers in some canonical format, but that probably won't work at all.

**Comment by magnumripper** [comment]
Dang, there's a lot of hardcoded "4" and "2" in sse-intrinsics.c. I'm in the process of fixing it.

@jfoug is this right? VS64 is just a shorthand for SIMD_COEF_64 so with AVX it's a no-op. But will it be correct for AVX2?
```diff
                i=0;
                //SHA512_PARA_DO(i)
                {
-                       vstore((vtype*)&out[i*(16/2)*8+( 0/2)], a);
-                       vstore((vtype*)&out[i*(16/2)*8+( 4/2)], b);
-                       vstore((vtype*)&out[i*(16/2)*8+( 8/2)], c);
-                       vstore((vtype*)&out[i*(16/2)*8+(12/2)], d);
-                       vstore((vtype*)&out[i*(16/2)*8+(16/2)], e);
-                       vstore((vtype*)&out[i*(16/2)*8+(20/2)], f);
-                       vstore((vtype*)&out[i*(16/2)*8+(24/2)], g);
-                       vstore((vtype*)&out[i*(16/2)*8+(28/2)], h);
+                       vstore((vtype*)&out[i*4*VS64*8+0*VS64], a);
+                       vstore((vtype*)&out[i*4*VS64*8+1*VS64], b);
+                       vstore((vtype*)&out[i*4*VS64*8+2*VS64], c);
+                       vstore((vtype*)&out[i*4*VS64*8+3*VS64], d);
+                       vstore((vtype*)&out[i*4*VS64*8+4*VS64], e);
+                       vstore((vtype*)&out[i*4*VS64*8+5*VS64], f);
+                       vstore((vtype*)&out[i*4*VS64*8+6*VS64], g);
+                       vstore((vtype*)&out[i*4*VS64*8+7*VS64], h);
                }
        }
        else
@@ -2144,17 +2113,16 @@ void SSESHA512body(vtype* data, ARCH_WORD_64 *out, ARCH_WORD_64 *reload_state, u
                i=0;
                //SHA512_PARA_DO(i)
                {
-                       vstore((vtype*)&(out[i*(32/2)+( 0/2)]), a);
-                       vstore((vtype*)&(out[i*(32/2)+( 4/2)]), b);
-                       vstore((vtype*)&(out[i*(32/2)+( 8/2)]), c);
-                       vstore((vtype*)&(out[i*(32/2)+(12/2)]), d);
-                       vstore((vtype*)&(out[i*(32/2)+(16/2)]), e);
-                       vstore((vtype*)&(out[i*(32/2)+(20/2)]), f);
-                       vstore((vtype*)&(out[i*(32/2)+(24/2)]), g);
-                       vstore((vtype*)&(out[i*(32/2)+(28/2)]), h);
+                       vstore((vtype*)&(out[i*8*VS64+0*VS64]), a);
+                       vstore((vtype*)&(out[i*8*VS64+1*VS64]), b);
+                       vstore((vtype*)&(out[i*8*VS64+2*VS64]), c);
+                       vstore((vtype*)&(out[i*8*VS64+3*VS64]), d);
+                       vstore((vtype*)&(out[i*8*VS64+4*VS64]), e);
+                       vstore((vtype*)&(out[i*8*VS64+5*VS64]), f);
+                       vstore((vtype*)&(out[i*8*VS64+6*VS64]), g);
+                       vstore((vtype*)&(out[i*8*VS64+7*VS64]), h);
                }
```

**Comment by claudioandre** [comment]
> I'm in the process of fixing it.

Seems 'everybody' is changing the same files. Well, I'm sending a patch to magnum's mail (It is related to shared code for all files, and the initial clean up that will happen in GSoC).

**Comment by magnumripper** [comment]
Committed in 7a5c73e, thanks. I changed the new file name to rawSHA256_common_plug.c and dropped the changes to Makefile.

**Comment by magnumripper** [comment]
@zzlei I rebased my experimental branch onto latest bleeding which includes you patches, and committed in topic branch https://github.com/magnumripper/JohnTheRipper/commits/avx2. I might have broken some things. AVX2 is broken for sure, there are hard-coded vector widhts yet to find in sse-intrinsics.c

**Comment by magnumripper** [comment]
@zzlei I made you a collaborator so you can push directly to the repo if you like. If you are unsure of some patch, just do a PR anyway. Feel extra free to push to the avx2 branch, it's totally experimental anyway.

**Comment by magnumripper** [comment]
@jfoug do you own any AVX2 capable gear?

**Comment by magnumripper** [comment]
Closing this, as nearly all remaining issues are in Dynamic, #1189.
