### ISSUE TITLE
Improve the project details in Github page

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#1103]
Seems to me it is a good idea to show more information in the Github main project page, as you can see in the attached image below (notice the buttons in the bottom of the page). The obvious things include: build status, license, download link (zip or whatever). The patch is only a few lines in the top of the original README file (very easy to maintain).

Each image links to a proper file/site. To test: (https://github.com/claudioandre/JohnTheRipper/tree/readme)

![captura de tela de 2015-03-14 14 41 50](https://cloud.githubusercontent.com/assets/1702923/6652775/29b3f6d6-ca59-11e4-92a4-274dff593b7b.png)

**Comment by magnumripper** [comment]
Yeah, cool! Please make a PR, or perhaps I could just cherry-pick 8556a7d?
