### ISSUE TITLE
CPPFLAGS doesn't work in Makefile

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1105]
`./configure -h` says CPPFLAGS is for preprocessor flags, but actually it's not used in the Makefile, and setting CPPFLAGS has no effect on building. 
Maybe we can add CPPFLAGS to CFLAGSX ?

**Comment by magnumripper** [comment]
Yes we should, that is a bug.

**Comment by magnumripper** [comment]
Hm wait.. isn't CPPFLAGS used automatically by cpp? There should be no need to add them anywhere.

**Comment by magnumripper** [comment]
Fixed in 3ec8247
