### ISSUE TITLE
Mute a TestSuite error caused by an OpenCL message.

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#1112]
TestSuite is complaining because of a message we created. So, please, review (and apply) these patches:
edddd3ab9f5852937f6183622e99830c80c2c3a1
cc65a9b388e52df50997df6d5efbd60a78e10e6a

While at it, please review this (in order to avoid more differences between 'master' and me) 
ff618f808357e1599a7de374deb7480d8746b95f
e81ffc0956296f5e4636b75e7b8da63ae869a0d5
338427a308ac089cd27e3980f948295f61798ee7

This is a (in development) mask branch, it is easier cherry-pick (or wait to the moment of a PR)

**Comment by magnumripper** [comment]
o.O  Where is this branch? I can see the commits in the web gui but I don't get them when I fetch.

**Comment by magnumripper** [comment]
OK, found it. It's very weird that the links above points to magnumripper/ and not claudioandre/

**Comment by magnumripper** [comment]
Done, thanks
