### ISSUE TITLE
Drop the binary plugin code (plugin.c)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1124]
This code looks busted. I am 99% sure there are memory leaks, and I think an inf loop.  I doubt this has EVER worked, nor is ever going to be used.

Should it simply be dropped??

I am adding a comment and will check it in, then link that patch here.  I do not know the code nor have time. I really wonder if this is just a feature that someone thought that would be cool, that never got used?

**Comment by jfoug** [comment]
1094118

**Comment by magnumripper** [comment]
> Should it simply be dropped?

As long as it doesn't interfere with any other code, I think not. But we don't need to maintain this code at all.

**Comment by jfoug** [comment]
It never has been maintained, and likely never worked. It's been i the tree for 4 years.  What reason to keep it??

**Comment by magnumripper** [comment]
I won't just drop code like that without Solar's blessing. And I don't care about it enough to ask him.

That stuff is weird from the very start (closed source plugins?!) so who knows, someone may use it but not be very communicative about it.

**Comment by magnumripper** [comment]
Here's the origin of that code: http://www.openwall.com/lists/john-users/2011/09/27/1

Turns out it's same author as the OpenVMS format, which was first released as a runtime plugin. Maybe this actually is totally unused code since.

**Comment by jfoug** [comment]
Yes, this was done FOR the openVMS format, but that has since become a 'real' normal format, using the *_plug.c model.   I do not think ANYTHING has used plugin.c since, and I am 90% sure the code would not work.  

That was why I made this issue. I truly think this is just orphan code.

**Comment by magnumripper** [comment]
OK, I'll throw a question on john-users

**Comment by magnumripper** [comment]
http://www.openwall.com/lists/john-users/2015/03/19/1

**Comment by jfoug** [comment]
I saw that. I would not bet on getting any replies.

**Comment by magnumripper** [comment]
Me neither, but that leaves us with the power to do whatever we want! It will be like [this](http://www.openwall.com/lists/john-dev/2014/09/22/2)

**Comment by magnumripper** [comment]
Even Solar says we can drop it. Let's do so in a few days.
