### ISSUE TITLE
CPPFLAGS issue

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1137]
In configure.ac (about line 794), CPPFLAGS is not passed to $CPP when creating fmt_externs.h and fmt_registers. This will cause problem if we specify non-standard header path in CPPFLAGS.

**Comment by magnumripper** [comment]
That should be fixed. However, I can't immediately think of a situation where it would matter. We just run cpp to get the "plugin stanzas".

**Comment by zzlei** [comment]
I encountered this problem when configuring for MIC:
---------------------------------------------------------------
configure: creating ./fmt_externs.h
bitcoin_fmt_plug.c(19): error #2379: cannot open source file "openssl/opensslv.h"
  #include <openssl/opensslv.h>
                               ^

configure: creating ./fmt_registers.h
bitcoin_fmt_plug.c(19): error #2379: cannot open source file "openssl/opensslv.h"
  #include <openssl/opensslv.h>
                                                    ^
-----------------------------------------------------------------

That's how I noticed this issue.

**Comment by magnumripper** [comment]
The -I/path/to/openssl should(?) be in CFLAGS too. On my machine it is. Anyway, it should be fixed now.
