### ISSUE TITLE
raw SHA256 formats fail

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1139]
Only happens with full --test. It looks like something overwrote shared data (or thrashed their prepare?). Found with an ASan build, but ASan does not see any problem.
```
Testing: Raw-SHA256 [SHA256 128/128 SSE4.1 4x]... (2xOMP) FAILED (valid ($SHA256$5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8????????$SHA256$e3b0)

Testing: Raw-SHA256-ng [SHA256 128/128 SSE4.1 4x]... (2xOMP) FAILED (valid ($SHA256$5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8????????$SHA256$e3b0)
```

**Comment by magnumripper** [comment]
Non-ASan build has slightly different thrashing
```
Testing: Raw-SHA256 [SHA256 128/128 SSE4.1 4x]... (2xOMP) FAILED (valid ($SHA256$5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8c??fx?}e$SHA256$e3b0)

Testing: Raw-SHA256-ng [SHA256 128/128 SSE4.1 4x]... (2xOMP) FAILED (valid ($SHA256$5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8c??fx?}e$SHA256$e3b0)
```

**Comment by jfoug** [comment]
Is this only osx

**Comment by magnumripper** [comment]
No, the build bots see it too now. The strangest thing is that they only saw it after b042a99c while I can see it before that commit. Or did 9014d16e screw something up? That one should really be cosmetical.

**Comment by magnumripper** [comment]
I still see it after reverting to ac2e78a and doing a full distclean + configure + build.

**Comment by magnumripper** [comment]
Nailed it. It was introduced by @claudio in b9e13c38. That alloc_tiny must be a calloc_tiny.
