### ISSUE TITLE
Valid() function of ClearQuest format

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1144]
1. Is there anyway to generate hashes of ClearQuest format?

2. The valid() function **does not check salt**

* 2.1 Should **salt** be hex string or what else ?

In the below test hashes, salt is **"admin"** and **"clearquest"**

```C
static struct fmt_tests cq_tests[] = {
	{"$cq$admin$a9db7ca6", ""},
	{"$cq$admin$10200218", "admin"},
	{"$cq$admin$4cfb73f2", "password"},
	{"$cq$clearquest$a279b184", "clearquest"},
	{NULL}
};

static int valid(char *ciphertext, struct fmt_main *self)
{
	char *p, *q, *tmpstr;
	if (strncmp(ciphertext, FORMAT_TAG, TAG_LENGTH))
		return 0;

	tmpstr = strdup(ciphertext);
	q = p = &tmpstr[TAG_LENGTH];
	p[-1] = 0;
	p = strrchr(p, '$');
	if (!p)
		goto Err;

	p += 1;
	if (strlen(p) != BINARY_SIZE * 2)
		goto Err;

	if (!ishex(p))
		goto Err;

	if ((p - q) >= SALT_SIZE || p <= q)
		goto Err;

	MEM_FREE(tmpstr);
	return 1;
Err:;
	MEM_FREE(tmpstr);
	return 0;
}
```

**Comment by magnumripper** [comment]
Salt can probably be any cstring (except it can't contain ':' or '$')

**Comment by loverszhaokai** [comment]
@magnumripper  

> Salt can probably be any cstring (except it can't contain ':' or '$')

However, currently there is not check whether salt contains **':'** or **'$'**. 

And is there anyway to **generate** hashes of ClearQuest format?

**Comment by magnumripper** [comment]
> However, currently there is not check whether salt contains ':' or '$'.

I did not say a real Clearquest hash can't contain them, just that the code does not support them. ':' is never supported in JtR since that's the field delimiter. If it contained a ':' it would be split in loader so there is no point in checking for it here.

I think salt() has a bug - it should use strrchr instead of strchr. That would allow salts to contain '$'. valid() and binary() seem to allow it already.

**Comment by loverszhaokai** [comment]
@magnumripper  
>I think salt() has a bug - it should use strrchr instead of strchr.

Do you mean get_salt()? 

```C
static void *get_salt(char *ciphertext)
{
	static char salt[SALT_SIZE + 1];
	char *p, *q;

	memset(salt, 0, SALT_SIZE);
	p = ciphertext + TAG_LENGTH;
	q = strchr(p, '$');
	memcpy(salt, p, q - p);

	return salt;
}
```

Can we check the salt in valid()? The salt should not contain **':'** and **'$'**

**Comment by magnumripper** [comment]
> Do you mean get_salt()?

Yes, "get_salt" is an alias. The correct name is "salt".

> Can we check the salt in valid()? The salt should not contain ':' and '$'

Again, there is no reason to check for ':' because s tring with that character can't reach that function anyway. And '$' is probably **supposed** to be allowed.

**Comment by loverszhaokai** [comment]
@magnumripper 

Thank you for your reply. Sorry, I may not describe my problem explicitly.

The case below can pass valid()
```C
"$cq$ad$min$a9db7ca6"
```

However, in the function get_salt(), it copies **"ad"** to **salt** which should be "admin"
```C
static void *get_salt(char *ciphertext)
{
	static char salt[SALT_SIZE + 1];
	char *p, *q;

	memset(salt, 0, SALT_SIZE);
	p = ciphertext + TAG_LENGTH;
	q = strchr(p, '$');
	memcpy(salt, p, q - p);

	return salt;
}
```

**Comment by magnumripper** [comment]
Yes that is the bug I was pointing out. Just change that strchr to strrchr and I think problem is solved.

**Comment by loverszhaokai** [comment]
@magnumripper 

> Just change that strchr to strrchr and I think problem is solved.

Then it copies **"ad$min"** to salt. Does it right ?

**Comment by magnumripper** [comment]
> Then it copies "ad$min" to salt. Does it right ?

Yes if the input is "$cq$ad$min$a9db7ca6", the salt is indeed "ad$min"

> However, in the function get_salt(), it copies "ad" to salt which should be "admin"

If salt should be "admin" the hash should be "$cq$admin$a9db7ca6".

**Comment by loverszhaokai** [comment]
@magnumripper  

Thank you for your reply! I get it!
