### ISSUE TITLE
auto-tune in reset(), cosmetic regression

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1146]
I now get the "Local worksize(...)" test wedged in before DONE.
```
$ ../run/john -test -form:raw-sha256-opencl -dev=2
Device 2: GeForce GT 650M
Benchmarking: Raw-SHA256-opencl [SHA256 OpenCL]... Local worksize (LWS) 512, global worksize (GWS) 262144
DONE
Raw:	12458K c/s real, 41943K c/s virtual
```
Not quite sure what to do about it but no need to panic.

**Comment by claudioandre** [comment]
The reset() is called between the printf of [Benchmarking] and the printf of [DONE] in "core". Only a few possibilities.
- Or the printing versus reset position is changed in core.
- Or I have to print the "Local worksize(...)" after the bench process finishes (db is not NULL).
- Or mute it.

**Comment by magnumripper** [comment]
Yes I think we might want to just mute it, at normal verbosity. The auto-tune has become good enough it can normally be trusted, and that makes the figures a whole lot less interesting.

**Comment by claudioandre** [comment]
```
$ ../run/john -test -form:raw-sha256-opencl
Device 0: Juniper [AMD Radeon HD 6700 Series]
Benchmarking: Raw-SHA256-opencl [SHA256 OpenCL]... DONE
Raw:	15252K c/s real, 44150K c/s virtual
```

**Comment by magnumripper** [comment]
I cherry-picked it
