### ISSUE TITLE
--list=format-methods: asan error

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1153]
This bug is found by fuzzing the options of John.

# 1. Compile
$ export ASAN_OPTIONS='abort_on_error=1'
$ AFL_USE_ASAN=1 AFL_HARDEN=1 ./configure --enable-asan && make -sj8

# 2. Reproduce

$ ./john --list=format-methods

=================================================================
==28834== ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x00000243f080
    #0 0x7fc372f7e33a (/usr/lib/x86_64-linux-gnu/libasan.so.0.0.0+0x1533a)
    #1 0x7c0264 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_test_options_asan/run/john+0x7c0264)
    #2 0x488c6e (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_test_options_asan/run/john+0x488c6e)
    #3 0x74dca4 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_test_options_asan/run/john+0x74dca4)
    #4 0x79cdbe (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_test_options_asan/run/john+0x79cdbe)
    #5 0x7597db (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_test_options_asan/run/john+0x7597db)
    #6 0x75b188 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_test_options_asan/run/john+0x75b188)
    #7 0x7fc371804ec4 (/lib/x86_64-linux-gnu/libc-2.19.so+0x21ec4)
==28834== ABORTING
Aborted

$ asan_symbolize.py

#0 0x7fc372f7e33a in __interceptor_free ??:?
    #1 0x7c0264 in MEMDBG_off_free    src/memdbg.c:1099
    #2 0x488c6e in done                          src/dynamic_fmt.c:861 (discriminator 1)
    #3 0x74dca4 in fmt_done                   src/formats.c:112
    #4 0x79cdbe in listconf_parse_late    src/listconf.c:842
    #5 0x7597db in john_init                    src/john.c:1259
    #6 0x75b188 in main                          src/john.c:1674

**Comment by magnumripper** [comment]
This is the ASan bug, not a JtR bug.
