### ISSUE TITLE
descrypt-opencl fails self-test with Catalyst Omega

### ISSUE THREAD

**Issue by danlo8600** [magnumripper/JohnTheRipper#1172]
Hi, I have found this bug:
~./john --devices=0,1 --format=descrypt-opencl --test
Device 0: Devastator (AMD Radeon HD 7660D)
Local worksize (LWS) 64, Global worksize (GWS) 16384
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... "FAILED (get_hash [0](0))

Not work only with descrypt-opencl if I try with other work right.

I'have the latest ATI driver:
~fglrxinfo 
display: :0  screen: 0
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 7660D
OpenGL version string: 4.4.12968 Compatibility Profile Context 14.201.1006.1002

And last stable AMDSDK:
~echo $AMDAPPSDKROOT
AMDAPPSDK-2.9-1

There is a test with another crypt method that work fine:
./john --devices=0,1 --format=bcrypt-opencl --test
Device 0: Devastator (AMD Radeon HD 7660D)
Local worksize (LWS) 4, Global worksize (GWS) 1024
Benchmarking: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... DONE
Raw:	575 c/s real, 51200 c/s virtual

**Comment by danlo8600** [comment]
Another test not work:
Device 0: Devastator (AMD Radeon HD 7660D)
Building the kernel, this could take a while
Build time: 7 seconds
Local worksize (LWS) 64, global worksize (GWS) 8192
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... FAILED (get_hash[0](0))

Device 0: Devastator (AMD Radeon HD 7660D)
Building the kernel, this could take a while
Build time: 14 seconds
Local worksize (LWS) 256, global worksize (GWS) 1536
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... FAILED (get_hash[0](0))

Device 0: Devastator (AMD Radeon HD 7660D)
Local worksize (LWS) 64, Global worksize (GWS) 16384
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... FAILED (get_hash[0](0))

Device 0: Devastator (AMD Radeon HD 7660D)
OpenCL error (CL_INVALID_BUFFER_SIZE) in file (opencl_ntlmv2_fmt_plug.c) at line (143) - (Error creating device buffer)

**Comment by magnumripper** [comment]
Thank you for reporting this. There are known problems with the Omega drivers from Catalyst (eg. oclHashcat does not support them at all). If you can, please try with Catalyst 14.9 and see if problems go away (please report).

**Comment by claudioandre** [comment]
I'm using Omega and all these formats are working. Have you tried md4-opencl, md5-opencl, raw-sha256-opencl or raw-sha512-opencl?

**Comment by claudioandre** [comment]
BTW: I notice:
-  you don't have the latest version of JtR.
- devices=0,1 means (almost) nothing on a --test run. (it will only try device 0).

**Comment by danlo8600** [comment]
I have tried all opencl test and only those four not work. 

I have JtR 1.8.0-jumbo1 and this is the output of test without --devices option:

~/john-1.8.0-jumbo-1/run$ ./john --format=descrypt-opencl --test
Device 0: Devastator (AMD Radeon HD 7660D)
Local worksize (LWS) 64, Global worksize (GWS) 16384
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... FAILED (get_hash[0](0))

There is another version of JtR?

**Comment by magnumripper** [comment]
> There is another version of JtR?

This very repo is 1978 commits past 1.8.0-jumbo1, over 70,000 lines of code has changed. Try downloading a snapshot:
https://github.com/magnumripper/JohnTheRipper/archive/bleeding-jumbo.zip

**Comment by magnumripper** [comment]
Closing as stale
