### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1181]
I think these two cases are integer overflow.

# Case 1

File: [src/formats.c](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/formats.c)
Line: 71

```C
void fmt_init(struct fmt_main *format)
{
        ...
		if (!(opt = getenv("OMP_SCALE")))
			opt = cfg_get_param(SECTION_OPTIONS, NULL,
			                    "FormatBlockScaleTuneMultiplier");
		if (opt)
			d = atof(opt);
		if ((int)d > 1)
			format->params.max_keys_per_crypt *= (int)d; // line:73
        ...
}
```

# Case 2

File: [src/jumbo.c](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/jumbo.c)
Line: 341
```C
int setenv(const char *name, const char *val, int overwrite) {
	int len;
    ...
	len = strlen(name)+1+strlen(val)+1; // line:341
	str = mem_alloc_tiny(len, MEM_ALIGN_NONE);
	sprintf(str, "%s=%s", name, val);
	putenv(str);
	return 0;
}
```

**Comment by magnumripper** [comment]
Yes, that code is totally experimental and not for end users. Actually it should probably be removed now, or at least defined out when not needed.
