### ISSUE TITLE
Compile error on well.openwall.net

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1183]
$ ./configure && make

Error message:
/tmp/cc9aSDsO.s: Assembler messages:
/tmp/cc9aSDsO.s:447: Error: no such instruction: `vfmadd312sd .LC5(%rip),%xmm0,%xmm2'

However, the code compiles fine on both my laptop and our server. Is there something wrong with gcc?

**Comment by zzlei** [comment]
Well, the error is gone when I use gcc 4.9.2 instead of the default version.

**Comment by claudioandre** [comment]
This is duplicated:
* https://github.com/magnumripper/JohnTheRipper/search?q=vfmadd312sd&type=Issues&utf8=%E2%9C%93
