### ISSUE TITLE
Drop obsolete FMT_MAIN_VERSION #ifdef's

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1185]
https://github.com/magnumripper/JohnTheRipper/pull/1184#issuecomment-90115562
>> Actually since we have released Jumbo-1, I think we can remove them across the board. But you are right it's better done in a separate commit.

> Then let's create a new issue, and plan to cleanup all the other dependencies FMT_MAIN_VERSION:
```
    593 #if FMT_MAIN_VERSION > 11
     30 #if FMT_MAIN_VERSION > 9
      4 #if FMT_MAIN_VERSION > 10
      1 #if FMT_MAIN_VERSION > 11 && IKE_REPORT_TUNABLE_COSTS
```

> This could be an easy part of the GSoC code cleanup task.

**Comment by jfoug** [comment]
```Perl
#!/usr/bin/perl
use strict;
use warnings;
use Path::Class;
use autodie;

my $dir = dir("./");
my $ifile = $dir->file($ARGV[0])->openr();
my $ofile = $dir->file($ARGV[0].".tmp")->openw();
my $cnt=0;
my $in_def=0;
while( my $line = $ifile->getline() ) {
	if (index($line, "#if FMT_MAIN_VERSION >") == 0) {
		$in_def = 1; # no print.
		$cnt++;
	} elsif ($in_def > 0 && index($line, "#endif") == 0 && --$in_def == 0) {
		# do nothing, no print and if() statement adjusted $in_def
	} else {
		$ofile->print($line);
	}
}
$ifile->close();
$ofile->close();
if ($cnt > 0) {
	rename($ARGV[0].".tmp", $ARGV[0]);
	print ("Fixed $ARGV[0], remove $cnt #ifdefs\n");
} else {
	unlink($ARGV[0].".tmp");
}
```

After editing a few files, I gave up, and wrote a simple perl script to do it.  It handled all but a couple of files perfectely.  I did not take #else into account, lol.  Had to hand edit dynamic (2 files), ike_fmt and listconf.c   I think that was the only files the script did not handle perfectly.
