### ISSUE TITLE
Raw-MD4 OpenCL, mask mode runs out of memory?

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1188]
Seen on nvidia
```
$ seq 100000 999999 | ../run/pass_gen.pl -count=999999 raw-md4 > test4.in
$ ../run/john test4.in -form:raw-md4-opencl -verb=1 -mask:?d?d?d?d?d?d
Loaded 900000 password hashes with no different salts (Raw-MD4-opencl [MD4 OpenCL])
Using Mask Mode with internal candidate generation, global worksize(GWS) set to 16384
Press 'q' or Ctrl-C to abort, almost any other key for status
OpenCL error (CL_OUT_OF_RESOURCES) in file (opencl_rawmd4_fmt_plug.c) at line (390) - (failed in reading data back hash_ids)
```
@Sayantan2048 is this expected? 900,000 hashes is not that much.

**Comment by Sayantan2048** [comment]
Perhaps this is not a bug but more of a drawback!! There is no quick fix for this issue, however, I'll try to address the problem with new hash checking methods. Due to tight schedule, I may not be able to post a patch until the end of this month.

**Comment by magnumripper** [comment]
That's OK. What is the reason for it, what resources are exhausted? Or is that message misleading?

**Comment by claudioandre** [comment]
BTW: this high number of hashes loaded to a GPU resulted in a very unresponsive machine. 
- It is not difficult to think about the problem and its solution. 

But, the cracking process was much slower than it can be on a CPU
- This is something you guys have to think about.

**Comment by magnumripper** [comment]
Atom states oclHashcat can attack up to 100 million hashes. Not sure at what speed penalty though.

**Comment by magnumripper** [comment]
Are your latest series of patches mainly addressing this issue, or speed, or both? I tried it out today and it  seems it can load more hashes now. But speed is only 20% of oclHashcat's speed (with same number of hashes, tested on nvidia Maxwell). Not sure how he can get it that much faster. OTOH we haven't really optimized the hash function yet since there hasn't been any point until now.

**Comment by magnumripper** [comment]
@Sayantan2048 you need to review all use of multi_profilingEvent[] in raw-md4. All of them not in crypt_all() should be replaced with NULL. Others should be renumbered and the warn[] array should be updated. If these are wrong, auto-tune may end up wrong.

**Comment by Sayantan2048** [comment]
> @Sayantan2048 you need to review all use of multi_profilingEvent[] in raw-md4. All of them not in    > crypt_all() should be replaced with NULL. Others should be renumbered and the warn[] array should > be updated. If these are wrong, auto-tune may end up wrong.

Fixed in commit f07b7d9e88652306e416a

**Comment by Sayantan2048** [comment]
>  Are your latest series of patches mainly addressing this issue, or speed, or both? I tried it out       >  today and it seems it can load more hashes now. But speed is only 20% of oclHashcat's speed    >  (with same number of hashes, tested on nvidia Maxwell). Not sure how he can get it that much    >  faster. OTOH we haven't really optimized the hash function yet since there hasn't been any point > until now.
Yes it improves upon both, but tested mainly for GCN gpus. For speed comparison could you please report results for 100 hashes with -mask=?d?d?d?d?d?d?d?d?d?d?d. It'd give me a better idea of where the bottleneck is.

**Comment by magnumripper** [comment]
raw MD4 with bypassed auto-tune: LWS pinned at 256, GWS pinned at 8192. This is on Titan X.

num hashes | JtR | oclHashcat
--------|--------|----------
1       | 5882M  | 28965M
10      | 5882M  | 14867M
100     | 5882M  | 14837M
1000    | 5555M  | 14811M
10000   | 5555M  | 14636M
100000  | 4000M  | 13966M

At best we do less than 40% of Hashcat speeds.

**Comment by Sayantan2048** [comment]
We still are being bottlenecked due to password generation on CPU. I did some profiling using AMD CodeXL, which suggests that around 70% of the execution time is spent on CPU part for latest raw-md4-opencl. To get some estimate of how bad it is, I compared it with mscash2-opencl; CodeXL shows merely 15% of the execution time being spent on CPU. I don't understand how oclHashcat manges to eliminate these bottlenecks while still maintaining flexibility.

**Comment by magnumripper** [comment]
> 70% of the execution time is spent on CPU part for latest raw-md4-opencl

That's much worse than I thought. Are we not doing partial transfers in these formats? Maybe we should also start juggling with two of each buffer, so we fill *keys[1] while processing *keys[0] and so on.

**Comment by magnumripper** [comment]
Anyway this issue is fixed!
