### ISSUE TITLE
Dynamic formats (most of them) fails or segfaults with AVX2

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1189]
(in the avx2 topic branch)

I have fixed loads of cases where width was hardcoded as 4 (in various disguises, eg `>>2`, `&3` or `+24` to name but a few) but many probably still exist. Also, some code has worse problems, like this
```C
#undef inc
#if (SIMD_COEF_32==4)
#define inc 4
//# define incCRY 12
# define incCRY 14
#else
#define inc 2
# define incCRY 6
#endif
```
I guess the else clause is written for MMX. We need clauses for widths of 8, 16 and 32 but much better would be to make it a formula of some sort.

**Comment by magnumripper** [comment]
On the bright side, some formats does work now!
```
Benchmarking: dynamic_0 [md5($p) (raw-md5) 256/256 AVX2 (768*1)x8x2]... (8xOMP) DONE
Raw:	66416K c/s real, 8312K c/s virtual

Benchmarking: dynamic_18 [md5($s.Y.$p.0xF7.$s) (Post.Office MD5) 32/64 (3072*1)x2 (MD5_body)]... (8xOMP) DONE
Many salts:	26707K c/s real, 3342K c/s virtual
Only one salt:	19279K c/s real, 2413K c/s virtual

Benchmarking: dynamic_30 [md4($p) (raw-md4) 256/256 AVX2 (768*1)x8x2]... (8xOMP) DONE
Raw:	42000K c/s real, 5250K c/s virtual

Benchmarking: dynamic_90 [GOST($p) 64/64 (6144*1)x1]... (8xOMP) DONE
Raw:	4110K c/s real, 514435 c/s virtual

Benchmarking: dynamic_100 [WHIRLPOOL($p) 64/64 (6144*1)x1 OpenSSL]... (8xOMP) DONE
Raw:	6770K c/s real, 846336 c/s virtual

Benchmarking: dynamic_110 [Tiger($p) 32/64 (6144*1)x1 sph_tiger]... (8xOMP) DONE
Raw:	22407K c/s real, 2804K c/s virtual

Benchmarking: dynamic_120 [RIPEMD128($p) 32/64 (6144*1)x1 sph_ripmd]... (8xOMP) DONE
Raw:	21049K c/s real, 2634K c/s virtual

Benchmarking: dynamic_130 [RIPEMD160($p) 32/64 (6144*1)x1 sph_ripmd]... (8xOMP) DONE
Raw:	16308K c/s real, 2059K c/s virtual

Benchmarking: dynamic_140 [RIPEMD256($p) 32/64 (6144*1)x1 sph_ripmd]... (8xOMP) DONE
Raw:	20637K c/s real, 2579K c/s virtual

Benchmarking: dynamic_150 [RIPEMD320($p) 32/64 (6144*1)x1 sph_ripmd]... (8xOMP) DONE
Raw:	16576K c/s real, 2072K c/s virtual
```

**Comment by magnumripper** [comment]
All other  formats are now fixed, only dynamic remains. Then we can merge the AVX2 branch to bleeding-jumbo.

**Comment by magnumripper** [comment]
ef42a19 soft-disables known bad dynamic formats for now.

**Comment by magnumripper** [comment]
Fixed a few. Here's how we should fix things:
```diff
-#if (SIMD_COEF_32==4)
-#define inc 6
-#else
-#define inc 2
-#endif
+#define inc ((SIMD_COEF_32-1) * 2)
```

Here's how we shouldn't (but I did, as a quick fix). This code should be width-agnostic (there WILL be AVX1024 too, and who knows what), using `*cpo[SIMD_COEF_32]` and a for loop (which will be unrolled anyway, if that is sensitive).
```diff
                ARCH_WORD_32 *cpo = input_buf_X86[j].x1.w;
                ARCH_WORD_32 *cpo2 = input_buf_X86[j+1].x1.w;
 #if (SIMD_COEF_32==4)
                ARCH_WORD_32 *cpo3 = input_buf_X86[j+2].x1.w;
                ARCH_WORD_32 *cpo4 = input_buf_X86[j+3].x1.w;
 #endif
 #endif
+#if (SIMD_COEF_32>=8)
+               ARCH_WORD_32 *cpo5 = input_buf_X86[j+4].x1.w;
+               ARCH_WORD_32 *cpo6 = input_buf_X86[j+5].x1.w;
+               ARCH_WORD_32 *cpo7 = input_buf_X86[j+6].x1.w;
+               ARCH_WORD_32 *cpo8 = input_buf_X86[j+7].x1.w;
+#endif
+#if (SIMD_COEF_32>=16)
+               ARCH_WORD_32 *cpo9 = input_buf_X86[j+8].x1.w;
+               ARCH_WORD_32 *cpo10 = input_buf_X86[j+9].x1.w;
+               ARCH_WORD_32 *cpo11 = input_buf_X86[j+10].x1.w;
+               ARCH_WORD_32 *cpo12 = input_buf_X86[j+11].x1.w;
+               ARCH_WORD_32 *cpo13 = input_buf_X86[j+12].x1.w;
+               ARCH_WORD_32 *cpo14 = input_buf_X86[j+13].x1.w;
+               ARCH_WORD_32 *cpo15 = input_buf_X86[j+14].x1.w;
+               ARCH_WORD_32 *cpo16 = input_buf_X86[j+15].x1.w;
+#endif
```

Here's the biggest problem:
```C
#if (SIMD_COEF_32>=4)
			total_len[j] = 0x10101010;
#else
			total_len[j] = 0x00100010;
#endif
```
That else clause means MMX (width 2). This simply can't be fixed without rewriting the code. For some hysterical reason (paraphrasing historical - I think this is legacy from the 1st gen MMX code we had) we stuff many 8-bit lengths in one 32-bit integer. All over dynamic. It's hard to stuff eight of them, let alone 16.

**Comment by magnumripper** [comment]
```
Benchmarking: dynamic_0 [md5($p) (raw-md5) 256/256 AVX2 10x8x3]... DONE
Raw:	62781K c/s real, 62781K c/s virtual

Benchmarking: dynamic_2 [md5(md5($p)) (e107) 256/256 AVX2 10x8x3]... DONE
Raw:	31399K c/s real, 31399K c/s virtual

Benchmarking: dynamic_3 [md5(md5(md5($p))) 256/256 AVX2 10x8x3]... DONE
Raw:	21188K c/s real, 21188K c/s virtual
*** glibc detected *** ../run/john: munmap_chunk(): invalid pointer: 0x00000000012549d0 ***
```
```
Benchmarking: dynamic_18 [md5($s.Y.$p.0xF7.$s) (Post.Office MD5) 32/64 64x2 (MD5_body)]... DONE
Many salts:	5074K c/s real, 5074K c/s virtual
Only one salt:	4828K c/s real, 4828K c/s virtual

Benchmarking: dynamic_34 [md5(md4($p)) 256/256 AVX2 10x8x3]... DONE
Raw:	30381K c/s real, 30381K c/s virtual
```

**Comment by magnumripper** [comment]
AVX2 is now in bleeding-jumbo. Until this issue is fixed, AVX2 and Dynamic is mutually exclusive unless you configure with `--enable-experimental-code`.

**Comment by magnumripper** [comment]
Functions like `DynamicFunc__SSEtoX86_switch_*()` (and vice versa) are still busted. The MD5_X2 stuff doesn't make it easier.

**Comment by magnumripper** [comment]
All formats pass self-test as well as the Test Suite now.

@jfoug there were hundreds of cases of hardcoded vector widths and other problems that should now be fixed to survive even AVX-1024 with little (or no) problems.

@zzlei please test on MIC and open a new issue if you see any problems.

**Comment by zzlei** [comment]
All dynamic formats pass self-test on MIC. Awesome!

**Comment by zzlei** [comment]
BTW, I'm trying to test those AVX512 intrinsics with Intel SDE, but couldn't pass the building phase. 
The configure command is:
`./configure CC="icc" CFLAGS="-xCOMMON-AVX512" --host=x86_64 --disable-opencl`
(gcc has trouble handling AVX512 intrinsics)

And I got a bunch of link errors:
```
  "_AES_cbc_encrypt", referenced from:
      _crypt_all in 7z_fmt_plug.o
      _crypt_all in agilekeychain_fmt_plug.o
      _hash_plugin_check_hash in androidfde_fmt_plug.o
      _crypt_all in androidfde_fmt_plug.o
      _crypt_all in blockchain_fmt_plug.o
      _crypt_all in dmg_fmt_plug.o
      _crypt_all in keyring_fmt_plug.o
      ...
     (maybe you meant: _JTR_AES_cbc_encrypt)
  "_AES_cfb128_encrypt", referenced from:
      _check in gpg_fmt_plug.o
  "_AES_decrypt", referenced from:
      _crypt_all in openbsdsoftraid_fmt_plug.o
      _crypt_all in truecrypt_fmt_plug.o
      _cmp_exact in truecrypt_fmt_plug.o
     (maybe you meant: _JTR_AES_decrypt)

  (many more...)
```

Any hints?

**Comment by zzlei** [comment]
The release notes of gcc-4.9 claim it supports AVX-512, but it can't even handle a simple program like this:
```c
#include <immintrin.h>
#include <stdio.h>
int main() {
	__m512i v = _mm512_set1_epi64(1);
	printf("%ld\n", _mm512_reduce_add_epi64(v));
}
```

```
$ gcc -mavx512f test.c
/tmp/ccoCwlQ7.s: Assembler messages:
/tmp/ccoCwlQ7.s:22: Error: no such instruction: `vmovdqa64 -240(%rbp),%zmm0'
/tmp/ccoCwlQ7.s:24: Error: no such instruction: `kmovw %eax,%k1'
/tmp/ccoCwlQ7.s:25: Error: invalid character '{' in operand 2
/tmp/ccoCwlQ7.s:26: Error: no such instruction: `vmovdqa64 %zmm0,-112(%rbp)'
/tmp/ccoCwlQ7.s:27: Error: no such instruction: `vmovdqa64 -112(%rbp),%zmm0'
```

**Comment by magnumripper** [comment]
I assume this is on Linux? It looks to me gcc does support everything needed but your as(1) can't handle AVX2. So try upgrading as.

**Comment by magnumripper** [comment]
> I'm trying to test those AVX512 intrinsics with Intel SDE, but couldn't pass the building phase. 
The configure command is:
`./configure CC="icc" CFLAGS="-xCOMMON-AVX512" --host=x86_64 --disable-opencl`
(gcc has trouble handling AVX512 intrinsics)

On a sidenote, setting CFLAGS will make the default "-O2 -g" go away so when you do this you should probably set it as CFLAGS=""-xCOMMON-AVX512 -O2 -g"

> And I got a bunch of link errors

It looks like autoconf found headers from a newer OpenSSL version what is later found by the linker. You may need to add eg. some -L/usr/local/lib/whatever to LDFLAGS and/or make your system look in that directory by default (ldconfig(8) and files in /etc/ld.so.conf.d).

**Comment by zzlei** [comment]
> It looks like autoconf found headers from a newer OpenSSL version than what is later found by the linker. You may need to add eg. -L/usr/local/lib/whatever to LDFLAGS and/or make your system look in that directory by default (ldconfig(8) and files in /etc/ld.so.conf.d).

Actually there's only a single installation of OpenSSL on my computer (OS X), which is the default one. I also tried to build with the same configuration on our server, where there's also only one OpenSSL version, and still got the same error.

**Comment by zzlei** [comment]
> I assume this is on Linux? It looks to me gcc does support everything needed but your as(1) can't handle AVX-512. So try upgrading as.

After upgrading to the latest as (2.25), I got this error instead:
```
lei@well:~$ gcc -mavx512f test.c
/tmp/cchpLkZO.o: In function `main':
test.c:(.text+0x56): undefined reference to `_mm512_reduce_add_epi64'
collect2: error: ld returned 1 exit status
```
Replacing `_mm512_reduce_add_epi64` with some other "simpler" intrinsics would resolve this issue, though. It seems GCC's library support for AVX512 is incomplete yet.

**Comment by magnumripper** [comment]
> Actually there's only a single installation of OpenSSL on my computer (OS X), which is the default one

Then maybe it's somehow triggered by using icc - that I haven't tried on OS X. Please open a proper separate issue for this and document. If you can establish why it happens (and possibly fix it) it would be even better.

What is supposed to happen is we get HAVE_AES (and some others) undefined from this:
```C
AC_CHECK_FUNCS([EVP_aes_256_xts SHA256 WHIRLPOOL RIPEMD160 AES_encrypt EVP_sha512 BIO_new])
```
...and then the build should be fine, but disabling a few formats. I haven't tried native OSX for a while though, maybe they changed something is a recent update.

**Comment by magnumripper** [comment]
it seems we no longer check for HAVE_AES_ENCRYPT but are now trying to use AES-NI or else fall back to local AES implementation in C. So maybe there's some problem with aes/Makefile or something else under aes subdir, when using icc?

**Comment by magnumripper** [comment]
> Replacing `_mm512_reduce_add_epi64` with some other "simpler" intrinsics would resolve this issue

Or maybe emulate it for now. I guess everyone's AVX-512 is buggy as of now. We are early adopters!

**Comment by magnumripper** [comment]
> So maybe there's some problem with aes/Makefile or something else under aes subdir, when using icc?

Again, I think your problem is `--host=x86_64`. You should drop that whole option or use `--host=x86_64-pc-linux` or whatever is normal. What was the intention with this option?

**Comment by zzlei** [comment]
> What was the intention with this option?

Because program built with -mavx512 won't run natively on the host, and I need to explicitly set a host to tell configure I'm cross-compiling. I was a bit too casual when choosing the host name, though.

**Comment by magnumripper** [comment]
Oh, right. So maybe all is fine if you set a full triplet.
