### ISSUE TITLE
md5crypt fails on AVX2

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1192]
Presumably due to vector width hardcoded as 4 in a few places in sse-intrinsics.c. I'm hoping @bartavelle will have time to look at it.

**Comment by magnumripper** [comment]
I rock.

**Comment by bartavelle** [comment]
You rock !

**Comment by bartavelle** [comment]
Was just about to take a look ;)

**Comment by magnumripper** [comment]
I couldn't stop myself from trying yet another time :-)  The good thing is I started to understand that code. It was always voodoo magic to me.
