### ISSUE TITLE
Still not possible to build without plugin formats

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1207]
Now that all former plugin files that are required by other formats got renamed, it should be possible to build without any plugins.
But: 
```
$ ./configure && make -s -j 16
[...]
config.status: executing default commands
configure: creating ./fmt_externs.h
gcc: error: *_fmt_plug.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
configure: creating ./fmt_registers.h
gcc: error: *_fmt_plug.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: opencl_*_fmt_plug.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: cuda_*_fmt_plug.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
```
BTW: This is a non-GPU build, so why is autoconf checking opencl and cuda formats at all?

```
[...]
checking for john.local.conf... exists

Configured for building John the Ripper 1.8.0.2-jumbo-1-bleeding:
```
BTW: didn't you merge Solar's 1.8.0.4 changes, so why still `1.8.0.2-jumbo-1-bleeding`?

```
[...]
Configure finished.  Now 'make clean && make -s' to compile.
make[1]: *** No rule to make target `*_plug.o', needed by `../run/john'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```

**Comment by magnumripper** [comment]
This should work, I'll fix it.

> BTW: This is a non-GPU build, so why is autoconf checking opencl and cuda formats at all?

The "plugin stanza" within the files take care of that anyway so it would just be unnecessary extra logic.

> BTW: didn't you merge Solar's 1.8.0.4 changes, so why still 1.8.0.2-jumbo-1-bleeding?

Oh. My. God. @jfoug actually hard-coded it. That's incredibly dumb, will fix.

**Comment by magnumripper** [comment]
There were problems still present - 297d8e4 fixed dependency on netlm and nethalflm structs. Maybe the compiler optimized it away though.
