### ISSUE TITLE
macro __AVX512__ doesn't exist

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1210]
replace it with `__AVX512F__`,` __AVX512BW__`, etc

**Comment by magnumripper** [comment]
From ab66d857/682f91d7 we have tests in place in autoconf (untested).

**Comment by magnumripper** [comment]
So I guess it's pretty much like
```C
#if __AVX512F__ || __MIC__
(...)
#if __AVX512BW__
(...)
#else
(...emulation...)
#endif /* __AVX512BW__ */
#endif /* __AVX512F__ || __MIC__ */
```

**Comment by magnumripper** [comment]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/ is excellent for some cross reference searching

**Comment by zzlei** [comment]
I find some inconsistency between these two intrinsics guides:
[1] https://software.intel.com/sites/landingpage/IntrinsicsGuide/
[2] https://software.intel.com/en-us/node/513445

For example, [1] says _mm512_set1_epi64 is only available on AVX512F, while [2] says it's available on MIC. I think [2] seems more authoritative.

**Comment by magnumripper** [comment]
That's a pity cause the [1] has a good interface. I guess I'm going to use both. BTW the actual headers involved are the only hard facts, I guess. I suspect even [2] might be wrong about some detail.

**Comment by zzlei** [comment]
issue fixed by https://github.com/magnumripper/JohnTheRipper/commit/2f8bc4871b996366e936b300bc6df15351c7ebff

**Comment by zzlei** [comment]
Alas, it's even worse than I expected. Both guides say that `_mm512_i64gather_epi64` is unavailable on MIC. But when I tested it on MIC, it actually worked! You're right that the headers are the only hard facts.
