### ISSUE TITLE
compile warning message

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1214]
```
pp.c:2358:5: warning: implicit declaration of function 'munmap' is invalid in C99 [-Wimplicit-function-declaration]
    munmap(mem_map, file_len);
```

I guess sys/mman.h should be included, but some how it's not.

**Comment by magnumripper** [comment]
When does this happen? Linux? OSX? MIC target?

Autoconf should have found mmap() and defined HAVE_MMAP in autoconfig.h - did it? If not, try to find out why.

**Comment by magnumripper** [comment]
Oh, we have a logic bug in the #ifdefs. It's strange not many systems complained about this.

**Comment by zzlei** [comment]
I got this error on OS X. It also happened when cross-compiling for MIC on Linux.

**Comment by magnumripper** [comment]
Strange, I didn't see it on Yosemite. Neither with gcc-4.9 nor clang. Anyway it's gone now, right?

**Comment by zzlei** [comment]
I got this warning when using such configuration:
`$ ./configure CFLAGS="-mavx512f" --host=x86 --disable-opencl`

And after the latest commit, this warning still exists with this configuration.

**Comment by magnumripper** [comment]
Ahaa... what's with the --host=x86? Why did you add that, are you trying to make a 32-bit build? It doesn't work that way and it likely breaks things.
```
checking build system type... x86_64-apple-darwin14.3.0
checking host system type... x86-unknown-none
...
configure: WARNING: Uncertain support for x86-unknown-none, please report!
checking for arch.h alternative... autoconf_arch.h
...
checking for OS-specific feature macros needed... none
```

**Comment by zzlei** [comment]
I just intended to choose a host compatible with my computer. I didn't choose carefully though. It's my fault...

**Comment by magnumripper** [comment]
In this case you might be able to use `--disable-native-tests` (it's JtR specific) instead of cross compiling.

**Comment by zzlei** [comment]
Somehow `--disable-native-tests` doesn't work. 
`./configure` still prompts me to specify a host.
```
$ ./configure CC="icc -xCOMMON-AVX512" --disable-native-tests
...
checking whether we are cross compiling... configure: error: in `/Users/Lei/Source/JohnTheRipper/src':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
...
```

**Comment by magnumripper** [comment]
OK. So use the full triplet. Do you still see the munmap warning then?

**Comment by zzlei** [comment]
Yes, I still got this warning.
BTW, icc doesn't recognize the `-mavx512f` option added by ./configure, and emits a warning about it:
```
icc: command line warning #10159: invalid argument for option '-m'
```

**Comment by magnumripper** [comment]
> Yes, I still got this warning.

Strange. It'd be nice if you track down what happens and why.

> BTW, icc doesn't recognize the -mavx512f option added by ./configure, and emits a warning about it:

So what option does icc want for enabling AVX-512F?

**Comment by zzlei** [comment]
> Strange. It'd be nice if you track down what happens and why.

OK.

> So what option does icc want for enabling AVX-512F? It works fine with gcc.

Currently icc uses a different set of options:
```
-xCOMMON-AVX512   generate AVX512F, AVX512CD instructions
-xCORE-AVX512     generate AVX512F, AVX512CD, AVX512DQ, AVX512BW, AVX512VL instructions
...
```
Among those options `COMMON-AVX512` specifies the smallest subset. There's not a single option to enable AVX512F only. 

I'm not sure about Intel's intention. Maybe all forthcoming AVX512-compatible CPUs should support `COMMON-AVX512`?

**Comment by magnumripper** [comment]
So we may have to tweak configure.ac for this. But it can wait, I guess everyone's AVX512 stuff is somewhat in a state of flux. I expect gcc and icc to unify their options in one way or the other.

**Comment by zzlei** [comment]
There's a variable `ac_cv_func_mmap_fixed_mapped` in configure which is defined to `no` when cross-compiling, resulting in the missing of `#define HAVE_MMAP 1` in autoconfig.h, which in turn results in the warning we've got.

**Comment by magnumripper** [comment]
That means the problem is in AC_FUNC_MMAP which is a pre-fab macro we use in autoconf. I wonder why this happens. On the other hand we seem to have a bug in our code - if HAVE_MMAP isn't set we are not supposed to use mmap() nor munmap(). I will look into that (probably just a missing ifdef around that munmap()).

What if you edit autoconfig.h and define `HAVE_MMAP 1` between configure and make? Does it build just fine?

On MIC, you sometimes might want to run --fork=240 or something like that. If you do that with a 500 MB wordlist and not use mmap(), it will drain your memory pretty well...

**Comment by magnumripper** [comment]
I fixed the original bug in bbc38fc. But this bug was a good one since it made us aware of the fact MIC did not get HAVE_MMAP so I added a proper warning notice instead. We should try to ensure MIC gets HAVE_MMAP if applicable (it should be).

**Comment by zzlei** [comment]
> What if you edit autoconfig.h and define HAVE_MMAP 1 between configure and make? Does it build just fine?

Yes

I did a quick search on Google, where some guy suggested using `AC_CHECK_FUNCS(mmap)` instead of `AC_CHECK_MMAP`. I tested it and it actually worked... `AC_CHECK_FUNCS(mmap)` would define `HAVE_MMAP` when cross-compiling and solves our problem. I guess `AC_CHECK_MMAP` is somewhat buggy.

**Comment by magnumripper** [comment]
Yeah I guess. `AC_CHECK_MMAP` is supposed to check for a *working* mmap as opposed to just one being "present" and it was added in hope this would recognize non-working mmap() in Cygwin. But it doesn't, so I guess I'll just switch back to `AC_CHECK_FUNCS(mmap)`
