### ISSUE TITLE
New warnings on Fedora 22 beta, _BSD_SOURCE deprecated

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1227]
Apparently, as of as of glibc 2.19.90 ther feature test macros _SVID_SOURCE (which we don't use) and _BSD_SOURCE are deprecated.
```
$ make -s distclean; ./configure > /dev/null && make -s clean && make -s -j 8
In file included from /usr/include/stdio.h:27:0,
                 from jumbo.h:20,
                 from os-autoconf.h:29,
                 from os.h:20,
                 from bench.c:25:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
/usr/bin/ar: creating aes.a
In file included from /usr/include/stdio.h:27:0,
                 from vncpcap2john.c:54:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^

Make process completed.
```
The /usr/include/features.h include on my Fedora 20 system doesn't know `_DEFAULT_SOURCE`. I don't have a Fedora 21.
Even on Fedora 22, `man setenv` has
```
SYNOPSIS
       #include <stdlib.h>

       int setenv(const char *name, const char *value, int overwrite);

       int unsetenv(const char *name);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       setenv(), unsetenv():
           _BSD_SOURCE || _POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600
```
and doesn't mention `_DEFAULT_SOURCE`.

But if _GNU_SOURCE is defined, both the Fedora 20 and the Fedora 22 version of /usr/include/features.h define `_POSIX_C_SOURCE` as `200809L`, which is > 200112L.

**Comment by magnumripper** [comment]
So they try to convince us to break portability with old systems, by adding annoying warnings. That's not nice.

**Comment by frank-dittrich** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1067110, but I wouln't follow the suggestion to define _DEFAULT_SOURCE, since older systems don't know it.

I think, for Linux systems, we could use _GNU_SOURCE instead of _BSD_SOURCE.
Then, /usr/include/features.h will define _POSIX_C_SOURCE...

Annoying indeed. 

When you define both _DEFAULT_SOURCE and _BSD_SOURCE, the warning also disappears (for now, may be that changes in a later glibc version).

**Comment by magnumripper** [comment]
> When you define both _DEFAULT_SOURCE and _BSD_SOURCE, the warning also disappears (for now, may be that changes in a later glibc version).

Oh, right. Then we should obviously define both. I would not think they will start complaining in that situation. I will fix this.
