### ISSUE TITLE
new gcc 5.1.1 warning -Wmaybe-uninitialized in memdbg

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1228]
This is on a 64bit Linux system (Fedora 22 Beta 3, with all available updates):

```
$ make -s distclean; ./configure --enable-memdbg > /dev/null && make -s clean && make -s
[...]
memdbg.c: In function ‘MEMDBG_alloc_align’:
memdbg.c:652:15: warning: ‘ptr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  p->mdbg_fpst = MEMFPOST;
               ^
```

I think it is a false positive, because if the `_mem_alloc_align()` fails, `return NULL;` would have been processed.
So, unless I'm missing something, this might be due to running beta versions...

**Comment by magnumripper** [comment]
What version of gcc is that?

**Comment by frank-dittrich** [comment]
https://github.com/magnumripper/JohnTheRipper/issues/1229 may be related.

This is
```
$ gcc --version
gcc (GCC) 5.1.1 20150422 (Red Hat 5.1.1-1)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
On Fedora 22 *_BETA_* 3

**Comment by magnumripper** [comment]
But is gcc also beta? I guess it is, they usually have a minor of 2 for release.

**Comment by frank-dittrich** [comment]
I don't think gcc is beta.
5.1 is the latest release.
And the version string "syntax" matches the one of my Fedora 20 system.

**Comment by frank-dittrich** [comment]
I just confirmed that https://github.com/magnumripper/JohnTheRipper/commit/8506e3cc16ac56549b94bfb960ba78d390fe1107 fixed the warning as well.

**Comment by magnumripper** [comment]
Yes, it was a false positive from the compiler, worked around with `void ptr = NULL;`. We already had that workaround in memory.c
