### ISSUE TITLE
OpenCL formats vs. --list options, minor problem

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1237]
```
$ ../run/john -list=format-all-details -form:nt-opencl
Format label                         nt-opencl
 Disabled in configuration file      no
Min. password length in bytes        0
Max. password length in bytes        23
Min. keys per crypt                  1
Max. keys per crypt                  1
Flags
 Case sensitive                      yes
 Supports 8-bit characters           yes
 Converts 8859-1 to UTF-16/UCS-2     yes
 Honours --encoding=NAME             no
 False positives possible            no
 Uses a bitslice implementation      no
 The split() method unifies case     yes
 A $dynamic$ format                  no
 A dynamic sized salt                no
 Parallelized with OpenMP            no
Number of test vectors               41
Algorithm name                       MD4 OpenCL (inefficient, development use only)
Format name                          NT
Benchmark comment                    
Benchmark length                     -1
Binary size                          16
Salt size                            0
Tunable cost parameters              
Example ciphertext                   b7e4b9022cd45f275334bbdb83bb5be5

OpenCL error (CL_INVALID_MEM_OBJECT) in file (opencl_nt_fmt_plug.c) at line (191) - (Release mem in)
```
That error happens because fmt_init() no longer allocates any buffers. At exit we call fmt_done() which assumes there are buffers.

Not sure what is best. We could tweak done() or release_clobj() in all formats. Or we could always add some smallish buffers in init() - eg. `create_clobj(64, self)` and have reset() handle this (they need to be released before creating the new "real" ones). The latter solution would also let us self-test using the very small buffers, and leave the real group sizes to just the benchmark (or real run).

**Comment by claudioandre** [comment]
My opinion is that a simple fix is best. The simplest seems to check in done():
```
if (opencl_initialized) {
    //I have to release the opencl buffers.
    release_...
...
}
```
****
> would also let self-test using the very small buffers

I see no possible fails for small buffers. Have you thought about a possible error?

**Comment by magnumripper** [comment]
> I see no possible fails for small buffers. Have you thought about a possible error?

I mean testing a GWS of 64 is just as good (but a lot faster) than testing a GWS of 4M
