### ISSUE TITLE
Cygwin_x86-64 Build problem

### ISSUE THREAD

**Issue by richrumble** [magnumripper/JohnTheRipper#1266]
Trying the latest (5-4-2015) in a 64-bit windows cygwin environment
./configure --enable-mpi &&  make clean && make
...
Configured for building John the Ripper jumbo:

Target CPU .................................. x86_64 SSE4.1, 64-bit LE
AES-NI support .............................. depends on OpenSSL
Target OS ................................... cygwin
Cross compiling ............................. no
Legacy arch header .......................... x86-64.h

Optional libraries/features found:
Experimental code ........................... no
OpenMPI support (default disabled) .......... yes
Fork support ................................ yes
OpenMP support .............................. yes
OpenCL support .............................. no
CUDA support ................................ no
Generic crypt(3) format ..................... no
Rexgen (extra cracking mode) ................ no
GMP (PRINCE mode and faster SRP formats) .... no
128-bit integer (faster PRINCE mode) ........ yes
PCAP (vncpcap2john and SIPdump) ............. no
BZ2 (gpg2john extra decompression logic) .... yes
Memory map (share/page large files) ......... yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ............ disabled
AddressSanitizer ("ASan") ................... disabled
...
mpicc -DAC_BUILT -march=native -msse4.1 -c -g -O2 -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations -Wno-format-extra-args -std=gnu89 -D_POSIX_SOURCE -D_GNU_SOURCE -D__CYGWIN64__ -D__CYGWIN32__    -fopenmp -DHAVE_MPI    -funroll-loops tiger.c -o tiger.o
mpicc -DAC_BUILT -march=native -msse4.1 -c -g -O2 -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations -Wno-format-extra-args -std=gnu89 -D_POSIX_SOURCE -D_GNU_SOURCE -D__CYGWIN64__ -D__CYGWIN32__    -fopenmp -DHAVE_MPI    -funroll-loops ssh2john.c -o ssh2john.o
In file included from /usr/include/openssl/dtls1.h:78:0,
                 from /usr/include/openssl/ssl.h:1699,
                 from ssh2john.c:30:
/usr/include/sys/time.h:99:34: error: unknown type name ‘u_int’
 bintime_mul(struct bintime *_bt, u_int _x)
                                  ^
Makefile:1328: recipe for target 'ssh2john.o' failed
make[1]: *** [ssh2john.o] Error 1
make[1]: Leaving directory '/cygdrive/c/cygwin64/jtr-jumbo/src'
Makefile:182: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by magnumripper** [comment]
This is a dupe of #1250

**Comment by richrumble** [comment]
Same for 32bit yes :)
