### ISSUE TITLE
Verify support for password protected Office 2016 files

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1267]
Sample files are now available http://openwall.info/wiki/john/sample-non-hashes page.

**Comment by kholia** [comment]
Verified ;)

```
$ cat ../run/john.pot
$office$*2013*100000*256*16*9cee67bf6913ff1c488e12718fed2a24*8a4485d13c731a9a1882f8e44529afbd*db6b38c047c19d49ce9f0675019b7f806bbf2dce174b476bbab81dca6891676e:openwall
$office$*2013*100000*256*16*43190fa3565ea508cdf86589a3e3c488*b4889b671457b646fcc596e54937c255*bc7a2a00dada29c2527b2fc037afc4302ff47b67d27b3616803f69d2502efbe4:lolcats
$office$*2013*100000*256*16*e23615ec1d0ceb41cc26c901891c4dfd*f5ab60d0058a647361cfc8eb10df8841*fdfcf9a4e568d5a1927a9857972056eeeb6a86ebdb819e581180876687bcaab9:password123
```

**Comment by frank-dittrich** [comment]
Then, may be we need to adjust some format names, and may be even add/adjust some comments, etc.

**Comment by kholia** [comment]
Sure, please feel free to re-open, and possibly take over the ticket (I don't have the time to look further on).

**Comment by magnumripper** [comment]
> Verified

Great! I guess there was really no need for even upping iteration count.

> Then, may be we need to adjust some format name

I don't think so. It's like MSSQL05 being valid for >= SQL'05 and < SQL'12 and we can't change all format descriptions each year. But adding a comment somewhere that it's tested for Office 2016 wouldn't harm. May just doc/CHANGES-jumbo or something.
