### ISSUE TITLE
sunmd5 OMP fails self test for 32bit Linux build (i686 AVX2)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1281]
This is on a Fedora 21 installation on an USB thumb drive, CPU is Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz.

```
$ ./john --list=build-info
Version: 1.8.0.4-jumbo-1-bleeding_omp
Build: linux-gnu 32-bit AVX2-autoconf
Time stamp: Sat May  9 09:01:59 2015
Arch: 32-bit LE
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
File locking: fcntl()
Compiler version: 4.9.2 20150212 (Red Hat 4.9.2-6)
gcc version: 4.9.2
GNU libc version: 2.20 (loaded: 2.20)
OpenSSL library version: 0100010bf
OpenSSL 1.0.1k-fips 8 Jan 2015
fseek(): fseeko64
ftell(): ftello64
fopen(): fopen64
memmem(): System's

```

A non-OMP build works.
Using OMP_NUM_THREADS=1 with an OpenMP build works as well.
Otherwise, I get errors:

```
$ ./john --test=0 --format=sunmd5
Will run 4 OpenMP threads
Testing: SunMD5 [MD5 256/256 AVX2 8x3]... (4xOMP) FAILED (cmp_all(14))

$ OMP_NUM_THREADS=1 ./john --test=0 --format=sunmd5
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Testing: SunMD5 [MD5 256/256 AVX2 8x3]... PASS

$ OMP_NUM_THREADS=2 ./john --test=0 --format=sunmd5
Will run 2 OpenMP threads
Testing: SunMD5 [MD5 256/256 AVX2 8x3]... (2xOMP) FAILED (cmp_all(4))

$ OMP_NUM_THREADS=3 ./john --test=0 --format=sunmd5
Will run 3 OpenMP threads
Testing: SunMD5 [MD5 256/256 AVX2 8x3]... (3xOMP) FAILED (cmp_all(4))

$ OMP_NUM_THREADS=5 ./john --test=0 --format=sunmd5
Will run 5 OpenMP threads
Testing: SunMD5 [MD5 256/256 AVX2 8x3]... (5xOMP) FAILED (cmp_all(14))

```

On another test with OMP_NUM_THREADS=5 I got
```
$ OMP_NUM_THREADS=5 ./john --test=0 --format=sunmd5
Will run 5 OpenMP threads
Testing: SunMD5 [MD5 256/256 AVX2 8x3]... (5xOMP) Segmentation fault (core dumped)
```

**Comment by zzlei** [comment]
I used a simplified form of the OpenMP clause in that commit, 
```#pragma omp parallel for copyin(input_buf_big)```
which seems to get different interpretations from different compilers. 

It works with icc and gcc-4.9 in my experimentation, but somehow fails with gcc-4.4. I revised the code to use the verbose form of the OpenMP clause, which should resolve this issue. Please test it on your platform and see if the problem still exists.

**Comment by magnumripper** [comment]
Works for me on OSX 32-bit

**Comment by jfoug** [comment]
@frank-dittrich has this issue gone away?  If not, please test after the changes I made in 712bd58   VC complained about a couple functions in ways that appeared to me like they would use some global vars. That was strcpy and sprintf.  I removed them, and if these functions were the problems you were seeing, then this format should work.  Also, the code I added should be much faster, but the crtl functions were not called too often, so there will be no improvement in overall speed.

**Comment by frank-dittrich** [comment]
On 05/21/2015 08:23 PM, JimF wrote:
> @frank-dittrich <https://github.com/frank-dittrich> has this issue gone
> away? If not, please test after the changes I made in 712bd58
> <https://github.com/magnumripper/JohnTheRipper/commit/712bd585214b60af320cb7d0c0461a7affa6080f>


Probably I can't test this before Monday.

**Comment by frank-dittrich** [comment]
Meanwhile I tested this as well. I can confirm that the bug is gone.
