### ISSUE TITLE
Formats that profit from OMP_NUM_THREADS > # of cores

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1303]
Besides sunmd5, 
```
Will run 4 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4227 c/s real, 1086 c/s virtual

Will run 32 OpenMP threads
Benchmarking: SunMD5 [MD5 256/256 AVX2 8x3]... (32xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	4762 c/s real, 1202 c/s virtual
```
there are some other formats which on my quad core i5-4570 (default OMP_NUM_THREADS=4) profit from higher OMP_NUM_THREADS, which means there might be room for improving/tuning the format implementation.

sha1crypt:
```
Will run 4 OpenMP threads
Benchmarking: sha1crypt, NetBSD's sha1crypt [PBKDF1-SHA1 256/256 AVX2 8x2]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 64000 and 40000
Raw:	1796 c/s real, 448 c/s virtual

Will run 17 OpenMP threads
Benchmarking: sha1crypt, NetBSD's sha1crypt [PBKDF1-SHA1 256/256 AVX2 8x2]... (17xOMP) DONE
Speed for cost 1 (iteration count) of 64000 and 40000
Raw:	2327 c/s real, 582 c/s virtual
```

sha256crypt:
```
Will run 4 OpenMP threads
Benchmarking: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 256/256 AVX2 8x]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	7515 c/s real, 2122 c/s virtual

Will run 22 OpenMP threads
Benchmarking: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 256/256 AVX2 8x]... (22xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	8469 c/s real, 2123 c/s virtual
```

dmg:
```
Will run 4 OpenMP threads
Benchmarking: dmg, Apple DMG [PBKDF2-SHA1 256/256 AVX2 8x2 3DES/AES]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 1000
Raw:	28109 c/s real, 7010 c/s virtual

Will run 12 OpenMP threads
Benchmarking: dmg, Apple DMG [PBKDF2-SHA1 256/256 AVX2 8x2 3DES/AES]... (12xOMP) DONE
Speed for cost 1 (iteration count) of 1000
Raw:	29970 c/s real, 7585 c/s virtual
```

keyring:
```
Will run 4 OpenMP threads
Benchmarking: keyring, GNOME Keyring [SHA256 AES 256/256 AVX2 8x]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 3221 and 2439
Raw:	28981 c/s real, 7245 c/s virtual

Will run 23 OpenMP threads
Benchmarking: keyring, GNOME Keyring [SHA256 AES 256/256 AVX2 8x]... (23xOMP) DONE
Speed for cost 1 (iteration count) of 3221 and 2439
Raw:	29938 c/s real, 7532 c/s virtual
```

**Comment by magnumripper** [comment]
You might want to try out latest testparas.sh on that very system and see what interleaving factors it come up with as fastest.

**Comment by frank-dittrich** [comment]
Didn't have time earlier, ran the new testparas.pl just now:

gcc version 5.1.1 20150422 (Red Hat 5.1.1-1) (GCC) 
John the Ripper password cracker, version 1.8.0.5-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
running john with '-test' for each test

hash\para              |       1  |       2  |       3  |       4  |       5  |
-----------------------|----------|----------|----------|----------|----------|
nt                     |  56045K  |  77590K  |**84046K**|  79091K  |  76524K  |
nt-omp                 |  104333K  |  113246K  |**118996K**|  108462K  |  89948K  |
md5crypt               |   55040  |   77392  | **84408**|   83168  |   79640  |
md5crypt-omp           |  202976  |  291200  |**319680**|  308847  |  299040  |
pbkdf2-hmac-sha1       | **24552**|   23840  |   21696  |   19264  |   18520  |
pbkdf2-hmac-sha1-omp   | **92320**|   89536  |   80544  |   70912  |   69920  |
pbkdf2-hmac-sha256     |   **872**|     792  |     744  |     707  |     730  |
pbkdf2-hmac-sha256-omp |  **3296**|    3011  |    2756  |    2688  |    2742  |
pbkdf2-hmac-sha512     |   **138**|     127  |     114  |     108  |     114  |
pbkdf2-hmac-sha512-omp |   **522**|     480  |     407  |     411  |     424  |

`model name	: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz`

**Comment by frank-dittrich** [comment]
For pbkdf2-hmac-sha256 and pbkdf2-hmac-sha512 (with and without OMP), the para 5 values are better than  the para 4 values. For pbkdf2-hmac-sha512-omp, para 5 is even better than para 3.

**Comment by frank-dittrich** [comment]
I just tried params 1..12:

hash\para              |       1  |       2  |       3  |       4  |       5  |       6  |       7  |       8  |       9  |      10  |      11  |      12  |
-----------------------|----------|----------|----------|----------|----------|----------|----------|----------|----------|----------|----------|----------
nt                     |  56111K  |  77642K  |**84095K**|  79516K  |  76560K  |  75430K  |  75511K  |  74613K  |  70679K  |  72298K  |  71577K  |  72270K  |
nt-omp                 |  104235K  |  113442K  |**119341K**|  107806K  |  93143K  |  89554K  |  85277K  |  81788K  |  77856K  |  76185K  |  72450K  |  71761K  |
md5crypt               |   55064  |   77856  | **84120**|   82528  |   79560  |   76128  |   73416  |   73792  |   73440  |   71920  |   71544  |   64896  |
md5crypt-omp           |  202912  |  290176  |**320640**|  311936  |  299040  |  286272  |  276192  |  277760  |  269568  |  272320  |  266265  |  240768  |
pbkdf2-hmac-sha1       | **24520**|   23840  |   21696  |   18752  |   18178  |   18096  |   14840  |   15168  |   15264  |   14880  |   14784  |   15456  |
pbkdf2-hmac-sha1-omp   | **92320**|   89920  |   80448  |   71552  |   67200  |   67675  |   56000  |   56832  |   56174  |   56320  |   56320  |   58368  |
pbkdf2-hmac-sha256     |   **872**|     800  |     744  |     707  |     730  |     745  |     761  |     770  |     784  |     800  |     800  |     807  |
pbkdf2-hmac-sha256-omp |  **3263**|    3011  |    2796  |    2688  |    2769  |    2823  |    2854  |    2925  |    2960  |    3018  |    3017  |    3072  |
pbkdf2-hmac-sha512     |   **138**|     127  |     106  |     108  |     114  |     110  |     112  |     118  |     119  |     113  |     114  |     116  |
pbkdf2-hmac-sha512-omp |   **517**|     475  |     415  |     411  |     432  |     417  |     439  |     445  |     419  |     424  |     432  |     439  |

Even though the higher parameters don't match the para 1 results, yo can see that the values for  pbkdf2-hmac-sha256 and pbkdf2-hmac-sha512 are slowly improving.
With higher iteration counts, it is no surprise that higher interleaving or higher OMP_NUM_THREADS improve the c/s rate

**Comment by magnumripper** [comment]
> For pbkdf2-hmac-sha256 and pbkdf2-hmac-sha512 (with and without OMP), the para 5 values are better than the para 4 values. For pbkdf2-hmac-sha512-omp, para 5 is even better than para 3.

What do you mean? I can't see any sign of that in the tables. The bold figures are the best ones.

> I just tried params 1..12:

Double-checking it doesn't harm but anything above 5 is unreasonable and not supported in all formats. We should actually put #error directives for > 5.

**Comment by magnumripper** [comment]
I think this issue can be wrapped up for now. We may revisit it at some point in time, creating a new issue.
