### ISSUE TITLE
Warning on Cygwin32 GCC 4.9.2 on branch bleeding-jumbo

### ISSUE THREAD

**Issue by shinnok** [magnumripper/JohnTheRipper#1330]
Not sure if a false positive or not:

gcc -DAC_BUILT -march=native -mavx2 -c -g -O2 -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations -Wno-format-extra-args -std=gnu89 -D_GNU_SOURCE    -fopenmp     -funroll-loops DES_std.c -o DES_std.o
DES_std.c: In function ‘DES_std_set_key’:
DES_std.c:639:17: warning: array subscript is above array bounds [-Warray-bounds]
   while (DES_key[i++]) k += 2;

**Comment by magnumripper** [comment]
It's a long standing FP, see #276 (!)
