### ISSUE TITLE
New build warning

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1336]
I presume this is from 3b6fd5d494
```
keyring2john.c: In function 'process_file':
keyring2john.c:161:12: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  file_name = fname;
            ^
```
@loverszhaokai please watch out for things like this. Always build using `make -s` so you see the warnings (and not just a wall of text).

**Comment by loverszhaokai** [comment]
@magnumripper  

>Always build using make -s so you see the warnings (and not just a wall of text).

Thanks. Get it.
