### ISSUE TITLE
BE problems

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1345]
Sparc 64 bit box, but 32 bit build.

Testing: pomelo [POMELO 32/32]... FAILED (cmp_all(1))

Surprisingly, this was it, and no cores.   Also no warnings about alignment being off (usually those are cores, lol).

Fixed:  Testing: has-160 [HAS-160 32/32]... FAILED (cmp_all(1))
Fixed:  Testing: dominosec8, Lotus Notes/Domino 8 [8/32]... FAILED (cmp_all(1))

**Comment by frank-dittrich** [comment]
On 05/21/2015 11:05 PM, JimF wrote:
> Sparc 64 bit box, but 32 bit build.
> 
> Testing: dominosec8, Lotus Notes/Domino 8 [8/32]... FAILED (cmp_all(1))
> Testing: has-160 [HAS-160 32/32]... FAILED (cmp_all(1))
> Testing: pomelo [POMELO 32/32]... FAILED (cmp_all(1))

For now, I would ignore the POMELO problem, because we'll probably
replace this implementation with Agnieszka's implementation.

**Comment by jfoug** [comment]
The easy 'try' for has-160 failed (i.e. alter endiantity within binary).

**Comment by jfoug** [comment]
affa587 fixes has-160

**Comment by magnumripper** [comment]
> Surprisingly, this was it, and no cores.

Cool! So we've learned. Not @kholia though :laughing:

**Comment by jfoug** [comment]
1ad5b88 fixed dominosec8.  Simple issue where pbkdf2 was used.  For this format, the easiest fix was to just do byte swap during binary load, so it is only done one time.

If pomelo is to not be fixed at this time, then this 'bug' is done.
