### ISSUE TITLE
Truecrypt: Support keyfiles

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1346]
http://www.openwall.com/lists/john-users/2015/05/21/1

https://github.com/bwalex/tc-play/blob/master/crypto.c#L201

https://download.truecrypt.ch/documentation/TrueCrypt%20User%20Guide.pdf#page=141&zoom=auto,54,771 (pages 141-142)

**Comment by kholia** [comment]
Done in commit 807e2f5916aec0a10680136000ad2a6e1d32e85a.

Sample files are at https://github.com/kholia/tc-sample-volumes page.
