### ISSUE TITLE
bash completion for --show= not working

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1350]
1.
with `__john_completion=2`, `./john --show[tab][tab]` should be completed to `./john --show=` (for john versions which do have `--show=LEFT`).

2.
For john versions that have `--show=LEFT` and `--show=types`, both options should be suggested for `./john --show=[tab][tab]`

BTW: should the `--list=hidden-options` output be changed from `--show=types` to `--show=TYPES`?

**Comment by magnumripper** [comment]
> BTW: should the --list=hidden-options output be changed from --show=types to --show=TYPES?

I think not - with our current usage syntax this would imply that TYPES is not literal but something that should be filled in by user. As in `--list=WHAT`

**Comment by frank-dittrich** [comment]
And what about 
```
--show[=LEFT]             show cracked passwords [if =LEFT, then uncracked]
```
in john's usage output? Should that change to  
```
--show[=left]             show cracked passwords [if =left, then uncracked]
```
and bash completion use lower case here as well?

**Comment by magnumripper** [comment]
Absolutely. The current output is confusing.

**Comment by frank-dittrich** [comment]
Fixed in commit https://github.com/magnumripper/JohnTheRipper/commit/c0a9e61ae8b5075e24f7e485cc97eb540ff8adab
