### ISSUE TITLE
Get MinGW builds working under Travis CI

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1377]
This should be possible.

* http://www.tinc-vpn.org/examples/cross-compiling-64-bit-windows-binary/

* https://github.com/ciphrex/mSIGNA/blob/master/docs/mingw-w64-build-environment

**Comment by magnumripper** [comment]
You mean Travis would ensure building works, but not actually run it? That's a great idea.

**Comment by kholia** [comment]
@magnumripper maybe, we can even test the MinGW builds under Wine ;)

**Comment by kholia** [comment]
This is being handled in https://github.com/magnumripper/JohnTheRipper/issues/1378 more actively.
