### ISSUE TITLE
Kerberos - pcap2john.py

### ISSUE THREAD

**Issue by FrankSpierings** [magnumripper/JohnTheRipper#1380]
pcap2john.py receives a pcap file, but in function pcap_parser_krbpa it expects a .pdml file. This obviously will never result in a win, for this part of the code.

**Comment by magnumripper** [comment]
Ouch. Thanks for reporting. We once had a krbpa2john that was accidentally incorporated into pcap2john.

@kholia can this be rewritten to read pcap? Or do we need to strip this from pcap2john and restore the old krppa2john tool?

**Comment by FrankSpierings** [comment]
magnum,

I think I will be able to rewrite the code, since there are more problems. My tshark, seems to use different names. So it will probably be better to use the pcap format. But I need some sample captures. Also to be sure, I need that other (cracking) issue fixed (or at least know whats missing).

**Comment by kholia** [comment]
@FrankSpierings thanks for taking a look! I will try to find some sample .pcap files!

@magnumripper restoring the old file might be a good idea (for now).

**Comment by magnumripper** [comment]
There are sample pcaps in http://openwall.info/wiki/john/sample-non-hashes?&#Kerberos-v5-Pre-Authentication

And here's the writeup I think I used when writing the format way back in 2011 or something:
http://www.securiteam.com/windowsntfocus/5BP0H0A6KM.html

**Comment by FrankSpierings** [comment]
The following will extract the kerberos hashes correctly:
https://github.com/lgandx/PCredz/

Maybe better to not reinvent the wheel?

**Comment by kholia** [comment]
@FrankSpierings great find (again). I will pull stuff from "PCredz" now.

**Comment by FrankSpierings** [comment]
Excellent! thanks!

**Comment by kholia** [comment]
@FrankSpierings ;(

https://github.com/lgandx/PCredz/blob/master/Pcredz#L171 looks super shaky, and doesn't work on our sample files (in fact, it shouldn't work at all).

**Comment by FrankSpierings** [comment]
I see what you mean. It did work for my own captures. I'll have a look at what we can fix with scapy.

**Comment by kholia** [comment]
@FrankSpierings I don't think that it can work with "kerberos" packets at all! it doesn't even extract the "encrypted timestamp" from the packets.

**Comment by FrankSpierings** [comment]
It's not as dodgy as it seems. I'm currently adding code to detect the sample hashes, using PCredz. Standby ;)

**Comment by kholia** [comment]
@FrankSpierings does commit c03a665663108f4ddded23df4ae4beb1699730a7 work for you?

**Comment by kholia** [comment]
Things should be working now (with all the multiple recent commits).
