### ISSUE TITLE
krb5pa type 23 - Unable to crack known password for PA-DATA-ENC-TIMESTAMP

### ISSUE THREAD

**Issue by FrankSpierings** [magnumripper/JohnTheRipper#1381]
I'm unable to crack a known password for a krb5pa type 23 PA-DATA-ENC-TIMESTAMP. The same timestamp is easily decoded by Cain and Abel. The example hash in the code does work.

Any idea's?

**Comment by magnumripper** [comment]
Can you supply a sample? What length is the password? Is there any non-ASCII in the password, username or domain?

**Comment by FrankSpierings** [comment]
Is it possible to give you the PA-DATA-ENC-TIMESTAMP and corresponding password through another (private) channel?

**Comment by FrankSpierings** [comment]
It is a full ascii password, containing numbers and starts with a '#'. If I understand the code correctly, the encoded timestamp in the capture should be sufficient to crack it. Therefore the realm, user etc shouldn't be relevant. Although I tried it with and without in the hash file.

**Comment by magnumripper** [comment]
> Is it possible to give you the PA-DATA-ENC-TIMESTAMP and corresponding password through another (private) channel?

Sure, just mail me in private.

**Comment by magnumripper** [comment]
> If I understand the code correctly, the encoded timestamp in the capture should be sufficient to crack it.

Yes, right. I wrote that long ago. There is a quick-reject feature depending on the timestamp starting with "20" (as in year 2015) so currently if the timestamp is off a lot (like 1999) it won't crack. I can't see that being a problem in real life though, until the year of 2100 :-)

**Comment by magnumripper** [comment]
This was just a formatting problem.

**Comment by FrankSpierings** [comment]
I didn't specify the parameters correctly. Sorry I feel very stupid! Thanks
for the help!

**Comment by magnumripper** [comment]
No problem, comments improved in 794cb0e per your suggestions. Thanks!
