### ISSUE TITLE
Cygwin Fork issue

### ISSUE THREAD

**Issue by richrumble** [magnumripper/JohnTheRipper#1383]
I'm using the recent cygwin build I created and placed in the custom builds wiki page.
Cracking without fork is working fine... The first error is without MPI built, and below that with OMP+MPI, again in the same build I uploaded. I believe the second one is due to the fact that I'm using JtR in a "standalone" method with all the dll's that should be required in a directory and using the native windows cmd shell as opposed to the Cygwin environment. I have tried both in the cygwin shell and both fail with the same trace and the same error for fork. However, when I use --inc instead of --external I do get a trace, but cracking continues.... that is the 3rd output...

C:\Users\richr\Downloads\hash-exercise\jtr>john_64.exe --session=n2 ..\hashes-all.txt-20.nt -fork=8 -format=nt -external=keyboard -pot=ntlm.pot
Using default input encoding: UTF-8
Loaded 15928 password hashes with no different salts (NT [MD4 128/128 SSE4.1 4x3])
Remaining 15591 password hashes with no different salts
Node numbers 1-8 of 8 (fork)
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064EFD160 rbx=000000000022CAC0 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=0000000600028390 rdi=000000000022CB75
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000001 r13=0000000000000000
r14=0000000000000000 r15=000000000022CB75
rbp=000000000022CBD0 rsp=000000000022C9F0
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 8348, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CAC0, 00000000001, 00000000000)
0000022CBD0  001005C5806 (0000022CAC0, 00600028390, 0000022CB75, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064EFD349 rbx=000000000022CAC0 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=0000000600028390 rdi=000000000022CB75
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000001 r13=0000000000000000
r14=0000000000000000 r15=000000000022CB75
rbp=000000000022CBD0 rsp=000000000022C9F0
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 6576, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CAC0, 00000000001, 00000000000)
0000022CBD0  001005C5806 (0000022CAC0, 00600028390, 0000022CB75, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064EFD6F7 rbx=000000000022CAC0 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=0000000600028390 rdi=000000000022CB75
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000001 r13=0000000000000000
r14=0000000000000000 r15=000000000022CB75
rbp=000000000022CBD0 rsp=000000000022C9F0
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 6704, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CAC0, 00000000001, 00000000000)
0000022CBD0  001005C5806 (0000022CAC0, 00600028390, 0000022CB75, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064EFD8E8 rbx=000000000022CAC0 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=0000000600028390 rdi=000000000022CB75
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000001 r13=0000000000000000
r14=0000000000000000 r15=000000000022CB75
rbp=000000000022CBD0 rsp=000000000022C9F0
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 2300, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CAC0, 00000000001, 00000000000)
0000022CBD0  001005C5806 (0000022CAC0, 00600028390, 0000022CB75, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064EFDAC3 rbx=000000000022CAC0 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=0000000600028390 rdi=000000000022CB75
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
Press 'q' or Ctrl-C to abort, almost any other key for status
r11=00000001005E089E r12=0000000000000001 r13=0000000000000000
r14=0000000000000000 r15=000000000022CB75
rbp=000000000022CBD0 rsp=000000000022C9F0
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 4932, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CAC0, 00000000001, 00000000000)
0000022CBD0  001005C5806 (0000022CAC0, 00600028390, 0000022CB75, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
1 0g 0:00:00:10  0g/s 480253p/s 480253c/s 7662MC/s 5rgthgfef..5rgthghbh
Waiting for 7 children to terminate
Session aborted
=============================================================

C:\Users\richr\Downloads\hash-exercise\jtr>john_64-MPI.exe --session=n2 ..\hashes-all.txt-20.nt -fork=8 -format=nt -external=keyboard -pot=ntlm.pot
Warning: '/dev/shm' does not exists or is not a directory.

POSIX shared memory objects require the existance of this directory.
Create the directory '/dev/shm' and set the permissions to 01777.
For instance on the command line: mkdir -m 01777 /dev/shm
Using default input encoding: UTF-8
Loaded 15928 password hashes with no different salts (NT [MD4 128/128 SSE4.1 4x3])
Remaining 15265 password hashes with no different salts
Node numbers 1-8 of 8 (fork)
Cygwin runtime failure: /jtr/john_64-MPI.exe:   Unknown pseudo relocation protocol version 0.

      0 [main] john_64-mpi 7176 fork: child -1 - forked process 6380 died unexpectedly, retry 0, exit code 0xE0000269, errno 11
fork: Resource temporarily unavailable
=============================================================
(cygwin shell)
 ./john_64.exe -session=n2 ../hashes-all.txt-20.nt -fork=8 -format=nt -inc -pot=ntlm.pot
Using default input encoding: UTF-8
Loaded 15928 password hashes with no different salts (NT [MD4 128/128 SSE4.1 4x3])
Remaining 15177 password hashes with no different salts
Node numbers 1-8 of 8 (fork)
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064FB53C2 rbx=000000000022CB40 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=00000001803039A8 rdi=000000000022CCF0
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
rbp=000000000022CBD0 rsp=000000000022CA70
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 2796, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CB40, 00000000000, 00000000000)
0000022CBD0  001005C5806 (0000022CB40, 001803039A8, 0000022CCF0, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064FB559B rbx=000000000022CB40 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=00000001803039A8 rdi=000000000022CCF0
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
rbp=000000000022CBD0 rsp=000000000022CA70
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 9028, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CB40, 00000000000, 00000000000)
0000022CBD0  001005C5806 (0000022CB40, 001803039A8, 0000022CCF0, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064FB5942 rbx=000000000022CB40 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=00000001803039A8 rdi=000000000022CCF0
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
rbp=000000000022CBD0 rsp=000000000022CA70
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 8632, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CB40, 00000000000, 00000000000)
0000022CBD0  001005C5806 (0000022CB40, 001803039A8, 0000022CCF0, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064FB5B14 rbx=000000000022CB40 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=00000001803039A8 rdi=000000000022CCF0
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
rbp=000000000022CBD0 rsp=000000000022CA70
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 1400, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CB40, 00000000000, 00000000000)
0000022CBD0  001005C5806 (0000022CB40, 001803039A8, 0000022CCF0, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=001005E08AE
rax=0000000064FB5CED rbx=000000000022CB40 rcx=0000000100D9F0C0
rdx=0000000000000000 rsi=00000001803039A8 rdi=000000000022CCF0
r8 =0000000180010000 r9 =019DB1DED53E8000 r10=0000000000230000
r11=00000001005E089E r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
rbp=000000000022CBD0 rsp=000000000022CA70
program=C:\Users\richr\Downloads\hash-exercise\jtr\john_64.exe, pid 6360, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022CBD0  001005E08AE (00000000007, 0000022CB40, 00000000000, 00000000000)
0000022CBD0  001005C5806 (0000022CB40, 001803039A8, 0000022CCF0, 0000022CBD0)
0000022CBD0  00180048551 (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  001800463EC (400040004000400, 400040004000400, 400040004000400, 400040004000400)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100628F91 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774059CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007763B981 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Press 'q' or Ctrl-C to abort, almost any other key for status
shilly85         (giurgea)
sexamook         (harbienko)
miconin1         (esmeria)
melacora         (guilbeaux)
megalona         (garmider)
..
bragonen         (alite)
1 94g 0:00:00:45  2.050g/s 12158Kp/s 12158Kc/s 186915MC/s b19pt2g..b19pt81
Waiting for 7 children to terminate
Use the "--show" option to display all of the cracked passwords reliably
Session aborted

**Comment by richrumble** [comment]
No other threads are created as far as I can tell, fork never creates the additional children.

**Comment by magnumripper** [comment]
@jfoug cygwin should work fine with fork nowadays, right? So what could be the problem here? It says *division by zero* both times.

@richrumble are these binaries stripped? The stack traces seem to lack any info about what part of the code crashed.

**Comment by richrumble** [comment]
Stripped? That made me look at what I did to them, I UPX packed john and the dll's to save space, and unpacking them fixed the issue... "I didn't know I couldn't do that officer" ~Dave Chappelle
So I won't be doing that again. Still testing, but I think this is self-induced :(

**Comment by richrumble** [comment]
Fork is working great, this one is totally on me, but I blame UPX ultimately :)

**Comment by magnumripper** [comment]
So problem solved, great!

**Comment by richrumble** [comment]
Sorry about that.

**Comment by magnumripper** [comment]
It's interesting to know that you can't use UPX though. I wonder why. Maybe the problem was in packing the dlls?
