### ISSUE TITLE
Bitcoin2john.py too long of a hash

### ISSUE THREAD

**Issue by giveen** [magnumripper/JohnTheRipper#1415]
I have two seperate wallets that I am attempting to look at the hash.

Wallet #1 pulls a 304 character hash that works fine
Wallet #2 pulls a 370 character hash that does not work

Both are dogecoin wallets, any ideas why the second one isnt working?

**Comment by kholia** [comment]
@giveen how did you generate these wallets? can you generate some sample wallets which exhibit this problem?

**Comment by giveen** [comment]
The wallets were generated with a dogecoin-qt core wallet 1.6, I think.

**Comment by giveen** [comment]
$bitcoin$96$856e263a5c91fa5df09049153f9b3b889b3b5be0185b2ca95a352832e83dc519c630​74a0bbc42615bae8b352149431f3$16$9dd95fb690bb7d5e$125989$96$0135a17e315d528da5978​92e4510d51971a4bb8b2da21f577620a294b8baabb88a0fe5aa4cb672ccdad575a9b9064fb1$130$​04c77ed36b8f0affb1b434ef6975b2fa224131f42ab47df30b7c6b6dffe47cc10c4d92b0bbb82055​21bd7b020db080b355acb75cf9ec04ebef0d2c3889f7369679


vs the one I know works 

$bitcoin$96$14dc151ca145c0ec267b363012338b537df18749abb5f0b2ae0bdcbccb724d12899d​08ad17e99fc0dcaf92c54194c396$16$3d72cf0dd583b5dd$81065$96$5308037f4fb3e4b531c83d​e779fb999863db2746ae0123aa8e5810047486ae9ad958d8dd1d7d0d554761fb588ea7f5ea$66$03​fd63e79f347dc1156e5820ce8ece56b16840bf2766b7aab225395e3e9e6abdc3

**Comment by magnumripper** [comment]
What is the problem you see, does it not load at all or does it load but fails to crack a known password?

There are some weird embedded invisible whitespace in the thing you posted above. Maybe that's a GitHub thing and not relevant to your actual issue? Here's the hash without it, it does load fine here (yours does not).
```
$bitcoin$96$856e263a5c91fa5df09049153f9b3b889b3b5be0185b2ca95a352832e83dc519c63074a0bbc42615bae8b352149431f3$16$9dd95fb690bb7d5e$125989$96$0135a17e315d528da597892e4510d51971a4bb8b2da21f577620a294b8baabb88a0fe5aa4cb672ccdad575a9b9064fb1$130$04c77ed36b8f0affb1b434ef6975b2fa224131f42ab47df30b7c6b6dffe47cc10c4d92b0bbb8205521bd7b020db080b355acb75cf9ec04ebef0d2c3889f7369679
```

**Comment by giveen** [comment]
I was actually using it in hashcat 1.36, but let me try loading it into JtR this week. If it works, I'll just put in a bug report with them.

**Comment by kholia** [comment]
This is turning out to be an instance of PEBKAC? :-)

@giveen please avoid opening bugs against john, without even trying it! 

Additionally, without a solid reproducer, this bug will be very hard to fix.

**Comment by giveen** [comment]
kholia, I never said it was an issue with JtR, but with the script that generates the output.

**Comment by kholia** [comment]
@giveen true, however the script needs to be used with JtR (rest of the tools are not supported here).

**Comment by magnumripper** [comment]
> I never said it was an issue with JtR, but with the script that generates the output.

If you came to that conclusion without actually testing it with JtR, that's a really flawed workflow. But nevermind, if you know the plaintext please test this with JtR and report back. Thanks!

http://hashcat.net/forum/thread-4419.html

**Comment by 01BTC10** [comment]
The hash is not wrong but Hashcat does does not recognize the pubkey format. Older Bitcoin Core wallets use uncompressed pubkey. 

Here I give an easy solution: https://hashcat.net/forum/thread-4419-post-28358.html#pid28358
