### ISSUE TITLE
Clean up the "lineage" format, and get it merged!

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1420]
https://github.com/kholia/JohnTheRipper/tree/lineage

**Comment by kholia** [comment]
@magnumripper @jfoug I could use some help in getting this merged.

https://github.com/kholia/JohnTheRipper/blob/lineage/src/lineage_fmt_plug.c#L345 is tricky to get working in MinGW environment, it seems.

**Comment by jfoug** [comment]
#if HAVE_CRYPT

Wrap the whole format in that.

**Comment by magnumripper** [comment]
Please drop "magnum 2012" from it, that's not correct at all. And add some comments on when/where this format was used IRL.

**Comment by jfoug** [comment]
I see it is wrapped now.  Did this fix the merge into MinGW issues?

**Comment by magnumripper** [comment]
Why wouldn't this format work with MinGW though? Nothing special in there, is it?

**Comment by kholia** [comment]
@magnumripper there is a call to the native "crypt" in this format.

**Comment by magnumripper** [comment]
Aha, I found it.. I only looked in crypt_all().

**Comment by magnumripper** [comment]
Code now in unused/ directory, see #1426

**Comment by kholia** [comment]
There seems to be no interest in this format. So, I am closing this issue (WONTFIX).
