### ISSUE TITLE
CRC-32C: Move functionality into CRC-32 format.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1422]
set_salt() can change the function pointer for crypt_all() so it points to either the crc-32 version of it, or the crc-32c one (depending on tag `$crc32$` or `$crc32c$`).

**Comment by jfoug** [comment]
```
$ ../run/john -test -form=crc32
Will run 8 OpenMP threads
Benchmarking: CRC32 [CRC32 32/64]... (8xOMP) DONE
Many salts:     335544K c/s real, 102957K c/s virtual
Only one salt:  80919K c/s real, 50412K c/s virtual

$ make -s
Make process completed.

$ ../run/john -test -form=crc32
Will run 8 OpenMP threads
Benchmarking: CRC32 [CRC32 32/64 CRC-32C SSE4.2]... (8xOMP) DONE
Many salts:     131403K c/s real, 33882K c/s virtual
Only one salt:  47934K c/s real, 25256K c/s virtual
```

Wow, I have to find out why this huge slowdown happened.  The changes were pretty trivial to get the 1 format to work for both crc32 and crc32c

**Comment by jfoug** [comment]
One issue is the salt went from 4 bytes to 5 bytes.  I just do not see how the change would make that much benchmark performance loss :(

**Comment by jfoug** [comment]
Found the problem.  I changed plaintext length to 125 (it was 31).  I changed it back to 31, and with the crc32c stuff commented out, I get this:

```
$ ../run/john -test -form=crc32
Will run 8 OpenMP threads
Benchmarking: CRC32 [CRC32 32/64 CRC-32C SSE4.2]... (8xOMP) DONE
Many salts:     331961K c/s real, 99921K c/s virtual
Only one salt:  95325K c/s real, 59297K c/s virtual
 ```

I will get the code checked in (with Plaintext set to 31)

**Comment by magnumripper** [comment]
Excellent!

On a side note I was also meaning to add experimental SHA-1/SHA-2 formats using the new SHA intrinsics but apparently it's not yet present in any CPU I can get my hands on. Anyway I suspect it won't help us at all since it will only calculate a single SHA per call, albeit very fast. But it would be nice to try it out.

**Comment by magnumripper** [comment]
Apparently the SHA intrinsics will come with Skylake.
