### ISSUE TITLE
base64conv: problems with empty lines and with '\0' bytes

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1423]
See also comment https://github.com/magnumripper/JohnTheRipper/issues/1399#issuecomment-110311531 and later comments ...

Looks like converting a raw file into hex and back drops empty lines (tested converting john.conf to john.conf.hex, and converting john.conf.hex into john.conf2, then checking the diff).

Apparently, base64conv cuts lines read from raw input files at '\0' bytes (such lines had been created by fuzzing tools mangling input files with password hash samples).

I think base64conf should be able to handle both of these issues, if not with default parameters, then by adding new command line options.

Any thoughts?

**Comment by magnumripper** [comment]
I agree

**Comment by jfoug** [comment]
Would we be ok with handing everything except embedded null bytes?  For one thing, I think john can not input NULL.  I 'might' be able to get null working, but I am not sure.

Ok, I got it working.

I added 2 params, which work together.

```
-r fname       This lists process the 'whole' file we read it in.
-w ofname     This is the name of the output file we write to.
NOTE, can not use redirection  the -r and -w have to be used as a pair.
```

So 

./basename -q -r infile -w outfile1 -i raw -o hex
./basename -q -r outfile1 -w outfile2 -i hex -o raw

infile and outfile2 should be identical.   I should be able to finish this up pretty easily.

**Comment by jfoug** [comment]
```
$ ../run/base64conv -q -r in -w in1 -i raw -o hex

$ ../run/base64conv -q -r in1 -w in2 -o raw -i hex

$ diff -b in in2
```

in (and in2) were 256 byte file, 0x01 to 0xff 0x00  (null byte last byte of file).   The tool now transfers this file 100% intact.
