### ISSUE TITLE
Travis MinGW builds not separate

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1425]
If possible, we should have the MinGW build as a separate job, just like gcc and clang builds are.

**Comment by jfoug** [comment]
@kholia is looking at a different CI.  Possibly we only test (and deploy) mingw on that one, if it works.   That CI has it's own VM inside the VM.  The base VM is Ubuntu, which has crappy support for MinGW.  But with VM software, we can install Fedora which has wonderful MinGW support environment.

At least, that is his plan.  It is CircleCI
