### ISSUE TITLE
Add support for TACACS+ hashes

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1430]
See http://www.insinuator.net/2015/06/tacacs-module-for-loki/ for details.

https://wiki.gentoo.org/wiki/Tac_plus

http://networkjutsu.com/tacacs/

http://www-arc.com/sara/cve/tacacs_server.html

http://agrrrdog.blogspot.in/2015/11/3-attacks-on-cisco-tacacs-bypassing.html

https://github.com/kholia/my-pcaps/tree/master/loki-pcaps

**Comment by jfoug** [comment]
@kholia if you can get to this one in near future, then please add it as a jumbo-2 milestone.

**Comment by kholia** [comment]
https://github.com/kholia/TacoTaco/blob/master/tac2cat.py

This looks easy enough?
