### ISSUE TITLE
Add LM OpenCL format, with GPU-side mask support.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1432]
@Sayantan2048 I just realized the 2013 bleeding-mask branch had LM-opencl with mask support, while current bleeding-jumbo doesn't have an LM-opencl format at all (I wondered why it was gone and realized we never had it, LOL). Would it be hard to import it and update it to current code?

**Comment by Sayantan2048** [comment]
Will do.
