### ISSUE TITLE
Use clock_gettime(CLOCK_MONOTONIC, ...) instead of gettimeofday?

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1438]
Especially OpenCL format implementations seem to use gettimeofday to calculate differences between start time and end time.
Shouldn't `clock_gettime(CLOCK_MONOTONIC, ...)` be used here instead?
Reasons:
-leap seconds (the next one on June, 30th)
-NTP
etc.
clock_gettime() exists for `_POSIX_C_SOURCE >= 199309L`.

**Comment by magnumripper** [comment]
The risk for this to cause a problem should be pretty slim, but if it's portable I guess we should change it anyway.

**Comment by magnumripper** [comment]
There doesn't seem to exist any `clock_gettime()` in OSX. That alone suggests this will introduce portability problems.

**Comment by magnumripper** [comment]
http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x
