### ISSUE TITLE
--regex=alpha or --regex='\0something' should work with --incremental and --markov (and may be even --external and --mask)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1445]
I think it would be great if you could run `./john --incremental=lower --regex=alpha:leet` etc. 
```
(bleeding-jumbo)run $ ./john --incremental=lower --regex=alpha:leet --stdout 
Warning: regex mode currently can't be resumed if aborted
alpha:leet
1p 0:00:00:00 0.00% 7.142p/s alpha:leet
(bleeding-jumbo)run $ ./john --markov --regex='test\0test' --stdout 
Warning: regex mode currently can't be resumed if aborted
testtest
1p 0:00:00:00 0.00% 7.692p/s testtest
```
But instead of treating the candidates generated by --incremental or --markov as input words for regex mode, --regex is run as a standalone mode.
Of course, when combined with --incremental or --markov, --regex=alpha:mode or --regex='...\0...' is required.

Combining --regex and --external is trickier, since with external filters, --regex should generate the passwords, otherwise, --regex should generate the candidates based on the candidates generated by --external.
Similarly, when combining --regex and --mask, any one of them should be allowed to generate the standalone passwords, while the other mode takes these as input words...

Current situation:
```
(bleeding-jumbo)run $ ./john --mask=?l?l?l --regex='test\0test' --stdout 
Invalid options combination or duplicate option: "--mask=?l?l?l"
(bleeding-jumbo)run $ ./john  --external=sequence --regex=leet --stdout=8
Warning: external mode 'sequence' can't be resumed if aborted
Warning: regex mode currently can't be resumed if aborted
leet
1p 0:00:00:00 0.00% 7.692p/s leet
(bleeding-jumbo)run $ ./john  --regex="[abc][def]" --external=filter_rot13 --stdout
No generate() for external mode: filter_rot13
(bleeding-jumbo)run $ ./john  --external=sequence --regex=alpha:leet --stdout
Warning: external mode 'sequence' can't be resumed if aborted
Warning: regex mode currently can't be resumed if aborted
alpha:leet
1p 0:00:00:00 0.00% 7.692p/s alpha:leet
```

**Comment by magnumripper** [comment]
In wordlist mode, we can have an external filter or a regex, but not both. This is for performance reasons but we might want to test the impact of actually supporting both (and I'm talking about *the impact when supported but not actually used*).

**Comment by frank-dittrich** [comment]
@magnumripper I don't understand what you mean.
You can use --wordlist with either --external or --regex, so both are supported.

```
(bleeding-jumbo)run $ cat test
abc
123
```

```
(bleeding-jumbo)run $ head -n 4 john.local.conf
[List.Rules:shift]
{
}

```

Wordlist (+rules) + regex:
```
(bleeding-jumbo)run $ ./john --wordlist=test --rules=shift --stdout --regex='\0-\0' 
bca-bca
231-231
cab-cab
312-312
4p 0:00:00:00 100.00% (2015-06-18 18:31) 30.76p/s 312-312
(bleeding-jumbo)run $ ./john --wordlist=test --rules=shift --stdout --regex=alpha:leet
buf=[b8]c[a4@]
bca
8ca
bc4
8c4
bc@
8c@
buf=231
231
buf=c[a4@][b8]
cab
c4b
c@b
ca8
c48
c@8
buf=312
312
14p 0:00:00:00 100.00% (2015-06-18 18:31) 116.6p/s 312
```
(I really think we should put the `printf("buf=...` in between `#ifdef DEBUG` ... `#endif` once Jan has fixed the currently known rexgen issues (he is currently working on them).

Wordlist (+rules) +external:

```
(bleeding-jumbo)run $ ./john --wordlist=test --rules=shift --stdout --external=filter_rot13 
opn
pno
2p 0:00:00:00 100.00% (2015-06-18 18:35) 15.38p/s pno
(bleeding-jumbo)run $ ./john --wordlist=test --rules=shift --stdout --external=filter_digits 
231
312
2p 0:00:00:00 100.00% (2015-06-18 18:35) 14.28p/s 312
```

For combining the two, you would need to apply them in a sequence (regex first, then external filter, or first filter, then regex, or, even more confusing, depending on the sequence of command line parameters).

The current situation needs fixing:

This seems to work:
```
(bleeding-jumbo)run $ ./john --wordlist=test --rules=shift --stdout --regex='\0-\0' --external=filter_rot13
bca-bca
cab-cab
2p 0:00:00:00 100.00% (2015-06-18 18:40) 16.66p/s cab-cab
```
(rules=shift applied, regex applied, external filter applied.

```
(bleeding-jumbo)run $ ./john --wordlist=test --rules=shift --stdout --regex='\0-\0' --external=filter_digits
0p 0:00:00:00 100.00% (2015-06-18 18:41) 0p/s
```
Apparently, the external filter is applied after the regex, otherwise, we should have seen 231-231 and 312-312.

But:
```
(bleeding-jumbo)run $ ./john --wordlist=test --rules=shift --stdout --regex=alpha:leet --external=filter_rot13
buf=[o0]pn
bca
0ca
buf=pn[o0]
cab
ca0
4p 0:00:00:00 100.00% (2015-06-18 18:44) 33.33p/s ca0
(bleeding-jumbo)run $ ./john --wordlist=test --stdout --regex=alpha:leet --external=filter_rot13
buf=n[o0]p
abc
a0c
2p 0:00:00:00 100.00% (2015-06-18 18:45) 14.28p/s a0c
```
This is broken.

**Comment by magnumripper** [comment]
> I don't understand what you mean. You can use --wordlist with either --external or --regex, so both are supported.

I meant *either* and *not both at once*. I'm surprised it sort of worked for you in some cases and now that I look at the code, maybe that is actually intended (Jim wrote it). I always thought using both at once wasn't supported at all.

For mask mode, we definitely support *either* mask or filter but not *both*.

**Comment by magnumripper** [comment]
And it's not always obvious how it should work, if supported. Should we first apply a filter, then a regex? Or should we first apply a regex (that may lead to many words from one original) and then a filter on each resulting word?

Mask mode has the same property of being able to produce many candidate from one input word.

**Comment by magnumripper** [comment]
Apparently I do not know what I'm talking about. I see now mask mode **does** support external filters. It's just that when it's used they are not applied in wordlist.c but in mask.c

I should probably shut up for now.

**Comment by magnumripper** [comment]
@frank-dittrich you have quite a lot of testing to do now :wink: 

I bet there's some minor flaws regarding aggregated max-length and things like that but in general we should be all set. Please open separate (at least per parent mode) new issues for any bugs seen.

**Comment by magnumripper** [comment]
```
$ ./john --incremental=lower --regex=alpha:leet --stdout | head
Press 'q' or Ctrl-C to abort, almost any other key for status
samila
$amila
5amila
s4mila
$4mila
54mila
s@mila
$@mila
5@mila
sam!la

$ ./john --markov --regex='test\0test' --stdout | head
Press 'q' or Ctrl-C to abort, almost any other key for status
MKV start (stats=$JOHN/stats, lvl=200 len=11 pwd=259356429)
testchanerereretest
testchanerereritest
testchanerereratest
testchanerererotest
testchanererertest
testchanerereletest
testchanererelatest
testchanererelitest
testchanererelotest
testchanerereltest
```

**Comment by magnumripper** [comment]
> Combining --regex and --external is trickier, since with external filters, --regex should generate the passwords, otherwise, --regex should generate the candidates based on the candidates generated by --external.
Similarly, when combining --regex and --mask, any one of them should be allowed to generate the standalone passwords, while the other mode takes these as input words...

See #1890 for that. It's very trivial except for the options parsing...
