### ISSUE TITLE
Ctrl+C crashes MinGW builds

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1449]
![mingw_ctrl c_crash](https://cloud.githubusercontent.com/assets/79528/8258810/5882362a-16b8-11e5-9b20-166cc533500f.png)

@jfoug solving this could be really helpful for our GUI team!

**Comment by jfoug** [comment]
My build is not crashing at all with ^C   I have tried both OMP and non-OMP builds  (From cmd.exe prompt).   Note, running on Win7

**Comment by magnumripper** [comment]
Closing for WO.
