### ISSUE TITLE
Dynamic:  Audit for new optimizations (flags) methods.

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1453]
Here is a prime example:  b083104

I am sure there are many others.

**Comment by jfoug** [comment]
I have added flags for 'all' crypt types, to handle the CRYPT($s) optimization.  I now have to add it to the types.

NOTE, I replicated dynamic_67 (calling it dynamic_69, so I can test side by side).  Here is the difference in speed  (should be about 25% better, and it is).  dyna-67 has 4 hash limbs (the final sha256 is a 2 limb hash), and the 'optimized' version requires only 3 limb hashes (the $s crypt is done at salt load).

```
$ ../run/john -test=3 -form=dynamic_67
Benchmarking: dynamic_67 [sha256(sha256($s).sha256($p)) 128/128 AVX 4x]... DONE
Many salts:     1697K c/s real, 1696K c/s virtual
Only one salt:  1640K c/s real, 1639K c/s virtual

$ ../run/john -test=3 -form=dynamic_69
Benchmarking: dynamic_69 [sha256(sha256($s).sha256($p)) 128/128 AVX 4x]... DONE
Many salts:     2142K c/s real, 2151K c/s virtual
Only one salt:  2008K c/s real, 2042K c/s virtual
```

**Comment by magnumripper** [comment]
> Now it works just fine for all hashes, so tiger(tiger($s).$p) would be able to be optimized.

Good stuff!

**Comment by jfoug** [comment]
Also added the optimization of doing crypt($p) putting the hex result into input1 (or at offset sizeof(crypt_binary)*2).  Again, this was ONLY done on MD5 before (I added SHA1 and SHA256 recently).  Now it is handled by all types.  This gives close to double speed on many salt formats for some types  :   crypt(crypt($p).s) types.

I have updated all of the 'large hash' (flat hash) types.   NOTE, the 2nd optimization (the crypt putting hex into input 1), is ONLY usable in 'flat' (or a non-sse build).  If the format is an interleaved SIMD, the format does NOT honor that flag.

**Comment by jfoug** [comment]
More optimizations (smaller, but still some)

f66b603

This optimizes   md5(md5(md5($p))) types   (would work for any 16 byte hash (md5, md4, ripemd128, etc). I do not plan on adding this optimization for all hash lengths.  There is 'some' gain, but not much.  The ROI on the amount of time to code it, and amount of actual code added simply is not good enough.

**Comment by jfoug** [comment]
After 1955702  I think I have about all of them. NOTE, i am still looking at the #saltfail type stuff.
