### ISSUE TITLE
compile failure with icc(14.0.0) on super

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1461]
Error message:
```
build_table.c(226): internal error: assertion failed at: "shared/cfe/edgcpfe/exprutil.c", line 18351

                iter = offset_data[offset_data_idx].iter++;
```

**Comment by Sayantan2048** [comment]
Try this:
change line 24 in build_table.c to
```
#if 0
```

**Comment by zzlei** [comment]
```c
#if _OPENMP > 201105
#define MAYBE_PARALLEL_FOR _Pragma("omp for")
#define MAYBE_ATOMIC_WRITE _Pragma("omp atomic write")
#define MAYBE_ATOMIC_CAPTURE _Pragma("omp atomic capture")
#else
#define MAYBE_PARALLEL_FOR _Pragma("omp single")
#define MAYBE_ATOMIC_WRITE
#define MAYBE_ATOMIC_CAPTURE
#endif
```

The `_OPENMP` defined by icc 14.0.0 is 201107, slightly higher than the threshold you used here. Maybe this version checking should be further refined?

**Comment by magnumripper** [comment]
Try after 48fc0f773

**Comment by zzlei** [comment]
It works. But I wonder how this threshold is chosen. Is there a standard minimum version requirement for those `_Pragma` features? Or we just test compilers one by one?

**Comment by zzlei** [comment]
After searching a bit on Google, I think this is another icc bug. According to [this](https://software.intel.com/en-us/forums/topic/277142) post, the `internal error` represents an internal compiler error, not something wrong with the code.

**Comment by Sayantan2048** [comment]
Actually it is a case where the compiler doesn't support some of the openmp constructs. In general, compilers with openmp 3.0 or higher support the constructs.

**Comment by zzlei** [comment]
Well, I think icc 14.0.0 does support the OpenMP atomic feature, which is used in some other formats and compiles fine, although they're in the `#pragma omp ...` form instead of `_Pragma("omp ...")` here.
