### ISSUE TITLE
Compile failure. Please fix ASAP

### ISSUE THREAD

**Issue by Sayantan2048** [magnumripper/JohnTheRipper#1462]
Configured for building John the Ripper jumbo:

Target CPU .................................. x86_64 XOP, 64-bit LE
AES-NI support .............................. depends on OpenSSL
Target OS ................................... linux-gnu
Cross compiling ............................. no
Legacy arch header .......................... x86-64.h

Optional libraries/features found:
Experimental code ........................... no
OpenMPI support (default disabled) .......... no
Fork support ................................ yes
OpenMP support .............................. yes (not for fast formats)
OpenCL support .............................. yes
CUDA support ................................ no
Generic crypt(3) format ..................... yes
Rexgen (extra cracking mode) ................ no
GMP (PRINCE mode and faster SRP formats) .... no
PCAP (vncpcap2john and SIPdump) ............. yes
Z (pkzip format, gpg2john) .................. yes
BZ2 (gpg2john extra decompression logic) .... yes
128-bit integer (faster PRINCE mode) ........ yes
Memory map (share/page large files) ......... yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ............ disabled
AddressSanitizer ("ASan") ................... enabled

$ make -s -j4
/usr/bin/ar: creating aes.a
luks2john.o: In function `hash_plugin_parse_hash':
/home/sayantan/JohnTheRipper/src/luks2john.c:179: undefined reference to `BIO_f_base64'
/home/sayantan/JohnTheRipper/src/luks2john.c:179: undefined reference to `BIO_new'
/home/sayantan/JohnTheRipper/src/luks2john.c:180: undefined reference to `BIO_new_fp'
/home/sayantan/JohnTheRipper/src/luks2john.c:181: undefined reference to `BIO_push'
/home/sayantan/JohnTheRipper/src/luks2john.c:182: undefined reference to `BIO_set_flags'
/home/sayantan/JohnTheRipper/src/luks2john.c:183: undefined reference to `BIO_write'
/home/sayantan/JohnTheRipper/src/luks2john.c:184: undefined reference to `BIO_ctrl'
/home/sayantan/JohnTheRipper/src/luks2john.c:189: undefined reference to `BIO_free_all'
collect2: error: ld returned 1 exit status
make[1]: *** [../run/luks2john] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2

**Comment by magnumripper** [comment]
This is a dupe of #1451, and there is a workaround described
