### ISSUE TITLE
Add preprocessor warnings for formats that are skipped

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1474]
Otherwise, users and developers will not notice that (and why) they do not get all the formats.
./configure of course mentions when you don't get OpenCL and CUDA formats in the "feature summary" output.
It also mentions pkzip format and generic crypt(3) format.
But it doesn't mention that you don't get OpenVMS format on big endian systems, or if some formats are suppressed due to missing CPU features (SSE4.1, etc).

In these cases, we should add a preprocessor warning, either for DEBUG builds or for all builds.

See comments on commit https://github.com/magnumripper/JohnTheRipper/commit/b1da77d8a235a0517782700f1cbe536e4203b0ed.

At least these formats can be skipped depending on endianness, CPU features, etc:
- [x] Stribog-256
- [x] Stribog-512
- [x] OpenVMS

So we need to add preprocessor warnings in case they are skipped.

**Comment by zzlei** [comment]
The build info of a POWER build compared with a typical x86 build (no CUDA or OpenCL):
```diff
1,3c1,3
< Version: 1.8.0-jumbo-1-2778-g9977f4c+
< Build: linux-gnu 64-bit powerpc64le-autoconf OMP
< Arch: 64-bit BE
---
> Version: 1.8.0-jumbo-1-2779-g2bda069
> Build: linux-gnu 64-bit AVX2-autoconf OMP
> Arch: 64-bit LE
15c15
< Compiler version: 4.9.2 20141101 (Red Hat 4.9.2-1)
---
> Compiler version: 4.9.2
17c17
< GNU libc version: 2.20 (loaded: 2.20)
---
> GNU libc version: 2.15 (loaded: 2.15)
19,21c19,21
< OpenSSL library version: 0100010bf
< OpenSSL 1.0.1k-fips 8 Jan 2015
< GMP library version: 6.0.0
---
> OpenSSL library version: 01000100f
> OpenSSL 1.0.1 14 Mar 2012
> GMP library version: 5.0.2
```

And the configure summary of the POWER build:
```
Target CPU .................................. powerpc64le, 64-bit BE
AES-NI support .............................. no
Target OS ................................... linux-gnu
Cross compiling ............................. no
Legacy arch header .......................... ppc32.h

Optional libraries/features found:
Experimental code ........................... no
OpenMPI support (default disabled) .......... no
Fork support ................................ yes
OpenMP support .............................. yes (not for fast formats)
OpenCL support .............................. no
CUDA support ................................ no
Generic crypt(3) format ..................... yes
Rexgen (extra cracking mode) ................ no
GMP (PRINCE mode and faster SRP formats) .... yes
PCAP (vncpcap2john and SIPdump) ............. no
Z (pkzip format, gpg2john) .................. yes
BZ2 (gpg2john extra decompression logic) .... yes
128-bit integer (faster PRINCE mode) ........ yes
Memory map (share/page large files) ......... yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ............ disabled
AddressSanitizer ("ASan") ................... disabled
```
There's another minor issue. The POWER platform in use is actually configured as little endian, but is reported as big endian here.

**Comment by frank-dittrich** [comment]
So, which formats are missing?
I am sure that OpenVMS format is most likely missing, I recently saw the `if ARCH_LITTLE_ENDIAN` in vms_fmt_plug.c.
But there must be some more that are missing in your POWER build.

**Comment by zzlei** [comment]
The missing formats are:
```
Raw-SHA1-Linkedin
Raw-SHA256-ng
Raw-SHA512-ng
Raw-SHA1-ng,
Stribog-256
Stribog-512
OpenVMS
```

**Comment by frank-dittrich** [comment]
`#if defined(SIMD_PARA_SHA1)` causes Raw-SHA1-Linkedin to be excluded.
`#if SIMD_COEF_32` causes Raw-SHA256-ng and Raw-SHA512-ng to be excluded.
`#if defined(SIMD_COEF_32) && (SIMD_COEF_32 < 16 || ARCH_BITS >= 64) && !_MSC_VER` causes Raw-SHA1-ng to be excluded.
For the `*-ng` formats there are similar formats without the `-ng` suffix. These should crack the same hashes, just a little slower.
Nevertheless, I think we should add a `#warning ...` here.
`#if __SSE4_1__` excludes Stribog-256 and Stribog-512.
And OpenVMS apparently only works for LE archs.

**Comment by zzlei** [comment]
In configure:
```
 7741   powerpcle) ARCH_LINK=ppc32.h endian=little ;;
 7742   powerpc*) ARCH_LINK=ppc32.h endian=big ;;
```
Both a LE build and a BE build use ppc32.h. But in ppc32.h:
```c
 26 #define ARCH_LITTLE_ENDIAN      0
```
This is problematic.

**Comment by frank-dittrich** [comment]
@zzlei what is the output of `--list=build-info` for your build?

**Comment by zzlei** [comment]
```
Version: 1.8.0-jumbo-1-2778-g9977f4c+
Build: linux-gnu 64-bit powerpc64le-autoconf OMP
Arch: 64-bit BE
$JOHN is ../run/
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
File locking: fcntl()
Compiler version: 4.9.2 20141101 (Red Hat 4.9.2-1)
gcc version: 4.9.2
GNU libc version: 2.20 (loaded: 2.20)
Crypto library: OpenSSL
OpenSSL library version: 0100010bf
OpenSSL 1.0.1k-fips 8 Jan 2015
GMP library version: 6.0.0
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by jfoug** [comment]
The problem is this is an LE system, but configure picks BE

**Comment by magnumripper** [comment]
> In configure:
```
 7741   powerpcle) ARCH_LINK=ppc32.h endian=little ;;
 7742   powerpc*) ARCH_LINK=ppc32.h endian=big ;;
```
Both a LE build and a BE build use ppc32.h. But in ppc32.h:
```c
 26 #define ARCH_LITTLE_ENDIAN      0
```
This is problematic.

I shouldn't be, the file starts with
```c
#if AC_BUILT
#include "autoconfig.h"
#else
```
and the things you refer to come after the #else

**Comment by magnumripper** [comment]
> In configure:
```
 7741   powerpcle) ARCH_LINK=ppc32.h endian=little ;;
 7742   powerpc*) ARCH_LINK=ppc32.h endian=big ;;
```

I think we need this
```diff
diff --git a/src/configure.ac b/src/configure.ac
index 2bffa44..d9c8db5 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -320,6 +320,8 @@ case "$host_cpu" in
   mips64*) ARCH_LINK=mips64.h endian=big ;;
   mips*) ARCH_LINK=mips32.h endian=big ;;
   pdp*) ARCH_LINK=autoconf_arch.h endian=little ;;
+  powerpc64le) ARCH_LINK=ppc64.h endian=little ;;
+  powerpc64*) ARCH_LINK=ppc64.h endian=big ;;
   powerpcle) ARCH_LINK=ppc32.h endian=little ;;
   powerpc*) ARCH_LINK=ppc32.h endian=big ;;
   sparc64) ARCH_LINK=sparc64.h endian=big ;;
```

**Comment by frank-dittrich** [comment]
Do we need to sanity-check the endianness of the build against any of these?
```
$ gcc -dM -E -x c /dev/null | grep -E "(ORDER|ENDIAN)"
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __ORDER_PDP_ENDIAN__ 3412
#define __ORDER_BIG_ENDIAN__ 4321
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
$ clang -dM -E -x c /dev/null | grep -E "(ORDER|ENDIAN)"
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __LITTLE_ENDIAN__ 1
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```

**Comment by zzlei** [comment]
```diff
diff --git a/src/configure.ac b/src/configure.ac
index 2bffa44..d9c8db5 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -320,6 +320,8 @@ case "$host_cpu" in
   mips64*) ARCH_LINK=mips64.h endian=big ;;
   mips*) ARCH_LINK=mips32.h endian=big ;;
   pdp*) ARCH_LINK=autoconf_arch.h endian=little ;;
+  powerpc64le) ARCH_LINK=ppc64.h endian=little ;;
+  powerpc64*) ARCH_LINK=ppc64.h endian=big ;;
   powerpcle) ARCH_LINK=ppc32.h endian=little ;;
   powerpc*) ARCH_LINK=ppc32.h endian=big ;;
   sparc64) ARCH_LINK=sparc64.h endian=big ;;
```
I think that's right solution. The actually CPU name is `powerpc64le`, and it was wrongly matched with `powerpc*`, thus the wrong endianness report.

**Comment by frank-dittrich** [comment]
> Version: 1.8.0-jumbo-1-2778-g9977f4c+
> Build: linux-gnu 64-bit powerpc64le-autoconf OMP
> Arch: 64-bit BE

What commit is 9977f4c? I don't find it in bleeding-jumbo.
What local changes do you have on top of commit 9977f4c, as indicated by the `+`?

bleeding-jumbo has the
```
 powerpc64le) ARCH_LINK=ppc64.h endian=little ;;
```
line in configure.ac since commit 93972e9a
```
commit 93972e9ac7b00d38a61e57d992403e8b0a264ede
Author: magnum <john.magnum@hushmail.com>
Date:   Tue May 13 16:18:25 2014 +0200

    Major autoconf arch.h tweaks. Separate generic tests from x86-specific
    ones. Most targets should now have basic buildability...
```

**Comment by zzlei** [comment]
@frank-dittrich It's a local commit, including modification of byteorder.h and something regarding to MIC.

```
powerpc64le) ARCH_LINK=ppc64.h endian=little ;;
```
This should solve my problem, but I couldn't see it in configure.ac as for now.

**Comment by frank-dittrich** [comment]
But if than is a local commit, how can github point to it (https://github.com/magnumripper/JohnTheRipper/commit/9977f4c8d3fef9fc900225eceab957721191fd0d) and show https://github.com/magnumripper/JohnTheRipper/commit/bd79343b7e0a36a6ac4fb8756b5b156531eb6f93 as the parent commit?

**Comment by zzlei** [comment]
Well, when I say 'local', I mean it's in my fork, but not pulled into the main repo yet.

**Comment by frank-dittrich** [comment]
But if bd79343 is the parent of 9977f4c, then either 9977f4c or your local (uncommitted) changes must have broken configure.ac, because when you check out bd79343, you an see
```
((HEAD detached at bd79343))src $ grep -n powerpc configure.ac 
323:  powerpcle) ARCH_LINK=ppc32.h endian=little ;;
324:  powerpc*) ARCH_LINK=ppc32.h endian=big ;;
```

**Comment by zzlei** [comment]
@frank-dittrich I'm a little confused of your words...

```
323:  powerpcle) ARCH_LINK=ppc32.h endian=little ;;
324:  powerpc*) ARCH_LINK=ppc32.h endian=big ;;
```
Yes, I do see those lines when I checkout https://github.com/magnumripper/JohnTheRipper/commit/bd79343b7e0a36a6ac4fb8756b5b156531eb6f93. What I couldn't see is thing like this
```
 powerpc64le) ARCH_LINK=ppc64.h endian=little ;;
```
I checked magnum's repo again, and the latest configure.ac doesn't contain this line. So maybe you're mistaking `powerpc64le` for `powerpcle`?

**Comment by frank-dittrich** [comment]
@zzlei  Yes, sorry, my fault. I guess I need a break.

**Comment by frank-dittrich** [comment]
See commit b3293b0a4f6b5abfc0450d03b7d2aff9036472fb

Now that Jim disabled some tools like luks2john 
```
+#if !AC_BUILT || HAVE_BIO_NEW
```
we might also need to add a warning if such tools disappear...

**Comment by frank-dittrich** [comment]
Stribog formats now have a warning:
```
ebbbfc1a (Dhiru Kholia   2015-05-16 17:36:40 +0200 493) #endif /* plugin stanza */
95df0edf (magnum         2015-05-20 00:25:24 +0200 494) 
3f31249a (Frank Dittrich 2016-01-12 15:39:29 +0100 495) #else
1a52a3b2 (JimF           2016-01-15 16:02:01 -0600 496) #if !defined(FMT_EXTERNS_H) && !defined(FMT_REGISTERS_H)
1a52a3b2 (JimF           2016-01-15 16:02:01 -0600 497) #ifdef __GNUC__
3f31249a (Frank Dittrich 2016-01-12 15:39:29 +0100 498) #warning Stribog-256 and Stribog-512 formats require SSE 4.1, formats disabled
1a52a3b2 (JimF           2016-01-15 16:02:01 -0600 499) #elif _MSC_VER
1a52a3b2 (JimF           2016-01-15 16:02:01 -0600 500) #pragma message(": warning Stribog-256 and Stribog-512 formats require SSE 4.1, formats disabled:")
1a52a3b2 (JimF           2016-01-15 16:02:01 -0600 501) #endif
b6744dbe (Frank Dittrich 2016-01-12 23:58:48 +0100 502) #endif
95df0edf (magnum         2015-05-20 00:25:24 +0200 503) #endif /* __SSE4_1__ */
```

**Comment by magnumripper** [comment]
I now removed the following from OP

- [ ] Raw-SHA1-Linkedin
- [ ] Raw-SHA256-ng
- [ ] Raw-SHA512-ng
- [ ] Raw-SHA1-ng

Reason being that all -ng formats are merely other versions of more portable ones, and the linkedin format isn't very interesting anymore (all complete hashes were later leaked IIRC).

Only one left is thus VMS. It gets disabled on BE platforms.
