### ISSUE TITLE
dynamic hash failure (md5 and md4 in same expression)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1479]
The dynamic_compiler has turned up a problem.  I get cmp_all(1) failure for this script (generated using the dynamic_compiler). I have checked this out, and it 'should' be OK. All of the test strings are correct, and the script should be correct.  Pretty much any md5(md4(...))  or md4(md5(...)) seems to fail for me.  I 'think' the para being used for md5 and md4 are the same on my build.

```
[List.Generic:dynamic_1599]
Expression=dynamic=md5(md4($p))
Flag=MGF_FLAT_BUFFERS
Test=$dynamic_1599$0cb0aaddd873eb3248032ec862a8e7e6:abc
Test=$dynamic_1599$a78c5a7483f204f05efb3c36217cd353:john
Test=$dynamic_1599$8e293278c5c90aaa8b188bc06d6af204:passweird
Func=DynamicFunc__clean_input_kwik
Func=DynamicFunc__append_keys
Func=DynamicFunc__MD4_crypt_input1_overwrite_input2
Func=DynamicFunc__MD5_crypt_input2_to_output1_FINAL
```

NOTE, is there a way to list the SIMD_COEF32 or *_PARA values we have built with??  If not, then I think these should be added to the --list=build-info

**Comment by magnumripper** [comment]
>  is there a way to list the SIMD_COEF32 or *_PARA values we have built with?

We could add it but I think we have too much in there already. You can see it in the algo name of most formats, as in:
```
Benchmarking: Raw-MD5 [MD5 128/128 AVX 4x3]... DONE
Raw:	34019K c/s real, 34019K c/s virtual
```
The 4x3 says coef 4, para 3.

**Comment by jfoug** [comment]
I guess.  I have listconf done, but if you think it is too much, I will drop it.  As you see from my format, it was  md5(md4($p))  The algo name does not carry information about this.  You need to know them both.  Yes, easy way is to check raw-md5 and raw-md4.

**Comment by magnumripper** [comment]
It would be convenient to read all paras in one place, I give you that. What I dislike is having a zillion lines output that's never really needed. Current output is 27 lines for CUDA+OpenCL build. I think the coef's are not needed at all (I'm sure you know them by heart from reading eg. "AVX") but if we can stuff all para's in one line in some sane format, I'm totally fine with it.

Hmm we actually repeat arch info "64-bit" in current output:
```
Version: 1.8.0.6-jumbo-1-166-gf4e5114
Build: darwin14.3.0 64-bit AVX-autoconf OMP
Arch: 64-bit LE
(...)
```

Perhaps we could do something like this:
```
Version: 1.8.0.6-jumbo-1-166-gf4e5114
Build: darwin14.3.0 64-bit LE autoconf OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
(...)
```
This removes no info but adds paras, without increasing the number of lines.

Perhaps @frank-dittrich will complain that there might be a script somewhere depending on the "Arch:" line though. And he'd be right, at least in theory. I'm open for ideas.

**Comment by magnumripper** [comment]
Back on topic, who tells the MD5 about the length? Is `DynamicFunc__MD4_crypt_input1_overwrite_input2` implying a "set length to 16" as well?

**Comment by frank-dittrich** [comment]
@jfoug I had a similar listconf.c patch ready in the past, tried to convince magnum, failed, and finally gave up.
I'd still love to see it. If magnum really thinks it is too much, may be only for `#ifdef DEBUG`.

Or, we introduce `--list=all-build-details`. (just kidding)

**Comment by magnumripper** [comment]
We can have `--list=Frank's-details` with all sorts of info :laughing:

**Comment by frank-dittrich** [comment]
+1 for making --list=build-info depend on user name.

**Comment by magnumripper** [comment]
But then we need --list=username for knowing what we actually get :dancers:

**Comment by frank-dittrich** [comment]
> This removes no info but adds paras, without increasing the number of lines.
> 
> Perhaps @frank-dittrich <https://github.com/frank-dittrich> will
> complain that there might be a script somewhere depending on the "Arch:"
> line though. And he'd be right, at least in theory. I'm open for ideas.

You are, of course, right.

https://xkcd.com/1172/

**Comment by magnumripper** [comment]
> Pretty much any md5(md4(...)) or md4(md5(...)) seems to fail for me

How about dynamic_34? It doesn't fail for me.
```
//dynamic_34 --> md5(md4($p))
static DYNAMIC_primitive_funcp _Funcs_34[] =
{
        //MGF_KEYS_INPUT
        //MGF_SET_INP2LEN32
        DynamicFunc__crypt_md4,
        //DynamicFunc__clean_input2_kwik,
        //DynamicFunc__append_from_last_output_to_input2_as_base16,
        DynamicFunc__overwrite_from_last_output_to_input2_as_base16_no_size_fix,
//      DynamicFunc__set_input2_len_32,
        DynamicFunc__crypt_md5_in2_to_out1,
        NULL
};
static struct fmt_tests _Preloads_34[] =
{
        {"$dynamic_34$70bd0343fde5c0ce439b8eaed1c5930d","test1"},
        {"$dynamic_34$7e716c197034cfc4dcdc1d23234bf65a","thatsworking"},
        {"$dynamic_34$68fb8e1b89e88a8d006905edf3c3207f","test3"},
        {"$dynamic_34$1af18a178e07721f618dbe6ef4340aea", "1234567890123456789012345678901234567890123456789012345"},
#ifndef SIMD_COEF_32
        {"$dynamic_34$e4f6c3f090122b8002e6d3951327926c", "12345678901234567890123456789012345678901234567890123456789012345678901234567890"},
#endif
        {NULL}
};
```

**Comment by jfoug** [comment]
I will have to look at that one.

**Comment by jfoug** [comment]
Found the issue. It was 100% a problem with the BIG-hash (flat hash) MD4 code.

**Comment by jfoug** [comment]
This is now fully fixed, in the dynamic_big_crypt.c auto-generated code.  The problem was 'some' functions in some hashes were inconsistant.  Also, there were other bugs, such as keys not getting fully cleaned when bouncing between BE and LE formats in SIMD code.  That has all been addressed in the dyna_big_crypt auto-generation project.
