### ISSUE TITLE
byteorder.h: strange int types

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1483]
The code in byteorder.h uses types like `uint16` and `uint32`:
```c
148 #define SSVAL(buf,pos,val) SSVALX((buf),(pos),((uint16)(val)))
149 #define SIVAL(buf,pos,val) SIVALX((buf),(pos),((uint32)(val)))
150 #define SSVALS(buf,pos,val) SSVALX((buf),(pos),((int16)(val)))
151 #define SIVALS(buf,pos,val) SIVALX((buf),(pos),((int32)(val)))
```
I think the proper form should be `uint16_t` & `uint32_t`. This issue triggers a compile error on PowerPC.

**Comment by magnumripper** [comment]
I think this file is from the Samba project and we should eventually drop it and re-write our code. We have our own means for swapping etc. nowadays.
