### ISSUE TITLE
Turn dynamic_big_crypt.c into autogenerated code, done at configure time

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1491]
This code is pretty huge, and every hash is THE SAME, with just a couple things variable.  I have been finding dependencies between the hashes (BAD!!).

I plan on making a 'generic' set of macros for these hashes, and then include these macros for each specific hash type (after changing the variable stuff).  Then multiple runs through CPP outputting the resultant modified code, should be able to rebuild this file, and know that it is setup properly.  This would be a step within ./configure, likely down where we build fmt_externs.h, etc.

Once this is done, then only the input macro function(s) would need to ever be modified.  Once done, configure would properly rebuild the dynamic_big_crypt.c file.  One other nice thing about it, is that the code would not be interspersed with the ```#if SIMD_COEF_32 ....  #else .... #endif``` blocks. Since at configure time, we know if this is set, then only the usable code would need to be output.

Also, dynamic_big_crypt.c would end up in the .gitignore and the generation code/tool would be placed into github.

**Comment by jfoug** [comment]
The 2 commits above have completed the first stage of this patch.  NOW, I can do a little focus on optimzations AND adding new hashes.  New hashes should be able to be added in an hour or so, even if I can not get hashes from pass_gen.pl, since I can use the new dynamic_compiler code, LOL.

I know I started haval 'suite' of hashes a while back, but gave up on it, since I could not get pass_gen.pl to give me the data.  Well, now I probably could add those pretty easily.

If there are other hash types that should be added to dynamic, LET ME KNOW.

**Comment by magnumripper** [comment]
I think we need the following changes:
1. That chopper executable should be a perl script (or shell script). That also likely means we need no fallback in unused.
2. We can't build dynamic_big_crypt.c in configure, it won't be rebuilt when files are updated. It has to be a proper Makefile target. I actually see no problem at all with doing the changes described in https://github.com/magnumripper/JohnTheRipper/issues/1463#issuecomment-119365301 - what was the rationale for putting it in configure?!

**Comment by jfoug** [comment]
Look at the complexity of chopper, and you tell me.  I really wanted to do this without putting a requirement of perl on the system.  

> what was the rationale for putting it in configure?!

How are you going to do this in a cross compile environment in makefile?

**Comment by jfoug** [comment]
Makefile.in:
```
dynamic_big_crypt.c: dynamic_big_crypt_hash.cin dynamic_big_crypt_header.cin   dynamic_big_crypt_generator.sh unused/dynamic_big_crypt.cxx
    dynamic_big_crypt_generator.sh
    @if [ ! -e dynamic_big_crypt.c ] ; then $(CP_PRESERVE) unused/dynamic_big_crypt.cxx dynamic_big_crypt.c ; fi
```

I like that method a lot, and will make it that way,

**Comment by magnumripper** [comment]
> Look at the complexity of chopper, and you tell me.  I really wanted to do this without putting a requirement of perl on the system.  

It's not much code and it's a LOT more suitable for perl anyway. You already had problems with cross-compile and has to use a fallback, no?

>> what was the rationale for putting it in configure?!

> How are you going to do this in a cross compile environment in makefile?

With a perl script! The current solution is worse than you doing the generation yourself and committing the result. If you did that, nobody would have to re-run configure for a change in some of the source files.

**Comment by magnumripper** [comment]
BTW we already rely on perl for autoconf.

**Comment by jfoug** [comment]
But not with the run of ./configure   No user should be running autoconf.

I will do it in perl, and put it into the Makefile.   I was more reading "in a shell script" and thinking I did not want to do it that way. If it was a simple string replacement problem, then it would be easy. To also make it handle #ifdef / #else and nested if/else removal was a bit more than I thought in a shell script.  In perl, easy...

I did c since I figured that was going to be the most portable. The problem is ideal for perl.

**Comment by magnumripper** [comment]
>> BTW we already rely on perl for autoconf.

> But not with the run of ./configure No user should be running autoconf.

Yes, I meant ./configure. But I'll admit it fails gracefully (you'll just end up without automagic Makefile dependencies). Perhaps you should keep that fallback file in case some oddball user doesn't have perl.

**Comment by jfoug** [comment]
NOTE, if we ever remove code (#ifdef type removal logic which we already do), for things that would be system specific, for instance removing the MD5_X2 code, then the file that is put into ./src/unused MUST NOT have any of these system specific defines removed.

Right now, we only remove 2 thing.  One is the 'trunc-16' logic. If a hash is > 16 bytes, then the _FINAL functions must not write directly to the output, but must write to a properly sized buffer, then memcpy the first 16 bytes.  For 16 byte hashes, all of this logic is stripped out.  BUT that is not system specific.  The other thing cut out right now is the SIMD_PARA_* logic for any hash that we do NOT have SIMD logic.  Again, both of these are 100% valid to be removed generically.

But if we 'know' that a system is not MD5_X2, we could remove all that logic, making the code easier to read.  OR if it is valid, then the actual lines of #if and #endif for the MD5_X2 are removed, leaving the actual code, but without the always true defines.  In this case, we would want to have the file that is kept in ./src/unused NOT doing this logic.

This is just a note for myself, if I ever edit that logic any more.
