### ISSUE TITLE
ishex(), ishexuc(), ishexlc() shouldn

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1494]
currently, ishex("123") would return true, but it shouldn't.

**Comment by frank-dittrich** [comment]
rationale: I'd prefer to avoid UbSan messages like
```
runtime error: signed integer overflow: -1116077172 * 2 cannot be represented in type 'int'
```
by changing
```
if (strlen(p) != res * 2)
```
into
```
if (strlen(p) / 2 != res)
```
instead of
```
if (strlen(p) - res != res)
```

**Comment by jfoug** [comment]
Should this be true?    isHex("");   ?

**Comment by frank-dittrich** [comment]
I don't care.

**Comment by jfoug** [comment]
Well, this is flat out WRONG!

```C
if (!ishex(p))
   goto err;
res = atoi(p);
```

**Comment by jfoug** [comment]
That was from valid in ssh format.  Is there an automatic way to find other instances of this type usage?  Where we do an ishex() followed by atoi ??

The problem is now that ishex will require even (I have an update that is fixed), then the above code is very wrong, BUT if there are no odd length integers in test strings, then all valid() will work, but the format will fail to crack hashes which have an odd length for that number field.

**Comment by jfoug** [comment]
NOTE, there are also formats which MUST allow odd length hex.  clipperz is one of them.  It is an SRP, and the data is in hex, with or without a leading 0.  The format was written properly to handle the odd length.

**Comment by magnumripper** [comment]
What is this issue about? The heading seem to be truncated.

> currently, ishex("123") would return true, but it shouldn't.

I guess you mean ishex() should return false if the number of hex characters is odd. I agree.

> Should this be true? isHex(""); ?

Jolly good question. I guess we can pick the answer that seems to be best for our current use, then document it.

**Comment by jfoug** [comment]
Ok, after 9a5f500, all formats properly pass, BUT I think there will be some additional fixes needed, if there is code like there was in ssh format.

Other things I can see, are not isdec() checking prior to an atoi(), then using that atoi result.

**Comment by frank-dittrich** [comment]
On 07/05/2015 11:11 PM, jfoug wrote:
> That was from valid in ssh format. Is there an automatic way to find
> other instances of this type usage? Where we do an ishex() followed by
> atoi ??

At least, a primitive approach doesn't find anothing else except:


(bleeding-jumbo)src $ git grep -B 2 atoi|grep -A 2 ishex
ssh_fmt_plug.c-	if (!ishex(p))
ssh_fmt_plug.c-		goto err;
ssh_fmt_plug.c:	res = atoi(p);
--
unused/pdf/pdf_fmt.c-static int ishex(char *q)
unused/pdf/pdf_fmt.c-{
unused/pdf/pdf_fmt.c:       while (atoi16[ARCH_INDEX(*q)] != 0x7F)
(bleeding-jumbo)src $

**Comment by jfoug** [comment]
>>  Should this be true? isHex(""); ?

> Jolly good question. I guess we can pick the answer that seems to be best for our current use, then document it.

It is true now. The only problem I see, is we do things like:

```valid("$test_hash$$$$$$$$$$$$$$$$$$$$$$$$$$");```

I just do not want that to somehow sneek through. BUT jtr should have already complained if it did.  NOTE, I was getting failures if ishex("") returned false, so now it does not.

**Comment by jfoug** [comment]
> I guess you mean ishex() should return false if the number of hex characters is odd. I agree.

clipperz it is valid for a odd length hex, and they do have strings which are odd (seen them ITW).  I wrote special code to convert into the binary blob for that format.  The odd length strings right trim the value. What you get is a modular residue, and they strip off any leading 0's.

I just created a ishex_oddOK(char*) function, and use it in clipperz.

**Comment by magnumripper** [comment]
OK, sounds good to me

**Comment by jfoug** [comment]
9a5f500 should have it completed.

**Comment by jfoug** [comment]
The commit closed this (I think).

**Comment by frank-dittrich** [comment]
I think this is fixed now,  not isdec() checking prior to an atoi(), then using that atoi result" is something that needs to be fixed, but that is not this issue.
