### ISSUE TITLE
rar-opencl format self test fails on super

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1499]
```
$ ./john --test=0 --format=rar-opencl
./john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./john)
./john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./john)
Device 0: Tahiti [AMD Radeon HD 7900 Series]
Testing: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... FAILED (valid (before init))

```

**Comment by magnumripper** [comment]
Failed valid?? That has nothing to do with OpenCL. It's caused by @jfoug's recent change to isHex()

**Comment by frank-dittrich** [comment]
Yes, you are right. The 9a5f5009388320cbaf0d810fac2454b602c386f4 changes to rar_fmt_plug.c need to be applied to the opencl version.

**Comment by magnumripper** [comment]
While at it, they should share code. There's an open issue for that (not specific to rar) I think.

**Comment by magnumripper** [comment]
It's sad you can't just "apt-get install" some CPU OpenCL driver in standard Ubuntu. Then we could have the build bots catch these things.

**Comment by magnumripper** [comment]
Hm, wait. Perhaps if we install fglrx on Travis, we'll get an unused GPU driver and a working CPU driver. I think I did that on some host. There might be warnings though. I'll try it out.

**Comment by magnumripper** [comment]
Travis now does OpenCL :sunglasses: 
```
Device 0: AMD Opteron(tm) Processor 6376                 
Testing: rar-opencl, RAR3 (length 4) [SHA1 OpenCL AES]... (4xOMP) FAILED (valid (before init))
```

**Comment by frank-dittrich** [comment]
Wouldn't it be good enough to test OpenCL with the gcc build and use --disable-opencl for the clang build? Or is it likely we find OpenCL bugs with clang that don't occur with gcc?

**Comment by frank-dittrich** [comment]
Hm, looking at the latest build, there really is a difference between gcc and clang:
With clang:
```
Testing: mscash-opencl, M$ Cache Hash [MD4 OpenCL]... FAILED (get_key(1))
```
which means, the test continues, so we see more errors in other formats.
Wich gcc:
```
Testing: mscash-opencl, M$ Cache Hash [MD4 OpenCL]... make: *** [check] Segmentation fault
```
So, let's keep the clang OpenCL build.

**Comment by frank-dittrich** [comment]
@magnumripper did you notice
```
Setting of real/effective user Id to 0/0 failed

FATAL: Could not load /lib/modules/2.6.32-042stab090.5/modules.dep: No such file or directory

Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly

Setting of real/effective user Id to 0/0 failed

FATAL: Could not load /lib/modules/2.6.32-042stab090.5/modules.dep: No such file or directory

Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
```
See https://travis-ci.org/magnumripper/JohnTheRipper/jobs/69860783

**Comment by magnumripper** [comment]
Yes, that's because it runs an AMD fglrx driver that can't find any GPU. The warnings can be ignored.

**Comment by frank-dittrich** [comment]
commit bd7aa1fbccf37a1b9618e3c46ca4fb5fcc6f2238 fixed the error by applying the ishex() change related CPU format fixes to the OpenCL format, but I postponed the code unification.

**Comment by frank-dittrich** [comment]
Since code sharing between OpenCL and CPU implementations is mentioned in  issue https://github.com/magnumripper/JohnTheRipper/issues/978, I am closing this one.
