### ISSUE TITLE
episerver and probably other formats need to improve base64 validation

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1513]
```
(bleeding-jumbo)run $ cat pw
test3

notused
(bleeding-jumbo)run $ cat fail_episerver 
1:$episerver$*0*fGJ2wn/5WlzqQoDeCA2kXA==*dxTlKqnxaVHs0210VcX+48QDonA=
2:$episerver$*0*fGJ2wn/5WlzqQoDeCA2kXA==*dxTlKqnxaVHs0210VcX+48QDonA=B
3:$episerver$*0*THk5ZHhYNFdQUDV1Y0hScg==*ik+FVrPkEs6LfJU88xl5oBRoZjY
4:$episerver$*0*THk5ZHhYNFdQUDV1Y0hScg==*ik+FVrPkEs6LfJU88xl5oBRoZjY=A
5:$episerver$*1*cW9DdnVVUnFwM2FobFc4dg==*Zr/nekpDxU5gjt+fzTSqm0j/twZ=ySBBW44Csoai2Fu
6:$episerver$*1*cW9DdnVVUnFwM2FobFc4dg==*Zr/nekpDxU5gjt+fzTSqm0j/twZySBBW44Csoai2Fug
```

```
(bleeding-jumbo)run $ ./john fail_episerver --wordlist=pw
Using default input encoding: UTF-8
Loaded 6 password hashes with 3 different salts (EPiServer [SHA1/SHA256 32/64 OpenSSL])
Loaded hashes with cost 1 (hash type [1: SHA1 2:SHA256]) varying from 1 to 2
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
test3            (6)
                 (4)
                 (3)
notused          (2)
notused          (1)
5g 0:00:00:00 DONE (2015-07-08 01:23) 125.0g/s 75.00p/s 225.0c/s 450.0C/s test3..notused
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john fail_episerver --wordlist=pw
Using default input encoding: UTF-8
Loaded 6 password hashes with 3 different salts (EPiServer [SHA1/SHA256 32/64 OpenSSL])
Remaining 3 password hashes with 3 different salts
Loaded hashes with cost 1 (hash type [1: SHA1 2:SHA256]) varying from 1 to 2
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
                 (3)
notused          (1)
2g 0:00:00:00 DONE (2015-07-08 01:23) 50.00g/s 75.00p/s 225.0c/s 225.0C/s test3..notused
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john fail_episerver --wordlist=pw
Using default input encoding: UTF-8
Loaded 6 password hashes with 3 different salts (EPiServer [SHA1/SHA256 32/64 OpenSSL])
Remaining 1 password hash
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:00 DONE (2015-07-08 01:23) 0g/s 150.0p/s 150.0c/s 150.0C/s test3..notused
Session completed
(bleeding-jumbo)run $ cat john.pot 
$episerver$*1*cW9DdnVVUnFwM2FobFc4dg==*Zr/nekpDxU5gjt+fzTSqm0j/twZySBBW44Csoai2Fug:test3
$episerver$*0*THk5ZHhYNFdQUDV1Y0hScg==*ik+FVrPkEs6LfJU88xl5oBRoZjY=A:
$episerver$*0*fGJ2wn/5WlzqQoDeCA2kXA==*dxTlKqnxaVHs0210VcX+48QDonA=B:notused
$episerver$*0*THk5ZHhYNFdQUDV1Y0hScg==*ik+FVrPkEs6LfJU88xl5oBRoZjY:
$episerver$*0*fGJ2wn/5WlzqQoDeCA2kXA==*dxTlKqnxaVHs0210VcX+48QDonA=:notused
(bleeding-jumbo)run $ ./john --show=left fail_episerver 
5:$episerver$*1*cW9DdnVVUnFwM2FobFc4dg==*Zr/nekpDxU5gjt+fzTSqm0j/twZ=ySBBW44Csoai2Fu

5 password hashes cracked, 1 left
```

I think base64_decode() needs to indicate success with the return value.
base64_decode() should indicate failure if there are characters != `'='` after the first `'='` or if there are too many `'='` at the end of the string.
Then, the formats which use base64 components in their hashes can use base64_decode() in valid().
Otherwise we end up spending time on invalid hashes, store multiple versions of the same hash in the pot file, etc.

**Comment by magnumripper** [comment]
Hmmm it is already `int base64_decode(char *in, int inlen, char *out)` but it **always** returns zero.

**Comment by frank-dittrich** [comment]
We could also turn base64_convert() into void and create a new isbase64()

**Comment by jfoug** [comment]
how about base64len(char *input, int flags)  ?

Or is there any way we can adjust the interface as it exists to do what is needed?

**Comment by frank-dittrich** [comment]
Yes, base64len() sounds fine. Will it return a negative value for invalid base64()?
And what are the flags for? To pick a specific variant of the "base64" dialects?

I'd prefer to avoid the current interface, since I don't want to allocate and free buffers just to validate a base64 string.

**Comment by jfoug** [comment]
This function is already there:

``C
int base64_valid_length(const char *from, b64_convert_type from_t, unsigned flags) {
	int len=0;
	if (!mime_setup)
		setup_mime();

	switch (from_t) {
		case e_b64_hex:		/* hex */
			if ( (flags & flg_Base64_HEX_UPCASE) == flg_Base64_HEX_UPCASE) {
				while (atoi16[ARCH_INDEX(*from)] != 0x7f) {
					if (*from >= 'a' && *from <= 'f')
						break;
					++len;
					++from;
				}
			} if ( (flags & flg_Base64_HEX_LOCASE) == flg_Base64_HEX_LOCASE) {
				while (atoi16[ARCH_INDEX(*from)] != 0x7f) {
					if (*from >= 'A' && *from <= 'F')
						break;
					++len;
					++from;
				}
			} else {
				while (atoi16[ARCH_INDEX(*from++)] != 0x7f)
					++len;
			}
			break;
		case e_b64_mime:	/* mime */
			if ( (flags&flg_Base64_MIME_PLUS_TO_DOT) == flg_Base64_MIME_PLUS_TO_DOT) {
				while (atoi64md[ARCH_INDEX(*from++)] != 0x7f)
					++len;
			} else if ( (flags&flg_Base64_MIME_DASH_UNDER) == flg_Base64_MIME_DASH_UNDER) {
				while (atoi64mdu[ARCH_INDEX(*from++)] != 0x7f)
					++len;
			} else {
				while (atoi64m[ARCH_INDEX(*from++)] != 0x7f)
					++len;
			}
			--from;
			if ( (flags&flg_Base64_MIME_TRAIL_EQ_CNT) == flg_Base64_MIME_TRAIL_EQ_CNT) {
				while (*from++ == '=')
					++len;
			}
			break;
		case e_b64_crypt:	/* crypt encoding */
		case e_b64_cryptBS:	/* crypt encoding, network order (used by WPA, cisco9, etc) */
			while (atoi64[ARCH_INDEX(*from++)] != 0x7f)
				++len;
			break;
		default:
			return ERR_base64_unk_from_type;
	}
	return len;
}
```

This returns the length of the string.   I have made changes so it 'can' return a -1 (with proper flags), and have added a function in common.c  ``` base64_mime_len(char *p);  base64_crypt_len(char *p)  base64_mime_du_len(char *p);```  These functions simply call base64_valid_length, filling in proper type, and flags.  I will have this checked in shortly.  I will not change the 'default' return of base64_valid_length, since it is used with the existing logic.  But no where does this new flag get used, other than in code that will know how to handle negative values.

**Comment by jfoug** [comment]
```C
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "common.h"

int main() {
	char *cp = "fa;slkdjfgaighasflk";
	printf("%d %s\n", base64_mime_len(cp), cp);
	return 0;
}
```

$ ./a
-2 fa;slkdjfgaighasflk

**Comment by jfoug** [comment]
dbfdee2

**Comment by jfoug** [comment]
7523089 fixes a bug.

```C
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "common.h"

int main() {
	char *cp = "fa;slkdjfgaighasflk";
	printf("%d %s\n", base64_mime_len(cp), cp);
	cp = "lfjasfhdlajf";
	printf("%d %s\n", base64_mime_len(cp), cp);
	return 0;
}
```

before fix:
$ ./a
-2 fa;slkdjfgaighasflk
-12 lfjasfhdlajf

after fix:
$ ./a
-2 fa;slkdjfgaighasflk
12 lfjasfhdlajf
