### ISSUE TITLE
Test OpenCL formats on Linux with beignet driver and CPU/Intel GPU

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1515]
https://gist.github.com/spiralray/cae0bc235509e495fec1

**Comment by magnumripper** [comment]
Also see #1571 (not quite sure why that is a separate issue).

**Comment by frank-dittrich** [comment]
That's because I didn't remember you opening this issue. My main interest wasn't beignet, but making use of the haswell GPU.

**Comment by magnumripper** [comment]
Let's use that issue in favor of this
