### ISSUE TITLE
Invalid signature line trying to link to dynamic format

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1518]
Tested on super

```

$ ./john --make_check
./john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./john)
./john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./john)
Testing: descrypt, traditional crypt(3) [DES 128/128 AVX-16]... PASS
[...]

Testing: nk, Nuked-Klan CMS [SHA1 MD5 32/64]... PASS
Error, Invalid signature line trying to link to dynamic format.
Original format=md5ns
Signature line=$dynamic_2004$c8c5cd1d2f62efb1814649b7b01e6661$HEX$61646d696e3a41646d696e697374726174696f6e20546f6f6c733a
```

With --test=0, the next format after nk is
```
Testing: md5ns, Netscreen [md5($s.$p) (OSC) (PW > 31 bytes) 128/128 AVX 4x3]... PASS
```

```
$ ./john --list=build-info
./john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./john)
./john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./john)
Version: 1.8.0.6-jumbo-1-305-g5f3c270+
Build: linux-gnu 64-bit AVX-ac
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.9.1
GNU libc version: 2.12 (loaded: 2.12)
OpenCL library version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 01000105f
OpenSSL 1.0.1e-fips 11 Feb 2013
GMP library version: 4.3.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by magnumripper** [comment]
Doesn't happen on my gear.

**Comment by magnumripper** [comment]
I lied, it does happen here.
```
...
Testing: nk, Nuked-Klan CMS [SHA1 MD5 32/64]... (8xOMP) PASS
Error, Invalid signature line trying to link to dynamic format.
Original format=md5ns
Signature line=$dynamic_2004$c8c5cd1d2f62efb1814649b7b01e6661$HEX$61646d696e3a41646d696e697374726174696f6e20546f6f6c733a
```

**Comment by magnumripper** [comment]
...and yes, it only happens with `--make_check`. So what is special about that option? Why does it even exist?

**Comment by frank-dittrich** [comment]
It is a core option to verify builds, it is not even listed as an option. I remembered it when I compared Makefile.in and Makefile.legacy's check target.

**Comment by magnumripper** [comment]
It replaces argv with `--test=0` But here's the difference.

john.c:1260 (john_init)
```c
	if (!make_check) {
		if (options.config)
		{
			path_init_ex(options.config);
			cfg_init(options.config, 0);
			cfg_init(CFG_FULL_NAME, 1);
			cfg_init(CFG_ALT_NAME, 0);
		}
		else
		{
#if JOHN_SYSTEMWIDE
			cfg_init(CFG_PRIVATE_FULL_NAME, 1);
			cfg_init(CFG_PRIVATE_ALT_NAME, 1);
#endif
			cfg_init(CFG_FULL_NAME, 1);
			cfg_init(CFG_ALT_NAME, 0);
		}
	}
```

**Comment by frank-dittrich** [comment]
Yes, it fails on the first thin format which is linked to a dynamic format from a config file.
I think it is not worth the effort to address this.
(I wouldn't want to read the config for --make_check.)
I'll keep the issue open for a while, may be I find an easy way which doesn't involve messing with a lot of @jfoug's code.

**Comment by ksimka** [comment]
I have the same issue, but in runtime, not while doing make.

```
./run/john --format=dynamic-all some_passwd

...

Error, Invalid signature line trying to link to dynamic format.
Original format=md5ns
Signature line=$dynamic_2004$c8c5cd1d2f62efb1814649b7b01e6661$HEX$61646d696e3a41646d696e697374726174696f6e20546f6f6c733a
```

If you need any additional info - just ask.

**Comment by magnumripper** [comment]
@ksimka is that with latest code from here?

**Comment by frank-dittrich** [comment]
@magnumripper Why would you think the "issue" is gone with latest bleeding-jumbo?
I think an end user isn't supposed to run `./john --make_check`, since that option isn't mentioned in john's usage output or --list=hidden-options output..

**Comment by magnumripper** [comment]
I was just asking in case he was running J1 or something like that since I can't reproduce. And @ksimka wasn't running -make-check but some totally normal command.

@ksimka what if you try `./run/john --format=dynamic-all -pot=test.pot some_passwd` with "test.pot" being some non-existing file - does the problem go away?

**Comment by ksimka** [comment]
@magnumripper
> @ksimka is that with latest code from here?

Yes.

> @ksimka what if you try ./run/john --format=dynamic-all -pot=test.pot some_passwd with "test.pot" being some non-existing file - does the problem go away?

Sounds weird, but yes, it's not reproduced anymore. I mean, once running that command with -pot now john is running without it.

Must be I changed something, cause I don't believe in magic.

**Comment by magnumripper** [comment]
Wow, I wasn't expecting it to go away for good, just for that run. I suppose something in your normal john.pot file triggered it.

**Comment by jfoug** [comment]
I am unable to replicate this bug at all.  Well, I can for --make_check. That one is SUPER easy to see why.  We never load config for a make_check  (reason for this is NOT obvious).

But I have tried sprinkling a lot of different hash signatures into a .pot file, and an input file, and I have not been able to get this to fail with --format=dynamic-all

**Comment by magnumripper** [comment]
Well he says he can't reproduce it anymore so let's consider it some kind of PEBCAK (no offense, just a label :wink: ).

**Comment by magnumripper** [comment]
BTW I consider the original `-make-check` issue a non-issue since that options is not documented anywhere. Perhaps we should even actually disable it completely in Jumbo.

**Comment by frank-dittrich** [comment]
What if you replace dynamic.conf with an empty file?
That would still be PEBKAC, but may be the error message could be improved?
