### ISSUE TITLE
strip-opencl: Warning: salt() returned misaligned pointer

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1519]
So far only seen on Travis (clang builds only)
```
Testing: strip-opencl, STRIP Password Manager [PBKDF2-SHA1 OpenCL]... Warning: salt() returned misaligned pointer

PASS
```

**Comment by magnumripper** [comment]
After my recent fixes, that warning can only be a compiler bug (I think we saw it before).

**Comment by magnumripper** [comment]
BTW we should mute those warnings `#if JTR_RELEASE_BUILD`

**Comment by magnumripper** [comment]
I was wrong, another struct was involved too
