### ISSUE TITLE
unplug some hash formats

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1525]
These need to be unplugged, since they are used in the dynamic_compiler code, that is not plug compatible and must be built.

haval_plug
skein_plug
md2_plug
panama_plug
whirlpool_plug

**Comment by frank-dittrich** [comment]
Is it possible to unplug ust parts of those source files and keep the formats as plugins?

**Comment by magnumripper** [comment]
Not without duplicating code. Is there any RoI?

**Comment by jfoug** [comment]
the formats can be plug.  It is the hashes themselves   (the whirlpool_plug.c) that need to be unplugged.   Keeping the whirlpool_fmt_plug.c as a plug is 100% ok.

**Comment by frank-dittrich** [comment]
@jfoug OK, so I was confused. Thanks for the clarification.
