### ISSUE TITLE
sha256crypt-cuda fails self test on super

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1532]
This is with `scl enable devtoolset-3 bash`, i.e., `gcc (GCC) 4.9.1 20140922 (Red Hat 4.9.1-10)`:
```
Testing: sha256crypt-cuda, crypt(3) $5$ (rounds=5000) [SHA256 CUDA (inefficient, please use sha256crypt-opencl instead)]... FAILED (cmp_all(7))
```

**Comment by magnumripper** [comment]
Good you added an issue. It has been broken for quite a while and I kept forgetting about it.

It does work fine on OSX, CUDA v6.5.51

**Comment by magnumripper** [comment]
Still OSX, upgraded to CUDA v7.0.52 and voila
```
Benchmarking: sha256crypt-cuda, crypt(3) $5$ (rounds=5000) [SHA256 CUDA (inefficient, please use sha256crypt-opencl instead)]... FAILED (cmp_all(7))
```

**Comment by magnumripper** [comment]
I have no idea what's going on here. @ukasz could you have a look at this please?

**Comment by magnumripper** [comment]
Bull, CUDA 4.2.1, fails too. WTF? Did it fail long ago too?

**Comment by magnumripper** [comment]
Doesn't fail now. Not sure if 06a953ec had anything to do with it.
