### ISSUE TITLE
Some dynamic formats report an incorrect salt size of 0

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1535]
Noted by Aleksey in http://www.openwall.com/lists/john-users/2015/06/30/1

Field 12 is "salt size" and the quoted whitespace in the command-line below are escaped tabs:
```
$ ../run/john --list=format-details -form=dynamic | cut -d" " -f1,7,12 | grep -F '$s' | grep "   0"
dynamic_1011	md5($p.md5($s)) (WebEdition CMS) 128/128 AVX 4x3	0
dynamic_1012	md5($p.md5($s)) (WebEdition CMS) 128/128 AVX 4x3	0
dynamic_1014	md5($p.$s) (long salt) 128/128 AVX 4x3	0
dynamic_1016	md5($p.$s) (long salt) 128/128 AVX 4x3	0
dynamic_1017	md5($s.$p) (long salt) 128/128 AVX 4x3	0
dynamic_1502	sha1(sha1($p).$s) (XenForo SHA-1) 128/128 AVX 4x1	0
dynamic_1503	sha256(sha256($p).$s) (XenForo SHA-256) 128/128 AVX 4x	0
dynamic_1504	sha1($s.$p.$s) 128/128 AVX 4x1	0
```
I suppose these formats don't actually report a salt size of 0 when cracking, but it should be fixed for --list=format-[all-]details anyway. For example, they would be missed if we search for #saltfail formats like this:
```
$ ../run/john --list=format-details -form=dynamic | cut -d" " -f1,7,12 | grep -E '       (sha|md[45])\(\$s' | grep "     64$" 
dynamic_2004	md5($s.$p) (OSC) (PW > 31 bytes) 128/128 AVX 4x3	64
dynamic_2009	md5($s.md5($p)) (PW > 55 or salt > 23 bytes) 128/128 AVX 4x3	64
dynamic_2010	md5($s.md5($s.$p)) (PW > 32 or salt > 23 bytes) 128/128 AVX 4x3	64
dynamic_2011	md5($s.md5($p.$s)) (PW > 32 or salt > 23 bytes) 128/128 AVX 4x3	64
md5ns	md5($s.$p) (OSC) (PW > 31 bytes) 128/128 AVX 4x3	64
```

**Comment by jfoug** [comment]
The thing is that on the output lines, the code drills down into the dyna format structure (in the private parts), to find the real salt size.  Dyna ALWAYS uses a salt size of a pointer.  It is the original dyna_salt format.  dyna_salt was a generalization of the technique I used in dynamic, since it has to handle all sorts of variable sized salt crap.

What is wrong, is in dynamic.conf, there is no  ```SaltLen=#``` line, so within the listopts code, there is nothing to find.   Also, i did not write these, so do not know what it should be.  NOTE, if it is variable, then we need to make the value negative, and of either the max size, or 110 (negative), whichever is smaller

**Comment by jfoug** [comment]
Btw, I get a different list, and could not figure out how to make cut work with a tab, so I found a way with perl

```
/c/phpbb/johnripper/bleed-64/src $ ../run/john --list=format-details -form=dynamic-all | perl -nle 'print if $.==1;@a=split;print join "\t", @a[0,6,11]' | grep -F '$s' | grep 0$
dynamic_1       md5($p.$s)      0
dynamic_4       md5($s.$p)      0
dynamic_12      md5(md5($s).md5($p))    0
dynamic_38      sha1($s.sha1($s.sha1($p)))      0
dynamic_39      md5($s.pad16($p))       0
dynamic_40      sha1($s.pad20($p))      0
dynamic_91      GOST($s.$p)     0
dynamic_92      GOST($p.$s)     0
dynamic_95      GOST(GOST($p).$s)       0
dynamic_96      GOST($s.GOST($p))       0
dynamic_1007    md5(md5($p).$s) 0
dynamic_1501    sha1($s.sha1($p))       0
```

**Comment by magnumripper** [comment]
> Also, i did not write these, so do not know what it should be. NOTE, if it is variable, then we need to make the value negative, and of either the max size, or 110 (negative), whichever is smaller

So how will these formats actually work as written now? There must be a default, intended or not.

> and could not figure out how to make cut work with a tab

Your list is wrong because it doesn't count two tabs as two fields, and there are eg. FORMAT_NAME fields that are empty. You use ctrl-v + TAB within quotes for cut in all shells I know of.

**Comment by jfoug** [comment]
They are MGF_SALTED.  With no salt length, there is no validatation done (I think).  The only thing that salt-len does is validation.  Dyna is pretty robust on what it tries to handle.  Things like salt len were added to keep it from killing itself.  There are some items that have exact salt lengths. For those, salt len is set to positive, and then if the salt is NOT that exactly that long, valid will fail it.

Btw, my perl was wrong.  I fixed it, and get same results.

**Comment by jfoug** [comment]
I was able to optimize 1011 a lot.


$ ../run/john -test=3 -form=dynamic_1011
Benchmarking: dynamic_1011 [md5($p.md5($s)) (WebEdition CMS) 128/128 XOP 4x2]... DONE
Many salts:     5372K c/s real, 5370K c/s virtual
Only one salt:  4451K c/s real, 4492K c/s virtual

$ ../run/john -test=3 -form=dynamic_1011
Benchmarking: dynamic_1011 [md5($p.md5($s)) (WebEdition CMS) 128/128 XOP 4x2]... DONE
Many salts:     10228K c/s real, 10241K c/s virtual
Only one salt:  7440K c/s real, 7432K c/s virtual

As I fix the salts on the rest, I will see about optimizations. I swore I searched recently and could not find any where this trick was not being used (MGF_SALT_AS_HEX flag).

**Comment by magnumripper** [comment]
dynamic_1011    md5($p.md5($s)) (WebEdition CMS)
dynamic_1012    md5($p.md5($s)) (WebEdition CMS)
These are same format. Why, and why are both kept? BTW they should be replaced with md5($p.md5($u)) anyway.

dynamic_1013    md5($p.PMD5(username)) (WebEdition CMS)
This has a fixed salt length of 32

dynamic_1014    md5($p.$s) (long salt)
dynamic_1016    md5($p.$s) (long salt)
These are duplicates, and BOTH are deprecated in favor of dynamic_2001

dynamic_1017    md5($s.$p) (long salt)
deprecated by dynamic_2004

dynamic_1502    sha1(sha1($p).$s) (XenForo SHA-1)
I'd set saltlen to -70 (110-40)

dynamic_1503    sha256(sha256($p).$s) (XenForo SHA-256)
I'd set saltlen to -46 (110-64) but I don't understand the test vectors. Salt is given in hex? Can we do three limbs?

dynamic_1504    sha1($s.$p.$s)
seems to be generic

**Comment by magnumripper** [comment]
This one (as well as 1013) was missed with my one-liner
```
dynamic_1401	md5($u.\nskyper\n.$p) (Skype MD5) 128/128 AVX 4x3	0	0
```

**Comment by magnumripper** [comment]
> BTW they should be replaced with md5($p.md5($u)) anyway.

This was not correct. I got fooled by some test vectors.

**Comment by magnumripper** [comment]
> I was able to optimize 1011 a lot.

It's still much slower than 1012
```
Benchmarking: dynamic_1011 [md5($p.md5($s)) (WebEdition CMS) 128/128 AVX 4x3]... DONE
Many salts:	11734K c/s real, 11618K c/s virtual
Only one salt:	9669K c/s real, 9765K c/s virtual

Benchmarking: dynamic_1012 [md5($p.md5($s)) (WebEdition CMS) 128/128 AVX 4x3]... DONE
Many salts:	22559K c/s real, 22559K c/s virtual
Only one salt:	15691K c/s real, 15691K c/s virtual

Benchmarking: dynamic_1013 [md5($p.PMD5(username)) (WebEdition CMS) 128/128 AVX 4x3]... DONE
Many salts:	22026K c/s real, 22246K c/s virtual
Only one salt:	15182K c/s real, 15182K c/s virtual
```
And 1013 is pointless since we optimize it anyway (1012 is just as fast)

**Comment by jfoug** [comment]
1011, 1012 and 1013 were all left in there at one time.  I think I even talk about them in the dyna.doc file.

**Comment by jfoug** [comment]
Note, I took out optimizations to 1011, so that it could be seen the difference of using that flag or not, and how to do it, and why.

**Comment by magnumripper** [comment]
BTW when comparing self-contained dyna I see this
```
magnum@mbpr-osx:src [bleeding-jumbo]$ ../run/john -test -form='dynamic=md5($p.md5($s))'
Benchmarking: dynamic=md5($p.md5($s)) [128/128 AVX 4x3]... DONE
Many salts:	18293K c/s real, 18293K c/s virtual
Only one salt:	14047K c/s real, 14047K c/s virtual

$ ../run/john -test -form='dynamic=md5($p.md5($u))'
Benchmarking: dynamic=md5($p.md5($u)) [128/128 AVX 4x3]... DONE
Many salts:	8077K c/s real, 7997K c/s virtual
Only one salt:	7402K c/s real, 7402K c/s virtual
```
Using $u should be exactly as fast as $s, no? It's a prepare thing, nothing else, right?

**Comment by jfoug** [comment]
the only optimization right now is SALT_AS_HEX.   If all $s are in the form of hash($s), then we set that flag, and simply append the salt, vs create the hash.

There is the same optimization (I think) for user name.  But I do not yet detect it

**Comment by jfoug** [comment]
I was wrong, there is no username as hex

**Comment by frank-dittrich** [comment]
> Btw, I get a different list, and could not figure out how to make cut
> work with a tab

To make cut work with tab, dont' use -d at all, as tab is the default
delimiter.

**Comment by magnumripper** [comment]
> To make cut work with tab, dont' use -d at all, as tab is the default delimiter.

Oh, right. Lol.
