### ISSUE TITLE
$pass, $salt vs. $p, $s

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1543]
Hashcat and InsidePro use $pass and $salt while we use $p and $s. Would it be doable (with moderate effort) for us to support both? It'd help when copy-pasting foreign formats to your command line. I think this mostly or solely applies to self-contained dynamic.

We have to unify them somewhere in the process so they'd still always end up in their short form in eg. pot files (`@dynamic` tags). Basically we could do some (early) string replacements in options.format, and be done with it.

See also #1436 and [Hashcat wiki](http://hashcat.net/wiki/doku.php?id=example_hashes)

**Comment by magnumripper** [comment]
They also have $u as $username (not $user)

**Comment by jfoug** [comment]
Easy (I think) to do, BUT since there is absolutely NO hash out there using the dynamic= syntax, is this really needed??

I can easily put it in place however.  There already is a normalize() function  (listed as //TODO: ) in the compiler.c so I will simply normalize down to single bytes.

**Comment by jfoug** [comment]
There are all sorts of non expression things in there, and some other stuff also.

I can see strupper used against a hash.  Also there are string literals within the expressions, etc.  I do not handle either of those.  I 'could', but now you are talking about putting quite a bit of smarts into prepare, almost a mini parser. I would NOT want to do that.  I do not want to have 2 sources of this code.  It is complex enough.

**Comment by magnumripper** [comment]
I'm not suggesting we should allow all Insidepro syntax. Just the $user, $pass and $username would make editing after a copy-paste easier and I'm hoping it's fairly trivial.

**Comment by jfoug** [comment]
See what you think with this one:  535dd76

**Comment by magnumripper** [comment]
Looks good to me, thanks!

**Comment by magnumripper** [comment]
I added $password too, after stumbling upon it. I can't see it ever hurt.
https://hashcat.net/forum/thread-4539-post-25800.html
