### ISSUE TITLE
pufferfish: stop using custom encrypt64/decrypt64 and use base64_conv code

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1549]
Self explanatory title.  Found out what PF is doing when fixing valid.  I have not fixed it yet, I just wanted to make note of it so I did not forget.

**Comment by jfoug** [comment]
This is a unique base64 alphabet.  It might not be worth the time to fix if no other formats are using it.

**Comment by frank-dittrich** [comment]
OK, let's wait until there's a second format with an individual alphabet, then write wrapper functions which get the alphabet passed as a parameter, do the translation, bail out on unexpected characters, etc...
