### ISSUE TITLE
raw-sha1-opencl doesn't work with large hash file

### ISSUE THREAD

**Issue by salu90** [magnumripper/JohnTheRipper#1559]
If i try to use john to crack the linkedin hash list(more than 6 million of hash) with opencl i get this error:

*** Error in `./john': malloc(): memory corruption: 0x0000000033524ba0 ***

*** Error in `./john': malloc(): memory corruption: 0x0000000033524ba0 ***

Segmentation fault (core dumped)

**Comment by Sayantan2048** [comment]
This should be an issue. How much RAM do you have ? Is your memory OK? Have you run memtest86 ?

This is on my system with 8GB RAM and 3GB Video memory. Although video memory requirement is low, however system memory requirement could be steep. 
```
./john  -format=raw-sha1-opencl 7M_sha1 -mask=?d?d?d?d?l?l?l?l?l?l
Device 0: Tahiti [AMD Radeon R9 200 / HD 7900 Series]
Using default input encoding: UTF-8
Loaded 7000000 password hashes with no different salts (Raw-SHA1-opencl [SHA1 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:30 0.37% (ETA: 01:31:40) 0g/s 382293Kp/s 382293Kc/s 2676TC/s GPU:47°C util:99% fan:20% 0000uognca..0000bbdpca
0g 0:00:00:32 0.43% (ETA: 01:19:38) 0g/s 419840Kp/s 419840Kc/s 2938TC/s GPU:48°C util:98% fan:20% 0000qklyca..0000xwhada
0g 0:00:00:35 0.49% (ETA: 01:16:32) 0g/s 430665Kp/s 430665Kc/s 3014TC/s GPU:49°C util:98% fan:20% 0000euthda..0000lgqjda
0g 0:00:00:39 0.60% (ETA: 01:04:31) 0g/s 478916Kp/s 478916Kc/s 3352TC/s GPU:50°C util:98% fan:20% 0000ozgcea..0000vldeea
0g 0:00:00:43 0.68% (ETA: 01:02:34) 0g/s 487709Kp/s 487709Kc/s 3413TC/s GPU:51°C util:98% fan:20% 0000shipea..0000zterea
0g 0:00:00:48 0.80% (ETA: 00:57:33) 0g/s 512000Kp/s 512000Kc/s 3584TC/s GPU:51°C util:98% fan:20% 0000cnvjfa..0000jzrlfa
0g 0:00:00:50 0.85% (ETA: 00:55:12) 0g/s 524288Kp/s 524288Kc/s 3670TC/s GPU:52°C util:98% fan:20% 0000qwdtfa..0000xiavfa
0g 0:00:00:54 0.94% (ETA: 00:52:19) 0g/s 540065Kp/s 540065Kc/s 3780TC/s GPU:53°C util:98% fan:20% 0000kdyjga..0000rpulga
```

**Comment by salu90** [comment]
I haven't run memtest86 but i don't think that my hardware is the problem because "john-1.8.0-jumbo-1" with the same command works.This is my hardware:


Platform #0 name: AMD Accelerated Parallel Processing
Platform version: OpenCL 1.2 AMD-APP (1573.4)
	Device #0 (0) name:	Hawaii
	Device vendor:		Advanced Micro Devices, Inc.
	Device type:		GPU (LE)
	Device version:		OpenCL 1.2 AMD-APP (1573.4)
	Driver version:		1573.4 (VM) - Catalyst 14.9 (Mantle) [recommended]
	Native vector widths:	char 4, short 2, int 1, long 1
	Preferred vector width:	char 4, short 2, int 1, long 1
	Global Memory:		3.0 GB
	Global Memory Cache:	16.0 KB
	Local Memory:		32.0 KB (Local)
	Max memory alloc. size:	2.0 GB
	Max clock (MHz):	1018
	Profiling timer res.:	1 ns
	Max Work Group Size:	256
	Parallel compute cores:	44
	Stream processors:	2816  (44 x 64)
	PCI device topology:	0e:00.0
	ADL:			Overdrive0, device id -1

	Device #1 (1) name:	Hawaii
	Device vendor:		Advanced Micro Devices, Inc.
	Device type:		GPU (LE)
	Device version:		OpenCL 1.2 AMD-APP (1573.4)
	Driver version:		1573.4 (VM) - Catalyst 14.9 (Mantle) [recommended]
	Native vector widths:	char 4, short 2, int 1, long 1
	Preferred vector width:	char 4, short 2, int 1, long 1
	Global Memory:		3.0 GB
	Global Memory Cache:	16.0 KB
	Local Memory:		32.0 KB (Local)
	Max memory alloc. size:	2.0 GB
	Max clock (MHz):	1018
	Profiling timer res.:	1 ns
	Max Work Group Size:	256
	Parallel compute cores:	44
	Stream processors:	2816  (44 x 64)
	PCI device topology:	0d:00.0
	ADL:			Overdrive0, device id -1

	Device #2 (2) name:	Hawaii
	Device vendor:		Advanced Micro Devices, Inc.
	Device type:		GPU (LE)
	Device version:		OpenCL 1.2 AMD-APP (1573.4)
	Driver version:		1573.4 (VM) - Catalyst 14.9 (Mantle) [recommended]
	Native vector widths:	char 4, short 2, int 1, long 1
	Preferred vector width:	char 4, short 2, int 1, long 1
	Global Memory:		3.0 GB
	Global Memory Cache:	16.0 KB
	Local Memory:		32.0 KB (Local)
	Max memory alloc. size:	2.0 GB
	Max clock (MHz):	1018
	Profiling timer res.:	1 ns
	Max Work Group Size:	256
	Parallel compute cores:	44
	Stream processors:	2816  (44 x 64)
	PCI device topology:	06:00.0
	ADL:			Overdrive0, device id -1

	Device #3 (3) name:	Hawaii
	Device vendor:		Advanced Micro Devices, Inc.
	Device type:		GPU (LE)
	Device version:		OpenCL 1.2 AMD-APP (1573.4)
	Driver version:		1573.4 (VM) - Catalyst 14.9 (Mantle) [recommended]
	Native vector widths:	char 4, short 2, int 1, long 1
	Preferred vector width:	char 4, short 2, int 1, long 1
	Global Memory:		3.0 GB
	Global Memory Cache:	16.0 KB
	Local Memory:		32.0 KB (Local)
	Max memory alloc. size:	2.0 GB
	Max clock (MHz):	1018
	Profiling timer res.:	1 ns
	Max Work Group Size:	256
	Parallel compute cores:	44
	Stream processors:	2816  (44 x 64)
	PCI device topology:	05:00.0
	ADL:			Overdrive0, device id -1

	Device #4 (4) name:	Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
	Device vendor:		GenuineIntel
	Device type:		CPU (LE)
	Device version:		OpenCL 1.2 AMD-APP (1573.4)
	Driver version:		1573.4 (sse2,avx)
	Native vector widths:	char 16, short 8, int 4, long 2
	Preferred vector width:	char 16, short 8, int 4, long 2
	Global Memory:		62.0 GB
	Global Memory Cache:	32.0 KB
	Local Memory:		32.0 KB (Global)
	Max memory alloc. size:	15.0 GB
	Max clock (MHz):	1200
	Profiling timer res.:	1 ns
	Max Work Group Size:	1024
	Parallel compute cores:	8
	PCI device topology:	00:00.0

**Comment by Sayantan2048** [comment]
Please post the exact options you used along with the command line output leading up to the error. Also add -v=4 with your options.

**Comment by salu90** [comment]
./john --markov=0-260:0:0:12 ../combo_not.txt --format=raw-sha1-opencl -v=4
Device 0: Hawaii
Warning: excessive partial hash collisions detected
Using default input encoding: UTF-8
Loaded 6458020 password hashes with no different salts (Raw-SHA1-opencl [SHA1 OpenCL])
Remaining 6458004 password hashes with no different salts
Options used: -I ./kernels -cl-mad-enable -DDEVICE_INFO=266 -D_OPENCL_COMPILER -DDEV_VER_MAJOR=1573 -DDEV_VER_MINOR=4 -D OFFSET_TABLE_SIZE=11 -D HASH_TABLE_SIZE=5 -D SHIFT64_OT_SZ=5 -D SHIFT64_HT_SZ=1 -D SHIFT128_OT_SZ=3 -D SHIFT128_HT_SZ=1 -D NUM_LOADED_HASHES=4 -D NUM_INT_KEYS=1 -D SELECT_CMP_STEPS=2 -D BITMAP_SIZE_BITS_LESS_ONE=262143 -D USE_LOCAL_BITMAPS=0 -D IS_STATIC_GPU_MASK=0 -D CONST_CACHE_SIZE=65536 -D LOC_0=-1 -D LOC_1=-1 -D LOC_2=-1 -D LOC_3=-1
Calculating best global worksize (GWS); max. 1s total for crypt_all()
gws:      1024	   7595593 c/s     7595593 rounds/s 134.815us per crypt_all()!
gws:      2048	  22514401 c/s    22514401 rounds/s  90.964us per crypt_all()!
gws:      4096	  42732546 c/s    42732546 rounds/s  95.852us per crypt_all()+
gws:      8192	  79561788 c/s    79561788 rounds/s 102.964us per crypt_all()+
gws:     16384	 136030022 c/s   136030022 rounds/s 120.444us per crypt_all()+
gws:     32768	 214949653 c/s   214949653 rounds/s 152.445us per crypt_all()+
gws:     65536	 247408358 c/s   247408358 rounds/s 264.890us per crypt_all()+
gws:    131072	 269489197 c/s   269489197 rounds/s 486.372us per crypt_all()+
gws:    262144	 343321738 c/s   343321738 rounds/s 763.552us per crypt_all()+
gws:    524288	 318852178 c/s   318852178 rounds/s   1.644ms per crypt_all()
gws:   1048576	 360454679 c/s   360454679 rounds/s   2.909ms per crypt_all()+
gws:   2097152	 366549671 c/s   366549671 rounds/s   5.721ms per crypt_all()+
gws:   4194304	 368112757 c/s   368112757 rounds/s  11.394ms per crypt_all()
Max local worksize 256, Local worksize (LWS) 64, global worksize (GWS) 2097152
Segmentation fault (core dumped)



./john --mask=?l?l?l?l?l?l?l?l ../combo_not.txt --format=raw-sha1-opencl -v=4
Device 0: Hawaii
Warning: excessive partial hash collisions detected
Using default input encoding: UTF-8
Loaded 6458020 password hashes with no different salts (Raw-SHA1-opencl [SHA1 OpenCL])
Remaining 6458004 password hashes with no different salts
Options used: -I ./kernels -cl-mad-enable -DDEVICE_INFO=266 -D_OPENCL_COMPILER -DDEV_VER_MAJOR=1573 -DDEV_VER_MINOR=4 -D OFFSET_TABLE_SIZE=11 -D HASH_TABLE_SIZE=5 -D SHIFT64_OT_SZ=5 -D SHIFT64_HT_SZ=1 -D SHIFT128_OT_SZ=3 -D SHIFT128_HT_SZ=1 -D NUM_LOADED_HASHES=4 -D NUM_INT_KEYS=1 -D SELECT_CMP_STEPS=2 -D BITMAP_SIZE_BITS_LESS_ONE=262143 -D USE_LOCAL_BITMAPS=0 -D IS_STATIC_GPU_MASK=0 -D CONST_CACHE_SIZE=65536 -D LOC_0=-1 -D LOC_1=-1 -D LOC_2=-1 -D LOC_3=-1
Calculating best global worksize (GWS); max. 1s total for crypt_all()
gws:      1024	   8439653 c/s     8439653 rounds/s 121.332us per crypt_all()!
gws:      2048	  22662387 c/s    22662387 rounds/s  90.370us per crypt_all()!
gws:      4096	  39051178 c/s    39051178 rounds/s 104.888us per crypt_all()+
gws:      8192	  79561788 c/s    79561788 rounds/s 102.964us per crypt_all()!
gws:     16384	 137210237 c/s   137210237 rounds/s 119.408us per crypt_all()+
gws:     32768	 214742581 c/s   214742581 rounds/s 152.592us per crypt_all()+
gws:     65536	 253215617 c/s   253215617 rounds/s 258.815us per crypt_all()+
gws:    131072	 258543012 c/s   258543012 rounds/s 506.964us per crypt_all()+
gws:    262144	 293542148 c/s   293542148 rounds/s 893.037us per crypt_all()+
gws:    524288	 340381550 c/s   340381550 rounds/s   1.540ms per crypt_all()+
gws:   1048576	 357523247 c/s   357523247 rounds/s   2.932ms per crypt_all()+
gws:   2097152	 145382045 c/s   145382045 rounds/s  14.425ms per crypt_all()
gws:   4194304	 368884969 c/s   368884969 rounds/s  11.370ms per crypt_all()+
Max local worksize 256, Local worksize (LWS) 256, global worksize (GWS) 4194304
Using Mask Mode with internal candidate generation, global worksize(GWS) set to 65536
Press 'q' or Ctrl-C to abort, almost any other key for status
Segmentation fault (core dumped)

**Comment by Sayantan2048** [comment]
do a:
git pull --rebase
make distclean
./configure --enable-asan(speed is lower, please reconfigure without this option.)
make -s -j8
run john with -v=4

You're running an older build.

**Comment by Sayantan2048** [comment]
I have found the issue. Debugging it now!!

**Comment by Sayantan2048** [comment]
Temporary bug fix applied. 52bf4c5642af1b34a2ddd66.

**Comment by magnumripper** [comment]
Is the linkedin dataset even usable with raw-sha1-opencl? Will it handle the crippled hashes?

**Comment by frank-dittrich** [comment]
I thought the same when reading
```
Warning: excessive partial hash collisions detected
```

It will most likely not produce useful results.
For CPU, we have  Raw-SHA1-Linkedin, but there was no OpenCL version.
(Most of the hashes could easily be cracked with the CPU format, though.)

**Comment by Sayantan2048** [comment]
I don't know for sure as I haven't test using LinkedIn hashes. However, this patch will fix segmentation fault due to excessive hash collisions. At least we should be able to load them on to GPU memory.

**Comment by magnumripper** [comment]
Yes, the fixes applies anyway

**Comment by salu90** [comment]
Thanks for the fix.
The raw-sha1-opencl doesn't crack the linkedin crippled hashes but only the normal SHA1 hashes in the dataset

**Comment by frank-dittrich** [comment]
@salu90 Yes, that's why you should filter out all those crippled hashes and use raw-sha1-opencl on the remaining hashes.

**Comment by magnumripper** [comment]
For things like Markov mode, the CPU format might be better anyway - especially if using an AVX2 build.

**Comment by magnumripper** [comment]
One could want our normal SHA1 formats to reject any hashes starting with hex "00000" and output a warning. But one real hash out of a million or so actually starts with five zeros, so we can't.

**Comment by salu90** [comment]
@magnumripper Why the CPU format works better than the GPU format using the markov mode?
I read the paper that inspired the markov mode(Fast Dictionary Attacks on Passwords Using Time-Space tradeoff), which type of markov algorithm(zero-order, first-order) is used by the john markov mode?

**Comment by frank-dittrich** [comment]
@salu90 given john's current architecture, for very fast hash formats like this one, the main bottleneck is transfer of password candidates to GPU, --mask mode is the only one which avoids this, because with --mask mode, part of the candidates is generated on the GPU.

**Comment by magnumripper** [comment]
>  --mask mode is the only one which avoids this, because with --mask mode, part of the candidates is generated on the GPU.

Currently, yes. At some point in time we may have Markov and/or Incremental modes with GPU generation too. And/or something else.

I'm not sure which Markov type we use, @bartavelle wrote it. Docs refer to http://www.cs.utexas.edu/~shmat/shmat_ccs05pwd.ps

**Comment by magnumripper** [comment]
Oh BTW you can combine them. For example, Markov mode with 4 digits appended by mask mode would be fast in mask-aware OpenCL formats.

**Comment by Sayantan2048** [comment]
Proper fix. de8eb66a6d4f
