### ISSUE TITLE
lm-opencl problem with nvidia under OSX

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1561]
```
$ for i in 0 1 2 ; do ../run/john -test -form:lm-opencl -dev=$i ; done
Device 0: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
Benchmarking: lm-opencl, traditional crypt(3) [LM BS OpenCL(inefficient)]... DONE
Many salts:	21802K c/s real, 4085K c/s virtual
Only one salt:	21282K c/s real, 3570K c/s virtual

Device 1: HD Graphics 4000
Benchmarking: lm-opencl, traditional crypt(3) [LM BS OpenCL(inefficient)]... DONE
Many salts:	20295K c/s real, 148034K c/s virtual
Only one salt:	20460K c/s real, 139810K c/s virtual

Device 2: GeForce GT 650M
Benchmarking: lm-opencl, traditional crypt(3) [LM BS OpenCL(inefficient)]... OpenCL error (CL_INVALID_OPERATION) in file (opencl_lm_b_plug.c) at line (200) - (failed to get CL_DEVICE_WARP_SIZE_NV.)
```
This is nvidia, but OSX does not expose any proprietary queries so we can't rely on them (actually we should never rely on them, there should always be a fallback). @Sayantan2048 you can ignore this, I'll look into it.

**Comment by magnumripper** [comment]
BTW the "traditional crypt(3)" text is not correct for this format.

**Comment by Sayantan2048** [comment]
There's another error- this is a non salted hash but somehow the benchmark shows many salts row. Any clue what's wrong?

**Comment by magnumripper** [comment]
Ah, yes. I'll fix that too. It's BENCHMARK_LENGTH. It should be 0 for non-salted formats.

**Comment by magnumripper** [comment]
Fixed. Real-crack speed look pretty low at first because auto-tune happens late (and is slow).

**Comment by Sayantan2048** [comment]
Why does the clock keeps ticking while we're still inside reset ? Is there a logical reason to start the timer before reset ?

**Comment by magnumripper** [comment]
I'm planning to have a look at that. I added a clock reset years ago, perhaps I need to move that now. It was only recently we started tuning in reset instead of init.
