### ISSUE TITLE
Contrived dynamic test fails

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1563]
I saw the dynamic compiler format defaults to a test vector of just `dynamic=md5($p)` and thought we should use something that exercises the format better.
```
$ ../run/john -test=0 -form:'dynamic=md4(MD4(md4_raw(md5(MD5(md5_raw(sha1(SHA1(sha1_raw(sha256(SHA256(sha256_raw(sha512(SHA512(sha512_raw($p)))))))))))))))'
Testing: dynamic=md4(MD4(md4_raw(md5(MD5(md5_raw(sha1(SHA1(sha1_raw(sha256(SHA256(sha256_raw(sha512(SHA512(sha512_raw($p))))))))))))))) [128/128 AVX 4x]... FAILED (cmp_all(2))

$ ../run/john -test=0 -form:'dynamic=md4(MD4(md4_raw(md5(MD5(md5_raw(sha1(SHA1(sha1_raw(sha256(SHA256(sha256_raw(sha512(SHA512(sha512_raw($p))))))))))))))),debug'
push
push
push
push
push
push
push
push
push
push
push
push
push
push
push
app_p
f512r
f512H
f512h
f256r
f256H
f256h
f1r
f1H
f1h
f5r
f5H
f5h
f4r
f4H
f4h
Expression=dynamic=md4(MD4(md4_raw(md5(MD5(md5_raw(sha1(SHA1(sha1_raw(sha256(SHA256(sha256_raw(sha512(SHA512(sha512_raw($p)))))))))))))))
Flag=MGF_FLAT_BUFFERS
Test=@dynamic=md4(MD4(md4_raw(md5(MD5(md5_raw(sha1(SHA1(sha1_raw(sha256(SHA256(sha256_raw(sha512(SHA512(sha512_raw($p)))))))))))))))@4afea72e363898acc198409bc0032aef:abc
Test=@dynamic=md4(MD4(md4_raw(md5(MD5(md5_raw(sha1(SHA1(sha1_raw(sha256(SHA256(sha256_raw(sha512(SHA512(sha512_raw($p)))))))))))))))@abb24138187b6ca94aeecbc63d513de2:john
Test=@dynamic=md4(MD4(md4_raw(md5(MD5(md5_raw(sha1(SHA1(sha1_raw(sha256(SHA256(sha256_raw(sha512(SHA512(sha512_raw($p)))))))))))))))@c8b7f09e41b1bb4fce6dd070276cbdae:passweird
Func=DynamicFunc__clean_input_kwik
Func=DynamicFunc__LargeHash_OUTMode_raw
Func=DynamicFunc__append_keys
Func=DynamicFunc__SHA512_crypt_input1_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16u
Func=DynamicFunc__SHA512_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16
Func=DynamicFunc__SHA512_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_raw
Func=DynamicFunc__SHA256_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16u
Func=DynamicFunc__SHA256_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16
Func=DynamicFunc__SHA256_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_raw
Func=DynamicFunc__SHA1_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16u
Func=DynamicFunc__SHA1_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16
Func=DynamicFunc__SHA1_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_raw
Func=DynamicFunc__MD5_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16u
Func=DynamicFunc__MD5_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16
Func=DynamicFunc__MD5_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_raw
Func=DynamicFunc__MD4_crypt_input2_overwrite_input2
Func=DynamicFunc__LargeHash_OUTMode_base16u
Func=DynamicFunc__MD4_crypt_input2_overwrite_input2
Func=DynamicFunc__MD4_crypt_input2_to_output1_FINAL
MaxInputLenX86=110
MaxInputLen=110
```
Interestingly enough, the first two test vectors pass but the third fails. EDIT: The first passes, the second fails.

**Comment by jfoug** [comment]
May still be a key cleaning issue, bouncing from 64 bit to 32 bit MD hashes.

**Comment by jfoug** [comment]
First glance, it looks like the raw BE formats if done with SIMD are needing byte swapped.

**Comment by jfoug** [comment]
The problem is in the sse-int functions.  Why are we byte swapping for flat formats?

**Comment by magnumripper** [comment]
Not sure what you mean. Obviously we're byte swapping SHA1/SHA2 flat input?

**Comment by jfoug** [comment]
Nope, problem was all in key cleaning for the 64 bit hashes.  I have to clean at offset 56 of the buffer, if the length of hash is < 56 bytes.  I ALSO had to clean at offset end of 3rd buffer (192-8) if the length of the hash is < 184.  That 2nd clean was the key.  There was residue from a sha256 of 128 byte string in there.  So bytes 128 to 192 were cleaned, EXCEPT for the length in the 184-192 range.  So my clean logic was cleaning stuff up, but leaving that 0x400 in the buffer

This was a dynamic problem, NOT a dyna-compiler problem. The compiler was working just fine.  The script being generated was fine.  The test strings generated were fine.  I also found a bug in pass_gen.pl (I used it to help debug this problem in dynamic),  It was passing a lc expression to the dynamic engine, thus losing all of the things like SHA512(expr)

**Comment by jfoug** [comment]
There were still issues.  Right now, I have numerous fixes being worked on.  Fixing one issue turned up another.  Fixing that allowed first to be undone (or partly undone), ...  rinse and repeat.  It will be nice when this code is stabilized.

**Comment by magnumripper** [comment]
It's worth it. This feature simply rocks! We're not in a hurry but I picture we should eventually do automatic #saltfail optimizations when applicable, and so on. Perhaps even non-flat stuff at times? Why not, given the primary functions already exist? Sooner or later all "numbered" dynamic formats will be obsolete - this new thing will simply always produce whatever code is best :wink:

**Comment by jfoug** [comment]
I believe after this change, that this issue is now fully addressed,  d32843a

> Sooner or later all "numbered" dynamic formats will be obsolete 

That is the plan. This is gen3 (or gen4) of dynamic.   gen1 was md5gen.  gen2 was adding other hashes.  gen3 was adding the scripting language (not sure if other hashes of the script language was first).  gen4 is self compiling

I am not 100% sure I can get rid of the flat code, since there is some stuff that is MUCH more heavily optimized.  However, I might simply move all of the scripts out of the dynamic with numbers, into a 'library' of scripts. Then if someone asks for md5($p) I can give them the optimal script. If they ask for md5($p),inputlen=110  then I can use the compiler to generate the code in flat format. But the dyna compiler would treat both of them as the same, when loading files (at least .pot files).  There are only a few things which 'belong' to the expression that follow the expression (with comma's, etc). Some of those are the constants.  They fully matter.  I really think that might be it. I do not see salt-length, input-length, or things like a fixed salt, fixed user name, etc, would make 2 expressions different from each other.

There is one additional thing I will have to normalize when it comes to constants:  ``` md5($c1.$p.$c2),c1=x,c2=x ```  and  ``` md5($c1.$p.$c1),c1=x ```  are the same.   Also ``` md5($c2.$p.$c1),c1=x,c2=y ```  and  ``` md5($c1.$p.$c2),c1=y,c2=x ``` are the same.  The normalizer will have to address these, and put them into cannonical layout

**Comment by jfoug** [comment]
I will be working on the optimizer some this weekend. But I think the biggest gain on optimizations is to simply 'cheat', and store a library of fast proper built scripts, lol, like we have in dynamic-prepare.c and dynamic.conf

**Comment by magnumripper** [comment]
After #1564 (crackpot edition) we can finally stop producing new formats and just tweak the optimizer now and then. Heh.

**Comment by jfoug** [comment]
When I started dynamic years ago, I had semi-high hopes of just that.  It has fallen considerably short of that.  The biggest issue, is in things like text manipulations, and input format handling, etc.  Those are the 2 biggest hurdles that i really do not think can be overcome easily.  Take for instance any of the crypt* formats.  They have internal conditional logic within the looping.  Hard to do in the type of code that dynamic is. Or a real winner, SunMD5.  I do not see Moffet Coinflip being something 'easy' to do generically.  Heck, even HMAC and PBKDF2 would require specialized logic to handle.

**Comment by jfoug** [comment]
If I get the dox done this weekend, and get some minor optimizations in, I might be ready to announce this thing on the email list.   There is LOTS of good stuff in here. Heck, this is the ONLY place in john, where many of these hashes can even be found.  Most of the haval algorithms are only here.  Same for ripemd, skein, etc, where only a few of the hashes have formats for them.  Dyna has all of them, and the dyna-compiler can handle all of them and do it pretty well.

**Comment by magnumripper** [comment]
SunMD5 is a good example of what we should not support in dynamic. Dynamic should be all about `md4(md5(sha1(sha256(sha512($s(sha384(sha224($p))))))))))` that absolutely no-one else would consider supporting.

**Comment by jfoug** [comment]
dynamic as a CGI page on the net (php, or whatever), would be pretty cool.  Simply do a php rendering engine, that sucks off the expression, sanatizes it, computes it, and returns the results.  Would take the place of what InsideOut used to have, but do SOOOOO much more, as a user could build any expression they wanted.  Hell, it would not even have to use jtr. It could really be an interface that launches pass_gen.pl, and that tool does all the heavy lifting.

**Comment by magnumripper** [comment]
Anyways, this issue is fixed
