### ISSUE TITLE
All the recent whitespace problems

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1567]
@jfoug @Sayantan2048 

It would be awesome if you could fix your editor to not introduce whitespace errors. I do "git log -p" every morning, and seeing all those whitespace errors (in glorious red color) isn't very pleasant ;)

@loverszhaokai 

How far did you get in "enforcing" coding style? It would be great to have something like https://github.com/DynamoRIO/dynamorio/blob/master/make/git/devsetup.sh for JtR.

**Comment by magnumripper** [comment]
Coding style is @loverszhaokai

**Comment by Sayantan2048** [comment]
I'm using kwrite with the editor configured to remove trailing white spaces while saving. Strangely it's not doing its job very well.  I'll update to a newer version and hope it'll fix the issue.

**Comment by jfoug** [comment]
I just found this, and will see how it works   http://editorconfig.org/   They have a plugin for both VC, and for Notepad++ so hopefully I can get these working in a consistent manner and avoid this crap.

**Comment by jfoug** [comment]
Many github projects have their own .editorconfig file..

https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig

**Comment by magnumripper** [comment]
That doesn't look too bad, it might be something for @loverszhaokai to pick up. I think we use a good number of different editors.

On a side note I have tried several times getting Jumbo into an Xcode project but always fail and I hate spending time learning proprietary crap. I did a couple of one-shot imports to Eclipse just for tricky rebasing, but that is easy enough I always dropped the project after doing the task at hand.

**Comment by jfoug** [comment]
I will add a .editorconfig to our project.  I am installing this plugin in my editors.

The nice thing, is that for code in other areas I work in, there will not be a .editorconfig, so it will use my 'normal' config that is used for other things.

**Comment by kholia** [comment]
I now remember @magnumripper telling me to fix my editor configuration some years back (2010?). I spent a fair bit of time reading about "Indent with tabs, align with spaces" thing, and tweaking my Vim. I fuck up less now :-)

Thanks for taking care of this! :)

**Comment by magnumripper** [comment]
We should add info about this editorconfig thingy to the devel wiki

**Comment by jfoug** [comment]
Can we stick a fork in this issue, and call it done?

**Comment by magnumripper** [comment]
Yep
