### ISSUE TITLE
encoding_data.h can not be updated any more

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1568]
./run/cmpt_cp.pl and ./src/unused/UnicodeData.txt files are no longer in the project.

**Comment by magnumripper** [comment]
They are in a patch or tarball on the Openwall wiki (and UnicodeData.txt is better taken from Unicode consortium). Maybe I should just place cmpt_cp.pl in the tree.

**Comment by jfoug** [comment]
Does the script complain and tell a user where to get the UnicodeData.txt (and the casing and multi-byte) files?   If not, then we probably should update the script itself to gracefully tell a user what is expected.

Yes, I did find that patch, and understand we do not want to drop out a 1+mb file, especially when it will almost certainly be out of date when someone wants to use it.

**Comment by jfoug** [comment]
I just noted the problem, because I wanted to fix the script to not output lines with trailing spaces, and could not find the script.
