### ISSUE TITLE
pkzip format: Default to not use file magics.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1569]
We had a tricky problem on the ML and with a good portion of luck I could spot the problem: http://www.openwall.com/lists/john-users/2015/07/21/6

User had a file named john-1.8.0-jumbo-1.gz - but it wasn't gzipped at all, the extension lied. User zipped it with a password and ran zip2john on it to produce a test hash. zip2john decided to use the file magic for gz so user ended up with false negative (shrug)!

Since the Huffman checks are so excellent now, I think we should simply disable all use of file magics, at least by default.

**Comment by magnumripper** [comment]
I see a mere 1% speed drop (even though file is 30 MB)

**Comment by jfoug** [comment]
Sounds like all the tricky code for the 'magic' crap ended up being not that beneficial, with the latest other enhancements we had.  Good thing. Sorry for the obscure bug.

**Comment by magnumripper** [comment]
I wouldn't want to drop the code though, it IS faster (especially for huge files) and sometimes you *know* you can use it.
