### ISSUE TITLE
Travis CI  Upgrade to a container environment

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1570]
We use container environment (I think) on Circle. It allows installing a lot of packages up front, instead of installing to a vanilla 'OS' each time we build.

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by claudioandre** [comment]
This is done. No one interested upstream. Tests include:
- Ubuntu devel (17.04 months ago; now 17.10).
- CentOS
- Ubuntu LTS
