### ISSUE TITLE
Testing before CMIYC2015

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1572]
I think it might be a good idea to do some extended testing before CMIYC2015. Especially new stuff like GPU-side mask mode and ad-hoc dynamic.

We might want to fix the TS vs UTF8 issues, or just revert the john.conf changes while testing.

Should we even add a "milestone" of "CMIYC2015" with date set to Aug 6?

**Comment by jfoug** [comment]
Did you have any specific priority on things TBD before CMIYC ?  I hate to say it, but I think the few in this milestone are not overly significant.

**Comment by magnumripper** [comment]
Nah I just added a couple issues labeled as 'bug' without much thought. The important thing is testing.
