### ISSUE TITLE
can not build 'true' SSE2  32 bit.  x86-sse.s built with -native

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1575]
I am trying to build a 'pure' SSE2 on cygwin, and configure does not allow it  (32 bit).  The reason I am trying this, is I had a LOT of errors building on a 32 bit linux VM on the x86-sse.S file.  There were macros which should only have 4 params, that had 5. But I have not seen a problem building any where else.

So I am trying to do this:

CPPFLAGS="-mno-sss3" ./configure

but the ASFLAGS is this in makefile (I guess I could also totally override them)

ASFLAGS = -DAC_BUILT  -DARCH_LITTLE_ENDIAN=1 -march=native -msse2 -c -fopenmp   -DUNDERSCORES

CFLAGS = -DAC_BUILT -march=native -msse2 $(CFLAGSX)

-march=native is also there :(

Since -march=native is there, I get XOP for all my DES stuff, even though I really want SSE2 only.

**Comment by jfoug** [comment]
I really think we should make controlling '-enable / -disable' for these forced CPU flavors.  I have thought that a long time, especially since people insist that -march-native gets shoved into the *FLAGS lines.

It makes building a 'safe' exe for a machine other than the one used to build the exe, a hard thing to do

**Comment by frank-dittrich** [comment]
Can you try a 32bit legacy build as a workaround?
THere you should be able to pick just sse2.

**Comment by magnumripper** [comment]
Use --disable-native-march just for disabling the march=native.

**Comment by jfoug** [comment]
--disable-native-march works just fine. I should have looked at the help provided by configure.  That does what I want.

so now: ``` CPPFLAGS="-mno-sss3" ./configure --disable-native-march```   Will get me a 'pure' SSE2 item, and  ``` CPPFLAGS="-mno-avx -mno-xop" ./configure --disable-native-march``` will get me a 'pure' SSE4.1 item.
