### ISSUE TITLE
LM-opencl should support OpenCL 1.1

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1586]
Super currently doesn't build lm-opencl after `scl enable devtoolset-3 bash`. We should support OpenCL 1.1.

Having said that, I have added `HAVE_OPENCL_1_2` macro that actually tests the *lib* for presence. But please note that the *device* (as in run-time build of kernel) may **still** be only 1.1, even though your headers and driver platform are 1.2. At least this is the case for 1.1 vs. 1.0.

**Comment by Sayantan2048** [comment]
Now fixed with 37c88d.
