### ISSUE TITLE
bitcoin2john.py

### ISSUE THREAD

**Issue by whitj00** [magnumripper/JohnTheRipper#1595]
Every single time I'm just getting this..

" ERROR:root:Couldn't open wallet.dat/main. Try quitting Bitcoin and running this again."

I have tried it on windows and linux VM..

I have completely stopped bitcoin core, copied the wallet.dat to a new location.. tried everything possible with the same result.. I change some of the code to show this error

    r = db.open(walletfile, "main", DB_BTREE, flags)
bsddb.db.DBInvalidArgError: (22, 'Invalid argument -- C:\\Users\\x3\\AppData\\Roaming\\Bitcoin\\new\\bitcoin2john.py: unexpected file type or format')

Command I'm using

C:\Users\x3\AppData\Roaming\Bitcoin\new>bitcoin2john.py wallet.dat

wallet.dat is in the new folder..

I am using python 2.7

**Comment by magnumripper** [comment]
@kholia?

**Comment by kholia** [comment]
@whitj00 do you have a sample "wallet.dat" file which clearly exhibits this problem?

If not, I won't be able to debug this for a long long while.

**Comment by whitj00** [comment]
Every wallet.dat... I have asked friends to try and every one of them has the same problem.

**Comment by kholia** [comment]
@whitj00 this should be fixed now, thanks for reporting! :+1:

**Comment by magnumripper** [comment]
Wow that was easy. Thanks @kholia!

**Comment by jerry4free** [comment]
I also encounter this problem on macOS today, every wallet.dat. How was it fixed?@ @kholia
