### ISSUE TITLE
setup a CI for non-SIMD builds

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1598]
we should be able to do this on one of the existing CI environments

**Comment by zzlei** [comment]
I think this would be very useful. I just caught a couple of bugs in a non-SIMD ARM build.

**Comment by jfoug** [comment]
I was the one that introduced many of the recent flurry of non-SIMD bugs.  I think I have most of them were brought on with the changes to dyna to get it to build better for wider SIMD codes, and in the cleanup of tiny-alloc for all formats.

But I think things are once again 'caught up' where non-SIMD build properly  (oSSL, md5_body and md5_body with MD5_X2).   I just want to make sure things stay 'caught up'.  So putting this into a CI now, for a CPPFLAGS="-mno-sse2" seems like the right thing to do.

**Comment by jfoug** [comment]
@kholia   I think you will have to fix the fedora docker image. I tried adding libs needed to build, but the build complains about lack of sudo   I have fired off a build with sudo commented out (just using dnf raw), but I am 99% sure it will fail with a 'dnf requires root access' or some similar error.

Can you update the Fedora image, getting it where it can build JtR for Linux (not just the cross compile).

I have the script updated, but you may want to remove the dnf line, once the image is up to date.

**Comment by jfoug** [comment]
Holly crap!  that worked without sudo!!!  lol.  I can live with that.   But it would still be nice to have libssl-devel installed on the docker already.
