### ISSUE TITLE
rename fmt_plaintext to fmt_zzz_plaintext?

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1610]
to make plaintext the last plugin format which gets registered, just in case?
```
diff --git a/src/plaintext_fmt_plug.c b/src/plaintext_fmt_plug.c
index f13cbd7..38b6790 100644
--- a/src/plaintext_fmt_plug.c
+++ b/src/plaintext_fmt_plug.c
@@ -21,7 +21,7 @@
  *
  */
 
-#define FMT_STRUCT     fmt_plaintext
+#define FMT_STRUCT     fmt_zzz_plaintext
 
 #if FMT_EXTERNS_H
 extern struct fmt_main FMT_STRUCT;
```

**Comment by jfoug** [comment]
Any reason why you just did not check this in?  The change seems to be very innocuous

**Comment by frank-dittrich** [comment]
Just because I thought magnum had a reason.
But I might as well just commit it.

**Comment by jfoug** [comment]
Putting that one dead last makes sense to me, at least.

**Comment by frank-dittrich** [comment]
OK. (It will be "almost" last - there are a few non-plugins...)

**Comment by jfoug** [comment]
but I agree with you (yes, crypt is last, so that 'better' plug functions will be used), but this one as a plug should be last, as should dummy.

**Comment by frank-dittrich** [comment]
Done, commit 46dda3f7ba21475a22a5a759e109334aa286e584

**Comment by jfoug** [comment]
we spent more time on this conversation than the commit process, lol.

**Comment by frank-dittrich** [comment]
Dummy is core.

**Comment by jfoug** [comment]
Gotcha, but so is crypt.  They both should be last or pretty close to last.

**Comment by frank-dittrich** [comment]
Yes, instead of putting the jumbo logic after dummy and before crypt, I think we should move it before
` john_register_one(&fmt_dummy);` in john.c. @magnumripper what do you think?

**Comment by frank-dittrich** [comment]
moved down dummy as well.
commit dbf6f998f67a4b4c78454e428ddbdada4c854761

**Comment by magnumripper** [comment]
Not sure what you are doing here. Doesn't the plaintext format **require** the `$0$` tag?

**Comment by magnumripper** [comment]
If you did this from some IRL problem, I'm fine with it. If it was from dry-running I will be angry ;-)

**Comment by jfoug** [comment]
Might be time to watch a movie again, lol

You need to build an 'angry room' for yourself.

**Comment by magnumripper** [comment]
I'm on vacation now, even you two trolls can't make me angry. I'll just have another beer :beers: :beer: :beers:
