### ISSUE TITLE
Implement ?W for --mask mode

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1612]
Unlike `?w`, I'd like `?W` to mean the input word, but case toggled for every character.
With `--mask='?W?s?w'`, you could easily produce candidates like `WORD!word` etc.
If GPU side mask mode doesn't support that right after implementation, I wouldn't care too much.

**Comment by jfoug** [comment]
so you would want ?w?W to be   JohnjOHN if the input word is John ?

**Comment by Sayantan2048** [comment]
This does not affect gpu side mask.

**Comment by jfoug** [comment]
I did not think it would impact GPU stuff. It looks like ?w (and now ?W when I can figure out what is wrong with my git), simply set constant data into the mask, so the GPU does not even know ?w or ?W were even used.

**Comment by magnumripper** [comment]
Good stuff. Cool idea, and implemented a couple hours later! :+1:

**Comment by frank-dittrich** [comment]
This was just to compensate for moving your plaintext format down the list.
@Sayantan2048 had to fix what @jfoug accidentally broke, but now everything works.
