### ISSUE TITLE
rawSHA1 / nsldap formats should merge into a single format

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1613]
- [x] nsldap/rawSHA1  and (and place common functions into a common source)
- [x] rawsha1-ng (just add {SHA} support)
- [x] raw-sha1 linked in (just add {SHA} support)
- [ ] opencl_rawsha1/opencl_nsldap 
- [x] nsldaps/saltedsha1
- [ ] opencl_salted_sha/opencl_nsldaps
- [x] deprecate gen-sha1 (just drop it, no need for compatibility)  [moved to unused for now]

This should be a single format, simply adding a prepare and or split to convert one into the other.  Same for opencl. We should do this with a rawSHA1_common_plug.c, putting all the valid(), prepare(), split(), etc into that one file (and any other code that should be common).

I am sure there are also other formats which we have more than 1 format that should be 'merged' into a single format.  I have not looked for them, but I am pretty sure there are numerous.

**Comment by Sayantan2048** [comment]
I saw this late. So, I already commented on 7e1d355eec95100.  

@jfoug , @magnumripper I have added a template split/prepare/valid to raw-sha1-opencl so that you don't have to modify any opencl stuff. See 6188680. Please modify the split/prepare/valid in raw-sha1-opencl to adjust nsldap and delete this one.

**Comment by jfoug** [comment]
From Solar:
```
On Thu, 13 Aug 2015 13:03:47 -0500, Solar Designer <solar@openwall.com> wrote:

> magnum, Sayantan -
>
> We have this historical format name Salted-SHA1, which I think we should
> get rid of in favor of either NSLDAPS (consistent with NSLDAP, and IIRC
> we also had an NSLDAPS format before?) or SSHA (consistent with SSHA512).
>
> Here are the relevant formats:
>
> [solar@super src]$ fgrep -il nsldap *.c
> nsldap_fmt_plug.c
> opencl_nsldap_fmt_plug.c
> opencl_nsldaps_fmt_plug.c
> opencl_salted_sha_fmt_plug.c
> salted_sha1_fmt_plug.c
> ssha512_fmt_plug.c
> [solar@super src]$ fgrep -wl SSHA *.c
> opencl_nsldaps_fmt_plug.c
> opencl_salted_sha_fmt_plug.c
> salted_sha1_fmt_plug.c
>
> So we currently have two OpenCL formats for the same(?) thing -
> opencl_nsldaps_fmt_plug.c and opencl_salted_sha_fmt_plug.c.  Perhaps we
> should only keep the latter code (since it's newer and more elaborate),
> but rename it to the former's filename and format name?  And perhaps we
> should do the same for salted_sha1_fmt_plug.c.
>
> Then, why is opencl_salted_sha_fmt_plug.c GPL'ed?  Sayantan, did you use
> any GPL'ed code when making it?  What code?
>
> Let's figure this out and clean it up.
>
> Thanks,
>
> Alexander
```

**Comment by jfoug** [comment]
I also see the somewhat unneeded generic-sha1 format. It does sha1($p.$s) and sha1($s.$p).  It has no SIMD, but does handle long passwords. Solar wrote the thing, and it really should just be scrapped and changed into a thin dynamic format.  The format is IMHO a format we could completely deprecate.

**Comment by jfoug** [comment]
These should be merged into 2 formats, with a common code interface:

rawSHA1_fmt_plug.c  nsldap_fmt_plug.c
opencl_rawsha1_plug.c opencl_nsldap_fmt_plug.c

My vote is to drop the 2 nsldap, add the code to the rawSHA1 and opencl_rawsha1 to handle things.  But we should also make 'common' interface code for these.

**Comment by jfoug** [comment]
for raw-sha1, I would also recommend dropping the $dynamic_26$ and switch to {SHA} with mime encoding.

**Comment by magnumripper** [comment]
> it really should just be scrapped and changed into a thin dynamic format

generic-sha1 doesn't need to be a thin dynamic. It can simply be dropped.

> for raw-sha1, I would also recommend dropping the $dynamic_26$ and switch to {SHA} with mime encoding.

Dropping? What do you mean? We probably need backward compatibility for this format.

**Comment by frank-dittrich** [comment]
Yes, we can't just drop support. We could plan to drop it in the future, if we provide a conversion tool and add a warning when john finds those legacy hash representations, pointing to the conversion tool.

**Comment by jfoug** [comment]
Dropping was the wrong word..  I would still 'support' dyna_26, in .pot file on in the input file.  I would also support raw hex (upper/lower), and {SHA}base-64.  But what would be written into the .pot file would be {SHA}base-64

**Comment by jfoug** [comment]
d3273e2  (raw-sha1-ng)

**Comment by jfoug** [comment]
@Sayantan2048, is opencl_rawsha1.c the one to 'keep' ?

Also, which is the 'keeper' hash between opencl_salted_sha.c and opencl_nsldaps.c ?

**Comment by jfoug** [comment]
There is no nsldaps_fmt.c  It was already merged at some time. However, I am going to create a 'common' .c and .h file, so that the merge of the opencl ssha1 and nsldaps can use 'common' code for things like prepare/split/valid, etc.

At this time, only the openCL formats are left.

**Comment by jfoug** [comment]
At this time, I am pretty much done with this.  I can not get raw-sha1-opencl or salted-sha1-opencl to run on any of my GPUs (including my Tahiti 7900).  The only one that i can run at all, is ssha-opencl (the nsldaps). I can get it to run on my 7900 and even on my laptop.

So I will not be the one to merge these formats (since I can not test them).   Whoever does, be sure to use the new '*_common.h' file, removing the test strings from the local file, the valid, and prepare/strip, etc, and properly putting these common functions into the format structure.

**Comment by jfoug** [comment]
I assigned to @magnumripper  but @Sayantan2048 may be the proper assignee.

**Comment by magnumripper** [comment]
I did a similar thing to MD5, supporting `{MD5}CY9rzUYh03PK3k6DJie09g==` style hashes. I didn't change the john.pot format though - in fact I'm still not quite sure we wanted to do that for SHA-1. Perhaps we should consult the user base, on john-users?
