### ISSUE TITLE
Avoid unaligned memory accesses for specific archs

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1614]
(potentially) problematic formats:

XSHA512_fmt_plug.c
XSHA_fmt_plug.c
citrix_ns_fmt_plug.c
mssql05_fmt_plug.c
mysqlSHA1_fmt_plug.c
nsldap_fmt_plug.c
nt2_fmt_plug.c
ntlmv1_mschapv2_fmt_plug.c
oracle11_fmt_plug.c
rawMD4_fmt_plug.c
rawMD5_fmt_plug.c
rawSHA1_fmt_plug.c
rawSHA1_linkedIn_fmt_plug.c
rawSHA224_fmt_plug.c
rawSHA256_fmt_plug.c
rawSHA384_fmt_plug.c
rawSHA512_fmt_plug.c
rawmd5u_fmt_plug.c
salted_sha1_fmt_plug.c
sapG_fmt_plug.c
ssha512_fmt_plug.c

**Comment by magnumripper** [comment]
I guess you mean code within `#if SIMD_COEF_xx` that assumes ARCH_ALLOWS_UNALIGNED (which was a correct assumption until you added non-intel intrinsics). We should start with just adding `#if ARCH_ALLOWS_UNALIGNED` around all such code.

And perhaps
```
#if ARCH_ALLOWS_UNALIGNED
    old code;
#else
#error Implement me!
#endif
```

**Comment by zzlei** [comment]
Can I require the caller of `set_key()` to guarantee the alignment of the `key` buffer? Or I just make an aligned copy of it inside the function?

If taking the latter approach, I think it's questionable which kind of overhead is bigger: memory copying or unaligned access.

**Comment by magnumripper** [comment]
I think currently we can't guarantee any alignment. On Intel, unaligned access is dirt cheap but for others a copy might be worthwhile.

**Comment by magnumripper** [comment]
Some (all?) fixes in d713419cd

**Comment by zzlei** [comment]
Some improvements in https://github.com/magnumripper/JohnTheRipper/pull/1695.

I checked all formats that contain variable `keybuf_word`. I don't know if there're other formats that have potentially unaligned accesses.

**Comment by magnumripper** [comment]
I think this is essentially done.

**Comment by frank-dittrich** [comment]
If anybody wants to do more, the --enable-ubsan could be enhanced.

For X86 and other architectures where unaligned access works:
```
-fsanitize=undefined -fno-sanitize=alignment -fsanitize-undefined-trap-on-error
```

For architectures where unaligned access doesn't work (or is much slower):
```
-fsanitize=undefined -fsanitize-undefined-trap-on-error
```
