### ISSUE TITLE
Build JtR as 32-bit on 64-bit platforms

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1617]
I encountered some strange issue on 32-bit ARM, and wanted to know if that's something specific to a 32-bit build. I attempted to build JtR as 32-bit binary on several 64-bit x86 platforms (linux & OS X), but to no avail.

I used `./configure CFLAGS=-m32 LDFLAGS=-m32`, and tried disabling OpenCL or CUDA, none of which worked. The toolchains used should be fine, as I can use them to compile simple 32-bit programs.

Is it possible to build a 32-bit JtR on 64-bit platforms?

**Comment by jfoug** [comment]
You may have to add -m32 to ASFLAGS also.  I have built 32 bit, and there is a couple 32 bit builds for our Circle-CI testing machine.

Now on the Circle-CI, I am using the legacy makefile, so I also may have not been able to get configure to work.  Likely it is the ASFLAGS. Here is one of the build lines from Circle-CI test script:

JOHN_CFLAGS=-m32 JOHN_ASFLAGS=-m32 JOHN_LDFLAGS=-m32 make -f Makefile.legacy -sj4 linux-x86-any

**Comment by zzlei** [comment]
I tested both approaches on well.openwall.net, but unfortunately neither worked.

With -m32 added to CFLAGS, LDFLAGS and ASFLAGS, ./configure recognizes the target as `x86_64 AVX2, 32-bit LE` and arch.h is linked to x86-64.h. I think this is wrong for a 32-bit build.

As for the legacy makefile, the error is
```
/usr/include/gmp.h:47:22: fatal error: gmp-i386.h: No such file or directory
 #include "gmp-i386.h"
                      ^
```

**Comment by magnumripper** [comment]
Here's a safe alternative
```
./configure CC='gcc -m32`
```

**Comment by jfoug** [comment]
That does not work at all for me.  I get 'C compiler can not create executables' right away in configure

**Comment by magnumripper** [comment]
You do? You should have a look in config.log and find out why. Works for me on most any platform.

**Comment by jfoug** [comment]
I have gotten it to build, but it is not a 32 bit build (not a right one).. It links in x86-64.h, x86-64.S (and that will not build).   Configure does not detect you want the 32 bit build, at least in my testing.

That is why I used Makefile.legacy on the CircleCI.  I just could not get it working.

**Comment by jfoug** [comment]
Ok, I have gotten it to work

./configure CC='gcc -m32' --host=i686-pc-linux  && make -s clean && make -sj4

That builds a correct 32 bit linux process for me.

**Comment by zzlei** [comment]
```
./configure CC='gcc -m32' --host=i686-pc-linux  && make -s clean && make -sj4
```
That still doesn't work on well, giving the message
```
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
```
Do I need to manually build a 32-bit version of OpenSSL?

**Comment by magnumripper** [comment]
Yes of course. Unfortunately, Debian/Ubuntu & co. can't have both archs of OpenSSL installed simultaneuosly (I think it's a bug but it's not trivial) so while you *should* be able to just `apt get install openssl:i386` or something like that, it wont work.

**Comment by zzlei** [comment]
Well, I just `apt get install libssl-dev:i386` on my VM (ubuntu 14) and `./configure CC='gcc -m32' --host=i686-pc-linux`, then everything worked like a charm :)

BTW, I found nothing wrong in the 32-bit build. I'll look elsewhere for the bug.

**Comment by magnumripper** [comment]
Wow, is that Ubuntu 14:10? I can't wait to use that. I use to stay with the LTS releases. That multiarch bug has been annoying me for years and years.

**Comment by zzlei** [comment]
Mine is Ubuntu 14.04.

**Comment by magnumripper** [comment]
I need to re-test. If 14.04 can do multiarch openssl, my life will suddenly get a whole lot easier!
