### ISSUE TITLE
Add ability to have 2nd pot file (read only) for usage. (would help in contests, etc)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1623]
Add something (probably in john-local.conf) but also on command line, that would allow a contest version of john to read in and strike off candidates from a 2nd 'global' .pot file, but not write to it.  This would allow keeping your own .pot file(s) while striking off candidates found by the whole team.

**Comment by magnumripper** [comment]
Perhaps it could even be a directory, where we'd use all files found.

**Comment by jfoug** [comment]
I think all in a directory would be fine also.  I guess if what the user gives us is a single file we use it. If it is directory, we use ${dir}/*.pot as our input 'files'.

NOTE, these would be read-only, at load time simply to strike off already found candidates.  I have wanted this behavior for a LONG time, and really surprised I have not added it yet.

This would allow keeping a nice 'clean' .pot file, yet still eliminating found things. Yes in the contest server, we did have the input files being 'chopped' and also had the 'global' john.pot file.  So a user can easily pull the uncracked files.  But with a load time only .pot read, it allows you to keep the input files pristine while providing the same end results.

**Comment by jfoug** [comment]
The .pot file(s) should also be re-read at certain intervals in time. We may want to timestamp the file(s) so that we know if we need to read them in again or not.  This would simply allow a long running run to continue, but still remove salts which are found by others to keep things running 'as fast' as possible.

We already have something like this in fork mode, correct?

**Comment by magnumripper** [comment]
The pot sync, yes. It's always enabled, not just for fork (so it will also sync stuff cracked using other single-process instances of john).

The initial loading is not very performance critical, but the pot sync is.

**Comment by jfoug** [comment]
For these 'extra' files, we can easily add a timestamp check, so they are not reloaded unless they change.  I guess the same logic could be said of the pot sync.  No reason to re-read that file, if it has not changed from some other fork.

**Comment by magnumripper** [comment]
The current pot sync just remembers the last read position. Since it can only be appended to, we check if EOF has moved forward.

**Comment by jfoug** [comment]
I do not think we can start at a given offset on a 'foreign' .pot file.  If a file is modified or a new one shows up in a directory, then we pretty much have to read it from start to finish (if we are going to add this to pot sync). 

The reason we 'get away' with saving state in our current .pot file is by knowing that our process (or group of processes) are writing to the end of the file.  For foreign files, we would not know that.  A .pot file like this may get entries added (or deleted).  We really have no way of knowing if an entry we thought was found later becomes 'unfound', due to cross checking or something such, so would have no way to re-add a stripped off salt.  But along with that, the order may or may not be the same, AND the offset within the file may even change.  In this contest we had many hashes that were sent using code pages, but then later 'fixed' and put into proper utf8 format. Thus the size of string is different.  Even if the worker robot 'tried' to keep the .pot file in order, knowing the offset to start from would not work at all.

**Comment by magnumripper** [comment]
Right. But the pot sync would be the last feature to care about when implementing this. As a workaround, you could always stop/resume to re-read the foreign files.

**Comment by frank-dittrich** [comment]
I'd prefer to allow just a single file and document that the the file may have added new lines while running, but it must not be changed otherwise (i.e. only `>> second.pot` is allowed.)
Allowing a directory with tons of files with redundant hashes or allowing files that change repeatedly is just crazy.

**Comment by jfoug** [comment]
I think I will attack this by just removing hashes at program start, for these 'foreign' .pots, and I don't think it will be any harder to allow single pots, or multiple.  I can easily see the item simply being a wildcard specification, then if someone lists  ./contest-pots/*.pot  as the pot file(s), then all .pots in that dir will be read.  If they list ./contest-pots/john.pot then only that one will load.

Easy-peasy either way.

But I do agree with magnum (now), that this foreign load at program start (at least to begin), is the right way to go.  That may later change, but I do not think the stipulation of always append is going to work  ITRW

**Comment by magnumripper** [comment]
I never quite understood RF_ALLOW_DIR in loader.c... is that actually just the code we need for reading a directory of pots?

**Comment by jfoug** [comment]
I believe (from memory) that RF_ALLOW_DIR was to work around problem seen when wild-carding input files.  If a directory was part of the mix, this kept john from erroring out (IIRC).  This may have been a cygwin/mingw/vc type thing.

**Comment by jfoug** [comment]
I gave it ability to load 100 .pot files (only used to scrub off candidates).  The main .pot file from options is still the only one used to write to.

**Comment by magnumripper** [comment]
This adds a lot of unneccessary scanning for items that doesn't exist. I can't see why you didn't just make it a list? All code already written. No particular limitation on number of files.

Also, I really think we should add support for "all files in <path>" because that would be much more useful.

**Comment by jfoug** [comment]
If it was done as a list, what would you say should be done?  just file names one after the other?
I thought about all pots in a dir, and we can probably add that easily.  The actual code is trivial, just keep calling the load_pot function, and the single call to fix_database cleans it all up.  'hopefully' (I have not really tested much), dupes will not be an issue.

**Comment by magnumripper** [comment]
It'd be like
```
[List.Options:potfiles]
somefile.pot
someother.pot
...
mylast.pot
```

**Comment by magnumripper** [comment]
I'm not quite sure whether the name *has* to start with `List.` or not. I can have a look at rewriting this tomorrow.

**Comment by magnumripper** [comment]
Rewritten. I ended up using `[List.Extra:Potfiles]`. Directory handling yet to be handled. I do NOT think it should be some other section - we just stat each entry and see if it's a directory or a file. So it can be:
```
[List.Options:potfiles]
somefile.pot
path/to/directory
```

**Comment by magnumripper** [comment]
Now added directory traversal (not recursive, that's kind of dangerous). @jfoug I suppose this works on Cygwin but not MinGW. There is supposedly a port [here](http://www.softagalleria.net/download/dirent/), maybe you can look into it? Or it will just be defined out by autoconf.

Please test. I tested a little, seems to work like a champ.

**Comment by jfoug** [comment]
circleCI will tell us in a minute if this will build in MinGW

**Comment by jfoug** [comment]
I think we can close this. It is now doing all we wanted (with exception of reloading the .pots, but we sort of put that idea out to pasture).

Builds on both VC and MinGW with no problems, but they do not get directory loaded logic. Builds and runs fine on Cygwin (which has dirent.)

I am not overly worried about this logic not being in mingw/VC.  There are few using those (I probably am it for VC, and I only use it to develop/debug).  Mingw 'might' not be bad to get a dirent, if they want to use that tool for johnny, but I still think a cygwin build is better for johnny.

**Comment by jfoug** [comment]
NOTE, I could do dirent port (in macros and stub functions) for Win32 (VC) easily.  Same type stuff, other than the functions used. 

```
DIR        ->  WIN32_FIND_DATA
opendir()  ->  FindFirstFile()
readdir()  ->  FindNextFile()
closedir() ->  FindClose()
```

There is some controlling logic that would be different, but it is almost the same.  Very trivial stuff.

**Comment by jfoug** [comment]
This port is done.   No need for some dirent 'wrapper' code. This loop is so trivial it only took a couple minutes to port.  Not worth the time to try to incorporate that wrapper stuff, changing configure, etc. 

https://github.com/magnumripper/JohnTheRipper/commit/1ba091e34553023d315742ffe8124150c08a662f
https://github.com/magnumripper/JohnTheRipper/commit/2154f50dacd564e210ba1bb9c467e6ddfc006538

**Comment by magnumripper** [comment]
We need to unify behavior: I guess I'll give in, we should change directory mode to only consider files ending in `.pot`.
