### ISSUE TITLE
kwallet2john reports unknown version for Kubuntu 15.04

### ISSUE THREAD

**Issue by yoshimo** [magnumripper/JohnTheRipper#1626]
Kubuntu 15.04 is using a kwallet manager that was ported to the new kde frameworks 5.
kwallet2john can't read that new file format yet.

**Comment by kholia** [comment]
http://osdir.com/ml/kde-commits/2015-02/msg03331.html

**Comment by kholia** [comment]
We get a sightly better output message now with https://github.com/magnumripper/JohnTheRipper/commit/e1c8bdd4c4414742931079ecf22929b8a498d9ef.

@magnumripper this ticket can be fully done after jumbo-2, I think.
