### ISSUE TITLE
Create more test vectors

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1637]
There are 13 formats only have **one** test vector.
- [x] agilekeychain
- [x]  Blackberry-ES10
- [x]  cloudkeychain
- [x]  dmd5
- [ ] fde
- [x]  keystore
- [x]  lp
- [x]  LUKS
- [x]  OpenBSD-SoftRAID
- [x] \* Oracle12C
- [x]  pomelo
- [x]  Raw-SHA3
- [x]  Stribog-512

Since we want to detect FMT_\* flag errors, so there should be more test vectors.

magnum said:

> Actually there are a lot of formats that lack appropriate test vectors. All formats should test its own max. length, a null string (if applicable) and other random words of various length. 8-bit formats should also have some 8-bit test vector.

Solar said:

> some lack proper test vectors - some have just one correct password, some even test empty string only.

**Comment by jfoug** [comment]
@loverszhaokai are you working on getting these?

**Comment by loverszhaokai** [comment]
@jfoug  Yes, but not finished.

**Comment by kholia** [comment]
This is almost done. It is super hard to get extra test vectors for `fde` and `dmd5` formats. I will close this bug if we can't find the required test vectors in a reasonable amount of time.

**Comment by kholia** [comment]
The `dmd5` format will soon have additional test vectors.

**Comment by kholia** [comment]
It is hard to get test vectors for the `fde` format. I don't even remember how it works ;(

I am closing this ticket as it is 99% done.
