### ISSUE TITLE
The "grace time" for --max-run-time should be a john.conf option

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1638]
I think it is a good thing to have for GPU formats where a single call to crypt_all takes very long, and you want to make sure you interrupt the session when you don't loose much work.
For CPU formats, --max-run-time will be OK in most cases, but for OpenCL formats which process a huge number of candidates per crypt_all() call, you risk wasting much time if you interrupt at the wrong time.
With that option, you could try several attacks, and then (in a loop) restore the most successful sessions...

**Comment by magnumripper** [comment]
Any naive implementation of this risk harming performance. So some finesse is needed here.

**Comment by frank-dittrich** [comment]
A naive implementation being one check after every crypt_all() call? That could harm fast CPU formats with a small MAX_KEYS_PER_CRYPT, not sure how much, though. But is there an alternative to test this?
An even more naive implementation would do two checks (check whether the options is set, then check whether the number of crypt_all() calls has been reached).

The alternative would be to allow exceeding the run time specified by --max-run-time=n even if that should take an hour (until the GPU finishes the current block).

**Comment by magnumripper** [comment]
After every call to crypt_all() we'd either have to increment a new counter (adding a little overhead) or do something with an existing counter (likely adding more overhead, due to a division).

We could add some alternative like `-max-run-time-soft` that always waits until a completion of crypt_all(). And perhaps also all salts?

**Comment by frank-dittrich** [comment]
Yes. I am looking wor a way to do some work without causing unnecessary duplicate effort when restoring; --max-run-time-soft would be perfect.
And yes, actually I want all salts being processed before the current session stops.

**Comment by frank-dittrich** [comment]
I guess that for a hybrid --mask session, not all duplicate effort can be avoided, because the .rec file only records progress of the main cracking mode, is that right?

**Comment by magnumripper** [comment]
Yes. Even some core modes of operation have that simplification iirc.

**Comment by magnumripper** [comment]
The current "grace time" for --max-run=N is 30 seconds. After that, it aborts another time (similar to pressing ctrl-c a second time) so will abort abruptly.

How about we simply move the "30 seconds" to a john.conf option? Setting it to -1 would allow it to complete the batch, and (I think) all salts, no matter how slow.

**Comment by frank-dittrich** [comment]
Before you implement this as an option, try if it works with hard coding -1. I am not convinced.
But if -1 works, such an option would be great.

**Comment by magnumripper** [comment]
>> I guess that for a hybrid --mask session, not all duplicate effort can be avoided, because the .rec file only records progress of the main cracking mode, is that right?

> Yes. Even some core modes of operation have that simplification iirc.

I think the current hybrid mask duplicates very little effort [unless aborted hard]. Actually I think only some External modes are bad at resuming (well some can't even resume but you get a warning about it).

**Comment by magnumripper** [comment]
> Before you implement this as an option, try if it works with hard coding -1. I am not convinced.
But if -1 works, such an option would be great.

There are different code paths depending on OS_TIMER so we probably need to add logic translating -1 into MAX_INT or whatever is needed. We'd have 0 (zero) mean "hard abort immediately" as well. No grace time at all.

**Comment by frank-dittrich** [comment]
OK, now I get it. Good idea!
