### ISSUE TITLE
Fork issue  (multiple same words found)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1643]
I know this was reported on the email list, and we found 'explanations', and kind of ignored the warning.

However, I have a input file that is 100% lower cased and unique.  I am running with fork=8, and getting all sorts of same items found. To me, it looks like fork is either sending the same passwords to multiple threads, or something way wrong is happening. If this a PEBCAK, then I apologize up front, but I do not think so.

This is a rules based search.  

Here is a list of rules (partial)
```
[List.Rules:utf8-insert-everywhere]
!?LlcA[0z1-9AB]'Я'
!?LlcA[0z1-9AB]'â'
!?LlcA[0z1-9AB]'ä'
!?LlcA[0z1-9AB]'à'
...
```

```
$ run/john -rules=utf8-insert-everywhere -inp=utf-8 -inter=utf-8 -w=RockYou-lc-u.txt -pot=pw-all.pot -ses=xxyz orig/pro-hashes.1.txt -form=nt -fork=6
Loaded 24136 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Remaining 24058 password hashes with no different salts
Node numbers 1-6 of 6 (fork)
Press 'q' or Ctrl-C to abort, almost any other key for status
España           (?)
Password|        (?)
Andricks|        (?)
Passwo|rd        (?)
Pass|word        (?)
Passw|ord        (?)
Password|        (?)
Andricks|        (?)
Password|        (?)
Password|        (?)
Password|        (?)
Andricks|        (?)
Andricks|        (?)
Andricks|        (?)
Javé             (?)
Iléana           (?)
Suécia           (?)
Aidés            (?)
Kélian           (?)
Javé             (?)
Javé             (?)
Adély            (?)
Javé             (?)
Javé             (?)
Javé             (?)
Poêles           (?)
Noëlla           (?)
Uèni             (?)
Nièce            (?)
Planète          (?)
Promaèe          (?)
Chopí            (?)
Chopí            (?)
Chopí            (?)
Chopí            (?)
Chopí            (?)
Turíbio          (?)
Chopí            (?)
Thaïny           (?)
Maïarky          (?)
Keìra            (?)
Carloß           (?)
Strauß           (?)
Fußballgott      (?)
Carloß           (?)
Carloß           (?)
Carloß           (?)
Carloß           (?)
Strauß           (?)
Carloß           (?)
Strauß           (?)
Strauß           (?)
Strauß           (?)
Strauß           (?)
...
```

**Comment by frank-dittrich** [comment]
Can you enable logging of cracked passwords in john.conf and run with --mkpc=1?
Then you should see which rule id processed by which process when a password is found.

**Comment by frank-dittrich** [comment]
No: A8"ß", A9"ß" and Az"ß" will all append if your word is shorter.

You have to refine your rules.

**Comment by frank-dittrich** [comment]
>[0-9A-Za-z]A\p\0"ß"

**Comment by jfoug** [comment]
You are right, PEBCAK.

**Comment by jfoug** [comment]
All of the dupes are the last letter.

**Comment by jfoug** [comment]
>  ```>[0-9A-Za-z]A\p\0"ß"```

That will ONLY put a character in the 2nd to last location (insert prior to last char).  I also tried with the underscore char (for exact equal to length). That appended (only) the character.

I have also tried a range, and that fails with invalid position code:

```_[0-9A-Za-z]A[0-\p\0]"ß"   and also _[0-9A-Za-z]A[0-\0]"ß"```  Neither work.  Any help would be appreciated.

**Comment by frank-dittrich** [comment]
Unfortunalely, you need to do this separately.
For a single character, you'd do
```
<*$[abc123]
^[abc123]
>[1-9A-Za-y]i\p\1[abc123]
```
I used `\p\1` here. As long as there are no other ranges, first (`\1`) and previous (`\0`) range are the same. 
Since rules don't recognize 'ß' as a single character, the annoying workarounds are necessary. 
<*Az"ß"
A0"ß"
>[0-9A-Za-y]\A\p\1"ß"

Or, instead of 
```
/a saä
```
/a DpAp"ä"
```

Something that hopefully will no longer be needed once --rules support char size >1 byte.

**Comment by frank-dittrich** [comment]
Or convince Jan to finally fix the memleaks in rexgen.

**Comment by jfoug** [comment]
Or right a much better rexgen myself.
