### ISSUE TITLE
Wordlist + Rules + Hybrid Mask mode producing wrong candidates

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1648]
I saw this with descrypt, now simulating with --stdout=8

```
[List.Rules:c_lt13]
-c <D c Q M u Q c
```

```
./john  --wordlist=facebook-firstnames.txt --stdout=8 --rules=c_lt13 --mask='?w[13][37]' | LC_ALL=C grep -a -C 3 -n -v "[13][37]$" |head -n 20
1:Michael1
2:Michael3
3-John13
4-John33
5-John17
--
32-Robert33
33-Robert17
34-Robert37
35:Jessica1
36:Jessica3
37-Sarah13
38-Sarah33
39-Sarah17
40-Sarah37
41:Jennifer
42:Paul##
43:Brian##
44:Kevin##
45-Daniel13
```
Lines 1, 2, 35, 36, 41 are OK (cut to length 8).
Lines 42-44 are not.

The next such issue appears here:
```
61:Michelle
62:Steve##
63:Lisa##
64:Alex##
65:Joe##
```

Looks like when --stdout (or the format specific max length) reduce the length of the generated candidate, mask mode will produce wrong candidates for the next input words (due to dupes suppression, I am not sure how many candidates --mask produces.

**Comment by magnumripper** [comment]
@Sayantan2048 do you have a idea where to look?

**Comment by Sayantan2048** [comment]
Sorry, I missed the notification earlier. I'll look into it.

**Comment by Sayantan2048** [comment]
First of all mask mode shouldn't be fed with words of size > (max-length - mask_add_len). If we do so, mask mode will produce varied number of candidates each time it is called with base words of different length. 

I just fixed a bug, where base words of size > (max-length - mask_add_len) would cause segfault. But such words I guess shouldn't even reach mask mode.

Second, I can't replicate the above issue at all. I ended up fixing some other bugs though!!

**Comment by magnumripper** [comment]
> mask mode shouldn't be fed with words of size > (max-length - mask_add_len)

We have code in many places that ensures this. Maybe it's missing in some situation. Here's some susceptible code in wordlist.c
```c
   550          length = db->format->params.plaintext_length - mask_add_len;
   551          if (mask_num_qw > 1)
   552                  length /= mask_num_qw;
   553          if (maxlength && maxlength < length)
   554                  length = maxlength;
(...)
   984                  /* rules.c honors -min/max-len options on its own */
   985                  rules_init(pers_opts.internal_enc == pers_opts.target_enc ?
   986                             length : db->format->params.plaintext_length);
```
Looks like we're doing it wrong when using an internal encoding. I will investigate further.

**Comment by magnumripper** [comment]
> I can't replicate the above issue at all.

That is likely because we changed the default for internal encoding in 02586d1. Try running with `--internal-enc=latin1`

This is probably a correct fix:
```diff
diff --git a/src/wordlist.c b/src/wordlist.c
index 4a4254e..84f6ccf 100644
--- a/src/wordlist.c
+++ b/src/wordlist.c
@@ -531,6 +531,7 @@ void do_wordlist_crack(struct db_main *db, char *name, int rules)
 	int maxlength = options.force_maxlength;
 	int minlength = (options.req_minlength >= 0) ?
 		options.req_minlength : 0;
+	int rules_length;
 #if HAVE_REXGEN
 	char *regex_alpha = 0;
 	int regex_case = 0;
@@ -550,6 +551,10 @@ void do_wordlist_crack(struct db_main *db, char *name, int rules)
 	length = db->format->params.plaintext_length - mask_add_len;
 	if (mask_num_qw > 1)
 		length /= mask_num_qw;
+
+	/* rules.c honors -min/max-len options on its own */
+	rules_length = length;
+
 	if (maxlength && maxlength < length)
 		length = maxlength;
 
@@ -981,9 +986,7 @@ REDO_AFTER_LMLOOP:
 			error();
 		}
 
-		/* rules.c honors -min/max-len options on its own */
-		rules_init(pers_opts.internal_enc == pers_opts.target_enc ?
-		           length : db->format->params.plaintext_length);
+		rules_init(rules_length);
 		rule_count = rules_count(&ctx, -1);
 
 		if (do_lmloop || !db->plaintexts->head)
```
I'll try to reproduce with and without this patch.

**Comment by magnumripper** [comment]
Yeah that was it.
