### ISSUE TITLE
Message "Compiler error in %s at line %d: %s\n" with wrong fle name.

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1650]
When an external mode (either filter or standalone) has syntax errors, the error message prints the correct line number, but not the correct file name, if the external mode is defined in an included config file.

**Comment by jfoug** [comment]
I will look at this.  I thought I worked on this problem when originally getting the include crap to work.  I thought I fixed it, but it may be that I could not get it fixed.

**Comment by magnumripper** [comment]
Yes I was going to say IIRC this was fixed but for some other issue (like rules errors). So it's probably just some replicating of whatever fix **that** was, into external.c or something.

**Comment by jfoug** [comment]
I bet you are right. I may have ONLY been fixed in rules.

**Comment by jfoug** [comment]
Simple fix.  The code was just using the wrong file name.
