### ISSUE TITLE
CircleCI spurious failures

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1652]
There have been quite a few.  Some are due to my recent multi building, where I am installing components, and the Fedora install times out. We could fix them, by having the image up to date, so it can build 64 AND 32 bit. But not all failures are like that.

Here is an example:

https://circleci.com/gh/magnumripper/JohnTheRipper/641

Since @kholia owns the fedora image, to get it updated may require him to do so.  But we also need to figure out how best to address some of these other spurious failures.

**Comment by jfoug** [comment]
We are getting the same error again. There is something wrong with the CI setup.

**Comment by kholia** [comment]
@jfoug I just updated the image, and also installed the various i686 packages. Hopefully, the builds will be more stable now.

**Comment by magnumripper** [comment]
I got a failure after that.

**Comment by kholia** [comment]
@magnumripper do we know what exactly fails?

**Comment by frank-dittrich** [comment]
```
  adding: README-jumbo (deflated 45%)
wine: created the configuration directory '/root/.wine'
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
wine: configuration in '/root/.wine' has been updated.
==lxc-start: lxc_start.c: main: 342 The container failed to start.

docker run --name fedora -v /home/ubuntu:/base -i -t dhiru/fedora /base/JohnTheRipper/src/CircleCI-MinGW.sh returned exit code 1

lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options. Action failed: docker run --name fedora -v /home/ubuntu:/base -i -t dhiru/fedora /base/JohnTheRipper/src/CircleCI-MinGW.sh
```

**Comment by kholia** [comment]
It seems that I will need to SSH into the CircleCI box itself.

**Comment by kholia** [comment]
I have reached out to CircleCI support (I can't make much sense of that error message myself).

**Comment by jfoug** [comment]
I do not fully understand the setup you did with docker, but is there any external servers being accessed for these images (i.e. scp to somewhere)?  I know that it is often in the external site communications that we see failures. This is why the mingw stuff was sporadically failing. It would work most of the time, but then it would have a timeout downloading some package, and thus not be able to build, link or run something.  It wasn't that the code was bad, just that building the framework of the server failed.  Since we are using an external script as a single point of testing, the CI has no choice other than to say the run failed.

I wonder if we can work around a lot of this by updating the script to be a little more bullet proof?  I think the updates were happening within the script.

Now, I know the problem we are seeing now is not part of the script run (I think), but in the CI setup code (trying to get the image docked.)

Hopefully CI support can point out the problems.

**Comment by kholia** [comment]
See https://github.com/kholia/JohnTheRipper/commits/CircleCI-stability-fixes for my approach to fixing this stuff.

With those changes, I get the following errors in the build process,

```
******************************************************************************
now testing a NON-SIMD build
******************************************************************************

checking build system type... x86_64-unknown-linux-gnu
...
configure: Testing build host's native CPU features
checking for MMX... yes
checking for SSE2... no
checking for arch.h alternative... x86-64.h
checking whether compiler understands -march=native... yes
checking for 32/64 bit... 64-bit
checking for extra ASFLAGS... None needed
checking for X32 ABI... no
checking for byte ordering according to target triple... little
checking for OPENSSL... no
configure: error: in `/base/JohnTheRipper/src':
configure: error: JtR requires OpenSSL and OpenSSL-devel being installed. Install if not installed.
Try using --disable-pkg-config and possibly helping configure find oSSL by providing hints in CFLAGS and LDFLAGS
See `config.log' for more details
lxc-start: lxc_start.c: main: 342 The container failed to start
```

We are much closer to fixing the real problem now, I think. Any hints?

**Comment by kholia** [comment]
https://github.com/magnumripper/JohnTheRipper/pull/1739 should help in fixing this.
