### ISSUE TITLE
Blockchain2john.py Invalid arguments.

### ISSUE THREAD

**Issue by whitj00** [magnumripper/JohnTheRipper#1653]
Using

Blockchain2john.py wallet.aes.json

It gives error:

Blockchain2john.py: Invalid argument provided

Again.. tried on windows and ubuntu.

Please help fix.

Edit: NVM, I just used an older version of blockchain2john.. which worked fine.

**Comment by magnumripper** [comment]
> I just used an older version of blockchain2john.. which worked fine.

That's interesting. So in this case, we're not lagging behind, rather the opposite :confused:

**Comment by kholia** [comment]
@whitj00  this should be fixed now,  can you please see if the latest version works for you?

**Comment by magnumripper** [comment]
OP failed to report back. Assuming fixed.
