### ISSUE TITLE
Descrypt loopback crash

### ISSUE THREAD

**Issue by richrumble** [magnumripper/JohnTheRipper#1654]
During CMIYC 2015, running -format=descrypt -loop, with or without rules caused a crash in my cygwin build and my linux build. I just cat'd the pot file to a wordlist and it worked. Mask mode worked fine, as well as external modes and incremental modes. Loop was the only issue, and it was only against descrypt I had the issue.
D:\john-1.8.0.5-jumbo-1-bleeding-cygwin_64>john.exe street.txt -format=descrypt -session=wiki -loop
Using default input encoding: UTF-8
Loaded 1385 password hashes with 1175 different salts (descrypt, traditional crypt(3) [DES 128/128 SSE2-16])
Remaining 1336 password hashes with 1138 different salts
Will run 4 OpenMP threads
      4 [main] john 16192 cygwin_exception::open_stackdumpfile: Dumping stack trace to john.exe.stackdump

Stackdump:===========================================
Exception: STATUS_ACCESS_VIOLATION at rip=001004073B2
rax=0000000000000008 rbx=000006FFFFD16CC0 rcx=000006FFFFD1BCC0
rdx=000006FFFFD184C0 rsi=000006FFFFD16CC0 rdi=0706050403020100
r8 =000006FFFFD1BC50 r9 =000006FFFFD1BB90 r10=0000000000000000
r11=0000000100773DC0 r12=F7F6F5F4F3F2F1F0 r13=2F2E2D2C2B2A2928
r14=2726252423222120 r15=000006FFFFD1BC60
rbp=000006FFFFD1BB80 rsp=000000000022C3D0
program=D:\john-1.8.0.5-jumbo-1-bleeding-cygwin_64\john.exe, pid 16192, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
6FFFFD1BB80  001004073B2 (0000022C82C, 00100000004, 00000000008, 006002826C0)
00000000008  003FC324312 (0007750BA3E, 00100635040, 006002826C0, 00100635040)
00000000008  0010040F896 (468EA92E00000006, 00000000005, 00100773DE4, 00000000001)
00000000008  0010040177E (00000610230, 000006103B8, 00000000041, 00000260230)
00000000008  001005C4E3E (00000000000, 00000000000, 00000000000, 00000000000)
0000022CBD0  001005CCFAF (00000000005, 0000022CB00, 00000000001, 00000000000)
0000022CBD0  001005CDB8F (0000022CB00, 0000022CBD0, 00000000001, 00000000000)
0000022CBD0  00180048551 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001800463EC (39003700380037, 00000000038, 00000000000, 0006C671ABE)
00000000000  00180046494 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100633C51 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000774D59CD (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007770B891 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

Not as much info from my linux build though...

Using default input encoding: UTF-8
Loaded 1385 password hashes with 1175 different salts (descrypt, traditional crypt(3) [DES 128/128 AVX-16])
Will run 24 OpenMP threads
Segmentation fault

------------build-info----------------
Version: 1.8.0.6-jumbo-1-647-gbf6e62e
Build: linux-gnu 64-bit AVX-ac OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.8.2
GNU libc version: 2.19 (loaded: 2.19)
Crypto library: OpenSSL
OpenSSL library version: 01000106f
OpenSSL 1.0.1f 6 Jan 2014
GMP library version: 5.1.3
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by magnumripper** [comment]
I can't reproduce. Can you? It might be some specific content in that pot file of yours that triggered it, or perhaps some specific content in your input file.

On Linux, you should run it in the debugger for a proper backtrace.

**Comment by magnumripper** [comment]
(I got some input OOB will look into it)

**Comment by magnumripper** [comment]
This is incredibly odd. First, the crash happens during fmt_self_test(), before any cracking mode code is executed. Nevertheless, it **only** happens with --loopback. For example, it doesn't happen with --wordlist... *what's the difference?!*

If I extract only the DES hashes from street.txt to a new file and use that instead, no crash. If I run with --skip-self-test, no crash.

**Comment by magnumripper** [comment]
OK it must be due to the hack in john.c:1104

**Comment by magnumripper** [comment]
Sure enough it's that little gem. But why? And why only in some cases?

**Comment by richrumble** [comment]
On Sun, Aug 16, 2015 at 4:40 PM, magnum <notifications@github.com> wrote:

> Sure enough it's that little gem. But why? And why only in some cases?
>
I wish I knew :) Sorry I only break all the things !)

**Comment by jfoug** [comment]
> (I got some input OOB, will look into it)

And this was??

**Comment by magnumripper** [comment]
I'll mail it to you. I think it was input files from CMIYC. I see nothing special with the hashes but the problem is only triggered with the file that contains a lot of formats in addition to the descrypt ones.

**Comment by richrumble** [comment]
Yes it was the Street team CMIYC hashes.
http://contest-2015.korelogic.com/downloads.html
-rich

**Comment by jfoug** [comment]
I will have a look at this tonite, and see if anything jumps out at me. IF I can replicate the problem with a VC build, it should not take more than a couple minutes to fix (I hope).  However, there are some things that simply do not trigger problems with VC (such as the gcc specific problems in the external compiler).

**Comment by magnumripper** [comment]
I just confirmed it happens with an empty (actually not existing) john.pot
```
$ ../run/john -form:descrypt street.txt -loop
Using default input encoding: UTF-8
Loaded 1385 password hashes with 1175 different salts (descrypt, traditional crypt(3) [DES 128/128 AVX-16])
Will run 8 OpenMP threads
Segmentation fault: 11
```
You really should be able to reproduce that. Same thing, using a file with **only** the (same) descrypt hashes:
```
$ ../run/john -form:descrypt des-hashes-from-street.txt -loop
Using default input encoding: UTF-8
Loaded 1385 password hashes with 1175 different salts (descrypt, traditional crypt(3) [DES 128/128 AVX-16])
Will run 8 OpenMP threads
Error, dictionary file is empty
```
No crash. If you have a non-empty john.pot, it will run a proper loopback instead of complaining about empty dictionary. Note that the same amount of hashes & salts was loaded (I verified it's the exact same net content).

**Comment by magnumripper** [comment]
...and if you disable the code in john.c:1104, the problem goes away. Somehow that thing messes with something in the format. For the life of me I can't see what/why.

**Comment by magnumripper** [comment]
Hm, wait... here's finally (perhaps) a clue: LM and DEScrypt does share some amount of code. Only DEScrypt has this problem... only LM is looked for while assembling halves...

**Comment by magnumripper** [comment]
BTW it's apparently john.c:1108 as of today :)

I guess in the unlikely event we never figure out what's causing this, we could just do
```diff
diff --git a/src/john.c b/src/john.c
index 8f27440..a243d5f 100644
--- a/src/john.c
+++ b/src/john.c
@@ -1109,7 +1109,7 @@ static void john_load(void)
           ldr_drop_database() after this, but it's built with mem_alloc_tiny()
           so it's not trivial. Works like a champ though. */
        if (options.flags & FLG_LOOPBACK_CHK &&
-           database.format != &fmt_LM) {
+           database.format != &fmt_LM && database.format != &fmt_DES) {
                struct db_main loop_db;
                struct fmt_main *save_list = fmt_list;
                char *save_pot = pers_opts.activepot;
```

...and actually we could even make it like this, because the normal case for this IRL is l0pthcrack format input
```
diff --git a/src/john.c b/src/john.c
index 8f27440..cba2db7 100644
--- a/src/john.c
+++ b/src/john.c
@@ -1109,7 +1109,9 @@ static void john_load(void)
           ldr_drop_database() after this, but it's built with mem_alloc_tiny()
           so it's not trivial. Works like a champ though. */
        if (options.flags & FLG_LOOPBACK_CHK &&
-           database.format != &fmt_LM) {
+           (!strcasecmp(database.format->params.label, "nt") ||
+            !strcasecmp(database.format->params.label, "nt-old") ||
+            !strcasecmp(database.format->params.label, "nt-opencl"))) {
                struct db_main loop_db;
                struct fmt_main *save_list = fmt_list;
                char *save_pot = pers_opts.activepot;
```

**Comment by jfoug** [comment]
Hmmm,

```
$ ../run/john -loop /c/Users/barb/Downloads/cmiyc-2015-street-hashes.tar_1_/street-hashes.5.txt  -form=descrypt
Using default input encoding: UTF-8
Loaded 1385 password hashes with 1175 different salts (descrypt, traditional crypt(3) [DES 128/128 XOP-16])
Warning: invalid UTF-8 seen reading $JOHN/john.pot
Warning: invalid UTF-8 seen reading $JOHN/john.pot
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
Füller           (?)
Øystein          (?)
2g 0:00:00:14 1.27% (ETA: 19:45:04) 0.1337g/s 4383p/s 5599Kc/s 6745KC/s PÇASSWO..ÈPaSSWO
Use the "--show" option to display all of the cracked passwords reliably
Session aborted
```

That was 'empty' .pot file, well there was a .pot, but it contained nothing from this list.

**Comment by jfoug** [comment]
I am also running XOP while you were running AVX code.  Not sure, of difference ,but ....

**Comment by magnumripper** [comment]
> That was 'empty' .pot file, well there was a .pot, but it contained nothing from this list.

**Anything** it contains will be used as candidates. The current loopback mode does two things:

1. Assemble LM halves to a list. This step *does* need the hashes to exist in your input file(s)
2. More or less the same as `cut -d: -f2 john.pot | unique`

You got stuff from step 2.

**Comment by magnumripper** [comment]
BTW I got the crash with OpenMP or not, and using ASan or not (but it isn't an "ASan crash", just a normal segfault for access violation).

**Comment by jfoug** [comment]
```
 $ ../run/john -loop /c/Users/barb/Downloads/cmiyc-2015-street-hashes.tar_1_/street-hashes.5.txt -pot=not-there.pot
Warning: detected hash type "descrypt", but the string is also recognized as "descrypt-opencl"
Use the "--format=descrypt-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1385 password hashes with 1175 different salts (descrypt, traditional crypt(3) [DES 128/128 XOP-16])
Device 0: Devastator [AMD Radeon HD 7640G]
Build log: ".\OCL8067.tmp.cl", line 165: warning: goto statement may cause irreducible
          control flow
                loop_body();
                ^

".\OCL8067.tmp.cl", line 167: warning: goto statement may cause irreducible
          control flow
                if (rounds_and_swapped > 0) goto start;
                                            ^

".\OCL8067.tmp.cl", line 171: warning: goto statement may cause irreducible
          control flow
                if (--iterations) goto swap;
                                  ^

".\OCL8067.tmp.cl", line 180: warning: goto statement may cause irreducible
          control flow
                if (--rounds_and_swapped) goto start;
                                          ^

".\OCL8067.tmp.cl", line 185: warning: goto statement may cause irreducible
          control flow
                goto start;
                ^


Will run 4 OpenMP threads
Error, dictionary file is empty
```

```
$ ../run/john -loop /c/Users/barb/Downloads/cmiyc-2015-street-hashes.tar_1_/street-hashes.5.txt -pot=not-there.pot -form=descrypt
Using default input encoding: UTF-8
Loaded 1385 password hashes with 1175 different salts (descrypt, traditional crypt(3) [DES 128/128 XOP-16])
Will run 4 OpenMP threads
Error, dictionary file is empty
```


Still no crash, even with a missing .pot file.  This is also under cygwin-64 build.

**Comment by jfoug** [comment]
Unfortunately, a VC debug build also does not crash.

**Comment by magnumripper** [comment]
But you are using a file containing only DEScrypt. As already stated, that doesn't crash for me either. Use street.txt from Rich that I forwarded to you (did you get it? It was fairly big).

Or concat all street-hashes.*.txt into a big street-hashes-all.txt and try that one, I guess Rich's file was pretty much made like that.

**Comment by jfoug** [comment]
Got it to crash with all streets cat'd into one file.  Now hopefully it will crash VC (I think it should).

**Comment by jfoug** [comment]
```
(gdb) bt
#0  0x0000000100407088 in _mm_xor_si128 (__B=..., __A=...)
    at /usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/emmintrin.h:1284
#1  DES_bs_crypt_25._omp_fn.0 () at DES_bs_b.c:1368
#2  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

Memory overwrite somewhere.  Need to focus on that part of john.c    I am heading off to work, so will look a bit when I get there, if you have not figured it out by then.  I am really surprised that ASAN is not trapping on the overwrite......

**Comment by magnumripper** [comment]
I'll just apply the workaround. But I really wonder exactly what happens.
