### ISSUE TITLE
Loopback very Slow + Opencl issue

### ISSUE THREAD

**Issue by denis0** [magnumripper/JohnTheRipper#1655]
Hi,

I have some issue with the "--loopback" option, where this process is very low on the last version of jtr ( 1.8.0.6 - Jumbo, it was the case since the 1.8.x versions..)

I make several's test already with different Algo's / ahshes lists, with & without salt, but the more speaking test is the one is going to follow.

More clearly, compared to the JTR 1.7.9 Version, where the run take only a few sec' !

but better to demo the cmd, the build, OS / system etc...

***********************************

System =  Macbook Pro 17' - I7 - SSD - Full of Ram -Mac_OSX Mavericks , 1.9.5

JTR tested = 

a/ fresh install of bleeding last verion from today / to be noted = no tweak for optimal install on the Mac , like ; Homebrew, GCC etc...just classic fresh install

b/ JTR Version 1.7.9 - Jumbo ( i keep it & continue to use this version regulary because on some Algo's is faster then the new 1.8.0.x version)

Hashes = Raw-md5 without salt & size around = 13 Mo

Old John.pot of around 500 Mo ( i read as well the new version of JTR is now full utf-8 & tis .pot file have to converted or recreated to better use....)

*************************

1/ ./configure && make

2/ done....cd to /run

3/ macbookpro:run xxx$ ./john --list=build-info

Version: 1.8.0.6-jumbo-1-bleeding
Build: darwin13.4.0 64-bit AVX-ac
SIMD: AVX, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
clang version: 6.0 (clang-600.0.57) (gcc 4.2.1 compatibility)
OpenCL library version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 0009081af	(loaded: 0009081df)
OpenSSL 0.9.8za 5 Jun 2014	(loaded: OpenSSL 0.9.8zd 8 Jan 2015)
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

*******************
4/ macbookpro:run xxxx$ ./john -form=raw-md5 --test
Benchmarking: Raw-MD5 [MD5 128/128 AVX 4x5]... DONE
Raw:	25132K c/s real, 24883K c/s virtual

******************

5/ ./cprepair -p john.pot > john2.pot

6/ macbookpro:run xxxx$ wc -l john.pot
 12397024 john.pot

macbookpro:run xxxx$ wc -l john2.pot
 12397024 john.pot

**************
7/ macbookpro:run xxx$ ls -lh john.pot
-rw-------@ 1 xxxxx  staff   487M  8 aoû 00:06 john.pot

macbookpro:run xxxxx$ ls -lh john3.pot
-rw-r--r--  1 xxxxx  staff   485M 12 aoû 18:38 john2.pot

********************************
8/ Hashes = raw-md5

macbookpro:run1 xxxx$ wc -l md.txt
  398065 md.txt

macbookpro:run1 xxxx$ ls -lh md.txt
-rwxr-xr-x  1 xxxxx  staff    13M  9 aoû 21:59 md.txt

***************************
TEST N°1

9/ macbookpro:run xxxxx$ ./john -form=raw-md5 --loopback md.txt
Using default input encoding: UTF-8
Loaded 398066 password hashes with no different salts (Raw-MD5 [MD5 128/128 AVX 4x5])
Remaining 377508 password hashes with no different salts

******

2350g 0:00:03:12 0.81% (ETA: 01:34:42) 12.17g/s 3118Kp/s 3118Kc/s 1176GC/s avoiKn4L..jaisHyaM

************

D/ Like you can see, it seem never end, or ended with an ETA super long ...after 3;:12 mn i am at only 0.81%

Where with the JTR VERSION 1.7.9 the same process take a fex sec' ! ( i demo below..)

****************************************************************
****************************************************************

On the same Machine , same OS, & JTR Version 1.7.9 - Jumbo

10/ macbookpro:run1 xxxx$ ./john -fo=raw-md5 --test
Benchmarking: Raw MD5 [128/128 SSE2 intrinsics 12x]... DONE
Raw:	28693K c/s real, 28693K c/s virtual

macbookpro:run1 xxx$ ./john --list=build-info
Version: 1.7.9-jumbo-7
Build: macosx-x86-64 OMP
Arch: 64-bit LE
$JOHN is ./
Format interface version: 9
Rec file version: REC3
Charset file version: CHR2
CHARSET_MIN: 32 (0x20)
CHARSET_MAX: 126 (0x7e)
CHARSET_LENGTH: 8
Max. Markov mode level: 400
Max. Markov mode password length: 30
Compiler version: 4.7.2
gcc version: 4.7.2
OpenSSL library version: 90812f	(loaded: 90818f)

**********************************
TEST N° 2

11/macbookpro:run1 xxxx$ ./john -fo=raw-md5 --loopback md.txt
Loaded 398066 password hashes with no different salts (Raw MD5 [128/128 SSE2 intrinsics 12x])
Remaining 377508 password hashes with no different salts
Loop-back mode: Reading candidates from pot file $JOHN/john.pot

……..
guesses: 1529  time: 0:00:00:04 DONE (Wed Aug 12 18:55:05 2015)  c/s: 807926M  trying: yorokobikin'niku - hazureruyasai
Use the "--show" option to display all of the cracked passwords reliably

Like you can see the same john.pot ( Around 500 Mo ) take 4 sec' to perform !

Any help to resolve that issue will be super welcome !

***********************************************************************

Thank you in advance for your help,

Denis

**Comment by magnumripper** [comment]
Current Jumbo defaults to using some rules for loopback (default aims to case-correct NT hashes from cracked LM ones). For the 1.8 test, try adding `--rules:none` and it too will probably take 4 seconds.

**Comment by magnumripper** [comment]
I see we missed documentation on that. Added now, thanks for reporting! Please close this issue if you don't have any follow-up issues.

**Comment by denis0** [comment]
Thank you Magnum, ok for the "--rules=none"....

What about the opencl issue ? or you prefer i opened a new post for that ?

2015-08-13 0:12 GMT+02:00 magnum <notifications@github.com>:

**Comment by frank-dittrich** [comment]
Just for LM hashes that change is crazy.

1. You would need to concatenate the first and second halves into one word and apply NT rules on the result.
2. You shouldn' use NT rules on any password that contains a lower case letter, since that password cannot be from an LM Hash...

**Comment by frank-dittrich** [comment]
And if you crack neither LM nor NT hashes, there are probably more interesting rules to try instead.

**Comment by frank-dittrich** [comment]
@denis0 Yes I think a separate issue for the opencl problem is better.

**Comment by denis0** [comment]
@frank-dittrich 

Thank you for the tips about LM & well done for the second issue, i opened a new thread then.

**Comment by magnumripper** [comment]
I can't even spot any opencl issue in the original wall of text :sunglasses:

**Comment by denis0** [comment]
@magnumripper 

I follow the Frank Advices & open a new thread about, by the way i edit my frist post & copy/past on the new one here => https://github.com/magnumripper/JohnTheRipper/issues/1657


***************

Beside, how you close a topic ?

**Comment by magnumripper** [comment]
I closed it :-)

**Comment by frank-dittrich** [comment]
Actually, I'd like to discuss loopback default rules on john-dev and/or john-users (hoping for more support for my point of view) before closing this issue.
I think many people are unaware of running tons of more or less useless rules with --loopback.

**Comment by magnumripper** [comment]
@frank-dittrich

The NT case-correct rules have a rule-reject flag `-c` that will disable them for LM. So for NT -> LM loopback, there is only one single rule: the truncation one.

Likewise, the LM split rule have a rule-reject flag `-s` so it will ONLY affect formats that splits the hashes into two.

**Comment by magnumripper** [comment]
> You would need to concatenate the first and second halves into one word and apply NT rules on the result.

The --loopback mode does just that (before the naive loopback), when applicable. It didn't in 1.7.9-jumbo-7 but it does since over a year ago.

**Comment by magnumripper** [comment]
Here's a snippet from doc/ENCODINGS
```
Example using the now default john.conf settings:

   $ ../run/john hashfile -form:lm -single
   Using default input encoding: UTF-8
   Target encoding: CP850
   Loaded 3 password hashes with no different salts (LM [DES 128/128 AVX-16])
   Press 'q' or Ctrl-C to abort, almost any other key for status
   GEN              (Kübelwagen:2)
   KÜBELWA          (Kübelwagen:1)
   MÜLLER           (Müller)
   3g 0:00:00:00 DONE (2014-03-28 20:48) 300.0g/s 12800p/s 12800c/s 38400C/s
   Warning: passwords printed above might be partial
   Use the "--show" option to display all of the cracked passwords reliably
   Session completed

   $ ../run/john hashfile -form:nt -loopback
   Rules engine using CP850 for Unicode
   Loaded 2 password hashes with no different salts (NT [MD4 128/128 SSE2-16])
   Assembling cracked LM halves for loopback
   Loop-back mode: Reading candidates from pot file $JOHN/john.pot
   Press 'q' or Ctrl-C to abort, almost any other key for status
   Kübelwagen       (Kübelwagen)
   müller           (Müller)
   2g 0:00:00:00 DONE (2014-03-28 20:48) 200.0g/s 3200p/s 3200c/s 6400C/s
   Use the "--show" option to display all of the cracked passwords reliably
   Session completed
```
The default rules are made for this being a no-brainer.

**Comment by magnumripper** [comment]
So what remains of your doubts is this: Using loopback (even when LM and NT is not involved) will default to a case-toggling rule that is rather costly (while otherwise not bad at all) for slow hashes. It was bad that it wasn't documented (now corrected) but otherwise it's not a very bad thing. I'll leave it open though, I'm open for discussion here or on ML.

**Comment by frank-dittrich** [comment]
I'll self-assign, to be reminded of bringing this up on john-users.

**Comment by magnumripper** [comment]
@frank-dittrich can we close this?

**Comment by frank-dittrich** [comment]
@magnumripper I don't mind.
