### ISSUE TITLE
4 byte utf8 issues

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1658]
As seen in comments in this commit:  https://github.com/magnumripper/JohnTheRipper/commit/91bd304258c4edfda84fc89c77d1e586e7bb6e59#commitcomment-12680110   There are formats which appear to not be properly handling Unicode characters which require 4 or more bytes of utf8 to represent.

So, we need to get some of this data into the jtrts input files (for unicode formats).   We also need to get test hashes inside the Unicode formats that use these characters when a run is done with target encoding of utf-8

**Comment by magnumripper** [comment]
But this is (first) a TS issue, not JtR.

BTW I find it strange that TS doesn't check EVERY length from 0 up to max. length for every format. We jump randomly from 12 to 17 to 24 while a format might have a max. of 15. That sure is room for improvement.

**Comment by jfoug** [comment]
Part of that 'randomness' was to cause overflows.  Early stuff did do incremental length gain, and I was having runs that did not expose overflows. Once I went to random orders, the crashes and 'missed' cracks that are the symptoms of overwrite.

I put this as an issue for JtR, so that we can get test strings into formats.  Better to have them self test fail, than to have changes made that cause false positives or false negatives that happen to not get tested in the TS. Yes, this is also something that the TS needs to have added.

**Comment by magnumripper** [comment]
I'm not talking about random order, I'm talking about "random" lengths being tested. A **lot** of lengths are not tested at all. 
```
$ LC_ALL=C ./pw_len_finder.sh episerver_sha256_tst.in 
num	len	sum
1	0	1
3	1	4
16	4	20
16	5	36
14	6	50
41	7	91
97	8	188
200	9	388
218	10	606
212	11	818
232	12	1050
181	13	1231
120	14	1351
79	15	1430
38	16	1468
8	17	1476
2	21	1478
14	24	1492
8	25	1500
```
We're not testing length 23, 22, 20, 19, 18. This is just an example. For some (I think many) formats, this currently means we are not testing max length at all.

**Comment by jfoug** [comment]
Yes, that was with pw.dic   Look at one using pw-new.dic   I have known (and have issues to replace) pw.dic has problems.

**Comment by magnumripper** [comment]
Are we using both? Why?

**Comment by magnumripper** [comment]
IMHO we should have one (1) pw.dic and it should be proper UTF-8. It should contain all lengths and characters from all supported codepages. It should contain 2, 3 and 4-byte multibyte UTF-8 stuff. And, like today, it should contain many oversized lines.

Then, for eg CP850, jtrts.pl should make a temp dict file from that one, filtering out any characters that can't be written in CP850. Obviously the fmt_tst_cp850.in should be created by the same "algorithm".

**Comment by magnumripper** [comment]
I removed the bug label from this issue since there's no known bug - just a need for more testing.
