### ISSUE TITLE
New --test-full option behaves differently than --test

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1659]
```
$ ../run/john -test -form:nt
Benchmarking: NT [MD4 128/128 AVX 4x3]... DONE
Raw:	49188K c/s real, 49680K c/s virtual

$ ../run/john -test -form:nt -enc:utf8
Benchmarking: NT [MD4 128/128 AVX 4x3] in UTF-8 mode... DONE
Raw:	40924K c/s real, 40518K c/s virtual

$ ../run/john --test-full -form:nt
Benchmarking: NT [MD4 128/128 AVX 4x3] in UTF-8 mode... DONE
Raw:	40718K c/s real, 40718K c/s virtual
```
As seen above, using --test, we do NOT honor the john.conf option of defaulting to UTF-8. That one is only for real crack runs, not test. The `--test-full` option should behave the same way, to avoid confusion.

See john.c line 816

**Comment by magnumripper** [comment]
BTW sapG and luks formats also has tests for FLG_TEST_CHK that currently does not test FLG_TEST_FULL_CHK

**Comment by magnumripper** [comment]
@loverszhaokai did you see this issue?

**Comment by loverszhaokai** [comment]
@magnumripper  Sorry. I will solve this issue.
