### ISSUE TITLE
John outputs No password hashes loaded (see FAQ)

### ISSUE THREAD

**Issue by Yanpas** [magnumripper/JohnTheRipper#1660]
Followed this tutorial and got an error. I enter command `john out.txt`, where out.txx is:
`x.docx:$office$*2007*20*128*16*751dc7e002837fda2c68a580b7890f26*3753714098407532be0f60cbf97e9fcd*392a30898d6775dda2e2a32b0eb807167f888ace`

To generate hashes I used https://github.com/magnumripper/JohnTheRipper/blob/unstable-jumbo/run/office2john.py

John version 1.8.0-1

**Comment by magnumripper** [comment]
Did you use a Jumbo version of john? "1.8.0-1" sounds like non-jumbo to me.

**Comment by Yanpas** [comment]
I'm not sure which version do I use, it is version from ubuntu repos. I think this patch only can parse specific format, classic version is able to decipher my hash too, isn't it? I should only rename the string

**Comment by frank-dittrich** [comment]
@Yanpas what is the output of
```john```
(with no additional parameters?)

But I guess magnum is right and ubuntu provides a non-jumbo version.

**Comment by Yanpas** [comment]
Output
```
$ john
John the Ripper password cracker, version 1.8.0
Copyright (c) 1996-2013 by Solar Designer
Homepage: http://www.openwall.com/john/

Usage: john [OPTIONS] [PASSWORD-FILES]
--single                   "single crack" mode
--wordlist=FILE --stdin    wordlist mode, read words from FILE or stdin
--rules                    enable word mangling rules for wordlist mode
--incremental[=MODE]       "incremental" mode [using section MODE]
--external=MODE            external mode or word filter
--stdout[=LENGTH]          just output candidate passwords [cut at LENGTH]
--restore[=NAME]           restore an interrupted session [called NAME]
--session=NAME             give a new session the NAME
--status[=NAME]            print status of a session [called NAME]
--make-charset=FILE        make a charset, FILE will be overwritten
--show                     show cracked passwords
--test[=TIME]              run tests and benchmarks for TIME seconds each
--users=[-]LOGIN|UID[,..]  [do not] load this (these) user(s) only
--groups=[-]GID[,..]       load users [not] of this (these) group(s) only
--shells=[-]SHELL[,..]     load users with[out] this (these) shell(s) only
--salts=[-]N               load salts with[out] at least N passwords only
--save-memory=LEVEL        enable memory saving, at LEVEL 1..3
--node=MIN[-MAX]/TOTAL     this node's number range out of TOTAL count
--fork=N                   fork N processes
--format=NAME              force hash type NAME: descrypt/bsdicrypt/md5crypt/
                           bcrypt/LM/AFS/tripcode/dummy/crypt
```

**Comment by magnumripper** [comment]
That is a non-Jumbo and has no support for Office (or most anything else)

**Comment by frank-dittrich** [comment]
@Yanpas ubuntu should have a version of john's doc/FAQ installed.

One of the possible answers to your question in that FAQ is
```
A: Your password hash or cipher type(s) might not be supported by John,
or at least by the version and build of John that you're using.  If
you're using a non-jumbo version, you will likely want to try -jumbo
instead, which supports a lot of additional hash and cipher types
```

**Comment by ryuzakyl** [comment]
A good tutorial for installing a Jumbo version on Ubuntu is [this one](https://linuxreference.wordpress.com/2019/06/07/howto-install-john-the-ripper-in-ubuntu-18-04/).

Hope it helps.

**Comment by solardiz** [comment]
Good tutorials should be added to https://openwall.info/wiki/john/tutorials. Unfortunately, the one mentioned by @ryuzakyl shows confusion on behalf of its author. It includes several unneeded and dangerous things (installs some unneeded packages, builds the source code as root), and results in a setup that isn't entirely correct (is neither user-local nor system-wide, but is a broken mix of both) and would have issues in actual use (beyond `--test`).

**Comment by ndurand1** [comment]
There is a snap package "john-the-ripper" that installs the jumbo version 1.9. Also, make sure that your hash file includes a username followed by a colon (i.e. root:<hash>) so that john recognizes it as a password!

**Comment by ghost** [comment]
@ndurand1, since you edited your post, I guess you found what was missing in you input file (so JtR is now able to recognize it as a valid hash).

**Comment by solardiz** [comment]
@ndurand1 edited the comment to say: "make sure that your hash file includes a username followed by a colon (i.e. root:) so that john recognizes it as a password!"

While I'm happy that presumably things somehow worked, that addition of "username followed by a colon" thing shouldn't be necessary for non-ancient versions of JtR like 1.8 or 1.9 (specifically, it was only needed prior to 1.7.6), and there was probably some other issue and some other change that helped.

I am posting this for others who might come across this issue (presumably by googling the error message instead of literally seeing the [FAQ](https://www.openwall.com/john/doc/FAQ.shtml)), so that they're not confused by the wrong advice. There are plenty of reasons why that catch-all error message might appear, but missing username isn't one of those.

**Comment by aiy2002** [comment]
> There is a snap package "john-the-ripper" that installs the jumbo version 1.9. Also, make sure that your hash file includes a username followed by a colon (i.e. root:) so that john recognizes it as a password!

@ndurand1 Where did you find the snap package?

**Comment by ndurand1** [comment]
> > There is a snap package "john-the-ripper" that installs the jumbo version 1.9. Also, make sure that your hash file includes a username followed by a colon (i.e. root:) so that john recognizes it as a password!
> 
> @ndurand1 Where did you find the snap package?

`snap info john-the-ripper`

**Comment by ghost** [comment]
> Where did you find the snap package?

If you are already using Ubuntu, just type `sudo snap install john-the-ripper` (or via Ubuntu Sofware). If you need to enable snap support in your distro, read https://github.com/openwall/john-packages#snap

* the package is in the official repo
![Captura de tela de 2020-12-28 20-01-59](https://user-images.githubusercontent.com/1702923/103247999-a6826080-4947-11eb-948d-58dce314fec0.png)

**Comment by aiy2002** [comment]
After downloading John The Ripper through the Ubuntu Software store I set up a mysql root in Vim, and when I type the command john hashes ( hashes being what I named the vim file), I still receive the error "No password hashes loaded (see FAQ)." I'm not sure if it is still downloading an outdated file of JTR for some reason. @claudioandre-br

**Comment by magnumripper** [comment]
@aiy2002 what's the output of `which john`?

**Comment by solardiz** [comment]
> when I type the command john hashes

As @magnumripper guessed, the command `john` probably invokes another build of JtR, not what came from the snap package. To invoke the snap package's build, the command is `john-the-ripper`. See examples in:

https://github.com/openwall/john-packages#snap

Yes, this is weird. @claudioandre-br Can you come up with any way to make this more intuitive?

**Comment by ghost** [comment]
You can also use `john` to run the snap package (main) binary. In my machine `/snap/bin` is the last directory in `$PATH`. Anyone can change that permanently, of course.

BTW: `john` is a global alias I had to request (the name was not available).

**Comment by ghost** [comment]
@aiy2002, (using snap or not) you can still get version, build date, ... E.g., `john --list=build-info` (after you run `which john`).

**Comment by aadesunloro** [comment]
<img width="505" alt="error message on johnny" 

> src="htt
<img width="505" alt="error message on johnny" src="https://user-images.githubusercontent.com/70285271/109430762-8e22d680-79c8-11eb-8772-097b912dcab0.PNG">
ps://user-images.githubusercontent.com/70285271/109430725-6af82700-79c8-11eb-8b05-8e2369981564.PNG">[](url)

Please, how do I correct "No hashes loaded[format=], see console log.

Kindly advise ASAP!

**Comment by solardiz** [comment]
@aadesunloro We don't provide user support in the manner you seem to expect, and normally not on GitHub at all. We do provide friendly community discussions on the [john-users mailing list](https://www.openwall.com/lists/john-users/), but for that you got to be comfortable describing things in pure text (no screenshots) and communicating via e-mail that gets published for everyone else to read and benefit from. Also, to ask a reasonable question you have to start by explaining what you're trying to do and why, and to know half the answer. Finally, you shouldn't expect answers "ASAP".

Your screenshot and brief question that you posted in here do not have just one possible answer. Several answers are given in the corresponding [FAQ](https://www.openwall.com/john/doc/FAQ.shtml) entry, although they don't consider possible specifics of Johnny the GUI.

**Comment by lindhe** [comment]
> There is a snap package "john-the-ripper" that installs the jumbo version 1.9.

Just a heads-up that the `john-the-ripper` package on Snap is not published by a verified publisher (claims to be "Claudio André (claudioandre-br)"), so it's hard to know if it runs trustworthy software on your computer if you install it.

**Comment by ghost** [comment]
It does not claim to be me, it is me. Well actually you can read all the logs and the logs include all the tasks done during the build including the `git clone` of this repository (the build happens in Lauchpad, only the build recipe exist there).

The logs are produced by the snap build tool and it is available inside the snap package.

Anyway, I don't think it will be verified anytime soon. It is an administrative process, probably complicated one.

**Comment by lindhe** [comment]
Wow, it might not even be possible to become one. :/ https://askubuntu.com/questions/1090483/how-to-become-the-verified-publisher-of-a-snap-package

**Comment by JamesPeterAnderson** [comment]
Appreciate that the original post is quite old now, but this thread is one of the top results when googling the below error:

**Using default input encoding: UTF-8
No password hashes loaded (see FAQ)**

After reading through this thread, I checked my JTR version and I was running 1.8.0, so I proceeded to uninstall JTR and reinstall to the latest version, but I continued to get the same error...

In my scenario I am running Kali Linux and I was trying to decrypt passwords from another Unix system.

(See fifth question on JTR's FAQs - [https://www.openwall.com/john/doc/FAQ.shtml](https://www.openwall.com/john/doc/FAQ.shtml))

I used the unshadow utility to create my password file from the /etc/passwd and /etc/shadow files, then ran john using the default wordlist on the password file, but still got the same error.

I found that the only way that I could get JTR to decrypt the password file was to specify the format at the end of the command.
e.g john --wordlist=password.lst passwdfile.txt `--format=crypt`

During my search for an answer I found the below list of JTR Hash Formats which may also help?
[https://pentestmonkey.net/cheat-sheet/john-the-ripper-hash-formats](https://pentestmonkey.net/cheat-sheet/john-the-ripper-hash-formats)

Not sure if any of that helps, but hopefully this information is useful?

JA

**Comment by ghost** [comment]
> I found that the only way that I could get JTR to decrypt the password file was to specify the format at the end of the command.
e.g john --wordlist=password.lst passwdfile.txt -format=crypt

So, it seems it is yescrypt. See #4621. If that is the case, for now you must use `--format=crypt` [1].

[1] For Linux distros that have started to use native yescrypt hashes via libxcrypt
