### ISSUE TITLE
.rec file problem with hybrid --regex mode

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1678]
With hybrid --regex mode (i.e., --wordlist --regex), the .rec file apparently stores the word which is currently used for generating candidates , not the word for which the generation of candidates has been competed.
So when you interrupt and restore such a hybrid session, you will not get some duplicate candidates, but instead, you'll miss some candidates.

That's why, you cannot really workaround rexgen's memory leaks by just repeatedly interrupting and restoring such a session.

The preferable solution would be to stop the session only after all the candidates of a single input word have been generated.
(Depending on word length and `[List.Rexgen.Alpha:name]` definition, there can be many candidates per word.)

May be hybrid mask mode has the same problem, I did not check that.

Here's how to reproduce:

```
[List.Rexgen.Alpha:ascii2nonascii]
A=[ÀÁÂÃÄÅÆĀĂĄǍǞǠǺȀȂȦȺA]
B=[ƁƂɃʙB]
C=[ÇĆĈĊČƇȻC]
D=[ÐĎĐƉƊƋǱǲD]
E=[ÈÉÊËĒĔĖĘĚƎƏƐȄȆȨɆE]
F=[ƑF]
G=[ĜĞĠĢƓǤǦǴɢG]
H=[ĤĦǶȞʜH]
I=[ÌÍÎÏĨĪĬĮİƗǏȈȊɪI]
J=[ĴƖɈJ]
K=[ĶĸƘǨK]
L=[£ĹĻĽĿŁȽʟL]
M=[ƜM]
N=[ÑŃŅŇŊƝǸȠɴN]
O=[ÒÓÔÕÖØŌŎŐŒƆƟƠǑǪǬǾȌȎȪȬȮȰƢO]
P=[ƤP]
Q=[ɊQ]
R=[®ŔŖŘƦȐȒɌʀʁʶR]
S=[ŚŜŞŠƧȘS]
T=[ŢŤƬƮȚȾT]
U=[ÙÚÛÜŨŪŬŮŰŲƯǓǕǗǙǛȔȖɄU]
V=[ɅV]
W=[ŴW]
Y=[¥ÝŶŸƳȲɎʏY]
Z=[ŹŻŽƵȤZ]
a=[àáâãäåæāăąǎǟǡǻȁȃȧɐɑɒa]
b=[ƀƃɓb]
c=[¢©çćĉċčƈȼɕc]
d=[ðďđƌƍȡɖɗǳd]
e=[èéêëēĕėęěǝȅȇȩɇɘəɚɛɜɝɞe]
f=[ƒf]
g=[ĝğġģǥǧǵɠɡg]
h=[ħȟɥɦʮʯʰʱĥh]
i=[ìíîïĩīĭįıǐȉȋɨi]
j=[ĵǰȷɉɟʄʝʲj]
k=[ķƙǩʞ]
l=[ĺļľŀłƚƛȴɫɬɭl]
m=[µɯɰɱm]
n=[ñńņňŉŋƞǹȵɲɳn]
o=[òóôõöøōŏőœơǒǫǭǿȍȏȫȭȯȱɵƣȣo]
p=[ƥp]
q=[ɋʠq]
r=[ŕŗřȑȓɍɹɺɻɼɽɾɿʳʴʵr]
s=[śŝşšſƨșȿʂs]
t=[ţťŦŧƫƭțȶʇʈt]
u=[ùúûüũūŭůűųưǔǖǘǚǜȕȗʉu]
v=[ʌv]
w=[ŵʍʷw]
x=[×x]
y=[ýÿŷƴȳɏʎʸy]
z=[źżžƶȥɀʐʑz]
```

Then start one session:
```
./john --stdout --wordlist=test --regex=alpha:ascii2nonascii --max-run-time=2 > file1
```
And another:
```
./john --stdout --wordlist=test --regex=alpha:ascii2nonascii --max-run-time=1 > file2
./john --restore >> file2
```
To be paranoid, pass the output through unique

```
./unique file1.txt < file1 
./unique file2.txt < file2 
```

Then cut whichever file has more lines to the number of lines of the smaller file.
```
head -n 13728808 file1 >.txt > file3.txt
```
Then compute the sha1sum of both files or look at the diff.
```
$ diff -C 3 file2.txt file3.txt |head
*** file2.txt	2015-08-17 21:06:58.751932751 +0200
--- file3.txt	2015-08-17 21:06:47.404199835 +0200
***************
*** 6962308,6962313 ****
--- 6962308,9702003 ----
  ¢ɑsïnȫ
  ©ɑsïnȫ
  çɑsïnȫ
+ ćɑsïnȫ
+ ĉɑsïnȫ
```

`çɑsïnȫ` was the last candidate generated when the process got interrupted after 1 second.
But there were many more candidates to be generated from the input word `casino`.

**Comment by frank-dittrich** [comment]
BTW: In my hybrid mask mode test, no candidates got list, but the interrupted session produced one candidate twice:
```
*** 16379534,16379539 ****
--- 16379534,16379540 ----
  -v)1234563 
  .v)1234563 
  /v)1234563 
+ /v)1234563 
  0v)1234563 
  1v)1234563 
  2v)1234563 
```

Mask was `?a?a?a?w?a?a?a`

**Comment by magnumripper** [comment]
Hybrid mask resuming was thoroughly tested at some point in time. I haven't ever tested resuming hybrid regex.

**Comment by magnumripper** [comment]
Found a couple other bugs while looking.

**Comment by magnumripper** [comment]
@frank-dittrich I added your cool rexgen "alphabet" to our presets, in 8f34425.
