### ISSUE TITLE
7-zip doesn't use any salt within its KDF

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1679]
...so we can do the same trick we do with WPA-PSK, boosting the "many salts" speed infinitely.

However, let's wait until we have merged @zzlei's SIMD code first (or maybe he implements this too)

**Comment by magnumripper** [comment]
Here's the trick code from WPA
```c
static int crypt_all(int *pcount, struct db_salt *salt)
{
        const int count = *pcount;

        if (new_keys || strcmp(last_ssid, hccap.essid)) {
                wpapsk(count, inbuffer, outbuffer, &currentsalt);
                new_keys = 0;
                strcpy(last_ssid, hccap.essid);
        }

        wpapsk_postprocess(count);

        return count;
}

static int salt_compare(const void *x, const void *y)
{
        return strncmp((const char*)x, (const char*)y, 36);
}
```

**Comment by magnumripper** [comment]
This is among the best seen many-salts boosts ever :sunglasses: 
```
$ ../run/john -test -form:7z
Will run 8 OpenMP threads
Benchmarking: 7z, 7-Zip (512K iterations) [SHA256 AES 32/64]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 524288
Many salts:	7876 c/s real, 1085 c/s virtual
Only one salt:	42.1 c/s real, 5.5 c/s virtual
```
The format has a salt (for AES) but for cracking purposes, it's unsalted.

**Comment by jfoug** [comment]
So if someone can have multiple 7z's to crack (say 100), it would be nearly 100x faster.  Do the hash 1 time for the passwords, then re-use for every salt?  Is that right?

**Comment by magnumripper** [comment]
Yup. Discussion at http://www.openwall.com/lists/john-dev/2015/08/18/19

**Comment by magnumripper** [comment]
> So if someone can have multiple 7z's to crack (say 100), it would be nearly 100x faster

As Solar put it: You can attack 256 unrelated archives with only 1.1x the effort of attacking one. And the more archives, the closer to 1x we get.

**Comment by magnumripper** [comment]
On another note I got inspired and replaced Dhiru's naive reference code in the OpenCL version of 7-Zip with optimized ninja stuff. This (5d8a78c) rendered an immediate 65-75% boost and now we're even 10-15% faster than oclHashcat :sunglasses: 

However, I wish someone took care of #335 and #717

**Comment by magnumripper** [comment]
Note to self: If we ever find out there are 7-Zip archives using some "NumCyclesPower" other than 19 (512K), we'll just add a salt_compare() so loader.c sorts the salts. (EDIT: this is done, #1728)

**Comment by magnumripper** [comment]
Correction for clarity: The KDF does involve a salt, but all archives we've seen has a salt length of 0. In #4847 I'm adding some checks that should ensure the CPU format works correctly in case we're actually given a 7z hash with a salt.

The OpenCL format currently doesn't even have the salting code in its kernel so after #4847 it will reject hashes with a salt length > 0 and warn about it. If ever needed, we'll probably want to have a separate kernel for when a salt is used, in order not to slow down no-salt hashes.
