### ISSUE TITLE
Try to get rid of as much OpenSSL EVP and BIO crap as possible, as well as Gladman stuff.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1686]
High-level interfaces and abstraction layers are not the best things you can put in high-performance code.

Unfortunately our own AES (aes.h) can only do CBC (right now anyway).

---

Here is a start, at least ID possible files/formats to work on (edited by jfoug):
#### EVP_ stuff
- [x] dmg_fmt_plug.c   (des_ede3:cbc, aes:cbc, hmac:sha1)
- [x] opencl_dmg_fmt_plug  (des_ede3:cbc, aes:cbc, hmac:sha1)
- [ ] encfs_common_plug.c (aes:cbc aes:cfb)
- [x] openbsdsoftraid_fmt_plug.c (hmac:sha1)
- [ ] openssl_enc_fmt_plug.c  (only EVP_BytesToKey remains)
- [x] rar_common.c (aes:cbc)
- [x] ssh2john.c/ssh_fmt_plug.c (numerous crypts, PEM_ stuff, etc)
- [x] wpapsk.h
- [ ] autoconf (provided we manage to remove all of the above)
#### BIO_ stuff
- [x] ssh2john.c/ssh_fmt_plug.c
- [x] ssh_ng_fmt_plug.c
- [x] john.c  (wrapper keeping pfx2john and ssh2john from building)
- [x] luks2john.c    used for base-64 ??? wtf?
- [x] pfx_fmt_plug.c/pfx2john.c  (PKCS12_bio ?)
- [ ] autoconf (provided we manage to remove all of the above)
#### Gladman stuff
- [x] dmg2john.c
- [x] efs_fmt_plug.c
- [x] krb5pa-sha1_fmt_plug.c
- [x] opencl_krb5pa-sha1_fmt_plug.c
- [x] opencl_zip_fmt_plug.c
- [x] putty_fmt_plug.c
- [x] twofish_plug.c
- [x] zip2john.c
- [x] zip_fmt_plug.c
- [x] Makefile.in & Makefile.legacy
- [x] **delete** all gladman files after the above

**Comment by jfoug** [comment]
Here is a start:

```
$ grep -co EVP_ *.c | grep -v :0
django_fmt_plug.c:1
dmg_fmt_plug.c:21
encfs_common_plug.c:26
openbsdsoftraid_fmt_plug.c:1
opencl_dmg_fmt_plug.c:20
openssl_enc_fmt_plug.c:4
pufferfish_api_plug.c:2
pufferfish_fmt_plug.c:2
pufferfish_plug.c:2
putty_fmt_plug.c:1
rar_common.c:15
ssh2john.c:8
ssh_fmt_plug.c:31
truecrypt_fmt_plug.c:2
unrar.c:2
wpapsk_fmt_plug.c:9

$ grep -co BIO_ *.c | grep -v :0
john.c:1
luks2john.c:10
pfx2john.c:3
pfx_fmt_plug.c:9
ssh2john.c:6
ssh_fmt_plug.c:8
ssh_ng_fmt_plug.c:8
```

**Comment by magnumripper** [comment]
I'm looking at RAR right now

**Comment by magnumripper** [comment]
The RAR patch shows all benefits: Less code, cleaner code, no OpenMP problems and workarounds, better performance.

**Comment by jfoug** [comment]
Yes,, dumping the very high level oSSL crap whenever we can, sometimes makes things MUCH better. I have seen 2x or 4x improvements (10x if we have SIMD stuff).  An yes, things like openmp issues go away along with all sorts of other shit.

This should almost be in the coding style, to use our own fast and internally maintained code, over 3rd party stuff whenever we can.

**Comment by magnumripper** [comment]
> This should almost be in the coding style

Agreed. I hate high-level stuff, frameworks and abstractions - well at least in JtR I do.

I was the one adding EVP crap to RAR long ago though. That was the way to get AES-NI at the time.

Anyway, I wonder if we could do EDE3 using Solar's/Deepika's bitslice DES. Maybe tricky. Those HMAC-SHA1 should be piece of cake. If we don't have a shared function already we should add one (we might even be able to use SIMD while at it).

Base64, wow lol.

**Comment by jfoug** [comment]
Another set of stuff that was hard to wean ppl off of was that gladman hmac crap.  It was harder than using the damn pbkdf2*.h files (by far), but some simply would not use anything but that gladman code.  I am glad (pun intended) it is gone man.

**Comment by magnumripper** [comment]
Yeah BTW I thought all gladman files were gone but I see they are still there:
```
$ ls *glad*
gladman_fileenc.h	gladman_hmac.h		gladman_pwd2key.c	gladman_pwd2key.o
gladman_hmac.c		gladman_hmac.o		gladman_pwd2key.h	gladman_sha1.h

$ git grep -l "gladman.*h"
Makefile.in
Makefile.legacy
dmg2john.c
efs_fmt_plug.c
gladman_fileenc.h
gladman_hmac.c
gladman_hmac.h
gladman_pwd2key.c
krb5pa-sha1_fmt_plug.c
opencl_krb5pa-sha1_fmt_plug.c
opencl_zip_fmt_plug.c
putty_fmt_plug.c
twofish_plug.c
zip2john.c
zip_fmt_plug.c
```
We should probably fix that too. Or is there anything good in them?

**Comment by jfoug** [comment]
I thought we smoked them??  Someone put them back :-1: :-1: :-1:

**Comment by magnumripper** [comment]
We probably just stopped using them for PBKDF2. But dropping them should be easy. I'm adding it to the list for this issue.

**Comment by jfoug** [comment]
babb42f   These header includes were not needed.

**Comment by jfoug** [comment]
Gladman code totally gone. Actually VERY trivial (other than a couple defines needed moved into pkzip.h).

The only thing used was hmac_sha1() function, so I wrote 'our own' for JtR. It is faster than gladmans code. It is only about 15% faster, but still faster :+1:

**Comment by jfoug** [comment]
992af99  openbsd-softraid.  This crap is easy to remove, now that i have added hmac_sha1.h  There should be NO excuse now, for @kholia or others using other type code for these simple things. IF we need to add other hmac algos, then by all means speak up, and we can EASILY add them.

**Comment by jfoug** [comment]
f837171  dmg hmac:sha1 only  (still the DES stuff to do)

**Comment by jfoug** [comment]
My opinion about removing the EVP_* and BIO_* checks from the configure, even if we do remove all current code that uses them, is that we should not remove them.

Some of these changes are HARD, and not trivial.  Having these options available to developers to quickly add a format is really needed.  Later we can clean them up and 'own' the code.  Some things like the PKCS12_bio 'can' be done with our owned code (and when I did it, I got a couple orders of magnitude improvement, and could do SIMD), BUT it takes a lot of code reversing to get to an understanding of the actual algorithm used.  However, using already created samples moving to a john format quickly pretty much means that we need to know and use these high level interfaces at times.

**Comment by magnumripper** [comment]
Yeah that sounds like a good idea

**Comment by jfoug** [comment]
Building full oSSL with VC with debug symbols in it (no asm also).  This should make stepping into a lot of the code to really see the simplicity of the 'real' algorithm SOOOO much easier.   Things seem to be building well.  I used perl inside cygwin, so the canned .bat files from the oSSL sources had to be interpreted and turned into commands properly handled in cygwin (mostly changing \ to / )    But with the ability to step into oSSL functions will help in figuring out if we can remove them.

**Comment by magnumripper** [comment]
I suspect the DMG format (especially OpenCL) has huge problems with OpenMP. We should try to switch to some lower-level interface even if still using OpenSSL.

**Comment by jfoug** [comment]
I bet there are more than just that format.  I have been digging into oSSL, and yes, they have thread support, but it sucks, AND you actually LOSE performance going to OMP, because all of the oSSL code handles multi threading by letting only 1 thread at a time run, IF it even works properly.  So removing the oSSL, then managing threading by making sure that each thread gets it's OWN data to work on, so that all threads can run, IS the right way to go.

Again, when cygwin was having those horrible issues on certain formats with OMP, once I ported code out of oSSL, all of those problems went away, and huge performance improvements were seen.

**Comment by magnumripper** [comment]
I really need to fix the DMG format. Had to disable OpenMP completely for it due to segfaults from threading, and it was a major performance hit. I will look into it.

**Comment by magnumripper** [comment]
DMG fixed. Note, I added this to jumbo.[hc]
```c
/*
 * Standard PKCS padding check. On success, returns net length.
 * On failure, returns -1.
 */
extern int check_pkcs_pad(const unsigned char* data, size_t len, int blocksize);
```
`blocksize` is obviously 16 for AES, 8 for DES and so on.

The EVP functions check padding but now we need to do it ourselves. Goes like this:
```c
	DES_ede3_cbc_encrypt(in, out, len, &ks1, &ks2, &ks3, iv, DES_DECRYPT);

	if (check_pkcs_pad(out, len, 8) < 0)
		goto early_reject;
```

**Comment by kholia** [comment]
Commit 063b838e021007a746dc9698a4135779ce22b337 fixes the problem for ssh-ng format.

**Comment by kholia** [comment]
BIO_ stuff is all gone now. Let's keep the support for it in our autoconf scripts for now.

https://www.cryptopp.com/wiki/OPENSSL_EVP_BytesToKey documents the algorithm behind `EVP_BytesToKey` function.
