### ISSUE TITLE
Dynamic getting wrong hash type for SIMD > 128 bit

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1688]
Here is an example:

```
$ ../run/john -test=3 -form=phpass
Will run 8 OpenMP threads
Benchmarking: phpass ($P$9) [phpass ($P$ or $H$) 256/256 AVX2 8x3]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 2048
Raw:    235260 c/s real, 31686 c/s virtual

$ ../run/john-old -test=3 -form=phpass
Benchmarking: phpass ($P$9) [phpass ($P$ or $H$) 128/128 AVX2 8x3]... DONE
Raw:    59599 c/s real, 59617 c/s virtual

$ OMP_NUM_THREADS=1 ../run/john -test=3 -form=phpass
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: phpass ($P$9) [phpass ($P$ or $H$) 256/256 AVX2 8x3]... DONE
Speed for cost 1 (iteration count) of 2048
Raw:    63393 c/s real, 63537 c/s virtual
```

Note, the old run was dynamic.  It shows 128/128 for AVX2 (shows the AVX2 right however).

**Comment by magnumripper** [comment]
I don't see that. Here's a run on well
```
$ ../run/john -test=0 -form:dynamic | grep 128/128
$ ../run/john -test=0 -form:dynamic | grep 256/256 | wc
    103     894    7590
```

**Comment by jfoug** [comment]
I just added this issue as a place holder. I was busy doing other things, and did not want to forget about it.   If this was simply because I was multiple compiling in the wrong way, then I will close this out.  But I certainly was seeing a 128/128 and then AVX2 within dyna, but NOT seeing that (was 256/256 AVX2) for the new phpass fat format.

**Comment by magnumripper** [comment]
Maybe it ends up incorrectly for some specific combination of build? Better have a look at the ladder of ifdefs.

**Comment by jfoug** [comment]
> Better have a look at the ladder of ifdefs.

More like a spaghetti bowl :-1:

**Comment by jfoug** [comment]
This may have been 'fixed' when I scrubbed dynamic_17.  Looking at line 7591 from this change (where I cut the code out)  https://github.com/magnumripper/JohnTheRipper/commit/af2f484eb6fa227467c2763e1a3a7d98735a6dbb  It looks like this may have been the spurious 128/128  Now with that code gone, I am seeing all proper 256/256 for dynamic.
