### ISSUE TITLE
LUKS2john/luks_fmt  If the 'dump' file is created, john is not cracking the hash

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1696]
we now have 2 ways to create luks hashes.  Inline, and in a DUMP file.

I removed all BIO_base-64 crap so was was testing. I was NOT able to get john to crack the files if a dump file was created. I changed the luks2john.c so that the inline hash was done, and the file cracked just fine.

A couple luks files can be found here:  http://openwall.info/wiki/john/sample-non-hashes

**Comment by magnumripper** [comment]
This sounds like a bad bug... false negatives, ouch.

**Comment by jfoug** [comment]
Yup, things 'appear' to be working, but cracks are not found.  Not good.

I have not looked into it, I just wanted to document the problem for when someone has time to work on it.  It may just be something in the binary loading, or salt loading that is slightly off, but off it is.
