### ISSUE TITLE
Markov, Incremental and External modes shouldn't silently ignore a --rules option. 

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1697]
See http://openwall.com/lists/john-users/2015/08/21/10

Either stop with an error message or handle it like prince (i.e., apply all rules to a word generated by markov before proceeding to the next word).

**Comment by magnumripper** [comment]
I wonder if it worked right after 4988b833 or not

**Comment by frank-dittrich** [comment]
I made it a separate issue because at that time I didn't know whether it is jumbo specific or not.

**Comment by magnumripper** [comment]
It did not even work at 4988b83
