### ISSUE TITLE
Confusing sequence of candidates in --mask mode 

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1698]
The sequence mask mode generates candidates is somewhat confusing.

```
./john --stdout --mask='20[01]?d'|head -n 30
Press 'q' or Ctrl-C to abort, almost any other key for status
20p 0:00:00:00 100.00% (2015-08-21 22:31) 153.8p/s 2019
2000
2010
2001
2011
2002
2012
2003
2013
2004
2014
2005
2015
2006
2016
2007
2017
2008
2018
2009
2019
```
I would have expected the rightmost expression to change first, i.e., the years to be generated in chronological order.
Is there a reason for this, i.e. is the generation of candidates faster this way?

The sequence of generating candidates generated for a given mask seems not to be documented.

**Comment by frank-dittrich** [comment]
Master doesn't have these problems.

```
(master)run $ ./john --stdout --external=keyboard --rules
Invalid options combination or duplicate option: "--rules"
(master)run $ ./john --stdout --incremental --rules
Invalid options combination or duplicate option: "--rules"
```

**Comment by magnumripper** [comment]
Why do you expect them to come in any particular order? I think in other cases the opposite would be just as confusing.

For example, do you find the output from `-mask=[a-c] -min-len=0 -max-len=3` confusing? If we reversed it like you want, how would that end up?

**Comment by magnumripper** [comment]
Here's a data point though: In some situations, a big-endian behavior (as you want) would make some optimizations possible, like storing part of previous Merkel-Damgard block halfway through the digest. Hashcat does that but we currently don't have such plans.

**Comment by frank-dittrich** [comment]
First generating all candidates of length 1, then all of length two before switching to length 3 is fine.
But I would indeed expect the length 2 candidates to be generated in the sequence
```
aa
ab
ac
ba
bb
bc
ca
cb
cc
```
instead of
```
aa
ba
ca
ab
bb
cb
ac
bc
cc
```
This is how regex expansion in rexgen and rules expansion work.
If this sequence is better for further optimizations, all the more reason to change it, even if we don't intend to do that optimization now.

**Comment by frank-dittrich** [comment]
In which sequence is GPU side mask mode resolving the GPU part of the mask?

**Comment by magnumripper** [comment]
I think it works the same way, and the portion it takes is also the leftmost *n* number of placeholders.

**Comment by Sayantan2048** [comment]
It's not necessary that GPU side mask portion are the leftmost n. Whatever combination of placeholder satisfy a fomat's demand for n candidates are chosen. If exact demand can't be met, then a combination of placeholders closest to the format's requirement are chosen.

**Comment by magnumripper** [comment]
I had a look at the "reversing by keeping all but w[0] constant" trick and I really don't think it suits JtR anyway.

**Comment by magnumripper** [comment]
I believe this issue is moot since we introduced frequency based ordering.

**Comment by frank-dittrich** [comment]
@magnumripper you may think it is moot, some might argue that change made it worse -
at least for debugging purposes, since it is extremely hard to find out the expected sequence of candidates.

But I have to admit I have no good idea how to improve that.

**Comment by magnumripper** [comment]
For debugging, just use eg. `[a-z]` instead of `?l`.

**Comment by frank-dittrich** [comment]
Of course.
```
./john --stdout --mask='[a-c][3-1]'
a3
b3
c3
a2
b2
c2
a1
b1
c1
9p 0:00:00:00 100.00% (2015-11-23 09:05) 225.0p/s c1

```

May be we should document in doc/MASK that mask modes sequence of candidates differs from what you might expect from e.g. --rules processing, and that the sequence of characters when using `?d`, `?l`, etc. is derived from (rockyou's) frequency information.

**Comment by magnumripper** [comment]
Yeah why not. Feel free to amend doc/MASK.
