### ISSUE TITLE
Pufferfish hash/format should be dropped

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1702]
I have talked with Jeremi about this. The v1 pufferfish we have is pretty much totally busted.  The multiple usage of the HMAC_SHA512() macro is very wrong, BUT that is how the algorithm is written.  Jeremi states to have no interest in working on this algo any longer, and thinks it should just die on the vine.

I vote we scrub this one.

**Comment by epixoip** [comment]
IMO it never should have been committed in the first place, for the same reason I never submitted a pull request for my v0 JTR patch. Doesn't really make sense to have a plugin for an algorithm that isn't used anywhere outside of one contest one time.
