### ISSUE TITLE
How to implement your own format

### ISSUE THREAD

**Issue by Thanathan-k** [magnumripper/JohnTheRipper#1704]
I'm not sure if this is the right place, but I would like to ask when the wiki page for implementing own formats is gonna be edited. Or if someone could give me a short walktrough/guideline on how to do it.

If this isn't the right place, I would greatly appreciate it if you could give me the correct place to ask this question.

**Comment by magnumripper** [comment]
The john-dev mailing list (see openwall.com) would be the best place to discuss it. We already have #1475 so I'll close this.
