### ISSUE TITLE
Single mode: make retrying cracked passwords on other hashes configurable

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1706]
Currently, single mode retries cracked passwords on other hashes (single.s, single_process_buffer(), `if (guessed_keys->count)`.
I'd like to configure that behavior. Default should be Y, to be compatible with core john, But I'd like to set the variable to N if I am sure that it is very unlikely these passwords are reused (or I intend to use --loopback later...)

**Comment by jfoug** [comment]
See what you think Frank. It seems to run much faster for me. I just want to make sure things are the way they should be, before i close this issue out.

**Comment by magnumripper** [comment]
I re-wrote this in 83f9ca6 in a cleaner way and used a correct name style. The option is now in john.conf:
```
# Un-commenting this stops Single mode from re-testing guessed plaintexts
# with all other salts.
#SingleRetestGuessed = N
```

**Comment by magnumripper** [comment]
GitHub almost unusable now. The DoS attacks come from China, as usual :angry:

**Comment by jfoug** [comment]
This patch makes a hell of a difference on the A-M leak.  I ran a -single against my rand 250k, using just 3 rules

[List.Rules:Single_AM]
>4
@?d >4
@?D >4

It is at 75% now (after 9 hours).  At 1500+ cracks.  Single chugged along for quite a while, doing it's thing and finding a few. Then after about 6 hours of running, it logs this line:

'Processing the remaining buffered candidate passwords, if any'

and that is really where things start to find cracks quickly.  That was only 3 hours ago.  Almost all cracks were found after this.  Up to that point, the cracks were multi-word, where one or more word parts were used.  It did find some, but takes a LONG time.  Also, there is no ETA during that initial run (whatever it is).

**Comment by frank-dittrich** [comment]
Apparently you didn't read http://openwall.com/lists/john-users/2015/08/21/1 or you would have known that before.

**Comment by frank-dittrich** [comment]
@jfoug Do you still use jumbo's default value of 6 for SingleWordsPairMax? Try changing it to 0.

**Comment by frank-dittrich** [comment]
I think the "buffered remaining candidate passwords" are those where john didn't get the required optimal number of candidates per hash, even after processing all rules (due to rejected words...).

**Comment by frank-dittrich** [comment]
And, BTW, the 75% is misleading. It just means that at least for one hash john had to process 75% of the rules to get the MAX_KEYS_PER_CRYPT number of candidates for this hash.

**Comment by frank-dittrich** [comment]
May be my understanding of single mode process is wrong. With just 3 rules, you can hardly be at 75% when counting processed rules.

**Comment by frank-dittrich** [comment]
This feature is also very useful once we try to verify uploaded cracks during a contest. (Only passwords with colons will need special handling.)

**Comment by frank-dittrich** [comment]
But for verification during contest we would also need to prevent john's single mode from splitting the input word at certain special characters.

**Comment by frank-dittrich** [comment]
Perfect (optimal usage of run time) would be to use the top (MAY_KEYS_PER_CRYPT - 1) cracked passwords to fill those partly empty buffers at the end of single mode processing.

**Comment by magnumripper** [comment]
That's the kind of comment you probably should send to john-dev too... it sounds like a good idea!

**Comment by magnumripper** [comment]
OK so I had a go at the AM stuff. How the heck do you even load them? I guess you are using `NoLoaderDupeCheck = Y` in john.conf? Still, it seems to take forever (I'm trying to load a quarter of them).

**Comment by magnumripper** [comment]
Something must be O(n²) here, we should profile it and fix it. 250K hashes loads in a blink.

**Comment by magnumripper** [comment]
Perhaps bump SALT_HASH_LOG in params.h? I wonder if all code supports bumping that.

**Comment by magnumripper** [comment]
Wow. I just bumped it from 12 to 24 and 9,000,000 salts are loaded in a few seconds!

**Comment by jfoug** [comment]
yup, there are some 'very' poor selecctions in some parts of john.  I remember when I started using the unique file, it was hours or more to work (sometimes days).  now it is much faster and configurable..

I think things like this should auto-detect based upon file size.  No reason to go overboard for a 1mb file, but if it is 1gb (or multi gb), then you need to rethink some hash table sizes.

**Comment by jfoug** [comment]
This is SUPER slow data.  I think it is likely best to split it up in to 250k hashes (or even smaller) anyway.   250k gives you 145 files.

The amount of data here, along with how slow these are is pretty much overwhelming.  It is a couple weeks just to run a minimal set of passwords (just enough to fill your bcrypt buffers).
