### ISSUE TITLE
With SessionFileProtect = Always, it is not possible to ./john --restore=session

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1711]
I only wanted to avoid accidentally overwriting a session file, not preventing a restore ;)
(Workaround: comment, restore, remove comment)

**Comment by magnumripper** [comment]
LOL. Was that after my recent patch, or before it too?

**Comment by frank-dittrich** [comment]
With your latest patch, I am not even able to start a session --session=name.

```
(bleeding-jumbo)run $ rm sapb-test*.*  
(bleeding-jumbo)run $ ./john hashes.sapb --session=sapb-test
Warning: SAP-B format should never be UTF-8.
Use --target-encoding=iso-8859-1 or whatever is applicable.
Using default input encoding: UTF-8
Loaded 10 password hashes with 10 different salts (sapb, SAP CODVN B (BCODE) [MD5 128/128 AVX 4x3])
Warning: invalid UTF-8 seen reading $JOHN/john.pot
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
ERROR: SessionFileProtect enabled in john.conf, and sapb-test.rec exists
(bleeding-jumbo)run $ ls -l sapb-test.*
-rw-------. 1 fd fd 1169 Aug 26 01:31 sapb-test.log
-rw-------. 1 fd fd  137 Aug 26 01:31 sapb-test.rec
```

**Comment by magnumripper** [comment]
Wasn't that the whole idea? The file exists and you try to overwrite it.

**Comment by magnumripper** [comment]
Oh, you mean it did create them, and then complained they were there? WTF. I tested this and it worked fine.

**Comment by magnumripper** [comment]
That problem may be only with batch mode. It seems we need to re-work this. I need some sleep now.

**Comment by magnumripper** [comment]
I just can't see why 86c16b1 doesn't work. Apparently FLG_RESTORE_CHK is not set at the time. I *will* take some rest now though.

**Comment by magnumripper** [comment]
OK, so whether restoring or not, the following is true
```
	if (!(options.flags & FLG_RESTORE_CHK))
```
I can't understand that.

**Comment by magnumripper** [comment]
I think that flag might come true **after** we restore. But how do we even know we should restore if it's false before that happens?

**Comment by magnumripper** [comment]
OK here's how to check it (at that point). Pretty unintuitive.
```
	if (rec_restored)
```
This is true if we're restoring and false if we're not.

**Comment by magnumripper** [comment]
@frank-dittrich please test. My tests seem to indicate it's AOK now.

**Comment by magnumripper** [comment]
I've used this with no problems for some time now - closing.
