### ISSUE TITLE
keccak (sha3) do we have SIMD code?

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1712]
If not, then why do all of those raw formats list SIMD for the algorithm ?

**Comment by magnumripper** [comment]
I thought they have their own SIMD (like Blake), supporting up to AVX (not AVX2), and not using our pseudo-intrinsics (so no Altivec/ARM NEON). But now that I look at Keccak files they seem to be totally lying about any and all SIMD support.

**Comment by jfoug** [comment]
That is why I asked the question.   It appears that there are only AVX/XOP define looking to make the strings listing that these are supported, but I saw NOTHING in code about SIMD usage.  

Yes, it is lying to us, lol

**Comment by jfoug** [comment]
Btw, I found this since I am adding SHA3 into dynamic.  Without having SIMD, the code generated and put into dynamic_big_crypt.c is simpler

**Comment by magnumripper** [comment]
See also #1216 (which was assuming there actually was some SIMD code in it)

**Comment by magnumripper** [comment]
Note though that wherever @kholia got the code, I'm pretty sure there are SIMD versions too. So maybe we should fix this prior to you including it in dynamic?

**Comment by jfoug** [comment]
It is easy to re-gen later, with SIMD.  Well, possibly not, if it is not using our SIMD 'interface'.  If it is a total stand alone interface, then it may have to be done outside of generated code.

**Comment by jfoug** [comment]
With the recent changes to dyna, it really is only a few hours work to get a new hash installed.  I am doing these:

SHA3-224
SHA3-256
SHA3-384
SHA3-512
KECCAK-256   (not sure these 2)
KECCAK-512   (are really useful)

I might look at SHAKE128 and SHAKE256 if they are applicable.

So far, the total change is a few lines in dynamic_big_crypt.cin (include and some defines), and 6 lines added to dynamic_big_crypt_generator.sh

**Comment by magnumripper** [comment]
Dang, now that I'm so used to the Merkel Damgard buffer, how can I learn Keccak? Note to self: http://keccak.noekeon.org is a good page.

I wonder how Keccak will fit a GPU?

**Comment by magnumripper** [comment]
SHA-3 is an instance of Keccak, right? Like "Keccak-f[1600]" or something like that. Is that it, or is it more to SHA-3?

**Comment by magnumripper** [comment]
Apparently, PBKDF2-HMAC-SHA3 does not make sense. It will be just PBKDF2-SHA3.

**Comment by jfoug** [comment]
> Dang, now that I'm so used to the Merkel Damgard buffer, how can I learn Keccak? Note to self: http://keccak.noekeon.org is a good page.

This is the first non MD I have worked with either (other than encryption, des/aes, etc).

sha3 is simply keccak-512 but the block padding is a 6  vs a 1 (at least I think that is the only diff).   I read up an hour or so on keccak last nite trying to figure shit out.  I could not find ANY online calcs that would do SHA3 properly. They would always give me keccak-512 (or 256).  

The only thing different about Keccak-512 and SHA3-512 is the call to keccak_init.  One passes in a 1, one a 6.

Look at the top of dynamic_compiler.  I have some macros.  The init is quite a bit different than for a MD.  For keccak, you pass in several other parameters that adjust the soak up and squeeze out rates (and sizes), and final bit sizes, etc. But things like the update are simply the same call for 'all' flavors.

Yes, I am not sure what we are doing on this one for SIMD.  We may not be able to interleave the same way we do for MD's, I am not sure.
