### ISSUE TITLE
Misuse of error functions

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1714]
@jfoug in dynamic_compiler.c, you mis-use error exits in several ways:
```
	error("exiting now");
```
We should almost never call `exit()` so you got that part right. But the core `error()` function takes no argument. The way to use it is
```
	fprintf(stderr, "error message");
	error();
```

Also, you do this in one place with no `errno` used/defined:
```
	pexit ("compile_keys_base16_in1_type() : Error parsing %s, we got to %s\n", _p->pExpr, p);
```
This is also wrong, because `pexit()` is only for printing the error in `errno` with an optional extra message. It will work as intended **except** it will also add a confusing message from some previous unrelated use of `errno`.

Maybe we should add a jumbo str_error() function that does what you meant.

**Comment by jfoug** [comment]
Missed a file in last commit  95e717f
