### ISSUE TITLE
OpenCL: Issues with Intel HD Graphics

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1723]
OSX, HD Graphics 4000 (driver version 1.2(Jul 29 2015 02:40:37)):

```
$ ../run/john -test=0 -form:opencl 
Device 1: HD Graphics 4000
Testing: agilekeychain-opencl, 1Password Agile Keychain [PBKDF2-SHA1 OpenCL AES]... (8xOMP) FAILED (cmp_all(1))

Testing: blockchain-opencl, blockchain My Wallet [PBKDF2-SHA1 OpenCL AES]... (8xOMP) FAILED (cmp_all(1))

Testing: dmg-opencl, Apple DMG [PBKDF2-SHA1 OpenCL 3DES/AES]... (8xOMP) FAILED (cmp_all(1))

Testing: keychain-opencl, Mac OS X Keychain [PBKDF2-SHA1 OpenCL 3DES]... (8xOMP) FAILED (cmp_all(1))

Testing: ODF-opencl [SHA1 OpenCL Blowfish]... (8xOMP) FAILED (cmp_all(1))

Testing: ODF-AES-opencl [SHA256 OpenCL AES]... (8xOMP) FAILED (cmp_all(1))

Testing: PBKDF2-HMAC-SHA512-opencl, GRUB2 / OS X 10.8+, rounds=10000 [PBKDF2-SHA512 OpenCL]... FAILED (cmp_all(1))

Testing: strip-opencl, STRIP Password Manager [PBKDF2-SHA1 OpenCL]... (8xOMP) FAILED (cmp_all(1))

Testing: sxc-opencl, StarOffice .sxc [PBKDF2-SHA1 OpenCL Blowfish]... (8xOMP) FAILED (cmp_all(1))

Testing: zip-opencl, ZIP [PBKDF2-SHA1 OpenCL AES]... (8xOMP) FAILED (cmp_all(1))

10 out of 53 tests have FAILED
```

All failures above are just two kernels; The SHA-1's are the "unsplit pbkdf2-hmac-sha" kernel.

Linux, HD Graphics 4600 (driver version 16.4.2.1.39163):

```
$ ../run/john -test=0 -form:opencl -dev=3 | grep -v PASS
Device 3: Intel(R) HD Graphics
Testing: PBKDF2-HMAC-MD4-opencl [PBKDF2-MD4 OpenCL]... FAILED (cmp_all(1))

Testing: PBKDF2-HMAC-MD5-opencl [PBKDF2-MD5 OpenCL]... FAILED (cmp_all(1))

Testing: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... FAILED (cmp_all(1))

Testing: PBKDF2-HMAC-SHA512-opencl, GRUB2 / OS X 10.8+, rounds=10000 [PBKDF2-SHA512 OpenCL]... FAILED (cmp_all(1))

4 out of 53 tests have FAILED
```

And curiously enough:

```
$ ../run/john -test=0 -form:pbkdf2-hmac-m*opencl -dev=3 -force-vector:2
Device 3: Intel(R) HD Graphics
Testing: PBKDF2-HMAC-MD4-opencl [PBKDF2-MD4 OpenCL 2x]... PASS
Testing: PBKDF2-HMAC-MD5-opencl [PBKDF2-MD5 OpenCL 2x]... PASS
All 2 formats passed self-tests!
```

**Comment by magnumripper** [comment]
See also #1571

**Comment by magnumripper** [comment]
Majority fixed (the pbkdf2-hmac-sha1 ones) on OSX (driver bug, silly workaround).

**Comment by magnumripper** [comment]
Myrice's raw-sha512-opencl and xsha512-opencl crashes during build (OSX w/ Iris (I think 5100) device using version 1.2(Jul 29 2015 02:40:39)). Other than that, these fail:
```
Testing: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... FAILED (cmp_all(1))
Testing: PBKDF2-HMAC-SHA512-opencl, GRUB2 / OS X 10.8+, rounds=1000 [PBKDF2-SHA512 OpenCL]... FAILED (cmp_all(1))
```

**Comment by crioux** [comment]
I'm getting a hang with clBuildProgram on Windows using Intel HD 530 latest drivers (as well as older drivers)

Platform #1 name: Intel(R) OpenCL, version: OpenCL 2.0
    Device #0 (3) name:     Intel(R) HD Graphics 530
    Device vendor:          Intel(R) Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0
    Driver version:         20.19.15.4364
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          12.0 GB
    Global Memory Cache:    512.5 KB
    Local Memory:           64.0 KB (Local)
    Max memory alloc. size: 3.0 GB
    Max clock (MHz):        1150
    Profiling timer res.:   83 ns
    Max Work Group Size:    256
    Parallel compute cores: 24
    Speed index:            27600
    PCI device topology:

It hangs compiling $JOHN/kernels/DES_bs_kernel_h.cl

100% cpu and stuck in the igc64.dll compiler. probably an unroll/nested loop/ something bug.

**Comment by magnumripper** [comment]
All OpenCL formats currently work fine with Intel(R) HD Graphics 630 under macOS.
