### ISSUE TITLE
Lotus5-OpenCL problems

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1726]
Segfaults during autotune. Seems like it was introduced with 14437f60b.
BOF, set_key() is called with a key pointing to random garbage.

**Comment by magnumripper** [comment]
@Sayantan2048 what's "PADDING" for? Is that just to make some headroom against bugs? ;-)

**Comment by Sayantan2048** [comment]
PADDING is for those cases where GWS is rounded up to be greater than what has been allocated. one such case is when LWS is greater than GWS.

**Comment by magnumripper** [comment]
That shouldn't ever happen. Neither `count` nor `local_work_size` can be greater than `global_work_size`.

**Comment by magnumripper** [comment]
BTW this is a very bad idea:
```
#define PADDING 		2048
...
	assert(local_work_size <= PADDING);
```
We've seen devices that can have a local worksize of 8192.

**Comment by magnumripper** [comment]
IMHO you should just drop all uses of PADDING in all formats.

**Comment by Sayantan2048** [comment]
Agreed, at least for lotus5-opencl. When I said "One such case is when LWS is greater than GWS", I meant that as a bug. Howver, for mscash2-opencl PADDING is used to adjust work partioning between various devices. I'll look into other formats and drop use of PADDING if they are only for byepassing round up errors.

**Comment by magnumripper** [comment]
There still are problems.
```
$ OMP_NUM_THREADS=1 ../run/john -test=0 -form:opencl -dev=7
Device 7: GeForce GTX TITAN
Testing: sha1crypt-opencl, (NetBSD) [PBKDF1-SHA1 OpenCL 2x]... PASS
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... PASS
Testing: PBKDF2-HMAC-MD4-opencl [PBKDF2-MD4 OpenCL 2x]... PASS
Testing: PBKDF2-HMAC-MD5-opencl [PBKDF2-MD5 OpenCL 2x]... PASS
Testing: PBKDF2-HMAC-SHA1-opencl [PBKDF2-SHA1 OpenCL]... PASS
Testing: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... PASS
Testing: RAR5-opencl [PBKDF2-SHA256 OpenCL]... PASS
Testing: lotus5-opencl, Lotus Notes/Domino 5 [OpenCL]... OpenCL CL_OUT_OF_RESOURCES error in opencl_lotus5_fmt_plug.c:326 - Failed to read buffer cl_tx_binary.
```

**Comment by magnumripper** [comment]
@Sayantan2048 could you have a look at this? Fails every time on Titan X.
```
$ ../run/john -test=0 -form:opencl -dev=6
Device 6: GeForce GTX TITAN X
Testing: sha1crypt-opencl, (NetBSD) [PBKDF1-SHA1 OpenCL]... PASS
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... PASS
Testing: PBKDF2-HMAC-MD4-opencl [PBKDF2-MD4 OpenCL]... PASS
Testing: PBKDF2-HMAC-MD5-opencl [PBKDF2-MD5 OpenCL]... PASS
Testing: PBKDF2-HMAC-SHA1-opencl [PBKDF2-SHA1 OpenCL]... PASS
Testing: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (32xOMP) PASS
Testing: RAR5-opencl [PBKDF2-SHA256 OpenCL]... PASS
Testing: lotus5-opencl, Lotus Notes/Domino 5 [OpenCL]... OpenCL CL_OUT_OF_RESOURCES error in opencl_lotus5_fmt_plug.c:322 - Failed to read buffer cl_tx_binary.
```

**Comment by Sayantan2048** [comment]
simple --test option crashed tahiti on my system as well as super. Also memdbg is showing memory leaks when --test option is used. I think it stems from auto-tune or improper use of auto-tune. Please review and make necessary changes as required.

**Comment by magnumripper** [comment]
The mem leak was a separate shared code issue introduced by Solar, fixed now. I removed that weird "PADDING" stuff and all problems seem to have disappeared.

**Comment by magnumripper** [comment]
WTF now it re-appeared for no reason. Not sure what is happening.

**Comment by magnumripper** [comment]
I am more or less convinced the remaing problem is some nvidia driver bug. There's nothing wrong in the code but it acts like something is not initialized properly. I tried to work around it today but didn't come up with anything.

To trigger: run `--test=0 --format=opencl`
To "fix": run `--test` with either `--format=opencl` or just `--format=lotus5-opencl`
After that it usually keeps working even with `--test=0` as long as you also supply `--format=lotus5-opencl`. As soon as you run some other format, it goes bad again.

**Comment by magnumripper** [comment]
Lotus5 also (possibly intermittently) hangs on Tahiti
```
$ ../run/john -test=0 -form:opencl -dev=2
Device 2: Tahiti [AMD Radeon HD 7900 Series]
Testing: sha1crypt-opencl, (NetBSD) [PBKDF1-SHA1 OpenCL]... PASS
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... FAILED (cmp_all(1))

Testing: PBKDF2-HMAC-MD4-opencl [PBKDF2-MD4 OpenCL]... PASS
Testing: PBKDF2-HMAC-MD5-opencl [PBKDF2-MD5 OpenCL]... PASS
Testing: PBKDF2-HMAC-SHA1-opencl [PBKDF2-SHA1 OpenCL]... PASS
Testing: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (32xOMP) PASS
Testing: RAR5-opencl [PBKDF2-SHA256 OpenCL]... PASS
^CSession abortedpencl, Lotus Notes/Domino 5 [OpenCL]... ^CWait...
```
That was after like 10 minutes of hanging.

**Comment by magnumripper** [comment]
...so it likely **is** a bug somewhere in the format but I certainly can't find it.

**Comment by magnumripper** [comment]
Segfault seen with Intel CPU driver as well. Again using `--test` but not with `--format:lotus5-opencl`.

**Comment by magnumripper** [comment]
Looks like this is gone now - either due to driver fixes or some other thing we did over time.
