### ISSUE TITLE
Some code aligns >16 on stack.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1731]
Apparently you are not guaranteed that `__attribute__ ((aligned(32)))` or higher actually works (on stack). I think we use it in several places (most often as `aligned(MEM_ALIGN_SIMD)` for AVX2 or better).

We should first confirm that it's a real problem though (we haven't seen any problem). To build for AVX2 you need eg. gcc 4.7 or higher. Maybe they actually support it since? I can't see a technical reason they would not support it.

**Comment by magnumripper** [comment]
```
$ git grep -F 'ALIGN(MEM_ALIGN_SIMD)' | grep -v static | cut -d: -f1 | uniq
bitcoin_fmt_plug.c
cryptsha256_fmt_plug.c
cryptsha512_fmt_plug.c
dynamic_big_crypt_hash.cin
hmacMD5_fmt_plug.c
hmacSHA1_fmt_plug.c
hmacSHA224_fmt_plug.c
hmacSHA256_fmt_plug.c
hmacSHA384_fmt_plug.c
hmacSHA512_fmt_plug.c
mssql-old_fmt_plug.c
mssql05_fmt_plug.c
mysqlSHA1_fmt_plug.c
pbkdf2_hmac_md4.h
pbkdf2_hmac_md5.h
pbkdf2_hmac_sha1.h
pbkdf2_hmac_sha256.h
pbkdf2_hmac_sha512.h
pseudo_intrinsics.h
rakp_fmt_plug.c
rawSHA1_linkedIn_fmt_plug.c
simd-intrinsics.c
unused/dynamic_big_crypt.c
```

**Comment by magnumripper** [comment]
This may actually be a (fixed) but in gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16660

**Comment by zzlei** [comment]
This is indeed a real problem, as discussed in http://www.openwall.com/lists/john-dev/2015/08/24/8

**Comment by magnumripper** [comment]
Oh, right. So we should review all allocs and change to this style (this example from cryptsha256_fmt_plug.c):
```c
                char tmp_sse_out[8*MAX_KEYS_PER_CRYPT*4+MEM_ALIGN_SIMD];
                ARCH_WORD_32 *sse_out;
                sse_out = (ARCH_WORD_32 *)mem_align(tmp_sse_out, MEM_ALIGN_SIMD);
```

**Comment by jfoug** [comment]
This change mostly reverted, and instead 013be13 is used.  This kills both birds with 1 stone, and should be faster than even the inline function.

@magnumripper please regression test for speed, comparing against the original code (using JTR_ALIGN()) then against code using your prior inline function.  I am pretty sure this code should be as fast as the JTR_ALIGN model, and this one works for ANY alignment if the initial buffer is setup large enough.

NOTE, we may want to audit the .C files, to make sure our buffer allocs are only SIMD_ALIGN number of bytes larger, and note SIMD_ALIGN*sizeof buffer element type.

**Comment by magnumripper** [comment]
@zzlei please review (and/or test) fa475e4
