### ISSUE TITLE
Office2john.py - OSError: incorrect DIFAT

### ISSUE THREAD

**Issue by darklighterz** [magnumripper/JohnTheRipper#1732]
I was just playing around with the office2john.py tool. I have noticed if I add a video or something inside the document to increase its size to 70mb+ I can no longer get a hash and instead get the below message.

OSError: incorrect DIFAT

Ive not tested to see just how big a file needs to be before this starts to happen though.

**Comment by kholia** [comment]
The latest version of office2john.py works for such files (talked with the reporter in private emails).
