### ISSUE TITLE
Dynamic ad-hoc formats: Constants with colons etc.

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1747]
```
$ ./john --single 2M --format=dynamic='md5(lc($u).$c1.lc($p)),c1=::'
[...]
61278g 0:01:27:07 DONE (2015-09-11 16:04) 11.72g/s 245492p/s 245492c/s 245492C/s girlyfun991907..girlyfun991900
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john --show 2M --format=dynamic='md5(lc($u).$c1.lc($p)),c1=::' 
0 password hashes cracked, 1999999 left
```
The reason is that colons as part of a hash break loading cracked hashes:
`@dynamic=md5(lc($u).$c1.lc($p)),c1=::@...`

I think it would be even better to convert
```
@dynamic=md5(lc($u).$c1.lc($p)),c1=::@
```
into
```
@dynamic=md5($s.$p)@
```
and convert the constant and the user name (after conversion to lower case) into a salt (using hex if there are any illegal characters).

Of course, this is not trivial, because for `md5(lc($u).lc($p).$c1)` you'd need two salts etc.

But storing colons as part of the hash must be fixed.

**Comment by magnumripper** [comment]
This is already supported, you need to use \x3a for colon. Some of the "documentation" are still just within the source files :-)

**Comment by magnumripper** [comment]
I was going to report that this segfaulted but you just fixed it in fa77788
```
../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p)),c1=\x3a\x3a,saltlen=-16'
```

**Comment by frank-dittrich** [comment]
OK, I can live with that.
Nevertheless, reducing `lc($u).$c1.lc($p)` to `$s.$p` or at least `lc($u).$c1.$p` (the password will be lowercase when written to the pot file) or `$u.$c1.$p` (if user name is converted to lowercase before storing it in the pot file) would be great.

**Comment by jfoug** [comment]
> Some of the "documentation" are still just within the source files :-)

the compiler is 'fully' documented within the source files, lol

**Comment by jfoug** [comment]
> (if user name is converted to lowercase before storing it in the pot file) would be great.

The format has no control over this.

**Comment by magnumripper** [comment]
```
Nevertheless, reducing lc($u).$c1.lc($p) to $s.$p or at least lc($u).$c1.$p (the password will be lowercase when written to the pot file) or $u.$c1.$p (if user name is converted to lowercase before storing it in the pot file) would be great.
```
`$u` **is** a salt, it's merely telling the format to fetch it from the login field but after loading it should be the very same thing. Doesn't dynamic treat it correctly as a salt after loading?

And why would you want to get rid of the lc()? That one is marvelous: It reduces the key space of length 8 ascii with 93%.

**Comment by jfoug** [comment]
So, right now, what are the 'known' bad characters?  I am going to auto correct these, before parsing script.

I can see these: 
   :  (due to john using them for field separator)
   $ (due to dynamic, BUT I think they may be safe here, since they are in the signature)
   *  (possibly we should fix this in dynamic_fmt.c instead)
  '   (not sure)
  "  (not sure)

The quotes likely will need quoting only if being used. Unix uses single quotes, windows CMD uses doubles. I think those will need hexing, and we probably should hex them both.

So I really think that : ' and " are the only ones that should 'require' hexing.

**Comment by frank-dittrich** [comment]
@magnumripper Yes, lc($u) plus 4c1 IS the salt.
That's why I want the hash to be stored as `@dynamic=md5($s.$p)@` in the .pot file.

$u only matters for the format to know where to grab the salt.
When storing the hash, it makes little sense to store it as 
```
@dynamic=md5(lc($u).$c1.lc($p)),c1=::@
```
Because the same password would also be valid for other representations of what basically is the same hash.

```
@dynamic=md5(lc($u).$c1.lc($p)),c1=::@
@dynamic=md5(lc($u).$c1.$p),c1=::@
@dynamic=md5($u.$c1.$p),c1=::@
@dynamic=md5($s.$p),c1=::@
```

If john doesn't reduce the expression to the simplest representation, then we might have to recrack hashes which might have been cracked earlier, just because they have been stored using a different representation of that same hash.

**Comment by magnumripper** [comment]
Now I see what you mean. We'd still use `md5(lc($u).$c1.lc($p)),c1=\x3a\x3a` when cracking it but could be `md5($s.$p)`in the .pot file. That makes sense and this is a variant of #1469 but with less caveats.

**Comment by magnumripper** [comment]
`$u` should always be stored as `$s` as an easy start.

**Comment by magnumripper** [comment]
> I can see these: 
```
   :  (due to john using them for field separator)
   $  (due to dynamic, BUT I think they may be safe here, since they are in the signature)
   *  (possibly we should fix this in dynamic_fmt.c instead)
   '  (not sure)
   "  (not sure)
```
The quotes likely only require quoting only if being used. Unix uses single quotes, windows CMD uses doubles. I think those should be hexed to keep then uniform

> So I really think that : ' and " are the only ones that should 'require' hexing.

The `*` problem is also from john.c's "format class" wildcard. I think we'll just have to escape them. I see no reason to escape `'`´or `"`, we are not (and should not) dealing with shell problems here. But empirical tests show we need to escape `@`.

**Comment by magnumripper** [comment]
BTW any escapes must be canonically handled, eg. if I (for no reason) escape `a` as \x061, it should hit a .pot entry that has it without escape and vice versa. The easiest might be to always store all constants as hex.

**Comment by frank-dittrich** [comment]
replacing $u with $s only works if you don't have $s. Otherwise, you must replace $u with $s2.
Easier should be to just drop lc() and uc() as a first step.

**Comment by jfoug** [comment]
No, the best way is to properly build your input file from the start ;)  Trying to put this form of intelligence into the already over complex format is not the proper way. The proper way is to make it as streamline as possible, and then all the gray matter work such as figuring this crap out, is to be done by the one with the gray matter.

**Comment by jfoug** [comment]
I certainly am planning on canonizing the hashes, BUT there is only so much that can be done.  canonization is not going to be a complete expression parsing / reducing engine, unless you want to write and maintain that monster. That would be as hard, if not harder than the dynamic expression parser all by itself.

**Comment by magnumripper** [comment]
> No, the best way is to properly build your input file from the start

If you mean eg. lower-casing usernames in the input file, I disagree. There might even be different users called bob and BOB. When BOB was cracked we wouldn't want it to say "bob".

**Comment by frank-dittrich** [comment]
@jfoug In this case, `--format=dynamic='md5(lc($u).$c1.lc($p)),c1=\x3a\x3a'` is the proper way.
Otherwise, you could drop supporting $u, $c1, and may be even lc() and uc().

But, if you later encounter a format which uses salts and `--format=dynamic='md5($s.$p)'`, and the salt of a hash happens to be exactly the same as `lc($u).$c1`, and the password is the same, we would need to re-crack that one, even though it is already stored in the pot file, just in a different way.

But I agree that it would add a lot of complexity. May be just dropping lc() and uc() before storing in john.pot wouldn't be that complex.

**Comment by jfoug** [comment]
no, bob and Bob and BOB would still be user names, BUT the file should be built properly from the start to simply be md5($s.lc(p)) and the input data should have a $salt appended to it with all proper data, and proper casing (NOTE, with the ::, $HEX$ format would need to be used, universally.

So, a line would be:

Bob:md5_hex$HEX$proper_full_salt_in_hex
BOB:md5_hex$HEX$proper_full_salt_in_hex_for_BOB_record

**Comment by jfoug** [comment]
The lc($p) IS magic, and must be preserved. As has been mentioned, it vastly reduces the input wordspace.  But the rest should be proply build INTO the salt, from the start. You have 100% of the exact data to properly build it. It will speed up the format, 5-10% or more anyway, by simply reducing the operations overhead.  The lc(u) is not an issue.  It is done (I think) at prepare() time.  But true canonization like this really should be done by the user, who KNOWS enough to look into the problem.

**Comment by jfoug** [comment]
I do agree, that the .pof format may be better to NOT have the [ul]c($p) or [ul]c($u) stored, just storing the $u and $p.  And then on load know that $lc($u)==$u upon load, for found candidate strike off.

But my point does still stand.  the compiler 'should' not auto try to convert md5(lc($u).$c1.lc($p)) into md5($s.lc($p))  If the user does not perform that logic, then it is his own fault.

Now, I will 'fix' things like:   md5($s.$c1.$p.$c3.$p.$c2) vs md5($s.$c1.$p.$c2.$p.$c3) 

or md5($c1.$p.$c2),$c1=x,$c2=y and md5($c2.$p.$c1),$c2=x,$c1=y md5($c1.$p.$c2),$c2=y,$c1=x

Those all get 'normalized'  (not sure the code was done, but that was the plan).  For canonization, all constansts would be c1 c2, c3.... as first seen from left to right in the expression, AND the order after the expression preserved. Also, the order of the different things that DO follow after the expression (the params), would be in a canonical defined order. Also, there are numerous of these parameters which would not be used in checking if we have a pot match (and possibly not stored in the .pot file).

HOWEVER, those ideas have not seen the light of code yet.  They are simply still in my head.  NOTE, the dyna compiler is a very early release. It is not complete.  It works for what it is, but still there is much to do.

**Comment by jfoug** [comment]
This is the best I can think of for the input for this hash (2 forms)

```
userid1:$dynamic_4$e651b1baf80874161e743b32915c8eaa$HEX$313132323a3a:$2a$12$6YEtyM93L2EQkHzs/PSP6OKEiW6fS3dSZCozzDrMKhHqRmI6NjS1S
userid2:$dynamic_4$d5c45946999f5b57509727bd8d20fe62$HEX$626f6f626f6f3a3a:$2a$12$3V0bFXAv1b4DT1KHh3uqjumaRYysI.NNpgXlcFEfulNUoBYtBEtTG
userid3:$dynamic_4$c3d35357af459646513b9b6d75ae4e86$HEX$627574746572666c793a3a:$2a$12$8b5m318FP10GzXI.mtJyh.L.LFjK5iZMwen9gJ68OrkrSLJrKsq1e
userid4:$dynamic_4$7ac3af0ef869d79e28bf1e9b36e7f3aa$HEX$6461766964626f793a3a:$2a$12$XC2CQOA5agBimTPHdvcsKOVgKkDwfjXFPyZjNhCFxhxj0yZS/T9f.
userid5:$dynamic_4$a1a0d56cb1cf99b57c7b6fd8eed2361b$HEX$6c617572656e3a3a:$2a$12$4FOWYjeL4AtnSuWqP7.1NeeBejEvwBFI/K3Pjt2r0jg5RhnPF38ja
```

The other form will be same hash, but using the format type of:  ``` @dynamic=md5($s.$p),saltlen=--100@ ```  That hash type should be used for ALL accounts that have a user name longer than 22 byte.  Dyna_4 is setup to only work up to salt length of 24.

Then when you use john -show, you get this 'wonderful' output:

```
user1:987654:$2a$12$YevCi.aYHTObuVnj.oMSlOefRAmMPuk0IgiJvvTMmZ0s/aqlRddTi
user2:987654:$2a$12$THXtRY7Er7mN17qRNGAoj.5jblDk.W4./fl/yWq8e962Mf14Gasuq
user3:987654:$2a$12$QKWOSnvd7AZiKMf6IvgfRegdV6r8ZT22E9uFYviw4bh2pAM9tY2HW
user4:987654:$2a$12$vNmbOIwaT96eILMBOF.obOL/IjLy1Mtaq5.fJ7/MKxHE1tLq9o/fe
```

which is darn near ready to use to find the real password for the bcrypt.

**Comment by magnumripper** [comment]
> The lc($p) IS magic, and must be preserved

Sure, but not in the .pot file. The `lc()` does no good there. But I agree it might be too complicated to be worthwhile.

**Comment by jfoug** [comment]
I believe this would only matter on .pot strike out, and at that time, lc($p) should be ignored, yes.  As should things like salt length.  Just because a salt is too long for the current running hash (or even too short, etc), does NOT mean we should ignore any found hashes.  If they have the same hash value, then they are found.  A good example would be running a set of raw salted hashes. First using a quicker short salt format.  Then later re-running with a 'slower' long salt format. You certainly would want the .pot removal code to strike off all of the already found hashes, even if the match was not quite right.

**Comment by magnumripper** [comment]
Not sure whether this particular issue should be closed and some more generic should be opened (or maybe some alrady exist?)

**Comment by jfoug** [comment]
Ok, : done in 11f1dd5

$ is not a problem.

* is a problem, BUT it has to be fixed in john.c I think:
```
$ run/john in -form='dynamic=md5($p.$c1),c1=*x*r'
Only one wildcard allowed in format name
```

'  is not a problem.
"  is not a problem.

@
```
$ run/john in -form='dynamic=md5($p.$c1),c1=@x@r'
Unknown ciphertext format name requested
```

,
```
pass_gen does not work if comma is first char of the constant (but could do it with \xHH
```
.  is not a problem.
(  is not a problem.

)
```
$ run/john in -form='dynamic=md5($p.$c1),c1=)x)r'
Error, a c1 found in expression, but the data for this const was not provided
Dyna expression syntax error around this part of expression
md5($p.$c1),c1=)x)r
       ^
Invalid token following the . character
exiting now
```


So these chars need work:


*  (john.c I think)
@
,     (comma)
)

**Comment by jfoug** [comment]
e846601  Fixes ) char.

**Comment by jfoug** [comment]
1684923 fixes @ char

**Comment by jfoug** [comment]
I am going to ignore fixing the ```*``` char, since JtR proper lists why it is not accepted (jtr core is treating it like a wild card).

I think all issues I will fix have been fixed (special chars in constants).

**Comment by magnumripper** [comment]
This fixes `*` with no bad side effect I can imagine
```diff
diff --git a/src/john.c b/src/john.c
index ff72cfc..b8f32e6 100644
--- a/src/john.c
+++ b/src/john.c
@@ -202,6 +202,9 @@ static void john_register_one(struct fmt_main *format)
        if (options.format) {
                char *pos = strchr(options.format, '*');
 
+               if (!strncasecmp(options.format, "dynamic=", 8))
+                       pos = NULL;
+               else
                if (pos != strrchr(options.format, '*')) {
                        if (john_main_process)
                        fprintf(stderr, "Only one wildcard allowed in format "
```

**Comment by jfoug** [comment]
Cool, thanks.

**Comment by jfoug** [comment]
Are you checking that in?

**Comment by magnumripper** [comment]
No, I wasn't sure you were quite done. Feel free to do so or I'll do it tomorrow.

**Comment by jfoug** [comment]
I am done for now, and with the new gf, I usually do not even log on after work hours ;)

**Comment by jfoug** [comment]
b05fce4 : I have tested with 1, 2 and 3 ```*``` chars.  Things work fine with your code change.    Was this the last issue on this bug?

**Comment by magnumripper** [comment]
Oh right I forgot to commit that. Thanks!
