### ISSUE TITLE
Dynamic ad-hoc format: AM "complex" does not work

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1748]
```
$ ../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p).$c2.lc($s).$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73@^bhhs&#@&^@8@*$'
Unknown ciphertext format name requested
```
I think I write it correctly. Why is it not recognized at all?

**Comment by magnumripper** [comment]
Tried hexifying @ and $, no difference
```
$ ../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p).$c2.lc($s).$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs&#\x40&^\x408\x40*\x24'
Unknown ciphertext format name requested
```

**Comment by frank-dittrich** [comment]
Trying to reduce that:
```
$ ../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p).$c2.lc($s).$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73'
ERROR in dyna-parser. Have salt_as_hex_type set, but do not KNOW this type of hash
```

**Comment by frank-dittrich** [comment]
```
../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p).$c2.lc($s).$c3),c1=\x3a\x3a,c2=\x3a,c3=a,debug'
push
app_u_lc
.
app_1
.
app_p_lc
.
app_2
.
app_sh
.
app_3
f5h
ERROR in dyna-parser. Have salt_as_hex_type set, but do not KNOW this type of hash
```

**Comment by jfoug** [comment]
This should not have salt_as_hex set.  lc($s) is not a hashing function.

I think the parser is failing.  It must be using 'any' function as a salt_as hex, when parsing. It should ONLY do that for a hashing type.  The uc/lc are not really functions. They just use function-like syntax

**Comment by jfoug** [comment]
& has to be encoded   (even in '...' the shell wants to start background processes)
* 'may' have to be.

**Comment by jfoug** [comment]
```
$ ../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p).$c2.$s.$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs\x26#\x40\x26^\x408\x40\x2a\x24,saltlen=-16,debug'
push
app_u_lc
.
app_1
.
app_p_lc
.
app_2
.
app_sh
.
app_3
f5h

crc32 = 396C64FD
pExpr=md5(lc($u).$c1.lc($p).$c2.$s.$c3)
extraParams=,c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs\x26#\x40\x26^\x408\x40\x2a\x24,saltlen=-16,debug
signature=@dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs\x26#\x40\x26^\x408\x40\x2a\x24,saltlen=-16,debug@
line1=@dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3)@811c5755f866441acdb35728c21ae2af$df694488$$U87ffb1c9
line2=@dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3)@4a4f7cc851d6914842312e3efb0fc85f$a69c5744$$U4f58497b
line3=@dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3)@611e2cb6f91efec854ee95c2b2eed3bd$e0b88e64$$U35644f9d

##############################################################
#  Dynamic script for expression md5(lc($u).$c1.lc($p).$c2.$s.$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs\x26#\x40\x26^\x408\x40\x2a\x24,saltlen=-16,debug
##############################################################
Expression=dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3)
#  Flags for this format
Flag=MGF_FLAT_BUFFERS
Flag=MGF_SALTED
Flag=MGF_PASSWORD_LOCASE
Flag=MGF_USERNAME_LOCASE
#  Lengths used in this format
SaltLen=-16
MaxInputLenX86=110
MaxInputLen=110
#  The functions in the script
Func=DynamicFunc__clean_input_kwik
Func=DynamicFunc__append_userid
Func=DynamicFunc__append_input1_from_CONST1
Func=DynamicFunc__append_keys
Func=DynamicFunc__append_input1_from_CONST2
Func=DynamicFunc__append_salt
Func=DynamicFunc__append_input1_from_CONST3
Func=DynamicFunc__MD5_crypt_input1_to_output1_FINAL
#  Constants used by this format
Const1=\x3a\x3a
Const2=\x3a
Const3=\x3a73\x40^bhhs\x26#\x40\x26^\x408\x40\x2a\x24
#  The test hashes that validate this script
Test=@dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3)@811c5755f866441acdb35728c21ae2af$df694488$$U87ffb1c9:abc
Test=@dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3)@4a4f7cc851d6914842312e3efb0fc85f$a69c5744$$U4f58497b:john
Test=@dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3)@611e2cb6f91efec854ee95c2b2eed3bd$e0b88e64$$U35644f9d:passweird
```


```
$ ../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p).$c2.$s.$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs\x26#\x40\x26^\x408\x40\x2a\x24,saltlen=-16'
Benchmarking: dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3) [128/128 AVX 4x3]... DONE
Many salts:     7107K c/s real, 7111K c/s virtual
Only one salt:  4960K c/s real, 4956K c/s virtual
```

I have to 'fix' the compiler to not treat  lc($s) as a salt_as_hex type.  For the above test, I removed the lc($s) and just use $s.  Other than missing a dyna startup flag, the above format 'would' work. And if all the salts were already lower case in the input data, then this 'would' work.

**Comment by magnumripper** [comment]
> & has to be encoded   (even in '...' the shell wants to start background processes)
```*``` 'may' have to be.

I can't see why any of them would have to be escaped. We are inside single quotes already so the shell is not involved at all - **all** problems here are the format's problems.

I can buy that `@` and `:` need escaping since both have meanings to JtR.

**Comment by magnumripper** [comment]
OK, it was the `*`, not the `&`. I would like to know why `*` needs escaping. It's not used in dynamic, is it?

**Comment by magnumripper** [comment]
OK, here's why. Might even be my fault :stuck_out_tongue_closed_eyes: 
```
$ git grep -C1 '"\*"' dynamic*c
(...)
dynamic_fmt.c-
dynamic_fmt.c:  if (options.format && strstr(options.format, "*"))
dynamic_fmt.c-          wildcard = 1;
```

**Comment by magnumripper** [comment]
> This should not have salt_as_hex set. lc($s) is not a hashing function.

> I think the parser is failing. It must be using 'any' function as a salt_as hex, when parsing. It should ONLY do that for a hashing type. The uc/lc are not really functions. They just use function-like syntax

I tried to find this but can't see where it happens?

**Comment by magnumripper** [comment]
Scrap that remark. It happens in `comp_optimize_expression()`.

**Comment by magnumripper** [comment]
This seems to address the problem
```
diff --git a/src/dynamic_compiler.c b/src/dynamic_compiler.c
index 47b6fa8..cfe5f23 100644
--- a/src/dynamic_compiler.c
+++ b/src/dynamic_compiler.c
@@ -1040,9 +1040,11 @@ static char *comp_optimize_expression(const char *pExpr) {
                }
                if (n1 == n2) {
                        // ok, all were same hash type.  Now make sure all $s are in crypt($s)
+                       // Ignore lc() and uc() */
                        n2 = 0;
                        p = strstr(pBuf, "$s");
-                       while (p) {
+                       while (p && (p[-1] != '(' || p[-2] != 'c' ||
+                                    (p[-3] != 'l' && p[-3] != 'u'))) {
                                ++n2;
                                p = strstr(&p[1], cpType);
                        }
```
But it ends up with an other problem
```
Dyna expression syntax error around this part of expression
md5(lc($u).$c1.lc($p).$c2.lc($s).$c3)
                          ^
Invalid token following the . character
```

**Comment by magnumripper** [comment]
OK... `lc($s)` is simply not supported yet while `lc($u)` and `lc($p)` are. So I think my patch above is correct, but we also need to actually support `lc($s)`.

**Comment by magnumripper** [comment]
We don't even have MGF_SALT_LOCASE

**Comment by magnumripper** [comment]
I'll admit it's not very relevant to support `lc($s)` or `uc($s)` even though it'd be nice in this case. The easy solution is to prepare the input file correctly.

**Comment by magnumripper** [comment]
I will actually commit the patch above. It's relevant for getting the proper error, and if we'll support case-correcting `$s` in the future, it still stands.

Other than that, this issue is more or less PEBCAK.

**Comment by magnumripper** [comment]
So @jfoug I'll let you decide: Either close this now, or implement lc/uc for salt.

Oh, and we should document which characters need escaping.

**Comment by jfoug** [comment]
this 'fixes' the lc($s) not parsing, but there are only 2 valid uc/lc situations. That is user name and pass.

Remind me why casing of the salt is needed?  Can't it just be properly built in the first place??

**Comment by magnumripper** [comment]
Yeah, sure. I just wrote it as `lc($s)` from a writeup about AM hashes. The solution is preparing the input.

I'm fine with this issue being closed now that we get the proper error.

**Comment by jfoug** [comment]
it's not an error if you are not 'trying' to support lc($s), but since lc() will parse (as will any expression.

wow. I just thought of something, do not submit that yet

**Comment by magnumripper** [comment]
I already committed that SALT_AS_HEX parsing fix.

**Comment by jfoug** [comment]
We have to whitelist what is allowed, not black list.  Take this point

md5($p.fuckoff($s))

I think that will parse properly, because the optimizer will turn it into md5($p.$s), and set the 'this hash uses salt-as-hex' flag

**Comment by magnumripper** [comment]
LOL so fuckoff() is a no-op

**Comment by jfoug** [comment]
:)  But then it will fail to find FUCKOFF_SALT_AS_HEX flag when later trying to emit the flag

**Comment by magnumripper** [comment]
I'm laughing so much my wife will wake up. We definitely should have a FUCKOFF_SALT_AS_HEX flag just for the hell of it.

**Comment by jfoug** [comment]
what I am saying is that the optimizer will have to white list (that sucks, because now I have to edit that WL every time I add a crypt type.  So it will ONLY work for md5($s), or sha1($s) and anything else, it leaves alone, so that the original text is in there, and the parser will have context on what 'bad' part of the expressino was seen

**Comment by magnumripper** [comment]
Yes I see what you mean. Unless you can find a nice way with that CPP magic stuff.

**Comment by jfoug** [comment]
it will be with cpp magic, but it is just another edit point, no different than the rest.  I just put a magic signature, then search for that, and wherever it is found, I figure out what needs to be there, and add it.  At least I am not writing code into each of the 30 or so edit points.

**Comment by magnumripper** [comment]
But this all can wait now. We should fix #1746 but I'm lost there.

**Comment by jfoug** [comment]
it will be a macro that does something like:

CHK(A,B) if (offset > B && !strncmp(&p[- B], A)) valid=1

Then have a set of macros like:

valid=0;
CHK("md5(",4); CHK("md4(",4); CHK("sha1(",5); ....
if(valid) { /* do the logic */ }

**Comment by magnumripper** [comment]
No, not #1746, I meant the build bot problems. We should open an issue for that.

**Comment by jfoug** [comment]
I am leaving things alone right now, letting you dig in a bit.  You might hopefully find stupid things I am doing, and help fix some design problems, in your digging in to understand just wtf is going on.

**Comment by jfoug** [comment]
One thing I may end up doing, is to not use the parsed reverse polish type data, other than to syntax check, and then later to run to get the test vars. I may re-do the code emission module to work directly from the original expression.  I toyed with that a bit, but stopped the implementation about the time the AM leak sprung.  Going from that recursive stack machine, to a 2 variable large instruction set system where all you can do is overwrite/append/clear/hash, does not map well at all.  Although I 'may' do this by building a 2nd emulator, and actually RUNNING the code again, keeping track of the state of the machine, so that I know var 1 is free, var 2 is used for this part of the sub expression, etc, etc.  IF I can get the code working like that, then it would be about as perfect as you can get.If you can actually do the expression by hand, that type of a parser could build a script to do it.  It is no where NEAR that powerful today. It works for many common cases, but falls apart when there are more than 2 parts of the sub expression that need to be tracked and worked on at the same time.

**Comment by magnumripper** [comment]
Anyway this issue can be closed. The following works:
```
$ ../run/john -test -form:dynamic='md5(lc($u).$c1.lc($p).$c2.$s.$c3),c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs&#\x40&^\x408\x40\x2a$'
Benchmarking: dynamic=md5(lc($u).$c1.lc($p).$c2.$s.$c3) [256/256 AVX2 8x3]... DONE
Many salts:	9189K c/s real, 9189K c/s virtual
Only one salt:	7103K c/s real, 7103K c/s virtual
```

Verify the escapes:
```
$ echo -e 'c1=\x3a\x3a,c2=\x3a,c3=\x3a73\x40^bhhs&#\x40&^\x408\x40\x2a$'
c1=::,c2=:,c3=:73@^bhhs&#@&^@8@*$
```

Email address has to be lower-cased in input file, as in
```
username:<md5 hash>$email@address
```
