### ISSUE TITLE
Introduce AVX-512's ternary logic instruction

### ISSUE THREAD

**Issue by zzlei** [magnumripper/JohnTheRipper#1749]
Theoretically, all 3-argument operations like `SHA1_I()` can be implemented with just one ternary logic instruction.

However, one thing that bothers me a bit is that simd-intrinsics.c might eventually be bloated with things like `#if ... #else ... #endif`, which I (we) wish to appear only in pseudo-intrinsics.h.

**Comment by magnumripper** [comment]
I see what you mean but I think it's the right thing for now. Compare with HAVE_ANDNOT or whatever it was we just introduced. It's sensible.

If you come up with a better idea I'm all ears though!

**Comment by magnumripper** [comment]
So what is this, bitselect() on acid? Can we implement *any* MD4/5/SHA function using a single instruction?

**Comment by magnumripper** [comment]
I can't find it in https://software.intel.com/sites/landingpage/IntrinsicsGuide

**Comment by magnumripper** [comment]
https://software.intel.com/en-us/node/523807

**Comment by zzlei** [comment]
> So can we implement any MD4/5/SHA function using a single instruction?

Not necessarily. But at least they can be compacted to use much fewer instructions.

**Comment by magnumripper** [comment]
But if the function is `F(x, y, z)` it should always be implementable with a single instruction, no? You'd just need a trivial tool to find out the truth table.

**Comment by magnumripper** [comment]
OK, not if there are bit shifts within the function of course. But as long as there's only and, or, not and so on, in any combination.

**Comment by zzlei** [comment]
I have a question regarding to the code: what's the difference between `MD5_H()` and `MD5_H2()`? It seems to me they are doing the same thing, i.e. `x^y^z`.

Then why are the operands written in different orders?
```c
#define MD5_H(x,y,z)                            \
    tmp[i] = vxor((x[i]),(y[i]));               \
    tmp[i] = vxor((tmp[i]),(z[i]));

#define MD5_H2(x,y,z)                           \
    tmp[i] = vxor((y[i]),(z[i]));               \
    tmp[i] = vxor((tmp[i]),(x[i]));
```

**Comment by magnumripper** [comment]
They are originally like this
```
#define H(x, y, z)			(x ^ y ^ z)
(...)
    H(a, b, c, d, k)
    H(d, a, b, c, k)
    (...)
```
If you expand that, you'll see that we do `a ^ b` twice. So with this optimization we store the result from the first and re-use it.

**Comment by magnumripper** [comment]
BTW for plain scalar C, we just do it like this. It merely hints to the optimizer that it should do the same thing (and a good optimizer might see it anyway):
```
#define H(x, y, z)          ((x ^ y) ^ z)
#define H2(x, y, z)         (x ^ (y ^ z))
(...)
    H(a, b, c, d, k)
    H2(d, a, b, c, k)
    (...)
```

**Comment by zzlei** [comment]
I'm using this command `./configure CC="gcc-5 -mavx512f" --host=x86_64-linux`, but it still got configured as AVX2. Any hint about this?

**Comment by magnumripper** [comment]
When I tried a while ago, gcc could produce the assembler but as(1) didn't understand the new instructions. Maybe this is the case here for you?

**Comment by zzlei** [comment]
Oh, I figured it out. When compiling some non-AVX512 test code in ./configure, gcc generated code that can execute natively. Although I used `--host=x86_64-linux`, it's still not configured as cross-compiling.

OTOH, when compiling the same test code, icc emitted some AVX512 instructions in the generated code, which cannot run natively. So ./configure correctly recognized it as cross-compiling.

Is there a way that I can force ./configure to cross-compile?

**Comment by magnumripper** [comment]
--disable-native-tests should fix that

**Comment by zzlei** [comment]
> --disable-native-tests should fix that

Oh, thanks! That's exactly what I'm looking for.

**Comment by magnumripper** [comment]
Done in #1762. Good stuff!
