### ISSUE TITLE
Formats which should handle input hash case changes in some manner (fixing or rejecting) (found by Kai's patch)

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1752]
This patch https://github.com/loverszhaokai/JohnTheRipper/commit/01abf3ff176d371441b979fb750c885d3c91f0d9 found some formats which maybe should unify cases in split() and add FMT_SPLIT_UNIFIES_CASE. 
**Most of these formats have been found by Jim's patch**. See https://github.com/magnumripper/JohnTheRipper/issues/1742
There are many formats which my patch did not catch but Jim's patch did.

**Both found by Jim's patch and my patch**:

- [ ] chap
- [ ] eCryptfs
- [ ] eigrp
- [ ] EPI
- [ ] keystore
- [ ] MD2
- [ ] MongoDB
- [ ] Mozilla
- [ ] mssql
- [ ] mssql05
- [ ] mssql12
- [ ] ODF
- [ ] Office
- [ ] OpenBSD-SoftRAID
- [ ] oracle11
- [ ] Oracle12C
- [ ] Panama
- [ ] PBKDF2-HMAC-MD5
- [ ] pomelo
- [ ] postgres
- [ ] PST
- [ ] RACF
- [ ] RAdmin
- [ ] RAR5
- [ ] rsvp
- [ ] skey
- [ ] Snefru-128
- [ ] Snefru-256
- [ ] sxc
- [ ] VNC
- [ ] vtp
- [ ] wbb3
- [ ] has-160

**Only found by my patch**:

- [ ] Blackberry-ES10
- [ ] cq
- [ ] hdaa
- [ ] krb5-18
- [ ] lp
- [ ] lotus5
- [ ] LUKS
- [ ] mdc2
- [ ] PBKDF2-HMAC-MD4

**Comment by jfoug** [comment]
I am going to close this one, and add the new found items to #1472

**Comment by magnumripper** [comment]
You meant #1742 (luckily there was a link right above your post)
