### ISSUE TITLE
Non-iterated SHA-2 OpenCL formats unusable with many hashes

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1753]
http://www.openwall.com/lists/john-dev/2015/09/13/14

*I think we might in fact want to revert the non-iterated SHA-2 GPU formats to prior to Claudio's implementation of hash comparisons on GPU, which mostly made things worse (way too slow when cracking more than a handful of hashes - turned out to be unusably slow in the recent contest).  myrice's implementations worked better (and IIRC had no GPL restrictions on them too).*

@claudioandre are you aware of this problem?

**Comment by magnumripper** [comment]
See #676 for why we dropped Myrice's SHA-512 formats.

**Comment by claudioandre** [comment]
I'll try to find the Myrice's file on git history!

Just wait a day or two.

2015-09-13 13:19 GMT-03:00 magnum <notifications@github.com>:

**Comment by magnumripper** [comment]
185333e4 dropped the format files from unused, and c5f50a90 dropped the kernel too.

**Comment by claudioandre** [comment]
Ok, I will get them from there (but I'm not sure they will work at all).

Moving my format to be a '-ng' now.

**Comment by claudioandre** [comment]
I can't compile Myrice code. Seems API changed meanwhile.

Myrice wasn't active when the code was dropped, I'm affraid he is not active now.

**Comment by claudioandre** [comment]
Ok, I finished to read the thread now. 
- @magnumripper said it can revert (I did, but failed to compile. There are some API chances - at least).

That said, I'm affraid I can't fix Myrice file right now.
---

I can leave a maskless version of 'my' own format as a replacement (while waiting for Myrice).

Working on this now (any known regression will be fixed).

**Comment by magnumripper** [comment]
So should I merge #1755? Then I could try to fix Myrice's format.

**Comment by claudioandre** [comment]
Just wait a few minutes.

**Comment by claudioandre** [comment]
You can merge now.
- I reverted raw-sha512-opencl to its previous 'maskless' version. 

So, meawhile you fix Myrice code, the version available  has no regressions dealing with a lot  of hashes (got what I mean?).

**Comment by magnumripper** [comment]
ae78af6a put Myrice's formats back. They need auto-tuning and shit fixed so issue remains open.

**Comment by magnumripper** [comment]
> They need auto-tuning and shit fixed

Auto-tuning and shit fixed.
