### ISSUE TITLE
Regex mode: Generator or amplifier.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1757]
See also #1756 

If regex contains `\0`, we are in "hybrid regex" mode, ie. regex is an amplifier.

**Comment by magnumripper** [comment]
Is there any point in supporting eg. `-mask -regex` or `-markov -regex` at all?

**Comment by magnumripper** [comment]
> If regex contains `\0`, we are in "hybrid regex" mode, ie. regex is an amplifier.

We also have the "alpha" feature of wordlist+regex, which doesn't use `\0`.

**Comment by magnumripper** [comment]
Minor fixes in de75990

**Comment by magnumripper** [comment]
Closing until librexgen gets stable enough to bother with

**Comment by frank-dittrich** [comment]
Wouldn't it have been better to keep it open, remove the 1.8.0-jumbo-2 milestone and the "Maintenance/cleanup" tag, and add the " notes/external issues" tag if stability fixes in rexgen are a precondition?

**Comment by magnumripper** [comment]
No

Sent from my iPhone
