### ISSUE TITLE
Consider using Judy array for OpenCL formats

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1761]
http://www.openwall.com/lists/john-dev/2015/09/12/12

**Comment by claudioandre-br** [comment]
Bug closed as:

* **Low Priority** - They have a tendency to become high priority if enough of the users complain.

* **Business Priority** - Obsolete hardware and software. Hardware nobody owns, etc.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action.
  * Nobody cares.
  * Can't reproduce, working as intended, obsolete.
  * Required information was not provided.
****
BTW: when I implemented Bloom Filter I considered Judy not suitable for GPUs.

**Comment by solardiz** [comment]
Related: @alainesp's https://github.com/alainesp/Practical_Research/blob/master/research_cuckoo_cbg.md
