### ISSUE TITLE
Long standing 'bug' in common.c

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1766]
```C
const char itoa16[16] =
	"0123456789abcdef";
const char itoa16u[16] =
	"0123456789ABCDEF";
```

Not quite sure how/if to fix this one.   It may actually be by design, BUT I am not 100% sure it will have the same behavior always (such as in ASAN builds, etc).  I would also assume that this behavior would vary based upon compiler.

itoa16 is actually 0123456789abcdef0123456789ABCDEF since the null byte of itoa16 is overwritten by the first byte of itoa16u.  Also, the null byte of itoa16u is past the end of it's 'owned' buffer, thus reading it like a string should trip some ASAN read-past error (but I would assume the same thing for itoa16)

**Comment by magnumripper** [comment]
No, you are wrong. In C++ you are right, but not in C. We have discussed this on john-dev.

In C, those declarations will be without the ending null.

**Comment by jfoug** [comment]
But one 'bug'

**Comment by magnumripper** [comment]
LOL, but the bug is in your printf. It's not a cstring. It's an array of chars.

**Comment by magnumripper** [comment]
http://www.openwall.com/lists/john-dev/2013/02/10/12

**Comment by jfoug** [comment]
So then this code should be viewed as invalid in it's usage:

```C
ipb2 format
static int valid(char *ciphertext, struct fmt_main *self)
{
	if (strncmp(ciphertext, "$IPB2$", 6) != 0)
		return 0;

	if (strlen(ciphertext) != CIPHERTEXT_LENGTH)
		return 0;

	if (ciphertext[16] != '$')
		return 0;

	if (strspn(ciphertext+6, itoa16) != SALT_LENGTH*2)
		return 0;

	if (strspn(ciphertext+17, itoa16) != MD5_HEX_SIZE)
		return 0;

	return 1;
}
```

**Comment by magnumripper** [comment]
That is a bug, yes. And I seem to be the author :sunglasses: 

So the question is whether we should fix **that** bug or change the definitions to `[17]` or even `[]` and be done with it.

**Comment by jfoug** [comment]
I was 'correcting' my post when you posted,  Read above.

**Comment by jfoug** [comment]
Note, I am working on the ibp2 issue. I am going down the list of all the split-case issues.  This one just stood out, because it 'appears' to be right.

**Comment by magnumripper** [comment]
I thing your suggestion is better. We might even want one that allows any case
```
#define HEXCHARSl "0123456789abcdefABCDEF"
#define HEXCHARSl "0123456789abcdef"
#define HEXCHARSu "0123456789ABCDEF"
```
But then it must be used with things like strspn only, so we don't end up parsing eg. 0xD as 19...

**Comment by jfoug** [comment]
I agree with that, OR we should 'enhance' the ishex*() into something like ishexn() and ishexlcn() that pass a length in.

Straight ishex() expects the whole string to be hex or it returns false.   Then we simply use those, vs using the strspn stuff at all. the ishex is probably much faster anyway, since it is a repeated table lookup.

**Comment by jfoug** [comment]
How about this:

```diff
$ git diff common.[ch]
diff --git a/src/common.c b/src/common.c
index dd66f4b..67d32bb 100644
--- a/src/common.c
+++ b/src/common.c
@@ -18,14 +18,11 @@

 /* This is the base64 that is used in crypt(3). It differs from MIME Base64
    and the latter can be found in base64.[ch] */
-const char itoa64[64] =
-       "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
+const char itoa64[64] = BASE64_CRYPT;
 unsigned char atoi64[0x100];
+const char itoa16[16]  = HEXCHARS_lc;
+const char itoa16u[16] = HEXCHARS_uc;

-const char itoa16[16] =
-       "0123456789abcdef";
-const char itoa16u[16] =
-       "0123456789ABCDEF";
 unsigned char atoi16[0x100], atoi16l[0x100], atoi16u[0x100];

 static int initialized = 0;
diff --git a/src/common.h b/src/common.h
index b123637..21e98be 100644
--- a/src/common.h
+++ b/src/common.h
@@ -77,6 +77,12 @@ typedef unsigned long long ARCH_WORD_64;
 /*
  * ASCII <-> binary conversion tables.
  */
+#define DIGITCHARS   "0123456789"
+#define HEXCHARS_lc  DIGITCHARS"abcdef"
+#define HEXCHARS_uc  DIGITCHARS"ABCDEF"
+#define HEXCHARS_all DIGITCHARS"abcdefABCDEF"
+#define BASE64_CRYPT "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
+
 extern const char itoa64[64]; /* crypt(3) base64 - not MIME Base64! */
 extern unsigned char atoi64[0x100];
 extern const char itoa16[16];
```

**Comment by magnumripper** [comment]
Looks fine to me. It will clash a little with any core changes but then again it already did. BTW Solar has contributed lots of code directly to Jumbo lately, which is much more pleasant than CVS merges...

**Comment by jfoug** [comment]
I have added a bit more.  It is here.  24e5f75    Added are ishexn*() class of functions (adding a length), and l and u functions for hexlen()

If there is too much (additional merge issues), then we can redo this.  NOTE, I have not started to use these defines in any formats (yet), but it will be easy to add.   strspn is a good 'start', but then looking for the actual strings would work also.

**Comment by magnumripper** [comment]
We still need to change IPB, right?

**Comment by jfoug** [comment]
Correct.  Sorry, I got interrupted by 'work', lol.

**Comment by jfoug** [comment]
I closed this, but we probably should look at using the macros in common.h vs inlined stuff inside of functions.

A good 'start' is to grep c source for strspn.  But those are just cleanup, and not a bug fix.
