### ISSUE TITLE
Implement --show=invalid

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1773]
If I have a file which should contain 10000 valid hashes of a given format (say bcrypt), but john claims to only find 9998 valid hashes, I'd like to have an easy way to identify the few invalid hashes, e.g., by running `./john --show=invalid my_file --format=bcrypt`

**Comment by jfoug** [comment]
I like this option, and will get on it.  

Should there be a requirement that the --format= flag be used?

**Comment by magnumripper** [comment]
Please place any commits for this in a topic branch for review. I also like the idea but we need to be careful not ruining recent huge speedups.

**Comment by magnumripper** [comment]
> Should there be a requirement that the --format= flag be used?

I think it will be very hard to implement (or slow as h3ll) otherwise but that's just a guess.

**Comment by frank-dittrich** [comment]
I wouldn't mind if you require --format=name (to be revised later if it turns out running that command doesn't take too long).
You can just run :/john without --format on that file to see what formats are in it.

**Comment by frank-dittrich** [comment]
> Please place any commits for this in a topic branch for review. I also like the idea but we need to be careful not ruining recent huge speedups.


If that is a separate routine, you would hardly have a performance impact for existing functionality.

**Comment by jfoug** [comment]
This change is SUPER trivial, and does NOT impact any hot path.

This is the entire change (in loader)

```diff
static void ldr_show_pw_line(struct db_main *db, char *line)
{
	int show, loop;
	char source[LINE_BUFFER_SIZE];
+	char orig_line[LINE_BUFFER_SIZE];
	struct fmt_main *format;
	char *(*split)(char *ciphertext, int index, struct fmt_main *self);
	int index, count, unify;
	char *login, *ciphertext, *gecos, *home, *uid;
	char *piece;
	int pass, found, chars;
	int hash;
	struct db_cracked *current;
	char utf8login[LINE_BUFFER_SIZE + 1];
	char utf8source[LINE_BUFFER_SIZE + 1];
	char joined[PLAINTEXT_BUFFER_SIZE + 1] = "";

+	if (db->options->showinvalid)
+		strnzcpy(orig_line, line, sizeof(orig_line));
	format = NULL;
	count = ldr_split_line(&login, &ciphertext, &gecos, &home, &uid,
		source, &format, db->options, line);
	if (!count) return;

+ /* If we are just showing the invalid, then simply run that logic */
+	if (db->options->showinvalid && count == -1) {
+		printf ("%s",orig_line);
+		return;
+	}

 /* If just one format was forced on the command line, insist on it */
	if (!fmt_list->next && !format) return;
```

> I think it will be very hard to implement (or slow as h3ll) otherwise but that's just a guess.

That was my thoughts also, BUT if the input file is a proper 'solid' file of 1 type hash, then it works fine without forcing the -format.  I have the forced logic in, but will have it commented out. If we later need to add it, then we can.

**Comment by jfoug** [comment]
Let me finish some testing and get this in. I was happy at how easy it worked.This is sample 'output'

```
bcrypt:$2a$05sCCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW:U*U
bcrypt:$2a$05sCCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK:U*U*
0 password hashes cracked, 4 left

```

**Comment by jfoug** [comment]
NOTE, within the ldr_show_pw_line() function, we 'may' also want to return if count==-1 (just like we do if count==0)

**Comment by jfoug** [comment]
Have a test please. I think things are working fine, and this is certainly GOOD helpful logic.

**Comment by frank-dittrich** [comment]
The change should also be documented (and may mentioned for --list=hidden-options

**Comment by frank-dittrich** [comment]
Now I realize I could have done 

```
./john --show=types my_file |LC_ALL=C grep -v ":bcrypt:"
```
But --show=invalid --format=bcrypt should be faster.

**Comment by jfoug** [comment]
It still needs documented. It is on --list=hidden-options.  I was not going to document until we made our mind on if the -format=xx was going to be force required. 

In the current code, I do not.

**Comment by jfoug** [comment]
NOTE, in the way I did this, if you provide a .pot file that has many of the hashes cracked, then it will 'show' those also.  If that is a problem, we can easily work around that, by always returning in this mode, not completing the function.  I left the default code in there to get a count of 'valid' hashes also.

**Comment by jfoug** [comment]
I have made changes, so that in the -show=invalid, it simply prints out invalid, and nothing else.  Also, the OPTIONS file is updated. I added a stub comment for the -show=types  I was not aware of that function, so what I put there may not be 100% complete or right.  Please check and change it if it needs to be.

**Comment by jfoug** [comment]
This issue 'may' be done. I think it is, and should have no impact to any part of john if not using the -show=invalid switch.

**Comment by frank-dittrich** [comment]
I really prefer the version where --show=invalid would not print any cracked passwords, 

Also, I would prefer if the summary line "%d passwords cracked, %d left" would go to stderr instead of stdout (similar to what --show=left does).

**Comment by frank-dittrich** [comment]
Or may be just suppress that summary (similar to options.loader.showtypes)

**Comment by magnumripper** [comment]
> I would prefer if the summary line "%d passwords cracked, %d left" would go to stderr instead of stdout (similar to what --show=left does).

That output is not specific for this feature so we can't change it unconditionally. But it's still doable.

> Or may be just suppress that summary (similar to options.loader.showtypes)

I think I want it. It's a good summary.

**Comment by magnumripper** [comment]
Fixed

**Comment by jfoug** [comment]
Ok, are we good with this enhancement?  If so, someone can close it.

I think this was a great idea.  I will certainly use it. It has always been tough to chop a file up into 5 million line subfiles, only to find that 18 records were not right.  Yea right, go find those needles in the haystack.  Now with this change, it is easy.   Yes, @frank-dittrich did find a viable workaround method, but that would even take a bit of extra time if it had to output and parse all 5 million lines.

**Comment by frank-dittrich** [comment]
Thanks, @jfoug and @magnumripper

**Comment by magnumripper** [comment]
:+1: this is very usable both for development and use.

**Comment by jfoug** [comment]
Agreed.  It is kind of a head slap moment. About like when you added the vector command to pass_gen.pl.   Something we should have had a LONG time ago, and I was quite happy with how easily things went together.

**Comment by magnumripper** [comment]
After d50ef36 the hash counts were always zero so 7536bef ended up pointless. I dropped it in 2d1d5dd.

**Comment by jfoug** [comment]
We 'could' have changed to have # valid and # invalid?  Would still be easy to do, if we think that would be helpful.  Until I 'saw' the vars used, I was not sure where the numbers came from (and did not spend time digging into to find out). Now that the vars are apparent, we can easily list how many good, how many bad, and then change the output to state that fact (to stderr).

**Comment by jfoug** [comment]
```
$ cat in
bcrypt:$2a$05$CCCCCCCCCCCCCCCCCCCCC.7uG0VCzI2bS7j6ymqJi9CdcdxiRTWNy:::
bcrypt:$2a$05sCCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW:::U*U
bcrypt:$2a$05sCCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK:::U*U*
bcrypt:$2b$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a:::U*U*U
bcrypt:$2a$05$CCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW:::U*U
bcrypt:$2a$05$CCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK:::U*U*


$ ../run/john -show=invalid in.txt
bcrypt:$2a$05sCCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW:::U*U
bcrypt:$2a$05sCCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK:::U*U*
4 valid hashes, 2 invalid hashes
```

How does that 'look' ?  I have to test just a touch, but it was super trivial to add. That was why I was initially letting the data 'pass-through' in that loader function, I was hoping to get to that type output.

Also, the ```4 valid hashes, 2 invalid hashes``` goes to stderr, not stdout, so will not pollute a file.

**Comment by magnumripper** [comment]
You did in slightly wrong: Numbers were totally incorrect for split hashes like LM. You need to actually use the **value** of `count` (it may be 2 or more). Fixed in 55ffbb2.

I also fixed your terrific deviation from core. Your diff against core was like this:
```diff
                                ldr_show_pw_file(&database, current->data);
                        } while ((current = current->next));
 
-                       printf("%s%d password hash%s cracked, %d left\n",
-                               database.guess_count ? "\n" : "",
-                               database.guess_count,
-                               database.guess_count != 1 ? "es" : "",
-                               database.password_count -
-                               database.guess_count);
+                       if (john_main_process && !options.loader.showtypes) {
+                               int left = database.password_count - database.guess_count;
+                               if (options.loader.showinvalid)
+                                       fprintf(stderr,
+                                               "%d valid hash%s, %d invalid hash%s\n",
+                                               database.guess_count,
+                                               database.guess_count != 1 ? "es" : "",
+                                               left,
+                                               left != 1 ? "es" : "");
+                               else
+                                       printf("%s%d password hash%s cracked, %d left\n",
+                                               database.guess_count ? "\n" : "",
+                                               database.guess_count,
+                                               database.guess_count != 1 ? "es" : "",
+                                               left);
+                       }
+                       fmt_all_done();
 
                        return;
                }
```

After my fixes it's like this:
```diff
                                ldr_show_pw_file(&database, current->data);
                        } while ((current = current->next));
 
+                       if (john_main_process && options.loader.showinvalid)
+                       fprintf(stderr,
+                               "%d valid hash%s, %d invalid hash%s\n",
+                               database.guess_count,
+                               database.guess_count != 1 ? "es" : "",
+                               database.password_count,
+                               database.password_count != 1 ? "es" : "");
+                       else
+                       if (john_main_process && !options.loader.showtypes)
                        printf("%s%d password hash%s cracked, %d left\n",
                                database.guess_count ? "\n" : "",
                                database.guess_count,
```
This makes a world of difference when merging core.

**Comment by jfoug** [comment]
I will keep that in mind, at maintenance of WS is critical.

So I can just use 'origin/master' to see what damage changes would cause to core?  I will also keep that in mind.  Both versions are very similar, but I agree, a block of ++++ vs the ----+++++ is much better.

**Comment by magnumripper** [comment]
Yeah it's not about me understanding the change, it's about Git understanding it. The adds-only will never ever need manual attention when merging. The other one will for sure, as soon as Solar touches a single bit of it in core. That's also why I rather violate the "coding style" (not indenting the core line when introducing `if (john_main_process)`). I don't give a shit about coding style in that situation :-)

All this is rather silly though - it's a weird situation with a core origin that we can't touch and that lives in CVS. We just have to live with it.
