### ISSUE TITLE
SessionFileProtect problem in batch mode

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1774]
Without any mode option, john will fail when switching from --single mode to --wordlist mode.
May be we need to find a place to check this before forking. Too bad it can't be in the same place as LogFileProtect check.

**Comment by magnumripper** [comment]
> Or may be we can't move the SessionFileProtect checks into log_init().
While --nolog isn't a problem --stdout is (log_init isn't called for --stdout).

Maybe we can have -stdout call log_init() - but imply -nolog?

**Comment by frank-dittrich** [comment]
Tha would work (and add one more core deviation)

**Comment by magnumripper** [comment]
That's a deviation we can live with. The really bad merge troubles are core changes to loader/cracker stuff if we deviate much (or unwisely).

**Comment by magnumripper** [comment]
@frank-dittrich -stdout now calls log_init(). Feel free to work with this if/when you got the time.

**Comment by magnumripper** [comment]
Can't be done in log_init(). It's simply too early. I just added a hack for batch mode.

**Comment by magnumripper** [comment]
I guess I should revert f69d8d3d.

**Comment by frank-dittrich** [comment]
Why is checking for an existing .rec file in log_init() too early?

**Comment by magnumripper** [comment]
I spent all of yesterday trying to make it work. Several problems, most stemming from the fact node number(s) are not known yet. I sort of got it working, with huge deviations from core and too messy to commit.

It's a pity though because it really bailed out immediately as opposed to after a spending a good while loading hashes and parsing pots. I still have the code, in case I get a lightbulb moment.

**Comment by frank-dittrich** [comment]
@magnumripper Why would we care about node numbers?
Just check for the "main" .rec file.
If that one doesn't exist, a session.2.rec file is of little use anyway, so there would be no problem overwriting it.

**Comment by magnumripper** [comment]
Yeah that works in the -fork case, but with MPI we already run *n* processes and they are mostly *totally unsynchronized* (which is a feature and a design choice). This means the main node might create the (new) file and only then, node 163 checks for it and sees it's already there. And bails out.

Things like that. Many moving parts involved.
