### ISSUE TITLE
Travis/Circle warnings

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1785]
Travis gcc
```
postgres_fmt_plug.c: In function ‘valid’:
postgres_fmt_plug.c:112:2: warning: passing argument 1 of ‘hexlenl’ discards ‘const’ qualifier from pointer target type [enabled by default]
common.h:120:5: note: expected ‘char *’ but argument is of type ‘const char *’
postgres_fmt_plug.c:119:2: warning: passing argument 1 of ‘hexlenl’ discards ‘const’ qualifier from pointer target type [enabled by default]
common.h:120:5: note: expected ‘char *’ but argument is of type ‘const char *’
```

Travis clang
```
lotus85_fmt_plug.c:59:19: warning: unused variable 'LOTUS85_BASE16_CHARSET'
      [-Wunused-const-variable]
static const char LOTUS85_BASE16_CHARSET[] = "0123456789ABCDEFabcdef";
                  ^
1 warning generated.
postgres_fmt_plug.c:112:14: warning: passing 'const char *' to parameter of type
      'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
        if (hexlenl(&p[1]) != 2*BINARY_SIZE)
                    ^~~~~
./common.h:120:19: note: passing argument to parameter 'q' here
int hexlenl(char *q); /* lower cased only */
                  ^
postgres_fmt_plug.c:119:18: warning: passing 'const char *' to parameter of type
      'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
        if (abs(hexlenl(&p[1])) != 8)
                        ^~~~~
./common.h:120:19: note: passing argument to parameter 'q' here
int hexlenl(char *q); /* lower cased only */
```

Circle
```
postgres_fmt_plug.c: In function 'valid':
postgres_fmt_plug.c:112:14: warning: passing argument 1 of 'hexlenl' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  if (hexlenl(&p[1]) != 2*BINARY_SIZE)
              ^
In file included from postgres_fmt_plug.c:35:0:
common.h:120:5: note: expected 'char *' but argument is of type 'const char *'
 int hexlenl(char *q); /* lower cased only */
     ^
postgres_fmt_plug.c:119:18: warning: passing argument 1 of 'hexlenl' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  if (abs(hexlenl(&p[1])) != 8)
                  ^
In file included from postgres_fmt_plug.c:35:0:
common.h:120:5: note: expected 'char *' but argument is of type 'const char *'
 int hexlenl(char *q); /* lower cased only */
     ^
```

**Comment by magnumripper** [comment]
Another one in another CircleCI build
```
options.c: In function 'opt_init':
options.c:472:28: warning: implicit declaration of function 'strcasestr' [-Wimplicit-function-declaration]
   else if (options.mask && strcasestr(options.mask, "?w")) {
                            ^
```
Not sure why that happens in just one build. I don't even know what build that is - MinGW? 32-bit non SIMD?

**Comment by jfoug** [comment]
```
#if AC_BUILT && !HAVE_STRCASESTR || !AC_BUILT && defined(__MINGW__)
char *strcasestr(const char *haystack, const char *needle);
#endif
```
the ```||``` in the if is being added.  NOTE, we are doing mingw without a configure, (legacy).  That is why this 'implicit' warning is happening, I think.   That the code LINKS bothers me. It means that mingw actually must 'have' that function, it simply does not expose it, at least in the same way that we have header includes.   So I am adding the same OR block to the jumbo.c file also.  NOTE, it may cause the mingw build to fail (multiple defined at link time).  We will have to see.  But if we are going to use our declaration, we should use our definition of the function.  The mingw 'could' be defined in a dll or something, so I am not sure about this one.  But the implementation we have is safe and matches 100% what is declared in jumbo.h (albet a little slow).

**Comment by jfoug** [comment]
I will check things in, but not close this, until I see that the CI's are building without these warnings. I am not getting them on my builds (cygwin and fedora) but since this bug is against the CI's, I want to make sure they are happy, AND I do not have clang installed, so can not check against that.

**Comment by jfoug** [comment]
NOTE, all of the common crap SHOULD have been const from the start.  Telling the compiler that we were 'open' to editing the string was bad design from the start. So these bugs WERE good pointers to give the compiler the knowledge that these helper functions were 'safe' against the string, so it may be able to optimize better.  Now, where these are used is not really critical hot code, AND this may make no difference at all in the final binary, BUT it should have been done this way from the start, and was a good catch.

**Comment by jfoug** [comment]
Travis gcc/clang both are warning free now.

The warning is still on circleci.  Not sure why ??  It may be that due to prior builds, the system is still 'setup' with AC_BUILT headers or something.   I am not going to proceed forward with that one, I really am not overly concerned with it.  If you think it should be opened to a bug, then re-open this.  However, the other pedantic compiler warnings (some were very helpful), are toast.
