### ISSUE TITLE
repo is huge, generated configure scripts should not be checked in

### ISSUE THREAD

**Issue by rofl0r** [magnumripper/JohnTheRipper#1787]
having the configure script checked into the source tree admittedly makes it easier for users,
but it heavily increases the size of the repo.
for the sake of making (tag) releases a configure script needs to be generated on the publishers machine ( see https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck )

**Comment by magnumripper** [comment]
Are you talking about `src/configure`? It's 0.12% of the total size. Removing it would be ridicuolus.

**Comment by rofl0r** [comment]
yeah, but every change to configure.ac expand to a ton of changes in the configure script (2 lines in your configure.ac result in ~120 changes to configure in https://github.com/magnumripper/JohnTheRipper/commit/e14451e43e07c2ea59b772bd270f65d4d63d3aee )
and unnecessarily clutter the diff.

**Comment by jfoug** [comment]
No, NOT checking in configure is a very bad thing.  Did you even read the  https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck  here?   That discussion was about the problems and significant issues of NOT pushing ./configure, leaving the onus of building that to the end user.

Yes, it does increase the size of the repo, but so what?  We certainly do NOT WANT to force all users to have all of the proper components installed on there system to auto gen the script.

**Comment by jfoug** [comment]
well, i guess you did read it, since you wrote it, lol.    But exactly 'what' are you saying is proper.   I find no problem in the least having configure being part of the source 'proper'.  It simply makes sense, and is maintained and up to date.

**Comment by magnumripper** [comment]
> every change to configure.ac expand to a ton of changes in the configure script (2 lines in your configure.ac result in ~120 changes to configure

Sure, that is totally expected since configure.ac is the source and configure is the result. What problem are you trying to solve?

What we *could* do (but certainly won't) is only supplying configure, and keep configure.ac to our selves.
