### ISSUE TITLE
FMT_REMOVE needs actual implementation of removal.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1793]
http://www.openwall.com/lists/john-dev/2015/09/29/4

569daf1c implements half of it, but lacks this:

*Moreover, when your code sees "binary = NULL", it will also remove that
entry from the list.  crk_remove_hash() doesn't do this when there's a
bitmap to avoid traversing the list on every guess, but you're
traversing the list for transfer to GPU anyway.*

@Sayantan2048 are you in progress of implementing this? Otherwise I can do it.

**Comment by magnumripper** [comment]
I did it. Please review dcec4c4.

**Comment by Sayantan2048** [comment]
It's fine. Also did the same for descrypt-opencl in 0d7cf37c51902d2a
