### ISSUE TITLE
(TRAVIS): Testing: Raw-SHA512-opencl [SHA512 OpenCL (inefficient, development use mostly)]... FAILED (cmp_all(49))

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1794]
This is happening a lot on Travis (but not every time).  Should we add this to the john.conf disabled, or can someone find the problem????

**Comment by magnumripper** [comment]
I intend to look into it. Happens with xsha512-opencl too. Both are Myrice's formats that we had ditched but Solar wanted them back.

**Comment by jfoug** [comment]
Do we think this is Hard - medium - easy fix with this older code?  Is the code faster, or why was it asked for?

**Comment by magnumripper** [comment]
Claudio's formats are faster for single hash (or few hashes) but Myrice's is way better when loading many hashes. I'm hoping @claudioandre can get around the many-hash problems and re-introduce GPU-side mask (perhaps using Sayantan's recent stuff, or maybe even "Judy"). Then I see no reason to keep Myrice's formats.

**Comment by magnumripper** [comment]
I suspect e137572 fixes the problem, but only time will tell.

**Comment by magnumripper** [comment]
LOL, that was a quick verdict :cry: 
https://travis-ci.org/magnumripper/JohnTheRipper/jobs/83774233
```
Testing: XSHA512-opencl, Mac OS X 10.7+ [SHA512 OpenCL (efficient at "many salts" only)]... FAILED (cmp_all(49))
```

**Comment by jfoug** [comment]
Hey, better now, than getting a biach slap after 8 commits, and then not KNOWING why.  At least this time we know we did not correct anything.

**Comment by magnumripper** [comment]
Yeah. And I think those barriers should definitely be there anyway. I'm not aware of any guarantee we're executing in lock-step.

**Comment by frank-dittrich** [comment]
Now even your grammar fix in a john.conf comment caused XSHA512-opencl to fail (for the clang build) where it succeeded in the previous commit.

https://travis-ci.org/magnumripper/JohnTheRipper/builds/84466102

**Comment by magnumripper** [comment]
Do we have something in place to easily disable these formats just for Travis?

**Comment by magnumripper** [comment]
Offending formats excluded in f9c89a36
