### ISSUE TITLE
g3d7c8cf descrypt-opencl cores

### ISSUE THREAD

**Issue by roycewilliams** [magnumripper/JohnTheRipper#1796]
On these platforms and builds:

John the Ripper 1.8.0.6-jumbo-1-1311-g3d7c8cf OMP [linux-gnu 64-bit AVX-ac]
John the Ripper 1.8.0.6-jumbo-1-1311-g3d7c8cf OMP [linux-gnu 64-bit XOP-ac]

... descrypt-opencl test cores here:

    $ ./john --test --format=descrypt-opencl --device=gpu
    ./john: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by ./john)
    Device 0: GeForce GTX 750 Ti
    Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... Salt compiled from Source:1
    Segmentation fault (core dumped)

Happening on CUDA 6.5 and a CUDA 7.5 systems.

**Comment by magnumripper** [comment]
Happens for me to, using nvidia on OSX
```
$ ../run/john --test --format=descrypt-opencl -dev=2
Device 2: GeForce GT 650M
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... Abort trap: 6
```

The Intel HD Graphics works fine
```
$ ../run/john --test --format=descrypt-opencl 
Device 1: HD Graphics 4000
Benchmarking: descrypt-opencl, traditional crypt(3) [DES OpenCL]... DONE
Warning: "Many salts" test limited: 2/256
Many salts:	944663 c/s real, 104857K c/s virtual
Only one salt:	927943 c/s real, 104857K c/s virtual
```

**Comment by Sayantan2048** [comment]
Could you please run using -v=4 option ?

**Comment by Sayantan2048** [comment]
@roycewilliams please test 64d1ae9137790b950518.

**Comment by roycewilliams** [comment]
Up and working again - thanks!
