### ISSUE TITLE
Update on blockchain cracking?

### ISSUE THREAD

**Issue by ljx34** [magnumripper/JohnTheRipper#1803]
Don't think much has been done about it... I do believe that it's not cracking wallets that it should be..

I have downloaded a wallet I know the password of, used blockchain2john.py and tried to crack with no luck.

Could somebody give me some info on this? also am I supposed to be using the -json option when using blockchain2john  from a downloaded wallet? 

Please I could really use your help, thanks for this fantastic mod :)

**Comment by magnumripper** [comment]
This may be a dupe of #663 and/or #1050

**Comment by ljx34** [comment]
Maybe.. but is there no response on this then? because thats from june 2014..?

Also I did ask other questions I have an issue with/not sure about.

**Comment by magnumripper** [comment]
Sorry, all of us work on a voluntary basis here. Your best hope is for @kholia to get a relapse.

**Comment by kholia** [comment]
@ljx34 

Please upload a sample wallet file which exhibits the problem clearly. Also, describe the exact steps you took earlier. Thanks!

**Comment by magnumripper** [comment]
Please do so in #663 or #1050, I'm closing this one.
