### ISSUE TITLE
OSX - El Capitan - Openssl not found

### ISSUE THREAD

**Issue by denis0** [magnumripper/JohnTheRipper#1812]
Hi,

I just update my system to EL CAPITAN in case that can resolve the issue i have here : https://github.com/magnumripper/JohnTheRipper/issues/1786 ( in case is a driver way ) : , i try to compile, but failed ! seem he don't find OpenSSL

System : MacBookPro I7 / SSD / Full Ram

Here i check about SSL ;

MacBookPro:~ xxxx$ which openssl
/usr/bin/openssl
MacBookPro:~ xxxx$ openssl version
OpenSSL 0.9.8zg 14 July 2015

*******************************************

Here the compile logs Part,

## --------- ##

hostname = MacBookPro.local
uname -m = x86_64
uname -r = 15.0.0
uname -s = Darwin
uname -v = Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: i486 (Intel 80486)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 200 tasks, 727 threads, 8 processors
Load average: 1.20, Mach factor: 6.78
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/local/bin

********************************************

1 error generated.
configure:6720: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "john"
| #define PACKAGE_TARNAME "john"
| #define PACKAGE_VERSION "jumbo"
| #define PACKAGE_STRING "john jumbo"
| #define PACKAGE_BUGREPORT "john-users mailing list at openwall.com"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:6745: result: gcc -E
configure:6765: gcc -E  conftest.c
configure:6765: $? = 0
configure:6779: gcc -E  conftest.c
conftest.c:9:10: fatal error: 'ac_nonexistent.h' file not found
#include <ac_nonexistent.h>
         ^
1 error generated.
configure:6779: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "john"
| #define PACKAGE_TARNAME "john"
| #define PACKAGE_VERSION "jumbo"
| #define PACKAGE_STRING "john jumbo"
| #define PACKAGE_BUGREPORT "john-users mailing list at openwall.com"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
*************************************************

configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "john"
| #define PACKAGE_TARNAME "john"
| #define PACKAGE_VERSION "jumbo"
| #define PACKAGE_STRING "john jumbo"
| #define PACKAGE_BUGREPORT "john-users mailing list at openwall.com"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_INT_P 8
| #define SIZEOF_VOID_P 8
| /* end confdefs.h.  */
*******************************************

etc.....

**********************************************

configure:9488: result: no
configure:9488: checking openssl/opensslv.h presence
configure:9488: gcc -E  conftest.c
conftest.c:26:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^
1 error generated.
configure:9488: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "john"
| #define PACKAGE_TARNAME "john"
| #define PACKAGE_VERSION "jumbo"
| #define PACKAGE_STRING "john jumbo"
| #define PACKAGE_BUGREPORT "john-users mailing list at openwall.com"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_INT_P 8
| #define SIZEOF_VOID_P 8
| #define ARCH_LITTLE_ENDIAN 1
| /* end confdefs.h.  */
| #include <openssl/opensslv.h>
configure:9488: result: no
configure:9488: checking for openssl/opensslv.h
configure:9488: result: no
configure:9588: error: in `/Users/xxxx/desktop/jj/src':
configure:9590: error: JtR requires OpenSSL headers being installed
See `config.log' for more details

**************************************************

Thanks in advance,

Denis

**Comment by DomT4** [comment]
Not an official answer here, but it's looking for the OpenSSL headers which no longer ship anywhere with OS X 10.11.

You'll need to compile your own OpenSSL, or use Homebrew/MacPorts/Fink/etc to do so, and then point the JTR installation at that installation. Alternatively you can use CommonCrypto, but I don't think that's intended as a complete replacement yet and seems to cause compile issues still:

```
./configure --with-commoncrypto --without-openssl

gcc -DAC_BUILT -march=native -mavx -c -g -O2 -I/usr/local/include -DCOMMON_DIGEST_FOR_OPENSSL -DARCH_LITTLE_ENDIAN=1 -DJOHN_SYSTEMWIDE -DJOHN_SYSTEMWIDE_EXEC='"/tmp/testing"'   -Wall -Wdeclaration-after-statement -fomit-frame-pointer -Wno-deprecated-declarations -Wno-format-extra-args -Qunused-arguments -std=gnu89 -Wdate-time      -D_THREAD_SAFE -pthread  -I/usr/local/include -DHAVE_OPENCL -D_THREAD_SAFE -pthread -funroll-loops sha2.c -o sha2.o
In file included from sha2.c:26:
./sha2.h:36:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^
1 error generated.
make[1]: *** [sha2.o] Error 1
make: *** [default] Error 2
```

**Comment by denis0** [comment]
@DomT4 
Thank you, understand now...well done...i will see for homebrew so....& by the way for Homebrew i think we have to unlocked the sip apple protection also ! ? https://developer.apple.com/library/prerelease/ios/documentation/Security/Conceptual/System_Integrity_Protection_Guide/System_Integrity_Protection_Guide.pdf

**Comment by DomT4** [comment]
You can find Homebrew's documentation on SIP [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md). You can install Homebrew pretty much anywhere though; If you wanted to install it in `/opt/brew` or `~/brew` or such with `git clone https://github.com/Homebrew/homebrew.git` you can.

The advantage of using `/usr/local` is broader binary package (Bottle) availability which saves having to manually compile many things, but it'll work almost anywhere you can own & write into.
