### ISSUE TITLE
Amd gpu

### ISSUE THREAD

**Issue by ljx34** [magnumripper/JohnTheRipper#1813]
I have followed the instructions in the docs to install for AMD gpu and after building it shows "opencl: NO"

Also when trying to run john with one of the -opencl options such as form=blockchain-opencl

it says unknown ciphertext.

Basically it's a fresh install of ubuntu...
followed this 

"==== If you have an AMD GPU (or want to use CPU as OpenCL device)

    sudo apt-get install fglrx-updates-dev"

Built it and at the end it says that "opencl: no"

Am I doing something wrong and can somebody point me in the right direction? thanks <3

**Comment by claudioandre** [comment]
There is a config.log file in $JOHN/src directory. Inside it you will be able to find what wrong is happening.

BTW: If you have an AMD GPU, you also need to install the SDK 
- (http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/).

****

Since this is not the right place to ask for support questions, please check if you are running the closed source video driver. Use lsmod, fglrxinfo or whatever:

```
$ fglrxinfo
display: :0  screen: 0
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 6700 Series  
OpenGL version string: 4.5.13399 Compatibility Profile Context 15.20.1046
```

After installing AMD APP SDK, you can also check if things are ok running:
```
$ clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (1800.11)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon HD 6700 Series  
[...]
```

**Comment by claudioandre** [comment]
BTW: ```$ dpkg-query -L fglrx-dev``` suggests the the SDK is mandatory always (if one is going to build JtR).

If so, there is a 'bug' in documentation.

**Comment by ljx34** [comment]
Installed sdk > built again > still "openCL support = no".

Tried fglrxinfo command, says no command found....I have fglrx-updates-dev

**Comment by claudioandre** [comment]
It means you don't have the AMD driver properly installed:

 1. from now on, here is not the right place to talk about this error (for a good reason).
 2. you have to install the proprietary driver. Only after that we can talk about JtR OpenCL compilation.

* I suppose you can ask for help in john-users.
* Also, there are hundreds of Ubuntu sites that might help.
* Ubuntu has a graphical tool that helps ```software-properties-gtk --open-tab=4```. Shows and installs proprietary drivers.

Only after a valid fglrxinfo run you can try JtR again.
* Later, you can also run clinfo and see what kind of message you will get.
