### ISSUE TITLE
OpenCL: Use bitalign for 64-bit rotate on AMD

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1819]
http://www.openwall.com/lists/john-dev/2015/10/10/1

**Comment by magnumripper** [comment]
```
#define ror(x, n)       ((n) < 32 ? (amd_bitalign((uint)((x) >> 32), (uint)(x), (uint)(n)) | ((ulong)amd_bitalign((uint)(x), (uint)((x) >> 32), (uint)(n)) << 32)) : (amd_bitalign((uint)(x), (uint)((x) >> 32), (uint)(n) - 32) | ((ulong)amd_bitalign((uint)((x) >> 32), (uint)(x), (uint)(n) - 32) << 32)))
```

**Comment by magnumripper** [comment]
*Further speedup might be possible through switching the SWAP64() macro
from using rotate() to using the approach above.  However, it is
currently used on both vector and scalar arguments, so my trivial
attempt at changing it like that failed.  I guess we'd need to split it
into two macros: one for vectors and one for scalars.  I am leaving this
for Claudio or/and magnum to experiment with.*

**Comment by claudioandre** [comment]
AMD Radeon 6770:
- 10% gain for sha512crypt

**Comment by claudioandre** [comment]
AMD Radeon 7990 (super)
* > 20% gain on sha512crypt

**Comment by claudioandre** [comment]
Note: SWAP64 is not very important (at least for a while):

```
#define SWAP64(n)  (n)  //I mean, do nothing. Skip self-test.
```

60-90 c/s better. Not even 1%.
