### ISSUE TITLE
Mask mode: default mask vs. format's max length.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1828]
Somehow this fails (found when implementing the `-test -mask` feature but the bug was there before):
```
$ ../run/john test.in -dev=6 -form:descrypt-opencl -mask
Device 6: GeForce GTX TITAN X
Loaded 10 password hashes with 10 different salts (descrypt-opencl, traditional crypt(3) [DES OpenCL])
Salt compiled from Source:910
(...)
Press 'q' or Ctrl-C to abort, almost any other key for status
Format internal ranges cannot be truncated!
Use a bigger key length or non-gpu format.
```
The "cause" is likely that the default mask (in john.conf) is longer than format's max length. But we should obviously just truncate it (at least in case of using the default mask). And anyway the error message is very confusing.

**Comment by magnumripper** [comment]
@Sayantan2048 please review 76a41c41. It might be some cleaner way to implement this. The problem was that default mask was ?1?2?2?2?2?2?2?3?3?3?3?d?d?d?d and the last four ?d?d?d?d were picked as "internal". Only then, truncation removed them. My hack fix truncates it earlier in the process but I'm not sure it's very well written as-is.

**Comment by magnumripper** [comment]
That hack fix is not enough when using a length range with `-min-len=x -max-len=y`

**Comment by magnumripper** [comment]
I thought this was a regression but the problem is only with *GPU-side* truncation.

These work (truncating or stretching, not GPU-side):
```
$ ../run/john -stdout -mask -min-len=1 -max-len=5

$ ../run/john -stdout -mask=?d -min-len=1 -max-len=5
```

This doesn't (truncating, GPU-side):
```
$ ../run/john scraped.sam -form:nt-opencl -mask -min-len=4 -max-len=6
```

**Comment by magnumripper** [comment]
That hack fix did more bad than good. Reverted now.

**Comment by claudioandre** [comment]
@magnumripper , can you run a ```../run/john -form:nt-opencl --mask --test``` on super or well?

**Comment by magnumripper** [comment]
```
[magnum@super src]$ ../run/john -form:nt-opencl --mask --test
Device 6: GeForce GTX TITAN X
Benchmarking: nt-opencl, NT [MD4 OpenCL]... Format internal ranges cannot be truncated!
Use a bigger key length or non-gpu format.

[magnum@super src]$ ../run/john -form:nt-opencl --mask:?a?a?a --test
Device 6: GeForce GTX TITAN X
Benchmarking: nt-opencl, NT [MD4 OpenCL]... DONE, GPU util:97%
Raw:	11311M c/s real, 11199M c/s virtual
```
The problem when you don't specify a mask is that the default mask is `?1?2?2?2?2?2?2?3?3?3?3?d?d?d?d`. GPU-side mask mode picks ?d?d?d?d in the end, but then the mask is truncated to length 8. The fix would obviously be to pick GPU-side mask *after* truncation.

**Comment by magnumripper** [comment]
This bug died of age (some other change fixed it).

**Comment by claudioandre** [comment]
Are you sure?
```
$ ../run/john | head -n 3
John the Ripper 1.8.0-jumbo-1-5103-g393456a+ OMP [linux-gnu 64-bit AVX-ac]
Copyright (c) 1996-2016 by Solar Designer and others
Homepage: http://www.openwall.com/john/

super src]$ ../run/john -form:nt-opencl --mask --test 
Device 6: GeForce GTX TITAN X
Benchmarking: nt-opencl, NT [MD4 OpenCL]... Format internal ranges cannot be truncated!
Use a bigger key length or non-gpu format.
```

**Comment by magnumripper** [comment]
I tested exactly that!? Perhaps I got different GPU-side size because I used a weaker device.

**Comment by claudioandre** [comment]
(Confimation neeed) I am almost sure it used to work on my deceased computer with 6770. 

* The final mask/cut is calculated based on the computer and device in use.

**Comment by magnumripper** [comment]
Apparently we can't coun't on Sayantan doing any more work. We need to dig in to all these issues and try to fix them...
