### ISSUE TITLE
Some mask-mode formats don't handle "-test -mask" properly yet

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1835]
At least DEScrypt and LM formats does not benchmark properly using `-test -mask`. I had a look but haven't been able to fix it (when I tried they started crashing).

I'm planning to change the MD4/5 and SHA1 formats to use shared auto-tune, hopefully they are no harder than NT or mscash which are already done and works just fine with mask benchmark.

**Comment by magnumripper** [comment]
@Sayantan2048 I am experimenting with a shared function that can build a `struct db_main *fake_db` from any format's test vectors. Would that not be a good thing for these formats? I reckon it would remove much special handling in the code?

**Comment by magnumripper** [comment]
See https://gist.github.com/magnumripper/48d96088ea84ce76bc79#file-fake_db-diff for an early version. Seems to work fine but I have yet to try using it.

**Comment by Sayantan2048** [comment]
Yeah fake db would be awesome. It means I can eliminate test specific code. Regarding test mask - how are things handled during self-test when the session is for actual cracking with user specified mask? Is the default mask overruled with user specified mask ? 

Also, I would be little less active for the next few days as it is festival season in my country. :)

**Comment by magnumripper** [comment]
Actual cracking is not affected by latest changes. And self-test currently never involves mask-mode anyway, only benchmark does.

The default mask from john.conf is used unless you specify one.

**Comment by magnumripper** [comment]
That function is added in df94976. We might have to tweak it but it seems to produce a valid db.

**Comment by magnumripper** [comment]
We probably also have to change most/all `crypt_all(count, NULL)` in format tests and benchmarks, to `crypt_all(count, db->salts)`.

**Comment by magnumripper** [comment]
http://www.openwall.com/lists/john-dev/2015/10/18/1

**Comment by magnumripper** [comment]
Experiment topic branches, neither of them is 100% OK right now:

Branch fakedb_format uses this in nt-opencl only, aaefa2b. 
* `-test` works
* `-test -mask` works
* real crack fails self-test

Branch fakedb_core instead implement it in core, ece8f89 but only nt-opencl is modified accordingly.
* `-test` works
* `-test -mask` works
* real crack fails self-test

**Comment by magnumripper** [comment]
Current (rebased and tweaked) fakedb_core branch fails real crack for some reason. I'm investigating.

**Comment by magnumripper** [comment]
Latest fakedb_core code works fine. Special code for self-test dropped for NT and mscash. Maybe we should merge it but I'm still considering the alternatives.

**Comment by magnumripper** [comment]
@Sayantan2048 I merged the "fake db" branch now, I think we really need it. If you look at commits like e83f99f1 and 1c7b5dcdf you can see how much simpler it gets in the format.
