### ISSUE TITLE
sha512crypt-opencl fails with cmp_all(1)

### ISSUE THREAD

**Issue by fortytwopar** [magnumripper/JohnTheRipper#1850]
When I run `../run/john --format=sha512crypt-opencl --test -v=5` I get
```
initUnicode(UNICODE, ASCII/ASCII)
ASCII -> ASCII -> ASCII
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Device 0: GeForce 9500 GT
Options used: -I ../run/kernels -cl-mad-enable -DSM_MAJOR=1 -DSM_MINOR=1 -cl-nv-verbose -D__GPU__ -DDEVICE_INFO=18 -DDEV_VER_MAJOR=340 -DDEV_VER_MINOR=93 -D_OPENCL_COMPILER  $JOHN/kernels/cryptsha512_kernel_GPU.cl
Calculating best GWS for LWS=32; max. 150ms single kernel invocation.
Raw speed figures including buffer transfers:
xfer: 29.344us, crypt: 119x21.271ms, xfer back: 43.808us, prep: 25.136ms, pp: 244.832us, final: 1.148ms, var: 21.266ms/21.257ms
gws:       512      200c/s     1000000 rounds/s    2.558s per crypt_all()!
xfer: 53.056us, crypt: 119x42.503ms, xfer back: 81.856us, prep: 48.948ms, pp: 287.136us, final: 2.267ms, var: 42.533ms/42.521ms
gws:      1024      200c/s     1000000 rounds/s    5.113s per crypt_all()
xfer: 101.632us, crypt: 119x84.975ms, xfer back: 161.216us, prep: 98.554ms, pp: 378.144us, final: 4.506ms, var: 84.968ms/84.973ms
gws:      2048      200c/s     1000000 rounds/s   10.219s per crypt_all()
xfer: 199.040us, crypt: 119x169.952ms (exceeds 150ms)
Calculating best LWS for GWS=512
Testing LWS=32 GWS=512 ... 106.315ms+
Testing LWS=64 GWS=512 ... 56.638ms+
Testing LWS=128 GWS=512 ... 56.542ms
Calculating best GWS for LWS=64; max. 300ms single kernel invocation.
Raw speed figures including buffer transfers:
xfer: 16.576us, crypt: 119x10.671ms, xfer back: 22.528us, prep: 12.409ms, pp: 239.136us, final: 585.504us, var: 10.674ms/10.675ms
gws:       256      199c/s      995000 rounds/s    1.283s per crypt_all()!
xfer: 29.312us, crypt: 119x11.315ms, xfer back: 42.816us, prep: 13.129ms, pp: 246.080us, final: 625.728us, var: 11.312ms/11.301ms
gws:       512      376c/s     1880000 rounds/s    1.360s per crypt_all()+
xfer: 52.576us, crypt: 119x22.597ms, xfer back: 81.888us, prep: 26.109ms, pp: 315.232us, final: 1.224ms, var: 22.598ms/22.612ms
gws:      1024      376c/s     1880000 rounds/s    2.718s per crypt_all()
xfer: 101.696us, crypt: 119x45.120ms, xfer back: 157.088us, prep: 52.124ms, pp: 382.240us, final: 2.430ms, var: 45.231ms/45.074ms
gws:      2048      377c/s     1885000 rounds/s    5.429s per crypt_all()
xfer: 199.072us, crypt: 119x90.231ms, xfer back: 309.568us, prep: 104.296ms, pp: 528.096us, final: 4.835ms, var: 90.216ms/90.159ms
gws:      4096      377c/s     1885000 rounds/s   10.848s per crypt_all()
xfer: 393.184us, crypt: 119x180.494ms, xfer back: 613.536us, prep: 208.275ms, pp: 809.504us, final: 9.644ms, var: 180.208ms/180.113ms
gws:      8192      377c/s     1885000 rounds/s   21.680s per crypt_all()
xfer: 780.192us, crypt: 119x360.470ms (exceeds 300ms)
Local worksize (LWS) 64, global worksize (GWS) 512
FAILED (cmp_all(1))
```
I am running on x86_64 Linux with a GeForce 9500 GT.

https://github.com/magnumripper/JohnTheRipper/issues/1794 seems similar, though I am not familiar enough with the code to know whether it is.

**Comment by claudioandre** [comment]
Thanks.
************
Can you do some tests so we can narrow it? I don't have access to a 9500 GT board and I guess the format is working in all NVIDIA we have. So, if possible, try:

- For example:

Change line 32 inside cryptsha512_kernel_GPU.cl
From
```#define UNROLL_LEVEL	0```

To
```#define UNROLL_LEVEL	4```

- And/Or:
```
git checkout 970f01a068caf544e5f7843d23520e5d24934d75
configure
make clean & make 
```

- And/Or:

Try using the latest NVIDIA driver (not exactly the latest, 346 seems good (or what @magnumripper recommends)).

**Comment by fortytwopar** [comment]
The change of `UNROLL_LEVEL` makes it appear to hang. No input came out, after the initial printing of the version which was the same as before

I could not get that commit to compile, with a bunch of `/home/par/john/JohnTheRipper/src/opencl_rawmd4_fmt_plug.c:743: undefined reference to 'clEnqueueFillBuffer'` errors. 

The board is old enough that I am using an older version of the NViDIA driver, because that is what supports CUDA for this board. I could try newer, but I am doubtful that it would help the situation. The 9500 GT may be old enough that it be not supported. if that were the case, I would completely understand that. It is right now the only hardware i have that fits.

**Comment by claudioandre** [comment]
> /home/par/john/JohnTheRipper/src/opencl_rawmd4_fmt_plug.c:743: undefined reference to 'clEnqueueFillBuffer' errors.

In order to test, you can safely remove the file that generates the error.
******
It seems 9500 gt is more than 7 years old. It means it is very old for sure, but I see no reason sha512crypt cannot work on it. But keep in mind that ```FAILED (cmp_all(1))``` means the NVIDIA compiler is failing terribly.

BTW: you are using 340 driver (less than 2 yeas). I guess it is a good driver, maybe not good as it should be for 9500GT. Try other formats, check how everything else behaves.

**Comment by fortytwopar** [comment]
Once I removed the offending files, the commit did the same as changing the source line, it hung.

Right now, I am upgrading to the newest version of the NVIDIA driver in the Debian testing repos, 340.93-3, from 340.93-1. both should be supported, and if I were to download it from NVIDIA, I would be getting 340.93, unspecified subversion, which was released on September 2 of this year. I will try next those from unstable which is 340.93.9.

**Comment by claudioandre** [comment]
Hung is always a bad result (it means the compiler cannot handle the source code it has). BTW: on AMD, it could hang for 10 minutes and works after that. On NVIDIA I have no idea. Give it a try.

The last thing to try (if this fails, I'm afraid there is nothing else to do):
```
_TYPE=0  ../run/john --format=sha512crypt-opencl --test
```

**Comment by fortytwopar** [comment]
I was unable to get any of these things to work. I let it sit for about 20 minutes, and it showed no signs of progress.

When I do _TYPE=0, there are two threads, one active and the other inactive, and they each allocate 4Gb of memory, and appear to do nothing as well. I can probably borrow a friend's (modern) GPU/computer for a while to do this, because it sounds like a specific card issue.

**Comment by magnumripper** [comment]
@claudioandre we have this in other places. Almost same card.
```c
#if SM_MAJOR < 2
#define OLD_NVIDIA 1
#endif
```
```c
/* Workaround for problem seen with 9600GT */
#if OLD_NVIDIA
#define MAYBE_CONSTANT	__global const
#else
#define MAYBE_CONSTANT	__constant
#endif
```

**Comment by fortytwopar** [comment]
Forcing these one way or another does not seem to make a difference in cryptsha512-opencl. If I force it to 0 in one of the formst it's referenced, like wpapsk-opencl, then that format hangs like before.

**Comment by magnumripper** [comment]
Try replacing all `__constant` in opencl/cryptsha512_kernel_GPU.cl to `__global const`.

**Comment by fortytwopar** [comment]
That worked. Thanks! Now that I look back it seems marginally clearer why it worked.

**Comment by magnumripper** [comment]
Great to hear that!

Re-opening so @claudioandre can add that workaround logic to the kernel.

**Comment by magnumripper** [comment]
Ideally you should source opencl_misc.h instead of copying the logic though...

**Comment by claudioandre** [comment]
@fortytwopar, please test if the new code works for you.

```
git clone https://github.com/claudioandre/JohnTheRipper.git toTest
cd toTest/src
git checkout to_pull

configure && make
```
