### ISSUE TITLE
Amd documentation for ubuntu

### ISSUE THREAD

**Issue by ljx34** [magnumripper/JohnTheRipper#1854]
The amd install-ubuntu documentation doesn't elaborate enough or is lacking certain things, I have tried from a fresh ubuntu 14.05 and 15.10 with no success.

I have installed my proprietary driver for my amd radeon 7970, installed the sdk, tried to build john with an end result of "opencl: no", tried this with and without the instruction of installing fglrx-updates-dev, which when you install.. uninstalls the fglrx-core that comes with the amd driver. I have tried litterly everything I can but with no success so I can only assume this is a problem with john or missing documentation.

EDIT: found this.. http://openwall.info/wiki/john/GPU going to give it a shot when I get back.. I have not tried this command "make linux-x86-opencl" if this is the reason maybe it should be added to documentation? cheers

**Comment by ljx34** [comment]
I fixed it somehow... installed a lot of different shit and somewhere along the way it fixed.

Is it normal when asking for status on opencl that it shows the same password but after a little while shows a different password + increased %

**Comment by magnumripper** [comment]
> Is it normal when pressing s for status on opencl that it shows the same password but after a little while shows a different password + increased %

Yes, especially for extremely slow formats or lots of salts. It happens with CPU formats too.

**Comment by magnumripper** [comment]
The "make linux-x86-opencl" is obsoleted by autoconf.

**Comment by frank-dittrich** [comment]
For GPU formats it is usually worse, due to max. keys per crypt being larger.
