### ISSUE TITLE
NT-opencl intermittent problem

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1857]
Apparently this doesn't happen with `--test` or `--test --mask`, but during self-test before a real crack run. Also, it only affects some devices. And even then, it's somewhat intermittent. All below are running bfe5112.

Test file (run with -w)

```
$ ../run/john -form:cpu --list=format-tests | cut -f3 >alltests.in
```

well (Catalyst 14.12):

```
Device 0: Bonaire [AMD Radeon HD 7700 Series]
Using default input encoding: UTF-8
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Remaining 54 password hashes with no different salts
Self test failed (get_key(2))

Device 1: Capeverde [AMD Radeon HD 7700 Series]
Using default input encoding: UTF-8
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Remaining 54 password hashes with no different salts
Self test failed (get_key(2))
```

super (Catalyst 15.7):

```
Device 0: Juniper [AMD Radeon HD 6700 Green Edition]
Using default input encoding: UTF-8
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Remaining 54 password hashes with no different salts
Self test failed (get_key(0))
```

Macbook (OSX 10.11.1):

```
Device 0: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
Using default input encoding: UTF-8
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Remaining 54 password hashes with no different salts
Self test failed (cmp_all(0))

Device 2: GeForce GT 650M
Using default input encoding: UTF-8
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Remaining 54 password hashes with no different salts
Self test failed (cmp_all(0))
```

**Comment by magnumripper** [comment]
Maybe what we're seeing here are simply driver bugs. I'm pretty sure the OSX case is.

**Comment by magnumripper** [comment]
Another datapoint: Running the fakedb_core branch, I can't reproduce the bug on well's devices. But it's still there on super's Juniper.

**Comment by magnumripper** [comment]
The Juniper works fine with de54acf70. I'm bisecting now.

**Comment by crioux** [comment]
Can confirm this on x86_64 Radeon HD 7990 dual gpu on Windows.

**Comment by magnumripper** [comment]
@crioux what driver version are you using? Does WPAPSK-opencl work fine?

**Comment by crioux** [comment]
Driver version 15.201.1151.0
I don't have data on WPAPSK-opencl.
Can confirm the problem is intermittent and only observed right now with nt-opencl. Will send much more detail in a bit when i return to this bug.

**Comment by magnumripper** [comment]
I think 15.201.1151.0 is a beta driver. Also, I'm not sure how to parse that version number vs. the ones reported by the driver, please report it as shown with `./john --list=opencl-devices | grep version`

**Comment by crioux** [comment]
Platform #0 name: AMD Accelerated Parallel Processing, version: OpenCL 2.0 AMD-APP (1800.11)
    Device #0 (0) name:     Tahiti
    Board name:             AMD Radeon R9 200 / HD 7900 Series
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (1800.11)
    Driver version:         1800.11 (VM)
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          3.0 GB
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        925
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 32
    Speed index:            29600
    PCI device topology:

    Device #1 (1) name:     Tahiti
    Board name:             AMD Radeon R9 200 / HD 7900 Series
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (1800.11)
    Driver version:         1800.11 (VM)
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          3.0 GB
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        925
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 32
    Speed index:            29600
    PCI device topology:

    Device #2 (2) name:     AMD FX(tm)-8350 Eight-Core Processor
    Device vendor:          AuthenticAMD
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (1800.11)
    Driver version:         1800.11 (sse2,avx,fma4)
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          31.0 GB
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Global)
    Max memory alloc. size: 7.0 GB
    Max clock (MHz):        4018
    Profiling timer res.:   69 ns
    Max Work Group Size:    1024
    Parallel compute cores: 8
    Speed index:            128576
    PCI device topology:

**Comment by magnumripper** [comment]
OK, that seems to mean Catalyst 15.8 beta.

**Comment by magnumripper** [comment]
On super, running things like:
```
$ for i in 0 2 6 7 0 2 6 7 0 2 6 7 0 2 6 7 ; do rm -f ../run/john.pot ; ../run/john scraped.sam -form:nt-opencl -mask:password -dev=$i || break ; done
Device 0: Juniper [AMD Radeon HD 6700 Green Edition]
Using default input encoding: UTF-8
Loaded 5294 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
password         (user)
1g 0:00:00:00  1.923g/s 1.923p/s 1.923c/s 10180C/s password
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
Device 2: Tahiti [AMD Radeon HD 7900 Series]
Using default input encoding: UTF-8
Loaded 5294 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
password         (user)
1g 0:00:00:00  3.703g/s 3.703p/s 3.703c/s 19607C/s password
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(...)
```

...will sooner or later result in
```
Device 6: GeForce GTX TITAN X
Using default input encoding: UTF-8
Loaded 5294 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Self test failed (get_key(3))
```
...on (it seems) **any** device (so doesn't look like driver bug).

Also, this was seen once (likely same bug)
```
Device 0: Juniper [AMD Radeon HD 6700 Green Edition]
Using default input encoding: UTF-8
Loaded 5294 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Remaining 5293 password hashes with no different salts
Press 'q' or Ctrl-C to abort, almost any other key for status
??|         (Guest)
```
Here, it happened to pass self-test, then gave a false positive for "Guest" with some data it made up itself, AND gave a false negaitve for "user".

Race condition? Barrier needed somewhere?

**Comment by magnumripper** [comment]
Newsflash: This seems to happen only with UTF-8 encoding! Using eg. `-enc:cp1252` seems to make it go away. This makes it my problem :worried:

**Comment by magnumripper** [comment]
Stress test
```
$ ../run/john -form:cpu --list=format-tests | cut -f3 >alltests.in
$ ../run/john -form:nt alltests.in -pot:correct.pot -mask:password

$ while true ; do for i in ascii utf8; do for j in 0 2 7; do rm -f test.pot ; echo $i $j ; ../run/john -form:nt-opencl alltests.in -mask:password -pot:test.pot -dev=$j -enc:$i || break 3 ; diff -q test.pot correct.pot || break 3 ; done ; done ; done
```
Can be left unmonitored - it will stop on error

**Comment by magnumripper** [comment]
Juniper
```
utf8 0
Device 0: Juniper [AMD Radeon HD 6700 Green Edition]
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
Lbaaaaaa         (?)
password         (?)
2g 0:00:00:00  3.571g/s 1.785p/s 1.785c/s 164.2C/s Lbaaaaaa
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
Files test.pot and correct.pot differ

$ cat test.pot
$NT$31d6cfe0d16ae931b73c59d7e0c089c0:Lbaaaaaa
$NT$8846f7eaee8fb117ad06bdd830b7586c:password
```
The 31d6... is a null hash. False positive.

**Comment by magnumripper** [comment]
Tahiti
```
utf8 2
Device 2: Tahiti [AMD Radeon HD 7900 Series]
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
password         (?)
                 (?)
2g 0:00:00:00  4.166g/s 2.083p/s 2.083c/s 191.6C/s password
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
Files test.pot and correct.pot differ
[magnum@super src]$ cat test.pot
$NT$8846f7eaee8fb117ad06bdd830b7586c:password
$NT$31d6cfe0d16ae931b73c59d7e0c089c0:
```
In this case it's not quite a false positive but hey, we didn't actually test for the null string!

**Comment by magnumripper** [comment]
CPU (AMD-driver) (found by [stress-test](https://github.com/magnumripper/JohnTheRipper/issues/1857#issuecomment-163713475))
```
utf8 3
Device 3: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
password         (?)
                 (?)
2g 0:00:00:00  4.444g/s 2.222p/s 2.222c/s 204.4C/s password
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
Files test.pot and correct.pot differ
[magnum@super src]$ cat test.pot
$NT$8846f7eaee8fb117ad06bdd830b7586c:password
$NT$31d6cfe0d16ae931b73c59d7e0c089c0:
```

**Comment by magnumripper** [comment]
Another variant
```
ascii 3
Device 3: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
Segmentation fault
```

**Comment by magnumripper** [comment]
OS X (I also saw this on older Intel CPU driver on Linux)
```
ascii 1
Device 1: HD Graphics 4000
Loaded 92 password hashes with no different salts (nt-opencl, NT [MD4 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
                 (?)
password         (?)
2g 0:00:00:00  3.125g/s 1.562p/s 1.562c/s 143.7C/s 
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
Files test.pot and correct.pot differ
$ cat test.pot 
$NT$31d6cfe0d16ae931b73c59d7e0c089c0:
$NT$8846f7eaee8fb117ad06bdd830b7586c:password
```

**Comment by magnumripper** [comment]
I've run the stress test for long periods without seeing any problem with nvidia Titan or Titan X.

**Comment by magnumripper** [comment]
I've seen another problem a number of times: On a newly cold started machine running nvidia GPU, nt-opencl nearly always fails self-test when using mask mode on a real run (as the very first thing you do with that format). You can try again and it will fail again. Workaround: Run eg. a `-test -mask:?a`. After that, no problem until next time machine is cold started.

Seen on Linux with Titan X and on OSX with GT650M.

**Comment by magnumripper** [comment]
Haven't seen any problem for quite a while now. Probably something changed that happened to fix it.
