### ISSUE TITLE
BE Problems

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1861]
bash-3.2$ ../run/john -test-full=0 | grep -v PASS
- [x] Testing: LUKS [PBKDF2-SHA1 32/32]... FAILED (cmp_all(1))
- [x] Testing: dynamic_395 [sha3_384(sha3_384($p).$s) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_396 [sha3_384($s.sha3_384($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_397 [sha3_384(sha3_384($s).sha3_384($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_398 [sha3_384(sha3_384($p).sha3_384($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_403 [sha3_512(sha3_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_405 [sha3_512(sha3_512($p).$s) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_406 [sha3_512($s.sha3_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_407 [sha3_512(sha3_512($s).sha3_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_408 [sha3_512(sha3_512($p).sha3_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_423 [keccak_512(keccak_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_425 [keccak_512(keccak_512($p).$s) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_426 [keccak_512($s.keccak_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_427 [keccak_512(keccak_512($s).keccak_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: dynamic_428 [keccak_512(keccak_512($p).keccak_512($p)) 64/32 keccak]... FAILED (cmp_all(2))
- [x] Testing: NT [MD4 32/32]... FAILED (source)
- [x] Testing: Raw-MD4 [MD4 32/32]... FAILED (source)
- [x] Testing: Raw-MD5 [MD5 32/32]... FAILED (source)
- [x] Testing: Raw-SHA1 [SHA1 32/32]... FAILED (source)
19 out of 631 tests have FAILED

**Comment by magnumripper** [comment]
You made BE fixes to LUKS in b6845c56 so something must have sneaked in after that.

**Comment by magnumripper** [comment]
I just reviewed a `git diff b6845c5..HEAD luks_fmt_plug.c` and see absolutely nothing suspect.

**Comment by jfoug** [comment]
Did it have 2 tests before, or is that 'new' ?  I thought it was only 1 test vector.

**Comment by jfoug** [comment]
If I comment out the 2nd test, I do not get a failure, so at least I know which one it is (or think i do).  Hard part is I can not edit the file on the sparc box (with vi).  The lines are too long, lol.

**Comment by frank-dittrich** [comment]
grep -v

**Comment by jfoug** [comment]
I think I found the BE problems in keccak :(  Not good.  There is all sorts of BE work done, BUT I think the current 'optimized' version has never been checked against BE.   What I have done is to swap64 the input data (have to pad even 64 bits, nulling out the last one before memcopying).  Then use that buffer.  That seems to give proper results, so all is well.

This appears to be since the macros are using uint64 objects, and reading from the input data 64 bits at a time.  I think the original code must have only read byte by byte or something.

I still have to clean things up,  (and make sure that this DOES fix things fully), and get it checked in.

I think 'some' formats worked, because only the 'load full limbs first' code seems to do this. The 'load last limb' must still be byte-byte reading.  So hashes that did not go past 104 bytes never got into the load full limbs part.

**Comment by jfoug** [comment]
The 'easy' fix, is to #define out the 2nd hash for BE build, LOL!

I really hate this format

**Comment by magnumripper** [comment]
The easy & safe fix is to disable Keccak formats for BE builds.

**Comment by magnumripper** [comment]
I hate that format too. I think it's unreasonable to have those damned test vectors in there. We should leave them out and just test it in TS, or something. It breaks the C standard and many editors. The LINE_BUFFER_SIZE was bumped to an unreasonable value to even allow this crap and I hate that too.

To be just a little more sane, it'd be easy enough to split the lines into
```
	{"$luks$1$592$4c554b53babe000161657300000000000000000000000000000000000000"
	 "000000000000000000006362632d65737369763a73686132353600000000000000000000"
	 "000000000000736861310000000000000000000000000000000000000000000000000000"
```
...and so on. Maybe we should at least do that.

**Comment by magnumripper** [comment]
I moved them to a separate file. Doesn't fix many of the problems, but at least we don't have to look at or navigate through the shit.

**Comment by magnumripper** [comment]
LOL, GitHub even refuses to show the diff of 94836be

**Comment by jfoug** [comment]
Yep, that format sux. 100k line length, is just pushing it for any system..  I already had to ifdef if for VC to even be able to build the damn thing, loading it late.  I think it had a 85k limit on inlined constant strings.

**Comment by magnumripper** [comment]
Folded lines in 8feb31a.

**Comment by jfoug** [comment]
Found the LUKS problem

**Comment by jfoug** [comment]
Doing a final -test-all=0, but I think that all BE problems are gone again.

**Comment by jfoug** [comment]
```
bash-3.2$ ../run/john -test-full=0 | grep -v PASS
All 632 formats passed self-tests!
```
