### ISSUE TITLE
./configure does not add the path to openssl header files in generated Makefile on OSX

### ISSUE THREAD

**Issue by priorityinterrupt** [magnumripper/JohnTheRipper#1865]
On OSX the Makefile created by ./configure is missing the path to the openssl header files.  

    make clean && make -s
    rm -f ../run/john ../run/unshadow ../run/unafs ../run/unique ../run/undrop ../run/rar2john ../run/zip2john ../run/genmkvpwd ../run/mkvcalcproba ../run/calc_stat ../run/tgtsnarf ../run/racf2john ../run/hccap2john ../run/raw2dyna ../run/keepass2john ../run/dmg2john ../run/putty2john ../run/uaf2john ../run/wpapcap2john ../run/luks2john ../run/gpg2john ../run/cprepair ../run/base64conv ../run/pfx2john ../run/ssh2john ../run/SIPdump ../run/vncpcap2john
    rm -f john-macosx-* *.o escrypt/*.o *.bak core
    rm -f ../run/kernels/*
    rm -f detect bench generic.h tmp.s
    rm -f cuda/*.o cuda/*~ *~
    cp /dev/null Makefile.dep
    /usr/bin/find . -name \*.a -exec /bin/rm -f {} \;
    /usr/bin/find . -name \*.o -exec /bin/rm -f {} \;
    /bin/rm -f tests crypto_scrypt-best.o crypto_scrypt-common.o sha256.o tests.o crypto_scrypt-*.o
    In file included from md5.c:25:
    ./md5.h:25:10: fatal error: 'openssl/md5.h' file not found
    #include <openssl/md5.h>
             ^
    1 error generated.
    make[1]: *** [md5.o] Error 1
    make: *** [default] Error 2

If I manually add the path to the Makefile it compiles and runs successfully. I am assuming this is the default system one installed with xCode but I cant say with 100% certainty. 

    CPPFLAGS =  -I/usr/local/include -I/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include

Alternatively I can use the homebrew version which is a much nicer path but dependent on homebrew having installed openssl.  

    CPPFLAGS =  -I/usr/local/include -I/usr/local//Cellar/openssl/1.0.2d_1/include/

Here is some additional system info:

    $ xcodebuild -version
    Xcode 7.1
    Build version 7B91b

    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.11.1
    BuildVersion:	15B42

This is from a successful build after manually adding the openssl include path (the one under the Xcode.app dir path). 

    ./john --list=build-info
    Version: 1.8.0-jumbo-1-4148-gff38778
    Build: darwin15.0.0 64-bit AVX-ac MPI
    SIMD: AVX, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
    $JOHN is ./
    Format interface version: 13
    Max. number of reported tunable costs: 3
    Rec file version: REC4
    Charset file version: CHR3
    CHARSET_MIN: 1 (0x01)
    CHARSET_MAX: 255 (0xff)
    CHARSET_LENGTH: 24
    SALT_HASH_SIZE: 1048576
    Max. Markov mode level: 400
    Max. Markov mode password length: 30
    clang version: 7.0.0 (clang-700.1.76) (gcc 4.2.1 compatibility)
    Crypto library: OpenSSL
    OpenSSL library version: 0009081df
    OpenSSL 0.9.8zd 8 Jan 2015	(loaded: OpenSSL 0.9.8zg 14 July 2015)
    GMP library version: 6.0.0
    File locking: fcntl()
    fseek(): fseek
    ftell(): ftell
    fopen(): fopen
    memmem(): System's

**Comment by magnumripper** [comment]
I thought Apple stopped supplying OpenSSL headers with El Capitan but I see they're there now (maybe they were re-added in 10.11.1?)
```
$ locate openssl/md5.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include/openssl/md5.h
/usr/local/Cellar/openssl/1.0.2d_1/include/openssl/md5.h
```
The thing is autoconf is not really supposed to go out of its way to find it. These are both non-standard paths so it's natural you need to supply one of them. Some hard-core beards would even say we shouldn't look in /usr/local/include unless told so (but I disagree).

I usually have a symlink like this one for Homebrew:
```
$ ls -l /usr/local/include/openssl
lrwxr-xr-x  1 magnum  admin  50 Oct  3 17:00 /usr/local/include/openssl -> /usr/local/Cellar/openssl/1.0.2d_1/include/openssl
```

However, since this is a very common special-case, I guess we should do two things: 1. Add instructions to doc/INSTALL about how to handle eg. Homebrew and (perhaps) 2. find that crazy long path under /Applications/Xcode.app as a last resort.

**Comment by magnumripper** [comment]
BTW I consider this a bug in Homebrew:
```
$ pkg-config --cflags configure
Package configure was not found in the pkg-config search path.
Perhaps you should add the directory containing `configure.pc'
to the PKG_CONFIG_PATH environment variable
No package 'configure' found
```
The pkg-config thing is utterly useless unless they start actually supplying configs for it when installing things. We do include `pkg-config --cflags configure` in our AC enumeration.

**Comment by magnumripper** [comment]
Apparently most other Homebrew packages has it right
```
$ pkg-config --cflags libpcre
-I/usr/local/Cellar/pcre/8.37/include
```

**Comment by magnumripper** [comment]
This is odd
```
$ cat /usr/local//Cellar/openssl/1.0.2d_1/lib/pkgconfig/openssl.pc
prefix=/usr/local/Cellar/openssl/1.0.2d_1
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries and tools
Version: 1.0.2d
Requires: libssl libcrypto
```
It actually has the info. So why isn't pkg-config supplying it?!

**Comment by magnumripper** [comment]
OK, there's several problems. First, the openssl.pc file is missing `Libs:` and `Cflags` entries. Second, it should be symlinked into /usr/local/lib/pkgconfig/openssl.pc.

The info we get for --cflags actually come from the native OpenSSL, in /usr/lib/pkgconfig/openssl.pc and this file is ALSO buggy - it should obviously list /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include for `Cflags:`.

**Comment by magnumripper** [comment]
OK, here's how to do it for Homebrew:
```
brew link --force openssl
```
After that, it should work.

**Comment by magnumripper** [comment]
LOL, I was going to add instructions to doc/INSTALL and found we already had them
```
  2. Install Homebrew's gcc and openssl:
	brew install gcc openssl
	brew link --force openssl
```
