### ISSUE TITLE
OpenCL - "Can't read source kernel" - on OSX El Capitan 

### ISSUE THREAD

**Issue by priorityinterrupt** [magnumripper/JohnTheRipper#1867]
I cannot run OpenCL formats on OSX. I have tried leaving the GPU in dynamic mode, forcing it to discrete, and forcing it to integrated. I get the same error in all cases. 

No mater what mode my GPU is in without specifying a device it tries to use my integrated graphics.  I am not sure if this is suppose to be the case or not. 

    $ ./john --test=10 --format=md5crypt-opencl
    Device 1: HD Graphics 4000
    Benchmarking: md5crypt-opencl, crypt(3) $1$ [MD5 OpenCL]... Can't read source kernel: No such file or directory

I can specify to use the discrete GPU though with the same results.  

    $ ./john --dev=2 --test=10 --format=md5crypt-opencl
    Device 2: GeForce GT 650M 
    Benchmarking: md5crypt-opencl, crypt(3) $1$ [MD5 OpenCL]... Can't read source kernel: No such file or directory

Here is my system information: 

    ProductName:	Mac OS X
    ProductVersion:	10.11.1
    BuildVersion:	15B42

    Version: 1.8.0-jumbo-1-4150-g9cb4e47
    Build: darwin15.0.0 64-bit AVX-ac
    SIMD: AVX, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
    $JOHN is ./
    Format interface version: 13
    Max. number of reported tunable costs: 3
    Rec file version: REC4
    Charset file version: CHR3
    CHARSET_MIN: 1 (0x01)
    CHARSET_MAX: 255 (0xff)
    CHARSET_LENGTH: 24
    SALT_HASH_SIZE: 1048576
    Max. Markov mode level: 400
    Max. Markov mode password length: 30
    clang version: 7.0.0 (clang-700.1.76) (gcc 4.2.1 compatibility)
    OpenCL headers version: 1.2
    Crypto library: OpenSSL
    OpenSSL library version: 01000204f
    OpenSSL 1.0.2d 9 Jul 2015
    GMP library version: 6.0.0
    File locking: fcntl()
    fseek(): fseek
    ftell(): ftell
    fopen(): fopen
    memmem(): System's

    ./john --list=OpenCL-devices
    Platform #0 name: Apple, version: OpenCL 1.2 (Sep 21 2015 19:24:11)
    Device #0 (0) name:     Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Device vendor:          Intel
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2
    Driver version:         1.1
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          16.0 GB
    Global Memory Cache:    64.0  B
    Local Memory:           32.0 KB (Global)
    Max memory alloc. size: 4.0 GB
    Max clock (MHz):        2700
    Profiling timer res.:   1 ns
    Max Work Group Size:    1024
    Parallel compute cores: 8
    Speed index:            86400

    Device #1 (1) name:     HD Graphics 4000
    Device vendor:          Intel
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2
    Driver version:         1.2(Oct 13 2015 18:35:07)
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          1.0 GB
    Local Memory:           64.0 KB (Local)
    Max memory alloc. size: 384.3 MB
    Max clock (MHz):        1300
    Profiling timer res.:   80 ns
    Max Work Group Size:    512
    Parallel compute cores: 16
    Speed index:            20800

    Device #2 (2) name:     GeForce GT 650M
    Device vendor:          NVIDIA
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2
    Driver version:         10.6.47 310.42.05f01
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          1024.0 MB
    Local Memory:           48.0 KB (Local)
    Max memory alloc. size: 256.2 MB
    Max clock (MHz):        900
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 2
    Stream processors:      384  (2 x 192)
    Speed index:            345600

**Comment by magnumripper** [comment]
You're not the first with this problem. I have no idea what's wrong but the problem is you don't get your kernals copied to run/kernels. This should happen with `make`.

You can do it manually like this (from the base john directory)
```
$ mkdir -p run/kernels
$ cp src/opencl/* src/opencl_*.h run/kernels
```
After that you should be fine, but I would really *love* to understand why `make` doesn't do it for you.

**Comment by priorityinterrupt** [comment]
Great; that worked. For what its worth (if it helps you troubleshoot) the run/kernels directory did exist and have the following contents before the copy.  

    opencl_DES_hst_dev_shared.h	
    opencl_lm_hst_dev_shared.h	
    opencl_sha256.h			
    opencl_sha512.h
    opencl_device_info.h		
    opencl_misc.h			
    opencl_sha2_common.h

Thanks!

**Comment by magnumripper** [comment]
That's very interesting. So it got all the headers but not a single kernel. I need to dig into that.

**Comment by priorityinterrupt** [comment]
I installed a new virgin install of El Capitan in a virtual machine. The only things I did on this machine where:

Install El Capitan (using VMware Fusion to install from my recovery partition)
Applied all the Apple supplied Updates 
Install Xcode
Install xcode command line tools
Install Xterm2
Install Homebrew
brew install openssl
brew link --force openssl
brew install git 
git clone https://github.com/magnumripper/JohnTheRipper.git

I had the same exact results as described above. I obviously did not expect to actually use OpenCL on the VM but I wanted to see if it built any differently.

**Comment by magnumripper** [comment]
OK I can reproduce. It's a problem with native sed(1) not recognizing `\b` (and apparently that's not POSIX). I use GNU sed in /usr/local/bin so I never saw this.

**Comment by magnumripper** [comment]
On a side note, I have used to do things like `mv /usr/local /usr/local_` in order to get a "native" system (hiding all Homebrew stuff) but the new security features of El Capitan doesn't allow that. Now I had to `mkdir -p /usr/local/.disabled && mv /usr/local/* /usr/local/.disabled`.

**Comment by magnumripper** [comment]
I'm glad we nailed this one.
