### ISSUE TITLE
CUDA compile issue - OSX El Capitan 

### ISSUE THREAD

**Issue by priorityinterrupt** [magnumripper/JohnTheRipper#1868]
"Since CUDA is more or less deprecated right now, it's disabled by default if OpenCL is found." - README-CUDA

Since "more or less" is sort of ambiguous I don't know if anyone cares to address this or not. Its NOT important to me but I figure its worth mentioning. 

Since I am having issues with OpenCL at the moment and have a separate issue open for that I decided to try giving cuda a try. 

I installed the cuda components from Nvida for OSX.  I added the following paths to my .bash_profile.

    export PATH=/Developer/NVIDIA/CUDA-7.5/bin:$PATH
    export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$DYLD_LIBRARY_PATH 

I ran autoconfig with --enable-cuda --disable-opencl and I am getting the following make error:

    In file included from wpapsk.cu:9:
    In file included from ./../cuda_wpapsk.h:8:
    ./../wpapsk.h:20:10: fatal error: 'openssl/hmac.h' file not found
    #include <openssl/hmac.h>
         ^
    1 error generated.
    make[1]: *** [cuda_wpapsk.o] Error 1
    make: *** [default] Error 2

I have ran brew link --force openssl and /usr/local/include/openssl/hmac.h exists.  The Makefile does reference /usr/local/include/.

This is only a problem when I --enable-cuda.  I am running OSX El Capitan. 

    ProductName:	Mac OS X
    ProductVersion:	10.11.1
    BuildVersion:	15B42

Here is the build-info from a working build from the same source on the same system without using --enable-cuda:

    ./john --list=build-info
    Version: 1.8.0-jumbo-1-4150-g9cb4e47
    Build: darwin15.0.0 64-bit AVX-ac
    SIMD: AVX, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
    $JOHN is ./
    Format interface version: 13
    Max. number of reported tunable costs: 3
    Rec file version: REC4
    Charset file version: CHR3
    CHARSET_MIN: 1 (0x01)
    CHARSET_MAX: 255 (0xff)
    CHARSET_LENGTH: 24
    SALT_HASH_SIZE: 1048576
    Max. Markov mode level: 400
    Max. Markov mode password length: 30
    clang version: 7.0.0 (clang-700.1.76) (gcc 4.2.1 compatibility)
    OpenCL headers version: 1.2
    Crypto library: OpenSSL
    OpenSSL library version: 01000204f
    OpenSSL 1.0.2d 9 Jul 2015
    GMP library version: 6.0.0
    File locking: fcntl()
    fseek(): fseek
    ftell(): ftell
    fopen(): fopen
    memmem(): System's

**Comment by magnumripper** [comment]
I run 10.11.1, very latest CUDA and Homebrew openssl 1.0.2d. I can't reproduce! It just builds and works fine.

I do get these warnings, and they are new
```
./../wpapsk.h(203): warning: the "always_inline" attribute is ignored on non-inline functions

./../wpapsk.h(203): warning: the "always_inline" attribute is ignored on non-inline functions

```
...but they are mere warnings.

**Comment by magnumripper** [comment]
I see one difference: I have PATH with /usr/local/cuda *last*, not first. Maybe it matters?

**Comment by priorityinterrupt** [comment]
I just changed the order on mine sourced and confirmed the change.  Still getting the same error... I have a mac mini running as a media server I can try on.  Not sure if it has cuda capable hardware in it or not though.

**Comment by magnumripper** [comment]
Your devices indicate you have exactly the same system as me (an MBPr '2012 or so, right?). And we run the same version of El Capitan and we use Homebrew for OpenSSL. And we use the latest CUDA. So what the heck is different?!

**Comment by priorityinterrupt** [comment]
Yes a early 2013 MBP.

**Comment by priorityinterrupt** [comment]
I doubt it means anything but I do get a lot of these ptxas info messages before the error. 

    ptxas info    : Used 63 registers, 48 bytes cmem[0], 24 bytes cmem[16]
    ptxas info    : 0 bytes gmem, 288 bytes cmem[2]
    ptxas info    : Compiling entry function '_Z13kernel_sha256P15sha256_passwordP11sha224_hash' for 'sm_20'
    ptxas info    : Function properties for _Z13kernel_sha256P15sha256_passwordP11sha224_hash
        264 bytes stack frame, 8 bytes spill stores, 8 bytes spill loads

**Comment by magnumripper** [comment]
Those are perfectly normal. This is very very strange. I haven't ever had any problems with it and you run a virtually identical system.

Also, I haven't ever came across #1867. Why do you (and others) get that, but not me??

**Comment by priorityinterrupt** [comment]
I created a new virgin install of El Capitan in a VM as mentioned in #1867.

I installed the CUDA drivers and this error went away. I even was able to copy the run directory from the VM to my laptop and ran a cuda test successfully.

Still does not make any sense at all since openssl/hmac.h is present on my laptop and only a problem when compiling --enable-cuda but probably not worth investigating unless someone else mentions it.

**Comment by magnumripper** [comment]
Moving Homebrew (except openssl) out of the way, I can reproduce this too. This is new, it did not happen before El Capitan.

**Comment by priorityinterrupt** [comment]
Which makes me wonder why I was able to build in new VM I made.  Only Homebrew stuff being openssl and git.

**Comment by magnumripper** [comment]
Yeah that is strange. Anyway I have a fix in a minute.
