### ISSUE TITLE
sha512crypt-opencl fails on GeForce GT650M on OSX El Capitan

### ISSUE THREAD

**Issue by priorityinterrupt** [magnumripper/JohnTheRipper#1873]
I am unable to run sha512crypt-opencl on my GeForce GT650M.  It works fine on the integrated intel graphics.

Failing on GeForce GT 650M 

    ./john --dev=2 --test=30 --format=sha512crypt-opencl --log-stderr
    Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Device 2: GeForce GT 650M
    0:00:00:00 Device 2: GeForce GT 650M
    Abort trap: 6

Working on HD Graphics 4000

    ./john --dev=1 --test=30 --format=sha512crypt-opencl
    Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Device 1: HD Graphics 4000
    DONE
    Speed for cost 1 (iteration count) of 5000
    Raw:	554 c/s real, 75851 c/s virtual

Output of lldb. I have no idea what I am doing with lldb. If there is a better command to run let me know. 

    lldb ./john
    (lldb) target create "./john"
    Current executable set to './john' (x86_64).
    (lldb) run --test=30 --dev=2 --format=sha512crypt-opencl
    Process 45132 launched: './john' (x86_64)
    Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Device 2: GeForce GT 650M
    Process 45132 stopped
    * thread #1: tid = 0x742d5, 0x00007fff920090ae libsystem_kernel.dylib`__pthread_kill + 10, queue = 'opencl_runtime', stop reason = signal SIGABRT
    frame #0: 0x00007fff920090ae libsystem_kernel.dylib`__pthread_kill + 10
    libsystem_kernel.dylib`__pthread_kill:
    ->  0x7fff920090ae <+10>: jae    0x7fff920090b8            ; <+20>
    0x7fff920090b0 <+12>: movq   %rax, %rdi
    0x7fff920090b3 <+15>: jmp    0x7fff920043ef            ; cerror_nocancel
    0x7fff920090b8 <+20>: retq

Build Info 

    Version: 1.8.0-jumbo-1-4156-g65a0cf8
    Build: darwin15.0.0 64-bit AVX-ac
    SIMD: AVX, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
    $JOHN is ./
    Format interface version: 13
    Max. number of reported tunable costs: 3
    Rec file version: REC4
    Charset file version: CHR3
    CHARSET_MIN: 1 (0x01)
    CHARSET_MAX: 255 (0xff)
    CHARSET_LENGTH: 24
    SALT_HASH_SIZE: 1048576
    Max. Markov mode level: 400
    Max. Markov mode password length: 30
    clang version: 7.0.0 (clang-700.1.76) (gcc 4.2.1 compatibility)
    CUDA headers version: 7.5
    OpenCL headers version: 1.2
    Crypto library: OpenSSL
    OpenSSL library version: 01000204f
    OpenSSL 1.0.2d 9 Jul 2015
    GMP library version: 6.0.0
    File locking: fcntl()
    fseek(): fseek
    ftell(): ftell
    fopen(): fopen
    memmem(): System's

System Info

    ProductName:	Mac OS X
    ProductVersion:	10.11.1
    BuildVersion:	15B42

**Comment by magnumripper** [comment]
You ask for a `bt` in lldb just like with gdb. But it will just show that this happens in the driver. Unfortunately the OSX drivers got a lot worse with El Capitan. The Yosemite drivers worked with all of our formats. See #1786 and #1800 Not much we can do about it, but I sometimes manage to work around their dang bugs.
