### ISSUE TITLE
OpenSSL ( Again ! ) - El Capitan

### ISSUE THREAD

**Issue by denis0** [magnumripper/JohnTheRipper#1877]
Hi,

I continue my fight with this new El Capitan !

To follow the shared advices on my first thread here = https://github.com/magnumripper/JohnTheRipper/issues/1812#issuecomment-147208120

I compile my Own OpenSSL from source by following this tut => http://mac-dev-env.patrickbougie.com/openssl/

& unfortunately can't compile the last version of JTR as well !

I got again the same error as usual at the end ;

configure: error: in `/Users/cyril/desktop/jj/src':
configure: error: JtR requires OpenSSL headers being installed

I check ;

macbookpro:src xxxx$ which openssl
/usr/local/openssl/bin/openssl

macbookpro:src xxx$ openssl version -a
OpenSSL 1.0.2d 9 Jul 2015
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: cc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/openssl-1.0.2d/ssl"

macbookpro:~ xxxx$ cat .bash_profile
export PATH=/usr/local/openssl/bin:$PATH
export MANPATH=/usr/local/openssl/ssl/man:$MANPATH

maybe a problem of path or symlink ( aka = ln -s openssl-1.0.2d /usr/local/openssl ) ??

Can you please help me to fix it, thank you in advance,

Regards,

Denis

**Comment by DomT4** [comment]
Either install `pkg-config` and export your OpenSSL's `pkg-config` path or pass CFLAGS/LDFLAGS. It won't automatically find it in non-standard paths.

**Comment by magnumripper** [comment]
Thanks @DomT4 

@denis0 this is a bug tracker, please do not use it for support. The john-users mailing list is a better place for support.
