### ISSUE TITLE
different input for --make-charset:

### ISSUE THREAD

**Issue by jun0s** [magnumripper/JohnTheRipper#1878]
Maybe john can make a charset of a wordlist and not only pot files? i try with --make-charset:namefile -pot:wordlistx.txt and --make-charset:namefile anydic.txt and dont work.

thanks.. and i am sorry for my bad english.

**Comment by frank-dittrich** [comment]
If you just have a word list, you can create a dummy pot file (the first colon will be used as separator between "hash" and password).
```
LC_ALL=C grep -a -n "^" wordlist > dummy1.pot
./john --pot=dummy1.pot --make-charset=test1.chr
```
Even a dummy pot file with ':' as the first character of each line would work.

**Comment by magnumripper** [comment]
This is not a support forum though. You are only support to report bugs here.

**Comment by frank-dittrich** [comment]
@magnumripper I thought this was a feature request, and provided a workaround.
(It might not be obvious that a dummy pot file works for --make-charset.)

**Comment by jun0s** [comment]
already knew similar option, but thank u frank... and yes, this was a feature request.

**Comment by frank-dittrich** [comment]
@jun0s GIven that such an easy workaround exists (you can just delete the dummy pot file after generating the .chr file), I don't think we need a new feature here.

**Comment by magnumripper** [comment]
Oh, pardon my brutal closing then :sunglasses:

**Comment by magnumripper** [comment]
Yeah it's easy enough to do without it. However, if you're to build a charset from a huge wordlist (and perhaps while running off pendrives), it would come handy. And it should be really trivial to implement. I'll give it a thought.

**Comment by magnumripper** [comment]
I'm not sure about option syntax. @frank-dittrich how about this?
`./john --make-charset=custom.chr` normal behavior (use default john.pot and expect colons)
`./john --pot=some.pot --make-charset=custom.chr` normal behavior (expect colons)
`./john --wordlist=some.txt --make-charset=custom.chr` wordlist behavior (do not expect colons)

**Comment by frank-dittrich** [comment]
I still think that feature is not needed.
Allowing --wordlist with --make-charset just complicates things (you have to avoid the combination of --make-charset with --wordlist and --pot).
But if you still want to implement this, `(do not expect colons)` is confusing, because colons are allowed (They are just part of the input word...)

**Comment by frank-dittrich** [comment]
If you implement this, think about a way to compute a Markov stats file from a pot file instead of a word list.

**Comment by magnumripper** [comment]
> I still think that feature is not needed.
Allowing --wordlist with --make-charset just complicates things (you have to avoid the combination of --make-charset with --wordlist and --pot).

I believe it's very trivial and I actually often cursed the need for needing to create a potentially huge interim file. The options parsing is a very small change, (once you figure it out, which admittedly can be like a pro-level Sudoku).

> But if you still want to implement this, (do not expect colons) is confusing, because colons are allowed

Of course, I was just being terse here.

> If you implement this, think about a way to compute a Markov stats file from a pot file instead of a word list.

Good idea. Should also be trivial.
