### ISSUE TITLE
Try to get closer to Jumbo-2

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1879]
Here's current **blockers** for a Jumbo-2. Tick off, or add to, this list as needed.
- [ ] #2437 Unprintable characters in pot file after cracking a dynamic_25 hash ( @jfoug )
- [ ] #1911 Credits, changes ( @magnumripper )

---

Here's [all current bugs](https://github.com/magnumripper/JohnTheRipper/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
Here's [everything marked with Jumbo-2 milestone](https://github.com/magnumripper/JohnTheRipper/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.8.0-jumbo-2)

**Comment by magnumripper** [comment]
Some of the blockers are depending on @Sayantan2048. I've tried to address them but I don't seem to get anywhere.

**Comment by jfoug** [comment]
#1428 ?
#1289 ?
#1199 ?
#570 ?

Should we change the other jumbo-2 to jumbo-3 ?

**Comment by magnumripper** [comment]
Those you list (and some others) should be fixed if possible but are definitely not blockers. They can be tagged J2 for now but may change to J3.

I changed a number of enhancements/new-formats to J3 milestone (or no milestone).

**Comment by magnumripper** [comment]
BTW I don't care much about JP problems if Solar doesn't bother fixing them. When we're done with our blockers and some more testing, we can suggest to Solar we're ready for a release and he may consider fixing #1199 and others while at it.

(JP is what I suggest we call "John Proper" aka "non Jumbo" from now on - "core" is better used for core *code* as in cracker.c and loader.c - basically anything but formats)

**Comment by jfoug** [comment]
That was my reason for including #1199.    how about JPr ? :)  Or even JB  (john base)

**Comment by magnumripper** [comment]
Someone apparently added non-blockers like #883 to the list. I'll let them stand for now, it would be awesome to get all of them fixed but they are definitely not blocking a release of Jumbo 2.

**Comment by jfoug** [comment]
I added everything to this list which was marked as J2.   I know you removed a bunch, but someone else re-marked them.  If they are in the search for J2, they are also on this list.

**Comment by magnumripper** [comment]
That's 100% redundant. A list of *blockers* is not. Fixing things like #883 is not very important - if it's not fixed we'll just move it to J3. Same goes for many others.

**Comment by magnumripper** [comment]
I dropped the non-blockers from the list.

**Comment by jfoug** [comment]
bump!!   jumbo 1 is REALLY getting dated, and is what is in all the distro's that install john.

**Comment by magnumripper** [comment]
We've got lots of bugs: https://github.com/magnumripper/JohnTheRipper/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by jfoug** [comment]
Many of those 'bugs' are far from show stoppers.

**Comment by magnumripper** [comment]
Sure, but most of them should definitely be fixed before a release.

**Comment by kholia** [comment]
If we want to make this release, I think we have to drop some "blocker" bugs for this issue.

For example,  #1746 doesn't look like a blocker bug to me. #1908 is about performance, doesn't sounds like a blocker.

**Comment by kholia** [comment]
@Sayantan2048 seems gone for a while. We have a workaround for #1782 which works fine, so it doesn't sound like a blocker.

**Comment by magnumripper** [comment]
I really think #1746 should be fixed, but in a pinch we could just document it as "some combinations simply won't work right now - but they will fail self-test".

I removed the milestone from #1782 and #1908.

**Comment by magnumripper** [comment]
I dropped #1938 as well, it's just a variant of #1782.

**Comment by claudioandre** [comment]
There is another critical bug that needs attention: the --restore bug. 
* it misses candidates (oh, it is a bad bug).

**Comment by magnumripper** [comment]
Yeah I was just going to add that we need lots and lots of soft-stop/restore and hard-stop/restore testing after all changes @jfoug did to resuming. I've found and fixed bugs since that and I suspect there are more. That "restore tester format" doesn't seem very good since he actually *introduced* bugs when using it 😢

**Comment by claudioandre** [comment]
I know @solardiz and @magnumripper are busy people, but we are seeing "messages", the Fedora 23 issue I just post (no link on purpose) is only the latest, suggest that people might became confused and disappointed about JtR maintenance status.

**Comment by solardiz** [comment]
We definitely ought to make a new numbered release soon. I'd appreciate it if you folks get jumbo closer to that state. From my side, I intend to release 1.8.1, in part so that jumbo's version number differs from the previous one at least this little bit more. ;-) So let's plan to release a 1.8.1-jumbo-1 soon - perhaps in two months?

**Comment by magnumripper** [comment]
We have a really nasty blocker in #2817 now. I wish Jim could come back to us for a while again...

**Comment by jfoug** [comment]
I will be around some shortly, and will look into #2817  I am actually retiring from tech at the end of the year, and moving towards more peace in my life.  I am just tired of the corp rat race.

**Comment by kholia** [comment]
@jfoug Having you back would be awesome. I tried hacking on the dynamic compiler recently but didn't find a good solution for the problem I was trying to solve.

**Comment by magnumripper** [comment]
Closing this in favor of a new one
