### ISSUE TITLE
dynamic_20: Cisco ASA MD5 hashes with salt length smaller than 4 don't load

### ISSUE THREAD

**Issue by hypn0s** [magnumripper/JohnTheRipper#1887]
I was testing the hashcat Cisco ASA MD5 example against John the Ripper and it doesn't load with the dynamic format dynamic_20:
```
$ cat cisco_asa_md5_dynamic_20
test-Cisco-ASA:$dynamic_20$02dMBMYkTdC5Ziyp$36
$ ./john --format=dynamic_20 cisco_asa_md5_dynamic_20 
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

But it is loaded when I use the format asa-md5:
```
$ cat cisco_asa_md5 
test-Cisco-ASA:02dMBMYkTdC5Ziyp:36
$ ./john --format=asa-md5 cisco_asa_md5
No dupe-checking performed when loading hashes.
Using default input encoding: UTF-8
Loaded 1 password hash (asa-md5, Cisco ASA [md5($p.$s) (Cisco ASA) 256/256 AVX2 8x3])
...
```

Moreover, it is loaded when I provide a salt with at least 4 bytes:
```
$ cat cisco_asa_md5_dynamic_20_salt4
test-Cisco-ASA:$dynamic_20$02dMBMYkTdC5Ziyp$test
$ ./john --format=dynamic_20 cisco_asa_md5_dynamic_20_salt4  
No dupe-checking performed when loading hashes.
Using default input encoding: UTF-8
Loaded 1 password hash (dynamic_20 [md5($p.$s) (Cisco ASA) 256/256 AVX2 8x3])
Warning: no OpenMP support for this hash type, consider --fork=8

```

**Comment by jfoug** [comment]
```
$ cat cisco_asa_md5 
test-Cisco-ASA:02dMBMYkTdC5Ziyp:36
$ ./john --format=asa-md5 cisco_asa_md5
No dupe-checking performed when loading hashes.
```

Note, the only reason that worked, is because the asa code made this into the hash:

$dyanmic_20$02dMBMYkTdC5Ziyp$test

It took first 4 bytes of user name, and used as hash.

This was hard coded to only handle 4 byte salts.  I will fix this to handle salts from 1 to 4 bytes (truncated user name).

**Comment by jfoug** [comment]
do you know the password that cracks this hash (hashcat often uses hashcat as the password, so I will check that)

**Comment by hypn0s** [comment]
Yes, the password is 'hashcat'.

**Comment by jfoug** [comment]
Please test. It cracks the sample hash just fine after change.

**Comment by hypn0s** [comment]
Yes, it works well now. Thank's!
