### ISSUE TITLE
Fails to generate generic.h with legacy Makefile

### ISSUE THREAD

**Issue by rhertzog** [magnumripper/JohnTheRipper#1894]
Following your advice in #1656 I opted to use the legacy Makefile... unfortunately, the jumbo changes break the build of generic.h which is currently used by the "generic" target that is by the Debian package for the armel and armhf port.

The problem is that memdbg.h includes memory.h which in turn includes arch.h. But arch.h does not exist at that point since we want to turn it into a symlink to generic.h that the make rule is currently building...

Here's the log of the failing build (reproducable with make -f Makefile.legacy generic.h):
```
rm -f arch.h
gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DJOHN_SYSTEMWIDE
-DJOHN_SYSTEMWIDE_EXEC=\\\"/usr/lib/john\\\" -DCFG_FULL_NAME=\\\"/etc/john/john.conf\\\" -c -Wall -Wdeclaration-after-statement -O2
-fomit-frame-pointer -I/usr/local/include `find 2>&1 /usr/include/librexgen/api/c /usr/local/include/librexgen/api/c -name "librexgen.h" | grep -q
"librexgen.h" && echo -DHAVE_LIBREXGEN=1` `find 2>&1 /usr/include /usr/local/include -name "gmp.h" | grep -q "gmp.h" && echo -DHAVE_LIBGMP`
detect.c
<command-line>:0:23: warning: missing terminating " character
<command-line>:0:16: warning: missing terminating " character
In file included from memdbg.h:25:0,
                 from detect.c:16:
memory.h:22:18: fatal error: arch.h: No such file or directory
compilation terminated.
make[2]: *** [generic.h] Error 1
Makefile.legacy:1943: recipe for target 'generic.h' failed
```

**Comment by magnumripper** [comment]
Thank you for reporting. Hopefully, @frank-dittrich will give the legacy Makefile some TLC sooner or later. Meanwhile, I updated #1656 with a link to a recently added wiki page on how to create fallback chains **with** autoconf.

**Comment by magnumripper** [comment]
@jfoug why does memdbg mess with stuff when not activated?

**Comment by jfoug** [comment]
I think this was needed for aligned allocations

**Comment by frank-dittrich** [comment]
@rhertzog @magnumripper Some of my recent commits fixed legacy build problems.
Currently, `make -s -f Makefile.legacy clean; make -s -f Makefile.legacy generic` works for me, on a 64bit linux AVX system and on a Raspberry Pi 2.


Please let mew know if there's anything else that needs to be fixed for legacy generic builds.

**Comment by magnumripper** [comment]
Closing this - @rhertzog please reopen if there's still problems.
