### ISSUE TITLE
Add support for cracking signed JWT tokens

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#1898]
* https://en.wikipedia.org/wiki/JSON_Web_Token

* https://github.com/jmaxxz/jwtbrute

**Comment by jfoug** [comment]
Does this:  https://github.com/magnumripper/JohnTheRipper/commit/85aa7b3e3f8204360683ddc5ec9734bf793d07cf  complete this task ?

**Comment by magnumripper** [comment]
It definitely does for HMAC-SHA256, which should be most common (required for all implementations). We could probably add almost exactly same code to some more formats with ease: [RFC7518](https://tools.ietf.org/html/rfc7518#section-3.1) mentions HMAC-SHA-384 and HMAC-SHA-512 too (as "recommended" for implementations). So I think we should do them too.

It also mentions some other recommended: RSASSA-PKCS1-v1_5 and ECDSA. I guess we'll leave them for now.

**Comment by magnumripper** [comment]
BTW we could add the official test vectors as well, that is always a good thing: https://tools.ietf.org/html/rfc7518#appendix-B

**Comment by jfoug** [comment]
Can we get samples of sha384/sha512 variants?  Also, have we increased the salt length of those formats?

**Comment by magnumripper** [comment]
Ah, no the salt fixes should be replicated too. 2d353eda1, 23f77d2a and 2f8a9b135.

**Comment by magnumripper** [comment]
BTW isn't there more fixes needed, allowing for nulls in the salt? We currently treat it as a C string, doing strlen and so on.

**Comment by jfoug** [comment]
Yes, I produced a patch that 'fixed' the problems.  This was the original stuff, where get_salt was setting the salt length, so only the last salt loaded set the length.

**Comment by jfoug** [comment]
https://github.com/magnumripper/JohnTheRipper/commit/23f77d2a91a8669937fa0916b896d007f7f6146b and https://github.com/magnumripper/JohnTheRipper/commit/2f8a9b1353b98e3b38e4e4661130ca41c8414416 were the corrections for your original code.

**Comment by jfoug** [comment]
JWT does not have nulls in the salts.  The salts are the original base64 string.

IF the jwt string was 
fdljkalsfdjk.lfskjflkasjdflkjalsf.lllllllllllllllll

Then the salt is fdljkalsfdjk.lfskjflkasjdflkjalsf  and the result is the base-64 decode of lllllllllllllllll  (the 3rd part).

If you base-64 decode the first 2 parts, you see the json stuff, BUT the salt is not the decoded parts, it is the original base-64 encoded data.

**Comment by magnumripper** [comment]
Aha, cool. I would still like to let us use binary salts for generic HMAC but it can wait to later.

**Comment by magnumripper** [comment]
Added SHA384 & SHA512. Test vectors are mock-ups, we should try to find real stuff. If we see some other algo needed, let's open new issue(s).
