### ISSUE TITLE
pkzip format fails

### ISSUE THREAD

**Issue by MikeDawg** [magnumripper/JohnTheRipper#1900]
Attempting to use john to crack a pkzip format hash, fails, with the following error:

Error, Invalid signature line trying to link to dynamic format.
Original format=md5ns
Signature line=$dynamic_2004$HEX CHARS$HEX$HEX CHARS

I was attempting to crack the following hash (created with zip2john):

Data.zip:$pkzip2$1*2*2*0*20*14*HEX CHARS*0*42*0*20*ff1e*0b48*HEX CHARS*$/pkzip2$:::::/tmp/Data.zip

NOTE: HEX CHARS is not the original message, just inserted as a placeholder for hex characters.

**Comment by frank-dittrich** [comment]
I bet you somehow managed to delete your config files, move them to an unexpected location, or you replaced john.conf with an older version (likely one from a release without dynamic formats support).

Furthermore, this problem is not related to pkzip.

What john version are you using? Please post the output of
```
./john --list=build-info
```

**Comment by MikeDawg** [comment]
# ./john --list=build-info
Version: 1.8.0-jumbo-1-4263-g950de64
Build: linux-gnu 64-bit XOP-ac OMP
SIMD: XOP, interleaving: MD4:2 MD5:2 SHA1:1 SHA256:2 SHA512:1
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.1.1
GNU libc version: 2.22 (loaded: 2.22)
Crypto library: OpenSSL
OpenSSL library version: 01000204f
OpenSSL 1.0.2d-fips 9 Jul 2015
GMP library version: 6.0.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's


So, you might be on to something, because I had to initially create a blank john.conf file, Let me copy over the one from the ./run directory, and see if that fixes the problem.

**Comment by frank-dittrich** [comment]
The john.conf file from the run directory "includes" other *.conf files, so you'll need to copy those other config files as well..

**Comment by magnumripper** [comment]
I would recommend not moving stuff away from the run directory at all (or copy *all* of it)

**Comment by MikeDawg** [comment]
So, with that being said. I attempted to get rid of the /run directory, at ./configure time, by using --prefix=/pentest/john/ however, the /pentest/john/run directory was still created, and the binaries were still put in there. Is there a different configuration option that should be used as opposed to --prefix? maybe something like --sbindir or --bindir?

**Comment by magnumripper** [comment]
Actually the autoconf `--prefix` option is pretty much broken. It will be reworked soon.

I think what you are after is "systemwide", which is soon documented. For now there is some notes in https://github.com/magnumripper/JohnTheRipper/wiki/Fallback-binary-chains

**Comment by MikeDawg** [comment]
Thanks. For the time being, I'm copying run/*
