### ISSUE TITLE
JOHN_PRIVATE_HOME ignores $HOME

### ISSUE THREAD

**Issue by dunn** [magnumripper/JohnTheRipper#1901]
Maybe this should be sent to Openwall instead of here, if so let me know.

In `params.h`, `JOHN_PRIVATE_HOME` is set to `~/.john`.  The way `~` is evaluated ignores the `HOME` environment variable, so it always tries to write logs and recovery files to the user's actual home directory.  (This is causing problems in Homebrew, where we run tests in a sandbox and set `HOME` to a temporary directory.)

**Comment by magnumripper** [comment]
Please report this to the john-users mailing list.

**Comment by dunn** [comment]
Done: http://openwall.com/lists/john-users/2015/11/23/2

Feel free to close this issue if there's nothing to do on this end but hope upstream fixes it.

**Comment by magnumripper** [comment]
Thanks. From Solar's answer I take it we need to fix it in Jumbo. I'll have a look at this sooner or later, unless you or someone else does and make a PR.

**Comment by magnumripper** [comment]
Fixed in d29ad8aa
