### ISSUE TITLE
LM-OpenCL allocations fail in 32-bit mode

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#1906]
LM-opencl allocates a lot of contiguous main memory. It allocates equal amounts of normal memory as it does GPU memory, So if you allocate 512MB of GPU memory, it tries to do a giant 512MB malloc, which on many 32-bit systems will fail because the allocation has to be CONTIGUOUS, while on 64-bit systems, I have not seen it fail. This happens during the autotuning process.

If there's a way to avoid needing to allocate that much main memory at once, that would be more efficient and less likely to crash. 

It would also seem that it has its own autotuning code. Not sure why that's not using generic code for all opencl kernels or why it's different.

**Comment by magnumripper** [comment]
We are usually not allocating memory on the host side, only address space. I'm not sure about LM though. @Sayantan2048 what do you say about this?

And I agree about auto-tune, this is kind-of included in #1835.

**Comment by magnumripper** [comment]
On another thought, we do allocate actual memory on host side - we have to! But yes, 512MB sounds a bit too much.

**Comment by crioux** [comment]
On my branch, I have found that capping the gws_limit in gws_tune() to "	gws_limit = 100000; " not only keeps the memory where it needs to be, but also has minimal impact on performance.

Probably not the optimal fix, but it's better than blowing out all the memory on the machine.

**Comment by crioux** [comment]
Another side effect of this,and the common autotuning used by nt-opencl and others, is that if you have two john nodes/processes running at once, for two GPUs cores in parallel that happen to share one bank of GPU memory (like my HD 7990), you can have a scenario where one process is 'autotuning' and blowing out the memory of the card, while another process is attempting to allocate a buffer, which causes the second process to fail.

Not sure what to do about it. 

If I ran the zoo, i'd have ripped out all the autotuning calls all over the place and just made john use sensible defaults unless overriden by the command line (--gws-limit?) or john.conf, and provide a command line option "john --autotune --format=nt-opencl --device=1" or whatever to generate the 'best autotuning settings' for a particular hash format, so you can put those in your local john.conf

**Comment by claudioandre** [comment]
It is (will be) possible to do something like this (per format, per board). 
1. BUT there is going to be a lot of defaults in john.conf (via .include, I guess).
2. opencl_speed_index() cannot be used to do the calculation. well is a example: the best GPU [1] uses the smallest GWS value. 
3. this is shared code, when implemented it will work in all formats (that uses shared tuning).

[1] both clock and processor count are better.

```
diff --git a/run/john.conf b/run/john.conf
index e66ce45..1a1aef5 100644
--- a/run/john.conf
+++ b/run/john.conf
@@ -318,9 +318,10 @@ AutotuneLWS = 1
 # Best configuration value to be used at runtime.
 sha512crypt_Bonaire = -DUNROLL_LOOP=132104
 
-# Example: Override auto-tune for RAR format.
-#rar_LWS = 128
-#rar_GWS = 8192
+# Sensible default values for LWS and GWS.
+# Using zeros in environment LWS or GWS will override these settings.
+sha256crypt_Tune_Juniper = 64, 65536
+sha512crypt_Tune_Juniper = 64, 32000
```

**Comment by magnumripper** [comment]
> If I ran the zoo, i'd have ripped out all the autotuning calls all over the place and just made john use sensible defaults unless overriden by the command line (--gws-limit?) or john.conf, and provide a command line option "john --autotune --format=nt-opencl --device=1" or whatever to generate the 'best autotuning settings' for a particular hash format, so you can put those in your local john.conf

LOL, that's how it worked years ago and it was crappy as h3ll: One problem with that approach is that the recorded tune settings may be completely wrong for a later run (say, with a totally different iteration count, or a totally different password length in RAR3). Another is that Joe Random Luser wont do the autotune, so he ends up using the crappy defaults and then writes JtR off as the slowest cracker on earth. BTW there is no such thing as "sane defaults" considering the possible device speed ranges from ridiculous to astonishing.

I suspect you draw conclusions from seeing the LM format - but that one is not release ready at all so you can't. It allocates far too much memory and uses some oddball auto-tune code that is bad in so many ways. The NT format, and other ones that use the shared code, should be perfectly fine. As far as I can see, NT-opencl never allocates more than tens of megabytes (so the original issue here doesn't apply) even on Titan X, and it's quick on any device.

**Comment by magnumripper** [comment]
> It is (will be) possible to do something like this (per format, per board). 

I don't really object to that, but I will never use it myself, ever. Auto-tune is the only way ahead - that's my story and I'm sticking to it! We can still make that auto-tune quicker and better (we certainly have done so over time) and that is always a win.

**Comment by crioux** [comment]
Yea, forget what I said. Autotune can be made to work, it's just that blowing out the resources of the card to do it can have unintended consequences, like other things failing elsewhere. Not sure what the best thing to do is. In my branch i'm capping the 'get_max_mem_alloc_size' to the number divided by the node count, which isn't right if you're running nodes on other machines. Anyway, complicated.

**Comment by magnumripper** [comment]
There's no reason to blow out resources - if some format does (eg. LM-opencl), it should be fixed. BTW we never do a single malloc on GPU that is larger than a quarter of it's total memory. This should normally leave plenty of headroom for concurrent processes on your 7990.

**Comment by magnumripper** [comment]
Anyway, I'm closing this - we already have issues for dropping the custom auto-tune functions in favor of the shared code.

**Comment by claudioandre** [comment]
Thinking about it: a patch like this is mandatory (at least, if a user uses --fork=n and n > 4).

```
diff --git a/src/common-opencl.c b/src/common-opencl.c
index 730a035..5478957 100644
--- a/src/common-opencl.c
+++ b/src/common-opencl.c
@@ -1955,7 +1955,7 @@ size_t get_device_max_lws(int sequential_id)
 
 cl_ulong get_max_mem_alloc_size(int sequential_id)
 {
-       cl_ulong max_alloc_size;
+       cl_ulong alloc_size, max_alloc_size;
 
        HANDLE_CLERROR(clGetDeviceInfo(devices[sequential_id],
                                       CL_DEVICE_MAX_MEM_ALLOC_SIZE,
@@ -1963,6 +1963,15 @@ cl_ulong get_max_mem_alloc_size(int sequential_id)
                                       &max_alloc_size, NULL),
                       "Error querying CL_DEVICE_MAX_MEM_ALLOC_SIZE");
 
+       if (options.fork) {
+               HANDLE_CLERROR(clGetDeviceInfo(devices[sequential_id],
+                                      CL_DEVICE_GLOBAL_MEM_SIZE,
+                                      sizeof(max_alloc_size),
+                                      &alloc_size, NULL),
+                      "Error querying CL_DEVICE_GLOBAL_MEM_SIZE");
+
+               max_alloc_size = MIN((max_alloc_size), (alloc_size / options.fork));
+       }
        return max_alloc_size;
 }
```

**Comment by claudioandre** [comment]
BTW: the 4 seen above is implementation dependent (could be 2 and it will be ok according to the OpenCL specification).

**Comment by magnumripper** [comment]
Why is it needed? If you use --fork=*n* you probably have *n* cards.

**Comment by magnumripper** [comment]
For the specific case of a 7990 with two chips sharing the same memory (BTW I did not know about that until @crioux mentioned it), something along the lines of that could be needed though. But we can't assume that, and that card is not suitable for cracking anyway. AFAIK no such card on the market has proper cooling for sustained password cracking.

**Comment by magnumripper** [comment]
> BTW: the 4 seen above is implementation dependent (could be 2 and it will be ok according to the OpenCL specification).

True. But I have yet to see any device report more than a quarter. I heard some devices report less than a quarter though (I think it's some AMD with plenty of vram) and I think they'll under-report for CL_DEVICE_GLOBAL_MEM_SIZE as well. I have no idea why, it just sounds silly in my ears.

**Comment by claudioandre** [comment]
> Why is it needed? If you use --fork=n you probably have n cards.

Oh, I'm thinking about fast hashes on 1 card.

**Comment by magnumripper** [comment]
You mean using fork in lack of good GPU-side generation. Well, you can always bypass auto-tune using john.conf or environment variables. And yes, we could create some mechanism similar to that patch above - but (afaics) we can't allow it to kick in unless specifically requested.

**Comment by magnumripper** [comment]
> unless specifically requested.

Perhaps it's not too hard to actually determine this from some other parameter. It's kind of similar to what I did today with c2dbd45f for MPI - at first I thought it was "impossible" without some weird extra option but once I realized how to do it, that was very simple. In that case, the criteria was "if I am an MPI process, and there are *no other* MPI processes for the same job **on this host**, then do not let the "poor man's multi-device support" kick in". After that patch, I can run one mscash2 process using *n* devices, or *n* processes using 1 device each, as I please - without any special option.

So - in this case what's the criteria? I guess it would be something like "if we are using fork, and the device list is shorter than the number of processes [ie. we have to re-use same device], then { your patch }". Something like that, right?

**Comment by claudioandre** [comment]
Notice that it does not harm. 
- Using -fork=4 -dev=1,2,3,4 will give you the same results as it does now.
- Using -fork=8 -dev=1,2,3,4 means divide 'TOTAL memory' by 2. And if it is smaller than CL_DEVICE_MAX_MEM_ALLOC_SIZE, do something.
```
max_alloc_size = MIN((max_alloc_size), (alloc_size / (options.fork / get_number_of_devices_in_use())));
```

**Comment by magnumripper** [comment]
You are right. And this will never apply to MPI and AFAIK we can't have more than 8 devices locally. So yeah maybe we should try it.
