### ISSUE TITLE
Odd Benchmarks

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#1907]
On my hardware, in both x86_64 and x86 compilations, I get just about the same c/s rate for SSE2, SSSE3, SSE41 for all the hashes I care about. LM, NTLM, DES/Crypt etc.

XOP and AVX modes run slower by a factor of 5.

I am integrating JtR into L0phtCrack 7, and attempting to understand why these modes, which naively should be faster are not faster. For example, one would imagine than an SSE41 compilation would be faster than an SSE2 one, and that AVX should be faster than either of them, but it's not the case.

This screen capture is from a part of the program I am currently working on, which basically runs 'john --test=5 --format=<format>' for the various formats, across each of the jtr versions, and attempt to pick the fastest mode. Each of these numbers is for one core (for my debugging purposes).

![image](https://cloud.githubusercontent.com/assets/819652/11330796/6162d186-9166-11e5-9f0b-1f78f8165a3b.png)

If someone could help me understand the c/s I am seeing that would be great.
I am compiling JtR differently than the stock makefile and attempting to determine if this is the kind of performance you would expect and is common, or if i am somehow compiling things different and/or wrong. 

Not a bug report, just wondering if this is normal.

**Comment by magnumripper** [comment]
First, we're mostly hitting a bottleneck in candidate generation. An AVX2 build does show a significant bump in performance but does also suffer even more from that bottleneck. For fast GPU formats, using -mask:?a?a will render Gc/s speeds but doing `-test -mask` is WIP (see #1835). It currently works for NT but not for LM or DES IIRC.

Second, we basically tune things to whatever CPU we happen to use. Right now we're almost exclusively testing on Intel. While I believe differences like 31.169 vs. 30.801 might be random variations rather than a regression (try running them several times and see if/how it fluctuates) it can admittedly also be real regressions. We do use the theoretical best code for each arch but sometimes the whole picture (which is very complex) doesn't match the one naively zoomed in on the hash function alone. We've always seen large variations among different CPU types.

And BTW, for a custom build tuned to your CPU & toolchain you might want to try running `./testparas.pl` in the src directory, and then re-build according to the output. It might give a significant boost. This ultimately needs to be done separately for each arch.

**Comment by kholia** [comment]
`I am integrating JtR into L0phtCrack 7..`

This sound pretty cool, and the work seems to be happening in,
https://github.com/crioux/jtrdll/commits/bleeding-jumbo repository.

I don't understand the project goals but it would be nice if we can figure out ways to upstream most of the changes, if possible :)

**Comment by crioux** [comment]
The variations appear to be random variation, and not regression. The concern is that even in test mode (which, can't possibly have that high of a 'candidate generation' bottleneck!) that the SSE2 version is somehow the fastest one in many cases. It's like why bother compiling for an enhanced instruction set if you're not going to get enhanced performance?  To my naive brain, this either means I'm doing something wrong, or there's something implemented suboptimally. 

I will try working with the compilation settings some and tracing through this. It could just be something I'm doing wrong. And I'll test on my hardware with an 'official' build as well, for comparison purposes and report back.

**Comment by magnumripper** [comment]
> XOP and AVX modes run slower by a factor of 5.

This is definitely something amiss. AVX and XOP use to be significantly faster than anything below it.

**Comment by crioux** [comment]
Due to using MSVC in my compilation there are a number if GNUC dependent ifdefs that may be resulting in suboptimal performance. For now assume this is my problem. 

I will confirm and report back.

Either way I will have recommendations for MSVC compilation that you could incorporate.

**Comment by magnumripper** [comment]
Oh, that probably explains it. Jim put some MSVC stuff in there that is totally for debugging and not for real use. Like this, in pseudo-intrinsics.h
```c
#if _MSC_VER && !_M_X64
/*
 * These are slow, but the F'n 32 bit compiler will not build these intrinsics.
 * Only the 64-bit (Win64) MSVC compiler has these as intrinsics. These slow
 * ones let me debug, and develop this code, and work, but use CPU
 */
#define _mm_set_epi64 __mm_set_epi64
#define _mm_set1_epi64 __mm_set1_epi64
_inline __m128i _mm_set_epi64(long long a, long long b)
{
	__m128i x;

	x.m128i_i64[0] = b;
	x.m128i_i64[1] = a;
	return x;
}
_inline __m128i _mm_set1_epi64(long long a)
{
	__m128i x;

	x.m128i_i64[0] = x.m128i_i64[1] = a;
	return x;
}
#define vset1_epi64x(x)         vset_epi64x(x, x)
#define vset_epi64x(x1, x0)     (vtype)(vtype64){x0, x1}
#endif
```
We don't really support using MSVC, only Cygwin and MinGW.

**Comment by magnumripper** [comment]
OTOH that bad stuff only happens for 32-bit. Are you running 64-bit?

**Comment by crioux** [comment]
i am running both 32 and 64 and observing similar behavior on both. its probably my build process.

an effect of my branch will be full MSVC support, albeit using my cmake build on jtrdll.

**Comment by magnumripper** [comment]
FWIW here's my i7-3615Q, 2.30GHz

build | NT | LM | DEScrypt | Bcrypt
----|----|---|---|---
SSE2 | 38240K | 62849K | 7766K | 4633
AVX | 44606K | 75595K | 15728K | 4680

**Comment by crioux** [comment]
Okay, i'm pretty sure this is my issue now. Due to restrictions of MSVC only on 32-bit, AVX, AVX2 and XOP modes are not allowed as written due to the s-boxes implementation passing __m128i parameters by value and expecting 16 byte alignment. http://stackoverflow.com/questions/16264802/visual-studio-parameter-alignment-restrictions-and-windows-x64-abi
I also had some compilation settings that were off. Will post adjusted benchmark shortly.

**Comment by crioux** [comment]
Okay, this was definitely my issue.

1. Not building with all the right flags.
2. Looking at debug build numbers for 64-bit not release build.
3. I can't use >AVX on 32-bit due to MSVC limitations the way the code is written (might be able to refactor to get this, not sure if there's a point though)

Here's an updated 'calibration dialog' from LC7 that shows the speeds on my machine:
![image](https://cloud.githubusercontent.com/assets/819652/11459399/abe4b7b4-968a-11e5-8d95-6112ae7a2abf.png)

And with that I'm closing this so we can move on :)
