### ISSUE TITLE
Update doc/CREDITS-jumbo and doc/CHANGES-jumbo

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1911]
Note to self!

**Comment by magnumripper** [comment]
Bump

**Comment by magnumripper** [comment]
Bump (this has been addressed a couple of times but it's due again)

**Comment by magnumripper** [comment]
Updated again now

**Comment by magnumripper** [comment]
Updated today, fa80d62f2

**Comment by magnumripper** [comment]
Updated just now

**Comment by magnumripper** [comment]
Unless we find some more bugs to fix, this is updated for 1.9.0-Jumbo-1 now

**Comment by solardiz** [comment]
We'll definitely at least update NEWS. Do those commits not count? ;-)

**Comment by solardiz** [comment]
Also, #3926 wasn't merged yet. Now it is.

**Comment by magnumripper** [comment]
Yeah I saw. #3926 deserves an update but minor things like a final NEWS update obviously isn't that important, especially not in terms of crediting. Having said that, I'll try to update it right before doing the release commit and tagging.

**Comment by magnumripper** [comment]
BTW we should probably rename `CHANGES-jumbo.git` to something else (now or later). The .git extension is confusing.

**Comment by magnumripper** [comment]
There's an other file actually called CHANGES-jumbo, more resembling our new NEWS file. I suggest we drop that one (possibly adding its content to the end of NEWS) and rename the CHANGES-jumbo.git to CHANGES-jumbo.

Any better idea?

**Comment by magnumripper** [comment]
On a side note, I do think `.txt` extensions are good. If I were to choose, I'd put that extension to all files under .doc (that hasn't already got some, like .md of course).

**Comment by claudioandre-br** [comment]
Solar, recently (on a Windows PR) complained about this. IMO, it does not hurt.

**Comment by solardiz** [comment]
> There's an other file actually called CHANGES-jumbo, more resembling our new NEWS file. I suggest we drop that one (possibly adding its content to the end of NEWS)

Unfortunately, that old CHANGES-jumbo only goes up to 1.7.9-jumbo-7. We don't appear to have a similar list of changes for 1.8.0-jumbo-1. Maybe we need to get at least something from somewhere (my list posting announcing 1.8.0-jumbo-1?) so that we don't have a versions gap in NEWS.

> Solar, recently (on a Windows PR) complained about this. IMO, it does not hurt.

I complained about a post-build script always renaming our tree's files to .txt, which would alter the tree. I am willing to consider pre-renaming all files to .txt perhaps if/once we drop the core vs. jumbo separation, continuing with a jumbo-based tree for future one and only JtR.

**Comment by magnumripper** [comment]
> > There's an other file actually called CHANGES-jumbo, more resembling our new NEWS file. I suggest we drop that one (possibly adding its content to the end of NEWS)
> 
> Unfortunately, that old CHANGES-jumbo only goes up to 1.7.9-jumbo-7. We don't appear to have a similar list of changes for 1.8.0-jumbo-1. Maybe we need to get at least something from somewhere (my [list posting announcing 1.8.0-jumbo-1](https://www.openwall.com/lists/announce/2014/12/18/1)?) so that we don't have a versions gap in NEWS.

IMHO, NEWS doesn't have to include any history. Current version of this PR is better: Old stuff remains in CHANGES-jumbo and CREDITS-jumbo without (I think) any gaps. NEWS is all about 1.9.0-jumbo-1.
