### ISSUE TITLE
episerver_sha1 format errors in test suite

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1915]
On a 64bit Linux system (AVX and Non-OMP) and on with a 32bit NEON-ac OMP build on a Raspberry Pi 2 I get exactly the same errors:
```
form=episerver_sha1               guesses: 1476 -show=1476 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
form=episerver_sha1-utf8          guesses: 1403 -show=1403 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!]
form=episerver_sha256-utf8        guesses: 1437 -show=1437 0:00:00:00 DONE : Expected count(s) (1500)(1202)  [!!!FAILED1!!!]
```

The problem seems to have existed for a while now.

**Comment by jfoug** [comment]
https://github.com/magnumripper/jtrTestSuite/commit/5335741a6c5c6846f92c7cb1550fe2f71c34b14e

jtrts.dat problem (SIMD can only do 19 byte passwords). I had to also make a new counter script for utf8 encoding to validate that the right counts are being found.
