### ISSUE TITLE
Default GPU device should be the most powerful one

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1930]
We currently default to first GPU device (as opposed to eg. CPU devices) found. Failing that, we default to device 0. Both cases can supposedly be overridden by john.conf settings for Platform/Device under `[Options:OpenCL]` (I didn't test those for quite some time, not sure they even work as supposed). On a side note, that "Platform" notation in john.conf should be removed in favor of our newer "sequential device number".

But here's the main issue: Now that we have a rough speed index for each device, we should default to the one that's fastest. To complicate matters slightly, I think we should still default to GPU (or "accelerator") over CPU - so in case we have a weak GPU and a very fast CPU (perhaps simply due to lots of cores) we should still pick the [fastest] GPU.

A good example is "super" which now has a weak Juniper at device 0 as default while the Titan X at device 6 is significantly more powerful. Another example is some systems with Intel HD Graphics, which will be picked as default if it happens to be listed before a discrete GPU.

**Comment by magnumripper** [comment]
@claudioandre perhaps you'd like to have a look at this?

**Comment by claudioandre** [comment]
> On a side note, that "Platform" notation in john.conf should be removed in favor of our newer "sequential device number".

My vote is to remove the platform option entirely (it works but it lacks some power --dev has) but I suppose an ok from john-users is necessary.

**Comment by magnumripper** [comment]
Nah, we are benevolent dictators. Let's ditch it for Jumbo-2 (that is, now!).

**Comment by claudioandre** [comment]
>  I think we should still default to GPU (or "accelerator") over CPU - so in case we have a weak GPU and a very fast CPU (perhaps simply due to lots of cores) we should still pick the [fastest] GPU.

You did this (auto select GPU formats) in the past and had to revert. For now force the user to select whatever-opencl and pick a good/the best GPU is the best option.

**Comment by magnumripper** [comment]
Exactly. Pretty intuitive: `-form:wpapsk` will be CPU, `-form:wpapsk-opencl` will be GPU (if there is one) and you need to explicitly say `-dev=cpu` (or use numbers) to run OpenCL on CPU.

**Comment by magnumripper** [comment]
Fortunately, we've only listed --platform among "hidden options" for quite some time - and it even says "deprecated". So simply dropping it without any backward compatibility is no problem!

**Comment by magnumripper** [comment]
Fixed in #1933, thanks!
