### ISSUE TITLE
HANDLE_CLERROR evaluates 'cl_error' multiple times

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#1934]
```
/* Use this macro for OpenCL Error handling anywhere else */
#define HANDLE_CLERROR(cl_error, message)	  \
	do { \
		if (cl_error != CL_SUCCESS) { \
			fprintf(stderr, "OpenCL %s error in %s:%d - %s\n", \
			    get_error_name(cl_error), __FILE__, __LINE__, message); \
			error(); \
		} \
	} while (0)
```

Note that cl_error is evaluated once in the conditional, and once if it fails. For constructs such as this:
```
HANDLE_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], buffer_hash_ids, CL_TRUE, 0, sizeof(cl_uint), zero_buffer, 0, NULL, NULL), "failed in clEnqueueWriteBuffer buffer_hash_ids.");
```
in opencl_hash_check_128_plug.c, this is going to cause issues :)

Also affects BENCH_CLERROR.

Patch attached:
[patch.txt](https://github.com/magnumripper/JohnTheRipper/files/49415/patch.txt)

**Comment by magnumripper** [comment]
Ouch! Good catch, bad code! It'd only happen when failing anyway so I guess it mostly led to sometimes giving confusing messages.

Committed in 6a1f842 (next time I'd appreciate a PR), thanks!

**Comment by crioux** [comment]
Yes, I got a failing error and it was of type CL_SUCCESS, so you can see my confusion :)
