### ISSUE TITLE
cygwin compilation issue 

### ISSUE THREAD

**Issue by jun0s** [magnumripper/JohnTheRipper#1935]
Hi...
cp opencl/cryptsha512_kernel_DEFAULT.cl ../run/kernels
cp  ../run/kernels
cp: falta el fichero de destino después de «../run/kernels»
Pruebe 'cp --help' para más información.
Makefile:858: fallo en las instrucciones para el objetivo 'opencl/cryptsha512_kernel_GCN.cl'
make[1]: *** [opencl/cryptsha512_kernel_GCN.cl] Error 1
make[1]: se sale del directorio '/home/neo/johnbleeding/src'
Makefile:187: fallo en las instrucciones para el objetivo 'default'
make: *** [default] Error 2
thanks!

**Comment by magnumripper** [comment]
You need to re-run `./configure`

**Comment by jun0s** [comment]
sorry and thank u! :$
