### ISSUE TITLE
Travis is broken (again)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1936]
https://travis-ci.org/magnumripper/JohnTheRipper/jobs/95087961

Having problems with a lib (I think openCL).   Any ideas?

**Comment by magnumripper** [comment]
Strange. I just re-scheduled the job - sometimes in the past there have been intermittent failures.

**Comment by magnumripper** [comment]
That didn't help

**Comment by magnumripper** [comment]
Let's see if #1937 can work around it.

**Comment by magnumripper** [comment]
Yeah, that did the trick. Now if we fail installing fglrx, it'll still build (but we wont get OpenCL tested).
