### ISSUE TITLE
"Cannot distribute work among nodes!" in gpu mask code

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#1938]
If you set min-length to 2 and specify you're doing one of two nodes, it complains:

> john --mask=?a --format=lm-opencl --node=1/2 --min-length=2 --max-length=7 pwfile2.txt
> Device 0: Tahiti [AMD Radeon R9 200 / HD 7900 Series]
> Using default input encoding: UTF-8
> Using default target encoding: CP850
> Node number 1 of 2
> Insufficient work. Cannot distribute work among nodes!
> Loaded 21 password hashes with no different salts (LM-opencl [DES BS OpenCL])
> Remaining 10 password hashes with no different salts

If you set min-length to 3, however, it works fine.

(if you set min-length to 1, you get the other bug 'format internal ranges cannot be truncated!')

**Comment by magnumripper** [comment]
This is related to #1782, at least from a user perspective.

As a user, I'd like the ability to just `mpirun (...) ./john -min-len=0 -max-len=7 -mask:(...)` even if it would mean the shortest lengths would just run on one of the nodes.

**Comment by magnumripper** [comment]
I believe this is fixed now
