### ISSUE TITLE
double free in ssh2john

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1941]
Reported by [Hanno Böck](http://www.openwall.com/lists/john-dev/2015/12/08/1)

There is a double free error in ssh2john if you run it against a file
that contains two ssl certificate blocks.

Just take a random certificate, add it twice to a file:
```
cat test.crt test.crt > out.crt
```
and run
```
ssh2john out.crt
```
Seems there is a loop that is freeing all openssl objects at the end of
the loop and then reusing the same objects and freeing them for every
iteration of the loop.

**Comment by kholia** [comment]
I am thinking of removing ssh2john.c and ssh_fmt_plug.c. The code is simply terrible.

`ssh-ng` and `pem` formats are better for doing this stuff.

**Comment by magnumripper** [comment]
Is there any functionality that only the non-ng format can provide?

**Comment by kholia** [comment]
`ssh` can handle PEM files which use AES. Our new `pem` format can be extended to do that as well.

**Comment by magnumripper** [comment]
This is sort of fixed (deprecating the format) but not merged yet. Changing label accordingly.
