### ISSUE TITLE
Mask commands not doing what expected

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#1947]
Specifying a --max-len=8 fix it.

```
$ ../run/john -stdout --mask=?l --min-len=8
[...]
26p 0:00:00:00 100,00% (9) (2015-12-09 11:01) 288.8p/s q
```

**Comment by magnumripper** [comment]
We've got two options:

1. If -min-len=N is supplied, default to -max-len=N
2. If -min-len=N is supplied, default to -max-len=*format's max length*

Which is better? I think 2.

Oh BTW we do have this behavior:
```
$ ../run/john -stdout --mask=?l --max-len=8
Press 'q' or Ctrl-C to abort, almost any other key for status
aaaaaaaa
eaaaaaaa
iaaaaaaa
(...)
```
...so only supplying -max-len=N will imply -min-len=N. So I guess option 2 is more usable.

**Comment by claudioandre** [comment]
> ...so only supplying -max-len=N will imply -min-len=N. So I guess option 2 is more usable.

Make sense.

**Comment by magnumripper** [comment]
I'm leaning towards changing the latter instead. Like this:

* Only supplying -min-len=N will imply -max-len=*format's max length*
* Only supplying -max-len=N will imply -min-len=*format's min length* (usually 0)

I'll try it out and see if it "feels" right.
