### ISSUE TITLE
Numerous long runs end up with .rec file full of null bytes

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1949]
I have seen this several times.  A resume file that simply is nulls.   I have only seen this on cygwin64 (which is what I mostly use for long runs).  I have even seen a fork save, where 1 of the rec files was like this, and the other 3 were fine.

**Comment by magnumripper** [comment]
That's a horrible bug. I've never seen it though. Might be cygwin-specific, or triggered by some not so common circumstances?

Very hard to fix unless we can narrow it down or find a way to reproduce.

How many times have you seen it? Do you have any idea of when this started to happen? Recently, or since forever?

I take it you got "lots of null bytes" as opposed to a zero length file. Does it even look like it might be correct length? I think that points towards OS or (rather) cygwin bug.

**Comment by jfoug** [comment]
It is the correct length, but null bytes.

I have seen it about half a dozen times.  Just got it on a OMP=4 run, that was 9 days old.  It was a minlen=maxlen=7 inc:lowernum run.  I was able to build a rec file by piping data into a perl script, that was looking for the right candidate (about 2000 before the last password in my pot file), and once found, the perl script write a pause file, and would sleep a second after every line read.  A 'q' then a ^c was able to drop a working .rec file.

But yes, this bug sux.  The worst part was in the -fork where one of them failed.  I had no way to re-create that, so I am simply continuing with 3 out of the 4 items.

I really think this has something to do with the file locking.  I am pretty sure that cygwin is NOT solid there.  I should really try to write a small test case, in code outside of john, and see if I can re-create this type of problem.  But yes, this type bug really is HARD to fix, without having a way to replicate it.

It has happened to me before, but this is the 4th time in less than a month.  It may happen a lot more often, but I really do not restart all that often.

1 was due to shutting down the cygwin shell unexpectedly (by accident).
1 was due to ^C (by accident). This was the fork run
1 was due to a hard machine lock up (keyboard/mouse were locked hard).  This one just happened today, and was the 4-OMP run of inc:lowernum

Those are all that I remember fully, but there have been other 'times' that I have had null byte rec files.

**Comment by magnumripper** [comment]
I can't see how anything related to file locking would lead to sympthoms like this. Also, there's no race about rec files, only log and pot files.

**Comment by jfoug** [comment]
But it could be a kernel race, where something can not properly flush out the OS file handle to disk.

Again, I have no idea why this is failing. There is no where that we write all of this to a memory buffer, and then fwrite this buffer to the final file.  If we had that, I could 'see' that somehow we would memset the data before writing it.  But i am pretty sure this is fprintf type file writing, line by line.  Thus this type behavior would seem to be to be AFTER john closed the file.

**Comment by magnumripper** [comment]
I'm downgrading to "external issue", but thus doesn't mean it's less critical. I'm just pretty much certain this is a Cygwin problem.

I tried googling for Cygwin64 trashing files in various ways but came up with nada. Perhaps one should simply have a look at all open bugs - I didn't try that yet.

BTW what exact version of Cygwin are you running, and is there any newer?

**Comment by jfoug** [comment]
I have no idea how to tell a version.  I There is a 'setup-64.exe' that does installs/updates.  I think I am only a few weeks out of date.

I am adding this code to recovery, and doing a rebuild, and will see if I have any problems. AGAIN, since I can not replicate this, but it just happens, I have no idea if this make things better OR worse.

```C
#ifdef __CYGWIN__
#undef OS_FLOCK
#define
```

I will not check that code in, I simply will use that build for my runs and see how things work.

**Comment by jfoug** [comment]
I do agree, this is a cygwin problem.   It is very likely a cygwin bug, in dealing with how we are writing to this file within john.

**Comment by jfoug** [comment]
@magnumripper  can you explain why we are using file locking for the *.rec files ?

**Comment by frank-dittrich** [comment]
My guess is to prevent two processes restoring the same session...

**Comment by magnumripper** [comment]
Yeah, if we didn't you could accidentally start another session using the same (or default) session name, overwriting the first.

**Comment by jfoug** [comment]
Ok, keeping a 2nd process from grabbing and overwriting the .rec file certainly makes all the sense needed.  That also explains why it is kept open, so that we would not have to re-read and parse the file to make sure it was 'our' process that is using it.

But the way we are using it (opened in locking mode, and then keeping it open, re-writing it, and changing the file length), 'may' be what is causing the cygwin builds to write bad .rec files at some times.

I will keep an eye on some processes running with file locking off, and see if the problem does not happen.  Again, I think this may be some issue with Cygwin.  I do not remember seeing this, until I had updated computers to Win10, BUT I also had a failure on my Win7 development box at work.  But I also had not done too many resumes until recently (more service pack updates on Win10).  So this may have been an issue for a LONG time, just something I had not experienced.

**Comment by magnumripper** [comment]
You could also try forcing flock() instead of fcntl locks and see if it makes a difference.

**Comment by jfoug** [comment]
The worst part of this issue, is there is no way to 'know' that something is fixed.  We just keep this open, and I will watch.  IF things look good, I will start use different locking, OR possibly drop down and use Win32 API level locking, skipping the Cygwin wrapper code.  But I still am not sure that removing the locking has made any difference at all.

**Comment by jfoug** [comment]
I just got this email offlist.  It's not only me that is being hit. I do think it is the file locking causing the problems.

```
Hi,
sorry for bothering.
 
I know you are using cygwin too.
 
I get the following issue after compiling john bleeding jumbo (newest) under cygwin64 version 2.4.0:
 
Using default input encoding: UTF-8
Loaded 4 password hashes with no different salts (Raw-MD5 [MD5 128/128 AVX 4x3])
Node numbers 1-8 of 8 (fork)
Each node loaded 1/8 of wordfile to memory (about 3417 KB/node)
Crash recovery file is locked: Crash recovery file is locked: Crash recovery file is locked: Crash recovery file is locked: Crash recovery file is locked: Crash recovery file is locked: Crash recovery file is locked: john.5.recjohn.8.recjohn.2.recjohn.recjohn.7.recjohn.6.recjohn.4.rec
 
Can you repoduce this? Thanks for your help.
fatuma
```

**Comment by magnumripper** [comment]
That last scenario is likely OT for this issue, it looks like there are zombie children running. For example, start a session using -fork and then `kill -9` the mother process. Then re-run or resume the session. I'm pretty sure you will get that exact output.

**Comment by jfoug** [comment]
Is this a fix for this issue?  https://github.com/magnumripper/JohnTheRipper/commit/1f3462039e336e63944cf032ffb56c2bef1e4f5d

Btw, where did you find dox about this problem?

**Comment by magnumripper** [comment]
1f34620 is unrelated but needed for #1954 (I'm regression testing a commit for that one).

The zombie process problem is obvious and ultimately doesn't have a cure: If you kill the mother process brutally enough that it doesn't signal its children, the described scenario will and does happen. I've seen it.

**Comment by jfoug** [comment]
But I have had empty (full of NULL bytes) session files happen, several times.  It was not due to a zombie process issue.  I have changed the defines so that restore when built under cygwin does not lock files at all (non checked in code, just my local tree).  Since that change, I have had no issues.  HOWEVER, the issue was so intermittent (only happened twice of 1000's of hours of running), that I can NOT say that removing the locking fixed it, just that I have not seen it since that time.

**Comment by magnumripper** [comment]
I'm not questioning the OP, I'm just saying this offline mail you've got was zombies and had nothing to do with it.

**Comment by jfoug** [comment]
Just happened again to me today :(  I was sitting at desk when it happened.

3 forks running.  rec file 0 and 3 are full of null. rec file 2 is ok.   Unfortunately, I was running memdbg, so it was not a 'normal' jtr build (so I can not point fingers at a 'normal' run).  I just had a 5s power flicker, but long enough to drop the machine (had a GPU and this 3-fork CPU job running).

Files inc-6-all-002.rec and inc-6-all-002.3.rec are both pure null bytes.  inc-6-all-002.2.rec is just fine.

Here are timestamps:

```
$ stat inc-6-all*.rec
  File: ‘inc-6-all-002.2.rec’
  Size: 286             Blocks: 1          IO Block: 65536  regular file
Device: 16883e01h/378027521d    Inode: 3940649674097160  Links: 1
Access: (0640/-rw-r-----)  Uid: ( 1000/ Haswell)   Gid: (  513/    None)
Access: 2016-03-13 14:02:19.302965000 -0500
Modify: 2016-03-25 12:16:59.578145800 -0500
Change: 2016-03-25 12:16:59.578145800 -0500
 Birth: 2016-03-13 14:02:19.302965000 -0500
  File: ‘inc-6-all-002.3.rec’
  Size: 284             Blocks: 1          IO Block: 65536  regular file
Device: 16883e01h/378027521d    Inode: 4785074604229130  Links: 1
Access: (0640/-rw-r-----)  Uid: ( 1000/ Haswell)   Gid: (  513/    None)
Access: 2016-03-13 14:02:21.241649100 -0500
Modify: 2016-03-25 12:17:01.498107200 -0500
Change: 2016-03-25 12:17:01.498107200 -0500
 Birth: 2016-03-13 14:02:21.241649100 -0500
  File: ‘inc-6-all-002.rec’
  Size: 286             Blocks: 1          IO Block: 65536  regular file
Device: 16883e01h/378027521d    Inode: 3940649674097161  Links: 1
Access: (0640/-rw-r-----)  Uid: ( 1000/ Haswell)   Gid: (  513/    None)
Access: 2016-03-13 14:02:21.212751700 -0500
Modify: 2016-03-25 12:17:02.752736900 -0500
Change: 2016-03-25 12:17:02.752736900 -0500
 Birth: 2016-03-13 14:02:21.212751700 -0500
```

This bug really pisses me off, but I really do not know wtf is the problem :(

**Comment by jfoug** [comment]
@crioux pointed out a problem for MSCV in recovery.c, where at the end we do not ftruncate the file properly for VC.  However, in looking at the function I see a __CYGWIN__ thing (and VC thing) right at the start, that appear to try to trucate file to 0 bytes when starting.

I wonder if THIS could be the cause of the problem seen here!!!  I really see no reason at all for a ftruncate to 0 bytes at beginning anyway, if the ftruncate will be called at the end of writing??  just done not seem needed, and may be problem causing!

```C
void rec_save(void)
{
	int save_format;
#ifdef HAVE_MPI
	int fake_fork;
#endif
	int add_argc = 0, add_enc = 1, add_2nd_enc = 1;
	int add_mkv_stats = (options.mkv_stats ? 1 : 0);
	long size;
	char **opt;

	log_flush();

	if (!rec_file) return;

	if (fseek(rec_file, 0, SEEK_SET)) pexit("fseek");
#ifdef _MSC_VER
	if (_write(fileno(rec_file), "", 0)) pexit("ftruncate");
#elif __CYGWIN__
	if (ftruncate(rec_fd, 0)) pexit("ftruncate");
#endif

	save_format = !options.format && rec_db->loaded;

#ifdef HAVE_MPI
	fake_fork = (mpi_p > 1);
#endif
	opt = rec_argv;
	while (*++opt) {
#ifdef HAVE_MPI
		if (!strncmp(*opt, "--fork", 6))
			fake_fork = 0;
		else
#endif
		if (!strncmp(*opt, "--encoding", 10) ||
			!strncmp(*opt, "--input-encoding", 16))
			add_enc = 0;
		else if (!strncmp(*opt, "--internal-codepage", 19) ||
		         !strncmp(*opt, "--internal-encoding", 19) ||
		         !strncmp(*opt, "--target-encoding", 17))
			add_2nd_enc = 0;
		else if (!strncmp(*opt, "--mkv-stats", 11))
			add_mkv_stats = 0;
	}

	if (add_2nd_enc && (options.flags & FLG_STDOUT) &&
	    (options.input_enc != UTF_8 || options.target_enc != UTF_8))
		add_2nd_enc = 0;

	add_argc = add_enc + add_2nd_enc + add_mkv_stats;
#ifdef HAVE_MPI
	add_argc += fake_fork;
#endif
	fprintf(rec_file, RECOVERY_V "\n%d\n",
		rec_argc + (save_format ? 1 : 0) + add_argc);

	opt = rec_argv;
	while (*++opt)
	{
		/* Add defaults as if they were actually on **argv */
		if (options.wordlist &&
		    !(strcmp(*opt, "--wordlist") && strcmp(*opt, "--loopback")))
			fprintf(rec_file, "%s=%s\n", *opt, options.wordlist);
		else if (!strcmp(*opt, "--rules"))
			fprintf(rec_file, "%s=%s\n", *opt,
			        options.activewordlistrules);
		else if (!strcmp(*opt, "--single"))
			fprintf(rec_file, "%s=%s\n", *opt,
			        options.activesinglerules);
		else if (!strcmp(*opt, "--incremental"))
			fprintf(rec_file, "%s=%s\n", *opt,
			        options.charset);
		else if (!strcmp(*opt, "--markov"))
			fprintf(rec_file, "%s=%s\n", *opt,
			        options.mkv_param);
		else
			fprintf(rec_file, "%s\n", *opt);
	}

	if (save_format)
		fprintf(rec_file, "--format=%s\n",
		    rec_db->format->params.label);

	if (add_enc)
		fprintf(rec_file, "--input-encoding=%s\n",
		        cp_id2name(options.input_enc));

	if (add_2nd_enc && options.input_enc == UTF_8 &&
	    options.target_enc == UTF_8)
		fprintf(rec_file, "--internal-codepage=%s\n",
		        cp_id2name(options.internal_cp));
	else if (add_2nd_enc)
		fprintf(rec_file, "--target-encoding=%s\n",
		        cp_id2name(options.target_enc));

	if (add_mkv_stats)
		fprintf(rec_file, "--mkv-stats=%s\n", options.mkv_stats);
#ifdef HAVE_MPI
	if (fake_fork)
		fprintf(rec_file, "--fork=%d\n", mpi_p);
#endif

	fprintf(rec_file, "%u\n%u\n%x\n%x\n%x\n%x\n%x\n%x\n%x\n"
	    "%d\n%d\n%d\n%x\n",
	    status_get_time() + 1,
	    status.guess_count,
	    status.combs.lo,
	    status.combs.hi,
	    status.combs_ehi,
	    status.crypts.lo,
	    status.crypts.hi,
	    status.cands.lo,
	    status.cands.hi,
	    status.compat,
	    status.pass,
	    status_get_progress ? (int)status_get_progress() : -1,
	    rec_check);

	if (rec_save_mode) rec_save_mode(rec_file);
	/* these are 'appended' resume blocks */
	save_salt_state();
	if (rec_save_mode2) rec_save_mode2(rec_file);
	if (rec_save_mode3) rec_save_mode3(rec_file);
	if (options.flags & FLG_MASK_STACKED)
		mask_save_state(rec_file);

	if (ferror(rec_file)) pexit("fprintf");

	if ((size = ftell(rec_file)) < 0) pexit("ftell");
	if (fflush(rec_file)) pexit("fflush");
#ifndef _MSC_VER
	if (ftruncate(rec_fd, size)) pexit("ftruncate");
#endif
#if HAVE_WINDOWS_H==0
	if (!options.fork && fsync(rec_fd))
		pexit("fsync");
#endif
}

void rec_init_hybrid(void (*save_mode)(FILE *file)) {
	if (!rec_save_mode2)
		rec_save_mode2 = save_mode;
	else if (!rec_save_mode3)
		rec_save_mode3 = save_mode;
}
```

**Comment by magnumripper** [comment]
@jfoug if you haven't seen the problem since 8189b34 I guess we can stick a fork in this one.
