### ISSUE TITLE
New option: --queue

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1954]
Basic idea, usage:

Session 1:
```
$ ./john -session:thisorthat (...)
Loaded 123 hashes (...)
(...)
```

Session 2 (note that session 1 is still *running*):
```
$ ./john -session:thisorthat -queue (...)
Waiting...
```

Basic idea, how to implement:
* If the session file doesn't exist, this is a no-op option - we just start the job as usual.
* If the session file does exist, take a blocking write lock on it. Wait forever for the lock to disappear (the "Waiting..." message above is printed while waiting).
* Once we got the lock, verify that the session file has been deleted. If it has, it's our turn and we start the job.

* If the file was NOT deleted, the first job must have been aborted. Bail out saying "Queing failed" or something (this behavior can be enhanced later in various ways).

If this scheme works, this is a super trivial KISS[tm] way to add ability to queue jobs that need to be run in sequence.

**Comment by magnumripper** [comment]
Caveat: The `-queue` option must not be stored in the session file.

**Comment by jfoug** [comment]
I was going to comment about breaking out of the first process, but you handled that.  I do like this, and yes, the caveat is valid.

One other thing.  Yes, you mention KISS.  but in the current form, you can only have a running process and 1 item in queue (if sequential processing is wanted.).

But a more simple KISS method would be:

#!/bin/sh
.....

:)

**Comment by magnumripper** [comment]
I often start things like this:
```
$ ./john -session:thisorthat (...) && ./john -session:thisorthat (...)
```
This is akin to your shell script (btw I think you need to use `#!/bin/sh -e`) and these are the simplest ways to achieve this of course. If a session is aborted or fails in any way, the rest of the line is aborted.

However, the `-queue` option can be used **after** the first session is already running. You start a job and only then realize another job you want to start after the first one is done. To accomplish this today, you need to abort session 1 and then do this oneliner:
```
$ ./john -res:thisorthat && ./john -session:thisorthat (...)
```

**Comment by jfoug** [comment]
Do not take my KISS mention of a shell script as a poo poo against this function. I do see that it can certainly be beneficial.  I also simply listed that you can only queue 1 item at a time, for a running session, unless you do not care about order.

**Comment by frank-dittrich** [comment]
One more caveat:
Decide how to handle LogFileProtect = Named | Always for --queue, and document that behavior.

**Comment by magnumripper** [comment]
@jfoug but it's a valid concern. I actually had the idea you could queue more than one job but that won't work with the proposed design. I will ponder other options. If we can't make this **really** usable, we should just ditch this idea (after all it will add possible bugs!).

**Comment by frank-dittrich** [comment]
If you are willing to change the .rec file format, you could allow --queue for a session which is not currently running, by just appending the information for the next task(s) to the existing .rec file.
When you restore and finish the first task, you just have to remove the information related to the first task, then proceed with the next task.
But then you need to address issues related to --fork=n and possibly varying n for different wueued tasks...

**Comment by jfoug** [comment]
I am pretty sure we 'could' queue as many as we wanted, and they should be released 1 at a time, BUT there is no assurance of order.  It would be classic uncontrolled multi-processing problem (i.e. dining philosophers problem).  1 of them should get released, but there is no assurance of any order, and no assurance that some process would not starve and never get to work.

**Comment by jfoug** [comment]
Ok, how about this:

1. a new file:  called session_name.queue  (has to be hand created).
2. when a run completes fully, that file is looked for (same location as the *.rec file just removed).
3. That search is done right at the end of main().  If found, then we 'fixup' the file (removing the top line, and rewrite the file, or delete it if there was only 1 entry).
4. john then spawn a new john session using that command line

This is 'still' pretty KISS, and it allows ordered running, and only continuing upon full completion of the current run (we can talk about that also).

What do others 'think' about this. There would be NO additional command line args required. This would be driven by instruction file only.

**Comment by magnumripper** [comment]
It's too complicated to use. I have other vague ideas, will experiment a little.

**Comment by jfoug** [comment]
Why could we not have john itself add lines the queue file (if the --queue switch was used) ???

Thus it would be 100% user interface the same as you suggested from the start. But then we would not have a process doing a busy wait to run.  It would simply add a line to the queue file. Then when the first process completes, that process will launch the next process while exiting.

**Comment by magnumripper** [comment]
Maybe. But this will be a good chunk of code, in core, with file locking and whatnot.

Another option would be a standalone thing, a wrapper for JtR, instead.

**Comment by jfoug** [comment]
Are you thinking of adding this to core???  (john proper).

I would see only a couple of lines added.  One right after loading command params. The other within main() right before exit.

Then the rest would be 'hidden' in a new source file (the real guts).  This really should not be 'that' big of an addition.

**Comment by magnumripper** [comment]
No I meant core code in Jumbo. And regardless of where we place the code, it will be a whole new world of possible bugs. There must be an easier way to do this!

**Comment by magnumripper** [comment]
Think fork, or MPI...

**Comment by magnumripper** [comment]
Like this scenario: First session is a single thread CPU format doing mask mode for lengths up to 4. Second session is an MPI job on several remote hosts with OpenCL, starting at length 5. Things like that was what I originally had in mind. And my original idea would work in that scenario, except it wouldn't be able to queue a third job.

**Comment by magnumripper** [comment]
Here's an alternative that might work (needs more thought)
```
--queue[=session]  take a blocking lock on session.rec, once you get it ensure
                   it has been deleted. Then start. "session" must be different
                   from your own.
```
It would work something like this
```
$ john -ses:1 (...)

$ john -ses:2 --queue=1 (...)

$ john -ses:3 --queue=2 (...)
```
* Session 1 starts and runs
* Session 2 will create its session file and lock it, but it will pause waiting for session 1 before actually starting.
* Session 3 will create its session file and lock it, but it will pause waiting for session 2 before actually starting.

**Comment by jfoug** [comment]
That logic appears solid.  However, what happens if session1 is killed (i.e. session 1.rec is not removed) ?

**Comment by frank-dittrich** [comment]
Or, what happens if session 1 still runs, but session 2 gets killed?

**Comment by magnumripper** [comment]
> what happens if session1 is killed (i.e. session 1.rec is not removed) ?

We'll still have code for ensuring the preceding session file was deleted. So session 2 get a lock but then bail out with an error message because 1.rec was not deleted. After that, session 3 will bail for the same reason.

> what happens if session 1 still runs, but session 2 gets killed?

Same code: Session 3 will get the lock of 2.rec but notices it wasn't deleted, so it bails out.

**Comment by magnumripper** [comment]
1f34620 is a first step. Unfortunately it looks like this type of queueing can't be made safe on Windows since that poor OS can't delete a locked file (if it has locks at all).

**Comment by magnumripper** [comment]
I'm regression testing a working commit implementing this. It will be completely disabled on Windows. It *does* support queueing after a session with same name as "our" session. Also, it does filter out the "--queue-after" from the session file.

**Comment by frank-dittrich** [comment]
Should john warn on Windows if it processes such a session file?

**Comment by magnumripper** [comment]
There will be no such session files. The option is used and then discarded. When resuming, there is no queueing.

However, I'm considering the alternative to support adding queueing on resume: `john -resume:yyy -queue=zzz`. This is a core change (and may be tricky).

**Comment by frank-dittrich** [comment]
Yes, you can't produce such session files on Windows. But what if you copy them from a Linux machine and try to restore on Windows?

**Comment by magnumripper** [comment]
Read it again. The option never ends up in the session file even on Linux. It happens for first run, not for resume (unless you give the option again when resuming).

**Comment by magnumripper** [comment]
Some testing indicates this works very poorly on NFS file systems. I'm currently considering ditching the whole idea or going for a completely different solution, possibly with a standalone wrapper.

**Comment by magnumripper** [comment]
Ditching this. One could implement a stand-alone tool but that'd be a new issue.

**Comment by magnumripper** [comment]
Here's a KISS solution

filewait.c
```c
/*
 * Usage: "filewait <file> && do_next"
 *
 * Main purpose is JtR session files. Eg:
 * $ ./filewait sessionA.rec && ./john -ses:sessionB (...)
 *
 * Check the file once every three seconds. Once the file no longer exists,
 * EXIT_SUCCESS.
 *
 * This file is Copyright (c) 2017 magnum
 * and is hereby released to the general public under the following terms:
 * Redistribution and use in source and binary forms, with or without
 * modifications, are permitted.
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

void usage(char *me)
{
	printf("Usage: %s <file>\n\n"
	       "If <file> does not exist, exit SUCCESS.\n"
	       "If it does, wait for its deletion. Once it's unlinked, exit SUCCESS.\n\n"
	       "Example use:\n"
	       "%s john.rec && ./john -ses:next_session (...)\n\n", me, me);
}

int main(int argc, char **argv)
{
	char *filename;

	if (argc != 2) {
		usage(argv[0]);
		return EXIT_FAILURE;
	}

	filename = argv[1];

	fprintf(stderr, "Waiting for %s... ", filename);

	if (access(filename, F_OK) == -1) {
		fprintf(stderr, "Done!\n");
		return EXIT_SUCCESS;
	}

	do {
		if (access(filename, F_OK) == -1)
			break;
		else
			sleep(3);
	} while (1);

	fprintf(stderr, "Done!\n");

	return EXIT_SUCCESS;
}
```

`gcc -O2 -Wpedantic -o /usr/local/bin/filewait filewait.c`
