### ISSUE TITLE
Can we drop the --fix-state-delay option for wordlist mode?

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1955]
I believe this option is obsolete now that almost all formats have a max keys per crypt much larger than 1.

@jfoug you added this many years ago, right? Do you ever use it nowadays?

Note: If we are to obsolete it, I will do that - implementing some planned fixes for allowing (ignoring) obsoleted options while a) warning about them, and b) not storing them to the session file arguments.

**Comment by jfoug** [comment]
I believe this is still an issue.  I will check and post back. (no time to check right now).

**Comment by magnumripper** [comment]
Actually some code were "missing" making us do the fseek() even when not needed (memory buffered). After 68de7cd I see no speedup from using --fix-state-delay=1000 (actually I see a regression from it!).

**Comment by jfoug** [comment]
--fix-state-delay was ONLY designed for OS's which have shitty file io, for things like seeks  (anything on top of Win32 systems).

**Comment by magnumripper** [comment]
Oh, I meant ftell(). Anyway I actually saw a gain on OSX before 68de7cd, but not after it. I thought ftell() would be a cheap function.

**Comment by jfoug** [comment]
> I thought ftell() would be a cheap function.

Depends on OS, and possibly on size of file.

**Comment by magnumripper** [comment]
The OS already knows the position. It wouldn't need to touch the file at all. fseek is a different story of course, but ftell should just be a lookup in the file struct, on any OS.

**Comment by jfoug** [comment]
Ok, here IS a demo.  Done with cygwin64.  My WPA-LIST-all.txt is about 3.4gb.  Input file is one line (0123456....01, so that it 'matches' 32 byte hex for NT format).

```
$ ../run/john -w=/c/projects/phpbb/dictionaries/BIG-WPA-LIST-all.txt  -rules -form=nt in
Using default input encoding: UTF-8
Loaded 1 password hash (NT [MD4 128/128 AVX 4x3])
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:19 0.32% (ETA: 12:55:53) 0g/s 2625Kp/s 2625Kc/s 2625KC/s trumpetpebbleses..trumpetpedro7
0g 0:00:00:41 1.06% (ETA: 12:21:29) 0g/s 4527Kp/s 4527Kc/s 4527KC/s 5fillipped..5fillllif
0g 0:00:00:59 1.07% (ETA: 12:48:22) 0g/s 3214Kp/s 3214Kc/s 3214KC/s 5domainame..5domainbytesbsw
0g 0:00:01:19 1.41% (ETA: 12:49:49) 0g/s 3175Kp/s 3175Kc/s 3175KC/s 6sevitnat..6sevitnevni
0g 0:00:01:41 1.55% (ETA: 13:05:38) 0g/s 2675Kp/s 2675Kc/s 2675KC/s 8bogsprogs..8bogstalker
0g 0:00:01:56 1.75% (ETA: 13:07:24) 0g/s 2599Kp/s 2599Kc/s 2599KC/s Aanstipts6..Aanstoke4
Session aborted

$ ../run/john -w=/c/projects/phpbb/dictionaries/BIG-WPA-LIST-all.txt  -rules -form=nt in -fix-state-delay=50
Using default input encoding: UTF-8
Loaded 1 password hash (NT [MD4 128/128 AVX 4x3])
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:17 1.13% (ETA: 11:44:23) 0g/s 11694Kp/s 11694Kc/s 11694KC/s 8etsabure..8etsacbsw
0g 0:00:00:48 2.80% (ETA: 11:47:50) 0g/s 7204Kp/s 7204Kc/s 7204KC/s 5h0r73n3d..5h0re81rd
0g 0:00:01:01 3.58% (ETA: 11:47:42) 0g/s 6425Kp/s 6425Kc/s 6425KC/s Rinnastuksia3..Rinnastuksina0
0g 0:00:01:04 3.70% (ETA: 11:48:06) 0g/s 6384Kp/s 6384Kc/s 6384KC/s Spoogers..Spooges9
Session aborted
```

**Comment by jfoug** [comment]
There seems to be little or no difference on Linux (VM).  It was just a touch slower using -fix-state=50, but there were times where it was faster and times slower, but all in all, I would say no change.  NOTE, I did copy over a 1GB file to the VM's virtual disk. When I was trying to read from the physical hd (using virtual box's vboxsf file system.    That was so variable, that timings are NOT possible.

But as for the question, this switch DOES improve win32 speeds significantly, especially for larger files doing seeking (i.e. rules, etc).
