### ISSUE TITLE
Option --fuzz-dump should remove the pwfile.<format> once the format specific test completed without errors.

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1969]
Otherwise you'll end up with gigabytes of pwfile.* files until your file system is full.
Most likely, those dumped files will only be needed to reproduce a problem discovered by --fuzz-dump.

May be it makes sense to keep that pwfile.<format> if the test was limited to a single format using the --format option, even if that test didn't fail. I am not sure about this. It could be useful if you want to examine what kind of fuzzing is implemented or if you want to use that file to fuzz other format methods ... in a real cracking run.

**Comment by jfoug** [comment]
Should the fuzz_status/format  files also be removed after a successful run of -fuzz  ?

**Comment by jfoug** [comment]
6f97949

**Comment by jfoug** [comment]
I think this change is wrong (looking back at the code).  When -fuzz-dump is used, there are no tests done.  I think that -fuzz-dump is used to get a file of data to playback, once you have an idea of 'where' the fuzzing crashed.   If so, this modification needs to be rolled back.

I have never used fuzzing, so I am not sure exactly what the behavior is supposed to be.  But looking back, I think you fuzz until a crash.  Then use the status file to figure out 'about' where you were at wen things crashed, and then -fuzz-dump out a file and use that to find the actual 'bad' line.  But if that is the case, then the logic I added which @frank-dittrich asked for is very wrong.

**Comment by frank-dittrich** [comment]
@jfoug I think you are right.
Would it be a better idea to require --format= option when using --fuzz-dump?
Or just revert https://github.com/magnumripper/JohnTheRipper/commit/6f97949bb5ae1b278608adef31bcc79dcd9f97ed and keep the old logic?

**Comment by magnumripper** [comment]
I'm considering dropping all the HAVE_FUZZ code from Jumbo. As far as I can see it's just a shitload of unmaintained and unused code. Or do you actually use it a lot? How much better is this (if at all) compared to external scripts and stuff?

**Comment by jfoug** [comment]
The change has been rolled back.  4198692
