### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1972]
The list of documentation files in the end is not complete for current Jumbo

**Comment by seekaddo** [comment]
@magnumripper I have been looking into this. I want to finish it so that we can close this fast. I have one question though. Should every the list contain every doc file with a little description?

**Comment by solardiz** [comment]
FWIW, I provided some feedback on #3003 at the time, and my last comment there is: "As far as I can tell, my feedback on this PR has been ignored so far. @seekaddo was going to open a new PR to address it, but never did. :-("

So this issue still needs work. Please review the comments on #3003 before working in it.

**Comment by solardiz** [comment]
I think we've cleaned up README.md enough for 1.9.0-jumbo-1, so I'll close this issue.
