### ISSUE TITLE
Add TSan (threadsanitizer) support

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1981]
see https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual and https://github.com/magnumripper/JohnTheRipper/issues/1980#issuecomment-169175278

**Comment by frank-dittrich** [comment]
Most likely, --enable-tsan will not work together with --enable-asan (not sure about --enable-ubsan).

**Comment by magnumripper** [comment]
I'm not sure we should bloat configure with this (or even the existing ASan/UbSan). You can just add whatever special things you want to CFLAGS when running configure.

**Comment by magnumripper** [comment]
...but feel free to add it if you really want it.

**Comment by kholia** [comment]
No further action is required here. This bug is just collecting dust now, closing!
