### ISSUE TITLE
mask.c : stretch_mask adds too many characters

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#1983]
If you set (for example)
--mask=?a --max-length=5
the output of stretch_mask is ?a?a?a?a?a?a , which is one character too long, because it is appending 'options.req_maxlength' characters to the end of the mask regardless of the the length of the input mask.

Don't know if this screws anything up later in the program but it doesn't seem right either.

**Comment by magnumripper** [comment]
This might actually worsen the problem where GPU-side mask picks stuff that later get truncated. I'll have a look at it.
