### ISSUE TITLE
mask_int_cand_target is arbitrarily set

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#1984]
in opencl_lm_b_plug.c (and other places) we see this:

	mask_int_cand_target = opencl_speed_index(gpu_id) / 300;

On my gpu, this results in mask mode running at 1.2Gc/s for a ?a?a?a?a?a?a mask. and 7Mc/s for a ?A?A?A?A?A?A mask. This is because it caps to only doing like 1 character or something on the gpu because the character set is larger and mask_calc_combination cuts it down.

If I change 300 to 200, i get 1.3Gc/s for the ?a?a?a?a?a?a mask and 540Mc/s for the ?A?A?A?A?A?A mask.

1. I don't get how this number was chosen and why it isn't something that autotune takes care of.
2. I don't get why there's any difference at all in c/s for different masks of the same length.

Thoughts?

**Comment by claudioandre** [comment]
> I don't get why there's any difference at all in c/s for different masks of the same length.

@magnumripper: Ok, I can see why the length of the mask means (almost) nothing for these c/s differences, but is it possible to avoid such a huge difference? Other tools suffer as JtR? Is that hard to send the same number of candidates despite of the mask?

E.g. think about a mask like this ?a?a (markers:  ##) (two positions, handled as a#, b#, c#, d#, ...). A lot of kernel calls - the multiplier is 95. Could it be broke as (multiplier would be 43*95):
* [a-z]#     -> And then 
* [A-|]#

*********

Just thinking loud, not a real RFC. Anyway, Is it possible to make speed uniform for different masks by hand. But it is not intuitive. 
```
GWS=32768 _GPU_MASK_CAND=50000 ../run/john --format=raw-sha256-opencl --test --mask=?A?A?A?A?A?A -dev=2
GWS=32768 _GPU_MASK_CAND=18000 ../run/john --format=raw-sha256-opencl --test --mask=?l?l?l?l?l?l -dev=2
GWS=65536 _GPU_MASK_CAND=10000 ../run/john --format=raw-sha256-opencl --test --mask=?a?a?a?a?a?a -dev=2
```

**Comment by magnumripper** [comment]
These things are still somewhat early code, we're waiting for @Sayantan2048 to get up to speed again. The "speed index" is a very rough figure but is much better than the fixed multiplier that was used before it.

**Comment by magnumripper** [comment]
I'm closing this. The biggest problem by far here is that GPU-side mask mode currently can't use "parts of" a placeholder. So given ?a?a?a?a the "multiplier" has to be either 95 or 95*95 (roughly 10,000) whereas the optimum may be somewhere inbetween. This is covered by #2022.
