### ISSUE TITLE
dynamic expressions with constants containing NULL bytes

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1985]
Apparently, dynamic expressions with constants containing NULL bytes don't work.

An example with a constant not containing NULL bytes, working:
```
$ ./john --test --format=dynamic='md5($c1.$p),c1=test_\x3a\x3a_test'
Benchmarking: dynamic=md5($c1.$p) [128/128 AVX 4x3]... DONE
Raw:	8057K c/s real, 8057K c/s virtual

```

A similar example, but with a constant containing a NULL byte:
```
 $ ./john --test --format=dynamic='md5($c1.$p),c1=test_\x00\x3a_test'
Benchmarking: dynamic=md5($c1.$p) [128/128 AVX 4x3]... FAILED (cmp_all(1))

```

The documentation doesn't mention that you can't use NULL bytes.
Fixing it might not be trivial, since you can't just treat that constant as a string and use string functions.

**Comment by jfoug** [comment]
```
[List.Generic:dynamic_3000]
Expression=md5($c1.$p)
CONST1=abc\x00\xff
Func=DynamicFunc__clean_input
Func=DynamicFunc__append_input1_from_CONST1
Func=DynamicFunc__append_keys
Func=DynamicFunc__crypt_md5
Test=$dynamic_3000$b4f4a325fecba00057a8bbeaca6e07fd:password
```

Works for me.  pass_gen.pl does not create the proper format string, however.

**Comment by jfoug** [comment]
ah.  dyna compiler.  Let me look at that one.  But since code came from pass_gen.pl, it is likely that the bug from there is why it is failing.

**Comment by jfoug** [comment]
```
$ ../run/john --test --format=dynamic='md5($c1.$p),c1=test_\x00\x3a_test'
Benchmarking: dynamic=md5($c1.$p) [128/128 AVX 4x3]... (8xOMP) DONE
Raw:    13565K c/s real, 5313K c/s virtual
```
