### ISSUE TITLE
Build depends on host architecture even if using VM

### ISSUE THREAD

**Issue by Fist0urs** [magnumripper/JohnTheRipper#1986]
configure script relies on host architecture when building john in a virtual machine. The script says: 

\# NOTE, later, we will probably do this by parsing the host or target to figure
\# out the system, then have a switch statement, based upon the system, calling
\# the proper JTR_cputype_SPECIAL_LOGIC

Meanwhile it is done, you could add  something like "try using --disable-native-march --disable-native-tests" in error message

**Comment by magnumripper** [comment]
In what error message?

**Comment by magnumripper** [comment]
I can't see how it would see anything from the host arch when running in a VM. Can you be more specific?

**Comment by Fist0urs** [comment]
Running simple configure && make clean && make, here is what I get:

    ./john --list=build-info 
    Sorry, SSE4.1 is required for this build

Also:

    cat /proc/cpuinfo | grep "flags"
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm

**Comment by magnumripper** [comment]
What type of VM is this? My guess is you are just seeing bugs/limitations in the VM. IIRC @jfoug saw things like that too.

**Comment by Fist0urs** [comment]
It's an Ubuntu 12.04 LTS running in VirtualBox, I'll take a closer look at what exactly happens

**Comment by magnumripper** [comment]
During configure, this program is compiled with `-O0 -msse4.1`:
```c
#include <smmintrin.h>
#include <stdio.h>

extern void exit(int);

int main()
{
    __m128d t;
    *((long long*)&t) = 1;
    t = _mm_round_pd(t,1);
    if ((*(long long*)&t) == 88)
        printf(".");
    exit(0);
}
```
If compilation doesn't fail, the program is run. If this doesn't produce a segfault, configure believes (on good grounds) you have SSE4.1.

**Comment by Fist0urs** [comment]
Well this compiles with no segfault and *(long long*)&t values 0

**Comment by frank-dittrich** [comment]
On my system (local)
```
$ gcc -dM -E -x c /dev/null | grep SSE
#define __SSE2_MATH__ 1
#define __SSE_MATH__ 1
#define __SSE2__ 1
#define __SSE__ 1
[fd@f22 ~]$ gcc -march=native -dM -E -x c /dev/null | grep SSE
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE2_MATH__ 1
#define __SSE_MATH__ 1
#define __SSE2__ 1
#define __SSSE3__ 1
#define __SSE__ 1
#define __SSE3__ 1
```

So, it should be possible to check for the drfinition of `__SSE4_1__ 1` and exit with an error code if not defined, no?

**Comment by frank-dittrich** [comment]
On he same system:
```
$ gcc -march=native -dM -E -x c /dev/null | grep AVX
#define __AVX__ 1
$ gcc -mavx -dM -E -x c /dev/null | grep AVX
#define __AVX__ 1
gcc -mavx2 -dM -E -x c /dev/null | grep AVX
#define __AVX__ 1
#define __AVX2__ 1
```

So may be just enforcing -msse4.1 isn't right?
OTOH, configure gets the AVX / AVX2 setting right on my system:
```
$ ./configure |grep -i avx
checking for AVX... yes
checking for AVX2... no
Target CPU ................................. x86_64 AVX, 64-bit LE
```

Could it be that `_mm_round_pd()` is somehow emulated on that non-SSE4.1 system?

**Comment by frank-dittrich** [comment]
@Fist0urs Another idea: do you get a working binary with either
`./configure "CC=gcc -msse4.1"` or `./configure CFLAGS_EXTRA=-msse4.1`?

**Comment by Fist0urs** [comment]
Here is the output on my VM:

    $ gcc -dM -E -x c /dev/null |grep SSE
    #define __SSE2_MATH__ 1
    #define __SSE_MATH__ 1
    #define __SSE2__ 1
    #define __SSE__ 1
    
    $ gcc -march=native -dM -E -x c /dev/null |grep SSE
    #define __SSE2_MATH__ 1
    #define __SSE_MATH__ 1
    #define __SSE2__ 1
    #define __SSSE3__ 1
    #define __SSE__ 1
    #define __SSE3__ 1


> @Fist0urs Another idea: do you get a working binary with either
> ./configure "CC=gcc -msse4.1" or ./configure CFLAGS_EXTRA=-msse4.1?

No this does not work either (well, configure detects SSE4.1 is available on my system, so enforcing these parameters leads to the same result)

I also have a VM running Ubuntu on VirtualBox on another computer and I do not have this problem. I'll take a look at this one tomorow.

**Comment by magnumripper** [comment]
> So, it should be possible to check for the definition of __SSE4_1__ and exit with an error code if not defined, no?

No, we do these tests for compilers that lack -march=native!

**Comment by magnumripper** [comment]
> Could it be that _mm_round_pd() is somehow emulated on that non-SSE4.1 system?

I'm pretty sure it's a shortcoming of VirtualBox. I'm not sure we care about it, but if someone finds a viable workaround, that's fine to add of course.

**Comment by jfoug** [comment]
The problem is VirtualBox.   They added > SSE3 in vb 5, but then reverted it in an update.  I am still running the older version 5.0.0 r101573 and things work but the new version 5.0.10 removed access to these new SIMD enhancements.

If you read the version change manifest, you will see that they added higher SIMD support in 5, but then in the update 5.0.10 removed it.  If you are running that version, then you will have to wait for Oracle to add support again.  There is nothing that can be done in the configure script, OR in the build to make it work.  If you build a SSE4.1, it will core.

**Comment by Fist0urs** [comment]
That's could effectively be VirtualBox, by version 5.0.10 many things got screwed up (and my VM running Ubuntu where things work runs through version < 5.0.10).

I think we should wait&see if Oracle decides to fix things up...

**Comment by Fist0urs** [comment]
Ok, I have a VM running Ubuntu in VirtualBox 5.0.10 r104061, and it does recognizes SSE4.1 and jtr build works...

**Comment by jfoug** [comment]
It looks like 5.0.14 may have fixed this issue.  My 5.0.0 would NOT start on my Win10 systems after they updated.  I even tried to repair install, and then install it again (Oracle does keep older versions if you look).  No good. 

So I installed the newest cut (5.0.14). Wow, AVX2 working on that version, so happy days again. Now, I can start virtualbox without it beochin about a new version.

**Comment by Fist0urs** [comment]
I tried it too and it works!

**Comment by magnumripper** [comment]
Jolly good
