### ISSUE TITLE
Legacy generic builds broken

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1992]
I just noticed that apparently commit cca621a17d05cc4c7458d527882150cc0e44e910 broke legacy generic builds.

```
$ make -s -f Makefile.legacy generic
Compiling: DES benchmark (code version #1)
bench-t.o: In function `benchmark_all':
bench.c:(.text+0xab1): undefined reference to `ldr_init_test_db'
bench.c:(.text+0xb07): undefined reference to `ldr_free_test_db'
collect2: error: ld returned 1 exit status
Makefile.legacy:1790: recipe for target 'bench' failed
make[1]: *** [bench] Error 1
Makefile.legacy:1780: recipe for target 'generic.h' failed
make: *** [generic.h] Error 1
```

Trying to add a loader_g.o to the bench build and sprinkling `#ifndef BENCH_BUILD` ... `#endif` all over loader.c  gets really messy.
Not sure how to proceed and whether it is worth it.

OTOH, `make -f Makefile.legacy generic` is probably the most useful of all the legacy targets.
(I even intended to automatically test if #BF_X2 3 is better than #BF_X2 1 for generic builds.)

**Comment by magnumripper** [comment]
> Trying to add a loader_g.o to the bench build and sprinkling #ifndef BENCH_BUILD ... #endif all over loader.c gets really messy.

A cleaner alternative might be to define a dummy stub `ldr_init_test_db()` in bench.c or somewhere else.

**Comment by jfoug** [comment]
Please check out cef44cc  This was not nearly as easy as building some 'macro'.   But putting this code into bench was simpler than all the ```#ifndef BENCH_BUILD``` and the other files that would have to have been included.  I started down that rabbit hole, and it appeared to have no bottom.

**Comment by magnumripper** [comment]
Gosh. I guess sooner or later we'll need to drop support for legacy/generic builds...

**Comment by jfoug** [comment]
Out of all the legacy stuff, the generic is probably the only one I really give a crap about.  But the systems which AC does not work on is hopefully not too large of a percentage.

**Comment by magnumripper** [comment]
If we had put all time we spent on legacy crap into AC instead, we'd now be able to configure&&make on a Casio fx-180p or a middle-endian 33-bit weather satellite.

**Comment by jfoug** [comment]
lol, have u tried building there ;)
