### ISSUE TITLE
oldoffice-opencl test failed 

### ISSUE THREAD

**Issue by watanuoli** [magnumripper/JohnTheRipper#1994]
I came across this issue with the AMD R9 290x (2 cards)
It seems to be the same as #1497.

./john -test  -format=oldoffice-opencl
Device 0: Hawaii [AMD Radeon R9 200 Series]
Benchmarking: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... FAILED (cmp_all(3))

Driver info:
ii  fglrx                 2:15.201-0ubunt amd64           Video driver for the AMD graphics accelerators
ii  fglrx-amdcccle        2:15.201-0ubunt amd64           Catalyst Control Center for the AMD graphics acc
ii  fglrx-core            2:15.201-0ubunt amd64           Minimal video driver for the AMD graphics accele
ii  fglrx-dev             2:15.201-0ubunt amd64           Video driver for the AMD graphics accelerators (

AMD opencl SDK info:
AMD-APP-SDK-v3.0.130.135-GA-linux64.sh

GPU info:
jim@pwc-01:/workspace/john/run$ clinfo 
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (1800.11)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 

  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 3
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon R9 200 Series
  Device Topology:				 PCI[ B#3, D#0, F#0 ]
  Max compute units:				 44
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1030Mhz
  Address bits:					 64
  Max memory allocation:			 2934964224
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 4096786432
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2934964224
  Max global variable size:			 2641467648
  Max global variable preferred total size:	 4096786432
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 524288
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7f74706cd430
  Name:						 Hawaii
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 1800.11 (VM)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 AMD-APP (1800.11)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_ext_atomic_counters_32 cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images 

  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 
  Device Topology:				 PCI[ B#4, D#0, F#0 ]
  Max compute units:				 44
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1030Mhz
  Address bits:					 64
  Max memory allocation:			 3008888832
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 4250927104
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 3008888832
  Max global variable size:			 2707999744
  Max global variable preferred total size:	 4250927104
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 524288
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7f74706cd430
  Name:						 Hawaii
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 1800.11 (VM)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 AMD-APP (1800.11)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_ext_atomic_counters_32 cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images

**Comment by magnumripper** [comment]
clinfo is messy, `./john -list=opencl-devices`shows everything we need.

What if you reverse acfd4198, does that help?

Before that, try this
```
for i in 0 1 3 4 ; do ./john -test=0 -form:oldoffice-opencl -cost=$i:$i; done
```
Does some of them pass?

**Comment by watanuoli** [comment]
The result shows as below:
for i in 0 1 3 4 ; do ./john -test=0 -form:oldoffice-opencl -cost=$i:$i; done
Device 0: Hawaii [AMD Radeon R9 200 Series]
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... PASS
Device 0: Hawaii [AMD Radeon R9 200 Series]
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... PASS
Device 0: Hawaii [AMD Radeon R9 200 Series]
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... FAILED (cmp_all(1))

Device 0: Hawaii [AMD Radeon R9 200 Series]
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL]... FAILED (cmp_all(1))

**Comment by watanuoli** [comment]
Here list the opencl devices : GPU x2 and CPU x1
./john -list=opencl-devices
Platform #0 name: AMD Accelerated Parallel Processing, version: OpenCL 2.0 AMD-APP (1912.5)
    Device #0 (0) name:     Hawaii
    Board name:             AMD Radeon R9 200 Series
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0 AMD-APP (1912.5)
    Driver version:         1912.5 (VM) - Crimson 15.11 
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          3.0 GB
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        1030
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 44
    Stream processors:      2816  (44 x 64)
    Speed index:            2900480
    Wavefront width:        64
    PCI device topology:    03:00.0
    ADL:                    Overdrive6, device id 0
    Fan speed:              20%
    Temperature:            42°C
    Utilization:            7%

    Device #1 (1) name:     Hawaii
    Board name:             AMD Radeon R9 200 Series
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0 AMD-APP (1912.5)
    Driver version:         1912.5 (VM) - Crimson 15.11 
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          3.0 GB
    Global Memory Cache:    16.0 KB
    Local Memory:           32.0 KB (Local)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        1030
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 44
    Stream processors:      2816  (44 x 64)
    Speed index:            2900480
    Wavefront width:        64
    PCI device topology:    04:00.0
    ADL:                    Overdrive6, device id 6
    Fan speed:              20%
    Temperature:            40°C
    Utilization:            3%

    Device #2 (2) name:     Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Device vendor:          GenuineIntel
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (1912.5)
    Driver version:         1912.5 (sse2,avx) 
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          7.0 GB
    Global Memory Cache:    32.0 KB
    Local Memory:           32.0 KB (Global)
    Max memory alloc. size: 2.0 GB
    Max clock (MHz):        3808
    Profiling timer res.:   1 ns
    Max Work Group Size:    1024
    Parallel compute cores: 8
    Speed index:            121856
    PCI device topology:    00:00.0

**Comment by watanuoli** [comment]
It works after I reversed  acfd419 !
btw:
The version of driver I am using is 15.302(official latest) and opencl APP SDK v2.9.

**Comment by magnumripper** [comment]
> The result shows as below:

So it fails in SHA-1 but works with the MD4 versions.

> It works after I reversed acfd419 !

Lol. AMD are the worst of the worst. I'll see if I can wrap that workaround in a version test.

**Comment by magnumripper** [comment]
Please verify that a0b4554 works. Thanks for reporting and testing.

**Comment by watanuoli** [comment]
Verified. The patch a0b4554 works on the 2 platforms below.  Thanks.

R9 280x 
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon R9 200 Series                          
OpenGL version string: 4.5.13399 Compatibility Profile Context 15.201.1151
OpenCL 1.2 AMD-APP (1800.11)

R9 290x
OpenGL renderer string: AMD Radeon R9 200 Series
OpenGL version string: 4.5.13416 Compatibility Profile Context 15.302
OpenCL 1.2 AMD-APP (1912.5)
