### ISSUE TITLE
OpenCL "Default to best GPU device" is broken

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1995]
After a recent change of mine (maybe #1989) the "default to best GPU" is broken (looks like it picks one low, eg. 5 instead of 6)

**Comment by magnumripper** [comment]
Might be 0a026d50 or 296a6e1a

**Comment by claudioandre** [comment]
It is 0a026d50e0f135118bbfd31b11e338be384fb1e3. You missed one detail.

**Comment by magnumripper** [comment]
Got it. That was not easy to spot.
