### ISSUE TITLE
Use __ARM_NEON instead of __ARM_NEON__?

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1998]
According to http://infocenter.arm.com/help/topic/com.arm.doc.ihi0053b/IHI0053B_arm_c_language_extensions_2013.pdf (the ARM(R) C Language Extensions Release 1.1) `__ARM_NEON` has to be tested before including <arm_neon.h>.

Also, apparently, `__ARM_NEON__` is legacy, since it is not defined in the ARM C language extensions.
(Seems to be confirmed by https://gcc.gnu.org/ml/gcc-patches/2015-01/msg02717.html).

So, we should make sure to replace all occurrences of `__ARM_NEON__` with `__ARM_NEON`.
Since some `__ARM_NEON__` references are in src/DES_bs_b.c, I'll also post this in john-dev.

Also, src/configure and src/m4/jtr_arm_logic.m4 seem to use <arm_neon.h> without any test of `__ARM_NEON` or `__ARM_NEON__`:

```
(bleeding-jumbo)JtR $ git grep -i -n ARM_NEON
src/DES_bs_b.c:34:#if defined(__ARM_NEON__) && DES_BS_DEPTH == 64
src/DES_bs_b.c:35:#include <arm_neon.h>
src/DES_bs_b.c:65:#elif defined(__ARM_NEON__) && ARCH_BITS == 32 && DES_BS_DEPTH == 96
src/DES_bs_b.c:66:#include <arm_neon.h>
src/DES_bs_b.c:99:#elif defined(__ARM_NEON__) && DES_BS_DEPTH == 128 && defined(DES_BS_2X64)
src/DES_bs_b.c:100:#include <arm_neon.h>
src/DES_bs_b.c:134:#elif defined(__ARM_NEON__) && DES_BS_DEPTH == 128
src/DES_bs_b.c:135:#include <arm_neon.h>
src/DES_bs_b.c:165:#elif defined(__ARM_NEON__) && \
src/DES_bs_b.c:168:#include <arm_neon.h>
src/DES_bs_b.c:201:#elif defined(__ARM_NEON__) && DES_BS_DEPTH == 256
src/DES_bs_b.c:202:#include <arm_neon.h>
src/arm32le.h:44:#ifdef __ARM_NEON__
src/arm32le.h:80:#ifdef __ARM_NEON__
src/configure:7838:    #include <arm_neon.h>
src/configure:7869:    #include <arm_neon.h>
src/m4/jtr_arm_logic.m4:34:       [[#include <arm_neon.h>
src/m4/jtr_arm_logic.m4:53:       [[#include <arm_neon.h>
src/pseudo_intrinsics.h:39:#ifdef __ARM_NEON__
src/pseudo_intrinsics.h:40:#include <arm_neon.h>
src/rawSHA1_ng_fmt_plug.c:26:#if defined(SIMD_COEF_32) && (SIMD_COEF_32 < 16 || ARCH_BITS >= 64) && !_MSC_VER && !__ARM_NEON__
src/rawSHA1_ng_fmt_plug.c:279:#if (__AVX512F__ && !__AVX512BW__) || __MIC__ || __ALTIVEC__ || __ARM_NEON__
src/rawSHA1_ng_fmt_plug.c:796:#elif __ARM_NEON__
src/rawSHA256_ng_fmt_plug.c:61:#elif __ARM_NEON__
src/rawSHA512_ng_fmt_plug.c:57:#elif __ARM_NEON__
src/simd-intrinsics.c:70:#elif __ARM_NEON__
src/simd-intrinsics.c:134:#if !__AVX512F__ && !__ARM_NEON__
src/simd-intrinsics.c:438:#if (ARCH_SIZE >= 8) || defined(__i386__) || defined(__ARM_NEON__)
src/simd-intrinsics.h:33:#elif __ARM_NEON__
```

When testing for `__ARM_NEON` in configure, the test might need some adjustment.

On my raspbian system with this CPU
```
pi@raspberrypi ~ $ lscpu 
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 5 (v7l)
CPU max MHz:           900.0000
CPU min MHz:           600.0000
pi@raspberrypi ~ $ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5
[...]
processor	: 3
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 57.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: BCM2709
Revision	: a01041
Serial		: 00000000........
```

Unfortunately, with these compilers
```
pi@raspberrypi ~ $ gcc --version
gcc (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

pi@raspberrypi ~ $ clang --version
Raspbian clang version 3.5.0-10+rpi1 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: arm-unknown-linux-gnueabihf
Thread model: posix
```

I need some tricks to enable __ARM_NEON

clang:
```
pi@raspberrypi ~ $ clang -dM -E -x c /dev/null | grep -i -E "(SIMD|NEON)"
pi@raspberrypi ~ $ clang -march=armv7 -dM -E -x c /dev/null | grep -i -E "(SIMD|NEON)"
#define __ARM_NEON 1
#define __ARM_NEON__ 1
```

gcc:
```
pi@raspberrypi ~ $ gcc -dM -E -x c /dev/null | grep -i -E "(SIMD|NEON)"
#define __ARM_NEON_FP 4
#define __ARM_FEATURE_SIMD32 1
pi@raspberrypi ~ $ gcc -mfpu=neon -dM -E -x c /dev/null | grep -i -E "(SIMD|NEON)"
#define __ARM_NEON_FP 4
#define __ARM_NEON__ 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_NEON 1
pi@raspberrypi ~ $ gcc -mfpu=neon-vfpv4 -dM -E -x c /dev/null | grep -i -E "(SIMD|NEON)"
#define __ARM_NEON_FP 6
#define __ARM_NEON__ 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_NEON 1
```

**Comment by frank-dittrich** [comment]
Just in case someone is interested in all the ARM definitions:
```
pi@raspberrypi ~ $ clang -march=armv7 -dM -E -x c /dev/null | grep -i -E ARM 
#define __ARMEL__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_ACLE 200
#define __ARM_ARCH 7
#define __ARM_ARCH_7A__ 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH_PROFILE 'A'
#define __ARM_EABI__ 1
#define __ARM_NEON 1
#define __ARM_NEON__ 1
#define __ARM_PCS 1
#define __ARM_PCS_VFP 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 4
#define __ARM_VFPV3__ 1
#define __arm 1
#define __arm__ 1
```

```
pi@raspberrypi ~ $ gcc -mfpu=neon-vfpv4 -dM -E -x c /dev/null | grep -i -E ARM
#define __ARM_SIZEOF_WCHAR_T 32
#define __ARM_FEATURE_SAT 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARMEL__ 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 14
#define __ARM_NEON_FP 6
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_PCS_VFP 1
#define __ARM_FEATURE_LDREX 4
#define __ARM_FEATURE_QBIT 1
#define __ARM_FEATURE_FMA 1
#define __ARM_NEON__ 1
#define __ARM_ARCH_6__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_ARCH_ISA_THUMB 1
#define __ARM_ARCH 6
#define __arm__ 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_NEON 1
#define __ARM_EABI__ 1
#define __ARM_FEATURE_DSP 1
```

**Comment by frank-dittrich** [comment]
Unfortunately, just using `clang -march=native` or `gcc -march=native` doesn't define `__ARM_NEON`.

**Comment by magnumripper** [comment]
> Also, src/configure and src/m4/jtr_arm_logic.m4 seem to use <arm_neon.h> without any test of `__ARM_NEON` or `__ARM_NEON__`

This might be fine, just as we don't test for `__SSE2__` and so on in these tests.

> I need some tricks to enable __ARM_NEON

This is normal for a plethora of systems/archs and the normal thing you'd do for configure is... nothing! You'd just pass it in CFLAGS. We do all kinds of automatic things with intel just because it's 99.5% of our user base, that's all. Otherwise we should actually require passing things like -msse2 or -avx too. I don't mind someone adding neon tests similar to what we do for intel but it's not exactly missing now, it's more of a possible feature (and bloat).

**Comment by magnumripper** [comment]
> Unfortunately, just using clang -march=native or gcc -march=native doesn't define `__ARM_NEON`.

That's exactly what our tests are about. So maybe the fix (for auto-detection) would be to evaluate whether  -march=armv7, -mfpu=neon or -mfpu=neon-vfpv4 is supported, and whether the resulting test binary runs without problems.

**Comment by frank-dittrich** [comment]
I intended to try those options, check if the self tests pass, and compare the benchmarks.
But most likely not today or tomorrow.

**Comment by frank-dittrich** [comment]
> That's exactly what our tests are about. So maybe the fix (for auto-detection) would be to evaluate whether -march=armv7, -mfpu=neon or -mfpu=neon-vfpv4 is supported, and whether the resulting test binary runs without problems.

SInce for x86-64, `-march=native` will enable the right SSE and AVX definitions, it might also be seen as gcc or clang compiler bugs for ARM. Unfortunately, raspbian includes somewhat older compiler versions.
I'll see if I can run newer versions and may be report gcc and clang bugs if -march=native doesn't enable the right definitions.

**Comment by jfoug** [comment]
We could add this to jumbo.h
```c
#if defined __ARM_NEON__ && !defined(__ARM_NEON)
#define __ARM_NEON 1
#endif
```

Or we could put the opposite define, and leave the other code intact, making only that single change inside jumbo.h

**Comment by frank-dittrich** [comment]
Solar already changed master.  And magnum changed bleeding-jumbo.
Do you really think we'll encounter a system where `__ARM_NEON__` is defined, but `__ARM_NEON` isn't?

**Comment by jfoug** [comment]
I was just going off of the comment:

```
__ARM_NEON has to be tested before including .
```

**Comment by frank-dittrich** [comment]
@jfoug I was just referring to the ARM(R) C Language Extensions Release 1.1)
http://infocenter.arm.com/help/topic/com.arm.doc.ihi0053b/IHI0053B_arm_c_language_extensions_2013.pdf
```
<arm_neon.h> is provided to define the NEON intrinsics. As these intrinsics are in the user namespace, an implementation would not normally define them until the header is included.
The __ARM_NEON macro should be tested before including the header:
#ifdef __ARM_NEON
#include <arm_neon.h>
#endif /* __ARM_NEON */
```
