### ISSUE TITLE
md5crypt-opencl benchmark failure.

### ISSUE THREAD

**Issue by watanuoli** [magnumripper/JohnTheRipper#1999]
Benchmarking: md5crypt-opencl, crypt(3) $1$ [MD5 OpenCL]... FAILED (cmp_all(1))

Tested on the following platform: 1 pass 1 fail
1. R9 280x (pass)
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon R9 200 Series
OpenGL version string: 4.5.13399 Compatibility Profile Context 15.201.1151
OpenCL 1.2 AMD-APP (1800.11)

2. R9 290x (failed)
OpenGL renderer string: AMD Radeon R9 200 Series
OpenGL version string: 4.5.13416 Compatibility Profile Context 15.302
OpenCL 1.2 AMD-APP (1912.5)

**Comment by claudioandre** [comment]
Crimson is known to be a bad choice for JtR. With SDK 3.0 it segfaults even AMD's clinfo.

IMHO it is fair enough to consider it beta quality and not suited for production usage yet.

**Comment by watanuoli** [comment]
Yes, I suppose to change to NVDIA platform.

**Comment by claudioandre** [comment]
This is off-topic: 
- you should move these two AMD boards to another computer (no need to be a powerful one). You might have a board and processor laying around without use.
- install Radeon 15.9 (see computer number 1 above) on it and keep it to be your second machine. Or use it to try long cracking sessions. Or only to run on fast hashes. Whatever seems good.

You have too much AMD "power". Add a new NVIDIA computer to it and get even more "power".
