### ISSUE TITLE
Add a format tag to krb5tgs

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2002]
I started on this but there's some question marks that need straightening out, plus I'm waiting for "standardization" with Hashcat: https://github.com/hashcat/oclHashcat/issues/81

**Comment by magnumripper** [comment]
Note to self: Any change in kirbi2john.py should be pushed upstream to [kerberoast](https://github.com/nidem/kerberoast).

**Comment by magnumripper** [comment]
My current test vector looks like this but is subject to change
```c
+       // This is AP_REQ
+       {"$krb5tgs$23$$$$3864faafef433c99b49c83fba4b6b33ff24312596347d7b9b1a30d36606987caef3e9198659fbbc08ddac9fb6b80ef167ccfebe09ec71973695675438a53ee1cdae29601f423dea0b223c1fccc05d841e7a02144e3a35b56c09609df000e74b165ae6eea7fc12b9919a54c0070dc8555b1c228b45089be24648b20dbef720ac71ef4a4bd3808a8489adae7fe6e3f2663e881ad57033e91583fdca5b2db96de53192a381654d83d489fb292826118564fa0ef7901fc25deda154978e5b15f23fb11038a46f2d478c31c11aa7f6e02a66de6ce3b5079fdf9cd76861d56bc70a4eb4c0ebbceac383fd5b0545070d9c7a33b9a45cbed4314f28cbaea345a1d834b46a05f67eb8114da7140b9365dec429967d20aa864853579b61a0f581ae9e7570c94351edc6b5e74585d2ce0640fe7a5704e6dad5431e975ab7800bd03a01226c77c12e01c647500a682ebc465df6cff7086a580e2abfc195fbf3516e53ac1ff9d99240226715e5885a5c57b0722d0c807fbe6df27d2a00b8f2e6e7e6263ea73fe10b4ce74bbc54eb620f89dc34d8348289d0bea42dfe10c0b821f7dba10455dfe3abe48f1ca5ac9ce45d4b3641749ed66fe5bfe7a57f267fd3d1841aae466214cc719cb58b4fe8ac2ed42c77cc905273ad7316efb5c119fcfc6cebf87149646e4c220527fd3a4c9a03de296f03eccee17f90dc2523805adf2f1c60afcfb575608362c0df24b15445eb08f1ea795f3e482a333a6a63b83d4def63cc2f6c9d10d46a05a82bc7b2d6524ef2560f50f902ecb0cb586376b2af4c16547d4b30ec2c239d6d625edf375d1067e8f8b057a865b88d63399cf136d3c2628f9fc695c298f99f1e61d3ed427c1434c9da4de069c24aa1ad3912744a0002b8f2596bc56a91a80970012ef5064c99af082e3494e2f6d37597cc62522503811c31446d6447d7286a1820f6bf99cc28166cbbac3174138ed1830aa6b312ad2b277f059635d52f6d3b20109d65d5b725f49a306ebc347df39628b443c3fcc1f564d31ddde0efaad4434500c6428575df45f84549a884b08c6aca82d9d06c903cca44c38516d15a43c3b0482f098351b783bed14a3a18c91efda24328453c65aad96da81557db1242650757f5ab95c23a1bcd87f496344f7225a5e36f9bc5e0f77f18891d8360acf805b3c71cf78ac6ac79c527ab29493c35c41409cb28d14c16db1ba2b6a775461a1defd783c1acbb295ba6bd31a7b4d4bb6991e2e9a1b6c740f3175cbdd3d9fb8c5bf250e39b3caf558d32d4e4ebbc6732486004657581f74d5af8293ec16baffe27ceb54cef29d2c21732b18ce297a4582fb5fcffe92ce4ff469b835075f1867c3ac140ffc44802634eb33543fe1cb887dec5d84718502a3bb0eecec2a0c154370555b5627420ee8fff83021a6a43a788747e6f43c48e605cddbf6dc31c8f8bc95f79f43d865677ecaeb71f738d496f797cd06975c1438f5575b6442980a1c31b5d5d0a31356fab640301a8089141b529e9fd010693be794d602ed567c5fcd1b4cee7eb065", "Oksala123"},
```

**Comment by Fist0urs** [comment]
I don't get it, "Kerberos 5 AP-REQ" == "krb5_tgs_fmt_plug.c" currently implemented in john. I think I didn't get what you mean exactly by "add support"... Do you mean hash format normalization?

**Comment by magnumripper** [comment]
LOL, we have too many formats. I didn't know that :sunglasses: 

So maybe we should just use that format? It's untagged though, which is bad for auto recognition. Current format is simply `<hex checksum>$<hex data>`. I still think we should add some tag like `krb5tgs$23$`at minimum. Besides, the $23$ is relevant, isn't it? If we implement the other algos they will have other numbers, right?

**Comment by Fist0urs** [comment]
Just for others to follow conversation, I replied this on the other thread:

    Yes, 23 is the constant that specifies that RC4_HMAC_NT is used. This could indeed be the tag we are searching for, to identify the format (as DES_CBC_MD5 would be 3).

    Fyi, "AP-Req" is the name of the process which consists in relaying a TGS ticket to the server which hosts the service we want to authenticate to. This TGS ticket is the result of the "TGS-Rep" obtained after doing a "TGS-Req" to the KDC.

   That's why there is a bit of confusion AP-Req/TGS-Rep but they are the same tickets :)

Yes this is the same thing, so no need to re-implement it :p. And don't worry, people use both names for this operation which confuses everyone ;)

**Comment by Fist0urs** [comment]
Ok to close this issue
