### ISSUE TITLE
undrop.exe works incorrect

### ISSUE THREAD

**Issue by shrikus** [magnumripper/JohnTheRipper#2011]
undrop copies only 12 characters from password, instead of 13 (including leading '+').

patch for undrop.c:
```
@@ -68,8 +68,8 @@ int undrop(int argc, char *argv[]) {
 	}
 
 	if (strncmp(t_line, "--PASS +", 8) == 0) {
-	    sscanf(t_line, "--PASS %12s", password);
-	    printf("%s:%s:::%s:\n", username, password, flags);
+	    sscanf(t_line, "--PASS +%12s", password);
+	    printf("%s:+%s:::%s:\n", username, password, flags);
 	}
 	fflush(stdout);
     }
```

**Comment by magnumripper** [comment]
I never used this but I wonder how that happened... did the format of the userfile change? If so we might need some backwards compatibility.

**Comment by shrikus** [comment]
nope, nothing was changed, it's just a bug ;)

here is a test data from BFEgg_fmt_plug.c:
```
static struct fmt_tests tests[] = {
    {"+9F93o1OxwgK1", "123456"},
    {"+C/.8o.Wuph9.", "qwerty"},
    {"+EEHgy/MBLDd0", "walkman"},
```
So password length must be 13 characters (with leading '+').

**Comment by magnumripper** [comment]
Thanks!
