### ISSUE TITLE
Fix Raw-SHA2-opencl scalability

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2016]
*New branch* code

|Test|Speed|Candidates|Guesses|??|
|----|-----|----|----|----|
|[1]|523906K c/s|-|-|-|
|[2]|448418Kp/s| 995 | 995| Argh! | 
|[3]|477642Kp/s| 9006 | 5 | Hmmm! |
|[4]|470812Kp/s|100001|1|D'oh!|

```
rm ../run/*.pot
../run/john --format=raw-SHA512-ng-opencl --test=5 --mask=?d?d?d?d?d?d
../run/john test512_1.in -form=raw-sha512-ng-opencl -mask:?a?d?a?a?a?a 
../run/john test512_2.in -form=raw-sha512-ng-opencl -mask:?a?d?a?a?a?a 
../run/john test512_3.in -form=raw-sha512-ng-opencl -mask:?a?d?a?d?a?a?d
```
```
for i in `seq 100005 100999`; do echo -n $i | sha512sum | sed 's/-/ /g'; done >  test512_1.in # 995    -> 995g
for i in `seq 090999 100004`; do echo -n $i | sha512sum | sed 's/-/ /g'; done >  test512_2.in # 9006   ->5g
for i in `seq 200000 299999`; do echo -n $i | sha512sum | sed 's/-/ /g'; done >  test512_3.in # -----------
for i in 1234567            ; do echo -n $i | sha512sum | sed 's/-/ /g'; done >> test512_3.in # 100001 ->1g
```
****
Current status in HEAD (**not** the -ng format)
```
../run/john test512_3.in -form=raw-sha512-opencl -mask:?a?d?a?d?a?a?d
[...]
0g 0:00:02:38 5,27% (ETA: 16:52:42) 0g/s 27184Kp/s 27184Kc/s 2718GC/s GPU:50°C &0t00Y1..c7@00Y1
```

**Comment by claudioandre** [comment]
**Note**. BUG, a format is not using shared code.

*Loaded* **X** *password hashes*
*Remaining* **Y** *password*

```
../run/john --format=raw-SHA512 alltests.in --incremental --max-run=10
Using default input encoding: UTF-8
Loaded 10 password hashes with no different salts (Raw-SHA512 [SHA512 128/128 AVX 2x])
Remaining 7 password hashes with no different salts
```
```
--format=raw-SHA512-opencl alltests.in --incremental --max-run=10
Device 6: GeForce GTX TITAN X
Using default input encoding: UTF-8
Loaded 9 password hashes with no different salts (Raw-SHA512-opencl [SHA512 OpenCL (inefficient, development use mostly)])
```

**Comment by claudioandre** [comment]
Note to self: ask if something like this make sense/can be done:

```
../run/john ~/crame_me -form=raw-sha512-ng-opencl -mask:?A -min-len=0 -max-len=4 --internal-codepage=ALL
```

I'm testing this on CMIYK 2015 file (if I got the correct file). There are encoded characters.

* ../run/john ~/crame_me [...] -min-len=0 -max-len=4 --internal-codepage=KOI8-R
* ../run/john ~/crame_me [...] -min-len=0 -max-len=4 --internal-codepage=CP720
* And so on.

**Comment by claudioandre** [comment]
|Test|Original|Candidates|Guesses| Status Now
|----|-----|----|----|----|----
|[1]|528000K c/s|-|-| 557443K c/s
|[2]|458383Kp/s| 995 | 995|  491125Kp/s
|[3]|492854Kp/s| 9006 | 5 |  509066Kp/s
|[4]|430955Kp/s|100001|1| 505904Kp/s
|[5]| - |300002|1|  512268Kp/s

```
rm ../run/*.pot
for i in `seq 1 300000`        ; do echo -n '#'$i'&' | sha512sum | sed 's/-/ /g'; done >  test512_4.in # -----
for i in 123456                ; do echo -n $i | sha512sum | sed 's/-/ /g'; done >> test512_4.in # 
for i in 1234567               ; do echo -n $i | sha512sum | sed 's/-/ /g'; done >> test512_4.in # 
```
```
../run/john test512_4.in -form=raw-sha512-ng-opencl -mask:?a?d?a?d?a?a?d 
Device 6: GeForce GTX TITAN X
Using default input encoding: UTF-8
Loaded 300002 password hashes with no different salts (Raw-SHA512-ng-opencl [SHA512 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
1234567          (?)
1g 0:00:02:39 DONE (2016-02-01 22:33) 0.006272g/s 512268Kp/s 512268Kc/s 153681GC/s GPU:81°C ##M#E|7..##t#a|7
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by magnumripper** [comment]
Nice figures. Did you use Sayantan's hash stuff or something else?

**Comment by claudioandre** [comment]
I'm building each piece my own way in order to see where I can get.
****

BTW: I posted a question about Japanese/Chinese characters not been found. Thinking again, no encoding generates such characters, right? 
If so, is this feature request in top trends (in terms of number of people)?. Seems useful.

**Comment by claudioandre** [comment]
### Strategy for salted formats [WIP]

Possible now (note: tableX means bitmap or hash table or whatever):

```
prepare_tableX(struct db_salt *salt)
	//build a lookup table using all hashes in this salt
	for each item in (db->salts->list)
		add(item->binary);

	writeBufferToGPU(tableX)
	clFinish() //Transfer data do GPU

reset(struct db_main *db)
	if (db)
		prepare_tableX(db->salts);

set_salt(void *salt)
	prepare_tableX(salt); //Nighmare: recompute and extra data transfer in every set_salt().

	writeBufferToGPU(salt_itself)
	clFinish() //Transfer data do GPU

crypt_all(struct db_salt *salt)
	if (any hash has been cracked)
		prepare_tableX(salt); //ok, rebuild your table

	doTheRealWork()
```

* Problem 1. For every set_salt() I will have to build and transfer tableX. Of course, more hashes means less performance.
* Should be possible to save tableX inside core db->salts (to avoid to recompute tableX for every set_salt())?

Possibilities:
* Behave as saltless formats, transfer tableX once in reset(). Note: **N** salts.
* Produce false positives on GPU.
* Do a full hash computation on CPU and check.

Problems:
* I can't see all salts in crypt_all (I need to recompute tableX to remove the cracked items). 
* Is it safe to keep a copy of db from reset()?

**Comment by magnumripper** [comment]
> BTW: I posted a question about Japanese/Chinese characters not been found. Thinking again, no encoding generates such characters, right? 

No 8-bit [single-byte] *codepage* does this as far as I'm aware. Prior to UTF-8 they had other multi-byte variants somewhat similar to UTF-8. I never heard anyone wanting support for the old stuff and I have absolutely no idea how they work.

**Comment by magnumripper** [comment]
Regarding salts, have a peak at mscash [not mscash2]. I think that one is good. I'm pretty sure all salts are only transfered once.

**Comment by claudioandre** [comment]
```
$ ../run/john --format=xSHA512-ng-opencl --test=5 --mask=?d?d?d?d?d?d
Device 6: GeForce GTX TITAN X
Benchmarking: XSHA512-ng-opencl, Mac OS X 10.7 salted [SHA512 OpenCL]... DONE, GPU util:99%
Warning: "Many salts" test limited: 23/256
Many salts:	552000K c/s real, 550923K c/s virtual
Only one salt:	550923K c/s real, 549852K c/s virtual
```

**Comment by claudioandre** [comment]
|Test|Candidates|Guesses| Status
|----|----|----|----|----
|[1]|-     |-| 560761K c/s
|[5]|300,002|1| 512268Kp/s
|[6]|3,062,025|1| 504680Kp/s
```
$ ../run/john test512_5.in -form=raw-sha512-ng-opencl -mask:?l?l?a?d?a?a?a
Device 6: GeForce GTX TITAN X
Using default input encoding: UTF-8
Loaded 3062025 password hashes with no different salts (Raw-SHA512-ng-opencl [SHA512 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
ax41672          (?)
1g 0:00:18:11 DONE (2016-02-04 16:05) 0.000915g/s 504680Kp/s 504680Kc/s 1545TC/s GPU:82°C vk#3#}|..vn#3#}|
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```
```
cp test512_4.in test512_5.in
for i in `seq 300001 7000000`   ; do echo -n $i | sha512sum | sed 's/-/ /g'; done >> test512_5.in # Gave up at some point
for i in ax41672                ; do echo -n $i | sha512sum | sed 's/-/ /g'; done >> test512_5.in # 
```

**Comment by claudioandre** [comment]
|Test|Candidates|Guesses| Status
|----|----|----|----|----
|[1]|-     |-| 593050K c/s
|[2]|995|995| 515681Kp/s
|[5]|300,002|1| 543004Kp/s 
|[6]|3,062,025|1| 542469Kp/s

**Comment by claudioandre** [comment]
```
rm ../run/*.pot
for i in `seq 1 300000`        ; do echo -n '#'$i'&' | sha256sum | sed 's/-/ /g'; done >  ~/data/test256_5.in # -----
for i in 123456                ; do echo -n $i | sha256sum | sed 's/-/ /g'; done >> ~/data/test256_5.in # 
for i in 1234567               ; do echo -n $i | sha256sum | sed 's/-/ /g'; done >> ~/data/test256_5.in # 
for i in ax41672               ; do echo -n $i | sha256sum | sed 's/-/ /g'; done >> ~/data/test256_5.in # 
for i in `seq 300001 4000000`  ; do echo -n $i | sha256sum | sed 's/-/ /g'; done >> ~/data/test256_5.in # 
```

**Comment by jfoug** [comment]
You might want to check out pass_gen.pl ;)  This script runs in a less than a minute.
```sh
rm ../run/*.pot
perl -e 'for($i = 1; $i < 300000; ++$i){print"#$i&\n";}' > dict
echo 123456 >> dict
echo 1234567 >> dict
echo ax41672 >> dict
perl -e 'for($i = 300001; $i < 4000000; ++$i){print"#$i&\n";}' >> dict
../run/pass_gen.pl -count=99999999999 raw-sha256 < dict > ~/data/test256_5a.in
rm dict
```

**Comment by jfoug** [comment]
ca65fac was a change to pass_gen.pl to allow better formatting of the output lines.

For the above script, you might want to add the -outformat=raw command switch to pass_gen.pl

**Comment by claudioandre** [comment]
Very good!!

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by claudioandre** [comment]
raw-SHA256 [GPU]

Using k=2 in the B. Filter:
- false positives rate decreases from 0,05% (thousands) to less than 200 (0,0002%).

**Comment by claudioandre** [comment]
raw-SHA256 [GPU]

|Test|Candidates|Guesses| Status
|----|----|----|----|
|[1]|-     |-| 1488M c/s
|[2]|-     |-| 1397M c/s
|[3]|1|1| 1420Mp/s
|[4]|1.5M|1| 1297Mp/s

```
../run/john --format=raw-SHA256-opencl --test=5 --mask=?d?d?d?d?d?d
../run/john --format=raw-SHA256-opencl --test=5 --mask:?l?l?a?d?a?a?a
rm ../run/*.pot; ../run/john ~/data/test256_1.in -form=raw-sha256-opencl -mask:?l?l?a?d?a?a?a
rm ../run/*.pot; ../run/john ~/data/test256_5.in -form=raw-sha256-opencl -mask:?l?l?a?d?a?a?a
```
