### ISSUE TITLE
--enable-mpi causes john to hang out on specific hardware

### ISSUE THREAD

**Issue by Fist0urs** [magnumripper/JohnTheRipper#2017]
I don't know if this issue is from john core or libmpi, but when compiling using --enable-mpi, a simple call to john (no argument) causes it to hang out indefinitly.

Some extra informations:

    $ ltrace ./john
    getenv("CPUID_DISABLE")                                                                          = NULL
    MPI_Init(0x7fff29dcc0bc, 0x7fff29dcc0b0, 0x7fff29dcc238, 524800, 0x1670010

    $ strace ./john
    cntl(9, F_GETFL)                       = 0x2 (flags O_RDWR)
    fcntl(9, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
    connect(9, {sa_family=AF_INET, sin_port=htons(40402), sin_addr=inet_addr("IP_ADDRESS")}, 16) = -1 EINPROGRESS (Operation now in progress)
    poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=9, events=POLLOUT}], 4, 1000) = 0 (Timeout)
    sched_yield()                           = 0
    poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=9, events=POLLOUT}], 4, 1000) = 0 (Timeout)
    sched_yield()                           = 0
    poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=9, events=POLLOUT}], 4, 1000) = 0 (Timeout)
    sched_yield()                           = 0
    poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=9, events=POLLOUT}], 4, 1000) = 0 (Timeout)
    sched_yield()                           = 0
    poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=9, events=POLLOUT}], 4, 1000) = 0 (Timeout)
    sched_yield()                           = 0
    poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=9, events=POLLOUT}], 4, 1000) = 0 (Timeout)
    sched_yield()                           = 0
    poll([{fd=4, event

and cpu info:

    $ cat /proc/cpuinfo
    processor       : 0
    vendor_id       : GenuineIntel
    cpu family      : 6
    model           : 44
    model name      : Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
    stepping        : 2
    microcode       : 0x14
    cpu MHz         : 2933.574
    cache size      : 12288 KB
    physical id     : 0
    siblings        : 6
    core id         : 0
    cpu cores       : 6
    apicid          : 0
    initial apicid  : 0
    fpu             : yes
    fpu_exception   : yes
    cpuid level     : 11
    wp              : yes
    flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm arat dtherm tpr_shadow vnmi flexpriority ept vpid
    bogomips        : 5867.14
    clflush size    : 64
    cache_alignment : 64
    address sizes   : 40 bits physical, 48 bits virtual
    power management:

**Comment by magnumripper** [comment]
Not sure this is a JtR issue at all. Is the network configuration OK on that machine?

**Comment by Fist0urs** [comment]
Yes it is ok

**Comment by magnumripper** [comment]
I can see it's Linux and intel. What distro, and/or what MPI flavor is it? The MPI stuff in Jumbo is tested on quite a lot of different platforms, both with MPICH2 and OpenMPI and a range of versions.

**Comment by Fist0urs** [comment]
It is Ubuntu 12.04 LTS x64. Concerning MPI I'm not an expert, is this what you are asking for?:

    dpkg --get-selections | grep mpi
    libopenmpi-dev                                  install
    libopenmpi1.3                                   install
    openmpi-bin                                     install
    openmpi-checkpoint                              install
    openmpi-common                                  install

**Comment by magnumripper** [comment]
I know MPI has been working just fine on Ubuntu 12.04 and/or OpenMPI 1.3. Something must be wrong with your setup. Can you try some other MPI program?

Also, what if you actually use MPI, as in `mpirun ./john` or mpirun -np4 ./john`?

**Comment by magnumripper** [comment]
WO
