### ISSUE TITLE
Build a tool to create and execute test cases

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2019]
Get some code from TS and build a tool that parses and execute test cases: 
1. read the test cases;
2. for each test case, execute the commands requested;
3. validate as TS does now: # of guesses ok, exit()=0, etc.

Examples:
```
<Prepare>
	../run/john -form:cpu --list=format-tests | cut -f3 >alltests.in
	../run/john --format=cpu --list=format-tests | cut -f4 > solution.dic
</Prepare>

<Clear>
	rm ../run/*.pot
</Clear>

<TestCases format=raw-SHA512-opencl>

<Case1 guesses=1>
../run/john alltests.in -form=raw-sha512-ng-opencl -mask=?u?u?uCAPS
</Case1>

<Case2 guesses=10>
../run/john alltests.in -form=raw-sha512-ng-opencl --wo:solution.dic
</Case2>
<TestCases>

<Execution>
  <Name=T1>
 	DO=Prepare()
	DO=Clear()
	DO=Case1()
	DO=Case2()
  </Name>
</Execution>
```

**Comment by jfoug** [comment]
and how is this different/better than ```./jtrts.pl -internal``` ?

**Comment by claudioandre** [comment]
I have to admit that I do not have a clear view of -internal. Anyway, I want to create test cases, to:
- automate the check of reported errors/avoid regressions.
- I would like to test if mask works: none, few and all cracked.
- I would like to test --skip-self-test 
- I would like to test --min-len and --max-len
- Etc.

The point is: I need to test. And I have to write these tests all the time.

**Comment by magnumripper** [comment]
The best would be to add features to the TS.

**Comment by claudioandre** [comment]
I probably will mess up things inside TS. So, I created a script just to keep tests saved.

I added it to /unused and will PR (to keep it saved and under VC)

**Comment by claudioandre** [comment]
3e455de886d610520250fff3714134e4989e8692
