### ISSUE TITLE
Mask mode bug: Placeholder within brackets

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2029]
[Solar  wrote](http://www.openwall.com/lists/john-users/2016/02/07/4):
> magnum, Sayantan -

> However, this appears buggy:
```
$ ./john --mask='[1?9]' --stdout
1
[
]
3p 0:00:00:00 100.00% (2016-02-08 02:50) 50.00p/s ]
```
and e.g. '[1?2]' is even worse.  Looks like we're (wrongly) expanding
?digit (but not ?letter) even inside square brackets?  This looks like a
jumbo bug to me.

**Comment by jfoug** [comment]
What IS the proper handling ??

[ab?9]   Should that be [ab] since we do not have any custom ?9 or [ab?9]

**Comment by jfoug** [comment]
@magnumripper can you validate that the committed fix is the right logic please.  If so, this bug is completed.

**Comment by magnumripper** [comment]
From just looking at it, I was convinced your fix was completely wrong [as in wrong place]... BUT fortunately some quick tests seem to indicate I was wrong! More testing needed though. We have a topic somewhere (not sure it's open or closed) that lists a lot of test cases and their expected behavior.

**Comment by jfoug** [comment]
If you use MASK_DEBUG, things are pretty easy to follow along, and that is why I zero'd in on that function.  I 'know' what that function is doing (just replacing unknown replacements with known ones).  The problem appears to be that when we were doing that, we simply were jamming in a new [xxxxx] group block.  But that was wrong logic if we are INSIDE a group already.  In that case, we just leave the ? and digit alone.

If there are more test cases, that would be fine.

**Comment by magnumripper** [comment]
Yeah I see now it's absolutely the correct function, I'm pretty sure this is correct.

**Comment by magnumripper** [comment]
You don't handle escaped brackets though. This is a can of worms...

**Comment by jfoug** [comment]
lol, you beat me to it (see edited message above).

**Comment by jfoug** [comment]
The \] and \[ should be the only things to 'worry' about, right ?

**Comment by magnumripper** [comment]
I think so. A big problem here is we haven't really established a 100% complete syntax, and how to handle situations like #2033.

**Comment by jfoug** [comment]
Easy fix.

a62352e

**Comment by jfoug** [comment]
Yes, I understand that #2033 'may' change things, such as () being 'like' []

I might actually have a quick look at adding that type syntax. It really should be easy to put the syntax in (having (-[ and )-] meaning the same thing. Then add logic to the ( and ) so that they have another value that is nothing.  But that will be for another day.  Now that I have found MASK_DEBUG, it makes working on mask a lot easier. I have never touched mask.c before.

**Comment by magnumripper** [comment]
#841 has a lot of test cases and discussion

**Comment by magnumripper** [comment]
IMO we can't add any special meaning to normal parens without consulting john-users and possibly the Hashcat team.
