### ISSUE TITLE
raw SHA-1 output format

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2032]
Our current SHA-1 code unifies all pot entries to Base64 (since 25092e1), which is different from latest release. I think a change like that need to be discussed on john-users first, we may want to unify to hex instead.

**Comment by frank-dittrich** [comment]
Didn't test this right now. But if the old hex format is still valid, and pot file lines with hex encoding are not ignored, I think such a change could be acceptable. I agree this should be discussed on john-users.

**Comment by magnumripper** [comment]
Old entries are supposedly parsed OK, so no conversion of old pots are needed. Still, I'd like folks to have a chance to comment before a change like that.

We should also verify that loading of eg. 100M hashes isn't busted by this, memory or performance wise.

**Comment by magnumripper** [comment]
I reverted this in 934794f since there were several problems. We now unify to hex.
