### ISSUE TITLE
Mask mode, undefined custom placeholder

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2033]
If a custom placeholder is used but not defined, we should bail out with error, or possibly treat it as "nothing" for all purposes. We currently don't.

Example:
```
../run/john -stdout -mask=a?9b
```
The current behavior is very strange, I'm not quite sure how it ends up that way but it's 255 lines of `a` and then finally a line of `a\x7fb` and I have absolutely no idea where that `\x7f` comes from.

**Comment by jfoug** [comment]
Should we 'bail' or just output nothing (for that replacement?

**Comment by jfoug** [comment]
de19a0e  (simply 'skips' any non-set replacements).

```
$ ../run/john -stdout -mask='a?9x?2'
axa
axe
axi
axo
axn
axr
axl
axs
axt
axm
axc
axd
axy
axh
axu
axb
axk
axg
axp
axj
axv
axf
axw
axz
axx
axq
ax1
ax0
ax2
ax3
ax9
ax8
ax5
ax4
ax6
ax7
36p 0:00:00:00 100.00% (2016-02-10 14:41) 1000p/s ax7
```

**Comment by jfoug** [comment]
NOTE, the 'same' bug is seen here, however, so we may want to look at how groups are handled.

```
$ ../run/john -stdout -mask='a[]'
a
a
a
...  255 a's
```

**Comment by jfoug** [comment]
In mask_debug I see this:

```
parse_hex([aeionrlstmcdyhubkgpjvfwzxq1023985467AEIOLRNSTMCDBYHUPKGJVFWZXQ])
parse_hex([aeionrlstmcdyhubkgpjvfwzxq1023985467])
parse_hex([aeionrlstmcdyhubkgpjvfwzxq1023985467*!$@_])
Custom masks expanded (this is 'mask' when passed to parse_braces()):
'pa[]'
parse_braces('pa[]')
parse_qtn('pa[]')
qw 0 minlen -1 maxlen 0 fmt_len 125 mask_add_len 5
Custom masks expanded (this is 'mask' when passed to init_cpu_mask()):
'pa[]'
init_cpu_mask('pa[]')
mask_crk_init()
do_mask_crack((null))
generate_template_key('pa[]') key (null) len 0 (max 125)
Mask ''pa#'' has no 8-bit
'pa
```

**Comment by jfoug** [comment]
I am going to close this one (the issue was addressed), and open a new issue about 'empty' braces.
