### ISSUE TITLE
doc/AxCrypt-Auditing-HOWTO.md: Little-endian UTF-16 Unicode text, with CRLF, CR line terminators

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2041]
Two problems: line endings and UTF-16 instead of UTF-8 (or ascii).
```
(bleeding-jumbo)doc $ file AxCrypt-Auditing-HOWTO.md
AxCrypt-Auditing-HOWTO.md: Little-endian UTF-16 Unicode text, with CRLF, CR line terminators
```

I noticed that when a git pull apparently treated that file as binary:
```
(bleeding-jumbo)JtR $ git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/magnumripper/JohnTheRipper
   fee3260..967be59  bleeding-jumbo -> origin/bleeding-jumbo
Updating e454cca..967be59
Fast-forward
 doc/AxCrypt-Auditing-HOWTO.md         |  Bin 0 -> 8412 bytes
 doc/CHANGES                           |   12 +-
```

**Comment by jfoug** [comment]
There were also WS ending line problems, strange intermix of spaces and tabs for indentation, etc.  I fixed all of that also.

Not sure what editor was used, but certainly it was not reading or observing our .editorconfig file

**Comment by Fist0urs** [comment]
I used notepadd++ and I forgot to dos2unix, my bad :-1:

**Comment by jfoug** [comment]
Load EditorConfig plugin (into notepad++), and this should auto work right.  However, the .md extension probably is not set in john's .editorconfig file.

Also, I am not sure EditorConfig plugin will keep notepad++ from writing out in UC2 encoding. You might have to do that yourself (ASCII is what to use).

**Comment by frank-dittrich** [comment]
May be we should add
```
charset = utf-8
```
to .editorconfig "section" `[*]`

**Comment by magnumripper** [comment]
Yeah I guess. And perhaps document/advertise the editorconfig stuff a bit..

**Comment by frank-dittrich** [comment]
Jim already committed that .editorconfig change.
