### ISSUE TITLE
Zip format fails to load some entries

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2063]
http://www.openwall.com/lists/john-users/2016/02/22/2

I'm currently bisecting

**Comment by magnumripper** [comment]
Bug introduced in 1b0031f0e. The commit right before it is c52b152 and it works fine.

**Comment by magnumripper** [comment]
I have no time for this right now.

**Comment by frank-dittrich** [comment]
When fixing that bug, the some_pdfs.zip hash might be added to the self tests, to protect against re-introducing that bug in the future.

**Comment by magnumripper** [comment]
Maybe not... the problem could be that it's an external file. We could have it in TS though.
