### ISSUE TITLE
 more undefined references to `JOHNSWAP64' follow

### ISSUE THREAD

**Issue by dibiloid** [magnumripper/JohnTheRipper#2076]
/home/corvet/data/Download/JohnTheRipper/src/cuda_rawsha512_fmt_plug.c:210: undefined reference to `JOHNSWAP64'
/home/corvet/data/Download/JohnTheRipper/src/cuda_rawsha512_fmt_plug.c:210: undefined reference to `JOHNSWAP64'
/home/corvet/data/Download/JohnTheRipper/src/cuda_rawsha512_fmt_plug.c:210: undefined reference to `JOHNSWAP64'
/home/corvet/data/Download/JohnTheRipper/src/cuda_rawsha512_fmt_plug.c:210: undefined reference to `JOHNSWAP64'
/home/corvet/data/Download/JohnTheRipper/src/cuda_rawsha512_fmt_plug.c:210: undefined reference to `JOHNSWAP64'
cuda_rawsha512_fmt_plug.o:/home/corvet/data/Download/JohnTheRipper/src/cuda_rawsha512_fmt_plug.c:210: more undefined references to `JOHNSWAP64' follow
collect2: error: ld returned 1 exit status
make[1]: *** [../run/john] Error 1
make[1]: Leaving directory `/data/data/Download/JohnTheRipper/src'
make: *** [default] Error 2

Linux Mint 17.2

**Comment by jfoug** [comment]
Please verify that this problem is gone.

**Comment by dibiloid** [comment]
ar: creating aes.a
ptxas info    : 0 bytes gmem
cuda_cryptmd5_fmt_plug.c:31:2: error: invalid preprocessing directive #inculde
 #inculde "johnswap.h"
  ^
make[1]: *** [cuda_cryptmd5_fmt_plug.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2

**Comment by jfoug** [comment]
lol, what a bonehead typo.  This is the problem of not building cuda.

Please try after 33f8615

**Comment by dibiloid** [comment]
good fix !!!
