### ISSUE TITLE
latest windows build JtR-MinGW-3b8c5b3.zip --> 0xc0000142

### ISSUE THREAD

**Issue by ulu** [magnumripper/JohnTheRipper#2083]
Today I tried to get any pre-compiled windows version of JtR from http://www.openwall.com/john/ running on my Windows 10 x64 but I got always error messages (e.g. `Couldn't compute FAST_CWD pointer`). Trying to build any 1.7.9-jumbo or 1.8.0-jumbo also failed with missing symbol `MD5_body_for_thread` during linking . So I decided to use the latest build from Download section in `Readme.md` of https://github.com/magnumripper/JohnTheRipper/tree/bleeding-jumbo. After decrompression of JtR-MinGW-3b8c5b3.zip I tried to generate a hash file using following command:
`zip2john.exe d:\__HDD_saving\HDD3\privat.zip > d:\zip.hashes`

But all I got is an error message box complaining about an execution error 0xc0000142.

Here is the windows event log:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-03-10T18:07:48.166545900Z" /> 
  <EventRecordID>4797</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>KiSchwa-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>john.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>libwinpthread-1.dll</Data> 
  <Data>1.0.0.0</Data> 
  <Data>8973db78</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000002bbb</Data> 
  <Data>3048</Data> 
  <Data>01d17af7c0c82f06</Data> 
  <Data>d:\JtR-MinGW-3b8c5b3\run\john.exe</Data> 
  <Data>d:\JtR-MinGW-3b8c5b3\run\libwinpthread-1.dll</Data> 
  <Data>3c111a1e-66e8-4741-9425-ad03e112dc18</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by magnumripper** [comment]
See #2190 (dupe) for more details.

**Comment by kholia** [comment]
The latest MinGW builds work fine on Windows 10 x64. This issue can be closed now.
