### ISSUE TITLE
pbkdf2-hmac-sha1-opencl segfaults

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2094]
eff5a92 broke pbkdf2-hmac-sha1-opencl. Segfaults every time during auto-tune (so eg. --test=0 works fine while --test does not). Given the problem I wonder whether you verified performance before/after at all?

**Comment by magnumripper** [comment]
Also, please note more formats use the same kernel:
```
$ git grep -l opencl_pbkdf2_hmac_sha1.h
opencl/pbkdf2_hmac_sha1_kernel.cl
opencl_encfs_fmt_plug.c
opencl_iwork_fmt_plug.c
opencl_krb5pa-sha1_fmt_plug.c
opencl_pbkdf2_hmac_sha1_fmt_plug.c
```
So three formats that use this shared kernel were not adapted at all. They seem to work fine, I just hope we don't have latent problems in them now?

**Comment by jfoug** [comment]
I for the life of me, can not find this.  It only happens during auto-tune.  The thing is, the format will crack just fine and ST just fine, if LWS/GWS are given.   I have found a couple issues, but nothing that was any kind of core, just things which should have been copied over to 'common' coding.

**Comment by jfoug** [comment]
The bug had to do with change to salt.  Nothing  past split() expected to ever see . chars again. Split removes them and replaces them with '$' chars (which really should have been proper normalization from start).

BUT finding GWS and LWS did not call split (only prepare).

I have added split call after prepare, and am testing all opencl hash types.  I do not expect any problems from that addition, but want to check other formats just to be sure.

So there was no 'latent' problems with buffer size changes or anything like that within the CPU<->GPU code.  It was simply my lack of understanding how the auto-tune was doing self test work, and possibly an issue all along in that part of the ST work chain.

**Comment by jfoug** [comment]
This is the change I am validating

```diff
$ git diff common-opencl.c
diff --git a/src/common-opencl.c b/src/common-opencl.c
index 96ea7e3..6f3a408 100644
--- a/src/common-opencl.c
+++ b/src/common-opencl.c
@@ -1208,6 +1208,7 @@ static cl_ulong gws_test(size_t gws, unsigned int rounds, int sequential_id)
        if (!self->params.tests[0].fields[1])
                self->params.tests[0].fields[1] = self->params.tests[0].ciphertext;
        ciphertext = self->methods.prepare(self->params.tests[0].fields, self);
+       ciphertext = self->methods.split(ciphertext, 0, self);
        salt = self->methods.salt(ciphertext);
        if (salt)
                dyna_salt_create(salt);
@@ -1420,6 +1421,7 @@ void opencl_find_best_lws(size_t group_size_limit, int sequential_id,
        if (!self->params.tests[0].fields[1])
                self->params.tests[0].fields[1] = self->params.tests[0].ciphertext;
        ciphertext = self->methods.prepare(self->params.tests[0].fields, self);
+       ciphertext = self->methods.split(ciphertext, 0, self);
        salt = self->methods.salt(ciphertext);
        if (salt)
                dyna_salt_create(salt);
```

**Comment by magnumripper** [comment]
Wow, so that was a bug long before eff5a92 yet it never showed up until that commit. Your proposed patch definitely makes sense.

**Comment by magnumripper** [comment]
Thanks, will test.

**Comment by jfoug** [comment]
Yup, this issue has been there forever, but until a format came across which 'required' it, nothing bad ever showed up.  Now pbkdf2-hmac-sha1* requires split to normalize out all the '.' separators so bam, a strange crash that really was NOT apparent. I kept looking in the code where the CPU/GPU interfaced, thinking that was likely the bad stuff.   The thing that bothered me most, was the this format WORKED just fine.  It would crack, ST, everything, as long as it did not have to go through the auto-tune code.

**Comment by jfoug** [comment]
NOTE, I also did find a couple minor issues (like binary doing up to 4 limb length binaries). NOTE, I simply added the code to do that. We only use the first binary limb, which is all we really need no matter what.  If we have 20 bytes of matched binary, then there is NO REASON at all to get more of it, UNLESS we were going to use that data for a key or something. Since we are simply doing this as a validation that the password is right, then a 1 limb binary is all we need to care about.

**Comment by jfoug** [comment]
That is the correct order for the format methods, correct?

prepare()
split()
salt()
set_salt()
crypt_all()

**Comment by frank-dittrich** [comment]
IIRC, split() is allowed to assume that all the hashes have passes valid().

**Comment by jfoug** [comment]
I thought split() was called prior to valid()

**Comment by jfoug** [comment]
This is in the common code:

```C
int pbkdf2_hmac_sha1_valid(char *ciphertext, struct fmt_main *self) {
	char *ptr, *ctcopy, *keeptr;
	size_t len;
	char *delim;

	if (strncasecmp(ciphertext, PBKDF2_SHA1_FORMAT_TAG, PBKDF2_SHA1_TAG_LEN))
		return 0;
	if (strlen(ciphertext) > PBKDF2_SHA1_MAX_CIPHERTEXT_LENGTH)
		return 0;
	ciphertext += PBKDF2_SHA1_TAG_LEN;
	delim = strchr(ciphertext, '.') ? "." : "$";
	if (!(ctcopy = strdup(ciphertext)))
```

So valid DOES look for both a . and a $.

**Comment by jfoug** [comment]
So the 'correct' order of method calls is:

That is the correct order for the format methods, correct?

```
// during load
prepare();
valid();
split();
salt();
binary();
//during crack
  set_key() ... set_key()
    set_salt()
      crypt_all()
      cmp_all() [ _one() _exact() log crack, etc ]
    set_salt()
      crypt_all()
      cmp_all()
```

And during some ST runs, certain things are not done (like cmp_all() ?) or valid(), etc

**Comment by frank-dittrich** [comment]
And, from formats.h:
`prepare(), valid(), and split() are the only methods that are allowed to be called before a call to init()`
