### ISSUE TITLE
use John the Ripper with custom rules

### ISSUE THREAD

**Issue by zjhxmjl** [magnumripper/JohnTheRipper#2096]
I am trying to use John the Ripper with custom rules. I first added few extra rules in /etc/john.conf.
 For example 
[List.Rules:CustomRule]
cA0"[0-9][0-9]"
A0"[0-9][0-9]"
I tried to generate passwords using those rules but getting this error info:
$ john --wordlist:short-dict.txt --rules:CustomRule --stdout
Extra parameter for option: "--rules:CustomRule"
john version:John the Ripper password cracker, version 1.8.0
OS:fedora 20
thanks million!

**Comment by jfoug** [comment]
You are trying to use jumbo 'logic' but are using a non-jumbo build of john   the core build (non-jumbo), ONLY knows how to read from 

[List.Rules:Wordlist]  (I think that is the rule list).  It does not know how to be told to use alternative rules sections.

I would strongly recommend obtaining bleeding jumbo from this github, and building it. base john and jumbo john are night and day different.

**Comment by zjhxmjl** [comment]
thanks @jfoug

**Comment by zjhxmjl** [comment]
@jfoug is there some guides for install on fedora 20?

**Comment by frank-dittrich** [comment]
@zjhxmjl you closed the issue, so you probably managed to install bleeding-jumbo.
But why fedora 20? Fedora 20 has reached it's end-of life a long time ago, so you'll have many unfixed security issues. You really should install something more recent, e.g. fedora 23.

**Comment by zjhxmjl** [comment]
@frank-dittrich Thank you for your reminder
