### ISSUE TITLE
some questions about John the Ripper with custom rules

### ISSUE THREAD

**Issue by zjhxmjl** [magnumripper/JohnTheRipper#2097]
1,if i can specify two wordlist files with john?because i want to combination of two wordlists?maybe use rules can achive this?
for example:
file 1:                                                        file2:
zhu                                                          1231
yang                                                         2345
tian                                                           4579
i want to result:
zhu1231
zhu2345
zhu4579
yang1231
yang2345
........
tian4579

2,i want to limit the total length to 8
for example:
file 1:                                                               file2:
zhu                                                                  1231
yang                                                                2345
tian                                                                  4579
i want to result:
zhu1231 --(length 7,so not include)
zhu2345--(length 7,so not include)
zhu4579--(length 7,so not include)
yang1231--(length 8,so include)
yang2345--(length 8,so include)
........
tian4579(length 8,so include)

i find the rules,i modify but not success!
[List.Rules:KoreLogicRulesAddJustNumbersLimit8]
<8>1cAz"[0-9]"
<8>1Az"[0-9]"
<8>1A0"[0-9]"
<8>1cA0"[0-9]"
<7>1Az"[0-9][0-9]"
<7>1cAz"[0-9][0-9]"
<7>1A0"[0-9][0-9]"
<7>1cA0"[0-9][0-9]"
<6>1Az"[0-9][0-9][0-9]"
<6>1cAz"[0-9][0-9][0-9]"
<5>1Az"[0-9][0-9][0-9][0-9]"
<5>1cAz"[0-9][0-9][0-9][0-9]"

3,i google and find some rules,but i don't know what's mean ?for example:
[List.Rules:Prepend2Letters]
cA0"[abcdefghjklmnopqrstwxyz][abcdefghjklmnopqrstwxyz]"
A0"[abcdefghjklmnopqrstwxyz][abcdefghjklmnopqrstwxyz]"
cA0 and A0 what's the diffenece?

4,i want to create a rule about append year-month-day,eg:yyyymmdd,(19700101-20161231)
it's my rule,but wrong!
[List.Rules:apppendyearmonthday]
A0"20[0-1][0-6][01-12][1-31]"
A0"19[7-9][0-9][01-12][1-31]"

sorry,waste your time!thanks million!

**Comment by claudioandre** [comment]
This kind of question should be posted in john-user mailing list:
1. it is not an issue at all.
2. you just need to learn how to use john modes.

NOT *on behalf of an angry magnum.*

**Comment by zjhxmjl** [comment]
@claudioandre OK,i had sent email to john-users@lists.openwall.com,but where i can see the mail list?thanks!
![2016-03-25-102741_798x393_scrot](https://cloud.githubusercontent.com/assets/4043922/14036511/67d09192-f274-11e5-8647-f981ee3e77e4.png)

**Comment by frank-dittrich** [comment]
@zjhxmjl As an unsubscribed user, your mail has to wait for moderator approval.
Also, make sure to read the documents in the doc directory, so you can ask questions that might be interesting for other users, or questions which indicate our docs need to be improved.
