### ISSUE TITLE
john fails compilation and I can't tell why

### ISSUE THREAD

**Issue by Viss** [magnumripper/JohnTheRipper#2123]
Here's the output of make -s:

> root@host:~/tools/john-git/src# make -s
> ptxas info    : 0 bytes gmem
> ptxas info    : 0 bytes gmem, 21 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z14kernel_crypt_rP18crypt_md5_passwordP15crypt_md5_crack' for 'sm_20'
> ptxas info    : Function properties for _Z14kernel_crypt_rP18crypt_md5_passwordP15crypt_md5_crack
>     64 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 31 registers, 5120 bytes smem, 48 bytes cmem[0], 16 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 12 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z13kernel_phpassPhP12phpass_crack' for 'sm_20'
> ptxas info    : Function properties for _Z13kernel_phpassPhP12phpass_crack
>     32 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 18 registers, 48 bytes cmem[0], 16 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 280 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z14kernel_crypt_rP21crypt_sha256_passwordPj' for 'sm_20'
> ptxas info    : Function properties for _Z14kernel_crypt_rP21crypt_sha256_passwordPj
>     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 62 registers, 7680 bytes smem, 48 bytes cmem[0], 28 bytes cmem[16]
> ptxas info    : Function properties for _Z11sha256cryptPKchPjjj1
>     336 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : 0 bytes gmem, 712 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z14kernel_crypt_rP21crypt_sha512_passwordP17crypt_sha512_hash' for 'sm_20'
> ptxas info    : Function properties for _Z14kernel_crypt_rP21crypt_sha512_passwordP17crypt_sha512_hash
>     8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 63 registers, 5120 bytes smem, 48 bytes cmem[0], 28 bytes cmem[16]
> ptxas info    : Function properties for _Z11sha512cryptPKchPmjj1
>     608 bytes stack frame, 1720 bytes spill stores, 2048 bytes spill loads
> ptxas info    : 0 bytes gmem, 108 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z13pbkdf2_kernelP16mscash2_passwordP12mscash2_hash' for 'sm_20'
> ptxas info    : Function properties for _Z13pbkdf2_kernelP16mscash2_passwordP12mscash2_hash
>     112 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 54 registers, 48 bytes cmem[0], 4 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 288 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z13kernel_sha256P15sha256_passwordP11sha256_hash' for 'sm_20'
> ptxas info    : Function properties for _Z13kernel_sha256P15sha256_passwordP11sha256_hash
>     264 bytes stack frame, 8 bytes spill stores, 8 bytes spill loads
> ptxas info    : Used 63 registers, 48 bytes cmem[0], 24 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 288 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z13kernel_sha256P15sha256_passwordP11sha224_hash' for 'sm_20'
> ptxas info    : Function properties for _Z13kernel_sha256P15sha256_passwordP11sha224_hash
>     264 bytes stack frame, 8 bytes spill stores, 8 bytes spill loads
> ptxas info    : Used 63 registers, 48 bytes cmem[0], 24 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 42 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z13mscash_kernelP15mscash_passwordP11mscash_hash' for 'sm_20'
> ptxas info    : Function properties for _Z13mscash_kernelP15mscash_passwordP11mscash_hash
>     112 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 27 registers, 48 bytes cmem[0], 4 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 664 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z14kernel_cmp_alliPmPh' for 'sm_20'
> ptxas info    : Function properties for _Z14kernel_cmp_alliPmPh
>     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 8 registers, 56 bytes cmem[0]
> ptxas info    : Compiling entry function '_Z14kernel_xsha512iP11xsha512_keyP12xsha512_hashPA110_c' for 'sm_20'
> ptxas info    : Function properties for _Z14kernel_xsha512iP11xsha512_keyP12xsha512_hashPA110_c
>     352 bytes stack frame, 152 bytes spill stores, 152 bytes spill loads
> ptxas info    : Used 63 registers, 64 bytes cmem[0], 20 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 40 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z20wpapsk_pbkdf2_kernelP15wpapsk_passwordP11wpapsk_hash' for 'sm_20'
> ptxas info    : Function properties for _Z20wpapsk_pbkdf2_kernelP15wpapsk_passwordP11wpapsk_hash
>     128 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 63 registers, 48 bytes cmem[0], 4 bytes cmem[16]
> ptxas info    : 0 bytes gmem, 648 bytes cmem[2]
> ptxas info    : Compiling entry function '_Z14kernel_cmp_alliPmPh' for 'sm_20'
> ptxas info    : Function properties for _Z14kernel_cmp_alliPmPh
>     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 8 registers, 56 bytes cmem[0]
> ptxas info    : Compiling entry function '_Z13kernel_sha512P10sha512_keyPA1_m' for 'sm_20'
> ptxas info    : Function properties for _Z13kernel_sha512P10sha512_keyPA1_m
>     352 bytes stack frame, 152 bytes spill stores, 152 bytes spill loads
> ptxas info    : Used 63 registers, 48 bytes cmem[0], 20 bytes cmem[16]
> ptxas info    : 0 bytes gmem
> ptxas info    : Compiling entry function '_Z13kernel_pwsafeP11pwsafe_passP11pwsafe_saltP11pwsafe_hash' for 'sm_20'
> ptxas info    : Function properties for _Z13kernel_pwsafeP11pwsafe_passP11pwsafe_saltP11pwsafe_hash
>     64 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> ptxas info    : Used 34 registers, 56 bytes cmem[0], 24 bytes cmem[16]
> ar: creating aes.a
> cuda_cryptmd5.o:(.eh_frame+0xdb): undefined reference to `__gxx_personality_v0'
> cuda_phpass.o:(.eh_frame+0x6b): undefined reference to `__gxx_personality_v0'
> cuda_mscash2.o:(.eh_frame+0x11f): undefined reference to `__gxx_personality_v0'
> cuda_rawsha256.o:(.eh_frame+0x8b): undefined reference to `__gxx_personality_v0'
> cuda_rawsha224.o:(.eh_frame+0x8b): undefined reference to `__gxx_personality_v0'
> cuda_mscash.o:(.eh_frame+0xbf): more undefined references to `__gxx_personality_v0' follow
> cuda_wpapsk.o: In function `wpapsk_postprocess(int)':
> tmpxft_00007371_00000000-4_wpapsk.cudafe1.cpp:(.text+0x82a): undefined reference to `prf_512(unsigned int*, unsigned char*, unsigned int*)'
> tmpxft_00007371_00000000-4_wpapsk.cudafe1.cpp:(.text+0x8d6): undefined reference to `prf_512(unsigned int*, unsigned char*, unsigned int*)'
> cuda_wpapsk.o:(.eh_frame+0x3bf): undefined reference to `__gxx_personality_v0'
> cuda_pwsafe.o:(.eh_frame+0x6b): undefined reference to `__gxx_personality_v0'
> collect2: error: ld returned 1 exit status
> Makefile:1390: recipe for target '../run/john' failed
> make[1]: *** [../run/john] Error 1
> Makefile:187: recipe for target 'default' failed
> make: *** [default] Error 2

I googled around for that last error message with pwsafe and it said something about g++ - I tried to see if the working amazon ec2 ami (where this compiled and ran just fine) had the same packages, and I've done that - the machine with the problem and the ec2 instances have the same packages installed - Im not sure where to go from here..

**Comment by claudioandre** [comment]
I googled and it seems your environment is, somehow, damaged. I guess you won't get a better response here. So:
- check if your environment seems ok;
- use only the latest JtR from github.
- check if you did a make clean / distclean;
- disable things on ./configure to identify a culprit (e.g., I saw only cuda related errors in your post).
- AND building using root? Why?

BTW: since this is not an error or JtR bug, here is not the best place to ask for advice. Moreover, on a mailing list you might find someone who solved the same problem.

**Comment by Viss** [comment]
Right, I googled first before asking here, and the reason I asked here was because, as the experts are here, I presumed some contributor would help me get to the bottom of the error.

Telling me to go away isn't really helpful.

**Comment by solardiz** [comment]
Viss, a more appropriate place for issues such as yours is the john-users mailing list, not GitHub issues, since chances are that it's a system issue rather than a JtR code revision issue.

That said, here's what I know about build failures such as yours:

1. Recent CUDA requires recent gcc. You appear to have too-recent CUDA for your gcc. For example, it is not possible to build with CUDA 7.5 on RHEL6.x (and clones) with that distros' default gcc/g++ (but is possible with Red Hat's devtoolkit-3 for RHEL6).

2. You really shouldn't want to be building the CUDA stuff at all. For us, it's mostly deprecated, in favor of OpenCL, and recent ./configure (in bleeding-jumbo) disables it by default (whenever OpenCL is available). So please just fetch latest bleeding-jumbo and don't override its ./configure settings, to let it keep CUDA disabled. Alternatively, if you're building 1.8.0-jumbo-1 (I think you never said which version you're building?), then you need explicit --disable-cuda, but it's much better to build bleeding-jumbo instead.

I hope this helps.

**Comment by Viss** [comment]
--enable-opencl vs --enable-cuda solved it!
Thanks, Solar! \o/
