### ISSUE TITLE
Possible to crack salted-sha512?

### ISSUE THREAD

**Issue by kost123** [magnumripper/JohnTheRipper#2125]
if not can it be implemented?

Sha512($password.$salt)

**Comment by jfoug** [comment]
simply type this command line switch:

--dynamic='sha512($p.$s)'

then the input needs to be 

hash_in_hex$salt

**Comment by kost123** [comment]
like this?

3032613338326161623232646163353939
3364386165636336356231383836316632
3630343965653838613531663631626365
6431633036353038623639666637313364
3763376465666565323364663637613532
6339336664323131636631616661326637
6630653163656231346666613636343933
313136633036333930:io9i43j90tj4

I just used a ascii to hex converter?

**Comment by jfoug** [comment]
That would ALL have to be on 1 line.  That is as long as the io9i43j90tj4 is the salt.  Also, instead of a : char you will need to use a $ char to separate the hash from the salt.  This is the line you will need:

3032613338326161623232646163353939336438616563633635623138383631663236303439656538386135316636316263656431633036353038623639666637313364376337646566656532336466363761353263393366643231316366316166613266376630653163656231346666613636343933313136633036333930$io9i43j90tj4

This woul

**Comment by jfoug** [comment]
It looks like you did a hex encoding of an already hex encoded string.  The string you have is 2x as long as it should be, and it only has 30 .. 39 and 61 to 66 hex digits in it.

The 'real' hex encoding of the binary data is:

```
02a382aab22dac5993d8aecc65b18861f26049ee88a51f61bced1c06508b69ff713d7c7defee23df67a52c93fd211cf1afa2f7f0e1ceb14ffa66493116c06390
```

**Comment by jfoug** [comment]
NOTE, this mail list, and issues database is not for how to use john, it is for bugs.  Not knowing how to use john is not a bug.   This discussion should be taken to the john-users email list.

**Comment by jfoug** [comment]
I see you also posted this same issue to the hashcat github.

To me, it appears that you simply need to read the documentation for both tools. This is a simple hash, and readily crackable by both tools, and certainly NOT a bug in either.

**Comment by kost123** [comment]
Not the same issue on hashcat, also, I didn't know if it was implemented so that's why I asked, My bad anyway.

**Comment by jfoug** [comment]
I think there may also be a 'fat' salted sha512 format (not 100% sure).  I do know that with dynamic, getting hashes like this where there is no 'real' format is pretty easy to do now.  With the new on-commandline dynamic, you do not even need to write a script any more.

**Comment by kost123** [comment]
I was just going to try that 128char salt on JTR.. see if it works, thanks for your help anyway/sorry.

**Comment by kost123** [comment]
```
kali:~/src/john/src$ ../run/john --wordlist=pass.txt hash.txt --dynamic='sha512($p.$s)' 
Unknown option: "--dynamic=sha512($p.$s)"
```

**Comment by jfoug** [comment]
-format='dynamic=sha512($p.$s)'

I typed the wrong instruction before.

**Comment by kost123** [comment]
Yea, I found it in your other posts :D thanks

**Comment by kost123** [comment]
No password hashes loaded (see FAQ)

Works with shorter salt but not longer, my problems continue :(

Don't even know where to start looking for this fat sha512 hash..

**Comment by jfoug** [comment]
-format='dynamic=sha512($p,$s),saltlen=128'

NOTE, you can not push saltlen too high.There is a 256 byte max length of buffer no matter what in the dynamic. That is for ALL usages of buffers.  So passwords count against this length in this format.

**Comment by jfoug** [comment]
there is a document that describes the '@dynamic=xxx@ format.  Give it a read.  All that I am typing is listed in there.

**Comment by kost123** [comment]
omg it worked :D I love you man.. thanks for helping me.

**Comment by kost123** [comment]
Is there a command to make it use the GPU?

**Comment by jfoug** [comment]
Nope, dynamic does not use GPU.
