### ISSUE TITLE
--max-run-reset-on-crack bloat option

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2139]
Here's an idea I got. I'm just documenting it for now, I'm not sure I want more bloat.

A typical incremental (or prince) run cracks a lot early but the crack rate decreases over time. We could add a --max-run-reset-on-crack option that optionally tweaks the --max-run-time=SECONDS option. Example use:
```
./john hashfile -inc -max-run=3600 -max-run-reset-on-crack
```
This will stop the run one hour *after last cracked password*. As long as at least one password is cracked per hour, it will never stop.

**Comment by jfoug** [comment]
This is how we should have done this in the first place.  Using a 2nd argument to get it done is fine, as that keeps the legacy 'KISS' mode of wall clock time.  This proposed mode is MUCH better than the current mode.

There are still times where some of these modes go 'stale' for a while, and then pick back up.  If the user is smart enough to be able to wait through these stale times, and then pick up the later hot spots, then all the better.  BUT at some point, these modes do dry up to the point that other methods end up getting better results.

**Comment by magnumripper** [comment]
I wouldn't say it's better. Sometimes you want the old way, sometimes the new option. I will try to implement it ASAP.

**Comment by magnumripper** [comment]
Done, works like a champ.

**Comment by magnumripper** [comment]
Change syntax (see https://github.com/magnumripper/JohnTheRipper/commit/0528d1b6db0c96f778af3eca0f622608801b6f01#commitcomment-17683657) so now there's no second option. `--max-run-time=60` will abort unconditionally after 60 seconds just like before, while a negative number like `--max-run-time=-60` will abort only after nothing was cracked in 60 seconds.

**Comment by jfoug** [comment]
Glad it was not much more in code or complexity.  But it should keep the UI (and internal flags) simpler.

I am glad solar spoke up on this one. Even though it makes the -max-run-time option a little more complex, I think it is less complex (to a user), than 2 cooperating switches, AND it should be 100% backward compatible (since only the positive were valid before).

Good stuff, and something I had wanted, but never looked into.
