### ISSUE TITLE
[bleeding-jumbo] i686 compile errors using automake and >= sse4 (sse4, avx, xop...) in gost3411-2012-sse41_plug.c

### ISSUE THREAD

**Issue by anthraxx** [magnumripper/JohnTheRipper#2146]
Hi, I'm a packager and want to provide a package that uses the CPU fallbacks, therefor I want to compile john for various instruction sets (generic, mmx, sse2, avx, xop).
For x86_64 everything works fine but if I try to compile for i686 then I get compile errors when the sse4 instruction sets are used (f.e. for the avx and xop builds).
Note 1: For testing reasons I have disabled openmp because it brings up some different kind of problems, will open a separate bug ticket for that.
Note 2: This only happens with bleeding-jumbo, the jumbo1 release works in this constellation 
Note 3: This only happens with the automake build env, using the Makefile.legacy still works
Note 4: gcc (GCC) 6.1.1 20160501
Note 5: The i686 build is done inside a 32bit chroot for packaging, therefor no -m32 is required
    
    ./configure --prefix=/usr --disable-native-tests CFLAGS="-mavx" CPPFLAGS="-mavx" --host=i686 --disable-openmp && make clean && make -j12
    [...]
    In file included from gost3411-2012-sse41_plug.c:5:0:
    gost3411-2012-sse41_plug.c: In function ‘my__mm_insert_epi64’:
    gost3411-2012-sse41_plug.c:25:6: error: selector must be an integer constant in the range 0..3
      a = _mm_insert_epi32(a, (unsigned int)b, c);
          ^
    gost3411-2012-sse41_plug.c:26:9: error: selector must be an integer constant in the range 0..3
      return _mm_insert_epi32(a, (unsigned int)(b >> 32), c + 1);
             ^

however when running with legacy:
    
    make -f Makefile.legacy linux-x86-avx
    [...]
    All done
    
and running automake with SSE2 (which dies not pull in the SSE4.1 stuff):
    
    ./configure --prefix=/usr --disable-native-tests CFLAGS="-msse2" CPPFLAGS="-msse2" --host=i686 --disable-openmp && make clean && make -j12
    [...]
    Make process completed.
    

I have checked the used instructions via objdump and it indeed uses AVX instructions.

PS: maybe this could be solved before jumbo2 ? :smile_cat:

**Comment by magnumripper** [comment]
Was this solved by using setarch? Please close if so.

**Comment by anthraxx** [comment]
no, this still happens with latest bleeding jumbo and >= sse4

**Comment by magnumripper** [comment]
```c
#if ARCH_BITS == 32
(...)
#undef _mm_insert_epi64
#define _mm_insert_epi64 my__mm_insert_epi64

static inline __m128i _mm_insert_epi64(__m128i a, uint64_t b, int c) {
	c <<= 1;
	a = _mm_insert_epi32(a, (unsigned int)b, c);
	return _mm_insert_epi32(a, (unsigned int)(b >> 32), c + 1);
}
#endif
```
Apparently I wrote this although I can't remember I did 😎. I believe this code depends on the compiler optimizing away `c` and `c + 1` replacing it with constants. And for some reason your compiler doesn't.

I think I see why: You use `CFLAGS=-mavx` and I believe that will mean the default CFLAGS of `-O2 -g` is lost. Right? Maybe `CFLAGS="-O2 -mavx"` would not only solve your problem (although this code should ideally be fixed too) but also make for a much faster build with some/many of the formats.

**Comment by magnumripper** [comment]
configure actually warned you about the situation:
```
configure: WARNING: No recognized optimization option present in CFLAGS

Configured for building John the Ripper jumbo:

Target CPU ................................. i686 AVX, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. none
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h
(...)
```

**Comment by anthraxx** [comment]
@magnumripper you were right, with -O2 this works so not a real issue here.

No worries, this was just a manual test invocation and for such I prefer not passing my default package building flags to minimize possible influence. I already found some bugs related to having O2 or O3 in other software, that's why my first manual pass (before using default buildchain) just strips as much as possible.... well in this case it was the other way around :smile_cat:

In fact i still use CFLAGS as the packaging toolchain automatically injects SSP, RELRO, O2 and other options.

thx for taking your time, I close this as non-issue

**Comment by magnumripper** [comment]
Cool, thanks. I opened #2156 for fixing the code anyway but I regard it pretty low priority.

**Comment by jfoug** [comment]
> Apparently I wrote this although I can't remember I did :sunglasses:. 

I think I wrote that and you checked it in.  Was needed for VC or something (possibly cygwin 32 bit).
