### ISSUE TITLE
[bleeding-jumbo] [jumbo1] i686 compile errors using automake with --enable-openmp in c3_fmt.c

### ISSUE THREAD

**Issue by anthraxx** [magnumripper/JohnTheRipper#2147]
Hi, I'm a packager and want to provide a i686 version of this package that uses openmp.
For x86_64 everything works fine in every constellation but if I try to compile for i686 then I get compile errors when enabling openmp via --enable-openmp.
Note 1: This happens with both, bleeding-jumbo and jumbo1.
Note 2: This happens always, no matter if sse2, avx or --enable-native-tests
Note 3: gcc (GCC) 6.1.1 20160501
    
     ./configure --prefix=/usr --disable-native-tests CFLAGS="-msse2" CPPFLAGS="-msse2"  --host=i686 --enable-openmp && make clean && make -j12
    [...]
    gcc -DAC_BUILT -msse2 -DJOHN_SSE2 -c -msse2 -I/usr/local/include -DARCH_LITTLE_ENDIAN=1 -DJOHN_SYSTEMWIDE -DJOHN_SYSTEMWIDE_EXEC='"/usr/bin"' -DJOHN_SYSTEMWIDE_HOME='"/usr/share/john"'   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations  -Wunused-but-set-variable -std=gnu89 -Wdate-time    -fopenmp  -pthread   -msse2 -I/usr/local/include -funroll-loops c3_fmt.c -o c3_fmt.o
    c3_fmt.c: In function ‘init’:
    c3_fmt.c:133:21: error: storage size of ‘data’ isn’t known
       struct crypt_data data;
                         ^~~~
    c3_fmt.c:227:8: warning: implicit declaration of function ‘crypt_r’ [-Wimplicit-function-declaration]
        c = crypt_r(tests[i].plaintext, salt, &data);
            ^~~~~~~
    c3_fmt.c:133:21: warning: unused variable ‘data’ [-Wunused-variable]
       struct crypt_data data;
                         ^~~~
    In file included from common.h:20:0,
                     from getopt.h:18,
                     from options.h:26,
                     from c3_fmt.c:76:
    c3_fmt.c: In function ‘valid’:
    c3_fmt.c:322:34: error: dereferencing pointer to incomplete type ‘struct crypt_data’
        *data = mem_alloc_tiny(sizeof(**data), MEM_ALIGN_PAGE);
                                      ^~~
    memory.h:107:49: note: in definition of macro ‘mem_alloc_tiny’
     #define mem_alloc_tiny(a,b) mem_alloc_tiny_func(a,b)
                                                     ^
    c3_fmt.c:325:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
       new_ciphertext = crypt_r(pw, ciphertext, *data);
                      ^
    c3_fmt.c: In function ‘crypt_all’:
    c3_fmt.c:563:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
        hash = crypt_r(saved_key[index], saved_salt, *data);
             ^
    c3_fmt.c:565:22: error: storage size of ‘data’ isn’t known
        struct crypt_data data;
                          ^~~~
    c3_fmt.c:565:22: warning: unused variable ‘data’ [-Wunused-variable]
    Makefile:1565: recipe for target 'c3_fmt.o' failed

**Comment by solardiz** [comment]
> ./configure --prefix=/usr --disable-native-tests CFLAGS="-msse2" CPPFLAGS="-msse2"  --host=i686 --enable-openmp && make clean && make -j12

With this line, you're not actually telling your compiler to produce 32-bit code. If you're on an x86_64 system, you need to have -m32 in CFLAGS. Without that, it is no surprise that the build will either fail or (worse) succeed yet be incorrect. Are you able to reproduce the issue with -m32 added?

Also, your CFLAGS are missing -O2 - I hope you did this to minimize your issue report only?

magnum - maybe we should have -m32 implied when --host=i686 (or other i.86) is specified?

**Comment by solardiz** [comment]
OK, jumbo's c3_fmt.c certainly looks like it has introduced a bug like this relative to core. In core, the `#define _XOPEN_SOURCE` ... `#define _GNU_SOURCE` lines are before the very first #include. In jumbo, they are after `#include <string.h>` or/and `#include <strings.h>`. This is wrong: the feature macros must be defined before the very first libc header is included. magnum, please correct this.

What I said about -m32 and -O2 also applies, but is likely not the issue seen here. (Omitting these may result in a broken or at best inefficient build.)

**Comment by anthraxx** [comment]
@solardiz I don't need to, its inside a 32bit chroot for building i686 packages, I just need to pass --host=i686 because it detects a x86_64 env, however everything inside that chroot is just i686 :smile:

**Comment by solardiz** [comment]
Oh, OK. You didn't specify it was 32-bit chroot. That's what I would have recommended for packaging anyway. So it's good.

You're right regarding  --host=i686. Alternatively, you can use "setarch i686", if you have setarch,. which changes the personality for the process sub-tree, so that uname will return i686 instead of x86_64.

As I already confirmed, the bug in jumbo's c3_fmt.c is for real - we need to fix it, then retest. We were unlucky it worked at all (on x86_64) - as written, it doesn't have to work anywhere at all (but it might).

FWIW, I just happened to find (before I read your last comment) how we were test-building for 32-bit on x86-64 without a 32-bit chroot: http://www.openwall.com/lists/john-dev/2015/08/19/15

**Comment by anthraxx** [comment]
@solardiz ``setarch`` is available, will use that instead... neat idea!

thank you very much for looking into this and finding the root of the problem :smile_cat:

**Comment by magnumripper** [comment]
See also #2146

**Comment by anthraxx** [comment]
@magnumripper any ETA? No rush, I'm just curious as this issue currently holds back the package update for Arch Linux

**Comment by magnumripper** [comment]
I haven't had any time to look at this. @solardiz what is the bug exactly? Is it trivial?

**Comment by solardiz** [comment]
The bug is that jumbo's modified c3_fmt.c wrongly defines some feature macros only after some of the #include's. All feature macros must be defined before the very first #include (of anything from other than the program itself). Yes, this is trivial to fix - move all of the feature macro #define's to be before all of the #include's. See how it's done in core's c3_fmt.c - the file starts with "#define _XOPEN_SOURCE 4" and so on right after the initial comment and before the very first #include.

**Comment by magnumripper** [comment]
I see. Looks like @jfoug did that on purpose in 70d2140a. Maybe we should just revert that commit.

**Comment by magnumripper** [comment]
@anthraxx can you try reverting 70d2140a and rebuild? Does it solve your problem?

**Comment by solardiz** [comment]
Commit 70d2140a is obviously wrong and must be reverted. The proper fix to the issue @jfoug mentioned in the comment in that commit would be to identify what feature macros MSVC (or whatever it was) needs to declare the required functions. There got to be a common set of feature macros that does what we need for all compilers/libc's, unless some are buggy in this respect. For example, maybe we need to define _XOPEN_SOURCE to a value higher than 4. As a last resort, we can put the #define's inside an #ifndef _MSC_VER ... #endif block or such.

**Comment by magnumripper** [comment]
Done. @anthraxx please test latest commit.

**Comment by anthraxx** [comment]
so far, the first manual run looks good. Let me invoke my packaging script chain building all instruction sets and then i will close this issue. thank you very much!

**Comment by anthraxx** [comment]
:+1:
