### ISSUE TITLE
dmg2john's dmg file header parsing bugs

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2151]
http://www.openwall.com/lists/john-dev/2016/06/10/1

@magnumripper @solardiz  dmg2john.py has fallen behind dmg2john.c in terms of development for a while now. Should we simply drop it?

I don't have a OS X system to experiment with this.

**Comment by solardiz** [comment]
On Tue, Jun 14, 2016 at 10:24:12PM -0700, Dhiru Kholia wrote:
> dmg2john.py has fallen behind dmg2john.c in terms of development for a while now. Should we simply drop it?

No, it continues to serve a useful purpose, and we should keep it. Fixing the 48 vs. 64 issue for v2 headers should be easy.

**Comment by kholia** [comment]
@solardiz 

I had a look at the DMG format and it seems that only the first 32 bytes of `encrypted_keyblob` matter. So the `48s` vs `64s` issue in `dmg2john.py` is not be a problem at all.

`https://github.com/kholia/VileFault/blob/master/tests/testimage.AES-256.64k.header_v2.dmg` has `encrypted_keyblob_size` set to 64 and JtR jumbo cracks it just fine. In fact, it is the first test vector in `dmg_fmt_plug.py`.

This said, I like the idea of changing `48s` to `64s` and truncating the output `encrypted_keyblob` value if required. This should not cause any problems. I will also add an output line recommending users to use `dmg2john` instead of `dmg2john.c`.

**Comment by kholia** [comment]
This can be closed now.
