### ISSUE TITLE
Dynamic ad-hoc format sha512(sha512($p).sha512($s)) failing self-tests

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#2152]
```
$ ./JohnTheRipper/run/john '--format=dynamic=sha512(sha512($p).sha512($s))' --test=1
Benchmarking: dynamic=sha512(sha512($p).sha512($s)) [128/128 SSE4.1 2x]... FAILED (cmp_all(1))
```
and similarly for `sha512(sha512($p).sha512($p))`

I think it is not the same as issue #1746 because similar formula with
sha256 works well. Test vectors are ok (a format produced by john-devkit
passes them).

**Comment by jfoug** [comment]
This can NOT be done on SIMD code.  I have only 256 byte buffers, and you need 256 byte buffer BEFORE the 0x80 byte, and the length. Doing this for SIMD would require 384 byte buffers.

The compiler will NOT be smart enough (at this time) to know that this must be done in non SIMD code.

**Comment by solardiz** [comment]
On Wed, Jun 15, 2016 at 12:11:37PM -0700, jfoug wrote:
> This can NOT be done on SIMD code.  I have only 256 byte buffers, and you need 256 byte buffer BEFORE the 0x80 byte, and the length. Doing this for SIMD would require 384 byte buffers.
> 
> The compiler will NOT be smart enough (at this time) to know that this must be done in non SIMD code.

Why not? Is it hard to detect maximum buffer space use? Even if it's somehow difficult to infer that at ad-hoc dynamic mode compile-time, surely you can detect it at runtime (such as by prefilling the buffer and seeing if your last filler byte got overwritten or not) and fallback to recompiling for non-SIMD then? As a last resort, maybe you can have it automatically recompile for non-SIMD whenever self-test fails for the SIMD compile. Just thought I'd suggest these options.

**Comment by jfoug** [comment]
I have no logic at all in the dynamic to handle non-simd.  It could be added, but it has NOT been on my priority list.

**Comment by solardiz** [comment]
On Wed, Jun 15, 2016 at 12:11:37PM -0700, jfoug wrote:
> I have only 256 byte buffers

Can the buffer sizes possibly be increased, or is there a reason why they're exactly 256 bytes for the SIMD code?

**Comment by jfoug** [comment]
The 'flat' buffer SIMD code uses the original non-SIMD buffers. There is SOOOO  much involved in increasing those buffers, and I have tried in the past and given up after about 40 hours of work.

That is '4' normal 64 byte buffers.  If it 'could' be increased, it will slow down many other operations all across dynamic (significantly).  256 was pushing it, but in the end was the limit, and did not seem to cause too much performance issues, even on normal 1 buffer work (for either 64 or 128 byte buffers).

**Comment by jfoug** [comment]
ALL code in the dyna compiler uses the 'flat' SIMD code, since it has a very simple interface.  It is notably slower for 1 buffer simple salt or non-salt MD4/5 and a bit slower for sha1.  But for the larger formats, the speed of the flat buffers was not much worse.  Also for 'complex' hashes (multiple calls, mixed salts, etc), the flat buffers can actually be faster, since the overhead of CPU doing the shuffling , and buffer cleaning takes more overhead/time than writing to a flat buffer and having the SIMD code (for 4.1+) do the shuffling work.

Again, this (all of this),. IS things which can  be put into this code.  But at this time it is not there.

**Comment by magnumripper** [comment]
Given it's not supported it should ideally bail out a little more elegantly than just failing self-test. But the dynamic compiler is a powerful but raw feature so I'm happy as long as it doesn't *pass* self-tests and then chugs along with false negatives.

**Comment by jfoug** [comment]
This is one of the main reasons I have not started to work on some of these. The ST fails, which does keep it from 'appearing' to work, while it is actually never doing anything productive.

The code that generates the ST string will work pretty much no matter what.  So those hashes are correct.  I use a recursive decent parser to parse the expressions, using ossl code with unbounded buffers.  So really horrible things that will never work in the dynamic code (let alone the dynamic 'compiler') will generate proper test strings, and thus the compiler will fail the ST.

Things like   sha512(sha512($p).sha512($s.$p).sha512($s.$p.$s).sha512($p.$s.$p).$p.sha512($p.$p).$s.sha512($p.$p.$s.$p). .....)  Will simply never be handled. There simply would need to be too many memory 'variables' for a function like that to be handled 'generically' within dynamic.  BUT the compiler test string generation code will produce 100% proper ST strings.  The ST generation code is simply a port from the expression engine I have in pass_gen.pl  It can handle expressions like that just fine.  But it is well beyond capabilities that even a hand coded dynamic script ever will be made to handle.

**Comment by AlekseyCherepanov** [comment]
Dynamics are impressive! Correct ST are great!

"Too many memory variables" would be real if all dyna functions were
redesigned to accept buffers as arguments. Buffers might be numbered:
`Func=DynamicFunc__crypt_md5_in2_to_out1` would be `Func=md5,1,2` or
`Func=1,md5,2` or even `Func=$1=md5($2)`.

Also explicitly separate sequences of 'Func's for each password, salt
and crypt() might be helpful.
