### ISSUE TITLE
uaf_encode.c: 56: 12: warning: missing whitespace after the macro name [enabled by default]

### ISSUE THREAD

**Issue by huanghemengxi** [magnumripper/JohnTheRipper#2154]
Hello everyone, I am being given when compiling JohnTheRipper-bleeding-jumbo version of the program, delete the makefile among uaf_ * After the compiler, would like to ask, what's missing is the installation package it?
Error prompt:
uaf_encode.c: 56: 12: warning: missing whitespace after the macro name [enabled by default]
uaf_encode.c: 57: 12: warning: missing whitespace after the macro name [enabled by default]
uaf_encode.c: 57: 0: warning: "UAI" redefined [enabled by default]
uaf_encode.c: 56: 0: note: this is the location of the previous definition
uaf_encode.c: 58: 12: warning: missing whitespace after the macro name [enabled by default]
uaf_encode.c: 58: 0: warning: "UAI" redefined [enabled by default]
uaf_encode.c: 57: 0: note: this is the location of the previous definition
uaf_encode.c: 59: 12: warning: missing whitespace after the macro name [enabled by default]
uaf_encode.c: 59: 0: warning: "UAI" redefined [enabled by default]
uaf_encode.c: 58: 0: note: this is the location of the previous definition
Environment configuration is as follows:
Operating systems: AIX Version 5.2
make version: GNU Make 3.81
gcc version: gcc version 4.6.1 (GCC)

**Comment by magnumripper** [comment]
This might be tricky to fix, you may need to disable UAF/VMS completely.

http://stackoverflow.com/questions/369495/what-are-the-valid-characters-for-macro-names

But you are using gcc so it *should* work... what is the exact output of `make uaf_encode.o`?

**Comment by magnumripper** [comment]
Not that tricky. Should be fixed now, please test.
