### ISSUE TITLE
regression: CUDA compile broken

### ISSUE THREAD

**Issue by kc9jud** [magnumripper/JohnTheRipper#2157]
The change at https://github.com/magnumripper/JohnTheRipper/commit/e78d6efcefd061d2a28030834b7779d5ff05d7e7#diff-e518fe747aeefd5de719aa0ff51b8647R262 breaks https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/cuda/cuda_common.cu#L176 as the number of arguments has changed.

**Comment by magnumripper** [comment]
Thanks for reporting, fixed now
