### ISSUE TITLE
win32 cygwin build

### ISSUE THREAD

**Issue by richrumble** [magnumripper/JohnTheRipper#2158]
Configured for building John the Ripper jumbo:

Target CPU ................................. x86_64 AVX2, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h

Optional libraries/features found:
Fuzzing test ............................... no
Experimental code .......................... no
OpenMPI support (default disabled) ......... yes
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
CUDA support (default disabled by OpenCL) .. no
OpenCL support ............................. no
Generic crypt(3) format .................... no
Rexgen (extra cracking mode) ............... no
GMP (PRINCE mode and faster SRP formats) ... yes
PCAP (vncpcap2john and SIPdump) ............ no
Z (pkzip format, gpg2john) ................. yes
BZ2 (gpg2john extra decompression logic) ... yes
128-bit integer (faster PRINCE mode) ....... yes
Memory map (share/page large files) ........ yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ........... disabled
AddressSanitizer ("ASan") .................. disabled
UndefinedBehaviorSanitizer ("UbSan") ....... disabled

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now 'make clean && make -s' to compile.

$ make clean
rm -f ../run/john.exe ../run/unshadow.exe ../run/unafs.exe ../run/unique.exe ../run/undrop.exe ../run/rar2john.exe ../run/zip2john.exe ../run/genmkvpwd.exe ../run/mkvcalcproba.exe ../run/calc_stat.exe ../run/tgtsnarf.exe ../run/racf2john.exe ../run/hccap2john.exe ../run/raw2dyna.exe ../run/keepass2john.exe ../run/dmg2john.exe ../run/putty2john.exe ../run/uaf2john.exe ../run/wpapcap2john.exe ../run/gpg2john.exe ../run/cprepair.exe ../run/base64conv.exe ../run/pfx2john.exe ../run/ssh2john.exe
rm -f john-macosx-* *.o escrypt/*.o *.bak core
rm -f ../run/kernels/*
rm -f detect bench generic.h tmp.s
rm -f cuda/*.o cuda/*~ *~
cp /dev/null Makefile.dep
make: *** [Makefile:1624: clean] Error 127

$ make -j4
make find_version
make[1]: Entering directory '/cygdrive/c/temp/john/JohnTheRipper/src'
/usr/bin/mkdir -p ../run/kernels
cp opencl_device_info.h ../run/kernels
cp opencl_DES_hst_dev_shared.h ../run/kernels
cp opencl_nonstd.h ../run/kernels
make[1]: *** [Makefile:873: ../run/kernels/opencl_device_info.h] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:873: ../run/kernels/opencl_DES_hst_dev_shared.h] Error 127
make[1]: *** [Makefile:873: ../run/kernels/opencl_nonstd.h] Error 127
make[1]: Leaving directory '/cygdrive/c/temp/john/JohnTheRipper/src'
make: *** [Makefile:187: default] Error 2

**Comment by magnumripper** [comment]
It's just a plain copy eg. `cp ../run/kernels/opencl_device_info.h ../run/kernels`. So what is Error 127 in Cygwin?

**Comment by magnumripper** [comment]
Ah, I guess ../run/kernels doesn't exist because `make clean` failed
```
(...)
	$(CP) $(NULL) Makefile.dep
	@for dir in ${subdirs}; do \
	  (cd $$dir && $(MAKE) clean) \
	  || case "$(MFLAGS)" in *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
```

**Comment by richrumble** [comment]
And I'm not building GPU... so I should need no kernels, me thinks

**Comment by jfoug** [comment]
Why are you using cygwin32 to build 64 bit binary????  Use cygwin64

**Comment by jfoug** [comment]
here is my 32 bit build:

```
Configured for building John the Ripper jumbo:

Target CPU ................................. i686 AVX, 32-bit LE
AES-NI support ............................. run-time detection
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h

Optional libraries/features found:
Fuzzing test ............................... no
Experimental code .......................... no
OpenMPI support (default disabled) ......... no
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
CUDA support (default disabled by OpenCL) .. no
OpenCL support ............................. yes
Generic crypt(3) format .................... yes
Rexgen (extra cracking mode) ............... yes
GMP (PRINCE mode and faster SRP formats) ... yes
PCAP (vncpcap2john and SIPdump) ............ yes
Z (pkzip format, gpg2john) ................. yes
BZ2 (gpg2john extra decompression logic) ... yes
128-bit integer (faster PRINCE mode) ....... no
Memory map (share/page large files) ........ yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ........... disabled
AddressSanitizer ("ASan") .................. disabled
UndefinedBehaviorSanitizer ("UbSan") ....... disabled

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now 'make clean && make -s' to compile.


$ make -sj8
ar: creating aes.a
common-gpu.c: In function ‘amd_probe’:
common-gpu.c:199:37: warning: passing argument 1 of ‘ADL_Main_Control_Create’ from incompatible pointer type
  if ((ret = ADL_Main_Control_Create(ADL_Main_Memory_Alloc, 1)) != ADL_OK)
                                     ^
common-gpu.c:199:37: note: expected ‘ADL_MAIN_MALLOC_CALLBACK’ but argument is of type ‘void * (*)(int)’
common-gpu.c: In function ‘get_temp_od5’:
common-gpu.c:309:30: warning: passing argument 1 of ‘ADL_Main_Control_Create’ from incompatible pointer type
  if (ADL_Main_Control_Create(ADL_Main_Memory_Alloc, 1) != ADL_OK)
                              ^
common-gpu.c:309:30: note: expected ‘ADL_MAIN_MALLOC_CALLBACK’ but argument is of type ‘void * (*)(int)’
common-gpu.c: In function ‘get_temp_od6’:
common-gpu.c:372:30: warning: passing argument 1 of ‘ADL_Main_Control_Create’ from incompatible pointer type
  if (ADL_Main_Control_Create(ADL_Main_Memory_Alloc, 1) != ADL_OK)
                              ^
common-gpu.c:372:30: note: expected ‘ADL_MAIN_MALLOC_CALLBACK’ but argument is of type ‘void * (*)(int)’
pp.c: In function ‘do_prince_crack’:
pp.c:1504:22: warning: implicit declaration of function ‘fileno’ [-Wimplicit-function-declaration]
                      fileno(read_fp), 0);
                      ^

Make process completed.

```

**Comment by jfoug** [comment]
Here is my cygwin64 build  (again, works just fine for me).

NOTE, I do not use openmpi.  Use that at your own risk.  Cygwin IS cygwin.  It is far from unix.  I also have opencl installed (on the windows side), and simply have made symlinks and path settings back into the windows directory structure so that cygwin can find/build and use the libs.


```
make -s clean && ./configure -C && make -sj8   
....
Configured for building John the Ripper jumbo:

Target CPU ................................. x86_64 AVX, 64-bit LE
AES-NI support ............................. run-time detection
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h

Optional libraries/features found:
Fuzzing test ............................... no
Experimental code .......................... no
OpenMPI support (default disabled) ......... no
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
CUDA support (default disabled by OpenCL) .. no
OpenCL support ............................. yes
Generic crypt(3) format .................... yes
Rexgen (extra cracking mode) ............... yes
GMP (PRINCE mode and faster SRP formats) ... yes
PCAP (vncpcap2john and SIPdump) ............ yes
Z (pkzip format, gpg2john) ................. yes
BZ2 (gpg2john extra decompression logic) ... yes
128-bit integer (faster PRINCE mode) ....... yes
Memory map (share/page large files) ........ yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ........... disabled
AddressSanitizer ("ASan") .................. disabled
UndefinedBehaviorSanitizer ("UbSan") ....... disabled

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now 'make clean && make -s' to compile.


rulez.c: In function ‘release’:
rulez.c:124:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  word_item *pi = *((word_item**)pl->data);
  ^
rulez.c: In function ‘rulez_single’:
rulez.c:225:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    pWord = *((word_item**)current->data);
    ^
pp.c: In function ‘do_prince_crack’:
pp.c:1504:22: warning: implicit declaration of function ‘fileno’ [-Wimplicit-function-declaration]
                      fileno(read_fp), 0);
                      ^
ar: creating aes.a

Make process completed.

```

Note, rulez.c is my own unreleased code, ignore the warnings there.

**Comment by jfoug** [comment]
Rich,

Please explain exactly what you are doing?  What cygwin you are using, and how you are expecting to build.  I see no problems at all.

**Comment by richrumble** [comment]
My steps are outlined in the initial issue, ./configure --enable-mpi, make
clean, make -j4
I've also tried on 32bit, which worked no problem. I can't say what I'm
doing different with the 64_bit build... it's windows 10 is the only
difference other than cygwin bit'ness. Otherwise I install the same
libraries as usual, OpenSSL, Krb5, OpenMpi, GMP, zlib's, and whatever those
depend on naturally.
I'll start over on the cygwin_64, on a new machine and see if that does the
trick.
Current version is:
uname -a
CYGWIN_NT-10.0 PC_NAME 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64 Cygwin

**Comment by jfoug** [comment]
Here is the version(s) I am using

CYGWIN_NT-6.1 1PQHGQ1 2.4.1(0.293/5/3) 2016-01-24 11:26 x86_64 Cygwin    (win 7pro box)

CYGWIN_NT-10.0 mom_laptop 2.4.1(0.293/5/3) 2016-01-24 11:26 x86_64 Cygwin  (win10 box)

Both work fine.  Note, I do not have OpenMPI installed, nor do I have any hand built compiler.  All installs were done using the setup(x64) little gui app.

**Comment by jfoug** [comment]
Try pulling john from git into a brand new directory.  Do you possibly cross use this dir (some under 'real' nix, some under cygwin) ?  If so, you will (can) have problems with symlinks.

I have also noticed that recent cygwin (within last year or so), has 'native' permissions problems (i.e. NT file permissioning).  Sometimes you simply have to start over, pulling new files.  If you use some tools in NT to edit, some in cygwin (and worse yet, some more from a mounted real nix VM), then file ownership/pemissioning gets totally fuk'd.  The worse part is directories getting hosed.  Again, sometimes I just some the dirs and start over, and things work fine (for months until they get screwed up again)

**Comment by jfoug** [comment]
@richrumble  has this been resolved?

**Comment by richrumble** [comment]
Not for the host I opened it on, I don't have other 64-bit cygwin hosts to
try it on at the moment. Is there anything I can provide that would help?
I'm attaching the config.log but not sure if it will send, cc'ing it too.
I tried a fresh git clone 2 minutes ago no change.

**Comment by jfoug** [comment]
Can you try without MPI.  Again, I have zero problems with cygwin64, but I have never found need to MPI, and thus have never built with that.

**Comment by jfoug** [comment]
Differences:

Yours   gcc 5.4    Mine 5.3

Mine:   checking additional paths gives me   -I/usr/local/include  (yours finds no additional includes)

Can you try this and see if it helps:


```sh
./configure CPPFLAGS=-I/usr/local/include
```

**Comment by richrumble** [comment]
no difference after rerunning configure (no mpi specified

./configure CPPFLAGS=-I/usr/local/include --disable-mpi


$ make clean
rm -f ../run/john.exe ../run/unshadow.exe ../run/unafs.exe
../run/unique.exe ../run/undrop.exe ../run/rar2john.exe ../run/zip2john.exe
../run/genmkvpwd.exe ../run/mkvcalcproba.exe ../run/calc_stat.exe
../run/tgtsnarf.exe ../run/racf2john.exe ../run/hccap2john.exe
../run/raw2dyna.exe ../run/keepass2john.exe ../run/dmg2john.exe
../run/putty2john.exe ../run/uaf2john.exe ../run/wpapcap2john.exe
../run/gpg2john.exe ../run/cprepair.exe ../run/base64conv.exe
../run/pfx2john.exe ../run/ssh2john.exe
rm -f john-macosx-* *.o escrypt/*.o *.bak core
rm -f ../run/kernels/*
rm -f detect bench generic.h tmp.s
rm -f cuda/*.o cuda/*~ *~
cp /dev/null Makefile.dep
make: *** [Makefile:1628: clean] Error 127

$ make -sj4
make[1]: *** [Makefile:877: ../run/kernels/opencl_device_info.h] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:877: ../run/kernels/opencl_DES_hst_dev_shared.h]
Error 127
make[1]: *** [Makefile:877: ../run/kernels/opencl_nonstd.h] Error 127
make[1]: *** [Makefile:877: ../run/kernels/opencl_sboxes-s.h] Error 127
make: *** [Makefile:187: default] Error 2

I cc'd you the make file.

**Comment by jfoug** [comment]
These lines are in your makefile:

```
opencl_%.h:	| ../run/kernels
	$(CP) $< ../run/kernels

%.cl:	| ../run/kernels
	$(CP) $< ../run/kernels

../run/kernels:
	$(MKDIR) ../run/kernels
```

So the files 'should' be there (../run/kernels/*.h|.cl )  But it looks like for some reason they are NOT there.

Can you do a make without the -s, so that we can see if the copy is happening, or if there is some other problem.

**Comment by jfoug** [comment]
From our original post:

```
$ make -j4
make find_version
make[1]: Entering directory '/cygdrive/c/temp/john/JohnTheRipper/src'
/usr/bin/mkdir -p ../run/kernels
cp opencl_device_info.h ../run/kernels
cp opencl_DES_hst_dev_shared.h ../run/kernels
cp opencl_nonstd.h ../run/kernels
make[1]: *** [Makefile:873: ../run/kernels/opencl_device_info.h] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:873: ../run/kernels/opencl_DES_hst_dev_shared.h] Error 127
make[1]: *** [Makefile:873: ../run/kernels/opencl_nonstd.h] Error 127
make[1]: Leaving directory '/cygdrive/c/temp/john/JohnTheRipper/src'
make: *** [Makefile:187: default] Error 2
```

So it 'appears' to make the subdir (../run/kernels), and then copies in the files, BUT for whatever reason, they are not appearing.

1.  Is ../run/kernels  directory created?
2. if so, does it contain all the *.cl and opencl_*.h files?

**Comment by jfoug** [comment]
Ok, I did rm -rf run/kernels (to make sure it was clean), and then did a simple make (no -j anything and no silent).  Here was the results (I hit ^C early on to kill it).

```
$ make
make find_version
make[1]: Entering directory '/cygdrive/c/projects/phpbb/johnripper/john-1.7.9/logmsg/src'
/usr/bin/mkdir -p ../run/kernels
cp opencl_device_info.h ../run/kernels
cp opencl_misc.h ../run/kernels
cp opencl_sha2.h ../run/kernels
cp opencl/7z_kernel.cl ../run/kernels
cp opencl_DES_hst_dev_shared.h ../run/kernels
cp opencl_nonstd.h ../run/kernels
cp opencl_sboxes.h ../run/kernels
cp opencl_sboxes-s.h ../run/kernels
cp opencl_DES_kernel_params.h ../run/kernels
cp opencl_mask.h ../run/kernels
cp opencl/DES_bs_finalize_keys_kernel.cl ../run/kernels
cp opencl/DES_bs_hash_checking_kernel.cl ../run/kernels
cp opencl/DES_bs_kernel.cl ../run/kernels
cp opencl/DES_bs_kernel_f.cl ../run/kernels
cp opencl/DES_bs_kernel_h.cl ../run/kernels
cp opencl/bf_cpu_kernel.cl ../run/kernels
cp opencl/bf_kernel.cl ../run/kernels
cp opencl/cryptmd5_kernel.cl ../run/kernels
cp opencl_sha2_common.h ../run/kernels
cp opencl_sha256.h ../run/kernels
cp opencl_cryptsha256.h ../run/kernels
cp opencl/cryptsha256_kernel_DEFAULT.cl ../run/kernels
cp opencl/cryptsha256_kernel_GPU.cl ../run/kernels
cp opencl_sha512.h ../run/kernels
cp opencl_cryptsha512.h ../run/kernels
cp opencl/cryptsha512_kernel_DEFAULT.cl ../run/kernels
cp opencl/cryptsha512_kernel_GPU.cl ../run/kernels
cp opencl_sha1_ctx.h ../run/kernels
cp opencl/gpg_kernel.cl ../run/kernels
cp opencl/keyring_kernel.cl ../run/kernels
cp opencl_sha1.h ../run/kernels
cp opencl/keystore_kernel.cl ../run/kernels
cp opencl_unicode.h ../run/kernels
cp opencl_rc4.h ../run/kernels
cp opencl_md4.h ../run/kernels
cp opencl_md5.h ../run/kernels
cp opencl/krb5pa-md5_kernel.cl ../run/kernels
cp opencl_lm_hst_dev_shared.h ../run/kernels
cp opencl_lm_kernel_params.h ../run/kernels
cp opencl_lm_finalize_keys.h ../run/kernels
cp opencl/lm_kernel_b.cl ../run/kernels
cp opencl/lm_kernel_f.cl ../run/kernels
cp opencl_lotus5_fmt.h ../run/kernels
cp opencl/lotus5_kernel.cl ../run/kernels
cp opencl/md4_kernel.cl ../run/kernels
cp opencl/md5_kernel.cl ../run/kernels
cp opencl/mscash_kernel.cl ../run/kernels
cp opencl/msha_kernel.cl ../run/kernels
cp opencl/nt_kernel.cl ../run/kernels
cp opencl/ntlmv2_kernel.cl ../run/kernels
cp opencl/o5logon_kernel.cl ../run/kernels
cp opencl/office2007_kernel.cl ../run/kernels
cp opencl/office2010_kernel.cl ../run/kernels
cp opencl/office2013_kernel.cl ../run/kernels
cp opencl/oldoffice_kernel.cl ../run/kernels
cp opencl_pbkdf1_hmac_sha1.h ../run/kernels
cp opencl/pbkdf1_hmac_sha1_kernel.cl ../run/kernels
cp opencl_pbkdf2_hmac_md4.h ../run/kernels
cp opencl/pbkdf2_hmac_md4_kernel.cl ../run/kernels
cp opencl_pbkdf2_hmac_md5.h ../run/kernels
cp opencl/pbkdf2_hmac_md5_kernel.cl ../run/kernels
cp opencl_pbkdf2_hmac_sha1.h ../run/kernels
cp opencl/pbkdf2_hmac_sha1_kernel.cl ../run/kernels
cp opencl/pbkdf2_hmac_sha1_unsplit_kernel.cl ../run/kernels
cp opencl/pbkdf2_hmac_sha256_kernel.cl ../run/kernels
cp opencl/pbkdf2_hmac_sha512_kernel.cl ../run/kernels
cp opencl/pbkdf2_kernel.cl ../run/kernels
cp opencl_ripemd.h ../run/kernels
cp opencl/pbkdf2_ripemd160_kernel.cl ../run/kernels
cp opencl/phpass_kernel.cl ../run/kernels
cp opencl/pwsafe_kernel.cl ../run/kernels
cp opencl/rakp_kernel.cl ../run/kernels
cp opencl/rar_kernel.cl ../run/kernels
cp opencl/salted_sha_kernel.cl ../run/kernels
cp opencl/sha1_kernel.cl ../run/kernels
cp opencl_rawsha256.h ../run/kernels
cp opencl_mask_extras.h ../run/kernels
cp opencl/sha256_kernel.cl ../run/kernels
cp opencl/sha512_kernel.cl ../run/kernels
cp opencl_rawsha512.h ../run/kernels
cp opencl/sha512_ng_kernel.cl ../run/kernels
cp opencl/wpapsk_kernel.cl ../run/kernels
cp opencl/xsha512_kernel.cl ../run/kernels
echo "#define JTR_GIT_VERSION \"1.8.0-jumbo-1-4978-ga2d590a+\"" > version.h.new
diff >/dev/null 2>/dev/null version.h.new version.h && rm -f version.h.new || mv -f version.h.new version.h
make[1]: Leaving directory '/cygdrive/c/projects/phpbb/johnripper/john-1.7.9/logmsg/src'
make[1]: Entering directory '/cygdrive/c/projects/phpbb/johnripper/john-1.7.9/logmsg/src'
gcc -DAC_BUILT -march=native -mavx -DJOHN_AVX -c -g -O2 -I/usr/local/include -I/opt/AMDAPP//include -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations  -Wunused-but-set-variable -std=gnu89 -Wdate-time -D_GNU_SOURCE -D__CYGWIN64__ -D__CYGWIN32__    -fopenmp   -DHAVE_HT  -I/usr/local/include -I/opt/AMDAPP//include -DHAVE_OPENCL  -funroll-loops opencl_DES_bs_b_plug.c -o opencl_DES_bs_b_plug.o
gcc -DAC_BUILT -march=native -mavx -DJOHN_AVX -c -g -O2 -I/usr/local/include -I/opt/AMDAPP//include -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations  -Wunused-but-set-variable -std=gnu89 -Wdate-time -D_GNU_SOURCE -D__CYGWIN64__ -D__CYGWIN32__    -fopenmp   -DHAVE_HT  -I/usr/local/include -I/opt/AMDAPP//include -DHAVE_OPENCL  -funroll-loops opencl_DES_bs_f_plug.c -o opencl_DES_bs_f_plug.o
gcc -DAC_BUILT -march=native -mavx -DJOHN_AVX -c -g -O2 -I/usr/local/include -I/opt/AMDAPP//include -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations  -Wunused-but-set-variable -std=gnu89 -Wdate-time -D_GNU_SOURCE -D__CYGWIN64__ -D__CYGWIN32__    -fopenmp   -DHAVE_HT  -I/usr/local/include -I/opt/AMDAPP//include -DHAVE_OPENCL  -funroll-loops opencl_DES_bs_h_plug.c -o opencl_DES_bs_h_plug.o
Makefile:1571: recipe for target 'opencl_DES_bs_h_plug.o' failed
make[1]: *** [opencl_DES_bs_h_plug.o] Interrupt
Makefile:187: recipe for target 'default' failed
make: *** [default] Interrupt

```

Can you replicate those steps (remove the run/kernels directory then do a vanilla make, no -j, no -s)

**Comment by richrumble** [comment]
Sorry to write back so late, I've reinstalled cygwin_64 and the problem is gone. I can't say for sure what it might have been, but seems there was something with the setup. I've built JtR a few times to be sure, no problem now.

**Comment by jfoug** [comment]
The only times I have had problems were with my opencl, which is not 'installed' in cygwin, but simply added paths back to the Win64 includes/libs.  

I am going to close this.  It really sounds like something on your setup/install.
