### ISSUE TITLE
'd' rule and long lines may smash rules.c buffers.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2160]
We need to protect ourselves from old pot lines from when LINE_BUFFER_SIZE was 0x30000. I believe the problem is already limited to just a few combinations of loop-back, memory-map, node/fork/MPI and rules. I will investigate further and try to establish a solid test case.

Care should be taken to not harm performance.

**Comment by jfoug** [comment]
Can we simply get by with memory leaks ?  These should be 1 time events (well, would they be if we have .pot reloads) ???

That huge line usage WAS the absolute worse choice ever made in jumbo!

**Comment by magnumripper** [comment]
I believe the problem is not fgetl() vs. fgetll() - any code that uses it is probably safe already. The problem here is mgetl() [same thing but reading from a memory map instead of a file handle] within wordlist.c. It doesn't have any check for oversize lines. This is probably pretty trivial but we need to watch out for performance.

**Comment by magnumripper** [comment]
I had a good look at this. `mgetl()` in fact has the same protection for overlong lines as `fgetl()` has.

Here's what I think was happening:
1. We read a legacy super-long pot line and truncated it properly to our current, smaller, LINE_BUFFER_SIZE.
2. --loopback was used, so the line was scanned for `:` field separator. In the truncated line none was found, so the truncated ciphertext was used. This is now optimized away in 786ffd2, we have no use for a truncated ciphertext as a candidate!
3. The long (but perfectly within proper limits) line triggered [this core bug](http://www.openwall.com/lists/john-dev/2016/07/06/1), yet to fix.

So it could just as well have been a plain wordlist and not loopback mode.

**Comment by magnumripper** [comment]
Fixed in core and merged to Jumbo in 26791bf0a
