### ISSUE TITLE
-aes-256-cbc algo

### ISSUE THREAD

**Issue by kost123** [magnumripper/JohnTheRipper#2163]
First off I'll front with this.. I don't know if this is already implemented somewhere in another module that can be easily modified but...

There are a few bitcoin related programs that many people use such as bitcoin wallet for android, multibit keys.. they all use this decryption method:

`openssl enc -d -aes-256-cbc -a -in "INFILE" -out "OUTFILE.txt" -k PASSWORD`

The creator of btcrecover.py made a good way to check for each of these programs decrypted data to see if the password was correct, it's written in python:

```
if b58_privkey[0] in b"LK5Q\x0a#":
                # Does it look like a base58 private key (MultiBit, MultiDoge, or oldest-format Android key backup)?

                # (there's a 1 in 300 billion chance this hits but the password is wrong)

                if b58_privkey[0] in b"LK5Q":  # private keys always start with L, K, or 5, or for MultiDoge Q

                    for c in b58_privkey[1:]:

                        # If it's outside of the base58 set [1-9A-HJ-NP-Za-km-z]

                        if c > b"z" or c < b"1" or b"9" < c < b"A" or b"Z" < c < b"a" or c in b"IOl": break  # not base58

                    else:  # if the loop above doesn't break, it's base58

                        return orig_passwords[count-1], count

                # Does it look like a bitcoinj protobuf (newest Bitcoin for Android backup) or a KnC for Android key backup?

                # (there's a 1 in 2 trillion chance this hits but the password is wrong)

                elif b58_privkey[2:6] == b"org." and b58_privkey[0] == b"\x0a" and ord(b58_privkey[1]) < 128 or \

                     b58_privkey == b"# KEEP YOUR PRIV":

                    return orig_passwords[count-1], count

```

So, can anybody make this algo?

**Comment by jfoug** [comment]
Within john, we already have this in aes/aes.h  (note this is a function pointer, where it will get replaced with SIMD aes or fall back to C aes is SIMD on the machine is not there, or can not do AES)

```C
// Input, output, key, number of blocks, iv
typedef void (*aes_fptr_cbc)(unsigned char *, unsigned char *, unsigned char *, size_t, unsigned char *);
```

So aes-cbc should be handled.

**Comment by kost123** [comment]
So how would I go about cracking a base64 encoded aes256 encryption on jtr?

**Comment by jfoug** [comment]
There is a utility class called base64_convert (well, it's in base64_convert.[ch])   You would convert the base64 string into it's binary value.  Then perform the aes256-cbc call, and compare the buffers.

**Comment by kost123** [comment]
Thanks, I'll give it a shot.. I don't know c syntax but google + knowledge of programming :D

**Comment by kholia** [comment]
I think that the existing `openssl_enc_fmt_plug.c` format can handle this. Also, it seems that OP's problem was "solved". Should we close this ticket?

**Comment by kost123** [comment]
I will try it out and let you know if it works, thanks.

**Comment by kholia** [comment]
No, there is no support for specifying regular expressions. Patches are welcome to add such a feature.

**Comment by kholia** [comment]
https://github.com/cesanta/slre looks good for implementing such a feature.

**Comment by kholia** [comment]
JtR now has native support for various wallet formats. Hence, I am closing this ticket.

**Comment by solardiz** [comment]
In 2017, @kholia wrote:

> JtR now has native support for various wallet formats. Hence, I am closing this ticket.

As I understand, our native support for wallets does not cover those wallets wrapped in "openssl enc", which some wallet software uses, and which this issue was about. Our "openssl-enc" format works on this outer layer fine, but suffers from too frequent false negatives - hence, @kost123's request here to detect correct decryption through wallet-specific patterns made sense. Unfortunately, it is non-trivial to implement given what we encode into `openssl2john.py` output and what we decrypt - namely, we decrypt only the last AES block, where we check the padding, whereas those patterns would be seen near the beginning of a wallet.

See also #4723, #4724.
