### ISSUE TITLE
Fuzzing support for long ciphertexts

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2166]
After we decreased LINE_BUFFER_SIZE, a lot more formats trigger this limitation:
```
$ ../run/john --format=bks --fuzz
Fuzzing: BKS [PKCS12 PBE SHA-1 32/64]... 
Created directory: fuzz_status
ciphertext='$bks$0$1$20$2036$...' is bigger than the LINE_BUFFER_SIZE=1024
```
Should be trivial, using alloc & free.

**Comment by magnumripper** [comment]
That was easy, I didn't realize this simple fix but it should do just fine.

**Comment by jfoug** [comment]
Trust me, it was not my first go at it, but once I F'd with it quite a bit (and the logic changes started to get a bit ugly), this one just 'hit me' (tm).  It is sort of a cheating way to do it, BUT works like a champ, and does not really modify any logic of the tool
