### ISSUE TITLE
rar2john: Support 64-bit sizes

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2170]
See comments in #2168 

See http://www.forensicswiki.org/wiki/RAR#File_Header_.28File_in_Archive.29

There's another 32 bits later on if bit 0x100 in HEAD_FLAGS is set. We currently do not read them.

**Comment by magnumripper** [comment]
Also, it seems we can't even handle sizes above 2 GB right now, despite using size_t.

**Comment by magnumripper** [comment]
@jfoug please commit that fix for now (but drop the old commented-out lines). Then we'll at least handle size up to 4 GB.

**Comment by magnumripper** [comment]
Perhaps this would work too
```c
       file_header_pack_size = file_header_block[7] +
            (file_header_block[8] << 8ULL) +
            (file_header_block[9] << 16ULL) +
            (file_header_block[10] << 24ULL);
```

**Comment by magnumripper** [comment]
LOL we do have this code
```c
		if (file_header_head_flags & 0x100) {
			if (verbose) {
				fprintf(stderr, "! HIGH_PACK_SIZE present\n");
			}
			if (fread(rejbuf, 4, 1, fp) != 1) {
				fprintf(stderr, "%s: Error: read failed: %s.\n",
					archive_name, strerror(errno));
				goto err;
			}

			ext_time_size -= 4;
		}
		if (file_header_head_flags & 0x100) {
			if (verbose) {
				fprintf(stderr, "! HIGH_UNP_SIZE present\n");
			}
			if (fread(rejbuf, 4, 1, fp) != 1) {
				fprintf(stderr, "%s: Error: read failed: %s.\n",
					archive_name, strerror(errno));
				goto err;
			}

			ext_time_size -= 4;
		}
```
...it's just that it doesn't USE the bits for sizes, it merely does this to find the correct place of FILE_NAME.

**Comment by magnumripper** [comment]
@jfoug I'm not touching anything until you say you're on it or not.

**Comment by jfoug** [comment]
Done with 31-32 bit change, and a FIXME comment     477054c

Sorry, was out partying and riding today.

**Comment by jfoug** [comment]
There are other issues (possible core issues).

Things like this in format.h:

```C
/* Size and alignment of internal salt representation, in bytes */
	int salt_size;
```

dyna_salt.c (but these use the int salt_size;
```C
/*
 * NOTE, will compare dyna and non-dyna salts.
 */
int dyna_salt_cmp(void *p1, void *p2, int comp_size);

/*
 * NOTE, will do the MD5 salt hashing for either non or dyna-salts.
 */
void dyna_salt_md5(struct db_salt *p, int comp_size);
```

These are just a couple things that likely should be size_t

I am having problems 'cracking' larger rar files.  The little ones seem fine.  I am just going to leave this bug open until we 'know' that really large rar files get cracked properly.

**Comment by jfoug** [comment]
NOTE, I just had a 4.8mb rar file taht does NOT find the password, but same password and a 114mb rar file cracks like a champ.

So it may simply be that we have rar problems, where NOT all rar files crack properly.  Likely that should just be a new-different bug.

**Comment by jfoug** [comment]
rar2john is fixed (64 bit).  But there are issues in rar  (actually now, in common.c (the hexlenl stuff).
