### ISSUE TITLE
GPU mask mode wrong speed reporting

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2181]
When running raw-md5-opencl with mask mode on Titan X, the reported p/s looks correct, whereas c/s and C/s are about 10 times lower:

```
[solar@super run]$ ./john pw -form=raw-md5-opencl -dev=6 -mask='?a?a?a?a?a?a?a1434'
Device 6: GeForce GTX TITAN X
[...]
Loaded 1 password hash (Raw-MD5-opencl [MD5 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:05 0.03% (ETA: 01:25:06) 0g/s 4731Mp/s 368861Kc/s 368861KC/s GPU:79C aa2Mnia1434..aa:_Via1434
[...]
0g 0:00:18:00 11.02% (ETA: 00:02:30) 0g/s 7123Mp/s 657524Kc/s 657524KC/s GPU:85C aai}pM21434..aa'r:M21434
```
95^7/7123/10^6*0.1102/60 = 18.01

This problem is not seen on a few other GPUs I tried, where c/s and C/s correctly match p/s when cracking just one raw-md5 hash with the exact same mask as above.

**Comment by magnumripper** [comment]
Although only seen on raw MD5, this bug would theoretically trigger with any GPU-side mask format whenever `keys_per_crypt` x `mask_int_cand.num_int_cand` overflowed 32-bit `*pcount` (in this case, 524288 * 95 * 95 overflowed while 262144 * 95 * 95 would fit).

After 4dc07048, GWS can never reach numbers that will overflow when taking mask_int_cand.num_int_cand in account.

@solardiz I believe we still violate the fact `*pcount` is signed, but all relevant code seem to end up correctly. Not sure if we want to fix that (changing it to unsigned) for good measure?

**Comment by solardiz** [comment]
We definitely should improve the formats API at some point, including moving to more appropriate integer types.  As to whether to do it now, and to single out this one parameter and make it just a little bit better (by making it "unsigned int"), I am not sure.
