### ISSUE TITLE
XSHA512 cores with -test=0 run on 32 bit sparc

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2187]
NOTE, it works 'fine' with -format=XSHA512 or -format=XSHA*  BUT cores on a simple -test

I have tried several things. I was thinking it was in allocation of binary, etc, and did aligned_calloc, but this did not fix the problem.  I will continue to look, but wanted a bug report so this does not get forgotten about.

Almost all other formats are now working fully on BE 32 bit where alignment is required (i.e. my sparc 32)

**Comment by jfoug** [comment]
This is now working.  Likely it was fixed with the normalization of the FORMAT TAGS, or something like that.  I can not get this to core at all any more.

**Comment by solardiz** [comment]
@jfoug Was it failing with SIGSEGV or SIGBUS? If the latter, it suggests unaligned access, so it isn't surprising that the issue may appear and disappear along with other changes. I wouldn't conclude that this is fixed merely because the issue disappeared for you for now. It it was SIGBUS, it will likely reappear, for you or for someone else. (Could be true for SIGSEGV too, but for SIGBUS I am almost certain it'll reappear.)

**Comment by jfoug** [comment]
I looked high and low IN the format. I am pretty sure that it was some OTHER format, that was corrupting memory somewhere (ASAN finds most, but not all).  The reason I think this is I was 100% unable to replicate this, UNLESS I ran a full test of all formats.

Yes, it could reappear.  But when I normalized some of the format_tag / format_tag_len stuff, I did find a few questionable things.

I have my own CI (like) environment that daily gits current bleeding, builds and runs, logging results, so if this problem reappears I will find it shortly.  I got tired of having to fight through 20 or so busted formats every 6 months, lol.

This was failing with a SIGSEGV (iirc).  I do not think unaligned gives a BUS error.  I think it gives a SEGV and a hard core (which sun studio does not load :( as a core file)

**Comment by solardiz** [comment]
On Tue, Aug 09, 2016 at 08:03:15PM -0700, jfoug wrote:
> This was failing with a SIGSEGV (iirc).  I do not think unaligned gives a BUS error.  I think it gives a SEGV and a hard core (which sun studio does not load :( as a core file)

Unaligned access used to give BUS on Solaris/SPARC.  I don't know if it's still the case for recent versions of Solaris, but I would expect so.
