### ISSUE TITLE
Error Compiling wpapsk.cu 

### ISSUE THREAD

**Issue by TiTi87** [magnumripper/JohnTheRipper#2198]
Hello,

On a fresh Debian 8.5. I'm trying to enable CUDA with John. But while compiling I get this error :
```
> make clean && make -s
[...]
cd cuda; /usr/local/cuda-7.5/bin/nvcc -c -Xptxas -v -fmad=true  wpapsk.cu -o ../cuda_wpapsk.o
../jumbo.h(276): warning: allowing all exceptions is incompatible with previous function "atoll"
/usr/include/stdlib.h(157): here

../formats.h(326): error: expected an identifier

1 error detected in the compilation of "/tmp/tmpxft_00026130_00000000-7_wpapsk.cpp1.ii".
Makefile:260: recipe for target 'cuda_wpapsk.o' failed
make[1]: *** [cuda_wpapsk.o] Error 2
make[1]: Leaving directory '/root/JohnTheRipper/src'
Makefile:187: recipe for target 'default' failed
make: *** [default] Error 2
```

Nvidia driver version 367.35 with a NVIDIA Telsa K40m is installed with CUDA-7.5, each of them from nvidia website. PATH and LD_LIBRARY_PATH are correctly defined and seems to be working fine.
John sources are up to date, and I havent modified any file

I know that OpenCL is better, but I just want to enable both of them on this server. 
Any idea ? Thanks in advance for your help.

**Comment by magnumripper** [comment]
I didn't build w/ CUDA for quite a while. Will look into this. Right now my whole build environment seems to be borken after an update of Homebrew (common problem) and I have very little time but sooner or later I will get up to speed again.

**Comment by JusticeForMikeBrown** [comment]
I have same problem.   See #2201

**Comment by claudioandre** [comment]
Reproducible on super. 

----
Looking at formats.h, the error message seems related to 4eb01693b225e2da1922585011aa3b944268511e. But I tested only:
```
git checkout 7b63341e651893306b83051d0149a76fa6b80af4
git checkout 4eb01693b225e2da1922585011aa3b944268511e
```

**Comment by magnumripper** [comment]
@TiTi87 @JusticeForMikeBrown please try again with latest code.
