### ISSUE TITLE
Cuda 7.5-18 Make Fails

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [magnumripper/JohnTheRipper#2201]
Linux Mint 17.3

This error is in the attached make.txt

cd cuda; /usr/local/cuda-7.5/bin/nvcc -c -Xptxas -v -fmad=true   wpapsk.cu -o ../cuda_wpapsk.o
../jumbo.h(276): warning: allowing all exceptions is incompatible with previous function "atoll"
/usr/include/stdlib.h(157): here

Any idea?

[cuda_pkgs.txt](https://github.com/magnumripper/JohnTheRipper/files/409723/cuda_pkgs.txt)

[make.txt](https://github.com/magnumripper/JohnTheRipper/files/409721/make.txt)

[configure.txt](https://github.com/magnumripper/JohnTheRipper/files/409708/configure.txt)

**Comment by JusticeForMikeBrown** [comment]
Second try:

ptxas info    : Used 63 registers, 64 bytes cmem[0], 20 bytes cmem[16]
../jumbo.h(276): warning: allowing all exceptions is incompatible with previous function "atoll"
/usr/include/stdlib.h(157): here

../formats.h(343): error: expected an identifier

1 error detected in the compilation of "/tmp/tmpxft_00002e7f_00000000-7_wpapsk.cpp1.ii".
make[1]: *** [cuda_wpapsk.o] Error 2
make: *** [default] Error 2

**Comment by jfoug** [comment]
Duplicate.
