### ISSUE TITLE
Benchmarking: ZipMonster Segmentation fault

### ISSUE THREAD

**Issue by TiTi87** [magnumripper/JohnTheRipper#2202]
Hello,

On a fully functional john, freshly compiled from sources. I've got a SEGFAULT on MD5(ZipMonster) while running `john --test`.
<code>
Benchmarking: ZipMonster, MD5(ZipMonster) [MD5-256/256 AVX2 8x3 x 50000]... (32xOMP) Segmentation fault
</code>

Not really important since john seems to be working fine on any others formats but still...

**Comment by magnumripper** [comment]
This should also be looked into (dropped?) while at it:
```
zipmonster_fmt_plug.c:147:20: warning: unused function 'hex_encode_uppercase'
      [-Wunused-function]
static inline void hex_encode_uppercase(unsigned char *str, unsigned char *_out)
                   ^
1 warning generated.
```

**Comment by kholia** [comment]
@TiTi87 Can you please provide more details about the crash? A gdb backtrace would be very helpful in narrowing down the problem. What operating system and compiler are you using?

**Comment by magnumripper** [comment]
We've been here before @kholia, you code too little nowadays 😉
