### ISSUE TITLE
Using private keyword as a variable name?

### ISSUE THREAD

**Issue by TheAifam5** [magnumripper/JohnTheRipper#2205]
cd cuda; /opt/cuda/bin/nvcc -c -Xptxas -v -fmad=true  rawsha512.cu -o ../cuda_rawsha512.o
../jumbo.h(276): warning: allowing all exceptions is incompatible with previous function "atoll"
/usr/include/stdlib.h(118): here
../formats.h(343): error: expected an identifier
1 error detected in the compilation of "/tmp/tmpxft_00002a4c_00000000-7_wpapsk.cpp1.ii".

I used this link to download:
https://codeload.github.com/magnumripper/JohnTheRipper/tar.gz/bleeding-jumbo

**Comment by claudioandre** [comment]
This bug report is a duplicate of: #2198
