### ISSUE TITLE
Symbol __fd_select (number 61) is not exported from dependent module /usr/lib/libc.a(shr.o)

### ISSUE THREAD

**Issue by huanghemengxi** [magnumripper/JohnTheRipper#2213]
Hello everyone, I am in compiling JohnTheRipper-bleeding-jumbo version of the program.
Run john error
```
exec(): 0509-036 Cannot load program ./john because of the following errors:
        0509-150   Dependent module /opt/freeware/lib/libcrypto.a(libcrypto.so) could not be loaded.
        0509-152   Member libcrypto.so is not found in archive     
--
exec(): 0509-036 Cannot load program openssl because of the following errors:
        0509-130 Symbol resolution failed for /usr/lib/libcrypto.a(libcrypto.so.1.0.0) because:
        0509-136   Symbol __fd_select (number 61) is not exported from dependent module /usr/lib/libc.a(shr.o).
        0509-150   Dependent module libcrypto.a(libcrypto.so.1.0.0) could not be loaded.
        0509-026 System error: Cannot run a file that does not have a valid format.
        0509-192 Examine .loader section symbols with the
                 'dump -Tv' command. 
```
------------------------------
Environment configuration is as follows:
Operating systems: AIX Version 5.2
make version: GNU Make 3.81
gcc version: gcc version 4.6.1 (GCC)

**Comment by jfoug** [comment]
See if you have pkg-config on your system.  If so:

$ pkg-config --libs libssl
$ pkg-config --cflags libssl

and post results here.

**Comment by huanghemengxi** [comment]
#pkg-config --libs libssl
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libssl' found

#pkg-config --cflags libssl
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libssl' found

find / -name *libssl*
/opt/freeware/lib/libssl.a
/opt/freeware/lib/libssl-static.a
/opt/freeware/64/lib/libssl.a
/opt/freeware/64/lib/libssl-static.a
/usr/lib/libssl.a
/usr/lib/libssl_compat.a
/usr/linux/lib/libssl.a
/usr/linux/lib/libssl-static.a

**Comment by huanghemengxi** [comment]
Suggesting no libssl package, but find to find libssl package

**Comment by magnumripper** [comment]
Try `find / -name libssl | xargs ls -lrt` so we can see file dates.

**Comment by huanghemengxi** [comment]
find / -name *libssl* | xargs ls -lrt
-rwxr-xr-x   1 root     system      1191902 Oct 04 2006  /opt/freeware/lib/libssl.a
-rw-r--r--   1 root     system       823634 Oct 04 2006  /opt/freeware/lib/libssl-static.a
-r-xr-xr-x   1 root     system      4373034 Feb 10 2016  /usr/lib/libssl.a
-r-xr-xr-x   1 root     system      2318128 Feb 10 2016  /usr/lib/libssl_compat.a
lrwxrwxrwx   1 root     system           18 Aug 16 12:23 /opt/freeware/64/lib/libssl.a -> ../../lib/libssl.a
lrwxrwxrwx   1 root     system           26 Aug 16 12:23 /usr/linux/lib/libssl.a -> /opt/freeware/lib/libssl.a
lrwxrwxrwx   1 root     system           25 Aug 16 12:23 /opt/freeware/64/lib/libssl-static.a -> ../../lib/libssl-static
.a
lrwxrwxrwx   1 root     system           41 Aug 16 12:23 /usr/linux/lib/libssl-static.a -> ../../../opt/freeware/lib/lib
ssl-static.a

**Comment by huanghemengxi** [comment]
（find / -name *libssl* | xargs ls -lrt）
-rwxr-xr-x   1 root     system      1191902 Oct 04 2006  /opt/freeware/lib/libssl.a
-rw-r--r--   1 root     system       823634 Oct 04 2006  /opt/freeware/lib/libssl-static.a
-r-xr-xr-x   1 root     system      4373034 Feb 10 2016  /usr/lib/libssl.a
-r-xr-xr-x   1 root     system      2318128 Feb 10 2016  /usr/lib/libssl_compat.a
lrwxrwxrwx   1 root     system           18 Aug 16 12:23 /opt/freeware/64/lib/libssl.a -> ../../lib/libssl.a
lrwxrwxrwx   1 root     system           26 Aug 16 12:23 /usr/linux/lib/libssl.a -> /opt/freeware/lib/libssl.a
lrwxrwxrwx   1 root     system           25 Aug 16 12:23 /opt/freeware/64/lib/libssl-static.a -> ../../lib/libssl-static
.a
lrwxrwxrwx   1 root     system           41 Aug 16 12:23 /usr/linux/lib/libssl-static.a -> ../../../opt/freeware/lib/lib
ssl-static.a

**Comment by huanghemengxi** [comment]
find / -name *libssl* | xargs ls -lrt
-rwxr-xr-x   1 root     system      1191902 Oct 04 2006  /opt/freeware/lib/libssl.a
-rw-r--r--   1 root     system       823634 Oct 04 2006  /opt/freeware/lib/libssl-static.a
-r-xr-xr-x   1 root     system      4373034 Feb 10 2016  /usr/lib/libssl.a
-r-xr-xr-x   1 root     system      2318128 Feb 10 2016  /usr/lib/libssl_compat.a
lrwxrwxrwx   1 root     system           18 Aug 16 12:23 /opt/freeware/64/lib/libssl.a -> ../../lib/libssl.a
lrwxrwxrwx   1 root     system           26 Aug 16 12:23 /usr/linux/lib/libssl.a -> /opt/freeware/lib/libssl.a
lrwxrwxrwx   1 root     system           25 Aug 16 12:23 /opt/freeware/64/lib/libssl-static.a -> ../../lib/libssl-static
.a
lrwxrwxrwx   1 root     system           41 Aug 16 12:23 /usr/linux/lib/libssl-static.a -> ../../../opt/freeware/lib/lib
ssl-static.a

**Comment by magnumripper** [comment]
So your system is inconsistently configured. This is not related to JtR and indeed your OP shows that even the openssl binary fails.

I think you need to tweak dynamic library path. I have no idea how you do that in AIX but it's off-topic for us. I'm closing this issue, you need to find answers elsewhere.

**Comment by huanghemengxi** [comment]
I recently installed the openssl-0.9.7l-1 package to delete or prompt the same error.
After the openssl-0.9.7l-1 package delete, run find / -name * libssl * | xargs ls -lrt results
find / -name *libssl* | xargs ls -lrt
-r-xr-xr-x   1 root     system      4373034 Feb 10 2016  /usr/lib/libssl.a
-r-xr-xr-x   1 root     system      2318128 Feb 10 2016  /usr/lib/libssl_compat.a
