### ISSUE TITLE
zip2john not working on file

### ISSUE THREAD

**Issue by kylet001** [magnumripper/JohnTheRipper#2219]
Forgive me, I new to JTR and zip2john.  I have tried a few test files and they seem to work fine, however on the file I'm trying to recover I get this response:

C:\JTR\run>zip2john zzz.zip
ver 14  efh 554e  efh 7075  zzz.zip->file.txt PKZIP Encr: 2b chk, TS_chk, cmplen=0, decmplen=0, crc=C3FFA530

Any help would be much appreciated.

**Comment by claudioandre** [comment]
Related to #2193 ?

**Comment by kylet001** [comment]
Thanks for the quick response, I don't believe the is broken, here is the result of zip -lv zzz.zip

C:\zip\bin>unzip -lv zzz.zip
Archive:  zzz.zip
 Length   Method    Size  Ratio   Date   Time   CRC-32    Name
--------  ------  ------- -----   ----   ----   ------    ----
  157829  Defl:N    11237  93%  11/12/15 10:59  c3ffa530  file.txt
--------          -------  ---                            -------
  157829            11237  93%                            1 file

**Comment by magnumripper** [comment]
This actually looks like zip2john is doing something wrong. I wonder if we broke it recently? Perhaps #2193 is the same problem.

@kylet001 could you try with some pre-compiled 1.8.0-jumbo-1 or something, and see if that works better?

**Comment by magnumripper** [comment]
Also, I wonder if `ver 14` means *version used to create archive* or *minimum version needed to extract*. We should ideally output both since that's only diagnostic output anyway.

**Comment by magnumripper** [comment]
FWIW I just tried our samples from http://openwall.info/wiki/john/sample-non-hashes?&#ZIP and all of them works and cracks using latest code.

**Comment by magnumripper** [comment]
@kylet001 if you by any chance can share the original zip file, please send it to me (john.magnum@hushmail.com) and I'll have a look.

**Comment by kylet001** [comment]
emailed

**Comment by magnumripper** [comment]
Problem confirmed, will look into it.

**Comment by magnumripper** [comment]
We did not support flag bit 3 (data descriptor) properly. This is now fixed, although there *may* be some more edge cases that are not yet handled (eg. no data descriptor header and no next file).

**Comment by kylet001** [comment]
Thanks again for the help, issue resolved!

**Comment by buddybu** [comment]
I downloaded this today to recover the password from a system backup that I took but didn't record the password anywhere.  I am running the command line zip2john zipfile.zip >../encrypted.hash.  I see it processing, but it always stops in the same place with the message "Killed" and nothing else.  I cannot send the file as it is > 150GB in size.  Any thoughts I could do, like build for debugging and or adding some debug printf's in strategic locations?

Here are the last couple of lines of output:
ver 2.0 zipfile zip->.p2/pool/plugins/org.eclipse.modisco.doc_0.13.1.201508171002.jar PKZIP Encr: cmplen=16742789, decmplen=16742777, crc=6B97692E
Killed

**Comment by magnumripper** [comment]
I guess the humongous size is the problem. zip2john is probably trying to keep a list of every single file in the archive (for later picking the best/smallest) but ends up exhausting memory. We should be able to find a workaround.

**Comment by claudioandre** [comment]
We can try to create a test case on well, putting 100M small text files inside a zip. 

But, in fact, for a huge file like this, I was expecting to see a couple of files, one of them been, e.g, a database. @buddybu, do you mind to run a `unzip -l`?
***
BTW: you found a new error.

**Comment by buddybu** [comment]
It is a memory leak and  I fixed it by using standard c memory runtime, malloc and free.  I can provide you with the changes if you'd like.

I was planning on how best to solve it with in the framework currently being used.

John

**Comment by buddybu** [comment]
One other note, there are 169,000+ files in the archive of varying sizes, but it was the allocation of the hash_data field and never getting freed that is causing my issue.

**Comment by magnumripper** [comment]
Yeah that was a trivial memory leak bug. I believe I fixed it now. Thank you for reporting!

**Comment by magnumripper** [comment]
BTW @buddybu next time please open a new issue instead of hi-jacking an old one.

**Comment by buddybu** [comment]
I realized that after I had already posted my reply.  If I hadn't heard anything Ina couple of days I would have opened a new issue.

**Comment by Shrikrushnatekade** [comment]
> Forgive me, I new to JTR and zip2john. I have tried a few test files and they seem to work fine, however on the file I'm trying to recover I get this response:
> 
> C:\JTR\run>zip2john zzz.zip ver 14 efh 554e efh 7075 zzz.zip->file.txt PKZIP Encr: 2b chk, TS_chk, cmplen=0, decmplen=0, crc=C3FFA530
> 
> Any help would be much appreciated.

do not work this command 
plz help

**Comment by magnumripper** [comment]
@Shrikrushnatekade according to the output, the file is zero bytes. What size is `zzz.zip`? Perhaps the archive is damaged? Try listing it with `zipinfo`.

**Comment by magnumripper** [comment]
BTW I assume you're using the latest version of zip2john - if not, you're probably just seeing the OP bug.
