### ISSUE TITLE
CircleCI MinGW build fails due to atoll macro

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2220]
@jfoug we get this after my recent fix in 9c15f067
```
ar: creating aes.a
genmkvpwd.o: In function `main':
genmkvpwd.c:(.text.startup+0x273): undefined reference to `jtr_atoll'
genmkvpwd.c:(.text.startup+0x2a6): undefined reference to `jtr_atoll'
collect2: error: ld returned 1 exit status
Makefile.legacy:2066: recipe for target '../run/genmkvpwd' failed
make[1]: *** [../run/genmkvpwd] Error 1
```
I tried to fix that in e77f648f but it didn't help. Not sure why and I can't test Windows. Can you look into it?

**Comment by jfoug** [comment]
Gotta add jumbo.o to genmkvpwd target in Makefile.in.  I will get that in, and the problem should go away.

**Comment by jfoug** [comment]
Hopefully that will fix things.

**Comment by magnumripper** [comment]
Oh, right. Very obvious in hindsight 😎

**Comment by magnumripper** [comment]
...except it's needed in Makefile.legacy also (which is what CircleCI uses for MinGW). I fixed that.

**Comment by jfoug** [comment]
What triggered the change from atoll() to jtr_atoll()   ??  I would have thought the original code would have been fine. It would only build that for systems without atoll (well, legacy makefile is questionable).   I think the problem from the start was lack of jumbo.o in that target

**Comment by magnumripper** [comment]
It wasn't related at all. Before 9c15f067, CUDA builds got this:
```
../jumbo.h(276): warning: allowing all exceptions is incompatible with previous function "atoll"
/usr/include/stdlib.h(157): here
```

The #define is the only *really* safe way to do it. We do a similar thing for things like uint32_t and so on in stdint.h.

**Comment by magnumripper** [comment]
CircleCI passes now.

**Comment by jfoug** [comment]
good
