### ISSUE TITLE
Argon2d/i cleanup

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2229]
1.

There are still some diagnostics printed with default verbosity:
```
$  ./john --test=0 |LC_ALL=C grep -C 2 -v PASS 
Testing: aix-ssha256, AIX LPA {ssha256} [PBKDF2-SHA256 128/128 AVX 4x]... PASS
Testing: aix-ssha512, AIX LPA {ssha512} [PBKDF2-SHA512 128/128 AVX 2x]... PASS
Testing: argon2d [Blake2 AVX]... 
memory per hash : 16,00 MB
PASS
Testing: argon2i [Blake2 AVX]... 
memory per hash : 16,00 MB
PASS
Testing: asa-md5, Cisco ASA [md5($p.$s) (Cisco ASA) 128/128 AVX 4x3]... PASS
--
Testing: dummy [N/A]... PASS
Testing: crypt, generic crypt(3) DES [?/64]... PASS
All 354 formats passed self-tests!
```

2.

argon2d_fmt_plug.c and argon2i_fmt_plug.c ar both executable.

3.

Looking at the diff or at the similarities between argon2d_fmt_plug.c and argon2i_fmt_plug.c, I think some more stuff can be moved to a common file, e.g. argon2_core_plug.c.

4.

Those argon2 specific functions defined in argon2_core_plug.c etc. should be renamed, using a prefix argon2_ or similar, to avoid polluting the global name space (and possible future name collisions with core).

**Comment by magnumripper** [comment]
The "memory per hash" is gone with 7ec4a732, no? I don't get that output here.

I agree with the rest.

**Comment by frank-dittrich** [comment]
> The "memory per hash" is gone with 7ec4a73, no?

Not really.

```
(bleeding-jumbo)run $ ./john --test=0 --format=argon2*
Testing: argon2d [Blake2 AVX]... 
memory per hash : 16,00 MB
PASS
Testing: argon2i [Blake2 AVX]... 
memory per hash : 16,00 MB
PASS
All 2 formats passed self-tests!
(bleeding-jumbo)run $ ./john --test --format=argon2*
Benchmarking: argon2d [Blake2 AVX]... 
memory per hash : 16,00 MB
DONE
Speed for cost 1 (t) of 3, cost 2 (m) of 4096, cost 3 (l) of 1
Warning: "Many salts" test limited: 149/256
Many salts:	149 c/s real, 149 c/s virtual
Only one salt:	152 c/s real, 150 c/s virtual

Benchmarking: argon2i [Blake2 AVX]... 
memory per hash : 16,00 MB
DONE
Speed for cost 1 (t) of 3, cost 2 (m) of 4096, cost 3 (l) of 1
Warning: "Many salts" test limited: 148/256
Many salts:	148 c/s real, 148 c/s virtual
Only one salt:	149 c/s real, 147 c/s virtual

All 2 formats passed self-tests!
(bleeding-jumbo)run $ ./john --list=build-info 
Version: 1.8.0.6-jumbo-1-2522-g5cf6de3
Build: linux-gnu 64-bit AVX-ac
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 6.1.1
GNU libc version: 2.23 (loaded: 2.23)
Crypto library: OpenSSL
OpenSSL library version: 01000208f
OpenSSL 1.0.2h-fips  3 May 2016
GMP library version: 6.1.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by frank-dittrich** [comment]
I really need something in between --verbosity=3 and 4: 3 except for (log file) output which gets printed in core, but is suppressed in jumbo unless verbosity is > 3.

**Comment by magnumripper** [comment]
That's another issue but we can try to come up with some sane solution. Current params.h has:
```c
#define VERB_MAX			5
#define VERB_DEFAULT		3
```

There's nothing stopping us from having a VERB_MAX of 10 or whatever but maybe it's not even needed. In this particular case I'd be perfectly fine with only printing that diag output if we're at VERB_MAX.

**Comment by magnumripper** [comment]
BTW another option which has some merits is this:
- We lower jumbo's VERB_DEFAULT to 2.
- We define a VERB_LEGACY set to 3.
- At verbosity VERB_LEGACY, rules logging and any stuff like that behave *just like in john proper*.
- Diags like this are only printed if verb level > VERB_LEGACY.

**Comment by frank-dittrich** [comment]
@magnumripper I like your VERB_LEGACY idea. And I agree this should have been a separate issue.

**Comment by magnumripper** [comment]
I opened a separate issue for this and will delete the OT posts from *this* issue

**Comment by jfoug** [comment]
I am working on this.  4. is being handled by simply making a single format that handles both type d and type i.  There is no notable differences within the formats.  Why have 2.

**Comment by jfoug** [comment]
If you can spot any other cleanup issues, please post, but I think this format(s) is now cleaned up when viewed from 'outside'  (i.e. not trying to change any of the algorithms or original coding intentions).

**Comment by magnumripper** [comment]
Isn't argon2i_fmt_plug.c supposed to be deleted? And if not, it still has exec bit set.

**Comment by jfoug** [comment]
It was deleted.  Did the push not get it removed???   I had a damn merge conflict due to your changes (the VERB_LEGACY stuff).  But in the end, my commit did show that argon2i_fmt_plug.c was deleted, and argon2d_fmt_plug.c renamed to argon2_fmt_plug.c

After a git pull, you are still seeing the argon2i_fmt_plug.c file?

**Comment by jfoug** [comment]
Removed.   I had to add it again, then push.  Should be gone now (I hope).

**Comment by magnumripper** [comment]
> After a git pull, you are still seeing the argon2i_fmt_plug.c file?

Sure. You can see in 5a7cc9f that it's not deleted (or even mentioned in that commit).

**Comment by magnumripper** [comment]
Yeah, now it's gone.
