### ISSUE TITLE
./configure should fail when asking for --enable-asan instead of silently configuring with asan disabled

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2241]
Is it possible to make ./configure fail when I ask for options being enabled which end up not being enabled due to missing libraries etc.?

More than once I didn't realize I got a non-ASan-build on super, even though I ran `./configure --enable-asan`.
I would prefer ./configure to fail instead of silently doing something I didn't ask for.

**Comment by jfoug** [comment]
Thanks for reminding me.  This was something I was going to 'fix', but it slipped my mind.  It has been a bug with me for a while.

**Comment by jfoug** [comment]
Something like this?

```
$ ./configure -C --enable-asan
configure: loading cache config.cache
checking build system type... (cached) x86_64-unknown-cygwin
checking host system type... (cached) x86_64-unknown-cygwin
checking whether to compile using MPI... no
checking for gcc... (cached) gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... (cached) o
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking additional paths...  -L/usr/local/lib -I/usr/local/include
checking arg check macro for -m with gcc... yes
checking arg check macro for -Q with gcc... yes
checking if gcc supports -funroll-loops... yes
checking if gcc supports -Os... yes
checking if gcc supports -finline-functions... yes
checking if gcc supports -Og... yes
checking if gcc supports -fsanitize=address... no
checking if gcc supports -faddress-sanitizer... no
--enable-asan requested, but libraries are NOT present.  Aborting!
```

**Comment by jfoug** [comment]
These are the ones I can see adding abort logic to.  @frank-dittrich, do you see anything else?

--enable-asan
--enable-ubsan
--enable-cuda
--enable-mpi

**Comment by magnumripper** [comment]
Ideally all --enable's should have abort logic. That is, things like OpenCL defaults to "auto" which means it will be enabled if found and obviously no abort if not found. But if user explicitly says
--enable-opencl (setting the variable to "yes" instead of "auto" iirc), it should bail if OpenCL couldn't be found.

**Comment by frank-dittrich** [comment]
@magnumripper agreed.

**Comment by frank-dittrich** [comment]
@jfoug 
> ```
checking if gcc supports -fsanitize=address... no
checking if gcc supports -faddress-sanitizer... no
--enable-asan requested, but libraries are NOT present.  Aborting!
```
No need to specify why a certain option that was requested couldn't be enabled.
(Otherwise, you would need to invent individual texts for all these options, instead of just reusing some generic code.)

**Comment by jfoug** [comment]
How about this as a function?
```
# JTR_MSG_RESULT_POSIBLE_FAILURE(variable, value(s))
AC_DEFUN([JTR_MSG_RESULT_POSIBLE_FAILURE], [
  if test "$1" != xyes; then
    AC_MSG_RESULT([no])
  else
    AC_MSG_FAILURE([$2])
  fi
])
```

This will simply return a result of 'no'   (and the new line, just like normal processing, and continue, UNLESS the --enable-xxx  was used, giving us the 'xyes' value.  It would be called like this (generically)

JTR_MSG_RESULT_POSIBLE_FAILURE([x$enable_cuda], [Could not find all required CUDA components])

**Comment by jfoug** [comment]
Ok, I have this 'better' now, and more generic.  There will be 2 functions.  One will output a 'checking' message, then call the other.  The other will output the result  (yes, no), and then if things are forced (i.e. the var is xyes), then it will perform a failure

Here is what a cuda request will look like  (not the 'checking whether CUDA usable' is a new message line)

```
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... (cached) no
checking additional paths for CUDA... none
checking for nvcc... no
checking whether CUDA usable... no
configure: error: in `/c/phpbb/johnripper/bleed-64/src':
configure: error: Could not find all required CUDA components
See `config.log' for more details
```

Here are the 2 new macros (note I may dnl some of the comments)

```
# JTR_MSG_RESULT_FAILIF_FORCED(success, forced, forced_fail_msg)
# success and forced should be xvar strings, "x$enable_foobar", so they
# will be xno, xyes, xauto, etc.  forced_fail_msg is a message that
# will be output, and the script will abort, IF forced is xyes which
# means the user used --enable-foobar
AC_DEFUN([JTR_MSG_RESULT_FAILIF_FORCED], [
  if test "$1" == xyes; then
    AC_MSG_RESULT([yes])
  else
    AC_MSG_RESULT([no])
    if test "$2" == xyes; then
      AC_MSG_FAILURE([$3])
    fi
  fi
])

# JTR_MSG_CHECKING_AND_RESULT_FAILIF_FORCED(chk_msg, success, forced, forced_fail_msg)
# will output a checking 'chk_msg', then calls JTR_MSG_RESULT_FAILIF_FORCED
AC_DEFUN([JTR_MSG_CHECKING_AND_RESULT_FAILIF_FORCED], [
  AC_MSG_CHECKING([$1])
  JTR_MSG_RESULT_FAILIF_FORCED($2,$3,$4)
])
```

Now I can easily jam this macro into all result situations for the --enable-foobar data.  It will work like AC_MSG_RESULT but all self contained.  We may need to removed some if logic within the script, and replace it with a single call to JTR_MSG_RESULT_FAILIF_FORCED since the if has been moved into there.

**Comment by jfoug** [comment]
- [ ]  --enable-memdbg
- [ ]  --enable-asan
- [ ]  --enable-ubsan
- [ ]  --enable-plugin-dependencies
- [ ]  --enable-openmp-for-fast-formats
- [ ]  --enable-mpi
- [ ]  --enable-rexgen
- [x]  --enable-cuda
- [ ]  --enable-pcap
- [ ]  --enable-native-tests  
- [ ]  --enable-native-march 
- [ ]  --enable-ln-s
- [ ]  --enable-pkg-config
- [ ]  --enable-nt-full-unicode
- [ ]  --enable-int128
- [ ]  --enable-experimental-code
- [ ]  --enable-fuzz
- [ ]  --enable-openmp
- [ ]  --enable-opencl

**Comment by magnumripper** [comment]
Good stuff. Not the highest prio, but a substantial improvement for Joe Random L who's having a hard time figuring out what he's doing.
