### ISSUE TITLE
Bleeding-jumbo doesn't detect various representations of the same canonical hash as being the same 

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2245]
```
(bleeding-jumbo)run $ cat fail_ZIP.pw
$zip2$*0*1*#*9ffba76344938a7d*cc41*210*fb28d3fd983302058c5296c07442502ae05bb59adb9eb2378cb0841efa227cd58f7076ec00bb5faaee24c3433763d715461d4e714cdd9d933f621d2cf6ae73d824414ca2126cfc608d8fc7641d2869afa90f28be7113c71c6b6a3ad6d6633173cde9d7c1bb449cc0a1f8cbab8639255684cd25cb363234f865d9224f4065c0c62e5e60c2500bc78fa903630ccbb5816be2ef5230d411051d7bc54ecdf9dcbe500e742da2a699de0ec1f20b256dbcd506f926e91a1066a74b690f9dd50bd186d799deca428e6230957e2c6fcdcec73927d77bb49699a80e9c1540a13899ecb0b635fb728e1ade737895d3ff9babd4927bbbc296ec92bab87fd7930db6d55e74d610aef2b6ad19b7db519c0e7a257f9f78538bb0e9081c8700f7e8cd887f15a212ecb3d5a221cb8fe82a22a3258703f3c7af77ef5ecf25b4e6fb4118b00547c271d9b778b825247a4cd151bff81436997818f9d3c95155910ff152ad28b0857dcfc943e32729379c634d29a50655dc05fb63fa5f20c9c8cbdc630833a97f4f02792fcd6b1b73bfb4d333485bb0eb257b9db0481d11abfa06c2e0b82817d432341f9bdf2385ede8ca5d94917fa0bab9c2ed9d26ce58f83a93d418aa27a88697a177187e63f89904c0b9053151e30a7855252dab709aee47a2a8c098447160c8f96c56102067d9c8ffc4a74cd9011a2522998da342448b78452c6670eb7eb80ae37a96ca15f13018e16c93d515d75e792f49*bd2e946811c4c5b09694*$/zip2$
(bleeding-jumbo)run $ ./john fail_ZIP.pw                   
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x])
Press 'q' or Ctrl-C to abort, almost any other key for status
hello1           (?)
1g 0:00:00:02 DONE 2/3 (2016-08-29 02:03) 0.3424g/s 502.7p/s 502.7c/s 502.7C/s helene..hellohello
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john fail_ZIP.pw
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x])
Press 'q' or Ctrl-C to abort, almost any other key for status
hello1           (?)
1g 0:00:00:02 DONE 2/3 (2016-08-29 02:03) 0.3401g/s 499.3p/s 499.3c/s 499.3C/s helene..hellohello
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john fail_ZIP.pw
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x])
Press 'q' or Ctrl-C to abort, almost any other key for status
hello1           (?)
1g 0:00:00:02 DONE 2/3 (2016-08-29 02:03) 0.3389g/s 497.6p/s 497.6c/s 497.6C/s helene..hellohello
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ wc -l john.pot
3 john.pot
(bleeding-jumbo)run $ sort -u john.pot|wc -l
1
```

**Comment by jfoug** [comment]
What is the bug here frank.  valid() or the hash getting cracked again and again?

**Comment by frank-dittrich** [comment]
The `#` in `$zip2$*0*1*#*` is invalid. The rest of the hash is exactly copied from a self test.
valid() doesn't reject.
Password is cracked, hash stored in john,pot, but then the .pot hash will not be matched against the loaded hash.
I think, valid() should just reject that "hash".

**Comment by jfoug** [comment]
That field is the 'magic' type field, and is 100% ignored at this time.  There is no right or wrong value any more.

**Comment by frank-dittrich** [comment]
@jfoug so you are saying there's no canonical hash representation for zip.

**Comment by jfoug** [comment]
Not for that field. I am not sure we should 'prepare' it, since I still think it has value.  I think all of the code for the 'magic' has been removed from the format, BUT the signature is still the same.

**Comment by frank-dittrich** [comment]
In other formats, split() is used to produce a canonical hash representation. No need to do this in prepare(), when you don't even know yet whether the hash is valid.

**Comment by jfoug** [comment]
Shouldn't it be done before valid, so that valid can check for the canonical value?   Is prepare called on a pot load, however?

**Comment by frank-dittrich** [comment]
No, just let valid() ignore that field (may be just check for length 1 or value between '0' and '9'), and split() can replace the contents with a hard coded '0'.

**Comment by jfoug** [comment]
086b5c5   Still have opencl zip to do (but it is giving me problems)

**Comment by jfoug** [comment]
5dc7e91  This adds to the GPU code also    split()   It also makes split a common function, since it is the same between the 2

**Comment by frank-dittrich** [comment]
```
(bleeding-jumbo)run $ cat fail_ZIP.pw 
$zip2$*0*1*6*9ffba76344938a7d*cc41*210*fb28d3fd983302058c5296c07442502ae05bb59adb9eb2378cb0841efa227cd58f7076ec00bb5faaee24c3433763d715461d4e714cdd9d933f621d2cf6ae73d824414ca2126cfc608d8fc7641d2869afa90f28be7113c71c6b6a3ad6d6633173cde9d7c1bb449cc0a1f8cbab8639255684cd25cb363234f865d9224f4065c0c62e5e60c2500bc78fa903630ccbb5816be2ef5230d411051d7bc54ecdf9dcbe500e742da2a699de0ec1f20b256dbcd506f926e91a1066a74b690f9dd50bd186d799deca428e6230957e2c6fcdcec73927d77bb49699a80e9c1540a13899ecb0b635fb728e1ade737895d3ff9babd4927bbbc296ec92bab87fd7930db6d55e74d610aef2b6ad19b7db519c0e7a257f9f78538bb0e9081c8700f7e8cd887f15a212ecb3d5a221cb8fe82a22a3258703f3c7af77ef5ecf25b4e6fb4118b00547c271d9b778b825247a4cd151bff81436997818f9d3c95155910ff152ad28b0857dcfc943e32729379c634d29a50655dc05fb63fa5f20c9c8cbdc630833a97f4f02792fcd6b1b73bfb4d333485bb0eb257b9db0481d11abfa06c2e0b82817d432341f9bdf2385ede8ca5d94917fa0bab9c2ed9d26ce58f83a93d418aa27a88697a177187e63f89904c0b9053151e30a7855252dab709aee47a2a8c098447160c8f96c56102067d9c8ffc4a74cd9011a2522998da342448b78452c6670eb7eb80ae37a96ca15f13018e16c93d515d75e792f49*bd2e946811c4c5b09694*$/zip2$
(bleeding-jumbo)run $ ./john fail_ZIP.pw 
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x])
Press 'q' or Ctrl-C to abort, almost any other key for status
hello1           (?)
1g 0:00:00:02 DONE 2/3 (2016-08-29 20:46) 0.3546g/s 520.5p/s 520.5c/s 520.5C/s helene..hellohello
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john fail_ZIP.pw 
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x])
Press 'q' or Ctrl-C to abort, almost any other key for status
hello1           (?)
1g 0:00:00:02 DONE 2/3 (2016-08-29 20:46) 0.3521g/s 516.9p/s 516.9c/s 516.9C/s helene..hellohello
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john fail_ZIP.pw 
Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x])
Press 'q' or Ctrl-C to abort, almost any other key for status
hello1           (?)
1g 0:00:00:02 DONE 2/3 (2016-08-29 20:46) 0.3533g/s 518.7p/s 518.7c/s 518.7C/s helene..hellohello
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ wc -l john.pot
3 john.pot
(bleeding-jumbo)run $ sort -u john.pot|wc -l
1
```

For some reason, john doesn't notice that the hash has already been cracked.
Looks like john is trying to match the .pot file lines against hashes prior to the adjustment done split().

@magnumripper I think the matching of .pot file lines against the loaded hashes in their canonical representation has worked in the past. Am I missing something?

**Comment by frank-dittrich** [comment]
Tried to reproduce with LM (converts to lower case in split():
```
(bleeding-jumbo)run $ cat lm.hash 
1:$LM$a9C604d244c4e99d
(bleeding-jumbo)run $ ./john lm.hash --wordlist=lm.pw
Using default input encoding: UTF-8
Using default target encoding: CP850
Loaded 1 password hash (LM [DES 128/128 AVX-16])
Press 'q' or Ctrl-C to abort, almost any other key for status
AAAAAA           (1)
1g 0:00:00:00 DONE (2016-08-29 22:29) 16.66g/s 16.66p/s 16.66c/s 16.66C/s AAAAAA
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john lm.hash --wordlist=lm.pw
Using default input encoding: UTF-8
Using default target encoding: CP850
Loaded 1 password hash (LM [DES 128/128 AVX-16])
No password hashes left to crack (see FAQ)
(bleeding-jumbo)run $ cat john.pot
$LM$a9c604d244c4e99d:AAAAAA
(bleeding-jumbo)run $ ./john lm.hashes
Using default input encoding: UTF-8
Using default target encoding: CP850
Loaded 2 password hashes with no different salts (LM [DES 128/128 AVX-16])
No password hashes left to crack (see FAQ)
(bleeding-jumbo)run $ cat lm.hashes
1:$LM$a9C604d244c4e99d
2:$LM$a9C604D244C4E99D
```

So, with LM, matching the canonical hash representation against one which needs to be converted in split() works as expected.

**Comment by magnumripper** [comment]
> @magnumripper I think the matching of .pot file lines against the loaded hashes in their canonical representation has worked in the past. Am I missing something?

Good find. This is a bug with `$SOURCE_HASH$` since your input hash exceeds MAX_CIPHERTEXT_SIZE.

**Comment by frank-dittrich** [comment]
But there is a difference between master and bleeding-jumbo:

Master:
```
(master)run $ ./john lm.hashes --wordlist=lm.pw 
Loaded 1 password hash (LM [DES 128/128 AVX-16])
Press 'q' or Ctrl-C to abort, almost any other key for status
AAAAAA           (1)
1g 0:00:00:00 100% 50.00g/s 50.00p/s 50.00c/s 50.00C/s AAAAAA
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```
So, master detects that there are two hashes which are essentially the same.

Bleeding-Jumbo:
```
(bleeding-jumbo)run $ ./john lm.hashes
Using default input encoding: UTF-8
Using default target encoding: CP850
Loaded 2 password hashes with no different salts (LM [DES 128/128 AVX-16])
Press 'q' or Ctrl-C to abort, almost any other key for status
AAAAAA           (2)
AAAAAA           (1)
2g 0:00:00:00 DONE 2/3 (2016-08-29 22:37) 33.33g/s 19133p/s 19133c/s 38266C/s ORANGE..HORSES
Use the "--show" option to display all of the cracked passwords reliably
Session completed
(bleeding-jumbo)run $ ./john lm.hashes
Using default input encoding: UTF-8
Using default target encoding: CP850
Loaded 2 password hashes with no different salts (LM [DES 128/128 AVX-16])
No password hashes left to crack (see FAQ)
```

So, bleeding-jumbo sees these hashes as different:
```
1:$LM$a9C604d244c4e99d
2:$LM$a9C604D244C4E99D
```

Looks like bleeding-jumbo has a problem when loading the hashes.

**Comment by magnumripper** [comment]
OK so perhaps this is not related to `$SOURCE_HASH$`. We should concentrate on the LM case and only then re-test zip.

**Comment by magnumripper** [comment]
Someone should git bisect this problem using LM.

**Comment by frank-dittrich** [comment]
> Someone should git bisect this problem using LM.

Good idea. But not me (at least not the next 2 days).
Need to sleep now, and get up way too early in the morning.

**Comment by frank-dittrich** [comment]
Can't reproduce with LM anymore.
Not sure what I may have done differently when testing this yesterday.

**Comment by frank-dittrich** [comment]
Can't reproduce with LM anymore.
Not sure what I may have done differently when testing this yesterday.

**Comment by solardiz** [comment]
On Mon, Aug 29, 2016 at 01:46:23PM -0700, frank-dittrich wrote:
> (master)run $ ./john lm.hashes --wordlist=lm.pw 
...
> (bleeding-jumbo)run $ ./john lm.hashes

Note the different modes: wordlist vs. batch. The latter includes single mode, which inhibits duplicate hash elimination when the usernames are different (so that both usernames are preserved for single mode's use).

**Comment by magnumripper** [comment]
OK but the `$SOURCE_HASH$` issue (zip) remains. I'm on it.

**Comment by magnumripper** [comment]
OK. Formats that may have their ciphertext truncated with `$SOURCE_HASH$` can't use get_hash and binary_hash functions. I missed the zip (winzip) format when I did 12ed2c8 because it has a dynamic salt so didn't show a huge size in --list=format-details. I may have missed some more but this one is fixed now.

**Comment by frank-dittrich** [comment]
@magnumripper do we need to enhance jumbo's self test to detect this?

**Comment by magnumripper** [comment]
It still wont catch it unless at least one test vector is long enough to trigger truncation. Other than that, yes, we might want to do that.

**Comment by frank-dittrich** [comment]
@magnumripper what about
```
 char *signature[FMT_SIGNATURES];
```
in formats.h?

I though all formats that don't use chopped .pot lines use NULL, the others don't.
So, there should be no need for extra long self test hashes.

**Comment by frank-dittrich** [comment]
Apparently, many formats define that signature.
Why?
The comment in formats.h suggests detecting chopped .pot lines is the only use of that signature.

**Comment by magnumripper** [comment]
I guess Jim saw future alternate uses of that function. And I think I agree.

**Comment by magnumripper** [comment]
We could add an assertion in loader.c that catches the bug in "real use". But I think that's overkill since this bug is so benign. If there are a few formats still hiding now, we'll catch them sooner or later.

**Comment by jfoug** [comment]
> I guess Jim saw future alternate uses of that function. And I think I agree.

Yup, along with there is no 100% assured way to know that a format will not have hashes arrive that are long enough to truncate.   Is 1024 set in stone?  We may think so, but it is not.  Also when others submit formats, but without any long enough to chop, do we know for sure that there can not be longer hashes?

So I did all that have valid format tags which start from byte 0
