### ISSUE TITLE
can not support htpasswd format

### ISSUE THREAD

**Issue by sechacking** [magnumripper/JohnTheRipper#2250]
hi,

  can you make support htpasswd format?

**Comment by jfoug** [comment]
Here are the hashes I could find to be built with htpasswd:

jim2:$apr1$GJA34/..$MalP.BfwrdYgWBv8HKlYJ/
jim2:{SHA}W6ph5Mm5Pz8GgiULbPgzG37mj9g=
jim2:REkFemOGb1iAU
jim2:$2y$05$ViR/HoRR.8rHXxtGqhAO6uHVBAN/XP/3soRNwIZxWI4p67pLjOSNS
jim2:$2y$16$ttbQng.xFhQIrcdgUnpgY.WqMCd89ebZVsPj7v7bbuufpdx6LHZLu


All are password of password.  The last one is a 'stronger' bcrypt (level 16, vs level 5).

```
$ echo password | ../run/john htpasswd.pw -form=md5crypt --stdin
Loaded 1 password hash (md5crypt, crypt(3) $1$ [MD5 128/128 AVX 4x3])
password         (jim2)

$ echo password | ../run/john htpasswd.pw -form=raw-sha1 --stdin
Loaded 1 password hash (Raw-SHA1 [SHA1 128/128 AVX 4x])
password         (jim2)

$ echo password | ../run/john htpasswd.pw -form=descrypt --stdin
Loaded 1 password hash (descrypt, traditional crypt(3) [DES 128/128 AVX-16])
password         (jim2)

$ echo password | ../run/john htpasswd.pw -form=bcrypt --stdin
password         (jim2)
password         (jim2)
```

So just what are you expecting??   john handles everything that htpasswd can build.
