### ISSUE TITLE
1. Blockchain wallet-SECOND PASS syntax and 2. Error in blockchain2john.py

### ISSUE THREAD

**Issue by cryptobitch** [magnumripper/JohnTheRipper#2253]
How do I fix the error in blockchain2john.py? 
 blockchain2john.py", line 27
print "%s:$blockchain$%s$%s" % (filename,
                               ^
SyntaxError: invalid syntax

**Comment by frank-dittrich** [comment]
> How do I fix the error in blockchain2john.py? 

by using python 2.7 instead of python 3, or by not using a blockchain2john.py version from 2013.

You should fetch the latest git version of bleeding-jumbo, then you'll also have a working blockchain2john.py.

**Comment by magnumripper** [comment]
You should also not use this bugtracker for obsolete versions of Jumbo.
