### ISSUE TITLE
Are we over-using prepare() ?

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2254]
#2252 made me aware (again) of a growing problem: Any time we add `prepare()` to a format, we increase the risk of accepting bogus data. Any format that has prepare should have a VERY strict valid. Also, a format should only have a prepare if some wide-used tool have an output format that calls for it.

Like pwdump. I think the initial use of prepare was for NT with pwdump-format. The risk of false positives is slim because the input format is pretty much unique.

I think a format like o3logon really shouldn't have a prepare(). I'm not aware of any existing tool that outputs hashes in the format this `prepare()` takes care of (but I might be wrong of course). IMHO o3logon should be used with Ettercap or some pcap2john tool that emits the hashes **with** the `$o3logon$` tag in place, and so on.

Perhaps we should audit our use of prepare and look for uses that catches far too much, or is simply not needed. Note that prepare() is/may be a performance killer for auto-detection of format.

**Comment by magnumripper** [comment]
Here's all formats using prepare. Check the ones "audited" or known OK.

- [ ] LM_fmt.c
- [ ] MSCHAPv2_bs_fmt_plug.c
- [ ] NETLM_fmt_plug.c
- [ ] NETLMv2_fmt_plug.c
- [ ] NETNTLM_bs_fmt_plug.c
- [ ] NETNTLMv2_fmt_plug.c
- [ ] NETSPLITLM_fmt_plug.c
- [ ] NT_fmt.c
- [ ] asaMD5_fmt_plug.c
- [ ] dynamic_fmt.c
- [ ] hmacMD5_fmt_plug.c
- [ ] md2_fmt_plug.c
- [ ] mssql05_fmt_plug.c
- [ ] net_md5_fmt_plug.c
- [ ] net_sha1_fmt_plug.c
- [ ] nt2_fmt_plug.c
- [ ] o3logon_fmt_plug.c
- [ ] oldoffice_fmt_plug.c
- [ ] opencl_lm_fmt_plug.c
- [ ] opencl_nt_fmt_plug.c
- [ ] opencl_ntlmv2_fmt_plug.c
- [ ] opencl_oldoffice_fmt_plug.c
- [ ] opencl_rawmd5_fmt_plug.c
- [ ] oracle_fmt_plug.c
- [ ] panama_fmt_plug.c
- [ ] pdf_fmt_plug.c
- [ ] postgres_fmt_plug.c
- [ ] rawMD5_fmt_plug.c
- [ ] scrypt_fmt.c
- [ ] skein_fmt_plug.c
- [ ] snefru_fmt_plug.c
- [ ] tiger_fmt_plug.c
- [ ] wow_srp_fmt_plug.c

**Comment by magnumripper** [comment]
OK other than the seven formats that should use valid/split instead of prepare for merely adding a tag (I'll take care of them in a batch job soon), it was actually only o3logon that I'm unsure of. And even that one may be just fine as is. This was a relief!

**Comment by magnumripper** [comment]
The only thing left now is o3logon, I think. @jfoug is there a need for prepare in that format?

**Comment by jfoug** [comment]
o3logon format was added because the hash seen, is NOT in the format of $o3logon$user$salt$hash  but simply in salt/hash found in the pcap dump.  Now, once we have 100% assurity that a tool will always dump into $o3logon$ format, then the prepare can be removed.  But for now, prepare simply takes user:hash and makes a valid hash out of it.   

But IRL, the prepare here is very sketchy, since even the salt/hash are not in salt$hash format in the capture packet.  So if a user is going to put the data into salt$hash then they might as well put it into proper o3logon format.

**Comment by magnumripper** [comment]
OK, then I'm dropping it for now. Future support in ettercap et al should use the format seen in our test vectors. If some tool appears that has its own format, we'll add a prepare again.
