### ISSUE TITLE
base64conv should allow -r and -w independently

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2259]
```
$ echo d2ffffffffcb8dd24c | ../run/base64conv -q -i hex -o raw 
?????ˍ?L

$ echo d2ffffffffcb8dd24c | ../run/base64conv -q -i hex -o raw -w fail_gpg2john-1.raw
Error, -r and -w have to be used as a pair
```
Why!? I want to pipe the input. Of course, I can just use a `>` instead of `-w` but I can't see why.

**Comment by magnumripper** [comment]
OK, it's apparently processing it differently with -r / -w than when used as a stream.

**Comment by frank-dittrich** [comment]
-r and -w were introduced to correctly handle files with NULL bytes.
So, just using -r when reading raw data and converting it into something else should be OK.

**Comment by magnumripper** [comment]
Null bytes isn't a problem in a stream. Not sure why there would be any need for a special mode at all.
