### ISSUE TITLE
Ad-hoc dynamic: Alternate syntax

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2262]
Just took an example from [Hashcat issues](https://github.com/hashcat/hashcat/issues/489) and threw into dynamic as written:
```
$ ../run/john -test -form:'dynamic=md5($salt1.sha1($salt2.$pass))'
Dyna expression syntax error around this part of expression
md5($s1.sha1($s2.$p))
      ^
The only things valid to follow a string type are a . or a )
```

Apparently we can use `$salt` and `$salt2`
```
$ ../run/john -test -form:'dynamic=md5($salt.sha1($salt2.$pass))'
Benchmarking: dynamic=md5($s.sha1($s2.$p)) [128/128 AVX 4x1]... DONE
Many salts:	5204K c/s real, 5204K c/s virtual
Only one salt:	4791K c/s real, 4791K c/s virtual
```

If possible with little effort, `$salt1` (`$s1`) should be an alias for `$salt` (`$s`)

**Comment by jfoug** [comment]
Why?

**Comment by frank-dittrich** [comment]
Because in this case, the salt is split onto two parts that are used individually?
Or, may be, one of the parts is a user name? But that probably wouldn't work if both parts of the salt are random data.

**Comment by jfoug** [comment]
> Because in this case, the salt is split onto two parts that are used individually?

No, it simply is exactly identical to 

```
../run/john -test -form:'dynamic=md5($salt.sha1($salt2.$pass))'
```
but for some reason, someone added $salt1 and $salt2.   Yes, we 'could' add alias, but the more we do that, the more issues we have about canonization.  Yes, some alias work has been done, but continuing to simply to add aliases every time someone (not related to john) adds something not well thought out, that would fit into dyna, .....      So should we : 

```
$nonce = $salt
$pepper = $salt2
#random = $salt
@signature = $salt
etc, etc
```

Yes, we have $s == $salt and $s2 == $salt2, etc.  But continuing forward with everything that any arbitrary blogger posts is not productive, IMHO.

**Comment by magnumripper** [comment]
Agreed. There's another caveat. When programming, I sometimes use `foo` and `foo1` as two (obviously separate) variables. With the same mindset, someone could get the idea that
`dynamic=md5($salt.sha1($salt1.$pass))` would be two different salts, but they wouldn't. Perhaps this is an awful idea.
