### ISSUE TITLE
Some formats fail the test on AVX512

### ISSUE THREAD

**Issue by lei-april** [magnumripper/JohnTheRipper#2273]
When tested on an Intel KNC processor, which supports AVX512, the following formats failed:
- Blackberry-ES10
- Drupal7
- eCryptfs
- Office
- pwsafe
- 7z
- SybaseASE

The only hint I found is they are all SHA formats.

**Comment by magnumripper** [comment]
As of cad492f09f the list was the exact same *except* 7z now worked.

> The only hint I found is they are all SHA formats.

Yes but all different types of SHA. Here's the real hint:
```
$ git grep -l FLAT_OUT *fmt*c
SybaseASE_fmt_plug.c
blackberry_ES10_fmt_plug.c
drupal7_fmt_plug.c
ecryptfs_fmt_plug.c
office_fmt_plug.c
pwsafe_fmt_plug.c
```
Something's amiss with our pseudo-intrinsics for FLAT_OUT scatter. A work-around (revert to generic code) is now committed in dc61d377e, all formats now pass self-tests.

We might want to revisit the scatter-using-intrinsics later but I'm closing this.
