### ISSUE TITLE
*2john tools fail in CPU fallback due to path_init() is not been called soon enough

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2277]
Isn't a patch like this mandatory?

```
diff --git a/src/john.c b/src/john.c
index f230335..6c82b10 100644
--- a/src/john.c
+++ b/src/john.c
@@ -1408,7 +1408,6 @@ static void john_init(char *name, int argc, char **argv)
        if (make_check)
                argv[1] = "--test=0";
 
-       path_init(argv);
        CPU_detect_or_fallback(argv, make_check);
 
 #if HAVE_MPI
@@ -1891,6 +1890,7 @@ int main(int argc, char **argv)
 
        /* put the crc table init here, so that tables are fully setup for any ancillary program */
        CRC32_Init_tab();
+       path_init(argv);
 
        if (!strcmp(name, "unshadow")) {
                CPU_detect_or_fallback(argv, 0);
```

**Comment by magnumripper** [comment]
john Proper has it in `john_init()` right after the
```c
 #ifdef HAVE_JOHN_OMP_FALLBACK
                john_omp_fallback(argv);
 #endif
```

**Comment by magnumripper** [comment]
In Jumbo it was placed at current position after 9852e5e8 and 9e5f65aa

**Comment by claudioandre** [comment]
BTW: probably a better subject (and test case) should be:
*2john tools fail in CPU fallback due to path_init() is not been called soon enough.

Test case:
- build with CPU fallback
- call a 2john (being at john/src)
- it fails (**"$JOHN/" is not defined** - path_init() is called after the CPU fallback mechanism).
- call a 2john (being at john/run)
- it works

******

Move path_init() to main, line 1900, for example.
- it works

**Comment by claudioandre** [comment]
path_init() is necessary before any 2john CPU fallback. Not inside john_init(). An example:

```
1942	if (!strcmp(name, "gpg2john")) {
1943		CPU_detect_or_fallback(argv, 0);
1944		return gpg2john(argc, argv);
...
1965		john_init(name, argc, argv);
```

**Comment by claudioandre** [comment]
Since CPU fallback needs to know "$JOHN/".

```
#define CPU_FALLBACK_PATHNAME path_expand("$JOHN/" CPU_FALLBACK_BINARY)

execv(CPU_FALLBACK_PATHNAME, argv);
```

**Comment by claudioandre** [comment]
Ah! There is no "$JOHN" in john Proper. 
- Well, I see a bug in bleeding.

**Comment by magnumripper** [comment]
Oh. That explains it. So your original patch is likely what we need.
