### ISSUE TITLE
FAILED valid in nsec3 format

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2285]
I am building commit a66e3b33729a0f03b6cf117b62b4743520b87a00.

```
$ ../run/john --format=nsec3 --test-full=0
Testing: nsec3, DNSSEC NSEC3 [32/64]... FAILED (valid (before init))
```

I am wondering how this bug escaped our CI testing environments.

**Comment by kholia** [comment]
I had a local change in my repository which was causing this failure. Sorry for the noise.

**Comment by jfoug** [comment]
I know the feeling, lol

**Comment by magnumripper** [comment]
Yeah I can relate. Whoa, suddenly NOTHING is working well despite `git diff` showing nothing. Then it turns out I **did** have local changes but they were staged, so only seen with `git diff --cached`. Happens to me once in a while. That, or some obscure setting in john-local.conf 😆
