### ISSUE TITLE
OSX compilation issues post sierra

### ISSUE THREAD

**Issue by kureeoffsec** [magnumripper/JohnTheRipper#2286]
Recently home-brew quit allowing users to link brew’s openssl headers with the system install of openssl (which as of Sierra is still OpenSSL 0.9.8zh 14 Jan 2016.  

Attempting to force link the two fails with the following error:

Ultrons-MacBook-Pro:src Ultron$ brew link openssl --force
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

Unfortunately the developers of brew show absolutely no sign of changing their minds on this problem as can be seen in the following threads:

https://github.com/Homebrew/brew/issues/891
https://langui.sh/2015/07/24/osx-clang-include-lib-search-paths/

Of course this means that compiling JTR fails with the following error:

configure: error: in `/Users/ultron/Desktop/JohnTheRipper/src':
configure: error: JtR requires OpenSSL headers being installed

In order to correct this error, I have pulled openssl from source and compiled it locally on my desktop, and attempted to point the configure file at that install by invoking the following command:

./configure OPENSSL_CFLAGS="-I /usr/local/opt/openssl/include -L /usr/local/opt/openssl/lib"

Fortunately, the makefile build succeeds and prompts me to build the package with make clean && make -s.  

Make clean of course succeeds, but make -s fails.  

gpg2john.c:418:14: warning: comparison of constant -1 with expression of type 'unsigned char' is always false [-Wtautological-constant-out-of-range-compare]
                if (buf[i] == EOF)
                    ~~~~~~ ^  ~~~
1 warning generated.
ar: creating archive aes.a
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "_Camellia_cfb128_encrypt", referenced from:
      _gpg_common_check in gpg_common_plug.o
  "_Camellia_set_key", referenced from:
      _gpg_common_check in gpg_common_plug.o
  "_WHIRLPOOL_Final", referenced from:
      _get_salt in dynamic_fmt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_append_input2 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_append_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_at_offset_input2 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_at_offset_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_at_offset_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_at_offset_input2 in dynamic_big_crypt.o
      ...
  "_WHIRLPOOL_Init", referenced from:
      _get_salt in dynamic_fmt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_append_input2 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_append_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_at_offset_input2 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_at_offset_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_at_offset_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_at_offset_input2 in dynamic_big_crypt.o
      ...
  "_WHIRLPOOL_Update", referenced from:
      _get_salt in dynamic_fmt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_append_input2 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_append_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_at_offset_input2 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_at_offset_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input1_at_offset_input1 in dynamic_big_crypt.o
      _DynamicFunc__WHIRLPOOL_crypt_input2_at_offset_input2 in dynamic_big_crypt.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../run/john] Error 1
make: *** [default] Error 2

Any help in resolving this issue?

**Comment by magnumripper** [comment]
> Recently home-brew quit allowing users to link brew’s openssl headers with the system install of openssl

As far as I understand it's the other way around: **OS X** no longer allows you (even as root) to alter /usr/lib and many other directories. There's not much Homebrew or anyone else can do about that.

Anyway, I usually add -L and -I flags pointing to Homebrew OpenSSL, as in, exactly:
```
./configure LDFLAGS=-L/usr/local/opt/openssl/lib CPPFLAGS=-I/usr/local/opt/openssl/include
```
This works perfectly fine for me.

**Comment by kureeoffsec** [comment]
Ripper's command works correctly!

**Comment by mubix** [comment]
I keep forgetting to write this down, every time I reload OSX I have to relearn this. Someday I'll learn to put it somewhere I'll actually look for reference.

**Comment by magnumripper** [comment]
Perhaps we should consider adding /usr/local/opt/openssl to the default search paths. It's a tough choice though, it will help some users but may hit other users where they don't expect it.
