### ISSUE TITLE
bitcoin2john.py no longer works

### ISSUE THREAD

**Issue by blandyuk** [magnumripper/JohnTheRipper#2287]
OK tested it with an older wallet and it worked OK. Just created a new wallet.dat and created password for it. Then tryed bitcoin2john.py and I get:

Traceback (most recent call last):
  File "C:\Hacking\john180j1w\bitcoin2john.py", line 639, in parse_wallet
    d.update(parse_BlockLocator(vds))
TypeError: 'NoneType' object is not iterable
ERROR parsing wallet.dat, type bestblockkey data:       bestblockkey data in he
: 0962657374626c6f636bvalue data in hex: d0fb010000

Seems the wallet.dat has changed. Can you fix the py script?

**Comment by kholia** [comment]
I don't plan to fix this myself. Try https://github.com/gurnec/btcrecover project instead.

**Comment by magnumripper** [comment]
Looks like a good project. Well documented. I wonder if we could use its scripts, as in support their output format(s).

**Comment by kholia** [comment]
It seems that there are too many wallet formats to support. They are best handled by a dedicated project like https://github.com/gurnec/btcrecover.

@blandyuk Patches are welcome to fix / support parsing of newer wallet.dat files.
