### ISSUE TITLE
OpenCL multiple platform behavior

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2295]
http://www.openwall.com/lists/john-users/2016/10/03/1

Apparently there's platform #0 (Mesa) with no devices and platform #1 (nvidia) with two devices. We don't seem to handle that very well.

The following (from OP on ML) might be a problem with Mesa (I'm not quite sure):
```
NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              <checkNullCtx:2241: create context with device from non-default platform : error 209>
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

```

**Comment by magnumripper** [comment]
BTW our `--list=opencl-devices` is supposed to iterate over platforms and list each device on them. Not sure why even that fails.

**Comment by claudioandre** [comment]
We still need a crazy environment to improve the OpenCL detection robustness. 
* This particular case, I guess, I can solve easily.

BTW: --platform was removed on bleeding.

**Comment by magnumripper** [comment]
This should be history after #2298

**Comment by sadimanna** [comment]
Has this problem been solved? I can't figure out the solution. Can anyone help?

Getting output ::

```
NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [Intel]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
```

**Comment by magnumripper** [comment]
Are you using latest code from here?

**Comment by claudioandre-br** [comment]
> Has this problem been solved?

Could you please post the output?
* `_SKIP_OCL_INITIALIZATION=1 ./john --list=opencl-devices -verb=5`

And try to filter devices (what is really failing):
* `./john --list=opencl-devices -verb=5 -device=0`
* `./john --list=opencl-devices -verb=5 -device=1` #AND so on.
