### ISSUE TITLE
Fix latest librexgen encoding issues

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2296]
See #2294

**Comment by magnumripper** [comment]
We probably want these added to unicode.[ch]:
```c
int enc_to_wcs(wchar_t *dst, char *src, size_t dst_sz);
int wcs_to_enc(char *dst, wchar_t *src, size_t dst_sz);
```

**Comment by jfoug** [comment]
What is the difference here, from the current enc_to_utf16() / utf16_to_enc()  ?

The UTF16 'type' is our own construct.  wchar_t would have been a better type to use from the start.  The big issue might be we need to use the *_be() vs default LE conversions if on a BE machine

**Comment by magnumripper** [comment]
Our enc_to_utf16 is always to UTF-16LE regardless of arch. A wchar_t can be any size (including 8-bit) and endianness.

**Comment by magnumripper** [comment]
*"The width of wchar_t is compiler-specific and can be as small as 8 bits. Consequently, programs that need to be portable across any C or C++ compiler should not use wchar_t for storing Unicode text. The wchar_t type is intended for storing compiler-defined wide characters, which may be Unicode characters in some compilers."*

**Comment by jfoug** [comment]
> The width of wchar_t is compiler-specific and can be as small as 8 bits

This would ONLY be true on certain 'tiny' systems, like some super small embedded systems.  For 'real' systems wchar_t is 2 bytes.

**Comment by jfoug** [comment]
But you are right, about the enc_to_wchar   But in reality, those will likely just need to be wrappers, that 'normally' call either the utf16 or utf16be, depending upon the endianity of the computer.

**Comment by magnumripper** [comment]
> For 'real' systems wchar_t is 2 bytes.

That assumption is still a mistake. In Linux, wchar_t is normally (but not guaranteed) 32-bit, with endianity depending on platform.

But yes, we could make a series of ifdef's that end up using some of our existing functions when applicable, avoiding double conversions. Something like:
```c
#if SIZEOF_WCHAR_T == 2
#if ARCH_LITTLE_ENDIAN
#define enc_to_wcs enc_to_utf16
#define wcs_to_enc utf16_to_enc
#else
#define enc_to_wcs enc_to_utf16be
#define wcs_to_enc utf16be_to_enc
#endif
#elif SIZEOF_WCHAR_T == 4
#define enc_to_wcs enc_to_utf32
#define wcs_to_enc utf32_to_enc
#else
(...)
#endif
```

**Comment by jfoug** [comment]
good ifdefs. Then the else would be the code where we would have to handle things ourselves.  NOTE, we would need to handle SIZEOF_WCHAR_T == 4 where not little endian, I think we do not have utf32be stuff yet do we?

**Comment by magnumripper** [comment]
We do have UTF-32 functions and they don't care about endianity because it shouldn't be an issue as long as we don't feed UTF-32 to a byte-oriented hash function [like Windows' `md4(utf16($p))`]. And up to this day we don't.

**Comment by jfoug** [comment]
Endianity absolutely is imperative, no different than the UTF-16 stuff.  Why do you think there are BOM's ?

**Comment by magnumripper** [comment]
There is no BOM for UTF-32

**Comment by magnumripper** [comment]
Anyway for wchar_t I'd be very very surprised if our current, system-endian, UTF-32 functions did not end up correct.

**Comment by jfoug** [comment]
http://unicode.org/faq/utf_bom.html

Look for this string:   "Q: What are some of the differences between the UTFs?"

**Comment by magnumripper** [comment]
OK but anyway, for this purpose - we are never putting the stuff in a stream of octets - so system-endianess will always be the right thing. The ifdef's needed for our current UTF-16 functions is because they are **not** system-endianness but defined endianness.

**Comment by magnumripper** [comment]
A problem with libc wchar_t functions (like `mbtowc()` or `mbstowcs()`) is that they will need a locale to be set according to our current input encoding (or internal codepage if used). We have so far refrained from doing so, for various reasons. So that ifdef ladder is a much better alternative if it turns out successful.

**Comment by jfoug** [comment]
The problem is that rexgen DOES do this (setting locale, etc).  Again, fork, set it the way we want, and possibly disable modifications other than as directed by john, and proceed.  It may be that within john, we are setting a FIXED locale (I think i do when I init rexgen).  So knowing that, we 'know' how to proceed.

**Comment by magnumripper** [comment]
It does? That's just weird. Library functions should never set a locale, right? That should be up to the caller.

**Comment by magnumripper** [comment]
As far as I can see, librexgen doesn't set a locale. The standalone rexgen tool (rexgen.c) does, but that's not part of the library.

**Comment by magnumripper** [comment]
Yet, librexgen may or may not require us to call setlocale() before using it, for proper functionality.

**Comment by magnumripper** [comment]
Experimental patch (functionality inlined here instead of added to unicode.[ch])
```diff
diff --git a/src/regex.c b/src/regex.c
index 396bcdb..746c865 100644
--- a/src/regex.c
+++ b/src/regex.c
@@ -13,6 +13,11 @@
 
 #if HAVE_REXGEN
 
+#if !AC_BUILT || HAVE_LOCALE_H
+#include <locale.h>
+#endif
+#include <ctype.h>
+
 #include "misc.h" // error()
 #include "loader.h"
 #include "logger.h"
@@ -26,10 +31,7 @@
 #include "john.h"
 #include "mask.h"
 #include "external.h"
-#if !AC_BUILT || HAVE_LOCALE_H
-#include <locale.h>
-#endif
-#include <ctype.h>
+#include "unicode.h"
 #include "memdbg.h"
 
 #define UNICODE
@@ -136,21 +138,20 @@ static void rexgen_setlocale()
 }
 
 // Would be nice to have SOME way to be thread safe!!!
-static char BaseWord[1024];
+static wchar_t BaseWord[1024];
 
 size_t callback(wchar_t* dst, const size_t buffer_size)
 {
-       int len;
+       size_t len = wcslen(BaseWord);
 
-       if (!BaseWord[0]) {
+       if (len == 0) {
                *dst = 0;
+               return 0;
        }
-       len = strnzcpyn((char*)dst, BaseWord, 1024);
+
+       memcpy(dst, BaseWord, (len + 1) * SIZEOF_WCHAR_T);
        *BaseWord = 0;
-       if (*dst) {
-               return len;
-       }
-       return 0;
+       return len;
 }
 
 void SetupAlpha(const char *regex_alpha)
@@ -204,7 +205,18 @@ int do_regex_hybrid_crack(struct db_main *db, const char *regex,
        if (options.req_maxlength)
                max_len = options.req_maxlength;
 
+#if SIZEOF_WCHAR_T == 4
+       enc_to_utf32((UTF32*)BaseWord, 1024, (UTF8*)base_word, strlen(base_word));
+#elif SIZEOF_WCHAR_T == 2
+#if ARCH_LITTLE_ENDIAN
+       enc_to_utf16((UTF16*)BaseWord, 1024, (UTF8*)base_word, strlen(base_word));
+#else
+       enc_to_utf16be((UTF16*)BaseWord, 1024, (UTF8*)base_word, strlen(base_word));
+#endif
+#else
        strcpy(BaseWord, base_word);
+#endif
+
        if (bFirst) {
                bFirst = 0;
                rexgen_setlocale();
```
This seems to work on MacOS so likely on Linux too. Tested with UTF-8 as well as a code page.

**Comment by magnumripper** [comment]
@jfoug please test the above patch on Windows, using things like this:
```
$ echo magnum | ../run/john -stdout -stdin -regex='\0[01]'
Using default input encoding: UTF-8
magnum0
magnum1
2p 0:00:00:00 0.00% 200.0p/s magnum1

$  echo müller | iconv -t cp850 | ../run/john -inp=cp850 -stdout -stdin -regex='\0[01]'
müller0
müller1
2p 0:00:00:00 0.00% 200.0p/s müller1
```

**Comment by magnumripper** [comment]
#2297 is a more complete patch but principally the same as above. I ended up not trying to optimize UTF-16BE because some required bits (ie. `utf16_to_enc()`) isn't implemented. I don't see much point in doing so just for this. Just waiting for the bots' verdict now.

**Comment by jfoug** [comment]
> @jfoug please test the above patch on Windows, using things like this:

That is working fine under cygwin (windows).   I think this has nailed it for the hybrid rexgen (until Jan hoses us again).
