### ISSUE TITLE
krbpa2john.py fix for broken user extraction

### ISSUE THREAD

**Issue by ghostop14** [magnumripper/JohnTheRipper#2299]
Recently the tshark conversion of pcap files was failing on Kali rolling when extracting the user field from the packets.  Some troubleshooting found that the field name has changed in the pdml output.

In krbpa2john.py, the field name "kerberos.KerberosString" should be changed to "kerberos.CNameString" in the line:

r = msg.xpath('.//field[@name="kerberos.req_body_element"]//field[@name="kerberos.KerberosString"]') or msg.xpath('.//field[@name="kerberos.kdc_req_body"]//field[@name="kerberos.name_string"]')

**Comment by magnumripper** [comment]
Thanks for reporting. Would this change break older stuff?

**Comment by ghostop14** [comment]
Possibly.  It may be best to add it as an additional "or" clause for
backward compatibility.  It just showed up as an issue in Kali rolling
within the past few months.  I had just used the script back in August as
it is in the git repo and it had worked fine, so something's changed,
possibly in tshark since then to produce the field name change.

**Comment by magnumripper** [comment]
@kholia will you do this please? I'd probably just break something 😝

**Comment by kholia** [comment]
This code is quite fragile due to its dependency on tshark (which keeps changing its field names). I have already spent quite some time on this program.

@ghostop14 Does the following patch work for you on Kali Linux?

```
diff --git a/run/krbpa2john.py b/run/krbpa2john.py
index 4a86fcc..5f0c53f 100755
--- a/run/krbpa2john.py
+++ b/run/krbpa2john.py
@@ -85,7 +85,7 @@ def process_file(f):
             realm = r.attrib["show"]
 
             # locate cname
-            r = msg.xpath('.//field[@name="kerberos.req_body_element"]//field[@name="kerberos.KerberosString"]') or msg.xpath('.//field[@name="kerberos.kdc_req_body"]//field[@name="kerberos.name_string"]')
+            r = msg.xpath('.//field[@name="kerberos.req_body_element"]//field[@name="kerberos.KerberosString"]') or msg.xpath('.//field[@name="kerberos.kdc_req_body"]//field[@name="kerberos.name_string"]') or msg.xpath('.//field[@name="kerberos.req_body_element"]//field[@name="kerberos.CNameString"]')
             if r:
                 if isinstance(r, list):
                     r  = r[0]
```

**Comment by ghostop14** [comment]
Yes worked great.  Thanks!
