### ISSUE TITLE
Build, try and test JtR using a recent OS/compiler on Travis

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2303]
It is done, but I'm not sure what should I use?
- CentOS latest?
- Ubuntu latest or Ubuntu 16.04?
- Something else?

It is tested on 16.04. I guess CentOS is going to be a better choice, but I'm not sure if it is fresh enough.

**Comment by kholia** [comment]
For maximum compatibility of binary builds, CentOS should be good as a build platform.

**Comment by kholia** [comment]
If you are creating builds for distribution, CentOS is good.

If you are testing builds (e.g. using ASan / UBSan), then the latest operating systems and compilers are preferred.

**Comment by claudioandre** [comment]
My intention is to improve CI and testing. Ubuntu latest seems a better choice.
- CentOS latest works fine. If JtR make the move, its gcc is 4.8.5.
- Ubuntu 16.10 works fine. Sooner or latter it will became latest; its gcc is 6.2.0.

**Comment by kholia** [comment]
It is possible to use Docker on Travis CI to get access to updated Ubuntu releases.

See [this](https://github.com/search?utf8=%E2%9C%93&q=docker%20pull%2016.04+filename%3A.travis.yml) URL for some `.travis.yml` examples. I found this query from a Travis CI GitHub issue.

**Comment by claudioandre** [comment]
This is done. No one interested upstream.
