### ISSUE TITLE
Failing loading dynamic_6 hashes

### ISSUE THREAD

**Issue by Zeokat** [magnumripper/JohnTheRipper#2311]
I´m trying to load next hash wich is a Vbulletin hash, wich is dynamic_6 md5(md5($p).$s)

```
md5= 9939d1b089add6a296c39b34aead1896
salt= TRFLUAnMP9^B<L^^_3m/^~(#1`nRl:
```

As you can see the salt have a colon at the end. Im trying to load the hash in this way:

`Zeokat $dynamic_6$0639d1b089add6a296c39b34aead1896$BHFLUAnMP9^B<L^^_3m/^~(#1`nRl:`

And runing the command:
`john.exe --field-separator-char=" " --w:list.txt hasht.txt`

And john the ripper returns:

> using field sep char ' ' (0x20)
> Using default input encoding: UTF-8
> No password hashes loaded (see FAQ)

How can i load the hash properly? tryed to find the solution into the docs but... couldn't find the answer.

**Comment by claudioandre** [comment]
Salt size limit is 23 (using the input file seen below)

``` 
$dynamic_6$9939d1b089add6a296c39b34aead1896$TRFLUAnMP9^B<L^^_3m/
$dynamic_6$ceea95af553bda38ef29f40a5a9d2570$247824
$dynamic_6$34a7ffd83ecd3eecfc65a7fa3293d490$12345678901234567890123
$dynamic_6$34a7ffd83ecd3eecfc65a7fa3293d490$123456789012345678901234
$dynamic_6$34a7ffd83ecd3eecfc65a7fa3293d490$TRFLUAnMP9^B<L^^_3m/^~(#1`nRl:

$ ../run/john ~/hash --show:invalid
$dynamic_6$34a7ffd83ecd3eecfc65a7fa3293d490$123456789012345678901234
$dynamic_6$34a7ffd83ecd3eecfc65a7fa3293d490$TRFLUAnMP9^B<L^^_3m/^~(#1`nRl:
3 valid hashes, 2 invalid hashes
```

**Comment by claudioandre** [comment]
No 'colon' related problems

```
$ cat ./hash
u0 $dynamic_6$2870ee08ada8cd50a4841f9ae3ec7ea3$TRFLUAnMP9^B<L^^_3m/^~:
u2 $dynamic_6$cd7a93d396b79876d27fa517f9a2b724$TRFLUAnMP9^B<L^^_3m/^~(
u3 $dynamic_6$f45d710addbeb41b8533f7c03351b90c$/^~(#1`nl:9^<L^^_3m/^~(
```
```
$ john-the-ripper ./hash --field-separator-char=" " --mask=test
using field sep char ' ' (0x20)
Using default input encoding: UTF-8
Loaded 3 password hashes with 3 different salts (dynamic_6 [md5(md5($p).$s) 128/128 SSE2 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
test             (u3)
test             (u2)
test             (u0)
3g 0:00:00:00  12.50g/s 4.166p/s 12.50c/s 12.50C/s test
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by Zeokat** [comment]
But... how can decrypt VBulletin hashes with JTR then?

That hash and salt is extracted directly from a VBulleting database, i just double checked salt and length is 30 :cry:

**Comment by claudioandre** [comment]
You need a new dynamic. Edit the issue to ask for a new dynamic that handles 30 (or whatever you are seeing in the VBulleting database).

**Comment by jfoug** [comment]
Dynamic_2006.
