### ISSUE TITLE
wpapsk (or any format setting a min length)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2316]
```
Hello,

I'm trying to use john (v1.8.0) to test wpa security. I want it to generate 10-character passwords, so I've added this to `john.conf`:

[Incremental:Test]
File = $JOHN/alnum.chr
MinLen = 10
MaxLen = 10
CharCount = 62

However, when I run `john --format=wpapsk --session=mysession --incremental=Test data`, it prints:

    Note: minimum length forced to 8

and still starts with 8-character passwords. What am I missing? 
```

So if we have a min length > the min length for the format, then the format should NOT change the min-length in a forced manner.

The user was using 1.8.0 but I have validated this still exists in bleeding-jumbo.

**Comment by magnumripper** [comment]
This is not a support forum and the example isn't intended use at all. As a quick solution (off the top of my head), simply add options `--min-len=10 --max-len=10` and Bob will be your uncle's best grandma ever.

**Comment by jfoug** [comment]
So you believe 'forcing' the minimum length to be LESS than the wanted minimum length is ok???

**Comment by magnumripper** [comment]
I'm not sure, but I think it's a matter of syntax defintion. What comes first? What option over-rides the other?

**Comment by jfoug** [comment]
I would think that the inc file should 'imply' --min-len and --max-len   Would there be reasons why that is not correct logic?

**Comment by jfoug** [comment]
I agree that it is an 'order' or precedence issue.

**Comment by magnumripper** [comment]
I will have to ponder this. I never saw this issue until now.

**Comment by magnumripper** [comment]
And I'm open for ideas.

**Comment by jfoug** [comment]
Neither have I.  I was pretty shocked at seeing it, and it DOES work this way in bleeding.

**Comment by jfoug** [comment]
The only thing I can think of off my head woudl be combining inc and mask.
Then the min-len in inc may be 10 and max-len=10, but then --mask=?w?d?d and thus all words are 12 (but that would be outside of range).

**Comment by magnumripper** [comment]
I never saw those inc options as something you'd use this way. But again, I need to think. Perhaps there's a super simple fix that will make everyone happy.

**Comment by jfoug** [comment]
but I do not know if --mask and --inc are valid together (Probably are).   But requesting candidate engine to spew out only 10 char words, and having the format override that, certainly looks wrong.

**Comment by jfoug** [comment]
I use that in inc all the time.

**Comment by jfoug** [comment]
I looked at the code change within john.c where the 'force min length' code is set, but the parsing of the inc file has not been done at that point.  We 'could' add code there to also check if we are in inc mode, and if the mode has a length > the forced min length. BUT that would be pretty ugly.

This simple code does kick the length of the minimal value created within the inc mode up to what is in the inc section

```diff
$ git diff inc.c
diff --git a/src/inc.c b/src/inc.c
index a437ebe..c029538 100644
--- a/src/inc.c
+++ b/src/inc.c
@@ -521,6 +521,8 @@ void do_incremental_crack(struct db_main *db, char *mode)
        if ((max_length = cfg_get_int(SECTION_INC, mode, "MaxLen")) < 0)
                max_length = CHARSET_LENGTH;
        max_count = cfg_get_int(SECTION_INC, mode, "CharCount");
+       if (options.req_minlength != -1 && min_length > options.req_minlength)
+               options.req_minlength = min_length;

        /* Hybrid mask */
        min_length -= mask_add_len;
```

**Comment by jfoug** [comment]
The above patch is not right.  I have been digging into inc.c and there are all sorts of bugs. That it does not crash astounds me.  We subtract mask counts from min (and max and format max).  Also do -1 in regex mode. So if min is 1, then -mask=?w?d?d?d?d sets min to 0xfffffffc (this is for all formats that do not have a forced min).  Fixing a lot of that should be easy.

I am not really sure how to proceed here.  It looks like there was lots of work to track mask (but with bugs). Also something is being done with rexgen (not sure what).

But I do feel that if an inc mode lists a min, that the values returned by the inc mode should honor that value.    For the non-mask/non-rexgen mode (i.e. no hybrid), we can work around this issue by having the user issue a -min=xxx command line arg.  But I do not think that is an ideal solution either.

**Comment by jfoug** [comment]
Here is some examples showing some of this buggy behavior:

```
$ ../run/john -mask=?wxxx -inc:digits -stdout -min-len=7
MaxLen = 122 exceeds the compile-time limit of 24
```

**Comment by jfoug** [comment]
NOTE, I can see reducing the max count for inc and the format if there are things like -mask (or other hybrid stuff), but only reduce the max count for inc, IF that count + the hybrid count goes over the max length of the format.    But I really think the min length of the inc should be honored.   That value is defined for what the inc engine produces.    But that is not todays behavior.  It was how i thought it worked, but obviously, it is not working in that manner.

**Comment by magnumripper** [comment]
I will have a look at this. The current logic is sort-of correct but lacks a few tests.

> Here is some example showing some of this buggy behavior:
>
```
$ ../run/john -mask=?wxxx -inc:digits -stdout -min-len=7
MaxLen = 122 exceeds the compile-time limit of 24
```

It goes like this:
1. The --stdout "format" has a max length of 125 (unless you say --stdout=N)
2. The mask ?wxxx will add 3 mask characters to the base word, so we tell incremental mode that the max is 125-3 == 122.

When corrected, it should be something like this:
1. `inc_max_len` is set from the "digits" incremental mode (to 24)
2. `fmt_max_len` is set from format (to 125)
3. `mask_add_len` is derived from mask (to 3)
4. `effective_max_len` is `MIN(inc_max_len, fmt_max_len - mask_add_len)`

...so with your example, inc mode will run with a max len of 24. and the candidates will be 27 characters from the hybrid mask.

**Comment by solardiz** [comment]
An instance of this bug? -

$ ./john -form=descrypt-ztex -inc=alpha -min-len=4 -max-len=4 -mask='?w?l?l?l?l' ~/john/pw-fake-unix
1 device(s) ZTEX 1.15y ready
SN: .......... productId: 10.15.0.0 "inouttraffic UFM 1.15y" busnum:2 devnum:29
Using default input encoding: UTF-8
Loaded 3269 password hashes with 2243 different salts (descrypt-ztex, traditional crypt(3) [DES ZTEX])
Warning: Slow communication channel to the device. Increase mask or expect performance degradation.
Press 'q' or Ctrl-C to abort, almost any other key for status
Format internal ranges cannot be truncated!
Use a bigger key length or non-gpu format.

I wanted it to use 4-char incremental plus 4-char mask, for 8 total, but it refuses.

**Comment by magnumripper** [comment]
> I wanted it to use 4-char incremental plus 4-char mask, for 8 total, but it refuses.

It may be poorly documented but the intended way to say that is `-min-len=8 -max-len=8 -mask='?w?l?l?l?l'`. The -max-len option specifies the final candidate length, so it will end up with incremental mode automatically being limited to length 4 and then mask mode will add its 4 characters.

**Comment by solardiz** [comment]
Oh, so that's where the implementation complexity comes from. OK, this actually works with descrypt-ztex here.

**Comment by magnumripper** [comment]
This is still not 100% perfect but the issue as reported is fixed.
