### ISSUE TITLE
John does not fork as many times as I want

### ISSUE THREAD

**Issue by matlink** [magnumripper/JohnTheRipper#2317]
I'm using john-1.8.0-jumbo-1 to crack Linkedin password on a 64-core/512GB ram server.
I want john to fork many times, I'm then using the following command:

`$ john --fork=40 --format=Raw-SHA1-Linkedin ../UNZIPPED/linkedin/passwords.txt > linkedin.log`

After approx 5 minutes, john starts to fork and outputs:

`Node numbers 1-40 of 40 (fork)`

Even after waiting dozens of minutes, process monitoring only display 4 john forks:

`$ ps -ef | grep john | wc -l`
`5`

Is that an expected behavior or I am missing something?

**Comment by magnumripper** [comment]
I think you should ask that on the mailing list instead. This is a bug tracker.

**Comment by solardiz** [comment]
This behavior is not expected, but john-1.8.0-jumbo-1 is 2 years old, and we won't look into issues specific to that version now.  Please re-test on bleeding-jumbo, then bring this to the john-users mailing list as magnum suggested.  Thanks!

**Comment by matlink** [comment]
Well in fact, after that I have an error:
`1: fork:Cannot allocate memory`
which explains why not all forks can be made.
However it seems that I have plenty of memory available. Can this error come from another situation than lack of memory?

**Comment by frank-dittrich** [comment]
Most likely you'll not have enough memory (more than 40 times the memory to load all the hashes in Raw-SHA1-Linkedin).

512 GB sounds like a lot of memory, but
-how many hashes are in  Raw-SHA1-Linkedin?
-is any ulimit setting preventing you from using all that memory?

**Comment by solardiz** [comment]
Matlink, this is really john-users material.  No further comments on GitHub, please.

**Comment by matlink** [comment]
Well sorry then, will switch to john-users mailing list. @frank-dittrich please switch too :)
