### ISSUE TITLE
Auto include guidelines when an user create a new issue (or PR)

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2319]
As you can see below, it is possible to fill the 'new issue' text field with some guidelines.

- The goal is to prevent users from using github as a community forum.
****
![image](https://cloud.githubusercontent.com/assets/1702923/20017701/d0903470-a2ab-11e6-8f56-292f67abaf77.png)

**Comment by claudioandre** [comment]
As you can see, it is possible to test it before merging accessing my repo. Anyway, it is safe enough.

**Comment by magnumripper** [comment]
Awesome!

**Comment by jfoug** [comment]
Agreed!
