### ISSUE TITLE
"checking for libusb_init in -lusb-1.0... no"

### ISSUE THREAD

**Issue by smarteam** [magnumripper/JohnTheRipper#2322]
had to do "sudo ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0" for "configure --enable-mpi --enable-fuzz --enable-ztex" to work (on Ubuntu 14.04 LTS x64)

errors were:
checking libusb-1.0/libusb.h usability... yes
checking libusb-1.0/libusb.h presence... yes
checking for libusb-1.0/libusb.h... yes
checking for libusb_init in -lusb-1.0... no
configure: error: in `/home/elijah/src/john/src':
configure: error: ZTEX USB-FPGA module requires libusb-1.0.
See `config.log' for more details

configure:11533: checking libusb-1.0/libusb.h usability
configure:11533: mpicc -c -g -O2 -I/usr/local/include -I/opt/AMDAPP/include  -I/usr/local/include -I/opt/AMDAPP/include conftest.c >&5
configure:11533: $? = 0
configure:11533: result: yes
configure:11533: checking libusb-1.0/libusb.h presence
configure:11533: mpicc -E  -I/usr/local/include -I/opt/AMDAPP/include conftest.c
configure:11533: $? = 0
configure:11533: result: yes
configure:11533: checking for libusb-1.0/libusb.h
configure:11533: result: yes
configure:11535: checking for libusb_init in -lusb-1.0
configure:11560: mpicc -o conftest -g -O2 -I/usr/local/include -I/opt/AMDAPP/include  -I/usr/local/include -I/opt/AMDAPP/include  -L/usr/local/lib -L/opt/AMDAPP/lib/x86_64 conftes
t.c -lusb-1.0   >&5
/usr/bin/ld: warning: libudev.so.0, needed by /usr/local/lib/libusb-1.0.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_new'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_enumerate_scan_devices'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_monitor_receive_device'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_monitor_unref'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_unref'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_enumerate_new'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_device_get_action'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_enumerate_add_match_subsystem'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_list_entry_get_next'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_device_new_from_syspath'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_monitor_get_fd'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_enumerate_get_list_entry'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_device_unref'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_monitor_new_from_netlink'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_enumerate_unref'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_device_get_sysname'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_monitor_filter_add_match_subsystem_devtype'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_monitor_enable_receiving'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_list_entry_get_name'
/usr/local/lib/libusb-1.0.so: undefined reference to `udev_device_get_devnode'
collect2: error: ld returned 1 exit status

### System configuration
Version: 1.8.0-jumbo-1-5387-gdab7bc8
Build: linux-gnu 64-bit AVX2-ac MPI + OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ../run/
Format interface version: 14
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.8.4
GNU libc version: 2.19 (loaded: 2.19)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 01000106f
OpenSSL 1.0.1f 6 Jan 2014
GMP library version: 5.1.3
Regex library version: 1.4      (loaded: 1.4.0)
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by smarteam** [comment]
But I guess it is not the best way to deal with obsolete package. Possible solution is installing it from .deb
http://askubuntu.com/a/593420/348452

**Comment by magnumripper** [comment]
That solution is probably correct. Closing this.
