### ISSUE TITLE
Add ?h and ?H mask placeholders

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2324]
?h is [0-9a-f]
?H is [0-9A-F]

This is for compatibility with (bleeding) Hashcat

**Comment by jfoug** [comment]
We don't have those?  wow.  an oversite.  I know most do ?x type stuff (in rules not mask).    At the same time, I think we need to add these as rules char classes.  We have ?x which is [0-9][a-f][A-F]    So there is no way we could simply add ?X 

NOTE, I have not updated the title here, but once we make sure this observation is correct (I am not sure it is), then I think we should update this enhancement to be both mask and rules (and add 2 to-do check-boxes to the original post).

**Comment by smarteam** [comment]
Oh, compatibility is good.
Hope it will not bring us to separate entities for "suitable for email address", "suitable for domain name", "numpad and surrounding" character sets in core config instead of user-defined ranges/sets

Are you suggesting to add them globally of just update "!! hashcat logic ON" behaviour?

**Comment by jfoug** [comment]
Looking at rules.c, I think we have some VERY large bugs in the ?x (encoding)

```c
case ISO_8859_15:
		rules_init_class('x', CHARS_LOWER CHARS_UPPER
		                 CHARS_ALPHA_ISO_8859_15 CHARS_DIGITS
		                 CHARS_DIGITS_ISO_8859_15);
```

There are other cases like this.  This is NOT hex!

**Comment by jfoug** [comment]
> Are you suggesting to add them globally of just update "!! hashcat logic ON" behaviour?

I would think this would be global, and have nothing to do with 'hc' compatibility stuff in the reading of the rules.    Jumbo and core are NOT compatible, and never will be, until Solar implements things like the .include.......   logic.

**Comment by magnumripper** [comment]
> Looking at rules.c, I think we have some VERY large bugs in the ?x (encoding)

First, The ?x character class in rules have absolutely NOTHING to do with masks nor with this issue. They just look alike. Second, that is not a bug. Look at http://www.openwall.com/john/doc/RULES.shtml.
