### ISSUE TITLE
Add ?h and ?H character classes to rules.

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2325]
The ?h and ?H were recently added to mask. These should also be part of the rules character class sets.

Also, looking into code, it appears that many of the encoding aware ?x character sets are grossly broken.

**Comment by jfoug** [comment]
I did not realize until reading dox, that ?x was ?l?U?d (or ?X being complement)  I thought ?x was hex.  So that was taken off this issue, (since it is not a problem).

But the ?h / ?H will be added as a class.  I wonder if we should also do a class for [0-9a-fA-F] in some way ???

**Comment by smarteam** [comment]
But what is the usecase for mixed-case hex-strings? Ideally they are a computed output and have either upper or lower case but not the combination.

**Comment by jfoug** [comment]
I do not have a need for them. BUT providing primitives allows people with more smarts than me to devise ways to use them that do crack, OR that do help speed things up by reducing the input candidate count.

There 'may' actually be reasons to have ?h == [0-9a-f] ?H being ~[0-9a-f] coming up with some other class for [0-9A-F]  and  the capital class to be ~[0-9A-F], and then a 3rd pair for [0-9a-fA-F] and ~[0-9a-fA-F].

The adding of classes is TRIVIAL.  And I can see a reason to add 6 of these, vs a pair of oddballs, where both the lower case and upper case are searches (vs complements).  The complements have their reasons.  I think for many rules using classes, we have complement RULES which somewhat negate the need for the complement classes, BUT I am not sure that every rule type using a class has a complement.

Examples are:

!?d  == /?D

I need to look a bit deeper at what needs to be added.  Mostly in the letters of the classes.  h and x are the most easy to understand class letters. BUT x is already used.  h certainly make sense, BUT what other 2 letters 'should' be used.  We actually can use ANY letter, but making them humanly 'readable', makes remembering them much easier.  I already got the ?x confused, lol.

**Comment by jfoug** [comment]
Keep in mind, what we are doing with rules, is either mangling in specific ways, or LOOKING to see if words match specific criteria, because we have some inside information about what passwords are/can be used, or are 'more likely', thus we should skip anything that does not 'fit'

**Comment by jfoug** [comment]
Ok, I think I will do this:

?h == [0-9a-z]
?H == ~[0-9a-z]
?i == [0-9A-F]
?I == ~[0-9A-F]
?j == [0-9a-fA-F]
?J == ~[0-9a-fA-F]

Not sure I like this, BUT I can not really think of better, so this is how I am coding.  If someone has a better choice of class letters, post.  It is SUUUUUPPPPER trivial to make that change.  This will be on a topic branch, so there will be plenty of time for peer review.  This is an 'interface' change, so lets get it right, BEFORE turning it loose to the masses, since changes after the fact make for compatibility issue!

@magnumripper your insight is wanted!!  @frank-dittrich your insight is wanted!!! @kholia your insight is wanted!!!

**Comment by jfoug** [comment]
https://github.com/magnumripper/JohnTheRipper/pull/2326

This pull IS merge ready, other than if there are any changes to the ?i or ?j letters used for the upper case hex, and the mixed case hex classes.  But the code is super trivial, AND done/working.  There is a test john-local.conf file in the notes of the pull request

**Comment by jfoug** [comment]
Ok #2327 should be a viable 'clean' PR.  Other than the letters used, this one should be golden.

**Comment by magnumripper** [comment]
I see no reason to implement this. If you need it once in three years, just add a custom character class. In fact I think the ?h and ?H in masks are silly too. I just added them for hashcat compatibility.

**Comment by magnumripper** [comment]
Also, the more of these we add in Jumbo only, the more clashes we'll get with John Proper in the future once Solar uses the letters to something actually useful.
