### ISSUE TITLE
Cuda build error  `__gxx_personality_v0'

### ISSUE THREAD

**Issue by uscitp-rongcuid** [magnumripper/JohnTheRipper#2328]
### Steps to reproduce
On an Ubuntu 16.04 LTS(I am using Mint 18 but that is the base), with nvidia-cuda-toolkit from official repo installed(which gives 7.5).

Try to compile with `--enable-cuda`, using Bleeding Edge source

    ./configure --enable-cuda --enable-opencl && make clean && make -sj16

Gets following errors:
```
cuda_cryptmd5.o:(.eh_frame+0xdb): undefined reference to `__gxx_personality_v0'
cuda_phpass.o:(.eh_frame+0x6b): undefined reference to `__gxx_personality_v0'
cuda_mscash2.o:(.eh_frame+0x11f): undefined reference to `__gxx_personality_v0'
cuda_rawsha256.o:(.eh_frame+0x8b): undefined reference to `__gxx_personality_v0'
cuda_rawsha224.o:(.eh_frame+0x8b): undefined reference to `__gxx_personality_v0'
cuda_mscash.o:(.eh_frame+0xbf): more undefined references to `__gxx_personality_v0' follow
cuda_wpapsk.o: In function `wpapsk_postprocess(int)':
tmpxft_00007540_00000000-4_wpapsk.cudafe1.cpp:(.text+0x832): undefined reference to `prf_512(unsigned int*, unsigned char*, unsigned int*)'
tmpxft_00007540_00000000-4_wpapsk.cudafe1.cpp:(.text+0x8de): undefined reference to `prf_512(unsigned int*, unsigned char*, unsigned int*)'
cuda_wpapsk.o:(.eh_frame+0x3bf): undefined reference to `__gxx_personality_v0'
cuda_pwsafe.o:(.eh_frame+0x6b): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
Makefile:1426: recipe for target '../run/john' failed
make[1]: *** [../run/john] Error 1
Makefile:195: recipe for target 'default' failed
make: *** [default] Error 2
```

### System configuration
Attach details about your OS and about JtR, including:
- Using bleeding-jumbo
- It is compile error

**Comment by solardiz** [comment]
I previously saw this sort of errors when upgrading to CUDA 7.5 on Scientific Linux 6, but using devtoolset-3's newer gcc solved it. I am surprised Ubuntu 16.04 doesn't(?) have recent enough gcc, or/and that CUDA depends(?) on more recent gcc libs than are common on current distros (RHEL6 isn't current, but Ubuntu 16.04 is). How are people using recent CUDA on Ubuntu at all, then? Maybe it's just some Ubuntu packages not installed on this specific install?

If recent CUDA is indeed not supported on recent Ubuntu out of the box, this could be a reason for us to drop CUDA support, finally. We're already building without CUDA by default, for good reasons. I doubt any end-user would actually knowingly want to build with "--enable-cuda" now, and maybe we need to more clearly discourage that. Our OpenCL kernels are more numerous and (where there's overlap) superior anyway.

**Comment by claudioandre** [comment]
We are going to keep track of this on #2330.
