### ISSUE TITLE
CUDA known issues

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2330]
### IMPORTANT
* CUDA is more or less deprecated right now. Well, at least it is no longer a 1st class citizen. 
* **Use OpenCL instead**, see (https://github.com/magnumripper/JohnTheRipper/issues/622#issuecomment-253235967).

JtR developers already know about the CUDA issues seen below:
- See: #622, #2328, #2123
  - CUDA linking error. 
  - Build error `undefined reference to __gxx_personality_v0`

### Workaround
You can try to add -lstdc++ to LDFLAGS.

**Comment by kholia** [comment]
CUDA stuff is gone from the source tree. So this bug can be closed.
