### ISSUE TITLE
Add support for cracking Enpass databases

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2336]
* https://github.com/steffen9000/enpass-decryptor/blob/master/Enpassant.py

* https://www.enpass.io/security/

* https://github.com/sqlcipher/sqlcipher

**Comment by magnumripper** [comment]
How would we detect success or failure after trying a candidate?

**Comment by magnumripper** [comment]
I see we can use a padding check if we're lucky. But we may get too little margin unless there's always an extra empty block.

**Comment by kholia** [comment]
See `enpass_common_verify_page` in `enpass_common_plug.c` file. It has the logic to detect correct passwords.

**Comment by magnumripper** [comment]
Yeah I saw them (strip formats too) today and optimized them a little (very little) 😉

**Comment by damien122** [comment]
Hi @kholia, I tried john with an new created test tresor and a known password but I can't crack it with john.

My steps are:
`python .\enpass2john.py "C:\Path\to\Tresor\vault.enpassdb" > "C:\Path\to\Tresor\vault_hash_full.txt"`

and then run john with following command:
`.\john.exe --session=allrulesTest --wordlist="C:\Path\to\Tresor\wordlist.txt" --format=enpass "C:\Path\to\Tresor\vault_hash_full.txt"`

the wordlist contains this lines:
```
testBla
BlaTest
TestTest
testtest
```
and the last line is the correct enpass password but john don't show success. Is something wrong with my command? Or the wordlist?

**Comment by damien122** [comment]
@kholia @magnumripper as much as I can see, the implementation didn't work. Did you prove it with an created container?

**Comment by magnumripper** [comment]
Perhaps things changed since 2016. What version are you running?

**Comment by damien122** [comment]
John the Ripper 1.9.0-jumbo-1 OMP [cygwin 64-bit x86_64 AVX2 AC]
and Enpass 6.2.0

**Comment by damien122** [comment]
now I test it with the hash from your code tests "openwall" (src/enpass_fmt_plug.c) and it works as expected. But if I create a new tresor and get the hash from it with enpass2john.py and try it with a wordlist, it didn't works 😞

**Comment by damien122** [comment]
@magnumripper should I create a new Issue for enpass support?
