### ISSUE TITLE
BT dupe checking

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2339]
Apparently the code is supposed to remove dupes, but doesn't.

http://www.openwall.com/lists/john-users/2016/11/14/12

**Comment by magnumripper** [comment]
See #2232. I wonder if that problem actually only happened in certain situations. Just now I tried reverting b8a8484 and set NoLoaderDupeCheck=Y (or use single mode) and I can't immediately reproduce the problem.

What I'm saying is the `remove_duplicates()` function(s) in bt.c et al might be partially working but somewhat buggy.

**Comment by magnumripper** [comment]
I now pushed revertion of b8a8484. Sayantan's dupe removal code does work in all cases I tested. 

This issue remains open: I need a reproducible test case where `NoLoaderDupeCheck = Y` with dupe input gets stuck in infinite loop like http://www.openwall.com/lists/john-users/2016/11/14/1

**Comment by solardiz** [comment]
Maybe we need to point out this GitHub issue in the thread on john-users and ask the original reporter to try and reduce a testcase?

**Comment by magnumripper** [comment]
Yep, done

**Comment by magnumripper** [comment]
Update: I never managed to replicate the problem even with files supplied from OP. I'll try again soon and if I still can't reproduce I'll just close this one.
