### ISSUE TITLE
wpa false negative for SSSE3 non-OMP build.

### ISSUE THREAD

**Issue by rofl0r** [magnumripper/JohnTheRipper#2344]
i got this testhash here (produced with a modified version of @jfoug's pass_gen.pl): http://sprunge.us/ahbi
inlined version
```
The Future now:$WPAPSK$The Future now#EWOD.4LWw.kjpDupMzgPGdr4k6vmjjynZ7bZhayDW3lCsyY7vmyTWhkq5hM3qSXhDkh0jjE5SU5BEcy4yJZEafpjtuT3WH8648aJd9wwxSY262EJpXyN/x.qwGCrNgjsMUK9RcL1n.W3Zu3N8RguT4Dt50nqxOpZ9JD8zZujpGFRgIfQscnX2ct/KQeHc1YGS0JqXuqyY/dOkreNW2vRopc3g0DcTMyCe1L/hCRvxfHtuRLM........................................................................................................................................................................................................../c.....E...BsZ7dw6143U0W.glRjV9hE:0:0::

```
when i run it on a machine with AVX2, the password (futurenow) is found, not so on another machine with SSSE3. the version of john is identical on both devices, john.conf as well, the compiler used to build it was GCC 4.7.4. both systems use sabotage linux x86_64. the only difference are the auto-selected (by john's configure script) CFLAGS used to build, eventually the version of libressl and the CPUs in the systems.
example output from AVX2 machine:
```
# /share/john/run/john --session=fut --pot=fut.pot fut
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk, WPA/WPA2 PSK [PBKDF2-SHA1 256/256 AVX2 8x])
Note: minimum length forced to 8
Press 'q' or Ctrl-C to abort, almost any other key for status
futurenow        (The Future now)
1g 0:00:00:00 DONE 1/3 (2016-11-27 13:12) 4.545g/s 181.8p/s 181.8c/s 181.8C/s tthe future now..nthe future now
```

example output from SSSE3 machine:
```
# /share/john/run/john --pot=fut.pot --session=fut fut
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk, WPA/WPA2 PSK [PBKDF2-SHA1 128/128 SSSE3 4x])
Note: minimum length forced to 8
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:05 58.05% 1/3 (ETA: 13:23:15) 0g/s 1279p/s 1279c/s 1279C/s Nowfuture97..The future nowthe98
0g 0:00:00:12 98.58% 1/3 (ETA: 13:23:19) 0g/s 1301p/s 1301c/s 1301C/s nthe1903..the future now1902
0g 0:00:00:17 8.12% 2/3 (ETA: 13:26:36) 0g/s 1123p/s 1123c/s 1123C/s qwertyuiop1..christine1
0g 0:00:00:18 9.41% 2/3 (ETA: 13:26:18) 0g/s 1093p/s 1093c/s 1093C/s Anything1..Artemis1
Session aborted
```
the john version in use is from git bleeding-jumbo ~2-3 days ago

edit: john.conf is the default one that ships with john
edit: when i do `echo futurenow | john --pipe fut` the password is found on the SSSE3 machine as well, so it is probably not related to bad crypto code in libressl oslt

**Comment by claudioandre** [comment]
It is a non-OpenMP bug. It is possible to reproduce on super and well **disabling** OpenMP.
- --disable-openmp --disable-native-tests --march **fails**

Note: well AVX2 is working.

**Comment by jfoug** [comment]
I will get this corrected (hopefully, I can replicate ssse3.  I bet it is any SIMD x4 grouping however, in non-OMP mode.  The AVX2 is x8 vs x4 of older SSE* chips.

**Comment by rofl0r** [comment]
thanks jim and claudio. just out of curiosity, is there a way to reproduce the word combining magic in the automatic mode, so i can 
1) reproduce the same behaviour by feeding the ESSID into john via --pipe or --wordlist
2) spit out a list of all generated passes to stdout ?
it seems --single alone (or -ru=Single) doesn't cut it.

**Comment by magnumripper** [comment]
The only way to see all candidates for a Single mode run is to hack single.c

**Comment by magnumripper** [comment]
I can reproduce this problem with an OpenMP AVX build, using `OMP_NUM_THREADS=1`.

**Comment by magnumripper** [comment]
I suspect this bug is present even with AVX2 8x and even when running OpenMP (probably just needs another test case to trigger). I guess some slot(s) are not working.

**Comment by rofl0r** [comment]
yay ! thanks a lot.

**Comment by magnumripper** [comment]
The problem was limited to the CPU format and also only Single mode, but would happen also with AVX2 and/or OpenMP, it would just need other test cases. Very bad bug, thanks for finding it!
