### ISSUE TITLE
Drop CUDA from main tree

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2348]
- [ ] ~~Tag~~ Note last version that has CUDA support
- [ ] Drop all CUDA code and docs (except we might mention that ~~tag~~ version)

Edit: We can't add a tag because Github will see that as a "release" which is **really** not what we want, at least not until we also have a Jumbo-2 tag.

Edit 2: We could add a CUDA branch of course. I'll do so if/when we do this.

**Comment by jfoug** [comment]
I agree 100%. It has been a long time coming.  Should we do this after 1.8 J2 ?

**Comment by magnumripper** [comment]
We should probably do it *before* Jumbo-2 or we'll need to "support" it for years. And I have a commit ready to push. @solardiz any thoughts or should we just do it?

**Comment by magnumripper** [comment]
#2350 is up for review. I haven't tested a legacy build but it "should work" (famous last words).

**Comment by solardiz** [comment]
I haven't looked at the commit, but I think we should bite the bullet and merge it. If we've made the determination, then there's no reason to wait for after a release.

That said, I regret that not having CUDA support in the tree anymore would mean we wouldn't be able to accept would-be contributions of CUDA formats. I guess there may/will be cases when someone readily has CUDA code for whatever (non-)hash that they could wrap into a format and contribute, and now they would not.

**Comment by magnumripper** [comment]
There is now a branch [CUDA](https://github.com/magnumripper/JohnTheRipper/tree/CUDA) which is the very last version before we dropped CUDA support. I do not intend to maintain that branch, it will likely be frozen there.
