### ISSUE TITLE
bleeding-jumbo does not compile against OpenSSL 1.1.0

### ISSUE THREAD

**Issue by justinsteven** [magnumripper/JohnTheRipper#2355]
Continuing from #2279 

bleeding-jumbo as of 4859f4d3aa22c1b8156493b6f96ce3555fa698fe does not compile against OpenSSL 1.1.0

See, for example, https://bugzilla.redhat.com/show_bug.cgi?id=1383995

# Using Debian Stretch, before accepting the upgrade to `libssl1.1`

```text
7:16:17[justin@3e155c35d42b D ~/john/src](bleeding-jumbo)% git rev-parse HEAD
4859f4d3aa22c1b8156493b6f96ce3555fa698fe

7:16:30[justin@3e155c35d42b D ~/john/src](bleeding-jumbo)% dpkg -l | grep libssl
ii  libssl-dev:amd64                     1.0.2j-1                          amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                           1.0.2j-1                          all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.2:amd64                    1.0.2j-1                          amd64        Secure Sockets Layer toolkit - shared libraries

7:16:43[justin@3e155c35d42b D ~/john/src](bleeding-jumbo)% ./configure &>/dev/null && echo "succeeded"
succeeded

7:17:29[justin@3e155c35d42b D ~/john/src](bleeding-jumbo)% make clean && make -s
rm -f ../run/john ../run/unshadow ../run/unafs ../run/unique ../run/undrop ../run/rar2john ../run/zip2john ../run/genmkvpwd ../run/mkvcalcproba ../run/calc_stat ../run/tgtsnarf ../run/racf2john ../run/hccap2john ../run/raw2dyna ../run/keepass2john ../run/dmg2john ../run/putty2john ../run/uaf2john ../run/wpapcap2john ../run/gpg2john ../run/cprepair ../run/base64conv ../run/pfx2john ../run/SIPdump ../run/vncpcap2john
rm -f john-macosx-* *.o escrypt/*.o *.bak core
rm -f ../run/kernels/*
rm -f detect bench generic.h tmp.s
rm -f *~
cp /dev/null Makefile.dep
make[1]: Entering directory '/home/justin/john/src/aes'
/usr/bin/find . -name \*.a -exec /bin/rm -f {} \;
/usr/bin/find . -name \*.o -exec /bin/rm -f {} \;
make[1]: Leaving directory '/home/justin/john/src/aes'
make[1]: Entering directory '/home/justin/john/src/escrypt'
/bin/rm -f tests crypto_scrypt-best.o crypto_scrypt-common.o sha256.o tests.o crypto_scrypt-*.o
make[1]: Leaving directory '/home/justin/john/src/escrypt'
ar: creating aes.a

Make process completed.
```

# Using Debian Stretch, after accepting the upgrade to `libssl1.1`

```text
7:16:23[justin@878c46c24880 D ~/john/src](bleeding-jumbo)% git rev-parse HEAD   
4859f4d3aa22c1b8156493b6f96ce3555fa698fe

7:16:24[justin@878c46c24880 D ~/john/src](bleeding-jumbo)% dpkg -l | grep libssl
ii  libssl-dev:amd64                     1.1.0c-2                          amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                           1.1.0c-2                          all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.2:amd64                    1.0.2j-4                          amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                      1.1.0c-2                          amd64        Secure Sockets Layer toolkit - shared libraries

7:16:27[justin@878c46c24880 D ~/john/src](bleeding-jumbo)% ./configure &>/dev/null && echo "succeeded"
succeeded

7:17:34[justin@878c46c24880 D ~/john/src](bleeding-jumbo)% make clean && make -s
rm -f ../run/john ../run/unshadow ../run/unafs ../run/unique ../run/undrop ../run/rar2john ../run/zip2john ../run/genmkvpwd ../run/mkvcalcproba ../run/calc_stat ../run/tgtsnarf ../run/racf2john ../run/hccap2john ../run/raw2dyna ../run/keepass2john ../run/dmg2john ../run/putty2john ../run/uaf2john ../run/wpapcap2john ../run/gpg2john ../run/cprepair ../run/base64conv ../run/pfx2john ../run/SIPdump ../run/vncpcap2john
rm -f john-macosx-* *.o escrypt/*.o *.bak core
rm -f ../run/kernels/*
rm -f detect bench generic.h tmp.s
rm -f *~
cp /dev/null Makefile.dep
make[1]: Entering directory '/home/justin/john/src/aes'
/usr/bin/find . -name \*.a -exec /bin/rm -f {} \;
/usr/bin/find . -name \*.o -exec /bin/rm -f {} \;
make[1]: Leaving directory '/home/justin/john/src/aes'
make[1]: Entering directory '/home/justin/john/src/escrypt'
/bin/rm -f tests crypto_scrypt-best.o crypto_scrypt-common.o sha256.o tests.o crypto_scrypt-*.o
make[1]: Leaving directory '/home/justin/john/src/escrypt'
encfs_common_plug.c: In function 'encfs_common_streamDecode':
encfs_common_plug.c:212:17: error: storage size of 'stream_dec' isn't known
  EVP_CIPHER_CTX stream_dec;
                 ^~~~~~~~~~
encfs_common_plug.c:212:17: warning: unused variable 'stream_dec' [-Wunused-variable]
Makefile:1507: recipe for target 'encfs_common_plug.o' failed
make[1]: *** [encfs_common_plug.o] Error 1
Makefile:176: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by magnumripper** [comment]
I don't quite get this. We include "encfs_common.h" which includes <openssl/evp.h> and it in turn includes <openssl/ossl_typ.h>.
```
$ grep -r evp_cipher_ctx_st /usr/local/opt/openssl@1.1/include/
/usr/local/opt/openssl@1.1/include//openssl/ossl_typ.h:typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
```
EVP_CIPHER_CTX is typedef'd to `struct evp_cipher_ctx_st` which doesn't exist anywhere else in the include tree. Is this an OpenSSL bug?

**Comment by magnumripper** [comment]
Here's older OpenSSL, the struct exists:
```
$ grep -r evp_cipher_ctx_st /usr/local/opt/openssl/include/
/usr/local/opt/openssl/include//openssl/evp.h:struct evp_cipher_ctx_st {
/usr/local/opt/openssl/include//openssl/ossl_typ.h:typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
```

**Comment by magnumripper** [comment]
OK the RedHat link showed the way. Encfs problem is fixed but I get this now instead:
```
gpg_common_plug.c: In function 'check_dsa_secret_key':
gpg_common_plug.c:1030:29: error: dereferencing pointer to incomplete type 'DSA {aka struct dsa_st}'
  error = BN_mod_exp(res, dsa->g, dsa->priv_key, dsa->p, ctx);
                             ^~
gpg_common_plug.c: In function 'gpg_common_check':
gpg_common_plug.c:1352:8: error: storage size of 'dsa' isn't known
    DSA dsa;
        ^~~
gpg_common_plug.c:1352:8: warning: unused variable 'dsa' [-Wunused-variable]
make[1]: *** [gpg_common_plug.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```
Probably similar fix needed.

**Comment by magnumripper** [comment]
I hate this high level OpenSSL stuff. The DSA problem seem to be less trivial.

**Comment by magnumripper** [comment]
We need to use setters and getters
```
$ grep -r pqg /usr/local/opt/openssl@1.1/include 
/usr/local/opt/openssl@1.1/include/openssl/dh.h:void DH_get0_pqg(const DH *dh,
/usr/local/opt/openssl@1.1/include/openssl/dh.h:int DH_set0_pqg(DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g);
/usr/local/opt/openssl@1.1/include/openssl/dsa.h:void DSA_get0_pqg(const DSA *d,
/usr/local/opt/openssl@1.1/include/openssl/dsa.h:int DSA_set0_pqg(DSA *d, BIGNUM *p, BIGNUM *q, BIGNUM *g);
```

**Comment by jfoug** [comment]
> We need to use setters and getters

No, we really need to write our own high level shit, and scrap oSSL.  The crypt lib of oSSL, is easy, and interface stays same (and it is reasonably optimal).  The high level interface (EVP, etc), is SLOW, has multi thread problems (which the 'fix' by forcing single thread access with critical sections).  The high level interface is also the one that gets changed at times, AND will often require us to use oSSL version specifics during compile time to either allow or not allow the format to be built.

Yes, we need to support the high level oSSL, because that is how a lot of code will get submitted from authors. But then we should make our best effort to 'own' that code, decoupling it from oSSL and into john 'owned' code.  We have a git issue for this.  A lot of work was done, but I think it was mostly low hanging fruit, and what is left is the NON trivial high level stuff.  HOWEVER, it has been a long time since that issue was looked at, so I bet there are 4 or 5 new instances of low hanging fruit we could pick, along with taking a stab at some of the non-trivial code.

One way to get 'half' way there would be to take ownership of oSSL inside john.  Then we could at least do this:

```C
// change:
#include <openssl/xyz.h>
#include <openssl/foobar.h>

// to
#include "../openssl/xyz.h"
#include "../openssl/foobar.h"
```

Then at least we have a 'known' version of oSSL and can remove many of the multi-version issues.  Then we can continue to pick fruit higher up the tree, and start porting user code to use better, faster internal methods (some of which are done).

I know this sort of hijacks this topic a bit, but I think this discussion is due to be knocked around again.

**Comment by magnumripper** [comment]
Yeah. This is a fairly big task anyhow. Perhaps a GSoC thing, except it's not a cool or interesting project, just lots of muscle work.

**Comment by magnumripper** [comment]
For now though, we could (should) see to it that autoconf detects OpenSSL 1.1 and either simply bails out telling user about the problems, or (better) disable all formats that is incompatible with it.

**Comment by jfoug** [comment]
I am not sure how 'big' a deal it would be to put oSSL into john.  The big problem is it uses CMake (iirc).  But it also might not be hard to simply insert the high level stuff into john, and skip oSSL's CMake (i.e. does not need asm , or extreme optimizations). Then use the installed oSSL for libssl and libcrypto primatives.

That actually may not be 'all' that big of a problem. Would simply be the high level code, with as little glue code as it needed to make it work.  Then a single header would define the 'normal' EVC_* stuff to jtr_EVC (data and code).

**Comment by jfoug** [comment]
I created #2356 for this off topic talk.  Is there any way to move the last few posts to that new topic, short of copying the text and deleting the post?

**Comment by magnumripper** [comment]
Not that I'm aware of

**Comment by jacauc** [comment]
I have two versions of ssl installed:

> /usr/lib/ssl# dpkg -l | grep libssl
ii  libssl-dev:amd64                          1.1.0c-2                             amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                                1.1.0c-2                             all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.2:amd64                         1.0.2k-1                             amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                           1.1.0c-2                             amd64        Secure Sockets Layer toolkit - shared libraries

I'm getting the errors explained above:

> gcc -DAC_BUILT -march=native -mavx -c -g -O2 -I/usr/local/include -DARCH_LITTLE_ENDIAN=1   -Wall -Wdeclaration-after-statement -fomit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations -Wno-format-extra-args -D_GNU_SOURCE  -DHAVE_CUDA  -fopenmp  -pthread  -DHAVE_OPENCL -pthread -funroll-loops ssh2john.c -o ssh2john.o
ssh2john.c: In function ‘process_file’:
ssh2john.c:51:11: error: storage size of ‘pk’ isn’t known
  EVP_PKEY pk;
           ^
ssh2john.c:51:11: warning: unused variable ‘pk’ [-Wunused-variable]
Makefile:520: recipe for target 'ssh2john.o' failed
make[1]: *** [ssh2john.o] Error 1
make[1]: Leaving directory '/root/john-1.8.0-jumbo-1/src'
Makefile:185: recipe for target 'default' failed
make: *** [default] Error 2


is it possible to force the compiler to use 1.0.2 ssl by passing parameters to make? (until a permanent fix for openssl 1.1 is available)

**Comment by magnumripper** [comment]
> is it possible to force the compiler to use 1.0.2 ssl by passing parameters to make? (until a permanent fix for openssl 1.1 is available)

Sure, but I would expect that some package like "libssl1.0.2-dev" would be needed. Is there something like that available?

**Comment by artifexor** [comment]
indeed there is libssl1.0-dev which is in conflict with the default libssl-dev (=1.1). the default ssl version is 1.1 on the stretch/sid system but because some packages still depend on 1.0 the library package must be installed. after the transition the 1.0 will be removed from the system so would better to use the current 1.1 instead of previous 1.0 to make this application "future-proof".

**Comment by magnumripper** [comment]
Until we fix autoconf, I suspect you could end up with a working build for OpenSSL 1.1 like this:

1. `./configure && make -s clean && make -sj8`
2. remove the plugin file(s) that broke the build
3. repeat from 1

This should end up with a build lacking just a few formats (and this is exactly what our first autoconf fix will do also)

**Comment by MarioGeckler** [comment]
I built it sccessfully against OpenSSL 1.1 on Debian testing without the plugins:

gpg_common_plug.o
pfx_fmt_plug.o
opencl_wpapsk_fmt_plug.o
wpapsk_fmt_plug.o
gpg_fmt_plug.o

**Comment by kholia** [comment]
Out of these, we can remove the `pfx` format without any problems. We have `pfx-ng` format now to replace it.

**Comment by magnumripper** [comment]
Thanks @MarioGeckler this is useful input for us.

Now WPAPSK is one of the most important formats... I will look at that one first. Not sure why the OpenCL format would need OpenSSL at all though? It should do everything on GPU.

**Comment by magnumripper** [comment]
Fixed in 7610944. Formats that get disabled are currently GPG, GPG-opencl, KRB5TGS, PDF, PFX and WPAPSK (cpu). But WPAPSK-opencl will be there!

**Comment by magnumripper** [comment]
PDF and KRB5-TGS were fixed in 7610944, not disabled. Commit description lies.

**Comment by magnumripper** [comment]
All formats fixed now. No formats are disabled with OpenSSL 1.1.

**Comment by blshkv** [comment]
Guys, could you release a newer version? This is a short stopper for many distros.
Thanks.
