### ISSUE TITLE
Hash identification reports invalid hash types

### ISSUE THREAD

**Issue by hgbstu** [magnumripper/JohnTheRipper#2358]
When starting john without the --format parameter, hash type detection reports invalid hash types.

For example when trying to crack a md5 hash invalid information is printed
- dynamic=md5($p) is not a valid hash type. There is no such hash type in ./john --list=formats
- a md5 hash is identified as Raw-SHA1-* hash

### Steps to reproduce

> $ #md5(john)=527bd5b5d689e2c32ae974c6229ff785
> $ echo "527bd5b5d689e2c32ae974c6229ff785" > MD5.hash
> $ ./john MD5.hash
> Warning: detected hash type "LM", but the string is also recognized as "dynamic=md5($p)"
> Use the "--format=dynamic=md5($p)" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "HAVAL-128-4"
> Use the "--format=HAVAL-128-4" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "MD2"
> Use the "--format=MD2" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "mdc2"
> Use the "--format=mdc2" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "mscash"
> Use the "--format=mscash" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "mscash2"
> Use the "--format=mscash2" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "NT"
> Use the "--format=NT" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "Raw-MD4"
> Use the "--format=Raw-MD4" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "Raw-MD5"
> Use the "--format=Raw-MD5" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "Raw-MD5u"
> Use the "--format=Raw-MD5u" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "Raw-SHA1-AxCrypt"
> Use the "--format=Raw-SHA1-AxCrypt" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "Raw-SHA1-Linkedin"
> Use the "--format=Raw-SHA1-Linkedin" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "ripemd-160"
> Use the "--format=ripemd-160" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "Raw-SHA1-ng"
> Use the "--format=Raw-SHA1-ng" option to force loading these as that type instead
> Warning: detected hash type "LM", but the string is also recognized as "has-160"
> Use the "--format=has-160" option to force loading these as that type instead
> Using default input encoding: UTF-8
> Using default target encoding: CP850
> Loaded 2 password hashes with no different salts (LM [DES 128/128 AVX-16])
> Will run 8 OpenMP threads
> Press 'q' or Ctrl-C to abort, almost any other key for status

### System configuration
Jumbo bleeding branch built from source on 13.12.2016

> $ ./john --list=build-info
Version: 1.8.0.9-jumbo-1-bleeding
Build: linux-gnu 64-bit AVX-ac OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.8.4
GNU libc version: 2.19 (loaded: 2.19)
Crypto library: OpenSSL
OpenSSL library version: 01000106f
OpenSSL 1.0.1f 6 Jan 2014
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by claudioandre** [comment]
I'm affraid I failed to see your point. So, I tried JtR (the packaged version). Everything is working fine.

```
~$ echo "527bd5b5d689e2c32ae974c6229ff785" > MD5.hash
```

```
$ john-the-ripper --format='dynamic=md5($p)' MD5.hash 
Using default input encoding: UTF-8
Loaded 1 password hash (dynamic=md5($p) [128/128 SSE2 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
john             (?)
1g 0:00:00:00 DONE 2/3 (2016-12-13 12:40) 1.818g/s 3054p/s 3054c/s 3054C/s 123456..phillips
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

```
$ john-the-ripper --format=raw-md5 MD5.hash 
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-MD5 [MD5 128/128 SSE2 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
john             (?)
1g 0:00:00:00 DONE 2/3 (2016-12-13 12:42) 2.222g/s 533.3p/s 533.3c/s 533.3C/s brian..blazer
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by hgbstu** [comment]
I would expect that the format "dynamic=md5($p)" is listed when running the following command. 
> ./john --list=formats | grep "dynamic="

But that's not the case.

The second issue is that the hash 527bd5b5d689e2c32ae974c6229ff785 is recognized as a possible SHA1 hash. That's incorrect because SHA1 size is 160bit, and MD5 size is 128bit.
> Warning: detected hash type "LM", but the string is also recognized as "Raw-SHA1-AxCrypt"
Use the "--format=Raw-SHA1-AxCrypt" option to force loading these as that type instead
Warning: detected hash type "LM", but the string is also recognized as "Raw-SHA1-Linkedin"
Use the "--format=Raw-SHA1-Linkedin" option to force loading these as that type instead
Warning: detected hash type "LM", but the string is also recognized as "ripemd-160"
Use the "--format=ripemd-160" option to force loading these as that type instead
Warning: detected hash type "LM", but the string is also recognized as "Raw-SHA1-ng"

**Comment by claudioandre** [comment]
1. 
> I would expect that the format "dynamic=md5($p)" is listed when running the following command.
> ./john --list=formats | grep "dynamic="

But, then, it will list all dynamics. Big list. RFC.

**Comment by claudioandre** [comment]
2.
> is recognized as a possible SHA1 

It could be Raw-SHA1-AxCrypt (If I'm not wrong). But not Raw-SHA1-ng.

```
$ john-the-ripper MD5.hash --format=Raw-SHA1-ng
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

**Comment by claudioandre** [comment]
```
$ john-the-ripper MD5.hash --format=Raw-SHA1-Linkedin 
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

**Comment by claudioandre** [comment]
I added the bug label.

**Comment by claudioandre** [comment]
Look at what happened before has-160 valid():
- 527bd5b5d689e2c32ae974c6229ff78500000000

**Comment by claudioandre** [comment]
The one to blame is rawsha1_axcrypt_prepare()

**Comment by jfoug** [comment]
The ```-dynamic=md5($p)``` is the expression form of dynamic.  We can not list those, since they are given on the command line, and can be any arbitrary valid expression.

**Comment by magnumripper** [comment]
a54420a fixed the weird problems (and some other weird problems I had seen but haven't had time to narrow down).

This issue is mostly fixed, I think? Not sure why it lists "dynamic=md5($p)" instead of "dynamic_0" though.
