### ISSUE TITLE
Drop use of ARCH_WORD_64

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2361]
https://github.com/magnumripper/JohnTheRipper/commit/a54420a5ab7f6b85aeb23e2547dbcd163f2467a1#commitcomment-20192177

ARCH_WORD_64 is not even present in john proper. Not sure who introduced it (and it could be me) but we should replace all and any uses of it to uint64_t without a thought, and drop the ARCH_WORD_64 typedef.

**Comment by jfoug** [comment]
What about other items talked about?

Drop ARCH_WORD_32 ?
audit ARCH_WORD   (in jumbo code) ?

Yes, ARCH_WORD_64 is truly low hanging fruit (since it has no purpose at all), but why not make a issue with 3 todo tags in it, then start picking those off.

**Comment by magnumripper** [comment]
Sure, or make one or two separate issues for them. Actually I prefer that.

**Comment by jfoug** [comment]
They can certainly be done separately (to make them easier to actually complete).  Things like audit of the ARCH_WORD might take a significant amount of time, while ARCH_WORD_64 should take very little time (scripts should handle most of it without side effects).
