### ISSUE TITLE
Drop usage of ARCH_WORD_32 in lieu of uint32_t

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2363]
https://github.com/magnumripper/JohnTheRipper/commit/a54420a5ab7f6b85aeb23e2547dbcd163f2467a1#commitcomment-20192177

**Comment by magnumripper** [comment]
Wot I said there:
"ARCH_WORD_32 should not be used in Jumbo-only files at all. ARCH_WORD_32 can always be replaced with uint32_t except perhaps in Jumbo deviations of core code."

The above is actually not a universal truth, it's just an opinion. It's also 100% cosmetic. But I think we all agree on it, and IMHO uint32_t is a whole lot easier to read and write.

**Comment by jfoug** [comment]
Yup.  That plus it is default type for many editors, so they syntax color properly.  Yes, most of those editor 'can' have other types custom added to the color schemes, but using built-in types, especially WHEN there is no logical difference, simply makes sense.

**Comment by jfoug** [comment]
I did not have a binary prior to starting (my bad).

**Comment by jfoug** [comment]
There are really only a few files now (all 'master branch') which have this defined type.  They are listed in the above post.  With stdint.h, there really is not a good reason to have a type like this left around.

**Comment by magnumripper** [comment]
Nice!

**Comment by jfoug** [comment]
A bit of screw up that Claudio worked through, to get some of the CI issues worked out (and likely users with these antique systems).

But in all, good riddance to that self defined type, in lieu of uint32_t, which is a much more usable recent type.  It is not 100% 'good riddance', since it still is in Master john, but that usage is very minimal, and I expect Solar to smoke it at some time.  When Solar does, he may want to take our stdint.h 'wrapper' header file and do #include "stdint.h" vs doing #include <stdint.h>  as doing that 'will' help out if there are any portability issues in supporting very old compilers which may not have the system stdint.h file.

**Comment by jfoug** [comment]
NOT using ARCH_WORD_32 in code, and using the "" local header method for stdint.h should be placed into the style guidelines also, since we do not want this to slowly creep back in, from people starting from older legacy code.
