### ISSUE TITLE
Missing memory wrapper mem_realloc()

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2365]
Looking at the leaks in 'my' random tests, I noticed it is complaining about realloc().
- there is (already) a MEMDBG_realloc() in memdbg.c, 
- only the wrapper mem_realloc() is missing in memory.c

Is it by design or a mistake?

**Comment by claudioandre** [comment]
BTW: it also complains about a leak in path.c. The problem is that unless john proper uses something like the pseudo code below, any try to 'fix' the leak is much worse than the leak itself (we have to do a lot of copy/paste).

```
const char * tools[] = {
	"unshadow", "unafs", "unique", NULL
};

if (find_in_list(name, tools)) {
	CPU_detect_or_fallback(argv, 0);

	if (!strcmp(name, "unshadow"))
		ret = unshadow(argc, argv);

	else if (!strcmp(name, "unafs"))
		ret = unafs(argc, argv);

	else if (!strcmp(name, "unique"))
		ret = unique(argc, argv);

	return ret;
}
```

**Comment by magnumripper** [comment]
What's the original warning/complaint in path.c? Is it some alloc we can turn into alloc_tiny?

**Comment by claudioandre** [comment]
Short: we call path_init() without call path_done();

Message:
```
Index : alloc# :   Size : File(Line)  [first 20 bytes, or size of bytes]
1     : 1      :   4096 : path.c(101)  ../run/.............
```

**Comment by magnumripper** [comment]
OK so it's a leak-once and then we exit anyway. We could fix it just to avoid seeing the complaint (we've done so with other things) but there's no other reason.

**Comment by magnumripper** [comment]
So back to the original issue. We could/should add a mem_realloc with error checking a la mem_alloc but that "miss" itself should not be the problem here.

What are the complaints you see? What is missing? Under a memdbg build, it seems to me (at a quick glance just using grep) that memdbg.h defines realloc as macro pointing to MEMDBG_realloc.

**Comment by claudioandre** [comment]
```
Index : alloc# :   Size : File(Line)  [first 20 bytes, or size of bytes]
0     : 11     :   4096 : zip2john.c(328)  f54860d64e4a5a15c1af
```

Have you noticed this `#if !defined(__MEMDBG__)`?

**Comment by magnumripper** [comment]
Yes but `__MEMDBG__` is only defined when called *from* memdbg.c itself (do not confuse `__MEMDBG__` with eg. `MEMDBG_ON`)

**Comment by magnumripper** [comment]
Ah, OK this is a normal leak-once. It not about realloc, it could have been alloc just as well. We never free Buf - we just let the OS do it for us.

**Comment by magnumripper** [comment]
And that code is subject to change anyway, see https://github.com/magnumripper/JohnTheRipper/issues/2352#issuecomment-265020494

**Comment by claudioandre** [comment]
It was about style or consistency: if I can't use malloc(), then I can't use realloc(). Indeed, it is not a "real leak".

**Comment by magnumripper** [comment]
Agreed, we should add mem_realloc. In fact some of the realloc calls are much more likely to fail than any of the allocs. We have things like `if (size < needed) { size *= 2; realloc(buf, size); }`. So ensuring proper handling of errors (which is slightly more complicated for realloc than for alloc) is a good thing.
