### ISSUE TITLE
Option '--show' doesn't show the cracked passwords for a given password file

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2366]
Note that the 2nd run is lying to me: all passwords were cracked! 
- BTW: the same happens on Linux. I was on (b957228)

```
C:\Users\claud\bleeding\run>john C:\Users\claud\Desktop\hash.txt --show:left

2 password hashes cracked, 0 left

C:\Users\claud\bleeding\run>john C:\Users\claud\Desktop\hash.txt --show
0 password hashes cracked, 2 left
```

### Steps to reproduce
I used these 2 self-test hashes and cracked them
```
$6$ojWH1AiTee9x1peC$QVEnTvRVlPRhcLQCk/HnHaZmlGAAjCfrAN0FtOsOnUk5K5Bn/9eLHHiRzrTzaIKjW9NTLNIBUCtNVOowWS2mN.
$6$saltstring$svn8UoSVapNtMuq1ukKS4tPQd8iKwSMHWjl/O817G3uBnIFNjnQJuesI68u4OTLiBFdcbYEdFCoEOfaS35inz1
```

**Comment by magnumripper** [comment]
I too have seen inconsistencies. I thought they would go away with a54420a5 but they didn't. We probably need to bisect.

**Comment by claudioandre** [comment]
I already know what is wrong, we'll talk about it later. 

BTW: is the situation seen below known?

Hash file:
```
$6$a_valid_hash
$6$a_valid_hash
$gpg$a_valid_hash
$gpg$a_valid_hash
```

I cracked all sha512crypt hashes. To crack gpg, I must use --format, since JtR keeps trying to crack the first hash 'type' listed in the file. The user has to read everything to understand what is going on
And the `No password hashes left to crack (see FAQ)` might fool a few.

**Comment by magnumripper** [comment]
Yeah that's just how it works, from upstream.

**Comment by Hemza** [comment]
Hi, did you resolve the Probleme of message " No password hashes left to crack"
I've dumps sume hashes from windows server 2008 r2 and i can decrypt it with  John

--
root@kali:~/Desktop/JTR# john passsonAdmin.txt --format=LM
Using default input encoding: UTF-8
Using default target encoding: CP850
Loaded 3 password hashes with no different salts (LM [DES 128/128 AVX-16])
No password hashes left to crack (see FAQ)

---

**Comment by claudioandre** [comment]
John told you that:
- it found 3 LM password hashes; and:
- everything is already cracked; so:
- it has **nothing** to do.

Everything seems ok. If you have questions, please, ask for help in the support forum: http://www.openwall.com/lists/john-users/.
