### ISSUE TITLE
documenting interesting .cap file: pcap2john.py does not produce hash

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#2368]
In 3DSCTF, an interesting .cap file was given. `pcap2john.py` does not
produce any output on this file. I am not sure if `pcap2john.py` has
to produce a hash. The password is `RockYousucks`.

But hash may be obtained by other ways:

- `wpapcap2john` produces hash well.

- `aircrack-ng` with option `-J` produces .hccap file that can be converted to john's format using `hccap2john`.

That's all with the following output from `configure` with john 0ceedb24f4941bd06ce56b31398df19aa633a7c1:

```
checking pcap.h usability... no
checking pcap.h presence... no
checking for pcap.h... no
checking pcap/pcap.h usability... no
checking pcap/pcap.h presence... no
checking for pcap/pcap.h... no
checking for pcap.h... (cached) no
checking for pcap/pcap.h... (cached) no
[...]
PCAP (vncpcap2john and SIPdump) ............ no
```

[zechaveiro.cap.zip](https://github.com/magnumripper/JohnTheRipper/files/673232/zechaveiro.cap.zip)

**Comment by kholia** [comment]
`pcap2john.py` does not handle WPA by "design". `wpapcap2john` is the right tool for this job.

**Comment by magnumripper** [comment]
This is sort of a problem though. An ideal pcap2john should handle anything we support or AT LEAST point user to another tool. In this case, it could say something like "run wpapcap2john with this file to get WPA output" or whatever.

**Comment by kholia** [comment]
In addition to recognizing WPA stuff, pcap2john would have to be extended to recognize VNC and SIP stuff as well.

**Comment by kholia** [comment]
I tried solving this using code but no luck. How about adding a startup message to `pcap2john.py` which says something like, "Use wpapcap2john instead of me to extract possible WPA handshakes"?
