### ISSUE TITLE
bitcoin2john.py problem

### ISSUE THREAD

**Issue by kost123** [magnumripper/JohnTheRipper#2377]
Whenever I run it I get this, Have tried 3 different wallets same thing.

```
  File "C:\Users\x\btcrecover-master\bitcoin2john.py", line 639, in parse_wallet

    d.update(parse_BlockLocator(vds))
TypeError: 'NoneType' object is not iterable
```

**Comment by kholia** [comment]
Which type of wallets are you running bitcoin2john.py against? How do I create such a wallet for testing?

**Comment by kost123** [comment]
I fixed it by using "bitcoin tools master" on github and ran fix-wallet, it extracted my keys and created a wallet of old format which worked a charm.(cracked on a test wallet) thanks.
