### ISSUE TITLE
no --fork in JTR jumbo binari (windows)

### ISSUE THREAD

**Issue by kolet** [magnumripper/JohnTheRipper#2378]
hi, so 2 issue here.
1, their is no --fork option in the binary (for windows ) JTR jumbo
2, when running john.exe --format=dahua pw.txt
i received

>       1 [main] john 232912 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
> the public mailing list cygwin@cygwin.com

when rerunning john i am receiving the same error with a different  value for exmpale this num 232912  change each time i run john

thanks

**Comment by claudioandre** [comment]
First of all, which Windows binary are you talking about? Where you got it? GitHub?
- Fork is disabled on JtR MinGW binary for windows.

See also: #2083

**Comment by magnumripper** [comment]
Fork is enabled on systems [and build types] that support it.
