### ISSUE TITLE
office2john.py can't extract password hash for Excel 2003

### ISSUE THREAD

**Issue by amaist** [magnumripper/JohnTheRipper#2381]
I am trying to extract a password hash from Excel 2003 files. office2john.py does not create any output and simply exits with normal status.
For other office files it works fine.

Excel 2013
$ ./office2john.py Workbook2.xlsx 
Workbook2.xlsx:$office$*2013*100000*256*16*2bcd020dd1432ad22bcd020dd1432ad2*795b382cc22e2ffcb1c7cd4073815707*4a1172556ade3d90a7730d93cab050774c03b1382619370e86d4460a3e9d2b4e
Word 2003
$ ./office2john.py testing.doc 
testing.doc:$oldoffice$1*2bcd020dd1432ad22bcd020dd1432ad2*ff12403e5af76ded7a60b8dddd14cb56*35b6b49a82319b027ba3e2d60cb8c38a:::10000 1 1 7 983040 10000 XXX User Normal.dotm XXX User 2 120 13129138020 13129138140 1 1 7 Microsoft Macintosh Word 1::testing.doc
$ ./office2john.py Workbook2.xls
just exits back to the prompt.
I have tried it on Mac OS X Sierra, Windows 7, Freebsd 10.3 with the same result. Mac and FreeBSD with Python 2.7 and Windows with Python 3.3.

I have seen other reports of this issue in various security forums (Hashcat in particular).
Very easy to recreate the issue by saving a password encrypted Excel file with modern Excel (2015 or later versions on both Mac and Windows).

Thanks,

Andrei

**Comment by magnumripper** [comment]
Are you using latest office2john.py from GitHub? It was last updated November 7, 2016.

**Comment by amaist** [comment]
I apologize. I did not use the latest version and didn't properly check. I assumed I did.

The latest version works. I will close the issue now.
Sorry to waste your time.

**Comment by magnumripper** [comment]
NP, I'm delighted to hear it's working!
