### ISSUE TITLE
pdf2john.py generates unrecognized hashes.

### ISSUE THREAD

**Issue by ubitux** [magnumripper/JohnTheRipper#2388]
Using LibreOffice I created a pdf with a password but `pdf2john.py` generates unrecognized hashes:

```
[/tmp]☭ /usr/lib/john/pdf2john.py test.pdf > test.hash
[/tmp]☭ cat test.hash
test.pdf:$pdf$2*3*128*-1028*1*16*f2e3a4118491798c81904096dbc67300*:::::test.pdf
[/tmp]☭ john test.hash
No password hashes loaded (see FAQ)
[/tmp]☭ 
```

Notes:
- here `test.pdf` has 2 passwords, "foo" and "bar" respectively for read and editing according to LibreOffice.
- both `mupdf -p foo test.pdf` and `mupdf -p bar test.pdf` work (but not any other password)
- the issue is reproducible with only one password set
- `pdf2john.py` + `john` seems to work fine with another encrypted pdf I have

```[/tmp]☭ john --list=build-info
Version: 1.8.0-jumbo-1 MPI + OMP
Build: linux-gnu 64-bit AVX-autoconf
Arch: 64-bit LE
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
$JOHN is /usr/share/john/
Format interface version: 12
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
Compiler version: 6.2.1 20160830
gcc version: 6.2.1
OpenCL library version: 1.2
OpenSSL library version: 0100020af
OpenSSL 1.0.2j  26 Sep 2016
GMP library version: 6.1.1	(loaded: 6.1.2)
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by kholia** [comment]
Can you give https://github.com/kholia/npdf2john a try instead of pdf2john.py?

**Comment by ubitux** [comment]
`npdf2john` works fine here, `john` figures out the "foo" password from it.

**Comment by kholia** [comment]
@magnumripper We should try to merge https://github.com/kholia/npdf2john into bleeding-jumbo. I will open a PR soon.

**Comment by magnumripper** [comment]
So we can close this now, right?

**Comment by magnumripper** [comment]
> So we can close this now, right?

Perhaps not until we actually merge that PR though 😆

**Comment by cchristion** [comment]
I used npdf2john, but still getting the same string

Pdf2john
pdf:$pdf$2*3*128*-1852*1*16*617fb7c2e2dfe7a1a728a24559b97f2d*32*bfe39e32595b91601aad564d2c5897c800000000000000000000000000000000*32*2e24196b68073e33e6f36768f8e03d39923cc66b9cfa32b9768f87798eb19722

npdf2john
pdf:$pdf$2*3*128*-1852*1*16*617fb7c2e2dfe7a1a728a24559b97f2d*32*bfe39e32595b91601aad564d2c5897c800000000000000000000000000000000*32*2e24196b68073e33e6f36768f8e03d39923cc66b9cfa32b9768f87798eb19722

**Comment by magnumripper** [comment]
@clarychristionc hi-jacking an ancient (and closed) issue for unrelated problems is not great. The tool is called `pdf2john.pl` since January 2017. I assume you're not using the latest version? Try that for a starter.

Anyway it will probably output the same hash - and john will be able to crack it. I just tried loading the string(s) you posted and it loaded just fine. Not to mention it cracked in three seconds...
