### ISSUE TITLE
bleeding-jumbo compile fails with: undefined reference to `fmt_enpass'

### ISSUE THREAD

**Issue by bill-e-ghote** [magnumripper/JohnTheRipper#2391]
Note: I've been building JtR using the following steps without issue for a couple of years at least. I don't often run into build issues.

My environment:
Gentoo w/ Pentoo overlay.

I'm building John from bleeding-jumbo, updated immediately prior to setting environment, 'make clean', and then 'make'.

I set my environment accordingly:
./configure --disable-openmp

And several additional Makefile / params.h localizations not relevant to this issue.

The build appears to be normal until the final linking step:

john.o: In function `john_register_all':
/home/wdawson/Software/bleeding-jumbo/src/fmt_registers.h:43: undefined reference to `fmt_enpass'

**Comment by magnumripper** [comment]
OK you did say you did a make clean. Then I can't really see what could be wrong here.

**Comment by magnumripper** [comment]
I now tried `./configure --disable-openmp --disable-opencl` but still can't reproduce.

**Comment by bill-e-ghote** [comment]
I did another 'git pull' and rebuilt it with no errors. Whatever the issue, it was just a temporary glitch, apparently.

Thanks.

**Comment by magnumripper** [comment]
Cool!
