### ISSUE TITLE
CircleCI-MinGW.sh appends .exe extension to directories

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2397]
Inside our MinGW builds, I see that the directories in the `run` directory have `.exe` extension appended to their names. This breaks stuff.

```
# the mingw build does not name many exe files correctly.  Fix that.  Also strip all exe files for distro.
cd ../run
for f in `ls -l | grep wxr | grep -v [\.][epr] | cut -c 46-` ; do mv $f $f.exe ; done
for f in benchmark-unify mailer makechr relbench ; do mv $f.exe $f ; done
```

Download a build from http://daily-builds.appspot.com/latest URL to confirm this.

**Comment by claudioandre** [comment]
I've noticed this. In fact, if your hands are dirty:
* you can also see some errors 'Makefile.legacy' related (search for "error:").

And (it is my opinion only):
* better than `circle.yml` points to `username/fedora`, it should point to `fedora:25` or `fedora:latest`;
* then all `dnf install` is going to be inside **CircleCI-MinGW.sh**
* so, the "JtR maintainer" won't have to create an account on https://hub.docker.com/ site.

**Comment by kholia** [comment]
If `circle.yml` uses `fedora:latest` or `fedora:25`, then the package installation (`dnf install`) will take a huge amount of time and bandwidth.

**Comment by kholia** [comment]
@claudioandre I see the "error:" messages in the CircleCI build logs. I will try to fix them.

**Comment by kholia** [comment]
OK, all the "error:" messages are gone from the CircleCI builds. See PR #2401 for the fix involved.
