### ISSUE TITLE
dynamic_62 sha-256 salt issue ? 

### ISSUE THREAD

**Issue by rockygsm** [magnumripper/JohnTheRipper#2399]
info details

```
> 1 [main] john 3968 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
> the public mailing list cygwin@cygwin.com
> Version: 1.8.0-jumbo-1 OMP
> Build: cygwin 32-bit SSSE3-autoconf
> Arch: 32-bit LE
> $JOHN is
> Format interface version: 12
> Max. number of reported tunable costs: 3
> Rec file version: REC4
> Charset file version: CHR3
> CHARSET_MIN: 1 (0x01)
> CHARSET_MAX: 255 (0xff)
> CHARSET_LENGTH: 24
> Max. Markov mode level: 400
> Max. Markov mode password length: 30
> Compiler version: 4.5.3
> gcc version: 4.5.3
> OpenSSL library version: 00090812f
> OpenSSL 0.9.8r 8 Feb 2011
> fseek(): fseeko
> ftell(): ftello
> fopen(): _fopen64
> memmem(): System's
```
my hash $dynamic_62$3E8A5C3E0C867640EA3F289244BBDAC93B89E40BE8B3160063587DA6AC4312B4$HEX$000000000000000000000000000000000000000000000000
i know result is 3638303733393230000000000000000000000000000000000000000000000000
don't know why JTR not able to load hash..
always error "No password hashes loaded (see FAQ)"
i made deep check look like SALT SIZE issue any way to over come this with command line ? or i must rebuild it my own ?
i am using john180j1w on windows command line version..

**Comment by kholia** [comment]
1. Get latest Windows build from http://daily-builds.appspot.com/latest URL.

2. Run `john.exe --format=dynamic_62 hashes.txt`

While your sample hash loads in JtR, I believe that either the posted salt is wrong or the posted password is wrong. Post the correct hash and password. Also note that `dynamic_62` is `sha256($p.$s)`.

**Comment by rockygsm** [comment]
link u give is showing 503
my input is 3638303733393230000000000000000000000000000000000000000000000000
= 3E8A5C3E0C867640EA3F289244BBDAC93B89E40BE8B3160063587DA6AC4312B4
what is wrong in my input ?

**Comment by rockygsm** [comment]
ok your build work. and hash got cracked. its bug or limit ?

**Comment by kholia** [comment]
The http://daily-builds.appspot.com/latest URL is facing some problems. It would be fixed soon.

If the hash got cracked using the latest build, there is no bug or limit, right?

**Comment by rockygsm** [comment]
Yes 100%

**Comment by kholia** [comment]
UPDATE: http://daily-builds.appspot.com/latest should be a lot more stable now. https://github.com/kholia/daily-builds has the latest source code for the "daily-builds" service.
