### ISSUE TITLE
Add support for Apple iTunes Backup

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2405]
See https://github.com/philsmd/itunes_backup2hashcat repository.

It seems @philsmd has decided to use `*` as field delimiter and `$something$*` as FORMAT_TAG in the new hash format. My mistakes from the past are propagating!

**Comment by magnumripper** [comment]
To the dark side he has looked 😆

**Comment by magnumripper** [comment]
Spot the field delimiter
```
b109105f5fe0b899$d4f96690b1a8fe1f120b0290a85a2121

b109105f5fe0b899*d4f96690b1a8fe1f120b0290a85a2121
```

**Comment by kholia** [comment]
True, spotting "*" is much easier than spotting "$" :-)

**Comment by kholia** [comment]
PR #2410 adds support for cracking Apple iTunes Backup hashes.

**Comment by kholia** [comment]
Merged the PR, closing this issue.
