### ISSUE TITLE
iwork-opencl: GPU-side AES and verify enhancement

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2407]
@magnumripper `iwork-opencl` also seems like a good candidate for GPU-side AES and verify enhancement.

**Comment by kholia** [comment]
It seems that I would have been able to tackle this one myself :-) Since this ticket is assigned to you now, I will wait for updates from your side.

**Comment by magnumripper** [comment]
By all means, go ahead!

**Comment by kholia** [comment]
I gave it a shot, and I got a performance decrease on my GTX 960!

https://github.com/kholia/JohnTheRipper/tree/Pure-GPU-iWork has the corresponding code (top commit).

Also the Desktop interactivity is worse due to use of the "unsplit" PBKDF2 kernel.

@magnumripper any tips / thoughts?

**Comment by magnumripper** [comment]
I'm looking at it. Meanwhile, have a look at 5bb3e572 if you like

**Comment by magnumripper** [comment]
I see no obvious reason for it to be slower. It really should be faster.

Perhaps try `#define BENCHMARK_LENGTH        -1` instead. That way, the benchmark will be made with incorrect passwords, so we can early reject. That's a better figure anyway so perhaps that should be the default.

**Comment by magnumripper** [comment]
Updated previous comment to read -1001 and not -1

**Comment by magnumripper** [comment]
Also, have a look at the autotune figures with `-test -verb=5` and see if you should tune HASH_LOOPS. We should have our "wanted" GWS at about 100-200ms duration of the loop kernel. Not too small, not too large. 

Hmmm no wait. You actually switched from the split kernel to the obsolete crappy unsplit one. That was a bad idea! Have a look at recent enpass format instead. You should never ever use the unsplit kernel in a new format! In fact we should try to move all formats to the split kernel.

**Comment by magnumripper** [comment]
I think you could re-write iworks-opencl from scratch based on the enpass format (host code and kernel) with very little effort.

**Comment by kholia** [comment]
Thanks, I am on it.

**Comment by kholia** [comment]
The new versions (based on enpass-opencl and the "split' PBKDF2 kernel) is [here](https://github.com/kholia/JohnTheRipper/tree/Pure-GPU-iWork-v2) (top commit).

The speed of this pure GPU format is almost the same as the original iwork-opencl format! This format is too slow (< 10K c/s on GTX 960) and almost all of the time is taken by the PBKDF2 running on the GPU. Hence we are not gaining much by moving AES + SHA256 (both are lightweight operations compared to PBKDF2) to the GPU.

**Comment by kholia** [comment]
Opened PR #2417 with this new code.

**Comment by magnumripper** [comment]
Even if gain was small, GPU-only is better. And again, I haven't even started optimizing the AES yet...

**Comment by kholia** [comment]
@magnumripper PR #2417 is currently failing in Travis CI. I can't locate the source of the problem. It would be great if you could take a look at it.

**Comment by magnumripper** [comment]
Will do within (hopefully) 24h

**Comment by kholia** [comment]
This is done now. Closing the issue.
