### ISSUE TITLE
"leet" format fails on Debian PPC64 BE

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2414]
```
$ ../run/john --test=0
...

Testing: leet [SHA-512(32/32 OpenSSL) + Whirlpool(OpenSSL/32)]... Warning: binary() returned misaligned pointer
FAILED (get_hash[0](0) e!=8)
```

The following patch fixes the warning but the failure persists.

```
$ git diff
diff --git a/src/leet_cc_fmt_plug.c b/src/leet_cc_fmt_plug.c
index 7e015c0..3e334f5 100644
--- a/src/leet_cc_fmt_plug.c
+++ b/src/leet_cc_fmt_plug.c
@@ -195,7 +195,7 @@ static void *get_salt(char *ciphertext)
 static void *get_binary(char *ciphertext)
 {      static union {
                unsigned char c[BINARY_SIZE+1];
-               ARCH_WORD dummy;
+               uint64_t dummy;
        } buf;
        int i;
        unsigned char *out = buf.c;
```

```
$ uname -a
Linux debian 3.16.0-4-powerpc64 #1 SMP Debian 3.16.39-1 (2016-12-30) ppc64 GNU/Linux
```

**Comment by solardiz** [comment]
On Thu, Feb 02, 2017 at 06:40:28AM -0800, Dhiru Kholia wrote:
> -               ARCH_WORD dummy;
> +               uint64_t dummy;

If this makes a difference at all, I suspect that our configure script
defines ARCH_WORD incorrectly on that platform (not as 64-bit) - please
review the generated arch.h.

**Comment by kholia** [comment]
I am not using configure on this machine. The configure method resulted in too many weird compilation errors.

Instead I did,

```
$ make -f Makefile.legacy linux-ppc32
```

```
$ cat arch.h
...
 * Architecture specific parameters for 32-bit PowerPC.
...
#define ARCH_WORD                       long
#define ARCH_SIZE                       4
#define ARCH_BITS                       32
```

 Note that Debian PPC64 uses a 64-bit kernel with 32-bit user space. `sizeof(long)` is returning 4, while we have `#define BINARY_ALIGN sizeof(uint64_t)`, thus resulting in the misaligned pointer warning.

**Comment by solardiz** [comment]
On Thu, Feb 02, 2017 at 07:12:06AM -0800, Dhiru Kholia wrote:
> `sizeof(long)` is returning 4, while we have `#define BINARY_ALIGN sizeof(uint64_t)`, thus resulting in the misaligned pointer warning.

This BINARY_ALIGN is unnecessarily too high, then.  Perhaps both places should use either uint32_t or ARCH_WORD, then.

(Not that this would solve the original issue.)

**Comment by kholia** [comment]
For some unknown reason, the `SecureMode` feature is getting turned on this Debian 8 PPC64 BE system. I have `SecureMode = N` set in `john.conf` file.

**Comment by solardiz** [comment]
> For some unknown reason, the SecureMode feature is getting turned on this Debian 8 PPC64 BE system. I have SecureMode = N set in john.conf file.

This suggests an out-of-bounds write somewhere. Really nasty.

Regarding the alignments (previous comments), certainly the data type used in `BINARY_ALIGN` and in the union in `get_binary()` should be the same. Right now they're still different. Since you cast to `uint64_t` in `cmp_all()` and `cmp_one()`, that should be the type to use in both places.

**Comment by kholia** [comment]
> This suggests an out-of-bounds write somewhere. Really nasty.

I hope there is a simpler explanation for this (i.e. some PEBKAC).

I don't think that Address Sanitizer is available on this PPC64 Debian 8 VM. I will try some debugging things tomorrow morning.

**Comment by solardiz** [comment]
What kind of VM is that? Is it running on PPC64 hardware or is it emulated on some other CPU arch?

**Comment by kholia** [comment]
It is an emulated system. I am running `qemu-system-ppc64` on a standard x86-64 Linux box. It is somewhat slow but it works fine if one is patient.
