### ISSUE TITLE
Investigate a TS failure with recent agilekeychain-opencl

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2428]
https://github.com/magnumripper/JohnTheRipper/pull/2427#issuecomment-280461624

7fa10101 works
```
$ ./jtrts.pl agilekeychain-opencl
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, JimF & others
- Testing:  John the Ripper v3-2953-g7fa1010 OMP [darwin16.4.0 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=agilekeychain-opencl         guesses: 1200 0:00:00:21 DONE  [PASSED]

All tests passed without error.  Performed 1 tests.  Time used was 23 seconds
```

Latest:
```
$ ./jtrts.pl agilekeychain-opencl
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, JimF & others
- Testing:  John the Ripper v3-2983-g6bc03fd OMP [darwin16.4.0 64-bit AVX-ac]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=agilekeychain-opencl         guesses:  780 -show= 780 0:00:00:25 DONE : Expected count(s) (1200)(1500)  [!!!FAILED1!!!  ret_val=0]

Some tests had Errors. Performed 1 tests.  1 errors
Time used was 27 seconds
```

**Comment by magnumripper** [comment]
OK this is only due to PLAINTEXT_LENGTH being shortened to 28. I will update TS. The rationale is we got a slight boost in speed for single-salt and very few [crackable] passwords are longer than that anyway.

**Comment by jfoug** [comment]
ANY time the TS still gets some, but not all, and especially if there is more than 1 acceptable count already in the TS, the first thing to check is the plain length and see if it was reduced.  Then it is as simple as running that length script (I think it is in the test folder), and figuring out if the input file is a solid 1500 candidates, or if it is some smaller 'subset' run over and over with different salts. Then you can figure out what the proper value for the expectations are.  98 out of 100 times, it is correct, and simply needs to expect that number of cracks.

Btw, 28 cracks 99.9% of ITW passwords anyway.  One notable exception would be many corp secure wireless, where they are a random string of 63 bytes for the WPA stuff, and they simply place the key hash hexes (mic and something else I think) on a clients network setup.  But lets see ANY computer crack 63 random bytes of WPA2 ;)   The sun will burn out first (probably billions of times).
