### ISSUE TITLE
GPG2John says "Can't open .key" 

### ISSUE THREAD

**Issue by bosssmen** [magnumripper/JohnTheRipper#2438]
I've been trying to get the hash to my PGP private key and no matter what syntax I put i keep getting returned with either "can't open key" or  "Illegal Radix"

"Conversion Failed
Illegal radix64 character
(1024 bytes) partial start
unexpected end of file."

**Comment by kholia** [comment]
Upload a sample private key file which demonstrates this problem.

This issue sounds a bit like a support request to me.
