### ISSUE TITLE
Could not find /ID tag

### ISSUE THREAD

**Issue by Chintu91** [magnumripper/JohnTheRipper#2443]
When i run pdf2john.py for get pdf hash then i show the error
root@kali:~/JohnTheRipper/run# ./pdf2john.py /root/Desktop/a1.pdf> /root/Desktop/key.txt 
/root/Desktop/a1.pdf : Could not find /ID tag

**Comment by kholia** [comment]
Use `pdf2john.pl` script (from this repository) instead of `pdf2john.py`. Do report back if this fixes the problem.

**Comment by Chintu91** [comment]
Sorry for my bed


Thank you
Sir
