### ISSUE TITLE
can't start john

### ISSUE THREAD

**Issue by caledot** [magnumripper/JohnTheRipper#2446]
### Steps to reproduce

My environment: Ubuntu 14.04 in windows 10
What I'm doing: just finished the 'make' phase and runned the test command

### System configuration
I've just installed Jumbo but i cannot start John in any way. Everytime i try to start it, even to get report of my build info i got the following error:

![image](https://cloud.githubusercontent.com/assets/25247851/23791797/b0231a86-0584-11e7-8370-83c9ec445bfa.png)

How can I solve this?

Thanks in advance

**Comment by kholia** [comment]
Please think carefully about what you are doing. Do not create new issues. Use the existing one.

**Comment by caledot** [comment]
Ah ok sorry, the page crashed during editing so i didn't get any feedback if the mods on the previous one went well.
But any clue on how to solve my issue?
