### ISSUE TITLE
Error compiling gpg2john.c on Debian Stretch

### ISSUE THREAD

**Issue by BenderIsTheGreatest** [magnumripper/JohnTheRipper#2449]
Hello,

I got the following error when I tried to compile

> Configure finished.  Now 'make clean && make -s' to compile.
gpg2john.c: In function ‘Compressed_Data_Packet’:
gpg2john.c:2953:12: error: ‘Z_OK’ undeclared (first use in this function)
  int err = Z_OK;
            ^~~~
gpg2john.c:2953:12: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1514: recipe for target 'gpg2john.o' failed
make[1]: *** [gpg2john.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:171: recipe for target 'default' failed
make: *** [default] Error 2

I got all the right libs installed(I checked [it here](http://openwall.info/wiki/john/tutorials/Ubuntu-build-howto)) and am using Debian Stretch and I am not sure what to do to fix this.

**Comment by kholia** [comment]
Try the following steps,

```
$ sudo apt-get install zlib1g-dev

$ ./configure  # yes, re-run this

$ make -j8
```

**Comment by kholia** [comment]
Here is a patch which fixes this problem,

```
index a881305b6..e04d72923 100644
--- a/src/gpg2john.c
+++ b/src/gpg2john.c
@@ -2948,7 +2948,7 @@ set_binary(void)
 public void
 Compressed_Data_Packet(int len)
 {
-#if HAVE_LIBZ || HAVE_LIBBZ2
+#if HAVE_LIBZ // || HAVE_LIBBZ2
        unsigned int alg = Getc();
        int err = Z_OK;
        private int (*func)(byte *, unsigned int);
```

`Z_OK` comes from `zlib1g-dev`. If `zlib1g-dev` is not installed (like in this case) but `libbz2-dev` is installed, we run into this compilation error.

**Comment by kholia** [comment]
Better patch,

```
diff --git a/src/gpg2john.c b/src/gpg2john.c
index a881305b6..6f974a074 100644
--- a/src/gpg2john.c
+++ b/src/gpg2john.c
@@ -2950,7 +2950,7 @@ Compressed_Data_Packet(int len)
 {
 #if HAVE_LIBZ || HAVE_LIBBZ2
        unsigned int alg = Getc();
-       int err = Z_OK;
+       int err = 0; // both Z_OK and BZ_OK are 0
        private int (*func)(byte *, unsigned int);
 
        comp_algs(alg);
```

**Comment by BenderIsTheGreatest** [comment]
> $ sudo apt-get install zlib1g-dev
$ ./configure  # yes, re-run this
$ make -j8

did work, thanks. I didn't know I needed that lib
