### ISSUE TITLE
Travis CI, build and test JtR jumbo on OS X / macOS

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2454]
https://docs.travis-ci.com/user/osx-ci-environment/ is helpful. https://docs.travis-ci.com/user/multi-os/ is another useful link.

@claudioandre is this something which interests you?

**Comment by claudioandre** [comment]
No

**Comment by kholia** [comment]
OK :-)

I will try to tackle it some day then.

**Comment by kholia** [comment]
This is done now.
