### ISSUE TITLE
Add OpenCL support for cracking KeePass files

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2471]
The KDF of KeePass is pretty unique and the work intensive parts of the KDF involve AES.

**Comment by magnumripper** [comment]
I intend to look into this

**Comment by magnumripper** [comment]
a666e7e was a start

**Comment by magnumripper** [comment]
Dang, many moving parts here. Maybe it's all set now.

**Comment by magnumripper** [comment]
#3131

**Comment by magnumripper** [comment]
Final 1st version in fd81ff0b6 but with bot-checks disabled in 1e11797.
