### ISSUE TITLE
1.8.0.9-jumbo-1-bleeding vs. 1.8.0-jumbo-1-5577-g80eddc3 vs. 1.8.0.6-jumbo-1-2970-g80eddc3 

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2481]
When I create a new git clone, the version is 
```
(bleeding-jumbo)run $ ./john --list=build-info |head -n 1
Version: 1.8.0-jumbo-1-5577-g80eddc3
```
When I download https://github.com/magnumripper/JohnTheRipper/archive/bleeding-jumbo.tar.gz and build that binary, I get 
```
[run]$ ./john --list=build-info |head -n 1
Version: 1.8.0.9-jumbo-1-bleeding
```
So, it looks as if the version from the tar.gz file were newer (1.8.0.9-jumbo-1) than the version built from within the git repo (1.8.0-jumbo-1).

This is confusing and unfortunate.

With latest git (my current local repo), I get
```
(bleeding-jumbo)run $ ./john --list=build-info |head -n 1
Version: 1.8.0.6-jumbo-1-2970-g80eddc3
```
Some of the tags I have in my local repo have been deleted from the github repo:
```
(bleeding-jumbo)src $ git ls-remote|grep refs/tags
From https://github.com/magnumripper/JohnTheRipper
f4d54902e4aecafa2bdd2862a82633d5c50c0e66	refs/tags/1.7.8-jumbo-8
7bc55484f585c61cea21e922f231801413ceb30a	refs/tags/1.7.8-jumbo-8^{}
7894cc8e3052793020db34f4648182a890d8ba7e	refs/tags/1.7.9
cad3b0ec43b6b9af0eb478bed0e84e1461d7e412	refs/tags/1.7.9-jumbo-3
57a0e272bbba7187b3240c9c605281100b97515f	refs/tags/1.7.9-jumbo-4
488196c0a4919aa57e28f9bb00751e2ee97a30cc	refs/tags/1.7.9-jumbo-5
86e029712c563e27817b22384dd8599cd04b7292	refs/tags/1.7.9-jumbo-6
0ef286ee95d3e6df3246a19a3172a5ce7500fb56	refs/tags/1.7.9-jumbo-7
2e21c3f7bed68057e560ce45adeb014c6eb7e97c	refs/tags/1.8.0
35759de401951341b51b3bfeae2694fa50024315	refs/tags/1.8.0-jumbo-1
5fd8f688b695669951a3b0d406dd0bb5832d6d06	refs/tags/JOHN_1_7
fe5eccfa05b1d2f0646e563c7e33060dafd7a6ba	refs/tags/JOHN_1_7_8
4ab25da040252d4b1af82d134d750921532deb68	refs/tags/Owl-1_0-release
7c7af197628f608ca305bfda2787e948e45c8a84	refs/tags/Owl-1_1-release
03fa029f810c065f79edcdd1af465266538d7274	refs/tags/Owl-3_0-release
```
I do remember we had a discussion about tags some time ago.

https://github.com/magnumripper/JohnTheRipper/issues/1788 describes that @magnumripper deleted those tags, and that `git tag -d` can be used in the local repositories to get rid of these tags. 

https://github.com/magnumripper/JohnTheRipper/issues/1802 mentions that these tags were deleted because github will list any tag as a "release". Where can I see that list of "releases"?

When these tags were deleted, it would have been better to adjust the JOHN_VERSION definition in params.h as well, so that it doesn't report "1.8.0.9-jumbo-1-bleeding" any longer.

Unfortunately, the latest builds of windows binaries by Robert B. Harris, announced on john-users, also report version 1.8.0.9-jumbo-1-bleeding. 

I guess the current situation will only improve after the next "official" jumbo release.
But if the next jumbo release is based on 1.8.0.9, it will be difficult to distinguish the 1.8.0.9-jumbo-1-bleeding builds created before that jumbo release from those created after the release.

BTW: the latest release tag in the master branch is 1.8.0:
```
 (master)src $ git describe --tags 
1.8.0-1061-g1816b2c
```

**Comment by kholia** [comment]
https://github.com/magnumripper/JohnTheRipper/releases (list of "releases").

**Comment by frank-dittrich** [comment]
Assuming that github is using `git archive` to create the .tar.gz or .zip archives, we could also try something similar to what hashcat seems to be doing:

```
(master)hashcat $ cat .gitattributes
src/Makefile export-subst
(master)hashcat $ grep -n '\$Format:' src/Makefile 
117:VERSION_EXPORT          := $Format:%D$
(master)hashcat $ git grep -n VERSION_EXPORT
src/Makefile:117:VERSION_EXPORT          := $Format:%D$
src/Makefile:118:VERSION_TAG             := $(shell test -d .git && git describe --tags --dirty=+ || echo "$(VERSION_EXPORT)"|cut -d, -f2|$(SED) -r 's|.* (\w+/)?([^ ]+)|\2|')
(master)hashcat $ git grep -n VERSION_TAG
src/Makefile:118:VERSION_TAG             := $(shell test -d .git && git describe --tags --dirty=+ || echo "$(VERSION_EXPORT)"|cut -d, -f2|$(SED) -r 's|.* (\w+/)?([^ ]+)|\2|')
src/Makefile:375:       $(CC)    $(CFLAGS_NATIVE) $^ -L. -lhashcat $(LFLAGS_NATIVE) -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\" -DINSTALL_FOLDER=\"$(INSTALL_FOLDER)\" -DSHARED_FOLDER=\"$(SHARED_FOLDER)\" -DDOCUMENT_FOLDER=\"$(DOCUMENT_FOLDER)\" -o $@
src/Makefile:378:       $(CC)    $(CFLAGS_NATIVE) $^               $(LFLAGS_NATIVE) -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\" -DINSTALL_FOLDER=\"$(INSTALL_FOLDER)\" -DSHARED_FOLDER=\"$(SHARED_FOLDER)\" -DDOCUMENT_FOLDER=\"$(DOCUMENT_FOLDER)\" -o $@
src/Makefile:398:       $(CC_LINUX_32) $(CFLAGS_CROSS_LINUX32)    -o $@ $^ $(LFLAGS_CROSS_LINUX32) -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\" -DINSTALL_FOLDER=\"$(INSTALL_FOLDER)\" -DSHARED_FOLDER=\"$(SHARED_FOLDER)\" -DDOCUMENT_FOLDER=\"$(DOCUMENT_FOLDER)\"
src/Makefile:401:       $(CC_LINUX_64) $(CFLAGS_CROSS_LINUX64)    -o $@ $^ $(LFLAGS_CROSS_LINUX64) -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\" -DINSTALL_FOLDER=\"$(INSTALL_FOLDER)\" -DSHARED_FOLDER=\"$(SHARED_FOLDER)\" -DDOCUMENT_FOLDER=\"$(DOCUMENT_FOLDER)\"
src/Makefile:404:       $(CC_WIN_32)   $(CFLAGS_CROSS_WIN32)      -o $@ $^ $(LFLAGS_CROSS_WIN32)   -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\"
src/Makefile:407:       $(CC_WIN_64)   $(CFLAGS_CROSS_WIN64)      -o $@ $^ $(LFLAGS_CROSS_WIN64)   -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\"
src/Makefile:410:       $(CC_WIN_32)   $(CFLAGS_CROSS_WIN32)      -o $@ $^ $(LFLAGS_CROSS_WIN32)   -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\" -shared
src/Makefile:413:       $(CC_WIN_64)   $(CFLAGS_CROSS_WIN64)      -o $@ $^ $(LFLAGS_CROSS_WIN64)   -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\" -shared
src/main.c:967:    printf ("%s\n", VERSION_TAG);
src/main.c:981:  welcome_screen (hashcat_ctx, VERSION_TAG);
```
For a list of format placeholders, see `man git log`, section `PRETTY FORMATS`
We could use `"$Format:%h$"` as part of the version string for builds based on downloaded bleeding-jumbo archives.
  
That should avoid possible confusion.

**Comment by frank-dittrich** [comment]
See https://github.com/frank-dittrich/JohnTheRipper/commit/82bd82a88ab73a2233a8b4697a47e16ac946c377 as an example.

Building john based on a bleeding-jumbo archive download would result in this output:
```
[fd@f24x run]$ ./john --list=build-info |head -n 1
Version: 1.8.0-jumbo-1-bleeding-g82bd82a 2017-03-24T15:27:40+01:00
```

**Comment by magnumripper** [comment]
> We could use "$Format:%h$" as part of the version string for builds based on downloaded bleeding-jumbo archives.

I don't understand that string at all. What is it, what does it affect, what is the result? Is it a gmake thing?

**Comment by magnumripper** [comment]
> But if the next jumbo release is based on 1.8.0.9, it will be difficult to distinguish the 1.8.0.9-jumbo-1-bleeding builds created before that jumbo release from those created after the release.

The ones after will be called 1.8.0-jumbo-2 so should be very easy to distinguish. Or do I miss something?

**Comment by frank-dittrich** [comment]
> I don't understand that string at all. What is it, what does it affect, what is the result? Is it a gmake thing?

@magnumripper That `$Format:...$` string only has a "meaning" if there's also a `.gitattributes` line with the ` export-subst` keyword. Then these format strings are substituted when creating an archive file (tar/zip).

Check `man 1 git-archive`, especially the explanation of `export-subst` in the `ATTRIBUTES` section:

`If the attribute export-subst is set for a file then Git will expand several placeholders when adding this file to an archive. See gitattributes(5) for details.`

See also my commit https://github.com/frank-dittrich/JohnTheRipper/commit/82bd82a88ab73a2233a8b4697a47e16ac946c377.

Now, if you download https://github.com/frank-dittrich/JohnTheRipper/archive/bleeding-jumbo.tar.gz or https://github.com/frank-dittrich/JohnTheRipper/archive/bleeding-jumbo.zip, you'll get an archive file where params.h doesn't contain the string `$Format:-g%h %cI$`, so that with the appropriate substitutions done automatically by `git archive`, `JOHN_VERSION` will be defined as `"1.8.0-jumbo-1-bleeding-g82bd82a 2017-03-24T15:27:40+01:00"`. and if new commits are added on top of https://github.com/frank-dittrich/JohnTheRipper/commit/82bd82a88ab73a2233a8b4697a47e16ac946c377, the version string with have the information about the latest commit and its commit time stamp.

**Comment by frank-dittrich** [comment]
> The ones after will be called 1.8.0.x-jumbo-2-bleeding so should be very easy to distinguish. Or do I miss something?

Depends on the 'x'. As long as x >= 9, you are probably right - until @solardiz creates new core releases. Then, JOHN_VERSION might again be misleading.

**Comment by magnumripper** [comment]
So if using a tree not downloaded as an archive, params.h would contain the strange string, but the way hashcat does it should work around that. I think I get it. We should do this to Makefile.in and leave params.h alone. Also, I think the timestamp is overkill (and too long), we should just use the commit hash.

**Comment by frank-dittrich** [comment]
In the Makefile, you cold just use the commit date instead of the complete timestamp.
While we would be able to find out how old a build is based on the commit hash, a regular user wouldn't.

**Comment by frank-dittrich** [comment]
May be we could also use ` export-ignore` in `.gitattributes` to exclude some files or directories from the archives, e.g. 
```
circle.yml
.github
.gitignore
.gitmodules
.mailmap
.pre-commit.sh
.travis
.travis.yml
```

**Comment by magnumripper** [comment]
That's a good idea

**Comment by frank-dittrich** [comment]
The issues mentioned here have been fixed with https://github.com/magnumripper/JohnTheRipper/pull/3017, closing
