### ISSUE TITLE
Whitespace problems in src (CRLF line endings etc.)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2484]
```
(bleeding-jumbo)JohnTheRipper $ find . -type f -exec file \{\} \; |grep CRLF
./src/john.asm: ASCII text, with CRLF line terminators
./src/ztex/pkt_comm/inpkt.c: C source, ASCII text, with CRLF line terminators
./src/ztex/pkt_comm/word_gen.c: C source, ASCII text, with CRLF line terminators
./src/ztex/pkt_comm/cmp_config.c: C source, ASCII text, with CRLF line terminators
./src/ztex/pkt_comm/word_list.c: C source, ASCII text, with CRLF line terminators
./src/ztex/pkt_comm/Makefile.in: makefile script, ASCII text, with CRLF line terminators
./src/ztex/pkt_comm/pkt_comm.c: C source, ASCII text, with CRLF line terminators
./src/ztex/jtr_device.c: C source, ASCII text, with CRLF line terminators
./src/ztex/device.c: C source, ASCII text, with CRLF line terminators
./src/ztex/ez-usb/README: ASCII text, with CRLF line terminators
./src/ztex/ez-usb/inouttraffic.ihx: ASCII text, with CRLF line terminators
./src/ztex/device_format.c: C source, ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/word_gen_v2.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/inpkt_header.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/template_list.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/pkt_comm_input.vh: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/outpkt_v2.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/range_info_process.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/word_gen_char_range.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/pkt_comm_test.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/range_insert.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_comm/outpkt_checksum.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/main.vh: ASCII text, with CRLF line terminators
./src/ztex/fpga/util/cdc_reg.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/util/sync.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/util/global_wires.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/pkt_test/pkt_test.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/clocks.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/ztex_inouttraffic.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/ztex_inouttraffic.xds: XML 1.0 document, ASCII text, with very long lines, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/startup_spartan6.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/cmt_common.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/ztex_inouttraffic.ucf: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/vcr.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/output_limit_fifo.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/output_fifo.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/input_fifo.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/chip_select.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/cmt2.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/async2sync.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/ztex_inouttraffic/hs_io_v2.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/core_dout_proc.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/cmp_config.v: BSD makefile script, ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/pkt_comm_descrypt_test.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt.ucf: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt.v: BSD makefile script, ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/arbiter.v: BSD makefile script, ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/pkt_comm_test.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/wrapper.v: BSD makefile script, ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/descrypt16.v: BSD makefile script, ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/IP1.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/descrypt_core.v: BSD makefile script, ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/crypt3_ascii2bin.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/rotate_1or2_pc2.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/pc1.v: ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/descrypt_round.v: BSD makefile script, ASCII text, with CRLF line terminators
./src/ztex/fpga/descrypt/descrypt_core/SP_v2.v: ASCII text, with CRLF line terminators
./run/ztex/inouttraffic.ihx: ASCII text, with CRLF line terminators
```

I guess `src/john.asm` should not be changed, unless @solardiz changes it in core.

Should we adjust .editorconfig for src/john.asm? Is there a reason for using CRLF line endings here?

And what about all the ztex files? Fix the whitespace issues? (Not just CRLF line endings, but also trailing tabs etc.)
Should this be fixed, or should .editorconfig be adjusted?

(I found the whitespace problems in ztex when I wanted to change a simple spelling error, and ended up changing the whole file due to the CRLF line endings. )

**Comment by solardiz** [comment]
On Fri, Mar 24, 2017 at 04:59:53PM -0700, frank-dittrich wrote:
> I guess `src/john.asm` should not be changed, unless @solardiz changes it in core.
> 
> Should we adjust .editorconfig for src/john.asm? Is there a reason for using CRLF line endings here?

It was/is to be processed by TASM under DOS, and I have no idea what TASM does on bare LFs.  I should probably just drop DOS support in next release anyway.

> And what about all the ztex files? Fix the whitespace issues? (Not just CRLF line endings, but also trailing tabs etc.)
> Should this be fixed, or should .editorconfig be adjusted?
> 
> (I found the whitespace problems in ztex when I wanted to change a simple spelling error, and ended up changeing the whole file due to the CRLF line endings. ) 

Pinging @apingis

**Comment by magnumripper** [comment]
@roycewilliams do you have a test environment for this? What if you drop the CR's from all files under ztex/, does that still work fine (I have a feeling it will)?

Something along the lines of:
```
$ find ztex -type f -print0 | xargs -0 perl -pi -e 's/\r//g'
```

**Comment by solardiz** [comment]
On Mon, Apr 24, 2017 at 03:00:29PM -0700, magnum wrote:
> @roycewilliams do you have a test environment for this? What if you drop the CR's from all files under ztex/, does that still work fine (I have a feeling it will)?
> 
> Something along the lines of:
> ```
> $ find ztex -type f -print0 | xargs -0 perl -pi -e 's/\r//g'
> ```

We should primarily ask @apingis

**Comment by magnumripper** [comment]
We did and he didn't answer

**Comment by Apingis** [comment]
Hi,
All CRs can be removed (I've tested).

./src/ztex/ez-usb/inouttraffic.ihx
./run/ztex/inouttraffic.ihx
These are firmware images, exactly as they were produced by SDCC. Specs for IHX file format allows CR, LF or both. I've checked it works with CRs removed.

./src/ztex/fpga/ztex_inouttraffic/ztex_inouttraffic.xds - strategy file used by ISE, it's XML, works fine with CRs removed.

All other ztex files are sources. I'm using text editor integrated in ISE, it reads files with LF line terminators with no probs, however when I edit and add new lines it adds CR's. It seems I can't change this behavior - no editor preferences on line terminators. I think I'll be removing CRs before commits with shell command or maybe some post-commit hook can be setup.

**Comment by roycewilliams** [comment]
@Apingis, excellent - and good to hear from you!

All - I do still have a testing platform available, so you can ping me as needed.

**Comment by magnumripper** [comment]
> I'm using text editor integrated in ISE, it reads files with LF line terminators with no probs, however when I edit and add new lines it adds CR's. It seems I can't change this behavior - no editor preferences on line terminators.

So perhaps it's a better solution to keep the existing line endings, and adjust our `.editorconfig` file so it reflects the situation. That solves it 100% for me personally. We do this for eg. tab spacing in "john proper" vs. jumbo.

http://editorconfig.org

**Comment by magnumripper** [comment]
> So perhaps it's a better solution to keep the existing line endings

OTOH in that case we might want to do the opposite - ensure ALL files under ztex/ has CRLF line endings. Currently all have CRLF except these:
```
$ find ztex -type f | xargs file | grep -v CRLF
ztex/device.h:                                       c program text, ASCII text
ztex/device_bitstream.h:                             c program text, ASCII text
ztex/device_format.h:                                c program text, ASCII text
ztex/ez-usb/inouttraffic.c:                          c program text, ASCII text
ztex/fpga/descrypt/descrypt_core/des_loop.v:         BSD makefile script text, ASCII text
ztex/fpga/descrypt/descrypt_core/descrypt.vh:        ASCII text
ztex/fpga/descrypt/descrypt_core/Eblock.v:           BSD makefile script text, ASCII text
ztex/fpga/pkt_comm/word_gen.vh:                      ASCII text
ztex/fpga/util/log2.vh:                              ASCII text
ztex/fpga/ztex_inouttraffic/clocks.ucf:              ASCII text
ztex/inouttraffic.c:                                 c program text, ASCII text
ztex/inouttraffic.h:                                 c program text, ASCII text
ztex/jtr_device.h:                                   c program text, ASCII text
ztex/jtr_mask.h:                                     c program text, ASCII text
ztex/pkt_comm/cmp_config.h:                          c program text, ASCII text
ztex/pkt_comm/inpkt.h:                               c program text, ASCII text
ztex/pkt_comm/pkt_comm.h:                            c program text, ASCII text
ztex/pkt_comm/word_gen.h:                            c program text, ASCII text
ztex/pkt_comm/word_list.h:                           c program text, ASCII text
ztex/task.h:                                         c program text, ASCII text
ztex/ztex.c:                                         c program text, ASCII text
ztex/ztex.h:                                         c program text, ASCII text
ztex/ztex_scan.c:                                    c program text, ASCII text
ztex/ztex_scan.h:                                    c program text, ASCII text
```

**Comment by solardiz** [comment]
On Tue, Apr 25, 2017 at 02:09:10PM -0700, magnum wrote:
> > So perhaps it's a better solution to keep the existing line endings
> 
> OTOH in that case we might want to do the opposite - ensure ALL files under ztex/ has CRLF line endings. Currently all have CRLF except these:

Maybe keep all files as they are, because their current line endings are native for the tools used to edit those files, and adjust .editorconfig to reflect that (perhaps by filename suffix).

**Comment by magnumripper** [comment]
Yeah that's also not too weird. It'll be a whole lotta lines in the .editorconfig file but that one is not made for looks anyway.
