### ISSUE TITLE
New fglrx package and CI failures

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2488]
### Scenario
- There are new kernel and fglrx-* packages in "ubuntu-updates";
- There is, at least, one bug in these packages;
- You guys can workaround the bug;
- But, the relationship between these new packages + CI + JtR OpenCL is becoming "complicated". E.,g., Clang is really unhappy.

### You guys can
- workaround the bug and keep the OpenCL tests running (for a while).
- stop testing OpenCL (this will happen sooner or later);
- move to Intel driver (configure needs a patch);

****
* I decided to workaround and keep an eye on it for a while. So, your tests are not mandatory. 
* Also, I have one branch trying the Intel stuff.

**Comment by magnumripper** [comment]
For now I just allowed failures for OpenCL. Not sure how to actually get it working again.

**Comment by magnumripper** [comment]
What's the story behind "configure needs a patch"? Is it complicated?

**Comment by claudioandre** [comment]
If you want to see my CI in action (except the intel stuff, I prefer AMD), run (inside JtR main dir; I mean, above /src, /doc, ...): 
```
$ git checkout -b your_branch
$ rm -f get_tests.sh; wget https://raw.githubusercontent.com/claudioandre/packages/master/john-the-ripper/tests/get_tests.sh; chmod +x get_tests.sh ; ./get_tests.sh 
$ git push origin your_branch
```
*****

I have no idea where I put the intel stuff. Anyway, it is not hard. What I did inside the CI scripts:
- using CentOS 7.3 docker on Travis;
- wget the intel beta software (the only thing I was able to find inside intel's site);
- install it;
- patch configure to be able to find the intel driver;
- it will work and i'll show the Travis Intel CPU using `list=opencl-devices`

configure script (LD_FLAGS maybe)
```
   if test -d "/opt/intel/opencl/include"; then
       ADD_CFLAGS="$ADD_CFLAGS -I/opt/intel/opencl/include"
   fi
```
Test / environmnet script
```
      yum -y groupinstall 'Development Tools'; \
      yum -y groupinstall 'c-development'; \
      yum -y install rpmdevtools openssl openssl-devel bc; \
      wget http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB4.1_linux64.zip; \
      unzip SRB4.1_linux64.zip; \
      rpm -Uvh intel-opencl-r4.1-61547.x86_64.rpm; \
```

**Comment by magnumripper** [comment]
#2523 might be a "solution". Hopefully we can forget about fglrx and use OSX instead.

**Comment by magnumripper** [comment]
Done! Our OpenCL formats are now bot-tested on OSX' CPU device.
