### ISSUE TITLE
Add support for Ethereum Wallet(s)

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2492]
* https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts

* https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

* https://hashcat.net/forum/thread-6405-post-34457.html

* https://github.com/ethereum/cpp-ethereum/blob/develop/libdevcrypto/SecretStore.cpp#L378-L418 (thanks to philsmd)

* https://github.com/lexansoft/ethcracker/

* https://github.com/ryepdx/pyethrecover

**Comment by ethtester** [comment]
FYI. JTR Ethereum CPU cracking benchmarks;

Mist wallet (262144 iterations) = 1.269p/s
MyEtherwallet (1024 iterations) = 302.9p/s
