### ISSUE TITLE
Add support for FreeBSD whole disk encryption (GELI)

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2499]
Useful links,

* http://www.allanjude.com/bsd/AsiaBSDCon2016_geliboot.pdf

* https://github.com/freebsd/freebsd/blob/master/sys/geom/eli/g_eli.c

* https://github.com/freebsd/freebsd/tree/master/sys/geom/eli

* https://github.com/freebsd/freebsd/blob/master/sys/geom/eli/g_eli.h (important)

**Comment by kholia** [comment]
Done in PR https://github.com/magnumripper/JohnTheRipper/pull/2503.

I will open another issue for future enhancements (support for different versions and ciphers, support for keyfiles).

**Comment by danfe** [comment]
> ... support for keyfiles

That's definitely wanted, could we expect to see it soon? ;-)

**Comment by solardiz** [comment]
> > ... support for keyfiles
> 
> That's definitely wanted, could we expect to see it soon? ;-)

@danfe Only if you contribute it. Also, it doesn't look like @kholia opened any "issue for future enhancements (support for different versions and ciphers, support for keyfiles)." So you may do that if you know what we're still missing and should add. Thank you!

**Comment by solardiz** [comment]
Maybe the "support for different versions and ciphers" planned here is actually implemented in #2524 and #3863 / #3864. Also OpenCL support was added (for whatever versions/ciphers) in #2507 / #2586. I guess support for keyfiles is in fact missing?

**Comment by danfe** [comment]
> I guess support for keyfiles is in fact missing?

Yes, it is currently missing.

> Only if you contribute it. Also, it doesn't look like @kholia opened any [future enhancements] issue

Right.  Perhaps I would take a bite at this.  I just wanted to see maybe it's already cooking behind the scenes so to not redo the same research/work.
