### ISSUE TITLE
Bitlocker formats: Use improved bitlocker2john

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2508]
- [x] Use or adopt code from https://github.com/kholia/bitlocker2john
- [x] Adopt OpenCL format to that syntax (and 6-byte verifier)

I couldn't assign @e-ago to this issue because GitHub only allows me to list "collaborators", but I hope you and @kholia can work this out together.

**Comment by kholia** [comment]
This is in progress in PR https://github.com/magnumripper/JohnTheRipper/pull/2513 and https://github.com/magnumripper/JohnTheRipper/pull/2516.
