### ISSUE TITLE
Support RACF KDFAES hashes

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2511]
See #2510

**Comment by kholia** [comment]
@bigendiansmalls Hello! I am wondering about the status of this task (i.e. support of RACF KDFAES hashes).

Are you reversing s390x RACF binaries to determine the algorithm? Or is there a more easier approach available? :)

**Comment by kholia** [comment]
Some useful links,

* http://www.stuhenderson.com/Handouts/NyRug2015TakingTheSwordOutOfPassword.pdf

* http://www.racfsnow.co.uk/racfsnow.pdf

The first file has a high-level overview of this new RACF hashing algorithm.

**Comment by bigendiansmalls** [comment]
I'm looking into it, nothing trivial about it.  Nowhere is the algo documented fully.  It's some near derivative of PBKDF2

**Comment by kholia** [comment]
From https://www-03.ibm.com/systems/z/os/zos/features/racf/vm.html,

```
z/VM 6.4  is available!  The RACF Security Server for z/VM has
been updated with a number of security improvements and 
ease-of-use enhancements, including:

...
Password Encryption Upgrade (KDFAES)
...
```

However, z/VM 6.4 is not available for evaluation yet ;(

**Comment by kholia** [comment]
CC @mainframed. Hey! Would you happen to know which `z/OS binaries` are responsible for handling this KDF? Maybe, we can reverse engineer those binaries?

**Comment by jaytay79** [comment]
@kholia I have heard rumours that at least two parties have reverse-engineered the KDFAES encryption but are presumably not sharing due to either competitive or other restrictions.

**Comment by jaytay79** [comment]
@kholia This may be of interest: 
https://marc.info/?l=racf-l&m=154299413516964&w=2
