### ISSUE TITLE
iTunes backup confusion

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2526]
See https://github.com/hashcat/hashcat/issues/1236#issuecomment-298777744 and follow-ups.

I realize now that we're using IOS 9.x test vectors for benchmark. I didn't expect that from a format added just a few weeks ago, it's almost unreasonable - but OTOH we'd get REALLY unreasonably slow testing with real IOS 10 test vectors.

I think the least we should do is set `BENCHMARK_COMMENT` to something like "IOS 9.x". As an alternative we could define the 9/10 as a cost - then it'd be shown when benchmarking.

**Comment by kholia** [comment]
Yes, the real iTunes 10 test vector is disabled with a comment saying `this is very very slow!`.

I think we can't set the `BENCHMARK_COMMENT` to something like `iTunes 9.x` since we are also including some fake `iTunes 10` test vectors in the benchmarking.

I will look into showing the version (9/10) as a cost.

**Comment by kholia** [comment]
With latest changes (to be PR'ed) I see,

```
Benchmarking: itunes-backup, Apple iTunes Backup [PBKDF2-SHA1 AES 256/256 AVX2 8x]... DONE
Speed for cost 1 (version) of 9 and 10, cost 2 (iteration count) of 10000 and 10000000
Raw:	0.9 c/s real, 0.9 c/s virtual
```

Hopefully this should reduce/eliminate any confusion. The very slow test vector will be disabled in the actual committed version.

**Comment by magnumripper** [comment]
> I think we can't set the BENCHMARK_COMMENT to something like iTunes 9.x since we are also including some fake iTunes 10 test vectors in the benchmarking.

All test vectors are used for self-tests but only the first two are used for benchmarking. But this cost thing is better anyway.

**Comment by kholia** [comment]
Cool. I had moved the `iTunes 10` test vector to the second place to reflect the different `version` cost.
