### ISSUE TITLE
pkzip non-handled compression type

### ISSUE THREAD

**Issue by kestufabrix** [magnumripper/JohnTheRipper#2528]
Hi,
I need to crack a zip archive password containing two files, a small .txt and another big .zip. The password seems to be zipcrypto

I used zip2john to get the hash of the archive but I get :
ver 1.0 XXX.zip->YYY.txt PKZIP Encr: cmplen=51, decmplen=39, crc=BDF11DE0
ver 4.5 ~/Downloads/00-Utilitaires/XXX.zip->ZZZ.zip **is not encrypted, or stored with non-handled compression type**
(though it does ask for a password when unzipping)

the hash I get is :
```
XXX.zip:$pkzip2$1*1*2*0*33*27*bdf11de0*0*2c*0*33*bdf1*aa8a*e2f57a8f225245b7aa7ec500c0397f9a412f501c3f8ea362aa5dbf7fc0871054c2e305b60cf04c10575b6837737db7c5fbb609*$/pkzip2$:::::XXX.zip
```
John found a password within 3 hours but it won't work... Would you have any idea where the problem might be? (I must admit I can't be sure my archive is not broken...)

Thank you so much in advance...

Note I use an up-to-date bleeding jumbo version of john (though the "$john --list=build-info" command returns "unknown commands") on Ubuntu 17.04.

**Comment by magnumripper** [comment]
Any chance you can share that archive with us (privately)?

**Comment by kestufabrix** [comment]
Yes of course. Though it's a big file and its origin is not really secure nor very official... Honestly my purpose is just testing but it's certainly still not very very lawful... Let me know how to share it (dropbox?).

**Comment by kestufabrix** [comment]
Thanks for your answer. Unfortunately the ZZZ.zip does asks for a password! That's what troubles me...

**Comment by claudioandre** [comment]
JtR and the 2john can handle the **not encrypted, or stored with non-handled compression type**. I just tried to reproduce your use case. 
* encrypted 1.0 YYY.txt
* unencrypted 4.5 ZZZ.zip

```
ver 1.0 efh 5455 efh 7875 XXX.zip->YYY.txt PKZIP Encr: 2b chk, TS_chk, cmplen=16, decmplen=4, crc=7F808508
ver 4.5 XXX.zip->ZZZ.zip is not encrypted, or stored with non-handled compression type
XXX.zip:$pkzip2$1*2*2*0*10*4*7f808508*0*41*0*10*7f80*7319*8fe32c524ec41bc23f18d30fd3641020*$/pkzip2$:::::XXX.zip
```

So, it has to be something else.
****

BTW: are your saying that you can crack the hash you posted using something like this `./john ~/hash -mask=zipcrypto`?

**Comment by claudioandre** [comment]
Anyway, I was able to do something really interesting (the same salt for 2 different passwords):
```
XXX.zip:$pkzip2$1*2*2*0*10*4*7f808508*0*41*0*10*7f80*7319*8fe32c524ec41bc23f18d30fd3641020*$/pkzip2$:::::XXX.zip
XXX.zip:$pkzip2$1*2*2*0*10*4*7f808508*0*41*0*10*7f80*7319*30fc1e61e10e8d79ec55a90d58121392*$/pkzip2$:::::/home/claudio/Downloads/XXX.zip
```

For this hash file, JtR finds the wrong password for the 2nd line and can't find the right one.

**Comment by magnumripper** [comment]
@claudioandre that's weird, we need to look into that. When you say "same salt" you mean same actual pkzip salt but in JtR's perspective it's not regarded as a salt in normal sense, the whole hash is (and binary size is 0 -- what we use to call a non-hash).

@kestufabrix could you post the output of `zipinfo -v XXX.zip`? It should tell all details about encryption types, versions and so on.

**Comment by kestufabrix** [comment]
Actually john did crack the hash but without the zipcrypto mask. But anyway the password it finds won't work.

The output of zipinfo is:
Archive:  XXX.zip
Zip file size: 2831753269 bytes, number of entries: 2
-rw-a--     3.1 fat       39 BX stor 16-Oct-14 21:20 YYY.txt
-rw-a--     3.1 fat 2831752668 BX stor 16-Oct-09 23:41 ZZZ.zip
2 files, 2831752707 bytes uncompressed, 2831752707 bytes compressed:  0.0%

**Comment by magnumripper** [comment]
You need to add the `-v` option to zipinfo, that will tell a whole lot more.

**Comment by kestufabrix** [comment]
Of course, sorry, I updated the post

**Comment by magnumripper** [comment]
OK, here's a wild theory: Maybe our zip2john and/or the pkzip format have "32-bit issues". The size of ZZZ.zip can't be fit in a signed int.

**Comment by kestufabrix** [comment]
I admit I thought of that 32/64 bits issue but it is far beyond my skills and undestanding to solve the problem then! :-)

**Comment by claudioandre** [comment]
> When you say "same salt" you mean

I mean JtR said that to me. 
```
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (PKZIP [32/64])
Remaining 1 password hash
Will run 2 OpenMP threads
```

**Comment by magnumripper** [comment]
> I mean JtR said that to me.

Wow that is a bug. I guess Jim is setting a too small size on the dyna salt.

I will have a look at both of these issues tomorrow. If it's a 32-bit problem it should be easy to fix.

**Comment by claudioandre** [comment]
There a some stuff to clarify:
* @kestufabrix, can you please open the zip file, remove the huge ZZZ.zip file inside it and try to crack the resulting/new zip file? (of course, backup first).
* zip2john can't handle encrypted file type 4.5. If the file has 2 different passwords, JtR won't be able to crack the ZZZ.zip password.

**Comment by magnumripper** [comment]
Very good point. Another way to achieve the same is (or should be) `zip2john -o YYY.txt XXX.zip` to get the hash.

**Comment by magnumripper** [comment]
No wait, the hash you got in the first place was just that. It's the hash of the small txt file.

**Comment by claudioandre** [comment]
So, if he creates a new zip, we can compare the 2 hashes and discard (or be sure about) some kind of bugs.

**Comment by kestufabrix** [comment]
OK then, I deleted the big ZZZ.zip file. The hash I get then from zip2john is :

XXX.zip:$pkzip2$1*1*2*0*33*27*bdf11de0*0*2c*0*33*bdf1*aa8a*e2f57a8f225245b7aa7ec500c0397f9a412f501c3f8ea362aa5dbf7fc0871054c2e305b60cf04c10575b6837737db7c5fbb609*$/pkzip2$:::::XXX.zip

And now john is cooking... I'll let you know.

**Comment by magnumripper** [comment]
That's the same hash

**Comment by magnumripper** [comment]
@kestufabrix drop me a mail so I get your address. john.magnum@hushmail.com

**Comment by kestufabrix** [comment]
Ah yes it's the same hash, sorry, I checked too fast...

**Comment by magnumripper** [comment]
Some conclusions so far:
* Both files are stored, not inflated. In that case our only validation of a correct password is the 32-bit CRC. This means we'll have a false positive for every 4 billion guesses (on average) and that's what you saw. Adding the --keep-guessing option to john will make it go on and find more alternatives. When you find a password that works with unrar for both files, it's the correct one (I'm assuming they are having the same one).
* We handle legacy 32-bit sizes correctly but not 64-bit ones (newer, extended headers). I'm working on that, should be ready next week. But you probably don't need it. Just keep on attacking that little txt file until you find the correct password.

**Comment by solardiz** [comment]
On Sat, May 06, 2017 at 03:52:59AM -0700, magnum wrote:
> * Both files are stored, not inflated. In that case our only validation of a correct password is the 32-bit CRC. This means we'll have a false positive for every 4 billion guesses (on average) and that's what you saw. Adding the --keep-guessing option to john will make it go on and find more alternatives. When you find a password that works with unrar for both files, it's the correct one (I'm assuming they are having the same one).

In cases like this - with multiple files in a zip - would it be possible for us to have multi-file "hashes" and filter out guesses based on multiple 32-bit CRCs at once?

**Comment by magnumripper** [comment]
> would it be possible for us to have multi-file "hashes" and filter out guesses based on multiple 32-bit CRCs at once?

I believe that is actually what would happen with current code, if both files were supported. At least unless we disqualify the second file based on its huge size. I will look into that once I get support for v4.5 and 64-bit sizes.

**Comment by kestufabrix** [comment]
John is still running... 40 hours now.
It did find a second password but still not the good one. Id does try to extract the .txt file though but the .txt file seems corrupted with wrong UTF-8 characters... And the password won't work with the ZZZ.zip file anyway (I still assume it's the same password).

**Comment by magnumripper** [comment]
@kestufabrix if you ever crack it, please send the password to me (off list if you wish) so I can verify some changes to the format.

**Comment by magnumripper** [comment]
@kestufabrix I have committed a change that supports the larger file. The result of that, like Solar mentioned, is merely that you will get less false positives (it will verify both files CRC). I have tested this with some mockup files and it seems to work. It also did not break any old samples we had. You can keep running with what you've got, or you could try stopping the job, re-creating the input file (with updated zip2john) and then resume the job.

As always, no guarantees ;-)

**Comment by magnumripper** [comment]
I believe zip2john now fully supports 64-bit sizes. The pkzip format itself doesn't, in case any actual size exceeds 4 GB. This is a to-do and I'm working on it.

**Comment by magnumripper** [comment]
All problems I know of are now fixed.
