### ISSUE TITLE
New warnings generated by GCC 7

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2533]
While building JtR jumbo with GCC 7 I see,

```
dynamic_fmt.c: In function ‘prepare’:
dynamic_fmt.c:8212:19: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
      sprintf(Fld, "$$F%d", i);
                   ^~~~~~~
dynamic_fmt.c:8212:6: note: ‘sprintf’ output between 5 and 6 bytes into a destination of size 5
      sprintf(Fld, "$$F%d", i);
      ^~~~~~~~~~~~~~~~~~~~~~~~

sip_fmt_plug.c: In function ‘get_salt’:
sip_fmt_plug.c:261:61: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size between 57 and 311 [-Wformat-truncation=]
   snprintf(salt.static_hash_data, STATIC_HASH_SIZE, ":%s:%s:%s:%s:%s",
                                                             ^~
     login.nonce, login.nonce_count, login.cnonce,
                                     ~~~~~
sip_fmt_plug.c:261:3: note: ‘snprintf’ output 6 or more bytes (assuming 398) into a destination of size 314
   snprintf(salt.static_hash_data, STATIC_HASH_SIZE, ":%s:%s:%s:%s:%s",
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     login.nonce, login.nonce_count, login.cnonce,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     login.qop, static_hash);
     ~~~~~~~~~~~~~~~~~~~~~~~
```
[gcc-7-compilation-log.txt](https://github.com/magnumripper/JohnTheRipper/files/983386/gcc-7-compilation-log.txt) (full log).

I have not investigated these compiler warning messages.

**Comment by jfoug** [comment]
> dynamic_fmt.c: In function ‘prepare’:
dynamic_fmt.c:8212:19: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
      sprintf(Fld, "$$F%d", i);
                   ^~~~~~~
dynamic_fmt.c:8212:6: note: ‘sprintf’ output between 5 and 6 bytes into a destination of size 5
      sprintf(Fld, "$$F%d", i);
      ^~~~~~~~~~~~~~~~~~~~~~~~

That is a 100% bogus message.  The output will ALWAYS be 4 bytes + 1 byte null.  The 'fancy' new compiler is simply too smart for its own good.  There is a for loop, ``` for (x = 0; x < 10; ++x) ```  I guess we could change it to ```<= 9``` to pacify the stupid compiler warning (hopefully that will remove the warning).  Same end result, but no warning.

**Comment by kholia** [comment]
https://gcc.gnu.org/gcc-7/changes.html is relevant to this discussion. The `i` variable is a signed int, and the compiler falsely thinks that it can be negative. Hence, the compiler says that the sprintf output can be 6 bytes (one extra byte for the `-` sign character).

Yes, this seems to be a bogus warning.

**Comment by magnumripper** [comment]
Is this a stable gcc or some bleeding-edge beta?

**Comment by magnumripper** [comment]
So according to that document we should either bump size of `Fld` or make `i` unsigned (assuming this is a stable gcc).

**Comment by kholia** [comment]
These warnings are generated by stable GCC which will be shipping with Fedora 26.
