### ISSUE TITLE
Add a generic "no early reject" option

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2537]
See https://github.com/philsmd/7z2hashcat/issues/12#issuecomment-300272388

This might be combined with some idea of a generic "extra options option" like `--tweak=LIST`.

LIST could be anything comma-separated. For example `--tweak=no-early-reject` would solve this issue as written - but we could also support several options like `--tweak=no-early-reject,never-give-up` (not that I have the slightest clue what the latter option would mean). The idea is to implement the parsing code once, and only a single actual command line --option. Any future add-ons would just be supporting more stuff within LIST.

**Comment by magnumripper** [comment]
This could also mean we can deprecate some old nefarious options and add them as "tweaks".

For example, the existing `--mkpc=N` or `--fix-state-delay=N` options could be tweaks. Anything not quite kosher should be tweaks. Things like `--verbosity=N` should not.

**Comment by kholia** [comment]
How would a `--tweak=no-early-reject` option work in practice? How will the end-user determine when to use such an option?

Fixing the problem of false negatives in 7z format with such an option seems like a weird hack. This said, I can't think of a better way to fix the padding checks in the 7z format. Can't we simply remove those padding checks?

**Comment by magnumripper** [comment]
The `--tweak` option would be mostly for debugging/testing and very advanced options. It shouldn't normally be used at all. Using no-early-reject where not applicable (eg. for raw-md4) would not emit any error or warning. Perhaps we shouldn't even document it.

If we encounter more 7z files where we can't trust the padding, we simply have to remove it by default. That would unfortunately mean a huge performance hit. In that case we might want `--tweak=use-early-reject` instead.

**Comment by magnumripper** [comment]
It turned out skipping the padding check didn't hurt performance much (#2532), so I just did that. I'll close this issue for now.
