### ISSUE TITLE
Add support for cracking MultiBit wallets

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2539]
* https://multibit.org/
* https://github.com/keepkey/multibit-hd
* https://github.com/keepkey/multibit
* https://multibit.org/help/v0.5/help_walletFormats.html

This and other Bitcoin related enhancements might encourage people to open low-quality support tickets on GitHub. For example, one person is already asking for a very newbie friendly guide for cracking Ethereum wallets. I have no free time nor inclination for doing such newbie level support work.

@magnumripper @solardiz How do you propose dealing with low-quality support requests?

**Comment by magnumripper** [comment]
Anyone wanting support here at Github will be told off and issue closed with no mercy. We simply can't be helpful here, or things will go downhill very very fast.

The mailing lists will probably not be too helpful (as in no or little replies). OTOH some newbies might help other newbies there.

**Comment by kholia** [comment]
Thanks @magnumripper for the advice.

This ticket is done now in PR #2548.
