### ISSUE TITLE
PkZip 2john tool can't handle a zip file with more than one password

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2542]
### Case 1
[XXX.zip](https://github.com/magnumripper/JohnTheRipper/files/997535/XXX.zip)
Passwords: 123456 and 654321 

* works and cracks
```
$ ../run/zip2john -o teste ~/bin/XXX.zip
$ ../run/zip2john -o etset ~/bin/XXX.zip
```
* produces a hash but I was unable to crack it (the hash is a mix of the two ones seen above)
```
$ ../run/zip2john ~/bin/XXX.zip
```
********************
### Case 2
Passwords: claudio and zipcrypto

Order this way: it finds ONLY the 1st password (1st hash):
```
echo 'XXX.zip:$pkzip2$1*2*2*0*10*4*7f808508*0*41*0*10*7f80*7319*8fe32c524ec41bc23f18d30fd3641020*$/pkzip2$:::::XXX.zip' > ~/hash
echo 'XXX.zip:$pkzip2$1*2*2*0*10*4*7f808508*0*41*0*10*7f80*7319*30fc1e61e10e8d79ec55a90d58121392*$/pkzip2$:::::/home/claudio/Downloads/XXX.zip'  >> ~/hash
```
Invert the order: it cracks ONLY the 1st line (original 2nd hash);
```
echo 'XXX.zip:$pkzip2$1*2*2*0*10*4*7f808508*0*41*0*10*7f80*7319*30fc1e61e10e8d79ec55a90d58121392*$/pkzip2$:::::/home/claudio/Downloads/XXX.zip'  > ~/hash
echo 'XXX.zip:$pkzip2$1*2*2*0*10*4*7f808508*0*41*0*10*7f80*7319*8fe32c524ec41bc23f18d30fd3641020*$/pkzip2$:::::XXX.zip' >> ~/hash
```

**Comment by magnumripper** [comment]
I believe this is just a documentation issue. zip2john assumes all files have the same password. In the unlikely event that's not the case, you need to use the `-o` option.

**Comment by magnumripper** [comment]
Case 2 is a bug, but should almost never happen IRL. Should be fixed anyway.

**Comment by claudioandre** [comment]
>  In the unlikely event that's not the case, you need to use the -o option

It is fair. 

The devil here is that I was expecting to crack an "only one password file"; a file I was trying to find the key. 
- I failed to crack the file because I tried the correct password against a "bad" hash. Consider this is a note to self. But, if possible, JtR should warn somehow.
