### ISSUE TITLE
btcoin wallet password can not be cracked

### ISSUE THREAD

**Issue by watanuoli** [magnumripper/JohnTheRipper#2550]
I successfully extract encrypted content by the blockchain2john.py and it can be recognized as blockchain-opencl format.
But after the cracking ,there's no cleartext out.
./john --device=gpu --pot=/workspace/wallet.pot --format=blockchain-opencl --incremental=Digits --min-length=5 --max-length=5 wallet.txt
btw:
the password is 12345
The wallet is generated by Electrum as the following type.
![image](https://cloud.githubusercontent.com/assets/3291393/26192168/3b951c60-3be3-11e7-9ba7-0788eba39014.png)

[wallet.txt](https://github.com/magnumripper/JohnTheRipper/files/1010156/wallet.txt)

**Comment by kholia** [comment]
Electrum wallets are not the same as Blockchain wallets. The Blockchain format can't crack Electrum wallets.

Support for cracking Electrum wallets is coming in PR https://github.com/magnumripper/JohnTheRipper/pull/2541.
