### ISSUE TITLE
Add GPU support for Ethereum Wallet(s)

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2551]
CPU format added in #2492. We need GPU support.

**Comment by kholia** [comment]
The scrypt KDF needs to run on CPU(s). See https://github.com/hashcat/hashcat/issues/1228 for details.

**Comment by magnumripper** [comment]
The ethereum-opencl (not presale) format should also have GPU-side keccak just because we can (it will probably not make a difference in speed). BTW why are they different formats at all?

**Comment by magnumripper** [comment]
> The scrypt KDF needs to run on CPU(s)

Yeah apparently TMTO doesn't help. https://github.com/hashcat/hashcat/issues/1228#issuecomment-305794575

**Comment by kholia** [comment]
There are different formats because they (regular, presale) use PBKDF2 in different ways (password is the salt in `presale` OpenCL kernel).

**Comment by magnumripper** [comment]
Are we currently missing an ethereal-presale CPU format?

**Comment by kholia** [comment]
The regular `ethereum` format handles presale wallets as well. It has some "very nice" hacks to do so ;)

**Comment by magnumripper** [comment]
We can close this now, right?

**Comment by kholia** [comment]
Yes, closing!
