### ISSUE TITLE
Revert prepare changes from 272c664

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2554]
Sorry about this, but all my tests are automated and were designed to stop and fail for each error.
 
```
form=net-sha1 (dyna)              guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED1!!!  ret_val=0]
```

**Comment by magnumripper** [comment]
Well it's great that someone (or something) actually runs the TS!

**Comment by magnumripper** [comment]
Should be no more, I ran TS myself. Took 34 minutes. We've got to fix that, it's ridiculous. Most of that time are hypotetical dynamic formats that doesn't need much testing.
