### ISSUE TITLE
Last kerberom commit introduced CRLF and whitespace problems

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2559]
@Fist0urs  Commit 5ea6852e44b0c4671827b81b8847bc308667504b introduced some CRLF and whitespace problems.

They are bad to look at when doing `git log -p`.

@magnumripper We really need some scripts to catch such problems early on. Got any tips?

**Comment by magnumripper** [comment]
We'd need pre-commit hooks but that's too dangerous for Github to support because they'd basically let us run arbitrary code on their servers.

**Comment by magnumripper** [comment]
Perhaps some ideas from https://stackoverflow.com/questions/3462955/putting-git-hooks-into-repository would be usable.

**Comment by Fist0urs** [comment]
Damn, I developed on Windows for this update and my text editor adds CRLF stuff.

I'll fix it ASAP, my bad

**Comment by kholia** [comment]
Thanks!

Some lines have trailing whitespace(s). I use Vim with https://github.com/bronson/vim-trailing-whitespace plug-in and `git log -p` to detect whitespace problems.

**Comment by magnumripper** [comment]
Should be fixed now.
