### ISSUE TITLE
No password hashes loaded (see FAQ)

### ISSUE THREAD

**Issue by bantawa04** [magnumripper/JohnTheRipper#2565]
I have created a hash for password protected PDF with John The Ripper which looks like:
`Protected.pdf:$pdf$2*3*128*-3904*1*16*fa8b5911e99eb1a6d74b033402dce8d0*:::::../../Protected.pdf`

and it is saved in key.hash file in root folder. When I run the command `john ../../key.hash` it returns error
`No password hashes loaded (see FAQ)` 
I'm using John The Ripper [john-1.8.0-jumbo-1], in ubuntu

**Comment by magnumripper** [comment]
You are reporting a bug in a version released several years ago. Please try latest version, re-run pdf2john too. If the problem remains, reopen this issue.
