### ISSUE TITLE
Add support for Ethereum presale wallets

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2568]
References,

* https://github.com/ryepdx/pyethrecover

* https://github.com/ethereum/go-ethereum/blob/master/accounts/keystore/presale.go

* https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/KeyManager.cpp#L298-L326

It seems that this task requires some amount of asymmetric cryptographic code. The presale wallets cannot be bought fresh any more, so this task has very limited long-term value in my opinion.

Update:

If `bkp` field is present in the presale wallet, then no asymmetric cryptographic code is required. However, the current presale wallet format seems to be lacking the `bkp` field and such wallets are not supported currently.

Here are some [sample presale wallets](https://github.com/magnumripper/JohnTheRipper/files/1070672/sample-presale-wallets.zip) for testing.

**Comment by FredericHeem** [comment]
First of all, thanks a lot for this pull request.
In my use case, the output of ./run/ethereum2john.py is a 1367 character long line, it seems to be too big when inserted into the password file. The encoded seed length as an hex string is 1249.

**Comment by magnumripper** [comment]
Perhaps this format should set FMT_HUGE_INPUT? I believe there isn't much more to it now, core code will take care of the details.

**Comment by FredericHeem** [comment]
This is indeed the case, thanks for the prompt support.

**Comment by magnumripper** [comment]
@kholia any format that potentially need a line length longer than 1K should set FMT_HUGE_INPUT. If in doubt, set it. However, doing it where it's not needed eats some performance when loading.

**Comment by kholia** [comment]
Thanks @magnumripper. I was not aware of this new flag, will take care of it from now on.

**Comment by kholia** [comment]
This issue has been addressed now.
