### ISSUE TITLE
False positives in multibit

### ISSUE THREAD

**Issue by kost123** [magnumripper/JohnTheRipper#2578]
I am getting many false positives in multibit whenever trying 1bil or so passwords. I believe another program that does the same thing "btcrecover" had this problem and he recently fixed it with this commit:

https://github.com/gurnec/btcrecover/commit/8a6e74e6690ff94715fd651dbe48c5a2dfb51efd

**Comment by kholia** [comment]
@kost123 

Can you post a sample wallet and sample false passwords for testing this?

**Comment by kost123** [comment]
Unfortunately I don't have a wallet I can post with a false positive password. But I believe the reason the false positives are coming is that the the regex or whatever you are using to match that the decrypted string is a valid private key, sometimes the decrypted data fits the "regex", so I believe the solution gurnec used was to decrypt another AES block if available and see if that also fits base58, if not then it's a false positive.

**Comment by kost123** [comment]
Sending a false positive wallet + pass to your email.

**Comment by kost123** [comment]
Getting no more false positives and all knowns are found perfectly. good job.

**Comment by kholia** [comment]
Thanks! All credit goes to @gurnec for his great work on the btcrecover project.

**Comment by kost123** [comment]
Noticed quite a reduction in speed. With the changes you made, is it decrypting the first 16 bytes then only if that is successful checking the other 16?

**Comment by kholia** [comment]
No. I didn't implement this optimization yet. I will try to optimize this format a bit later.

**Comment by kost123** [comment]
Awesome thanks :)

**Comment by kost123** [comment]
More false positives >.> It's because when checking to see if it's a multibit/android key it also checks to see if its a bitcoinj protobuf key, so once "org." comes around it throws a false positive.. maybe a length check?

**Comment by kholia** [comment]
The false positives can be reduced by using that additional check but they won't go away.

The MultiBit format will keep cracking, so such false positives shouldn't matter much. Or are the false positives being found too frequently?

**Comment by kost123** [comment]
I found 2 in 24hours.. not sure if that is "frequent", going to try this fix, thanks for updating.

**Comment by kost123** [comment]
Just waiting on the daily-build, hasnt seemed to have updated in 2 days.

**Comment by kholia** [comment]
The `daily-builds` provided Windows builds are not optimized. I recommend building your own optimized builds.

Like I said earlier, updated builds require the merging of the PR to happen first.

**Comment by kost123** [comment]
Changes are working as intended, good job.

**Comment by kholia** [comment]
Thanks for the feedback 👍
