### ISSUE TITLE
feature: optional periodic status output

### ISSUE THREAD

**Issue by roycewilliams** [magnumripper/JohnTheRipper#2604]
Today, while tracking initial speed ramp-up for testing purposes, the user has to periodically press a key to show the status:

```
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:14  0g/s 0p/s 106815c/s 106815C/s loveaaaa..loveaaoa
0g 0:00:03:12  0g/s 0p/s 107169c/s 107169C/s loveaaaa..loveaaoa
0g 0:00:05:44  0g/s 0p/s 107173c/s 107173C/s loveaaaa..loveaaoa
0g 0:00:06:51  0g/s 0p/s 107181c/s 107181C/s loveaaaa..loveaaoa
0g 0:00:10:36  0g/s 0p/s 107190c/s 107190C/s loveaaaa..loveaaoa
0g 0:00:15:34  0g/s 0p/s 107197c/s 107197C/s loveaaaa..loveaaoa
```

It would be convenient to optionally show status every X seconds, similarly to these hashcat flags:

```
     --status                  |      | Enable automatic update of the status screen
     --status-timer            | Num  | Sets seconds between status screen updates to X
```
This would also more easily provide more regular sampling.

**Comment by solardiz** [comment]
We already have these:

```
$ ./john --list=hidden-options | grep status
--progress-every=N         emit a status line every N seconds
--crack-status             emit a status line whenever a password is cracked
```

(There's also the auto-status external mode, but it pre-dates these options.)

A minor issue is that with on-device mask the reported range's start is off right after a successful guess, so `--crack-status` will probably always report the wrong range start (matching the guess).  This is a shortcoming of how I extended the formats API to allow for on-device candidate generation.

**Comment by roycewilliams** [comment]
Totally forgot about hidden options. Thanks, and thanks for the caveat. Closing.
