### ISSUE TITLE
Support for MultiBit Classic

### ISSUE THREAD

**Issue by kost123** [magnumripper/JohnTheRipper#2611]
Right now jumbo has support for .keys and HD wallets but no support for multibit classic .wallet files.

**Comment by kholia** [comment]
@kost123 

We already support MultiBit Classic wallets. See `../run/multibit2john.py` for details.

If you still think that the support is missing, do the following,

* Describe in detail how to create such wallets.

* Describe how such wallets can be cracked.

**Comment by kholia** [comment]
```
$ ../run/multibit2john.py 
Usage: ../run/multibit2john.py [MultiBit Classic or HD wallets files (.key, mbhd.wallet.aes)]

MultiBit Classic -> for a wallet named 'xyz', we need the xyz-data/key-backup/xyz*.key file
```

**Comment by kost123** [comment]
Upon further review it seems like multibit .wallet files use protobuf, text files also start with "org.bitcoin.production" but the output I get when using multibit2john.py is incorrect and is the same for multiple different wallets.

**Comment by kholia** [comment]
```
MultiBit Classic -> for a wallet named 'xyz', we need the xyz-data/key-backup/xyz*.key file
```

Read this again, carefully.

A `.key` file is needed to crack MultiBit Classic wallets. What makes you think that you can use `.wallet` file instead of a `.key` file to crack MultiBit Classic wallets? Do you have any proof that `.wallet` files can be brute forced too?

**Comment by kost123** [comment]
Sure, check btcrecover, they have support for .wallet, again a key is just a single exported address, multibit wallet files use some form of protobuf that can be cracked.

**Comment by kholia** [comment]
```
$ ./btcrecover.py --passwordlist wordlist --wallet Untitled.wallet 
btcrecover.py: notice: for MultiBit, use a .key file instead of a .wallet file if possible
```

A `.key` file is recommended for cracking performance reasons (MD5 vs scrypt). I don't see much reason to add support for cracking `.wallet` files. Feel free to send a PR if you feel otherwise.

**Comment by kost123** [comment]
Not a lot of people extract a single .key, it is optimal to crack .keys but most people will just have there .wallet files.

**Comment by kholia** [comment]
From https://multibit.org/,

```
Dear Bitcoin Community,

It is time for us to let Multibit go.

KeepKey acquired Multibit a little over 1 year ago. At the time, the engineers
who originally built and supported Multibit had announced that they would no
longer be working on it or providing support. Multibit played an important role
in the Bitcoin infrastructure. We felt that it was important for Multibit to
continue and hoped that with our existing support and development teams, we
would be able to keep Multibit alive.

The reality is that Multibit is in need of a lot of work. It has stubborn bugs
that have caused us and Multibit users much grief. Additionally, Bitcoin has
gone through a fundamental change in regards to the way fees work. The addition
of SegWit in the coming weeks will mean the Multibit software has fallen still
further behind.

Unfortunately, KeepKey simply does not have the resources to support the
current issues, nor to rebuild Multibit to ensure ideal user experience. By
focusing our attention on the KeepKey device, we will continue building and
improving the best hardware wallet available.

Thus, KeepKey will discontinue support and maintenance of Multibit, effective
immediately.

We recommend that all Multibit users discontinue using it and you move your
keys to other wallet software of your choosing. We wrote a blog post describes
some options of your options in more detail.

Multibit was a fantastic piece of software in its time, and we want to thank
the Multibit developers for such an important contribution to Bitcoin's
history.

Sincerely,

Ken Hodler
Chief Technical Officer
KeepKey
```
