### ISSUE TITLE
SSH-ng and OpenBSD-SoftRAID formats don't report tunable costs

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2614]
SSH-ng doesn't report any tunable costs.  It should report two: key derivation algorithm (there appear to be four of them) and iteration count.  So that we can easily benchmark the different key derivation algorithms separately, etc.

OpenBSD-SoftRAID reports one tunable cost - iteration count.  It should also report the key derivation algorithm (there appear to be two of them).

(Fixing this issue is relevant to the task of implementing and making use of bcrypt_pbkdf on FPGA, which should not take too much effort now that we have bcrypt on FPGA.  A closely related task is also making use of our OpenCL code for both bcrypt and PBKDF2 from these formats.)

**Comment by kholia** [comment]
This should be solved now, closing the task.
