### ISSUE TITLE
Add support for 802.11w (WPA2-PSK-SHA256)

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2635]
I will try finding more technical and relevant links a bit later today.

* https://en.wikipedia.org/wiki/IEEE_802.11w-2009

* https://w1.fi/cgit/hostap/plain/tests/hwsim/test_ap_pmf.py

* https://w1.fi/wpa_supplicant/

* https://w1.fi/hostapd/

Looking at `hostapd` and `wpa_supplicant` code should help.

**Comment by kholia** [comment]
I am attaching configuration files (for hostapd and wpa_supplicant) for generating such "hashes".

* [wpa_supplicant.conf.txt](https://github.com/magnumripper/JohnTheRipper/files/1156203/wpa_supplicant.conf.txt)

* [hostapd.conf.txt](https://github.com/magnumripper/JohnTheRipper/files/1156206/hostapd.conf.txt)

```

$ sudo wpa_supplicant -i wlp4s0 -c wpa_supplicant.conf  # one one node

$ sudo hostapd hostapd.conf  # on another node
```

[Here](https://github.com/magnumripper/JohnTheRipper/files/1156223/WPA-PSK-SHA256-session.pcap.zip) is a sample pcap for a `WPA-PSK-SHA256` session.

**Comment by magnumripper** [comment]
Good call. I was just going to reference https://github.com/hashcat/hashcat/issues/1300

**Comment by magnumripper** [comment]
Good info here: https://github.com/hashcat/hashcat/issues/1300#issuecomment-316276163

Sample: https://github.com/hashcat/hashcat/issues/1300#issuecomment-316223363

**Comment by magnumripper** [comment]
> it does not have the usual wireless data link layer type, and other wireless "headers". It would be great to support such captures too.

Yes we should - in fact I thought we already did. I added all encapsulation types I could think of a couple years ago but I guess this is more like "no encapsulation"?

**Comment by kholia** [comment]
I tried adding support for `LINKTYPE_ETHERNET` and the hash extraction seems to be working. However, I am unable to crack the dumped hashes, probably due to a bug in my code.

@magnumripper Can you please take a look at this hack?

https://github.com/kholia/JohnTheRipper/tree/wpa-ethernet (top commit)

Thanks!

[ESSID "hello" with "password" as the password (pcap)](https://github.com/magnumripper/JohnTheRipper/files/1162613/hello-password-regular-ethernet.pcap.zip).

I am dumping the hash using `../run/wpapcap2john -e hello:c6:6c:4b:d0:9e:48 hello-password-regular-ethernet.pcap` command.

**Comment by kholia** [comment]
I have narrowed down the problem to following two lines,

```
memcpy(hccap.mac1, ((ether_frame_hdr_t*)pkt2)->addr1, 6);
memcpy(hccap.mac2, ((ether_frame_hdr_t*)(p13))->addr1, 6);
```

I think that EAPOL packets with Ethernet link type are currently lacking these values which causes broken hashes to be generated. Digging further!

**Comment by magnumripper** [comment]
Great. My time is very limited (due to motorcycles, beer and sun, in that order) at least until monday. Hopefully I can have a look at your code then.

**Comment by magnumripper** [comment]
@kholia I had to revert 8d7ccaf1 completely. It had hideous bugs and side effects. 802.11w still works fine, but if we want to support Ethernet encapsulation we need to revisit that. What the heck is that anyway? How were those pcaps made? Are they even valid (as in sane)?

**Comment by magnumripper** [comment]
All further discussion in #2751 please
