### ISSUE TITLE
wpapcap2john is generating broken output hashes

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2636]
[Here is a sample .pcap file to reproduce the problem](https://github.com/magnumripper/JohnTheRipper/files/1156632/regular-wpa2.pcap.zip). The password is `password`.

A git bisect run is pointing to commit 98e0672d2ff9ef83d96fc0aaf8593f0ab8fe1444 as the first bad commit. Commit 24b3091beffc4e91a47998e6539ea02d17566b6d works great.

ASan is detecting a bad memory access pattern (out-of-bounds read) with the current code during regular hash extraction operation. I will resume fuzzing wpapcap2john once these bugs are fixed.

**Comment by magnumripper** [comment]
Cool. I will look into this soon-ish unless someone else can spot the problem.

**Comment by kholia** [comment]
Here is an incorrect patch which fixes the problem for this particular pcap file,

``` diff
@@ -548,7 +553,7 @@ static void Handle4Way(int bIsQOS)
        // we already HAVE fully cracked this
 
        to_bssid(bssid, pkt->addr3);
-       for (i = nwpa - 1; i >= 0; --i) {
+       for (i = 0; i < nwpa; i++) {
                if (!strcmp(bssid, wpa[i].bssid)) {
                        ess=i;
                        break;
```

There is something weird with the way we parse the beacon packets and extract the various "tags". ASan does not like the `HandleBeacon` method at all.

**Comment by kholia** [comment]
Here is a better patch,

``` diff
diff --git a/src/wpapcap2john.c b/src/wpapcap2john.c
index 48fa37f..c02ed9a 100644
--- a/src/wpapcap2john.c
+++ b/src/wpapcap2john.c
@@ -513,6 +513,8 @@ static void HandleBeacon(uint16 subtype)
 
        while (((uint8*)tag) < pFinal) {
                char *x = (char*)tag;
+               if (x + tag->taglen > (char*)pFinal)
+                       break;
                if (tag->tagtype == 0 && tag->taglen < sizeof(essid))
                        memcpy(essid, tag->tag, tag->taglen);
                x += tag->taglen + 2;
```

This fixes the ASan problems, and also enables extraction of the correct hash.

**Comment by magnumripper** [comment]
I don't quite get it (dry-running fragments of code) but perhaps you should commit that last change and keep this issue open?

**Comment by kholia** [comment]
I recommend running wpapcap2john on the reproducer. Instead of getting "hello" as the ESSID in the output hash, a small binary string is present instead. I suspect that something is off in the `HandleBeacon` function which causes this problem. I have fixed some ASan crashes in PR https://github.com/magnumripper/JohnTheRipper/pull/2638, which magically also fixes this hash generation problem. I guess that the PR is fixing some "undefined behavior" present in the older code.

**Comment by kholia** [comment]
I think that this issue can be closed now.
