### ISSUE TITLE
static linking issue: libpcap depends on libnetlink

### ISSUE THREAD

**Issue by rofl0r** [magnumripper/JohnTheRipper#264]
the static linking mechanisms have nothing like the DT_NEEDED section in shared objects, so dependencies don't get linked in automatically.

thus when static linking is used we must use "-lpcap -lnl", or in my case "-lpcap -lnl-tiny" (libnl-tiny is a drop in replacement for netlink, so i should supposedly make a symlink libnl.a -> libnl-tiny.a)

(btw, this only affects the stuff built after john itself)

**Comment by magnumripper** [comment]
Static linking is currently out of scope for JtR out-of-the-box, and no-one seems to contribute to it. Closing.
