### ISSUE TITLE
Bleeding-jumbo compile fails with multiple definition of `main'

### ISSUE THREAD

**Issue by bill-e-ghote** [magnumripper/JohnTheRipper#2645]
Saw this starting with last 'git pull' from repo.
john.o: In function `main':
/home/wdawson/Software/bleeding-jumbo/src/john.c:1856: multiple definition of `main'
bitlocker2john.o:/home/wdawson/Software/bleeding-jumbo/src/bitlocker2john.c:186: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1441: ../run/john] Error 1
make[1]: Leaving directory '/home/wdawson/Software/bleeding-jumbo/src'
make: *** [Makefile:179: default] Error 2

**Comment by bill-e-ghote** [comment]
I solved my own issues by installing dev-libs/libFuzzer-3.9.1::gentoo. However, it's worth noting, I think, the compilation fails (for me) with the library missing.

**Comment by kholia** [comment]
Thanks for reporting this issue.

Can you please try running `make clean; ./configure; make`? I think that the problem should go away with these steps.

**Comment by kholia** [comment]
I am closing this issue now as I believe it is solved. Feel free to comment again if the issue persists. Thanks!
