### ISSUE TITLE
Not cracking complex passwords from a wordlist

### ISSUE THREAD

**Issue by gobiasinfosec** [magnumripper/JohnTheRipper#2647]
Running on Kali Linux,
Version: 1.8.0.6-jumbo-1-bleeding
Arch: 64-bit LE
Compiler version: 5.3.1 
GNU libc version: 2.21 (loaded 2.24)
OpenSSL: 1.0.2g
GMP library: 6.1.0

(This is the main computer, I've tried this on 4 different computers, including a kali-aws instance)

__________________________________________________

So the issue I'm having is that JtR seems to only be able to crack passwords of a single complexity type (alpha/numerals/special characters) when I am trying to crack it from a password list. Bruteforce works fine which tells me its not an issue with the hash itself. 

Some other weird issues is that it doesn't seem to be working at all with uppercase characters or special characters, even if it is single complexity.

I have tested this with raw-sha256, netntlmv2 and raw-md5. Absolutely no idea why this isn't working.

**Comment by kholia** [comment]
This is a very strange issue. Can you post some sample hashes which demonstrate the problem? Post your john commands as well.

While you are at it, can you build and try the latest JtR jumbo from this repository?

**Comment by gobiasinfosec** [comment]
For a quick example you can do the following:

echo -n 'a1' | sha256sum | cut -f 1 -d " " > hash
echo -n > pass a1
john --format=raw-sha256 -w pass hash

That won't work, but when you run:
john --format=raw-sha256 hash

It cracks it almost immediately. 

Here is the sample hash:
f55ff16f66f43360266b95db6f8fec01d76031054306ae4a4b380598f6cfd114

But if you do 'aa' instead of 'a1' it works with the wordlist, here is that hash:
961b6dd3ede3cb8ecbaacbd68de040cd78eb2ed5889130cceb4c49268ea4d506


Finally-> I noticed this when I was running responder and it wasn't cracking hashes that I was collecting that I knew I had the right passwords for. After some experimenting I figured this out. It's happening on all of my builds. But yeah I'll update to the new build and see if its anything different.

**Comment by kholia** [comment]
The following sequence is indeed problematic,

```
echo -n 'a1' | sha256sum | cut -f 1 -d " " > hash
echo -n > pass a1
john --format=raw-sha256 -w pass hash
```

The `john --format=raw-sha256 -w pass hash` part is incorrect I think. Use `john --format=raw-sha256 -w=pass hash` instead. See `john --help` for information on the command syntax.

**Comment by gobiasinfosec** [comment]
Yep, that would be it, I'm just an idiot. It is strange that it works without the '=' sign for non-complex passwords though. But yeah, consider this fixed, thank you!

**Comment by kholia** [comment]
Thanks.

This issue was indeed puzzling for a while :-) Happy cracking!

**Comment by solardiz** [comment]
On Mon, Jul 24, 2017 at 02:46:14PM +0000, Tobias Funke wrote:
> It is strange that it works without the '=' sign for non-complex passwords though.

Not really.  "-w" without a parameter means to use default wordlist, and then you list two hash files to load.
