### ISSUE TITLE
OpenCL support for WPA2-PSK-SHA256

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2648]
See https://github.com/magnumripper/JohnTheRipper/pull/2646, and https://github.com/magnumripper/JohnTheRipper/issues/2635.

**Comment by magnumripper** [comment]
https://github.com/magnumripper/JohnTheRipper/pull/2646#issuecomment-317613845
> http://ftp.usa.openbsd.org/pub/OpenBSD/src/sys/crypto/cmac.c seems like a fairly portable CMAC implementation.
>
> The wpa_supplicant project has another implementation of the CMAC function in src/crypto/aes-omac1.c file.
>
> Both these implementations are under the BSD license.
