### ISSUE TITLE
I have got the code of rar5tojohn.py, and I can get rar5 files' hash key, but is there a rar3tojohn.py can be used to get the old rar file's hash key?Please Help.

### ISSUE THREAD

**Issue by JialongWang1224** [magnumripper/JohnTheRipper#2649]
### IMPORTANT
- If you have questions, please ask them first in the mailing list john-users at lists.openwall.com;
- Use issues to keep track of ideas, enhancements, tasks, and bugs. NEVER as a support forum;
- Please, DO NOT create a new issue if your bug is already known:
  - OpenCL known issues #2331.
  - CUDA support is dropped from tree now. Do not post issues about that.

### Steps to reproduce
Try to be clear about your environment and what you are doing. If possible, share with us the file or hash you are auditing.

### System configuration
Attach details about your OS and about JtR, including:
- are you using bleeding-jumbo? Updated?
- `$ john --list=build-info`.
- `$ john --list=opencl-devices` (if applicable).

**Comment by kholia** [comment]
Use http://www.openwall.com/lists/john-users/ for support.

**Comment by JialongWang1224** [comment]
Thank you very much, I am a student in CHN, my English is little poor, I will visit the website you give and try to find the rar3tojohn.py. And you are so cool.

**Comment by kholia** [comment]
There is no such thing as `rar3tojohn.py`. Even `rar5tojohn.py` was removed from this repository a long time ago. It should no longer be used.

Use `rar2john.c` instead, for both RAR 3 and RAR 5 files.

**Comment by JialongWang1224** [comment]
Thanks, now I am doing a python project, so if I want to use  rar2john.c, I should first change it into python, right?

**Comment by magnumripper** [comment]
Sure. In fact, if you do a good port to Python (with all functionality intact) we might be interested in using it.
