### ISSUE TITLE
Ethereum pre-sale issue.

### ISSUE THREAD

**Issue by kost123** [magnumripper/JohnTheRipper#2651]
When trying to crack ethereum presale wallets with CPU or OpenCL (same problem) sometimes it finishes too early. Bruteforce/mask seems to work OK but when using wordlists it doesn't.

I started a wordlist of 20 GB yesterday on GPU and its ETA was 11 hours, but it finished in 2.5 hours, I tried a smaller list of about 10k passwords on CPU and it finished at about 33%.

Temps are fine.

**Comment by kholia** [comment]
How can I reproduce this problem locally? Describe all the steps involved in detail.

Which dictionary file were you using? Can you provide a sample hash which exhibits this problem?

Is the problem reproducible with the following (common) dictionary?

https://github.com/danielmiessler/SecLists/blob/master/Passwords/10k_most_common.txt

**Comment by kost123** [comment]
I used hashes.org list from weakpass.com with some simple rules appending 1-4 and do nothing.

I can't provide a sample hash. But I was able to produce it with a smaller wordlist:

roflcopy1
roflcopy2
roflcopy3
roflcopy4
roflcopy5
roflcopy6

Use this with --rules:Jumbo

It exits at 30% or so

**Comment by kholia** [comment]
I was able to observe similar behavior with following steps,

```
$ cat wordlist
roflcopy1
roflcopy2
roflcopy3
roflcopy4
roflcopy5
roflcopy6
```

Here is a sample hash for testing,

`$ethereum$w*4ab35fcb5c3101af70d5b3bf22829af3dbd48813273b17566ee364285c7bcfb2d52611a58e54d3e6be27e458073304e71e356afc4c97da0143910308f30563fe*c4dfdaa5288b477d0ff25a260ef32a24282cc4e2*97b3d2c2c8106507b87744f0b12f73c2`

```
$ ../run/john hash -w=wordlist --rules=jumbo
...
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:01 2.97% (ETA: 09:33:31) 0g/s 1674p/s 1690c/s 1674C/s y5roflcop..Rolcopy5
0g 0:00:00:02 4.26% (ETA: 09:33:44) 0g/s 1694p/s 1694c/s 1694C/s Roflcopy662..Roflcopy144
0g 0:00:00:03 7.32% (ETA: 09:33:38) 0g/s 1698p/s 1698c/s 1698C/s ROfLcOpy4..rOflcoPy5
0g 0:00:00:05 9.82% (ETA: 09:33:48) 0g/s 1708p/s 1708c/s 1708C/s roflcopy2459..roflcopy3480
0g 0:00:00:06 11.17% (ETA: 09:33:51) 0g/s 1708p/s 1708c/s 1708C/s roflcopy6757..roflcopy1779
0g 0:00:00:09 15.01% (ETA: 09:33:57) 0g/s 1711p/s 1711c/s 1711C/s Roflcopy2611..Roflcopy3632
0g 0:00:00:10 16.26% (ETA: 09:33:59) 0g/s 1710p/s 1710c/s 1710C/s Roflcopy4888..Roflcopy5909
0g 0:00:00:11 17.50% (ETA: 09:34:00) 0g/s 1707p/s 1707c/s 1707C/s roflcopy6cn..roflcopy1dj
0g 0:00:00:12 18.85% (ETA: 09:34:01) 0g/s 1705p/s 1705c/s 1705C/s roflcopy4oa..roflcopy5ov
0g 0:00:00:13 20.10% (ETA: 09:34:02) 0g/s 1704p/s 1704c/s 1704C/s roflcopy6yr..roflcopy1zn
0g 0:00:00:14 24.39% (ETA: 09:33:55) 0g/s 1701p/s 1701c/s 1701C/s jroflcopy2j..kroflcopy3e
0g 0:00:00:15 25.64% (ETA: 09:33:56) 0g/s 1697p/s 1697c/s 1697C/s uroflcopy4a..uroflcopy5v
0g 0:00:00:16 26.89% (ETA: 09:33:57) 0g/s 1694p/s 1694c/s 1694C/s ROFlCoPy6..roFlcopY1
0g 0:00:00:16 DONE (2017-08-04 09:33) 0g/s 1691p/s 1691c/s 1691C/s ROFLcOpY6..ROFLCOPY6
```

@magnumripper Your advice is needed here. I have no idea about what is going wrong here!

**Comment by kost123** [comment]
Ok so..

I'll switch to password* just to make it easier:

When trying

```
password1
password2
password3
password4
password5
password6
```

It stops at 30% mark ish.

When I scramble the passwords to this:

`passrgrword1
passwrgrord2
passworergrd3
passwordgreg4
passgrgrgword5
parggrgssword6`

It makes it to 50%

some more..

`passrgrword1
passwgregrgrord2
pasregrgsworergrd3
passrgregwordgreg4
pargrgssgrgrgword5
pgrgarggrgssword6`

100%

It is removing duplicates but not updating the % done? Is it possible that 66%+ of hashesorg is duplicates when used with rules? It certainly seems possible with these small lists.

**Comment by claudioandre** [comment]
Using:
```
../run/john  -w=wordlist --rules=jumbo --stdout > full
sort full | uniq > cleaned
wc -l cleaned
```

I compared:
```
passrgrword1
passwgregrgrord2
pasregrgsworergrd3
passrgregwordgreg4
pargrgssgrgrgword5
pgrgarggrgssword6
```
versus 
```
roflcopy1
roflcopy2
roflcopy3
roflcopy4
roflcopy5
roflcopy6
```

Then, I checked that, e.g. `16 seconds * 7602 p/s`, is the expected number of candidates.
`0g 0:00:00:16 DONE (2017-08-04 06:06) 0g/s 7602p/s 7602c/s 7602C/s psswrd1..psswrd6`

So, ETA was not updated fast enough. Other than this, reasonable results.
***

I tried a 386M wordlist and was able see ETA changing a lot. Have your checked how your 20GB wordlist behaves?

**Comment by kost123** [comment]
When you say not updated fast enough.. the output I posted above I tried on a list of about 10,000 passwords all of password1, password2.. etc format and it wasn't really a case of not being updated fast enough it was random jumps throughout, also why would the ETA not update fast enough for similar passwords but update fine on jumbled up ones?

**Comment by claudioandre** [comment]
> also why would the ETA not update fast enough for similar passwords but update fine on jumbled up ones?

Ok, you are right to disbelieve me. What I thought was:
- we are running 22k rules (approx) in the example;
- `--rules=jumbo` has a rule that deletes the last character; similarity becomes equality;
- then `Q` start rejecting all/every after rule # 7k (or 25%); 
- all rules were tried; but a lot were rejected and it seemed correct on a first thought;
- at the end, I used `stdout`and `wc` to confirm that things make sense;
- when running on a dissimilar wordlist, a lot of rules/words are rejected (above rule 7k), but not all of them.

That said, I was confident things are ok, but I failed to make a prove that JtR is working properly. In this case, the issue remains open.

****
Q	query the memory and reject the word unless it has changed

**Comment by claudioandre** [comment]
* As another evidence, I patched JtR to do nothing on `Q` rule:
```
diff --git a/src/rules.c b/src/rules.c
index 94ca9eb..0531fd7 100644
--- a/src/rules.c
+++ b/src/rules.c
@@ -1867,8 +1867,8 @@ char *rules_apply(char *word_in, char *rule, int split, char *last)
                        break;
 
                case 'Q':
-                       if (!strncmp(memory, in, rules_max_length))
-                               REJECT
+                       //if (!strncmp(memory, in, rules_max_length))
+                       //      REJECT
                        break;
 
                case 'X': /* append/insert/prepend substring from memory */
```

* Patched, it run up to 100% (producing dupes is my guess).
```
0g 0:00:03:06 95,52% (ETA: 19:39:27) 0g/s 640.3p/s 640.3c/s 640.3C/s ROFlcopy2..ROFlcopy5
0g 0:00:03:07 95,95% (ETA: 19:39:27) 0g/s 640.2p/s 640.2c/s 640.2C/s ROFlcoPY2..ROFlcoPY5
0g 0:00:03:08 96,48% (ETA: 19:39:27) 0g/s 640.3p/s 640.3c/s 640.3C/s ROFlcOPY4..ROFlcOPY1
0g 0:00:03:09 96,96% (ETA: 19:39:27) 0g/s 640.3p/s 640.3c/s 640.3C/s ROFlCoPy2..ROFlCoPy5
0g 0:00:03:10 97,44% (ETA: 19:39:27) 0g/s 640.5p/s 640.5c/s 640.5C/s ROFlCOpY6..ROFlCOPy3
0g 0:00:03:11 97,97% (ETA: 19:39:27) 0g/s 640.6p/s 640.6c/s 640.6C/s ROFLcopY2..ROFLcopY5
0g 0:00:03:12 98,45% (ETA: 19:39:28) 0g/s 640.7p/s 640.7c/s 640.7C/s ROFLcOpy6..ROFLcOpY3
0g 0:00:03:13 98,93% (ETA: 19:39:28) 0g/s 640.8p/s 640.8c/s 640.8C/s ROFLCopy4..ROFLCopy1
0g 0:00:03:14 99,46% (ETA: 19:39:28) 0g/s 641.0p/s 641.0c/s 641.0C/s ROFLCoPY6..ROFLCOpy3
0g 0:00:03:15 99,94% (ETA: 19:39:28) 0g/s 641.1p/s 641.1c/s 641.1C/s ROFLCOPY4..ROFLCOPY1
0g 0:00:03:15 DONE (2017-08-05 19:39) 0g/s 641.0p/s 641.0c/s 641.0C/s ROFLCOPY6..ROFLCOPY6
```

* Then, I compared the two wordlists produced. At last, `diff` told me both files are equal. 
```
$ ../run/john  -w=wordlist --rules=jumbo --stdout > regular
Press 'q' or Ctrl-C to abort, almost any other key for status
28063p 0:00:00:00 100,00% (2017-08-05 19:50) 400900p/s ROFLCOPY6

$ sort regular | uniq > reg_uniq
$ wc -l reg_uniq
26311 reg_uniq

$ ../run/johnQ  -w=wordlist --rules=jumbo --stdout > Qless
Press 'q' or Ctrl-C to abort, almost any other key for status
125197p 0:00:00:00 100,00% (2017-08-05 19:51) 1788Kp/s ROFLCOPY6

$ sort Qless | uniq > q_uniq
[claudio@super src]$ wc -l q_uniq
26311 q_uniq
```

Don't be upset with me, but, I am convinced things are ok.

**Comment by kost123** [comment]
Ofcourse I am not upset! I am only trying to find the end result of this :) It does appear by your work that everything is fine, so any patch to this would be purely cosmetic.

**Comment by kholia** [comment]
Thanks for helping me out here @claudioandre 👍
