### ISSUE TITLE
Add support for Dashlane password manager

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2658]
* https://courses.csail.mit.edu/6.857/2016/files/25.pdf

* https://gist.github.com/roblabla/4a43d0a5fc3769c815ab

* https://www.dashlane.com/download/Dashlane_SecurityWhitepaper_v2.8.5.pdf

Grabbing the password database seems to be the tricky part?

Update:

I have the various parts working now. Only the partial zlib stream decompression stuff is yet to be figured out.

**Comment by kholia** [comment]
Other things to look at,

* Data (.aes files) from Android devices.

* Dashlane secure archives created by Desktop versions of Dashlane.

**Comment by kholia** [comment]
Here is some sample Dashlane data for testing -> [Dashlane Sample Data.zip](https://github.com/magnumripper/JohnTheRipper/files/1220368/Dashlane.Sample.Data.zip)

**Comment by kholia** [comment]
https://hackerone.com/reports/227663 was super useful in figuring out this stuff. See `aes.mov` video from this link ;)

**Comment by kholia** [comment]
This is done now. Hence I am closing this issue.

**Comment by kholia** [comment]
https://stackoverflow.com/questions/25431160 (maximum size of encoded dynamic Huffman tree as used by DEFLATE). We might need to take this into consideration in our cracking code.

**Comment by magnumripper** [comment]
We have very clever early-rejection for various types of Huffman encoding in PKZIP and RAR formats.

**Comment by kholia** [comment]
EDPR in action,

![elcomsoft-edpr](https://user-images.githubusercontent.com/79528/30046218-acbbd11a-9226-11e7-861b-9969c8520e25.png)
