### ISSUE TITLE
"--fork" with multiple GPUs fails after commit 0168a45a

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2664]
As reported by Luis Rocha on john-users, trying to use multiple GPUs via "--fork" fails on recent bleeding-jumbo. In my testing with "--fork=2" and two GPUs, the child process becomes a zombie. Reverting the following commit fixes the issue for me:

```
commit 0168a45a145d3c3ff714dd9f6bf73128f5408bac
Author: magnum <john.magnum@hushmail.com>
Date:   Tue May 16 10:54:15 2017 +0200

    Don't start "the clock" until all loading, auto-tune etc. are done. This
    ensures stable speed readings from start, and things like --progress-every
    and --max-run-time will work better.
```

(Did we really have this fairly basic functionality broken for 3 months? I happen to have been occasionally using a build from May 15, so I wouldn't notice.)

**Comment by claudioandre** [comment]
As I wrote here: https://github.com/magnumripper/JohnTheRipper/issues/2547#issuecomment-322016628

There is a workaround, if anyone need it.

**Comment by solardiz** [comment]
Interesting. I vaguely recalled seeing those comments, but couldn't find them as I only searched for issues with "fork" in the description. I came up with 0168a45a145d3c3ff714dd9f6bf73128f5408bac being relevant on my own. I've just tried debugging this - for me, the problem _does_ occur on "super", and specifically the child process gets killed by SIGALRM - or at least that's what happens when I run under "strace -fF". There's no "-33" output either way (with "-verb=5"). So there appear to be two different issues: the "-33" and whatever bug was introduced by that commit.

**Comment by claudioandre** [comment]
> So there appear to be two different issues: the "-33"

The -33 happens only on darkbyte's machine and i'm pretty sure is caused by the OpenCL driver. What I meant was exactly that: 2 different issues.

**Comment by magnumripper** [comment]
The (now removed) `sig_init_timer()` in `sig_init_child()` should have been dropped in 0168a45a as more things happens *after* forking now. Not doing so meant things happened in weird order (the timer started raising SIGALRM although there was no handler for it yet).

The problem did not affect MPI, only fork, and that's why I never saw it. But it's strange no-one reported the problem much earlier.
