### ISSUE TITLE
wpapsk-opencl doesn't reject WPA-PSK-SHA256 hashes

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2678]
wpapsk-opencl gladly accepts the last three test vectors from the CPU format (that are supposed to be WPA-PSK-SHA256) even though it doesn't yet support them. This is a BIG no-no as users will get false negatives.

One of them, however, is actually cracked (the one with 12345678). Is that one really "802.11w with WPA-PSK-SHA256"?

**Comment by magnumripper** [comment]
This bug wasn't caused by 83d9406a0 - we always had it. I think we can simply test `hccap.keyver` in valid(). I'll fix this.

**Comment by kholia** [comment]
Good catch 👍

**Comment by magnumripper** [comment]
> One of them, however, is actually cracked (the one with 12345678). Is that one really "802.11w with WPA-PSK-SHA256"?

It's not. I moved it and dropped the misleading comment.
