### ISSUE TITLE
rar2john.exe issues windows

### ISSUE THREAD

**Issue by itchyballsack** [magnumripper/JohnTheRipper#2680]
Whenever I run rar2john.exe with cygwin1.dll provided in 'community-enhanced version' on http://www.openwall.com/john/ I get the error `0 [main] rar2john 2860 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer`. When I use latest cygwin1.dll it says 'application was unable to start correctly'. Any ideas?

**Comment by itchyballsack** [comment]
Whenever I run rar2john.exe with cygwin1.dll provided in 'community-enhanced version' on [.](http://www.openwall.com/john/) I get the error '0 [main] rar2john 2860 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer'. When I use latest cygwin1.dll it says 'application was unable to start correctly'. Any ideas?

**Comment by kholia** [comment]
Does the latest MinGW JtR jumbo build work for you? Use http://daily-builds.appspot.com/latest URL to download it.

This URL is linked to from the https://github.com/magnumripper/JohnTheRipper/ page.

**Comment by kholia** [comment]
I believe that such issues should be reported to "john-users" mailing list instead of here.

https://github.com/magnumripper/JohnTheRipper/ says,

This is a bug tracker, not a support forum. It's also not the place to report bugs you see in any version of Jumbo other than the LATEST, from HERE!

**Comment by itchyballsack** [comment]
It runs but is leaves a blank hash http://www.mediafire.com/file/6n7hsjsh1m7w3mf/SHIELD.rar

**Comment by itchyballsack** [comment]
This is the small rar I am trying to generate the hash file for, does it work for you?

**Comment by itchyballsack** [comment]
never mind, it worked when I extracted everything into the folder, what does rar2john need to run so I can delete everything unnecessary

**Comment by kholia** [comment]
@itchyballsack I don't know the answer to that particular question. Perhaps it is something to discover for yourself?

@solardiz This issue might need attention from your side. http://www.openwall.com/john/j/john180j1w.zip build might not be working 100%.

**Comment by solardiz** [comment]
> @solardiz This issue might need attention from your side.

Not when @itchyballsack clarified that the problem was caused by not extracting all of the `run` directory contents. Indeed, there are more DLLs in there, and with our symlink emulation approach many of the `*2john.exe` programs depend on `john.exe`.

**Comment by kholia** [comment]
Good point. Just to be on the safe side, I checked out the `john180j1w.zip` build on Windows 10.

```
C:\Users\...> rar2john.exe
0 [main] rar2john 5876 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.
Please report this problem to the public mailing list cygwin@cygwin.com

Usage: rar2john [-i <inline threshold>] <rar file(s)>
Default threshold is 1024 bytes (data smaller than that will be inlined)
```

The "FAST_CWD" warning message is present but the binary works, and is able to extract hashes from RAR files.

I think that our automatically generated MinGW builds might work better for users, with some additional work (e.g. AVX2 support with fallback binary chains).
