### ISSUE TITLE
Add support for cracking PGP Virtual Disk images

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2692]
Sample screenshots,

![pgp virtual disk 1](https://user-images.githubusercontent.com/79528/29514702-1650410c-8687-11e7-8ef1-ec93a765f0dc.png)
![pgp virtual disk 2](https://user-images.githubusercontent.com/79528/29514703-16807232-8687-11e7-983d-4ba7fd8852e9.png)

Sample data -> [Sample PGP Virtual Disk Images - openwall.zip](https://github.com/magnumripper/JohnTheRipper/files/1238500/Sample.PGP.Virtual.Disk.Images.-.openwall.zip). Password used is `openwall`.

**Comment by kholia** [comment]
More sample data for testing -> [Sample PGP Disk images.zip](https://github.com/magnumripper/JohnTheRipper/files/1242496/Sample.PGP.Disk.images.zip).

**Comment by kholia** [comment]
This is now done.

**Comment by kholia** [comment]
![edpr-pgp-disk-weird](https://user-images.githubusercontent.com/79528/29994314-a03feb08-8fea-11e7-9baa-4735a42aa941.png)

The latest version of EDPR works fine when cracking PFX files but it seems to be buggy when attacking `.pgd` files. It doesn't make use of the GPU and the cracking speed is low.

On the same box, JtR runs just fine.

```
$ ../run/john --test --format=pgpwde-opencl
Will run 4 OpenMP threads
Device 0: GeForce GTX 1050 Ti
Benchmarking: pgpwde-opencl [SHA1 OpenCL]... (4xOMP) DONE
Raw:	75350 c/s real, 45381 c/s virtual

$ ../run/john --test --format=pgpdisk-opencl
Will run 4 OpenMP threads
Device 0: GeForce GTX 1050 Ti
Benchmarking: pgpdisk-opencl [SHA1 OpenCL]... (4xOMP) DONE
Raw:	55296 c/s real, 39781 c/s virtual
```

**Comment by magnumripper** [comment]
Our speed is far from optimized though. Optimized code would not use the CTX versions of SHA-1 but fill raw buffers instead (using almost exclusively 32-bit operations), and call the raw SHA-1 digest function.

That would end up significantly faster but can be tricky to implement depending on how long and/or varying the input is. If we're lucky, some pre-processing could be done once in set_salt (or even get_salt) though, preparing almost-ready-to-use blocks of data.

**Comment by kholia** [comment]
@magnumripper I agree.

From https://www.elcomsoft.com/edpr.html,

Important note: hardware acceleration (for specific file formats and algorithms only, see the above chart for details) works properly only on Windows Server 2003/2008/2012 and Windows 7/8/8.1/10 (32-bit or 64-bit); specific versions of NVIDIA/AMD drivers are required; some other restrictions apply (e.g. for some file formats, it is implemented for brute-force attack only, while dictionary attack only works on the CPU, regardless the settings).

Keeping this in mind, I got the benchmark numbers from EDPR.

![edpr-pgp-disk-gtx-1050-ti](https://user-images.githubusercontent.com/79528/30000805-257cd8fc-9096-11e7-88f7-cd1592846e33.png)
![edpr-pgp-disk-gtx-1050-ti-2](https://user-images.githubusercontent.com/79528/30000806-257d23de-9096-11e7-9681-ec74a1c701d4.png)

EDPR does 140,000 c/s on a GTX 1050 Ti card while we currently get 55,296 c/s on the same card.

This is not a pure GPU format yet, AES / Twofish / CAST encryption of one block is done on the CPU. Also the usage of `SHA1 CTX` stuff is present.
