### ISSUE TITLE
Add OpenCL support for PGP WDE format

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2694]
The required kernel should be quite similar to `opencl/gpg_kernel.cl`.

**Comment by kholia** [comment]
@magnumripper Would you like me to attempt writing a quick-and-dirty version first?

It would be nice to compare speeds with Elcomsoft EDPR. I could not get EDPR to work with any of the sample PGP WDE disk images we have, so it would be hard to know the actual speed of EDPR. However, I do have an old picture which shows EDPR's speed on GTX 295.

**Comment by magnumripper** [comment]
Sure, give it a try!

**Comment by kholia** [comment]
For reference,

![pgp_2009](https://user-images.githubusercontent.com/79528/29719355-5688e69e-89d3-11e7-8b2a-752b82554543.gif)
