### ISSUE TITLE
"ztex/*" runtime pathnames should use $JOHN and be path_expand()'ed

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#2714]
descrypt-ztex failed with the following messages:
```
$ LANG=C john --test=5 --format=descrypt-ztex
Benchmarking: descrypt-ztex, traditional crypt(3) [DES ZTEX]... fopen(ztex/inouttraffic.ihx): No such file or directory
fopen(ztex/inouttraffic.ihx): No such file or directory
no valid ZTEX devices found
```

There is ztex/inouttraffic.ihx in run/ and in src/ . I can run the
test ok standing in run/ . After that, I can run descrypt-ztex from
other folders too. But bcrypt-ztex fails in other folders:
```
$ LANG=C john --test=5 --format=bcrypt-ztex
Benchmarking: bcrypt-ztex [Blowfish ZTEX]... fopen(ztex/ztex115y_bcrypt.bit): No such file or directory
```

I think, path starting from $JOHN should be used always.

john was rebuilt today after `git pull`:
Version: 1.8.0-jumbo-1-5825-g2a18678
Build: linux-gnu 64-bit SSE4.1-ac
SIMD: SSE4.1, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1

**Comment by solardiz** [comment]
@Apingis please look into this. (I haven't yet. The issue title edit is based on my best guess.)

**Comment by Apingis** [comment]
Confirmed issues, they are remnants from standalone application
- $JOHN, path_expand() are not used, fopen() fails if CWD is other than run/
- duplicate inouttraffic.ihx in both run/ and src/
