### ISSUE TITLE
Improve and rename krbpa2john.py script

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2721]
See PR https://github.com/magnumripper/JohnTheRipper/pull/2709.

This PR enhances the krbpa2john.py script to extract hashes from AS-REP messages. I think we need a better filename for our krbpa2john.py script since it does more than pre-authentication (pa) stuff now.

Sample .pcap files -> [AS-REP-examples-openwall.zip](https://github.com/magnumripper/JohnTheRipper/files/1272903/AS-REP-examples-openwall.zip)

The script generates two hashes for a single AS-REP packet in `AS-REP-eTYPE-RC4-HMAC-openwall.pcap` file. This is not correct. The script needs to only consider the second `enc-part` portion of the AS-REP packet. Ideas on how to do this are welcome!

We don't have a format to handle `AS-REP-eTYPE-AES256-CTS-HMAC-SHA1-96-openwall.pcap` currently. Maybe @Fist0urs can help with this part ;)

[KRB5-MitM-krb5_down-openwall.zip](https://github.com/magnumripper/JohnTheRipper/files/1287218/KRB5-MitM-krb5_down-openwall.zip) (for testing pre-authentication stuff).

**Comment by magnumripper** [comment]
> I think we need a better filename for our krbpa2john.py script since it does more than pre-authentication (pa) stuff now.

I guess we could rename it to just krb2john.py. Other possibilities are krbpcap2john.py, kerberos2john.py...

**Comment by magnumripper** [comment]
Perhaps krbpcap2john.py is best - Like wpapcap2john and vncpcap2john the name "alerts" the user that it's separate from pcap2john.py. OTOH since this is Python code, why not scrap the separate file and incorporate the code in pcap2john.py?

**Comment by kholia** [comment]
I forgot to note that krbpa2john.py program does not operate on `.pcap` files directly. First a `.pcap` files needs to be converted to a `.pdml` file. Subsequently krbpa2john.py needs to be used with the generated `.pdml` file.

The comments in the krbpa2john.py file explain this process.

**Comment by magnumripper** [comment]
Would it be hard for us (well, you) to rewrite it so we support pcap directly?

**Comment by kholia** [comment]
It can be done but it would involve writing a lot of new code for doing ASN.1 DER decoding and parsing of pretty large KRB5 messages. Such code is also likely to be error-prone (at least initially).

**Comment by kholia** [comment]
https://github.com/lgandx/PCredz/blob/master/Pcredz#L210 <- Code to extract `$krb5pa$23$` hashes from a .pcap file.

It uses a lot of hardcoded offsets and only works for UDP Kerberos messages. The code doesn't seem to be robust and reliable to me.

It doesn't extract the hash from `KRB5-MitM-krb5_down-openwall.pcap` file which is attached to this issue.

**Comment by kholia** [comment]
Also look at https://github.com/nidem/kerberoast/blob/master/extracttgsrepfrompcap.py script.

**Comment by kholia** [comment]
@magnumripper How do the names `krb2john.py` and `krb5tojohn.py` sound to you?

**Comment by magnumripper** [comment]
krb2john.py is better IMHO
