### ISSUE TITLE
Clean up Travis CI tests

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2736]
Due to an update on Travis Trusty images (on Sept. 7th, 2017), a lot of new crazy stuff can be seen in Travis builds:
* 3 https://travis-ci.org/magnumripper/JohnTheRipper/jobs/273111246
* 4 https://travis-ci.org/magnumripper/JohnTheRipper/jobs/273111248
* 6 https://travis-ci.org/magnumripper/JohnTheRipper/jobs/273111250

There are workarounds for every problem. I volunteer to fix it, and suggest that while at it, we remove all problematic (therefore useless) tests.

**Comment by kholia** [comment]
Thanks @claudioandre 👍 

I agree about removing the useless (and mostly ignored) tests.

**Comment by magnumripper** [comment]
Thanks. The missing libomp is weird, isn't that a problem Travis should fix at their end?

**Comment by claudioandre** [comment]
> The missing libomp is weird, isn't that a problem Travis should fix at their end?

More or less. The new "image" does not have the needed package installed by default (their decision, I guess). A lot of people are shrinking stuff recently.
