### ISSUE TITLE
Problem with status indicator

### ISSUE THREAD

**Issue by jeroen-80** [magnumripper/JohnTheRipper#2747]
Normally I (try to) crack a very limited number of hashes with an enormous keyspace. The status indicator works fine.

I recently had a rare case: cracking an enormous amount of hashes with a very limited keyspace (few lines dictionary). Now things go wrong. John instantly reports:

0g 0:11:54:05 DONE (2017-09-11 00:35) 0.00000g/s 0p/s 15.5c/s 15.5C/s ..zzzzzzz, where the ETA is the current system time.

However, the large hash set containing slow hashes will run for another week or two.

I guess it's got something to do with having all dictionary values queued in a thread (= DONE) without tracking the actual status (something like math containing password 1 out of 10 on hash 1 out of 1.000.000).

Running on Linux x86-64 on CPU from GIT.

**Comment by magnumripper** [comment]
What was the exact command line? How many salts are involved?

**Comment by frank-dittrich** [comment]
I think the behavior ids expected if the total number of password candidates is <= MAX_KEY_PER_CRYPT*OMP_NUM_THREADS.

**Comment by jeroen-80** [comment]
>What was the exact command line?
>How many salts are involved?

```
bofh@dev:/opt/JohnTheRipper/run$ wc -l /tmp/bcrypt.test
1784891 /tmp/bcrypt.test
bofh@dev:/opt/JohnTheRipper/run$ cat /tmp/dict.test
password
password01
bofh@dev:/opt/JohnTheRipper/run$ ./john /tmp/bcrypt.test --wordlist=/tmp/dict.test
Using default input encoding: UTF-8
Loaded 1784889 password hashes with 1728169 different salts (bcrypt [Blowfish 32/64 X2])
Remaining 1784888 password hashes with 1728168 different salts
Loaded hashes with cost 1 (iteration count) varying from 16 to 16384
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:01 DONE (2017-09-11 12:59) 0g/s 0p/s 16.84c/s 16.84C/s password..password01
```
The cracking process will eventually finish, but not near the current datetime it's displaying.

**Comment by solardiz** [comment]
The reported behavior is as expected for the current implementation, lacking per-salt progress tracking. I'll leave it up to magnum to decide on whether to simply close this issue, or maybe open an issue for a potential enhancement on this area - but I doubt anyone would work on that any time soon, if at all.

That said, there's some end-user support we could provide on the posted example, if this is brought up on john-users as it should be. Specifically, I'd recommend splitting the large set of hashes across several JtR invocations by cost. Running against such a wide range of cost values at once is suboptimal - not in terms of efficient use of CPUs (it's fine for that), but in terms of progressing through the wordlist.

**Comment by magnumripper** [comment]
> I doubt anyone would work on that any time soon, if at all.

Me too, closing.

**Comment by solardiz** [comment]
"Loaded hashes with cost 1 (iteration count) varying from 16 to 16384" - BTW, it's a bad idea to mix very different cost hashes in one JtR invocation like that. This is a reason why we added reporting of those costs. You could proceed through a lot more candidate passwords on the lower cost ones of these hashes, and likely crack more hashes total in the same amount of real time (if you split the allotted time e.g. in two halves by the tunable costs, which Frank's added command-line options allow you to do easily). But this becomes a john-users topic, not a closed GitHub issue topic.
