### ISSUE TITLE
wpapcap2john: Add "ethernet encapsulation"

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2751]
See #2635 

I reverted 8d7ccaf1 (in fd852c77) after seeing very strange side effects of it. Here's some ways to reproduce:

[WPA-PSK-SHA256-session.pcap](https://github.com/magnumripper/JohnTheRipper/files/1156223/WPA-PSK-SHA256-session.pcap.zip)
[n-02.cap](https://mega.nz/#!mExTULzA!LD4wYQh8aMoHrWrISh-n3wUnYGdzQq_nA8IVKcRZypQ)
```
./wpapcap2john WPA-PSK-SHA256-session.pcap > 1
./wpapcap2john n-02.cap > 2
./wpapcap2john WPA-PSK-SHA256-session.pcap n-02.cap > 3
./wpapcap2john n-02.cap WPA-PSK-SHA256-session.pcap > 4
```
Now compare the four outfiles. Data from `n-02.cap` gets *into* the data from `WPA-PSK-SHA256-session.pcap`.

Another problem is that dupe suppression is busted for Ethernet pcaps.

**Comment by magnumripper** [comment]
> Another problem is that dupe suppression is busted for Ethernet pcaps.

Actually, I now realize that is why the above problem happens! We have this:
```diff
+       // hack for ethernet packet captures (non-monitor mode)
+       if (bIsQOS == 3) {
+               p = packet;
+               ess = 0;
```
The `ess = 0` is a very, very bad idea...

We can probably put the code in 8d7ccaf back after some revision of it. I really want this code still in play:
```c
        for (i = nwpa - 1; i >= 0; --i) {
                if (!strcmp(bssid, wpa[i].bssid)) {
                        ess=i;
                        break;
                }
        }
        if (ess == -1) {
                fprintf(stderr, "Saw BSSID with unknown ESSID. Perhaps -e option needed?\n");
                goto out;
        }
        if (wpa[ess].fully_cracked)
                goto out;  // no reason to go on.
```
Note that if you don't get any beacons from this kind of files (due to PMF?), they should be manually entered using the already present `-e` option (eg. `-e Networkname:de:ad:ca:fe:ba:be`).

**Comment by magnumripper** [comment]
BTW we should add the (at least two) samples we have for this kind of pcaps to http://openwall.info/wiki/john/sample-non-hashes#WPA-PSK

**Comment by magnumripper** [comment]
Moving question from #2635 to here: How were those pcaps made? Are they even valid (as in sane)?

**Comment by kholia** [comment]
I believe that these "Ethernet pcaps" are just fine. They were generated by Wireshark sniffing on a WiFi device which was not in monitor mode. Wireshark dissects these pcap files very well.

**Comment by kholia** [comment]
> I reverted 8d7ccaf (in fd852c7) after seeing very strange side effects of it.

Maybe some global or static state is not getting reset between the processing of two .pcap files. I will double-check this.

**Comment by magnumripper** [comment]
Note that the whole `wpa[]` array is "global", not per file.

**Comment by magnumripper** [comment]
I took at stab at it in #2752. My code too is somewhat hairy, but it's less intrusive and keeps full functionality of wpa[ess] ie. dupe checking and so on.

What I do is "fabricate" a fake 802.11 packet using the original Ethernet data. It seems to work just fine, also when processing multiple files, and including with different encapsulations.
