### ISSUE TITLE
Mention AMDGPU-PRO driver in the documentation

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2765]
Links

* http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx
* http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Install.aspx

Our `../doc/INSTALL-UBUNTU` file needs to be updated with this information.

I don't have a AMD Radeon card to test this myself.

Note: Also test the ROCm component to see how our formats fare.

**Comment by claudioandre-br** [comment]
Bug closed as:

* **Fixed** - It was fixed.
