### ISSUE TITLE
Inside the run directory, john-local.conf is included twice

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2776]
Uncovered by magnum's recent verbosity adjustments:
```
~/git/JtR$ run/john --list=sections |grep new-section
list.rules:new-section
~/git/JtR$ cd run/
~/git/JtR/run$ ./john --list=sections |grep new-section
Warning! Section [list.rules:new-section] overridden by john-local.conf
list.rules:new-section
list.rules:new-section
~/git/JtR/run$ ./john --list=ext-modes |head -n 1
Warning! Section [list.rules:new-section] overridden by john-local.conf
repeats32
~/git/JtR/run$ tail john.conf

# include john-local.conf (This file can be created by user, to override defaults in this john.conf file)
.include '$JOHN/john-local.conf'

# include john-local.conf in local dir, it can override john.conf, john-local.conf (or any other conf file loaded)
.include './john-local.conf'

# End of john.conf file.
# Keep this comment, and blank line above it, to make sure a john-local.conf
# that does not end with \n is properly loaded.
```

If I would redefine a john.conf section, I definitely want to know about it.
But if I get that warning for every section defined in john-local.conf, that's annyoing.

**Comment by frank-dittrich** [comment]
I updated the issue description, since the
```
~/git/JtR/run$ ./john --list=ext-modes |head -n 1
Warning! Section [list.rules:new-section] overridden by john-local.conf
repeats32
```
part was missing

**Comment by frank-dittrich** [comment]
May be one of these 2 includes has to be renamed to john.local.conf.

**Comment by magnumripper** [comment]
I think we need the conf to stay as-is so perhaps we need some logic added so we don't load the second one if already loaded.

**Comment by magnumripper** [comment]
I bet #2480 is actually caused by this? Then we can close that issue and keep this one.

**Comment by frank-dittrich** [comment]
There may be reasons to include the same include twice, so don't disallow that. Just avoid loading the same include twice in a row.
I still think just renaming run/john-local.conf to run/john.local.conf is easier (except the need to adjust docs/release notes) and less confusng.

**Comment by magnumripper** [comment]
> I still think just renaming run/john-local.conf to run/john.local.conf is easier

No way. The current intended behavior, that $JOHN/john-local.conf can override other files and ./john-local.conf can override THAT and everything else, is great. We just need to fix the double sourcing.

**Comment by magnumripper** [comment]
> We just need to fix the double sourcing.

Just to be clear: When CWD is **not** same as $JOHN, we SHALL source both, if both exist.
