### ISSUE TITLE
Incorrect advisory while using --stdin: "consider --fork=N"

### ISSUE THREAD

**Issue by Apingis** [magnumripper/JohnTheRipper#2777]
### Steps to reproduce
$ perl comb.pl <20k.txt |/bleeding-jumbo/run/john.exe --stdin /bleeding-jumbo/run/pw-c8
Using default input encoding: UTF-8
Loaded 1 password hash (dynamic_2006 [md5(md5($p).$s) (PW > 55 bytes) 256/256 AVX2 8x3])
Warning: no OpenMP support for this hash type, consider --fork=4
Press Ctrl-C to abort, or send SIGUSR1 to john process for status

### System configuration
Using bleeding-jumbo. Updated.

**Comment by solardiz** [comment]
Yes. `--fork` isn't expected to work right with `--stdin`. Perhaps this affects the core tree as well, so I should patch it there.

What about jumbo's `--pipe` - is it compatible with `--fork` or not? (I don't know.)

**Comment by magnumripper** [comment]
No, I can't picture `--pipe` working well with `--fork` either.
