### ISSUE TITLE
Unsupported protected powerpoint (.pps) format (office2john.py)

### ISSUE THREAD

**Issue by fungos** [magnumripper/JohnTheRipper#2780]
Found an old .pps which looks like office2john does not support.

The file is here: [pw.zip](https://github.com/magnumripper/JohnTheRipper/files/1328223/pw.zip).

Trying to run office2john gives the following error:  https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/office2john.py#L2589

```
pw.pps : Document is corrupt, or ../run/office2john.py has a bug
```

Not sure which version of office it was created, but If I recall correctly, it is from about 2008 (so some office between 2006-2008 most probably).

**Comment by kholia** [comment]
@fungos Do you know the original password for this file? Are you certain that the file is not corrupt?

**Comment by fungos** [comment]
My wife can't remember the password, but I'm looking for it as I'm sure it is written down somewhere in her uni material. Almost sure it is not corrupt, I have a lot more files protected with the same password that I can make available. I've tried some trial password recovery tools and all say they found it, but I can't be sure.

**Comment by kholia** [comment]
Thanks for this information 👍 

Do you have a similar `.pps` file with a known password available? If not, would it be possible for you to create such a file using the old version of MS Office? Having a reproducer available would greatly simplify the debugging task.

The `find_rc4_passinfo_ppt` function looks shaky and it has comments indicating that it is potentially buggy.

**Comment by kholia** [comment]
Notes for developers,

https://blogs.msdn.microsoft.com/openspecification/2009/05/08/rc4-cryptoapi-encryption-password-verification/.

Is parsing of `.ppt` files somehow different from the parsing of `.pps` files?

**Comment by kholia** [comment]
@fungos PR https://github.com/magnumripper/JohnTheRipper/pull/2786 should fix this issue. Please give it a try, and do report back your results.

**Comment by fungos** [comment]
Looks like it works, still trying to find the actual password with John though.

Thanks for the amazing fast fix and sorry for the delay.

**Comment by kholia** [comment]
@fungos No worries, and good luck for cracking the password. 

Thank you for helping in making JtR better 👍
