### ISSUE TITLE
pdf2john hash issue

### ISSUE THREAD

**Issue by oscalation** [magnumripper/JohnTheRipper#2782]
Hoping to chat with magnum about this.

 I was working with a pdf, opening in notepad ++ shows it was pdf version 1.4. 10500. 
I was able to extract the hash but i continued to get length exception errors in hashcat. The hash I received was not the proper length according to the example hashes listed on hashcat wiki. 

I tried all pdf types for the -m in hashcat (10400 - 10700).

The password was recoverable however with a commercial password recovery tool. 

I was using the newest version of pdf2john.pl program.

**Comment by oscalation** [comment]
$pdf$1*2*40*-4*1*36*65623237393831382d636439372d343130332d613835372d343164303037316639386134*32*c7230519f7db63ab1676fa30686428f0f997932bf831f1c1dcfa48cfb3b7fe99*32*161cd2f7c95283ca9db930b36aad3571ee6f5fb5632f30dc790e19c5069c86b8

**Comment by kholia** [comment]
Debugging this issue will require access to the original (or equivalent) PDF file. Please send a copy of the file to me and @magnumripper.

**Comment by magnumripper** [comment]
> Hoping to chat with magnum about this.

@kholia is a better choice, he wrote it!

**Comment by kholia** [comment]
I didn't write it. I can't read and write Perl. I just added some "printf" calls at the right locations in ExifTool program :-)

It seems that we need to add some error handling instead of generating broken output hashes. It seems that Perl keep running even if errors occur in the execution of the program.

**Comment by kholia** [comment]
@oscalation Which commercial password recovery tool was able to parse this PDF file? I am curious.

**Comment by oscalation** [comment]
I can provide pdf - where and to whom shall i send it? 

elcomsoft PDF breaker and EDPR both cracked it

**Comment by kholia** [comment]
@oscalation Great! You may send the PDF along with the correct password (if possible) to `dhiru.kholia [at] gmail.com`. Thank you.

**Comment by kholia** [comment]
@oscalation Did you email the PDF file to me? I haven't received the file yet.

**Comment by oscalation** [comment]
send email now

**Comment by oscalation** [comment]
actually let me check a few things

**Comment by oscalation** [comment]
email with pdf sent

**Comment by kholia** [comment]
Thanks @oscalation. I was able to reproduce and solve the problem.

After applying the patch from PR https://github.com/magnumripper/JohnTheRipper/pull/2790,

```
$ ../run/john hash
Using default input encoding: UTF-8
Loaded 1 password hash (PDF [MD5 SHA2 RC4/AES 32/64])
Cost 1 (revision) is 2 for all loaded hashes
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
vision           (something.pdf)
```

The bug was present in the format, and not in `pdf2john.pl` program.

**Comment by kholia** [comment]
PR #2790 has been merged. Hence, this bug can be closed now.
