### ISSUE TITLE
gpg2john parser not robust, error reporting missing

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2783]
When invoked on a text file with both a public and a private key in it (in that order), `gpg2john` produces empty output and exits 0, yet invoked on only the private key portion of the same file it extracts the key just fine.

When invoked on a non-existent or unreadable file, `gpg2john` also produces empty output, including nothing on stderr, and also exits 0:

```
$ ./gpg2john nonexistent
$ echo $?
0
$ ./gpg2john /dev/sda
$ echo $?
0
```

Perhaps `gpg2john` should parse files with more than just the private key in them. Including with multiple private keys (processing all of them) intermixed with other content. When it fails to find any valid input or/and encounters an error, it should print something to stderr and exit non-zero.

**Comment by kholia** [comment]
Regarding the mixed input file.

```
$ cat ../doc/README.gpg 
...

1. Run gpg2john on PGP private key files (supports .skr files too!)

Ensure that the input file to gpg2john contains a single private key.
...
```

The error handling does need to improve in case of non-existent or unreadable input files.

I wonder if our upstream project, https://github.com/kazu-yamamoto/pgpdump, has the same limitations.

**Comment by solardiz** [comment]
Glad to know some of this is documented, but I think the error handling needs to improve for the case of unsupported input file formats as well - such as having more than just the private key in there or more than one - although ideally we'd also support those situations.

**Comment by kholia** [comment]
> I wonder if our upstream project, https://github.com/kazu-yamamoto/pgpdump, has the same limitations.

It seems that `pgpdump` has similar limitations. Parsing is limited to one public / private key per file.

[psirt_pgp_key_(0x33e9e596).txt](https://github.com/magnumripper/JohnTheRipper/files/1333190/psirt_pgp_key_.0x33e9e596.txt) <- GPG key pair for testing purposes.

**Comment by kholia** [comment]
Current behavior,

```
$ echo "x" > x
$ ../run/gpg2john x
can't find PGP armor boundary.
$ echo $?
1

$ echo "" > x
$ ../run/gpg2john x
can't find PGP armor boundary.
$ echo $?
1

$ ../run/gpg2john non-existent-file
$ echo $?
0
```

Only  the third case (out of these three scenarios) seems to be problematic.

**Comment by kholia** [comment]
Fixing the problematic test case should be easy,

``` diff
diff --git a/src/gpg2john.c b/src/gpg2john.c
index 4bdd146..3debd1e 100644
--- a/src/gpg2john.c
+++ b/src/gpg2john.c
@@ -357,7 +357,10 @@ int gpg2john(int argc, char **argv)
                char *hash;
                filename = argv[i];
                fp = fopen(filename, "rb");
-               if (!fp) continue;
+               if (!fp) {
+                       fprintf(stderr, "Unable to process %s, aborting execution.\n", filename);
+                       exit(EXIT_FAILURE);
+               }
                jtr_fseek64(fp, 0, SEEK_END);
                m_flen = (size_t)jtr_ftell64(fp);
                fclose(fp);
```

**Comment by kholia** [comment]
After applying PR #2795,

```
$ ../run/gpg2john psirt_pgp_key_\(0x33e9e596\).txt 
Error: No hash was generated for psirt_pgp_key_(0x33e9e596).txt, ensure that the input file contains a single private key only.

$ echo $?
1
```

**Comment by kholia** [comment]
For handling multiple keys per file, a feature request should be opened against https://github.com/kazu-yamamoto/pgpdump. I can backport the feature once it is available upstream.

**Comment by kholia** [comment]
PR https://github.com/magnumripper/JohnTheRipper/pull/2795 should fix this issue. Hence, I am closing this.
