### ISSUE TITLE
zip2john 1.8.0 jumbo output hash not recognised

### ISSUE THREAD

**Issue by MJonkers** [magnumripper/JohnTheRipper#2797]
The hash that's produced is not recognised: 
No password hashes loaded (see FAQ)

`$pkzip2$1*1*3*2*5b05*c200*99a59dd3*0*2c*8*1d*99a5*6af7*this.zip*$/pkzip2$`

John info:
Version: 1.8.0.6-jumbo-1-bleeding
Build: linux-x86-64-avx
Time stamp: Tue Jun 16 19:36:04 2015
Arch: 64-bit LE
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
$JOHN is /usr/share/john/
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
File locking: fcntl()
Compiler version: 5.3.1 20160224
gcc version: 5.3.1
GNU libc version: 2.21 (loaded: 2.24)
OpenSSL library version: 01000207f	(loaded: 0100020cf)
OpenSSL 1.0.2g  1 Mar 2016	(loaded: OpenSSL 1.0.2l  25 May 2017)
GMP library version: 6.1.0	(loaded: 6.1.2)
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): JtR internal

### IMPORTANT
- If you have questions, please ask them first in the mailing list john-users at lists.openwall.com;
- Use issues to keep track of ideas, enhancements, tasks, and bugs. NEVER as a support forum;
- Please, DO NOT create a new issue if your bug is already known:
  - OpenCL known issues #2331.
  - CUDA support is dropped from tree now. Do not post issues about that.

### Steps to reproduce
Try to be clear about your environment and what you are doing. If possible, share with us the file or hash you are auditing.

### System configuration
Attach details about your OS and about JtR, including:
- are you using bleeding-jumbo? Updated?
- `$ john --list=build-info`.
- `$ john --list=opencl-devices` (if applicable).

**Comment by magnumripper** [comment]
You can't report a bug in a two year old Jumbo here. Try with latest and open an issue if you've still got problems.
