### ISSUE TITLE
Add support for SHA-512 in GPG OpenCL format

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2801]
This is very similar to issue #2788.

Currently, our `opencl_sha2_ctx.h` file doesn't have code for doing SHA-512 hashing operations.

@magnumripper It would be great if you could add SHA-512 CTX OpenCL support. I am not confident about writing "low level" cryptographic primitives.

**Comment by magnumripper** [comment]
Will do soon!

**Comment by magnumripper** [comment]
@kholia done now.
