### ISSUE TITLE
Add check for UTF-16 BOM

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2802]
Provided we don't add a performance hit, we should detect UTF-16 BOM and bail out with an informative message.

https://github.com/magnumripper/JohnTheRipper/commit/91bd304258c4edfda84fc89c77d1e586e7bb6e59#commitcomment-24667963

**Comment by magnumripper** [comment]
And I do mean bail out. If given UTF-16 or UCS-2 input, it's, likely going dowhill very fast so user should get to reconsider.

**Comment by tgp1994** [comment]
Powershell users, [be warned](https://stackoverflow.com/questions/40098771/changing-powershells-default-output-encoding-to-utf-8).

**Comment by magnumripper** [comment]
Right! And emphasize from that quote: **"which isn't useful"** 😆  What the heck are Microsoft thinking? Oh, I know: "all systems in the world run our cuckoo system so let's get crazy and break any standard known to man. Yet again."

**Comment by magnumripper** [comment]
That's a good link BTW, with some solutions. And still caveats: *PowerShell, as of v5.1, invariably creates UTF-8 files with a (pseudo) BOM, which is customary only in the Windows world*.

I'm not sure there's anything I hate more than Windows. Sorry, I AM sure there isn't. The kernel is not bad at all but the userland is the worst crap that ever left the states, possibly except for the bombs.

**Comment by tgp1994** [comment]
Heh... That's sad too, because Powershell was supposed to be the ultimate replacement for Command Prompt. Yet here it is using some weird kind of encoding.

**Comment by magnumripper** [comment]
See #2812 for later events
