### ISSUE TITLE
INSTALL-UBUNTU should explicitly state it's about user-local build

### ISSUE THREAD

**Issue by libBletchley** [magnumripper/JohnTheRipper#2820]
I get `john.log: Permission denied` when running as a user.  This is the basic test session:
```
$ gpg -c -o /tmp/foo.txt.gpg <(printf '%s\n' foo)
$ /usr/local/src/john/run/gpg2john /tmp/foo.txt.gpg > /tmp/foo.txt.gpg.jtrhash

File /tmp/foo.txt.gpg
$ /usr/local/src/john/run/john /tmp/foo.txt.gpg.jtrhash
Using default input encoding: UTF-8
open: /usr/local/src/john/run/john.log: Permission denied
```
There is no mention of this log file in the man page or in `/usr/share/doc/john/CONFIG`.  It appears the executable is making bad assumptions, like that it has write access in the directory where the executable sits.  IMO it would be bad security for users to have write permission there.

As an experiment, I added `/usr/local/src/john/run` to the user's `$PATH` and ran `john` without a directory prefix.  It still fails, but for a different reason:
```
$ cd /tmp
$ john foo.txt.gpg.jtrhash
fopen: $JOHN/john.ini: No such file or directory
```

This is a new installation where root took these actions to install on a Debian Stretch system (following the `doc/INSTALL-UBUNTU` instructions):
```
  $ aptitude install libssl-dev yasm libpcap-dev libbz2-dev; #note already installed packages are omitted
  $ cd /usr/local/src
  $ git clone git://github.com/magnumripper/JohnTheRipper -b bleeding-jumbo john
  $ cd john/src
  $ ./configure && make -s clean && make -sj4
```
Installation was error-free AFAIK, and the `$ ../run/john --test=0` test passed.

### System configuration
Attach details about your OS and about JtR, including:
- are you using bleeding-jumbo? Updated?

I believe so.. used the `-b bleeding-jumbo` option.

- `$ john --list=build-info`.
```
$ john --list=build-info
Created directory: /root/.john
Unknown option: "--list=build-info"
```
- `$ john --list=opencl-devices` (if applicable).
```
john --list=opencl-devices
Unknown option: "--list=opencl-devices"
```

**Comment by magnumripper** [comment]
This is not a support forum. Try the john-users mailing list.

**Comment by magnumripper** [comment]
I'll give you a hint though: try `which john` and go figure.

**Comment by libBletchley** [comment]
`which john` gives `/usr/local/src/john/run/john`, which (as expected) this is what was built.  It's unclear how that explains the `fopen: $JOHN/john.ini: No such file or directory` error.

> This is not a support forum. Try the john-users mailing list.

I'm baffled that you aren't seeing the bugs.  I've counted 7 bugs so far in the above scenario.  Bug reports are created when software does not work _as documented_.  If you believe the software is working correctly, then the documentation is defective.  Even if you are ignoring the documentation factor, at least one of the bugs is most certainly a software bug.  Here's an enumeration of what I've encountered so far:

**(bug 1)** Running <absolute path>/`gpg2john` without having the path in the `$PATH` variable is an allowable way to execute something on linux, yet it causes `gpg2john` to attempt to write to a directory it does not have write permission on.  No such limitation is documented for `gpg2john`.  In fact, the first question in `/usr/share/doc/john/FAQ` states that it _is_ supported to prefix a path to the executable.  Apparently absence of the `$JOHN` variable leads to the software making an undocumented guess at what `$JOHN` should be set to.  Even if it were documented, this fails the _test of least astonishment_.  That is, experienced users would find it astonishing that a tool expects to have write access to the location where to tool itself is stored.
**(bug 2)** There is no man page for `gpg2john` (and i do stress that this is a _bug_ not an enhancement under the paradigm that software do what it's documented to do and that documentation states what the software does)
**(bug 3)** When executed using the `$PATH` (thus without a path prefix), `john` fails to find a file because it expects a shell variable `$JOHN` to be populated, yet there is no mention of that precondition in the `man john` pages.  Since this is documented in the `README`, I'll call this an _enhancement_, but it should appear in the man page as well in a section titled `ENVIRONMENT`.
**(bug 4 [w/3 sub-bugs])* The basename of the file sought in item 3 (above) is `john.ini`.  It's not only bizarre that this file would be expected on a UNIX-like system, it's also documented in `/usr/share/doc/john/CONFIG` that the filename is `john.conf`.  In fact, it's doubly documented as such, because the USAGE section of `man john` states `(configurable in the configuration file, ~/.john/john.ini or ~/.john/john.conf )`, with the latter being the convention on linux.  The FILES section of `man john` contradicts all, and states that the config file is expected to be `/etc/john/john.conf`.  So there's a clear discrepancy between the documentation and the software.  In this case, defects are actually in both the software and the documentation.  Software bug 4.1: convention favors `.conf` on UNIX-like systems, while the tool looks for `john.ini`.  Software bug 4.2: the tool is expecting to find a config file in `$JOHN`, but the docs point to two different places.  Doc bug 4.3: it's documented inconsistently.  Perhaps the intent of the tool is to look at both `~/.john/john.conf` and `/etc/john/john.conf`, in which case both should be in the FILES section of `man john`.
(bug 5) Use of `$JOHN` appears in `/etc/john/john.conf`.  The `CONFIG` doc does not state that environment variables may be used in the configuration file.  Is `$JOHN` interpreted as a special undocumented instance of one environment variable that is exceptionally permitted in the config file, or are all $-prefixed environment variables interpreted in that file?  Users of UNIX-like systems have no natural expectation that they may reference an environmental variable in the config file of a tool, so when it is the case it should be documented as such.

**Comment by kholia** [comment]
> Running <absolute path>/gpg2john without having the path in the $PATH variable is an allowable way to execute something on Linux, yet it causes gpg2john to attempt to write to a directory it does not have write permission on.

In your report, I don't see where `gpg2john` is trying to write to a directory it does not have write permissions on. Can you please point out the spot to me?

Also, lot of your other comments somehow sound off to me.

**Comment by libBletchley** [comment]
> In your report, I don't see where gpg2john is trying to write to a directory it does not have write permissions on. Can you please point out the spot to me?

Sorry, it was `john` that has that problem.  I'll correct that in the post.

**Comment by frank-dittrich** [comment]
Where does doc/INSTALL-UBUNTU mention you are supposed to run commands as root?

If you want a system-wide installation, you might want to check `./configure --help` and then try the option `--with-systemwide`.

BTW, I agree with @magnumripper .
Your questions would have been more appropriate in the john-users mailing list.

**Comment by libBletchley** [comment]
> Where does doc/INSTALL-UBUNTU mention you are supposed to run commands as root?

There are a number of `sudo`s that do not specify a user, which by default execute as root.  Of course I deviated and ran `git clone` as root in `/usr/local/src` because that's a linux convention for a systemwide installs.

> If you want a system-wide installation, you might want to check ./configure --help and then try the option --with-systemwide.

Ah, thanks.  Having a user unpack a release in `$HOME` with intent to execute a systemwide install isn't a standard practice.  Indeed I needed to be told that.  This inspires an enhancement to amend to the bug list:

**(bug 9)** Unconventional systemwide install procedure is under-documented.  Because conventions are deviated from, it's important that doc/INSTALL-UBUNTU hilight the `--with-systemwide` parameter, and the fact that a normal user takes this action.  The status quo is effectively a _gotcha_ for admins who don't run the (undocumented) `./configure --help` command.

**Comment by kholia** [comment]
@libBletchley It would be great if you could also post patches (PRs) to address the various bugs / enhancements you point out. Doing so shouldn't be too hard (for many cases), and from your posts it seems that you really care about these issues.

**Comment by libBletchley** [comment]
@kholia Indeed I was considering that.  They're probably good entry-level bugs.  I'll of course have to reach a point where things are working so the contributions I make are verified to some extent.

I just repeated the installation process using the systemwide variation as a user (suggested by @frank-dittrich) and although I noticed no errors, the test doesn't work.  This time running `tools/src/john/run/john --test=0` from `/home/alice` doesn't work -- it causes `fopen: $JOHN/john.ini: No such file or directory` (with `$JOHN` now being derived as `/usr/share/john/`).  Note that I still deviated from the procedure by rooting JTR in `$HOME/tools/src` instead of `$HOME/src`, which I would have hoped is innocent enough.  I was astonished that `./configure --with-systemwide` did not prompt for an admin password, and that (apparently) all users on the system must have access to `/home/alice/tools/src/run` (Alice's personal space) in order to use JTR.  Maybe I'm missing something, but I don't think there was even an attempt to write to `/usr/local` or `/opt`.

BTW the missing `john.ini` is just a bad error message.  I can see from using `strace -e open` that `john` is looking first for a non-existent `$JOHN/john.conf`, and only prints the last place it looks.

**Comment by claudioandre** [comment]
>>  are you using bleeding-jumbo? Updated?

> I believe so.. used the -b bleeding-jumbo option.

In the bug report, you were NOT using bleeding-jumbo. You have an ancient *John the Ripper* installed in your system.

> (bug 7) The github bug report template directs users to run john --list=build-info and john --list=opencl-devices, which were unknown commandline options when I ran them initially. It worked for me now when I just repeated it, and it's unclear why. Perhaps it can be reproduced by someone following INSTALL-UBUNTU as I did, and not going further to hack things to make it work.

Ops, it is not bleeding. But, you are right I'll change the template and add the **../run** to john [...] command line.

**Comment by claudioandre** [comment]
You were fooled by the system installed package. So:

> Your questions would have been more appropriate in the john-users mailing list.

From "JtR man page" (notice the DOES NOT):

    This manual page documents briefly the john command. This manual page was written for the 
    Debian GNU/Linux distribution because the original program does not have a manual page.

****
There are a reason:
- to use `--system-wide` or to need write permissions to john/run/john.log;
- to be unable to find the configuration (john.conf / john.ini) file in the reported scenario;
- even to fallback to an .ini file.

For sure the documentation is not as good as it should, and the `fopen` error message can be confusing, but you are trying to create a system wide build without following all required steps.

**Comment by libBletchley** [comment]
Now that `--list=build-info` works, I can see that I initially installed this version in /usr/local/: `Version: 1.8.0-jumbo-1-5954-gbf9a37bd9` and this version in `$HOME`: `Version: 1.8.0-jumbo-1-5955-g46b200f8c`

I'm surprised `git clone` would give me an ancient version.

**Comment by libBletchley** [comment]
> you are trying to create a system wide build without following all required steps.

@frank-dittrich stressed that I should follow the doc and run everything as a user.  I'm not sure what steps you're saying I missed, but I'm getting the impression that perhaps I was right the first time in running in `/usr/local/src` with admin rights, but that I should also include the `--with-systemwide` option.  I might try that on the 3rd install attempt.

Should I omit `-b bleeding-jumbo` from this:

 $ `git clone git://github.com/magnumripper/JohnTheRipper -b bleeding-jumbo john`

?  Is that what gave me an ancient version?

**Comment by claudioandre** [comment]
>> post patches (PRs) to address the various bugs

> Indeed I was considering that. They're probably good entry-level bugs.

All of us (plus the maintainer) welcome you, of course. And ANYONE else. But, take your time! 
- Besides the improvement on documentation, no other bug are listed.

On the contrary. E.g. (IMO):
> Since the procedure works for a pure and proper Debian system, occurrences of the word "Ubuntu" should be replaced with "Debian".

NEVER. The procedure was tested and works for Ubuntu. It might work unchanged on Debian (untested) and with modifications on Fedora.
- The user must adapt it accordingly.
- Or ask for help. 
- Or install an updated package (snap and flatpak packages are available).

****
That said, this is a invalid bug report.

**Comment by claudioandre** [comment]
>> you are trying to create a system wide build without following all required steps.

> @frank-dittrich stressed that I should follow the doc and run everything as a user.

Have you read README-DISTROS? Have you set JOHN_SYSTEMWIDE_EXEC and JOHN_SYSTEMWIDE_HOME?

> Should I omit -b bleeding-jumbo from this:

It depends. Never, if you want to build bleeding. And you do. 

> Is that what gave me an ancient version?

Yes, you might have cloned john proper.
****

Now notice that we are not being intransigent. These are welcomed questions for a support forum, but not on a bug tracker.

**Comment by solardiz** [comment]
Here are some assorted thoughts:

- Originally, JtR was not meant to be "installed" at all. You'd build and run it in a subdirectory under your user account's home directory. That's how I still use it almost all of the time, and what I recommend that others do. That's why the paths relative to `john` binary and assumption that this specific directory is writable by the same user, except in system-wide builds:

- Some years ago, I added system-wide installation support for packaging JtR by distros. I never intended this to be used other than by distros. I continue to recommend against use of this functionality other than by distros.

- Given the statements above, I recommend to OP to reconsider trying to do a system-wide install, and instead build and use JtR in a subdirectory in the user's home directory, like people normally do.

- Maybe we need to revise the documentation to make all of the above clearer. The approach we use with non-installation being primary, and system-wide installation being secondary and distros-only, is relatively uncommon.

- Maybe we need to revise the approach to make system-wide installation option a first-class citizen, although personally I'm going to continue to recommend non-installation anyway.

- Perhaps we need to be friendlier when responding to GitHub issues, even in cases when we feel the john-users mailing list should have been used instead. The person might genuinely think that they're reporting bug(s), and they might be right.

**Comment by solardiz** [comment]
> Of course I deviated and ran git clone as root in /usr/local/src because that's a linux convention for a systemwide install

I think we should explicitly state in `INSTALL-UBUNTU` that it's actually about a user-local build, not about a system-wide install, and that the commands not explicitly prefixed by `sudo` must be run as the user (that will use JtR) rather than as root.

I can see how coming from a distro that previously had JtR installed system-wide and reading that file can be confusing. We need to correct that one bug.

**Comment by solardiz** [comment]
> I was astonished that ./configure --with-systemwide

Unfortunately, right now doing a proper system-wide install of JtR is complex - we do not support a `make install`, and distros' packages effectively implement their own equivalent of it. Perhaps we should add a `make install` for simpler use by distros.

No wonder that an end-user trying to do a system-wide install would be confused or even astonished. We should more actively discourage that, unless/until it's eventually intended for more than distros.

**Comment by solardiz** [comment]
The `/etc/john` paths are a Debian package hack. I dislike this, but apparently they "have to" do it per Debian policy. The man page is also a Debian addition. I can see how this can be confusing, but there's little we can do about it, short of perhaps adopting the same directory path as an upstream default for system-wide installs. Right now, our system-wide installs use `/usr/share/john` as directory for all data files, including the default config file. Since sysmem-wide installs are only intended for use by distros anyway, I think it's not a big deal that some distros override this and some don't - it's up to them - although I like distros that don't unnecessarily override upstream defaults better.

The `john.conf` vs. `john.ini` confusion coming up in error messages is probably something we should fix by simply dropping support for the legacy `john.ini` filenames (needed for filesystems like MS-DOS FAT) along with support for builds with DJGPP. I might do that in the core tree soon. Right now, although JtR checks for both filenames, the `.ini` comes up in error messages when none of the files are found as it's what's checked for last (is a last resort fallback).

**Comment by claudioandre** [comment]
```
diff --git a/doc/INSTALL-UBUNTU b/doc/INSTALL-UBUNTU
index 5ce9fc178..b236d729f 100644
--- a/doc/INSTALL-UBUNTU
+++ b/doc/INSTALL-UBUNTU
@@ -1,4 +1,18 @@
+Please, read INSTALL for general information about installing John on your system.
+
+== Preamble
+
+    Notice that it's actually about a user-local build, not a system-wide.
+    In fact, most likely you do not need to install John the Ripper
+    system-wide.  Instead, after you compile the source code (see below),
+    you may simply enter the "run" directory and invoke John from there,
+    e.g., ./john --list=build-options.
+
+    Commands not explicitly prefixed by sudo must be run as a regular user
+    (the one that will use JtR) rather than as root.
+
 == How to install on Ubuntu (also works on Ubuntu for Windows)
+
     The steps listed below might work unchanged on Debian and derivatives (untested).
 
 === Install pre-requisites
```

**Comment by claudioandre** [comment]
> Perhaps we need to be friendlier when responding to GitHub issues, even in cases when we feel the john-users mailing list should have been used instead. The person might genuinely think that they're reporting bug(s), and they might be right.

Ok, but the maintainer does not want to deal with this kind of messages in a queue that requires his attention. And he is right:
*If anyone have questions, they should ask them first in the mailing list (the right place to so).

**Comment by libBletchley** [comment]
**ubuntu docs**
@claudioandre regarding this:
> Notice that it's actually about a user-local build, not a system-wide.
I think many readers will interpret "user-local" to mean "/usr/local".  I would transpose the words and remove the hyphen.  When you say "it's actually about", that's quite indirect.  So I would say something like "This is the process to perform a localized install in $HOME.  Systemwide installs are experimental, undocumented, and unsupported."

I also think users who are eager to make progress but lazy about reading will skip past the block of English.  Speed readers will see that it starts with "Notice" and think it's likely followed by some kind of exception case and skip it.  It might have more effect to concisely say:

=== Preconditions
 * You are installing to $HOME for a single (non-root) user.  (Systemwide installs are experimental, undocumented, and unsupported)
 * The `git` tool is installed
 * $HOME/src exists

> Since you have john man page installed, you have an ancient package installed in your system. Are you sure $PATH was not selecting it?

You must be mistaken.  I last ran JtR about 10 years ago, without issue in fact, but I've reinstalled Debian several times since then, and most recently I installed Stretch from scratch.  There is no chance of a preexisting `john`, and certainly no `john` is found in my `$PATH`.  Since I used `-b bleeding-jumbo` and the two installations I did a day apart are a micro build number apart, I believe I have the bleeding-edge latest.  A man page was installed, but as you know I installed initially as root in `/usr/local`.

> Have you read README-DISTROS? Have you set JOHN_SYSTEMWIDE_EXEC and JOHN_SYSTEMWIDE_HOME?

No, even if I'd known about that readme I would have figured it's not relevant to me since I'm not building a distro, and didn't know of the coupling between that an doing a systemwide install.

**debian support**
>> Since the procedure works for a pure and proper Debian system, occurrences of the word "Ubuntu" should be replaced with "Debian".
> NEVER. The procedure was tested and works for Ubuntu. It might work unchanged on Debian (untested) and with modifications on Fedora.
I didn't realize it was tested on Ubuntu, but this doesn't diminish the proposal -- it just increases the effort to be more than a mere string replacement.

A project has status and recognition when it makes it into an official Debian repository, which should be a long-term goal.  Projects that work on proper Debian are deemed trustworthy and capture a wide audience largely on the pure Debian platform but also automatically on all Debian derivatives (Ubuntu).  The trustworthiness is conveyed in part by the fact that a Debian developer must sign the work using a key that has been signed by others.

I know I'm getting ahead of myself there, and I don't want to come off as being pushy, but there's clear JtR-promoting rationale for at least going in the direction of Debian support.

**historic non-systemwideness**
@solardiz I appreciate the detailed history you've given.  I'll forget about a systemwide install for now, it's not that important.

**Comment by solardiz** [comment]
Thank you for the diff, Claudio! It mostly looks good to me. I think interpreting user-local as referring to `/usr/local` is a stretch, but we may consider that anyway and revise the wording very slightly - e.g., replacing "user-local" with "local to a user's home directory". And we may replace "Notice" with "Important". I think the rest of your suggested wording can stay as-is.

I dislike the specific wording suggested by @libBletchley: no need to refer to $HOME (let's say simply "home directory"); system-wide installs are actually non-experimental and supported - they are just complex and only for use by distros; instead of listing installed `git` as a precondition we may add it to one of the many `apt-get` lines; and we already include a `mkdir` to create the `src` directory.

> the maintainer does not want to deal with this kind of messages in a queue that requires his attention.

Sure, but these messages are typically worded as bug reports, not as questions. We should assume good faith - namely, that the person genuinely thinks they're reporting a bug to help the project. To save time, we may have a boilerplate response message that we'll be reusing, but it should be worded not to be as discouraging as our responses to this issue initially were.

**Comment by magnumripper** [comment]
Sorry for being discouraging (indeed I was) and thank you @libBletchley for not giving up.

**Comment by solardiz** [comment]
I've just dropped checks of `john.ini` from the core tree (except when it's built with DJGPP, in which case, on the contrary, only `john.ini` is looked for). magnum, please get this into jumbo at your convenience. Thanks!

Claudio, I think you're the one to complete and commit the `INSTALL-UBUNTU` edits based on the discussion so far. Thanks!

**Comment by magnumripper** [comment]
> magnum, please get this into jumbo at your convenience

Merged now.

**Comment by libBletchley** [comment]
I think I forgot to mention that INSTALL-UBUNTU says to run this command:
```
./configure && make -s clean && make -sj4
```
but if instead I just run `./configure` in order to micromanage the process, the output from  `./configure`  says:

`Configure finished.  Now 'make clean && make -s' to compile.`

So it's unclear if the two `make` commands can be (or should be) consolidated into `make -s clean`.

**Comment by magnumripper** [comment]
Neither of the options are needed at all, but they are useful and/or makes things faster. Perhaps I should use `-j8` in all examples, as Solar recently suggested elsewhere.

**Comment by claudioandre** [comment]
> may have a boilerplate response message that we'll be reusing

Ok, I'll try to use something like:

```
```
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken, since it seems to be a request for help. 

We assume your are genuinely thinking your are reporting a real bug to help the project.  That said, please:
* read INSTALL and INSTALL-UBUNTU located in the sub-directory named doc;
* confirm you are using the updated bleeding-jumbo source code;
* ensure that you ran a `make clean; ./configure; make -sj8`;
* try to make your point clearer;
* if you are not sure about what you are doing, please ask for help in the mailing list john-users at lists.openwall.com.

****

> not to be as discouraging

The main point is that we are putting effort in a black hole real users do not read. A good example of it is the answer here: https://github.com/magnumripper/JohnTheRipper/issues/2820#issuecomment-338030682

It simply was not bleeding.

**Comment by claudioandre** [comment]
> Perhaps I should use -j8 in all examples, as Solar recently suggested elsewhere.

Ah, you rich people...

JFR: I had to revert some `-sj4` to `-sj2` inside CI because it was too much. BTW: my own computer might trigger its triskaidekaphobia if I follow this advice.

**Comment by solardiz** [comment]
Some edits to the text proposed by Claudio (thanks!)

```
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

- read `INSTALL` and `INSTALL-UBUNTU` located in the sub-directory named `doc`;
- confirm you are using the updated bleeding-jumbo source code (not a numbered release, as this GitHub issue tracker is for issues still present in our latest code, not only in the releases we had made earlier);
- ensure that you ran a `./configure; make clean; make -sj8`;
- try to make your point clearer;
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).
```

Let's save this in a text file and reuse it when appropriate?

**Comment by frank-dittrich** [comment]
I would change
```
./configure; make clean; make -sj8
```
to 
```
./configure && make -s clean && make -sj8
```
(adding `-s` to `make clean` and stop the build if configure detected a problem)

or even 
```
make -s distclean; ./configure && make -s clean && make -sj8
```

**Comment by magnumripper** [comment]
>> Perhaps I should use -j8 in all examples, as Solar recently suggested elsewhere.
>
> Ah, you rich people...
>
> JFR: I had to revert some `-sj4` to `-sj2` inside CI because it was too much. BTW: my own computer might trigger its triskaidekaphobia if I follow this advice.

Oh. So maybe we should again change all `-j8` to `-j4` or even `-j2`?

**Comment by solardiz** [comment]
I edited my comment to use Frank's first suggestion. It's not perfect to recommend `make -s distclean` as well because there might not be a `Makefile` yet at this point, so people would complain that we asked them to run a command that says it can't work.

Regarding `-j8`, I don't mind reverting to `-j4`, but probably we shouldn't go lower than that.

**Comment by claudioandre** [comment]
I saved it on wiki at https://github.com/magnumripper/JohnTheRipper/wiki/Interacting-with-the-user-(WIP). 
* Easier to find than a closed issue;
* IT seems strange to commit to a text file since it is not related to JtR source or documentation.

**Comment by danielsokolowski** [comment]
The error `fopen: $JOHN/john.conf: No such file or directory` is misleading. Here I'm trying to fix it by exporting $JOHN environment variable pointing to the `/usr/local/src/github-magnumripper-JohnTheRipper/run/` built directory and it's not working, but executing john in the `run` folder does.

The original bug submitter had a point. My suggestion is clarify the error message and you will avoid balding hairlines and future bug submissions. 

Ping @claudioandre-br , @magnumripper @kholia

**Comment by magnumripper** [comment]
I can see your point. Please open as a new issue (you can refer to this one from it if you want to)
