### ISSUE TITLE
Support for cracking Kerberos hashes (etype 3/23/17/18)

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2824]
See https://github.com/hashcat/hashcat/issues/1386 for some background.

We already support auditing etype 23 and 18 hashes. See `../doc/Kerberos-Auditing-HOWTO.md` for more information on this.

A related issue is https://github.com/magnumripper/JohnTheRipper/issues/636.

Related note: Microsoft has disabled DES-CBC-CRC and DES-CBC-MD5 for Kerberos encryption from Windows 7 and Windows Server 2008 R2 onwards, by default.

**Comment by kholia** [comment]
@magnumripper The current code in `krb5-18_fmt_plug.c` is not flexible and only handles etype 18. The code for handling etype 17 would be very very similar. Should I add a new file called `krb5-17_fmt_plug.c` to support etype 17 cracking? Doing so would result in lot of duplicate code. Do you have a bright idea here which avoids the addition of a new file? Maybe adding a new `struct fmt_main` structure to the existing file would work?

**Comment by magnumripper** [comment]
Not sure. Perhaps support both in one format? That would involve renaming the format [label] to just krb5 or krb-db or whatever is reasonable (I have too little time to look closer right now).

**Comment by kholia** [comment]
I have PR https://github.com/magnumripper/JohnTheRipper/pull/2826 open for this issue. I implemented support for both `krb5-18` and `krb5-17` in a single file called `krb5_native_fmt_plug.c`. This way seemed less invasive and it maintains backwards compatibility.

**Comment by elitest** [comment]
@kholia please note that while DES is disabled in newer AD versions for encryption, it is still stored in the AD database(including 2k16 based on my testing).  The keys are still there and are dumped by tools like secretsdump(impacket).  Hypothesis is so that keys are already there if AD admins need to turn DES back on without needing to change password(and creating the key).

**Comment by kholia** [comment]
@elitest Thanks for this information. I will try to add support for DES based etypes soon.

**Comment by kholia** [comment]
This is done now.
