### ISSUE TITLE
Unable to crack certain RAR3 archives

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2899]
Sample file -> [secret-windows-1я1.rar.txt](https://github.com/magnumripper/JohnTheRipper/files/1484762/secret-windows-1.1.rar.txt) (remove the fake `.txt` extension)

Original password is `1я1`. This file was generated by WinRAR 5.50 running on Windows XP SP3 (English Edition).

I checked the non-SIMD code path, and didn't find anything weird. The `digest` value after KDF execution is `ff94c37588b0566c32d6b30d4477b46c562bb2f5` which is the same (for first 16 bytes) as the value in `unrar` software.

Another sample file -> [secret-abc.rar.txt](https://github.com/magnumripper/JohnTheRipper/files/1484788/secret-abc.rar.txt) (password is `abc`).

For some reason `p7zip Version 16.02` is unable to extract these files (`p7zip` seems to be broken on Fedora 25). An older version of RAR (RAR 3.50) can successfully extract these files.

**Comment by kholia** [comment]
Some notes,

These files are using CRC32.

The `if (rar_unpack29(cur_file->blob, solid, unpack_t))` call seems to be failing for such files.

It appears that that `rar2john.c` is generating the correct hash (CRC, encrypted data are fine).  Also, the values of the AES key, IV are fine and they match those generated by `unrar 5.5.8`.

**Comment by kholia** [comment]
It seems that this bug is not related to WinRAR 5.50 at all. Older versions of RAR (e.g. `rarlinux-3.5.0.tar.gz`) can generate such files too.

I have a feeling that this is not going to be trivial to debug.

**Comment by kholia** [comment]
Diffing our code against https://github.com/Cisco-Talos/clamav-devel/tree/master/libclamunrar should be a good start. According to Git commit history, some bugs have been fixed in this code base in recent years.

**Comment by magnumripper** [comment]
I updated it from upstream three years ago in 3dcef362a, perhaps it's time to do so again.

**Comment by magnumripper** [comment]
That code is not quite in sync with ours though. It must be some other fork than I originally used so I can't just look at commits since my latest update.

I can do it manually though - @kholia would you happen to know if Cisco-Talos is some kind of official upstream now?

**Comment by magnumripper** [comment]
> It must be some other fork

LOL, now I see what happened. Many differences is from me inserting comments from the **original** (not ClamAV but real unrar C++) sources. While they are good for debugging, they are bad for merging upstream.

**Comment by magnumripper** [comment]
That was a winning move!
```
$ ../run/john -form:rar issue2899.in --internal-codepage=cp1251 -mask:?1?2?1 -1=ac12 -2=?l?L
Using default input encoding: UTF-8
Rules/masks using CP1251
Loaded 2 password hashes with 2 different salts (rar, RAR3 [SHA1 128/128 AVX 4x AES])
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
abc              (secret-abc.rar:1)
1я1              (secret-windows-1.1.rar:1)
2g 0:00:00:05 N/A 0.3898g/s 230.7p/s 392.9c/s 392.9C/s aу1..2µ2
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by kholia** [comment]
> Would you happen to know if Cisco-Talos is some kind of official upstream now?

Not sure. I guess they contribute to ClamAV like other vendors / folks.

...

Nice work @magnumripper :+1:
