### ISSUE TITLE
Encoding test failures on OSX

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2923]
The failures are seen below; they are happening only on OSX.

```
Device 0: Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz
Testing: oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL] in UTF-8 mode... PASS
Testing: rar-opencl, RAR3 (length 4) [SHA1 OpenCL AES] in UTF-8 mode... PASS
Testing: krb5pa-md5-opencl, Kerberos 5 AS-REQ Pre-Auth etype 23 [MD4 HMAC-MD5 RC4 OpenCL] in UTF-8 mode... FAILED (cmp_one(0))
Testing: mscash-opencl, M$ Cache Hash [MD4 OpenCL] in UTF-8 mode... FAILED (cmp_one(0))
Testing: mscash2-opencl, MS Cache Hash 2 (DCC2) [PBKDF2-SHA1 OpenCL] in UTF-8 mode... PASS
Testing: nt-opencl, NT [MD4 OpenCL] in UTF-8 mode... FAILED (cmp_one(0))
Testing: ntlmv2-opencl, NTLMv2 C/R [MD4 HMAC-MD5 OpenCL] in UTF-8 mode... FAILED (cmp_one(0))
Testing: office-opencl, MS Office [SHA1/SHA512 AES OpenCL] in UTF-8 mode... PASS
Testing: 7z-opencl, 7-Zip (512K iterations) [SHA256 AES OPENCL] in UTF-8 mode... PASS
4 out of 9 tests have FAILED
```

Changing the subject, I'm afraid magnum will complain that the new tests increased the build time in more than 25%. More than that, one test is exceeding the maximum time limit for jobs. Only thinking aloud, I'm out of ideas for now.

**Comment by jfoug** [comment]
Is this found on the new Travis encoding tests?   I did ask @magnum prior to making changes.  Are there any tests which are longer (such as the opencl?   Also, we 'could' do just utf-8, or do utf-8 on one, encode on the other. BUT there are some formats which have 3 set_key functions.   Once for ASCII, one for encode, and one for utf8, so the testing really does need to be done 'somewhere'.....

It does appear that the testing has disturbed the force, and shown that we do have some form of problems somewhere that need addressed.

**Comment by magnumripper** [comment]
Yeah the new tests are only ~40 formats (the ones that are encoding-aware) so I figured it wouldn't affect test time much at all. Did it increase with 25%?

**Comment by magnumripper** [comment]
Also, if they only happen on OSX, odds are we're seeing driver/runtime bugs. There's really nothing special with OSX in our code.

**Comment by magnumripper** [comment]
Good news, I can reproduce on my macbook. I'll have a look at these.

**Comment by claudioandre** [comment]
>  Did it increase with 25%?

From 23 to 30 minutes. Well, some refactoring is already needed anyway.

**Comment by magnumripper** [comment]
Did an actual reconfig+rebuild happen between each test?

**Comment by claudioandre** [comment]
> Did an actual reconfig+rebuild happen between each test?

Do you mean between the regular test and the encoding one? No rebuild, the tests were added.

```
     ../run/john -test=0 --format=cpu
 +    ../run/john -test=0 --format=cpu --encoding=utf8
 +    ../run/john -test=0 --format=cpu --encoding=cp737
```

**Comment by jfoug** [comment]
I am wondering if we should reduce the tests. Just do 1 encodign utf8, one cp737.

ALSO, we should not do them on an ASAN build (that really is too slow already), but do not know the scripts well enough to strip out the testing.  Also, the enc test on openCL may push the limit on times also.  But again, I am not really sure of the overall script running.  I just added the extra tests, knowing that they are only 20-30 formats being tested.  I was hoping it would not be a show stopper amount of time, but it may be in some situations.  It certainly is on ASAN builds.

**Comment by magnumripper** [comment]
> I am wondering if we should reduce the tests. Just do 1 encodign utf8, one cp737.

That should do fine. "raw" is one code path, "utf8" is another and any other codepage is a third.

**Comment by magnumripper** [comment]
Or do you mean one single format? That would miss stuff.
