### ISSUE TITLE
Add support for more network hashes

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2933]
##### Old related tasks

* https://github.com/magnumripper/JohnTheRipper/issues/2534

* https://github.com/magnumripper/JohnTheRipper/pull/2589

##### New things

* https://wiki.wireshark.org/SampleCaptures#Sample_Captures (had a look, done)

* Do we support the `radius_localhost.pcapng` file? Just wondering (We do!)

* WLCCP (look at `loki` project, done)

* Port `asleap's` cracking stuff to JtR (done, optimization stuff pending)

* Look at https://github.com/theclam/dechap (seems to be buggy and/or limited)

* http://c0decafe.de/svn/codename_loki/trunk/ (done)

* https://tools.ietf.org/html/rfc2865#page-28 (RADIUS authentication, EAP-MD5 and CHAP done)

* Extract CHAP hashes from iSCSI traffic (extend my work from year 2012, done)

* https://github.com/aircrack-ng/aircrack-ng/tree/master/patches/wpe/freeradius-wpe

Samples,

 * https://c0decafe.de/svn/codename_loki/test/wlccp_example_auth.pcap (done)

* [radius_localhost.pcapng.txt](https://github.com/magnumripper/JohnTheRipper/files/1513247/radius_localhost.pcapng.txt) <- sample capture (remove .txt extension).

* [chap-radius-hello.pcap.txt](https://github.com/magnumripper/JohnTheRipper/files/1520514/chap-radius-hello.pcap.txt)

* [chap-another-radius-hello123.pcap.txt](https://github.com/magnumripper/JohnTheRipper/files/1520515/chap-another-radius-hello123.pcap.txt)

* [eap-md5-radius-hello.pcap.txt](https://github.com/magnumripper/JohnTheRipper/files/1520519/eap-md5-radius-hello.pcap.txt)

**Comment by kholia** [comment]
Current status,

```
$ tshark -q -Xlua_script:eapmd5tojohn.lua -r radius_localhost.pcapng
steve:$chap$103*ff0bf1d6e401a9cbe5b46eb943e5549a*c76e1d28726fd1c0cb671a5424168d26
steve:$chap$113*ba0bf4a7e7177359caa52e7eb10d9d0b*36d93b94f142714e95061613640ed36d
```

Packets 1 to 8 (EAD-MD5) are successfully handled.

**Comment by kholia** [comment]
WLCCP uses LEAP, and such hashes can be cracked with `netntlm` format.

```
$ cat hash
WDSUser:$NETNTLM$900d74be3b382664$24ae720f571ddcfdd74df0fc85f9aaf0a86c594a957b2078
```

```
$ ../run/john hash
Warning: detected hash type "netntlm", but the string is also recognized as "netntlm-naive"
Use the "--format=netntlm-naive" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (netntlm, NTLMv1 C/R [MD4 DES (ESS MD5) 256/256 AVX2 8x3])
Warning: no OpenMP support for this hash type, consider --fork=4
Press 'q' or Ctrl-C to abort, almost any other key for status
123qwe           (WDSUser)

```

**Comment by kholia** [comment]
After PR https://github.com/magnumripper/JohnTheRipper/pull/2943,

```
$ tshark -q -Xlua_script:radius2john.lua -r radius_localhost.pcap
steve:$chap$168*95bbe85b56ad0aa36dd80f9b7c59067d*0574ae2c413a393f07b5564984bda740
```

**Comment by magnumripper** [comment]
Good stuff 👍

**Comment by kholia** [comment]
I am thinking of removing `eapmd5tojohn.c`. It seems that `eapmd5tojohn.lua` works better and does a more through job.

**Comment by kholia** [comment]
This ticket is mostly done now. I will double-check if something more can be added to it.

**Comment by kholia** [comment]
More items,

* DHCP "delayed authentication", RFC 3118 -> I could not find a single sample capture with a known password. I also could not find a working implementation of RFC 3118.

* BIND "rndc authentication" -> Can this be cracked as well? Typically the strength of the secret key is pretty high.

**Comment by kholia** [comment]
DHCP OMAPI hashes,

```
$ cat dhcpd.conf
#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp*/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#

subnet 10.0.0.0 netmask 255.255.255.0 {
        option routers                  10.0.0.254;
        option subnet-mask              255.255.255.0;

        option domain-name              "internal";
        option domain-name-servers       8.8.8.8;

	range 10.0.0.10 10.0.0.100;
}

omapi-port 7911;
omapi-key omapi_key;

key omapi_key {
     algorithm hmac-md5;
     secret "b3BlbndhbGw=";
}


$ omshell
> server localhost
> key omapi_key openwall
> connect
obj: <null>
> new host
obj: host
> set ip-address = 192.168.4.50
> create
can't open object: connection reset by peer
obj: host
ip-address = c0:a8:04:32

$ omshell
> server localhost
> key omapi_key password
> connect
obj: <null>
> new host
obj: host
> set ip-address = 192.168.4.50
obj: host
ip-address = c0:a8:04:32
> create
can't open object: connection reset by peer
obj: host
ip-address = c0:a8:04:32
```

This should generate traffic with the "OMAPI hashes".

**Comment by kholia** [comment]
Simple rndc auth implementation,

https://fossies.org/linux/misc/dns/bind9/9.11.2/bind-9.11.2.tar.gz/bind-9.11.2/bin/python/isc/rndc.py.in

The Wireshark dissector for rndc packets is not that great currently.

**Comment by kholia** [comment]
It would be awesome if someones has information on DHCP "delayed authentication" feature (RFC 3118). I am looking for .pcap files with such traffic and with known password(s).

**Comment by kholia** [comment]
Director Response Protocol (DRP) -> Protocol used by the DistributedDirector feature in IP routing on Cisco devices. This uses port 1974, and supports authentication (`Keyed MD5`).

**Comment by kholia** [comment]
https://www.pentestpartners.com/security-blog/how-to-crack-private-apn-keys-with-hashcat/

Can we already extract PPP CHAP hashes from .pcap files?

**Comment by kholia** [comment]
Quick notes so that I don't forget.

+ Authenticated dynamic DNS updates

+ Other DNS authenticated things

**Comment by kholia** [comment]
Tracing TSIG (DNS),

```
$ gdb --args nsupdate -y update-key:MTIzNDU2Nzg= update.txt 
(gdb) break isc_hmacmd5_init
(gdb) r
Starting program: /usr/local/bin/nsupdate -y update-key:MTIzNDU2Nzg= update.txt
Outgoing update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id:      0
;; flags:; ZONE: 0, PREREQ: 0, UPDATE: 0, ADDITIONAL: 0
;; ZONE SECTION:
;example.com.			IN	SOA

;; UPDATE SECTION:
subdomain.example.com.	60	IN	A	127.0.0.1

Sending update to 192.168.122.142#53
[Switching to Thread 0x7ffff4c67700 (LWP 10722)]

Breakpoint 1, isc_hmacmd5_init (ctx=ctx@entry=0x7ffff7f960a8, key=key@entry=0x7ffff7f98fd0 "12345678", len=len@entry=64) at hmacmd5.c:250
250	{
```

**Comment by kholia** [comment]
https://github.com/rthalley/dnspython would be very helpful in parsing these "TSIG" packets.

Sample code,

``` python
#!/usr/bin/env python3

from __future__ import print_function

import socket

import dns.flags
import dns.message
import dns.rdataclass
import dns.rdatatype
import dns.tsigkeyring


keyring = dns.tsigkeyring.from_text({
    'update-key' : 'MTIzNDU2Nzg='
    })


wire = "4e65a8820001000000000001076578616d706c6503636f6d00000600010a7570646174652d6b65790000fa00ff00000000003a08686d61632d6d6435077369672d616c670372656703696e740000005a38f8c7012c0010867b3d04d7793a538509d8dd96f66bc24e6500000000".decode("hex")

xyz = dns.message.from_wire(wire, keyring=keyring)
print(xyz)
```

The data comes from the above post.

**Comment by kholia** [comment]
I can brute-force and crack client-to-server TSIG traffic now, but I am unable to crack server-to-client TSIG responses. 

Notes on debugging `named`,

```
$ sudo debuginfo-install bind -y

$ sudo gdb -p `pidof named`
(gdb) break isc_hmacmd5_init
Breakpoint 1 at 0x7fcbed1022c0
(gdb) break isc_hmacmd5_update
Breakpoint 2 at 0x7fcbed102510
```

**Comment by kholia** [comment]
Use a command line `nsupdate -y hmac-sha256:update-key:w6RiYw== update.txt` to try the various supported HMAC schemes.

**Comment by kholia** [comment]
This issue can be closed now. Hopefully, we will learn about more network protocols to attack in the near future.

**Comment by kholia** [comment]
https://github.com/kholia/rfc-3118 has stuff related to `delayed authentication` in DHCP.

**Comment by kholia** [comment]
Also see https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=1025 (Bug 1025 - dhcp packet crashes wireshark) for a little more information on `delayed authentication` in DHCP.

**Comment by kholia** [comment]
https://github.com/rsmarples/dhcpcd (DHCP client) has support for `delayed authentication` :-)

I couldn't find a DHCP server implementation with support for `delayed authentication` though.
