### ISSUE TITLE
JSON output with --show=types

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2938]
Add --show=types-json

Orginal line:
```
Administrator:500:11111111111111112222222222222222:33333333333333333333333333333333:::
```

Current show-type output (-form=cpu):
```
Administrator:11111111111111112222222222222222:500:::::LM:0:0:1:$LM$1111111111111111:$LM$2222222222222222::NT:0:0:0:$NT$33333333333333333333333333333333::NT-old:0:0:0:$NT$33333333333333333333333333333333:0:
```

JSON alternative (although we'll print it on a single line and with no spaces except in actual data):
```
{
  "lineNo" : "1",
  "login" : "Administrator",
  "ciphertext" : "11111111111111112222222222222222",
  "uid" : "500",
  "gid" : "",
  "gecos" : "",
  "home" : "",
  "shell" : "",
  "consistencyMark" : "0",
  "rowFormats" : [ {
    "label" : "LM",
    "disabled" : "0",
    "dynamic" : "0",
    "prepareEqCiphertext" : "1",
    "canonHash" : [ "$LM$1111111111111111", "$LM$2222222222222222" ]
  }, {
    "label" : "NT",
    "disabled" : "0",
    "dynamic" : "0",
    "prepareEqCiphertext" : "0",
    "canonHash" : [ "$NT$33333333333333333333333333333333" ]
  }, {
    "label" : "NT-old",
    "disabled" : "0",
    "dynamic" : "0",
    "prepareEqCiphertext" : "0",
    "canonHash" : [ "$NT$33333333333333333333333333333333" ]
  } ],
}
```

**Comment by magnumripper** [comment]
Added in a353bed0

**Comment by jfoug** [comment]
Love it!   Nice!

Any reason you added \n to each line?

**Comment by magnumripper** [comment]
Well the *n*th line in the output matches the *n*th line in the input, which is nice for many reasons.

**Comment by jfoug** [comment]
I understand the human readability, but I really do not see it.  However, the \n is irrelevant, so it really does not matter much.   You can not simply grep/sed a line and have it be valid JSON.  now, you 'could' have done this with each line being a valid JSON input string, but I am not sure how that would impact JSON readers.  I really see no impact of the extraneous \n, just asking.
