### ISSUE TITLE
MinGW build warnings

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2961]
MinGW builds puke dozens of build warnings due to incorrect macro definitions in jumbo.h An example:
```
rar2john.c: In function 'process_file':
rar2john.c:353:12: warning: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'long long unsigned int' [-Wformat=]
            "! HEAD_SIZE: %d, PACK_SIZE: "LLu", UNP_SIZE: "LLu"\n",
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rar2john.c:355:12:
            (unsigned long long)file_header_pack_size,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from rar2john.c:56:0:
jumbo.h:370:18: note: format string is defined here
 #define LLu "%I64u"
              ~~~~^
              %I64llu
```
So we print an unsigned long to LLu, which is correct, but then it translates to %I64u which ends up as %u... not correct. I guess the last line hints about a correct one being %I64llu.

**Comment by jfoug** [comment]
This is a new perversion in mingw.  Mingw used to follow vc. VC only handled %I64type

Now vc handles %lltype (just like unix), but mingw chose to go it on their own, jackasses.   One of the reasons I abandoned mingw years ago, and simply use cygwin.

mingw simply chose to stop supporting the original non-standard way they Were doing things, and built a whole new non-standard way to do it, at the same time changing the original concept of the first non-standard method.  Boneheads :(

I am not supporting this.   I know it was added for build bots, to do an 'automatic' build job.  But someone else is going to have to support this, if this is what is wanted.   I have never been overly happy about using Fedora as  a cross compiler on this type build.

**Comment by magnumripper** [comment]
Then we need a volunteer for maintaining MinGW ASAP. Unless we get that, I will drop all support for it.

**Comment by magnumripper** [comment]
Does MinGW also not support inttypes.h and PRI types?

**Comment by kholia** [comment]
I don't know this currently but will find out. I can maintain the MinGW stuff in JtR Jumbo.

@jfoug Hopefully I can rely on you to test that my MinGW related patches don't break VC ;)

**Comment by jfoug** [comment]
I do not know any more. The entire concept of mingw was to simply use things in the msvccrt.dll I think. That is why they only supported the %I64type stuff.  But that was years ago, and I am not sure where they have gone since then.

**Comment by jfoug** [comment]
I will test with VC yes, but again that really is NOT supported other than being the environment I build/debug on, lol.  As long as I can keep my debugging setup, I will be fine.  All real usage stuff I use, is done with cygwin, and that should not be impacted at all.     Also within the VC env I have, I have abaindoned the %I64type crap, and use %lltype which VC handles just fine.  It baffles me that Mingw changed the meaning of %I64u, and still refuses to deal with the %ll stuff properly.

**Comment by solardiz** [comment]
> I know it was added for build bots, to do an 'automatic' build job. But someone else is going to have to support this, if this is what is wanted.

Maybe we need to revisit my idea of building with Cygwin on ReactOS in a VM on Linux. We do need automated Windows builds that people could actually use, and this means builds made in a way that we support rather than a way that just happens to work but produces binaries of unknown reliability.

**Comment by kholia** [comment]
The MinGW builds are already usable by end-users, and they are generated automatically.

For Cygwin builds, https://www.appveyor.com/ can help, though it won't be running ReactOS internally. I am not a Cygwin user / fan, otherwise I would have given AppVeyor a try.

**Comment by solardiz** [comment]
> The MinGW builds are already usable by end-users, and they are generated automatically.

Dhiru, it's wrong that we simultaneously say we don't care about build warnings (and, more importantly, the known problems in code that the warnings are about) and offer those builds to end-users. Such builds might e.g. misbehave on large files.

**Comment by jfoug** [comment]
@kholia what exactly are your reservations about cygwin?  If you let me know, I  can either help you your, or you can enlighten me on why I should look for a better alternative.   A decade or more ago, I too was a fan of MinGW, and not a fan of cygwin.    But now, with a lot more usage on cygwin and the memories I had of trying to keep mingw running properly my 'fandom' has switched

I look at the cygwin/mingw sort of the differences of usage between using GMP vs Rexgen libraries.  Every time you turn around, the rexgen lib was re-written (re-interfaced) causing existing things to simply not work anymore without work.   I felt this way about MinGW.  Lack of a good installer, support system which was actually one of the hugest things that drove me to cygwin, which has a  pretty smooth upgrade/update interface.

Yes, the one drawback I can see, is the cygwin1.dll   BUT IMHO, this is a moot point, since even now under mingw, we are releasing numerous DLLs    Adding one singular Posix dll to the mix is a non-issue, IMHO, vs MinGW relying on the DLL hell of the 'standard' VC  DLL kernel files.

If there are great reasons to use MinGW, please enlighten me.  Getting the code ports figured out should not be hard at all.  But like Solar says, ```it's wrong that we simultaneously say we don't care about build warnings (and, more importantly, the known problems in code that the warnings are about) and offer those builds to end-users.```       This is why I have never 'tried' to get things buildable under VC.  There simply are too many nuanced problems, which yes I 'could' fix, but which would grow again from that point on, since no one else on the 'core' team cares about a VC project / build, and VC has not help at all for a 'configure' script built project.

**Comment by jfoug** [comment]
if @kholia wants to address the issues (warnings, and subsequent reason FOR the warnings) in MinGW, but has not up until now, due to the concern of problems we what that does to VC, then by all means get MinGW 'really' ported, I will deal with any form of fallout on the back end.  As long as it is not something that requires 4-6 hours or porting, every couple of months, then no problem.  If you can get it 'right' and even if it does take 4-6 hours to get VC to once again rebuild, if it stays in tune, without requiring a frequent re-fix on my end, I have no problems at all.

Some big positives for MinGW, is we already have it there, and I would be VERY surprised, if there were not 100's or even 1000's of people who have already downloaded and used the Windows binary port.  So if nothing else, it 'must' be working.

**Comment by jfoug** [comment]
@kholia, long ago (I think), I abandoned the %I64[ud] stuff on my VC builds.  I am pretty sure I use %ll[ud] as that is what VC can do, and what unix does.  If that is not the case, I can easily change jumbo.h (or wherever we have hidden that), so that my VC builds are not impacted by whatever is needed on MinGW for the printf stuff.

**Comment by kholia** [comment]
@solardiz I care about these build warnings. I believe that I have even reported such warnings previously. I just didn't know how to fix them.

I will now learn the stuff involved, and try to fix these warnings soon.

**Comment by kholia** [comment]
@jfoug Regarding Cygwin, I couldn't find something like a Cygwin cross-compiler. I wanted something which runs on Linux (my primary OS), and could generate Cygwin compatible Windows binaries.

**Comment by kholia** [comment]
Here are some easy wins,

```
diff --git a/src/keepass2john.c b/src/keepass2john.c
index a9ab305..dd5518d 100644
--- a/src/keepass2john.c
+++ b/src/keepass2john.c
@@ -257,7 +257,7 @@ static void process_old_database(FILE *fp, char* encryptedDatabase)
 
        /* we inline the content with the hash */
        fprintf(stderr, "Inlining %s\n", encryptedDatabase);
-       printf("*1*"LLd"*", datasize);
+       printf("*1*%"PRIu64"*", datasize);
        fseek(fp, 124, SEEK_SET);
        if (fread(buffer, datasize, 1, fp) != 1) {
                warn("%s: Error: read failed: %s.",
diff --git a/src/mkvcalcproba.c b/src/mkvcalcproba.c
index 3ff902b..8fac5ba 100644
--- a/src/mkvcalcproba.c
+++ b/src/mkvcalcproba.c
@@ -49,7 +49,7 @@ int main(int argc, char **argv)
        unsigned int j;
        unsigned int k;
        unsigned int l;
-       unsigned long long index;
+       uint64_t index;
        unsigned char position[256];
        unsigned int charset;
        unsigned int nb_lignes;
@@ -183,7 +183,7 @@ int main(int argc, char **argv)
                        i++;
                }
                if (index < 8E18)
-                       printf("\t%d\t%d\t" LLd "\t%d\n", k, i, index, l);
+                       printf("\t%d\t%d\t%" PRIu64 "\t%d\n", k, i, index, l);
                else
                        printf("\t%d\t%d\t-\t%d\n", k, i, l);
        }
```

These patches eliminate the following warnings,

```
mkvcalcproba.c: In function 'main':
mkvcalcproba.c:186:11: warning: format '%d' expects argument of type 'int', but argument 4 has type 'long long unsigned int' [-Wformat=]
    printf("\t%d\t%d\t" LLd "\t%d\n", k, i, index, l);
           ^~~~~~~~~~~~
keepass2john.c: In function 'process_old_database':
keepass2john.c:260:9: warning: format '%d' expects argument of type 'int', but argument 2 has type 'long long int' [-Wformat=]
  printf("*1*"LLd"*", datasize)
```

Some MinGW testing,

```
$ cat MinGW-1.c 
// x86_64-w64-mingw32-gcc -Wall MinGW-1.c
// i686-w64-mingw32-gcc -Wall MinGW-1.c

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

int main()
{
	uint64_t i = -1;

	printf("i = %" PRIu64 "\n", i); // works with MinGW GCC just fine!

	printf("i = %llu\n", i); // requires -D__USE_MINGW_ANSI_STDIO

	return 0;
}
```

We already have `__USE_MINGW_ANSI_STDIO` set in JtR Jumbo. This allows usage of things `%llu` with MinGW.

```
$ rpm -qa | grep -E '(mingw.*gcc)'
mingw64-gcc-c++-6.4.0-1.fc25.x86_64
mingw32-gcc-c++-6.4.0-1.fc25.x86_64
mingw64-gcc-6.4.0-1.fc25.x86_64
mingw32-gcc-6.4.0-1.fc25.x86_64
```

**Comment by kholia** [comment]
> Does MinGW also not support inttypes.h and PRI types?

@magnumripper It seems that MinGW does support `inttypes.h` and PRI types!

**Comment by kholia** [comment]
Fixed so far,

* keepass2john.c

* mkvcalcproba.c

* genmkvpwd.c

* gpg2john.c

* unique.c

* wordlist.c

* mask.c

* rar2john.c

* rar_common.c

* mkv.c 

I vaguely recall seeing similar warnings in pkzip format and zip2john.c too. I will try to reproduce those warnings as well. Let me know if you know how to do so ;)

@jfoug Does VC support things like `PRIu64` and `PRId64`?

**Comment by magnumripper** [comment]
> @magnumripper It seems that MinGW does support inttypes.h and PRI types!

Great, then the fixes are just towards real stuff and not cuckoo's nest Windows stuff! We should deprecate our LLu stuff and get rid of them in the long run.

**Comment by magnumripper** [comment]
> @jfoug Does VC support things like PRIu64 and PRId64?

I believe we have workarounds for PRI[uxd]64 in jumbo.h, others can be added if needed.

**Comment by kholia** [comment]
One of the serious problems with MinGW is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54412 (Request for 32-byte stack alignment with -mavx on Windows).

**Comment by jfoug** [comment]
> We should deprecate our LLu stuff and get rid of them in the long run.

Agreed!  The LLu defines were there to pacify MinGw/VC, but if there are better 'correct' ways, then lets dump them like cold dirty bath water!

> One of the serious problems with MinGW

I think that will only bite us on the *_ng formats, where people are writing roll it your own SIMD code.  I do not think this is an issue on any normal format, where we allocate all buffers used with SIMD registers using alignment allocation.  If this ends up a problem we can 1, define out mingw to not use the offending format, or 2 fix the format to knowingly and properly align.     But the good things is this should fail the CI testing IF there are problems and be easily seen.

**Comment by kholia** [comment]
The 64-bit MinGW AVX2 builds don't crash under Wine for some reason but they crash hard when run on real Windows. That is why I have started creating, and publishing 32-bit MinGW builds (with binary fallback chain) instead ;(

Even the `core` formats fail. See https://github.com/magnumripper/JohnTheRipper/issues/2543 for details.

**Comment by kholia** [comment]
This particular issue should be solved now with PR https://github.com/magnumripper/JohnTheRipper/pull/2964.

**Comment by claudioandre** [comment]
Why are you guys not seeing this warnings?

```
pp.c: In function 'save_state':
pp.c:859:17: warning: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'long long unsigned int' [-Wformat=]
   fprintf(file, ""LLu"\n", (unsigned long long)mpz_get_ui(half));
                 ^~         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from os-autoconf.h:29:0,
                 from os.h:20,
                 from win32_memmap.h:1,
                 from pp.c:71:
jumbo.h:373:18: note: format string is defined here
 #define LLu "%I64u"
              ~~~~^
              %I64llu
pp.c:862:17: warning: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'long long unsigned int' [-Wformat=]
   fprintf(file, ""LLu"\n", (unsigned long long)mpz_get_ui(half));
                 ^~         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from os-autoconf.h:29:0,
                 from os.h:20,
                 from win32_memmap.h:1,
                 from pp.c:71:
jumbo.h:373:18: note: format string is defined here
 #define LLu "%I64u"
              ~~~~^
              %I64llu
pp.c: In function 'restore_state':
pp.c:870:20: warning: format '%u' expects argument of type 'unsigned int *', but argument 3 has type 'long long unsigned int *' [-Wformat=]
   if (fscanf(file, ""LLu"\n", &temp) != 1)
                    ^~         ~~~~~
In file included from os-autoconf.h:29:0,
                 from os.h:20,
                 from win32_memmap.h:1,
                 from pp.c:71:
jumbo.h:373:18: note: format string is defined here
 #define LLu "%I64u"
              ~~~~^
              %I64llu
pp.c:874:20: warning: format '%u' expects argument of type 'unsigned int *', but argument 3 has type 'long long unsigned int *' [-Wformat=]
   if (fscanf(file, ""LLu"\n", &temp) != 1)
                    ^~         ~~~~~
In file included from os-autoconf.h:29:0,
                 from os.h:20,
                 from win32_memmap.h:1,
                 from pp.c:71:
jumbo.h:373:18: note: format string is defined here
 #define LLu "%I64u"
              ~~~~^
              %I64llu
In file included from pp.c:74:0:
```

**Comment by kholia** [comment]
I missed these warnings because I don't have the GMP package for MinGW installed? I will try to reproduce, and fix these warnings. Thanks!

**Comment by kholia** [comment]
Here is a patch which fixes these warnings,

```
$ git diff
diff --git a/src/pp.c b/src/pp.c
index 061c146be..3d6d34f39 100644
--- a/src/pp.c
+++ b/src/pp.c
@@ -856,22 +856,22 @@ static void save_state(FILE *file)
   mpz_t half; mpz_init(half);
 
   mpz_fdiv_r_2exp(half, rec_pos, 64); // lower 64 bits
-  fprintf(file, ""LLu"\n", (unsigned long long)mpz_get_ui(half));
+  fprintf(file, "%"PRIu64"\n", (uint64_t)mpz_get_ui(half));
 
   mpz_fdiv_q_2exp(half, rec_pos, 64); // upper 64 bits
-  fprintf(file, ""LLu"\n", (unsigned long long)mpz_get_ui(half));
+  fprintf(file, "%"PRIu64"\n", (uint64_t)mpz_get_ui(half));
 }
 
 static int restore_state(FILE *file)
 {
-  unsigned long long temp;
+  uint64_t temp;
   mpz_t hi;
 
-  if (fscanf(file, ""LLu"\n", &temp) != 1)
+  if (fscanf(file, "%"PRIu64"\n", &temp) != 1)
     return 1;
   mpz_set_ui(rec_pos, temp);
 
-  if (fscanf(file, ""LLu"\n", &temp) != 1)
+  if (fscanf(file, "%"PRIu64"\n", &temp) != 1)
     return 1;
   mpz_init_set_ui(hi, temp);
   mpz_mul_2exp(hi, hi, 64); // hi = temp << 64
```

**Comment by kholia** [comment]
Quick note,

Currently, `vncpcap2john.c` and other libpcap dependent bits are not getting built in MinGW builds.

``` bash
$ rpm -ql mingw32-wpcap
/usr/i686-w64-mingw32/sys-root/mingw/bin/packet.dll
/usr/i686-w64-mingw32/sys-root/mingw/bin/wpcap.dll
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/Gnuc.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/IP6_misc.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/Packet32.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/Win32-Extensions.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/bittypes.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap-bpf.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap-int.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap-namedb.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap-stdinc.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap/bluetooth.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap/bpf.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap/namedb.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap/pcap.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap/sll.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap/usb.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/pcap/vlan.h
/usr/i686-w64-mingw32/sys-root/mingw/include/wpcap/remote-ext.h
/usr/i686-w64-mingw32/sys-root/mingw/lib/libpacket.dll.a
/usr/i686-w64-mingw32/sys-root/mingw/lib/libwpcap.dll.a
/usr/i686-w64-mingw32/sys-root/mingw/lib/packet.def
/usr/i686-w64-mingw32/sys-root/mingw/lib/pkgconfig/wpcap.pc
/usr/i686-w64-mingw32/sys-root/mingw/lib/wpcap.def
/usr/share/doc/mingw32-wpcap
/usr/share/doc/mingw32-wpcap/LICENSE
```

Instead of checking/including `pcap/pcap.h`, I guess we need to check for `wpcap/pcap.h`. However, I don't think that doing so is worth the trouble. 

Hopefully, I will find time and motivation soon to look into Cygwin builds.
