### ISSUE TITLE
autoconf: Why are 'fuzzing test' and 'experimental code' under missing libs, and not development ?

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2970]
This is a question (possibly PEBCAK).  But it may also simply be that we adjust configure summary, and place these 2 items down in the development section.

**Comment by magnumripper** [comment]
I've had the exact same thoughts, just didn't have time to care yet. So yes, this issue is a to-do.

**Comment by magnumripper** [comment]
I think they simply pre-date the "development" heading.

**Comment by jfoug** [comment]
Ah, that makes 100% sense.   Simple to change.  I have been working on configure (as has @claudioandre).  Once it stablizes to where there is only 1 version being worked on, I can easily change this. It is simply moving 2 lines at the summary section, not a big deal. But those 2 options really are dev options, not for normal users.  As far as that goes, I think ALL development options on the summary should be hidden until at least 1 of them is selected.  What do you think about that??  They would still show up in the ./configure --help  just not show up in summary for a joe -luser

**Comment by jfoug** [comment]
Pretty trivial change. I just pushed to main branch.  d6b0f4c2a
