### ISSUE TITLE
Wasting CPU cycles on Circle

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2971]
Someone adjusted paralelism on CicleCI to 4 (we all can do it)
* https://circleci.com/gh/magnumripper/JohnTheRipper/edit#parallel-builds

Since it is not properly been used (all 4 instances build run the same tests), it seems just a waste of CPU cycles.

I intend to reset to 1 and close this, just waiting to see if anyone has a reason or plan for it.

**Comment by jfoug** [comment]
It was likely me, when I was trying to figure crap out. 

What did I do wrong?   likely my profile is now setup for 4x parallelism, and is also wasting CI cpu cycles.

**Comment by claudioandre** [comment]
> What did I do wrong? likely my profile is now setup for 4x parallelism, and is also wasting CI cpu cycles.

You did nothing wrong. You:
- asked for 4 jobs -> granted;
- now you have to use them; I mean, specify:
  - node 0: do this;
  - node 1: do that;
  - ...

If you don't, everybody is doing the same task, meaning the same task runs 4 times.

E.g., I have 2x, one is running the 32bits build and the other the 64bits.

**Comment by magnumripper** [comment]
I'm pretty sure I bumped it, sorry. I misunderstood its use.

OTOH we should definitely re-work the circle-ci job so it doesn't do a dozen of builds in one job (#2962) and then we might want to bump this again (provided I understand better now).

**Comment by jfoug** [comment]
@magnumripper I read your #2962, and simply do not understand it. You HAVE to do multiple builds, to test multiple builds???!!  I just do not understand the reasoning behind trying to do this all in a single build

**Comment by magnumripper** [comment]
In Travis, we have one "job" that builds plain CPU and no ASan. And *another* job that builds with OpenCL, a *third* that builds with OpenCL and so on. Each job is one configure+make. Any job failing is easy to spot.

In CircleCI, we have like **ONE** job with a script building a dozen of crazy builds for Windows, Linux, PDP-11, Apollo III, 17-bit, 35-bit and whatnot. That one "job" often passes without any clue even though some of the builds failed, some others segfaulted and some failed self-test.

**Comment by claudioandre** [comment]
Fixed.
