### ISSUE TITLE
fmt_registers.h:209: undefined reference to `fmt_stribog_256'

### ISSUE THREAD

**Issue by bill-e-ghote** [magnumripper/JohnTheRipper#2973]
I'm using bleeding-jumbo, updated just now. Final linking step breaks with the following error:

john.o: In function `john_register_all':
/home/wdawson/Software/bleeding-jumbo/src/fmt_registers.h:209: undefined reference to `fmt_stribog_256'
/home/wdawson/Software/bleeding-jumbo/src/fmt_registers.h:210: undefined reference to `fmt_stribog_512'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1320: ../run/john] Error 1
make[1]: Leaving directory '/home/wdawson/Software/bleeding-jumbo/src'
make: *** [Makefile:182: default] Error 2

This is for a Gentoo based system running as an Oracle VirtualBox guest with no opencl devices.

**Comment by magnumripper** [comment]
Did you try re-running `./configure`? We had a CPUID bug for a while that affected Stribog formats. Please fetch latest stuff and build properly.
