### ISSUE TITLE
Performing -test-full=1 gives some errors

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#2996]
```
Testing: dynamic=md5($p) [256/256 AVX2 8x3]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))

Testing: hdaa, HTTP Digest access authentication [MD5 256/256 AVX2 8x3]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))

Testing: krb5-17, Kerberos 5 DB etype 17 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))

Testing: krb5-18, Kerberos 5 DB etype 18 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))

Testing: krb5-3, Kerberos 5 DB etype 3 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))

Testing: Palshop, MD5(Palshop) [MD5 + SHA1 32/64]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))

6 out of 392 tests have FAILED
```
I am looking into this now, to see if this is a false alarm on the -test-full=1 usage, probably NOT

**Comment by jfoug** [comment]
I do see this comment in formats.c on the code that tests for this condition  (not sure who wrote it, might be me, lol)

```
/*
 * This function is to detect whether the format need to unify cases in split()
 * and add FMT_SPLIT_UNIFIES_CASE
 *
 *  NOTE, I think this test is NOT valid!  The 'results' of this function are
 *        currently not being listed to screen.  Right now, there is a handful
 *        of failures, and every one of them is a false-positive.
 */
```

So this might be a known PEBCAK issue.

**Comment by jfoug** [comment]
Well, I checked the dyna compiler format, and here is what I saw:

hash=@dynamic=md5($p)@900150983CD24FB0D6963F7D28E17F72
valid() returns true
split returns @dynamic=md5($p)@900150983CD24FB0D6963F7D28E17F72
binary returns expected value

hash=@dynamic=md5($p)@900150983cd24fb0d6963f7d28e17f72
valid() returns true
split returns @dynamic=md5($p)@900150983cd24fb0d6963f7d28e17f72
binary returns expected value


So yes, this one does need to unify case. Split should have returned @dynamic=md5($p)900150983cd24fb0d6963f7d28e17f72 for BOTH inputs!

**Comment by frank-dittrich** [comment]
@jfoug I guess you need to unify case to lower for raw hashes only, and reject hashes with dyna prefix and upper case hex in valid(). At least that's what most raw-* formats should) do and I think dyna should do the same.

**Comment by jfoug** [comment]
No, I am going to unify the dyna compiler stuff in split.

ALSO, I have found (I hope) the bug in test_fmt_split_unifies_case_3() function, to remove the false positives.  I FIXED dyna compiler, but was still getting that error.  I am testing now to see what still exists after that bug fix.

**Comment by jfoug** [comment]
Ok, after fixing dyna (adding fmt_split_unifies), and fixing split to actually perform the strlwr on the hash part, AND patching the test_fmt_split_unifies_case_3() function.   I get this:

```
Testing: cloudkeychain, 1Password Cloud Keychain [PBKDF2-SHA512 128/128 SSE4.1 2x]... PASS
Testing: dynamic=md5($p) [128/128 SSE4.1 4x1]... PASS
Testing: cq, ClearQuest [CQWeb]... PASS
```

So the error is gone (code fix), and the error text is gone.  This is a good change, and if that false positive crap is gone, we may want to look at a reintroduction of the ``` test_fmt_split_unifies_case_3() ``` back into -test-full=0  (with a PR of course to make sure the build bots are happy)

**Comment by jfoug** [comment]
Ok, after fixing dyna compiler (it WAS NOT a false alarm), and fixing the code in the test_case_3() function, running with ```--test-full=1``` works with zero problems.

I am going to check this in (through a PR). There is almost zero chance of damage (since that function is not even used, without ```--test-full=1``` and we use level 0, AND the change to dyna compiler is contained all within the split function.  Well, it is deeper in code that the outside world 'split' function, but it appears only in split() calls.

All other false alarms are taken care of with the code changes to the test_case_3(), and ALL of them were actually false alarms (and known to be false alarms).

**Comment by frank-dittrich** [comment]
@jfoug converting only raw hashes to lower case hex, and rejecting upper case hex in hashes with dynamic prefix should be faster.
I don't see any risk in rejecting upper case hex in such hashes.
If valid() rejects uppercase hex in prefixed hashes, test-full should work without problems, even with the current test-full implementation, see  
 https://github.com/magnumripper/JohnTheRipper/pull/2845#issuecomment-343122052

**Comment by jfoug** [comment]
the valid is dynamics valid.   that is a much larger task, BY FAR.

**Comment by jfoug** [comment]
The code for case-test#3 is now fixed. There were 2 formats which WERE buggy.  dynamic compiler and palshop.   Both are fixed and I am just waiting for build bots to complete and then merge.

**Comment by jfoug** [comment]
dyna_compiler format was not fixed, and had to be reverted.  So even though test case#3 is 'fixed' we still only are going to be able run it in --test-full=1 level, to keep the build bots happy.

**Comment by jfoug** [comment]
dyna compiler now fixed with proper split (inside normal dynamic format).  Also the revert of format.c reverted.
