### ISSUE TITLE
Add support for cracking Apple Secure Notes

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#2999]
The folks behind hashcat have done all the original hard work :+1: 

References,

* https://github.com/hashcat/hashcat/blob/master/tools/securenotes2hashcat.pl

*  Format code is in `m16200.cl` OpenCL kernel.

* `$ASN$*1*20000*35317234050571840136152316737833*fdcdf88f2b65f95d5b9225db2c85496e7ebb12e655314460:hashcat`

I wish that folks would stop making the same mistake (putting a `*` immediately after `$` at the hash start ) I made when designing the PDF output hash format in year 2011 :-)

**Comment by kholia** [comment]
When cloud syncing is not enabled, it seems that `ZISPASSWORDPROTECTED` is not set, and `ZCRYPTOWRAPPEDKEY` is empty. I have found a way to still crack such database entries.

**Comment by kholia** [comment]
Instead of naming the hash extraction tool as `securenotes2john.pl`, I am thinking of calling it `notes2john.py`. The name of the original software is `Apple Notes`. I am not sure which name is better. Suggestions are welcome!

**Comment by magnumripper** [comment]
applenotes2john perhaps? That says more about what it is for. It's not only iPhone but also iPad and macOS computers.

**Comment by kholia** [comment]
Thanks, `applenotes2john` it is then. This script also extracts the password hint(s) if present in the database.

**Comment by kholia** [comment]
The GPU utilization is great. All thanks to @magnumripper for writing the pure GPU kernel ("fvde" stuff).

```
$ cat hash.txt 
$ASN$*4*20000*caff9d98b629cad13d54f5f3cbae2b85*79270514692c7a9d971a1ab6f6d22ba42c0514c29408c998
```

```
$ ../run/john --format=notes-opencl --mask='o?l?l?l?lall' hash.txt 
Device 0: GeForce GTX 1050 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (notes-opencl, Apple Notes [PBKDF2-SHA256 AES OpenCL])
Cost 1 (iteration count) is 20000 for all loaded hashes
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:21 78.65% (ETA: 12:34:36) 0g/s 17107p/s 17107c/s 17107C/s GPU:56C oapdvall..oolkvall
openwall         (?)
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```


```
$ ../run/john --test=2 --format=notes-opencl
Device 0: GeForce GTX 1050 Ti
Benchmarking: notes-opencl, Apple Notes [PBKDF2-SHA256 AES OpenCL]... DONE, GPU util:100%
Speed for cost 1 (iteration count) of 20000
Raw:	18340 c/s real, 18249 c/s virtual
```

**Comment by kholia** [comment]
On `super` box,

```
$ ../run/john --test --format=notes-opencl
Device 6: GeForce GTX TITAN X
Benchmarking: notes-opencl, Apple Notes [PBKDF2-SHA256 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 20000
Raw:	41654 c/s real, 41654 c/s virtual
```

**Comment by jmvermeulen** [comment]
I've got a db with +- 200 rows. 

Some of them have identical hashcat values (of course the ID differences). Is there any conclusion that I can make about this? Like the password is by definition not the same for all notes? I read that a user can reset its password. This will not unlock older notes but sets a new password for the new created notes. The `salt` is the same over all notes by the way.

**Comment by magnumripper** [comment]
*Hashcat* values? You mean the last, 48-digit blob, right? I'm not sure yet what that tells us.

If the salt (the 32-digit blob) is indeed reused, I will add this format to my to-do for #3497 which would make your job 200x faster to attack (or `n`x faster for `n` salts). Although I'd rather guess it's only reused in case of same password. That would still be poor design because it'd mean you will know that and only attack one single line at first.

**Comment by magnumripper** [comment]
OK that blob is a KEK (Key Encryption Key). I'm not quite sure we can make any conclusion of same-salt-different-kek. Anyway, the salt re-use definitely looks like a blunder. I'll try to create a lab file and try to establish when the actual key changes (the one protected by the KEK).

**Comment by jmvermeulen** [comment]
Just a small reply on my phone.
I creaked all hash values today! All where the exact same password despite salt that was the same on quite some hashes but was unique too in other records. In my case the password was on a wordlist. It took some time for crack all hashes, despite being the same password for all rows. So yeah this could benefit strongly from you optional approach.

My conclusion, based on the different salts you cannot make the conclusion about the password being different or not. If you input a cracked password in the apple notes app, all notes with the same password unlock at the same time.

Just a thought, maybe it has to do with the device that adds the specific note. In my case it were notes added on different devices and synced thought iCloud. Will post some more example details tomorrow.

**Comment by magnumripper** [comment]
Thanks, that's good input.

**Comment by jmvermeulen** [comment]
Sorry I wasn't totally right.

The salt is consistent over all 200 rows.
Only the last  48-digit blob that's called `ZCRYPTOWRAPPEDKEY` in the sqllite changes in **some** cases. There are many exactly the same. As stated before, the password was the same for all.

**Comment by magnumripper** [comment]
In that case the existing version should see them as pure dupes. I assume John didn't say "Loaded 200 hashes" but instead the actual number of different combinations, right?

Is the iteration count the same for all of them BTW? Different iteration counts would give different KEK's even for same password.
