### ISSUE TITLE
configure: new cpuid logic (x86) needs quiet stderr output

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#3002]
From #2995 

@kholia : 
"
On our super box, I see.
```
$ ./configure > /dev/null; make -j32 > /dev/null
cc1: error: unrecognized command line option "-mavx2"
cc1: error: unrecognized command line option "-mavx2"
```
The build succeeds and works fine but these "error" messages are not looking good.
```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
```
I don't think that PR caused these message to show up. I am just noting it down here, so that I don't forget.
"

@jfoug : 
"
So on super, the compiler can build the cpuid code, have it detect AVX2, but the compiler does not support the -mavx2 flags?

Sounds like we have to change the logic on the new cpuid code. It will need to probe the compiler flags AND the CPU bits. then as long as both checks are ok, we try the next better CPU, until EITHER the cpuid flags say it is not there, OR the compiler says it knows nothing about that -mcpu flag
"

**Comment by claudioandre** [comment]
> So on super, the compiler can build the cpuid code, have it detect AVX2, but the compiler does not support the -mavx2 flags?

No. The cpuid detection is trying to detect avx2 (as it used to do):
* in fact, the error is not new [1]. In the past it was redirected to config.log.

A possible fix could be the redirection, as it used to happen.

[1]
```
$ cat config.log | grep -A36 -B1 mavx2
configure:9287: checking for AVX2
configure:9305: gcc -mavx2 -o conftest -m64 -g -O2 -I/usr/local/include -O0  -I/usr/local/include -m64  -L/usr/local/lib -L/usr/local/lib64 -L/usr/lib64 -L/lib64 conftest.c  >&5
cc1: error: unrecognized command line option "-mavx2"
configure:9305: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "john"
| #define PACKAGE_TARNAME "john"
| #define PACKAGE_VERSION "jumbo"
| #define PACKAGE_STRING "john jumbo"
| #define PACKAGE_BUGREPORT "john-users mailing list at openwall.com"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define SIZEOF_SHORT 2
| #define SIZEOF_INT 4
| #define SIZEOF_LONG 8
| #define SIZEOF_LONG_LONG 8
| #define SIZEOF_WCHAR_T 4
| #define SIZEOF_INT_P 8
| #define SIZEOF_VOID_P 8
| /* end confdefs.h.  */
| 
|     #include <immintrin.h>
|         #include <stdio.h>
|         extern void exit(int);
|         int main(){__m256i t, t1;*((long long*)&t)=1;t1=t;t=_mm256_mul_epi32(t1,t);if((*(long long*)&t)==88)printf(".");exit(0);}
| 
| 
configure:9312: result: no
```

**Comment by jfoug** [comment]
@kholia posted some useful output on the wrong thread (#2995)  Hopefully he will repost here.

So it sounds like correct results (i.e. the compile correctly fails, giving a NO result).  We just have compiler warnings being splattered into the ./configure output.

**Comment by frank-dittrich** [comment]
>  We just have compiler warnings being splattered into the ./configure output.

Those compiler warnings are written to stderr.
With `scl enable devtoolset-6 bash` on super, you get a more recent compiler which knows -mavx2.

**Comment by claudioandre** [comment]
BTW it is testing both the cpu AND the compiler.
* So the result will be NO even if the CPU can handle avx2 but the compiler can't.

**Comment by jfoug** [comment]
The end results are great.  It is the 'hiding' warning messages away from the configure screen output that i guess is the problem.

Yes, i agree, that code could compile but not run (i.e. new enough compiler, old CPU), or could 'have' run on this machine, but compiler too old.  So yes, I agree, that both the compiler and CPU get proper checks.

**Comment by magnumripper** [comment]
I have several fixes and new features cooking, this is probably solved already

**Comment by jfoug** [comment]
If you look at @kholia config output you can see the problem. I was hoping he would post here, so I would not have to copy his post:

@kholia 
```
$ ./configure
...
checking for SSE4.1... yes
checking for AVX... yes
checking for XOP... no
checking for AVX2... cc1: error: unrecognized command line option "-mavx2"
cc1: error: unrecognized command line option "-mavx2"
...
```

**Comment by kholia** [comment]
@jfoug I was just about to do so. You beat me to it. Thanks!

**Comment by jfoug** [comment]
title changed to reflect the real issue.

**Comment by kholia** [comment]
I can confirm that this issue has been fixed now.
