### ISSUE TITLE
Unify versioning used in JTR proper and bleeding

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#3014]
### IMPORTANT
Inside git:
```
1.8.0-jumbo-1-6249-g915e51d
```

Outside git:
```
Version: 1.8.0.12-jumbo-1-bleeding
```

**Comment by claudioandre** [comment]
* GitHub itself is not seeing the **1.8.1-jumbo-1** tag.

**Comment by frank-dittrich** [comment]
I still have these additional tags in my local repo:
```
1.8.0.5-jumbo-1
1.8.0.6-jumbo-1
```

AFAIK, @magnumripper deleted these tags, see

https://github.com/magnumripper/JohnTheRipper/issues/1788

I cloned the github repo before @magnumripper deleted these tags, and didn't delete these tags from my local git repo. 

Another problem: the version string for tarballs downloaded from github, i.e. the version string when john is built outside a git repo, says `1.8.0.12-jumbo-1-bleeding`. (It said `1.8.0.6-jumbo-1-bleeding` some time ago. I thinkt, that also is (or was) the version string of tarballs/"releases" downloadable via openwall. 

So, that version appears to be newer than the version when building a non-release inside a git repo.

**Comment by claudioandre** [comment]
IMO, the versioning scheme is confusing. There is no reason to use a pattern for git and something else if not using git.

I propose the patch below:
- unifies versioning scheme;
- show the correlation between bleeding and JtR proper;
- version is clear if you use git and if you don't;
- if the user is not using git, there is a cut-off date.
- allow to bump the cut-off date with a commit (but nodoby has to change the cut-off date);

Patch here: https://github.com/claudioandre/JohnTheRipper/commit/8364b45248ac7d0f7e9aeed72c8514eea6b81064

Real examples:
Version: 1.8.0.12-jumbo-1-bleeding-8364b45
Version: 1.8.0.12-jumbo-1-bleeding+20171215

**Comment by magnumripper** [comment]
The problem with tags is they will be shown as a "release" in GitHub. This means users will think it's a quality release.

**Comment by magnumripper** [comment]
@claudioandre I do not understand the issue. There is no 1.8.1-jumbo-1 tag and never was.

**Comment by claudioandre** [comment]
```
$ git show 1.8.1-jumbo-1
commit bc1f29d88c38182d222eff1a8e17e685b2fd1c31
Author: Dhiru Kholia <dhiru.kholia@gmail.com>
Date:   Wed Aug 23 21:05:40 2017 +0530

    Add support for EME2-AES in PGP Disk format
```

**Comment by frank-dittrich** [comment]
@claudioandre Do you want to commit a daily change updating the version string?

I think the best option is to look into `man git-archive`, especially section `ATTRIBUTES`, explanation for `export-subst`; `man 5 gitattributes`, and see if this allows adjusting the version string with something based on the git commit when the user downloads a tar archive from github.

But make sure we distinguish tar archive version strings from git repository version strings.

**Comment by frank-dittrich** [comment]
@claudioandre see also my older issue, https://github.com/magnumripper/JohnTheRipper/issues/2481

**Comment by magnumripper** [comment]
> ```
> $ git show 1.8.1-jumbo-1
> commit bc1f29d88c38182d222eff1a8e17e685b2fd1c31
> Author: Dhiru Kholia <dhiru.kholia@gmail.com>
> Date:   Wed Aug 23 21:05:40 2017 +0530
> 
>     Add support for EME2-AES in PGP Disk format
> ```

That's some tag you have locally.
```
$ mkdir temp
$ cd temp
$ git clone git://github.com/magnumripper/JohnTheRipper.git
Cloning into 'JohnTheRipper'...
remote: Counting objects: 79924, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 79924 (delta 27), reused 35 (delta 18), pack-reused 79869
Receiving objects: 100% (79924/79924), 87.85 MiB | 3.51 MiB/s, done.
Resolving deltas: 100% (62327/62327), done.
$ cd JohnTheRipper/
$ git show 1.8.1-jumbo-1
fatal: ambiguous argument '1.8.1-jumbo-1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by claudioandre** [comment]
Ok, I rewrote the history to make the point clear.
* I found the tag `1.8.1-jumbo-1` in 3 different computers, one of them is super (it is a clone of upstream, not my dev machine);
* I really believe someone else (not me) created the tag in upstream bleeding-jumbo; It was deleted;
* I was confused because I can see a tag `1.8.1-jumbo-1` and opened a bad bug report; BTW: solar was also expecting something greater than 1.8.0.xx as a version; So, it was not only me.

That said, the bug here is why the versioning is the way it is.

**Comment by claudioandre** [comment]
> Do you want to commit a daily change updating the version string?

No. Only if anyone add an important fix or a new resource and want to assure the user really has a new version. E.g., if I add a new algo to a *2john tool, that is an easy way to check if the user has the proper version looking at `build-info` (and I dont need to care about the user environment).

**Comment by magnumripper** [comment]
So let's forget about the bogus local tag. We still have an issue: I agree that the versioning scheme is strange. First, it will reflect any local tag the the user creates. Second, a non-git build version differs from a git build one in a way that is not very intuitive.

Your suggestion in https://github.com/claudioandre/JohnTheRipper/commit/8364b45248ac7d0f7e9aeed72c8514eea6b81064 is not too bad. The date can stay unchanged for a month or so but we'll still be able to figure out if someone on john-users are running an ancient build or not.

I'd love to produce a better value but I can't think of one.

**Comment by magnumripper** [comment]
I'm thinking most or all non-git builds are produced from some archive that preserves dates. Perhaps if we somehow fetch the file timestamp from a file that "never" changes (eg. `src/john.asm`), this might be a good indicator of when the archive was created?

**Comment by claudioandre** [comment]
> I'd love to produce a better value but I can't think of one.

Me neither. 
* The solution TM would be a GitHub webhook doing [1]. But this is not possible. GitHub only offers notifications on webhooks.

[1] `echo "#define commited_at $(date)" > github-date.h`

**Comment by frank-dittrich** [comment]
@magnumripper I doubt many users create local tags. Most of these local tags are leftovers from tags which existed in the github repo.
You could use annotated tags, and switch from `git describe --tags` to `git describe` to avoid the problem with those previous github tags leftover in local repositories.
The risk of users creating annotated tags in their local repositories is low, I think. 

We could also enhance  JTR_GIT_VERSION by adding the date of the most recent commit to the string.
(If a user has additional local commits, the date will change, compared to a repo without additional commits, but so will the abbreviated commit id in the version string).

For JtR build based on tarballs downloaded from github, we could try my suggestion in https://github.com/magnumripper/JohnTheRipper/issues/2481, specially something similar to https://github.com/frank-dittrich/JohnTheRipper/commit/82bd82a88ab73a2233a8b4697a47e16ac946c377, but adjust the Makefile instead of params.h.

**Comment by frank-dittrich** [comment]
What about this?

```diff
$ git show
commit b1330eed323746f3e6ed607446d392202dd162e7
Author: Frank Dittrich <frank.dittrich@mailbox.org>
Date:   Sat Dec 16 12:00:52 2017 +0100

    Unify john version string logic, based on ideas of Claudio André

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..503b8be
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1 @@
+src/Makefile.in export-subst
diff --git a/src/Makefile.in b/src/Makefile.in
index 6903e75..faa0920 100644
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -43,9 +43,13 @@ top_srcdir = @top_srcdir@
 srcdir = @srcdir@
 prefix = @prefix@
 
-JTR_GIT_VERSION = \"$(shell git describe --tags --dirty=+ --always 2>/dev/null)\"
-ifeq ($(JTR_GIT_VERSION), \"\")
-JTR_GIT_VERSION = JOHN_VERSION
+JTR_GIT_COMMIT = \"-$(shell git describe --dirty=+ --always 2>/dev/null)\"
+ifeq ($(JTR_GIT_COMMIT), \"-\")
+JTR_ARCHIVE_VERSION_STRING = "$Format:-%h %ci$"
+JTR_GIT_VERSION = JOHN_VERSION "\"$(JTR_ARCHIVE_VERSION_STRING)\""
+else
+JTR_GIT_HEAD_TS = \" $(shell git show -s --format=%ci HEAD 2>/dev/null)\"
+JTR_GIT_VERSION = JOHN_VERSION "$(JTR_GIT_COMMIT) $(JTR_GIT_HEAD_TS)"
 endif
 
 CPPFLAGS = @CPPFLAGS@
```
https://github.com/frank-dittrich/JohnTheRipper/commit/b1330eed323746f3e6ed607446d392202dd162e7


If will show the git commit and the timestamp of latest git commit (i.e., HEAD).

Inside a git repository:
```
$ ../run/john --list=build-info |head -n1
Version: 1.8.0.12-jumbo-1-bleeding-b1330ee 2017-12-16 13:06:36 +0100
$ ../run/john |head -n1
John the Ripper 1.8.0.12-jumbo-1-bleeding-b1330ee 2017-12-16 13:06:36 +0100 OMP [linux-gnu 64-bit x86_64 AVX AC]
```

An archive built using `git archive --format=tgz HEAD > ../test/fdtest.tgz` or downloaded from github (as long as you don't extract the archive inside a git repository), i.e., download a tar archive from my github repo:
https://github.com/frank-dittrich/JohnTheRipper/archive/bleeding-jumbo.tar.gz

```
$ ../run/john --list=build-info |head -n1
Version: 1.8.0.12-jumbo-1-bleeding-b1330ee 2017-12-16 13:06:36 +0100
$ ../run/john |head -n1
John the Ripper 1.8.0.12-jumbo-1-bleeding-b1330ee 2017-12-16 13:06:36 +0100 OMP [linux-gnu 64-bit x86_64 AVX AC]
```

Now there's no way to distinguish JtR builds from git repositories and JtR builds from downloaded github archives. We might want to change that.
The complete time stamp might be overkill as well.

**Comment by frank-dittrich** [comment]
Should create a github bug report because github shows all tags as "releases"m not just annotated tags?

See `man git tag`, especially:
```
Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will
ignore lightweight tags by default.
```

**Comment by magnumripper** [comment]
> What about this?

Sounds good

> Now there's no way to distinguish JtR builds from git repositories and JtR builds from downloaded github archives. We might want to change that.

I think not - as long as they're the same version that is a good thing!

**Comment by frank-dittrich** [comment]
> I think not - as long as they're the same version that is a good thing!

But currently you can tell whether a user works with a local git repo or a tarball.
In future, you can't tell, but suggestions what to do might depend on whether or not the user is using git.

**Comment by magnumripper** [comment]
True but IMHO the most important thing is knowing whether the user are running a fairly recent Jumbo or not. I guess you could simply add a tag like "archive" somewhere to indicate that if you wish.

**Comment by magnumripper** [comment]
> I guess you could simply add a tag like "archive" somewhere to indicate that if you wish.

I mean like in JTR_ARCHIVE_VERSION_STRING or something. I know nothing about that one but I'm pretty sure we could do something like that one way or the other.

**Comment by magnumripper** [comment]
> Should we create a github bug report because github shows all tags as "releases"m not just annotated tags?

I think we should

**Comment by frank-dittrich** [comment]
> I think we should

Apparently, the only way to report bugs is via mail to  support@github.com.

I think we should ask for an option (for the owner of a github repository) to only show annotated tags as releases.
(It is more likely that they add this option instead of changing the default behavior for all.)

**Comment by frank-dittrich** [comment]
> I think we should

Since you are the owner of this github repository, will you do it?

If so, make sure you quote this from `man git tag`:
```
Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will
ignore lightweight tags by default.
```

**Comment by magnumripper** [comment]
Will do, thanks
