### ISSUE TITLE
Hash from rar2john too large for cmd

### ISSUE THREAD

**Issue by itchyballsack** [magnumripper/JohnTheRipper#3024]
I have tried to make the cmd buffer size larger but that doesn't seem to help, any suggestions?

**Comment by kholia** [comment]
I don't understand what you are trying to say. Provide all the necessary details, and explain your problem again.

**Comment by itchyballsack** [comment]
Sorry, can you delete this issue, I had a blonde moment, I can just output the hash to a file

**Comment by kholia** [comment]
Issues can't be deleted. Please think critically before you open such low quality (non) issues. Such issues add to the noise, and waste precious time of others.
