### ISSUE TITLE
Create artificial test vectors for BitLocker format

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#3027]
Developing and testing BitLocker formats is a pain due to very high iteration count.

@jfoug Is this something which `pass_gen.pl` can help with (in the near future)?

**Comment by kholia** [comment]
Here are two artificial test vectors created by hacking the format a bit,

```
$ cat ../run/john.pot 
$bitlocker$0$16$134bd2634ba580adc3758ca5a84d8666$500$12$9080903a0d9dd20103000000$60$99919e1e955b55f75f2f16eb0af96f2d605630a49879d8f2458e390ef87722ae346e391be3e1c6d9af425a576dac155ad306e9ce7a407dd2ab431102:openwall@123
$bitlocker$0$16$73926f843bbb41ea2a89a28b114a1a24$500$12$30a81ef90c9dd20103000000$60$96461b121c7a42c454492162042586ea7848c5b09fdb58234f60c06ebf74b2e1ca6dec0b7f3958e32fa2c50f8772ca0a2227bad8ea10fce03fe07b6c:password@123
```

**Comment by magnumripper** [comment]
> I just discovered that the BitLocker OpenCL format does not support a variable iteration count.

It definitely should. Is this fixed in the pending PR's?

**Comment by kholia** [comment]
> Is this fixed in the pending PR's?

@e-ago tried to modify the OpenCL format in the latest PR to implement this but no luck yet.

**Comment by jfoug** [comment]
> @jfoug Is this something which pass_gen.pl can help with (in the near future)?

Working on this now.  I will post soon (hopefully), and point it back to this issue.

**Comment by e-ago** [comment]
See https://github.com/magnumripper/JohnTheRipper/pull/3038 for variable iteration count

**Comment by kholia** [comment]
This issue has been manually solved for now. Closing!
