### ISSUE TITLE
zip hash "No password hashes loaded"

### ISSUE THREAD

**Issue by chris948** [magnumripper/JohnTheRipper#3032]
### Steps to reproduce
Trying to follow a walk-through here:
https://vulnsec.com/2017/SANS-Holiday-Hack-Challenge-2016/

so taking the zip hash of http://northpolewonderland.com/SantaGram_v4.2.zip

./zip2john /root/Downloads/SantaGram_v4.2.zip > zip2.hash
ver 2.0 efh 5455 efh 7875 SantaGram_v4.2.zip->SantaGram_4.2.apk PKZIP Encr: 2b chk, TS_chk, cmplen=1962826, decmplen=2257390, crc=EDE16A54

./john /root/JohnTheRipper/run/zip2.hash
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

File locations are haphazard, got the same error on my Kali VM, so I'm trying a newer version of John. Googling it seems to suggest going back to a pre 1.8 version. Not even sure how to do that.

### System configuration
John the Ripper 1.8.0.12-jumbo-1-bleeding-eaf1723aa

**Comment by claudioandre** [comment]
To me it is working:

```
$ john-the-ripper.zip2john SantaGram_v4.2.zip  > zip2.hash
ver 2.0 efh 5455 efh 7875 SantaGram_v4.2.zip->SantaGram_4.2.apk PKZIP Encr: 2b chk, TS_chk, cmplen=1962826, decmplen=2257390, crc=EDE16A54

$ john-the-ripper zip2.hash
Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])
Will run 2 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:03  3/3 0g/s 83067p/s 83067c/s 83067C/s myses..154143
Session aborted
```

Are you sure you don't facing permissions problems?

**Comment by claudioandre** [comment]
Better, can you post the ./configure output? Focus on the line seen below

```
libz (pkzip format, gpg2john) .............. yes
```

**Comment by magnumripper** [comment]
Perhaps we should add a build `#warning` just like for eg. stribog w/o SSE4.1, suggesting to install libz and re-configure/re-build.

**Comment by chris948** [comment]
Thanks, I took the hint to install libz, but I didn't know to re-build, so thanks for both of the posts. I appreciate the help.

I'm starting to see with git that trying to just use a kali install is useless.

**Comment by magnumripper** [comment]
> Perhaps we should add a build #warning just like for eg. stribog w/o SSE4.1, suggesting to install libz and re-configure/re-build.

I'll open a new issue for this.

**Comment by hasib940** [comment]
mishty.rar:$rar5$16$937b4d423dad7d17aeedbca0a57e58ae$15$72eef76fc554bf78ec15ceae104da8bc$8$b1c8547ed670d122


can anyone decode this please????? :(

**Comment by King-Of-Game** [comment]
The another probability: the file in the compressed package is damaged

**Comment by magnumripper** [comment]
> The another probability: the file in the compressed package is damaged

I disagree with that being probable for the OP. Also, why are you even commenting an issue that was closed over two years ago? I will delete your post (and this answer of mine).
