### ISSUE TITLE
Can't enable OpenMP

### ISSUE THREAD

**Issue by mounirbelhniyene** [magnumripper/JohnTheRipper#3037]
Hi,

As I read at openwall's documentation, OpenMP is automaticlly enabled, but when I want to crack a zip file, OpenMP still disabled. How can I activate 

Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])
Warning: OpenMP is disabled; a non-OpenMP build may be faster

**Comment by kholia** [comment]
Use http://www.openwall.com/lists/john-users/ for end-user support questions.

**Comment by kholia** [comment]
It appears that you ignored the issue template message completely, which says,

```
- If you have questions, please ask them first in the mailing list john-users at lists.openwall.com;
- Use issues to keep track of ideas, enhancements, tasks, and bugs. NEVER as a support forum;
```

**Comment by mounirbelhniyene** [comment]
I'am really sorry about it, but I'm really frustrated with this lack of help and documentation, especially for 1.8.0-jumbo-1

**Comment by kholia** [comment]
You still haven't posted your question / problem to `john-users` mailing list. Also, your report is lacking details (OS, JtR Jumbo version, etc) and is not useful for others to diagnose the problem.

> I am really sorry about it, but I'm really frustrated with this lack of help and documentation.

Once you solve your problem, will you contribute back and help in improving the documentation?

Use `john-users` mailing list for further discussion on this topic.

**Comment by solardiz** [comment]
> You still haven't posted your question / problem to john-users mailing list.

Actually, I think @mounirbelhniyene had already sent the message by the time you posted this. There are moderation delays, and indeed someone who hasn't posted to the list previously has their messages pre-moderated. I note this for future occasions: just because you don't see a message on a list yet doesn't mean the person hasn't sent the message.

**Comment by kholia** [comment]
Thanks. Apparently I forgot to refresh my mail client. My bad.
