### ISSUE TITLE
32 bits CPU detection has problems

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#3041]
I don't do 32 bits on Linux, so it is a note I took on:
* Real Windows + CygWin
```
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for AVX... yes
checking for XOP... yes
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
checking for arch.h alternative... x86-sse.h
checking for byte ordering according to target triple... little
checking for OPENSSL... yes
[...]
Target CPU ................................. i686 AVX512BW, 32-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h
Optional libraries/features found:
```

**Comment by magnumripper** [comment]
> checking for AVX512F... yes
> checking for AVX512BW... yes

Doesn't look too good... But I don't see that on our bots?

**Comment by claudioandre** [comment]
You dont have 32 bits on AVX2 machine.

**Comment by solardiz** [comment]
BTW, we do have 32-bit libs on well, and could try making a 32-bit build there (would require `-m32`).

**Comment by magnumripper** [comment]
It's probably some glitch with the asm file. I could never test it very well.

**Comment by jfoug** [comment]
> You dont have 32 bits on AVX2 machine.

Are you saying you can not build a 32 bit binary on an AVX2 machine, or that you can not access AVX2 instructions 'from' a 32 bit build?   I think both assertions are invalid.

```
$ ./configure -C
configure: creating cache config.cache
checking build system type... i686-pc-cygwin
checking host system type... i686-pc-cygwin
checking whether to compile using MPI... no
checking for gcc... gcc
checking whether the C compiler works... yes
...
configure: Testing build host's native CPU features
checking for Hyperthreading... yes
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for AVX... yes
checking for XOP... yes   (___NOTE wrong___)
checking for AVX2... yes
checking for AVX512F... yes   (___NOTE wrong___)
checking for AVX512BW... yes   (___NOTE wrong___)
checking for arch.h alternative... x86-sse.h
.....
Configured for building John the Ripper jumbo:

Target CPU ................................. i686 AVX512BW, 32-bit LE   (___NOTE wrong___) should be AVX2
AES-NI support ............................. run-time detection
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h
```

Changed Makefile to be HAVE_AVX2  and -mavx2 and then built:

```
$ make -s clean && make -sj8
ar: creating secp256k1.a
ar: creating aes.a
Make process completed.

$ ../run/john -test=0
Will run 8 OpenMP threads
Testing: descrypt, traditional crypt(3) [DES 256/256 AVX2]... (8xOMP) PASS
Testing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 256/256 AVX2]... (8xOMP) PASS
Testing: md5crypt, crypt(3) $1$ [MD5 256/256 AVX2 8x3]... (8xOMP) PASS
Testing: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/32 X2]... (8xOMP) PASS
Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]... (8xOMP) PASS
Testing: LM [DES 256/256 AVX2]... (8xOMP) PASS
Testing: AFS, Kerberos AFS [DES 48/64 4K MMX]... PASS
Testing: tripcode [DES 256/256 AVX2]... (8xOMP) PASS
Testing: agilekeychain, 1Password Agile Keychain [PBKDF2-SHA1 AES 256/256 AVX2 8x2]... (8xOMP) PASS
Testing: aix-ssha1, AIX LPA {ssha1} [PBKDF2-SHA1 256/256 AVX2 8x2]... (8xOMP) PASS
Testing: aix-ssha256, AIX LPA {ssha256} [PBKDF2-SHA256 256/256 AVX2 8x]... (8xOMP) PASS
Testing: aix-ssha512, AIX LPA {ssha512} [PBKDF2-SHA512 256/256 AVX2 4x]... (8xOMP) PASS
...
```

So the 32 bit build runs just fine.

BUT as far as CPUID goes, it detects XOP, AVX512F and AVX512BW, even though this is a Haswell CPU (only has AVX2).  This problem is not seen on the 64 bit build.

Note, I did build with -mavx512bw flags left in,  and here is what I got:

```
$ ../run/john -test=0
Will run 8 OpenMP threads
Testing: descrypt, traditional crypt(3) [DES 256/256 AVX2]... (8xOMP) PASS
Testing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 256/256 AVX2]... (8xOMP) PASS
Testing: md5crypt, crypt(3) $1$ [MD5 256/256 AVX512F 8x3]... (8xOMP)
```

So the autodetect is not only broken in the configure, but also in the real john runtime.  If the CPUID was working within john proper, that program should bailed out saying the CPU was not what is required to run the process.

**Comment by jfoug** [comment]
>  I could never test it very well.

Hopefully I can look into it.  I can test under cygwin, but other than correctly failing on XOP/AVX512+ I am not sure how to detect problems.

**Comment by magnumripper** [comment]
>> You dont have 32 bits on AVX2 machine.
>
> Are you saying you can not build a 32 bit binary on an AVX2 machine, or that you can not access AVX2 instructions 'from' a 32 bit build?   I think both assertions are invalid.

He's saying we don't have that on our build bots

**Comment by claudioandre** [comment]
> I think he's saying we don't have that on our build bots

Indeed.

> But I don't see that on our bots?

Because 32 bits bots are SSE2. They give up very very soon.

**Comment by solardiz** [comment]
> Testing: md5crypt, crypt(3) $1$ [MD5 256/256 AVX512F 8x3]... (8xOMP)

Note that 256/256 is inconsistent with AVX512F.

**Comment by magnumripper** [comment]
I pushed a fix for ./configure. It was using x86-any.h instead of x86-sse.h for the CPU detection stuff.

Still, we should verify correct functionality and also improve the 32-bit AVX2 checks so it's same as for 64-bit.

**Comment by solardiz** [comment]
Why would ./configure need to use x86-sse.h for the CPU detection stuff?

**Comment by magnumripper** [comment]
Because it builds x86*.S just like in a real build of JtR (just like you suggested and an excellent idea).

BTW the "x86-any.S" is a confusing name: It's an old arch.h for non-SIMD use. The x86-sse.h is also confusing now - it doesn't merely support SSE.

**Comment by claudioandre** [comment]
Using HEAD

```
checking special compiler flags... Intel x86
configure: Testing build host's native CPU features
checking for Hyperthreading... yes
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for AVX... yes
checking for XOP... yes
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
checking for arch.h alternative... x86-sse.h
[...]
Target CPU ................................. i686 AVX512BW, 32-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h
```

But the commit fixed one problem in mingw
* Before
```
Target CPU ................................. i686, 32-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. mingw32
Cross compiling ............................ no
Legacy arch header ......................... x86-any.h
```

* After:
```
Target CPU ................................. i686 AVX512BW, 32-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. mingw32
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h
```

**Comment by magnumripper** [comment]
Strange. I could reproduce the problem building 32-bit on my Macbook and after 9e96d5c2 it worked just fine. This computer only has AVX though. I guess we now only have a problem with false positive for AVX512*. I'm not sure I ever tested that code on anything with AVX2.

**Comment by magnumripper** [comment]
LOL, I see the problem now. I never ever implemented AVX512 **at all** in the 32-bit asm.

This means we need to revert those tests, until someone (@solardiz?) implements proper stuff (including a correct test for AVX2).

**Comment by claudioandre** [comment]
I'm looking at the code now:
* where is the code to detect AVX512*? Ctrl+f 'AVX512' and **not found**?!?

**Comment by magnumripper** [comment]
Some manual fuzzing about with the cputest code gives me correct result for sse2, ssse3, sse4.1 and avx (all true) and avx2 (false) but then give a false positive for XOP already. That one **should** work.

**Comment by magnumripper** [comment]
I implemented the missing leaf 7 tests in x86.S and added some missing stuff in x86-sse.h. Should work now, although I still hope for a cleaner rewrite in core by @solardiz

**Comment by jfoug** [comment]
Not sure anything changed:

```
configure: Testing build host's native CPU features
checking for Hyperthreading... yes
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for AVX... yes
checking for XOP... yes
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
checking for arch.h alternative... x86-sse.h
checking for byte ordering according to target triple... little
```

**Comment by magnumripper** [comment]
@jfoug what exact commit was that? I tested everything and sprayed the code with `#warning`s to see the right stuff happened.

**Comment by magnumripper** [comment]
Try this

cputest.c
```c
extern int CPU_detect(void);
extern char CPU_req_name[];
unsigned int nt_buffer8x[4], output8x[4];

int main(int argc, char **argv) {
	return !CPU_detect();
}
```

This is how I ran it on my macbook, you may need to adjust/remove a few options (`-DUNDERSCORES` and the like)
```
$ for i in sse2 ssse3 sse4.1 avx xop avx2 avx512f avx512bw; do gcc -m32 -g -O2 -I/usr/local/include -m$i -P  -DUNDERSCORES -DBSD -DALIGN_LOG  -I/usr/local/include   -Wall -Wdeclaration-after-statement -fno-omit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations -Wunused-but-set-variable -std=gnu89 -Wdate-time x86.S  -I/usr/local/include  -L/usr/local/lib cputest.c -o cputest >/dev/null && ./cputest && echo $i || echo NOT $i ; done
sse2
ssse3
sse4.1
avx
NOT xop
NOT avx2
NOT avx512f
NOT avx512bw
```

**Comment by claudioandre** [comment]
It is still testing, but works.
* https://github.com/claudioandre/JohnTheRipper/tree/36fdd97f0085ba724f19ac4268ff4c9fbe34ab80/src

It can't detect AVX2 (or the machine is AVX only). I will try to rebuild later.
```
Target CPU ................................. i686 AVX, 32-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h
```

**Comment by magnumripper** [comment]
@claudioandre that link you posted looks like a branch that's three days behind?

**Comment by jfoug** [comment]
I took the changes from 5ffd17e (x86-sse.h and x86.S) and placed them into the code in my 32 bit directory (from a fresh pull)

**Comment by magnumripper** [comment]
OK but what commit were that directory at before this? If you don't have 9e96d5c2eb, that's the problem.

**Comment by magnumripper** [comment]
The fact it says `checking for arch.h alternative... x86-sse.h` does not mean that one was used for the CPU checks.

**Comment by jfoug** [comment]
>  If you don't have 9e96d5c, that's the problem.   

Gotcha.  I likely DO not have that.  arch->x86-any.h was what was sitting in the directory before I started doing the test script you listed.

BUT now I see this (so there is something still missing to run that test script)

``
`x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT sse2
```
All compiles are like the above.

**Comment by claudioandre** [comment]
> that link you posted looks like a branch/fork that's three days behind?

No. E.g.
* HEAD is -> Latest commit 36fdd97  22 minutes ago
* x86.S	x86.S, some clean-up.	an hour ago
* And history from https://github.com/claudioandre/JohnTheRipper/commits/36fdd97f0085ba724f19ac4268ff4c9fbe34ab80/src/configure

Configure and testing stuff
claudioandre committed 30 minutes ago 
 36fdd97  
 @magnumripper

Remove temporary workaround for 32-bit cpuid checks, and implement them.  …
magnumripper committed 2 hours ago
5ffd17e  
 @magnumripper 

Temporary bug workaround: Do not probe 32-bit x86 for better than AVX. …
magnumripper committed 3 hours ago
d1c4ee1  
 @magnumripper

Fix a problem with cpuid checks in ./configure on x86-32. See #3041.
magnumripper committed 5 hours ago
9e96d5c

**Comment by jfoug** [comment]
With a fresh pull from repo, i get detection up up to AVX, but no AVX2

**Comment by claudioandre** [comment]
I will save config.log to check. I believe it is not doing AVX2 (but it might be mingw/cywin).

![image](https://user-images.githubusercontent.com/1702923/34265801-387fecf0-e65e-11e7-8393-925213870a1b.png)

**Comment by claudioandre** [comment]
Better, I'll wait Jim, he can see config.log.

**Comment by magnumripper** [comment]
> With a fresh pull from repo, i get detection up up to AVX, but no AVX2

What if you run the manual test I posted a bit up here?

**Comment by jfoug** [comment]
Still seeing this:

```
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT sse2
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT ssse3
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT sse4.1
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT avx
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT xop
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT avx2
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT avx512f
x86.S: Assembler messages:
x86.S:152: Error: alignment not a power of 2
x86.S:637: Error: alignment not a power of 2
x86.S:672: Error: alignment not a power of 2
x86.S:727: Error: alignment not a power of 2
x86.S:832: Error: alignment not a power of 2
NOT avx512bw
```

**Comment by jfoug** [comment]
OK, removed BSD and ALIGN_LOG

```
$ for i in sse2 ssse3 sse4.1 avx xop avx2 avx512f avx512bw; do gcc -m32 -m$i -DUNDERSCORES x86.S  cputest.c -o cputest >/dev/null && ./cputest && echo $i || echo NOT $i ; done
sse2
ssse3
sse4.1
avx
NOT xop
NOT avx2
NOT avx512f
NOT avx512bw
```

This is what I see on configure also.

**Comment by magnumripper** [comment]
OK, now you have a chance to debug why AVX2 is not detected. I can't do it cause I don't have it here.

**Comment by jfoug** [comment]
Why not mimic x86-64.S   It does the leaf-7 tests last.  Also, the code for AVX2 simply places results of edx into eax and then the return happens.     So all the other tests have passed up to that point. IF that L7 test is OK (edx==1), then the return is true.

But where you have it, it is ok, but then the other tests happen after this.    Thus the logic is quite different.

**Comment by magnumripper** [comment]
> Why not mimic x86-64.S It does the leaf-7 tests last

The 32-bit version does strange things I don't even understand after these plain CPU tests. I can't deviate too much from core until I even understand that 😆

**Comment by magnumripper** [comment]
Found a silly bug, please try latest code.

**Comment by jfoug** [comment]
At least on my Haswel, this one works correctly:

```
$ for i in sse2 ssse3 sse4.1 avx xop avx2 avx512f avx512bw; do gcc -m32 -m$i -DUNDERSCORES -DBSD x86.S  cputest.c -o cputest >/dev/null && ./cputest && echo $i || echo NOT $i ; done
sse2
ssse3
sse4.1
avx
NOT xop
avx2
NOT avx512f
NOT avx512bw
```

**Comment by magnumripper** [comment]
I must have copy-pasted something from a leaf 1 check but the leaf 7 checks uses a different register 🙄

**Comment by jfoug** [comment]
This works fine on my AVX2 machine. I can not say for an XOP box, or an AVX512* system, but since they all use pretty much common code (just different defines), and it is the code also in x86-64.S, I would imagine that things are working on those systems also.

**Comment by magnumripper** [comment]
I really hope so, this has been a never ending story. I really like the fact we now use the very same tests in ./configure as in the final binary.
