### ISSUE TITLE
A few formats still use SIMD in --disable-simd builds

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#3044]
I believe this is the only hold out hash algo still using SIMD code when a non simd build is requested.

**Comment by magnumripper** [comment]
There's more, one even failing.
```
$ ../run/john -test=0 -form:@sse
Will run 8 OpenMP threads
Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 SSE2]... (8xOMP) PASS
Testing: argon2 [Blake2 SSE2]... (8xOMP) FAILED (cmp_all(1))

Testing: django-scrypt [Salsa20/8 128/128 SSE2]... (8xOMP) PASS
Testing: pomelo [POMELO 128/128 SSE2 1x]... (8xOMP) PASS
Testing: NT-old [MD4 128/128 X2 SSE2-16]... PASS
1 out of 5 tests have FAILED
```

**Comment by jfoug** [comment]
I thought I had blake2 handled.  That may be a false alarm. But I will get this addressed.

**Comment by jfoug** [comment]
I believe nt-old will have to be disabled in non-simd mode for 64 bits (on intel).  I am not sure about non-intel or 32 bit builds, I will check.  For 64 bit intel, ONLY the NT_X86_64 compatible code is contained within x86-64.S   So I think what we should do for a non-simd build, is to disable the format, AND make sure that code in x86-64.S does not compile.  Hopefully nothing else uses that code.

**Comment by jfoug** [comment]
All that is left is nt-old.   I would like some guidance on this one.  i would really just like to disable this format in non-simd builds.

But even if we do that, should we also scrub the code in x86-64.S and 'is' there code in x86.S (I would assume so) ?

**Comment by magnumripper** [comment]
Doesn't NT-old have an OpenSSL fallback?!

**Comment by magnumripper** [comment]
Here's a real non-SIMD build (using `-mno-mmx -mno-sse2` instead of --disable-simd)
```
Benchmarking: NT-old [MD4 32/64]... DONE
Raw:	15195K c/s real, 15195K c/s virtual
```

**Comment by magnumripper** [comment]
On a side note, the NT format is only half as fast as NT-old when it comes to non SIMD builds. I wonder why.
```
$ ../run/john -test -form:nt
Benchmarking: NT [MD4 32/64]... DONE
Raw:	7056K c/s real, 7056K c/s virtual
```

**Comment by magnumripper** [comment]
Ah, NT-old doesn't use OpenSSL, it has optimized C code that reverses steps.

**Comment by magnumripper** [comment]
Just a few arch.h changes needed for --disable-simd, I'm on it.

**Comment by jfoug** [comment]
Thanks for the NT-old help.  I thought it was going to be much more than that, due to some issues with the defines.

I did have an issue early on in the --disable-simd due to this format. looks like it is done correctly now.
