### ISSUE TITLE
New versioning problem

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#3047]
Or magnum did some repo cleanup or the GitHub staff did it (after our complain seen in #3042).

From:
   `Version: 1.8.0.12-jumbo-1-bleeding-b1330ee 2017-12-16 13:06:36 +0100`

To:
  `Version: 1.8.0.12-jumbo-1-bleeding-1.8.0-jumbo-1-6285-gc65fb94+ 2017-12-22 09:56:26 -0600`

The question is: what should we use? 
* I vote to remove the `git describe` and use `git rev-parse` in Makefile.in

**Comment by frank-dittrich** [comment]
What I like about `git describe` is that you see the number of commits since the release tag, e.g. 6285 commits after 1.8.0-jumbo-1.

**Comment by magnumripper** [comment]
Ouch, this is messy. I changed the 1.8.0-jumbo-1 tag to be annotated as we'll need that once GitHub fixes their bug.

**Comment by magnumripper** [comment]
I think we should just drop the `git describe`
