### ISSUE TITLE
SAP G format crashes on RPi3

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3050]
It's not really a bug, it's killed by the OOM reaper. I just want to confirm we're not using excessive memory without reason (many many formats pass but this one fails - why?)

**Comment by magnumripper** [comment]
It turns out I have 1 GB of memory and just 100 MB of swap with this noob installation of RPi. Still, ALL other formats does fine with that, only SAP-G fails. This is likely a problem with the format.

**Comment by kholia** [comment]
I can reproduce the problem on Fedora 27 running on x86-64 4xOMP hardware. The format tries to consume almost 2 GB of RAM.

**Comment by kholia** [comment]
I introduced this problem in my recent refactoring commits,

Here is a patch to fix this,

``` diff
diff --git a/src/sapG_fmt_plug.c b/src/sapG_fmt_plug.c
index f7e897106..c0cab1e8a 100644
--- a/src/sapG_fmt_plug.c
+++ b/src/sapG_fmt_plug.c
@@ -23,19 +23,6 @@ john_register_one(&fmt_sapG);
 #include <string.h>
 #include <ctype.h>
 
-#if defined(_OPENMP)
-#include <omp.h>
-#ifndef OMP_SCALE
-#if defined (SIMD_COEF_32)
-// Some OMP scaling moved into max_keys, so that we can have more values in SIMD
-// mode, to sort hashes by limb size.  (TODO)
-#define OMP_SCALE               128
-#else
-#define OMP_SCALE               2048
-#endif
-#endif
-#endif
-
 #include "arch.h"
 #ifdef SIMD_COEF_32
 #define NBKEYS                  (SIMD_COEF_32 * SIMD_PARA_SHA1)
@@ -48,6 +35,20 @@ john_register_one(&fmt_sapG);
 #include "options.h"
 #include "unicode.h"
 #include "johnswap.h"
+
+#if defined(_OPENMP)
+#include <omp.h>
+#ifndef OMP_SCALE
+#if defined (SIMD_COEF_32)
+// Some OMP scaling moved into max_keys, so that we can have more values in SIMD
+// mode, to sort hashes by limb size. (TODO)
+#define OMP_SCALE               128
+#else
+#define OMP_SCALE               2048
+#endif
+#endif
+#endif
+
 #include "memdbg.h"
 
 #define FORMAT_LABEL            "sapg"
```

I currently don't understand why this patch (essentially a revert of my changes) works.

**Comment by magnumripper** [comment]
> I currently don't understand why this patch (essentially a revert of my changes) works.

It bumps max keys per crypt (for SIMDx4 and OMPx8) from 256K to 4M because you test for SIMD_COEF_32 before sourcing arch.h that sets it (ie. you get `OMP_SCALE 128` instead of `OMP_SCALE 2048`).

I will fix it with less revertion.

**Comment by kholia** [comment]
I see. Thanks!
