### ISSUE TITLE
Add Fedora equivalent of INSTALL-UBUNTU doc

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3051]
This would be great, @kholia do you have some notes anywhere?

**Comment by magnumripper** [comment]
I added what I needed to build non-OpenCL on a RPi. We should add OpenCL with INSTALL-UBUNTU as a template.

**Comment by kholia** [comment]
I had no luck in getting OpenCL to work on Fedora 25 using the Fedora (or https://negativo17.org/nvidia-driver/) supplied NVIDIA rpm packages. After struggling for a bit, I gave up and installed Ubuntu on that machine.

**Comment by magnumripper** [comment]
Current docs will do for now.
