### ISSUE TITLE
New build warnings caused by recent "cleanups"

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3062]
```
krb5_db_fmt_plug.c:353:16: error: 'index' is used uninitialized in this function [-Werror=uninitialized]

   if (crypt_out[index][0] == *(uint32_t*)binary)

                ^
```
@kholia fix this and do check the bot logs for other problems.

**Comment by magnumripper** [comment]
@kholia forget that, I have a multitude of fixes for your fixes pending.

**Comment by kholia** [comment]
Thanks @magnumripper. My bad for missing/mangling many cases. Making bulk changes seems to be hard.

**Comment by magnumripper** [comment]
The hard part is the review 😉
