### ISSUE TITLE
Argon2 raw-blake and Tezos (all same code) fails on macOS with --disable-simd

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3079]
If I build with `--disable-simd`
**or** with `CFLAGS="-mno-mmx -mno-sse2 -g -O2"`
```
$ ../run/john -test=0 -form:@blake2
Will run 8 OpenMP threads
Testing: argon2 [Blake2]... (8xOMP) FAILED (cmp_all(1))

Testing: Raw-Blake2 [BLAKE2b 512 32/64]... FAILED (cmp_all(1))

2 out of 2 tests have FAILED
```

**Comment by magnumripper** [comment]
Running on super, both `--disable-simd` and `CFLAGS="-mno-sse2 -O2 -g"` results in a format that passes self-tests.

**Comment by magnumripper** [comment]
This works on macOS: `./configure CC=/usr/bin/gcc --disable-simd`. So the native macOS gcc (really a clang/llvm thing) doesn't have problems.

Thus the only compiler we know that trigger this problem is gcc version 7.2.0 (Homebrew's).

**Comment by magnumripper** [comment]
Homebrew's "gcc version 6.4.0" also has the problem.

**Comment by magnumripper** [comment]
Another parameter is clang doesn't have OpenMP... so perhaps the bug just hid under a stone when I build with the native compiler.

Testing...

Ok but the Homebrew gcc still fails when disabling OpenMP.

**Comment by magnumripper** [comment]
Building with Homebrew's "gcc version 5.5.0" also shows the bug. But I can't believe this is actually a gcc thing... something else must be "changing" when I build with native gcc.

**Comment by solardiz** [comment]
We might want to take care of #2738 (will this bring revised BLAKE2 code, too?) before looking into this issue.

**Comment by magnumripper** [comment]
I notice using `--disable-simd` on a RPi produces working formats. I suspect there's some `#if __SSEx__` things in there that lacks also checking for `JOHN_NO_SIMD`. I did look for that before but I'll do it again right now.

**Comment by solardiz** [comment]
Looks unrealistic we'll make relevant changes and properly re-test them on all platforms before the release. Changed milestone.

**Comment by magnumripper** [comment]
Hmm, per the earliest comments here, a missing `JOHN_NO_SIMD` wont be it. I think we'll just have #2738 fix this.
