### ISSUE TITLE
Change MD5_word to uint32_t

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#3103]
This is a core issue. It is currently in these files. I can not change dynamic without ugly typecasting until the core md5 stuff changes.

- [ ] MD5_std.h
- [ ] MD5_fmt.c
- [ ] MD5_std.c
- [x] PO_fmt_plug.c
- [x] dynamic_types.h
- [x] dynamic_fmt.c

**Comment by solardiz** [comment]
I don't understand why you need ugly typecasting. We currently have:

    typedef uint32_t MD5_word;

and we don't indent to change that (short of possibly getting rid of `MD5_word` entirely, as you suggest), so you can assume that if you have an `uint32_t` somewhere you can use it interchangeably with `MD5_word`.

**Comment by jfoug** [comment]
I have not looked into dyna.  It may be able to be done without any change, other than conversion of MD5_word into uint32_t.  I have not checked, but worry that warnings would start to appear.   The interface to MD5_std uses them, and I know dyna uses that.  This was the only reason I added the caveat to dynamic.

**Comment by solardiz** [comment]
With the typedef as it currently is, there should be no warnings from mixing these types arbitrarily.

**Comment by jfoug** [comment]
Ok, then I can easily make changes to dyna. I already checked in PO.  It did not use anything from MD5_std, just used the typedef.

**Comment by magnumripper** [comment]
So we can close this? I wouldn't want changes to the files that come from John proper unless really necessary.
