### ISSUE TITLE
Add support for MD5 CTX in our OpenCL code

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#3105]
It would be great to have a high-level OpenSSL-like API for computing MD5 digests in our OpenCL code.

This is similar to https://github.com/magnumripper/JohnTheRipper/issues/2801 and https://github.com/magnumripper/JohnTheRipper/issues/2788.

This code would be used by (1) GPG OpenCL kernel (2) SSPR OpenCL kernel (3) SNMPv3 OpenCL kernel.

@magnumripper Is this something you would be interested in? :-)

Thanks!

**Comment by magnumripper** [comment]
Easy as Pi
