### ISSUE TITLE
--mem-file-size=0 as documented in doc/OPTIONS is invalid

### ISSUE THREAD

**Issue by draeath** [magnumripper/JohnTheRipper#3106]
`--mem-file-size` seems to be intended to accept 0 as a special value, forcing JtR to attempt to load the word list into memory. This does not seem to actually work, instead merely resulting in the following error output:

`Invalid options combination or duplicate option: "--mem-file-size=0"`

I'm working around this by just tossing the wordlist in a tmpfs mount.

```
# didn't want the most recent handful of commits to bleeding-jump due to the build-bot errors
$ git --git-dir=JohnTheRipper/.git reflog
c216890 HEAD@{0}: checkout: moving from bleeding-jumbo to c216890b502a6bad0572785913b75d3fd953fa15
c3abb54 HEAD@{1}: clone: from https://github.com/magnumripper/JohnTheRipper.git

$ lsb_release --all
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:        7.4
Codename:       Maipo

$ JohnTheRipper/run/john --list=build-info
Version: 1.8.0.12-jumbo-1-bleeding-c216890 2018-01-09 16:38:00 +0100
Build: linux-gnu 64-bit x86_64 AVX AC MPI + OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX
$JOHN is JohnTheRipper/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.8.5
GNU libc version: 2.17 (loaded: 2.17)
Crypto library: OpenSSL
OpenSSL library version: 0100020bf
OpenSSL 1.0.2k-fips  26 Jan 2017
GMP library version: 6.0.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by draeath** [comment]
In actuality it doesn't seem to accept any value for this at all.

**Comment by frank-dittrich** [comment]
What was the exact command you tried?

**Comment by draeath** [comment]
`nice JohnTheRipper/run/john --session=foobar --mem-file-size=0 ./hashes.txt` - I also tried various positive numbers for the variable, and including a unit suffix.

The intent was to allow it to try the default sequence of single, wordlist (where the argument would presumably take affect), then incremental.

Does this argument only work when one explicitly specifies wordlist mode?

**Comment by magnumripper** [comment]
Yes, `--mem-file-size` is to be used with `--wordlist` and can't currently be used with batch mode. I'll consider changing that but the default is 2 GB so will be enough for most sane wordlists.

**Comment by magnumripper** [comment]
BTW I'm pretty sure you could change the definition of `WORDLIST_BUFFER_DEFAULT` in `params.h` to `0`, and rebuild. Then you'll have hard-coded unconditional memory loading.

**Comment by draeath** [comment]
Excellent!

If the system cannot satisfy the request, it'll fall back on mmap?

**Comment by magnumripper** [comment]
The documentation is slightly outdated: It will always mmap! The --mem-file-size nowadays merely adds some indexing, and only when rules are in use. The performance impact is thus only a fraction of what it was before we added mmap (several years ago).

**Comment by magnumripper** [comment]
And no, if you really said -mem-file-size=0 or changed params.h, it **will** add that index, even if it means swapping or running out of virtual memory and get slapped by the OOM watchdog.

**Comment by magnumripper** [comment]
> The --mem-file-size nowadays merely adds some indexing, and only when rules are in use.

I turns out I remembered that incorrectly: It doesn't merely add indexing but ready-to-use words in memory. So it's definitely faster than just mmap, but OTOH mmap by itself is a lot faster than the original code that just reads a line at a time from the file and rewinds the file for each rule.

Also, this memory buffer (not mmap alone) will do things like encoding conversions and other expensive stuff only once, and re-uses the result ever after.
