### ISSUE TITLE
Star Office is missing cracks

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#3111]
### IMPORTANT
I would say it is a JtR problem because it should handle the correct SHA implementation (new fixed files) plus the buggy one (legacy files). Anyway, I'm not sure yet.

* 3 days ago
```
form=sxc                          guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:sxc                      guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)
```
* Now
```
form=sxc                          guesses: 1080 -show=1080 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED1!!!  ret_val=0]
Exiting on error. The .pot file tst-.pot contains the found data
The command used to run this test was:
../run/john -ses=tst-  -pot=tst-.pot sxc_new_tst.in --wordlist=tst-pw-new-40.dic -form=sxc
and
../run/john -show   -pot=tst-.pot sxc_new_tst.in -form=sxc
```

**Comment by jfoug** [comment]
Yes, it is a bug in original modifications to the crypt_all in the star code. i spotted this a bit ago.

NOTE, I am dropping star, and merging the code into libre office.  It will properly handle both correct and buggy sha1 stuff when done.

**Comment by jfoug** [comment]
This has to do with password lengths.  Here is what I found:

sxc_new_tst.in has 60 blocks of same password.  6 of these are > 51 bytes long.  Thus there are 420 hashes that will not match.   1500-420 is 1080 the exact count we see.

NOTE, none of the hashes (generated wtih pass-gen.pl) would have triggered the buggy code.

**Comment by jfoug** [comment]
I will update jtrts.dat.  Especially since the sxc has now been merged into the odf format proper.
