### ISSUE TITLE
dmg-opencl poor scalability for old OS X dmg files (1000 iterations)

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3129]
dmg-opencl produces good speeds for recent OS X / macOS dmg files, which use dynamically tuned PBKDF2 iteration counts on the order of 100k. However, when faced with a dmg file from old OS X with only 1000 iterations, dmg-opencl running on a GPU results in high host CPU usage and shows speeds barely better than what the CPU dmg format achieves on the host CPU alone (e.g., 65k with dmg-opencl on super's Titan X vs. 39k on super's CPUs). Is this as expected for the current implementation, and can we improve it? I understand that we probably use 3DES/AES on host, but I'm surprised it's this heavy and slow - are we somehow processing large amounts of data there? Do we possibly have a bug?

**Comment by magnumripper** [comment]
Devices like Titan X are severly limited by CPU-side stuff at low iteration counts. Try commenting out the `hash_plugin_check_hash()` checks in `crypt_all()` and run with `--skip-self-tests`, then you'll see the speed we get when not CPU-bound.

Nowadays we do have shared code for GPU-side AES, but not 3DES. Are you aware of any open and fairly simple DES code I could adopt to GPU for use cases like this?

**Comment by solardiz** [comment]
You mean non-bitslice DES? I'd consider FreeSec, perhaps the revision of it that I made for musl (so look in the musl source tree), where I reduced its memory needs and IIRC Rich precomputed the tables so they can be in .rodata or .text (and perhaps in some kind of read-only/shared memory on an OpenCL device that has one). IIRC, we're not exporting the setkey/encrypt/decrypt interfaces in there, only exporting crypt(3), but they should be easy to expose for our OpenCL kernels' needs.

**Comment by solardiz** [comment]
For dmg specifically, does the 8 NUL's memset() really have to go over the entire buffer? Maybe we can decrypt just the few blocks where this pattern is actually expected? Of course, there's risk of us introducing false negatives when we make changes like this...

**Comment by magnumripper** [comment]
Another thought: If the first 8xNULL test hits, we set `ret = 1` but then we perform the "second buffer test" (if applicable) over another 4 KB instead of returning immediately. Changing that wouldn't even affect false negatives.

**Comment by magnumripper** [comment]
> Also, is the 8 NUL's pattern possibly necessarily aligned to some boundary?

I think we usually see a lot more than 8 of them so we may be able to look for them in our native alignment. If we try to do this on GPU-side, this would make a whole lot of difference.

> Of course, there's risk of us introducing false negatives when we make changes like this...

Yes, that's a problem. I wish we could find a safer *and* faster way.

**Comment by magnumripper** [comment]
> Another thought: If the first 8xNULL test hits, we set ret = 1 but then we perform the "second buffer test" (if applicable) over another 4 KB instead of returning immediately. Changing that wouldn't even affect false negatives.

This obviously wouldn't speed up negatives though, which is what we need to do of course. But I wonder if we could do with just checking one of those buffers (eg. the smaller one if present).

**Comment by magnumripper** [comment]
For what it's worth I tried replacing the `memmem()` calls with a function that searches for a single `(uint64_t)0` on 64-bit aligned boundaries and all samples I have still worked with that. It was obviously faster but we also need the 3DES, HMAC and AES to be GPU-side.

The 8 NUL's are usually much more than 8, but they're often in only one of the two buffers (not always the same one) and they are found at totally different offsets. I see no way to narrow it down more.

**Comment by magnumripper** [comment]
This was changed:
- All work now on GPU, and OpenMP dropped from the format.
- `memmem()` check was replaced with searching for "two aligned (uint32)0's in a row".

Current DES code is from "mbed TLS". I seem to fail miserably at implementing 3DES CBC functions based on musl. I have no idea why I never understood DES at all, but it seems to stick. @solardiz if you give me a push in some direction, I can revisit that - otherwise I'm more than happy for now.
