### ISSUE TITLE
Error, Invalid signature line trying to link to dynamic format

### ISSUE THREAD

**Issue by Womoba** [magnumripper/JohnTheRipper#3133]
Dear developers,
I meet an error already reported in #1518 with the very last version from git:

     john --make_check
     [...]
     Error, Invalid signature line trying to link to dynamic format.
     Original format=as400-ssha1
     Signature line=$dynamic_1590$4C106E52CA196986E1C52C7FCD02AF046B76C73C$HEX$0052004f00420020002000200020002000200020

but I meet the same error when I try to use a simple --conf from a lg.conf file:

     [Incremental:Custom]
     MinLen = 10
     MaxLen = 10
     File = $JOHN/ascii.chr

     john --conf=lg.conf --incremental=Custom mypasswd

Return me exactly the same error.
I compiled the last git today, I use CUDA and openmp under linux (debian).
Thanks

**Comment by magnumripper** [comment]
Your config file is not complete. Either copy the original `john.conf` to `lg.conf` and then make your edits as needed. Or rename `lg.conf` to `john-local.conf` and drop the `--conf` option from your command line.

**Comment by Womoba** [comment]
ok, sorry for the naive question. It worked on an other computer (without opencl) so I thought it was this.
Thanks, it works as expected now.
