### ISSUE TITLE
OpenCL: Check for/mitigate regressions for single-block AES

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3142]
KeePass format sets a key, then encrypts eg. 192 KB or 1.6 MB of data. The new AES code sped it up significantly but this probably came at the price of being slower for "set a key, decrypt a single block". I need to verify that and put back alternate code if needed.

Formats possibly affected: 7z-opencl, agilekeychain-opencl, bitwarden-opencl, enpass-opencl, ethereum-presale-opencl, fvde-opencl, iwork-opencl, o5logon-opencl, odf-aes-opencl and office-opencl.

**Comment by solardiz** [comment]
Why does the KeePass format encrypt(?) so much data? If it's CBC mode, can't we focus on just the few blocks where we expect anything non-random?

**Comment by magnumripper** [comment]
It's actually just 32 bytes, but iterated 6,000 or 50,000 times. It looks like a run-of-the-mill KDF except is uses AES ECB instead of a hash function.
```c
        // First, hash the masterkey
        SHA256_Init(&ctx);
        SHA256_Update(&ctx, masterkey, strlen(masterkey));
        SHA256_Final(hash, &ctx);

        if (csp->version == 2 && cur_salt->have_keyfile == 0) {
                SHA256_Init(&ctx);
                SHA256_Update(&ctx, hash, 32);
                SHA256_Final(hash, &ctx);
        }

        if (cur_salt->have_keyfile) {
                SHA256_Init(&ctx);
                SHA256_Update(&ctx, hash, 32);
                SHA256_Update(&ctx, cur_salt->keyfile, 32);
                SHA256_Final(hash, &ctx);
        }

        // Next, encrypt the created hash
        AES_set_encrypt_key(csp->transf_randomseed, 256, &akey);
        i = csp->key_transf_rounds;
        while (i--) {
                AES_encrypt(hash, hash, &akey);
                AES_encrypt(hash+16, hash+16, &akey);
        }
(...)
```
`masterkey` is our password candidate. Unfortunately a random seed is used as well, so many-salts are no better.

**Comment by solardiz** [comment]
Do we really need to produce all 32 bytes of the hash from that custom AES ECB KDF? It could produce 16 bytes twice faster. And if we do need the 32 bytes, we could maybe take advantage of the 2x parallelism here (tricky) to achieve same speed with twice lower GWS and lower memory usage.

**Comment by magnumripper** [comment]
Yeah we have to, the output from the AES loop is fed into SHA256 and so on.

OTOH the new OpenCL AES code apparently does two blocks in parallel without me doing any tricky stuff myself. They call it a "bitsliced" constant-time implementation, their quotes, I don't quite understand it but it sure is fast compared to the old one.

**Comment by magnumripper** [comment]
There is no problem: O5Logon (which only does a single SHA-1 and a single block of AES CBC) apparently got 6-7x faster with the new AES code. ODF-AES (which decrypts 1024 bytes) got 2x faster. The other formats had no significant difference - it's an unsignificant part of total time.

Looks like we don't have to care about the older AES code at all :)

On another note, o5logon would benefit a whole lot from GPU-side mask. I'll open an issue for that.
