### ISSUE TITLE
Add support for cracking Monero wallets

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#3144]
References,

* https://github.com/monero-project/monero.git (`verify_password` from `wallet2.cpp`)

* https://getmonero.org/downloads/

* https://github.com/monero-project/monero/blob/master/src/crypto/slow-hash.c

* https://github.com/lucasjones/testnotecoin/blob/master/src/crypto/slow-hash.c (without intrinsics stuff)

**Comment by kholia** [comment]
Monero wallet in action,

```
$ ./monero-wallet-cli 
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to ./monero-wallet-cli.log
Specify wallet file name (e.g., MyWallet). If the wallet doesn't exist, it will be created.
Wallet file name (or Ctrl-C to quit): test
No wallet found with that name. Confirm creation of new wallet named: test
(Y/Yes/N/No): Y
Generating new wallet...
Enter new wallet password: ********
Confirm Password: ********
List of available languages for your wallet's seed:
0 : Deutsch
1 : English
2 : Español
3 : Français
4 : Italiano
5 : Nederlands
6 : Português
7 : русский язык
8 : 日本語
9 : 简体中文 (中国)
10 : Esperanto
Enter the number corresponding to the language of your choice: 1
Generated new wallet: 44wWRqAhpiNYhWqFR1eB...
View key: b40be0ad2827575dca93d2d273...
**********************************************************************
Your wallet has been generated!
To start synchronizing with the daemon, use "refresh" command.
Use "help" command to see the list of available commands.
Always use "exit" command when closing monero-wallet-cli to save your
current session's state. Otherwise, you might need to synchronize 
your wallet again (your wallet keys are NOT at risk in any case).


PLEASE NOTE: the following 25 words can be used to recover access to your wallet. Please write them down and store them somewhere safe and secure. Please do not store them in your email or on file storage services outside of your immediate control.

neon madness sadness metro cousin reruns already knowledge
apricot wonders amaze lullaby velvet dusted hunter reorder
dauntless jostle sincerely unquoted threaten bobsled equip folding already
**********************************************************************
```

**Comment by kholia** [comment]
The KDF seems to be quite slow, and annoying to implement. Look at `cn_slow_hash` function in `src/crypto/slow-hash.c` file.

**Comment by kholia** [comment]
This KDF originally comes from CryptoNote progject, and is also used by Karbowanec Wallet (https://github.com/seredat/karbowanecwallet). Thanks @Chick3nman for finding this out.

**Comment by kholia** [comment]
Implementing this may require us to add the `OpenAES` library (2 files) to our code base.

See `oaes_pseudo_encrypt_ecb` from the following URL,
https://github.com/lucasjones/testnotecoin/blob/master/src/crypto/oaes_lib.c.

@magnumripper Do we know if we can emulate this `oaes_pseudo_encrypt_ecb` function using AES from OpenSSL? I am guessing not.

**Comment by magnumripper** [comment]
I have no idea. I guess the real question is "why is it called 'pseudo'"?

**Comment by magnumripper** [comment]
updated

**Comment by kholia** [comment]
In https://github.com/lucasjones/testnotecoin/blob/master/src/crypto/oaes_lib.c,

The `oaes_encrypt_block` (regular ECB I think) differs quite a bit from the `oaes_pseudo_encrypt_ecb` function. So, I don't think that using the regular ECB decryption code from OpenSSL will work.

**Comment by kholia** [comment]
Thanks @Chick3nman.

I am also in the process of reusing this code for cracking https://github.com/seredat/karbowanecwallet. Writing `karbowanec2john.py` will require some code reading as the wallet format seems to be different than the Monero one.

**Comment by Chick3nman** [comment]
I believe karbowanec is actually closer to the core CryptoNote than Monero(CryptoNight) so it should apply to other CryptoNote wallets a little better. It took me a while to read through it though to figure out if they were applying the same SlowHash to the wallet password. SlowHash is used in the actual mining for these currencies, so the wallet KDF can be whatever they want if they decide to roll their own.

**Comment by kholia** [comment]
@magnumripper Is this PR good enough to merge? I don't like it much but that is how it is ;(

**Comment by solardiz** [comment]
See also #5668
