### ISSUE TITLE
2 bugs with --mask

### ISSUE THREAD

**Issue by rofl0r** [magnumripper/JohnTheRipper#3149]
```
prompt$ /share/john/run/john --mask='ABCDEFGHIJK?d?d?d?d?d?d' --fork=8 --session=foo foo.key
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk, WPA/WPA2 PSK [PBKDF2-SHA1 256/256 AVX2 8x])
Node numbers 1-8 of 8 (fork)
Note: minimum length forced to 8
Press 'q' or Ctrl-C to abort, almost any other key for status
Insufficient work. Cannot distribute work among nodes!
prompt$ 8 0g 0:00:00:00  (13) 0g/s 0p/s 0c/s 0C/s
```
< at this point, a single john process is forked into background, and it tries all sorts of different lengths>

1) wpapsk sets --min-length, it causes --mask to iterate lengths even when --min-length --max-length were not specified at all

2) --mask with fixed part not shorter than specified by --min-length causes john to fork into background

**Comment by magnumripper** [comment]
A likely related bug: Recently I ran `-mask:?d -min-len=8 -fork=8` on something, and it ran just fine (started at length 8 and incrementing). Then I ran `-mask=?h -min-len=8 -fork=8` (?h is hex digits) but that one errored out with the dreaded `Insufficient work. Cannot distribute work among nodes!`. After some silly amount of brute-forcing arguments I found out that adding eg. `-max-len=12` made it work again. Not very intuitive.

**Comment by magnumripper** [comment]
@rofl0r I think it's all fixed now (and several other quirks gone too). Please re-open if you still see problems.

**Comment by rofl0r** [comment]
i can confirm it fixed :+1:
thanks for the great support!

**Comment by magnumripper** [comment]
Thanks for pushing me to finally fix these silly issues. I should have fixed them long ago!
