### ISSUE TITLE
I cannot locate zip2john, it seems to be missing.

### ISSUE THREAD

**Issue by RedTurtle77** [magnumripper/JohnTheRipper#3153]
### IMPORTANT
- If you have questions, please ask them first in the mailing list john-users at lists.openwall.com;
- Use issues to keep track of ideas, enhancements, tasks, and bugs. NEVER as a support forum;
- Please, DO NOT create a new issue if your bug is already known:
  - OpenCL known issues #2331.
  - CUDA support is dropped from tree now. Do not post issues about that.

### Steps to reproduce
Try to be clear about your environment and what you are doing. If possible, share with us the file or hash you are auditing.

### System configuration
Attach details about your OS and about JtR, including (please, adjust the path to the john binary accordingly):
- are you using bleeding-jumbo? Updated?
- `$ ../run/john --list=build-info`.
- `$ ../run/john --list=opencl-devices` (if applicable).

**Comment by magnumripper** [comment]
This is a bug tracker, not a helpdesk. You should probably look at http://www.openwall.com/john/ instead of GitHub. Perhaps http://openwall.info/wiki/john/custom-builds is more specific.
