### ISSUE TITLE
sshng2john and john don't support AES-192 or AES-256 PEM (PKCS#5) files

### ISSUE THREAD

**Issue by wdormann** [magnumripper/JohnTheRipper#3157]
### Steps to reproduce

sshng2john supports AES-128 RSA PKCS5 PEM files.   However, it doesn't support AES-192 or AES-256 versions of the same kind of file.   I tried modifying sshng2john.py to support AES-192 by adding a line to the CIPHER_TABLE with the appropriate key properties, and by fiddling with the case statement near the end to support both.

And while it was able to generate john hash output for both cases, john wasn't able to crack either.  Looking at the ssh_ng_fmt_plug.c code, it appears that it only can handle AES-128 RSA keys.  Attached are 3 RSA PEM files with key lengths of 128, 192, and 256.  All 3 have the password of "password"

Only the 128-bit one seems to work with john and its converter.

[test128.pem.txt](https://github.com/magnumripper/JohnTheRipper/files/1725375/test128.pem.txt)
[test192.pem.txt](https://github.com/magnumripper/JohnTheRipper/files/1725376/test192.pem.txt)
[test256.pem.txt](https://github.com/magnumripper/JohnTheRipper/files/1725377/test256.pem.txt)

**Comment by kholia** [comment]
Thanks @wdormann for this excellent report! I will try to fix this soon.

**Comment by kholia** [comment]
Here is how I am planning to fix this,

``` diff
diff --git a/run/sshng2john.py b/run/sshng2john.py
index ebc18b5db..310ea4f38 100755
--- a/run/sshng2john.py
+++ b/run/sshng2john.py
@@ -36,6 +36,7 @@ CIPHER_TABLE = {
     'AES-128-CBC': {'cipher': AES, 'keysize': 16, 'blocksize': 16, 'mode': "AES.MODE_CBC"},
     'DES-EDE3-CBC': {'cipher': DES3, 'keysize': 24, 'blocksize': 8, 'mode': "DES3.MODE_CBC"},
     'AES-256-CBC': {'cipher': AES_256, 'keysize': 32, 'blocksize': 16, 'mode': "AES.MODE_CBC"},
+    'AES-192-CBC': {'cipher': AES, 'keysize': 24, 'blocksize': 16, 'mode': "AES.MODE_CBC"},
 }
 
 
@@ -158,7 +159,10 @@ def read_private_key(filename):
             rounds == 16
 
     data = binascii.hexlify(data).decode("ascii")
-    if keysize == 24:
+    if keysize == 24 and encryption_type == "AES-192-CBC" and (ktype == 0 or ktype == 1):  # RSA, DSA keys using AES-192
+        hashline = "%s:$sshng$%s$%s$%s$%s$%s" % (f.name, 4, len(saltstr) // 2,
+            saltstr, len(data) // 2, data)
+    elif keysize == 24:
         hashline = "%s:$sshng$%s$%s$%s$%s$%s" % (f.name, 0,  # 0 -> 3DES
             len(salt), saltstr, len(data) // 2, data)
     elif keysize == 16 and (ktype == 0 or ktype == 1):  # RSA, DSA keys using AES-128
```

1. The code in `ssh_ng_fmt_plug.c` would need to be refactored.

2. We may need to recommission `generate_key_bytes` for handling AES-256-CBC mode.

**Comment by kholia** [comment]
I guess the handling of EC keys will need to be extended too. I think we may have to restrict ourselves to supporting only the common type+cipher combinations?

**Comment by kholia** [comment]
@wdormann This issue should be fixed now. Please let us know if you find other such issues. Thanks!

**Comment by wdormann** [comment]
Yeah, I tested your patch when you first posted it in #3159.  Works great...thanks!

I've got a pretty large pile of keys, so I suspect there may be others that fall into a similar boat.

**Comment by kholia** [comment]
Nice.

Please feel free to open new issue(s) as required :+1:
