### ISSUE TITLE
Make output length configurable in PBKDF2-SHA256 OpenCL kernel

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#3172]
See https://github.com/magnumripper/JohnTheRipper/pull/3171 for details.

To summarize,

* We need `OUTLEN` functionality in `pbkdf2_hmac_sha256_kernel.cl`

* The `ansible` format requires a 64-byte key

* Support for generating up to 80 bytes of output would be great

**Comment by magnumripper** [comment]
Done. Should now work similar to PPKDF2-HMAC-SHA1: Define MAX_OUTLEN to max used length and then set `salt->outlen` to current length, in `set_salt()`.

Note that in order to get more than 32 bytes of output, the host code need to be changed, from:
```c
	for (i = 0; i < (ocl_autotune_running ? 1 : loops); i++) {
		BENCH_CLERROR(clEnqueueNDRangeKernel(queue[gpu_id], split_kernel,
			1, NULL, &global_work_size, lws, 0, NULL,
			multi_profilingEvent[2]), "Run split kernel");
		BENCH_CLERROR(clFinish(queue[gpu_id]), "clFinish");
		opencl_process_event();
	}
	BENCH_CLERROR(clEnqueueNDRangeKernel(queue[gpu_id], final_kernel,
		1, NULL, &global_work_size, lws, 0, NULL,
		multi_profilingEvent[3]), "Run final kernel");
```

To something like this:
```c
	for (j = 0; j < (ocl_autotune_running ? 1 : (currentsalt.outlen + 31) / 32); j++) {
		for (i = 0; i < (ocl_autotune_running ? 1 : loops); i++) {
			BENCH_CLERROR(clEnqueueNDRangeKernel(queue[gpu_id], split_kernel,
				1, NULL, &global_work_size, lws, 0, NULL,
				multi_profilingEvent[2]), "Run split kernel");
			BENCH_CLERROR(clFinish(queue[gpu_id]), "Error running loop kernel");
			opencl_process_event();
		}

		BENCH_CLERROR(clEnqueueNDRangeKernel(queue[gpu_id], final_kernel,
			1, NULL, &global_work_size, lws, 0, NULL,
			multi_profilingEvent[3]), "Run final kernel");
	}
```

**Comment by magnumripper** [comment]
BTW for an actual max. length of 80 you should set MAX_OUTLEN to 96, eg. a multiple of 32. We could change the code to handle 80 as well but it won't be any faster.

**Comment by kholia** [comment]
Thanks @magnumripper :+1: 

In the current cracking method we are using, we don't require 80 bytes of output. We should be good with 64 bytes of PBKDF2 output, and we only use the last 32 bytes from those 64 bytes.

**Comment by magnumripper** [comment]
> we only use the last 32 bytes from those 64 bytes

So we should add and use "skip bytes" code in this kernel, for a 2x boost!
