### ISSUE TITLE
storage size of 'pk' isn't known

### ISSUE THREAD

**Issue by sebix** [magnumripper/JohnTheRipper#3186]
I get this error during compilation:
```
[  111s] gcc -c -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DJOHN_SYSTEMWIDE=1 -funroll-loops ssh2john.c -o ssh2john.o
[  111s] ssh2john.c: In function 'process_file':
[  111s] ssh2john.c:51:11: error: storage size of 'pk' isn't known
[  111s]   EVP_PKEY pk;
[  111s]            ^~
```

### Steps to reproduce
Building john 1.8.0 with jumbo 1 on openSUSE Tumbleweed

### System configuration
Full build log with all installed library versions is attached at [buildlog.txt](https://github.com/magnumripper/JohnTheRipper/files/1778847/buildlog.txt)

**Comment by magnumripper** [comment]
You can't report a bug here unless you actually used sources from here, it doesn't make sense.

**Comment by sebix** [comment]
> You can't report a bug here unless you actually used sources from here, it doesn't make sense.

The used sources are http://www.openwall.com/john/j/john-1.8.0.tar.xz and and http://openwall.com/john/j/john-1.8.0-jumbo-1.tar.xz

Is there a bugtracker for the downloads on openwall.com? Isn't the version provided here on github the same as on openwall.com?

**Comment by magnumripper** [comment]
> Isn't the version provided here on github the same as on openwall.com?

Well it was, years ago. As written in head line of [this repo's home page](https://github.com/magnumripper/JohnTheRipper): "The 'bleeding-jumbo' branch (default) is based on 1.8.0-Jumbo-1 (but we are literally several thousands of commits ahead of it)."

**Comment by sebix** [comment]
And is 1.8.0-Jumbo-1 is still the last (stable) release?

**Comment by magnumripper** [comment]
Unfortunately yes. Technically, I don't do releases - Openwall does. When that happens, I volunteer with lots and lots of time for systematic testing and bug fixing. Right now we don't have enough other people that do so, so we can't get to a "stable release" point.

Personally I regard latest code from here good enough to use though, and way way better than latest release. Try it!

**Comment by magnumripper** [comment]
@solardiz perhaps we should ditch the whole idea of releasing Jumbos? Just move the 1.8.0-jumbo-1 files to some archive and instead point to here with some words of caution. Most of the time we're pretty stable, but sometimes we're not.

**Comment by solardiz** [comment]
@magnumripper No, I think we should continue with the releases, and we should try to make one real soon. They serve some valid purposes and are not that hard to make, and the work on stabilizing the tree prior to a release is desirable anyway. We currently have some GitHub issues targeting milestone 1.8.0-jumbo-2 - we should try and take care of some of them now, and give up on or postpone the rest. (The actual release number should be 1.8.1-jumbo-1. I'll release 1.8.1 core just in time for that. But I want jumbo to be ready first.)
