### ISSUE TITLE
!John The Riper Github "Hybrid mask mode Bug" mask is arbitrarily lengthened.!

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#3189]
#In the hybrid mask mode, I can not control the mask. In the pre-installed version of Kali Linux or Parrot, there is no such error. Below are examples of a mask error

**John The Riper Github**
Hybrid mask mode EROR
file.txt (password)

john --wordlist=file.txt --format=wpapsk ~hash --mask=?w1
output to terminal password11111111

john --wordlist=file.txt --format=wpapsk ~hash --mask=?w
output to terminal password

john --wordlist=file.txt --format=wpapsk ~hash --mask=?w?1
output to terminal >rdfGQeaaaaa

john --wordlist=file.txt --format=wpapsk ~hash --mask=?w?d
output to terminal >rd00000000..rd99999999
john --wordlist=file.txt --format=wpapsk ~hash --mask=?d?d?d?d?d?d?d?d?d?d
Will run 2 OpenMP threads
Note: minimum length forced to 8
Hybrid mask must contain ?w or ?W

john --wordlist=file.txt --format=wpapsk ~hash --mask=?d?w
output to terminal 0passwordwwwwwww..9passwordwwwwwww

john --wordlist=file.txt --format=wpapsk ~hash --mask=?d?d?d?w
output to terminal 000passwordwwwww..999passwordwwwww

john --wordlist=file.txt --format=wpapsk ~hash -1=er --mask=?w?1
output to terminal passwordeeeeeeee..passwordrrrrrrrr..

**John The Riper Preinstalled version**
KALI LINUX,  Parrot
Hybrid mask mode OK
file.txt (password)

john --wordlist=file.txt --format=wpapsk ~hash --mask=?w1
output to terminal password1

john --wordlist=file.txt --format=wpapsk ~hash  --mask=?w?1
output to terminal passworda. passwordz

john --wordlist=file.txt --format=wpapsk ~hash --mask=?w?d
output to terminal password0..password9

john --wordlist=file.txt --format=wpapsk ~hash --mask=?d?w
output to terminal 0password..9password

**Comment by magnumripper** [comment]
This is already fixed. Reporting bugs in old versions is just a waste of our time, as well as yours.

**Comment by magnumripper** [comment]
I'm sorry, you are right! This will be fixed soon.

**Comment by magnumripper** [comment]
Fixed now, thanks for reporting!

**Comment by torerobo** [comment]
Yes, thank you fixed. Works properly.
