### ISSUE TITLE
Ethereum Presale OpenCL kernel needs to be rewritten (trivial)

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3215]
I noticed now that ethereum_presale_kernel.cl is a **copy** of an older pbkdf2-hmac-sha256 kernel, with stuff added. This must be fixed - the correct way is **sourcing** the pbkdf2 kernel like is done in many other formats (eg. ansible_kernel.cl). Otherwise any future enhancements and/or bug fixes to the pbkdf2 kernel probably wont propagate.

**Comment by kholia** [comment]
Sorry about this. I don't remember why I did this though :-|
