### ISSUE TITLE
Poor GPU utilization

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3216]
After my recent tweaks for GPU utilization output from `--test`, the following formats begs for attention (less than 90%, running single-thread in case of OMP):
```
(original list removed)
```
Good formats are very close to 100% (although a figure close to 100% does not guarantee everything is fine - the format may be compute bound and still poor). We have 77 GPU formats in total and the above list is ~~16~~ of them.

Really bad formats are not even showing a "GPU util" figure, because of close to 0% utilization due to **lots** of post-processing on CPU. They should really be fixed where possible.

Note that many of these formats may seem to perform well (just looking at GPU util) if supported by multi-threaded host side. But we should avoid host-side processing where at all possible.

**Comment by magnumripper** [comment]
I really thought BitLocker-opencl would do better, as @e-ago put some dedicated effort to it. Apparently there's things to do there!

**Comment by claudioandre** [comment]
> I really thought BitLocker-opencl would do better, as @e-ago put some dedicated effort to it. Apparently there's things to do there!

Please, remember that you need to pick GWS to test BitLocker-opencl properly (autotune figure does not hide latencies).

> Note though that ALL of the above figures can be taken with a grain of salt. We don't quite know what exactly is measured - and occasionally the figures read lower than otherwise for no particular reason (and AMD figures tend to be much less accurate IIRC).

You can use the manufacturer's tools, if you are in the mood. I, personally, think it is not necessary for what you are doing.

**Comment by claudioandre** [comment]
> Good formats are very close to 100% (although a figure close to 100% does not guarantee everything is fine - the format may be compute bound and still bad)

Very fast formats are hard to get 100% (you need to find the right mask, because a mere ?d?d?d is not able to produce the amount of needed keys).

Anyway, it is not hard to change the mask to get an improvement (even if you are "only" at 86%).

**Comment by magnumripper** [comment]
>> I really thought BitLocker-opencl would do better, as @e-ago put some dedicated effort to it. Apparently there's things to do there!
>
> Please, remember that you need to pick GWS to test BitLocker-opencl properly (autotune figure does not hide latencies).

True, I forgot that. I think hashcat is able to do way longer "total crypt durations" without the user noticing a difference.

**Comment by magnumripper** [comment]
Previous figure from above (as in bleeding-jumbo: Max. 10 seconds total `crypt_all()`):
```
Benchmarking: BitLocker-opencl, BitLocker [SHA256 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 500
Raw:	22861 c/s real, 21005 c/s virtual, GPU util: 69%
```

Figure with just a limit on single-call duration of 200ms (takes ages to complete):
```
$ ../run/john -test -form:bitlocker-opencl 
Device 6: GeForce GTX TITAN X
Benchmarking: BitLocker-opencl, BitLocker [SHA256 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 500
Raw:	521968 c/s real, 491520 c/s virtual, GPU util: 65%
```

Same (single-call 200ms) but with HASH_LOOPS lowered from 256 to 64:
```
$ make -sj4 && ../run/john -test -form:bitlocker-opencl 

Make process completed.
../run/john: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ../run/john)
Device 6: GeForce GTX TITAN X
Benchmarking: BitLocker-opencl, BitLocker [SHA256 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 500
Raw:	1344K c/s real, 1310K c/s virtual, GPU util: 99%
```
Now we're talking speed - and utilization. This is a limitation of JtR, not Elena's format. I'm removing it from the list above.

**Comment by claudioandre** [comment]
Ok, but have you committed using the best tuned value of HASH_LOOPS?

The `--test` wil be always a problem, but on a real run, we can improve things inside crypt_all() to quit fast, if needed.

**Comment by magnumripper** [comment]
Dashlane and EncFS were apparently false positives, I get 99% now. And PGP-SDA and ZIP also show over 90%. Removing them. Also removed Raw-SHA512-free since it has a faster alternative anyway.

The WPAPSK-PMK format simply needs internal mask. Added it to #1845.

**Comment by magnumripper** [comment]
krb5pa-sha1 fixed. Old figures (deleted from above):
```
Benchmarking: krb5pa-sha1-opencl, Kerberos 5 AS-REQ Pre-Auth etype 17/18 [PBKDF2-SHA1 OpenCL]... DONE
Raw:	179550 c/s real, 180374 c/s virtual
```

New figures:
```
Benchmarking: krb5pa-sha1-opencl, Kerberos 5 AS-REQ Pre-Auth etype 17/18 [PBKDF2-SHA1 OpenCL]... DONE
Raw:	289129 c/s real, 289129 c/s virtual, GPU util: 99%
```

...and for etype 17 (unrelated bugfix, we produced an unneeded amount of key length)
```
Benchmarking: krb5pa-sha1-opencl, Kerberos 5 AS-REQ Pre-Auth etype 17/18 [PBKDF2-SHA1 OpenCL]... DONE
Raw:	569878 c/s real, 569878 c/s virtual, GPU util: 99%
```

**Comment by magnumripper** [comment]
GELI-opencl fixed. Significant speedup, before:
```
Benchmarking: geli-opencl, FreeBSD GELI [PBKDF2-SHA512 OpenCL AES]... DONE
Speed for cost 1 (iteration count) of 256 and 512
Raw:	78329 c/s real, 77710 c/s virtual
```
After:
```
Benchmarking: geli-opencl, FreeBSD GELI [PBKDF2-SHA512 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 256 and 512
Raw:	378092 c/s real, 375206 c/s virtual, GPU util: 99%
```

**Comment by magnumripper** [comment]
PEM-opencl fixed. Before (removed from above):
```
Benchmarking: pem-opencl, PKCS#8 private key (RSA/DSA/ECDSA) [PBKDF2-SHA1 OpenCL 3DES]... DONE
Speed for cost 1 (iteration count) of 4096 and 4098
Warning: "Many salts" test limited: 2/256
Many salts:	24212 c/s real, 24212 c/s virtual
Only one salt:	34292 c/s real, 34292 c/s virtual
```

After:
```
Benchmarking: pem-opencl, PKCS#8 private key (RSA/DSA/ECDSA) [PBKDF2-SHA1 3DES OpenCL]... DONE
Speed for cost 1 (iteration count) of 4096 and 4098
Raw:	307200 c/s real, 307200 c/s virtual, GPU util: 99%
```

**Comment by magnumripper** [comment]
ODF fixed. Blowfish and a few SHA-1's moved to GPU. Before (deleted from above):
```
Benchmarking: ODF-opencl, OpenDocument + LibreOffice [SHA1 OpenCL Blowfish]... DONE
Speed for cost 1 (iteration count) of 1024
Raw:	20739 c/s real, 20739 c/s virtual
```

After:
```
Benchmarking: ODF-opencl, OpenDocument Star/Libre/OpenOffice [PBKDF2-SHA1 BF/AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 1024, cost 2 (crypto [0=Blowfish, 1=AES]) of 0
Raw:	73728 c/s real, 72998 c/s virtual, GPU util: 99%
```
Blowfish key setup is pretty GPU unfriendly. On CPU it's much faster than AES, on GPU it's the other way round.

**Comment by magnumripper** [comment]
Blockchain fixed and removed from above. Before:
```
Device 6: GeForce GTX TITAN X
Benchmarking: blockchain-opencl, blockchain My Wallet [PBKDF2-SHA1 OpenCL AES]... DONE
Raw:	1622K c/s real, 1559K c/s virtual, GPU util: 5%
```

After (this with GPU concurrently loaded by hashcat - I'll post a new figure later):
```
Device 6: GeForce GTX TITAN X
Benchmarking: blockchain-opencl, blockchain My Wallet [PBKDF2-SHA1 AES OpenCL]... DONE
Raw:	7347K c/s real, 7274K c/s virtual, GPU util: 99%
```

**Comment by magnumripper** [comment]
Keychain fixed. Before:
```
Benchmarking: keychain-opencl, Mac OS X Keychain [PBKDF2-SHA1 OpenCL 3DES]... DONE
Raw:	293444 c/s real, 290553 c/s virtual, GPU util: 25%
```

After (this with GPU concurrently loaded by hashcat - I'll post a new figure later):
```
Benchmarking: keychain-opencl, Mac OS X Keychain [PBKDF2-SHA1 3DES OpenCL]... DONE
Raw:	823296 c/s real, 807152 c/s virtual, GPU util: 99%
```

**Comment by magnumripper** [comment]
STRIP fixed. A little AES-CBC and verifying moved to GPU. Before:
```
Benchmarking: strip-opencl, STRIP Password Manager [PBKDF2-SHA1 OpenCL]... DONE
Raw:	250650 c/s real, 245760 c/s virtual, GPU util: 86%
```

After (this with GPU concurrently loaded by hashcat - I'll post a new figure later):
```
Benchmarking: strip-opencl, STRIP Password Manager [PBKDF2-SHA1 AES OpenCL]... DONE
Raw:	258694 c/s real, 256445 c/s virtual, GPU util: 100%
```
Not a huge boost but we're now leaving all CPU cores at rest for better use.

**Comment by magnumripper** [comment]
For GPG, duh, I'd need to implement IDEA, CAST5 and Camellia on GPU. Hmm and bignum? Not gonna happen soon.

**Comment by magnumripper** [comment]
Lastpass formats fixed. Before:
```
Benchmarking: lp-opencl, LastPass offline [PBKDF2-SHA256 OpenCL AES]... DONE
Speed for cost 1 (iteration count) of 500
Raw:	1097K c/s real, 1066K c/s virtual, GPU util: 63%

Benchmarking: lpcli-opencl, LastPass CLI [PBKDF2-SHA256 OpenCL AES]... DONE
Speed for cost 1 (iteration count) of 1234
Raw:	559651 c/s real, 548784 c/s virtual, GPU util: 81%
```

After (this with GPU concurrently loaded by hashcat - I'll post a new figure later):
```
Benchmarking: lp-opencl, LastPass offline [PBKDF2-SHA256 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 500
Raw:	1196K c/s real, 1186K c/s virtual, GPU util: 99%

Benchmarking: lpcli-opencl, LastPass CLI [PBKDF2-SHA256 AES OpenCL]... DONE
Speed for cost 1 (iteration count) of 1234
Raw:	481882 c/s real, 468114 c/s virtual, GPU util: 99%
```

**Comment by magnumripper** [comment]
Phpass overhauled. It had a fixed vector width of 8, which is not often optimal. It allso had severly limited max candidate length. Before:
```
Benchmarking: phpass-opencl ($P$9 lengths 0 to 15) [MD5 OpenCL]... DONE
Speed for cost 1 (iteration count) of 2048
Raw:	3423K c/s real, 2752K c/s virtual, GPU util: 88%
```

After (now using device-preferred width, max length bumped more than 2x and a few optimizations):
```
(GPU occupied, will post later):
```

**Comment by magnumripper** [comment]
This is the only one left right now and it's "impossible" to fix. Closing issue.
```
Benchmarking: gpg-opencl, OpenPGP / GnuPG Secret Key [SHA1/SHA2 OpenCL]... DONE
Speed for cost 1 (s2k-count) of 65536, cost 2 (hash algorithm [2:SHA1 8:SHA256 10:SHA512]) of 2, cost 3 (cipher algorithm [1:IDEA 2:3DES 3:CAST5 4:Blowfish 7:AES128 8:AES192 9:AES256 10:Twofish 11:Camellia128 12:Camellia192 13:Camellia256]) of 3
Warning: "Many salts" test limited: 79/256
Many salts:	961140 c/s real, 911504 c/s virtual, GPU util: 32%
Only one salt:	936807 c/s real, 892618 c/s virtual
```
