### ISSUE TITLE
issue of ethereum-opencl

### ISSUE THREAD

**Issue by watanuoli** [magnumripper/JohnTheRipper#3221]
I download ethereum wallet from https://www.ethereum.org/ and try to recover password of it by jtr.
python ethereum2john.py wallet.json > eth.enc
john --device=gpu  --format=ethereum-opencl eth.enc
it returns：
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

if running without opencl format, it works very but it's very slowly.
john --format=ethereum eth.enc
Using default input encoding: UTF-8
Loaded 1 password hash (ethereum, Ethereum Wallet [PBKDF2-SHA256/scrypt Keccak 256/256 AVX2 8x])
Cost 1 (iteration count) is 262144 for all loaded hashes
Cost 2 (kdf [0:PBKDF2-SHA256 1:scrypt 2:PBKDF2-SHA256 presale]) is 1 for all loaded hashes
0.03295g/s 2.109p/s 2.109c/s 2.109C/s

Does that mean the format of such wallet is not able to utilize gpu?

P.S. maybe it's not a bug , I've post mail in the john-users@lists.openwall.com but there's no reply.

**Comment by kholia** [comment]
Please do not post support questions on a bug tracker. Please have some patience.

**Comment by solardiz** [comment]
To be fair, the problem posted on john-users does look like a potential bug to me, and if @kholia is so sure it is not I would have appreciated his reply on john-users by now.

Other than that, yes, we try to reply to all support requests and questions on john-users, but sometimes this takes a while. If this specific message were left without a reply for much longer, I would be pinging the team about it to see who would reply.

**Comment by solardiz** [comment]
I really don't like the "lock as spam" thing. Being impatient is not the same as spamming. Let's not insult people with such things.

**Comment by kholia** [comment]
Hi! I don't have free time available these days. Despite requesting the user to not post support questions here (in the issue template language), the user didn't listen and went ahead. We can't encourage such behavior here. Maybe the "spam" tag wasn't correct but IIRC the other options weren't much better. I will double-check the available options more carefully next time.

**Comment by watanuoli** [comment]
ok, got it. Actually I am not sure if it's a bug, next time I'll make it clear firstly.

**Comment by solardiz** [comment]
Oh, @kholia provided a clear reply now. Indeed, we have no support for scrypt in OpenCL (nor would this run fast even if added - whether CPU or GPU is faster would vary by scrypt parameters and GPU type). We could have a GitHub issue hanging for adding scrypt in OpenCL, and then for using it from the many formats that have scrypt as a component, but this is a fairly obvious task (not really something we need to keep track of, with no specific plans nor volunteers to work on it) and is probably not worth our time just yet.

**Comment by solardiz** [comment]
Maybe we could enhance the reporting, though: `valid()` for `ethereum-opencl` could detect cases like this and print warnings. IIRC, we already do this sort of thing in some other formats where their `-opencl` counterpart is less capable than the CPU one.

@kholia or @magnumripper, please feel free to reopen this issue for that purpose, and adjust its description accordingly (not edit any comment - just make the one-line description reasonable). I think that would be a good thing to do, and I'd do that but I don't want to throw more work at you. Thanks!

**Comment by kholia** [comment]
Thanks! I have created a separate issue to stay on top of this.
