### ISSUE TITLE
Hangs: Denial Of Service

### ISSUE THREAD

**Issue by RootUp** [magnumripper/JohnTheRipper#3225]
While fuzzing with afl got an unique hang @ id:000000,src:000000,op:havoc,rep:8

`
hexdump -C id\:000000\,src\:000000\,op\:havoc\,rep\:8 
00000000  39 54 1f 0d 35 35 36 35  35 0a                    |9T..55655.|
0000000a
`

**Comment by kholia** [comment]
Can you please attach the reproducer (rename it to `.txt`) as it is?

**Comment by RootUp** [comment]
Ummmm I see, 

`
John the Ripper 1.8.0.13-jumbo-1-bleeding-cfb2215cda 2018-03-29 12:44:44 +0200 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2018 by Solar Designer and others
Homepage: http://www.openwall.com/john/
`

![jtr](https://user-images.githubusercontent.com/29517169/38165605-ad9bd1ce-3533-11e8-8401-439445ab709b.png)

**Comment by kholia** [comment]
```
$ git rev-parse HEAD
a66a3136b07c6e19ac8666cbb9937175cad47176
```

```
$ ../run/john id.000000.src.000000.op.havoc.rep.8.txt
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

```
$ xxd id.000000.src.000000.op.havoc.rep.8.txt
00000000: 3954 1f0d 3535 3635 350a                 9T..55655
```

Try to reproduce the "hang" manually. Can you?

**Comment by RootUp** [comment]
Arggh ! My bad looks a false positive to me.
