### ISSUE TITLE
no bitlocker option in the windows version.

### ISSUE THREAD

**Issue by kolet** [magnumripper/JohnTheRipper#3243]
hi,
first of all thanks alot for the great project.
JTR jumbo & JTR doesnt have the bitlocker option from bitcracker.

http://openwall.info/wiki/john/OpenCL-BitLocker
https://github.com/e-ago/bitcracker

john.exe --format=bitlocker-opencl password.lst bitlockerhash.txt

result in both JTR jumbo & JTR 

Unknown ciphertext format name requested

john.exe bitlockerhash.txt

No password hashes loaded (see FAQ)

**Comment by magnumripper** [comment]
So you are running some outdated or inappropriate john binary and open an issue for it here? What am I gonna do about it, break into your computer and fix it?

**Comment by kolet** [comment]
@magnumripper  i have downloaded the latest windows binary of john the ripper available in  http://www.openwall.com/john/

John the Ripper 1.7.9 (Windows binaries, ZIP, 2029 KB)
and
John the Ripper 1.8.0-jumbo-1 (Windows binaries, ZIP, 34 MB)

**Comment by kolet** [comment]
@magnumripper  u can check that urself :+1:

**Comment by magnumripper** [comment]
This is not Openwall, this is GitHub. Those binaries you've found are older than my mom. Issues here are only for **LATEST** code **FROM HERE**, as clearly indicated in many places.

**Comment by magnumripper** [comment]
There may be fresh binaries downloadable from the main page of [this very repo](https://github.com/magnumripper/JohnTheRipper). I'm not familiar with them though, I never tried them.

**Comment by magnumripper** [comment]
Also, I doubt the pre-build binaries for Windows include OpenCL support, but again I'm not familiar with them, nor do I ever touch anything Microsoft.

**Comment by claudioandre** [comment]
FTR, the fresh binaries see in [this very repo](https://github.com/magnumripper/JohnTheRipper) do **NOT** have OpenCL support.
***********

- you need support as an end-user, please ask for help on the mailing list 
  - john-users at lists.openwall.com.

**Comment by kolet** [comment]
gotcha, 
i thought they were both the same. i guess not.
thanks for opening my eyes.

downloading it from here worked like a charm :) thanks alot @magnumripper  !
![image](https://user-images.githubusercontent.com/17353839/39668507-4ca2770e-50d8-11e8-8f73-8e077e64b081.png)
