### ISSUE TITLE
Self-test with "-test -mask" benchmark

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3249]
Currently, `-test -mask` implies  `-skip-self-test`. We should fix that - and until then we should warn about it.

**Comment by solardiz** [comment]
Added milestone so that we at least "warn about it" in the next release.

**Comment by solardiz** [comment]
Why do we skip self test when benchmarking with mask? Can we fix that underlying issue before our upcoming release?

**Comment by claudioandre-br** [comment]
We don't have a mask to (self) test and produce a crack.

**Comment by solardiz** [comment]
I meant: why don't we run our usual self-test using our test vectors, and follow that with a benchmark that uses mask? I see no reason why not.

**Comment by magnumripper** [comment]
We should be able to do so now. At the time I implemented `-test -mask`, the internal-mask formats would not let me do that easily though, so I simply had it imply skipping self-tests. I believe it should be easier now. Should I concentrate on fixing this now?

**Comment by solardiz** [comment]
@magnumripper Probably yes, concentrate on fixing this now unless it turns out to be difficult. Thanks!
