### ISSUE TITLE
keystore-opencl is aborting on a real crack run

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#3254]
* Detected by CI
* Tested on super

### Steps to reproduce ###
Run:
```
./jtrts.pl -noprelims -internal --type keystore-opencl -v -v
```

Output
```
Cmd_data = 
../run/john: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ../run/john)
Device 6: GeForce GTX TITAN X
Press 'q' or Ctrl-C to abort, almost any other key for status
OpenCL CL_OUT_OF_RESOURCES (-5) error in opencl_keystore_fmt_plug.c:335 - Copy result back
```

**Comment by magnumripper** [comment]
This may well be same problem as discussed in [#3223](https://github.com/magnumripper/JohnTheRipper/issues/3223#issuecomment-389641586)

**Comment by magnumripper** [comment]
So this is our guinnea pig. Please try to provoke an abort now. I'll review all 75+ formats if this proves a good fix.

**Comment by magnumripper** [comment]
> I'm going to change my formats and I'll run the super's script test.

Feel free to push your formats' changes to the lws-botcheck branch (#3255) and we'll merge many at once after some testing.

**Comment by claudioandre** [comment]
I started to push to another branch to run test bot.
