### ISSUE TITLE
Self test failed (cmp_one(0)) RADEON 560 Pro

### ISSUE THREAD

**Issue by darryllane** [magnumripper/JohnTheRipper#3263]
I am having problems getting my macOS GPU cracking. Im running a Radeon Pro 560.

**Issue**
./john --format=ntlmv2-opencl  --rules --wordlist=/Users/darryllane/tools/wordlist/large/10million.txt  '/Users/darryllane/Desktop/testhash.txt'
Device 2: AMD Radeon Pro 560 Compute Engine
Using default input encoding: UTF-8
Loaded 1 password hash (ntlmv2-opencl, NTLMv2 C/R [MD4 HMAC-MD5 OpenCL])
Self test failed (cmp_one(0))

**HashUsed**
Admin.user::DOMAIN:1122334455667788:fb2ec49c2c8dc985b8c3d4d9b06279cc:0101000000000000eb633d4029f8d301ff553ef96ecbec7300000000020000000000000000000000

**Test1**
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: NT-opencl [MD4 OpenCL]... DONE
Note: This format may also be benchmarked using --mask (see doc/MASK).
Raw:	17825K c/s real, 24418K c/s virtual

**Test2**
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: ntlmv2-opencl, NTLMv2 C/R [MD4 HMAC-MD5 OpenCL]... FAILED (cmp_one(0))

**Info**
Version: 1.8.0.13-jumbo-1-bleeding-4bc191b05 2018-05-27 18:50:55 +0530
Build: darwin17.4.0 64-bit x86_64 AVX2 AC
SIMD: AVX2, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
clang version: 9.1.0 (clang-902.0.39.2) (gcc 4.2.1 compatibility)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 010101007
OpenSSL 1.1.1-pre7 (beta) 29 May 2018
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Devices**
    Platform #0 name: Apple, version: OpenCL 1.2 (Oct 31 2017 18:30:00)
    Device #0 (0) name:     Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Device vendor:          Intel
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2
    Driver version:         1.1
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          16 GB
    Global Memory Cache:    64 B
    Local Memory:           32 KB (Global)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 4 GB
    Max clock (MHz):        2900
    Profiling timer res.:   1 ns
    Max Work Group Size:    1024
    Parallel compute cores: 8
    Speed index:            92800

    Device #1 (1) name:     Intel(R) HD Graphics 630
    Device vendor:          Intel Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2
    Driver version:         1.2(Dec 19 2017 21:05:46)
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          1.5 GB
    Local Memory:           64 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 384 MB
    Max clock (MHz):        1100
    Profiling timer res.:   80 ns
    Max Work Group Size:    256
    Parallel compute cores: 24
    Stream processors:      192  (24 x 8)
    Speed index:            211200

    Device #2 (2) name:     AMD Radeon Pro 560 Compute Engine
    Device vendor:          AMD
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2
    Driver version:         1.2 (Dec 20 2017 17:28:06) - Catalyst
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          4 GB
    Local Memory:           32 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 1024 MB
    Max clock (MHz):        907
    Profiling timer res.:   40 ns
    Max Work Group Size:    256
    Parallel compute cores: 16
    Stream processors:      1024  (16 x 64)
    Speed index:            928768

**Comment by kholia** [comment]
This issue is already known. See https://github.com/magnumripper/JohnTheRipper/issues/3235 (Formats failing on macOS w/ AMD Radeon Pro 560) for details.
