### ISSUE TITLE
Modify FVDE mode to accept length 40 Blob

### ISSUE THREAD

**Issue by trounce1** [magnumripper/JohnTheRipper#3267]
### Steps to reproduce ###
Fresh Copy of Ubuntu, installed correct libraries to build JtR from instructions.

I modified one file called fvde_common.h and edited the blob length from 24 bytes to 40 bytes to accept longer blobs.  ( BLOBLEN )

configures, builds and compiles fine.

When running it now, it does not get the correct password

### System configuration ###
Attach details about your OS and about JtR, including:
- `$ ./john --list=build-info`.

Version: 1.8.0.13-jumbo-1-bleeding-266f1c8 2018-06-01 11:45:56 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.4.0
GNU libc version: 2.23 (loaded: 2.23)
OpenCL headers version: 2.0
Crypto library: OpenSSL
OpenSSL library version: 01000207f
OpenSSL 1.0.2g  1 Mar 2016
GMP library version: 6.1.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

Any help would be much appreciated, I'm sure I've made a noob mistake somewhere.

**Comment by kholia** [comment]
You need to explain what problem you are trying to solve.

**Comment by kholia** [comment]
I don't think that adding support for larger wrapped kek lengths would be so simple.

How are you extracting the "hashes" (which include the wrapped kek blob)?

I wonder how https://github.com/libyal/libfvde handles APFS encrypted volumes.

...

Do you have some steps to reproduce this problem? Is there a way to easily create such encrypted volumes?

**Comment by trounce1** [comment]
so i extract the hashes by debian live boot and running https://github.com/sgan81/apfs-fuse with the -d 16 arg. i ran it with a valid password on one of my macbooks pro's which was filevaulted pre APFS release and got a wrapped kek which was 48 bytes long with 32 bytes of padded 00's. running on a mac that came out of the box with APFS then enabling filevault gave me an 80 bytes wrapped kek.

im not sure apfs is implemented in  https://github.com/libyal/libfvde as that was my first port of call for apfs crypto info before i found https://github.com/sgan81/apfs-fuse
