### ISSUE TITLE
bitlocker2john: different AES-CCM offset

### ISSUE THREAD

**Issue by e-ago** [magnumripper/JohnTheRipper#3281]
Recently in this issue https://github.com/e-ago/bitcracker/issues/4 an user sent me an encrypted device image having the AES-CCM field in a different offset wrt the salt.

@kholia could you apply this commit to bitlocker2john?
https://github.com/e-ago/bitcracker/commit/13e53888b9c4906a0d4cd3f8367f2c8eaf09d290

In the next future I'm planning to rework this code with a more dynamic behavior.

**Comment by kholia** [comment]
This code was merged.
