### ISSUE TITLE
wpapcap2john: Handle "4addr"

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3282]
https://github.com/hashcat/hashcat-utils/pull/45

**Comment by ZerBea** [comment]
WDS and MESH systems ar upcomming very fast. So it's a nice improvement for wpapcap2john.
It could be a good idea to add addr 4 for both cases: QOS and non-QOS frames. According to this thread it's possible to disable QOS on WDS systems:
https://community.ubnt.com/t5/NanoStation-and-Loco-Devices/Enabled-QoS-causes-random-radio-lockups-in-AP-or-AP-WDS-mode/td-p/64498

**Comment by magnumripper** [comment]
I'd need a sample for non-QoS. Our code is a patchwork mess.

**Comment by ZerBea** [comment]
Maybe jamazi can help. I added non-QoS to hcxpacpatool, but is is untested, because lack of a cap.

**Comment by jamazi** [comment]
Hi, this is a random packets captured by wireless sniffer tool in mikrotik containing both QoS and non-QoS packets. You will need to strip tzsp first :
`bittwiste -M 105 -I input.cap -O out.cap -D 1-71`
[wlan_sniffer.pcap.gz](https://github.com/magnumripper/JohnTheRipper/files/2138635/wlan_sniffer.pcap.gz)

**Comment by ZerBea** [comment]
@jamazi: Some nice header inside. New stuff to analyze. Thanks.

$ hcxpcaptool -o test.hccapx wlan_sniffer.pcap.gz
decompressing wlan_sniffer.pcap.gz to /tmp/wlan_sniffer.pcap.gz.tmp
start reading from /tmp/wlan_sniffer.pcap.gz.tmp
summary:                                        
file name....................: wlan_sniffer.pcap.gz.tmp
file type....................: pcap 2.4
network type.................: DLT_EN10MB (1)
endianess....................: little endian
read errors..................: flawless
packets inside...............: 4478
skipped packets..............: 0
packets with FCS.............: 0
WDS packets..................: 744
beacons......................: 24
probe requests...............: 1
probe responses..............: 8
action packets...............: 81
IPv4 packets.................: 4479
IPv6 packets.................: 5
UDP packets..................: 3421
DHCPv6 packets...............: 5
TZSP (802.11) packets........: 3414

**Comment by magnumripper** [comment]
Cool, thanks! I'll have a look soon.

**Comment by magnumripper** [comment]
While at it, I'll add support for reading TZSP directly.

**Comment by ZerBea** [comment]
Great. Adding MikroTik's native protocol will be fine.
It's easy to add:
ETHII -> IPv4 -> UDP -> TZSP -> 802.11
ETHII -> IPv6 -> UDP -> TZSP -> 802.11

UDP destinationport is 37008
