### ISSUE TITLE
Add support for cracking SAP's PSE files with PBES1-3DES-SHA1

### ISSUE THREAD

**Issue by martingalloar** [magnumripper/JohnTheRipper#3302]
SAP's PSE files are used to store cryptographic material, including private keys and encryption and signature certificates. PSE files are encrypted with a PIN.

Encryption scheme for PSEs with PBES1-3DES-SHA1:
```
DerivedKey, IV = PBKDF1(SHA1, Iterations, Salt, PIN)
EncryptedPIN= 3DES(DerivedKey, IV, PIN)
PSEContent= 3DES(DerivedKey, IV, PSEEncCont)
```
\* `PBKDF1` as defined in PKCS#12 with PKCS#7 padding

Full details of the algorithm:
https://www.coresecurity.com/system/files/publications/2018/03/TR18-Hunting-crypto-secrets-in-SAP-systems-vFinal.pdf

Python imlpementation:
https://github.com/CoreSecurity/pysap/blob/master/pysap/SAPPSE.py#L304

PSE to John script:
https://github.com/CoreSecurity/pysap/blob/master/extra/pse2john.py

Hashes format:
`$pse$<pbe_algo=1>$<iterations>$<salt_size>$<salt>$<iv_size=8>$<iv=0x0>$<encrypted_pin_length>$<encrypted_pin>`

Example hashes:
`$pse$1$2048$8$0000000000000000$0$$8$826a5c4189e18b67` PIN: `1234`
`$pse$1$2048$8$0000000000000000$0$$16$4e25e64000fa09dc32b2310a215d246e` PIN: `12345678`
`$pse$1$10000$8$0000000000000000$0$$16$4b23ac258610078d0ca66620010850b8` PIN: `password`
`$pse$1$2048$8$0000000000000000$0$$16$70172e6c0eb85edc6344852fb5fd24f3` PIN: `1234567890`

**Comment by martingalloar** [comment]
As the format stores the PIN encrypted (with the derived key based on the PIN itself), we're aiming at cracking the encrypted PIN itself. I tried at implementing this but one of the challenges I faced was, besides my lack of knowledge about how to properly code for OMP/SIMD/OCL, how to have the encrypted PIN itself to be of an arbitrary length. If anyone has a take on that it would be great!

**Comment by kholia** [comment]
@martingalloar Thanks for the superb work on this topic and the excellent, detailed report. I will take a look at implementing this format (plugin) in JtR Jumbo soon.

**Comment by kholia** [comment]
A CPU cracker for this is available in PR https://github.com/magnumripper/JohnTheRipper/pull/3303 now.

```
$ ../run/john --test --format=sappse  # i3-4005U
Will run 4 OpenMP threads
Benchmarking: sappse [PKCS12 PBE SHA1 256/256 AVX2 8x]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 2048
Raw:	8320 c/s real, 2095 c/s virtual
```

**Comment by kholia** [comment]
@@martingalloar Would it be possible for you to create and share a `.pse` file which uses a unicode password (perhaps `åbc`)? Thanks!

**Comment by martingalloar** [comment]
While the format file itself support it, the tool to create `.pse` files (`sapgenpse`) doesn't support Unicode characters in the PIN, so it shouldn't be a valid case.

**Comment by kholia** [comment]
Thanks for this information. I will add a note regarding this to the code.

**Comment by kholia** [comment]
I will take a look at adding OpenCL support for this format at some point.

**Comment by martingalloar** [comment]
Python 3 is not supported yet, we're in the work for doing so but it might take a while still (https://github.com/CoreSecurity/pysap/projects/1). macOS should be working fine as we include it in our Travis CI tests, but as said with Python 2.

**Comment by kholia** [comment]
PR https://github.com/magnumripper/JohnTheRipper/pull/3306 adds OpenCL support for cracking SAP's PSE files.
