### ISSUE TITLE
Running the Recovery Password fast attack mode  bitlocker attack isnt recognising hash

### ISSUE THREAD

**Issue by the133448** [magnumripper/JohnTheRipper#3309]
I'm trying to run the bitlocker third attack hash through john the ripper using the --bitlocker option.
using this cmd
`./run/john --format=bitlocker ../files/recovery_passwords.txt ../files/hash_recv_pass.txt`
Currently if the hash I try is `$bitlocker$3$16$432dd19f37dd413a88552225628c8ae5$1048576$12$a0da3fc75f6cd30106000000$60$3e57c68216ef3d2b8139fdb0ec74254bdf453e688401e89b41cae7c250739a8b36edd4fe86a597b5823cf3e0f41c98f623b528960a4bee00c42131ef`
I end up with a  `No password hashes loaded`
However if I try changing the format of the hash to $bitlocker$0$ or $bitlocker$1$ it will start trying to crack.
I thought that the bitlocker format should be able to crack all the hashes as referenced in the docs. openwall.info/wiki/john/OapenCL-BitLocker

### System configuration ###
Attach details about your OS and about JtR, including:
Version: 1.8.0.13-jumbo-1-bleeding-3a0cf8805 2018-07-17 07:02:20 +0530
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.3.0
GNU libc version: 2.27 (loaded: 2.27)
Crypto library: OpenSSL
OpenSSL library version: 01010007f
OpenSSL 1.1.0g  2 Nov 2017
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by kholia** [comment]
I have opened https://github.com/magnumripper/JohnTheRipper/issues/3310 (Make BitLocker CPU format feature complete) to track this.

Currently, the BitLocker CPU format doesn't support these hash types.
