### ISSUE TITLE
Incorrect charset file format

### ISSUE THREAD

**Issue by kastellanos** [magnumripper/JohnTheRipper#3333]
### Error ###

When trying to crack hdaa hash that change to incremental mode using a charset show an error and stop.

Changing to the commit before bf2048be86c352efdd02b107687a464937c81bd3
that is c555cfa2b3675b54e47b4cd1f3adfffb0843de09 solves the problem.

### Steps to reproduce ###
Clone the latest version bf2048be86c352efdd02b107687a464937c81bd3
Compile with `./configure && make -s clean && make -sj4`
Run over a hdaa hash
`
usuario:$response$83e84151328239788082f61770e2114b$usuario$test$GET$/$8c12bd8f728afe56d45a0ce846b70e5a$00000001$4b61913cec32e2c9$auth
`
**Error**

Loaded 1 password hash (hdaa, HTTP Digest access authentication [MD5 256/256 AVX2 8x3])
Warning: no OpenMP support for this hash type, consider --fork=4
Press 'q' or Ctrl-C to abort, almost any other key for status
Incorrect charset file format: $JOHN/ascii.chr

`
$response$15dca6888fd3287cfdcc1c0aabffbe62$usuario$Niagara-Admin$GET$/platformInfo$8c12bd8f728afe56d45a0ce846b70e5a$00000001$4b61913cec32e2c9$auth
`
### System configuration ###
- OS: Ubuntu 16.04 

- `$ ./john --list=build-info`.

Version: 1.8.0.13-jumbo-1-bleeding-bf2048b 2018-07-27 14:13:39 +0530
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.4.0
GNU libc version: 2.23 (loaded: 2.23)
Crypto library: OpenSSL
OpenSSL library version: 01000207f
OpenSSL 1.0.2g  1 Mar 2016
GMP library version: 6.1.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by emwinkler** [comment]
I get the same error on MacOS 10.13.6 with Apple LLVM version 9.1.0 and with GCC 8.1.

**Comment by magnumripper** [comment]
Confirmed. @kholia fix this ASAP!

**Comment by magnumripper** [comment]
Also, perhaps you should do a full Test Suite run after changes like these.

**Comment by kholia** [comment]
Yeah, this is my bad. I shouldn't have messed with a core component. I am not used to changing core code.

**Comment by kholia** [comment]
Here is the quick fix,

```diff
diff --git a/src/charset.h b/src/charset.h
index 15677dca1..b1e2701a0 100644
--- a/src/charset.h
+++ b/src/charset.h
@@ -33,7 +33,7 @@
  */
 struct charset_header {
 /* CHARSET_V* */
-       char version[5];
+       char version[4];
 
 /* A checksum of the file or equivalent plus some space for future extensions
  * (only 4 bytes are used currently) */
```

**Comment by kholia** [comment]
This should be fixed now via PR https://github.com/magnumripper/JohnTheRipper/pull/3335.
