### ISSUE TITLE
JtR is missing candidates since bf2048b

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3336]
```
form=net-md5 (dyna)               guesses:  750 -show= 750 0:00:00:01 DONE : Expected count(s) (1500)  [!!!FAILED1!!!  ret_val=0]
```

I can reproduce on super using JtR as it is now; JtR is working at c555cfa2b3675b54e47b4cd1f3adfffb0843de09:
```
../run/john -ses=tst-  -pot=tst-.pot dynamic_39_tst.in --wordlist=pw.dic -form=net-md5
```

IMO, the commit(s) should be reverted and reapplied in smaller and safer chunks.

**Comment by claudioandre-br** [comment]
```
form=dynamic_39                   guesses:   24 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_39               guesses:    4 -show=  16 0:00:00:00 DONE : Expected count(s) (24)  [!!!FAILED4!!!   ret_val=0]  (2 val-pwd  2 inval-pwd)
```

**Comment by kholia** [comment]
@claudioandre-br Are there any other failures? 

The changes to the dynamic format code were tricky and I think I got them wrong.

**Comment by magnumripper** [comment]
> I don't think that the whole commit can be reverted safely due to the presence of subsequent commits to the same files.

Not a problem at all. Revert all of them, in reverse order. Then add things like `-Wno-error=stringop-truncation` in autoconf as needed.

**Comment by magnumripper** [comment]
> Revert all of them

That was mostly a joke BTW. Seriously @kholia I appreciate your efforts trying to fix gcc's idiocy. I do hate gcc for this mess though.

This is not the end of the world, we just need to test everything a lot now, and fix some more problems that very likely got in there. The Test Suite is not enough, we need to verify every xx2john tool you touched, and every other thing. Or simply review the commits much more closely.

**Comment by kholia** [comment]
My bad for introducing incorrect fixes (and worse, bugs) in some places.

I am happy to fix all such problems and to make the code better.

**Comment by kholia** [comment]
This should be fixed with recent commits.
