### ISSUE TITLE
Mask mode segfaults when moving to another length

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3358]
This used to work. For example:

### Steps to reproduce ###
```
$ ../run/john ~/hashes --format=raw-md5-opencl --mask=?a -min-len=1 -max-len=5
Device 6: GeForce GTX TITAN X
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (raw-MD5-opencl [MD5 OpenCL])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:02  (1) 0g/s 0p/s 0c/s 0C/s GPU:42°C
Falha de segmentação
```

**Comment by claudioandre-br** [comment]
On a second thought:
* As a matter of fact, I test just this in situations like:
```
do_Test "alltests.in"      "-form=raw-SHA512-opencl" "-mask:?a -min-len=0 -max-len=2"  
```

But, I do not test all formats. I can't guarantee what used to work.

**Comment by magnumripper** [comment]
> I test just this in situations like

Since some internal mask formats have an internal mask size of 2 characters I believe you should make it `-max-len=3` to catch more bad stuff.

**Comment by claudioandre-br** [comment]
Since it works for (raw) sha256, sha512, xsha512, and NT the bug is not in the shared code, but it have to be in how some formats are using OpenCL mask mode.

**Comment by magnumripper** [comment]
It's very likely in `reset()` (or something that function calls in turn). The biggest change with those commits was that formats now must be able to `reset()` at "any" time during cracking (well not quite any, but after a batch is processed fully) without losing track of everything. Many of Sayantan's formats could not handle that, and apparently this is still the case with these formats.

On a side note, I never figured out DEScrypt-opencl and LM-opencl so they are treated specially and still can't use a `-min-len` that truncates the internal mask (ie. at the start of an iterated length run):
```c
        /* These formats are too wierd for magnum to get working */
        if (!strcasecmp(mask_fmt->params.label, "descrypt-opencl") ||
            !strcasecmp(mask_fmt->params.label, "lm-opencl"))
                format_cannot_reset = 1;
```

**Comment by magnumripper** [comment]
The actual segfault is in `get_key()` in all formats, which indicate this is a trivial bug. I just need to narrow it down to whatever little detail is amiss. It will probably wait until next week though.
