### ISSUE TITLE
OpenCL support for cracking AxCrypt 2.x

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#3367]
We recently added a CPU format (patch) to crack AxCrypt 2.x containers.

Writing a pure OpenCL kernel should be possible.

**Comment by magnumripper** [comment]
So it's `key = SHA1(password[.keyfile]) ^ salt` then iterated AES_ECB on short data. Should be a good speedup on GPU.

**Comment by kholia** [comment]
AxCrypt 2.x is quite different from AxCrypt 1.x from OpenCL code perspective.

@magnumripper Would it be OK if I introduce a new OpenCL kernel + format to handle AxCrypt 2.x stuff?

**Comment by kholia** [comment]
Note: Support for keyfiles would be nice also.

**Comment by kholia** [comment]
> Support for keyfiles would be nice also.

Opened https://github.com/magnumripper/JohnTheRipper/issues/3561 for handling this.

**Comment by magnumripper** [comment]
Sure, that's fine.
