### ISSUE TITLE
JtR stops in middle of process when cracking Multibit Classic hashes

### ISSUE THREAD

**Issue by easyname889** [magnumripper/JohnTheRipper#3368]
I am trying to crack two multibit hashes at the same time on ubuntu. It goes smoothly for a day or two then it comes to a halt. 
I have 3 GFORCE 1080 TI  cards and some of the cards halt earlier than the other ones. 
Its always  the same point it gets stuck at if i rerun the process, give or take. 
My password list is 6.3TB and are on an external USB drive and i am running JTR in TMUX session.

Im running JTR with the command
./john --wordlist=/media/noname1/8ter/bigwordfile.txt hash.txt --encoding=ISO-8859-1 --fork=3 --dev=0,1,2 --session=sweeny

Here is how it looks when it halts
./john --status=sweeny
1 0g 1:17:09:02 63,00% (ETA: 2018-08-15 22:25) 0g/s 520594p/s 1041Kc/s 1041KC/s
2 0g 0:16:01:02 21,00% (ETA: 2018-08-17 10:30) 0g/s 453713p/s 907426c/s 907426C/s
3 0g 0:17:37:01 31,00% (ETA: 2018-08-16 13:28) 0g/s 606825p/s 1213Kc/s 1213KC/s

8min later, should have bumped a couple of 0.1 percentages but nothing
./john --status=sweeny
1 0g 1:17:09:02 63,00% (ETA: 2018-08-15 22:33) 0g/s 520594p/s 1041Kc/s 1041KC/s
2 0g 0:16:01:02 21,00% (ETA: 2018-08-17 10:38) 0g/s 453713p/s 907426c/s 907426C/s
3 0g 0:17:37:01 31,00% (ETA: 2018-08-16 13:36) 0g/s 606825p/s 1213Kc/s 1213KC/s

~/john/run$ ./john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-3a0cf88 2018-07-17 07:02:20 +0530
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.4.0
GNU libc version: 2.23 (loaded: 2.23)
OpenCL headers version: 2.0
Crypto library: OpenSSL
OpenSSL library version: 01000207f
OpenSSL 1.0.2g  1 Mar 2016
GMP library version: 6.1.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

~/john/run$ ./john --list=opencl-devices
Platform #0 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 9.2.147
    Device #0 (0) name:     GeForce GTX 1080
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
    Driver version:         396.37 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          8 GB
    Global Memory Cache:    320 KB
    Local Memory:           48 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 2 GB
    Max clock (MHz):        1759
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 20
    CUDA cores:             2560  (20 x 128)
    Speed index:            4503040
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     6.1 (sm_61)
    Kernel exec. timeout:   yes
    NVML id:                0
    PCI device topology:    06:00.0
    PCI lanes:              1/16
    Fan speed:              37%
    Temperature:            28°C
    Utilization:            29%

    Device #1 (1) name:     GeForce GTX 1080
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
    Driver version:         396.37 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          8 GB
    Global Memory Cache:    320 KB
    Local Memory:           48 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 2 GB
    Max clock (MHz):        1759
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 20
    CUDA cores:             2560  (20 x 128)
    Speed index:            4503040
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     6.1 (sm_61)
    Kernel exec. timeout:   no
    NVML id:                1
    PCI device topology:    07:00.0
    PCI lanes:              1/16
    Fan speed:              37%
    Temperature:            27°C
    Utilization:            14%

    Device #2 (2) name:     GeForce GTX 1080
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
    Driver version:         396.37 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          8 GB
    Global Memory Cache:    320 KB
    Local Memory:           48 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 2 GB
    Max clock (MHz):        1759
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 20
    CUDA cores:             2560  (20 x 128)
    Speed index:            4503040
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     6.1 (sm_61)
    Kernel exec. timeout:   no
    NVML id:                2
    PCI device topology:    0b:00.0
    PCI lanes:              1/16
    Fan speed:              37%
    Temperature:            30°C
    Utilization:            0%

1 1:10:36:01 Command line: ./john --restore=newrun
1 1:10:36:01 - ISO-8859-1 input encoding enabled
1 1:10:36:01 - Passwords will be stored UTF-8 encoded in .pot file
1 1:10:36:01 Sorting salts, for performance
1 1:10:36:01 - Hash type: multibit, MultiBit Wallet (min-len 0, max-len 125)
1 1:10:36:01 - Algorithm: MD5/scrypt AES 32/64
1 1:10:36:01 - Candidate passwords will be buffered and tried in chunks of 4
1 1:10:36:01 - Configured to use otherwise idle processor cycles only
2 0:11:50:01 Command line: ./john --restore=newrun
2 0:11:50:01 - ISO-8859-1 input encoding enabled
2 0:11:50:01 - Passwords will be stored UTF-8 encoded in .pot file
2 0:11:50:01 Sorting salts, for performance
2 0:11:50:01 - Will reject candidates longer than 125 characters
2 0:11:50:01 Proceeding with wordlist mode
2 0:11:50:01 - Wordlist file: /media/noname1/8ter/bigswe.txt
2 0:11:50:01 - memory mapping wordlist (6273935944705 bytes)
2 0:11:50:01 - No word mangling rules
2 0:13:44:04 - Will distribute words across nodes
1 1:10:36:01 - Will reject candidates longer than 125 characters
1 1:10:36:01 Proceeding with wordlist mode
1 1:10:36:01 - Wordlist file: /media/noname1/8ter/bigswe.txt
1 1:10:36:01 - memory mapping wordlist (6273935944705 bytes)
1 1:10:36:01 - No word mangling rules
1 1:16:57:29 - Will distribute words across nodes
1 1:17:09:02 Continuing an interrupted session
1 1:17:09:02 Loaded a total of 2 password hashes with 2 different salts
1 1:17:09:02 Sorting salts, for performance
1 1:17:09:02 Cost 1 (iteration count) is 3 for all loaded hashes
1 1:17:09:02 Cost 2 (kdf [1:MD5 2:scrypt hd 3:scrypt classic]) is 1 for all loaded hashes
1 1:17:09:02 - Node numbers 1-3 of 3 (fork)
1 1:17:09:02 Command line: ./john --restore=newrun
1 1:17:09:02 - ISO-8859-1 input encoding enabled
1 1:17:09:02 - Passwords will be stored UTF-8 encoded in .pot file
1 1:17:09:02 Sorting salts, for performance
1 1:17:09:02 - Hash type: multibit, MultiBit Wallet (min-len 0, max-len 125)
1 1:17:09:02 - Algorithm: MD5/scrypt AES 32/64
1 1:17:09:02 - Candidate passwords will be buffered and tried in chunks of 4
1 1:17:09:02 - Configured to use otherwise idle processor cycles only

What could be the problem?

**Comment by kholia** [comment]
This seems like a end-user support issue.

Use `john-users` (http://www.openwall.com/lists/john-users/) mailing list for support.

**Comment by kholia** [comment]
MultiBit support in JtR doesn't use GPUs (yet) I think.

**Comment by solardiz** [comment]
On Tue, Aug 14, 2018 at 01:48:38PM -0700, easyname889 wrote:
> ./john --wordlist=/media/noname1/8ter/bigwordfile.txt hash.txt --encoding=ISO-8859-1 --fork=3 --dev=0,1,2 --session=sweeny

Dhiru, we should probably refuse to run with the "--device" option when the format is neither OpenCL nor ZTEX (nor whatever future format types might be device-aware).  Including for auto-detected formats, like in this example.  Open a new issue for this?

**Comment by claudioandre-br** [comment]
The user convinced me that he (or she) might be facing a bug. Although 8 minutes is not enough, there is evidence of an issue, at least for a `needs info` label.

After a revision of the format, I do not see how the format itself can lock; but, in my opinion, it is feasible for a library call to hang. 
****
So, IMO it is a valid issue. And it can be a bug.

**Comment by magnumripper** [comment]
Note though that the user didn't press a key to get status but ran `./john --status`. I wonder what a keypress would have emitted.

**Comment by easyname889** [comment]
I'm running a new session now, will get back ASAP with results

**Comment by easyname889** [comment]
I just checked the old session again with ./john --status
The JtR status was at the same percentage as earlier but the Estimation time until finished had just been moved forward without any result showing at the percentages.

**Comment by claudioandre-br** [comment]
I would say magnum prefers that you move the JtR process to foreground and press a key to get the status. 

Plus:
- `tail` the log
- use `top` or `ps` to see if JtR is running or sleeping.

I mean, it is not hard to show that JtR is a zombie (if it really is).

**Comment by magnumripper** [comment]
> I just checked the old session again

Sure but me thinks it's not running at all so it'll just show whatever state it was when it *stopped* (for whatever reason) and the ETA will move forward accordingly.

Claudio's suggestion to `tail john.log` is a good one.

What happens of you try this?
```
./john --restore=sweeny
```
Then, after a minute or two, press some key to get a status line.

**Comment by magnumripper** [comment]
> `tail john.log`

I corrected the above, it should obviously be `tail sweeny.log` in this case

**Comment by magnumripper** [comment]
BTW the log you supply in your OP is from a whole different session, called "newrun".

/me thinks we should move this discussion to john-users mailing list.

**Comment by easyname889** [comment]
Actually, it is the same session, I just edited the first post due to privacy reasons.

I started a new session 1.5w ago
./john --wordlist=/media/noname1/8ter/bigswe.txt hash.txt --encoding=ISO-8859-1 --fork=3 --dev=0,1,2 --session=newrun
Loaded 2 password hashes with 2 different salts (multibit, MultiBit Wallet [MD5/scrypt AES 32/64])
Cost 1 (iteration count) is 3 for all loaded hashes
Cost 2 (kdf [1:MD5 2:scrypt hd 3:scrypt classic]) is 1 for all loaded hashes
Warning: OpenMP was disabled due to --fork; a non-OpenMP build may be faster
Node numbers 1-3 of 3 (fork)
Note: This format may emit false positives, so it will keep trying even after
finding a possible candidate.
Press 'q' or Ctrl-C to abort, almost any other key for status
1 0g 0:00:00:08 0,00% (ETA: 2018-08-20 04:28) 0g/s 611112p/s 1222Kc/s 1222KC/s $lasamatta..$lasan
3 0g 0:00:00:08 0,00% (ETA: 2018-08-20 04:28) 0g/s 611109p/s 1222Kc/s 1222KC/s $larsen..$larskadans
2 0g 0:00:00:08 0,00% (ETA: 2018-08-20 04:30) 0g/s 610810p/s 1221Kc/s 1221KC/s $kronika..$kronikers
3 0g 0:00:00:21 0,01% (ETA: 2018-08-19 22:36) 0g/s 617381p/s 1234Kc/s 1234KC/s 1950nedmattar..1950nedmontera
1 0g 0:00:00:21 0,01% (ETA: 2018-08-19 22:36) 0g/s 617380p/s 1234Kc/s 1234KC/s 1950nedlater..1950nedlockade
2 0g 0:00:00:21 0,01% (ETA: 2018-08-19 22:36) 0g/s 617380p/s 1234Kc/s 1234KC/s 1950nedlatet..1950nedlockar
Killed
noname1@Pinkypromise:~/john/run$ tail newrun.log
3 0:00:00:00 - Passwords will be stored UTF-8 encoded in .pot file
3 0:00:00:00 Sorting salts, for performance
3 0:00:00:00 - Will reject candidates longer than 125 characters
3 0:00:00:00 Proceeding with wordlist mode
3 0:00:00:00 - Wordlist file: /media/noname1/8ter/bigswe.txt
3 0:00:00:00 - memory mapping wordlist (6273935944705 bytes)
3 0:00:00:00 - No word mangling rules
2 0:00:00:00 - Will distribute words across nodes
3 0:00:00:00 - Will distribute words across nodes
1 0:00:00:00 - Will distribute words across nodes
noname1@Pinkypromise:~/john/run$ 


I now tried to restore the session
noname1@Pinkypromise:~/john/run$ ./john --restore=newrun
Loaded 2 password hashes with 2 different salts (multibit, MultiBit Wallet [MD5/scrypt AES 32/64])
Cost 1 (iteration count) is 3 for all loaded hashes
Cost 2 (kdf [1:MD5 2:scrypt hd 3:scrypt classic]) is 1 for all loaded hashes
Warning: OpenMP was disabled due to --fork; a non-OpenMP build may be faster
Node numbers 1-3 of 3 (fork)
Note: This format may emit false positives, so it will keep trying even after
finding a possible candidate.
Proceeding with wordlist:/media/noname1/8ter/bigswe.txt

A keypress in this state doesn't generate any response

**Comment by easyname889** [comment]
When I run a smaller wordlist with big rules instead it runs for weeks without a problem

**Comment by claudioandre-br** [comment]
```
./john --wordlist=/media/noname1/8ter/bigswe.txt hash.txt --encoding=ISO-8859-1 --fork=3 --dev=0,1,2 --session=newrun
```
Since you not using GPUs (there is no multibit OpenCL format), the `--dev=0,1,2` is neither required nor used.

**Comment by claudioandre-br** [comment]
So, after the restore:
* any useful information inside logs?
* are you able to see the processes running? I prefer top, anyway:

I can see JtR running. I'm not "out of memory", or swapping, etc.:
```
$ ps -eo pcpu,pid,pmem,args | sort -k 1 -r | head -10
%CPU   PID %MEM COMMAND
 918 13671  0.1 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
 910 13669  0.0 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
 906 13670  0.0 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
 1.0 13707  0.0 ps -eo pcpu,pid,pmem,args
 0.0   993  0.0 [md0_raid1]
 0.0    99  0.0 [migration/24]
 0.0    98  0.0 [watchdog/23]
 0.0    97  0.0 [ksoftirqd/23]
 0.0    96  0.0 [stopper/23]
```

```
$ ps a | grep john
13601 pts/0    Rl+   15:01 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
13602 pts/0    Rl+   15:00 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
13603 pts/0    Rl+   15:06 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
13651 pts/11   S+     0:00 grep john
```
Still running:
```
$ ps a | grep john
13601 pts/0    Rl+   20:49 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
13602 pts/0    Rl+   20:50 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
13603 pts/0    Rl+   21:01 ../run/john --wordlist=wordlist /home/claudio/multibit.in --encoding=ISO-8859-1 --fork=3 --session=sweeny
13654 pts/11   S+     0:00 grep john
```

**Comment by magnumripper** [comment]
> `3 0:00:00:00 - memory mapping wordlist (6273935944705 bytes)`

So you are you using a 6 terabyte wordlist. I've never tested anything that crazy, but I would think it should be handled just fine (the OS pager should take care of it).

**Comment by magnumripper** [comment]
> `Killed`

Was this you aborting the session, or did it terminate?

**Comment by kholia** [comment]
Is there anything in the output of `dmesg` command?

**Comment by magnumripper** [comment]
@easyname889 there's this setting in john.conf:
```
# Set this to N to disable use of memory-mapping in wordlist mode.
WordlistMemoryMap = Y
```
Try changing that to `N` instead. This should mean we revert to simply reading a line at a time from the file.

**Comment by easyname889** [comment]
> Was this you aborting the session, or did it terminate?

It wasn't me, it just got terminated somehow

**Comment by easyname889** [comment]
> Is there anything in the output of dmesg command?

`[251367.931942] [ 2923]   108  2923   210378        0   241664      293             0 indicator-sessi
[251367.931943] [ 2945]   108  2945   100787        0   393216      385             0 indicator-appli
[251367.931945] [ 2962]   108  2962   161655        0   368640      895             0 pulseaudio
[251367.931945] [ 2966]   108  2966   157412        0   589824     1160             0 unity-settings-
[251367.931946] [ 3638]  1000  3638    11319        0   131072      214             0 systemd
[251367.931948] [ 3639]  1000  3639    36345        0   167936      525             0 (sd-pam)
[251367.931950] [30894]  1000 30894     9503        0   102400      133             0 tmux
[251367.931951] [30895]  1000 30895     7814        1   102400      488             0 bash
[251367.931952] [30917]  1000 30917 1531743036        0 3866759168     3414             0 john
[251367.931954] [ 1588]     0  1588    25457        0   225280      305             0 cupsd
[251367.931955] [ 1589]     0  1589    68703        0   311296      336             0 cups-browsed
[251367.931956] [ 1684]     0  1684    14799        0   147456      149             0 sshd
[251367.931957] Out of memory: Kill process 30917 (john) score 237 or sacrifice child
[251367.931961] Killed process 30917 (john) total-vm:6126972144kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[251368.422501] oom_reaper: reaped process 30917 (john), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

**Comment by easyname889** [comment]
> Is there anything in the output of dmesg command?

[251367.931942] [ 2923]   108  2923   210378        0   241664      293             0 indicator-sessi
[251367.931943] [ 2945]   108  2945   100787        0   393216      385             0 indicator-appli
[251367.931945] [ 2962]   108  2962   161655        0   368640      895             0 pulseaudio
[251367.931945] [ 2966]   108  2966   157412        0   589824     1160             0 unity-settings-
[251367.931946] [ 3638]  1000  3638    11319        0   131072      214             0 systemd
[251367.931948] [ 3639]  1000  3639    36345        0   167936      525             0 (sd-pam)
[251367.931950] [30894]  1000 30894     9503        0   102400      133             0 tmux
[251367.931951] [30895]  1000 30895     7814        1   102400      488             0 bash
[251367.931952] [30917]  1000 30917 1531743036        0 3866759168     3414             0 john
[251367.931954] [ 1588]     0  1588    25457        0   225280      305             0 cupsd
[251367.931955] [ 1589]     0  1589    68703        0   311296      336             0 cups-browsed
[251367.931956] [ 1684]     0  1684    14799        0   147456      149             0 sshd
[251367.931957] Out of memory: Kill process 30917 (john) score 237 or sacrifice child
[251367.931961] Killed process 30917 (john) total-vm:6126972144kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[251368.422501] oom_reaper: reaped process 30917 (john), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by kholia** [comment]
Is there a memory leak in MultiBit format in JtR? Or did you system simply run out of memory?

**Comment by easyname889** [comment]
I really don't know how to find out that information, please guide me and I will check it out.

**Comment by easyname889** [comment]
Why does this issue have the "invalid / PEBCAK" label? 
I don't say its wrong, but there is no proof of that the label should be used yet.

**Comment by kholia** [comment]
> I really don't know how to find out that information, please guide me and I will check it out.

Is the memory usage of `john` process continually growing when cracking the MultiBit wallet (what are the values after 2 mins, 15 mins, 30 mins, and so on? You can monitor the memory usage using the `top` command.

If it's not then this this is a local limited problem with *your* system (it ran out of memory -> too many chrome tabs open?). We suspect this (or some other local end user problem) is the cause, hence the `invalid` label. Invalid indicates that it is not a problem with JtR itself.

**Comment by kholia** [comment]
Can you paste the complete OOM message from the `dmesg` command? In the partial OOM message, I see some large values associated with `john` process which are not looking good.

**Comment by solardiz** [comment]
This looks like a case of exhausting RAM through page tables in the kernel. Without huge pages, mapping a 6 TB file (and actually accessing those pages) should need 12 GB RAM (maybe more with multiple forked processes), whereas the system appears to have only 8 GB (plus swap, but it won't help in this case). I wonder why transparent huge pages presumably don't (fully) kick in.

What the user may do as a workaround is either avoid using wordlists this large (obvious) or disable use of mmap for wordlists (`WordlistMemoryMap = N` in `john.conf`).

What we may do is explicitly use huge pages, with a fallback if that fails, like I do in `yescrypt-platform.c`.

**Comment by magnumripper** [comment]
@easyname889 a 6 GB wordlist should work on most systems but is still insane IMHO and strongly indicates poor understanding of your tools and/or poor quality of the wordlist. And your wordlist is a THOUSAND TIMES that. I do regard it a "PEBCAK" but it's not really meant as an offense if you thought so.
Having said that, if you do change that setting in john.conf we've mentioned and things STILL go wrong - then we do have a bug.

> maybe we can introduce a WordlistMemoryMapMaxSize or whatever, and set the default to, say, 1 TB, so that for larger wordlists the memory-mapping would be automatically disabled?

That is a good idea, I'll look into that.

**Comment by kholia** [comment]
> A 6 GB wordlist should work on most systems...

According to @solardiz, the wordlist size seems to be 6 *TB*?

**Comment by solardiz** [comment]
Maybe we need to drop "PEBCAK" from the label name, leaving just "invalid". There's no need to use words that could appear offensive.

Regarding a `WordlistMemoryMapMaxSize` numeric setting, I think it could replace the existing `WordlistMemoryMap` Boolean setting, where `0` size would correspond to having this functionality disabled (same as `WordlistMemoryMap = N`). Maybe the numeric value should be in MB.

**Comment by kholia** [comment]
> Maybe we need to drop "PEBCAK" from the label name, leaving just "invalid". There's no need to use words that could appear offensive.

Ack. This has been fixed now.
