### ISSUE TITLE
duplicate of #2193

### ISSUE THREAD

**Issue by no1deer** [magnumripper/JohnTheRipper#3375]
I'm trying to extract the content of zip file that is password protected.
After extracting the hash i receive the message "No password hashes loaded (see FAQ)"

./john secret-pkzip.hash 
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

Here is the original file - 
[secret.zip](https://github.com/magnumripper/JohnTheRipper/files/2299566/secret.zip)

**cat secret-pkzip.hash** 
secret.zip:$pkzip2$1*1*2*0*14*8*77537827*0*24*0*14*7753*9827*8061b9caf8436874ad47a9481863b54443379d4c*$/pkzip2$:::::secret.zip

Can you confirm this behaviour by replicating the issue on your end please or advising as appropriate if i'm missing something?
Look sot be a bug from #2193 re appearing.

**Version:**
John the Ripper 1.8.0.13-jumbo-1-bleeding-b8b84632b 2018-08-06 22:27:50 +0200 MPI + OMP [linux-gnu 64-bit x86_64 AVX2 AC]

**unzip -lv file.zip**
Archive: secret.zip
Length Method   Size  Cmpr  Date            Time  CRC-32     Name
 8          Stored    8       0%     2018-01-24 19:01 77537827  secret
 8                         8       0%                            1 file

**Output from zipinfo**
#zipinfo secret.zip
Archive: secret.zip
Zip file size: 166 bytes, number of entries: 1
-r--a-- 6.3 fat 8 Bx stor 18-Jan-24 19:01 secret
1 file, 8 bytes uncompressed, 8 bytes compressed: 0.0%

**Output from zipdetails**
#zipdetails secret.zip

0000 LOCAL HEADER #1 04034B50
0004 Extract Zip Spec 14 '2.0'
0005 Extract OS 00 'MS-DOS'
0006 General Purpose Flag 0001
[Bit 0] 1 'Encryption'
0008 Compression Method 0000 'Stored'
000A Last Mod Time 4C389827 'Wed Jan 24 19:01:14 2018'
000E CRC 77537827
0012 Compressed Length 00000014
0016 Uncompressed Length 00000008
001A Filename Length 0006
001C Extra Length 0000
001E Filename 'secret'
0024 PAYLOAD .a...Cht.G.H.c.DC7.L

0038 CENTRAL HEADER #1 02014B50
003C Created Zip Spec 3F '6.3'
003D Created OS 00 'MS-DOS'
003E Extract Zip Spec 14 '2.0'
003F Extract OS 00 'MS-DOS'
0040 General Purpose Flag 0001
[Bit 0] 1 'Encryption'
0042 Compression Method 0000 'Stored'
0044 Last Mod Time 4C389827 'Wed Jan 24 19:01:14 2018'
0048 CRC 77537827
004C Compressed Length 00000014
0050 Uncompressed Length 00000008
0054 Filename Length 0006
0056 Extra Length 0024
0058 Comment Length 0000
005A Disk Start 0000
005C Int File Attributes 0000
[Bit 0] 0 'Binary Data'
005E Ext File Attributes 00000021
[Bit 0] Read-Only
[Bit 5] Archive
0062 Local Header Offset 00000000
0066 Filename 'secret'
006C Extra ID #1 000A 'NTFS FileTimes'
006E Length 0020
0070 Reserved 00000000
0074 Tag1 0001
0076 Size1 0018
0078 Mtime 01D39534F11E2900 'Wed Jan 24 17:01:14
2018 0ns'
0080 Ctime 01D3BF8C69BBCD83 'Mon Mar 19 14:13:11
2018 411853100ns'
0088 Atime 01D39534F11E2900 'Wed Jan 24 17:01:14
2018 0ns'

0090 END CENTRAL HEADER 06054B50
0094 Number of this disk 0000
0096 Central Dir Disk no 0000
0098 Entries in this disk 0001
009A Total Entries 0001
009C Size of Central Dir 00000058
00A0 Offset to Central Dir 00000038
00A4 Comment Length 0000
Done

**Comment by kholia** [comment]
You are using an old buggy version of `zip2john`.

With current version (from this repository),

```
$ ../run/zip2john secret.zip 
ver 2.0 secret.zip->secret PKZIP Encr: cmplen=20, decmplen=8, crc=77537827
secret.zip:$pkzip2$1*1*2*0*14*8*77537827*0*24*0*14*7753*9827*8061b9caf8436874ad47a9481863b54443379d4c*$/pkzip2$:::::secret.zip
```

```
$ git rev-parse --short HEAD
40b7a61ed
```

**Comment by no1deer** [comment]
I have updated to "40b7a61ed"  but have the same issue. I get the same hash as you have @kholia 
But yet when i try to run it against john i get the same error message.

root@debian-base:/opt/john/run# git pull .
From .
 * branch                HEAD       -> FETCH_HEAD
Already up to date.
root@debian-base:/opt/john/run# git rev-parse --short HEAD
40b7a61ed

root@debian-base:/opt/john/run# ./zip2john secret.zip  > secret-pkzip.hash
ver 2.0 secret.zip->secret PKZIP Encr: cmplen=20, decmplen=8, crc=77537827

secret.zip:$pkzip2$1*1*2*0*14*8*77537827*0*24*0*14*7753*9827*8061b9caf8436874ad47a9481863b54443379d4c*$/pkzip2$:::::secret.zip


root@debian-base:/opt/john/run# john secret-pkzip.hash 
No password hashes loaded (see FAQ)
