### ISSUE TITLE
incorrect behaviour in mask mode with custom placeholders

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3381]
There are 2 problems:
1) empty group [] synthesized from custom placeholder makes john to hang,
2) custom placeholder with ] ... [ inserts it into mask as text and causes unexpected results with complicated lists of chars (it could be a cool feature, but it is not at the moment).

### Steps to reproduce ###

```
$ john --stdout --mask='?1' --1='1-9['
(hangs)

$ john --stdout --mask='?1' --1='ab] asdf ['
(hangs)

$ john --stdout --mask='?1' --1='ab] asdf [cd'
a asdf c
b asdf c
a asdf d
b asdf d
4p 0:00:00:00 100.00% (2018-08-20 18:01) 100.0p/s b asdf d
```

### System configuration ###
```
$ john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-5d6ec13 2018-08-07 22:30:42 +0530
Build: linux-gnu 64-bit x86_64 SSE4.2 AC
[...]
gcc version: 5.1.0
GNU libc version: 2.19 (loaded: 2.19)
```

**Comment by magnumripper** [comment]
The hang bug is fixed now. After that, example 1 works as you'd expect. The other two are trickier but both work fine as soon as you escape the literal brackets. As said in doc/MASK (although it could be more strongly worded) the best is to always do so, better safe than sorry.
