### ISSUE TITLE
pcap2john.py is not user-friendly

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3382]
Currently, `pcap2john.py` has unusual dependencies (dpkt, scapy), and a user might spend time installing those (I did) only to receive this message:

```
Note: This program does not have the functionality of wpapcap2john, SIPdump, eapmd5tojohn, and vncpcap2john.
```

That message does not even say what functionality the program _does_ have. Perhaps what this program is and what it is not (and the available other programs, like in the message above) should be stated in a comment at the very beginning of this Python script.

**Comment by kholia** [comment]
This message was added on purpose. See https://github.com/magnumripper/JohnTheRipper/issues/2368 for the whole story.

**Comment by kholia** [comment]
I think a person who actually opens the source file to look at the comment (and actually understand it) can also look at [this code in the same file](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/run/pcap2john.py#L1419) to understand the same thing.

Maybe I am just not interested in this task? Please feel free to keep it open. I have removed my assignment as I am trying to find time to work on something else.

**Comment by solardiz** [comment]
Well, believe it or not I did not look at line 1419 until after having wasted time (and taken risk) to install the dependencies. I did appreciate the eventual message from the program, but I would have preferred to also have this info and more in a comment at the very beginning of the Python script, near the place where it initially fails to run on missing dpkt.

**Comment by kholia** [comment]
The dependency handling involves trial-and-error and is unfriendly (I just looked at that code). I can fix this real quick as it is a problem.

**Comment by solardiz** [comment]
Thanks, this is probably an improvement. But I'd like that comment at the start of the script as well.

**Comment by kholia** [comment]
This PR above only tackles the dependency handling part, which is a problem I should have fixed earlier.

I am not working on the comment part.

**Comment by solardiz** [comment]
I think simply duplicating the existing "Note: ..." message in the file's initial comment would already be a major improvement, and is quick to do along with the changes you're making now.

**Comment by kholia** [comment]
Great point.

I am on a phone now. I will fix this up tomorrow morning.

Thanks!

**Comment by kholia** [comment]
> I will fix this up tomorrow morning.

The suggested changes are in place now.

**Comment by solardiz** [comment]
Thanks! It would still be nice to list somewhere close to the start of script what functionality _is_ included, but the changes so far are sufficient to have saved me the trouble of installing dependencies only to find that the program wasn't right for my needs.
