### ISSUE TITLE
OpenCL-enabled PMKID attack fails to run

### ISSUE THREAD

**Issue by pqyptixa** [magnumripper/JohnTheRipper#3387]
I installed JtR from this repo on the lastest Kali. When running the PMKID attack, I get:
```
$  ./run/john -mask=?d?d?d?d?d?d?d?d --dev=gpu --format=wpapsk-pmk-opencl pmkid-test
Device 1: Baffin [Radeon RX 560 Series]
Using default input encoding: UTF-8
Loaded 87 password hashes with 87 different salts (wpapsk-pmk-opencl, WPA/WPA2/PMF/PMKID master key [MD5/SHA-1/SHA-2 OpenCL])
Cost 1 (key version [0:PMKID 1:WPA 2:WPA2 3:802.11w]) is 0 for all loaded hashes
Options used: -I /home/user/JohnTheRipper/run/kernels -cl-mad-enable -D__GPU__ -DDEVICE_INFO=522 -DSIZEOF_SIZE_T=8 -DDEV_VER_MAJOR=2633 -DDEV_VER_MINOR=3 -D_OPENCL_COMPILER -DPLAINTEXT_LENGTH=64 -DV_WIDTH=1 -DWPAPMK $JOHN/kernels/wpapsk_kernel.cl
Build log: In file included from /tmp/OCL7202T3.cl:13:
In file included from /home/user/JohnTheRipper/run/kernels/opencl_cmac.h:24:
/home/user/JohnTheRipper/run/kernels/opencl_aes.h:316:4: error: unsupported: typedef changes linkage of anonymous type, but linkage was already computed
        } aes_block_t;
          ^
/home/user/JohnTheRipper/run/kernels/opencl_aes.h:313:15: note: use a tag name here to establish linkage prior to definition
        typedef union {
                     ^
                      aes_block_t
1 error generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

Error -11 building kernel $JOHN/kernels/wpapsk_kernel.cl. DEVICE_INFO=522
OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1177 - clBuildProgram failed.
```

**Comment by pqyptixa** [comment]
Simply changing `typedef union {` to `typedef union _aes_block_t {` in `run/kernels/opencl_aes.h` seems to have fixed it...

**Comment by magnumripper** [comment]
Interesting, thanks for reporting.
```
	typedef union {
		ulong data[N_WORDS];
		uchar bytes[AES_BLOCK_SIZE];
	} aes_block_t;
```
So clang now doesn't understand anonymous unions? I will fix this (all cases of it).

**Comment by magnumripper** [comment]
Strange, the kernel file itself has this:
```c
typedef struct {
	uint keymic[16 / 4];
} mic_t;

typedef struct {
	uint  length;
	uint  eapol[(256 + 64) / 4];
	uint  eapol_size;
	uint  data[(64 + 12) / 4]; // pre-processed mac and nonce
	uchar salt[36]; // essid
} wpapsk_salt;

typedef struct {
	MAYBE_VECTOR_UINT W[5];
	MAYBE_VECTOR_UINT ipad[5];
	MAYBE_VECTOR_UINT opad[5];
	MAYBE_VECTOR_UINT out[5];
	MAYBE_VECTOR_UINT partial[5];
} wpapsk_state;
```
Those are structs though but the rules are the same in C11 (which OpenCL is a subset of IIRC). Anyway I'll change all unions only for now.

I'm hoping this could fix some macOS problems as well, but that's probably not gonna haooen.

**Comment by magnumripper** [comment]
@pqyptixa Could you please state what exact driver/runtime you have on that gear? Eg. the output of `john --list=opencl-devices -dev=1`.

**Comment by magnumripper** [comment]
@jsteube have you encounted this problem?

**Comment by magnumripper** [comment]
Looks like it could be amdgpu-pro 18.20

**Comment by jsteube** [comment]
Yes indeed, amdgpu-pro required me to place some volatiles to make it work: https://github.com/hashcat/hashcat/commit/dad05d9f6931523d06cd745feb5d0354cfa0acf0

**Comment by pqyptixa** [comment]
@magnumripper you forgot to modify run/kernels/opencl_aes.h (line 313).

**Comment by magnumripper** [comment]
> you forgot to modify run/kernels/opencl_aes.h (line 313).

No, that file is just copied from src/opencl/opencl_aes.h during `make`.

Thanks!

**Comment by pqyptixa** [comment]
Ah, OK, sorry. I had copied this repo again (just in case I had messed something up), but didn't notice the patches hadn't been pushed.
Thank you!

BTW, just in case someone came looking for instructions on crack these hashes: the command line I used was wrong. Simply removing "pmk-" from "--format=wpapsk-pmk-opencl" should make JtR work.

**Comment by magnumripper** [comment]
Right, the PMK formats expect 64-hex-chars candidates, i.e. raw master keys.

**wpapsk** or **wpapsk-opencl** can be used for what hashcat has as `-m 2500` and `-m 16800` (BTW this means we can attack a file with a mix of them, which hashcat can not)

**wpapsk-pmk** or **wpapsk-pmk-opencl** can be used for what hashcat has as `-m 2501` and `-m 16801`
