### ISSUE TITLE
AVX512 tweaks

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3399]
I could get my hands on some gear with Skylake Xeon (silver something).
```
$ gccmacros -march=native | grep AVX512
#define __AVX512F__ 1
#define __AVX512BW__ 1
#define __AVX512CD__ 1
#define __AVX512DQ__ 1
```

Any of BW, CD or DQ implies F, but only that. So to get it complete w/o "native", we need `-mavx512bw -mavx512cd -mavx512dq`. Not sure if that would make any difference at all right now but anyway we'll probably want to add checks for CD and DQ in autoconf sooner or later.

Edit for anyone stumbling in here:
```
$ alias gccmacros
alias gccmacros='gcc -dM -E -x c /dev/null'
```

**Comment by magnumripper** [comment]
BTW the very limited tests I did was faster with just AVX512F than with AVX512BW. Will look into that. Here's relevant code from pseudo-intrinsics.h:
```c
#if __AVX512BW__
#define vcmpeq_epi8_mask        (uint64_t)_mm512_cmpeq_epi8_mask
#define vshuffle_epi8           _mm512_shuffle_epi8
#define vshufflehi_epi16        _mm512_shufflehi_epi16
#define vshufflelo_epi16        _mm512_shufflelo_epi16
#define vslli_epi16             _mm512_slli_epi16
#define vsrli_epi16             _mm512_srli_epi16

#define vswap32(n)                                              \
    n = vshuffle_epi8(n, vset_epi32(0x3c3d3e3f, 0x38393a3b,     \
                                    0x34353637, 0x30313233,     \
                                    0x2c2d2e2f, 0x28292a2b,     \
                                    0x24252627, 0x20212223,     \
                                    0x1c1d1e1f, 0x18191a1b,     \
                                    0x14151617, 0x10111213,     \
                                    0x0c0d0e0f, 0x08090a0b,     \
                                    0x04050607, 0x00010203))
#define vswap64(n) \
    n = vshuffle_epi8(n, vset_epi64(0x38393a3b3c3d3e3fULL, \
                                    0x3031323334353637ULL, \
                                    0x28292a2b2c2d2e2fULL, \
                                    0x2021222324252627ULL, \
                                    0x18191a1b1c1d1e1fULL, \
                                    0x1011121314151617ULL, \
                                    0x08090a0b0c0d0e0fULL, \
                                    0x0001020304050607ULL))
#else /* workarounds without AVX512BW */
#define vswap32 vswap32_emu
#define vswap64(x) \
	(x = vshuffle_epi32(x, _MM_SHUFFLE(2, 3, 0, 1)), vswap32(x))

#endif /* __AVX512BW__ */

(...)

#define vswap32_emu(x) \
	x = vxor(vsrli_epi32(x, 24),                                            \
	         vxor(vslli_epi32(vsrli_epi32(vslli_epi32(x, 8), 24), 8),       \
	              vxor(vsrli_epi32(vslli_epi32(vsrli_epi32(x, 8), 24), 8),  \
                       vslli_epi32(x, 24))))
```

**Comment by magnumripper** [comment]
BTW if I run my own cpuid program (eg. the one posted in #1886) instead of just `gcc -march=native`, I can see we also have AVX-512VL (just like that Wikipedia page suggests):
```
$ cpuid 7
EAX=7h, ECX=0h CPUID
                31                             0
EBX:  d39ffffb  11010011100111111111111111111011
ECX:  00000008  00000000000000000000000000001000
```
Not sure if VL could be useful to us. It seems my gcc (5.4.0, Ubuntu 16.04) does support it:
```
$ gccmacros -mavx512vl | grep AVX512
#define __AVX512F__ 1
#define __AVX512VL__ 1
```
I wonder why `-march=native` doesn't turn it on though? I should try a newer gcc.

Another data point is that /proc/cpuinfo only shows avx512f and avx512cd. That's with a Ubuntu 4.4.0-128-generic kernel.

**Comment by magnumripper** [comment]
According to the AVX-512 Wikipedia page, all current/planned CPU's that have AVX-512F also have CD, 
and all that have BW also have DQ. But I'm not quite sure how to go about adding these in our CPU de
tection. Perhaps we should always add -mavx512cd whenever we add -mavx512f (so we'd test for both an
d use `-mavx512cd`)? And perhaps we should add another "level" for -mavx512dq which will include -ma
vx512bw (so we test for both plus the CD+F and enable all three `-mavx512cd -mavx512bw -mavx512dq`).

Or we could treat CD as a superset of F, like this (all implies any above):
AVX512F
+AVX512CD
+AVX512BW
+AVX512DQ

This however would mean we'd end up only using F for a hypotetical future CPU having F+BW but not CD. Perhaps we should simply not do anything at all until we want to add some intrinsics actually using CD or DQ (and we'd see where things stand at that time).

**Or** we could keep anything beyond F separated: We could change the fundamental functionality of CPU_detect(), or rather revert it to only include things up to and including AVX-512F and add a new function for the rest, outputing bits corresponding to features. That would be easy - actually easier than adding even more to the existing stuff (my additions to it have been very error-prone so far).

**Comment by magnumripper** [comment]
> the very limited tests I did was faster with just AVX512F than with AVX512BW

I believe I was mistaken. The difference is very small but BW seems to be slightly faster.

**Comment by magnumripper** [comment]
Results so far of various AVX-512 tweaks (measured with 1000 iterations of PBKDF2-HMAC). Above all this comes from using native rotate instructions.
```
MD4     26% faster
MD5     25%
SHA-1   47%
SHA-256 54%
SHA-512 56%
```
Not bad, I didn't expect this much

**Comment by magnumripper** [comment]
The CD/DQ/VL instructions doesn't seem to add anything we could want right now. The basic hash algos are very effective with AVX-512, using ternarylogic and rotate - I can't see any way to make it better.

**Comment by magnumripper** [comment]
I managed to get a few percent more from SHA-1 in 53cd16b80, now 54% faster than a few weeks ago.

And here's an AVX-512 build compared against an AVX2 build, running on that same machine, as of the commit mentioned above:
```
MD4     2.13x
MD5     1.68x
SHA-1   2.35x
SHA-256 2.29x
SHA-512 2.33x
```
Except for MD5, we're more than twice as fast mainly because of hardware rotate and ternary logic. I'm not sure why we don't even hit 2x for MD5, I will investigate that further.

On another note: Using gcc 5.4.0, `-march=native` produces an identical build to `-mavx512bw`. I haven't seen that before.

Oh, and this:

hash\para  |       1  |       2  |       3  |       4  |       5  |
-----------|----------|----------|----------|----------|----------|
md4        |   67312  | **93152**|   92688  |   87616  |   92560  |
md4-omp    |   67088  | **92960**|   92736  |   91968  |   89920  |
md5        |   51263  |   61248  |   61306  | **62336**|   61760  |
md5-omp    |   51744  |   60895  |   61152  |   60958  | **62240**|
sha1       | **35824**|   33440  |   29904  |   27328  |   26800  |
sha1-omp   | **35776**|   32832  |   30144  |   27264  |   26880  |
sha256     |   14704  | **14912**|   14880  |   11136  |   11280  |
sha256-omp |   14656  | **14880**|   14732  |   11136  |   11280  |
sha512     |  **6152**|    6128  |    5568  |    4480  |    4560  |
sha512-omp |  **6144**|    6128  |    5512  |    4480  |    4560  |

We could opt to decrease interleaving for MD4 from 3x to 2x, and increase it for MD5 from 3x to 4x and SHA-256 from 1x to 2x. But it would need further testing and most of all we should try a newer gcc as well.

**Comment by solardiz** [comment]
> Not sure if VL could be useful to us. It seems my gcc (5.4.0, Ubuntu 16.04) does support it:

Yes, we need AVX512VL's XOP-like bit rotates for faster Salsa20 in yescrypt. This doesn't affect native yescrypt's speed much, but it does provide great speedup for scrypt - which is what we currently use this code for. I'll open a separate issue.
