### ISSUE TITLE
Failing formats

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3405]
These don't fail at the build bots nor on my Macbook. They do (or did) fail on Ubuntu 18.04.1, bog standard AVX2 build (with OpenCL) ~running one thread (IIRC)~ and `-test=0 -form=cpu`:
```
Testing: argon2 [Blake2]... (8xOMP) FAILED (cmp_all(1))
Testing: Raw-Blake2 [BLAKE2b 512 32/64]... FAILED (cmp_all(1))
Testing: tezos, Tezos Key [PBKDF2-SHA512 64/64 OpenSSL]... (8xOMP) FAILED (cmp_all(1))
3 out of 706 tests have FAILED
```
Perhaps I just had an unclean build somehow, but I need to investigate.

**Comment by magnumripper** [comment]
I see now all three report not using SIMD at all. I need to check what the heck I was actually running.

**Comment by solardiz** [comment]
For `argon2` and `raw-blake2`, we need to update to latest upstream Argon2 code before we spend much time fixing whatever issues might be in those formats.

**Comment by solardiz** [comment]
> I see now all three report not using SIMD at all.

Looks like you previously discovered this behavior in #3079.

**Comment by magnumripper** [comment]
Yeah this is just a dupe of #3079 except I never saw it on Linux before.
