### ISSUE TITLE
--show not showing cracked passwords

### ISSUE THREAD

**Issue by phocean** [magnumripper/JohnTheRipper#3412]
### Steps to reproduce ###

`--show` does not work as expected.

It shows username and hash, but not the cracked password.

for instance with NT hashes:

```
user::1234:aad3b435b51404eeaad3b435b51404ee:c6f..................ebddf1:::
```

I would expect it to display cracked passwords.

### System configuration ###

```
➤  ./john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-6b8220e22 2018-09-25 14:23:03 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.3.0
GNU libc version: 2.27 (loaded: 2.27)
Crypto library: OpenSSL
OpenSSL library version: 01010007f
OpenSSL 1.1.0g  2 Nov 2017
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by kholia** [comment]
I guess you need to do something like `../run/john --format=nt --show`?

**Comment by kholia** [comment]
This sounds like a topic for `john-users` mailing list.

https://www.openwall.com/lists/john-users/

**Comment by magnumripper** [comment]
Here's a quick hack:
```diff
diff --git a/src/john.c b/src/john.c
index 211e01950..875641903 100644
--- a/src/john.c
+++ b/src/john.c
@@ -1888,8 +1888,17 @@ static void john_run(void)
 				fprintf(stderr, "%s%s and%s\n",
 				    might, partial, not_all);
 			}
-			fputs("Use the \"--show\" option to display all of "
-			    "the cracked passwords reliably\n", stderr);
+			if (database.format->methods.prepare !=
+			    fmt_default_prepare)
+				fprintf(stderr,
+				        "Use the \"--show --format=%s\" options"
+				        " to display all of the cracked "
+				        "passwords reliably\n",
+				        database.format->params.label);
+			else
+				fputs("Use the \"--show\" option to display all"
+				      " of the cracked passwords reliably\n",
+				      stderr);
 		}
 	}
 }
```
This triggers on any format that does have a `prepare()` so will sometimes output the extra option without need. That's actually a good thing if a user ran against a pwdump file without specifying format - it will emphasize that we were attacking LM and not NT.

**Comment by magnumripper** [comment]
> when splitting a string, I normally include any space characters at the end of the previous line

You didn't do so in `char *might` a couple lines above this 😉  ...but more importantly, I already hit column 80 without the spaces, so let's keep it this way.

**Comment by solardiz** [comment]
> This triggers on any format that does have a `prepare()` so will sometimes output the extra option without need.

FWIW, this is now triggered for `phpass*` formats because we have a `phpass_common_prepare`, which calls `phpass_common_split` to `convert dynamic_17 back into phpass format`. Maybe it's an error that we have a `prepare` in those formats - wouldn't `split` alone be enough there?

**Comment by magnumripper** [comment]
You may be right, Jim has over-used prepare in the past. We have https://github.com/magnumripper/JohnTheRipper/wiki/split()-vs.-prepare() as a reference now.

**Comment by solardiz** [comment]
Thanks, magnum. This says, among other things, that "prepare() should be used for [...] or conversion to canonical format". As I wrote in that 2011 john-dev thread you reference, I think it's undesirable to use `prepare` for conversion to canonical format. In the core tree, I do that in `split`. Yes, this does require that `valid` recognize non-canonical variations of the syntax as well.

BTW, I'm not happy we have this valuable content on the GitHub wiki - I'd be happier if we had it in JtR documentation (in the tree), on john-dev, or on Openwall wiki.
