### ISSUE TITLE
configure detects Hyperthreading incorrectly

### ISSUE THREAD

**Issue by jeroen-80** [magnumripper/JohnTheRipper#3418]
```
bofh@dev:/opt/JohnTheRipper/src$ ./configure
..
configure: Testing build host's native CPU features
checking for Hyperthreading... yes
..
bofh@dev:/opt/JohnTheRipper/src$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2609 v4 @ 1.70GHz
```
Threads per core = 1 (no HT) but configure scripts thinks HT is enabled and a make compiles a HT-optimized binary.

**Comment by claudioandre-br** [comment]
FTR:
https://github.com/magnumripper/JohnTheRipper/commit/260bef1d2d2bd2ed7b252e216e3c5229eddceee3#commitcomment-14393003

**Comment by magnumripper** [comment]
The only thing that happens when configure thinks you have HT is a slightly different code path for bcrypt, nothing else. If bcrypt is indeed important to you, I recommend trying some hard-coded settings for `BF_X2` in `x86-64.h` and see which is better.

**Comment by solardiz** [comment]
The CPUID HT flag is incorrectly set on many CPUs. It indicates something like "some CPUs like this one support HT, even though this specific one might not, and we have no idea whether HT is enabled in this machine's firmware and OS". IOW, when Intel disables HT on their cheaper CPUs, they don't care to also disable the flag. They do disable the flag when the underlying die never supports HT, e.g. on their Atom lines of processors.

We should possibly rework our HT check, or alternatively I should rework the bcrypt code such that this won't matter.

**Comment by solardiz** [comment]
Meanwhile, can we possibly have our `configure` report `maybe` instead of `yes`? Just a cosmetic fix to avoid confusing people, and avoid spending their time on reporting this as a bug to us?

**Comment by magnumripper** [comment]
Fair enough, I'll fix that.
