### ISSUE TITLE
Rar2john produces a hash that JtR does not recognize

### ISSUE THREAD

**Issue by zekritek** [magnumripper/JohnTheRipper#3431]
```
root@instance-1:~/JohnTheRipper-bleeding-jumbo/run# ./rar2john firmware.rar > firmware_hash
! file name: enchilada_22_O.25_180915\enchilada_22_O.25_180915.ops

! file name: enchilada_22_O.25_180915\md5sum_pack.md5

! file name: enchilada_22_O.25_180915\MsmDownloadTool V4.0.exe

! file name: enchilada_22_O.25_180915\rev_OverSeas_180915_0000_release_disable_OTA-BLOCK_Signed_fp1809150000_cve2018-09-05_ufs_9.0

! file name: enchilada_22_O.25_180915


root@instance-1:~/JohnTheRipper-bleeding-jumbo/run# cat firmware_hash 
firmware.rar:$RAR3$*1*8e30fc8dc5da49b1*00000000*16*0*1*946d355878172d06c5f01731f250eabf*33:1::enchilada_22_O.25_180915\enchilada_22_O.25_180915.ops enchilada_22_O.25_180915\md5sum_pack.md5 enchilada_22_O.25_180915\MsmDownloadTool V4.0.exe enchilada_22_O.25_180915\rev_OverSeas_180915_0000_release_disable_OTA-BLOCK_Signed_fp1809150000_cve2018-09-05_ufs_9.0 enchilada_22_O.25_180915 


root@instance-1:~/JohnTheRipper-bleeding-jumbo/run# ./john --incremental=Digits --format=rar firmware_hash 
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```
Why don't work ?

```
root@instance-1:~/JohnTheRipper-bleeding-jumbo/run# ./john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-80eb4b39d0 2018-10-14 11:14:23 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 6.3.0
GNU libc version: 2.24 (loaded: 2.24)
Crypto library: OpenSSL
OpenSSL library version: 0100020cf
OpenSSL 1.0.2l  25 May 2017
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by magnumripper** [comment]
Looks like we get a supposed unpacked size of 0.

If possible, please email me the archive and I'll have a look. Otherwise, what's the output of `unrar vt firmware.rar`?

**Comment by zekritek** [comment]
https://s3.amazonaws.com/oneplussupport/OP6/enchilada_22_O.25_180915.rar
http://surl.me/vbhrf

**Comment by zekritek** [comment]
> Looks like we get a supposed unpacked size of 0.
> 
> If possible, please email me the archive and I'll have a look. Otherwise, what's the output of `unrar vt firmware.rar`?

**Comment by zekritek** [comment]
https://s3.amazonaws.com/oneplussupport/OP6/enchilada_22_O.25_180915.rar
http://surl.me/vbhrf

**Comment by magnumripper** [comment]
Fixed! Please update your tree and rebuild, then re-run rar2john and you'll get a correct hash.

Thanks for helping find and fix this.

**Comment by zekritek** [comment]
How to update my tree ?

**Comment by zekritek** [comment]
I can re-download all source, it's same update tree ?
Thanks.

**Comment by claudioandre-br** [comment]
> I can re-download all source, it's same update tree ?

Yes, it is. Just re-download and rebuild.

**Comment by zekritek** [comment]
Ok i try :)

Le mar. 16 oct. 2018 à 22:09, Claudio André <notifications@github.com> a
écrit :

**Comment by zekritek** [comment]
--2018-10-16 21:16:15--  https://codeload.github.com/magnumripper/JohnTheRipper/zip/bleeding-jumbo
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘bleeding-jumbo’

bleeding-jumbo                   [                 <=>                          ]  40.79M  7.47MB/s    in 5.7s    

2018-10-16 21:16:21 (7.10 MB/s) - ‘bleeding-jumbo’ saved [42772715]

**Comment by zekritek** [comment]
GOOD JOB !

root@inst:~/JohnTheRipper-bleeding-jumbo/run# ./john --incremental=ascii --format=rar enchihash 
Using default input encoding: UTF-8
Loaded 1 password hash (rar, RAR3 [SHA1 256/256 AVX2 8x AES])
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:07  0g/s 209.0p/s 209.0c/s 209.0C/s manielle1992..marlamoramer
0g 0:00:00:15  0g/s 209.7p/s 209.7c/s 209.7C/s manielateamo..shertballata
......

**Comment by awsaxf** [comment]
> [自由软件网站](https://s3.amazonaws.com/oneplussupport/OP6/enchilada_22_O.25_180915.rar)
> http://surl.me/vbhrf

Hello, what is the password for this file?

**Comment by zekritek** [comment]
I don't know, i know its 12 c
Il have try with random but nothing...

**Comment by awsaxf** [comment]
> I don't know, i know its 12 c
> Il have try with random but nothing...

Thank you! May be its source URL?

**Comment by magnumripper** [comment]
> i know its 12 c

How do you know that?

**Comment by awsaxf** [comment]
I am a oneplus6 user, I really want to get it!

**Comment by zekritek** [comment]
It's work for me :

https://androidfilehost.com/?fid=746163614322268729

https://mega.nz/#F!CfBG0IgZ!Gmnu6B-a7yFyvMLNw_pz8w

**Comment by zekritek** [comment]
12 c beacause i see when Oneplus open rar file on my computer.
Oneplus Can remonte control your pc for help when phone is BRICKED.
You Can contact Oneplus for debrick.

God Bless

**Comment by awsaxf** [comment]
> 12 c因为我看到Oneplus在我的电脑上打开rar文件。
> 当手机被打砖时，Oneplus可以重新控制你的电脑以获得帮助。
> 您可以联系Oneplus进行debrick。
> 
> 上帝保佑

Thank you!
