### ISSUE TITLE
Formats failing on non-X86

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3438]
**s390x**
Target CPU ................................. s390x, 64-bit BE
Build: linux-gnu 64-bit s390x  AC OMP

```
Testing: adxcrypt [IBM/Toshiba 4690 - ADXCRYPT 32/64]... (4xOMP) FAILED (cmp_all(1048576))
Testing: enpass, Enpass Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(32))
Testing: monero, monero Wallet [Pseudo-AES / ChaCha / Various 64/64]... (4xOMP) FAILED (cmp_all(4))
Testing: STRIP, Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(256))

4 out of 399 tests have FAILED
 FAILED: -test-full=0
```

**Comment by magnumripper** [comment]
Tezos doesn't say so in its algorithm_name, but it does include Blake2.

S390x is 64-bit big-endian, right?

**Comment by claudioandre-br** [comment]
**arm64**

```
Testing: argon2 [Blake2]... (4xOMP) FAILED (cmp_all(8))
Testing: Raw-Blake2 [BLAKE2b 512 32/64]... FAILED (cmp_all(1))
Testing: tezos, Tezos Key [PBKDF2-SHA512 128/128 NEON 2x]... (4xOMP) FAILED (cmp_all(128))

3 out of 403 tests have FAILED
 FAILED:  -test-full=0
```

**Comment by claudioandre-br** [comment]
> S390x is 64-bit big-endian, right?

Yes (I updated the description above).

**Comment by claudioandre-br** [comment]
**armhf**
Target CPU ................................. armv7l NEON, 32-bit LE
Build: linux-gnueabihf 32-bit armv7l NEON AC OMP
SIMD: NEON, interleaving: MD4:2 MD5:2 SHA1:1 SHA256:1 SHA512:1

```
All 403 formats passed self-tests!
 Ok: -test-full=0
```

**Comment by kholia** [comment]
@claudioandre-br `STRIP` format failing on `s390x` looks pretty weird to me. The format works well on a `POWER7 BE` system.

What is the value of `MIN_KEYS_PER_CRYPT` on that `s390x` machine?

Do you see something wrong with the code for the STRIP format?

**Comment by claudioandre-br** [comment]
> What is the value of MIN_KEYS_PER_CRYPT on that s390x machine?

It is non SIMD. The value is hard-coded `#define MIN_KEYS_PER_CRYPT      1`

**Comment by claudioandre-br** [comment]
Bug closed as:

* **Low Priority** - They have a tendency to become high priority if enough of the users complain.

* **Business Priority** - Obsolete hardware and software. Hardware nobody owns, etc.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action.
  * Can't reproduce, working as intended, obsolete.
  * Required information was not provided.
