### ISSUE TITLE
Tezos-OpenCL - Compute as one

### ISSUE THREAD

**Issue by madtomic** [magnumripper/JohnTheRipper#3441]
@kholia 
Thank you for your work on tezos-opencl

Standard command
../run/john --device=1 --test --format=tezos-opencl

My question is...

Is this something possible, I guess I am asking if multiple devices can compute as one, like a cloud gpu?

Like using this method to make all these devices work as one?

--device=0,1,2 

This would use 3 gpu and compute as it would be a single gpu

Regards, I hope to hear back from you.
madtomic

**Comment by kholia** [comment]
This is not a support forum, it's a bug tracker. If you don't understand the difference, please do NOT open an issue. For questions and support, join john-users at http://lists.openwall.com

We are not interested in bugs in your distro-supplied and/or several years old Jumbo. Please do not open an issue unless you tried the latest version from HERE first.

**Comment by madtomic** [comment]
Sorry,

Anyway the link you reference is invalid.

This site can’t be reached

lists.openwall.com’s server IP address could not be found.
Try:
Checking the connection
ERR_NAME_NOT_RESOLVED

But I found how to join the proper channel on the main site. Anyway, I just want to get a quick answer since you are the author of this commit in regards to parallel computation across more than one devices than doing separate work.

**Comment by solardiz** [comment]
Dhiru, please edit the template e.g. to say: "For questions and support, review recent postings on the john-users mailing list at https://www.openwall.com/lists/john-users/ and then subscribe to the list at https://www.openwall.com/john/#lists and post your message to the list by e-mailing john-users at lists.openwall.com."

@madtomic Yes, you can use `--devices=0,1,2 --fork=3` to use 3 GPUs, but please note that this specific format also makes a lot of use of the host CPU and thus has limited scalability. It probably won't fully utilize e.g. 8x V100's (like you can have on the largest AWS or GCP instances) even with tens of CPU cores, so no point in going for that kind of GPU power per rig for running this code. If you have any further comments or questions, please use the john-users mailing list. Thanks.
