### ISSUE TITLE
Issue with zip2john 

### ISSUE THREAD

**Issue by adrastee** [magnumripper/JohnTheRipper#3461]
Using Ubuntu 16.04, I followed install guide from git source.

```
JohnTheRipper-1.8.0-jumbo-1/run$ md5sum john  zip2john
164b49cd8de1c4557a87d594a0971758  john
164b49cd8de1c4557a87d594a0971758  zip2john
```

```
$ zip2john test.zip
test.zip:$pkzip2$1*..... -> OK
```

```
$ john test.zip
Warning: invalid UTF-8 seen reading test.zip
```
```
$ readlink -f zip2john
.../JohnTheRipper-1.8.0-jumbo-1/run/john
```

Calling the **same** executable with the **same** args, why the output is **different** ?

Thank you.

**Comment by claudioandre-br** [comment]
You are using JtR the wrong way. Use:
```
./zip2john test.zip > ~/hashfile
./john ~/hashfile
```
*****

Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:
- try to make your point clearer;
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by kholia** [comment]
> Calling the same executable with the same args, why is the output is different?

Neat trick, right? ;)

Look into the source code to see how this is done.

**Comment by adrastee** [comment]
Thank you @claudioandre-br  but my question was not how to use john, but how the zip2john symlink works.
@kholia got the point ,"Neat trick, right? ;)" : exactly !
This was my question, how a link to john car ouput differently. I'll get a look at the source code but I'm not an expert in C/C++  :/

**Comment by adrastee** [comment]
Fom john.c:
>  So if the command was "-external_command=gpg2john secring.gpg" then we will be setup in gpg2john mode with command line arg of secring.gpg

But:
```
$ ./john --external_command=zip2john test.zip
Unknown option: "--external_command=zip2john"
```

I missed something?

**Comment by kholia** [comment]
@adrastee Please re-read the following message.

`
This is not a support forum, it's a bug tracker. If you don't understand the difference, please do NOT open an issue. For questions and support, review recent postings on the john-users mailing list at https://www.openwall.com/lists/john-users/ and then subscribe to the list at https://www.openwall.com/john/#lists and post your message to the list by e-mailing john-users at lists.openwall.com.
`

For questions related to JtR code, use the `https://www.openwall.com/lists/john-dev/` mailing list instead.

@adrastee This is the third time you have been requested to not create similar GitHub issues. Please pay attention to this, and use mailing lists instead for support questions.
