### ISSUE TITLE
False positive from RAR3 method 33

### ISSUE THREAD

**Issue by dosoos** [magnumripper/JohnTheRipper#3477]
## john has show a not correct password for this hash:
`xxoo.rar:$RAR3$*1*0e274594823ffc58*f716602f*16*1*1*5d32536c597d7c4b0c99c73f910e49b9*33:1::xxoo.pdf`

## password is 13935466120/xl but not correct

**Comment by kholia** [comment]
### IMPORTANT ###

This is not a support forum, it's a bug tracker. If you don't understand the difference, please do NOT open an issue. For questions and support, review recent postings on the john-users mailing list at https://www.openwall.com/lists/john-users/ and then subscribe to the list at https://www.openwall.com/john/#lists and post your message to the list by e-mailing `john-users at lists.openwall.com`.

We are not interested in bugs in your distro-supplied and/or several years old Jumbo. Please do not open an issue unless you tried the latest version from HERE first.

**Comment by kholia** [comment]
https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/.github/issue_template.md

**Comment by magnumripper** [comment]
@dosoos do you mean the password john found can not be used to open the archive?

@kholia I'm not sure why you are closing these issues.

**Comment by claudioandre-br** [comment]
As a side note (CPU x OpenCL):

```
$ ../run/john ~/hash -wo:/home/claudio/solucao --mask=?w?a?a?a
../run/john: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ../run/john)
Warning: detected hash type "rar", but the string is also recognized as "rar-opencl"
Use the "--format=rar-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (rar, RAR3 [SHA1 128/128 AVX 4x AES])
Will run 32 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
1393546612067a   (xxoo.rar)
1g 0:00:00:07 DONE (2018-11-30 11:00) 0.1385g/s 460.9p/s 460.9c/s 460.9C/s 13935466120aaa..139354661201xa
Use the "--show" option to display all of the cracked passwords reliably
Session completed
``` 

```
$ ../run/john ~/hash -wo:/home/claudio/solucao --mask=?w?a?a?a --format=opencl
../run/john: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ../run/john)
Device 6: GeForce GTX TITAN X
Using default input encoding: UTF-8
Loaded 1 password hash (rar-opencl, RAR3 [SHA1 OpenCL AES])
Will run 32 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
13935466120/xl   (xxoo.rar)
1g 0:00:00:06 DONE (2018-11-30 11:02) 0.1666g/s 11264p/s 11264c/s 11264C/s GPU:70°C 13935466120$Qr..13935466120OCl
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by magnumripper** [comment]
I think compressed size is 16 and uncompressed is just 1. That is bound to give some false positives. I will look into it - possibly we need to ensure uncompressed size is at least 8 bytes or so (unless we have reliable padding but I'm pretty sure we can't use padding checks with m33).

**Comment by kholia** [comment]
> @kholia I'm not sure why you are closing these issues.

My bad.

1. I was in a hurry to finish off processing GitHub notifications.

2. I was biased by a poor report from the same user (https://github.com/magnumripper/JohnTheRipper/issues/3472), which wasted my time earlier.

**Comment by magnumripper** [comment]
```diff
diff --git a/src/rar_common.c b/src/rar_common.c
index 960a7de96..07d81ad96 100644
--- a/src/rar_common.c
+++ b/src/rar_common.c
@@ -650,6 +650,10 @@ inline static void check_rar(int count)
 					                         &cur_file->crc.c, 4);
 				else
 					cracked[index] = 0;
+
+				if (cracked[index])
+#pragma omp critical
+					dump_stuff_msg(get_key(index), plain, 16);
 			}
 		}
 	}
```
```
13935466120/xl : b01819e8 13812816 5b9af4dd 010061ec
1393546612067a : ef0b193c f0dc89e5 f31c7d6d 1998aa8e
``

**Comment by magnumripper** [comment]
Speaking of `omp critical`... I wonder if this can be some thread safety issue introduced with recent changes.

**Comment by claudioandre-br** [comment]
> @claudioandre-br I can crack it using 13935466120/xl but not 1393546612067a. That is strange and suggests the bug is something other than I thought.

This happened on super at (buggy, I see now):
```
Version: 1.8.0.13-jumbo-1-bleeding-83b40d6 2018-11-15 09:28:36 +0530
```
****
Comparing HEAD versus 83b40d6 (notice the session duration)
```
$ ../run/john ~/hash -wo:/home/claudio/solucao --mask=?w?a?a?a
../run/john: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ../run/john)
Warning: detected hash type "rar", but the string is also recognized as "rar-opencl"
Use the "--format=rar-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (rar, RAR3 [SHA1 128/128 AVX 4x AES])
Will run 32 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
13935466120/xl   (xxoo.rar)
1g 0:00:02:11 DONE (2018-12-01 01:03) 0.007595g/s 530.8p/s 530.8c/s 530.8C/s 13935466120*xl..13935466120@$l
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```
```
Press 'q' or Ctrl-C to abort, almost any other key for status
1393546612067a   (xxoo.rar)
1g 0:00:00:07 DONE (2018-12-01 01:09) 0.1324g/s 440.7p/s 440.7c/s 440.7C/s 13935466120aaa..139354661201xa
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by dosoos** [comment]
1393546612067a this is wrong password
13935466120/xl this is wrong password

## build info
```
root@home-gpuserver:/usr/local/JohnTheRipper-bleeding-jumbo/run# ./john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-2596bd7af4 2018-11-28 00:56:15 +0000
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.3.0
GNU libc version: 2.27 (loaded: 2.27)
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010007f
OpenSSL 1.1.0g  2 Nov 2017
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

## note's
For security reasons, I didn't post the original hash code. The hash code above just changed the name of the file. Does this affect the result? If so, I can give the original hash to you.

@magnumripper 
@claudioandre-br

**Comment by dosoos** [comment]
## cat pot file
```
cat /data/file/60day.hash.tmp1
$RAR3$*1*0e274594823ffc58*f716602f*16*1*1*5d32536c597d7c4b0c99c73f910e49b9*33:13935466120/xl
```

**Comment by magnumripper** [comment]
> For security reasons, I didn't post the original hash code. The hash code above just changed the name of the file. Does this affect the result? If so, I can give the original hash to you.

No, that's fine. It doesn't matter for results.

**Comment by magnumripper** [comment]
@claudioandre-br that's good news (I think) because we're probably back to my initial assessment that we're dealing with a 1-byte file and that's not reliable.

**Comment by magnumripper** [comment]
@dosoos I pushed what I hope is a workaround. Please update your tree, re-build and re-run rar2john, then try again. Please report the results here and if new "hash" isn't too long, please consider posting that here as well (possibly with file name redacted).

**Comment by dosoos** [comment]
ok! in this version for git `e322335852e37a517601eb3acef8417ed3f37e6a` (today latest version)
generate hash file content is:
`xxoo.rar:$RAR3$*1*0e274594823ffc58*c2245171*16*5*1*18e15e082d91d6b08046b879a639e27a*33:1::xxoo.pdf`

**Comment by magnumripper** [comment]
That looks good, we should be set now! Happy cracking.

**Comment by dosoos** [comment]
i have a requestion, i have some video encrypt hash file is too large maybe 10+MB size, this is Normal? @magnumripper

**Comment by claudioandre-br** [comment]
This question can be useful for more people. Please use the `john-users at lists.openwall.com` list, so everyone can access the answer.

**Comment by maryn23** [comment]
Hi. I have this hash bakend13.rar:$RAR3$*1*889fe52a22a92959*9631d757*32*15*1*2faaa3de9161ea370ec1fb9e511b88a2b7ba1ccf19d8666a896fc8c44b3b5c7c*33:1::

It's crazy I need the files. I'm using John but it's a never ending process because when I reach ten hours a new blackout happens here. Somebody help me pls. 
![john long process](https://user-images.githubusercontent.com/51274670/58754639-db47e080-84a2-11e9-974c-342527c407a2.jpg)
