### ISSUE TITLE
Set GWS to next LWS multiple larger than count

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3489]
We need to revert to the old "Set GWS to next LWS multiple larger than count" approach as per discussion in https://github.com/magnumripper/JohnTheRipper/issues/3386#issuecomment-444872621

**Comment by magnumripper** [comment]
Agreed. Last week has been an eye opener. I can still see some caveats with it and merits of the current method but as long as we decide that's how we do it, it's just a matter of ensuring kernels can handle it.

For performance with non full batches, it's obviously a no brainer.

**Comment by solardiz** [comment]
Thank you for all your work, magnum! I am supposed to be focused on certain other projects this month, but I greatly appreciate your effort and try to make time and comment where I feel my input could help.

**Comment by solardiz** [comment]
I doubt we can reasonably test a change like this in a week before release, so I'll change the target milestone here.

**Comment by solardiz** [comment]
@claudioandre-br @magnumripper Did PR #3725 fully take care of this issue? Should we close this issue?

**Comment by claudioandre-br** [comment]
> Did PR #3725 fully take care of this issue? 

No. In fact there is no relationship between them.

**Comment by magnumripper** [comment]
I could try reverting a few commits from back then. All that reverts cleanly (should be dang near all) will need to re-testing (in fact they're more tested before that change than after). If my time allows...

**Comment by magnumripper** [comment]
s/to/no/
