### ISSUE TITLE
create coding-style.txt

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#350]
* create coding-style.txt

* look into commit hooks

**Comment by magnumripper** [comment]
@loverszhaokai I saw this issue when looking over old ones. Perhaps some tidbits you can use here?

**Comment by magnumripper** [comment]
Hmm lots of things mentioned here that should be in devel docs. Reopening.

**Comment by magnumripper** [comment]
Closing again, but referring that other issue here
