### ISSUE TITLE
implement ssh private key cracking on the GPU

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#351]
Implement ssh private key cracking on the GPU
- AES decryption on the GPU
- BER / DER decoding on the GPU

@gat3way want to join forces on this one?

**Comment by kholia** [comment]
This issue is about porting the "simple MD5" based KDF and decryption verification to OpenCL.

This is a fast format so we will need GPU side mask support.

**Comment by kholia** [comment]
We have all the required pieces now (OpenCL side ASN.1, DES, AES, and MD5).

We just need a person now who understands GPU side mask stuff (aka @magnumripper) :-)

**Comment by magnumripper** [comment]
Not quite sure GPU-side mask is needed. We'll see.

**Comment by kholia** [comment]
This is sort-of done now.
