### ISSUE TITLE
krb5 cache extract

### ISSUE THREAD

**Issue by FuckAllWorld** [magnumripper/JohnTheRipper#3524]
DC:Windows Server 2008 R2
Client:Ubuntu 16.04

python ccache2john.py /tmp/krb5cc_0

WARNING: Not all the hashes generated by this program are crackable. Please select the relevant hashes manually!
Unsupported etype 18 found. Please report this to us!

**Comment by kholia** [comment]
Thanks for reporting this.

It seems (not yet proven) that it is not possible to crack such hashes. See https://github.com/magnumripper/JohnTheRipper/issues/2809 for details.

I will remove this notice message soon.
