### ISSUE TITLE
dynamic_big_crypt.c in unused is not up to date

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#3538]
This file should be copied into unused from the scr directory after a successful build, AFTER the *.cin file is updated.  They were updated (by me) a while back, removing the undef of SIMD defines when building under a BE system.   I failed to update the correctly built 'unused' file, and need to do this.

**Comment by magnumripper** [comment]
I removed the "invalid" label, it's used for invalid issues/PEBCAK things
