### ISSUE TITLE
john tell me a not correct password for rar hash file

### ISSUE THREAD

**Issue by dosoos** [magnumripper/JohnTheRipper#3546]
## this hash file content:
```
xxooxxoo.file:$RAR3$*1*0bccfc9ac77a7463*45cf6ce9*16*1*1*8688300510aacc3da8c0c424e19d0875*33:1::xxoo.php
```
john tell me this hash password is `chuncg`, but i try use this password to open rar file is wrong! Some time ago i create #3477 issue, but i think this issue still exist. @magnumripper

**Comment by dosoos** [comment]
## john version

`# john
John the Ripper 1.8.0.13-jumbo-1-bleeding-4e905e839 2018-12-21 10:49:26 +0100 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2018 by Solar Designer and others
Homepage: http://www.openwall.com/john/`

**Comment by dosoos** [comment]
correct hash is:
`xxooxxoo.file:$RAR3$*1*0bccfc9ac77a7463*45cf6ce9*16*1*1*8688300510aacc3da8c0c424e19d0875*33:1::CMT xxoo.php`

**Comment by magnumripper** [comment]
That is strange, it shouldn't pick that file unless it's the only file in the archive. Is the archive very big or could you mail it to me?

**Comment by dosoos** [comment]
yeah! this file 50+MB, i can send this file for email to you. send mail success! please check receive

**Comment by magnumripper** [comment]
Thanks! From that file I got this hash from current rar2john
```
$RAR3$*1*0bccfc9ac77a7463*afea634e*32*14*1*0a7654d0695d93d924b5b48acd2bbb4cf914b167a608f3fcf2694a751f60f1f5*33:1
```
That looks good to me, it's two blocks of AES and an unpack size of 14. Did you somehow use an older rar2john?

**Comment by dosoos** [comment]
oh, sorry, i am forget generation this hash file of john is not latest john version

**Comment by magnumripper** [comment]
No problem @dosoos, it's a good thing we got this tested well. Don't hesitate to post any further problems 👍
