### ISSUE TITLE
bug in fgetl/fgetll  (misc.c)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#3574]
In the case we read a null byte in the stream, the code does not check after the null byte, looking for the \n (followed by a null), up to size, before starting to read byte/byte from the stream, looking for the \n.

Thus, if we have this file:

here is \0line 1\n
here is line 2\n
here is line 3\n
...

on call #1 to fgetl/fgetll, we get "here is "   On call 2, we get "here is line 3" missing the line "here is line 2" completely.

One other bug found.  fgetll would return the original pointer, in a long line, of that long line had a NULL byte in it, even though we have allocated a buffer (which the caller must free).  Memory leak, and we are returning a shorter section of the line.

**Comment by solardiz** [comment]
I noticed this issue and intend to look into it in core's context later.

**Comment by jfoug** [comment]
The change is actually pretty trivial, and safe.  Once you put logic in which was triggered by a short line that did not end in a \n, it will 'known' that the line had at least 1 embedded NULL.  Then simply walk the buffer of 'actual' read data.  If the \n is seen, then the call is done.  No need to read any more from the file.  Now, IF the line was full length, and did not contain a \n, then what we have is a line that is TOO long for our buffer. That's ok, and we simply read more data (throwing it way), until we he that \n EOL byte (or run out of file).
