### ISSUE TITLE
Files in ztex directory are all \r\n EOL

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#3582]
It seems all source files in ztex (or at least MANY of them), are DOS EOL files  (\r\n).

**Comment by jfoug** [comment]
This is a quick 1 liner to find crlf. I have this in a script, so I can ask for any wildcard type, or leave it blank and get my entire tree checked, and check often, since some of my tools will screw up files, when I cut/paste from sources like out of emails or browser.   I am used to seeing john.asm as a known \r\n, and leave it alone, since it is ONLY built by older Borland TASM/TLINK, which may need the \r\n, I am not sure.

#cat ~/bin/fnd_crlf
```sh
#!/bin/sh
grep --color=auto -lIUr "^M" $*
```

Note the ^M  is "ctrl-v crtl-m" (to actually embed the \r character into the script).

**Comment by magnumripper** [comment]
That's known and correct. I believe `.editorconfig` specifies them as well.

**Comment by magnumripper** [comment]
#2484

**Comment by jfoug** [comment]
Ok, not a problem  Just pointing out what I recently saw.  I was surprised that the .c files having DOS \r\n was allowed.  I was not sure about the other types of files (based on file extension) on whether they needed \r\n or not, but the c source seemed funny.
