### ISSUE TITLE
WPAPSK fixes for UTF-8

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3593]
1. In real life, people use UTF-8 in WPAPSK passphrases. The standard said printable ASCII last time I checked but might have been amended to allow it. The latter isn't important as long as it's seen in the wild.
2. The min_len is 8, but I've seen several cases where that is 8 **bytes** so it might be as little as 2 UTF-8 characters of 4 bytes each.

- [ ] Set `FMT_8_BIT`
- [ ] If selected target encoding is UTF-8, decrease min_len to 2.

**Comment by frank-dittrich** [comment]
I think sooner or later we need to add a check for length in bytes.
I don't think UTF-8 characters represented by 4-6 bytes are represented in any single-byte code page, so in this case min. length 3 instead of 2 should be OK, no?

**Comment by magnumripper** [comment]
Not sure what you mean now. If using a legacy encoding, bytes length == character length.
