### ISSUE TITLE
Unit Tests running when it shouldn't

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3601]
When a user builds JtR (a SIMD binary) to run in another machine [1], the build will fail due to invalid instructions in the "Unit Tests" binary.

```
Configure finished.  Now "make -s clean && make -sj4" to compile.
Now Running the Unit Tests
make: *** [../run/unit-tests] Illegal instruction (core dumped)
make: *** Deleting file '../run/unit-tests'
Makefile:1667: recipe for target '../run/unit-tests' failed
```
[1] e.g. `CPPFLAGS="-mavx2"` on super.

**Comment by magnumripper** [comment]
Doh. That's because such build isn't quite a cross compile, in autoconf sense. Not sure how to fix this without just dropping the automagic unit tests for all builds 😢

**Comment by magnumripper** [comment]
I wish we could do better, but after 9e0659a at least `--disable-native-tests` works,
