### ISSUE TITLE
John isn't listing all cracked passwords

### ISSUE THREAD

**Issue by Slad3G** [magnumripper/JohnTheRipper#3618]
### Steps to reproduce ###
As part of our reporting effort we like to give cracked password statistics to our clients. I can get accurate results, JtR will list every cracked password to stdout and the pot file,  if I don't load my custom large wordlist and just run:
`john <$hashfile> --format=<$format> --pot=<$pot>`

Running the same command with an 8GB wordlist only cracks a repeated hash once which skews my stats. The hashes are an acquired ntds.dit file and the individual lines are unique though several hashes are identical.

`john <$hashfile> --format=<$format> --pot=<$pot> --wordlist=<$largewordlist>`

### System configuration ###
I am running JtR on a Kali 2018.4 instance in an ESXi VM with mutliple cores
- `$ ./john --list=build-info`.

```
Version: 1.8.0.13-jumbo-1-bleeding-8c39fa882 2019-01-05 20:21:19 +0100
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 8.2.0
GNU libc version: 2.28 (loaded: 2.28)
Crypto library: OpenSSL
OpenSSL library version: 01010101f
OpenSSL 1.1.1a  20 Nov 2018
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by magnumripper** [comment]
The correct way of showing all cracked passwords is doing `john --show` afterwards. There are warnings/notices telling you this. Is this not what this is about?

**Comment by Slad3G** [comment]
Thanks for the quick response. No the --show is also not accurate but I am talking about the stdout that prints on the screen. Using --show displays the following:
`0 password hashes cracked, 31 left`

This is inaccurate, of the 31 hashes I have cracked 25 of them.

**Comment by solardiz** [comment]
Maybe we should improve this FAQ answer or add another Q/A specifically for `--show`. As it is, this Q/A is too focused on initially loading the file for cracking, essentially relying on the runtime `Warning` for the `--show --format=...` step.

**Comment by Slad3G** [comment]
@solardiz thanks for pointing out my --show error, that element of what I submitted was indeed just my issue. I am familiar with JtR and simply forgot the format argument as I was checking what @magnumripper posted earlier. 

Rerunning with the large wordlist has confirmed that JtR is simply not outputting to stdout when I use my large wordlist but that the .pot file does contain the accurate cracked statistics.

`27 password hashes cracked, 4 left`

While this may be a "works as intended" JtR has not displayed this behavior during the past 10+ years I have used it and has output every cracked line to stdout up until now. I am fine with pulling stats from the .pot moving forward using.
`--show --format=<$format>` 

Thanks for continuing to build and support a great tool. If I can be of any assistance with the FAQ I'd be happy to volunteer.

**Comment by magnumripper** [comment]
> While this may be a "works as intended" JtR has not displayed this behavior during the past 10+ years I have used it

I'm willing to satisfy your needs but I'm not quite understanding the issue at hand. What has changed?

**Comment by Slad3G** [comment]
@magnumripper when I am cracking without my large custom wordlist, JtR outputs every cracked password, including recurrences of the same hash, on the screen. When I use my large wordlist it only displays one iteration of the recurring hash on the screen but it does accurately populate the .pot file I have specified. This is a behavior that wasn't present in previous uses of JtR that I am only noticing now. Is that a sufficient explanation or am I still missing the mark here?

Thanks,

S

**Comment by Slad3G** [comment]
@frank-dittrich  thanks for your response, I listed the commands in the original posting and, in my experience, this is a new behavior. Each line of the NTDS.dit file I am cracking is unique although many users use the same password. To further clarify, the username on several lines of the file is different but all other information is identical (domain, blank LM, NTLM). Using my larger 8GB wordlist only the first instance of the hash is cracked and output to the screen but all instances are accurately cracked in the pot file. This is not a big deal, I just preferred being able to see everything print to the screen when giving talks or demonstrations.

I would be happy to set up a webex to demonstrate what I'm seeing if that would help.  I'm also happy to not have this further addressed as I can retrieve what's needed fron the pot file.

Thanks again,

S

**Comment by Slad3G** [comment]
@solardiz In your earlier post you stated

> Maybe we should improve this FAQ answer or add another Q/A specifically for --show. As it is, this Q/A is too focused on initially loading the file for cracking, essentially relying on the runtime Warning for the --show --format=... step.

I was only offering to assist if it would be helpful. Thank you for your further clarification and the support you provide for a great tool. Is it acceptable for me to close this non-issue?

**Comment by solardiz** [comment]
Oh, yes, I might "improve this FAQ answer or add another Q/A specifically for --show" next time I'm making edits nearby.

Yes, let's close this non-issue.
