### ISSUE TITLE
Standardize password & salt lengths for benchmarks

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3625]
Originally written as comment https://github.com/magnumripper/JohnTheRipper/issues/3620#issuecomment-459318786

Our default benchmarks should ideally be for length 7 in general, which is what Hashcat uses, and we should use same salt lengths that Hashcat uses - I think that's 8 for md5crypt and sha256crypt.

However, for many formats (any sane) password lengths don't significantly affect performance, and for those we can use arbitrary lengths (such as whatever we have now).

I think our priority (for these benchmark changes) should be md5crypt and sha256crypt formats (CPU, OpenCL, ZTEX), where our benchmark speeds closely reflect actual cracking speeds, but performance varies by password and salt length a lot.

We should start by deciding on and testing an approach to limiting the benchmarks to a few test vectors while having and using more test vectors for the self-test.

**Comment by magnumripper** [comment]
Benchmark for salted formats already use the only first two test vectors, doesn't it?

**Comment by solardiz** [comment]
I thought it was only the first two test vectors for the benchmarks, and their corresponding candidate password lengths, but putting two same-length passwords as first two test vectors for md5crypt-opencl didn't result in `--test` speeds I expected to see for same-length passwords. It resulted in speeds typical for mixed-length passwords.

**Comment by solardiz** [comment]
I think I figured it out. We use salts from the first two test vectors, but we use plaintexts of lengths like in all test vectors (and additionally we might occasionally truncate at a lower length if XOR'ing by `index & 127` results in a NUL - we should probably remove that non-intuitive behavior).

Also, our current `md5crypt-opencl` benchmark is for single salt only, which is a setting we probably inherited from the corresponding CPU format, but in the OpenCL format we should also benchmark for many salts since that keeps the transfer to device out of the loop. This is easy by changing `BENCHMARK_LENGTH` from -1 to 0, but I think ideally we should introduce the support for `BENCHMARK_LENGTH` actually dictating the exact length while also retaining the one vs. many salts benchmarks. Right now, if we set `BENCHMARK_LENGTH` to a value other than -1 or 0, it specifies a threshold length for short vs. long password benchmarks, and this replaces the one vs. many salts benchmarks - not what we want here.

So maybe introduce support for specifying e.g. 0x107 to mean exactly length 7.

**Comment by solardiz** [comment]
I think we took care of this issue by now: we specify password lengths for benchmarks via `benchmark_length`, and we know we use first two test vectors' salts, so we should arrange the test vectors accordingly - and we already did that for md5crypt and md5crypt-opencl, at least.
