### ISSUE TITLE
rar2john - hash output almost twice size of rar archive

### ISSUE THREAD

**Issue by se7enten** [magnumripper/JohnTheRipper#3653]
The file is vk.com.rar which is from Collection 3 of the Collection 1-5 leaks. At the bottom of this post are some links regarding these files but it is only necessary if you would like to track down the vk.com.rar file that I am having problems with. I can also supply the file if necessary.

When I run rar2john on the 2.3GB file the output is a long hash that is 4.5GB in size. 

### Steps to reproduce ###
```
$ du -hs vk.com.rar 
2.3G	vk.com.rar
```

```
$ /path/to/john/run/rar2john vk.com.rar > vk.com.rar.hash
! file name: Vk.com.txt
```

```
$ du -hs vk.com.rar*
2.3G	vk.com.rar
4.5G	vk.com.rar.hash
```

```
$ cat vk.com.rar.hash
vk.com.rar:$RAR3$*1*a34ed3cc5fcff92c*2be76e30*2376825872*8108047240*1*b72aa6e27a6b91aaf90bbfdd5a6637deca982e8369f47cfe055c7091cc0a33dc454d31f8da74634ec22e4e5494dc1f354b1b891ea
aea3a58fa9110af40f517883826885fabdbb1980e0c75248384769931e[cut this goes on for 4.5GB]
```

here is a larger snippet: https://www.hastebin.com/adodixakex.md

```
$ /path/to/john/run/john --incremental=Digits --format=rar vk.com.rar.hash 
Killed
```

```
$ unrar vt vk.com.rar

UNRAR 5.50 freeware      Copyright (c) 1993-2017 Alexander Roshal

Archive: vk.com.rar
Details: RAR 4

        Name: Vk.com.txt
        Type: File
        Size: 8108047240
 Packed size: 2376825872
       Ratio: 29%
       mtime: 2016-06-15 01:38:51,092254700
  Attributes: ..A....
       CRC32: 306EE72B
     Host OS: Windows
 Compression: RAR 3.0(v29) -m5 -md=4M
       Flags: encrypted 
```

### System configuration ###

```
$ /path/to/john/run/john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-1bc69682c 2019-02-16 12:37:51 +0100
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is /path/to/john/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.3.0
GNU libc version: 2.27 (loaded: 2.27)
Crypto library: OpenSSL
OpenSSL library version: 01010007f
OpenSSL 1.1.0g  2 Nov 2017
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

I apologize in advanced if these links are not allowed.

https://www.zdnet.com/article/security-firm-identifies-hacker-behind-collection-1-leak-as-collection-2-5-become-public/
https://www.troyhunt.com/the-race-to-the-bottom-of-credential-stuffing-lists-and-collections-2-through-5-and-more/
https://raidforums.com/Thread-Collection-1-5-Zabagur-AntiPublic-Latest-120GB-1TB-TOTAL-Leaked-Download

Thanks

**Comment by magnumripper** [comment]
This is normal. Basically we need to have the data from the smallest (in this file the only) file in the archive, and since we hex encode it, it get's exactly twice the size. We should change to Base64 at some point (I do have such patch somewhere) though, that will be a little better.

**Comment by se7enten** [comment]
should i open a new issue for this part?  is this expected?  sorry to reply to a closed thread.


```
$ /path/to/john/run/john --incremental=Digits --format=rar vk.com.rar.hash 
Killed
```

**Comment by magnumripper** [comment]
An educated guess is your processed is killed by the kernel OOM-killer because you have too little available memory to process the data. If you can replicate it on some machine with, say, 16 GB plus adequate swap space, feel free to re-open.

**Comment by magnumripper** [comment]
I just confirmed that JtR ate 11 GB or more (I was merely watching top(1) output) during loading and then about 7 GB during the rest of a crack session, running 8 threads. You can probably get away with just 8 GB RAM + a lot of swap.

**Comment by PROger4ever** [comment]
@se7enten, I look for the password to open that archive too. Have you found it? Send me a message to proger4ever@gmail.com or to write to me on facebook.com/PROger4ever
Thanks for your understanding and your help ;-)
I'll delete this message after we are got in touch.
