### ISSUE TITLE
Clarify error `fopen: $JOHN/john.conf: No such file or directory`

### ISSUE THREAD

**Issue by danielsokolowski** [magnumripper/JohnTheRipper#3670]
### Steps to reproduce ###
This is not a bug, it's a request to clarify the `fopen: $JOHN/john.conf: No such file or directory` which is generated when JrT is not built as a system-wide install and is executed outside of build directory. The 

It's in response to: https://github.com/magnumripper/JohnTheRipper/issues/2820#issuecomment-471917775

`$JOHN` name and error implies a system environment variable that need setting but doing so of course does not work and does result in lost time researching by the end user. 

Possibly the error message should mention that john should be run from within the directory it was installed in and that it was built is not a system-wide installation. 

Thank you kindly for considering my submission. 

### System configuration ###
```
Linux tardis 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
root@tardis:/usr/local/JohnTheRipper# ./john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-649bb4a33 2019-03-09 09:06:23 +0100
Build: linux-gnu 64-bit x86_64 SSSE3 AC OMP
SIMD: SSSE3, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: SSSE3
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 6.3.0
GNU libc version: 2.28 (loaded: 2.28)
Crypto library: OpenSSL
OpenSSL library version: 0101000af
OpenSSL 1.1.0j  20 Nov 2018
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
root@tardis:/usr/local/JohnTheRipper# ./john --list=opencl-devices
Section [opencl-devices] not found.
help[:WHAT], subformats, inc-modes, rules, externals, ext-modes, ext-hybrids,
ext-filters, ext-filters-only, build-info, hidden-options, encodings,
formats, format-details, format-all-details, format-methods[:WHICH],
format-tests, sections, parameters:SECTION, list-data:SECTION,
<conf section name>
```

**Comment by magnumripper** [comment]
There are various ways we could enhance this. First, we could actually start honoring `$JOHN` as an environment variable. That could end up very confusing though, probably not a good way to go. Second, we could simply enhance the messages in various ways. One way might be to simply `path_expand()` the file name before printing it.

**Comment by danielsokolowski** [comment]
Much obliged, and be great.
