### ISSUE TITLE
SSE4.2 CPU-detection for 32-bit intel builds are broken

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3678]
I mean, at least, drop what makes the source code harder to maintain:
- x86.*
- SIMD fallback on 32bits
- workarounds needed on 32 bit builds (e.g. #600, #3587, #1331, ...)

**Comment by magnumripper** [comment]
Not sure what you mean with "fallback for 32 bits" - do we have that? For the rest I think it's better to keep 32-bit stuff at least until it interferes with some specific future change or cleanup. For example, a Raspberry Pi build is usually 32-bit for the time being. A Pi is obviously not a potent cracking platform but it has specific uses eg. for wardriving.

#600 IIRC actually added an abstraction layer for many variants of 64-bit fseek/ftell/etc that we might need for 64-bit builds anyway (i.e. where "long" is 32-bit), while the last resort 32-bit code is just plain POSIX.

**Comment by solardiz** [comment]
I'm with magnum on this. I think we shouldn't hurry to drop 32-bit related things.

x86.S contains some crypto code for old CPUs, but it also contains CPU detection. The crypto code comes from core and doesn't take much effort to keep in jumbo. And we need the CPU detection for 32-bit builds with modern SIMD instruction sets, so that those builds can complain if their target SIMD instruction set is missing on a given system. I think this could still be relevant e.g. in builds for Win32, or are we going to discontinue those very soon?

**Comment by claudioandre-br** [comment]
> CPU detection for 32-bit builds 

CPU detection is not working on 32btis since SSE4.2 detection was introduced.

**Comment by magnumripper** [comment]
> CPU detection is not working on 32btis since SSE4.2 detection was introduced.

It isn't? Where's the issue for that? We've gotta fix that before a release.

**Comment by claudioandre-br** [comment]
> It isn't? 

Yes. You fixed it in #3119, then you introduced SSE4.2 and broke it again.

> Where's the issue for that? 

I haven't created one. 

Although 32bits may still be useful, no need to create a package that is able to fallback, me thinks. Note that nobody noticed this bug.

**Comment by magnumripper** [comment]
So how is it broken? Does it report SSE4_2 where it isn't available, or the other way round?

**Comment by claudioandre-br** [comment]
>  Does it report SSE4_2 where it isn't available, or the other way round?

I think so. But how can we test this now?

**Comment by magnumripper** [comment]
> how can we test this now?

Perhaps in a VM where we can decide what to support. Or perhaps using the garage laptop I use for upgrading maps in my motorcycle: I recently found out it's not even 64-bit (which surprised me, along with the ridiculous RAM amount of 2 GB) and if memory serves me it has SSE 4.1 or not even that. It's a Thinkpad X41 or something like that.

**Comment by claudioandre-br** [comment]
FTR: the test failed on Windows (I don't have 32bit Linux package).

**Comment by magnumripper** [comment]
That old laptop of mine doesn't even have SSSE3, it doesn't trigger any bug.

**Comment by magnumripper** [comment]
I tried a number of builds on that 32-bit SSE2-only laptop. Many problems. Apparently we get x86-any.h as arch.h and that one is outdated. Fixing that manually (simply linking to x86-sse2.h instead) doesn't make things much better: I either get no CPU detection at all, or build fails 😢

**Comment by solardiz** [comment]
FWIW, I did test latest core on 32-bit SSE2, MMX, and "any", and it works fine with the x86-sse.h and x86-any.h files currently in core.

**Comment by claudioandre-br** [comment]
I wouldn't say it is that bad.
```
config.status: creating Makefile
config.status: creating aes/Makefile
config.status: creating aes/aesni/Makefile
config.status: creating aes/openssl/Makefile
config.status: creating secp256k1/Makefile
config.status: creating ed25519-donna/Makefile
config.status: creating escrypt/Makefile
config.status: creating autoconfig.h
config.status: linking x86-sse.h to arch.h
config.status: executing default commands
configure: creating ./fmt_externs.h
configure: creating ./fmt_registers.h
Configured for building John the Ripper jumbo:
Target CPU ................................. i686 SSE2, 32-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-sse.h
``` 

https://ci.appveyor.com/project/claudioandre-br/johntheripper/build/job/kt3hu5j2mfna0x8i?fullLog=true

**Comment by magnumripper** [comment]
Maybe I got x86-any.h because I used eg. `--enable-simd=sse4.2`

**Comment by solardiz** [comment]
Do we need to keep this issue open and in "pending verify"? Who would realistically bother verifying this just because we have the issue open and hanging? Even if someone does verify the fix, it'd probably be accidental - because they actually build for a relevant system. So I'll close this.
