### ISSUE TITLE
macOS Mojave 10.14.2 build error with Homebrew "ar" producing wrong architecture files

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3687]
As seen in https://www.openwall.com/lists/john-users/2019/03/25/12:

It looks like "ar" is somehow creating archives for a wrong architecture.  This is puzzling to me because historically "ar" was a very simple archiver and technically not necessarily used for static libraries (and thus wouldn't need to be architecture-aware), although that ended up being its sole use case.

```
ar: creating aes.a
ar: creating ed25519-donna.a
ar: creating secp256k1.a
ld: warning: ignoring file aes/aes.a, file was built for archive which is not the architecture being linked (x86_64): aes/aes.a
ld: warning: ignoring file ed25519-donna/ed25519-donna.a, file was built for archive which is not the architecture being linked (x86_64): ed25519-donna/ed25519-donna.a
ld: warning: ignoring file secp256k1/secp256k1.a, file was built for archive which is not the architecture being linked (x86_64): secp256k1/secp256k1.a
Undefined symbols for architecture x86_64:
  "_ed25519_publickey", referenced from:
```

**Comment by magnumripper** [comment]
```
$ which ar
/usr/bin/ar

$ grep '\bar\b' Makefile
AR = ar
```
I never saw this problem. I'm at 10.14.3 now but I ran 10.14.2 as well. I guess https://www.openwall.com/lists/john-users/2019/03/26/2 nails it.

Perhaps we could somehow have autoconf pick `/usr/bin/ar` over the one in `$PATH` in this case - I'm just not sure what to test for. I guess I never had brew's binutils installed.

**Comment by magnumripper** [comment]
We could opt to just mention the problem and solution in doc/INSTALL

**Comment by magnumripper** [comment]
```
$ brew info binutils
binutils: stable 2.32 (bottled) [keg-only]
GNU binary tools for native development
https://www.gnu.org/software/binutils/binutils.html
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/binutils.rb
==> Caveats
binutils is keg-only, which means it was not symlinked into /usr/local,
because because Apple provides the same tools and binutils is poorly supported on macOS.

==> Analytics
install: 9,178 (30 days), 18,053 (90 days), 71,780 (365 days)
install_on_request: 7,181 (30 days), 14,433 (90 days), 54,933 (365 days)
build_error: 0 (30 days)
```
Even if a user installed binutils, the problem wouldn't happen unless user also went against the recommendations and manually linked it into path.

**Comment by solardiz** [comment]
I think we just need to be aware of the external issue for now, and close this issue here. We can reopen and see if we should do anything on it in case the user reports the advice didn't help, this becomes a frequent user complaint, or something new is uncovered. Thanks!
