### ISSUE TITLE
why have this issue? Error: --device must be between 1 and 8 (the number of devices available).

### ISSUE THREAD

**Issue by dosoos** [magnumripper/JohnTheRipper#3693]
`
# nvidia-smi
Wed Mar 27 07:51:32 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.116                Driver Version: 390.116                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  P106-100            Off  | 00000000:01:00.0 Off |                  N/A |
| 29%   38C    P0    28W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  P106-100            Off  | 00000000:03:00.0 Off |                  N/A |
| 29%   40C    P0    28W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  P106-100            Off  | 00000000:04:00.0 Off |                  N/A |
| 29%   40C    P0    28W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  P106-100            Off  | 00000000:05:00.0 Off |                  N/A |
| 29%   39C    P0    29W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  P106-100            Off  | 00000000:06:00.0 Off |                  N/A |
| 29%   38C    P0    29W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  P106-100            Off  | 00000000:07:00.0 Off |                  N/A |
| 29%   38C    P0    28W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  P106-100            Off  | 00000000:08:00.0 Off |                  N/A |
| 29%   37C    P0    28W / 120W |      0MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  P106-100            Off  | 00000000:09:00.0 Off |                  N/A |
| 29%   36C    P0    28W / 120W |      0MiB /  6080MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

`
# john --format=RAR5-opencl --fork=8 --devices=0,1,2,3,4,5,6,7 --pot=xx.pot --wordlist=xx.txt xx.hash
Using default input encoding: UTF-8
Loaded 1 password hash (RAR5-opencl [PBKDF2-SHA256 OpenCL])
Cost 1 (iteration count) is 32768 for all loaded hashes
Node numbers 1-8 of 8 (fork)
Error: --device must be between 1 and 8 (the number of devices available).
Error: --device must be between 1 and 8 (the number of devices available).
Error: --device must be between 1 and 8 (the number of devices available).
Error: --device must be between 1 and 8 (the number of devices available).
Error: --device must be between 1 and 8 (the number of devices available).
Error: --device must be between 1 and 8 (the number of devices available).
Error: --device must be between 1 and 8 (the number of devices available).
Error: --device must be between 1 and 8 (the number of devices available).
`

this my john version
# john
John the Ripper 1.8.0.16-jumbo-1-bleeding-4840892d68 2019-03-26 21:33:03 -0300 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2019 by Solar Designer and others
Homepage: http://www.openwall.com/john/

**Comment by dosoos** [comment]
just crack rar file have this question, zip hash is ok

**Comment by dosoos** [comment]
use --fork and remove --devices is ok! close this issue

**Comment by magnumripper** [comment]
You could also have changed `--device=0,1,2,3,4,5,6,7` to `--device=1,2,3,4,5,6,7,8` like the output suggested.
