### ISSUE TITLE
zip2john for this file, not generation any hash

### ISSUE THREAD

**Issue by dosoos** [magnumripper/JohnTheRipper#3694]
this command
`
# ./zip2john ../1553675821.5.zip
`
response no thing

this file download url:
https://drive.google.com/open?id=11S7X7HvUbDrJlqjc56FStfRuQ7eptqNE

this file is zip encrypt file

**Comment by dosoos** [comment]
sorry, this file changed extend name, have what tools can analysis file type without file suffix file name

**Comment by magnumripper** [comment]
Yes, that file is a RAR archive. This is not a support forum, please only report bugs here.
