### ISSUE TITLE
Bring x86-64.h and x86-sse.h closer to core's

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3696]
Especially after the recent core update and merge, jumbo's x86-64.h and x86-sse.h are significantly different from core's in unnecessary ways.

There are some real bugs, too - e.g., `DES_BS` is never set to 4 (so `sboxes-t.c` is never used - but it should be on AVX-512), x86-sse.h tries to use 256-bit XOP (which it calls "XOP2") whereas DES_bs_b.c no longer includes support for that, there are redefinitions of `CPU_FALLBACK_BINARY` on some builds (are likely to result in build-time warnings). These are just things I noticed when skimming the files. There are probably many more issues.

Of course, trying to bring these files closer to core's is a change relative to what we had tested in jumbo, and might introduce new bugs too, but at this point I think we should go for it.

**Comment by solardiz** [comment]
Specifically, I suggest to start with versions of these files from core and then re-introduce new implementations (consistent with core's) of whatever changes are actually needed in jumbo (such as for the extra SSE* levels). This might also require minor edits to the .S files - such as for `#if` vs. `#ifdef` for `CPU_REQ_*` - bringing them closer to core's, too.

As an option, this effort can be split into two steps: first fix two major bugs I mentioned above, then work on bringing the files closer to core's.

**Comment by magnumripper** [comment]
Making it closer to core's isn't very straightforward because that file is so DES-centric. We need CPU_DETECT, CPU_REQ, CPU_REQ_XX, CPU_NAME and CPU_FALLBACK_BINARY_DEFAULT for other things as well. Having said that, I'm reviewing them.

**Comment by solardiz** [comment]
I don't see a problem with defining the `CPU_*` things inside the DES-centric if/elif/else/endif's, yet using those SIMD instruction sets in non-DES formats as well. This might be unclean, but it will help bring the files in core and jumbo closer and avoid duplicate if/elif/else/endif chains (or equivalent) for DES_* and CPU_*.

Well, the SSE* flavors are the same thing for DES, so perhaps there might be an inner if/elif/else/endif chain for those inside the SSE2 block for DES.

**Comment by magnumripper** [comment]
> I don't see a problem with defining the CPU_* things inside the DES-centric if/elif/else/endif's

They will all be turned off for non-gcc AVX+ builds, resulting in SSE2...

**Comment by solardiz** [comment]
> They will all be turned off for non-gcc AVX+ builds, resulting in SSE2...

Oh, you're right. :-( This may be a reason for me to actually fix things in core so that we can drop this requirement (support AVX+ for DES on non-gcc). But that change is invasive and would be unsuitable to make so closely to our planned release.

**Comment by magnumripper** [comment]
So I'll first do something like `#if AVX512BW ... #elif AVX512F ...` and set the CPU_* stuff, then keep your DES settings straight copied from core file except the CPU_* stuff is removed from there. Also, in that DES block I'll treat AVX-512BW the same as AVX-512F

**Comment by solardiz** [comment]
@magnumripper Sounds good to me.

While you're at it, please drop these unneeded sections from DES_bs_b.c:

```
#elif defined(__ALTIVEC__) && \
    ((ARCH_BITS == 64 && DES_BS_DEPTH == 192) || \
    (ARCH_BITS == 32 && DES_BS_DEPTH == 160))
```

```
#elif defined(__ALTIVEC__) && DES_BS_DEPTH == 256
```

They're no longer in core, but somehow have remained in jumbo. We're only keeping the usual 128-bit AltiVec, not these weird experiments.

There's also that aspect where core's john.c is compiled without an `-m` flag enabling any SIMD instruction set, but is passed `-DJOHN_*` to tell its arch.h to require the right CPU_* for the rest of the program. I think jumbo broke that (and relies on the compiler just happening not to use any SIMD instructions when producing john.o). Maybe you'd have this in mind to get jumbo closer to unbreaking this?

**Comment by magnumripper** [comment]
> There's also that aspect where core's john.c is compiled without an -m flag enabling any SIMD instruction set, but is passed -DJOHN_* to tell its arch.h to require the right CPU_* for the rest of the program. I think jumbo broke that (and relies on the compiler just happening not to use any SIMD instructions when producing john.o). Maybe you'd have this in mind to get jumbo closer to unbreaking this?

It's complicated: https://github.com/magnumripper/JohnTheRipper/issues/2679#issuecomment-323809836 (not sure why issue is closed but we're probably not fixing it for this release anyway)
