### ISSUE TITLE
warning: GitHub is missing mail notifications

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3706]
People should read messages in https://github.com/notifications

I'll close this later today.

**Comment by solardiz** [comment]
Checked the notifications. I think I'm not missing any, and have received all the expected emails.

**Comment by claudioandre-br** [comment]
Internet is sick today. A simple rebuild will fix the failure seen at:

* https://circleci.com/gh/magnumripper/JohnTheRipper/4619

**Comment by magnumripper** [comment]
Perhaps it ended up on some other build host?

**Comment by magnumripper** [comment]
I can't see any missed notifications either. Perhaps you had an email glitch.

**Comment by claudioandre-br** [comment]
> Perhaps it ended up on some other build host?

Inside Docker your bleeding-jumbo branch is protected against "the host". 

> I can't see any missed notifications either. Perhaps you had an email glitch.

Maybe. Google servers might be under pressure.
