### ISSUE TITLE
incremental + hybrid mask + --min-length + --max-length is broken for FMT_TRUNC

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3712]
I tried to reproduce behaviour described by @solardiz in the following email:
https://www.openwall.com/lists/john-users/2019/03/25/13

```
Ditto, but limit this to (total) length of 8 (adjusts incremental mode
to only produces length 5 for its portion):
--incremental=digits --mask='?w?d?d?d' --min-length=8 --max-length=8
```

### Steps to reproduce ###
```
$ john --incremental=digits --mask='?w?d?d?d' --min-len=8 --max-len=8 --stdout | head
Press 'q' or Ctrl-C to abort, almost any other key for status
12345
12345
12345
...
```

I expect it to print 12345111, 12345011, 12345211 and so on.

### System configuration ###
I used the latest john from the repo.
```
$ john --list=build-info
Version: 1.8.0.16-jumbo-1-bleeding-1a11a75 2019-03-28 16:14:10 +0100
Build: linux-gnu 64-bit x86_64 SSE4.2 AC
SIMD: SSE4.1, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: SSE4.2
$JOHN is [...]
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 65535
Effective limit: Max. KPC 4096 at length 16, down to 525 at length 125
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 4.9.2
GNU libc version: 2.19 (loaded: 2.19)
Crypto library: OpenSSL
OpenSSL library version: 01000114f
OpenSSL 1.0.1t  3 May 2016
GMP library version: 6.0.0
Regex library version: 2.0	(loaded: 2.0.8)
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by claudioandre-br** [comment]
Hint: the `--max-len` is misbehaving

`john --incremental=digits --mask='?w?d?d?d' --min-len=8 --stdout | head` works

**Comment by solardiz** [comment]
Looks like the problem is with `--stdout`. When I specify a password hash file, then 8-character passwords are seen in the status line and some are actually getting cracked. Even with a format that lacks specialized mask mode support (e.g., md5crypt on host).

The combination of `--max-len` and `--stdout` is special: it tells where to truncate passwords. I suspect that we're not handling it right when the max length is adjusted internally to account for the mask. Such adjustment shouldn't affect stdout's truncation length, but it does.

**Comment by magnumripper** [comment]
Note that you can still set a (non-truncating) max length with `-stdout=8` instead:
```
$ ../run/john --incremental=digits --mask='?w?d?d?d' --min-len=8 --stdout=8 | head -5
Warning: MaxLen = 20 is too large for the current hash type, reduced to 5
Press 'q' or Ctrl-C to abort, almost any other key for status
12345111
12345011
12345211
12345311
12345911
```

We need to make sure this bug doesn't also affect eg. DEScrypt.

**Comment by magnumripper** [comment]
As I suspected, this is not a problem with -stdout but with FMT_TRUNC. Same is seen in DEScrypt. I'm on it.

**Comment by solardiz** [comment]
FWIW, before my comment yesterday, I actually tested Aleksey's command on descrypt as well, and it was testing 8-char strings as it should. I guess it's similar to `--stdout=8` also making things work right. I don't know what you mean by "Same is seen in DEScrypt."

**Comment by magnumripper** [comment]
Perhaps I'm seeing some other bug... `--mask=?w?d?d?d --min-length=5 --max-length=5` works, `--mask=?w?d?d?d --min-length=4 --max-length=4` doesn't.

**Comment by AlekseyCherepanov** [comment]
> The combination of --max-len and --stdout is special: it tells where to truncate passwords.

It does not seem true:
```
$ printf 'aaa\nbbbb\nccccc\n' | john --stdin --max-len=4 --stdout
Using default input encoding: UTF-8
aaa
bbbb
2p 0:00:00:00 0,00% 20.00p/s bbbb

$ printf 'aaa\nbbbb\nccccc\n' | john --stdin --stdout=4
Using default input encoding: UTF-8
aaa
bbbb
cccc
3p 0:00:00:00 0,00% 23.07p/s cccc

$ printf 'aaa\nbbbb\nccccc\n' | john --stdin --max-len=4 --stdout=4
Using default input encoding: UTF-8
aaa
bbbb
2p 0:00:00:00 0,00% 22.22p/s bbbb
```

Also `--help` and `--list=hidden-options` tell the following:
```
--stdout[=LENGTH]          just output candidate passwords [cut at LENGTH]
--max-length=N             request a maximum candidate length in bytes
```

BTW as user, I rely on assumption that `--stdout` does not change behaviour and I can get the full exact list of candidates checked against hashes replacing hash file with `--stdout` ("exact" modulo truncation implied by hash format, that I don't think about usually).

**Comment by magnumripper** [comment]
`-stdout` is normally max. length 125, truncating longer. Using `-stdout=8` makes it max. length 8 and still truncating longer. Using `-max-len=8` instead will set max. length 8 and rejecting, as opposed to truncating, longer.

Likewise, DEScrypt is truncating at 8 but using `-max-len=N` makes it reject, as opposed to truncate, longer than N (including for N == 8).

At least this is how it's supposed to be.

**Comment by magnumripper** [comment]
> BTW as user, I rely on assumption that --stdout does not change behaviour and I can get the full exact list of candidates checked against hashes replacing hash file with --stdout ("exact" modulo truncation implied by hash format, that I don't think about usually).

For DEScrypt you'd use `-stdout=8` while for eg. md5crypt you'd use `-stdout -max-len=15`, that is supposed to mimic the formats exactly, including truncation vs rejection.

**Comment by magnumripper** [comment]
Then again, for modes like incremental and/or mask, truncation or rejection should not matter because we're not supposed to produce any longer candidates in the first place.

**Comment by torerobo** [comment]
I tried with Cyrillic. John writes that he created 21 candidates, but he creates a "void"

**Comment by solardiz** [comment]
@torerobo Dropping the option `--internal-codepage=koi8-r` makes it actually print the expected 21 candidates for me, on a terminal actually set to koi8-r. With that option, yes, there's emptiness (confirmed with `od -tx1` - there are just linefeeds). I'm not familiar with JtR's encodings support; maybe @magnumripper will comment.

**Comment by torerobo** [comment]
@solardiz 
Here's another: if I specify [а-д]
Candidates are created alphabetically in Latin (A / B / C / D). A must in Cyrillic (А/Б/В/Г/Д)
```
john2 --mask=[а-д] --min-len=1 --stdout=2 --internal-codepage=koi8-r 
0p 0:00:00:00 0,00% (1) 0p/s
а
б
ц
д
4p 0:00:00:00 20,00% (2) (ETA: 20:27:59) 33.33p/s д
а
б
ц
д
а
б
ц
д
а
б
ц
д
а
б
ц
д
20p 0:00:00:00 100,00% (2) (2019-03-29 20:27) 166.6p/s д
```

**Comment by solardiz** [comment]
@torerobo There's certainly no support for alphabetic order for Cyrillic charsets in our code. The ranges are for 8-bit characters in their (extended) ASCII codes order.

No surprise there, and this doesn't belong to this issue.

**Comment by magnumripper** [comment]
KOI-8r happens to be sorted by transliteration from Latin-1 if I remember correctly. Try some other Cyrillic internal codepage:
```
$ ../run/john --mask=[а-д] --min-len=1 --stdout=2 --internal-codepage=cp1251 
а
б
в
г
д
5p 0:00:00:00 16.67% (2) (ETA: 19:45:37) 100.0p/s д
а
б
в
г
д
а
б
в
г
д
а
б
в
г
д
а
б
в
г
д
а
б
в
г
д
30p 0:00:00:00 100.00% (2) (2019-03-29 19:45) 600.0p/s д
```

**Comment by magnumripper** [comment]
Anyway (as seen) there's no idea trying to find other variants of this bug. I know exactly what commit caused it but have yet to nail it.
