### ISSUE TITLE
--stdin shows `Using default input encoding: UTF-8` while --pipe does not

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3717]
I noticed that `--stdin` reports use of UTF-8 while `--pipe` and `--wordlist` do not. I guess that's cosmetic.

As a crazier guess, I tried to feed multibyte utf-8 to check if `--stdout=N` and `--max-length=N` options would can count chars instead of bytes; no, they don't.

("фыва" is "asdf" typed with Russian layout. That's 4 chars or 8 bytes using utf-8.)
```
$ echo $LANG
ru_RU.UTF-8
$ printf 'фыва\n' | hd
00000000  d1 84 d1 8b d0 b2 d0 b0  0a                       |.........|

$ printf 'фыва\n' | john --stdin --stdout=4
Using default input encoding: UTF-8
фы
1p 0:00:00:00 0,00% 9.090p/s фы
$ printf 'фыва\n' | john --pipe --stdout=4
фы
1p 0:00:00:00 0,00% 9.090p/s фы

$ john --list=build-info
Version: 1.8.0.16-jumbo-1-bleeding-e9f0f93 2019-03-29 20:46:07 +0200
```

**Comment by magnumripper** [comment]
Yes, there are many such quirks in Jumbo (and most or all other tools). The only way to get everything straight is to convert all core stuff to working with UTF-32 (or my proprietary UTF-32-8) internally.

**Comment by magnumripper** [comment]
I believe if you use `-rules` and an `-internal-codepage`, the length stuff work better. But it's very far from perfect. Still, I am not aware of any other password cracking tool that has anyware near the Unicode support we have.

**Comment by magnumripper** [comment]
I do get a notice when using --wordlist

**Comment by AlekseyCherepanov** [comment]
- I get the notice for `--wordlist` with pw file.
- I get the notice for `--mask` with pw file.
- I don't get the notice for `--wordlist` with `--stdout`.

**Comment by magnumripper** [comment]
We shouldn't get it for --mask unless it's hybrid with stdin/pipe/wordlist.

**Comment by magnumripper** [comment]
Scrap that, we should get it for mask with pw file as well, because it tells us how we read that pw file.
