### ISSUE TITLE
final status line shows wrong range in -ztex formats with mask mode and hybrid mask mode

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3720]
When I run with mask mode or with hybrid mask, I get status line with
- range showing ## candidate for ?d?d,
- and ###..----- for ?d?d?d.
It does not seem that these candidates are really tried. So the problem should be in the reporting.

```
$ john t.pw --mask='?d?d?d' --format=md5crypt-ztex
[...]
0g 0:00:00:00  0g/s 4347p/s 13043c/s 13043C/s ###..-----
Session completed

$ john t.pw --mask='?d?d' --format=md5crypt-ztex
[...]
0g 0:00:00:00  0g/s 357.1p/s 1071c/s 1071C/s ##
Session completed

$ printf 'aaaa\n' > twl
$ john t.pw --wordlist=twl --mask='?w?d?d' --format=md5crypt-ztex
[...]
0g 0:00:00:00 DONE (2019-03-30 01:29) 0g/s 384.6p/s 1153c/s 1153C/s aaaa##
Session completed

$ john t.pw --wordlist=twl --mask='?w?d?d?d' --format=md5crypt-ztex
[...]
0g 0:00:00:00 DONE (2019-03-30 01:29) 0g/s 2941p/s 8823c/s 8823C/s aaaa###..-----
Session completed
```

**Comment by claudioandre-br** [comment]
This is expected when you run JtR using "on device mask mode".

The '#' is a placeholder used to `set_key()`. It is replaced only inside the device. So, host have to print '#'.
```
1g 0:00:02:11 17,45% (8) (ETA: 02:22:10) 0.007586g/s 288910Kp/s 288910Kc/s 5532MC/s ##nndhpo..##dksbpo
```
Or
```
0g 0:00:03:10 0,04% (ETA: 2019-04-04 15:34) 0g/s 294027Kp/s 294027Kc/s 5586MC/s ##awzfxlaa..##stvzxlaa
```
Or
```
0g 0:00:00:03 N/A 0g/s 101952Kp/s 101952Kc/s 1853MC/s ##anlx..##anlx
```

**Comment by magnumripper** [comment]
True, but it doesn't "have to" be that way. We should have a shared function that can do the GPU-side work on CPU, just for `get_key()`. Should be trivial.

**Comment by Apingis** [comment]
Of course we'd want
```0g 0:00:00:03 N/A 0g/s 101952Kp/s 101952Kc/s 1853MC/s 11anlx.77anlx```
instead of
```0g 0:00:00:03 N/A 0g/s 101952Kp/s 101952Kc/s 1853MC/s ##anlx..##anlx```
It happens when you press any key in the middle of the run.

At the end of the run on the final calls to ```get_key()``` mask data is not available, including ```mask_int_cand.num_int_cand``` equals to 0 and it has no other option but to print ```#```'s.

**Comment by claudioandre-br** [comment]
> We should have a shared function that can do the GPU-side work on CPU, just for get_key(). Should be trivial.

That is the point. This already exists and works. Ops, not exactly. There was a small bug that I just fixed.
****

But, this is disturbing ('#' printed while JtR is still cracking). In my mind, this was on purpose.
```
1g 0:00:02:11 17,45% (8) (ETA: 02:22:10) 0.007586g/s 288910Kp/s 288910Kc/s 5532MC/s ##nndhpo..##dksbpo
[....]
0g 0:00:03:10 0,04% (ETA: 2019-04-04 15:34) 0g/s 294027Kp/s 294027Kc/s 5586MC/s ##awzfxlaa..##stvzxlaa
[....]
0g 0:00:00:03 N/A 0g/s 101952Kp/s 101952Kc/s 1853MC/s ##anlx..##anlx
```

**Comment by claudioandre-br** [comment]
> But, this is disturbing ('#' printed while JtR is still cracking).

Maybe it's just my imagination, I can not reproduce.

**Comment by magnumripper** [comment]
Closing bc wo
