### ISSUE TITLE
empty mask --mask='' may be confusing

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3728]
It is not a real problem. It just took some minutes to realize that `--mask=''` is equivalent for `--mask` that uses DefaultHybridMask or DefaultMask. Together with `--stdin`, I would expect it to print `Hybrid mask must contain ?w or ?W`, because there is no `?w`.

```
$ echo | john --stdin --mask='' --stdout
Using default input encoding: UTF-8
1111
0111
2111
3111
9111
[...]
```

**Comment by claudioandre-br** [comment]
> it just took some minutes to realize that --mask='' is equivalent for --mask 

It loads a default value when --mask is empty.
* DefaultHybridMask, if stacked.
* Otherwise, DefaultMask.

> `-mask=''` that uses DefaultHybridMask [...] I would expect it to print Hybrid mask must contain ?w or ?W, because there is no ?w.

It is using `DefaultHybridMask` that has ?w.

**Comment by magnumripper** [comment]
So when we use a default mask, we could print a notice like
```
Using default mask ?w?d?d?d?d
```

**Comment by claudioandre-br** [comment]
Even for tests?
```diff
diff --git a/src/mask.c b/src/mask.c
index 35c734521..0a1fd3576 100644
--- a/src/mask.c
+++ b/src/mask.c
@@ -2130,6 +2130,9 @@ void mask_init(struct db_main *db, char *unprocessed_mask)
                else
                        options.mask = (char*)cfg_get_param("Mask", NULL, "DefaultMask");
 
+               if (options.verbosity >= VERB_DEFAULT && john_main_process)
+                       fprintf(stderr, "Using default mask:%s", options.mask);
+
```

**Comment by magnumripper** [comment]
No, not for tests I think. Also, if format or options truncates or stretches the default mask we should print the modified one (eg, `?1?2?2?2?2?2?2` for LM using DefaultMask)
