### ISSUE TITLE
--verbosity=1 suppresses --stdout

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3729]
`--stdout` does not print candidates with `--verbosity=1`. It does not seem right.
```
$ john --verbosity=1 --stdout --mask='?d'
10p 0:00:00:00 100,00% (2019-03-30 17:39) 90.90p/s 7
```

It is good starting from `--verbosity=2`.
```
$ john --verbosity=2 --stdout --mask='?d'
1
0
2
3
9
8
5
4
6
7
10p 0:00:00:00 100,00% (2019-03-30 17:41) 83.33p/s 7
```

**Comment by magnumripper** [comment]
That's on purpose, for performance tests and other things. Not sure if it's documented though.

**Comment by AlekseyCherepanov** [comment]
Main purpose of `--stdout` is to print candidates. I think `--stdout` is as important feature as cracking itself (particularly it is used to generate wordlists). For me it looks non-intuitive that `--verbose=1` may change main purpose of something like cracking or `--stdout`. (Not that I cannot adapt to a documented feature, I just try to share my way of thinking to give idea how user can think; OTOH I may or may not represent average user.)

Actually I've hit this behaviour when we were training with millions of sha1 and used `--verbose=1` actively to avoid printing of cracks. Then I changed command to use `--stdout`, added a pipe to next john and did not check the output...

**Comment by magnumripper** [comment]
We should definitely document it, if it's not already documented - I don't have time to check that now.

**Comment by magnumripper** [comment]
We could also print to stderr sth like
```
Minimum verbosity, will mute printing of candidates.
```

I use stdout with -v:1 a lot, for performance testing and bug hunting.

**Comment by AlekseyCherepanov** [comment]
doc/OPTIONS contains the following phrase:
```level 1 will mute printing of cracked passwords to screen.```

A message to stderr should be fine.

Separate option might be more natural. I am not sure.

**Comment by AlekseyCherepanov** [comment]
Separate option would not be as short as `-v:1`.
