### ISSUE TITLE
finishing --show=types: moving out, renaming(?), documentation

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3737]
@magnumripper asked me to move my code out from `ldr_split_line()` back in [2015](https://www.openwall.com/lists/john-dev/2015/11/23/1). I failed it miserably. I am sorry.

Since then, @magnumripper implemented json output (#2938).

I tried to make shortest possible format to reduce overhead and to avoid quoting. But the format turned out to be complicated and hard to use. Also it may fail (gracefully) when field separator char happens in field (for instance, in canon hash).

JSON is much more human friendly and does not require checking documentation every time. I tried to estimate size overhead: json is 2-4 times longer. It is not much.

I guess most JSON parsers require the whole input to be read before parsing. But it is easy to bypass this limitation and parse sequentially line by line: read line, strip left `[` and right `,` or `]`, parse as json. It will work as long as dictionary for original line/hash in json does not contain newlines and dictionaries are separated by newlines. JSON does not need newline in outputs, so we may keep it guaranteed.

So I'd drop original custom format and keep only json.

Also I'd rename it into `--show=formats`, while #3513 is not finished. I am not sure: it is about formats, john uses "format" everywhere, so "types" does not seem to fit well into that. OTOH `--show=formats` may be confused with `--list=formats`, but `--show=formats` require a hash file.

**Comment by AlekseyCherepanov** [comment]
@math07 and @shinnok, what do you think about dropping custom output format of `--show=types` in favour of json format? I guess johnny is the only consumer for `--show=types`.

**Comment by AlekseyCherepanov** [comment]
In current json, I'd change numeric "consistencyMark" to something readable.

**Comment by shinnok** [comment]
Hi @AlekseyCherepanov,

From Johnny's perspective, there is a json parser [in Qt](https://doc.qt.io/qt-5/json.html) so it could be quick to implement and probably more robust parser yes.

Regarding dropping `--show=types` custom format altogether, I'll leave that for @solardiz and @magnumripper. Rename to `formats` is consistent too.

**Comment by solardiz** [comment]
This isn't a core feature, so I'll leave it to @magnumripper @shinnok @AlekseyCherepanov to decide on.

On a related note, I still would like us to integrate Johnny into the jumbo tree after our upcoming 1.9.0-jumbo-1 release, but before the next release after it (which might be 2.0.0).

**Comment by magnumripper** [comment]
I'm fine with dropping non-JSON output unless some user shouts out to us. A good thing with renaming to `-show=formats` is we can make that JSON right away. Actually, even if someone arguments for keeping the CSV `-show=types` stuff, we can keep that but rename `-show=types-json` to `-show=formats` with future deprecation of `-show=types` in mind.

**Comment by AlekseyCherepanov** [comment]
I am going to make a separate file for code from ldr_split_line related to `--show=types`, ok?

Because it does not seem convenient to keep it in the same file: cycle in `--show=types` is similar to original, so it is easy to go from one function to another using search in editor, then it is hard to distinguish the functions.

**Comment by AlekseyCherepanov** [comment]
Temporarily I used `#include "showformats....c"`. I used separate functions for all code blocks, but I made a wrapper for skipping functions to be used from outside. At the moment, `showformats_skipped`, `showformats_short` and similar `showformats_nis` get inlined into `ldr_split_line`.
```c
[...]
static void showformats_short(char **login, char **ciphertext,
	struct db_options *db_opts, int line_no)
{
	int fs = db_opts->field_sep_char;

	if (db_opts->showtypes_json) {
		/* NOTE: closing "]" for JSON is in john.c. */
		printf("%s{\"lineNo\":%d,",
		       line_no == 1 ? "[" : ",\n",
		       line_no);
		if (**ciphertext)
			printf("\"ciphertext\":\"%s\",",
			       escape_json(*ciphertext));
		printf("\"consistencyMark\":3}");
	} else
		printf("%c%s%c3%c\n",
		       /* empty, */
		       fs, *ciphertext,
		       fs, /* 3, */
		       fs);
}

static void showformats_skipped(const char *reason,
	char **login, char **ciphertext,
	struct db_options *db_opts, int line_no)
{
	/* strcmp(reason, "NIS") */
	if (reason[0] == 'N') {
		showformats_nis(login, ciphertext, db_opts, line_no);
	} else {
		showformats_short(login, ciphertext, db_opts, line_no);
	}
}
[...]
```

With separate file, they will not be inlined. But I guess it does not affect performance much enough to check, right?

BTW `reason` is not correct name. Reason seems to be one: hash is too short to match any format, but it shows position in code where hash gets rejected. I used a string to embed it into json instead of `consistencyMark` in the future.

**Comment by AlekseyCherepanov** [comment]
Wow, gdb handles both file inclusion and inlining very well:
```
(gdb) break printf
[...]
(gdb) run --show=types ../../tt.pw
[...]
Breakpoint 4, __printf (format=format@entry=0x8a72d9 "%c%s%c3%c\n")
    at printf.c:28
28	printf.c: No such file or directory.

(gdb) finish
[...]
(gdb) list *$pc
0x6af9d5 is in ldr_split_line (showformats_temp_include.c:78).
73			printf("%s{\"lineNo\":%d,",
74			       line_no == 1 ? "[" : ",\n",
[...]
(gdb) info line
Line 82 of "showformats_temp_include.c"
   is at address 0x6ae0f0 <showformats_regular> but contains no code.
(gdb) bt
#0  0x00000000006af9d5 in showformats_short (login=<optimized out>, 
    db_opts=<optimized out>, db_opts=<optimized out>, line_no=1, 
    ciphertext=0x7fffffffd0e0) at showformats_temp_include.c:78
#1  showformats_skipped (reason=<synthetic pointer>, line_no=1, 
    db_opts=0x3d58648, ciphertext=0x7fffffffd0e0, login=0x7fffffffcf78)
    at showformats_temp_include.c:93
#2  ldr_split_line (login=login@entry=0x7fffffffd0d8, 
    ciphertext=ciphertext@entry=0x7fffffffd0e0, 
    gecos=gecos@entry=0x7fffffffd0e8, home=home@entry=0x7fffffffd0f0, 
    uid=uid@entry=0x7fffffffd0f8, source=source@entry=0x3d5b210 "", 
    format=0x7fffffffd0d0, db_opts=0x3d58648, line=0x0) at loader.c:513
```

**Comment by solardiz** [comment]
@AlekseyCherepanov Why are you working on this specific issue now? Do you feel it's a candidate for improvement _before_ and in time for our upcoming release? I am not tracking it as such, and we have far more pressing issues. Would you possibly help with those already identified release blockers instead?

I don't insist, I am just asking these questions and sharing this info with you. Thanks!

**Comment by AlekseyCherepanov** [comment]
I think it should be done before the release because we are going to rename option from `--show=types-json` to `--show=formats`.

This issue already took more time than I would like. But I'd like to finish it while I am on it.

Then I am going to try some ideas to find more (minor) bugs.

**Comment by solardiz** [comment]
@AlekseyCherepanov I think we don't want to find more _minor_ bugs at this time, except for those that are trivial to fix, because we're already aware of plenty of issues and have little time. After you finish work on this issue, I'd appreciate your help on other issues already assigned to the 1.9.0-jumbo-1 milestone. Thanks!

**Comment by AlekseyCherepanov** [comment]
I cannot just move the code into a separate file because the code uses `ldr_set_encoding()` that's not public:
```c
static void ldr_set_encoding(struct fmt_main *format)
```

Should I change `loader.h` to provide declaration for `ldr_set_encoding()` or leave `--show=types` code in `loader.c`?

**Comment by magnumripper** [comment]
> Should I change `loader.h` to provide declaration for `ldr_set_encoding()`

Sure, do so if needed.
