### ISSUE TITLE
john does not print final status line for --stdout in short pipe like `head -n 5`, killed by SIGPIPE

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3743]
I don't know if it is a problem.

john does not print final status line for `--stdout | head -n 5` for sufficiently big attacks.

But john stores session file after start. It is possible to restore the session and get all candidates again, e.g. redirecting to other pipe.

```
$ john --stdout --mask='?d?d?d?d' | head -n 5
Press 'q' or Ctrl-C to abort, almost any other key for status
1111
0111
2111
3111
9111

$ john --stdout --mask='?d?d?d?d' | tail -n 5
Press 'q' or Ctrl-C to abort, almost any other key for status
10000p 0:00:00:00 100,00% (2019-03-31 14:12) 100000p/s 7777
8777
5777
4777
6777
7777
```

```
$ strace ./JohnTheRipper/run/john --stdout --mask='?d?d?d?d' | head -n 5
[...]
write(1, "1111\n0111\n2111\n3111\n9111\n8111\n51"..., 4096) = 4096
1111
0111
2111
3111
9111
write(1, "061\n1261\n0261\n2261\n3261\n9261\n826"..., 4096) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=10372, si_uid=1000} ---
+++ killed by SIGPIPE +++
```

**Comment by magnumripper** [comment]
I guess the john process is killed hard by the SIGPIPE. We're not catching it.
```
$ git grep 'signal(' signals.c
signals.c:      signal(signum, handler);
signals.c:      signal(SIGHUP, SIG_IGN);
signals.c:      signal(SIGUSR2, SIG_IGN);
signals.c:      signal(SIGINT, sig_handle_abort);
signals.c:      signal(SIGTERM, sig_handle_abort);
signals.c:      signal(SIGXCPU, sig_handle_abort);
signals.c:      signal(SIGXFSZ, sig_handle_abort);
signals.c:      signal(SIGINT, SIG_DFL);
signals.c:      signal(SIGTERM, SIG_DFL);
signals.c:      signal(SIGXCPU, SIG_DFL);
signals.c:      signal(SIGXFSZ, SIG_DFL);
signals.c:      signal(SIGALRM, sig_handle_timer);
signals.c:      signal(SIGALRM, sig_handle_timer);
signals.c:      signal(SIGALRM, SIG_DFL);
signals.c:      signal(signum, SIG_IGN);
```
For some reason, adding `tee` in the chain make it work for me:
```
../run/john --stdout --mask='?d?d?d?d' | tee | head -n 5
```

**Comment by AlekseyCherepanov** [comment]
`tee` is killed by SIGPIPE, then john is killed by SIGPIPE. So john gets more time to write to the pipe, so it may finish before signal. A bigger attack is needed to trigger SIGPIPE with `tee`.

**Comment by AlekseyCherepanov** [comment]
john uses `puts()` to print candidates with `--stdout`:

```
$ ltrace -o out -e printf -e write -e _IO_putc -e puts -e fputs -e fputc -e putchar -e vfprintf -e fprintf -e fwrite  ./JohnTheRipper/run/john --stdout --mask='?d' && cat out
[...]
john->puts("1")                                 = 2
john->puts("0")                                 = 2
john->puts("2")                                 = 2
john->puts("3")                                 = 2
[...]
```

`puts` buffers output, so actual it is not printed immediately. So I guess john thinks that it printed more than actually was written to pipe. So catching and handling SIGPIPE as other signals would mean that john would save session file with higher progress than progress of other side of the pipe.

I tried `strace cat | head` and `killall head`: cat waits input and is not affected by killing of head; when cat tries to write input into pipe, it gets SIGPIPE.

Theoretically it should be possible to run `john --session=ses1 ... --stdout | john --session=ses2 --stdin ...`, to get the right hand side of the pipe killed, and to be able to recover it with `john --restore=ses1 | john --restore=ses2`.

So we should not save `ses1.rec` right after `puts()` in `--stdout`.

But with current implementation, it may happen anyway due to timer.

I guess there may be a moment when it is possible to do write() to pipe after the other side stopped processing input but before writing to pipe would cause SIGPIPE, so the left hand side of pipe would see successful write() while the other side would not process it. I'd say it depends on the size of pipe's buffer, but there may be other case anyway: ses1 writes, ses2 reads and gets killed, ses1 sees success that means that data was transfered well.

Left hand side does not know size of batches for processing on the right hand side of pipe. So it is not easy to make it (more) reliable than it is right now.

**Comment by AlekseyCherepanov** [comment]
```
$ (echo asdf; sleep 2; echo qwer; sleep 1; echo zxcv) | strace cat | sh -c 'sleep 1; kill $$'
[...]
read(0, "asdf\n", 131072)               = 5
write(1, "asdf\n", 5)                   = 5
read(0, "qwer\n", 131072)               = 5
write(1, "qwer\n", 5)                   = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=23073, si_uid=1000} ---
+++ killed by SIGPIPE +++
```

The right hand side of pipe (`sh`) is busy and does not read at all, but it is live. The left hand side (`cat`) writes "asdf\n" successfully. Then `sh` is killed. So `cat` tries to write "qwer\n" and fails. Nothing is processed on the right hand side.

**Comment by magnumripper** [comment]
This is all core stuff, I wont do any Jumbo-specific fixes.

**Comment by solardiz** [comment]
Like Aleksey wrote, I also "know if it is a problem." So I don't intend to make any changes in response to this now.
