### ISSUE TITLE
error: too few arguments to function ‘c_regex_cb_mb’

### ISSUE THREAD

**Issue by seanthegeek** [magnumripper/JohnTheRipper#3753]
### Steps to reproduce ###
Attempt to build the bleeding branch on Debain Buster

```
regex.c:47:30: warning: initialization of ‘c_iterator_ptr’ {aka ‘int’} from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
 static c_iterator_ptr iter = NULL;
                              ^~~~
regex.c:48:32: warning: initialization of ‘c_regex_ptr’ {aka ‘int’} from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
 static c_regex_ptr regex_ptr = NULL;
                                ^~~~
regex.c: In function ‘do_regex_hybrid_crack’:
regex.c:221:15: error: too few arguments to function ‘c_regex_cb_mb’
   regex_ptr = c_regex_cb_mb(regex, callback);
               ^~~~~~~~~~~~~
In file included from regex.h:35,
                 from regex.c:12:
/usr/local/include/librexgen/c/librexgen.h:47:13: note: declared here
 c_regex_ptr c_regex_cb_mb(
             ^~~~~~~~~~~~~
regex.c: In function ‘do_regex_crack’:
regex.c:336:14: error: too few arguments to function ‘c_regex_cb_mb’
  regex_ptr = c_regex_cb_mb(regex, callback);
              ^~~~~~~~~~~~~
In file included from regex.h:35,
                 from regex.c:12:
/usr/local/include/librexgen/c/librexgen.h:47:13: note: declared here
 c_regex_ptr c_regex_cb_mb(
             ^~~~~~~~~~~~~
make[1]: *** [Makefile:1876: regex.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:190: default] Error 2
```

**Comment by solardiz** [comment]
@magnumripper Should we possibly just drop this mode from our codebase before the upcoming release? As I understand, librexgen doesn't have a stable API, so people will keep running into issues like this even if we fix whatever one issue there might be this time.

I've never used the rexgen mode myself. I think our mask mode is so powerful that we might not need the rexgen mode. Maybe we need to provide more and easier to find and ranging from trivial to advanced examples for usage of masks instead.

**Comment by solardiz** [comment]
@seanthegeek Is there a specific reason why you're trying to build with rexgen support? Did you specifically install this library for use with JtR? What would your use case for the functionality be, if it built successfully? Please help us decide whether to keep repairing this or just drop it. Thanks!

**Comment by magnumripper** [comment]
I thought we could mark it clearly as "experimental" in doc/INSTALL as well as in autoconf summary, keeping it but not "supporting" it. It does have some extremely powerful uses, although most of them are small enough sets that you could just as well use a standalone `rexgen` and pipe it to JtR.

**Comment by magnumripper** [comment]
@seanthegeek what version of librexgen are you trying to use? I'm at "rexgen-2.0.8" (as output by `rexgen -v`) and I have no problems. I didn't check for updates to librexgen for quite a while.

**Comment by seanthegeek** [comment]
@solardiz I only included rexgen because its mentioned in `docs/INSTALL`. (this is my first time trying to build john)

@magnumripper rexgen 2.1.3 from git

**Comment by solardiz** [comment]
@magnumripper Your edits to `INSTALL-UBUNTU` look good to me.
Rather than "require --enable-experimental-code option to configure in order for it to auto-detect librexgen at all" we could add a specific `--enable-rexgen` or `--with-rexgen` option, like we have e.g. with `--enable-ztex`.

**Comment by frank-dittrich** [comment]
@solardiz But the `experimental-code` part IMHO makes it more obvious that there is limited support.

**Comment by magnumripper** [comment]
Good idea, we already have `--disable-rexgen` because it defaults to auto, I'll just change the default to no so you'll need to give `--enable-rexgen` to get it.

**Comment by magnumripper** [comment]
@seanthegeek I'm closing this. Eventually someone may adopt our code to latest version librexgen, but the latter has a sad history of changing its API all the time, breaking things. If you really want regex mode, try checking out librexgen 2.0.8 and build against that (now adding `./configure --enable-rexgen` for recent Jumbo)

**Comment by solardiz** [comment]
@magnumripper Do we have our tested/supported version(s) of librexgen documented somewhere? Perhaps we should?

**Comment by magnumripper** [comment]
If you mean declaring a known-good (sort of) version, I did so half a day ago in db4847e1
