### ISSUE TITLE
./john --test output (ASCII text, with overstriking) breaks relbench

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#3763]
I spent quite some time, not knowing what was wrong, until I checked this:
```
$ file tests-old-cpu.txt tests-bleeding-cpu.txt 
tests-old-cpu.txt:      ASCII text
tests-bleeding-cpu.txt: ASCII text, with overstriking
```

**Comment by frank-dittrich** [comment]
commit https://github.com/magnumripper/JohnTheRipper/commit/7187208dba553b6d648749de4b596bdedd96c547 added backspace characters to the benchmark output.

**Comment by frank-dittrich** [comment]
For now, I fixed relbench like this:
```
diff --git a/run/relbench b/run/relbench
index 4ba08bc5d..14f8014ce 100755
--- a/run/relbench
+++ b/run/relbench
@@ -76,7 +76,7 @@ sub parse
 			return;
 		}
 	} else {
-		($name) = /^\t?Benchmarking: ([^\[]+) \[.*\].* (DONE|Warning:.*)$/;
+		($name) = /^\t?Benchmarking: ([^\[]+) \[.*\].* (.....\b\b\b\b\b)?(DONE|Warning:.*)$/;
 		$ok = defined($name);
 	}
 	print STDERR "Could not parse: $_\n" if (!$ok);
```

**Comment by magnumripper** [comment]
That change should be solid. I think I want to keep the current overstriking output - it's nice seeing where self-test ends and benchmark starts.

**Comment by magnumripper** [comment]
The overstriking stuff is now reverted, and its reincarnation later will be without overstriking.
