### ISSUE TITLE
Line Status Problem

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#3766]
Problem number 1
The option --progress-every = 3 should output the status line after 3 seconds, but the output is minimum after 7s. (--progress-every = 1, also the status line will be updated in 7s only).

Problem number 2
Different output status bar. With the --stdin option, when the dictionary is input, the status bar is shortened and does not display the progress of the process (% of total time and time)
Example
0g 0: 00: 00: 14 0g / s 17.71p / s 17.71c / s 17.71C / s (unusual)
0g 0: 00: 00: 14 26.24% (ETA: 14:11:40) 0g / s 17.70p / s 17.70c / s 17.70C / s (normal)

Problem number 3
With the --stdin option it is not clear how to display the status line (usually the status line is displayed by pressing any key), you need to use the undocumented version (send SIGUSR1 to john process for status), so think about how to display the status using SIGUSR1
![1](https://user-images.githubusercontent.com/35532898/55682840-5e383900-5941-11e9-856f-1352910fb3cd.png)

**Comment by magnumripper** [comment]
> Problem number 1
> The option --progress-every = 3 should output the status line after 3 seconds, but the output is minimum after 7s. (--progress-every = 1, also the status line will be updated in 7s only).

This is because that format is so slow we actually don't get a chance to print more often than that.

> Problem number 2
> Different output status bar. With the --stdin option, when the dictionary is input, the status bar is shortened and does not display the progress of the process (% of total time and time)
> Example
> 0g 0: 00: 00: 14 0g / s 17.71p / s 17.71c / s 17.71C / s (unusual)
> 0g 0: 00: 00: 14 26.24% (ETA: 14:11:40) 0g / s 17.70p / s 17.70c / s 17.70C / s (normal)

We obviously can't know how much data we'll get from stdin, so how could we possibly display a progress?

> Problem number 3
> With the --stdin option it is not clear how to display the status line (usually the status line is displayed by pressing any key), you need to use the undocumented version (send SIGUSR1 to john process for status), so think about how to display the status using SIGUSR1

Undocumented? I'm not sure what you mean. We do print "Press Ctrl-C to abort, or send SIGUSR1 to john process for status"

> ![1](https://user-images.githubusercontent.com/35532898/55682840-5e383900-5941-11e9-856f-1352910fb3cd.png)

FCS please don't post screenshots of pure text, that's really lame. Copy/paste the text instead.

**Comment by torerobo** [comment]
2. > We obviously can't know how much data we'll get from stdin, so how could we possibly display a progress?
This is true only in part.
In this example (as seen in the screenshot), I file specifically the "file dictionary".

3. It is not clear how to display the status bar with --stdin (what do you need to do to display it?)

**Comment by claudioandre-br** [comment]
I agree with magnum.

> 2.

It is still stdin. And you can append to the file.

> 3.

Google. This is 100% Linux stuff.

**Comment by torerobo** [comment]
3. It should be not in google, in the JTR documentation.
2. At the input of the JTR, the dictionary is supplied in both cases (in one case the string is poor).

Closing a problem is always easier than analyzing ...

**Comment by claudioandre-br** [comment]
> At the input of the JTR, the dictionary is supplied in both cases (in one case the string is poor).

You piped. Should JtR know about what shell is doing?

> Instead of SIGUSR1, you can assign a key combination to display the status bar (for example, ctrl + B)

To me it seems better to "send signal to a process". It seems more natural. Anyway, you can implement this and defend your idea.

**Comment by torerobo** [comment]
I am not a developer and can only offer an idea how to do better for users (ctrl + B).

Can you give an example SIGUSR1 JTR?

**Comment by claudioandre-br** [comment]
Google gave me: https://www.thegeekstuff.com/2011/02/send-signal-to-process/

So:
```
$ ../run/john -form:raw-sha512-opencl ~/test.in --mask=?d --min-len=0 --max-len=12 --verb=1 &

$ ps ux
claudio  18980  0.0  0.0 143868  2680 ?        S    14:53   0:00 sshd: claudio@pts/0
claudio  18981  0.0  0.0 116676  3316 pts/0    Ss   14:53   0:00 -bash
claudio  25716 23.3  0.3 4641736 113384 pts/0  Sl   15:19   0:02 ../run/john -form:raw-sha512-opencl /home/claudio/test.in --mask=?d --min-len
claudio  25745  0.0  0.0  35864  1480 pts/0    R+   15:20   0:00 ps ux

$ kill -s USR1 25716
```

**Comment by claudioandre-br** [comment]
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by torerobo** [comment]
If I understand correctly, to get the status line, you need to open a new terminal window, look for the process, and type the command. This is not normal, assign another solution. At the moment it is a failure. You can remake (so that in the usual case, not --stdin) Print the status line not by pressing any key, but open the terminal again. So why didn't you do that? The answer is simple - it is complete nonsense. All you need to do is replace sgr with a hotkey. In general, it is very sad when the developer does not see a clear jamb.

**Comment by solardiz** [comment]
I'm sorry if I'm maybe out of context here, but FWIW I've just checked that JtR core opens `/dev/tty` and thus is able to detect keypresses on the same terminal even in `--stdin` mode, e.g.:

```
$ ./john -stdin -form=bcrypt pw-fake-unix < password.lst
Loaded 3107 password hashes with 3107 different salts (bcrypt [Blowfish 32/32 X2])
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:01 0g/s 0p/s 953.6c/s 953.6C/s 123456..hello
0g 0:00:00:02 0g/s 0p/s 1024c/s 1024C/s 123456..hello
0g 0:00:00:02 0g/s 0p/s 978.1c/s 978.1C/s 123456..hello
Session aborted
```

I pressed spacebar a couple of times, then `q` to produce the above output. All in one terminal.

@claudioandre-br Have we somehow broken that in jumbo? If so, please re-open, change the issue title, and let's work on a fix. Thanks!

@torerobo Your "complaint" isn't entirely reasonable. You're looking at this purely from a user perspective, which is understandable. I think the way @claudioandre-br is looking at it from a developer perspective is that he finds the functionality you ask for impossible or impractical to implement. I think he might be wrong about that, as I point out above, but if he were not then closing this issue like he did would have been appropriate. This is no one's fault, just a maybe misunderstanding of what's possible vs. not. It is also entirely possible that I misunderstand something (such as the context of this discussion).

**Comment by solardiz** [comment]
This also works OK in jumbo for me, so no, not broken:

```
$ ./john -stdin -form=bcrypt < password.lst ../../pw-fake-unix 
Using default input encoding: UTF-8
Loaded 3107 password hashes with 3107 different salts (bcrypt [Blowfish 32/64 X2])
Cost 1 (iteration count) is 32 for all loaded hashes
Will run 32 OpenMP threads
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
rascal           (u143-bf)
tigger           (u5-bf)
beavis           (u168-bf)
eeyore           (u82-bf)
shadow           (u23-bf)
5g 0:00:00:02  2.392g/s 0p/s 14422c/s 14422C/s 123456..knight
aaaaaa           (u156-bf)
internet         (u17-bf)
chicken          (u178-bf)
wizard           (u74-bf)
9g 0:00:00:03  2.912g/s 0p/s 14850c/s 14850C/s 123456..knight
fisher           (u134-bf)
12345678         (u53-bf)
cricket          (u181-bf)
asdfgh           (u76-bf)
1234             (u6-bf)
matthew          (u48-bf)
scooter          (u146-bf)
16g 0:00:00:04  3.809g/s 0p/s 14628c/s 14628C/s 123456..knight
Use the "--show" option to display all of the cracked passwords reliably
Session aborted
```

Again, it was just keypresses in the same terminal. No need to send signals from another terminal.

So OK to keep this closed - no issue here.

**Comment by solardiz** [comment]
Hmm, maybe the only issue here is we unnecessarily change the help message to "or send SIGUSR1 to john process for status". Why do we do that, again? Maybe only do it e.g. when we fail to open `/dev/tty`? Why would we realistically fail to open it?

**Comment by claudioandre-br** [comment]
> @claudioandre-br is looking at it from a developer perspective is that he finds the functionality you ask for impossible or impractical to implement.

I haven't said that.

**Comment by solardiz** [comment]
Oh, I see, this actually triggers the non-working keypresses:

```
$ cat password.lst | ./john -stdin -form=bcrypt ../../pw-fake-unix
```

and is indeed closer to simulating a reasonable use case for `--stdin`, and since we try and fail to open `/dev/tty` I guess there's nothing we can do here.

So the only improvement I think we can make here is detect the special case when we have succeeded in opening `/dev/tty` despite of `--stdin` and print the usual help message about keypresses in that case. Please feel free to re-open this issue or create another for this tiny improvement.

**Comment by solardiz** [comment]
@claudioandre-br Sorry, I assumed that was your line of thought, apparently wrongly.

**Comment by claudioandre-br** [comment]
There is something else. No reason to consider (ctrl + B) a magic solution:

```
$ xxd texto
00000000: 7465 7374 0274 6573 740a                 test.test.

$ mkpasswd -m sha-512 -P 0 -S salt4678 < texto > hash

$ ../run/john -stdin hash
Loaded 2 password hashes with no different salts (sha512crypt, crypt(3) $6$ [SHA512 256/256 AVX2 4x])
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
test^Btest
Warning: Only 1 candidate left, minimum 32 needed for performance.
testtest        (?)
```

**Comment by solardiz** [comment]
After some confusion, I figured out this refers to @torerobo's "Instead of SIGUSR1, you can assign a key combination to display the status bar (for example, ctrl + B)". Indeed, @torerobo doesn't know what's technically possible vs. not, nor does he have to know that in advance - we're to point these things out in response to unimplementable feature requests. So let me do that now:

@torerobo Unfortunately, as far as we're aware, your suggestion can't reasonably be implemented when we're in `--stdin` mode and the command isn't the first (or only) one in a pipe.

**Comment by solardiz** [comment]
> So the only improvement I think we can make here is detect the special case when we have succeeded in opening `/dev/tty` despite of `--stdin` and print the usual help message about keypresses in that case. Please feel free to re-open this issue or create another for this tiny improvement.

Looks like no, we can't even do that - when `john` isn't the first in a pipe, the open of `/dev/tty` succeeds anyway, but keystrokes from the terminal are not received there. So we don't seem to have a reasonable way to distinguish between the two cases, and sort of have to print the safer (guaranteed to work) one of the two help messages.

**Comment by magnumripper** [comment]
To actually give an answer to "how do I actually send SIGUSR1 to john?", here's a couple of ways to do it. All of them need to be issued in an other terminal session:

- Do a `pkill -usr1 john` (assuming you only have one session running, or want status from all running john processes)
- Find out exactly what PID your process have. For example, `ps w | grep john`, find the PID (first column), then `kill -usr1 <pid>`
- Run `top`, press `k`, then enter the PID (you should see the process and its PID in the list), then say `1` for `sigusr1`.

**Comment by magnumripper** [comment]
After #4403 is resolved (I have a PR pending but will wait until after #4394 is merged) much of this will be improved: We will always print the correct message if we can in fact read the keyboard, and we get a `--force-keys` option that lets us read/use keyboard even when we're not the foreground process (eg. we're piped to).
