### ISSUE TITLE
confusing message about counts from --show=invalid when 32 hex occurs, because full LM is reported as 2 hashes

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3775]
I am not sure that it is a problem.
```
$ cat ab.pw
AAa6CzJlsalyo
BBODHXVAdtcmc
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
$ john --show=invalid ab.pw
4 valid hashes, 0 invalid hashes
```

**Comment by solardiz** [comment]
This isn't specific to that jumbo functionality, nor to LM hashes. It also affects the number of hashes shown on the "Loaded ..." and "Remaining ..." lines, and the final line of a simple "--show". And it also applies to bigcrypt.

I think we've accepted treating of portions of split hashes as separate hashes for the hash counting throughout JtR and its reporting. So I'll treat this as not a problem we'd want to do anything about now, if ever.

**Comment by AlekseyCherepanov** [comment]
Unlike other places, here it is not obvious that LM format was active (for a part of hashes).

**Comment by solardiz** [comment]
That's a valid point, Aleksey, but it doesn't bring us any closer to somehow "fixing" this issue.

Besides, when loading descrypt hashes, it's also somewhat confusing that some might actually be bigcrypt, resulting in unexpected hash counts.
