### ISSUE TITLE
Complete "OpenCL: tune for the length a run will be using"

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3780]
The changes merged as part of #3776 are great, but incomplete:

1. That PR changed the auto-tune length in `gws_test`, but forgot to make similar change in `opencl_find_best_lws`. I think this is a bug. Also, ideally code duplication between these two functions should be avoided (duplicate code moved to a shared function called by both).

2. Can we possibly run poor man's mask length calculation early and use that for auto-tune? Count the number of non-? characters, the number of ?c specifiers, and count anything in square brackets as one character. It's 5 lines of code or so.

3. Nitpick: I think `len = cond ? something : len` (note `len` used on both sides) is misuse of the ternary operator, and would be cleaner written using `if`. So instead of:

```c
len = (len < options.req_minlength) ? options.req_minlength: len;
len = (options.req_maxlength && len > options.req_maxlength) ? options.req_maxlength: len;
```

We can have:

```c
if (len < options.req_minlength)
        len = options.req_minlength;
if (options.req_maxlength && len > options.req_maxlength)
        len = options.req_maxlength;
```

**Comment by magnumripper** [comment]
Some (as in several) formats are so slow, self-test after auto-tune will simply be WAY to slow. I've worked hard to get rid of that. Years ago, a simple -test=0 would take tens of minutes with some formats.

**Comment by magnumripper** [comment]
wrong thread, sorry :)

**Comment by magnumripper** [comment]
@claudioandre-br could you take this please?

**Comment by magnumripper** [comment]
Regarding 2. I think it's going backwards. Normally we should self-test with low worksizes. Normally, bugs will show up anyway (but sure, not always). Try doing a self-test with bitlocker-opencl tuned for a real run. Good luck with that.

**Comment by solardiz** [comment]
Wrong thread again? "2" here says nothing about self-test.

**Comment by magnumripper** [comment]
2 is needed only if you want to auto-tune before self-test

**Comment by solardiz** [comment]
You wrote: "`../run/john -form:rar-opencl all_tests.in -mask:alpha?abravo` will tune for length 5 instead of 11 because we auto-tune too early (mask mode not initialized) - I believe even before self test."

I read this as implying the condition "if -mask and no min/max are set, just use mask length" doesn't work yet. I see no reason why we can't make it work now (for the release), as I suggested. I see little relevance to self-tests here.

**Comment by magnumripper** [comment]
OK, that makes sense. I don't think it matters a lot though, and it'll just be temporary.

**Comment by magnumripper** [comment]
All done now, me thinks
