### ISSUE TITLE
Yescrypt warning

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3791]
```
yescrypt/yescrypt-opt.c:40:2: warning: #warning "Note: AVX is enabled, which is great for classic scrypt and YESCRYPT_WORM, but is sometimes slightly slower than plain SSE2 for YESCRYPT_RW" [-Wcpp]
 #warning "Note: AVX is enabled, which is great for classic scrypt and YESCRYPT_WORM, but is sometimes slightly slower than plain SSE2 for YESCRYPT_RW"
  ^~~~~~~
```
Should we disable AVX for that file? Or mute the warning perhaps... or not?

**Comment by solardiz** [comment]
I'm aware of this warning, and thought it's just fine because it tells a useful thing... but now that I thought of it some more, we don't expose native yescrypt yet, so this warning isn't useful yet. So we can temporarily mute it, then maybe re-enable it once we support native yescrypt.

**Comment by claudioandre-br** [comment]
BTW: clang is unhappy

```
yescrypt/yescrypt-opt.c:1185:23: error: comparison of constant 1493421638091770 with expression of type 'uint32_t' (aka 'unsigned int') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
                if (N / p <= 3 || p > SIZE_MAX / Salloc)
                                  ~ ^ ~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

**Comment by magnumripper** [comment]
Where does `-Wtautological-constant-out-of-range-compare` come from? Some default?

**Comment by solardiz** [comment]
I understand this is not pretty, but I see no clean and easy way to avoid doing the check just in cases where it'd be redundant.

**Comment by magnumripper** [comment]
Should I fix both these issues? Can I simply have autoconf add `-Wno-tautological-constant-out-of-range-compare` where supported?

**Comment by solardiz** [comment]
@magnumripper Yes, I'd be fine with that, thanks. I'm not sure if new gcc possibly also produces these warnings, and whether it has the same option to suppress them or not.
