### ISSUE TITLE
Unsolved PDF hash with known password

### ISSUE THREAD

**Issue by TragedyHasStruck** [magnumripper/JohnTheRipper#3797]
I'm unsable to use `john` to crack the password for a PDF where I know the password and have it in a wordlist, but I'm not sure how the PDF was generated. The PDF hash is on the following format:

    mypdf.pdf:$pdf$4*4*128*-1836*1*16*abcdef...*32*abcdefghijkl...

Where the first "abcdef" is 32 characters and the second is 132 characters. Since the password is relevant to me I'd prefer not sharing it in its original form. Is this format simply not supported?

### Steps to reproduce ###
    perl run/pdf2john.pl mypdf.pdf > hash
    run/john --wordlist=wordlist.txt hash

Leads to one unsolved

	Will run 8 OpenMP threads
	Press 'q' or Ctrl-C to abort, almost any other key for status
	0g 0:00:00:00 DONE (2019-04-12 07:45) 0g/s 200.0p/s 200.0c/s 200.0C/s abc..def
	Session completed
	Loaded 1 password hash (PDF [MD5 SHA2 RC4/AES 32/32])

### System configuration ###
My `pdf2john.pl` is from bleeding-jumbo, while `john` is the Windows binary:

	Version: 1.8.0-jumbo-1 OMP
	Build: cygwin 32-bit SSSE3-autoconf
	Arch: 32-bit LE
	$JOHN is /run/
	Format interface version: 12
	Max. number of reported tunable costs: 3
	Rec file version: REC4
	Charset file version: CHR3
	CHARSET_MIN: 1 (0x01)
	CHARSET_MAX: 255 (0xff)
	CHARSET_LENGTH: 24
	Max. Markov mode level: 400
	Max. Markov mode password length: 30
	Compiler version: 4.5.3
	gcc version: 4.5.3
	OpenSSL library version: 00090812f
	OpenSSL 0.9.8r 8 Feb 2011
	fseek(): fseeko
	ftell(): ftello
	fopen(): _fopen64
	memmem(): System's

**Comment by torerobo** [comment]
PDF is supported. You just need to update JtR.
The pdf module, for example, was from bugs in precompiled JtR and Parrot OS (by the way, some modules, for example wpapcap2john, are still with bugs).
In OS Kali / Parrot JtR rarely updated (there was a time when they did not update JtR from 2015 to autumn 2018)

**Comment by TragedyHasStruck** [comment]
Thank you for your input. I have successfully tested recovering passwords with other PDF hashes, so I knew PDF functioned, but not this particular format. However I will take your advice and try compiling from bleeding and see where that gets me. I'll report once I have the results.

**Comment by magnumripper** [comment]
You can't open issues for 1.8.0-jumbo-1, that's 7,400 commits ago
