### ISSUE TITLE
Enhance bcrypt-ztex to support > 512 hashes/salt

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3802]
`ztex/fpga-bcrypt/README.md` says:

```
- The design contains 124 cores. On-chip comparsion against up to 512 hashes is available. There's a runtime option to turn off the comparator, in that case it outputs all computed hashes.
```

Let's revise the host-side code to actually make use of this feature - have all computed hashes sent to host, and compared there - when the loaded number of hashes for a salt exceeds 512. (Right now, we merely print a warning and don't load the "excessive" hashes.)

BTW, there's a typo in "comparsion".

**Comment by solardiz** [comment]
Looks like we need to somehow have the host request that `mode_cmp` be set to 0, so that we trigger these:

```
                                        if (mode_cmp)
                                                state_rd <= STATE_RD_CMP;
                                        else
                                                state_rd <= STATE_RD_READ_COMPLETE;
```

```
                STATE_RD_READ_COMPLETE: begin
                        outpkt_type <= `OUTPKT_TYPE_RESULT;
                        empty <= 0;
                        state_rd <= STATE_RD_OUTPKT_RESULT;
                end
```

Looks like we also need to define `PKT_TYPE_RESULT` on host side (just the value 3?) and add its processing to `ztex/jtr_device.c: jtr_device_list_process_inpkt()`.

**Comment by AlekseyCherepanov** [comment]
I saw the following line and considered that I could set `app_mode` to specify `mode_cmp`.
```
(* KEEP="true" *) wire mode_cmp = ~app_mode[6];
```
I guess `app_mode` wire can be set from C using `device_list_set_app_mode()`. Particularly there is existing commented out line of code in `device_list_init()`. So I enabled output of in packet type and tried values of different bits: everything works the same, but value 64 causes the following error:
```
SN [...] FPGA #1 error: pkt_comm_status=0x80, debug=0xd3d2
SN [...] error -1 doing r/w of FPGAs (LIBUSB_ERROR_IO)
```
I tried to disable returning of error, then this error is printed multiple times, then john reports timeout of device and resets it.

Did I do right thing and it did not work? Or did I do wrong and have to search for correct way?

**Comment by solardiz** [comment]
Aleksey - I don't really know, but what you describe makes some sense. That commented out line is:

```c
        // Application mode 2: use high-speed packet communication (pkt_comm)
        // that's the primary mode of operation as opposed to test modes 0 & 1.
        // UNUSED
        //device_list_set_app_mode(device_list, 2);
```

So maybe the value should be 66?

**Comment by solardiz** [comment]
Maybe you're getting these in the `debug` value:
```
fpga-bcrypt/bcrypt/bcrypt.v:    assign debug2 = 8'hd2;
fpga-bcrypt/bcrypt/bcrypt.v:    assign debug3 = 8'hd3;
```

**Comment by solardiz** [comment]
If you configure the device right, I think you'd reach this place:

```c
                        // Unknown packet type
                        } else {
                                if (PKT_DEBUG >= 1)
                                        fprintf(stderr, "%s %s type=0x%02x id=%d: len=%d\n",
                                                jtr_device_id(dev), inpkt_type_name(inpkt->type),
                                                inpkt->type, inpkt->id, inpkt->data_len);
```

and your next task would be to add processing of that packet type.

**Comment by AlekseyCherepanov** [comment]
Somehow I was able to get the following condition.
```
#1 type=0xd3 (RESULT1) type=0xd3 id=1: len=30
SN [...]: bad input packet.
```
(output differs from current john because I modified code to print numeric value and label of packet type.)

To achieve that I've put `fpga_set_app_mode(fpga, 64);` in the beginning of cycle over devices in `device_pkt_rw()`. It seems that the difference is not principal. And it does not work anymore.

**Comment by Apingis** [comment]
I started to work on the issue. It raises error ```pkt_comm_status=0x80``` because when comparator is off it treats CMP_CONFIG packet with >0 hashes as error.
