### ISSUE TITLE
bcrypt-ztex cost 19 TargetSetting error mismatch

### ISSUE THREAD

**Issue by roycewilliams** [magnumripper/JohnTheRipper#3805]
When attacking bcrypt-ztex cost 19, this self-conflicting error appears:
```
$  ./john --format=bcrypt-ztex bcrypt19.hash
Warning: invalid TargetSetting=19 in john.conf. Valid values are 5-19
```
In other words, cost 19 appears to be both allowed and not allowed.

**Comment by magnumripper** [comment]
Thanks Royce! I hope we can fix this before release.

**Comment by roycewilliams** [comment]
Funny how I had never stumbled across this error until about 48 hours ago. ;)

**Comment by Chick3nman** [comment]
https://github.com/magnumripper/JohnTheRipper/blob/0432f83326992bb486887bf37411cc7ba230a863/src/ztex_bcrypt.c#L137

The logic issue that causes this is here ^

**Comment by roycewilliams** [comment]
Yep, I would have sent in a patch but I wasn't sure if the cap was really 18 or 19

**Comment by Chick3nman** [comment]
Either the logic on line 137 is incorrect and should be `> 19` or the logic following that line is incorrect and the true max supported should be 18. I'm inclined to say that it's line 18 but i need to review the rest of the code just a bit to see if i can locate the real source of the limitation, which is not obvious to me just yet.

**Comment by Apingis** [comment]
It has internal limit for cost no more than 19 (to save resources on decrement implementation, only 20 bits is processed). Previous version of the design had 19-bit decrement which occupied as much area as 20-bit.
I'm afraid I did not properly reflect that change in ```src/ztex_bcrypt.c```.
Thank you!

Processing of such hashes requires to adjust timeout in ```src/ztex/device_format.c:31```. It takes about a minute to generate a batch of such hashes.

**Comment by solardiz** [comment]
> Processing of such hashes requires to adjust timeout in `src/ztex/device_format.c:31`. It takes about a minute to generate a batch of such hashes.

This change isn't included in #3807, and its need is not documented anywhere except on this issue, correct? If so, perhaps it should at least be documented? Can JtR simply adjust the timeout on its own when it encounters hashes needing a higher timeout value? Or can it at least output a warning suggesting what to change (and preferably it'd be a `john.conf` setting rather than a source code edit)? Thanks!

**Comment by solardiz** [comment]
@Chick3nman You got any of those boards too? If so, we'd appreciate testing of #3807 from you, too. Thanks!

**Comment by Apingis** [comment]
> Can JtR simply adjust the timeout on its own when it encounters hashes needing a higher timeout value? Or can it at least output a warning suggesting what to change (and preferably it'd be a john.conf setting rather than a source code edit)?

It prints a warning suggesting what to change on hashes with setting 16+.
Having the timeout configurable in john.conf feels a good idea, easy to implement.

**Comment by roycewilliams** [comment]
Given that these boards have (somewhat) similar performance, the warning could probably also recommend a john.conf value to the user?

This looks like it's working well - the mismatched warning no longer appears. A DEVICE_TASK_TIMEOUT value of 60 (seconds) wasn't quite enough, so I am running with 70 seconds and it seems OK. 

```
$ cat bcrypt19.hash
$2y$19$3x2me87zKlcwJtfplFHgce4t3B5l3Nm.VNQ4Esxg1ESkH8hBuQ9DO

$ ./john --progress-every=60 --wordlist=rockyou.txt --format=bcrypt-ztex bcrypt19.hash
ZTEX 10 bus:1 dev:70 Frequency:141 141 141 141
ZTEX 11 bus:1 dev:66 Frequency:141 141 141 141
ZTEX 12 bus:1 dev:61 Frequency:141 141 141 141
ZTEX 13 bus:1 dev:68 Frequency:141 141 141 141
ZTEX 14 bus:1 dev:63 Frequency:141 141 141 141
ZTEX 15 bus:1 dev:57 Frequency:141 141 141 141
ZTEX 16 bus:1 dev:60 Frequency:141 141 141 141
ZTEX 17 bus:1 dev:65 Frequency:141 141 141 141
ZTEX 18 bus:1 dev:59 Frequency:141 141 141 141
ZTEX 19 bus:1 dev:69 Frequency:141 141 141 141
ZTEX 20 bus:1 dev:64 Frequency:141 141 141 141
ZTEX 21 bus:1 dev:58 Frequency:141 141 141 141
ZTEX 22 bus:1 dev:67 Frequency:141 141 141 141
ZTEX 23 bus:1 dev:62 Frequency:141 141 141 141
ZTEX 24 bus:1 dev:56 Frequency:141 141 141 141
Using default input encoding: UTF-8
Loaded 1 password hash (bcrypt-ztex [Blowfish ZTEX])
Cost 1 (iteration count) is 524288 for all loaded hashes
Note: This format may be a lot faster with --mask acceleration (see doc/MASK).
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: hash with setting=19, computation is going to be very too slow, timeout is possible, consider to increase device_format.c:DEVICE_TASK_TIMEOUT
0g 0:00:01:09 0.09% (ETA: 14:22:02) 0g/s 107.4p/s 107.4c/s 107.4C/s bugaboo..alegna
0g 0:00:02:18 0.13% (ETA: 2019-04-14 21:49) 0g/s 107.4p/s 107.4c/s 107.4C/s aireen..kamehameha
0g 0:00:03:27 0.17% (ETA: 2019-04-15 01:34) 0g/s 107.4p/s 107.4c/s 107.4C/s juggalette..moonwalk
0g 0:00:04:36 0.21% (ETA: 2019-04-15 03:50) 0g/s 107.4p/s 107.4c/s 107.4C/s moonmoon..110202
```
Thanks a lot! (And now that I have my setup powered up, refreshed, and solid ... I will also test some other things in one or more of the recent john-users threads!)

(Also, thanks for the serial-number substitution work. As you can see, this is working well. I put some dummy serials in as well, so that my numbering would start with 10 and be sortable when needed.)

**Comment by solardiz** [comment]
Thanks, Royce! BTW, I confirm that this is the expected full speed at bcrypt cost 19 on your boards at that clock rate.

**Comment by Chick3nman** [comment]
> 
> 
> @Chick3nman You got any of those boards too? If so, we'd appreciate testing of #3807 from you, too. Thanks!

I wish, don't have any of these sadly.

**Comment by solardiz** [comment]
I consider this fix tested by @roycewilliams, so I'll close this issue.

@Apingis You might want to fix the grammar in "very too slow" (leave either "very" or "too") next time you make an update.

> I have access to a few other types of FPGAs if you would like to work on other implementations

@Chick3nman What other types of FPGAs? If it's Xilinx 7 or 7+ series, we might be interested. More 6 series is probably not worth the effort now, Altera/Intel is too much of a change, and other companies don't have large enough FPGAs.
