### ISSUE TITLE
7z file have not correct password

### ISSUE THREAD

**Issue by dosoos** [magnumripper/JohnTheRipper#3806]
this 7z file hash:
`xxoo.7z:$7z$0$19$0$$8$9cd6504379dc3dbe0000000000000000$2944499551$144$130$83f734531750a6d4b2dad4e41ffc90206f7bcad1fa627d1f35f6e646e727fdc10021eb9115385021bfe3cbb6abd61b9b0312370c4dc7cee52dfad81c3b1b2a7560761b6762ba731e9fbaa417b051df3cd480af1f90c4c0aac8e26315c93af6ab7f2bc83d1523e318c2b3290a036ac943bdbeaaac52a14d51e1356e6fab62f7eeb7f10f751c71ce9d96e8f0f6e32cbb3f`

john cracked password is:
`Dahknee01`

but this password is not correct!

**Comment by dosoos** [comment]
john version is latest(b2d70a97f820324d7fa9d9dcfe75845946325f51)

**Comment by solardiz** [comment]
Confirmed that the password "Dahknee01" cracks that "hash" with both our CPU and our OpenCL format. No idea if it's the correct password or not, but @dosoos says that it is not.

@dosoos Can you please try adding `FMT_NOT_EXACT |` to the beginning of (currently) line 759 in `7z_fmt_plug.c` or to the equivalent (currently) line 781 in `opencl_7z_fmt_plug.c`, re-run `make`, remove your `john.pot`, and let `john` run against that "hash" again. See if it cracks only the same password or possibly also other passwords if you let it run for long enough. See if any of those other passwords let you decrypt the archive. And let us know of the results, and also tell us whether you're using the CPU or the OpenCL format. Thanks!

**Comment by dosoos** [comment]
ok, maybe Is there a problem with the script that generated this hash? I used the script 7z2john.pl, i can share this file let you test

**Comment by dosoos** [comment]
i add `FMT_NOT_EXACT |` to 7z_fmt_plug.c file 759, this is correct ?

786         fmt_default_salt_hash,
787         salt_compare,
788         set_salt,
789         sevenzip_set_key,
790         get_key,
791         fmt_default_clear_keys,
792         crypt_all,
793         {
794             fmt_default_get_hash
795         FMT_NOT_EXACT |},
796         cmp_all,
797         cmp_one,
798         cmp_exact

**Comment by solardiz** [comment]
> maybe Is there a problem with the script that generated this hash?

That's currently irrelevant. We need to see if you managed to get a false positive crack or not.

> i add `FMT_NOT_EXACT |` to 7z_fmt_plug.c file 759, this is correct ?

No, that's incorrect. You seem to have confused 759 with 795. Please add `FMT_NOT_EXACT |` to the start of the line that already has other `FMT_*` flags on it.

**Comment by solardiz** [comment]
> but this password is not correct!

Since you managed to confuse 759 with 795 so easily, frankly I now have serious doubts you tested the password correctly. ;-) How did you test it? Did you possibly e.g. enter "O" (letter) in place of "0" (digit), or something like that? And what makes you think the password is incorrect. Please re-test, and please be more specific about how you test the password and come to the conclusion it's incorrect.

**Comment by magnumripper** [comment]
Please note that instead of rebuilding Jumbo with FMT_NOT_EXACT you can just run it with option `—keep-guessing` added.

**Comment by solardiz** [comment]
I wasn't aware of that, magnum. Thanks.

@dosoos Then that's what you should do - use the `—keep-guessing` option, and let us know if you manage to get more than one guess.

**Comment by claudioandre-br** [comment]
You can try your cracking process using the attached file. It is a zip because GitHub does not accept .7z. Inside it there is a .7z encrypted file.
* You already know the password. But, you can try something like this `./john hash --mask=Dahknee?d?d`
* Also, to avoid troubles uncompressing **your** file, you can use a command line tool. E.g., 
```
$ 7z x xxoo.7z -p=Dahknee01
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=C,Utf16=off,HugeFiles=on,2 CPUs)

Processing archive: xxoo.7z

Extracting  Modelo.txt

Everything is Ok

Size:       21
Compressed: 167
```

Try your cracking process using the attached file.
[Inside-it-there-is-a-7z.zip](https://github.com/magnumripper/JohnTheRipper/files/3098071/Inside-it-there-is-a-7z.zip)

**Comment by dosoos** [comment]
ok, this is my file
[Encrype 7z file](https://drive.google.com/open?id=1MBe86QlyeS5KjxO_D9iUxQYpnx4py4A0)
maybe generate hash file error

**Comment by claudioandre-br** [comment]
Confirmed, the format is not working.
```
# 7z x 20190412-054608-1555047968_0.2537934672077743.7z -p=Dahknee01

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,2 CPUs AMD Athlon(tm) II P320 Dual-Core Processor (100F63),ASM)

Scanning the drive for archives:
1 file, 15807083 bytes (16 MiB)

Extracting archive: 20190412-054608-1555047968_0.2537934672077743.7z
ERROR: 20190412-054608-1555047968_0.2537934672077743.7z
Can not open encrypted archive. Wrong password?

ERRORS:
Headers Error
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

```

```
20190412-054608-1555047968_0.2537934672077743.7z:$7z$0$19$0$$8$9cd6504379dc3dbe0000000000000000$2944499551$144$130$83f734531750a6d4b2dad4e41ffc90206f7bcad1fa627d1f35f6e646e727fdc10021eb9115385021bfe3cbb6abd61b9b0312370c4dc7cee52dfad81c3b1b2a7560761b6762ba731e9fbaa417b051df3cd480af1f90c4c0aac8e26315c93af6ab7f2bc83d1523e318c2b3290a036ac943bdbeaaac52a14d51e1356e6fab62f7eeb7f10f751c71ce9d96e8f0f6e32cbb3f
```

**Comment by solardiz** [comment]
Unrelated observations while looking into this:

1. Our 7z2john.pl's dependency on Compress::Raw::Lzma is nasty. Can we possibly avoid it for some/most uses?

2. We only mention licensing terms for this file in README.7z2john.md - perhaps this should (instead) be in the Perl script itself. I only learned of this documentation file by reviewing git commit history for 7z2john.pl; if I didn't review that, I would think we don't have that file's licensing terms anywhere in the tree.

**Comment by magnumripper** [comment]
Just off the top off my head we’re using Phil’s version now, from hashcat, with minimal changes for our purposes. Any copyright/licensing changes would be best off coming from upstream. @philsmd

**Comment by magnumripper** [comment]
Also btw did anyone try cracking the sample file with hashcat?

**Comment by philsmd** [comment]
the file "Encrype 7z file" link from above contains indeed an interesting file.
The CRC32 checksum within the header of the 7z file is 2944499551 decimal (or 0xaf817f5f hex) and the AES decrypted string does indeed match with that specific crc32 checksum (you can just debug/print the bytes that get decrypted):
```
$ echo -n 87cb5696cb52fa40403bc08ea6e353e50c5a376f811ceb281a36cedbf1314d520f86587cc689cf6c78244999ce5b593863e7e047072520edaf52dafd7032bc1116f9996592e7e258c659b6e60ab095deaaa7034db058c5d59c1dd017cf0bdd7a475ac0d00d6c798acce505cc208a25ca243b2a231c8360937fb257f3a6a399e584c4 | xxd -r -p > c.txt

$ crc32 c.txt 
af817f5f
```

even though that in theory for a crc32 checksum with 4 bytes it is possible that there are collisions, it's actually very rare and in this case the probability that it has to be AES decrypted and need to be of exactly 130 bytes and it (still) exactly matches the crc32 checksum with a non-random looking password ("Dahknee01").

I also investigated this "problem" with the p7zip source code a little bit and even p7zip thinks/confirms that the password is correct (ReadAndDecodePackedStreams () doesn't give any errors as it normally does with wrong passwords, see https://github.com/jbdemonte/p7zip/blob/80636a06bc861d8fc004fe1913900b095cf1a399/CPP/7zip/Archive/7z/7zIn.cpp#L1581 , but the ReadHeader () function fails afterwards, see https://github.com/jbdemonte/p7zip/blob/80636a06bc861d8fc004fe1913900b095cf1a399/CPP/7zip/Archive/7z/7zIn.cpp#L1603 ).

I didn't analyse these decrypted header bytes yet, but I do not see any file names or any other non-random bytes within those decrypted bytes.

Do we know where this file comes from, what the "real" password is (if we really consider the case that "Dahknee01" is the wrong password) and if it was somehow manipulated or generated by a special program/lib etc ?

**Comment by magnumripper** [comment]
> even though that in theory for a crc32 checksum with 4 bytes it is possible that there are collisions, it's actually very rare and in this case the probability that it has to be AES decrypted and need to be of exactly 130 bytes and it (still) exactly matches the crc32 checksum with a non-random looking password 

It shouldn't be rare. Given an optimal CRC32 algo there **must** be one collision every 4 billion tries on average, so with current GPU speeds we should see them once per hour. The fact it's non-random looking is, I guess, merely because that was what was tried (e.g. using wordlists/rules/incremental mode).

Had the padding check been in use, we would require (in this case) 14 consecutive padding bytes after AES decryption. That's 112 bits so virtually can-not-be a false positive. Unfortunately we've had indications (actually just a single one) that the padding early-rejection isn't 100% safe so it's turned off by default. I should probably make that a john.conf option instead of a compile-time choice.

**Comment by magnumripper** [comment]
I just confirmed that the padding check does fail for this hash and password. My bet is it's a real FP and you can either try again with `--keep-guessing` or perhaps try enabling the padding check (this also gives a good boost).
You do this by changing `#define TRUST_PADDING 0` to `#define TRUST_PADDING 1` in `7z_fmt_plug.c` and/or `opencl_7z_fmt_plug.c`.

**Comment by philsmd** [comment]
yeah @magnumripper , I completely agree that it's not too difficult to find collisions with only 4 bytes crc32... even though the 7z algo with 2^19 iterations is quite slow and therefore you won't find as many because 4 billion tries/passwords is already a lot of work (with 2^19 iterations)...

if we just took at the crc32 checksum, it's of course very easy to find 130 byte long strings (even if semi-random) with the above crc32 checksum (2944499551 = 0xaf817f5f):
```0104d94d6d78a9b5844f7fd4f219e8588448899e16218d967b125ebc610c57c0852cb321ee4eba8e8a54be39eb118f9a3126364ce10fca30e23b3c2b99757685ed00104b2f7a2d97823579e105227e99803858bfaa1ad8e8193e30293c73fe3893035617747ab6bd4f3ff519475f9578557fc132b65d9a67b729c343eb009a802300
010499426605904177600832b8099928943195c9d40253233b4bf396e62189ac666a2554b669894b070c28dc8d7c99a0210069dec52e3c356614a7f24a59d4e8826154cb1420896f81094dab1f29c06b8d13fec15e45267342432ff051511cadcb4f9e3e483514a01f651390fc0c508633573f73a869a5153833936a5b4fd8b50e00
01044c73112e1c957d6a86cca413d1f22811f41b502a404231706442323d32664a268982c673a893c9001d542f63bf2de35257723d1acc2c434981c0211a07034a35048cea7a142b7a342c86d46818f198354589e958d9a14a02482d73643ccac74d469fac70d362df3031f6bb03989cdf509bd1845b210fe13e5deb481d0ee2e400
0104731765730513415b0c6c054dedc3f97acd763f3589e0113abd0ec94c32b8f413f073151889dae83dc895092f1e09c73c07f77f08f4b2905bf922fb6baec33e3a02f4cd4d1d0b853eccb5c074aabffe2f9837bc48f64c5d0b352b626562616410692c736e2747e654d028df6514c4db63a5ca761341e76a2931bb7656bd301700
010450535556192e531e520d6a08cabfba2e8522a01ee10d957af88ffd6eca09d8423067753e389da339eb0b883d37d49b3cc440072fdc1598765c235471ebcf483a3f26ea56a5962e0201d3eb397019b9251144e47bfc65ec2436c33839683ee4494219913fdea2da60e3026a78f095553fee18e70df9c0907f28d74210416df500
01045d49ac08c7b36765e6ef330d69f3a169deffc667bea45d19b570260f3b214860b17b5f4f11a9bc35630bfd578a206e20fbcec91116caee1999125e65599a0d57708a540b9247d03af24d4a27389b794018dbba63761f9a409c4fc4611d71514d1e0c413537501f132b638a724b6bb30871bf054861d6055640c8b765bb6b2b00
01043cd84532ca1fe42add715f4c5bbe2b6cc382105f24615a7a91ebee533933434086f4305cae1fc2636b7d8d7c10a9162e7b362110ba6914214c44e05856fc147546494640ded404532d6bf670f78e91394e376b2a572b474a357e0627f7bec454f59c4c25d150e43f6004034152090876fc422853e5f044625386f533d487c300
01044c630070d83e1d2f00bec54a82eb4510303edb1acdb2d42d256b0b6434908657ec0d5f26c1516a4dc8561e3b3a274d4b1c84941b29f2c32e0877e94a8b887516009479184e12f964cecdf87834529935bc740121dbbf261dbe497623cecc5a3f84345e7462b46c22c50c42334434e5514c621f2f4c351574dafe031daf62d700
01043c8f4751a222be7b92f5ad1e5158ee50de0fe4001157640000a49f41652bcf3cd426a97ff82f146d8cb2fe260dd13b04d81c32330092ba64a1cad115e19e3e6e7b1ae35dd001901f08721d2f58ad0c103fc4cd6cc533e444dcc81406fe5c6e5583deaa6940d7e63d999de32032de523c0ed3cb4dbde8c27b64fff8789e1b7100
01041bcf1e0e21fd8b597fed2f32ff77461e5bb05304e10a256c8bac576ca1ff1628c2e7af2541692955dac19577a30bdc3e71ee997770612b78964d6e068076a56e4b6262238e6f4f5076ac8d01e389724a5b08f431c6048079d7a0703b7392470a5811893a4dbb4440cf68cd5d3f1293499da1927ce6a9aa3ac26dbc656cc04400
010455a6bc078f51b672500337068bc9343e6622a4151ca1d57184a4096ade88d625578fe7534f45b218bee876000026e251d143925a4e9320027595d668081c502d9b9c285f88e47548c5197448f37dfc10596476605da87e432c0b9b21acfe9e1e94a39106f3ac8767e0a4f16ce587443ee7d74d2b5f296a139e82b7148e937700
01047e559055197f9e76a8d400169931a67908580211eb09483889d3a90868f2cd28fd54913bab81a4731715b1498a37e05e1637811fea179661853750048f0c0b0849b0316d734a151e4cbc337e6e465446302b1559508d6d2de4ba161400ea647b86a6e9086677b84e511a8542dffafa795991684e664cd852b63fd477af219a00
010437eb0c339fa7196defebc05736f43806eeea80309fc6e5707bf4423127ea2a7ad8091e1d9713d5138cf37102ba505d46b7381045504b0220ca535733e9660e5c9546033f63f2717faf04a4450b3b545f719f333b5884606afddff02704d8e15e6f05ec21f55a2a5fc2c9600fea0e401c03f06a37895a41666f52e853eefcc000
01044c234a6987dfe515db3b795bb1a889083d86ec44f44a453f2261944571fb6c5b15ddd90c2b9a685502d3d25499ddbc0de3054c2953d0f64d31dcc31029888e78b3d0703da8954d5c44a5e3112493b67207b626724b331365cc3bf96be19c56571f434a516ac6a6625ef11059485705206ad99720f574b43af260d16c8e23ba00
0104432cc7477699db6f4118c00c50112809f75f76017728eb6834d0e13ebbd69779cf216d098b0d3711a18b151db24af600e941b14afe9db56da97c0914e9372b7ae6b8bb7848c49a5986c04c4660981c6bc285fa3f109f953f0d3e467450441c4207cf3a7bed30175b2fd14e6f5f3dc621bee3a4790483d67a30c19f64ebab0200
01047d211303c6a147305b959771af4ac864ad86ff2744b1b0188a32f8684b4f8d4faa468a34bd3a7b78f8e40b00ff5756597b0b5420c53a5668a64e8f6fc9f5776d7d128b6c58dffe649b8a7028b85a45465c75124543a09d3d1e81e151c58ad4298d226d3e548a91120e0b1612e4726964e71add6787c47e6889675562082dff00
01042498f85733586179ef0a40707b786e1cdfb37e79052a772bbe14493ed675085a77770b525f69dd7dc2a14739e73da349abdd0c5407bdf96d4c616554b80d8d12893865224da38634aa8105691bae0a1e7dd1696c612010667ca5266a3198b342d24e780a481ae542810f291b52e40c23d1963d23b2a6c3063f656c486a8e5c00
01045965de30625c8d021b87c54b6741da7eb021e322aef2fd4c9124716ffc454753f65def7a78cd245e56f9dd73105a8a7d6ca9855163cf403029cf825fa272562659f6695105bc523f7df011698e336557d1834d6e5f61427e0983a87509a16500917b032bf6e7c959066335566089d22f2ff6b93233040b2b8a8b3e0895d56300
0104468e5379db537c41af2a0d4bdf9f5a5d3f3b983f01b2972e64e522606286bf73d8bb243f20e2af6858ed4a35560eae77bffc486492a1027407219327ddf8f41c6ee1412baf74ee41f558767b81f80248d305b60a006b607222dae83ae5756d6d704de8141a99d809f82e1455a2a9df09acbce3050a7d1b0e0c8875503b0ffe00
01040e4bd42fafd5001b46c2e74aceb37a2e166bb070314cc204130b572d9ca68e2bac9f6366336a3758ee642965423308092150ef572079ce5b4799650349429b3ace8d975513dda05ab12e743fad3c6f503a318565a9f8f80a3ae0d906568c8c236bcec55214bee50420a3922ac9717e1f926e6f31ee770413035cc02dde428800
01040232a01563263f56dc199c4109b48c0dca34875d89c3876744ab882c273d676ecbc6d846c6f59c23d62f444ad2ffba7ed8941367c5789e0052301e35559a3f71e1366f2191315d6fd73c1222e73bc8578ba44531b76e5a7816b3e9284ff2a50099b05a05d86fef7c7846f218ff6f76393361e4512cbd197d7e10983b6601ef00
0104468e5379db537c41af2a0d4bdf9f5a5d3f3b983f01b2972e64e522606286bf73d8bb243f20e2af6858ed4a35560eae77bffc486492a1027407219327ddf8f41c6ee1412baf74ee41f558767b81f80248d305b60a006b607222dae83ae5756d6d704de8141a99d809f82e1455a2a9df09acbce3050a7d1b0e0c8875503b0ffe00
0104065501547cabff7694a2da205aca4b7777b9bd790fd275207338903a042c2b70134e1218fc210c025c8fce4b7d89c0520ee0717eb43a1b5dc4c6812d076a534a45a3a94ed796493326c79f1079b29a2fc7f302357616fb5fad08232056d634203cc54e3db557531b6741860a7a6f317d20a82c75db306819ed39f80375a9b700
01047ecb15448bae29476c7bd56803009b5c92ae69465e4fdb1246484c70dfae1a08e47a991d1ec632605613bd49362b1e768e94d924adde8d72fb7f792f3659d16f74429e5c601ffd3664bb8048605aca2a3421872b7a51650db68756081beaec53eb2e08680014f6219ff0111ec1775c45f72d602a1a97742974682544c242e500
01045411691c1098024d7b70dd12fe09d056c7c93f1e3f4f8c7101ebfa32a88f3a2513e32b6381be360a5087712ab55f59274e0767267aefb9680e1f0d42383a863953296221ac2e1d51ed530d5b47f8067197f9020596916b561df91818761f9766b5c70c6f79f22b549cfde214ba1f31038f051d27dc66bc1635db6257a06e5000
01041f6fd77c40306158e09cfc0e626ab31b189e532e643885116371412586d82c28ee4307537957eb010ba6e96a12dbbf76853d795ed5ac9f3b4e508d5bbf20ef1ca8b8162739c1df2ff3e44f49f2f2906dfdeb51118c6dee36e456645bb4dcc429b286482e35fae232dbbbba2e08046b01c971682d6dad080d84a7102139491f00
01044137757ebf60a414a10450191c18183ec956eb1b5f993912cb2b7c5c4657d10d14e6465a4662545bbbacc06ceea46f1412531840071db00f9f4f945f18f4be06cec84545239bc50a4eac51260771873f10705301212e023a4ff8865062e5380a14497a188329db2d5913df55188ad91bbb4fde1afc12730b91ddd55cf2c52000
01043a45b465769a31499a65623155f51e79f5edfe2e3b1372609050ea3c583bc51aa2f5aa09e5a1581d6545df0f622c091940ffce30233f721af19d023df154374224f3655dfc461751518011073ea7bd5384cd963e0a9722689003d5099242fe0c5c937e553fa1921eb662202c9ec245348ae0681f98d9f229ac15a66ed0956800
010448d0a2552aab8e4ed0498c3dbb09d33d8f1af93e7929251399410a659001d81460bc2141918d1c60249fbd1a6032837aebedcb4a245e6a29d336487e4f60317b5900ef5116b61f6ffc0a744dbbd12f6e29624e40154ac608804078093ff2612c3d63d75edcf0fa4d68feb6056c08e046a5f49b27b4384603b5be530f76977700
01045224be55a715a60d3ca135553e38ae2dd2934e6a354cd44dec439f40eb495631c22ef4391dccc41f21ca915865db9b7ff202f41346ef271c1a6d8874b2df971905d64f3f8ffe093c90a0c37b4844d9284d52454db672600b778b1b7eba55936a732df5754d82ad50dcaf14743f9c0e561e1ac95934206d618e4b4f2842d92f00
01046808373c687717345604c937b56bfe2f007bf22ab20e1e291e32d463dc9fb005e1bc7249b265bb447f1c0538374f451d91bf2f4f4cf27c19f36dca7db119d15118e81b6a1f304e3855f07b532dfcf02852a1e621546bed6e28729256db17aa6325c1626055e73038ec197b40647b7e1f83a66f5030a6e1286168d9078bdd7100
010443486a789c157358f84ec75457dce64e458ac577ead44017f8e6d1591a8be248424b8b7ea9a6555657aada1a7e8b7e47ca91366a9d47d66b8095577cf22045731213f01b44206348ac1e2566442c9c3466bf6d33a5040e0e497fdd2e519eb437e061ea78c9b0fd60d5dcc9477a500f39b6396b3d01790f273205a47cfea41500
01046c057a6898893941e61fce4cabb0a6331b765607413bb92665f89b4054d3af3e6d86893afd5e692f0569e12f0abfdc07684bf07eec937d443cf6660a720e407fa208a15f2ce8ca397a6e102e3fc25e522d4b6a18d2e60b214e69fc0ccdda9443234123770b975403b33b182617d5a047c0fec405c3a924305bee6b33c679b500
0104715ee447bc517e1946d44e1a79c1656f71b748327840bf7c7b16ce35bc4fc3311b783160339c3227a5c70545f4c19251e2c4f91f0731a5613411bc195e749b08d57b6228c9d81379da07a4135da9cc436c1a4340e0028b16748ed94220164e650215eb36cfde8b61b030872cd1b0c4233cbc05286654a5168feabd149ba03d00
010476640179961cf767093c1d14d2b22962d3cae44adcfad6255fd2a11e422107448502f04b1e778c5cce61c6147d26e10b7ff9923c75fab715fb55723cb94e0517b5fcf1795c5609480c31897d8fe88832c6f3d521799c2612787d1d0204e2576466df396f07f1be291cc4166f98e78353e7b5e3791633241fb1ac294a4bb79f00
01040c7044736bf3843e322c7e77b7bff719c005655b31064865540bbb3db9bd8565e8d1c9647c97a94ab3efd278d2716d05f68150557a085853397b287f83d48e7dadf17d631c041e6594f1d266579c5920d3d56e745b671f26588451000bd90509c940082d6a4e071e8d87ce648ab2de58b172f63ef49b2c38bc21d36521b7d000
```

here I assumed that the strings need to start with \x01 to indicate the header for the file metadata and the \x04 for the file list ... at the end there should be \x00 for the end of the (file) metadata.

all the above hex bytes have a crc32 checksum of 2944499551 and I found them quite quickly (within some minutes) just be using a quickly hacked down ansi C code that uses srand () / rand () to generate the 127 missing bytes (of 130 total), checksum them and compare them to 2944499551 .

Said that, I'm still confident that it's quite difficult to get some real false positives with the slow algorithm like 7z, especially when you are not mask attacking the hashes, but using a dictionary attack.  OP was quite lucky to find a false positive in my opinion, because you won't find them that quickly for 7z (remember 2^19 rounds) !
