### ISSUE TITLE
7z format set_key() modifies the caller's key

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3808]
I just went to `relbench` our upcoming release vs. 1.8.0-jumbo-1, but the 7z format of a `--disable-openmp` build of our current code segfaulted on me. Per gdb, the crash is on the assignment to the caller's key here:

```c
static void sevenzip_set_key(char *key, int index)
{
        /* Convert key to utf-16-le format (--encoding aware) */
        int len;
        len = enc_to_utf16(saved_key[index], PLAINTEXT_LENGTH, (UTF8*)key, strlen(key));
        if (len <= 0) {
                key[-len] = 0; // match truncation
                len = strlen16(saved_key[index]);
        }
        len *= 2;
        saved_len[index] = len;

        new_keys = 1;
}
```

I think this is not allowed by our formats API, and we may be passing non-writable keys.

@kholia Can you (at least) comment on this, please? I think you wrote that format?

**Comment by solardiz** [comment]
With the `key[-len] = 0; // match truncation` line commented out, the format passes self-test for me. So why was this "match truncation" thing needed? If it's needed, then are we missing a test vector that would ensure we're doing everything that's needed?

(BTW, there's huge speedup for "Many salts" in this format. Does this mean it will actually crack multiple 7z archives at once roughly at the price of one? Have we tested that? We should.)

**Comment by solardiz** [comment]
The crash only happens with:

```
[Debug]
Benchmarks_1_8 = Y
```

**Comment by solardiz** [comment]
My _guess_ is `get_key` won't match `set_key` without proper truncation when a candidate password gets truncated in that place. This would be nasty. But for now even `-test-full=1` passes with that line commented out, indicating we have no proper test vector.

**Comment by kholia** [comment]
I will be away for a while. This format has been heavily modified since I wrote it.

**Comment by solardiz** [comment]
> I will be away for a while. This format has been heavily modified since I wrote it.

So we shouldn't expect any work from you on any of the issues assigned to you now, prior to our release?

**Comment by magnumripper** [comment]
The truncation could be eg. an invalid utf8 sequence. We should use ‘const’

**Comment by claudioandre-br** [comment]
The commit says: https://github.com/magnumripper/JohnTheRipper/commit/242931064b16bb07191a0a92aab44186a42e4fbc lei-april committed on 19 Aug 2015

```
7z: optimize SIMD performance

sort passwords by length before feeding them to SIMD SHA2 function
```

**Comment by magnumripper** [comment]
Get_key will be correct anyhow. Just drop that offendng truncation of key and keep the strlen16!

**Comment by magnumripper** [comment]
OpenCL version is correct

**Comment by solardiz** [comment]
The 7z format still appears to work after this fix, so I'll assume the fix is correct.
