### ISSUE TITLE
Deal with our radius format weirdness

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3809]
Our "radius" format reports much higher speeds for "Only one salt" than for "Many salts". This prompted me to take a look at its code, and here's what I found:

The format implements two different algorithms, and there are only two test vectors - one per algorithm.

The first test vector corresponds to an algorithm that doesn't even require cracking - instead of XOR'ing and comparing, we could have XOR'ed the other way around and printed the plaintext password. Indeed, the XOR'ing is also extremely fast, even if ridiculous to do like we do it now.

A question is whether that algorithm even fits JtR, or should be implemented elsewhere. If in JtR, then maybe we can have `valid` figure out the plaintext passwords and print them, but that wouldn't get them into `john.pot`. Maybe we need a formats interface extension where the format itself could suggest candidate passwords or explicitly provide cracked passwords.

As it is, our implementation of this algorithm is similar to what we do in the "dummy" and "plaintext" formats. Perhaps we should at least document that in a comment in the "radius" format.

The second test vector corresponds to an algorithm that requires computation of MD5 per candidate password. It is thus not as fast. Ideally, our first two test vectors would correspond to this algorithm, so that we'd have proper "Many salts" benchmark for it.

As a first step at fixing this issue, I'd like a second test vector (with a different salt) added for the algorithm that does require MD5 per-candidate, and those two test vectors specified at the beginning of the `tests` array. Dhiru, can you take care of this now please?

**Comment by magnumripper** [comment]
Can’t we just set it to raw for now?

**Comment by solardiz** [comment]
Our reporting of two tunable costs for some other formats implies that "Raw" should be equivalent to "Many salts", which in this case will imply that we'd be benchmarking a mix of MD5 and XOR and reporting an inbetween speed. This feels weird.

**Comment by solardiz** [comment]
As a temporary workaround, maybe we can set this to "Raw" _and_ list the same test vector twice.
