### ISSUE TITLE
-test -mask segfaults with Benchmarks_1_8

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3810]
Similarly to #3808, there's a write to test vectors in `bench.c`:

```c
                if (options.flags & FLG_MASK_CHK) {
                        plaintext[mask_key_len] = 0;
```

As a quick fix, maybe we should just check for this combinations of settings and refuse to run with a reasonable message, rather than segfault.

**Comment by magnumripper** [comment]
Switch to a copy in a ‘static char[]’ right before this is just as quick a fix

**Comment by solardiz** [comment]
While fixing this issue is within consideration for 1.9.0-jumbo-1, it is _not_ a blocker for the release because it's only triggered in an obscure situation that our users shouldn't face (it's relevant to us, not to them) and the only impact is the process crashing instead of e.g. it printing a message and terminating gracefully or ignoring a setting. Not a big deal, just unclean.
