### ISSUE TITLE
Blockchain format performance regression

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3813]
1.8.0-jumbo-1 `--disable-openmp`:

```
[solar@super run]$ ./john -test -form=blockchain
Benchmarking: Blockchain, My Wallet (x10) [PBKDF2-SHA1 AES 4x SSE2]... DONE
Raw:    313284 c/s real, 313284 c/s virtual
```

Today's bleeding-jumbo `--disable-openmp`, `Benchmarks_1_8 = Y`:

```
[solar@super run]$ ./john -test -form=blockchain
Benchmarking: Blockchain, My Wallet (x10) [PBKDF2-SHA1 AES 128/128 AVX 4x]... DONE
Raw:    265116 c/s real, 265116 c/s virtual
```

I haven't checked if the test vectors have possibly changed in a way causing this.

**Comment by solardiz** [comment]
This _might_ be another victim of benchmarks change, but some testing doesn't confirm that this is the only problem just yet. I'll run more tests.

**Comment by solardiz** [comment]
The benchmarks fix doesn't help the Blockchain format. Still need work here, @kholia.

**Comment by solardiz** [comment]
Disabling legacy benchmarks gives very close to the old speed:

```
[solar@super run]$ ./john -test -form=blockchain
Benchmarking: Blockchain, My Wallet (x10) [PBKDF2-SHA1 AES 128/128 AVX 4x]... DONE
Raw:    311228 c/s real, 311228 c/s virtual
```

So I'll just assume the only regression here is for correct guesses, which is OK.

**Comment by magnumripper** [comment]
It just hit me we had a feature back then that scrambled passwords when using benchmark_length >= 1000 or <= -1000 and it’s now obsoleted and dropped. That may be the cause of some apparent regression issues
