### ISSUE TITLE
ZIP format performance regression

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3818]
"ZIP" regression from:
```
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 4x SSE2]... DONE
Raw:    3692 c/s real, 3692 c/s virtual
```
to:
```
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x]... DONE
Raw:    3072 c/s real, 3041 c/s virtual
```
No mention of multiple tunable costs, although I think there are some, @frank-dittrich.

Just before the benchmark fix:
```
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x]... DONE
Raw:    3548 c/s real, 3548 c/s virtual
```

The first two test vectors appear unchanged. Old:
```
$ egrep '9ffba|855f6' ../src/zip_fmt_plug.c|md5sum
ea90d8b2fd5d0e0a977f1cac67aca045  -
```
New:
```
$ egrep '9ffba|855f6' ../src/pkzip.c|md5sum
ea90d8b2fd5d0e0a977f1cac67aca045  -
```

At the same time, we have a speedup for this same format in OpenMP-enabled builds. 1.8.0-jumbo-1:
```
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 4x SSE2]... (32xOMP) DONE
Raw:    43885 c/s real, 1383 c/s virtual
```
New, post benchmark fix:
```
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x]... (32xOMP) DONE
Raw:    48907 c/s real, 1524 c/s virtual
```
New, pre benchmark fix (so using first salt only):
```
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x]... (32xOMP) DONE
Raw:    56496 c/s real, 1777 c/s virtual
```

**Comment by magnumripper** [comment]
I’m stuck with no computer here, but did we not drop FMT_NOT_EXACT post J1?

**Comment by claudioandre-br** [comment]
```
Author: JimF <jfoug@cox.net>
Date:   Sun Jul 6 22:03:13 2014 -0500

    zip2 format. #434 #691  Removed FMT_NOT_EXACT. Now fully detects passwords.

```

**Comment by solardiz** [comment]
> did we not drop FMT_NOT_EXACT post J1?

Jul 2014 is before 1.8.0-jumbo-1, so this shouldn't be what caused the performance difference. Also, most if not all changes in that commit are for pkzip, and this issue is zip/winzip. (We have a separate issue for pkzip performance regression, though.)

**Comment by claudioandre-br** [comment]
Well, *cough*, I really can't see these regressions fixed.
* Anyway, how have you build JtR? I can get 3.6k on 1.8J1, but not 3.0k in 1.9. On super:

```
$ ../run/john --test=15 --format=zip
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 4x SSE2]... DONE
Raw:	3643 c/s real, 3643 c/s virtual
```
```
$ ../run/john-sse2-no-omp --test=15 --format=zip
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 128/128 SSE2 4x]... DONE
Raw:	8514 c/s real, 8514 c/s virtual
```
```
$ ../run/john-avx-no-omp --test=15 --format=zip
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 128/128 AVX 4x]... DONE
Raw:	10715 c/s real, 10715 c/s virtual
```

**Comment by claudioandre-br** [comment]
I have to enable 1_8 benchmark. And the correct value should be:

2/3 of the original value (SSE2 x SSE2).
```
$ ../run/john-sse2-no-omp --test=15 --format=zip
Benchmarking: ZIP, WinZip [PBKDF2-SHA1 128/128 SSE2 4x]... DONE
Raw:	2425 c/s real, 2423 c/s virtual
```

**Comment by solardiz** [comment]
I doubt 1.8.0-jumbo-1's reporting of SSE2 is for real - I think it's a misreporting bug, separate from the performance regression. We can't easily have SSE2 in an AVX-enabled build, which is what I was using, because the same intrinsics would actually compile into AVX code. So the claimed-SSE2-in-AVX-build to proper-AVX comparison was probably correct.

**Comment by solardiz** [comment]
I think we should re-test for this and other maybe-regressions using actual cracking runs, with the same "hashes" and same input wordlists (or faster alternatives for fast hashes) for both versions.

**Comment by solardiz** [comment]
I think I figured this out. This commit fixed a bug where only one hit would be found per SIMD block:

```
commit 01b6e1d130645c1959e79144b2cb44625ead0c1d
Author: jfoug <jfoug@openwall.net>
Date:   Thu Oct 20 20:04:53 2016 -0500

    zip: when there were multiple hits in the same SIMD block, later hits would not get properly found. #2281
```

When we're legacy-benchmarking using correct passwords, we may well be getting multiple hits per SIMD block, so the new code correctly runs slower.

The only maybe-surprise is then why the OpenMP code didn't become slower. But since we're looking at a combination of optimizations and bug fixes that may have performance impact like the above, this isn't necessarily wrong. So I'll close this issue.
