### ISSUE TITLE
SIP fails cracking qop=auth

### ISSUE THREAD

**Issue by nanosonde** [magnumripper/JohnTheRipper#3830]
Has a SIP format with qop=auth ever been tested? 
I do not see any test vectors in the code that's why I am asking.

I have the following SIP trace from a REGISTER sip:sip.provider.com SIP/2.0 message:
```
Authorization: Digest username="155350609596347633",realm="sip.provider.com",nonce="7dfb229f37d9834084f1aa5cdd1e2460",uri="sip:sip.provider.com",qop=auth,nc=00000147,cnonce="547401db",response="e1facc132ebe3973521a83950ff54994",algorithm=MD5
```

Username is: 155350609596347633
Password is: abc
Method: REGISTER
EntityBody: <empty>

I am **able** to crack the password using the tool "HTTPBrute" with the above parameters, but **not** using JtR.

![grafik](https://user-images.githubusercontent.com/2073569/56219660-6db53180-6067-11e9-89af-c6cbc13325b8.png)

**Comment by solardiz** [comment]
I don't know the answer, but I think it'd help if you post the exact input to JtR you were testing with. Thanks!

**Comment by nanosonde** [comment]
This is the file that sipdump created from manually entering the above details: 
```
1.2.3.4"5.6.7.8"155350609596347633"sip.provider.com"REGISTER"sip:sip.provider.com"7dfb229f37d9834084f1aa5cdd1e2460"547401db"00000147"auth"MD5"e1facc132ebe3973521a83950ff54994
```
Note: That the two IP addresses (client/server) 1.2.3.4 and 5.6.7.8 aare not used for calculations.
I guess they are just for documentation purposes.

Running the sipdump2john.py on this file generated this output for use with JtR:
```
1.2.3.4-5.6.7.8:$sip$*1.2.3.4*5.6.7.8*155350609596347633*sip.provider.com*REGISTER*sip*sip.provider.com**7dfb229f37d9834084f1aa5cdd1e2460*547401db*00000147*auth*MD5*e1facc132ebe3973521a83950ff54994
```
Running JtR with this file ("./john sip.login.john") does even find the password from the wordlist file where the password "abc" is also included.

**Comment by solardiz** [comment]
I think we have enough info here to proceed to look into this issue when one of us - perhaps @kholia - is available for that. Thanks!

**Comment by nanosonde** [comment]
Here is a patch for pass_gen.pl which add "sip_qop" to generate test vectors for this auth type.

```
diff --git a/run/pass_gen.pl b/run/pass_gen.pl
index 17b7b69..ff32542 100755
--- a/run/pass_gen.pl
+++ b/run/pass_gen.pl
@@ -68,7 +68,7 @@ my @funcs = (qw(DESCrypt BigCrypt BSDIcrypt md5crypt md5crypt_a BCRYPT BCRYPTx
                hmac-sha256 hmac-sha384 hmac-sha512 sha1crypt sha256crypt sha512crypt
                XSHA512 dynamic_27 dynamic_28 pwsafe django drupal7 epi zip
                episerver_sha1 episerver_sha256 hmailserver ike keepass
-               keychain nukedclan radmin raw-SHA sip SybaseASE
+               keychain nukedclan radmin raw-SHA sip sip_qop SybaseASE
                wbb3 wpapsk sunmd5 wowsrp django-scrypt aix-ssha1 aix-ssha256
                aix-ssha512 pbkdf2-hmac-sha512 pbkdf2-hmac-sha256 scrypt
                rakp osc formspring skey-md5 pbkdf2-hmac-sha1 odf odf-1 office_2007
@@ -1945,6 +1945,28 @@ sub sip {
        return "\$sip\$*$serverIP*$clientIP*$user*$realm*$method*$URIpart1*$clientIP**$nonce****MD5*$h";
 }

+sub sip_qop {
+       my $IPHead = "192.168." . (int(rand(253))+1) . ".";
+       my $serverIP = $IPHead . (int(rand(253))+1);
+       my $clientIP = $IPHead . (int(rand(253))+1);
+       my $user = randstr(5, \@chrAsciiNum);
+       my $realm = "asterisk";
+       my $method = "REGISTER";
+       my $URIpart1 = "sip";
+       my $nonce = randstr(32, \@chrHexLo);
+       my $uri = "$URIpart1:$clientIP";
+       my $qop = "auth";
+       my $nonce_count = "00000001";
+       my $cnonce = randstr(32, \@chrHexLo);
+
+       my $static_hash = md5_hex($method.":".$uri);
+       my $dynamic_hash_data = "$user:$realm:";
+       my $static_hash_data = ":$nonce:$nonce_count:$cnonce:$qop:$static_hash";
+       my $dyna_hash = md5_hex($dynamic_hash_data.$_[0]);
+       my $h = md5_hex($dyna_hash.$static_hash_data);
+       return "\$sip\$*$serverIP*$clientIP*$user*$realm*$method*$URIpart1*$clientIP**$nonce*$cnonce*$nonce_count*$qop*MD5*$h";
+}
+
 sub bitlocker {
        require Crypt::AuthEnc::CCM;
        my $itr = get_loops(1048576);
```

I have tested the tested the calculated values with HTTPbrute and it works.

Example output:
```
[user@machine run]$ ./pass_gen.pl -outformat vectors sip_qop

Enter words to hash, one per line.
abc
        {"$sip$*192.168.45.143*192.168.45.184*37498*asterisk*REGISTER*sip*192.168.45.184**ea1e1d84de885063fe5300048dc75c04*de1cedf12bedb4a86bb818342d80ad8f*00000001*auth*MD5*701b95a702bb9899742b6b3f9674e400", "abc"},
```

**Comment by solardiz** [comment]
Thanks, @nanosonde. Why don't you start contributing to our project more directly, with pull requests?

**Comment by nanosonde** [comment]
@solardiz No time to do that. ;-)

Please find thr attached fix which fixes this issue and adds a test vector with qop=auth.
The issue is related to the nonce_count parameter.
This parameter has a fixed length of 8 characters.
However, only 8 chars were allocated including the NULL char leaving only 7 chars for the nonce count.
So a nounce_count of "00000001" became "0000000". As a result the wrong hashes were calculated.

The problem arises from strncpy() operation which copies string lines[10] to string login.nonce_count. 

With this fix, the test vector works.

```
diff --git a/src/sip_fmt_plug.c b/src/sip_fmt_plug.c
index 5482c17..72900cc 100644
--- a/src/sip_fmt_plug.c
+++ b/src/sip_fmt_plug.c
@@ -69,6 +69,7 @@ static struct fmt_tests sip_tests[] = {
        {"$sip$*192.168.196.105*192.168.196.192*81670*asterisk*REGISTER*sip*192.168.196.192**747f072a****MD5*d15c84b1bdc2155db12b721d7fb9445b", "password"},
        {"$sip$*192.168.119.6*192.168.119.154*65790*asterisk*REGISTER*sip*192.168.119.154**8d4e1a4b****MD5*dcc0d8a4c105dbf3ecf5b281f4c57356", "happy123"},
        {"$sip$*192.168.113.63*192.168.113.78*59810*asterisk*REGISTER*sip*192.168.113.78**b778256e****MD5*cb13933a5986df471265231d08206509", "aobdataeteag"},
+        {"$sip$*192.168.44.162*192.168.44.11*12315*asterisk*REGISTER*sip*192.168.44.11**825f321ad9886ef434788ebfb8dbf150*b78b5a31*00000001*auth*MD5*23802bb930873797f0c7a1f0e595a94e", "abc"},
        {NULL}
 };

diff --git a/src/sip_fmt_plug.h b/src/sip_fmt_plug.h
index 5197b4f..c1ffb59 100644
--- a/src/sip_fmt_plug.h
+++ b/src/sip_fmt_plug.h
@@ -12,7 +12,7 @@
 #define URI_MAXLEN        256    /* Max len of uri            */
 #define NONCE_MAXLEN      128    /* Max len of nonce value    */
 #define CNONCE_MAXLEN     128    /* Max len for cnonce value  */
-#define NONCECOUNT_MAXLEN   8    /* Max len for nonce count   */
+#define NONCECOUNT_MAXLEN   9    /* Max len for nonce count   */
 #define QOP_MAXLEN         12    /* Max len for qop value     */
 #define LOGIN_MAXLEN     1024    /* Max len of login entry    */
 #define ALG_MAXLEN          8    /* Max len of algorithm name */
```

**Comment by solardiz** [comment]
@claudioandre-br You want to turn the above contribution into a PR as well? I took a look at the code, and there are a lot of things I dislike about it and would have written differently, but keeping the rest of the code as-is the proposed fix looks OK to me.

I checked that the buffer is pre-initialized to all-zeroes, so the string will be NUL terminated. And I checked that the code does assume there's NUL termination.

I also checked that those `strncpy` with `-1` are _not_ another victim of gcc 8 warnings. Per `git blame`, these date back to 2012. So nothing to revert there.

**Comment by solardiz** [comment]
@nanosonde If your patch and thus #3840 fully fixes this issue, then please close the issue now. Thank you!

**Comment by nanosonde** [comment]
yes, it is working now. Thx!

**Comment by ghost** [comment]
> How can I download the program

I'm afraid this is NOT a support forum. Please, ask for support using john-users mailing list.
