### ISSUE TITLE
SIPdump generates invalid dump files in manual entry mode

### ISSUE THREAD

**Issue by nanosonde** [magnumripper/JohnTheRipper#3835]
```
[user@machine run]$ ./SIPdump -m test
* Enter login information manually:

* Enter server IP  : 1.2.3.4
* Enter client IP  : 5.6.7.8
* Enter username   : username
* Enter realm      : realm
* Enter Method     : REGISTER
* Enter URI        : sip:realm
* Enter nonce      : deadbeef
* Enter qop        : auth
* Enter cnonce     : beefdead
* Enter nonce_count: 00000001
* Enter algorithm   : MD5
* Enter response   : beefbeef
```
generates

```
[user@machine run]$ cat test
1.2.3.4
"5.6.7.8
"username
"realm
"REGISTER
"sip:realm
"deadbeef
"beefdead
"00000001
"auth
"MD5
"beefbeef

[user@machine run]$
```
 which SHOULD be

```
1.2.3.4"5.6.7.8"username"realm"REGISTER"sip:realm"deadbeef"beefdead"00000001"auth"MD5"beefbeef
```
without any newline characters. Also at the end of the line there must not be any newline character.

sipdump2john.py is not able to consume this file and throws an error.
(NB: the own original companion tool sipcrack was also not able to read the dump files from its companion sipdump in manual mode because of this. :-/ )

**Comment by solardiz** [comment]
@nanosonde Thanks! Do you possibly want to fix this for us, and send us a pull request?

**Comment by nanosonde** [comment]
Here is a patch for this:

```
diff --git a/src/SIPdump.h b/src/SIPdump.h
index 2ae2071..e3ef879 100644
--- a/src/SIPdump.h
+++ b/src/SIPdump.h
@@ -174,8 +174,7 @@ void get_string_input(char *outbuf, size_t outbuf_len, const char *fmt, ...)
        } while (!fgets(outbuf, outbuf_len, stdin));

        /* Remove newline */
-       if (outbuf[strlen(outbuf) - 1] == 0x0d)
-               outbuf[strlen(outbuf) - 1] = 0x00;
+       outbuf[strcspn(outbuf, "\r\n")] = 0x00; // works for LF, CR, CRLF, LFCR, ...

        return;
 }
```

**Comment by solardiz** [comment]
Thanks, @nanosonde. This fix looks correct to me, whereas the original lines you're removing were problematic in multiple ways. We're already using the `strcspn` function in wordlist.c, so this is fine in portability terms as well. We'd appreciate this same patch in a pull request from you.

**Comment by solardiz** [comment]
Oh, @claudioandre-br was quicker to make that PR, #3836. Next time, then.

**Comment by nanosonde** [comment]
Thx! Working now!
