### ISSUE TITLE
ocl_hc_128_prepare_table uninitialized allocation

### ISSUE THREAD

**Issue by crioux** [magnumripper/JohnTheRipper#3849]
### Issue ###
ocl_hc_128_prepare_table has an uninitialized table, allocated on line 42: 

```hash_ids = (cl_uint*) mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));```

The fix is this:

```hash_ids = (cl_uint*) mem_calloc((3 * num_loaded_hashes + 1), sizeof(cl_uint));```

(notable this code is fixed in `ocl_hc_128_prepare_table_test`, but not in `ocl_hc_128_prepare_table`)

This uninitialized hash id table results in intermittent cracking failures for nt-opencl hashes.

### Steps to reproduce ###
Run any self test with nt-opencl format. Intermittent failures depending on compiler defaults and system allocation strategy result.

### System configuration ###
Windows 64 bit, JtR from L0phtCrack integration

**Comment by solardiz** [comment]
I think we might have more instances of this bug. Let's review.

```
$ grep 'hash_ids.*_alloc.*num_loaded_hashes' *.c
opencl_krb5pa-md5_fmt_plug.c:   hash_ids = (cl_uint*) mem_alloc((3 * max_num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_mscash_fmt_plug.c:       hash_ids = (cl_uint*) mem_alloc((3 * max_num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_mysqlsha1_fmt_plug.c:    hash_ids = (cl_uint*) mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_mysqlsha1_fmt_plug.c:            hash_ids = (cl_uint*)mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_ntlmv2_fmt_plug.c:       hash_ids = (cl_uint*) mem_alloc((3 * max_num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_rawsha1_fmt_plug.c:      hash_ids = (cl_uint*) mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_rawsha1_fmt_plug.c:              hash_ids = (cl_uint*)mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_salted_sha_fmt_plug.c:   hash_ids = (cl_uint*) mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_salted_sha_fmt_plug.c:           hash_ids = (cl_uint*)mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_sl3_fmt_plug.c:  hash_ids = mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
opencl_sl3_fmt_plug.c:          hash_ids = mem_alloc((3 * num_loaded_hashes + 1) * sizeof(cl_uint));
```

```
$ grep 'hash_ids.*_calloc.*num_loaded_hashes' *.c
opencl_hash_check_128_plug.c:   hash_ids = (cl_uint*) mem_calloc((3 * num_loaded_hashes + 1), sizeof(cl_uint));
opencl_hash_check_128_plug.c:   hash_ids = (cl_uint*) mem_calloc((3 * num_loaded_hashes + 1), sizeof(cl_uint));
opencl_lm_b_plug.c:     hash_ids     = (unsigned int *) mem_calloc (3 * num_loaded_hashes + 1, sizeof(unsigned int));
```

**Comment by solardiz** [comment]
Claudio, I'd appreciate your help with this review/fixes, if you're OK with that. Thank you!

**Comment by magnumripper** [comment]
Hopefully some or all of them have memsets but anyway good catch!

**Comment by solardiz** [comment]
> Hopefully some or all of them have memsets

I had tried `grep -A2` before I posted the list in here - none of them had `memset` within that context.

**Comment by solardiz** [comment]
After #3868, my grep doesn't see any of these anymore.
