### ISSUE TITLE
bcrypt-ztex misses passwords

### ISSUE THREAD

**Issue by AlekseyCherepanov** [magnumripper/JohnTheRipper#3851]
@Apingis It seems that current bcrypt-ztex format misses passwords.

I found it with a wordlist. I can reproduce it with synthetic passwords and mask mode.

I was not able to reproduce it on cost 5. So my hashes are cost 10.

I did not try to reproduce it with a few hashes per salt.

I used the following command to generate hashes.
```
$ python -c $'import passlib.hash\nfor i in range(20000): print passlib.hash.bcrypt.hash("{:05d}".format(i), salt = "CCCCCCCCCCCCCCCCCCCCC.", rounds = 10, ident = "2a")' > tbcrypt.pw
```

It is so slow, I tried on a part. The file is attached.
```
$ wc -l tbcrypt.pw
3961 tbcrypt.pw
```

So we are going to get 3961 cracks with '0?d?d?d?d' mask:
```
$ rm -f empty.pot; john tbcrypt.pw --mask='0?d?d?d?d' --pot=empty.pot
Loaded 3961 password hashes with no different salts (bcrypt-ztex [Blowfish ZTEX])
ZTEX [...] bus:4 dev:4 Frequency:150 150 150 150 
[...]
Warning: salt with 3961 hashes, onboard comparators support up to 512 hashes/salt, turned off
[...]
3958g 0:00:00:03 N/A 1252g/s 3164p/s 3164c/s 8506KC/s 07777..05374
```

3 missed. Ok, let's try to crack them with the same attack:
```
$ john tbcrypt.pw --mask='0?d?d?d?d' --pot=empty.pot
[...]
02505            (?)
00939            (?)
Warning: Only 2064 candidates left, minimum 3968 needed for performance.
02507            (?)
3g 0:00:00:03 N/A 0.9677g/s 3225p/s 3225c/s 8345C/s 02507..07777
```

Similar effect with a wordlist:
```
$ john --mask='0?d?d?d?d' --stdout > twl

$ rm -f empty.pot; john tbcrypt.pw --pot=empty.pot --wordlist=twl
[...]
3957g 0:00:00:03 DONE (2019-04-20 23:32) 1248g/s 3154p/s 3154c/s 8481KC/s 07777..05374

$ john tbcrypt.pw --wordlist=twl --pot=empty.pot
[...]
03481            (?)
01125            (?)
02878            (?)
Warning: Only 2064 candidates left, minimum 3968 needed for performance.
02137            (?)
4g 0:00:00:03 DONE (2019-04-20 23:33) 1.333g/s 3333p/s 3333c/s 9946C/s 02137..07777
```

That's with `TargetSetting = 10`.

```
$ john --list=build-info
Version: 1.9.0-jumbo-1-bleeding-4bf9652 2019-04-19 19:08:24 +0200
```
[tbcrypt.pw.txt](https://github.com/magnumripper/JohnTheRipper/files/3100575/tbcrypt.pw.txt)

**Comment by solardiz** [comment]
@AlekseyCherepanov Please re-test this at a lower frequency, like 141 that we had before. It might be that your board actually has a 0.1% error rate at 150 for bcrypt cost 10.

**Comment by solardiz** [comment]
> I was not able to reproduce it on cost 5. So my hashes are cost 10.

One bcrypt hash computation at cost 5 is 32x less processing than for cost 10, which also means a correspondingly(?) lower error rate per hash computed.

**Comment by AlekseyCherepanov** [comment]
I tried different frequencies:
- 141-148 work well,
- 149-154 miss passwords,
- 155 gives timeouts and errors.

I thought -ztex formats should not miss passwords on errors. OTOH in #3848 I saw that timeouts do not happen when results are transferred (but these timeout were not caused by errors). Could john miss passwords without transfer mode?

**Comment by solardiz** [comment]
Thanks, Aleksey. Maybe we were too quick to decide on 150 as the new default, or maybe not. Maybe we should lower the frequency e.g. to 145, or maybe not. The current behavior of bcrypt-ztex might very well be consistent with (or even better than) behavior we currently have for other hash types at our current defaults - we just haven't run directly comparable tests (e.g., try the same number of sha512crypt hashes tuned to the same c/s and expecting same number of successful guesses in the same amount of real time).

Of course, when the hardware isn't working 100% reliably, there can be a variety of errors, including occasional incorrect computation of hashes. We could try to make bcrypt-ztex the 100% reliable exception (since for this one the design tools' reported frequency of 141 actually works, unlike for all others where we have to choose a frequency empirically), but do we want to?

**Comment by AlekseyCherepanov** [comment]
> Could john miss passwords without transfer mode?

Yes, it can.

**Comment by solardiz** [comment]
Aleksey, oh, I didn't realize you still needed this question answered. Of course, the answer is yes, as you already figured out.

**Comment by solardiz** [comment]
"Transfer mode" makes it easier for us to detect miscalculated hashes and figure out what the error rate is, because we're able to test each and every hash computation by having a matching expected hash on the host.

**Comment by claudioandre-br** [comment]
> Maybe we should lower the frequency e.g. to 145

Release using a safe frequency. Revert to an experimental value after that.

**Comment by solardiz** [comment]
Thanks, Claudio! The thing is we _have_ to experiment for all *-ztex formats but this one. So my choice to also use a higher frequency here, based on testing, is for consistency. We'd be sort of artificially slowing down this one if we kept it at the design tools' "guaranteed" frequency of 141.

FWIW, here's my testing with Aleksey's file, `TargetSetting = 10`, four boards, 150 MHz:

```
$ for n in `seq 1 20`; do rm john.pot; ./john -form=bcrypt-ztex --mask='0?d?d?d?d' -verb=1 tbcrypt.pw.txt 2>&1 | fgrep g/s; done
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:01  3883g/s 9803p/s 9803c/s 38833KC/s 07777..01111
3961g 0:00:00:01  3961g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3961g 0:00:00:01  3961g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:01  3961g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3961g 0:00:00:00  4001g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:01  3883g/s 9803p/s 9803c/s 38833KC/s 07777..01111
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:00  4001g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3961g 0:00:00:01  3961g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3961g 0:00:00:01  3883g/s 9803p/s 9803c/s 38833KC/s 07777..01111
3961g 0:00:00:01  3961g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3961g 0:00:00:00  4001g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3961g 0:00:00:01  3921g/s 9900p/s 9900c/s 39217KC/s 07777..01111
3961g 0:00:00:01  3961g/s 10000p/s 10000c/s 39610KC/s 07777..01111
```

Ditto, 152 MHz:

```
3960g 0:00:00:01  3960g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3960g 0:00:00:00  4000g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3961g 0:00:00:01  3961g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3960g 0:00:00:00  4040g/s 10204p/s 10204c/s 40418KC/s 07777..01111
3959g 0:00:00:01  3959g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3960g 0:00:00:01  3960g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3960g 0:00:00:00  4000g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3960g 0:00:00:00  4000g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3960g 0:00:00:00  4000g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3959g 0:00:00:00  3998g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3957g 0:00:00:00  3996g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3959g 0:00:00:00  3998g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3957g 0:00:00:01  3957g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3961g 0:00:00:00  4001g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3958g 0:00:00:00  3997g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3959g 0:00:00:01  3959g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3959g 0:00:00:00  3998g/s 10101p/s 10101c/s 40010KC/s 07777..01111
3959g 0:00:00:01  3959g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3959g 0:00:00:01  3959g/s 10000p/s 10000c/s 39610KC/s 07777..01111
3957g 0:00:00:01  3917g/s 9900p/s 9900c/s 39217KC/s 07777..01111
```

So we got quite close to the maximum stable frequency here with 150.

**Comment by solardiz** [comment]
I think we'll just stay with the 150 MHz default for now, possibly revisiting this along with a design update (maybe a few more cores).
