### ISSUE TITLE
GELI md_aalgo 256

### ISSUE THREAD

**Issue by trounce1** [magnumripper/JohnTheRipper#3863]
when i run geli hash with md_aalgo of 256, it does not want to run.

is this because 256 is not implemented and only 128 will work?

thanks

**Comment by trounce1** [comment]
when modifying src/geli_common_plug.c to allow md_aalgo of 128 or 256. my password cracked successfully. can this be modified and pushed?

**Comment by claudioandre-br** [comment]
> when modifying src/geli_common_plug.c to allow md_aalgo of 128 or 256. my password cracked successfully. can this be modified and pushed?

Please, do it! Thanks

**Comment by trounce1** [comment]
https://github.com/magnumripper/JohnTheRipper/pull/3864

**Comment by solardiz** [comment]
Fixed with #3864, thanks!
