### ISSUE TITLE
Repurpose aix-smd5 format

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3872]
Dhiru created the aix-smd5 format in 2013 to support AIX's variation of md5crypt. We've since added support for those hashes to our main md5crypt and md5crypt-opencl and even md5crypt-ztex formats.

Presently, the only value the aix-smd5 format provides is it supporting passwords of arbitrary length (up to JtR's global limit), whereas our other md5crypt formats are length-limited (to 15, except md5crypt-ztex which allows up to 64, but requires the rare hardware).

We might want to rename and repurpose the aix-smd5 format as e.g. md5crypt-long.

**Comment by magnumripper** [comment]
Agreed. On the other hand I'd like to see support for >15 (obviously only when needed) in the optimized md5crypt format as well, but I haven't groked all optimizations.

**Comment by solardiz** [comment]
Right. For the upcoming release renaming this format is within scope and would reduce further confusion and simplify further `relbench`, while making invasive changes to our optimized format is not.

**Comment by solardiz** [comment]
Along with the rename, it's probably also easy enough to enhance this format to:

1. Support apr1 hashes.
2. Avoid modulo division - have counter(s) increase up to the divisor(s), then reset to 0.

**Comment by solardiz** [comment]
Can we rename this format's source file such that it's benchmarked right after our main md5crypt format? Or would that perhaps require a john.c edit, since the main md5crypt format comes from core and isn't a plugin format? Either way, I think ideally we'd have it benchmarked right at that time, so that users learn of its existence and of its relative speed (~7x slower on AVX build).

**Comment by solardiz** [comment]
We could also have this format count how many of the tested passwords, say, in the first 1 million (then disable the counting) are up to 15 chars vs. 16+, and report those statistics at the 1 million mark if the percentage of the up to 15 chars passwords is significant (say, 1% or above), suggesting use of the main md5crypt format on those shorter candidate passwords.

**Comment by magnumripper** [comment]
Instead of spending time on such bodges, how long would it take you to add support for longer passwords to the SIMD format? And what length would "next" optimization be, 30?

**Comment by solardiz** [comment]
> how long would it take you to add support for longer passwords to the SIMD format?

I guess it's like 2 hours to complete repurposing this format vs. 40 hours to (semi-)properly rework and enhance the SIMD format. Also relevant is how much _slower_ the SIMD format would become for passwords that are up to 15 - how much slower we can tolerate in order to minimize our development effort. Maybe 1%? To get the SIMD format to work with longer passwords _somehow_, like we would under time pressure (e.g., if we needed to for a contest), could possibly be done in e.g. 8 hours - but that's no good for release, I think.

> And what length would "next" optimization be, 30?

I guess more like 47 (as 15+64/2).

What we could do in maybe 8 hours of effort and in a release-suitable form is enhance the main md5crypt format to fallback to scalar code for passwords longer than 15, perhaps buffering them separately, perhaps with a larger max_keys_per_crypt to have decent SIMD buffer fill rate. This would have better usability than two separate formats.

**Comment by solardiz** [comment]
The SIMD format could possibly be sped up by switching from scalar to SIMD code for the unaligned buffer writes. We're effectively already doing that in OpenCL, it's just implicit due to the SIMT model. We can try that on CPU as well, with explicit SIMD that time. So it feels wrong to "simply" add complexity to support longer passwords on top of what we have without giving this change a try first. Greater complexity would make trying out such changes harder.

**Comment by magnumripper** [comment]
PR made. I did rename and unplug the format (placing it right after md5crypt) but I did not consider https://github.com/magnumripper/JohnTheRipper/issues/3872#issuecomment-490512683. I think that's too much work in the wrong direction.
