### ISSUE TITLE
Inconsistent messages from -test -mask

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3875]
Using `-test -mask`
```
Note: Self-tests currently not performed when using -mask with -test

(...)

All 55 formats passed self-tests!
```

**Comment by magnumripper** [comment]
I think I'll change it to `55 formats benchmarked!` for this case.

**Comment by solardiz** [comment]
@magnumripper Your fix here broke "make -f Makefile.legacy generic" - you refer to `options` outside of a `#ifndef BENCH_BUILD`. Please fix that.

(I wanted to check if my later changes to bench.c are OK with respect to "make generic", but this issue got in the way.)

**Comment by magnumripper** [comment]
Done, tested and merged
