### ISSUE TITLE
SL3-opencl intermittent self-test failure

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3880]
Seen on super, both AMD and nvidia. Also seen on macOS, all devices. So this is not a driver/runtime issue. I've never seen it before. Tried reverting to before 2478f4c127d (just in case) but that wasn't it.

```
$ ../run/john -form:sl3-opencl all_tests.in -mask:012345678912345
Device 3: AMD Radeon Pro 560 Compute Engine
No dupe-checking performed when loading hashes.
Using default input encoding: UTF-8
Loaded 2 password hashes with 2 different salts (SL3-opencl, Nokia operator unlock [SHA1 OpenCL])
Self test failed (The length of string returned by get_key() is 0 but should be between plaintext_min_length=15 and plaintext_length=15)
```

**Comment by magnumripper** [comment]
Happens in real runs as well as benchmark

**Comment by magnumripper** [comment]
Does not seem to happen with `-test=0` or `--test-full=0`

**Comment by magnumripper** [comment]
Doesn't happen with `-test -mask` but that's just because we're currently skipping self-test then.

**Comment by magnumripper** [comment]
Sometimes it just works
```
$ ../run/john -form:sl3-opencl --test=-1
Device 3: AMD Radeon Pro 560 Compute Engine
Benchmarking: SL3-opencl, Nokia operator unlock [SHA1 OpenCL]... FAILED (The length of string returned by get_key() is 0 but should be between plaintext_min_length=15 and plaintext_length=15)

$ ../run/john -form:sl3-opencl --test   
Device 3: AMD Radeon Pro 560 Compute Engine
Benchmarking: SL3-opencl, Nokia operator unlock [SHA1 OpenCL]... DONE
Warning: "Many salts" test limited: 43/256
Note: This format may also be benchmarked using --mask (see doc/MASK).
Many salts:	357138K c/s real, 9017M c/s virtual
Only one salt:	57009K c/s real, 115137K c/s virtual

$ ../run/john -form:sl3-opencl --test
Device 3: AMD Radeon Pro 560 Compute Engine
Benchmarking: SL3-opencl, Nokia operator unlock [SHA1 OpenCL]... DONE
Warning: "Many salts" test limited: 43/256
Note: This format may also be benchmarked using --mask (see doc/MASK).
Many salts:	357138K c/s real, 7214M c/s virtual
Only one salt:	57568K c/s real, 112923K c/s virtual

$ ../run/john -form:sl3-opencl --test=-1
Device 3: AMD Radeon Pro 560 Compute Engine
Benchmarking: SL3-opencl, Nokia operator unlock [SHA1 OpenCL]... DONE
Note: This format may also be benchmarked using --mask (see doc/MASK).
Many salts:	365218K c/s real, 7158M c/s virtual
Only one salt:	57358K c/s real, 110014K c/s virtual

$ ../run/john -form:sl3-opencl --test   
Device 3: AMD Radeon Pro 560 Compute Engine
Benchmarking: SL3-opencl, Nokia operator unlock [SHA1 OpenCL]... FAILED (The length of string returned by get_key() is 0 but should be between plaintext_min_length=15 and plaintext_length=15)
```

**Comment by magnumripper** [comment]
The format is nearly identical with salted-sha1-opencl and uses same kernel (with `-DSL3` passed when building). I really can't see any differences that should pop up here. Perhaps salted-sha1-opencl might fail intermittently too, but I haven't seen it do so yet.

**Comment by magnumripper** [comment]
Forcing LWS=32 seems to "cure" it

**Comment by magnumripper** [comment]
I'm stumped. I need to think about this for a while. @claudioandre-br any ideas? Something seems to not get properly initialized at all times, but when and why?

**Comment by solardiz** [comment]
> Perhaps salted-sha1-opencl might fail intermittently too, but I haven't seen it do so yet.

Perhaps salted-sha1-opencl doesn't have a minimum plaintext length, so the self-test wouldn't detect that failure? OTOH, perhaps it should detect `get_key` not returning the exact right key? This brings me to a guess: maybe the failures for SL3 are for keys that were never correctly set by the host, and shouldn't actually be expected to be of a valid length when read back? Or perhaps all keys should be set by the host to be of valid lengths?

**Comment by claudioandre-br** [comment]
* SL3-OpenCL is a disabled format to me. So, it is not new it fails.
* To me it seems it is not cleaning the buffers it should (when needed).
  * E.g.: it is doing `memset(saved_idx, 0, sizeof(cl_uint) * global_work_size);`
  * but only in `clear_keys()`

As an example, when tuning, JtR will try 1k, 2k, 4k, etc. without cleaning. Off the top of my head, this is bad.

**Comment by magnumripper** [comment]
> This brings me to a guess: maybe the failures for SL3 are for keys that were never correctly set by the host, and shouldn't actually be expected to be of a valid length when read back?

I verified that we're setting a correct length-15 key right before this happens. I noticed the self-tests sometimes might set zero-length keys (I'll change that at some point later) but that particular part of self-tests doesn't try to read it back.

> As an example, when tuning, JtR will try 1k, 2k, 4k, etc. without cleaning

I fixed all such bugs (of Sayanyan's origin) months ago.

Anyway, I was just tired. This is trivial, I'll just debug it closely. I need some more break first, with a soldering iron and a beer.

**Comment by magnumripper** [comment]
BTW my bet is on 8b15b23a8. But instead of reverting that, I just need to ensure format can handle whatever situation is triggering the faults.

**Comment by magnumripper** [comment]
Yup, that seems to be it. Just a key cleaning issue, I'll nail it and fix it in a few hours.

**Comment by magnumripper** [comment]
Note to self: Whatever fix I come up with is *likely* needed in salted-sha1 as well, and perhaps some/all other of Sayantan's internal mask formats (or based on such).
