### ISSUE TITLE
dmg2john Warning from CircleCI Wine64

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3902]
I've never seen this before.
```
dmg2john.c: In function 'hash_plugin_parse_hash':
dmg2john.c:252:17: warning: overflow in conversion from 'long long unsigned int' to 'long int' changes value from '18446744073709550340' to '-1276' [-Woverflow]
   if (lseek(fd, -sizeof(cencrypted_v1_header), SEEK_END) < 0) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by magnumripper** [comment]
Win64 has 32-bit longs, doesn't it?

**Comment by claudioandre-br** [comment]
Once upon a time, I tried to narrow this. My conclusion was the message is a false positive. 
* there is no ultra-giga-mega-big value involved.
* the `sizeof()` will be, e.g., 1k.

**Comment by magnumripper** [comment]
> there is no ultra-giga-mega-big value involved.

Well, we have a negative converted to unsigned, and different types. That's ultra-giga-mega-big at some point. We should get away with some casting.

**Comment by magnumripper** [comment]
Note that it's not just `sizeof(...)` but `-sizeof(...)` or for clarity `0 - sizeof(...)`

**Comment by magnumripper** [comment]
Perhaps something like this
```diff
- if (lseek(fd, -sizeof(cencrypted_v1_header), SEEK_END) < 0) {
+ if (lseek(fd, (off_t)(0 - (int)sizeof(cencrypted_v1_header)), SEEK_END) < 0) {
```

**Comment by magnumripper** [comment]
I'll try a commit and see what the bot says

**Comment by claudioandre-br** [comment]
Well, I did `printf(sizeof(cencrypted_v1_header))`. It is alow value as, for example, 1233. Anyway, your fix is good.

**Comment by magnumripper** [comment]
A more interesting thing would be printing `sizeof(size_t)` and `sizeof(off_t)`. Are they different *sizes* on Win64?!

**Comment by claudioandre-br** [comment]
The Wine build is reproducible, So, you can try it locally, in you machine, using Docker.

**Comment by magnumripper** [comment]
I won't go that near Windows. Looking at the bots disgusting CRLF output is about as much I can stand.

**Comment by claudioandre-br** [comment]
My final observation: it is the only compiler complaining is this one. I use, maybe, 15 compilers.

**Comment by claudioandre-br** [comment]
> I won't go that near Windows. 

This is Fedora + Wine + Mingw. Condoms in place.

**Comment by magnumripper** [comment]
It's not about the compiler it's about LLP64 vs. LP64. Windows is the former and most everything else is the latter.

**Comment by claudioandre-br** [comment]
The real Windows build do not complain about dmg2john (32 and 64 bits).
