### ISSUE TITLE
error: 'CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE' undeclared (first use in this function)

### ISSUE THREAD

**Issue by trounce1** [magnumripper/JohnTheRipper#3915]
Hi Guys,

Any ideas of this error.

Ive been trying for an hour to fix this.

Cheers

make find_version
make[1]: Entering directory '/home/test/newjohn/JohnTheRipper/src'
echo "#define JTR_GIT_VERSION JUMBO_VERSION "\"-c771966\" \" 2019-05-10 00:59:38 +0200\""" > version.h.new
diff >/dev/null 2>/dev/null version.h.new version.h && rm -f version.h.new || mv -f version.h.new version.h
make[1]: Leaving directory '/home/test/newjohn/JohnTheRipper/src'
make[1]: Entering directory '/home/test/newjohn/JohnTheRipper/src'
echo "#define JTR_GIT_VERSION JUMBO_VERSION "\"-c771966\" \" 2019-05-10 00:59:38 +0200\""" > version.h.new
diff >/dev/null 2>/dev/null version.h.new version.h && rm -f version.h.new || mv -f version.h.new version.h
gcc -DAC_BUILT -mavx2 -DJOHN_AVX2 -c -m64 -g -O2 -I/usr/local/include -DARCH_LITTLE_ENDIAN=1  -Wall -fno-omit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations -Wformat-extra-args -Wunused-but-set-variable -std=gnu89 -Wdate-time -D_POSIX_SOURCE -D_GNU_SOURCE -D_XOPEN_SOURCE=600  -fopenmp  -pthread   -I/usr/local/include -DCL_SILENCE_DEPRECATION -DHAVE_OPENCL -pthread -funroll-loops opencl_common.c -o opencl_common.o
In file included from opencl_common.c:50:0:
opencl_common.c: In function 'get_kernel_preferred_multiple':
opencl_common.c:2536:3: error: 'CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE' undeclared (first use in this function)
   CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE,
   ^
opencl_common.h:260:23: note: in definition of macro 'HANDLE_CLERROR'
  do { cl_int __err = (cl_error); \
                       ^
opencl_common.c:2536:3: note: each undeclared identifier is reported only once for each function it appears in
   CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE,
   ^
opencl_common.h:260:23: note: in definition of macro 'HANDLE_CLERROR'
  do { cl_int __err = (cl_error); \
                       ^
opencl_common.c: In function 'get_processors_count':
opencl_common.c:2623:34: error: 'CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG' undeclared (first use in this function)
                                  CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG,
                                  ^
opencl_common.h:260:23: note: in definition of macro 'HANDLE_CLERROR'
  do { cl_int __err = (cl_error); \
                       ^
opencl_common.c: In function 'opencl_list_devices':
opencl_common.c:3031:20: error: 'CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR' undeclared (first use in this function)
                    CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR,
                    ^
opencl_common.c:3035:20: error: 'CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT' undeclared (first use in this function)
                    CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT,
                    ^
opencl_common.c:3039:20: error: 'CL_DEVICE_NATIVE_VECTOR_WIDTH_INT' undeclared (first use in this function)
                    CL_DEVICE_NATIVE_VECTOR_WIDTH_INT,
                    ^
opencl_common.c:3043:20: error: 'CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG' undeclared (first use in this function)
                    CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG,
                    ^
Makefile:1866: recipe for target 'opencl_common.o' failed
make[1]: *** [opencl_common.o] Error 1
make[1]: Leaving directory '/home/test/newjohn/JohnTheRipper/src'
Makefile:189: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by solardiz** [comment]
We need info on your setup. Also, were you able to build (older) jumbo on this system before or is it the first time you're building jumbo on it? Thanks.

Can you try dropping `#define CL_TARGET_OPENCL_VERSION 120` from our opencl_common.h?

**Comment by trounce1** [comment]
same error when dropping this line. what command shall i run to give you my setup info?

**Comment by trounce1** [comment]
i have never been able to build jumbo on this machine. i could build standard john

**Comment by solardiz** [comment]
We don't have one universal command to query the system (maybe we should come up with a lengthy one for future occasions). We primarily need to know where your OpenCL headers come from, and what version. So: what OS/distro/version is that, and what package, etc. does /usr/include/CL/cl.h (or the like, if you use a different include path) come from?

**Comment by trounce1** [comment]
/usr/include/CL/cl.h exists. 

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

linux 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

OpenCL 1.2 CUDA 9.0.368

**Comment by solardiz** [comment]
> /usr/include/CL/cl.h exists.

Sure, but can you show where it came from? Please try `dpkg -S /usr/include/CL/cl.h`. This will tell us what package dpkg thinks the file came from, but unfortunately it's also possible some non-package overwrote the file since. So please also show us e.g. `head -10 /usr/include/CL/cl.h`.

**Comment by trounce1** [comment]
opencl-headers: /usr/include/CL/cl.h

i did head -50

/*******************************************************************************
 * Copyright (c) 2008 - 2013 The Khronos Group Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and/or associated documentation files (the
 * "Materials"), to deal in the Materials without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Materials, and to
 * permit persons to whom the Materials are furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Materials.
 *
 * THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.
 ******************************************************************************/

#ifndef __OPENCL_CL_H
#define __OPENCL_CL_H

#ifdef __APPLE__
#include <OpenCL/cl_platform.h>
#else
#include <CL/cl_platform.h>
#endif	

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/

typedef struct _cl_platform_id *    cl_platform_id;
typedef struct _cl_device_id *      cl_device_id;
typedef struct _cl_context *        cl_context;
typedef struct _cl_command_queue *  cl_command_queue;
typedef struct _cl_mem *            cl_mem;
typedef struct _cl_program *        cl_program;
typedef struct _cl_kernel *         cl_kernel;
typedef struct _cl_event *          cl_event;
typedef struct _cl_sampler *        cl_sampler;

typedef cl_uint             cl_bool;                     /* WARNING!  Unlike cl_ types in cl_platform.h, cl_bool is not guaranteed to be the same size as the bool in kernels. */ 
typedef cl_ulong            cl_bitfield;

**Comment by trounce1** [comment]
also to note. hashcat builds fine

**Comment by solardiz** [comment]
And what did `dpkg -S /usr/include/CL/cl.h` say?

@magnumripper Can you look into this, please? If hashcat builds fine, then maybe this is something we can fix or workaround.

**Comment by trounce1** [comment]
user@machine:/usr/local/include$ dpkg -S /usr/include/CL/cl.h
opencl-headers: /usr/include/CL/cl.h

**Comment by magnumripper** [comment]
Not sure why it's not working for you but Ubuntu 16.04 is very well tested (perhaps most of all distros and versions) and shouldn't give any problems at all. Please have a look at doc/INSTALL-UBUNTU and see if something's missing.

**Comment by trounce1** [comment]
ok so i have just followed the instructions perfectly and the same error occurs.

**Comment by claudioandre-br** [comment]
I would say this is a better command to see what is happening:
`cat /usr/include/CL/cl.h | grep -B3 -A4 CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE`

1. this is OpenCL 1.1 (not 1.0);
2. you probably have old headers installed somewhere;
3. you have to find them all and remove old software;
3.1 this is 100% your environment, not JtR itself;
4. 16.04 is well tested;
5. other tools (probably) are not using **CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE**;
6. so, they don't fail.

Or `opencl_headers` from 16.04 are 1.0 and you have to use NVIDIA headers. I don't know.

**Comment by trounce1** [comment]
#define CL_KERNEL_WORK_GROUP_SIZE                   0x11B0
#define CL_KERNEL_COMPILE_WORK_GROUP_SIZE           0x11B1
#define CL_KERNEL_LOCAL_MEM_SIZE                    0x11B2
#define CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE 0x11B3
#define CL_KERNEL_PRIVATE_MEM_SIZE                  0x11B4
#define CL_KERNEL_GLOBAL_WORK_SIZE                  0x11B5
    
/* cl_kernel_exec_info */

**Comment by trounce1** [comment]
i updated headers and it worked.

**Comment by trounce1** [comment]
if its possible to add to the source to check that the header version is correct @solardiz ???

that would be helpful with other that experience the issue where there rigs are airgapped and not updated for a while

**Comment by solardiz** [comment]
@trounce1 How exactly did you update the headers?

@claudioandre-br @magnumripper Maybe @trounce1's suggestion is reasonable - have an `#ifndef CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE` and our own `#error` suggesting to update the OpenCL headers? Would be less confusing than many other compile warnings and errors.

FWIW, I am able to build current jumbo with OpenCL fine on Ubuntu 12.04 (yes, that old) with NVIDIA & AMD drivers from the era. So it isn't like we're requiring anything very recent. But maybe Ubuntu 16.04's opencl-headers were at some point out of date, even for its release date?

**Comment by claudioandre-br** [comment]
> @claudioandre-br @magnumripper Maybe @trounce1's suggestion is reasonable - have an #ifndef CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE 

I would say:
* if it is not OpenCL 1.2, bail with error. 

Anyway, this is a call to magnum (which is stopping his Bruce Wayne life because of JtR).

I mean, we have to focus. We have five hundred formats; plus:
* a lot of drivers manufactures. [1]
* `-enable-OMP-for-fast-formats`
* SIMD and non-SIMD
* fork, openMPI, ...
* 32 and 64 bits
* Windows

E.g.: focus on NVIDIA and AMD; require SIMD on x86, drop 32bits, ... Thinking out loud, we don't need to remove all possibilities.

[1]
E.g., the message we received today about Beignet (Beignet is dead, for a year or two).

**Comment by claudioandre-br** [comment]
Me thinks, for OpenCL:
- AMD and NVIDIA. Intel if anyone convinces me it works;
- OpenCL 1.2 is required;
- Ignore POCL, Beignet, ... (I'll keep using POCL for testing, so, it is not a curse)
- Ignore OpenCL on CPU;

It will be possible to someone to use OpenCL 1.0.
Or to run some formats using a 100% free driver.
We are only saying we support and recommend `this` and `that`.

**Comment by trounce1** [comment]
@solardiz i updated files in /usr/include/CL with https://github.com/KhronosGroup/OpenCL-Headers

**Comment by magnumripper** [comment]
We can "ignore" POCL and others in terms of not considering problems with them as blockers, but I'll always keep trying to "support" anything OpenCL >= 1.2 where "support" means best-effort and never anything else.

**Comment by magnumripper** [comment]
Opened #3918  for checking header and lib versions

**Comment by magnumripper** [comment]
> Anyway, this is a call to magnum (which is stopping his Bruce Wayne life because of JtR).
> 
> I mean, we have to focus. We have five hundred formats; plus:

Am I having a Bruce Wayne life?! Sounds cool 😎 Thing is, I'm not so sure we *have* to focus. We can put our *best effort* (my very favourite words) into supporting just **anything** including Eastern Europe three-phase coffee machines running some pirated version of iRMX-86 as long as it has support for OpenCL 1.2, but that doesn't mean we sign up to support it with early response (or any response at all) in case of problems.

**Comment by solardiz** [comment]
> i updated files in /usr/include/CL with https://github.com/KhronosGroup/OpenCL-Headers

I wonder what would have happened if you installed Ubuntu updates. Do they possibly have an appropriate update for their opencl-headers package for 16.04? I think 16.04 is still recent enough that our users will be running into this issue, and we need to know what to tell them.

**Comment by solardiz** [comment]
> hashcat builds fine

As I understand, hashcat bundles the Khronos Group headers under `deps/OpenCL-Headers` in its tree. Maybe we should consider doing the same.

**Comment by magnumripper** [comment]
Like we said, 16.04 is very well tested, I've never seen anything like this. No special moves needed at all: Install Linux from a stick, follow INSTALL-UBUNTU and you're set.

But yes, I've also considered including the headers.

**Comment by magnumripper** [comment]
We've been including headers (or needed parts of them) for AMD and nvidia fan/temp control for a long time.
