### ISSUE TITLE
Raw-MD4 fails test in a forced-OpenMP build on big-endian

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3916]
On Linux/sparc64, in a `./configure --enable-openmp-for-fast-formats` build:

```
solar@gcc202:~/JohnTheRipper/src$ time ../run/john -test -form=raw-md4
Will run 64 OpenMP threads
Benchmarking: Raw-MD4 [MD4 32/64]... (64xOMP) FAILED (cmp_one(2))


real    0m13.173s
user    0m0.000s
sys     0m0.000s

solar@gcc202:~/JohnTheRipper/src$ OMP_NUM_THREADS=1 ../run/john -test -form=raw-md4
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: Raw-MD4 [MD4 32/64]... FAILED (cmp_one(2))
```

All other formats passed test with `OMP_NUM_THREADS=13 time ../run/john -test-full=1`. Also, all formats passed test in a default build (no options to `configure`).

**Comment by solardiz** [comment]
It's puzzling that the error comes from `cmp_one` rather than `cmp_all`, whereas these have essentially the same trivial `memcmp` for the non-SIMD case that we have here.

**Comment by solardiz** [comment]
OK, this was obvious:
```diff
+++ b/src/rawMD4_fmt_plug.c
@@ -306,7 +306,7 @@ static int cmp_one(void *binary, int index)
 
        return ((uint32_t*)binary)[1] == ((uint32_t*)crypt_key)[x+y*SIMD_COEF_32*4+SIMD_COEF_32];
 #else
-       return !memcmp(binary, crypt_key, BINARY_SIZE);
+       return !memcmp(binary, crypt_key[index], BINARY_SIZE);
 #endif
 }
 
```
but then:
```
solar@gcc202:~/JohnTheRipper/src$ OMP_NUM_THREADS=1 ../run/john -test -form=raw-md4
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: Raw-MD4 [MD4 32/64]... FAILED (get_hash[0](1) 1d!=fa)
```

It looks like we never tested this format for non-SIMD OpenMP. Not even on x86. We don't have such tests in CI? :-(

**Comment by claudioandre-br** [comment]
>
> solar@gcc202:~/JohnTheRipper/src$ OMP_NUM_THREADS=1 ../run/john -test
> -form=raw-md4
>
> Warning: OpenMP is disabled; a non-OpenMP build may be faster
> Benchmarking: Raw-MD4 [MD4 32/64]... FAILED (get_hash[0](1) 1d!=fa)
>
> It looks like we never tested this format for non-SIMD OpenMP. Not even on
> x86. We don't have such tests in CI? :-(
>
> I run a non-SIMD OpenMP test.
``
Testing: Raw-Keccak-256 [Keccak 256 32/64]... (2xOMP) PASS
Testing: Raw-MD4 [MD4 32/64]... PASS
```

But, I'm in release mode for a while (no more tests since I have to switch
"modes").

>

**Comment by solardiz** [comment]
> Testing: Raw-MD4 [MD4 32/64]... PASS

That's non-OMP, indicating `--enable-openmp-for-fast-formats` was not passed along with `--disable-simd`. It's this combination, as well as `--enable-openmp-for-fast-formats` on platforms where we lack SIMD support, that is problematic.

**Comment by solardiz** [comment]
For fixing raw-MD4, I think we should bring its source file in sync with raw-MD5's, reintroducing only intentional differences. I won't work on that right now. Any takers?

**Comment by claudioandre-br** [comment]
You said `non-SIMD OpenMP` only. No extra `--enable`. But, In fact, I don't test every possibility of `--enable-openmp-for-fast-formats`

**Comment by claudioandre-br** [comment]
Well, since you will have to move to something newer than Subversion + Wikis, you may consider moving (hosting yourself, if you want) to GitLab. 
* If you have one GitLab CI runner, you can have a matrix with one hundred items testing all JtR possibilities;
* running once a week (for example).

**Comment by magnumripper** [comment]
> OK, this was obvious:
> 
> ```diff
> +++ b/src/rawMD4_fmt_plug.c
> @@ -306,7 +306,7 @@ static int cmp_one(void *binary, int index)
>  
>         return ((uint32_t*)binary)[1] == ((uint32_t*)crypt_key)[x+y*SIMD_COEF_32*4+SIMD_COEF_32];
>  #else
> -       return !memcmp(binary, crypt_key, BINARY_SIZE);
> +       return !memcmp(binary, crypt_key[index], BINARY_SIZE);
>  #endif
>  }
>  
> ```
> 
> but then:
> 
> ```
> solar@gcc202:~/JohnTheRipper/src$ OMP_NUM_THREADS=1 ../run/john -test -form=raw-md4
> Warning: OpenMP is disabled; a non-OpenMP build may be faster
> Benchmarking: Raw-MD4 [MD4 32/64]... FAILED (get_hash[0](1) 1d!=fa)
> ```
> 
> It looks like we never tested this format for non-SIMD OpenMP. Not even on x86. We don't have such tests in CI? :-(

Oh yes, we did. I'd say it looks like we didn't re-test the format for OpenMP after some later changes. We should add such test to CI also.

**Comment by magnumripper** [comment]
I'll have a look at this right now

**Comment by solardiz** [comment]
What was previously failing on the sparc64 for me is now passing tests, after magnum's fix here. Thanks!
