### ISSUE TITLE
times() vs. clock() discrepancies

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3924]
JtR core uses times(2). JtR jumbo will sometimes use clock(3) instead, for systems where times(2) is presumably unavailable. However, JtR jumbo "forgets" that while times(2) clocks are in units of `sysconf(_SC_CLK_TCK)`, clock(3) ones are in units of CLOCKS_PER_SEC. Hopefully, these just happen to be the same on systems where jumbo uses clock(3) now (MinGW, etc.) - but we need to carefully review the code and make sure we start using the proper units corresponding to the calls we make.

**Comment by magnumripper** [comment]
Apparently `CLOCKS_PER_SEC` is 1000 under Windows (and it's `clock()` doesn't just count CPU time but also sleep time - why am I not surprised?). I yet to find any reference to `sysconf(_SC_CLK_TCK)` under Windows (using Google as a shield).

**Comment by magnumripper** [comment]
Confirmed - they are both 1000 under MinGW, 32-bit or 64-bit. This means we could merge the PR, but it also means we don't need to yet %-)
