### ISSUE TITLE
Tasks to do for release

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3929]
Notes to self:

- Ready to deploy (https://github.com/magnumripper/JohnTheRipper/commit/0e556d5ebb497fb129ac19cf7fb3d2a6afbe9cb7)
- Document the "packaging process";
  - For Launchpad: build and deploy;
  - For AppVeyour: build, save the files, and publish;
  - For Flatpak bundle: build, save the files, and publish;
  - For FlatHub: push and ask for a review;
  - Docker Hub: push and test the image saved in the Hub.
- Get and save:
  - ALL build logs;
  - detached zip files;
  - hashes in checksum.txt
- Then, allow people to get all relevant files;

* [x] Launchpad
```
wget https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/557702/+files/buildlog_snap_ubuntu_xenial_armhf_john-the-ripper_BUILDING.txt.gz
wget https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/557699/+files/buildlog_snap_ubuntu_xenial_i386_john-the-ripper_BUILDING.txt.gz
wget https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/557703/+files/buildlog_snap_ubuntu_xenial_arm64_john-the-ripper_BUILDING.txt.gz
wget https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/557701/+files/buildlog_snap_ubuntu_xenial_amd64_john-the-ripper_BUILDING.txt.gz
wget https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/557704/+files/buildlog_snap_ubuntu_xenial_ppc64el_john-the-ripper_BUILDING.txt.gz
wget https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/557700/+files/buildlog_snap_ubuntu_xenial_powerpc_john-the-ripper_BUILDING.txt.gz
wget https://launchpad.net/~claudioandre.br/+snap/john-the-ripper/+build/557705/+files/buildlog_snap_ubuntu_xenial_s390x_john-the-ripper_BUILDING.txt.gz
```

* [x] Windows
```
wget https://ci.appveyor.com/api/buildjobs/uauet2ejqx0742d3/artifacts/win_x64.zip  -O x64_win.zip
wget https://ci.appveyor.com/api/buildjobs/uauet2ejqx0742d3/artifacts/optional.zip -O x64_optional.zip
wget https://ci.appveyor.com/api/buildjobs/uauet2ejqx0742d3/log                    -O x64_log.txt

wget https://ci.appveyor.com/api/buildjobs/dq1hp9jbkmyo0sc4/artifacts/win_x32.zip  -O x32_win.zip
wget https://ci.appveyor.com/api/buildjobs/dq1hp9jbkmyo0sc4/artifacts/optional.zip -O x32_optional.zip
wget https://ci.appveyor.com/api/buildjobs/dq1hp9jbkmyo0sc4/log                    -O x32_log.txt
```

* [x] Flatpak Bundle
```
wget https://gitlab.com/claudioandre-br/packages/-/jobs/212460694/artifacts/download  -O john.flatpak.zip
wget https://gitlab.com/claudioandre-br/packages/-/jobs/212460694/raw                 -O bundle_log.txt
wget https://gitlab.com/claudioandre-br/packages/-/jobs/212460695/raw                 -O bundle_test.txt
```

* [x] FlatHub
```
Build 3430 successful
To test this build, install it from the testing repository:

flatpak install --user https://dl.flathub.org/build-repo/3277/com.openwall.John.flatpakref
```
* [x] Docker Image
```
wget https://api.travis-ci.org/v3/job/532480502/log.txt -O docker_log.txt
docker pull claudioandre/john:v1.9.0J1 # and push it to your Docker registry
```
* [x] Binaries checksums
https://openwall.info/wiki/_media/john/1.9.0J1/checksum.txt

**Comment by claudioandre-br** [comment]
Situation:
* [ ] Snap package (waiting)
* [ ] Windows (waiting)
* [ ] Flatpak bundle package (waiting)
* [ ] FlatHub (publishers are reviewing; be patient)
* [ ] Docker Image (waiting)

**Comment by claudioandre-br** [comment]
Testing:
* [ ] Multi Arch
* [ ] CI
* [x] BSD
* [x] Windows

Notes:
- bcrypt: what changed?

**Comment by claudioandre-br** [comment]
What we know:
* some OpenCL formats fail on AMD (but 100% pass Titan X on super);
* a few formats fail on BE (non-SIMD);
* powerpc build has "problems";
* it is possible to crash JtR using fuzzing;
* ...

**Comment by solardiz** [comment]
> * a few formats fail on BE (non-SIMD);

All of those are auto-disabled on BE. All remaining ones pass self-test on BE. So this isn't user-visible unless the user actually wanted to use some of those few formats, which would end up missing.

> * powerpc build has "problems";

I'm not aware of any current problems on PowerPC. I probably need to retest there.

**Comment by claudioandre-br** [comment]
> I'm not aware of any current problems on PowerPC

For example:
`Benchmarking: dynamic=md5($p) [Dynamic RDP]... FAILED (cmp_all(1))`

**Comment by solardiz** [comment]
Ouch. Is this in your current testing? We were aware of this issue before?

**Comment by claudioandre-br** [comment]
On GitHub since Apr 8. But, it works on 64bit BE (non-SIMD) and powerpc64le.

**Comment by solardiz** [comment]
What GitHub issue is that? I was truly under impression we either fixed all of those or disabled the formats on affected platforms.

**Comment by claudioandre-br** [comment]
The 1.9.0 J1 issue itself, as a side note (as I'm doing here).

**Comment by solardiz** [comment]
I've just merged my md5crypt-long optimizations, so please include that in your testing from this point on. Thanks!

**Comment by claudioandre-br** [comment]
These are the formats I disable before testing:
- https://raw.githubusercontent.com/claudioandre-br/packages/master/john-the-ripper/tests/disable_formats.sh

Some fail on BE, some are so slow that hurts CI, ... But, I re-enabled them to check how things are now.

S390x
```
Testing: enpass, Enpass Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(32))
Testing: STRIP, Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(256))

2 out of 402 tests have FAILED
 FAILED: -test-full=0 --format=cpu
```

That said, I need them disabled and the "what we know" above is correct.

**Comment by claudioandre-br** [comment]
If you guys don't mind, I would like to move the discussion to another thread. Keep here only my top 3-5 messages. 
****
Follow up, as another example:

powerpc

```
Testing: AndroidBackup [PBKDF2-SHA1 128/128 AltiVec 4x AES]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
Testing: radius, RADIUS authentication [MD5 32/32]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
Testing: bitshares, BitShares Wallet [SHA-512 64/32]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
Testing: andOTP [SHA256 32/32]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
```

**Comment by solardiz** [comment]
Please move the discussion about formats failing on non-x86 for a new issue. Thanks! It's a nasty surprise to me we still have those issues, and will probably want to fix them - or at least try. All of these tests are passing for me e.g. on sparc64.

**Comment by claudioandre-br** [comment]
Tested. For me, it is ready (what is buggy is failing for months).

**Comment by solardiz** [comment]
>     * a complex environment confuses OpenCL (so, confuses JtR)

I guess we "simply" lack whatever magic is needed to read the temperature via ADL from the second GPU on a dual-GPU AMD card.

**Comment by magnumripper** [comment]
IIRC, ADL is so poorly defined we can only guess the relation between ADL numbers and OpenCL device numbers - I think I recall atom complaining about it too.

BTW didn't you mention some newer temp readings from `/proc` or whatever it was? What driver was that? We don't support reading that at all yet - we should open an issue for that.

**Comment by solardiz** [comment]
> BTW didn't you mention some newer temp readings from `/proc` or whatever it was?

That was `/sys`, and it's issue #3615

**Comment by claudioandre-br** [comment]
Any interested person may request access to:
```
Repository has been created: https://github.com/flathub/com.openwall.John
```

As seen in: https://github.com/flathub/flathub/pull/966#issuecomment-492779051
