### ISSUE TITLE
Discussion about formats failing on non-x86

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3932]
Please move the discussion about formats failing on non-x86 for a new issue. Thanks! It's a nasty surprise to me we still have those issues, and will probably want to fix them - or at least try. All of these tests are passing for me e.g. on sparc64.

_Originally posted by @solardiz in https://github.com/magnumripper/JohnTheRipper/issues/3929#issuecomment-491539404_
*****

> * a few formats fail on BE (non-SIMD);

All of those are auto-disabled on BE. All remaining ones pass self-test on BE. So this isn't user-visible unless the user actually wanted to use some of those few formats, which would end up missing.

> * powerpc build has "problems";

I'm not aware of any current problems on PowerPC. I probably need to retest there.
*****

These are the formats I disable before testing:
- https://raw.githubusercontent.com/claudioandre-br/packages/master/john-the-ripper/tests/disable_formats.sh

Some fail on BE, some are so slow that hurts CI, ... 

But, I re-enabled them to check how things are now. Unfortunately:

S390x
```
Testing: enpass, Enpass Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(32))
Testing: STRIP, Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(256))

2 out of 402 tests have FAILED
 FAILED: -test-full=0 --format=cpu
```

That said, I need them disabled and the "what we know" above is correct.

****
Follow up, as another example:

powerpc

```
Testing: AndroidBackup [PBKDF2-SHA1 128/128 AltiVec 4x AES]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
Testing: radius, RADIUS authentication [MD5 32/32]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
Testing: bitshares, BitShares Wallet [SHA-512 64/32]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
Testing: andOTP [SHA256 32/32]... (4xOMP) Warning: salt() returned misaligned pointer
PASS

dynamic_assign_script_to_format() the dynamic.cmp_all/cmp_one() failed. This expression can not be handled by john!
Benchmarking: dynamic=md5($p) [Dynamic RDP]... FAILED (cmp_all(1))

 FAILED: -test=3 -form="dynamic=md5($p)"
```

**Comment by solardiz** [comment]
@magnumripper Can you please look for issues that could be causing the failures and warnings above? Finding and fixing the lack of salt alignment is probably the easiest. Thanks!

I'll also take a look if there's anything left, but not right now.

**Comment by claudioandre-br** [comment]
The builds are (WIP)

```
Target CPU ................................. powerpc Altivec, 32-bit BE
AES-NI support ............................. no
Target OS .................................. linux-gnu
Cross compiling ............................ no
Legacy arch header ......................... ppc32.h
```

```
Target CPU ................................. s390x, 64-bit BE
AES-NI support ............................. no
Target OS .................................. linux-gnu
Cross compiling ............................ no
Legacy arch header ......................... autoconf_arch.h
```

**Comment by claudioandre-br** [comment]
ppc64

```
Testing: argon2 [Blake2]... (4xOMP) FAILED (cmp_all(8))
Testing: Raw-Blake2 [BLAKE2b 512 32/64]... (4xOMP) FAILED (cmp_all(131072))
Testing: tezos, Tezos Key [PBKDF2-SHA512 128/128 AltiVec 2x]... (4xOMP) FAILED (cmp_all(512))

3 out of 404 tests have FAILED
 FAILED: -test-full=0 --format=cpu
```

**Comment by claudioandre-br** [comment]
```
Testing: argon2 [Blake2]... (4xOMP) FAILED (cmp_all(8))
Testing: Raw-Blake2 [BLAKE2b 512 32/64]... (4xOMP) FAILED (cmp_all(16384))
Testing: tezos, Tezos Key [PBKDF2-SHA512 128/128 ASIMD 2x]... (4xOMP) FAILED (cmp_all(128))

3 out of 404 tests have FAILED
 FAILED: -test-full=0 --format=cpu
```

**Comment by magnumripper** [comment]
> @magnumripper Can you please look for issues that could be causing the failures and warnings above? Finding and fixing the lack of salt alignment is probably the easiest. Thanks!
> 
> I'll also take a look if there's anything left, but not right now.

Absolutely. Will look into it once I wake up in like 75 hours, or in worst case 7.5

**Comment by magnumripper** [comment]
I can't understand how bitshares format could return a misaligned pointer? It does return a pointer to a static struct, and SALT_ALIGN is indeed `sizeof(struct custom_salt*)`?

**Comment by magnumripper** [comment]
Wait, am I stupid now? It doesn't quite return a pointer, it returns the address of a struct.

**Comment by magnumripper** [comment]
Alignments should be fixed. Can't find the other problems.

**Comment by solardiz** [comment]
> S390x
> 
> ```
> Testing: enpass, Enpass Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(32))
> Testing: STRIP, Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(256))
> ```

What compiler are you using there? Are there any compile-time warnings for these? Maybe about strict aliasing violations?

**Comment by solardiz** [comment]
In general, can you try building for s390x, ppc64, and armv8 (the 3 archs where you had failing formats) with `-fno-strict-aliasing` (if with gcc) and see if it makes a difference?

**Comment by claudioandre-br** [comment]
All snaps use the same LTS environment. At this right moment, it is Xenial.

```
---------------------------- TESTING -----------------------------
Created directory: /root/.john
Version: 1.9.0-jumbo-1-bleeding-0e556d5 2019-05-11 20:32:59 +0200
Build: linux-gnu 64-bit s390x  AC OMP
System-wide exec: /snap/john-the-ripper/current/run
System-wide home: /snap/john-the-ripper/current/run
Private home: ~/.john
OMP fallback binary: john-non-omp
$JOHN is /snap/john-the-ripper/current/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.4.0
GNU libc version: 2.23 (loaded: 2.23)
Crypto library: OpenSSL
OpenSSL library version: 01000207f
OpenSSL 1.0.2g  1 Mar 2016
GMP library version: 6.1.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```

**Comment by claudioandre-br** [comment]
None has important warnings:
```
Optional libraries/features found:
Memory map (share/page large files) ........ yes
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
OpenCL support ............................. no
Generic crypt(3) format .................... yes
libgmp (PRINCE mode and faster SRP formats)  yes
128-bit integer (faster PRINCE mode) ....... yes
libz (pkzip and some other formats) ........ yes
libbz2 (gpg2john extra decompression logic)  yes
libpcap (vncpcap2john and SIPdump) ......... yes
OpenMPI support (default disabled) ......... no
ZTEX USB-FPGA module 1.15y support ......... no

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now "make -s clean && make -sj4" to compile.
monero_fmt_plug.c:288:2: warning: #warning ": monero format requires little-endian, format disabled." [-Wcpp]
 #warning ": monero format requires little-endian, format disabled."
  ^
rar_fmt_plug.c:442:2: warning: #warning ": target system requires aligned memory access, rar format disabled:" [-Wcpp]
 #warning ": target system requires aligned memory access, rar format disabled:"
  ^
stribog_fmt_plug.c:472:2: warning: #warning Stribog-256 and Stribog-512 formats require SSE 4.1, formats disabled [-Wcpp]
 #warning Stribog-256 and Stribog-512 formats require SSE 4.1, formats disabled
  ^
vms_fmt_plug.c:312:2: warning: #warning ": OpenVMS format requires little-endian, format disabled." [-Wcpp]
 #warning ": OpenVMS format requires little-endian, format disabled."
  ^
ar: creating aes.a
ar: creating secp256k1.a
ar: creating ed25519-donna.a

Make process completed.

```

**Comment by claudioandre-br** [comment]
The pool is busy today. So, I'll have to wait longer. 
* ARM64 is running and I can't see new warnings or failures. When I get the final result I'll let you know.
```
=== modified file 'build.sh'
--- build.sh	2019-05-11 19:07:36 +0000
+++ build.sh	2019-05-12 14:05:45 +0000
@@ -73,8 +73,8 @@
 
 else
     # Non X86 CPU
-    ./configure $OTHER_NO_OPENMP CPPFLAGS="-D_SNAP -D_BOXED" && do_build ../run/john-non-omp
-    ./configure $OTHER_REGULAR   CPPFLAGS="-D_SNAP -D_BOXED -DOMP_FALLBACK -DOMP_FALLBACK_BINARY=\"\\\"john-non-omp\\\"\"" && do_build
+    ./configure $OTHER_NO_OPENMP CPPFLAGS="-fno-strict-aliasing -D_SNAP -D_BOXED" && do_build ../run/john-non-omp
+    ./configure $OTHER_REGULAR   CPPFLAGS="-fno-strict-aliasing -D_SNAP -D_BOXED -DOMP_FALLBACK -DOMP_FALLBACK_BINARY=\"\\\"john-non-omp\\\"\"" && do_build

```

**Comment by claudioandre-br** [comment]
> The pool is busy today. So, I'll have to wait longer.

Much longer, in fact. 

But (`ba9cfd9B` + `-fno-strict-aliasing`), armv8 -> clear
```
-------------------------------------------
### Performed 14 tests in 1329 seconds ###
-------------------------------------------
```

```
All 404 formats passed self-tests!
 Ok: -test-full=0 --format=cpu
```

**Comment by claudioandre-br** [comment]
```
Testing: enpass, Enpass Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(32))
Testing: STRIP, Password Manager [PBKDF2-SHA1 32/64]... (4xOMP) FAILED (cmp_all(128))

2 out of 402 tests have FAILED
 FAILED: -test-full=0 --format=cpu
```

\-------------------------------------------
\###  Performed 14 tests in 397 seconds  ###
\-------------------------------------------
\----------------- s390x ------------------
\----------------------------------------
\###    Build failed with 1 errors    ###
\----------------------------------------

**Comment by claudioandre-br** [comment]
ppc64le-> clean
```
All 404 formats passed self-tests!
 Ok: -test-full=0 --format=cpu
```

```
-------------------------------------------
###  Performed 14 tests in 658 seconds  ###
-------------------------------------------
```

**Comment by solardiz** [comment]
> But (`ba9cfd9B` + `-fno-strict-aliasing`), armv8 -> clear

So we probably need to look for aliasing violations in those formats that failed on armv8 before, @magnumripper.

**Comment by claudioandre-br** [comment]
Other archs are building clean.

**Comment by magnumripper** [comment]
> So we probably need to look for aliasing violations in those formats that failed on armv8 before, @magnumripper.

Okay, will have a look. Most such problems we've had in the past was in SIMD code. Enpass and STRIP are nearly identical code so it's probably the same bug in both.

**Comment by magnumripper** [comment]
No wait, the armv8 ones are not Enpass and Strip - it's the Argon/Blake formats! So could the problem with them (that I see too when disabling SIMD) simply be aliasing violations? I need to test `-fno-strict-aliasing` myself.

**Comment by magnumripper** [comment]
Sure enough, either using `-Og` or `-fno-strict-aliasing` fixes the blake2 formats for me. But if I just do that for the actual format files, it doesn't help. So this ultimately boils down to #2738, doesn't it?

**Comment by magnumripper** [comment]
I had a look at syncing latest Argon2 but too much has changed, now is not the time.

**Comment by magnumripper** [comment]
The fouling file should be `blake2b-ref_plug.c`. It's a fairly small file but I can't see anything suspicious in it.

**Comment by magnumripper** [comment]
This diff fixes the problem on my gear:
```diff
diff --git a/src/blake2b-ref_plug.c b/src/blake2b-ref_plug.c
index 11ee5e0a6..1fb3c62b7 100644
--- a/src/blake2b-ref_plug.c
+++ b/src/blake2b-ref_plug.c
@@ -1,6 +1,8 @@
 #include "arch.h"
 #if defined(JOHN_NO_SIMD) || (!defined(__SSE2__) && !defined(__SSE4_1__) && !defined(__XOP__))
 
+#pragma GCC optimize 1
+
 /*
    BLAKE2 reference source code package - reference C implementations
 
```

**Comment by magnumripper** [comment]
Oh, how strange. I found the actual problem, although it's not clear to me why it's a problem.

**Comment by magnumripper** [comment]
Dang, that wasn't it. Something just wasn't rebuilt 😢

**Comment by solardiz** [comment]
Aliasing aside, looks like we also have a problem with possible reliance on `blake2*_param` structs being packed, but we've commented out the corresponding pragmas, and if we enforce struct packing then we might have problems with unaligned accesses to fields. I think this is beyond scope for trying to fix now, before our release - and we should update to newer upstream code first anyhow.

**Comment by magnumripper** [comment]
I could simply disable the affected formats unless `__SSE2__`

**Comment by magnumripper** [comment]
BTW I de-commented those pragma pack's and it made no difference in this case

**Comment by solardiz** [comment]
> I could simply disable the affected formats unless `__SSE2__`

I don't mind, but these formats do pass tests on many non-x86 machines, just not all. So I'm also OK leaving things as they are.

**Comment by magnumripper** [comment]
I also think that's better. Not sure if you're going to re-introduce something like BUGS (or just refer to GitHub issue, or something else) but just documenting it as a known problem should be enough.

**Comment by solardiz** [comment]
I think I see the problem. In blake2-impl.h we have special-case code for little-endian archs, where we violate aliasing rules. We should probably drop those optimizations.

**Comment by magnumripper** [comment]
Yeah I was just going to try that!

**Comment by solardiz** [comment]
This optimization appears to come from upstream - we're just changing the macro we check for. But that doesn't mean it's right.

**Comment by magnumripper** [comment]
Sure enough, that fixes them!

**Comment by magnumripper** [comment]
I'll commit a fix

**Comment by solardiz** [comment]
Were those failing archs little-endian only?

**Comment by magnumripper** [comment]
My failing macbook sure isn't

**Comment by magnumripper** [comment]
I mean IS

**Comment by claudioandre-br** [comment]
> Were those failing archs little-endian only?

Yes

**Comment by solardiz** [comment]
Upstream uses `memcpy` in those places now - quite silly, I think, unless they've ensured typical compilers optimize that out: https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-impl.h

**Comment by solardiz** [comment]
I'll be gone for the night. Good luck!

**Comment by magnumripper** [comment]
I understand why it's an endian problem and/or a problem with archs that doesn't allow unaligned reads. But I don't quite understand what makes it an aliasing violation, and just what my compiler decided to do with the code that broke it.

**Comment by solardiz** [comment]
> I don't quite understand what makes it an aliasing violation

It is not allowed to alias using types other than `char *` and `unsigned char *`. This is aliasing with wider-than-char integer types, presumably of different-size caller's types. (maybe indirect caller's, via several functions, with inlining). The compiler is free to assume no aliasing, so e.g. reorder writes to arguments to such inlined functions to be after reads using the presumed-non-aliasing types by the inlined functions themselves.

**Comment by solardiz** [comment]
> Why didn't ANY compiler warn about this one?

I'm not aware of any compiler that would detect and report on 100% of aliasing violations. I think this problem isn't even decidable in the general case, which is precisely why we have those rules and the `restrict` keyword - or else compilers would simply do the optimal thing exactly whenever possible without needing such rules and hints.

> it _might_ be that some of my OpenCL code

I actually don't know whether OpenCL has the same aliasing rules as C or not. We need to read up on that.

**Comment by magnumripper** [comment]
I understand most of it per se but in this very case I don't quite get how/why it did end up a problem. These functions are so simple and one would think on x86 it shouldn't be a problem. But like you say, inlining and other optimizations probably make the picture a bit more complicated.

**Comment by claudioandre-br** [comment]
After 4674105349589d11519b1ae84ebb7fcdadb0d696, only S390 is failing a `--test` run.

**Comment by magnumripper** [comment]
Enpass and STRIP probably have the one same bug, heaven knows what.

**Comment by claudioandre-br** [comment]
If you guys are going to disable the formats on that arch, I recommend using:
```
"$CC" -dM -E -x c /dev/null
#define __s390__ 1
#define __s390x__ 1
```

**Comment by magnumripper** [comment]
Thanks. I'll make a PR for that, although I'll let Solar decide whether to add it or not
