### ISSUE TITLE
fcntl(F_WRLCK) errors with mpirun

### ISSUE THREAD

**Issue by ringt** [magnumripper/JohnTheRipper#3956]
When using JtR/magnum across a decently large number of nodes, large numbers of write lock errors occur, terminating those specific threads.  

Using default input encoding: UTF-8
Node numbers 1-1056 of 1056 (MPI)
119@nid04460: fcntl(F_WRLCK): Resource temporarily unavailable
82@nid04459: fcntl(F_WRLCK): Resource temporarily unavailable
960@nid04570: fcntl(F_WRLCK): Resource temporarily unavailable
81@nid04459: fcntl(F_WRLCK): Resource temporarily unavailable
969@nid04572: fcntl(F_WRLCK): Resource temporarily unavailable
948@nid04570: fcntl(F_WRLCK): Resource temporarily unavailable
884@nid04569: fcntl(F_WRLCK): Resource temporarily unavailable
963@nid04570: fcntl(F_WRLCK): Resource temporarily unavailable
962@nid04570: fcntl(F_WRLCK): Resource temporarily unavailable
899@nid04569: fcntl(F_WRLCK): Resource temporarily unavailable
967@nid04570: fcntl(F_WRLCK): Resource temporarily unavailable
920@nid04569: fcntl(F_WRLCK): Resource temporarily unavailable
972@nid04572: fcntl(F_WRLCK): Resource temporarily unavailable
970@nid04572: fcntl(F_WRLCK): Resource temporarily unavailable
826@nid04563: fcntl(F_WRLCK): Resource temporarily unavailable
<snip>  

### Steps to reproduce ###
I am not the SA of the system(s) and unfortunately on this particular one they are still using CUDA versus OpenCL, so the configuration from the build was as follows:
./configure --enable-mpi --disable-opencl --enable-pkg-config 
I have tried different versions of MPI/GCC and that hasn't seemed to matter.  I did try using FLOCK instead of FNCTL but it produces similar errors.

Using the built-in queuing system (basically a wrapped mpirun where things like the number of processes are set in a script as variables) as follows:
aprun -F e -B ./john --pot=./john.pot --format=NT --incremental=VarAll12 --session=nt-incva12 ${HOME}/hashes.txt > va12-john.out

Current configuration distributes it across 1056 nodes, though it could be more or less if I so chose.  It doesn't seem to matter if I give a session name or not and if the file exists previously or not.  VarAll12 uses a custom characterset using successfully cracked passwords as the seed with a current character count of 91 and sets the MinLength to 8 and MaxLength to 12.

- `$ ./john --list=build-info`.
Version: 1.9.0-jumbo-1-bleeding-6f13d1be5 2019-04-26 14:32:05 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC MPI + OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 8.2.0
GNU libc version: 2.22 (loaded: 2.22)
Crypto library: OpenSSL
OpenSSL library version: 0100020bf
OpenSSL 1.0.2k  26 Jan 2017
GMP library version: 5.1.3
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

- `$ ./john --list=opencl-devices` (if applicable).
N/A

uname -a: Linux XXXXXXXX 4.4.162-94.72-default #1 SMP Mon Nov 12 18:57:45 UTC 2018 (9de753f) x86_64 x86_64 x86_64 GNU/Linux

**Comment by magnumripper** [comment]
This is likely a file locking problem in the cluster and not a JtR problem. What if you just start 10 nodes or so?

In Jumbo's `src/unused` directory there's a script for testing locks with flock(1) and if you modify it you could also try it with fcntl-lock(1) from https://github.com/magnumripper/fcntl-lock.

**Comment by magnumripper** [comment]
The failures are not in MPI-specific code, they are in `log_file_flush()`, logger.c:185.

Note that if you simply disable locking you are very likely to get thrashed output files (worst one, john.pot of course).

However, considering it's called "temporary" I wonder if we should catch some errno and simply retry taking the lock forever. Perhaps `EDEADLK`?

You could try this patch, and please report back:
```diff
diff --git a/src/logger.c b/src/logger.c
index 942349fe5..1ab93d95e 100644
--- a/src/logger.c
+++ b/src/logger.c
@@ -181,7 +181,7 @@ static void log_file_flush(struct log_file *f)
 	memset(&lock, 0, sizeof(lock));
 	lock.l_type = F_WRLCK;
 	while (fcntl(f->fd, F_SETLKW, &lock)) {
-		if (errno != EINTR)
+		if (errno != EINTR && errno != EDEADLK)
 			pexit("fcntl(F_WRLCK)");
 	}
 #else
```
If this helps, we need to do similar things to other locking.

If `EDEADLK` is indeed the problem here, a permanent fix might also include some random sub-second sleeping.

**Comment by ringt** [comment]
Patch applied and recompiled.  Will post back results when job finishes.

**Comment by ringt** [comment]
In response to your first post:
./fcntl-locktest.sh 
File initially not locked.
Locking file exclusively, using fcntl lock for 5 seconds.
Confirmed, file is locked. Waiting for shared lock...
Got it, now releasing.

./flocktest.sh 
File initially not locked.
Locking file exclusively, using flock(2) for 5 seconds.
Confirmed, file is locked. Waiting for shared lock...
Got it, now releasing.

In a short debug run, it appeared that I am not seeing the error message any longer, but I am also not seeing other evidence of a run (.rec files), so setting up a longer test outside of debug to confirm behavior.

**Comment by magnumripper** [comment]
Digging into some system headers, it appears "Resource temporarily unavailable" is not `EDEADLK` but `EAGAIN`. Now this is strange because we should never get that with `F_SETLKW` but regardless you should probably try the same patch as before but replacing `EDEADLK` with `EAGAIN`.

**Comment by magnumripper** [comment]
I now made a PR #3958 that you should apply instead. Please test that and report back!

**Comment by magnumripper** [comment]
An unrelated note:  "Incremental" mode doesn't behave well for that large number of nodes! It's distribution starts getting really poor long before three-digit node counts, let alone a thousand of them! So unless you plan to only exhaust a fraction of the actual keyspace, you'd be better off using subsets, pure mask mode or Markov mode.

**Comment by ringt** [comment]
I've pulled that branch, recompiled, and submitted the job.  Will post updates when I have them.

I have noticed wonky load distribution across the nodes but was living with it.  In reading the docs, blogs, reading lists on markov vs incremental mode, most of what i was reading suggested that with the changes to incremental and using a custom character set based off of past cracked passwords that their performance became essentially the same.  I also have to play nice with others and stop/resume sessions and as I recall markov didn't allow restoring sessions versus incremental allowing it.  Thank you for the insight, will dust off my markov notes and play around with it.

**Comment by magnumripper** [comment]
Markov has had resume support as far as I can recall, so that's not a problem!

**Comment by ringt** [comment]
Tested the incremental mode example and am no longer receiving thread terminations/errors. It appears fixed to me.

**Comment by magnumripper** [comment]
Thanks, so we'll probably merge the workaround. But this is ultimately a bug in your cluster. What is it, Linux?

**Comment by solardiz** [comment]
@ringt While we intend to include a workaround for this issue - repeating the call on `EAGAIN` - this has performance impact. I think the underlying issue is you're bumping into a limit on the number of concurrently held locks, and you might have a way to lift that limit, e.g. maybe `ulimit -x` or maybe it's some NFS-specific limit.

> they are still using CUDA versus OpenCL,

I think this is a misconception on your part. NVIDIA's OpenCL support comes as part of their CUDA releases. So them installing CUDA is just right, and shouldn't prevent you from building JtR with OpenCL support and running that, including with MPI.

**Comment by solardiz** [comment]
@ringt Can you also try running with the `--nolog` option? Maybe writes to the shared log file cause most of the problem.

**Comment by ringt** [comment]
To answer magnum, i included a uname -a in my initial report: 
uname -a: Linux XXXXXXXX 4.4.162-94.72-default #1 SMP Mon Nov 12 18:57:45 UTC 2018 (9de753f) x86_64 x86_64 x86_64 GNU/Linux
Additional info: 
cat /etc/os-release 
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

I will go back to an up to date clone and try with nolog and report back.
I will also work on trying to compile with opencl; however, I recall i ran into problems when i tried a good while ago and blamed the problems on the deprecation of CUDA (from CHANGES-jumbo "	Drop CUDA support. Closes #2348.")  and it not finding the opencl headers/libraries.

**Comment by ringt** [comment]
Same results by using the --nolog option with the patch not applied (with obviously no log).

This environment is meant for massively parallel openmpi computing, I would be surprised if there were low limits on file locks, but I will check with the SAs.

**Comment by solardiz** [comment]
> Same results by using the --nolog option with the patch not applied

Same as in "issue still present" (like it was originally) or "issue gone" (like it was with the repeat on `EAGAIN` workaround)?

**Comment by solardiz** [comment]
> blamed the problems on the deprecation of CUDA (from CHANGES-jumbo " Drop CUDA support. Closes #2348.")

Apparently, a lot of people are misreading this. Any suggestions on how to avoid that?

> and it not finding the opencl headers/libraries.

OpenCL headers/libraries are supposed to come from the CUDA install (when that's what you have).

Alternatively, OpenCL headers may be installed separately e.g. as the `opencl-headers` package on Debian & Ubuntu or downloaded from The Khronos Group website and put in place manually. We're considering bundling The Khronos Group's OpenCL headers along with JtR going forward, to avoid build issues on some misconfigured-OpenCL systems.

**Comment by ringt** [comment]
> > Same results by using the --nolog option with the patch not applied
> 
> Same as in "issue still present" (like it was originally) or "issue gone" (like it was with the repeat on `EAGAIN` workaround)?

As in not seeing the error messages and the threads are not terminating early (ie, like it was when i applied the patch)

**Comment by ringt** [comment]
> > blamed the problems on the deprecation of CUDA (from CHANGES-jumbo " Drop CUDA support. Closes #2348.")
> 
> Apparently, a lot of people are misreading this. Any suggestions on how to avoid that?
> 
You could maybe put the CUDA readme back out there and include this information or reference it more clearly in the OPENCL readme

**Comment by solardiz** [comment]
> not seeing the error messages and the threads are not terminating early

Great. I wonder if us increasing `LOG_BUFFER_SIZE` in `params.h` would also help. Can you try adding an extra `0` to that number, yet keep the log enabled (don't use the `--nolog` option)? The default is 1 MiB, adding a 0 to the hex number would make it 16 MiB. Are individual instances filling up the 1 MiB so frequently? Maybe, or maybe they reach some other log sync point. It would also be interesting to know what your log size is after running for how long.

> put the CUDA readme back

We still have this, but perhaps it's a too obscure file location and content:

```
$ cat doc/extras/README-CUDA
README CUDA:

CUDA support has been dropped. The last git revision containing CUDA was
aa3602b. Note that an OpenCL build has much more (and better) formats than
a CUDA-only build anyway - and nvidia works perfectly fine with OpenCL.
```

Please feel free to send us a PR that would have helped you figure out that our OpenCL support is meant to just work on a system with CUDA installed.

**Comment by ringt** [comment]
Trying the change in params.h.  Log file (admittedly not run long b/c debugging) were between 600K and 2M.

At least for me, i totally missed it under extras.  Also, my attention->0 after seeing first sentence (CUDA support has been dropped).  Will work on a PR, its been a minute since I've done one so will have to dust off those old notes as well.

**Comment by solardiz** [comment]
> Log file (admittedly not run long b/c debugging) were between 600K and 2M.

Then the buffer size increase shouldn't make a difference, and I'm surprised that/why we were apparently acquiring a lock on it so frequently... or maybe not frequently, but just by all processes at roughly the same time?

>  Also, my attention->0 after seeing first sentence

Then we need to work on the first sentence.

**Comment by solardiz** [comment]
In NEWS, we have:

```
- Dropped CUDA support because of lack of interest.  We're focusing on OpenCL,
  which is more portable and also runs great on NVIDIA cards (in fact, much
  better than CUDA did for us before, due to our runtime auto-tuning and
  greater focus on getting OpenCL right).
```

This mentions NVIDIA on the second line... but doesn't say that one still needs to install CUDA to get OpenCL on NVIDIA cards. Perhaps we can start with this and improve upon it.

**Comment by ringt** [comment]
I would suspect it was lots of processes all firing off in very close proximity to each other. I did check ulimit and file locks are unlimited. (ulimit -x)

**Comment by ringt** [comment]
Confirming that changing params.h had no impact on errors (the FNCTL errors came back with LOG_BUFFER_SIZE set to 0x1000000)

**Comment by solardiz** [comment]
OK, then I guess we'll use the retry on `EAGAIN` workaround. Thanks!

**Comment by ringt** [comment]
As far as the documentation goes, i'll try to play around with setting up a dev environment and do a pull request, but that won't happen quickly.  My recommendation would be to move README-CUDA back to docs, and change the text to something like (more or less what you said here in this issue (I'm far from an expert, I am only repeating back what you said as I understood it)):

> Please note that CUDA packages typically include OpenCL support/headers.  While JtR has migrated away from CUDA only support, this does not prevent compiling/using OpenCL with JtR where CUDA and its development packages have been properly installed. 

The last git revision containing CUDA was aa3602b. 

The OpenCL build has much more (and better) formats than a CUDA-only build, including with nvidia,  and is already included with most CUDA packages or may be installed directly (without CUDA) in most distros with the opencl-headers package.
