### ISSUE TITLE
OldOffice-OpenCL is missing cracks

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3957]
An easy way to reproduce:
```
./jtrts.pl --internal -type oldoffice-opencl -v -v
# or
../run/john -skip -pot=tst-.pot ~/alltests.in --wordlist=/home/claudio/solucao -form=oldoffice-opencl
```

This is a post-release issue.

**Comment by magnumripper** [comment]
How could me miss this one?

**Comment by solardiz** [comment]
Do we have an idea of what's causing this issue and when it got introduced?

**Comment by magnumripper** [comment]
I have bisected it to 7078470601, which is kinda surprising. I will continue tomorrow with finding out just *what* change triggered this, and why. Not sure how many users need this format but it may call for a Jumbo-2 ASAP.

**Comment by claudioandre-br** [comment]
Strange, dozens of TS tests after that (with logs). Why we catch it now?

**Comment by magnumripper** [comment]
I have no idea. I just confirmed on a totally different computer that it's that very commit.

**Comment by magnumripper** [comment]
Somehow Jim changed functionality of `hexlen()`. I haven't yet investigated exactly what happened, just copied working code from CPU format, and problem gone.

**Comment by magnumripper** [comment]
Assuming 7078470 actually only fixes bug and doesn't introduce new ones, the bug was introduced in dace1b349, also by Jim. He did this change to oldoffice-opencl but not to oldoffice.
