### ISSUE TITLE
SSE4.1 versus SSE4.2

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3969]
This is buggy: `SIMD: SSE4.1` and `CPU tests: SSE4.2`.
```
$ ../run/john --list=build-info | head
Version: 1.9.0-jumbo-1-bleeding-0bf1679 2019-05-17 16:10:58 +0200
Build: linux-gnu 64-bit x86_64 SSE4.2 AC OMP
SIMD: SSE4.1, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: SSE4.2
$JOHN is ../run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
```

```
$ ../run/john --test --format=sha512crypt
Will run 8 OpenMP threads
Benchmarking: sha512crypt, crypt(3) $6$ (rounds=5000) [SHA512 128/128 SSE4.1 2x]... (8xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	2718 c/s real, 339 c/s virtual
```

I did: `./configure --disable-native-tests CPPFLAGS='-msse4.2'`.

**Comment by magnumripper** [comment]
SSE4.2 only adds CRC-32C stuff, so all other formats use SSE4.1 instructions. Try benchmarking `-form:crc32 -cost=1` using SSE4.1 vs. SSE4.2 and there should be some difference. All other formats are merely using SSE4.1 instructions.

**Comment by claudioandre-br** [comment]
Build-info is correct, then?

**Comment by magnumripper** [comment]
>> Build: linux-gnu 64-bit x86_64 SSE4.2 AC OMP
>> SIMD: SSE4.1, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
>
> Build-info is correct, then?

The SSE4.2 instructions used for CRC-32 aren't SIMD (as in vector stuff), so I believe it is correct. It's an SSE4.2 build using SSE4.1 SIMD.
