### ISSUE TITLE
Should we release a Jumbo-2 with just the oldoffice-opencl bugfix?

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3973]
We can easily make a branch right at 1.9.0-jumbo-1, cherry-pick the oldoffice bugfix (and perhaps more, but not all) to it and tag the result as 1.9.0-jumbo-2.

Or should we wait a little more to see if something more pops up?

**Comment by solardiz** [comment]
Making a release+builds+announcements is significant effort. I am not willing to go for it _just_ for the oldoffice fix. Besides, I think Claudio's Windows builds are easier done based off our latest tree, and we must get AVX-512 support into whatever new 64-bit Windows builds we publish.

So my direct answer to your question is "no".

However, I think we should in fact continue working on improving stability and cleaning up the jumbo tree, over making unrelated invasive changes that are likely to break stuff. Maybe we'll release a 1.9.0-jumbo-2 in a month or two.

**Comment by claudioandre-br** [comment]
> I think Claudio's Windows builds are easier done based off our latest tree, and we must get AVX-512 support into whatever new 64-bit Windows builds we publish.

As a side note, I don't have a road-map for "under development" releases. At this right moment, none is available.
