### ISSUE TITLE
Is it possible to add an option to john: formats supported by OpenCL?  (for those who do not have a video card)

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#3976]
For example, I study the documentation [readme-opencl].  There is a command line 80: "./john --list = formats --format = opencl".  But I do not have support for opencl, so I get an error, but I would like to understand which formats are supported in theory.

john --list=formats --format=opencl
Unknown ciphertext format name requested

**Comment by claudioandre-br** [comment]
You don't need GPU software/drivers (or CPU OpenCL runtime) to have OpenCL. You need OpenCL itself.
```
$ john-the-ripper.opencl --list=opencl-devices
Error: No OpenCL-capable platforms were detected by the installed OpenCL driver.
Error: No OpenCL-capable devices were detected by the installed OpenCL driver.

$ john-the-ripper.opencl --list=formats --format=opencl
sha1crypt-opencl, KeePass-opencl, oldoffice-opencl, PBKDF2-HMAC-MD4-opencl, 
PBKDF2-HMAC-MD5-opencl, PBKDF2-HMAC-SHA1-opencl, rar-opencl, RAR5-opencl, 
TrueCrypt-opencl, lotus5-opencl, AndroidBackup-opencl, agilekeychain-opencl, 
ansible-opencl, axcrypt-opencl, axcrypt2-opencl, bcrypt-opencl, 
BitLocker-opencl, bitwarden-opencl, blockchain-opencl, cloudkeychain-opencl, 
md5crypt-opencl, sha256crypt-opencl, sha512crypt-opencl, dashlane-opencl, 
descrypt-opencl, diskcryptor-opencl, diskcryptor-aes-opencl, dmg-opencl, 
electrum-modern-opencl, EncFS-opencl, enpass-opencl, ethereum-opencl, 
ethereum-presale-opencl, FVDE-opencl, geli-opencl, gpg-opencl, iwork-opencl, 
keychain-opencl, keyring-opencl, keystore-opencl, krb5pa-md5-opencl, 
krb5pa-sha1-opencl, krb5asrep-aes-opencl, lp-opencl, lpcli-opencl, LM-opencl, 
mscash-opencl, mscash2-opencl, mysql-sha1-opencl, notes-opencl, NT-opencl, 
ntlmv2-opencl, o5logon-opencl, ODF-opencl, office-opencl, 
OpenBSD-SoftRAID-opencl, PBKDF2-HMAC-SHA256-opencl, 
PBKDF2-HMAC-SHA512-opencl, pem-opencl, pfx-opencl, pgpdisk-opencl, 
pgpsda-opencl, pgpwde-opencl, PHPass-opencl, pwsafe-opencl, RAKP-opencl, 
raw-MD4-opencl, raw-MD5-opencl, raw-SHA1-opencl, raw-SHA256-opencl, 
raw-SHA512-free-opencl, raw-SHA512-opencl, salted-SHA1-opencl, sappse-opencl, 
7z-opencl, SL3-opencl, solarwinds-opencl, ssh-opencl, sspr-opencl, 
strip-opencl, telegram-opencl, tezos-opencl, vmx-opencl, wpapsk-opencl, 
wpapsk-pmk-opencl, XSHA512-free-opencl, XSHA512-opencl, ZIP-opencl
```

I need to double check on Windows, but, I'm almost sure you have all you need in the Windows package from Openwall site and in the snap Linux package.
If you want to build it yourself, you only need the OpenCL package(s) (no ICD, no runtime, ...).

**Comment by claudioandre-br** [comment]
That said, I see no issue here (nor improve documents). Closing.

**Comment by torerobo** [comment]
GNU/Linux
apt-get install opencl-headers...

john2 --list=opencl-devices
Section [opencl-devices] not found.
help[:WHAT], subformats, inc-modes, rules, externals, ext-modes, ext-hybrids,
ext-filters, ext-filters-only, build-info, hidden-options, encodings,
formats, format-details, format-all-details, format-methods[:WHICH],
format-tests, sections, parameters:SECTION, list-data:SECTION,
<conf section name>


I can not exactly say for installing opencl.  But the flag in jtr in any variation (opencl) is not accepted.

**Comment by magnumripper** [comment]
Did you re-configure and rebuild Jumbo after you installed those headers?

**Comment by solardiz** [comment]
We might want to put the output of "--list=formats --format=cpu" and "--list=formats --format=opencl" from a fully-capable build into documentation files as part of our release-making, so that people can reference those lists for what formats are _potentially_ available. We're already excluding a few other formats when certain libraries are missing or when (not) on certain CPU architectures. When we make our dependency on OpenSSL optional, which we should, the number of such potentially-excluded formats will likely increase, at least initially.

**Comment by torerobo** [comment]
> Вы переконфигурировали и перестраивали Jumbo после того, как установили эти заголовки?
Yes, I compiled john again.  I repeat: there is no video card, serrer.  There is nothing about opencl.

![IMG_20190520_231322_335](https://user-images.githubusercontent.com/35532898/58049191-ea4e9a80-7b54-11e9-8015-1bb3fdfcfb0a.jpg)

**Comment by magnumripper** [comment]
For heaven's sake do not post screen shots of TEXT! Instead please copy the text and paste it as text or you look like an 11-year old 😉 

I would think you need not only the headers but also **some** OpenCL lib. On some debian RPi I have it's called `ocl-icd-libopencl1`.

**Comment by torerobo** [comment]
> You don't need GPU software/drivers (or CPU OpenCL runtime) to have OpenCL. You need OpenCL itself.
> 
> ```
> $ john-the-ripper.opencl --list=opencl-devices
> Error: No OpenCL-capable platforms were detected by the installed OpenCL driver.
> Error: No OpenCL-capable devices were detected by the installed OpenCL driver.
> 
> $ john-the-ripper.opencl --list=formats --format=opencl
> sha1crypt-opencl, KeePass-opencl, oldoffice-opencl, PBKDF2-HMAC-MD4-opencl, 
> PBKDF2-HMAC-MD5-opencl, PBKDF2-HMAC-SHA1-opencl, rar-opencl, RAR5-opencl, 
> TrueCrypt-opencl, lotus5-opencl, AndroidBackup-opencl, agilekeychain-opencl, 
> ansible-opencl, axcrypt-opencl, axcrypt2-opencl, bcrypt-opencl, 
> BitLocker-opencl, bitwarden-opencl, blockchain-opencl, cloudkeychain-opencl, 
> md5crypt-opencl, sha256crypt-opencl, sha512crypt-opencl, dashlane-opencl, 
> descrypt-opencl, diskcryptor-opencl, diskcryptor-aes-opencl, dmg-opencl, 
> electrum-modern-opencl, EncFS-opencl, enpass-opencl, ethereum-opencl, 
> ethereum-presale-opencl, FVDE-opencl, geli-opencl, gpg-opencl, iwork-opencl, 
> keychain-opencl, keyring-opencl, keystore-opencl, krb5pa-md5-opencl, 
> krb5pa-sha1-opencl, krb5asrep-aes-opencl, lp-opencl, lpcli-opencl, LM-opencl, 
> mscash-opencl, mscash2-opencl, mysql-sha1-opencl, notes-opencl, NT-opencl, 
> ntlmv2-opencl, o5logon-opencl, ODF-opencl, office-opencl, 
> OpenBSD-SoftRAID-opencl, PBKDF2-HMAC-SHA256-opencl, 
> PBKDF2-HMAC-SHA512-opencl, pem-opencl, pfx-opencl, pgpdisk-opencl, 
> pgpsda-opencl, pgpwde-opencl, PHPass-opencl, pwsafe-opencl, RAKP-opencl, 
> raw-MD4-opencl, raw-MD5-opencl, raw-SHA1-opencl, raw-SHA256-opencl, 
> raw-SHA512-free-opencl, raw-SHA512-opencl, salted-SHA1-opencl, sappse-opencl, 
> 7z-opencl, SL3-opencl, solarwinds-opencl, ssh-opencl, sspr-opencl, 
> strip-opencl, telegram-opencl, tezos-opencl, vmx-opencl, wpapsk-opencl, 
> wpapsk-pmk-opencl, XSHA512-free-opencl, XSHA512-opencl, ZIP-opencl
> ```
> 
> I need to double check on Windows, but, I'm almost sure you have all you need in the Windows package from Openwall site and in the snap Linux package.
> If you want to build it yourself, you only need the OpenCL package(s) (no ICD, no runtime, ...).

Thanks for the list!  There are a lot of theoretically supported formats.  Prost check yourself is not possible, but the documentation ...

**Comment by torerobo** [comment]
> Ради всего святого, не размещайте снимки экрана с текстом! Вместо этого, пожалуйста, скопируйте текст и вставьте его как текст, или вы выглядите как 11-летний
> 
> Я думаю, вам нужны не только заголовки, но и **некоторые** OpenCL-библиотеки. На некоторых Debian RPi у меня это называется `ocl-icd-libopencl1`.

I do not quite understand your disappointment in screenshots (this gives more information), ok..

dpkg -l
|/ Имя                      Версия       Архитектура  Описание
+++-========================-============-============-==========ii  ocl-icd-libopencl1:amd64 2.2.12-2     amd64        Generic Op

(install)

**Comment by torerobo** [comment]
agree with @solardiz 
Add "potential opencl supported formats" to the documentation.  Users of this information is interesting.

**Comment by magnumripper** [comment]
> I do not quite understand your disappointment in screenshots (this gives more information), ok..

Many reasons. Among them are: The text in a screenshot isn't searchable. Also, if we wanted to replicate something in your build (eg. if it had contained a Git hash), we can't copy-paste the text from a picture but have to type it manually, which is tedious. You seem to use some English-Russian translator yourself - would that be able to translate this answer if it was a picture of text? I guess not. And so on.
