### ISSUE TITLE
AC: Add -lrt if available

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3984]
We should link with `-lrt` like legacy builds now do (although no-one seems to have issues with us failing to do it), see #3981 (discussion).

**Comment by magnumripper** [comment]
According to man pages, `-lrt` is needed only for glibc versions before 2.17. And not needed on OSX, so probably not BSD either. I'll add it if needed (that is, if AC finds `clock_gettime` in that lib).

**Comment by solardiz** [comment]
I didn't review your changes, but current bleeding-jumbo fails to build on super with devtoolset-8:

```
[solar@super src]$ make -sj32
ar: creating aes.a
ar: creating ed25519-donna.a
ar: creating secp256k1.a
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: timer.o: undefined reference to symbol 'clock_getres@@GLIBC_2.2.5'
//lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1724: ../run/john] Error 1
make: *** [Makefile:190: default] Error 2
```

I'll re-open this issue now, but please feel free to close and track this separately instead.

**Comment by magnumripper** [comment]
Oh, I see now I probably missed adding `@RT_LIBS@` to Makefile.in (eg. right after `@M_LIBS@`).

**Comment by magnumripper** [comment]
@solardiz could you please try that, and commit it if that's the solution? I have nearly no time for JtR for a week or so. I will read mail sporadically.

**Comment by solardiz** [comment]
@magnumripper I'd rather leave this to you. Personally, I'm not convinced we should have gone for this complexity at all (higher-res timers).
