### ISSUE TITLE
Add padding check to bitcoin format, just to be sure.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#399]
https://github.com/magnumripper/JohnTheRipper/commit/89bf80fbd6df52ae7d04d94b3c3a826000b30549#commitcomment-4366056

We should verify if it's true the padding is always 16 bytes. If so, we can definitely do without FMT_NOT_EXACT (and we should stop allowing >=4).

**Comment by kholia** [comment]
This ticket is up for grabs now.

**Comment by kholia** [comment]
The current padding check in `bitcoin_fmt_plug.c` seems to be solid. So I am closing this very old ticket.
