### ISSUE TITLE
Make ZTEX firmware version string independent of JtR version

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#3992]
This is somewhat tricky to edit, so I chose not to bother, nor to bother @Apingis with a request to make this edit prior to our 1.9.0-jumbo-1 release (especially given that he was mostly unavailable at the time). However, the string still saying "JtR 1.8.x" might confuse some people.

I imagine the easiest way to edit this string is in the .ihx file, without actually recompiling the firmware, and in the host code for what string to expect. Should we maybe use JtR-unrelated versioning scheme there, so that this doesn't become confusing each time we make a new major release?

Alternatively, we might hide reporting of this string, and use it for JtR-internal comparisons only (like we already do). But I think coming up with a JtR-unrelated versioning scheme is both easier and better.

Please make suggestions in comments to this issue before actually committing a change.

**Comment by Apingis** [comment]
The firmware is relatively stable comparing to the rest of the project, I don't expect frequent updates nor there're any planned updates.
I'd chose JtR-unrelated versioning scheme, with version identifiers different from JtR versions (e.g. "inouttraffic 1.0.2 JtR").

**Comment by solardiz** [comment]
> The firmware is relatively stable comparing to the rest of the project, I don't expect frequent updates

Yet the firmware is part of our project's code, so please get its source code and build instructions into our tree.

> I'd chose JtR-unrelated versioning scheme, with version identifiers different from JtR versions (e.g. "inouttraffic 1.0.2 JtR").

This looks good to me. Maybe start with "inouttraffic 1.0.0 JtR".

**Comment by Apingis** [comment]
> Yet the firmware is part of our project's code, so please get its source code and build instructions into our tree.

OK, that's in src/ztex/ez-usb/
