### ISSUE TITLE
Is it possible to improve the --dupe-suppression option?

### ISSUE THREAD

**Issue by torerobo** [magnumripper/JohnTheRipper#4001]
cat word
aKuS1
ber
hu
gf

john2 --prince=word --rules=single --stdout > bigword
Press 'q' or Ctrl-C to abort, almost any other key for status
1106708p 0:00:00:00 100,00% (2019-05-26 13:42) 4426Kp/s dsdsdsdsdsdsdsds

sort -u bigword | wc -l                **1005452**

john2 --prince=word --dupe-suppression --rules=single --stdout > nodublebigword
Press 'q' or Ctrl-C to abort, almost any other key for status
1106708p 0:00:00:00 100,00% (2019-05-26 13:42) 4426Kp/s dsdsdsdsdsdsdsds

~/doc/PRINCE

> You can use Jumbo's normal --dupe-suppression option for suppressing dupes
>     from input.

--dupe-suppression successfully works with the dictionary, but does not work intellectually with the rules

**Comment by magnumripper** [comment]
"...for suppressing dupes from **input**."

It works as stated. Despite that PRINCE mode (or rules) can obviously produce duplicates in **output** but that's not what we're trying to suppress because it would have serious performance impact (to the end that it'll be contra productive).
