### ISSUE TITLE
unique may truncate output file lines

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#4006]
`unique` will **silently** truncate any input lines exceeding `LINE_BUFFER_SIZE` (currently 1024 characters). I think that's dangerous - we should warn (once) any time this happens, *possibly* even returning with non-true status (we should not abort in the middle though, just return some error after all done, so eg. scripts using `unique && this || that` won't go on deleting the original files).
@solardiz what are your opinions here?

**Comment by solardiz** [comment]
I think this is an area for improvement, but I think it's overkill to treat this as a dangerous bug given typical uses of `unique`. 1024 is way higher than our maximum plaintext length of 125, so for those uses the truncation makes no difference.

I doubt I'll bother doing anything about this in core.

**Comment by magnumripper** [comment]
Sure, for typical core use (word lists) it's more like a feature. But it's not far fetched that someone would concatenate and `unique` a bunch of input files created over time with eg. zip2john and rar2john (which admittedly doesn't exist in core) or something like that, and then delete the originals. This would thrash them for good as nearly all archives IRL exceeds 1024 hex chars.

This actually happened to me, with a huge set of samples (although fortunately I hadn't yet deleted the original files).
