### ISSUE TITLE
SHA384 Hash from wallet.dat

### ISSUE THREAD

**Issue by ashraful1980** [magnumripper/JohnTheRipper#4280]
Dear Sir,
I would like to inform you that i extract wallet.dat and found $bitcoin$96$e648d207eb6a457cc3b415e5e6db38759de529051d808b5d34c679c43020a233e6b5161de2e85070127009d61e4c24c8$16$09792b4786f368cb$49019$96$aa9a6db8d6b1eb081826eb4f04cbc7a101653ba3e8af175756fdd400ae207de9d41e5749b96666579fd842f47b00489d$66$03ffd375f01d1ba11d8f24d69363cb92c031e998fd27946d103dc37b67544dbeb1

I have a questions that can i run SHA384 Hash from JohnTheRipper as like : john.exe --format=raw-sha384  hash.txt (e648d207eb6a457cc3b415e5e6db38759de529051d808b5d34c679c43020a233e6b5161de2e85070127009d61e4c24c8). Also can i find password from this command line. Please advice

Thanks & Regards,
Md. Ashraful Alam

**Comment by claudioandre-br** [comment]
You don't need to inform the `--format` option in order to crack this hash type. John can detect it automatically.

```
$ cat hash.txt 
$bitcoin$96$e648d207eb6a457cc3b415e5e6db38759de529051d808b5d34c679c43020a233e6b5161de2e85070127009d61e4c24c8$16$09792b4786f368cb$49019$96$aa9a6db8d6b1eb081826eb4f04cbc7a101653ba3e8af175756fdd400ae207de9d41e5749b96666579fd842f47b00489d$66$03ffd375f01d1ba11d8f24d69363cb92c031e998fd27946d103dc37b67544dbeb1
```
```
$ john hash.txt 
Using default input encoding: UTF-8
Loaded 1 password hash (Bitcoin, Bitcoin Core [SHA512 AES 256/256 AVX2 4x])
Cost 1 (iteration count) is 49019 for all loaded hashes
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:/snap/john-the-ripper/current/run/password.lst
0g 0:00:00:06 0.70% 2/3 (ETA: 18:53:14) 0g/s 192.9p/s 192.9c/s 192.9C/s 
```
*****

That said:
* The GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. If you still need user support from the community, please use the john-users mailing list instead.
