### ISSUE TITLE
Add new single-wordlist cracking mode

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#497]
Currently we have these two ways (among others) of producing candidates:
- Single mode will use 'user info' but not a wordlist
- Wordlist mode will use a wordlist but the 'user info' is unavailable

Combine that! Add a Single mode that takes a wordlist file, and add rules (or variables?) for the current user name (and gecos info etc). So if we have this hash:

```
root:<hash>:0:0:Super User::
```

Combining the word 'pass' from a wordlist with the user info, rules could construct password candidates like rootpass, passSuper, SuperUserpass and so on. I believe this would prove very powerful.

**Comment by magnumripper** [comment]
Like I just mentioned in a commit comment, I'm on to this (will be `--single-wordlist=FILE`). I have some ideas for how to do it KISS, with very little code added (and I will enhance `--single-seed=WORD` at the same time so it allocates the word(s) just once - that's quite some difference with a 100 million users).

I picture things like `--single-wordlist=car_brands.lst` and things like that (always fairly short wordlists of course) will be very effective. It will produce things like "beemer_bob" and "JohnnyDMC-12". Then change car_brands.lst against soccer_teams.lst or whatever. The sky's the limit!

**Comment by magnumripper** [comment]
Note to self: No word pairs should be created with two seed words - at least one of them must come from login or GECOS field. I think I know how to code this.

**Comment by magnumripper** [comment]
Dropped the "non-trivial" label. It **is** trivial, it just took me 2.5 years to figure it out 😎

**Comment by magnumripper** [comment]
A less important decision is whether `--single-wordlist` and/or `--single-seed` should imply
`--single` so you don't need to write that too.

**Comment by claudioandre** [comment]
+1 to imply.

**Comment by magnumripper** [comment]
> it just took me 2.5 years to figure it out

Looking at the mail archives, It actually took 6.5 years 😆

**Comment by magnumripper** [comment]
Another note to self: Single mode will create some word pairs for eg. "John Random Luser" of eg. "JRandom" and "JohnR". This should never happen to a seed word. It should only be used in full. Abbreviating "Chelsea" to "C" makes no sense at all in this context.

**Comment by jfoug** [comment]
Single mode is SO powerful, but improving it in this manner makes it MUCH more powerful yet.  The single mode 'is' showing a bit of age, and this gets it back up to cutting edge.  I really think single mode (if there is GECOS data) is by far the most powerful and fast mode out there.  For HUGE and slow cracking (like AM was prior to the legacy crypt bug found), single was pretty much the ONLY way to attack that data.  I ran just single mode, and had cracked over a million candidates (I back-filled with 12345 and 123456 when the crack was not 'full').  That mode really handled terribly slow monster dumps well.    But having seeds of ashley and madison (or sex, xxx, etc) would really improve AM.   Also, this would add a very useful help when a web site is dumped.  Many users do things like  netflix-password for their netflix account, etc.  Providing ability to easily inject knowledge to things like known website dumps will crack a very good amount of extra hashes.

**Comment by jfoug** [comment]
Can we simply enhance the --single option, vs making 3 of them??

**Comment by magnumripper** [comment]
Ideally it should've been `--single --rules=RULES` instead of `--single=RULES` and then we could have added options. I don't like overloading an option like was done to Markov.

**Comment by jfoug** [comment]
It IS --single=RULES

**Comment by claudioandre** [comment]
I like "--single=RULES" (but this is personal). Since JtR already has it, Jim's "one option" is a choice:
```
RULE | -wordlist=FILE | -seed=WORD
```

Maybe awkward (?!). I'm afraid I don't like its "muchness".
```
--single=-seed=brand
--single=-wordlist=family_names.txt
--single=-wordlist=car_brands.lst --rules=jumbo #If I want both.
```

**Comment by jfoug** [comment]
> Maybe awkward (?!). I'm afraid I don't like its "muchness".

I came up with it off the cuff.  If you have better ideas, toss them out.  I also think what I have is awkward, but usable.

> --single=-wordlist=car_brands.lst --rules=jumbo #If I want both.

Could also do both like this:

```--single=jumbo:-wordlist=car_brands.lst

**Comment by magnumripper** [comment]
You are kidding, right!? I really hate what we did to --markov and now you are proposing the same crap again 😆
How would anyone remember that oddball syntax? How would we tell getopt how to check syntax? How would we implement bash completion for it? 

I'm done adding the functionality and right now it's separate options `--single-seed` and `--single-wordlist`. Personally I see absolutely no need for making it harder than that. Try it out instead, it rocks.

**Comment by magnumripper** [comment]
>> A less important decision is whether --single-wordlist and/or --single-seed should imply --single so you don't need to write that too.
>
> +1 to imply.

Haven't tried it yet and I'm not sure I will bother. There's some caveats with option flags and stuff... I think I'll just leave it as-is.
