### ISSUE TITLE
port keyring2john.c to python

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#549]
@sanjukholia feel free to work on this issue, as well.

**Comment by tkisason** [comment]
Is http://openwall.info/wiki/john/sample-non-hashes#GNOME-Keyring the correct target for testing the new python code? Is anyone else working on this?

**Comment by kholia** [comment]
@tkisason yes, that is the correct target. Feel free to get this done :+1:

**Comment by tkisason** [comment]
Done, check if the pull request is ok and if it can be merged

**Comment by magnumripper** [comment]
Thanks, I merged it without testing for now, as it can't possibly break anything anyway. Leaving the test to @kholia for now.

**Comment by kholia** [comment]
@tkisason @magnumripper looks and runs well, thanks!

**Comment by tkisason** [comment]
Thanks. Off to the next one.. :)
