### ISSUE TITLE
add pause-button

### ISSUE THREAD

**Issue by rofl0r** [magnumripper/JohnTheRipper#635]
it's tedious to interrupt current jobs and restart them later, especially if you're half-way through and forgot to use a session name.
as there are often situations one wants to pause to use cores temporarilly for something else, i think adding a pause keyboard shortcut (maybe P) for pausing/continuing a run would greatly improve usability.

**Comment by claudioandre-br** [comment]
I skipped issues like this. But, it is clear that:

* **Fixed** - It was fixed.

* **WontFix** - Covers all the reasons we chose to close the bug without taking action.
  * Nobody cares.
