### ISSUE TITLE
clang debug build problem on 32bit linux

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#661]
With

```
make distclean; CC=clang ./configure && make debug
```

I get

```
clang -DAC_BUILT -march=native -mssse3 -c -g -O2 -I/usr/local/include   -Wall -Wdeclaration-after-statement -fomit-frame-pointer -Wno-deprecated-declarations -Wno-format-extra-args -Qunused-arguments -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE  -DHAVE_NSS -I/usr/include/nss3 -I/usr/include/nspr4     -pthread  -O0 -DDEBUG -funroll-loops gost.c -o gost.o
gost.c:147:4: error: inline assembly requires more registers than available
                        "movl %%ebx, %13\n\t"
                        ^
gost.c:147:4: error: inline assembly requires more registers than available
gost.c:147:4: error: inline assembly requires more registers than available
gost.c:147:4: error: inline assembly requires more registers than available
gost.c:147:4: error: inline assembly requires more registers than available
gost.c:147:4: error: inline assembly requires more registers than available
gost.c:147:4: error: inline assembly requires more registers than available
7 errors generated.
make[2]: *** [gost.o] Error 1
make[2]: Leaving directory `/home/fd/git/JtR/src'
make[1]: *** [default] Error 2
make[1]: Leaving directory `/home/fd/git/JtR/src'
make: *** [debug] Error 2
```

When I change the Makefile generated by ./configure to use -O1 instead of -O0 for  debug targets, the build succeeds.
gost.c is the only source which requires -O1, all other object files can be built with -O0.

With gcc, the debug build succeeds with -O0.

I am not sure what would be the best option to resolve the issue.
Generally switching to -O1 for debug builds (like Makefile.legacy does)?
Just using -O1 for 32bit builds, or only for 32bit clang builds?

**Comment by Rohitpoddar92** [comment]
Did anyone find a workaround for it? I am facing the same issue.
"pushl       %%ebx           \n\t" ......... 

inline assembly requires more registers than available

**Comment by magnumripper** [comment]
Not that I know of. You probably need to upgrade clang or use gcc instead.

**Comment by Rohitpoddar92** [comment]
I am using the latest version of clang. I can't move to GCC. 

Does it mean I need to rewrite the entire assembly code?

**Comment by kholia** [comment]
@Rohitpoddar92 This is a issue tracker for the JtR jumbo project. Are you trying to compile JtR and getting compilation errors *OR* are you compiling some other stuff and just complaining here? I can't tell.

**Comment by Rohitpoddar92** [comment]
ohh. sorry, I noticed it now.  
I am not working on JtR combo. I am woking on some other project.

**Comment by magnumripper** [comment]
Duh. Good catch, @kholia!

**Comment by kholia** [comment]
I guess no further action is required here.
