### ISSUE TITLE
Update formats using high count PBKDF2-hmac-xx that do not use pbkdf2-hmac-xxx.h

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#872]
___***First***___, make a list of the formats here, then start to pick them off.  Most are easy do do and get at least 2x improvements, and once you get SIMD, you get another 2x-4x.

I am NOT tagging this issue to any milestone (at this time).  But it might be good for jumbo-2

- [x] ~~~efs_fmt_plug.c~~~  (done, but was a 'buggy' pbkdf2 implementation)
- [x] ~~~known_hosts_plug.c~~~  (was only simple hmac, BUT salt/pass were reversed, so we got 2x gain precomputing the 1st half of the hmac in get_salt)
- [x] ~~~siemens-s7~~~ Some gain here, doing 1/2 of hmac only when new_keys are done. (doubled many salts speed)
- [x] ~~~rsvp~~~  simple hmac.  We can load 1/2 of the hmac in set_key and double many salts speed. (well, speed was not quite double, but close).
- [x] ~~~krb5-18_plug.c~~~  (done, had to convert from -krb5 at same time. 16x improvement)

**Comment by magnumripper** [comment]
I think this was fixed long ago
