### ISSUE TITLE
OMP_SCALE auto-tuning

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#875]
Continued from #871

**Comment by magnumripper** [comment]
I think this issue was obsoleted by lots of work we did half a year ago plus even more work @zzlei did this summer.

**Comment by jfoug** [comment]
It is not obsoleted, BUT it has actually been updated so that it works better across more current platforms.  So taking the full step of probing and detecting, or simple 'providing' overrides to allow someone to do it easily themselves may now not be that great on ROI

2 or 3 years from now, it might be, when we have to spend a lot of time getting things re-tuned with whatever the state of hardware is at that time, but we certainly can kick the can down the road until then, lol.

**Comment by magnumripper** [comment]
We'll probably revisit this at some point but not much of the info here is up to date now so it's probably better to open a new issue at that time.

I just finished a minor audit of all open issues without a milestone, and closed a few. I also renamed your "Jumbo-2 (not critical)" milestone, or what it was called, to "Jumbo-3" but they're just labels anyway - we might end up fixing some of those prior to J2 anyway.

**Comment by jfoug** [comment]
We probably should have milestones for most issues, even if the milestone is ```tasks to do only when you are so bored because you are buried in snow in a cabin in the woods```  :smirk:

**Comment by magnumripper** [comment]
I actually considered that, to separate them from "issues that are yet to classify". We could have a milstone of "later".

**Comment by jfoug** [comment]
later is so boring, but yes, it works, lol.  Some of the issues are really more discussion issues, so they should have some non-milestone milestone that separates them. There are not too many of them, but some.    Some (as I hate to think, the unicode port) are pretty pie in the sky.  They would be great IF we could do them, but they may actually be larger than what actually ever gets done.

**Comment by jfoug** [comment]
Actually, this issue sort of fit into that category.  A very good thing if we could do it, but probably a much bigger project that was doable.  The way we worked around this, hard coding stuff was a very good stop gap. 

But there are others in this group.  I really think the configure script was looked at this way for a long time. Yes, we thought it would be great, but it was just more than we knew how to do.   Yet now, I can not see john without it and would NEVER want to go back.
