### ISSUE TITLE
OMP scaling

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#877]
Here is an example (cygwin64, OMP build)

```
$ OMP_NUM_THREADS=8 ../run/john -test=5 -form=tc_ripemd160
Will run 8 OpenMP threads
Benchmarking: tc_ripemd160, TrueCrypt RIPEMD160 AES256_XTS [32/64]... (8xOMP) DONE
Raw:    4.8 c/s real, 4.5 c/s virtual


$ OMP_NUM_THREADS=1 ../run/john -test=5 -form=tc_ripemd160
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Benchmarking: tc_ripemd160, TrueCrypt RIPEMD160 AES256_XTS [32/64]... DONE
Raw:    39.4 c/s real, 39.7 c/s virtual
```

I have fixed one of these https://github.com/magnumripper/JohnTheRipper/commit/38aa13b3d9d1999be70973117d2f1a893190aaf5   But we need to identify them, and at least work around them (like this). It would be nice to know WHY, and if why, then try some way to auto-detect.

It likely (for the tc_* hashes on cygwin), that the PKCS5_PBKDF2_HMAC() oSSL function was made thread safe by simply putting a mutex around the call, OR worse, they put a mutex around some interal part of the call (such as the HMAC).  The 2nd is more likely.  So what happens is 8 threads start into PKCS5_PBKDF2_HMAC() call, then they all but one block and that one does an HMAC.  That thread then is stopped, and the next thead gets it's chance to go.  HORRIBLE performance!!

That is just a theory, but from dealing with poorly coded MT code before, it is what it looks like it is doing.

I will add some rel-bench runs where I cut out things that did not look quite right, and put them into a follow up post.

**Comment by jfoug** [comment]
I did some work on dyna. I was able to get things to have more or less values in OMP.  Now comes the tough part. There are some formats that get slower (some much slower), when you increase count, and some that get faster.  So, I may have to make some changes.  For these changes I will need to:

1. find the max required (for any dyna)
2. allocate (we only allocate ONE time) the buffers based upon this max.
3. add data to formats that allow them to override (down) from this max OMP value).
4. make changes to some functions which simply use MAX_KEYS in for loops. They would have to use the 'max' value for the specific dyna format.

But all in all, I think I can get 150% for many formats (the faster ones), might get 200% for some that are over scaled today, and get 110-120% for most others.  Some may have no change at all.

For example, here were some timings I saw

```
8x-OMP on my Core-i7 quad HT

raw-md5
   68000k
dyna_0
   44000k   (6144 scale)
   54000k   (6144*2 scale)
   56000k   (6144*3 scale)
   56000k   (6144*4 scale)  (this one fluxuated quite a bit)
```

So you can see for this format, we got about have of the loss back, and there is no way we can get it all, there simply is WAY too much overhead in dyna that I simply can not eliminate.

But I do think I can get dyna working quite a bit quicker for many of the formats.  It may not be a trivial undertaking, but I really think it needs done.  At the same time, I really would love to simplify this somewhat, but I may not be able to do that.  Being able to handle SIMD (of multiple flavors), oSSL, md5_go, md5_body and md5_body-x2 is NOT trivial, especially allowing switching in and out of SIMD/flat.  The code prior to md5_body-x2 was quite a bit more simplistic, BUT that md5_body_x2 does provide a significant improvement in performance, so I think coding for it, even though it adds 100's of extra lines of #ifdef code, does make the format faster.

**Comment by magnumripper** [comment]
Is Dynamic all-or-nothing OMP? I usually build with --disable-openmp-for-fast-formats. I use --fork for the fast ones.

**Comment by jfoug** [comment]
I believe it is all or nothing.  I may have to address the disable-omp-for-fast-formats switch.

**Comment by jfoug** [comment]
Ok, here is a 'checking' program (to test BE and LE GETPOS macros).

```C
#include <stdio.h>
#include <string.h>

// GETPOS test.
//  This will work with generating a proper get-pos for SIMD_COEF_32 of 
//  2, 4, 6, 16 limbs, for LE or BE.

void dump4(int, unsigned char *);

// I did this without using #defines, to allow easier debugging in MSVC.
// These will be defines in 'real' code
int SIMD_COEF_32=4;
int SIMD_SHIFT;
int SHA_BUF_SIZ=2;
int MD5_BUF_SIZ=2;

#define GETPOS_BE32(i, idx) ((idx & (SIMD_COEF_32-1)) * 4 + ((i) & (0xffffffff - 3)) * SIMD_COEF_32 + (((i) & 3) ^ 3) + (idx >> SIMD_SHIFT) * SHA_BUF_SIZ * SIMD_COEF_32 * 4)
#define GETPOS_LE32(i, idx) ((idx & (SIMD_COEF_32-1)) * 4 + ((i) & (0xffffffff - 3)) * SIMD_COEF_32 +  ((i) & 3)      + (idx >> SIMD_SHIFT) * MD5_BUF_SIZ * SIMD_COEF_32 * 4)

int main() {
	unsigned char Buf[512];
	int i, idx;

	if (SIMD_COEF_32==16)      SIMD_SHIFT=4;
	else if (SIMD_COEF_32==8)  SIMD_SHIFT=3;
	else if (SIMD_COEF_32==4)  SIMD_SHIFT=2;
	else if (SIMD_COEF_32==2)  SIMD_SHIFT=1;

	memset(Buf, 0, sizeof(Buf));
	for (idx = 0; idx < SIMD_COEF_32*2; ++idx) {
		for (i = 0; i < 4; ++i) {
			Buf[GETPOS_BE32(i,idx)]= (unsigned char)((i*16)+idx);
		}
	}
	dump4(1, Buf);
	memset(Buf, 0, sizeof(Buf));
	for (idx = 0; idx < SIMD_COEF_32*2; ++idx) {
		for (i = 0; i < 4; ++i) {
			Buf[GETPOS_LE32(i,idx)]= (unsigned char)((i*16)+idx);
		}
	}
	dump4(0, Buf);
}

/* Dumps 4 limbs.  Does BE to LE conversion if in BE format. */
void dump4(int isBE, unsigned char *buf) {
	int i;
	printf ("%s_%d: ", isBE?"BE":"LE", SIMD_COEF_32);
	for (i = 0; i < SIMD_COEF_32*4*4; i += 4) {
		if (buf[i] == 0 && buf[i+1] == 0 && buf[i+2] == 0 && buf[i+3] == 0)
			printf ("0 ");
		else {
			if (isBE)
				printf ("%02x%02x%02x%02x ", buf[i+3], buf[i+2],buf[i+1],buf[i]);
			else
				printf ("%02x%02x%02x%02x ", buf[i], buf[i+1],buf[i+2],buf[i+3]);
		}
	}
	printf ("\n");
}
```

Here are some results.  @magnum, can you please validate that the results for 8 and 16 coef are correct.  I 'think' they are, but I am not 100% sure.

```
BE_2: 00102030 01112131 0 0 02122232 03132333 0 0
LE_2: 00102030 01112131 0 0 02122232 03132333 0 0

BE_4: 00102030 01112131 02122232 03132333 0 0 0 0 04142434 05152535 06162636 07172737 0 0 0 0
LE_4: 00102030 01112131 02122232 03132333 0 0 0 0 04142434 05152535 06162636 07172737 0 0 0 0

BE_8: 00102030 01112131 02122232 03132333 04142434 05152535 06162636 07172737 0 0 0 0 0 0 0 0 08182838 09192939 0a1a2a3a 0b1b2b3b 0c1c2c3c 0d1d2d3d 0e1e2e3e 0f1f2f3f 0 0 0 0 0 0 0 0
LE_8: 00102030 01112131 02122232 03132333 04142434 05152535 06162636 07172737 0 0 0 0 0 0 0 0 08182838 09192939 0a1a2a3a 0b1b2b3b 0c1c2c3c 0d1d2d3d 0e1e2e3e 0f1f2f3f 0 0 0 0 0 0 0 0

BE_16: 00102030 01112131 02122232 03132333 04142434 05152535 06162636 07172737 08182838 09192939 0a1a2a3a 0b1b2b3b 0c1c2c3c 0d1d2d3d 0e1e2e3e 0f1f2f3f 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10203040 11213141 12223242 13233343 14243444 15253545 16263646 17273747 18283848 19293949 1a2a3a4a 1b2b3b4b 1c2c3c4c 1d2d3d4d 1e2e3e4e 1f2f3f4f 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
LE_16: 00102030 01112131 02122232 03132333 04142434 05152535 06162636 07172737 08182838 09192939 0a1a2a3a 0b1b2b3b 0c1c2c3c 0d1d2d3d 0e1e2e3e 0f1f2f3f 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10203040 11213141 12223242 13233343 14243444 15253545 16263646 17273747 18283848 19293949 1a2a3a4a 1b2b3b4b 1c2c3c4c 1d2d3d4d 1e2e3e4e 1f2f3f4f 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by jfoug** [comment]
Here were the 'originals'

```
#define GETPOS(i, idx)     ((idx & (SIMD_COEF_32 - 1)) * 4 + \
                           ((i) & (0xffffffff - 3)) * SIMD_COEF_32 + \
                           (((i) & 3) ^ 3) + (idx >> (SIMD_COEF_32 >> 1)) * \
                           SHA_BUF_SIZ * SIMD_COEF_32 * 4)
#define GETPOS(i, idx)     ((idx & (SIMD_COEF_32 - 1)) * 4 + \
                           ((i) & (0xffffffff - 3)) * SIMD_COEF_32 + \
                           ((i) & 3)      + (idx >> (SIMD_COEF_32 >> 1)) * \
                           MD5_BUF_SIZ * SIMD_COEF_32 * 4)
```

Here are my modifications
```
#define GETPOS_BE32(i,idx) ((idx & (SIMD_COEF_32-1)) * 4 + \
                           ((i) & (0xffffffff - 3)) * SIMD_COEF_32 + \
                           (((i) & 3) ^ 3) + (idx >> SIMD_SHIFT) * \
                           SHA_BUF_SIZ * SIMD_COEF_32 * 4)
#define GETPOS_LE32(i,idx) ((idx & (SIMD_COEF_32-1)) * 4 + \
                           ((i) & (0xffffffff - 3)) * SIMD_COEF_32 + \
                           ((i) & 3)      + (idx >> SIMD_SHIFT) * \
                           MD5_BUF_SIZ * SIMD_COEF_32 * 4)
```


The only thing that was changed was the ```(SIMD_COEF_32>>1)``  becoming ``` SIMD_SHIFT```   and SIMD_SHIFT will probably have to be SIMD32_SHIFT since we may have the same thing for SIMD64

**Comment by magnumripper** [comment]
I think they are OK, but I have been confused before :-)

**Comment by jfoug** [comment]
I am pretty sure dyna will be a real bitch when it comes to COEF > 4

I think for GSOC, we should probably just have them first create the SIMD code, and then simply create as small an update as possible for the raw format.  So they should update:

rawMD4_fmt_plug.c
rawMD5_fmt_plug.c
rawSHA1_fmt_plug.c
rawSHA256_fmt_plug.c
rawSHA512_fmt_plug.c

at first. Get them solid, and with as 'minimal' as possible change so that COEF==4|8|16 all work.  Once we get to that point, we can start to move out. I think the pbkdf2_*.h would probably be the 2nd thing(s) to do, as they are somewhat simple to change, and impact a bunch of formats.  Then start doing one off's on the other 70 or so SIMD formats, and also start on dyna.

Yes, getting some of these things like we are in this thread done up front is good. I really think we could get the raw formats 'ready', just waiting for the code.  But on a lot of it, we simply will have to put out fires.
