### ISSUE TITLE
lastpass_fmt_plug.c: Fix this format

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#883]
The salt definition includes a component iterations which is never used.
crypt_all seems to use a hard coded value of 500.
Who knows whether this format should handle a varying iteration count?
(If the number of iterations isn't a constant, it should be reported as a tunable cost.)

**Comment by jfoug** [comment]
Tied to #890

**Comment by Fist0urs** [comment]
As I said here:

[https://github.com/magnumripper/JohnTheRipper/issues/890#issuecomment-177023820](url)

Iteration number is not constant :/

**Comment by kholia** [comment]
This should be now fixed with PR #2661.
