### ISSUE TITLE
Problem with format LUKS

### ISSUE THREAD

**Issue by BenZero** [magnumripper/JohnTheRipper#946]
Hello , I try to recover a Luks encrypted partition 

I extracted the hash with luks2john but when i try to run john at the hash file i get the following error:

"592 : No such file or directory!" 

The output of luks2john starts with:

ubuntu@ubuntu:~/john/src$ sudo ../run/luks2john /dev/sda5
Best keyslot [0]: 162849 keyslot iterations, 4000 stripes, 40750 mkiterations
Cipherbuf size: 256000
Generating inlined hash with attached dump!
$luks$0$592$4c554b53babe00................................................

what i am doing wrong ?

Thanks in advance

**Comment by magnumripper** [comment]
I will presume it is. Good stuff :+1:
