### ISSUE TITLE
Use new common ishex() etc in more formats valid() function

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#954]
See https://github.com/magnumripper/JohnTheRipper/commit/4770e4c7efde2d61f86f04c85bd11651f2129b26#commitcomment-9091916 for discussion and examples of finding more formats where these common functions can save code, and be common code which can cut down on mistakes.

**Comment by solardiz** [comment]
I think many of our `valid` functions are best to be rewritten using some entirely new universal syntax-checking API, yet to be introduced. I doubt micro-enhancements like what's suggested in this stale issue are worth our time to perform them as a separate task going over all formats.
