### ISSUE TITLE
Drop some academic Dynamic formats unless -DDEBUG

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#956]
We might want to consider a cleanup of Dynamic formats. First, I never really understood why we have hard-coded copies of config-file formats. One of them should go (if the hard-coded ones are not faster than config-file ones I think the hard-coded ones should go). Second, some (I think many!) formats are never found IRL but created for testing/exercising the format. These should be limited to debug builds but I'm not sure how to make that happen for config-file formats... unless we add a special config file section for them, that is only read by debug builds?

**Comment by magnumripper** [comment]
> I just wonder if users will flip. J1 comes out with 382. J2 arrives with a pitiful 294, lol

That's no problem, we'll just have @kholia create a hundred new formats :-)

**Comment by kholia** [comment]
LOL, maybe I will ;)

**Comment by jfoug** [comment]
Ok, I have made changes to a make debug will 'ignore' the disabled flag for all dynamic formats.  So a 'debug' build will test ALL dynamic formats.  The other disabled formats are still disabled.  But any format with FMT_DYNAMIC flag set will be valid.
