### ISSUE TITLE
crypt format: Self test failed (valid (before init))

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#967]
```
(bleeding-jumbo)run $ cat fail_crypt.hex1 
313337793a2b394639336f314f7877674b31
(bleeding-jumbo)run $ cat fail_crypt.hex2 
2436244c4b4f2f55746534305433464e4639352436532f36543259754f494859304e335c704c4b61424a33736f5963584439ed423775566274455a446a2f4c4e736357685a6f5a394445482e7342636944725d7348cf574f6f4153624e4c547970482f31583236674e30
(bleeding-jumbo)run $ ./base64conv -q -i hex -o raw < fail_crypt.hex1 > fail_crypt.pw1
(bleeding-jumbo)run $ ./base64conv -q -i hex -o raw < fail_crypt.hex2 > fail_crypt.pw2
(bleeding-jumbo)run $ ./john --format=crypt fail_crypt.pw1 fail_crypt.pw2
Warning: hash encoding string length 13, type id #1
appears to be unsupported on this system; will not load such hashes.
Loaded 1 password hash (crypt, generic crypt(3) [?/64])
Will run 8 OpenMP threads
Self test failed (valid (before init))
```

**Comment by magnumripper** [comment]
Doesn't happen under OSX
```
$ ../run/john -form:crypt c3.in 
Warning: hash encoding string length 106, type id $6
appears to be unsupported on this system; will not load such hashes.
Loaded 1 password hash (crypt, generic crypt(3) [?/64])
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:10  3/3 0g/s 160032p/s 160032c/s 160032C/s alfmck..almcss
Session aborted
```

**Comment by jfoug** [comment]
It will only happen on a system that handle $6$ I think. Cygwin does not show the problem either.

**Comment by frank-dittrich** [comment]
On a system that doesn't handle $6$, you might be able ro reproduce this by combining a DES hash and a $1$ hash.

**Comment by magnumripper** [comment]
https://github.com/magnumripper/JohnTheRipper/issues/967#issuecomment-68228739 seems to show the bug even though $6$ is not supported

**Comment by magnumripper** [comment]
No, wait, it's DES that is not handled in that case.

**Comment by magnumripper** [comment]
So I reversed the order of input but it still does not trigger. I guess it's in the glibc-specific code.

**Comment by frank-dittrich** [comment]
So we just enhance autoconfig to enable the use of an alternative libc.
Then I might try to build john with dietlibc, http://www.fefe.de/dietlibc/, and see if the bug disappears.

**Comment by magnumripper** [comment]
Just squash the bug instead, that should be a lot easier...

**Comment by magnumripper** [comment]
...or even better, add an `#undef __GLIBC__` after the `#include <stdio.h` line and see if bug disappears!

**Comment by frank-dittrich** [comment]
I just added a printf.
The format is failing on this ciphertext: `CCNf8Sbh3HDfQ` from the first self test.
But what causes valid to fail here?

**Comment by frank-dittrich** [comment]
The trouble is that this hash from the input file is considered invalid by libc's crypt_r: `+S/.8o.Wuph9.`.
Later on, all descrypt hashes will be rejected as invalid here:
```
/* Previously detected as unsupported */
        if (sup_length[length] < 0 && sup_id[id] < 0) {
                return 0;
        }
```

**Comment by frank-dittrich** [comment]
That means, just because libc considered one has of length 13 as invalid and it considered one hash of ID 1 as invalid, we can't reject all the other hashes of id 1 and length 13. We'll have to let libc decide which of these hashes are valid.
The same applies for the other check:
```
 /* Previously detected as supported */
        if (sup_length[length] > 0 && sup_id[id] > 0)
                return 1;
```

Just because one of those hashes was valid doesn't mean libc can handle all of them.

**Comment by frank-dittrich** [comment]
These are the ciphertexts valid() is checking when I run `./john --format=crypt fail_crypt.pw1 fail_crypt.pw2`:
```
+9F93o1OxwgK1
$6$LKO/Ute40T3FNF95$6S/6T2YuOIHY0N3\pLKaBJ3soYcXD9<ED>B7uVbtEZDj/LNscWhZoZ9DEH.sBciDr]sH<CF>WOoASbNLTypH/1X26gN0
0x01008548B5723A6E41F9E689BA1EEC41164DA3531A6EE6CB6FF83A6E41F9E689BA1EEC41164DA3531A6EE6CB6FF8
0x01008548B57268F9F30CC3E3BB81ABF40D80E0BDCB463277A44F68F9F30CC3E3BB81ABF40D80E0BDCB463277A44F
0x01008548B5722D1D837C33D192DA05DAF1C5332FF485B1FE8D2810F3050AEEC770CEF80D1B7883CA32857B662FED
0x01008548B572CB6A67AD56A30555FAD5B2ADA272C961668FB74C6B448577AEA89AE6C82F70CF26AF2D425580E999
0x01008548B5726E4BB27440050708945E8A29F8CE0D87BB11590C3C06A2EAB2968ECF56193845C34094BBFBA61B50
0x01008548B572AA485DFA28D3AF6749A6A3094E455FAC5586DB8959AED7F3A559FF87BEA0DA1E3602A3BE05A5DF7F
0x01008548B572D50D38F242A0F02D39967E90DA11DC32B6E3B41AD50D38F242A0F02D39967E90DA11DC32B6E3B41A
0x01008248B84890DBDC8063E003604D83DD38D53B49A3377B9C5790DBDC8063E003604D83DD38D53B49A3377B9C57
0x01008548B5724301EB9294F1AF3F549FC8C33EDFA7498AA3D0E64301EB9294F1AF3F549FC8C33EDFA7498AA3D0E6
0x01008548B572BB2ADEED51163FA90514451F5A48F21A533C2729BB2ADEED51163FA90514451F5A48F21A533C2729
0x01008548B5727411A2B7CF2C84D1B89C050546B8277B94BBD7447411A2B7CF2C84D1B89C050546B8277B94BBD744
...
0x01008848B11CB49A59EDA3178A39E83E323212859D038FCC572FB1AEEA5E6924F7BF7D903D9C57227B8588648633
0x01008848B11CC302152CB0BEE04237FEE313925F051856A8A505C302152CB0BEE04237FEE313925F051856A8A505
0x01008848B11CFF3288253864BC0E9E247AB68E0C0F45D4A9F6A2FF3288253864BC0E9E247AB68E0C0F45D4A9F6A2
0x01008848B11C3669B22ED0770353AF488989B1C3DFF6057937103669B22ED0770353AF488989B1C3DFF605793710
0x01008848B11C59283C39A0D511E1F234EA047D733FB0F1C15AB959283C39A0D511E1F234EA047D733FB0F1C15AB9
0x01008848B11C18B5D835D9575D64403182FF977ED193254630F818B5D835D9575D64403182FF977ED193254630F8
0x01008848B11CDA4D8BDD56B44BF3BF5C4259D760B5EBC3262641DA4D8BDD56B44BF3BF5C4259D760B5EBC3262641
0x01008848B11CEBCC45DC8A9C16B4A18AD0DB82D57AB28C9B5EE3EBCC45DC8A9C16B4A18AD0DB82D57AB28C9B5EE3
0x01008848B11C63F26AE52039527427674471CEED5F3F89A30C2263F26AE52039527427674471CEED5F3F89A30C22
0x01008848B11CAA96776DD3505191778B6859B96C2F02C3C119858E65C48CFE405204FC97A32FE252713D61695084
0x01008848B11C546076251DB985B2CA395A2C71417B62718EF7F4546076251DB985B2CA395A2C71417B62718EF7F4
0x01008848B11C1D1F2A4917E8E0C1F9E40D1610BD56A9940396AEB537C2010E5997D074CC0F1BBF1D7D411B69239F
0x01008848B11C19954BE180C947715B631B6C2B55EDA92282BD6C8F3CDF1C73AD8F32A2F374695F7B80F63B6B6E11
0x01008848B11C03B1E562A7A3234949CE19E2D20FE2043595D48BFF2E3683CBC96AE7E379197BFAD670593CD492B8
CCNf8Sbh3HDfQ
```
In total, there are exactly 1500 garbage hashes tested in addition to the expected hashes.

**Comment by frank-dittrich** [comment]
I just confirmed this.
I can reproduce the input file with
```
137y:+9F93o1OxwgK1
x:CCNf8Sbh3HDfQ
```

The only thing that matters is that the first line contains a hash of length 13 which libc considers to be invalid, and that there is at least one valid hash in it.

```
$ OMP_NUM_THREADS=1 ./john --format=crypt fail/fail_crypt.pw1 
Warning: hash encoding string length 13, type id #1
appears to be unsupported on this system; will not load such hashes.
No password hashes loaded (see FAQ)
```

That means, the valid descrypt hash which comes second is now rejected as invalid.

When I change the sequence of these hashes in the input file, I get:
```
(bleeding-jumbo)run $ OMP_NUM_THREADS=1 ./john --format=crypt fail/fail_crypt.pw1 
Loaded 2 password hashes with 2 different salts (crypt, generic crypt(3) [?/64])
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: crypt_r() returned NULL
0g 0:00:00:02  3/3 0g/s 152564p/s 304713c/s 304713C/s astrula..babiana
0g 0:00:00:04  3/3 0g/s 187916p/s 375603c/s 375603C/s pilum..pop29
0g 0:00:00:06  3/3 0g/s 205156p/s 410115c/s 410115C/s bialy91..127285
Session aborted
```

**Comment by magnumripper** [comment]
> The trouble is that this hash from the input file is considered invalid by libc's crypt_r: +S/.8o.Wuph9.

Why is that? Is there something wrong with that hash? Did they drop support for DES?

**Comment by frank-dittrich** [comment]
I just virified that the same problem exists in core:

```
((detached from 1.8.0))run $ ./john --format=crypt fail/fail_crypt.pw1 
Loaded 2 password hashes with 2 different salts (crypt, generic crypt(3) [?/64])
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: crypt() returned NULL
fopen: ./ascii.chr: No such file or directory
((detached from 1.8.0))run $ ./john --format=crypt fail/fail_crypt.pw  
Warning: hash encoding string length 13, type id #1
appears to be unsupported on this system; will not load such hashes.
Loaded 1 password hash (crypt, generic crypt(3) [?/64])
Self test failed (valid)
```

**Comment by frank-dittrich** [comment]
> Why is that? Is there something wrong with that hash? Did they drop support for DES?

No, DES is still supported.
Apparently, `+S/.8o.Wuph9.` is not a valid DES hash.

**Comment by frank-dittrich** [comment]
BTW: `+9F93o1OxwgK1` is a valid BFegg hash from the BFegg self tests;)

**Comment by frank-dittrich** [comment]
`+S/.8o.Wuph9.` is a result of fuzzing `+C/.8o.Wuph9.` which also is a valid BFegg hash from the BFegg self tests.

**Comment by frank-dittrich** [comment]
I reported the core issue on john-users:
http://thread.gmane.org/gmane.comp.security.openwall.john.user/7815
http://openwall.com/lists/john-users/2015/01/04/1

**Comment by frank-dittrich** [comment]
BTW:
```
(bleeding-jumbo)run $ ./john fail_crypt.pw --format=descrypt --show=LEFT
?:CCNf8Sbh3HDfY
?:CCNf8Sbh3HDfU
?:CCNf8Sbh3HDfQ
0 password hashes cracked, 3 left
(bleeding-jumbo)run $ ./john fail_crypt.pw --format=crypt --show=LEFT
?:CCNf8Sbh3HDfZ
?:CCNf8Sbh3HDfY
?:CCNf8Sbh3HDfX
?:CCNf8Sbh3HDfW
?:CCNf8Sbh3HDfV
?:CCNf8Sbh3HDfU
?:CCNf8Sbh3HDfT
?:CCNf8Sbh3HDfS
?:CCNf8Sbh3HDfR
?:CCNf8Sbh3HDfQ
```

**Comment by magnumripper** [comment]
> Apparently, +S/.8o.Wuph9. is not a valid DES hash.

Bull does not show this behavior. It's valid in c3.

**Comment by magnumripper** [comment]
OK, man page says *salt  is  a  two-character  string chosen from the set [a–zA–Z0–9./].  This string is used to perturb the algorithm in one of 4096 different ways.*

This means we can probably work around this issue.

**Comment by frank-dittrich** [comment]
But there are "broken" descrypt implementations that accept other salts, e.g. implementations using password[0] and password[1] as the salt!
You can't just drop supporting these hashes if libc's crypt() accepts them.

I think Solar will have an opinion about how to handle this in core.

OTOH, there's another difference between what libc's crypt() accepts as valid and what th descrypt format accepts as valid (only 1 out of 4 hashes in a sequence, see my comment from 5 hours ago.

**Comment by jfoug** [comment]
Well, just use libc in valid()

**Comment by frank-dittrich** [comment]
valid() does use libc's crypt() (or crypt_r() for OMP builds), but it tries to remember whether libc supports a particular hash type and hash length, and reuse this informaton.
May be Solar wants to change this for all hash types and lengths, may be he just finds a workaround for what looks like descrypt hashes.

**Comment by frank-dittrich** [comment]
On my system, libc's crypt() is broken because it accepts all of these 4 hashes as valid, while just one of them is:
```
?:CCNf8Sbh3HDfT
?:CCNf8Sbh3HDfS
?:CCNf8Sbh3HDfR
?:CCNf8Sbh3HDfQ
```
But at least, all these 4 hashes have the same salt, so the overhead is not that bad, compared to the overhead of calling libc's crypt() instead of using --format=descrypt.

**Comment by magnumripper** [comment]
Note though that the generic crypt format is for systems that implement something we do not (yet). Like (initially) sha2crypt or sunmd5. I'd be perfectly fine with just closing this issue with no fix. Actually I **really** think we should leave this alone until Solar fixes it in core (if he ever cares to). We can leave the issue open forever, that is fine. This problem is not a problem in real life, or even semi real life.

**Comment by jfoug** [comment]
Here is one thing that 'appears' to fix it.  NOTE, if there are many of these 'bad' DES crypts they will all output. BUT this stops dropping ALL of them.

NOTE, I am pretty sure that the other ones would also be a problem, IF we have the first one found, that is right length, right 3 byte signature, but FAILS in the test load (for whatever reason).  I do not know if any others have failure points. Possibly they do for invalid characters, in the salt or hash.

I really think these should be ignored (possibly warned about), but the rest of the file processed.  Just because 1 fails, does not mean all of them from that point on should fail.

However, this is Solar's format.  I pretty much refuse to make too many 'core' changes to it.  IMHO, this whole short circuit should be removed, and the warning output only done in -verb=2 or more (but that does not exist in core, grrr).

```
diff --git a/src/c3_fmt.c b/src/c3_fmt.c
index bfbbd4d..c613816 100644
--- a/src/c3_fmt.c
+++ b/src/c3_fmt.c
@@ -333,9 +333,9 @@ static int valid(char *ciphertext, struct fmt_main *self)
                    "will not load such hashes.\n",
                    length, id > 0x20 ? '$' : '#', id > 0x20 ? id : '0' + id);
 
-       if (!sup_length[length])
+       if (id > 1 && !sup_length[length])
                sup_length[length] = -1;
-       if (!sup_id[id])
+       if (id > 1 && !sup_id[id])
                sup_id[id] = -1;
        return 0;
 }
```

**Comment by frank-dittrich** [comment]
May be we should just warn if someone attempts to use `--format=crypt` for descrypt hashes.
For other algorithms this can make sense, either because the algorithm is not supported otherwise, or because --format=crypt allows longer passwords to be tested.

**Comment by jfoug** [comment]
I agree with the warning. Having c3_fmt around on jumbo is rather pointless. Especially since the c3_fmt is 'not' dynamic, pulling hashes that exist on some obscure system and handling them. It will ONLY handle hashes that we have coded for. So it's usefulness is very dubious, other than in Core.

**Comment by frank-dittrich** [comment]
No, c3_fmt is not pointless.
We do restrict max. password length for performance reasons, so you can use --format=crypt even if it is much slower.
But for descrypt this is definitely pointless.

**Comment by magnumripper** [comment]
> It will ONLY handle hashes that we have coded for.

Not true. You can only *benchmark* it for formats we have prepared test vectors for but you can *use* it for any future format as long as you run it on a host that supports it.

**Comment by magnumripper** [comment]
Not sure what Solar would say (and we are not required to listen to him at all times) but we could definitely have it default as disabled in john.conf

**Comment by jfoug** [comment]
Part of the problem with disabling descrypt for C3, is that there are some OS's (psuedo OS, like cygwin), which do have 'crypt' format, but only have descrypt.  So if it is disabled, we may get into situation where we 'think' we have a crypt format, BUT it can do nothing.

**Comment by jfoug** [comment]
I believe this corrects this issue. We simply never 'fully' disable length 13 hashes, since they are in the ST code.  This may make input loading slower, for a TON of 13 byte busted hashes.  But the format will now work properly, IF there are busted ones in there.

We really should look at this disable code more closely. If we find a hash that is not workable by the crypt engine, and IF that format really is in valid input syntax, then we could disable. BUT if it is some invalid syntax, then we should be very careful about disabling all of that length.

8fb75dd

**Comment by magnumripper** [comment]
I did not test it, but the approach sounds AOK to me.

**Comment by jfoug** [comment]
All it really does is to not use the disabled flags for length 13.  I really wonder about the disabled all the way around, but I guess if crypt only looks at $1$ and figures if it can process it or not, then the disabled is probably the way to go.  It looks like 'some' crypt() put much more effort into validation of descrypt than other implementations.  So that appears to be why this bug was seen in the first place.

If you are happy, I think we can close this. Should we push the diff file up to Solar as an issue for core?

**Comment by magnumripper** [comment]
As far as I can recall, Solar hasn't ever used a single line of code I wrote :-)

**Comment by frank-dittrich** [comment]
Since my old john-users mail from January got no response, I tried with a john-dev mail:
http://openwall.com/lists/john-dev/2015/05/06/5

**Comment by rodrigojalves** [comment]
Hello there! I'm having that kind of trouble too. When I try to use john with mpiexec (with a cluster) I got a similar error.
"Generic crypt(3) module: hash encoding string lenght 98, type id $6
appears to be unsupported on this system; will not load such hashes"

When I try to run the same command, but without mpiexec (using just the master pc of the cluster) it appears to work. 


Can someone help me? Thanks?

**Comment by magnumripper** [comment]
You don't need the generic crypt format, just use the optimized formats instead. The generic one was created for situations where your system supports some format that JtR does not support natively. Right now I'm not aware of *any* such format existing.

**Comment by rodrigojalves** [comment]
Which format can I use? I'm just doing some tests with john and the cluster, trying to crack my own passwords.

The command line i'm using is this:
mpiexec -f hosts -np 12 /home/cluster/john/run/./john /home/cluster/passwords.txt -users=teste

It returned the same thing (Generic crypt(3))


If I try to run it without "mpiexec", it runs ok.
If I try another app with mpiexec, it runs ok too
If i try the "./john -test", it runs ok too....


Thanks for the help! :)

**Comment by magnumripper** [comment]
If the hashes start with `$6$´ you should use `-format:sha512crypt`.

**Comment by jfoug** [comment]
He is running non-jumbo.

**Comment by magnumripper** [comment]
Non-jumbo with MPI?

**Comment by jfoug** [comment]
Then why is it picking crypt when $6$ is the signature ?

**Comment by magnumripper** [comment]
I guess you are right. Or he's running a version of Jumbo older than my wife.

**Comment by rodrigojalves** [comment]
Thanks magnumripper... i'll try that...

I'm running jumbo, ..1.7.9

Well.. thanks for the help! 
:)

**Comment by magnumripper** [comment]
That version is ancient and this bug tracker is the wrong forum for discussing this.
