### ISSUE TITLE
./john --test=0 | grep -v PASS issue due to "Warning: No dupe-salt detection"

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#983]
```
(bleeding-jumbo)run $ ./john --test=0 | grep -v PASS
Will run 4 OpenMP threads
Testing: IKE, PSK [HMAC MD5/SHA1 32/64]... (4xOMP) Warning: No dupe-salt detection
Testing: LUKS [PBKDF2-SHA1 8x SSE2]... (4xOMP) Warning: No dupe-salt detection
Testing: PFX, PKCS12 (.pfx, .p12) [32/64]... (4xOMP) Warning: No dupe-salt detection
Testing: PKZIP [32/64]... (4xOMP) Warning: No dupe-salt detection
At Program Exit
MemDbg_Validate level 0 checking Passed
All 295 formats passed self-tests!
```
If there were errors in some of these formats, you wouldn't know which formats, since the `PASS` output is on a separtate line.

So, for --test, the `puts("Warning: No dupe-salt detection");` should be avoided.
If you want to keep the output, avoif the `\n` for --test.
BTW: shouldn't that warning go to stderr instead?

**Comment by magnumripper** [comment]
Solar has them as puts() in core John so we just did the same. We could change them to use a static fmt_puts() that only outputs a newline unless in --test

**Comment by jfoug** [comment]
I would claim that logically, these are not fully passing self test.

**Comment by frank-dittrich** [comment]
Nevertheless, --test=0 will print PASS, just in a new line. And these problems are not counted as errors.

**Comment by jfoug** [comment]
I do realize that Frank.  It was sort of a tongue  in cheek response (even thought it is sort of true).

We really should not print PASS when there are problems like this. Yes, the format may crack hashes, BUT there are problems with it. It should (at best), be a partial pass.

**Comment by frank-dittrich** [comment]
If we intend to fix those warnings prior to the next release, I have no problem keeping that PASS in a separate line for --test runs.

**Comment by jfoug** [comment]
That is on the J2 milestone (I think).

**Comment by magnumripper** [comment]
> If there were errors in some of these formats, you wouldn't know which formats, since the PASS output is on a separtate line.

Yes you would. You would grep away the single "PASS" line, not the warning line where the format is also printed.

**Comment by magnumripper** [comment]
> If we intend to fix those warnings prior to the next release, I have no problem keeping that PASS in a separate line for --test runs.

Let's leave this alone then.
