### ISSUE TITLE
For dynamic formats, use *dynamic_FIX_SALT_TO_HEX() in ldr_show_left()

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#986]
Otherwise, dynamic hashes with salts that need to be `$HEX$`-converted will be printed in a way that the loader cannot process correctly.
dynamic_FIX_SALT_TO_HEX() takes care of converting dynamic hashes where the salt contains problematic characters (':', '\n', '\r', '$') or the (salted) ciphertext ends with a ' ' or '\t' which gets truncated by the loader.

**Comment by frank-dittrich** [comment]
Couldn't dynamic's source() method do the $HEX$ conversion? The source method is called in ldr_show_left().

**Comment by jfoug** [comment]
I have no time to look now, BUT we are progressing fast into a very nuanced area, where we start making changes to work around 1 bug, and create 2 others (which we may not see until weeks later).  There are certain core parts of Dyna that I DO NOT like messing with much, unless there is a REAL problem.  split() prepare() source() valid() salt() are some of these.  Any outward behavior changes often causes some pretty serious side effect ripples.

**Comment by magnumripper** [comment]
--show=LEFT is a hack and has several problems (there are open issues iirc). We should actually try to re-code it from scratch.

**Comment by jfoug** [comment]
Should we milestone this for jumbo-2  ?   It might not be bad to try to clean up anomolies like this one. I find -show=left to be a very useful feature.  I know we have added work arounds here and there to get it 'better'. But like you mentioned, it may be nice to re-engineer it properly.

**Comment by frank-dittrich** [comment]
We should make a proper --show=LEFT issue listing all the known problems.
I think other problems with --show=LEFT have been discussed on john-dev or john-users. I'll try to find them.

**Comment by frank-dittrich** [comment]
http://thread.gmane.org/gmane.comp.security.openwall.john.devel/271/focus=272
http://thread.gmane.org/gmane.comp.security.openwall.john.user/4916
http://thread.gmane.org/gmane.comp.security.openwall.john.user/5060

Basically, it is all about --show=LEFT dropping information that might be useful to crack the remaining hashes (especially for single mode).

**Comment by magnumripper** [comment]
> Should we milestone this for jumbo-2 ?

Feel free to set or change milestones - we have absolutely no idea if/when Solar will release next time. I use to set J2 for things that ideally should be fixed immediately, and for fixes/features that would be very nice.

**Comment by jfoug** [comment]
There have been some very serious fix/enhancements recently. I hope we see a j2 this winter. It would be a good upgrade over j1 which was really needed but a little rushed.

**Comment by jfoug** [comment]
> Couldn't dynamic's source() method do the $HEX$ conversion? The source method is called in ldr_show_left().

Dyna only uses source() for non-salted types.

**Comment by jfoug** [comment]
Fixed in f6af7d7

The change should be pretty safe and transparent.  We only call the dynamic_FIX_SALT_TO_HEX() function only if the format starts with $dynamic_   NOTE, it may not be the case for thin formats (but may be the case).  If thin output $dynamic strings, then we do call it. If not, we do not.  NOTE, we could have simply called it every time, since there is a check for "$dynamic_" in the function itself.

This fix has ZERO impact on dynamic. The change is localized into the ldr_show_left() function.
