### ISSUE TITLE
RAR fails TS

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#992]
```
(master)test $ ./jtrts.pl -type rar
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [linux-gnu 64-bit AVX2-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=rar                          guesses:  130 0:00:00:51 DONE  [PASSED]
.pot CHK:rar                      guesses:  130 0:00:00:07 DONE  [PASSED]

form=rar                          guesses:  261 -show= 261 0:00:02:39 DONE : Expected count(s) (297)  [!!!FAILED!!!]
.pot CHK:rar                      guesses:  261 0:00:00:39 DONE  [PASSED]

Some tests had Errors. Performed 2 tests.  1 errors
Time used was 264 seconds
```

**Comment by magnumripper** [comment]
I wonder if these new problems are bugs with recent shared valid/split/etc - or the result of some recent change in TS. I did verify it has nothing to do with the new -random option, at least for #990.

**Comment by frank-dittrich** [comment]
At least https://github.com/magnumripper/JohnTheRipper/issues/989 had been triggered by tghe pw.dic changes introduced with commit https://github.com/magnumripper/jtrTestSuite/commit/01c00a0f7faf9e06b82d82f526f9b44738228080.
Other recent TS commits also introduced pw.dic changes (longer password candidates) that could trigger bugs

**Comment by magnumripper** [comment]
I thought we always had lines longer than 125 in the wordlist?!

**Comment by magnumripper** [comment]
1.8.0-jumbo-1 has the same problem.

**Comment by jfoug** [comment]
No, it is more candidates cause not enough to be put into the input file.  I am re-computing. I think I need to move it from 42 to 49. If so, I will set it at 60 words, for rar2

**Comment by jfoug** [comment]
Fixed in

https://github.com/magnumripper/jtrTestSuite/commit/2c338b90fc1e61877b27769227cbec504a5f8bdf
