### ISSUE TITLE
add support for kerberos TGS rep cracking

### ISSUE THREAD

**Issue by Twi1ight** [magnumripper/JohnTheRipper#995]
there is a python version: https://github.com/nidem/kerberoast
details in tgsrepcrack.py , and wish a opencl version , because cpu cracking is extremely slow
a demo file for test: https://drive.google.com/file/d/0Bz9B6P75LaTuSlJhMmFLSEtGcWs/view?usp=sharing
the password for demo file is "1qaz@WSX"

**Comment by kholia** [comment]
This is now done, thanks to Michael Kramer!
