### ISSUE TITLE
Add minimum length to format struct

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#996]
Now that J1 is released we could do some struct changes that was deferred. One is adding plaintext_min_length to the format struct. Then we can get rid of the kludges in john.c that currently exist for WPAPSK and WoW.

BFEgg may need this set to 1, see #989

**Comment by frank-dittrich** [comment]
Do we put the output of the min. length next to the max length output in llist=format-(all-)details, or do we put it close to the end, to reduce the risk of breaking some scripts users might have created?

**Comment by jfoug** [comment]
Could we 'borrow' some bits from Plaintext length, simply converting it into a union ?

**Comment by jfoug** [comment]
Once we add this, undo the hack for #989 (736c18d) along with hack logic for WoW and WPAPSK

**Comment by magnumripper** [comment]
> Could we 'borrow' some bits from Plaintext length, simply converting it into a union ?

That would mean a whole lot more changes in core code... what's the upside?

> Or do it with ```<<``` and `` >>```

I can't spot the difference?

**Comment by magnumripper** [comment]
This is done. Regression testing now.

**Comment by magnumripper** [comment]
Fixed in a916df7. Before you ask, yes I considered adding `#if FMT_MAIN_VERSION` but opted not to. We do not have branches right now that make it worthwhile.

**Comment by magnumripper** [comment]
I'm not sure. Parts of me did want to add ifdef's for this patch too.

Considering Solar's comments before J1 I doubt there will be a J2 any time soon. I will presume it might take a year or two. That's why I did not post-pone these fixes anymore.
