### ISSUE TITLE
Add salt_compare function pointer to format struct.

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#997]
This would get rid of kludges for WPAPSK and Dynamic in loader.c

**Comment by jfoug** [comment]
Would salt sorting still be done outside of the format?  just the compare requirement?

**Comment by magnumripper** [comment]
The sorting would be kept in loader.c but the salt_compare would be format local.

I think we'll have a fmt_default_sort that sorts by "most used salt first" which is marginally more clever than not sorting at all. And that's the current behaviour unless wpapsk or dynamic.

**Comment by magnumripper** [comment]
I think we need to drop your extra layer of indirection and have it as
```
@@ -234,6 +237,9 @@ struct fmt_methods {
  * used by the password file loader. */
        int (*salt_hash)(void *salt);
 
+/* Compare function used for sorting salts */
+       int (*salt_compare)(const db_salt *x, const db_salt *y);
+
 /* Sets a salt for the crypt_all() method */
        void (*set_salt)(void *salt);
 
```
The current implementation is very limiting - we'd need to keep kludges in loader.c

**Comment by magnumripper** [comment]
Scrap that, using a void pointer to salt->salt will suffice for all but the very special case "sort by count" that is of dubious value anyway.

**Comment by magnumripper** [comment]
Notes to self
```
sed -ri 's/^(\s+)([^\s]*)salt_hash,$/\1\2salt_hash,\n\1fmt_default_salt_compare,/g' *fmt*c
```

**Comment by magnumripper** [comment]
This is done. Regression testing now.
