### ISSUE TITLE
Implement "unrule"

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#998]
Brainstorming...

Say you had a utility you could run like this:
```
./unrule --rules=jumbo --input-enc:utf8 --internal-enc:cp1252 rockyou.txt > rockyou-jumbo.txt
```

Goal: Produce the smallest possible wordlist that will still cover 100% of rockyou.txt when run with --rules=jumbo

One thing that makes this project interesting is we can actually start out pretty rough (even just supporting a single rule) and best-effort and improve it over time. Even if not perfect it will never be a bad thing.

I initially thought this would be a perl script - but then we'd need to port a whole lot of code to perl for reading config files and include directives, and pre-processing rules. And possibly even support those encoding options.

**Comment by magnumripper** [comment]
Found this http://hashcat.net/forum/thread-1305.html

**Comment by jfoug** [comment]
I really think this is something that could be done in perl.  The rules themselves are not that complex, and would work wonderful in perl (just like I put the dynamic 'language' into pass_gen.pl).  It would be no where near as fast as rule processing in JtR (it would likely be a recursive decent parser), BUT speed is not what we are looking for.  

This might be a fun project to greater improve my Perl.

Now, the tr-sed 1 liner from epixiop is a wonderful pre-screening tool.  We would assume that stripping out that crap would often be a good step to find many base words. Should it always be done, hard to say.  If for instance, your rules did not have the 1337 rulez, then that is not good. Same thing for removing things like 143345password$ => password (or passwords) IF your rules do not have append of 6 numbers.

Now, if it would be better to pre-process a wordlist, or to build a 'proper' unruler to simply run rules in reverse order to find minimal valids.

I guess, what we should do, is to do some of these BY hand, talking them out.  Algorithms will fall out of talk like that.

**Comment by magnumripper** [comment]
Making it "perfect" for an exact set of rules is probably a very complex task though.

Say we start with this wordlist
```
Password
Password123
```
Say we un-rule "capitalize" and change it to
```
password
password123
```
Then we un-rule "append three digits" and drop the dupe so we end up with
```
password
```
This looks good. But the problem is that running this with those two rules will produce this:
```
Password
password123
```
So we never produce the original `Password123` because we never apply both rules at once.

**Comment by jfoug** [comment]
It has to be done 1 rule at a time (in current john compat mode).

You really need to have this:  1 starting word list, and mimimized word list for each rule.  
So here, original list is:

Password
Password123

The unrule list for append 3 digits is:
Password

The unrule list for capitialize is
password
password123

As you see, the Capitalize rule does not come into play.  We have found a smaller wordlist from just the append-3num.

**Comment by magnumripper** [comment]
So we should finally look at both lists and somehow produce either
```
password
Password
```
or
```
password
password123
```

**Comment by magnumripper** [comment]
And given 4,000,000 rules after PP, how would we write that!?

**Comment by jfoug** [comment]
by handing pp inline, and not 'creating' pseudo rules from the pre-processor.

If the rule is:

$[0-9]$[0-9]$[0-9]

we do not have to create 1000 separate rules. we simply write code that handles this.

**Comment by magnumripper** [comment]
I mean if we are to keep a list from each unrule to process later, we'll have 4M lists...

But perhaps my example is bad. Given an original wordlist of
```
password
Password
password123
Password456
```
After processing "Capitalize" we could definitely drop "Password" for good. And after processing "append3" (with no "memory" of the previous operation except our one list is shorter now) we could definitely *change* the words with numbers in the end to not have them. And *this re-inserts "Password"*. So we'd end up with
```
password
Password
```

**Comment by jfoug** [comment]
This is getting uglier and uglier.  There are some really ugly things to take into account:

s?CY
@X 
@?CY

Note, that we have no way to 'undo' that, in any 1 to 1 manner.  What we would need to do for each of these, is to attempt to find words which would satisfy the purge/replacement, BUT still satisfy as many as possible OTHER words.

Many of the rules are easy to 'undo'.  They are all 1 to 1, and done if a very specific order. Some of these purge / replacements may end up being close to show stoppers.

**Comment by magnumripper** [comment]
So s?CY is "replace all chars of class ?C with Y" and @X is "purge all X"

I see no problem. The quest is not really to *undo* anything. The quest is to remove all words from the initial wordlist that will be produced by some other word + rule.

The result from original rockyou.txt + rules will produce a whole lot of dupes. I think after processing, we'll have a much shorter rockyou2.txt, that will still produce all the original words with rules applied, and more (eg. an original word of password123 may now be password + any tree digits).

**Comment by magnumripper** [comment]
> Goal: Produce the smallest possible wordlist that will still cover 100% of rockyou.txt when run with --rules=jumbo

Maybe this is ambigous - and I'm not 100% sure what we want. It's either "original without rules is 100% covered with new list + rules" or "original + rules is a subset of new list + rules" and I think the latter is a superset of the former.

**Comment by magnumripper** [comment]
I think we need to stick with "original without rules is 100% covered with new list + rules" or this will be hairy.

**Comment by magnumripper** [comment]
> But perhaps my example is bad. Given an original wordlist of
```
password
Password
password123
Password456
```
After processing "Capitalize" we could definitely drop "Password" for good.
```
password
password123
Password456
```
And after processing "append3" (with no "memory" of the previous operation except our one list is shorter now) we could definitely *change* the words with numbers in the end to not have them.
```
password
password
Password
```
And *this re-inserts "Password"*. So after dropping dupes we'd end up with
```
password
Password
```
This is doable and it will produce all original words.

This is still not it. If we proceed to process a rule "append 'ord' to the end" we would end up like this
```
passw
Passw
```
But this will never produce "password123" or "Password456"

**Comment by jfoug** [comment]
Ok, here is an algorithm (note, typing on the fly)

```Perl
nCnt = LoadWords(@words);
@newwords = ();
do {
  nRemoved = 0;
  $best_rule  = "";
  foreach $rule (@rules) {
    nRemove = find_best($rule, @words);
    if (nRemove > nRemoved) {
      nRemoved = nRemoved;
      $best = $best_rule;
    }
  }
  if (nRemoved > 0) {
     @newwords.add(RemoveWords(@words, $best_rule, nCnt);
  }
} while (nRemoved > 1);
@newwords .= @words;  # yes, I know this is not valid statement, but you know what I mean
print "Here is our new wordlist:  There are ", scalar @newwords + scalar @words, " final words\n";
foreach $word(@newwords) {print "$word\n";}
foreach $word(@words) {print "$word\n";}
```

Ok, what find_best() does, is find the highest number of multiple words within the current word list that will be replaced by a single word, having that single word run through the rules.  So something like password password1 password2 ... password9 would return 9 for Az,[0-9], since 10 words would be replaced by the single input password.

Then the RemoveWords() would return the proper 'base' word (which is added to the @newwords array, and all of the words would be removed from the @words array.  In this case the word 'password' should probably also be removed, even though it did not satisfy the "Az,[0-9]," rule, the base word was contained within the output wordlist proper.  Also, nCnt would be reduced by 10 for this 'hit'.

In this algorithm, we look for the 'best' hit, remove that word (based upon the rule), then look for the remaining 'best' hit based upon the words that are still left.

This ALMOST CERTAILY is not an optimal algorithm, but I assure you, it is valid, AND will exit when complete. There are only so many words in the @words array.  As long as we can make that list smaller we continue. Once we  can no longer make it smaller, we exit, and print both the replacement words, and whatever was left over. That should be a complete replacement set.

**Comment by jfoug** [comment]
Ok, using the above algorithm, (very brain dead method, yes I know).   I also created a hard coded specific 'simple' rule to check.

I created code for this rule:

```
# Lowercase every pure alphanumeric word
-c >3 !?X l Q
```

A simple lower case.  I have done NO optimizations.  My code simply loads the rockyou.txt file like this:

my @words = <IN>;     That takes 45s by itself and consumes a boat load of memory.

My main loop is then this:
```Perl
my %map = ();
foreach my $word (@working_words) {
	chomp $word;
	                                       # ignore the -c
	next if (length($word) < 4);           # handle >3
	next if (contains_class($word, "X"));  # handle !?   X
	$word = lc $word;                      # handle the l
	$map{$word} += 1;
	if ($map{$word} > $bestCnt) {
		$base = $word;
		$bestCnt = $map{$word};
	}
}
$_[1] = $base;
return $bestCnt;
```

This takes right at 2 minutes to run. It returns 34 and password. If I grep -i -w password and cut 'only' pure password stuff, I get 34, so the count done by valuemap is working just fine

But it is probably WAY too slow (to satisfy usability in the original algorithm), and uses a shit load of memory.

**Comment by jfoug** [comment]
Now again, "l" is not the 'best' rule, but I wanted to start there, since it is pretty much the easiest and quickest type of rule.   But even here, 719 removals out of 14.34 million is pretty minor.

One other 'fun' thing, is that the rule rejections have to almost be done later on.  So we will probably have to un-run the rule mangling, and only then, check to see if the rejection rules are satisfied.

**Comment by magnumripper** [comment]
Could you not use (ie. remove) all of `keys(%map)` after one run, instead of just the best hit? I'm not sure I follow.

**Comment by magnumripper** [comment]
I think I meant all of `keys(%map)` that has a value larger than 1...

**Comment by magnumripper** [comment]
It took only 40s on my laptop.

Why limit to 10? I get a total of 513143 possible removals using this code (after yours)
```
my $total = 0;

foreach my $key (sort { $map{$b} <=> $map{$a} } keys %map) {
	next if $map{$key} <= 1;
	$total += $map{$key} - 1;
	printf "%d\t%s\n", $map{$key}, $key;
}

printf "\nTotal: %d\n", $total;
```
I had the `contains_class` thing commented out though.

**Comment by magnumripper** [comment]
Adding contains_class() decreased it to 493062 (and it took 57s)

**Comment by jfoug** [comment]
What we are looking for is finding 'base' words, in the proper order, that each word replaces the most original words from the wordlist based upon 'some' rule.  So to do that (in an ideal manner), we would use an algorithm like I first mentioned, which is to fine the BEST overall word (against all rules), and add that word to our 'new' set of words, removing all of the words which that rule would have found.  Then repeat the same steps.  Now, the repeat really 'could' be improved a lot. We could re-compute data for each rule, by simply removing the words.  So after the initial load, we find that adding the word 'password' removed 250000 lines, based upon rule X, then we remove all 250000 of those 'final wordlist' words, and update each of the rule sets, undoing those 250k words.  Then the next best word is rockyou.  Say some specific rule and that base-word removes 63500 original words that are still left.  We then remove those 63500 words, and recompute all the rules removing these words.


New thought.  When we 'find' a base-word, we should then run that base-word through EVERY rule, and remove all found words for that base word.    So take password.  Then simply play that word back through the wordlist, using every rule and whatever words are still left, removing each of them.

That would be a pretty big speedup.  We know probably 1000 (or 2500) GOOD base words.  We could play each of those original 'known' good base-words through each rule, and remove those items out of the original list, so that instead of loading 14.34 million words, we only load 3 or 4 million of them.  That is a pretty huge improvement.   I will look at something like that first. This really is a O(N^3) or possibly a O(N^4) problem.  Reducing the size of input greatly improves this problem.

**Comment by jfoug** [comment]
The time may be limited upon memory (also the perl). I am using cygwin, and I ASSURE you, it is slow.  I also only have 8GB on this box.  More memory would almost certainly run quite a bit faster.

**Comment by jfoug** [comment]
Side thought.  

```
../run/pass_gen.pl raw-md5 -count=15000000 < rockyou.txt > rockyou.in
```
creates a quick 'input' file.  (980mb). This took about a minute to create.

Then
```
../run/john -w=../run/password.lst -rules=jumbo rockyou.in -pot=password-lst.pot -form=raw-md5 >/dev/null
```
This took about 20s to load but only 10s to run.

```
$ ../run/john -w=../run/password.lst -rules=jumbo rockyou.in -pot=password-lst.pot -form=raw-md5 >/dev/null
Warning: poor OpenMP scalability for this hash type
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
642146g 0:00:00:03 14.30% (ETA: 16:49:30) 177437g/s 2526Kp/s 2526Kc/s 42330GC/s Forum486..Nirvana516
756521g 0:00:00:07 DONE (2015-01-08 16:49) 107490g/s 2654Kp/s 2654Kc/s 36736GC/s RAstAFAriaN..WINNIETHEPOOH
Use the "--show" option to display all of the cracked passwords reliably
Session completed
At Program Exit
MemDbg_Validate level 0 checking Passed
```

It only found 756521 hashes however (5%).  I was expecting MUCH more than this to be removed.

**Comment by magnumripper** [comment]
Cracking 750K/5% of a real password database using a 3546 line wordlist is a feat. Also, the real database had lots and lots of dupe passwords so it would be a LOT more than that.

**Comment by jfoug** [comment]
Ok, I am not 100% sure things are working properly, but it 'could' be due to other words being in password.lst file.

This data was generated from -rules:jumbo using password.lst
```
$ grep -i password password-lst.pot  | wc
   1277    1277   71004
```

This was a complete new run, using 'just' the line "password" in a input file:

```
$ echo -n password | ../run/john -pipe -rules=jumbo rockyou.in -pot=password.pot -form=raw-md5 >/dev/null
1115g 0:00:00:00 DONE (2015-01-08 16:56) 12528g/s 65235p/s 65235c/s 83279MC/s password..PASSWORD
```

**Comment by jfoug** [comment]
Yes, I know, the data that I am using is greatly reduced, since the duplication has been removed. This is rockyou 'unique' words.  But I did expect a higher success with the -rules:jumbo AND a high quality wordlist.

**Comment by magnumripper** [comment]
Try -rules:all and see how much better it gets...

**Comment by frank-dittrich** [comment]
And "unrule" password.lst first!

**Comment by jfoug** [comment]
Here is a 'new' better baseword sorted list:

run  	epixoip baseword 1-liner:

cat rockyou.dic | tr A-Z a-z | sed 's/^[^a-z]*//g; s/[^a-z]*$//g; y/112345677890@\$\!\#/ilzeasbzvbgoasih/; s/[^a-z]//g; /^$/d' >basewords

sort it by count:

LC_ALL='C' sort < basewords | LC_ALL='C' uniq -c -d | sort -n -r > basewords.cnt

 head -7830 basewords.cnt | awk '{print $2;}' > bestbase.lst

7830 was all lines with 100 or more 'base' words.

Now I will run with THIS file, and see how things go (both jumbo, and then all rules), and follow up.

**Comment by jfoug** [comment]
```
$ ../run/john -rules:jumbo -w=bestbase.lst rockyou.in -form=raw-md5 -pot=ru-jumbo-rules-bestbase.pot >/dev/null
1170310g 0:00:00:12 11.23% (ETA: 18:32:17) 93251g/s 1185Kp/s 1185Kc/s 16835GC/s far831..raptor835
1477174g 0:00:00:29 DONE (2015-01-08 18:31) 49699g/s 1382Kp/s 1382Kc/s 18735GC/s PiNkPANTheR..CHEEKYMONKEY
```

So here, we have 10% processed with -rules:jumbo and the top 7800 'base' words.  This shows that the 3500 words in 'password.lst' is very strong, since it was general words, and not specifically FROM the RU list.  These 7800, were specially built data right from the RU data.

**Comment by magnumripper** [comment]
Here's rockyou *with* original dupes
```
$ ../run/pass_gen.pl dummy -count=99000000 < /Users/magnum/john/dict/rockyou.original.dlst > rockyou.dupes.dummy

$ rm -f test.pot && ../run/john -w=../run/password.lst -rules=jumbo rockyou.dupes.dummy -pot=test.pot -form=dummy -verb=1
dummy password length 101 > currently supported length 95
dummy password length 126 > max. supported lengh 125
Loaded 14343707 password hashes with no different salts (dummy [N/A])
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
756521g 0:00:00:14 DONE (2015-01-09 00:15) 52030g/s 1285Kp/s 1285Kc/s 18365GC/s WINNIethEpOOH..WINNIETHEPOOH
Session completed

$ ../run/john rockyou.dupes.dummy -pot=test.pot -form=dummy -show | tail -1
dummy password length 101 > currently supported length 95
dummy password length 126 > max. supported lengh 125
9417519 password hashes cracked, 23185176 left
```
That's over 40% of the passwords using a 3500 line wordlist. Pure awsomeness!

And using -rules=all
```
$ rm -f test2.pot && ../run/john -w=../run/password.lst -rules=all rockyou.dupes.dummy -pot=test2.pot -form=dummy -verb=1
dummy password length 101 > currently supported length 95
dummy password length 126 > max. supported lengh 125
Loaded 14343707 password hashes with no different salts (dummy [N/A])
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
1362862g 0:01:08:43 DONE (2015-01-09 01:27) 330.5g/s 5883Kp/s 5883Kc/s 77075GC/s informix999999..sss999999
Session completed
```
This took it past 50%. Solar's wordlist is amazing. Add -loopback for even more cracks without actually adding any new data (I can't test this, it will take a month using -rules=all but it cracked yet another 3.5 million passwords (counting dupes, it was 1 million unique ones) in three minutes which took the total crack rate over 66%. This is almost unbelievably good.

**Comment by magnumripper** [comment]
(I miscalculated the percentages above, edited now)

**Comment by magnumripper** [comment]
> Add -loopback for even more cracks without actually adding any new data (I can't test this, it will take a month using -rules=all but it cracked yet another 3.5 million passwords (counting dupes, it was 1 million unique ones)

For -rules=jumbo it's much faster though. Starting with the 28% cracked with -w -rules=jumbo from above and running loopback:
```
$ ../run/john -loop -rules=jumbo rockyou.dupes.dummy -pot=test.pot -form=dummy -verb=1
dummy password length 101 > currently supported length 95
dummy password length 126 > max. supported lengh 125
Loaded 14343707 password hashes with no different salts (dummy [N/A])
Remaining 13587186 password hashes with no different salts
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
2444417g 0:00:26:58 DONE (2015-01-09 02:32) 1510g/s 2298Kp/s 2298Kc/s 26707GC/s WINNIETHEPOOHZ..winniethepooh19
Session completed

$ ../run/john rockyou.dupes.dummy -pot=test.pot -form=dummy -show | tail -1
dummy password length 101 > currently supported length 95
dummy password length 126 > max. supported lengh 125
16344475 password hashes cracked, 16258220 left
```
...we got over 50% of the passwords in no time.

**Comment by magnumripper** [comment]
I added a perl script that does it the "epixoip way" plus removes dupes and outputs sorted by count. It's a very good start.
