### ISSUE TITLE
Add CRAM-MD5 format

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#999]
For some reason @kholia never released the cram-md5 format but sent it to unused and in decb2b3aa it was dropped even from there.

**Comment by kholia** [comment]
http://www.openwall.com/lists/john-users/2010/07/27/1 is relevant. 

I am still not sure why I didn't commit the format to the tree. Do we really need it?

**Comment by magnumripper** [comment]
Ah, I remember that post now. So it's just plain HMAC MD5. So maybe we should just copy some of that text to a doc/CRAM-MD5 file.
